### ISSUE TITLE
clusterimpl: Switch Child LB to Graceful Switch

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc-java#10006]
Me Eric and Michael (who was guided by Mark) came to the conclusion that the Child LB of the cluster impl should be a Graceful Switch Balancer. This is needed to correctly support the scenario where the Child Type changes, and is currently a correctness issue.

Eric also mentioned writing a cross language interop test for this case.

**Comment by ejona86** [comment]
It seems the code only uses the child policy type the first time it is called. I the child type changes, this could easily cause a ClassCastException and cause the channel to panic.

https://github.com/grpc/grpc-java/blob/bbe5a0227dd54fe97c59f8674a6e486e513fc38e/xds/src/main/java/io/grpc/xds/ClusterImplLoadBalancer.java#L117-L136
