### ISSUE TITLE
federation test is flaky

### ISSUE THREAD

**Issue by YifeiZhuang** [grpc/grpc-java#10015]
https://source.cloud.google.com/results/invocations/c4cc2099-dfd7-4628-baf8-527912e9068b/targets/github%2Fgrpc-java%2Fxds%2Fbuild%2Ftest-results%2Ftest%2FTEST-io.grpc.xds.XdsClientFederationTest/tests

```
expected not to be: null
	at io.grpc.xds.XdsClientFederationTest.lrsClientsStartedForLocalityStats(XdsClientFederationTest.java:147)
```

**Comment by ejona86** [comment]
This has been seen again at f6ddd63, which was after the fix.
https://source.cloud.google.com/results/invocations/95aa226c-3d5f-475b-8551-9ddf3501491f

**Comment by ejona86** [comment]
Actually, it even failed at 1e028c4, which was the fix.
https://source.cloud.google.com/results/invocations/ab572794-df0c-4d91-be5a-e10877886870

So of two runs, it failed both times, but only on Mac OS. May be a race.
