### ISSUE TITLE
[Backport Request to 1.47.x] https://github.com/grpc/grpc-java/pull/9846

### ISSUE THREAD

**Issue by imnotanoob** [grpc/grpc-java#10017]
- Request to backport this PR (https://github.com/grpc/grpc-java/pull/9846) to 1.47.x
- We heavily use this library, and upgrading it currently would be a huge undertaking for us.
- This would be super helpful and seems to be pretty simple since there is a backport to 1.45.x?

**Comment by ejona86** [comment]
Backporting is easy. The time consuming part is doing a release. It was backported to 1.51 and 1.52, but we didn't do a release for those. That would be an easier sell. How did #9563 only recently become an issue for you?

**Comment by ejona86** [comment]
Looking around, I see some other folks using 1.50. If we released the fix on 1.50.x, would that help?

**Comment by imnotanoob** [comment]
1.50.x would be amazing @ejona86 :D

**Comment by ejona86** [comment]
Backport in #10019

**Comment by ejona86** [comment]
1.50.3 is now released. It shows up on Maven Central's repo1, so is available for use now (or maybe after another hour to let mirrors propagate). It generally takes a day to be indexed by search.maven.org, but that doesn't impact whether you can use it.

Release notes have not yet been published.
