### ISSUE TITLE
Remove old experimental xds flags

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#10054]
These flags seem to have been default-enabled for quite a while:
 * GRPC_XDS_EXPERIMENTAL_FAULT_INJECTION
 * GRPC_XDS_EXPERIMENTAL_ENABLE_RETRY
 * GRPC_XDS_EXPERIMENTAL_RBAC
 * GRPC_EXPERIMENTAL_XDS_CUSTOM_LB_CONFIG
 * GRPC_EXPERIMENTAL_ENABLE_OUTLIER_DETECTION

We should remove them and the `false` codepaths.

**Comment by YifeiZhuang** [comment]
where are these from?

**Comment by ejona86** [comment]
They've just slowly accumulated from completed gRFCs. You were involved with the RBAC one. Terry was for the CUSTOM_LB and OUTLIER_DETECTION. RETRY was Penn, and FAULT_INJECTION was Penn/Chengyuan.

**Comment by YifeiZhuang** [comment]
Removing the `GRPC_XDS_EXPERIMENTAL_FAULT_INJECTION ` environmental variable changes the behaviour. Currently if `GRPC_XDS_EXPERIMENTAL_FAULT_INJECTION ` is not to false, it allows httpfilter config in httpConnectionManager to be empty. After removing it, it NACKs if empty.  It seems align with [A39](https://github.com/grpc/proposal/blob/master/A39-xds-http-filters.md), but it changes the behaviour...

**Comment by ejona86** [comment]
Removing GRPC_XDS_EXPERIMENTAL_FAULT_INJECTION does not change the current behavior, because it is already defaulting to true:
https://github.com/grpc/grpc-java/blob/8d12baa4477d177bb4d27c07ee58b139b247820a/xds/src/main/java/io/grpc/xds/XdsResourceType.java#L50

Yes, someone could change the behavior by setting it, but they haven't told us of any trouble and at this point if there was an issue we'd say, "fix the control plane." We have no need to support disabling that feature at this point.

The risky point is not removing the variable. The risky point was changing the default from false to true. Since that was successful, removing the variable should be a non-event.
