### ISSUE TITLE
Linker failed while linking protoc-gen-grpc-java

### ISSUE THREAD

**Issue by guysung** [grpc/grpc-java#10063]
I am trying to set up the environment and followed the `COMPILING.md` with the following contents in the gradle.properties file.
```
skipAndroid=true
skipCodegen=false
```
But I had the following link errors, what could I possibly miss here? Any help would be appreciated.
```
./gradlew build
  * Skipping the build of Android projects because skipAndroid=true

> Configure project :grpc-compiler
*** Building codegen requires Protobuf version 3.21.7
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin

> Task :grpc-compiler:linkJava_pluginExecutable FAILED
ld: warning: ignoring file /usr/local/lib/libprotoc.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /usr/local/lib/libprotobuf.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:

....

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-compiler:linkJava_pluginExecutable'.
> A build operation failed.
      Linker failed while linking protoc-gen-grpc-java.
  See the complete log at: file:///Users/gkim/GenDev/grpc-java/compiler/build/tmp/linkJava_pluginExecutable/output.txt
   > Linker failed while linking protoc-gen-grpc-java.
```
FYI, I followed the "How to build code gen plugin" and it's successful.  I am using M1 Macbook.

Any help or suggestion would be appreciated. Thx

**Comment by ejona86** [comment]
This is somewhat related to https://github.com/grpc/grpc-java/issues/7690 . Looks like you built protobuf for arm but grpc for amd64.

**Comment by guysung** [comment]
Yeah, I followed the "How to build code gen plugin" so I successfully compiled protobuf in my M1 mac, and tried to build grpc-java.
How to build protobuf for arm64 so that it matches the grpc-java? Would you elaborate more?

**Comment by ejona86** [comment]
Why are you building from source? Are you trying to get native ARM binaries instead of the x86_64 ones that we provide? If so, this issue would be essentially the same as  #7690.

**Comment by guysung** [comment]
I tried the suggestion in #7690 but it didn't work out, that's why.
The following are the code snippets I changed in the build.gradle in the root of the grpc-java repo.
```
           project.protobuf {
                protoc {
//                    if (project.hasProperty('protoc')) {
//                        path = project.protoc
//                    }
//                    else {
//                        artifact = libs.protobuf.protoc.get()
//                    }
                    // for apple m1, please add protoc_platform=osx-x86_64 in $HOME/.gradle/gradle.properties
                    if (project.hasProperty('protoc_platform')) {
                        artifact = "com.google.protobuf:protoc:3.21.7:${protoc_platform}"
                    } else {
                        artifact = "com.google.protobuf:protoc:3.21.7"
                    }
                }
  ```
My goal is simple as I followed the instructions and wanted to clone the **grpc-java** into my M1 Mac and build the projects successfully to play around, and learn about it. FYI, not only I couldn't build the **grpc-java** projects, but also I couldn't build the examples project which gave different errors. Any feedback and guidelines would be appreciated.

**Comment by ejona86** [comment]
For getting started, don't try to build gRPC itself. Just start with the examples.

What errors do you get for the examples? Make sure to check out a release tag and not master.

**Comment by guysung** [comment]
Following your tips, all works fine. The errors for the examples probably came after messing up with attempts to build gRPC. I wonder if there is any related document that I missed. Thanks much.
