### ISSUE TITLE
Under High load, request are getting queued up.

### ISSUE THREAD

**Issue by RITESHMOHAPATRA** [grpc/grpc-java#10088]
How can i resolve my latency issue as my grpc request is taking time from grpc queue  to service invocation in a spring boot application?

**Comment by YifeiZhuang** [comment]
Sorry to see the high latency and need to investigate.
Is it a cold start or not? what is the memory usage? are there tls involved? I was wondering if there are something else other than the queueing that caused the latency. Probably need more investigation to find the bottleneck.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
