### ISSUE TITLE
why grpc-core maven-metadata.xml file dose not contains version 1.28.0

### ISSUE THREAD

**Issue by z7658329** [grpc/grpc-java#10086]
i have execute "mvn clean install" in my project ,but build error:
[ERROR] Failed to execute goal on project hugegraph-rpc: Could not resolve dependencies for project org.apache.hugegraph:hugegraph-rpc:jar:1.0.0: Failed to collect dependencies at com.alipay.sofa:sofa-rpc-all:jar:5.7.6 -> io.grpc:grpc-netty-shaded:jar:1.28.0 -> io.grpc:grpc-core:jar:[1.28.0]: No versions available for io.grpc:grpc-core:jar:[1.28.0] within specified range -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project hugegraph-rpc: Could not resolve dependencies for project org.apache.hugegraph:hugegraph-rpc:jar:1.0.0: Failed to collect dependencies at com.alipay.sofa:sofa-rpc-all:jar:5.7.6 -> io.grpc:grpc-netty-shaded:jar:1.28.0 -> io.grpc:grpc-core:jar:[1.28.0]
   
so i have check the error log, i find the grpc-core [maven-metadata.xml](https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml) file 
dose not contains version 1.28.0? is it ok?  
<img width="677" alt="image" src="https://user-images.githubusercontent.com/5474723/233282790-250963dc-94f8-4135-9e2a-8b88109b9eb8.png">

**Comment by ejona86** [comment]
I don't know, and we aren't in control of that file. The best that could happen is to file an issue at issues.sonatype.org about an issue with OSSRH. That said, the version does exist: https://repo.maven.apache.org/maven2/io/grpc/grpc-core/1.28.0/ .

That version is three years old, so I don't see much point in fixing the issue. I suggest hugegraph upgrade their dependencies. It could have used sofa-rpc-all 5.9.x before its release, and it uses 1.33.1. That's still 2.5 years old, so a bug against sofa-rpc would be good too. The oldest defendable version is 1.41, if you need to support Java 7, but sofa-rpc requires Java 8.

But you already saw you can upgrade these versions yourself. I don't know why you excluded the transitive version when doing an upgrade; that's asking for a brittle dependency tree and I don't see you using dependencyConvergence which is the only time I see that practice. Simply adding the direct dependency on the newer version should have been enough. I suggest using Maven Enforcer's requireUpperBoundDeps to make sure that Maven doesn't downgrade dependencies.

**Comment by ejona86** [comment]
It is showing up now. Sonatype was busted. I'm going to hope it was related to #10043, but whatever. Everything is working now.
