### ISSUE TITLE
java.util.NoSuchElementException: SecurityProtocolNegotiators$ClientSdsHandler#0 in xDS gRPC Java Client 

### ISSUE THREAD

**Issue by oc007us** [grpc/grpc-java#10119]
### What version of gRPC-Java are you using?

1.53.0

### What is your environment?

MacOS

### What did you expect to see?

No exceptions

### What did you see instead?

20:08:52.838 [grpc-nio-worker-ELG-1-7] WARN io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.util.NoSuchElementException: SecurityProtocolNegotiators$ClientSdsHandler#0

### Steps to reproduce the bug

Provided for troubleshooting

**Comment by ejona86** [comment]
This is being fixed by #10118.

**Comment by sanjaypujare** [comment]
I had the comment https://github.com/grpc/grpc-java/pull/10118#issuecomment-1533149522 in #10118 which got merged but this issue didn't get closed?

**Comment by ejona86** [comment]
Yeah, it needs to be in the description or the commit message.
