### ISSUE TITLE
C++ Server Response Content Type null

### ISSUE THREAD

**Issue by adnaan** [grpc/grpc-java#1012]
Unary call for a blocking stub fails on Android at:

https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/Http2ClientStream.java#L97

with:

09-12 02:45:02.561 2330-2347/? E/JOBS: error while executing job
09-12 02:45:02.561 2330-2347/? E/JOBS: io.grpc.StatusRuntimeException: INTERNAL: Invalid content-type: null

Works fine after commenting out the check.

Skimming through the c++ server code shows content-type is not being set on the response?

Not sure where is the right place to raise this.

**Comment by yang-g** [comment]
https://github.com/grpc/grpc/pull/3288 is fixing it.
