### ISSUE TITLE
GRPC performance is slower than REST

### ISSUE THREAD

**Issue by skumar1987** [grpc/grpc-java#10126]
I have deployed the grpc service which will encrypt the text, but response time is slower than REST service.
below is my GRPC proto file:

```proto
message CipherApiInput {

  string key=1 [(validate.rules).string.min_len = 1];
  string cipherProvider=2 [(validate.rules).string = {in: ['CloudHSM','IngrianProvider']}];
  repeated PairData pairData=3 [(validate.rules).repeated.min_items = 1];;
}

message CipherApiOutput {
repeated CloudHSMOutput cloudHSMOutput=1;

}

message CloudHSMOutput {
 string id=1;
 string value=2;
 string errorMessage=3;
}

message PairData
{
  string id=1 [(validate.rules).string.min_len = 1];
  string value=2 [(validate.rules).string.min_len = 1];
}
```

Server Configuration:
```java
  GrpcServerConfigurer grpcServerConfigurer() {
		
	      return builder -> {
	          ((NettyServerBuilder) builder)
	                .workerEventLoopGroup(new EpollEventLoopGroup())
	                .bossEventLoopGroup(new EpollEventLoopGroup())
	                  .channelType(EpollServerSocketChannel.class)
	                  .intercept( new ValidationInterceptor())
	                  .executor(Executors.newFixedThreadPool(200));
	      };
	  }
```

```
REST Performance                                                                                  GRPC Performance       
1 response  response time : 55 msec                                                     1 response  response time : 155 msec 
Load test : 10k request 100 req at a time - throughput 404                  Load test : 10k request 100 req at a time - throughput  164
```

I am testing from Postman and Jmeter from local machine and micorservice is deployed in kubernetes aws cluster.
Kindly let me know which can improve it's performance.

using open Jdk 1.8

**Comment by ejona86** [comment]
Those numbers are very slow. How many Channels/clients are being used for the gRPC benchmark? How large is the request and response? How much time was spent warming up the server?

Remove the event loop group (and thus also the channelType) configuration, or decrease the number of threads there. More threads is not better. Using the default is probably for the best here.

Does your service do blocking (e.g., waiting for an RPC, waiting for another thread) when processing? If not and it is just CPU, then using a fixed thread pool closer to the number of cores your machine has will probably reduce thrashing and increase throughput. The `executor()` is good to tune based on your workload, because your service runs on those threads.

For reference, [our benchmarks](https://grpc.io/docs/guides/benchmarking/) have (they broke recently, look at the last 30 days to see data) a small unary RPC taking less than 150 µs using TLS between two VMs (this is only one at a time). Unary TLS throughput QPS (multiple simultaneous) is at ~170K QPS. Both of those have a service that does nothing.

**Comment by skumar1987** [comment]
Hi Eric,

Thanks for replying,
 Request and response is small only and testing is done after warming up the server only, with single client and single request also I am not getting good performance and for load test I used 100 concurrent client in jmeter.
After using default configuration as below response time increased to 200 ms
((NettyServerBuilder) builder.intercept( new ValidationInterceptor());

Below is req : 
{
    "cipherProvider": "CloudHS",
    "key": "test",
    "pairData": [
        {
            "id": "1",
            "value": "shobhit"
        }
    ]
}

**Comment by ejona86** [comment]
> with single client and single request

That is a very minimal warmup. The JIT will not have kicked in, but at least class loading will have happened. Run a benchmarks until you get 20-30 seconds worth of requests. Then run the benchmark again to get a more accurate results.

I do think you want to specify `executor()`. That is the one performance configuration we tend to suggest.

**Comment by skumar1987** [comment]
I have run load test after 1 mins number is improved (throughput ~216 ) but again it's not matching with Rest ( throughput ~409)
Tested with 100 concurrent client and 10k request
Added below configuration:
 ((NettyServerBuilder) builder)
  .intercept( new ValidationInterceptor())
 .executor(Executors.newFixedThreadPool(100));

**Comment by ejona86** [comment]
My earlier recommendation hasn't changed:

> Does your service do blocking (e.g., waiting for an RPC, waiting for another thread) when processing? If not and it is just CPU, then using a fixed thread pool closer to the number of cores your machine has will probably reduce thrashing and increase throughput.

**Comment by skumar1987** [comment]
Yes it's blocking, getting a request and sending a response.
I am testing from local machine and service is deployed on cloud and I am testing from postman and jmeter.
Now I am trying to test with java client and I see each request taking 46 msec now while with postman it's 150 msec.

**Comment by ejona86** [comment]
That's surprising to me, but at least the mystery is at least partly solved. If you are going over the internet, a substantial part of the ~50 ms is just network latency. You should notice the concurrency level (100) has a lot of impact. 150 ms makes me think postman accidentally has two additional roundtrips being introduced. I wonder if it may be creating a new connection for each RPC. A tcpdump/wireguard session would probably make that clear. (Turn down the concurrency to 1 though if you looking into it; it'll reduce the amount of data you need to look through.)

**Comment by ejona86** [comment]
Seems like this is resolved/workedaround/understood enough to see it isn't this gRPC implementation. It is probably worth following up with postman so they are aware something is awry. But I don't see much more we can do here. If that's not the case, comment, and it can be reopened.
