### ISSUE TITLE
http2 Host"NameResolver

### ISSUE THREAD

**Issue by wenmingwei** [grpc/grpc-java#10171]
```java
ManagedChannelBuilder builder = ManagedChannelBuilder.forTarget("istio.test.cn")
                            .nameResolverFactory(new GrpcNameResolverProvider(this))
                            .usePlaintext();
```

I used nameResolverFactory to do load balancing and routing.

When I access grpc service deployed in istio, and route by "Host", envoy cannot get correct Host in http2 header.

My question is: How to set http2 "Host" attribute while using nameResolverFactory

PS: I tried to access grpc service in istio without nameResolverFactory, it works well.

**Comment by wenmingwei** [comment]
```java
ManagedChannelBuilder builder = ManagedChannelBuilder.forTarget("istio.test.cn")
                            .nameResolverFactory(new GrpcNameResolverProvider(this))
                            .usePlaintext();
```

I used nameResolverFactory to do load balancing and routing.

When I access grpc service deployed in istio, and route by "Host", envoy cannot get correct Host in http2 header.

My question is: How to set http2 "Host" attribute while using nameResolverFactory

PS: I tried to access grpc service in istio without nameResolverFactory, it works well.

**Comment by ejona86** [comment]
Note that 1.22 is very old and unsupported and `nameResolverFactory` is deprecated. To set the host, use [`overrideAuthority()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#overrideAuthority-java.lang.String-).

**Comment by wenmingwei** [comment]
Thank you very much, your suggestion resolved my question.
