### ISSUE TITLE
Enabling retries for a gRPC service defined in proto

### ISSUE THREAD

**Issue by MonssifEchadli** [grpc/grpc-java#10170]
Should we use PROTO_FILENAME.SERVICE_NAME or PROTOFILE_PACKAGE_NAME.SERVICE_NAME in the json to enable Retry

**Comment by ejona86** [comment]
The proto file name is not used. The name is the fully-qualified service name, which is `the.package.name.TheServiceName`

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
