### ISSUE TITLE
Implement static stride in weighted round robin

### ISSUE THREAD

**Issue by YifeiZhuang** [grpc/grpc-java#10180]
Currently java uses a priority queue to implement the `EDF` algorithm in WRR in the scheduler. It requires holding the lock to update weights and pick a subchannel. An optimization is to use the static stride algorithm. The static stride maps the weight sets in to float numbers and return an index for the next pick result. It does not require a lock so potentially reduces pick latency due to lock contention. It also aligns with other languages implementation, e.g. C++ uses the static stride.

A global sequence number may be used among picker instances to give move accurate results.

[go/static-stride-scheduler](https://goto.google.com/static-stride-scheduler)

cc. @ejona86

**Comment by endurance21** [comment]
hey @YifeiZhuang !
This seems interesting, can I pick it up?

**Comment by YifeiZhuang** [comment]
@endurance21 Thank you, this already had an owner though!
