### ISSUE TITLE
How to create custom health check in grpc

### ISSUE THREAD

**Issue by skumar1987** [grpc/grpc-java#10204]
how can I write my own health check implementation for grpc in java.

**Comment by sanjaypujare** [comment]
Take a look at https://github.com/grpc/grpc/blob/master/doc/health-checking.md and see if that's what you want. There is an example in Java for this at https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/healthservice explained briefly in https://github.com/grpc/grpc-java/blob/master/examples/README.md#basic-examples

**Comment by skumar1987** [comment]
Thanks for your help.
 I am able to call custom healthcheck by adding service in grpc server
 return builder -> {
	          ((NettyServerBuilder) builder)
	              .addService(new GrpcActuatorHealthService())
	                  .executor(Executors.newFixedThreadPool(maxServerThreads));
	      };
