### ISSUE TITLE
C++ doesn't send content-type

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1021]
Although C++ should be sending a content-type, it currently isn't. We'll need to figure out our interop story for Java.

```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Invalid content-type: null

Metadata({grpc-status=[0]})
    at io.grpc.Status.asRuntimeException(Status.java:428)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:156)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:106)
```

**Comment by ejona86** [comment]
So for beta we are going to disable the content-type check in Java. Java master will continue checking content-type. C is going to fixed their master and release a beta patch.

**Comment by ejona86** [comment]
grpc/grpc#3288 should fix the issue on C-side.

**Comment by truebid** [comment]
Go server stack have same problem

**Comment by iamqizhao** [comment]
not sure how you got this impression

https://github.com/grpc/grpc-go/blob/262b78b833bc8c14d344466cd1e3ec18a30e16cb/transport/http2_server.go#L448

On Mon, Sep 28, 2015 at 10:55 PM, Daniel Petersson <notifications@github.com
