### ISSUE TITLE
connection refused after server start success for many seconds

### ISSUE THREAD

**Issue by wqliang** [grpc/grpc-java#10212]
I have a gRPC server and a gRPC client, and I run the server and client, the gRPC invoke was ok. 
Then I shutdown the server, the client throw the exception "connection refused". 
And then I start the server again,  after server start finish, the client still throw "connection refused". I see a range about 1~15 second from server start finished to client reconnect success.
Besides, I see a TCP retransmission  for SYN package between client and server.  And in server side, I create a Socket to server itself imediately after server start() finish, and the socket was create success imediately and no any delay.

Any idea of the above problem? What's the cause of it? How to solve it?

**Comment by ejona86** [comment]
Disabling it to mean you want it to spin in a tight loop trying to connect? No, that is not available.

**Comment by wqliang** [comment]
> Disabling it to mean you want it to spin in a tight loop trying to connect? No, that is not available.

@ejona86 I'd like to make upper bound of backoff a smaller value. 
Thank you for your prompt, I find the docs https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md

**Comment by ejona86** [comment]
If you had control, what value would you like for the max backoff?

**Comment by z0mb1ek** [comment]
@ejona86 Hi, i had the same trouble, i have 3 microservices and 1 client in kubernetes. While microservices updating client turns off them from availability list and finally i see: 
```
io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: streams/10.111.10.124:7000
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
```
and my high availability fails. After error dns updates and all start working, earlier i didn't see this error, what can I do in such case?

**Comment by temawi** [comment]
I'm closing this as I believe the question was answered.
