### ISSUE TITLE
Debugging newFutureStub asynchronous calls

### ISSUE THREAD

**Issue by hakusai22** [grpc/grpc-java#10210]
Hello, I used newFutureStub for asynchronous calls and encountered a large number of requests being lost. Asynchronous tasks cannot see logs and are difficult to troubleshoot. Have you encountered the same scenario?

**Comment by ejona86** [comment]
When you say "lost" do you mean the RPCs failed or the RPCs hung or the Futures themselves were lost?

**Comment by hakusai22** [comment]
> When you say "lost" do you mean the RPCs failed or the RPCs hung or the Futures themselves were lost?

Invoking RPC asynchronous tasks multiple times in a thread, only 2 out of 100 were successful, and the rest did not even have log information

**Comment by ejona86** [comment]
> the rest did not even have log information

You haven't presented what logging you are doing, so this doesn't really tell me anything. Right now, the problem could be as simple as "you aren't listening for future failure." Another option is "the RPCs are still running" (so maybe the server leaked the RPCs).
