### ISSUE TITLE
Bazel Support is missing documentation on README and website

### ISSUE THREAD

**Issue by vorburger** [grpc/grpc-java#10215]
### What version of gRPC-Java are you using?

`master`

### What is your environment?

Linux Java 11

### What did you expect to see?

Looking at https://github.com/grpc/grpc-java/blob/master/README.md and/or https://grpc.io I was hoping to see documentation which describes (copy/pasta!) how to use `grpc-java` in a project which uses Bazel as its build system (just like it does for Maven and Gradle), which I would like to do for https://github.com/enola-dev/enola/issues/202.

### What did you see instead?

No documentation for Bazel.

I did find https://grpc.io/blog/bazel-rules-protobuf/ from 6.5 years ago, and was pointed to [this example](https://github.com/grpc/grpc-java/blob/master/examples/BUILD.bazel), and will try to use that (and sources) as inspiration.

I will see if I can contribute to this project with a docs PR once I have successfully learnt how to do this for https://github.com/enola-dev/enola/issues/202.

I suggest to document the current as-is state, that is, without e.g. possible future #9559 (yet, update for that later).

My personal interest and focus for a contribution is non-Android, so I won't look at #4465.

/Cc @lowasser @ejona86

**Comment by vorburger** [comment]
This documentation should ideally clarify how using `java_proto_library` and `java_grpc_library` relates to the `proto_library` from https://github.com/bazelbuild/rules_proto and https://bazel.build/reference/be/protocol-buffer... for the naive uniiniated it's not super clear.

**Comment by vorburger** [comment]
What #10217 does not address is how exactly to use `http_archive` to `load("@io_grpc_grpc_java// ...)"`

In my https://github.com/enola-dev/enola/issues/202 it only works because I'm still partially using https://rules-proto-grpc.com.

**Comment by ejona86** [comment]
Bazel users are vastly outnumbered by Maven/Gradle users, so yeah, the docs aren't optimized for it. Configuring the WORKSPACE is also some effort, so the best docs right now are indeed "look at the example."

But it is true that Bazel users may not be aware of the conventions for making proto_library/java_proto_library/java_grpc_library, so it would be appropriate to show that pattern somewhere other than a big BUILD file.

**Comment by larry-safran** [comment]
Several of the examples have BUILD.bazel files such as
https://github.com/grpc/grpc-java/blob/master/examples/example-alts/BUILD.bazel
  and
https://github.com/grpc/grpc-java/blob/master/examples/example-hostname/BUILD.bazel
