### ISSUE TITLE
How is exception propagated to client side from server side and how to handle the exceptions on client side

### ISSUE THREAD

**Issue by sfc-gh-bdeng** [grpc/grpc-java#10227]
Moved the conversation from #1913 

Have two questions regarding exception handling in grpc Java

1) If StatusException and StatusRuntimeException are not serializable, then when I wrote something like @ericmandm did above
responseObserver.onError(new StatusRuntimeException(Status.INTERNAL.withCause(t)));

How is the exception propagated back to the client? In order for the client to get notified there is an exception (and got the corresponding description etc), it has to be serialized on the server side first, right? Does the library does some conversion automatically? I would appreciate it if I can get some pointer to the code

2) For blocking unary call, is it true that grpc always wrap the exception into StatusRuntimeException? If so, is it enough to try and catch StatusRuntimeException if I want to catch all Exceptions?
```
try {
   client.blockingUnaryCallForSomeAPI(...)
   } catch (StatusRuntimeException e) { //  any reason I probably should use Exception here instead?
}
```
Thanks!

**Comment by ejona86** [comment]
Answer from https://github.com/grpc/grpc-java/issues/1913#issuecomment-1568617625 :
> The short answer is this issue is about Java serialization. gRPC [doesn't use](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) Java serialization for Status. gRPC doesn't transmit the stack trace nor causal chain, the status code is encoded in `grpc-status` header, and the description is in the `grpc-message` header. The exception is just a Java-ism adaptation of the gRPC protocol.

For the second question, yes, it is a StatusRuntimeException. The method doesn't throw checked exceptions, so it can't be StatusException. [The hello-world example](https://github.com/grpc/grpc-java/blob/4277867a7dcfd73706f347f11f6e0476c1d2d032/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java#L50-L55) just catches StatusRuntimeException, like you have here, for error handling.

**Comment by sfc-gh-bdeng** [comment]
@ejona86 Thank you! That answers my question!
