### ISSUE TITLE
Add java.time.Duration overloads to CallOptions, AbstractStub, Deadline, and other APIs

### ISSUE THREAD

**Issue by kluever** [grpc/grpc-java#10245]
### Is your feature request related to a problem?
`long, TimeUnit` APIs encourage plumbing a pair of variables through various layers, or require plumbing a single ambiguous numeric primitive (e.g., `long deadlineInSeconds`). The modern alternative is to use a `java.time.Duration`.

### Describe the solution you'd like
Every API that requests a `long, TimeUnit` should have a `java.time.Duration` overload as well

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by kluever** [comment]
Also leaving a breadcrumb that Eric mentioned to me: those methods will probably need the `org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement` annotation on them.

**Comment by kluever** [comment]
SGTM --- this is very similar to what we do in Guava APIs that historically accept a `long, TimeUnit` tuple. E.g., https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/Futures.java#L222-L259

You'll likely want to decompose to nanoseconds, but be aware of the potential for overflow (which happens at +/- 292 years). We've been using a helper function to decompose a `Duration` safely:
https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/Internal.java#L27-L42

**Comment by ejona86** [comment]
`TimeUnit.NANOSECONDS.convert(duration)` looks better than `Duration.toNano()` for us, as it saturates and we aren't trying to avoid TimeUnit.

APIs that would be quick:
CallOptions
Deadline
AbstractStub

Then there's a longer tail:
ManagedChannelBuilder (and transport-specific friends)
ServerBuilder
... certainly there are others

Dunno about these and blocking methods in general. The only occurrence in java.util.concerrent is TimeUnit. I don't see _a single_ blocking method have Duration in Java, so I think we'll leave the awaitTermination and blocking as old-style:
(don't change these)
ManagedChannel
Server

**Comment by kluever** [comment]
Thanks! My understanding is that the JDK folks have been a bit apprehensive about adding `Duration`-based overloads to `java.util.concurrent` APIs, since most of those APIs are very low-level concurrency building blocks (and allocation _could_ matter in some cases). However, for user-facing APIs such as gRPC, `Duration` is almost certainly going to be better for your users.

**Comment by shubhamraj-samsung** [comment]
Hi I am new to open source and would like to contribute to this issue

**Comment by ejona86** [comment]
Huh. I was able to assign you. I thought folks had to be in the grpc org for that to work.

**Comment by shubhamraj-samsung** [comment]
Hi @ejona86 
I have implemented `java.time.Duration` overload function for `CallOptions` as follows. Please check if this is what you are expecting

`  /**
   * Returns a new {@code CallOptions} with a deadline that is after the given {@code duration} from
   * now.
   */
  public CallOptions withDeadlineAfter(Duration duration) {
    return withDeadline(Deadline.after(toNanosSaturated(delay), TimeUnit.NANOSECONDS));
  }


  /**
   * Returns a new {@code CallOptions} with a deadline that is after the given {@code duration} from
   * now.
   */
  public CallOptions withDeadlineAfter(long duration, TimeUnit unit) {
    return withDeadline(Deadline.after(duration, unit));
  }`

**Comment by shubhamraj-samsung** [comment]
Hi
I have implemented `java.time.Duration` overload function for `CallOptions` as follows. Please check if this is what you are expecting

``` /**
   * Returns a new {@code CallOptions} with a deadline that is after the given {@code duration} from
   * now.
   */
  public CallOptions withDeadlineAfter(Duration duration) {
    return withDeadline(Deadline.after(toNanosSaturated(delay), TimeUnit.NANOSECONDS));
  }


  /**
   * Returns a new {@code CallOptions} with a deadline that is after the given {@code duration} from
   * now.
   */
  public CallOptions withDeadlineAfter(long duration, TimeUnit unit) {
    return withDeadline(Deadline.after(duration, unit));
  }```

**Comment by shubhamraj-samsung** [comment]
Hi
I have implemented `java.time.Duration` overload function for `CallOptions` as follows. Please check if this is what you are expecting

``` /**
   * Returns a new {@code CallOptions} with a deadline that is after the given {@code duration} from
   * now.
   */
  public CallOptions withDeadlineAfter(Duration duration) {
    return withDeadline(Deadline.after(toNanosSaturated(delay), TimeUnit.NANOSECONDS));
  }


  /**
   * Returns a new {@code CallOptions} with a deadline that is after the given {@code duration} from
   * now.
   */
  public CallOptions withDeadlineAfter(long duration, TimeUnit unit) {
    return withDeadline(Deadline.after(duration, unit));
  }
  ```

**Comment by shubhamraj-samsung** [comment]
Hi
I have implemented `java.time.Duration` overload function for `CallOptions` as follows. Please check if this is what you are expecting
```
   /**
   * Returns a new {@code CallOptions} with a deadline that is after the given {@code duration} from
   * now.
   */
    // This is my overloaded function
  public CallOptions withDeadlineAfter(Duration duration) {
    return withDeadline(Deadline.after(toNanosSaturated(delay), TimeUnit.NANOSECONDS));
  }


  /**
   * Returns a new {@code CallOptions} with a deadline that is after the given {@code duration} from
   * now.
   */
  public CallOptions withDeadlineAfter(long duration, TimeUnit unit) {
    return withDeadline(Deadline.after(duration, unit));
  }
  ```

**Comment by shubhamraj-samsung** [comment]
My question is where should I create the java file for method `toNanosSaturated(delay)` since other files for which I should write overloads are in different folders.

**Comment by kluever** [comment]
In Guava, we just made a package-private `Internal.java` class in each package where we wanted to use it: https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/Internal.java#L27-L42

I'm not sure if gRPC can use Java 11+ APIs, but if so, you could do what @ejona86 suggested above: [`TimeUnit.convert(Duration)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/TimeUnit.html#convert(java.time.Duration))

**Comment by ejona86** [comment]
Doh, `TimeUnit.convert(Duration)` is Java 11. No, we can't use it. Yeah, just use a package-private class. I don't think we'd have a good class already to put it in; you can name it `JavaTimeUtil` or whatever.

**Comment by kluever** [comment]
In `scheduleWithFixedDelay(...)`, both delays use the same `TimeUnit` (which is a bit of a weird API, but that's how it works).

So I'd add an overload and have it's impl just delegate to the safe nano decomposition helper:

```java
public final ScheduledHandle scheduleWithFixedDelay(Runnable task, Duration initialDelay, Duration delay, ScheduledExecutorService timerService) {
  return scheduleWithFixedDelay(
      task,
      toNanosSaturated(initialDelay),
      toNanosSaturated(delay),
      TimeUnit.NANOSECONDS,
      timerService);
}
```

**Comment by ankit-kumar-dwivedi** [comment]
Hi @shubhamraj-samsung it's been a while since your last comment and I also don't see any related PR/draft. 
Are you still working on this one? 
If not @ejona86 can I pick this one?
Thanks!

**Comment by kannanjgithub** [comment]
> `TimeUnit.NANOSECONDS.convert(duration)` looks better than `Duration.toNano()` for us, as it saturates and we aren't trying to avoid TimeUnit.

@ejona86 TimeUnit.NANOSECONDS.convert takes a long and a TimeUnit as arguments and returns the value in nanoseconds. java.time.Duration has getSeconds() so we could call TimeUnit.NANOSECONDS.convert(duration.getSeconds(), TimeUnit.SECONDS). But the nano portion from Duration will be lost. 
Instead if we used duration.toNanos() directly there will be no loss of precision except in the case of overflow but the overflow is not peculiar to this approach but can occur in TimeUnit.NANOSECONDS.convert also.

**Comment by kluever** [comment]
Two slight corrections to the above comment:

- `duration.toNanos()` throws an exception if the duration is greater than 2^63 -1 nanoseconds
- `TimeUnit` conversion APIs won't overflow either, they silently saturate to `Long.MAX_VALUE`

**Comment by kannanjgithub** [comment]
About the 2nd point, yes, by overflow I meant the overflow and its handling in the exception block that we call saturation.

**Comment by ejona86** [comment]
We used to use `-source` and `-target`, which would let us use newer APIs (carefully). That's no longer the case with `-release`. Let's just not update Deadline for now.

**Comment by kannanjgithub** [comment]
@ejona86 can you also look at the concern I raised above about using the TimeUnit.NANOSECONDS.convert(long, TimeUnit) approach?

**Comment by SreeramdasLavanya** [comment]
> We used to use `-source` and `-target`, which would let us use newer APIs (carefully). That's no longer the case with `-release`. Let's just not update Deadline for now.

Reverting changes for DeadLine and raising the PR for the same.

**Comment by ejona86** [comment]
@kannanjgithub wrote:
> TimeUnit.NANOSECONDS.convert takes a long and a TimeUnit as arguments and returns the value in nanoseconds.

No, I was talking about [the one that accepts a Duration directly](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/TimeUnit.html#convert(java.time.Duration)). But then [it was pointed out](https://github.com/grpc/grpc-java/issues/10245#issuecomment-1591208782) that method is Java 11+. So that meant we needed a helper to wrap `duration.toNanos()`.

**Comment by SreeramdasLavanya** [comment]
@ejona86 

I've done the necessary changes and raised PR, kindly confirm.

https://github.com/grpc/grpc-java/pull/11562
