### ISSUE TITLE
Add setScheduledExecutorService() to NettyChannelBuilder

### ISSUE THREAD

**Issue by danfaer** [grpc/grpc-java#10246]
### Is your feature request related to a problem?
The `NettyTransportFactory.getScheduledExecutorService()` method returns the `EventLoopGroup` used for scheduling timeout tasks and other operations. However, the current implementation of `EventLoopGroup.schedule()` calls `EventLoopGroup.next()`, which moves the index of the current event loop to the next position. This behavior leads to unpredictable event loop selection for `NettyClientTransport`, potentially causing multiple Netty channels to share the same event loop, even if the number of event loops in the group is greater than the number of channels.

### Describe the solution you'd like
I propose adding a setter for the `ScheduledExecutorService` in the `NettyChannelBuilder`. If a user-defined `ScheduledExecutorService` is set, it will be returned by `NettyTransportFactory.getScheduledExecutorService()` and used for scheduling tasks. As a result, the call to `EventLoopGroup.next()` will exclusively occur from `NettyClientTransport.start()`.

### Describe alternatives you've considered
An alternative solution would be to use a Composite EventLoopGroup that handles `EventLoopGroup.schedule()` differently. However, implementing this solution is not straightforward due to the `EpollEventLoopGroup` being a `final class`.

**Comment by sanjaypujare** [comment]
Background discussion https://groups.google.com/g/grpc-io/c/xR82L6dNhfk/m/8ry1e9pLAwAJ

**Comment by sanjaypujare** [comment]
@danfaer are you interested in contributing a PR for this?

**Comment by ejona86** [comment]
> potentially causing multiple Netty channels to share the same event loop

Is that a problem? We generally expect and assume this will happen.

> even if the number of event loops in the group is greater than the number of channels

This is possible a limited amount of connection churn as well.

> The deadline task may end up in the same slow EventLoop, which subsequently requires its cancellation.

Overall, I'm not seeing something we'd call a problem. But I do expect there was a problem and it just wasn't fully shared. This quote from the mailing list may be a hint though. Did you experience a latency issue on one connection because it was shared with another? Can you share how severe the issue was?

**Comment by danfaer** [comment]
here is the original problem - https://stackoverflow.com/questions/76106267/grpc-java-call-takes-much-longer-than-deadline

**Comment by danfaer** [comment]
I made a local patch using 'NettyChannelBuilder.scheduledExecutorService' and set up an experiment to compare the time taken for each timing out request , with the stub created using scheduledExecutorService and the one without it (which will preserve the current behavior of using EventLoopGroup for timeout task scheduling).

Here is the snippet of my code:

```
private static ManagedChannel buildChannel(String host, int port, boolean scheduledService) {

    ThreadFactory threadFactory = new ThreadFactoryBuilder().setNameFormat("io-event-loop-%s").setDaemon(true).build();
    EventLoopGroup eventLoopGroup = new KQueueEventLoopGroup(1, threadFactory);

    NettyChannelBuilder builder = NettyChannelBuilder
            .forAddress(host, port)
            .eventLoopGroup(eventLoopGroup)
            .channelType(NettyCommonUtils.socketChannel(eventLoopGroup))
            .defaultLoadBalancingPolicy("round_robin")
            .executor(GrpcUtils.createExecutor("grpc-client-executor-", 50))
            .usePlaintext();
    if (scheduledService) {
        builder.scheduledExecutorService(Executors.newSingleThreadScheduledExecutor());
    }

    return builder.build();
}

void runExperiments() {
    HostAndPort hostAndPort = HostAndPort.fromParts("127.0.0.1", 5658);
    
    createAndStartGrpServer(new InetSocketAddress(hostAndPort.getHost(), hostAndPort.getPort()));

    final MyTestServiceGrpc.MyTestServiceBlockingStub stub = MyTestServiceGrpc.newBlockingStub(
            buildChannel(hostAndPort.getHost(), hostAndPort.getPort(), false));

    final MyTestServiceGrpc.MyTestServiceBlockingStub stubWithScheduledExecutor = MyTestServiceGrpc.newBlockingStub(
            buildChannel(hostAndPort.getHost(), hostAndPort.getPort(), true));

    // Warm-up calls
    MyTestProto.Request warmUpRequest = MyTestProto.Request.newBuilder().setValue(1).build();
    for(int i = 0; i < 5; i++) {
        stub.myTest(warmUpRequest);
        stubWithScheduledExecutor.myTest(warmUpRequest);
    }

    // The request asks the service to sleep for 100 ms before responding
    MyTestProto.Request request = MyTestProto.Request.newBuilder().setValue(100).build();
    int numTasks = 50;
    ExecutorService executorService = Executors.newFixedThreadPool(numTasks, new ThreadFactoryBuilder().setNameFormat("main-grpc-request-%d").build());

    for(MyTestServiceGrpc.MyTestServiceBlockingStub currentStub : List.of(stub, stubWithScheduledExecutor)) {
        AtomicLong totalTimePerExperiments = new AtomicLong();
        for (int i = 0; i < 5; i++) {
            CountDownLatch startLatch = new CountDownLatch(1);
            CountDownLatch finishLatch = new CountDownLatch(numTasks);

            AtomicLong maxTime = new AtomicLong();
            AtomicLong minTime = new AtomicLong(Integer.MAX_VALUE);
            AtomicLong totalTime = new AtomicLong();

            for (int j = 0; j < numTasks; j++) {
                CompletableFuture.supplyAsync(() -> {
                    try {
                        try {
                            startLatch.await();
                        } catch (InterruptedException e) {
                            throw new RuntimeException(e);
                        }
                        StopWatch stopWatch = StopWatch.createStarted();

                        try {
                            currentStub.withDeadlineAfter(50, TimeUnit.MILLISECONDS).myTest(request);
                        } catch (StatusRuntimeException e) {

                        }

                        final long time = stopWatch.getTime();
                        maxTime.set(Math.max(maxTime.get(), time));
                        minTime.set(Math.min(minTime.get(), time));
                        totalTime.addAndGet(time);

                    } catch (Exception e) {
                       

 log.error(e, e);
                    } finally {
                        finishLatch.countDown();
                    }
                    return null;
                }, executorService);
            }

            startLatch.countDown();
            finishLatch.await();

            totalTimePerExperiments.addAndGet(totalTime.get());
            log.info("withScheduledService={}, testNum={}, maxTime={}, minTime={}, totalTime={}", currentStub == stubWithScheduledExecutor, i, maxTime, minTime, totalTime);
            Thread.sleep(100);
        }
        log.info("withScheduledService={}, totalTimePerExperiments={}", currentStub == stubWithScheduledExecutor, totalTimePerExperiments);
        Thread.sleep(1000);
    }
}
```

The output is : 

withScheduledService=false, testNum=0, maxTime=163, minTime=109, totalTime=6638
withScheduledService=false, testNum=1, maxTime=118, minTime=60, totalTime=3639
withScheduledService=false, testNum=2, maxTime=185, minTime=112, totalTime=7988
withScheduledService=false, testNum=3, maxTime=196, minTime=162, totalTime=8957
withScheduledService=false, testNum=4, maxTime=126, minTime=91, totalTime=4843
withScheduledService=false, totalTimePerExperiment=32065


withScheduledService=true, testNum=0, maxTime=111, minTime=78, totalTime=4930
withScheduledService=true, testNum=1, maxTime=67, minTime=61, totalTime=3275
withScheduledService=true, testNum=2, maxTime=85, minTime=74, totalTime=4024
withScheduledService=true, testNum=3, maxTime=69, minTime=65, totalTime=3420
withScheduledService=true, testNum=4, maxTime=71, minTime=65, totalTime=3400
withScheduledService=true, totalTimePerExperiment=19049

**Comment by ejona86** [comment]
Two seconds is really long. If the network threads are seeing 2s of latency, lots of things will be bad. We would want to look into that and address that, independent of deadlines.

I have seen a synthetic test that could maybe do that by starting a _ton_ of RPCs on a single connection, but it is hard to reproduce without running out of memory. I'd normally expect that to be caused by someone "blocking on the network thread." That'd be some user that did blocking in a NameResolver or StreamTracer, or tried to eek out more performance by using `managedChannel.directExecutor()`. But the only way to fix those is to find the offending code and fix it.

If this is actually a general problem and not "someone doing something wrong," it'd probably be better to change our default, because it would be far too deep for users to diagnose why they are getting weird latencies. We'd swap to our shared scheduledExecutorService (and provide the override in the builder). But we'd want something more to be confident this is the problem.

If the problem is just `next()` mutating the counter, it might not be horrible to use `iterator()` to make a copy of the executor list and keep our own counter. That'd keep things mostly the same as they are now. It does assume that the group won't change size.

I saw you posted a reproduction, but then removed it. The timing difference you saw was just the JVM warming up. If you alternate more times between "today" and "using scheduledExecutorService" the latency difference disappears (for that specific attempt to reproduce).

**Comment by danfaer** [comment]
Eric, you are correct that the time difference in my reproducer is mainly
due to JVM warmup. I removed my comment because I switched the order and
observed the opposite result. However, in any case, I was able to
consistently reproduce delays, although I can't prove that an external
scheduled executor is better.

The reproducer setup is as follows:
- One shared channel with a connection to one local server.
- The client's EventLoopGroup with 20 threads.
- 100 threads start sending requests at the same time with a DeadlineAfter
of 200 ms.
- The server takes 500 ms to respond.
- Time is measured outside the call.

The minimum time observed was 250 ms, and the maximum time was 400 ms.

**Comment by ejona86** [comment]
When I ran that reproducer (with 50 tasks, and 1 eventloop in the group) it didn't show any serious latency. My service implementation threw away the request, so it was guaranteed to timeout without me needing to schedule anything on server-side or have more threads.

I wouldn't expect a burst-send-with-later-timeout to show much issue. The creation of the RPCs is bursty, but the timeout is scheduled on the calling thread and when the timeout fires the system is close to idle. The timeout causes a small RST_STREAM and a callback to the application, which couldn't contribute ms.

A simple noop RPC takes ~200 µs, so doing half of it serially would only be 20 ms. I would have expected a larger RPC (metadata or message size) to be necessary to trigger this.

It's possible something is wrong with Netty's KQueue channel. I am testing on my i7-8650U Linux laptop with epoll. It might be worth checking if Nio behaves the same way on Mac.

Alternating the tests back-and-forth:
```
withScheduledService=false, testNum=0, maxTime=61, minTime=52, totalTime=2,771
withScheduledService=false, testNum=1, maxTime=56, minTime=50, totalTime=2,706
withScheduledService=false, testNum=2, maxTime=51, minTime=50, totalTime=2,505
withScheduledService=false, testNum=3, maxTime=72, minTime=51, totalTime=3,176
withScheduledService=false, testNum=4, maxTime=124, minTime=67, totalTime=3,731
withScheduledService=false, totalTimePerExperiments=14,889
withScheduledService=true, testNum=0, maxTime=51, minTime=50, totalTime=2,503
withScheduledService=true, testNum=1, maxTime=58, minTime=51, totalTime=2,751
withScheduledService=true, testNum=2, maxTime=56, minTime=51, totalTime=2,705
withScheduledService=true, testNum=3, maxTime=57, minTime=51, totalTime=2,736
withScheduledService=true, testNum=4, maxTime=53, minTime=51, totalTime=2,588
withScheduledService=true, totalTimePerExperiments=13,283
withScheduledService=false, testNum=0, maxTime=51, minTime=50, totalTime=2,510
withScheduledService=false, testNum=1, maxTime=53, minTime=50, totalTime=2,601
withScheduledService=false, testNum=2, maxTime=51, minTime=50, totalTime=2,502
withScheduledService=false, testNum=3, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=false, testNum=4, maxTime=58, minTime=50, totalTime=2,737
withScheduledService=false, totalTimePerExperiments=12,850
withScheduledService=true, testNum=0, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=true, testNum=1, maxTime=56, minTime=50, totalTime=2,637
withScheduledService=true, testNum=2, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=true, testNum=3, maxTime=54, minTime=51, totalTime=2,618
withScheduledService=true, testNum=4, maxTime=52, minTime=50, totalTime=2,546
withScheduledService=true, totalTimePerExperiments=12,801
withScheduledService=false, testNum=0, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=false, testNum=1, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=false, testNum=2, maxTime=51, minTime=50, totalTime=2,504
withScheduledService=false, testNum=3, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=false, testNum=4, maxTime=52, minTime=50, totalTime=2,567
withScheduledService=false, totalTimePerExperiments=12,571
withScheduledService=true, testNum=0, maxTime=51, minTime=50, totalTime=2,513
withScheduledService=true, testNum=1, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=true, testNum=2, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=true, testNum=3, maxTime=51, minTime=50, totalTime=2,501
withScheduledService=true, testNum=4, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=true, totalTimePerExperiments=12,514
withScheduledService=false, testNum=0, maxTime=52, minTime=50, totalTime=2,566
withScheduledService=false, testNum=1, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=false, testNum=2, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=false, testNum=3, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=false, testNum=4, maxTime=50, minTime=50, totalTime=2,500
withScheduledService=false, totalTimePerExperiments=12,566
```

**Comment by danfaer** [comment]
Replicating your experiment with back and forth 8 times, service throwing away request.
posting here 4 last results: 

KQueue

```
withScheduledService=false, testNum=0, maxTime=69, minTime=64, totalTime=3371
withScheduledService=false, testNum=1, maxTime=60, minTime=54, totalTime=2990
withScheduledService=false, testNum=2, maxTime=57, minTime=54, totalTime=2797
withScheduledService=false, testNum=3, maxTime=59, minTime=57, totalTime=2916
withScheduledService=false, testNum=4, maxTime=55, minTime=55, totalTime=2750
withScheduledService=false, totalTimePerExperiment=14824
withScheduledService=true, testNum=0, maxTime=58, minTime=55, totalTime=2863
withScheduledService=true, testNum=1, maxTime=56, minTime=55, totalTime=2752
withScheduledService=true, testNum=2, maxTime=56, minTime=56, totalTime=2800
withScheduledService=true, testNum=3, maxTime=72, minTime=62, totalTime=3534
withScheduledService=true, testNum=4, maxTime=59, minTime=56, totalTime=2917
withScheduledService=true, totalTimePerExperiment=14866
withScheduledService=false, testNum=0, maxTime=86, minTime=72, totalTime=3986
withScheduledService=false, testNum=1, maxTime=61, minTime=57, totalTime=2965
withScheduledService=false, testNum=2, maxTime=53, minTime=50, totalTime=2521
withScheduledService=false, testNum=3, maxTime=53, minTime=50, totalTime=2584
withScheduledService=false, testNum=4, maxTime=57, minTime=55, totalTime=2810
withScheduledService=false, totalTimePerExperiment=14866
withScheduledService=true, testNum=0, maxTime=63, minTime=61, totalTime=3114
withScheduledService=true, testNum=1, maxTime=62, minTime=58, totalTime=3092
withScheduledService=true, testNum=2, maxTime=78, minTime=66, totalTime=3555
withScheduledService=true, testNum=3, maxTime=105, minTime=85, totalTime=4616
withScheduledService=true, testNum=4, maxTime=62, minTime=55, totalTime=2928
withScheduledService=true, totalTimePerExperiment=17305
```


Nio

```
withScheduledService=false, testNum=0, maxTime=60, minTime=58, totalTime=2976
withScheduledService=false, testNum=1, maxTime=57, minTime=56, totalTime=2814
withScheduledService=false, testNum=2, maxTime=58, minTime=57, totalTime=2899
withScheduledService=false, testNum=3, maxTime=57, minTime=56, totalTime=2811
withScheduledService=false, testNum=4, maxTime=58, minTime=55, totalTime=2895
withScheduledService=false, totalTimePerExperiment=14395
withScheduledService=true, testNum=0, maxTime=57, minTime=52, totalTime=2741
withScheduledService=true, testNum=1, maxTime=71, minTime=60, totalTime=3473
withScheduledService=true, testNum=2, maxTime=58, minTime=56, totalTime=2857
withScheduledService=true, testNum=3, maxTime=63, minTime=57, totalTime=2986
withScheduledService=true, testNum=4, maxTime=60, minTime=53, totalTime=2811
withScheduledService=true, totalTimePerExperiment=14868
withScheduledService=false, testNum=0, maxTime=58, minTime=54, totalTime=2735
withScheduledService=false, testNum=1, maxTime=61, minTime=57, totalTime=3045
withScheduledService=false, testNum=2, maxTime=57, minTime=53, totalTime=2814
withScheduledService=false, testNum=3, maxTime=53, minTime=52, totalTime=2649
withScheduledService=false, testNum=4, maxTime=55, minTime=54, totalTime=2738
withScheduledService=false, totalTimePerExperiment=13981
withScheduledService=true, testNum=0, maxTime=64, minTime=54, totalTime=2957
withScheduledService=true, testNum=1, maxTime=60, minTime=52, totalTime=2707
withScheduledService=true, testNum=2, maxTime=79, minTime=66, totalTime=3462
withScheduledService=true, testNum=3, maxTime=122, minTime=104, totalTime=5733
withScheduledService=true, testNum=4, maxTime=66, minTime=50, totalTime=2694
withScheduledService=true, totalTimePerExperiment=17553
```

**Comment by ejona86** [comment]
Those are really weak results... I even ran while doing a video chat where chrome was using 150% CPU (of 4 cores total) and didn't see much difference to what I posted before. You aren't running on battery during the test, right?

I've dumped the code at:
https://github.com/ejona86/grpc-java-10246

@sanjaypujare, would you mind running the code in that repository on your M1 and see if you also see poor deadline latency? You'll need to check out https://github.com/grpc/grpc-java/pull/10250 (`git fetch https://github.com/danfaer/grpc-java.git ncb-scheduled-executor; git checkout FETCH_HEAD`).

**Comment by sanjaypujare** [comment]
>...
> @sanjaypujare, would you mind running the code in that repository on your M1 and see if you also see poor deadline latency? You'll need to check out #10250 (`git fetch https://github.com/danfaer/grpc-java.git ncb-scheduled-executor; git checkout FETCH_HEAD`).

Sure, will try and let you know

**Comment by sanjaypujare** [comment]
So I ran it. Had to make a small change in `build.gradle`:

```
-        grpc { artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}" }
+        grpc { artifact = "io.grpc:protoc-gen-grpc-java:1.55.1" }
```

Because I cannot build the plugin on the Mac. I don't think this should affect the numbers.

So here's the output:

```
Using class io.netty.channel.kqueue.KQueueSocketChannel
Using class io.netty.channel.kqueue.KQueueSocketChannel
withScheduledService=false, testNum=0, maxTime=56, minTime=53, totalTime=5,474
withScheduledService=false, testNum=1, maxTime=54, minTime=51, totalTime=5,302
withScheduledService=false, testNum=2, maxTime=54, minTime=51, totalTime=5,296
withScheduledService=false, testNum=3, maxTime=57, minTime=51, totalTime=5,452
withScheduledService=false, testNum=4, maxTime=53, minTime=51, totalTime=5,166
withScheduledService=false, totalTimePerExperiments=26,690
withScheduledService=true, testNum=0, maxTime=55, minTime=51, totalTime=5,255
withScheduledService=true, testNum=1, maxTime=55, minTime=55, totalTime=5,500
withScheduledService=true, testNum=2, maxTime=55, minTime=53, totalTime=5,343
withScheduledService=true, testNum=3, maxTime=55, minTime=54, totalTime=5,427
withScheduledService=true, testNum=4, maxTime=52, minTime=50, totalTime=5,068
withScheduledService=true, totalTimePerExperiments=26,593
withScheduledService=false, testNum=0, maxTime=54, minTime=50, totalTime=5,007
withScheduledService=false, testNum=1, maxTime=52, minTime=50, totalTime=5,101
withScheduledService=false, testNum=2, maxTime=51, minTime=51, totalTime=5,100
withScheduledService=false, testNum=3, maxTime=51, minTime=50, totalTime=5,098
withScheduledService=false, testNum=4, maxTime=51, minTime=50, totalTime=5,021
withScheduledService=false, totalTimePerExperiments=25,327
withScheduledService=true, testNum=0, maxTime=55, minTime=52, totalTime=5,315
withScheduledService=true, testNum=1, maxTime=54, minTime=50, totalTime=5,101
withScheduledService=true, testNum=2, maxTime=55, minTime=54, totalTime=5,430
withScheduledService=true, testNum=3, maxTime=53, minTime=52, totalTime=5,286
withScheduledService=true, testNum=4, maxTime=54, minTime=53, totalTime=5,376
withScheduledService=true, totalTimePerExperiments=26,508
withScheduledService=false, testNum=0, maxTime=51, minTime=50, totalTime=5,002
withScheduledService=false, testNum=1, maxTime=51, minTime=50, totalTime=5,087
withScheduledService=false, testNum=2, maxTime=51, minTime=50, totalTime=5,012
withScheduledService=false, testNum=3, maxTime=51, minTime=50, totalTime=5,039
withScheduledService=false, testNum=4, maxTime=51, minTime=50, totalTime=5,023
withScheduledService=false, totalTimePerExperiments=25,163
withScheduledService=true, testNum=0, maxTime=55, minTime=52, totalTime=5,246
withScheduledService=true, testNum=1, maxTime=54, minTime=53, totalTime=5,380
withScheduledService=true, testNum=2, maxTime=53, minTime=52, totalTime=5,218
withScheduledService=true, testNum=3, maxTime=53, minTime=53, totalTime=5,300
withScheduledService=true, testNum=4, maxTime=53, minTime=53, totalTime=5,300
withScheduledService=true, totalTimePerExperiments=26,444
withScheduledService=false, testNum=0, maxTime=51, minTime=50, totalTime=5,002
withScheduledService=false, testNum=1, maxTime=51, minTime=51, totalTime=5,100
withScheduledService=false, testNum=2, maxTime=51, minTime=51, totalTime=5,100
withScheduledService=false, testNum=3, maxTime=51, minTime=50, totalTime=5,058
withScheduledService=false, testNum=4, maxTime=51, minTime=50, totalTime=5,016
withScheduledService=false, totalTimePerExperiments=25,276
```

**Comment by ejona86** [comment]
@sanjaypujare, your results are much better than @danfaer. I am really suspicious that this may just be an OS scheduling issue or configuration, with Apple trying to save power/heat or some such. But Sanjay's results do show the separate service helped. If we went down this road more, I'd probably have Sanjay re-run the test but using NIO instead of KQueue; NIO uses KQueue but there may be something special about how they wake up a sleeping loop.

But even as it stands, Sanjay's numbers aren't _that_ different between separate executor and not. And probably well within acceptability for a laptop. We need to keep in mind the benchmark may not demonstrate the full extent of the problem, but there doesn't seem to be much reason to be worried here.

@danfaer, where does that leave us with you? You are definitely seeing really poor results. It seems unlikely to be a M1 vs M1 Pro problem (although I don't really know what precise hardware Sanjay has). It could easily be a heat problem, like [the left vs right charging port](https://www.forbes.com/sites/barrycollins/2020/04/24/why-you-shouldnt-charge-your-macbook-pro-from-the-left-hand-side/?sh=4ce423da78ff) which surprised people years ago. I think the "kernel_task" there was just forcing the CPU to sleep to reduce heat; that type of heat reduction throttling would have significant impact to latency.

Overall, "how much does this matter?" How much will this impact you now that we have a bit of a better idea it isn't a general problem? Are you running production workloads on Mac? Or are you just doing testing on your local machine? If this is a work project, you might see if your coworkers see similar behavior.

**Comment by danfaer** [comment]
Poor results on my local machine do not matter much; it's good to know that it's not a general problem. The next step for me would be to check the performance on our production Linux boxes after my changes with the scheduled executor service are deployed.

**Comment by danfaer** [comment]
@ejona86 My changes, which involved using a separate scheduled executor implemented using a dynamic proxy, were deployed to production last week. Unfortunately, I have not observed any improvement in the high request times. Despite setting a deadline of 200ms, it reaches 1000ms.

**Comment by ejona86** [comment]
@danfaer, you may find [perfmark](https://github.com/perfmark/perfmark/) to be useful. It can do cross-thread tracing to help track down where latency is introduced. gRPC is instrumented it for it.

One thing I'd suggest checking, is if you are using a fixed-sized thread pool as the channel/server `executor()`, make sure you aren't doing excessive blocking within callbacks. Or if you are doing blocking, realize that gRPC may not be able to _notify the application_ that a RPC has been cancelled until a thread from that pool becomes available.

**Comment by danfaer** [comment]
@ejona86 
We have a metric for event loop queue length, which is periodically updated. The event loop group is shared among all gRPC clients running on a given JVM. With the standard event loop group, some queues may contain up to 45 tasks. However, with the dynamic proxy event loop group, which redirects 'schedule' requests to a separate event loop group with two loops, the maximum queue has decreased to 2 tasks. The same queue length is shown for the event loop group used for scheduling.

I have not been able to observe the effects of shorter queues on call latencies, but it is possible that they have been overshadowed by other factors. This change shows promising improvements for our system, and I would greatly appreciate it if you could approve my PR.

**Comment by danfaer** [comment]
https://github.com/ejona86/grpc-java-10246/pull/1

**Comment by danfaer** [comment]
@ejona86 Can you please check ?

**Comment by danfaer** [comment]
@ejona86 As we discussed in person today, my workaround using Dynamic Proxy for `EventLoopGroup` intercepts `schedule()` calls and redirects them to an additional `EventLoopGroup`, dedicated for scheduling.

This approach works for calls from `io.grpc.internal.Rescheduler`, but does not work for calls from `io.grpc.internal.KeepAliveManager` because the latter uses the `EventLoop` returned from the `group.next()` call.

**Comment by danfaer** [comment]
> The difference in pending tasks max counts is 2x
  Never mind. It depends on the order of tests executions. The test does not show any advantage of having scheduled tasks separated.

**Comment by ejona86** [comment]
@danfaer, oh, so you disproved the benefit? So you are still suffering from the latency problem but no longer trust the test, or no longer trust the fix?

Since you were seeing high latency, if the problem isn't timer scheduling, one possibility is you are suffering from unfairness. You may try decreasing the WriteQueue's DEQUE_CHUNK_SIZE (but that's hard without a reproduction; want us to make this a system property?):

https://github.com/grpc/grpc-java/blob/cfecc4754b603e950f6f65ee1a2deb697c3f9a61/netty/src/main/java/io/grpc/netty/WriteQueue.java#L39C20-L39C36

The current number was pretty arbitrary. If your clients are _sending_ heavily, that could contribute. Note that that will do nothing for the queue length. But decreasing the value would increase the fairness across connections.

Other shots in the dark: maybe MaxMessagesRecvByteBufAllocator could be reduced to increase fairness.

**Comment by danfaer** [comment]
@ejona86 I do see the benefit in decreased queue length but not in latency. The test does not consistently show a decrease in either queue length nor latency. The latency problem "solved itself", probably because of some changes on the server.
Thanks for the pointers, i will look at it
