### ISSUE TITLE
binder: Will it support transporting `Binder objects`. i.e: ParcelFileDescriptor

### ISSUE THREAD

**Issue by CCint3** [grpc/grpc-java#10253]
grpc-binder can currently use Metadata to transfer simple Parcelable objects.

But when a Parcelable object contains Binder objects, it will not be able to do so.

For example: When transferring a ParcelFileDescriptor object, an exception will occur.

```log
SerializingExecutor: java.lang.IllegalStateException: java.lang.RuntimeException: Tried to marshall a Parcel that contained Binder objects.
SerializingExecutor:  at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:617)
SerializingExecutor:  at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)
SerializingExecutor:  at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
SerializingExecutor:  at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
SerializingExecutor:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
SerializingExecutor:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
SerializingExecutor:  at java.lang.Thread.run(Thread.java:920)
SerializingExecutor: Caused by: java.lang.RuntimeException: Tried to marshall a Parcel that contained Binder objects.
SerializingExecutor:  at android.os.Parcel.nativeMarshall(Native Method)
SerializingExecutor:  at android.os.Parcel.marshall(Parcel.java:621)
SerializingExecutor:  at io.grpc.binder.internal.ParcelableInputStream.getDelegateStream(ParcelableInputStream.java:102)
SerializingExecutor:  at io.grpc.binder.internal.ParcelableInputStream.read(ParcelableInputStream.java:116)
SerializingExecutor:  at com.google.common.io.ByteStreams.toByteArrayInternal(ByteStreams.java:191)
SerializingExecutor:  at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:238)
SerializingExecutor:  at io.grpc.Metadata.streamToBytes(Metadata.java:1046)
SerializingExecutor:  at io.grpc.Metadata.access$1300(Metadata.java:58)
SerializingExecutor:  at io.grpc.Metadata$LazyValue.toBytes(Metadata.java:942)
SerializingExecutor:  at io.grpc.Metadata.valueAsBytes(Metadata.java:183)
SerializingExecutor:  at io.grpc.Metadata.toString(Metadata.java:554)
SerializingExecutor:  at java.lang.String.valueOf(String.java:2924)
SerializingExecutor:  at java.lang.StringBuilder.append(StringBuilder.java:132)
SerializingExecutor:  at dragon.grpc.server.HeaderServerInterceptor.interceptCall(HeaderServerInterceptor.java:22)
SerializingExecutor:  at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269)
SerializingExecutor:  at io.grpc.binder.internal.BinderTransportSecurity$ServerAuthInterceptor.interceptCall(BinderTransportSecurity.java:88)
SerializingExecutor:  at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269)
SerializingExecutor:  at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:701)
SerializingExecutor:  at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:408)
SerializingExecutor:  at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:613)
SerializingExecutor:  ... 6 more
```

This is because grpc-binder will use `Parcel.marshall` to serialize `Metadata` into a byte array. 

But the Binder object contained in the ParcelFileDescriptor object cannot or does not support being serialized.

Therefore, according to the above content, it is not known whether grpc-binder will support complex Parcelable object transmission by exposing more APIs or other methods in subsequent updates, so as to make full use of the characteristics of Android AIDL.

**Comment by ejona86** [comment]
The problem seems to be that `dragon.grpc.server.HeaderServerInterceptor` is trying to form a string including the parcelable. What would you hope would happen in that case? We know nothing about what your interceptor is trying to accomplish.

**Comment by CCint3** [comment]
> The problem seems to be that `dragon.grpc.server.HeaderServerInterceptor` is trying to form a string including the parcelable. What would you hope would happen in that case? We know nothing about what your interceptor is trying to accomplish.

Oh, I'm very sorry, this is the problem caused by my coding error. It turns out that grpc-binder can transmit Binder objects through `Metadata`. In my `HeaderServerInterceptor` code, I try to print `Metadata` to `logcat`(like this `Log.d(TAG, "interceptCall: header received from client:" + requestHeaders);`), which will cause serialization A Binder object to byte array. Hence this exception.

Thank you very much for your reminder, it helped me a lot.

**Comment by sanjaypujare** [comment]
I am assuming this issue can now be closed?

**Comment by CCint3** [comment]
> I am assuming this issue can now be closed?

yes.
