### ISSUE TITLE
How to achieve grpc communication without using xx.proto file

### ISSUE THREAD

**Issue by Layfolk-zcy** [grpc/grpc-java#10254]
1、i want to send json call grpc server by postman
2、How can the grpc server be invoked by the client without using the xx.proto file

**Comment by sanjaypujare** [comment]
Take a look at [this](https://grpc.io/blog/grpc-with-json/#receiving-rpcs) to see how to build a gRPC server to receive JSON RPCs. I am assuming you can use postman to send gRPC calls with JSON.

**Comment by Layfolk-zcy** [comment]
> Take a look at [this](https://grpc.io/blog/grpc-with-json/#receiving-rpcs) to see how to build a gRPC server to receive JSON RPCs. I am assuming you can use postman to send gRPC calls with JSON.

Is xx.proto on the server necessary? It is not clear at first contact. thank you

**Comment by sanjaypujare** [comment]
> > Take a look at [this](https://grpc.io/blog/grpc-with-json/#receiving-rpcs) to see how to build a gRPC server to receive JSON RPCs. I am assuming you can use postman to send gRPC calls with JSON.
> 
> Is xx.proto on the server necessary? It is not clear at first contact. thank you

No proto files as mentioned in the article

**Comment by Layfolk-zcy** [comment]
> > > Take a look at [this](https://grpc.io/blog/grpc-with-json/#receiving-rpcs) to see how to build a gRPC server to receive JSON RPCs. I am assuming you can use postman to send gRPC calls with JSON.
> > 
> > 
> > Is xx.proto on the server necessary? It is not clear at first contact. thank you
> 
> No proto files as mentioned in the article

In the official case of grpc-java in Java, the server interface generation still requires xxx.proto file generation. The client can pass json data to the server for conversion. But I was wondering if I could save the way xx.proto generates interfaces on the server side

**Comment by Layfolk-zcy** [comment]
> > > Take a look at [this](https://grpc.io/blog/grpc-with-json/#receiving-rpcs) to see how to build a gRPC server to receive JSON RPCs. I am assuming you can use postman to send gRPC calls with JSON.
> > 
> > 
> > Is xx.proto on the server necessary? It is not clear at first contact. thank you
> 
> No proto files as mentioned in the article

In the official case of grpc-java in Java, the server interface generation still requires xxx.proto file generation. The client can pass json data to the server for conversion. But can I skip the way xx.proto generates interfaces on the server side

**Comment by sanjaypujare** [comment]
> ...
> In the official case of grpc-java in Java, the server interface generation still requires xxx.proto file generation. The client can pass json data to the server for conversion. But can I skip the way xx.proto generates interfaces on the server side

Yes. Please look at the instructions at https://grpc.io/blog/grpc-with-json/#receiving-rpcs which says:

"Again, what Protobuf would normally have generated for us we need to write ourselves. Here is what the base service looks like:"  and then later:

"KeyValueServiceImplBase will serve as both the service definition (which describes which methods the server can handle) and as the implementation (which describes what to do for each method). It serves as the glue between gRPC and our application logic. Practically no changes are needed to swap from Proto to GSON in the server code"

If you define the equivalent of `KeyValueServiceImplBase` class yourself (which normally the proto compiler generartes) then you have no dependency on any xx.proto file. So the key is for you to define the `xxxImplBase` class yourself.

**Comment by ejona86** [comment]
@Layfolk-zcy, you don't explain why you want to avoid the proto-powered code generation. If you want to make a dynamic server, that is still able to convert JSON, you could follow something similar to  https://stackoverflow.com/a/61144510/4690866 . It still requires protoc to be run, but you can receive the descriptors at runtime.

A different potential use-case is for a proxy. https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/grpcproxy/GrpcProxy.java provides an example of that, and it doesn't need any details about the methods it is handling.

**Comment by ejona86** [comment]
Seems like this is resolved as best we can. If not, comment, and it can be reopened.
