### ISSUE TITLE
Boolean field started in ServerImpl is not flipped to false in shutdown or shutdownNow method

### ISSUE THREAD

**Issue by xcchang** [grpc/grpc-java#10275]
Hi team,

In the implementation of `ServerImpl.java`, if I have a usage pattern like below, it will not work when Server is restarted
```java
server.start();     //   boolean field started set to true
...                       //  some other work
server.shutdownNow();     //  boolean field started NOT set back to false
...                       //  some other work
server.start();     //   IllegalStateException thrown because of the Precondition check of field started is still true
```
Did I miss something or `Server` is just not supposed to be restarted in that way? since otherwise I have to instantiate the `ServerImpl` object every time I start the Server.

**Comment by sanjaypujare** [comment]
That's working as designed. Once a server has been shut down it cannot be restarted - you will have to build a new instance. You can just call `build()` again on the original builder you used to build the first instance.
