### ISSUE TITLE
CheckReturnValue error shown when trying to compile with io.grpc:protoc-gen-grpc-java:1.56.0

### ISSUE THREAD

**Issue by rndhacker** [grpc/grpc-java#10291]
Hello everyone, I am trying to set a new grpc environement for my Android project. Unfortunately, when attempting to add the plugin section in the protobuf {} the compiler fails with 'cannot access CheckReturnValue' in compileDevDebugWithJavac. Can anyone please help me out? Thanks in advance!
Please let me know if you need any more info.

### What version of gRPC-Java are you using?
io.grpc:grpc-okhttp:1.56.0
io.grpc:grpc-protobuf-lite:1.56.0
io.grpc:grpc-stub:1.56.0
org.apache.tomcat:annotations-api:6.0.53

protobuf ->
com.google.protobuf:protoc:3.23.2
io.grpc:protoc-gen-grpc-java:1.56.0
### What is your environment?

Mac M1 

### What did you expect to see?
a successful build from Android Studio
### What did you see instead?
'cannot access CheckReturnValue' in compileDevDebugWithJavac
## Build.gradle (app)
```
    implementation("io.grpc:grpc-okhttp:1.56.0") // CURRENT_GRPC_VERSION
            {
                exclude group: 'com.google.guava', module: 'guava' //excluding because it conflicts with another dependency
            }
    implementation("io.grpc:grpc-protobuf-lite:1.56.0") // CURRENT_GRPC_VERSION
            {
                exclude group: 'com.google.guava', module: 'guava'
            }
    implementation("io.grpc:grpc-stub:1.56.0") // CURRENT_GRPC_VERSION
            {
                exclude group: 'com.google.guava', module: 'guava'
            }
    implementation("org.apache.tomcat:annotations-api:6.0.53") {
        exclude group: 'com.google.guava', module: 'guava'
    }
}
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.23.2'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.56.0' // <==== THROWS ERROR WHEN ADDING GRPC PLUGIN, COMPILES FINE WITHOUT IT
        }
    }
    generateProtoTasks {
        all().configureEach { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
            task.plugins {
                grpc { option "lite" }
            }
        }
    }
}
```

**Comment by temawi** [comment]
I see a few recent posts pointing a finger at guava: [[1]](https://github.com/google/guava/issues/2450) [[2]](https://groups.google.com/g/protobuf/c/U153utPnV4Y). Looks like it might be related to Guava version r19. You could check to see if you have that version and if downgrading helps.

**Comment by rndhacker** [comment]
I wrote [2] and [1] is from 2016, I doubt that it has to do with their newest version.

**Comment by temawi** [comment]
Ah, sorry, I guess those posts are not helpful.

`CheckReturnValue` is from ErrorProne and it's possible that your project is not including the version of `errorprone-annotations` that gRPC requires, currently that is version 2.18.0. Please check if in your gradle project definition you are not forcing a downgrade.

If you still see the error, please include the full error message you see here.

**Comment by rndhacker** [comment]
I tried adding 
```
    configurations.all {
        resolutionStrategy {
            force 'com.google.errorprone:error_prone_annotations:2.18.0'
        }
    }
```
Same 'cannot access CheckReturnValue' in compileDevDebugWithJavac Error

**Comment by ejona86** [comment]
ResolutionStrategy will make sure to use a particular version, but the exclusions may cause the dependency not to be present at all. Try adding an implementation dependency on error_prone_annotations.

Note that we can't really support things when you are downgrading dependencies, like guava. I assume that is why it is being excluded, as an upgrade wouldn't need any special configuration.
