### ISSUE TITLE
gRPC Java compiler isn't using fully qualified names for String

### ISSUE THREAD

**Issue by pkwarren** [grpc/grpc-java#10316]
### What version of gRPC-Java are you using?

v1.56.0

### What is your environment?
Linux, Java 17

### What did you expect to see?
Generated code from the gRPC Java compiler should use fully qualified names for `String`.

### What did you see instead?
Compilation error for inputs that include a message type named `String`.

### Steps to reproduce the bug
```proto
syntax = "proto3";

package example;

message String {
  string val = 1;
}

message GetThingRequest {
  string id = 1;
}

message GetThingResponse {
  String id = 1;
}

service ExampleService {
  rpc GetThing(GetThingRequest) returns (GetThingResponse);
}
```

To generate code, I'm using buf with this `buf.gen.yaml`:
```yaml
version: v1
managed:
  enabled: true
plugins:
- plugin: buf.build/protocolbuffers/java
  out: gen
- plugin: buf.build/grpc/java
  out: gen
```

The issue seems to be that the variable here https://github.com/grpc/grpc-java/blob/f3399e3d0e52c4c20409de3b4435fea12bec12c6/compiler/src/java_plugin/cpp/java_generator.cpp#L1224 isn't being used at the following locations:
* https://github.com/grpc/grpc-java/blob/f3399e3d0e52c4c20409de3b4435fea12bec12c6/compiler/src/java_plugin/cpp/java_generator.cpp#L992
* https://github.com/grpc/grpc-java/blob/f3399e3d0e52c4c20409de3b4435fea12bec12c6/compiler/src/java_plugin/cpp/java_generator.cpp#L994
* https://github.com/grpc/grpc-java/blob/f3399e3d0e52c4c20409de3b4435fea12bec12c6/compiler/src/java_plugin/cpp/java_generator.cpp#L1152

I'm happy to raise a PR to fix but I'm having a hard time getting the local build to work end to end on MacOS arm64 and Linux arm64. I imagine this will require not only changing the compiler but also potentially updating tests and regenerating code with the new compiler.

**Comment by pkwarren** [comment]
Opened related issue #10317 for updating the compilation docs to work with newer protoc versions.

**Comment by ejona86** [comment]
Yeah, we need to use the fully-qualified String. I know it is annoying for us Java developers to need to build C++, but let's see if that gets working in #10317.
