### ISSUE TITLE
How to Implement Strict Load Balancing Strategies?

### ISSUE THREAD

**Issue by cdming405003** [grpc/grpc-java#10319]
I have implemented load balancing for a gRPC with the following issues, similar to https://github.com/grpc/grpc-java/issues/9936

For example, after service discovery, two subchannels will be generated: c1 and c2. According to my rules, traffic should be routed to c2. However, due to the update policy of gRPC, the pick generated after c1 update can only be routed to c1, which does not meet my expectations. May I ask if there are any good solutions to the problems I have encountered?

**Comment by Layfolk-zcy** [comment]
> I have implemented load balancing for a gRPC with the following issues, similar to #9936
> 
> For example, after service discovery, two subchannels will be generated: c1 and c2. According to my rules, traffic should be routed to c2. However, due to the update policy of gRPC, the pick generated after c1 update can only be routed to c1, which does not meet my expectations. May I ask if there are any good solutions to the problems I have encountered?

```java
ManagedChannelBuilder<?> builder = ManagedChannelBuilder
                // build channel to server with server's address "discovery:///serverName"
                .forTarget(contextPath)
                // 设置拦截器
                .intercept(new ContextClientInterceptor())
                // 设置默认的负载规则
                .defaultLoadBalancingPolicy(loadBalance)
                // 不会再去尝试升级http1
                .usePlaintext()
                // 消息传输大小限制
                .maxInboundMessageSize(100 * 1024 * 1024)
                // 关闭重试
                .disableRetry();
        ManagedChannel channel = builder.build();
```

**Comment by temawi** [comment]
Can you please clarify where "your rules" are defined? Did you implement your own load balancing policy? Or are you using a built-in one like round robin?

**Comment by larry-safran** [comment]
@Layfolk-zcy we cannot help you without knowing how `loadBalance` is defined and configured.  If you are using a custom load balancer, then we'll need the full code for that to help you.  It sounds like there is probably a bug in your code somewhere that is causing the update of c1 to interfere with the desired behavior.
