### ISSUE TITLE
Compilation docs no longer work in latest grpc-java

### ISSUE THREAD

**Issue by pkwarren** [grpc/grpc-java#10317]
### What version of gRPC-Java are you using?
v1.56.0

### What is your environment?
MacOS/Linux arm64

### What did you expect to see?
Following instructions in `COMPILING.md` should result in a successful build.

### What did you see instead?
https://github.com/grpc/grpc-java/blob/f3399e3d0e52c4c20409de3b4435fea12bec12c6/COMPILING.md#how-to-build-code-generation-plugin refers to the protobuf-all artifact, which is no longer shipped with newer releases (grpc-java requires protoc 22.3). It also refers to using autotools to build protoc from source, which is no longer supported (ref: https://protobuf.dev/news/2022-08-03/).

### Steps to reproduce the bug
Attempt to follow the steps in COMPILING.md to build grpc-java (including the compiler).

**Comment by pkwarren** [comment]
It looks like #10048 will fix most of these issues (when merged).

**Comment by ejona86** [comment]
Ugh, yeah. The trick right now is _Java_ is depending on 22.3, but we are still using 21.x for c++. Do the instructions work if you try and use the older version?

**Comment by pkwarren** [comment]
> Ugh, yeah. The trick right now is _Java_ is depending on 22.3, but we are still using 21.x for c++. Do the instructions work if you try and use the older version?

Good to know. I got confused by this while building:
```
> Configure project :grpc-compiler
*** Building codegen requires Protobuf version 3.22.3
```

I managed to get it building with the current instructions (although I had to set `org.gradle.jvmargs=-Xmx4g` in gradle.properties to get xds code to build as the default 1g wasn't enough).

**Comment by ejona86** [comment]
> *** Building codegen requires Protobuf version 3.22.3

Oh... I know how that happened.  I think I'm just going to delete the version in that message. Most of the time you can use an older version without issue.

> although I had to set org.gradle.jvmargs=-Xmx4g in gradle.properties to get xds code to build as the default 1g wasn't enough

"Fork javac to avoid OOM" in https://github.com/grpc/grpc-java/pull/10299 may fix that. We've been fighting OOM for a while on the CI; I'm hopeful we've tracked down the major source.
