### ISSUE TITLE
Protobuf versions compatibility expectations

### ISSUE THREAD

**Issue by atollena** [grpc/grpc-java#10320]
The `grpc-services` module depends on proto-generated Java files for channelz, health, etc. As a result, when using `io.grpc:grpc-services` with a project that depends directly on `com.google.protobuf:protobuf-java` (as is the case for most Java projects using gRPC I suppose), projects need to make sure that the version of protobuf they use is compatible with the version that grpc-java used to compile grpc-services.

We are running into a problem when attempting to upgrade from grpc v1.54.1 to 1.55.1. Our project builds with protobuf v3.19.2. When using a grpc client with health checking enabled, the health check client fails with `UnsupportedOperationException` when attempting to serialize `HealthCheckRequest`. As far as I understand, this is because our version of `com.google.protobuf.GeneratedMessageV3` that comes with `com.google.protobuf:protobuf-java:3.19.2` is incompatible with the message classes that ship with `io.grpc:grpc-services:1.55.1`, such as `io.grpc.health.v1.HealthCheckRequest`.

Things are working fine on grpc v1.54.1. I see that grpc-java switched to protobuf 3.22 in 1.55.

Is there an official compatibility matrix between versions of protobuf and versions of grpc-java? Is there a more specific policy that should apply to grpc-services?

**Comment by ejona86** [comment]
This is a question about the compatibility of protobuf's generated code and protobuf runtime. The generated code depends on protobuf-java that is at least the same version, and protobuf-java keeps stability of any APIs used by the generated code. So normal library versioning applies: "you can upgrade." You can generate code with protoc 3.19.2 (or 19.2 for new-style versions) and use it with protobuf-java 3.22 at runtime.

I do suggest considering upgrading the version of protoc you use, on general principal, but there's no compatibility harm from using it until such events like a protobuf-java 4.x or such.

The same applies to grpc-java's generated code and runtime libraries.

**Comment by atollena** [comment]
> This is a question about the compatibility of protobuf's generated code and protobuf runtime.

Yes, your explanation is clear. I did not understand the ties between runtime and generated code versions. I just re-read https://github.com/protocolbuffers/protobuf/blob/main/java/README.md#maven and now it's clear:

> Make sure the version number of the runtime matches (or is newer than) the version number of the protoc.

So in the context of grpc-java, the implications is that projects that depends on grpc-java must use a minor version of protobuf-java (runtime) that is >= to the version that grpc-java uses for protoc to generate e.g. the health check service. At the moment, this version is 3.22. But it does not necessarily imply upgrading protoc and the generated code all in one step. This allows doing things in two steps: 1. upgrade runtime + grpc, 2. then the generated code with protoc if desired.

**Comment by ejona86** [comment]
> the implications is that projects that depends on grpc-java must use a minor version of protobuf-java (runtime) that is greater or equal to the protoc version that grpc-java uses to generate

Right. Although you don't easily know what version of protoc we were using, so you'd mostly see the version of protobuf-java we used and avoid downgrading that version. Gradle would do that automatically, and Maven can detect downgrades with requireUpperBoundDeps.

And yes, right now we are on version 3.22.3, since grpc-java 1.55.1.

**Comment by atollena** [comment]
👍 Thanks for the quick answers.
