### ISSUE TITLE
how config crl by NettyServerBuilder

### ISSUE THREAD

**Issue by diandianxinchen** [grpc/grpc-java#10335]

**Comment by ejona86** [comment]
There is not a convenience API for this. You get to use the Java JSSE API to configure a TrustManager and then pass that TrustManager to gRPC via [`TlsServerCredentials.Builder.trustManager(TrustManager...)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/TlsServerCredentials.Builder.html#trustManager-javax.net.ssl.TrustManager...-).

I believe the general approach is you configure `PKIXBuilderParameters`, then build a `CertPathTrustManagerParameters` to pass to `TrustManagerFactory.init(ManagerFactoryParameters)`. But I've not actually configured it before. You might find [the non-CRL flow we use](https://github.com/grpc/grpc-java/blob/1a9c2a0dacdd97b074d2055f66149c65dff9424c/okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java#L699) slightly helpful as a reference point.

CC @erm-g

**Comment by ejona86** [comment]
Cross-referencing: https://stackoverflow.com/questions/76580057/how-config-crl-list-by-nettyserverbuilder

**Comment by temawi** [comment]
I'm closing this issue as answered.
