### ISSUE TITLE
Cancellation of server-streaming RPCs does not work with InProcessTransport

### ISSUE THREAD

**Issue by tombergan** [grpc/grpc-java#10363]
### What version of gRPC-Java are you using?

1.54

### What is your environment?

Android

### What did you expect to see?

When the client cancels an RPC call via a CancelableContext, the Server RPC call should be cancelled.

### What did you see instead?

The Server RPC never stops.

### Steps to reproduce the bug

[This commit](https://github.com/grpc/grpc-java/commit/74137b09785c81f2ccf2ce57eac844dc849b926d) may have broken cancellation of client-unary-server-streaming RPCs over the InProcessTransport. The sequence of events is:

1. Client sends the RPC request message, which immediately calls InProcessClientStream.halfClose.
2. That [calls serverStreamListener.halfClosed from the syncContext](https://github.com/grpc/grpc-java/blob/68e29922cfe74829279aa0ee772759b4bcce533b/core/src/main/java/io/grpc/inprocess/InProcessTransport.java#L857).
3. That calls the [halfClose implementation here](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L346), which calls ServerCall.Listener.onHalfClose.
4. That enters the UnaryServerCallHandler, because of the code [here](https://github.com/grpc/grpc-java/blob/68e29922cfe74829279aa0ee772759b4bcce533b/stub/src/main/java/io/grpc/stub/ServerCalls.java#L61).
5. That reaches the code [here](https://github.com/grpc/grpc-java/blob/68e29922cfe74829279aa0ee772759b4bcce533b/stub/src/main/java/io/grpc/stub/ServerCalls.java#L182), which IIUC, invokes the actual server implementation of that RPC call.

Steps 3-5 happen within SynchronizationContext.drain. That call, IIUC, expects callbacks to happen quickly, without blocking. However, in the above sequence, SynchronizationContext.drain ends up calling the user-specified implementation of the server call. We have an implementation which looks like:

```
class Service extends ServiceGrpc.ServiceImplBase {
  void Method(Request request, StreamObserver<Response> response) {
    var op = new LongRunningOp();
    var executor = Executors.newScheduledThreadPool(5);
    Context.current().addListener()(context -> op.stop(), executor);
    ...
    // This is a blocking call which generates a response stream until it receives
    // a cancellation from the client, via the above op.stop() call.
    op.run(response);
  }
}
```

Note that our implementation blocks. If the client attempts to cancel this RPC, we deadlock:

6. The client cancels the context, which eventually calls InProcessClientStream.cancel.
7. That [queues a task on syncContext](https://github.com/grpc/grpc-java/blob/68e29922cfe74829279aa0ee772759b4bcce533b/core/src/main/java/io/grpc/inprocess/InProcessTransport.java#L844) to notify the server of cancellation.
8. The syncContext is blocked in op.run, which never finishes, because op.run is waiting for cancellation, which is waiting on syncContext.

I believe the root problem is that [this call](https://github.com/grpc/grpc-java/blob/68e29922cfe74829279aa0ee772759b4bcce533b/stub/src/main/java/io/grpc/stub/ServerCalls.java#L182) needs to execute on a different thread, although I don't know enough about grpc internals to know which thread is correct.

**Comment by tombergan** [comment]
Turns out we were using a directExecutor which explicitly says not to block, which means this is not a bug after all. Sorry for the noise!

**Comment by larry-safran** [comment]
No problem, tracing through it was a good educational experience :)
