### ISSUE TITLE
Ping message

### ISSUE THREAD

**Issue by ankur8819** [grpc/grpc-java#10391]
I am having issues to connect grpc server and grpc client. Below is the sequence of logs after enabling io.grpc. It looks like server closes the connections after some time.
Can some one help in understanding  the sequence of messages below.

Grpc Server implemntation : 1.35.0
GrpcClient : 1.55.1

HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_128_GCM_SHA256
OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
INBOUND SETTINGS: ack=false settings={HEADER_TABLE_SIZE=4096, ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=65535, MAX_FRAME_SIZE=16384}
 OUTBOUND SETTINGS: ack=true
 INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=458751
 INBOUND SETTINGS: ack=true
OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: x.x.x.x:40300, :path: /com.SomeService/Exchange, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.55.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
OUTBOUND DATA: streamId=3 padding=0 endStream=false length=79 bytes=000000004a08013a468a031853494d42415f4952445f505249434552315f434c49454e54a003f2a7acc69631c2031853494d42415f4952445f50524943455231...
OUTBOUND PING: ack=false bytes=1111
 INBOUND PING: ack=true bytes=1111
OUTBOUND PING: ack=false bytes=1111
INBOUND PING: ack=true bytes=1111
 OUTBOUND PING: ack=false bytes=1111
  INBOUND RST_STREAM: streamId=3 errorCode=1

**Comment by sanjaypujare** [comment]
Couple of things:

- Can you use the latest gRPC release (esp gRPC server which is on 1.35 and kind of old)
- generate logs on both client and server and include them here

**Comment by temawi** [comment]
@ankur8819 We haven't heard from you so I'll close the bug, but you can re-open it if needed.
