### ISSUE TITLE
Plugin is not building following current instructions

### ISSUE THREAD

**Issue by LisaFC** [grpc/grpc-java#104]
Final gradle install is giving me:

Could not resolve all dependencies for configuration ':grpc-netty:compile'.

> Could not find io.netty:netty-codec-http2:5.0.0.Alpha2-SNAPSHOT.
>   Searched in the following locations:
>       https://repo1.maven.org/maven2/io/netty/netty-codec-http2/5.0.0.Alpha2-SNAPSHOT/maven-metadata.xml
>       https://repo1.maven.org/maven2/io/netty/netty-codec-http2/5.0.0.Alpha2-SNAPSHOT/netty-codec-http2-5.0.0.Alpha2-SNAPSHOT.pom
>       https://repo1.maven.org/maven2/io/netty/netty-codec-http2/5.0.0.Alpha2-SNAPSHOT/netty-codec-http2-5.0.0.Alpha2-SNAPSHOT.jar
>       file:/usr/local/google/home/lcarey/.m2/repository/io/netty/netty-codec-http2/5.0.0.Alpha2-SNAPSHOT/maven-metadata.xml
>       file:/usr/local/google/home/lcarey/.m2/repository/io/netty/netty-codec-http2/5.0.0.Alpha2-SNAPSHOT/netty-codec-http2-5.0.0.Alpha2-SNAPSHOT.pom
>       file:/usr/local/google/home/lcarey/.m2/repository/io/netty/netty-codec-http2/5.0.0.Alpha2-SNAPSHOT/netty-codec-http2-5.0.0.Alpha2-SNAPSHOT.jar
>   Required by:
>       io.grpc:grpc-netty:0.1.0-SNAPSHOT

**Comment by lsuggula** [comment]
Yes update and try, got the same error.

**Comment by lsuggula** [comment]
Or do this: Change from io.netty:netty-codec-http2:4.1.0.Beta5-SNAPSHOT to io.netty:netty-codec-http2:4.1.0.Beta4 in build.gradle file

**Comment by ejona86** [comment]
Did you first install Netty? As in the docs:
```
$ git submodule update --init
$ cd lib/netty
$ mvn install -pl codec-http2 -am -DskipTests=true
```

**Comment by lsuggula** [comment]
Yes.

**Comment by ejona86** [comment]
Maybe it failed? What platform are you on? I just now ran on a fresh container and it all seemed to work.
