### ISSUE TITLE
Interceptor for the Transport layer

### ISSUE THREAD

**Issue by danrotBlo** [grpc/grpc-java#10409]
### Is your feature request related to a problem?

I receive many messages that I would like my server to ignore in the transport layer - i.e. Http/1 requests or other non GPRC requests.

### Describe the solution you'd like

add a filter or interceptor for the transport layer.

### Describe alternatives you've considered

I have tried using the interceptor but it is meant for application layer filtering.

**Comment by ejona86** [comment]
The transport layer is quite different between the various transports. So we can't/don't want to really provide an API to handle requests at that layer.

But that said, the transport should be failing HTTP/1 connections and fail non-GRPC requests. What is wrong with the current behavior?

**Comment by danrotBlo** [comment]
It would be use full if I could have some control over that - i.e. HTTP2 requests get logged, HTTP1 are rejected and so on. I just had such an issue where we wanted to keep HTTP2 requests and disregard HTTP1.

**Comment by ejona86** [comment]
The transports don't support generic HTTP. They are grpc-only.
