### ISSUE TITLE
Netty 4.1.87 to 4.1.94 seriously regressed perf

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#10401]
On July 6th a change to master [seriously impacted](https://grafana-dot-grpc-testing.appspot.com/?orgId=1&from=1688194800000&to=1688885999000) our performance benchmarks.

The only interesting thing from that time is [the Netty upgrade](https://github.com/grpc/grpc-java/commit/361616ae7ce081fd22a2f2e4d4a2ab34cc4e954a).

The prod team noticed as well, in b/290613465 . We have two candidate PRs as the cause for the slowdown, but still investigating.

**Comment by ejona86** [comment]
I've confirmed that https://github.com/netty/netty/pull/13408 is the cause of the regression.

```
Benchmark                                                             (direct)  (transport)    Mode     Cnt           Score          Error  Units
4.1.87:
TransportBenchmark.streamingCallsMessageThroughput                       false        NETTY   thrpt      10      645802.206 ±    13270.777  ops/s
4.1.88:
TransportBenchmark.streamingCallsMessageThroughput                       false        NETTY   thrpt      10      654535.745 ±     7323.670  ops/s
4.1.93:
TransportBenchmark.streamingCallsMessageThroughput                       false        NETTY   thrpt      10      658665.726 ±    12600.729  ops/s
4.1.94 (two runs):
TransportBenchmark.streamingCallsMessageThroughput                       false        NETTY   thrpt      10      564743.743 ±     4025.113  ops/s
TransportBenchmark.streamingCallsMessageThroughput                       false        NETTY   thrpt      10      600532.355 ±    19314.619  ops/s
Custom 4.1.94 build with PR 13408 reverted:
TransportBenchmark.streamingCallsMessageThroughput                       false        NETTY   thrpt      10      653681.499 ±     5988.903  ops/s
```

**Comment by normanmaurer** [comment]
@ejona86 Hmm... This is interesting. I wonder why this could cause a regression...

**Comment by franz1981** [comment]
@ejona86 there is anything that was making uses of the specific classes I have removed/changed?
Like using reflection to do something specific that now fail?

If there is a microbench, next week I can help to investigate

**Comment by ejona86** [comment]
https://github.com/netty/netty/pull/13510 tries to address this. I will run the benchmarks and see how things fare.

I was totally with y'all; I didn't understand how the change caused such a regression. It looked like a plain code movement. We are scheduled to do our release build today, so I was moving fast to avoid reverting to 4.1.87. I only tracked it down late on a Friday and it is probably already fixed Monday morning!

**Comment by ejona86** [comment]
The benchmarks recovered after this change: https://grafana-dot-grpc-testing.appspot.com/?orgId=1&from=1688194800000&to=1690268399000

**Comment by chrisvest** [comment]
@ejona86 if you have time, it'd be interesting to see a run based on netty/netty#13510 where this condition is re-introduced: https://github.com/netty/netty/pull/13408/files#diff-c24e989820523c812b36dea1eb81cbbde7822d060eac7bf136fa96be00956e3fR521
That would tell us if there's something weird with computing the sizes of the small and normal caches, or if the previous change (with the extra cache class) made the JIT unhappy somehow.

**Comment by ejona86** [comment]
With the added-back condition:
```diff
diff --git a/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java b/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java
index afbe10e7c8..985e93fbdb 100644
--- a/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java
+++ b/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java
@@ -515,12 +515,12 @@ public class PooledByteBufAllocator extends AbstractByteBufAllocator implements
             final Thread current = Thread.currentThread();
             final EventExecutor executor = ThreadExecutorMap.currentExecutor();
 
-            if (useCacheForAllThreads ||
+            if ((smallCacheSize != 0 || normalCacheSize != 0) && (useCacheForAllThreads ||
                     // If the current thread is a FastThreadLocalThread we will always use the cache
                     current instanceof FastThreadLocalThread ||
                     // The Thread is used by an EventExecutor, let's use the cache as the chances are good that we
                     // will allocate a lot!
-                    executor != null) {
+                    executor != null)) {
                 final PoolThreadCache cache = new PoolThreadCache(
                         heapArena, directArena, smallCacheSize, normalCacheSize,
                         DEFAULT_MAX_CACHED_BUFFER_CAPACITY, DEFAULT_CACHE_TRIM_INTERVAL, true);
```

@chrisvest, it is still fast with the condition:
```
4.1.94+425aa8a+23da118+dc16c581+cond:
TransportBenchmark.streamingCallsMessageThroughput     false        NETTY  thrpt   10  652665.210 ± 13148.084  ops/s
4.1.94+425aa8a+23da118:
TransportBenchmark.streamingCallsMessageThroughput     false        NETTY  thrpt   10  571977.989 ± 7822.770  ops/s
```

Sooo.... JIT? Bizarre. These benchmarks ran on JDK 8. I'd have to ask around to see what version of Java populates the dashboard.

------------------------------

To run the benchmark, I hacked up Netty with the following, just to reduce variables:
```diff
diff --git a/buffer/pom.xml b/buffer/pom.xml
index aa261a4d64..afdd6a4fbb 100644
--- a/buffer/pom.xml
+++ b/buffer/pom.xml
@@ -25,6 +25,7 @@
 
   <artifactId>netty-buffer</artifactId>
   <packaging>jar</packaging>
+  <version>4.1.95.Final-SNAPSHOT</version>
 
   <name>Netty/Buffer</name>
 
@@ -36,7 +37,7 @@
     <dependency>
       <groupId>${project.groupId}</groupId>
       <artifactId>netty-common</artifactId>
-      <version>${project.version}</version>
+      <version>4.1.94.Final</version>
     </dependency>
     <dependency>
       <groupId>org.mockito</groupId>
```

And then I removed cases we don't care about from the benchmark and used my netty snapshot (I'm not certain that moving `mavenLocal()` was necessary, but I didn't want to fiddle with it so I only tried it this one way).
```diff
diff --git a/benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java b/benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java
index ea23fadee..236f7e5e1 100644
--- a/benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java
+++ b/benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java
@@ -70,9 +70,9 @@ public class TransportBenchmark {
     INPROCESS, NETTY, NETTY_LOCAL, NETTY_EPOLL, OKHTTP
   }
 
-  @Param({"INPROCESS", "NETTY", "OKHTTP"})
+  @Param({"NETTY"})//"INPROCESS", "NETTY", "OKHTTP"})
   public Transport transport;
-  @Param({"true", "false"})
+  @Param({"false"})//"true", "false"})
   public boolean direct;
 
   private ManagedChannel channel;
diff --git a/build.gradle b/build.gradle
index 0d76097dc..e2edc1956 100644
--- a/build.gradle
+++ b/build.gradle
@@ -25,8 +25,8 @@ subprojects {
     repositories {
         maven { // The google mirror is less flaky than mavenCentral()
             url "https://maven-central.storage-download.googleapis.com/maven2/" }
-        mavenCentral()
         mavenLocal()
+        mavenCentral()
     }
 
     tasks.withType(JavaCompile).configureEach {
diff --git a/netty/build.gradle b/netty/build.gradle
index 0f22d2774..a77a04f54 100644
--- a/netty/build.gradle
+++ b/netty/build.gradle
@@ -15,6 +15,7 @@ configurations {
 
 dependencies {
     api project(':grpc-core'),
+            'io.netty:netty-buffer:4.1.95.Final-SNAPSHOT',
             libraries.netty.codec.http2
     implementation libs.netty.handler.proxy,
             libraries.guava,
```
And then I ran:
```
./gradlew :grpc-benchmarks:jmh -PjmhIncludeSingleClass=TransportBenchmark.streamingCallsMessageThroughput
# outputs to benchmarks/build/results/jmh/results.txt
```

The benchmark uses multiple threads. Based on our performance dashboard, increasing the number of threads makes the issue dramatically worse. I didn't try changing the threads for this benchmark though.

I ran the benchmarks on my desktop with an Intel Xeon E5-1650.

**Comment by franz1981** [comment]
Thanks @ejona86 apart from https://bugs.openjdk.org/browse/JDK-8180450 I'm not aware of scalability issues which involve "type pollution" really; if not megamorphism calls - but here we're still within the bi-morphism which  should be handled decently well by JDK 8 - this is a mistery to me but if you can run it with `-prof perfasm` and send me the ASM (here or in a gist) I can shred some light on this; I admit I'm pretty curious!

**Comment by ejona86** [comment]
The internal investigation saw higher lock contention in PoolArena.

@franz1981, see the perfasm results:
[perfasm-fast.txt](https://github.com/grpc/grpc-java/files/12163835/perfasm-fast.txt)
[perfasm-slow.txt](https://github.com/grpc/grpc-java/files/12163836/perfasm-slow.txt)

**Comment by franz1981** [comment]
I hope I can find some time to run the bench, any additionl contention on `PoolArena` seems to me that the thread-local pool cache isn't effective enough (that's why I've pointed in the direction of the condition - that could have disabled using the thread local cache). Thanks!
