### ISSUE TITLE
io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream possible leak ?

### ISSUE THREAD

**Issue by lmcdasi** [grpc/grpc-java#10415]
Hi,

   I'm having an issue regarding: “io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream”

   When I run load test I'm getting a leak and based on heap hprof, the most used is from:
![image](https://github.com/grpc/grpc-java/assets/947517/920e2a0a-dcb2-4509-bd0d-88a3dacdbcb4)

   That code that streamed was running ok until:  I changed from jdk 11 to jdk 17 and did a minor change in the way I stream data out. When I build the bytebuffer I use 'UnsafeByteOperations.unsafeWrap(unsafeByteBuffer)' instead of passing a 'regular' byte buffer.

  I would like to know if there is some form of incompatibility between jdk17 and grpc/netty that I somehow missed.

Thank you.

**Comment by ejona86** [comment]
Streams are bound to the connection. If you are seeing a stream leak, then you are probably leaking a Channel/Server, or not waiting long enough with awaitTerminated() for it to clean up.

**Comment by ejona86** [comment]
Or... you're saying it is a leak _while running_? If you are seeing streams leak while running, most likely you are orphaning RPCs in your application.

**Comment by lmcdasi** [comment]
I do have a simulator & an on-prem service that I test under load. For whatever reasons the simulator streaming did only log a statement on the onCompleted method - initially.

The rpc is: 

rpc StreamMedia (stream StreamMediaRequest) returns (StreamMediaResponse);

and should be a one-direction streaming from the onPrem towards the cloud (client -> server).

During the load test, both are on separate vm's with no envoy in between.
And as long as I do not add an onNext()/onCompleted on the sim side as bellow:

           @Override
            public void onCompleted() {
                LOGGER.debug("on completed");
               final var streamMediaResponseOrBuilder = StreamMediaResponse.newBuilder();
               streamObserver.onNext(streamMediaResponseOrBuilder.
                       setStatus(Status.newBuilder().setStatusCode(StatusCode.OK).build()).build());
               streamObserver.onCompleted();
            }

that leak is present - on the client side (I did not look at the server side - sim).

I do understand the validity of the "onComplete" on the server side. I just want to make sure it is 'mandatory' to avoid that leak.

Or do I have other issues on the onPrem software that I need to look after.
Thank you.

**Comment by ejona86** [comment]
The server decides when the RPC completes. The only exception is if the client cancels the RPC. On server-side, `streamObserver.onCompleted()` or `onError()` completes the RPC. If neither of those is called, then the RPC continues to exist. If you leak the `streamObserver` before calling `onCompleted()`/`onError()` then you are leaking memory.

The `onCompleted()` method on server-side is called when the client finishes its stream.

**Comment by lmcdasi** [comment]
Fair enough. I have one more question if you do not mind.

In real life, the client will communicate with the server via envoy. In this case the client might not know if there is a communication issue between envoy & the server.
Would it be possible that the 'oncompleted' might not arrive at the client in some corner case scenarios ? If that is the case, are there any extra precautions steps to mitigate that ?

Based on your comments, should the client call onError after a certain timeout if no onComplete received from server ?

Thank you.

**Comment by ejona86** [comment]
> In this case the client might not know if there is a communication issue between envoy & the server.

You should configure Envoy to monitor the connection. There's keepalive config within [`Cluster.http2_protocol_options`](https://github.com/envoyproxy/envoy/blob/06e3e7d59fddc6541cecf399a8adc64092df7ed8/api/envoy/api/v2/cluster.proto#L628). Generally you want to configure keepalive on both sides of every connection. The client-side is generally more aggressive to reduce the latency to noticing an issue, and the server side could be conservative just to clean up eventually.

> Based on your comments, should the client call onError after a certain timeout if no onComplete received from server ?

It's common to specify a deadline when creating the call (or configure a timeout in service config). Since you are doing streaming, it can make sense to do this manually like you mentioned to have more control.

**Comment by lmcdasi** [comment]
Thank you for your answers.
