### ISSUE TITLE
How to dynamically modify the defaultLoadBalancingPolicy (loadBalance) of ManagerChannel to retrieve a new ManagerChannel client and call the server, and use NameResolver to resolve the service name for service discovery

### ISSUE THREAD

**Issue by Layfolk-zcy** [grpc/grpc-java#10424]
How to dynamically modify the defaultLoadBalancingPolicy (loadBalance) of ManagerChannel to retrieve a new ManagerChannel client and call the server, and use NameResolver to resolve the service name for service discovery

**Comment by Layfolk-zcy** [comment]
> The only method to dynamically change the service config is for [a NameResolver to return the service config](https://grpc.github.io/grpc-java/javadoc/io/grpc/NameResolver.ResolutionResult.Builder.html#setServiceConfig-io.grpc.NameResolver.ConfigOrError-).

Shouldn't the client decide the load strategy? I am not very clear about the content of GRPC, and I hope to seek advice. Thank you very much

**Comment by ejona86** [comment]
"Service config" is the configuration that service owners can create to control client behavior. Clients shouldn't decide on the load balancing strategy; the service owner is responsible for that.

**Comment by ejona86** [comment]
An example of what, specifically? You say "corresponding load configuration," but don't what it corresponds to. I don't know your objectives, so it is hard to help.

**Comment by Layfolk-zcy** [comment]
>An example of what, specifically?

As described in my question title, I want to modify the policy in the **ManagerChannel. defaultLoadBalancingPolicy()** method through an external interface call after the client service is started. However, after trying to modify the method myself, I am unable to implement the policy modification and the control console will report an exception At that time, your suggestion was to modify it through the "Service config" method. After reading the GRPC source code, I still had no idea how to implement it

**Comment by sanjaypujare** [comment]
The way to do this is to implement your own NameResolver - just to be able to provide the serviceConfig you want. Your NameResolver could wrap an existing NameResolver and add the serviceConfig. 

There is an example for a custom NameResolver at https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/nameresolve . It doesn't have serviceConfig. But you can take a look at gRPC's DnsNameResolver at https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L291 to see how serviceConfig is added to the ResolutionResult.
