### ISSUE TITLE
Client StreamObserver stops receiving callbacks seemingly due to interference with another library

### ISSUE THREAD

**Issue by gjajoo** [grpc/grpc-java#10431]
We're running into an issue with Client StreamObserver ceasing to receive callbacks (streaming and unary) on a specific channel. It always coincides with the occurrence of the following messages in the log, as long as the channel was used before these messages. 
|i.n.h.c.compression.ZlibCodecFactory (ZlibCodecFactory.java:39) - -Dio.netty.noJdkZlibDecoder: false
|i.n.h.c.compression.ZlibCodecFactory (ZlibCodecFactory.java:42) - -Dio.netty.noJdkZlibEncoder: false
|i.n.h.c.compression.JdkZlibEncoder (JdkZlibEncoder.java:76) - -Dio.netty.jdkzlib.encoder.maxInitialOutputBufferSize=65536
|i.n.h.c.compression.JdkZlibEncoder (JdkZlibEncoder.java:77) - -Dio.netty.jdkzlib.encoder.maxInputBufferSize=65536

These messages are generated in a flow within a third-party open source library that also has netty as a dependency. While these specific messages may be a red herring, is it possible for a thirdparty library to mess with a GRPC netty channel that it doesn't even own? 

The channel is plaintext and we haven't enabled any compression on it. The server doesn't seem to notice any issues at the other end and doesn't report any onError etc... Is this a known issue? How can we enable Netty's LoggingHandler on both server and client to try to debug this? Don't mind using unsupported api to enable such netty specific logging. Any other advice welcome :-)

**Comment by ejona86** [comment]
Are you using `grpc-netty` or `grpc-netty-shaded`? Which OS are you running on?

**Comment by gjajoo** [comment]
grpc-netty
client OS: Windows
server OS: Linux

Upon further investigation, it appears that there is no interference. Windows client stops receiving data silently. The same code running on Linux doesn't have this issue. We enabled ALL for j.u.l and debug for "io.netty" in logback - no messages indicating anything was off.
________________________________

**Comment by ejona86** [comment]
So you're saying you previously thought you knew an approximate trigger for the hang, but now you've seen it even without those other logs?

If you can try easily, I'd suggest trying `grpc-netty-shaded`. There are JNI components, and some other copy of Netty might be breaking that native code if they weren't careful. I've only really seen how it breaks on Linux, so it might behave in this weird way on Windows.

**Comment by gjajoo** [comment]
Yes, there doesn't seem to be any interference. It breaks on its own on Windows. What logging options do we have grpc-netty? How can we enable wire level message logging?
We won't be able to switch to grpc-netty-shaded without extensive testing. But for some medium-term options - can grpc-netty-shaded be used safely with another library using netty native, possibly another version?
________________________________

**Comment by ejona86** [comment]
`grpc-netty-shaded` makes a copy of Netty for just grpc's usage. It insulates gRPC from any other Netty you may have in your dependency tree. (At the cost of not being able to share event loops and such.)

See https://github.com/grpc/grpc-java/issues/9680#issuecomment-1307973994 for an example configuration to get HTTP/2 frame-level logging.

**Comment by temawi** [comment]
Seems like this issue can be closed - feel free to re-open if needed.
