### ISSUE TITLE
In Android, when using gRPC, the data cannot be received when the app is switched to the background.

### ISSUE THREAD

**Issue by lvtie** [grpc/grpc-java#10444]
In Android, when using gRPC, the data cannot be received when the app is switched to the background.

**Comment by temawi** [comment]
Can you please be more specific about what goes wrong or give steps to reproduce the problem?

Also, are you sure you have not disabled background data in Android settings?

**Comment by larry-safran** [comment]
@lvtie was this resolved?

**Comment by lvtie** [comment]
I have identified that the issue is caused by the Doze mode on the phone. On Android, it is necessary to add the REQUEST_IGNORE_BATTERY_OPTIMIZATIONS permission and request this permission from the user by sending an Intent with the ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS to resolve this.
