### ISSUE TITLE
Attributes.Key doesn't implement .equals

### ISSUE THREAD

**Issue by rp-** [grpc/grpc-java#10454]
The Attributes.Key class doesn't implement `.equals` so `Attributes.get()` will never work.

https://github.com/grpc/grpc-java/blob/cde208afce38186d06084605abed36f21b003465/api/src/main/java/io/grpc/Attributes.java#L119

**Comment by sanjaypujare** [comment]
If you look at the Javadoc for `Key` it says it used reference equality. That's why `Attributes.data` is an `IdentityHashMap`.  In an IdentityHashMap, two keys k1 and k2 are considered equal if and only if (k1==k2). You are supposed to use statically defined `Key`s for Attributes

**Comment by rp-** [comment]
mea culpa, I didn't find the predefined Keys and thought I can't access them then.
