### ISSUE TITLE
How to add retry mechanism to handle expired tokens?

### ISSUE THREAD

**Issue by puliv02** [grpc/grpc-java#10462]
My question is similar to https://github.com/grpc/grpc-java/issues/5856. My use case is 
1. send the grpc call with token - using withCallCredentials
2. In the interceptor, check the status and if it is UNAUTHENTICATED, then perform refresh action and get new token
3. Retry grpc call with this new token

To achieve this, I'm trying to use in-built [retry](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#maximum-number-of-retries) feature of grpc-java along with an interceptor class. Is this the right approach? If yes, I need help in achieving the following two parts:
1. How to update the credentials that were set initially using withCallCredentials
2. Retry with default Service config is not working. My proto package name is similar to packageName.v1, service name is TestServiceName and in the service config, I'm using below service config
```
{
  "methodConfig": [
    {
      "name": [
        {
          "service": "packageName.TestServiceName"
        }
      ],

      "retryPolicy": {
        "maxAttempts": 2,
        "initialBackoff": "0.5s",
        "maxBackoff": "30s",
        "backoffMultiplier": 2,
        "retryableStatusCodes": [
          "UNAUTHENTICATED"
        ]
      }
    }
  ]
} 
```

blockingStub definition : 
```
TestServiceNameGrpc.newBlockingStub(
                        ManagedChannelBuilder.forAddress(<host>,<port>)
                                .intercept(new GrpcClientRequestInterceptor())
                                .defaultServiceConfig(config)
                                .enableRetry()
                                .build())
                .withCallCredentials(creds);
```

**Comment by ejona86** [comment]
CallCredentials are not designed to be updated; you can use a single CallCredentials instance for a channel at creation time and not change it. CallCredentials can have internal mutable state, and it is expected that state would change as appropriate. Each retry attempt will call the CallCredentials, so it can return a different result for each.

Your issue seems to be that the CallCredentials needs to receive UNAUTHENTICATED. Does that mean you aren't using something OAuth-like that has a provided expiration time?

**Comment by larry-safran** [comment]
@puliv02 Did the above comment address your issue?

**Comment by puliv02** [comment]
@ejona86 , thanks for the update. Its oauth that I'm using and now I updated the logic to check the expiration time before sending the grpc call and if the token is expired, then refresh and send the new token. I'm using withCallCredentials to do this as it'll be called every time we make a grpc call. Please correct me if i'm wrong here. 

On a side note, regarding my second point, I never got to see retry working with the set up I mentioned. Can you provide some pointers for this?

**Comment by larry-safran** [comment]
@puliv02 Are your questions now resolved?

**Comment by puliv02** [comment]
Yes @larry-safran , this is resolved now, thank you.
