### ISSUE TITLE
io.grpc.StatusRuntimeException: UNKNOWN: channel closed

### ISSUE THREAD

**Issue by marx-freedom** [grpc/grpc-java#10474]
### What version of gRPC-Java are you using?
1.56.1

### What is your environment?

Linux
`EpollEventLoopGroup` is used to configure gRPC client.

### What did you expect to see?
StatusRuntimeException with `UNAVAILABLE` status on network failure.

### What did you see instead?
StatusRuntimeException with `UNKNOWN` status.

Our logs contains only trimmed stack trace:
```
io.grpc.StatusRuntimeException: UNKNOWN: channel closed
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:275)
Caused by:
java.nio.channels.ClosedChannelException
        at io.grpc.netty.Utils.statusFromThrowable(Utils.java:275)
Caused by:
io.netty.channel.StacklessClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
Caused by:
io.netty.channel.unix.Errors$NativeIoException: sendAddress(..) failed: Connection reset by peer
```

Sometimes message in NativeIoException contains other function names - writeAddress, readAddress,...

### Steps to reproduce the bug
Unfortunately, cannot reproduce this issue on my local Linux-machine.

**Comment by ejona86** [comment]
So the base error there is "Connection reset by peer." That could be caused by multiple things, but the easiest to trigger in firewalls/NATs in a home/office network (not datacenter). gRPC can't solve this problem for you directly, as it can have lots of causes, but generally by specifying a "keepalive time" you can cause activity to prevent the firewall/NAT from dropping the connection. What value to use depends on which type of network you are experiencing the problem.

**Comment by marx-freedom** [comment]
I understand the cause of a "reset by peer" and keepalive is configured. I don't understand why gRPC translates `ClosedChannelException` to `UNKNOWN` status? It seems to me that `ClosedChannelException` can be mapped to `UNAVAILABLE` status like any other `IOException` [here](https://github.com/grpc/grpc-java/blob/beaeeefdd25e8c26d4b999a7977efba94b5a4463/netty/src/main/java/io/grpc/netty/Utils.java#L277)

**Comment by ejona86** [comment]
Oh, I see. Yeah, it should be UNAVAILABLE. This looks to be the same as b/273930962. The failing assumption that I think causes this is that a _write_ failed; normally a _read_ fails.

From b/273930962, I said:
> In Utils.statusFromThrowable() we need to dig into the ClosedChannelException and do something better _when there is a cause_. We will still need to handle the case where there is a ClosedChannelException without a cause.
