### ISSUE TITLE
android.net.ConnectivityManager$TooManyRequestsException

### ISSUE THREAD

**Issue by LingLuoJack** [grpc/grpc-java#10488]
Hello, many online users have encountered this issue，We have detected that the problem comes from this code segment
```
AndroidChannelBuilder
                    .forAddress(host, port)
                    .usePlaintext()
                    .directExecutor()
                    .context(applicationContext)
                    .keepAliveWithoutCalls(true)
                    .idleTimeout(300, TimeUnit.SECONDS)
                    .build()
```
this is issue detail
![image](https://github.com/grpc/grpc-java/assets/113987410/6518f20e-d3ad-496d-b176-dc699c60e250)
please help me

**Comment by ejona86** [comment]
[ConnectivityManager limits the number of monitors to 100](https://developer.android.com/reference/android/net/ConnectivityManager#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback)). If you are exceeding the limit, you are probably creating channels but not shutting them down when no longer needed.

**Comment by LingLuoJack** [comment]
> 

But I only create one Channel object in the whole app life cycle。
Is it because the channel was not shut down when the app was killed?

**Comment by ejona86** [comment]
The limit is per-app, so your app seems to be leaking them somehow. Maybe the problem isn't in gRPC but elsewhere in your app? CC @temawi

**Comment by ejona86** [comment]
I don't think we can help more here at present, as we see no way one channel could cause this problem. If there's more we can do or you find out more, comment, and we can reopen.
