### ISSUE TITLE
Can you clarify what exactly runs in the offloadExecutor?

### ISSUE THREAD

**Issue by BenjaminMalley** [grpc/grpc-java#10508]
From [the javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#offloadExecutor(java.util.concurrent.Executor)), I would assume that the offload executor is used for any blocking operations, which I would assume includes ClientInterceptors but this does not appear to be the case.

Can it be clarified either here or in the documentation what exactly runs on the offload executor?

Thanks!

**Comment by larry-safran** [comment]
The offload executor is used for "out of band" communication such as the DNS name resolvers and call credentials.  
All of our RPC messages are done asynchronously at the lower levels, even the blocking ones, which is why interceptors always have to be designed to be asynchronous.
