### ISSUE TITLE
compile error for grpc-java 1.54.1

### ISSUE THREAD

**Issue by ad-c2-ip58n4** [grpc/grpc-java#10515]
I followed the document
https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin
to build protobuf and grpc-java

here is my comand:
$ PROTOBUF_VERSION=21.7
$ curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protobuf-all-$PROTOBUF_VERSION.tar.gz
$ tar xzf protobuf-all-$PROTOBUF_VERSION.tar.gz
$ cd protobuf-$PROTOBUF_VERSION
$ ./configure --disable-shared
$ make   # You may want to pass -j to make this run faster; see make --help
$ sudo make install

wget https://github.com/grpc/grpc-java/archive/refs/tags/v1.54.1.tar.gz
cd grpc-java/
./gradlew  build -PskipAndroid=true

when compling grpc-java, error reported

```
  * Skipping the build of Android projects because skipAndroid=true

Configure project :grpc-compiler
*** Building codegen requires Protobuf version 3.21.7
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin

Task :grpc-compiler:linkJava_pluginExecutable
/usr/bin/ld: /usr/local/lib/libprotoc.a(code_generator.o): in function `google::protobuf::internal::ArenaStringPtr::Set(char const*, google::protobuf::Arena*)':
/home/hzchenyuefang/tools/protobuf-21.7/src/./google/protobuf/arenastring.h:409: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
/usr/bin/ld: /usr/local/lib/libprotoc.a(code_generator.o): in function `google::protobuf::stringpiece_internal::StringPiece::CheckSize(unsigned long)':
/home/hzchenyuefang/tools/protobuf-21.7/src/./google/protobuf/stubs/stringpiece.h:190: undefined reference to `google::protobuf::stringpiece_internal::StringPiece::LogFatalSizeTooBig(unsigned long, char const*)'
/usr/bin/ld: /home/hzchenyuefang/tools/protobuf-21.7/src/./google/protobuf/stubs/stringpiece.h:190: undefined reference to `google::protobuf::stringpiece_internal::StringPiece::LogFatalSizeTooBig(unsigned long, char const*)'
/usr/bin/ld: /home/hzchenyuefang/tools/protobuf-21.7/src/./google/protobuf/stubs/stringpiece.h:190: undefined reference to `google::protobuf::stringpiece_internal::StringPiece::LogFatalSizeTooBig(unsigned long, char const*)'
/usr/bin/ld: /home/hzchenyuefang/tools/protobuf-21.7/src/./google/protobuf/stubs/stringpiece.h:190: undefined reference to `google::protobuf::stringpiece_internal::StringPiece::LogFatalSizeTooBig(unsigned long, char const*)'
/usr/bin/ld: /home/hzchenyuefang/tools/protobuf-21.7/src/./google/protobuf/stubs/stringpiece.h:190: undefined reference to `google::protobuf::stringpiece_internal::StringPiece::LogFatalSizeTooBig(unsigned long, char const*)
```

what's the problem with my compiling command? and how to fix it?

**Comment by larry-safran** [comment]
Can you please specify the operating system on which you are trying to build?  

Is there a reason you aren't using the prebuilt binaries and using skipCodegen=true? 

For brand new work, why not use the latest version of grpc-java?

**Comment by ad-c2-ip58n4** [comment]
1. my system
hzchenyuefang@hih-l-6975:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

hzchenyuefang@hih-l-6975:~$ uname -a
Linux hih-l-6975 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

2. when use the latest grpc-java v1.57.1, I should use protobuf v3.22.1
and I follow the document https://github.com/protocolbuffers/protobuf/blob/main/src/README.md
'''
To build the C++ Protocol Buffer runtime and the Protocol Buffer compiler (protoc) execute the following:

bazel build :protoc :protobuf
The compiler can then be installed, for example on Linux:

cp bazel-bin/protoc /usr/local/bin
'''
only protoc is copied, and no protobuf lib;

so when I compile grpc-java, error happend, and chatgpt told me it is version incompatible.

**Comment by ad-c2-ip58n4** [comment]
I use this command 
./gradlew  build -PskipAndroid=true -PskipCodegen=true
then build success， but there is no bin file protoc-gen-grpc-java  generated

**Comment by sanjaypujare** [comment]
> ...but there is no bin file protoc-gen-grpc-java generated

Yes, but why do you need to build "protoc-gen-grpc-java"  if you didn't make any changes to code generation. The downloaded one should suffice.

**Comment by sanjaypujare** [comment]
Closing it for now. Pls comment here and we will reopen
