### ISSUE TITLE
Getting HTTP2 exception after enabling nginx controller on GKE with grpc services

### ISSUE THREAD

**Issue by MohitMehta1986** [grpc/grpc-java#10523]
In my project using gRPC Java on GKE. I have enable nginx controller for grpc service. I have spring boot service connecting to grpc service. 

The documentation here mentions that the client code for a secure channel is this:

ManagedChannel channel = ManagedChannelBuilder.forAddress("myservice.example.com", 443).build();
GreeterGrpc.GreeterStub stub = GreeterGrpc.newStub(channel);
And this is my code:

channel = ManagedChannelBuilder
                    .forAddress(domain, port)
                    .usePlaintext()
                    .build();

Before enable nginx controller it was working fine. But after enabling it I am getting HTTP2 exception

"io.netty.handler.codec.http2.Http2Exception:** First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f"

grpc curl is working fine.

**Comment by sanjaypujare** [comment]
Hex dump for first 5 bytes: 485454502f translates to "HTTP/" . Can you use wireshark or additional logging to get the complete output? 

Also is grpcurl also going through the same path (i.e. Nginx controller) as your client? If not, may be you need to look into the nginx controller config?

**Comment by MohitMehta1986** [comment]
nginx controller is configured to use TLS. 
It works fine by removing plaintext and using NettyChannelBuilder

**Comment by sanjaypujare** [comment]
> ... It works fine by removing plaintext and using NettyChannelBuilder

Curious, why did you have to switch to NettyChannelBuilder. You could have continued using ManagedChannelBuilder and just remove the `usePlaintext` part.

**Comment by MohitMehta1986** [comment]
NettyChannelBuilder provide facility for passing sslcontext with Managebuilder alone i am getting error.

**Comment by sanjaypujare** [comment]
There is another way [`Grpc.newChannelBuilderForAddress`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/Grpc.java#L109) to which you can pass [`TlsChannelCredentials`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/TlsChannelCredentials.java) . This is thew new and recommended API. See if you can use that instead of passing the `SslContext`.

**Comment by MohitMehta1986** [comment]
Thanks this also works. Any documentation available which api use to when.

**Comment by sanjaypujare** [comment]
> Thanks this also works. Any documentation available which api use to when.

I recommend reading https://github.com/grpc/proposal/blob/master/L74-java-channel-creds.md which will not only answer your questions but also provide more context.
