### ISSUE TITLE
CANCELLED: io.grpc.Context was canclled without error

### ISSUE THREAD

**Issue by hakusai22** [grpc/grpc-java#10534]
CANCELLED: io.grpc.Context was canclled without error。

**Comment by hakusai22** [comment]
In what scenario will grpc appear with io. grpc. StatusRuntimeException: CANCELLED: io. grpc. Context was cancelled without error

**Comment by YifeiZhuang** [comment]
It means the current or parent context for the current RPC is cancelled with null throwable parameter:
Use `CancellableContext.cancel(e)` to provide a [cause](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.CancellableContext.html#cancel(java.lang.Throwable)).

Refer to these good [examples](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/cancellation/CancellationClient.java#L66) that shows proper usage of context for cancellation.

**Comment by hakusai22** [comment]
My case is that HTTP calls asynchronous future rpcA, and in rpcA, blockFuture calls rpcB/rpcC. The first time the HTTP interface is called, the exception context is canceled, and I call it again and return normally. What I am thinking is whether it is possible that the asynchronous rpcA context ends and will be abnormal to the rpcB/C context

**Comment by YifeiZhuang** [comment]
Oh yea in this case, if all these RPCs are called from the same thread, they use the same context. So it sounds like the rpcB and rpcC will be cancelled, too.

**Comment by ejona86** [comment]
If you want "child" RPCs to outlive the RPC that caused them to be created, use [fork](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html#fork()): `Context.current().fork().execute(() -> asyncRpc())`.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
