### ISSUE TITLE
Is this Any typeUrl correct?

### ISSUE THREAD

**Issue by ronsigal** [grpc/grpc-java#10535]
When I pack an inner class from CC1_proto (created by the gRPC compiler) into an Any, like this:
```
	CC1_proto.gString.Builder builder = CC1_proto.gString.newBuilder();
	CC1_proto.gString gs = builder.setValue("abc").build();
	Any any = Any.pack(gs);
	System.out.println(any.getTypeUrl());
```
I get this URL:  "type.googleapis.com/dev.resteasy.grpc.example.gString". But then
```
		String className = any.getTypeUrl().substring(any.getTypeUrl().indexOf('/') + 1);
		System.out.println("className: " + className);
		Class<?> clazz = Class.forName(className);
```
prints "className: dev.resteasy.grpc.example.gString" and fails with `ClassNotFound`. If I do this
```
		CC1_proto.gString.Builder builder = CC1_proto.gString.newBuilder();
		CC1_proto.gString gs = builder.setValue("abc").build();
		Any any = Any.pack(gs);
		String className = any.getTypeUrl().substring(any.getTypeUrl().indexOf('/') + 1);
		String pkg = className.substring(0, className.lastIndexOf('.'));
		String simpleClassName = className.substring(className.lastIndexOf('.') + 1);
		String fullClassName = pkg + ".CC1_proto$" + simpleClassName;
		System.out.println("fullClassName: " + fullClassName);
		try {
			Class<?> clazz = Class.forName(fullClassName);
			System.out.println(clazz.getCanonicalName());
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```
I get "fullClassName: dev.resteasy.grpc.example.CC1_proto$gString" and it works. Is that intentional?

Thanks.

**Comment by ejona86** [comment]
`Any` stores the _protobuf name_ of a message. That is the protobuf package name + the protobuf message name. That is cross-language. You can't dynamically load the message using reflection.

You probably want to use a [`TypeRegistry`](https://protobuf.dev/reference/java/api-docs/com/google/protobuf/TypeRegistry.Builder.html). You register all messages you are interested in. It keeps track of all the transitive messages used. Then you can look up a message by its typeUrl. You can then use protobuf's `DynamicMessage` to process the message.

This is much more of a protobuf question, so https://github.com/protocolbuffers/protobuf is a more appropriate place to get further details.

**Comment by ronsigal** [comment]
Thank you, Eric. It's obvious, isn't it ... :(

And thank you for the pointer to TypeRegistry.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by ronsigal** [comment]
Yes, @ejona86, it's resolved. Sorry for wasting your time. :-P
