### ISSUE TITLE
netty: IOException should map to UNAVAILABLE

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1053]
NIO can throw `java.io.IOException: Connection reset by peer`. In general, it seems that `IOException` would be `UNAVALIABLE`, although there are certainly outliers given the heavy overloading/abuse of `IOException` in Java.

**Comment by carl-mastrangelo** [comment]
Seems like generalizing IOException to always mean UNAVAILABLE would be risky, since UNAVAILABLE implies the rpc can be retried idempotently.  Perhaps selective callsites can do this mapping?

**Comment by ejona86** [comment]
I see nothing regarding idempotency with UNAVAILABLE, but agree that it doesn't quite match. The only other option for "TCP connection is severed mid-stream" would be ABORTED, and that was previously (stubby days) decided to avoid from in the library. So right now UNAVAILABLE seems to be "the (mostly) right thing". This is based on a conversation with @a11r.

It sounds like @a11r and myself would be fine with reinvestigating what to use, but neither of us are willing to drive it.

**Comment by ejona86** [comment]
This requires a change to `AbstractNettyHandler.exceptionCaught()`, since it would currently be defeating any instanceof detection.

**Comment by nmittler** [comment]
@ejona86 @carl-mastrangelo do we have a test that reproduces this?

**Comment by carl-mastrangelo** [comment]
I don't believe so.

**Comment by ejona86** [comment]
I think I may have run into it reliably when using LocalChannel instead of loopback for NettyTransportTest, because LocalChannel behaves slightly differently when the endpoint isn't available.
