### ISSUE TITLE
How to access unparsed response data in ClientInterceptor?

### ISSUE THREAD

**Issue by pratiksanglikar** [grpc/grpc-java#10541]
I am working on a caching solution much like it is described in #1403, however with a difference where the cache actually lives in the different caching server cluster. To achieve this, the idea is to use a ClientInterceptor and make a call to the caching server to see if the response is already available and if so, return the raw binary response from the interceptor, else make a call to the downstream service and then cache the raw binary response in the caching server.

The workaround described in #1403 works for ServerInterceptor, however I wanted to check how can we access unparsed raw binary response data in the ClientInterceptors?

**Comment by ejona86** [comment]
You can do the same approach as done for server-side: change marshallers in the MethodDescriptor. Looks like this could be used as an example:

https://github.com/grpc/grpc-java/blob/134b0490d5470d2f1c65a7f2bba87d3e3d7736c1/api/src/main/java/io/grpc/ClientInterceptors.java#L103-L140

And for the marshaller you use something like the [ByteArrayMarshaller](https://github.com/grpc/grpc-java/blob/134b0490d5470d2f1c65a7f2bba87d3e3d7736c1/examples/src/main/java/io/grpc/examples/preserialized/ByteArrayMarshaller.java) or something like it of your choosing (e.g., an [InputStream marshaller](https://github.com/grpc/grpc-java/blob/134b0490d5470d2f1c65a7f2bba87d3e3d7736c1/api/src/main/java/io/grpc/ServerInterceptors.java#L141-L157)).
