### ISSUE TITLE
CallOptions.withStreamTracerFactory

### ISSUE THREAD

**Issue by 313hemant313** [grpc/grpc-java#10544]
Wanted to use below grpc-java api's to trace network issues / retry logging.

Not able to find withStreamTracerFactory in stub.

Tried this but not sure if this will replace any existing ClientStreamTracker or not.
Also is this the correct way to add Option to stub ?

```
@Bean
public StubTransformer customStubTransformer() {
    return (name, stub) -> stub.withOption(CallOptions.Key.create("streamTracerFactories"), List.of(new ClientStreamTracer.Factory() {
        @Override
        public ClientStreamTracer newClientStreamTracer(ClientStreamTracer.StreamInfo info, Metadata headers) {
            return new CustomClientStreamTracer(info);
        }
    }));
}
```

Spring boot grpc issue: https://github.com/yidongnan/grpc-spring-boot-starter/issues/954

**Comment by ejona86** [comment]
We don't really want/expect individual callsites to use tracers, and instead would expect an interceptor to do so. Easiest thing for you at the moment is to make an interceptor and add it to the stub.

https://github.com/grpc/grpc-java/issues/2143 tracks allowing you to use CallOptions that aren't on the AbstractStub.

**Comment by 313hemant313** [comment]
Okay but how to get below information in an interceptor ?

When extending ClientStreamTracer we get streamClosed method to override.
```
    private final ClientStreamTracer.StreamInfo streamInfo;
    
    @Override
    public void streamClosed(Status status) {
        if (status != Status.OK) {
            log.warn("For gRPC streamClosed with status: {}, isTransparentRetry: {} and previousAttempts: {}", status,
                    streamInfo.isTransparentRetry(), streamInfo.getPreviousAttempts());
        }
        super.streamClosed(status);
    }
```

**Comment by ejona86** [comment]
```java
stub = stub.withInterceptors((method, callOptions, next) -> {
  callOptions = callOptions.withStreamTracerFactory(...);
  return next.newCall(method, callOptions);
});
```
