### ISSUE TITLE
CallOptions custom options overhead

### ISSUE THREAD

**Issue by kilink** [grpc/grpc-java#10546]
The way it is currently implemented, adding a custom option to a `CallOptions` instance with the `withOption` method copies the underlying array on each invocation, making adding several custom options in one go incur overhead, particularly if it's on the hot path.

e.g.:
```java
callOptions.withOption(FOO_KEY, "foo")
    .withOption(BAR_KEY, "bar")
    .withOption(BAZ_KEY, "baz");
```

It would be great if such usage didn't cause excessively copying (persistent?), or if an API were available to add multiple options at once somehow.

**Comment by ejona86** [comment]
I think the general recommendation is to use a single key for all three things. Is there a reason you need three separate keys?

It'd be easy to have a method that adds multiple at once, but I am doubtful that it should be needed often.

**Comment by ejona86** [comment]
We really need to understand why three separate keys are being used and we've not heard back, so closing. More information can be provided and then we can reopen.

**Comment by kilink** [comment]
That's fair, in this particular contrived example it probably could be avoided by combining them into one key; it does seem that unrelated interceptors could also run into the same issue though.
