### ISSUE TITLE
Is grpc-java stable enough to use in production environment?

### ISSUE THREAD

**Issue by dawnbreaks** [grpc/grpc-java#1056]
Hi, i notice that there were 5 releases for grpc-java, and Is grpc-java stable enough to use in production environment? 

Thanks & Best Regards!

**Comment by ejona86** [comment]
grpc-java 0.9.0 (release made Thursday, but not yet announced) is considered beta. We are aware of some rollouts on the verge of using it in production, but it is not yet considered GA.

**Comment by hepin1989** [comment]
@ejona86 It's synced with the ```grpc/grpc``` right?When ```grpc/grpc``` get GA then this project will get GA soon right？thanks。

**Comment by ejona86** [comment]
Yes, we are releasing grpc/grpc-java on roughly the same schedule as grpc/grpc, and they should go into GA at roughly the same time. Individual languages could lag behind, but our goal is to get all off them GA at around the same time.

**Comment by hepin1989** [comment]
Thanks for that detail,very helpful.
