### ISSUE TITLE
Can project loom improve performance of Grpc's bidirectional streaming?

### ISSUE THREAD

**Issue by EclipseDaebak** [grpc/grpc-java#10569]
Our microservice will consist of spring boot and grpc. And we'll use Grpc's bi-directional streaming.
It'll be like this.
```
service OurService {
  rpc Req(stream Request) returns (stream Event);
}

message Request {
  message Msg1 {}
  message Msg2 {}
  ...

  oneof request {
    Msg1 msg1 = 1;
    Msg2 msg2 = 2;
    ...
  }
}

...
```

We have to choice r2dbc + webflux VS jpa.
I wonder if we choose jpa + grpc's bi-directional streaming, using virtual thread of project loom can improve performance.

**Comment by ejona86** [comment]
I've answered at https://stackoverflow.com/questions/77146964/will-javas-virtual-thread-be-useful-for-grpc-bidirectional-stream-application/
