### ISSUE TITLE
What is the gRPC threading model?

### ISSUE THREAD

**Issue by tisonkun** [grpc/grpc-java#10561]
The actual issue is that, I'd like to perform some blocking operations in the generated stub, said:

```java
    @Override
    public void readEntry(ReadEntryRequest request, StreamObserver<ReadEntryReply> responseObserver) {
        final long ledgerId = request.getLedgerId();
        final long entryId = request.getEntryId();
        try {
            final Entry entry = bookie.readEntry(ledgerId, entryId);
            responseObserver.onNext(
                    ReadEntryReply.newBuilder().setEntry(entry.toEntryProto()).build());
            responseObserver.onCompleted();
        } catch (Exception e) {
            responseObserver.onError(e);
        }
    }
```

... where `bookie.readEntry` can block on file IO. I wonder if it will block other calls or if too much such blocking calls will exhaust thread pool assigned to the gRPC service if any.

**Comment by kjwise** [comment]
You can easily return from readEntry without calling any method on the responseObserver. Just notify it once you are done with your blocking call. This will at least not making the method readEntry itself blocking, but no response will be sent to the client until you notify the observer.

**Comment by tisonkun** [comment]
@kjwise Are you suggesting move the blocking ops to a separated executor or make it async?

This is the exact question I have: do I have to do it or I can write code as above and it runs optimal?

**Comment by kjwise** [comment]
That's what I did, I had to go a bit further since I also wanted to map all requests that were asking for the same thing, so only 1 thread actually does the work, and once it returns, all observers waiting for the same result are notified at once.

This way whatever netty threads or event loops that are running in the framework can happily keep on churning.

**Comment by tisonkun** [comment]
@kjwise to be clear, does this mean that the gRPC method call is as significant as the main loop in Actor model that should not be blocked

**Comment by ejona86** [comment]
You can block within a gRPC callback. The callback runs on `serverBuilder.executor()` (defaults to a cached thread pool). So blocking just consumes your application resources, but doesn't cause problems for gRPC. It only impacts other RPCs if the executor runs out of threads (assuming you set an executor with a maximum size).
