### ISSUE TITLE
gRPC- ManagedChannel Builder -DNS IPCaching

### ISSUE THREAD

**Issue by banandh** [grpc/grpc-java#10581]
Hi - gRPC services are hosted behind the AWS ALB. gRPC service to service communication happens via ALB url.

During ALB scale up events it has more backend IP's to support the gRPC channel connections but when the ALB scales down backend IP's whichever part of ALB's are released and ALB is limited with connection as per the load it gets. After ALB scale down event if I trigger any load test on the gRPC service I keep getting NoRouteToHostException with certain IP numbers , and when I checked with AWS support this IP's were part of ALB and due to scale down they are not part of ALB backend anymore. Java gRPC ManagedChannelBuilder is caching the IP address and that's causing this issue.

What is the recommended options to get rid of DNS IP caching or refresh DNS IP's after a very first occurrence of the issue

**Comment by ejona86** [comment]
> Java gRPC ManagedChannelBuilder is caching the IP address and that's causing this issue.

Java itself caches the IP address. See [`networkaddress.cache.ttl`](https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html). I believe the default is 30 seconds. How long did this issue last?

**Comment by larry-safran** [comment]
Please let us know if setting the java property to 0 eliminates the issue `networkaddress.cache.ttl=0`.  If that works, you could then increase it to a number of seconds that your users can tolerate.

**Comment by ejona86** [comment]
I don't recommend setting `networkaddress.cache.ttl=0`. Having some amount of cache is fair. Setting it to 0 can hammer DNS servers.

In gRPC we want to avoid the DNS server from requesting too frequently, so the other languages delay DNS refresh if a refresh has already happened within ~30s or such. In Java, Java's DNS cache interferes with that technique, but provides something similar (although not quite as good).

There can be multiple things going on here, but without understanding the timing expected/observed there's not much to do from our side.

**Comment by ejona86** [comment]
Unclear if this is resolved, but we've helped as we can and haven't heard back. If not resolved, comment, and it can be reopened.

**Comment by banandh** [comment]
It still reoccurs. We even tried setting this properties via command line argument but still this issue persist. More than performance the ip caching should be sorted out first. Any guidance around it can be add value.

-Dnetworkaddress.cache.ttl=1 -Dnetworkaddress.cache.negative.ttl=1
-Dsun.net.inetaddr.ttl=1

We are using Open Zulu JDK. If some other option form gRPC libraries please help us with.

**Comment by larry-safran** [comment]
Which Load Balancer are you using in this application (e.g. RoundRobin, RingHash, PickFirst, etc.)?  
Are you seeing the NoRouteToHostException disappear after a certain number of seconds or does it vary?

**Comment by banandh** [comment]
@larry-safran  - AWS ALB with round robin. Yes for certain duration java caches the IP address and whatever the request triggered in a window those all fails and after certain time its disappearing. 

Sine ours is batch usecase at times even the complete file is failing. We need give some time or restart the apps to bring back it to normal state.

Even after setting the recommended variables via command line , we get this error. Not sure if something is wrong from ourend.

**Comment by larry-safran** [comment]
You still haven't responded whether it is half a second, one second, 30
seconds or more that RPCs are failing.
The most likely explanation if it is a short time is that the first failure
triggered a dns refresh, but while that was waiting to be received and
processed a number of rpcs were started and immediately failed.
Since this is a batch job, you can use waitForReady which instead of
immediately failing the RPC will wait (up to duration) for the channel to
establish a working connection.
