### ISSUE TITLE
AndroidChannelBuilder and TlsChannelCredentials

### ISSUE THREAD

**Issue by developerGM** [grpc/grpc-java#10606]
I am testing grpc and I am trying to connect to a server using TLS.

Using `AndroidChannelBuilder` is impossibile to connect, I receive `UNAVAILABLE: End of stream or IOException`
I can only connect using `Grpc.newChannelBuilderForAddress` but lost the android optimization (using `Context`) that have with `AndroidChannelBuilder` 

With this code I can connect
```
TlsChannelCredentials.Builder tlsBuilder = TlsChannelCredentials.newBuilder();
ManagedChannelBuilder<?> channelBuilder = Grpc.newChannelBuilderForAddress("XXX", 443, tlsBuilder.build());
```

is right solve like this?

**Comment by sanjaypujare** [comment]
If you still want to use the context of AndroidChannelBuilder how about:

```
TlsChannelCredentials.Builder tlsBuilder = TlsChannelCredentials.newBuilder();
ManagedChannelBuilder<?> channelBuilder = Grpc.newChannelBuilderForAddress("XXX", 443, tlsBuilder.build());

AndroidChannelBuilder androidBuilder = AndroidChannelBuilder.usingBuilder(channelBuilder).context(myContext);
```

Hopefully it works?

**Comment by developerGM** [comment]
It's perfect!

**Comment by sanjaypujare** [comment]
Sounds good. If there is nothing else I think we can close the issue
