### ISSUE TITLE
StreamObserver on mainThread

### ISSUE THREAD

**Issue by developerGM** [grpc/grpc-java#10605]
Hi, how can update my UI?
I receive `Can't toast on a thread that has not called Looper.prepare()`
but `newStub` not is asyncronous?

```
        SessionServiceGrpc.newStub(GrpcClient.getInstance().getChannel()).createAppSession(req, new StreamObserver<CreateAppSessionResponse>() {
            @Override
            public void onNext(CreateAppSessionResponse value) {
                    Toast.makeText(requireContext(), "TEST", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onError(Throwable t) {
                    Toast.makeText(requireContext(), "TEST", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onCompleted() {
                    Toast.makeText(requireContext(), "TEST", Toast.LENGTH_SHORT).show();
            }
        });
```

**Comment by sanjaypujare** [comment]
This StackOverflow thread might be helpful https://stackoverflow.com/questions/3875184/cant-create-handler-inside-thread-that-has-not-called-looper-prepare 

Another possible solution (not verified):

```
            public void onNext(CreateAppSessionResponse value) {
                   Thread thread = new Thread(){
                        public void run(){
                           Looper.prepare();//Call looper.prepare()
 
                           Handler mHandler = new Handler() {
                                 public void handleMessage(Message msg) {
                                     Toast.makeText(requireContext(), "TEST", Toast.LENGTH_SHORT).show();
                                 }
                            };
                            Looper.loop();
                        }
                   };
                   thread.start();
            }
```

**Comment by developerGM** [comment]
Yes, I know but so if I have 50 calls, for each `onNext ` or on `onError` I need to implement `Handler` to update my UI?

**Comment by sanjaypujare** [comment]
> Yes, I know but so if I have 50 calls, for each `onNext ` or on `onError` I need to implement `Handler` to update my UI?

This requirement is really coming from the Android UI layer and not gRPC. May be you can create a helper method/class based on the above?

**Comment by developerGM** [comment]
Yes, I will create a `CustomStreamObserver `that extends `StreamObserver`
and then I will expose the results on mainthread
`new Handler(Looper.getMainLooper()).post(() -> { here });`

**Comment by sanjaypujare** [comment]
Sounds good. If you have a solution, and there is nothing else to discuss in this issue, we should close the issue.

**Comment by developerGM** [comment]
yes, you can close. thanks
