### ISSUE TITLE
grpc-java does not work with grpc-cpp anymore?

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc-java#1061]
It used to work to run greeter_client.cc from grpc-cpp with HelloWorldServer from grpc-java, but this seems not to work anymore with grpc-0_11_0 release and latest protobuf anymore. There are multiple problems: first, to get HelloWorldServer compiled with the proto example file, I needed to fiddle with the java "package" in several places. After the compile worked, the client connects to the server but nothing happens. The remote method sayHello() seems never to return. Only when killing the server the client will finally return an (unsuccessful) response.

**Comment by emmenlau** [comment]
Oh and HelloResponse is now called HelloReply, as far as I could see...

**Comment by ejona86** [comment]
@tbetbetbe, did Java not get updated for some proto changes to the examples? I think it got the route guide changes, but maybe not hello world changes?

**Comment by emmenlau** [comment]
Thanks for looking into this, its high priority for us! Could you please also check that afterwards, the helloworld-example from grpc-java and grpc-cpp can work together? Its our source for getting started.

**Comment by emmenlau** [comment]
I'm really sorry if I appear pushy, but we are completely blocked trying to use grpc cross-platform. Its still not working. Could you please help? I assumed this is a key feature of grpc. Does it work for you with grpc-java server with grpc-cpp client? Can you help out with such an example that works? Anything I can try? Please help! :-(

**Comment by ejona86** [comment]
Interop is a key feature and is tested [continuously](https://grpc-testing.appspot.com/job/gRPC_interop_master/).

I just tested java->cpp and cpp->java (java master ↔ cpp master, java 0.9.0 ↔ cpp master, java 0.9.0 ↔ cpp 0.11.0) without any issues. The java and cpp clients compiled without needing to modify any files. I'm not sure what would have caused sayHello() to hang. Maybe it could have been a long delay instead of a full hang, which [was fixed in 0.11.1 cpp](https://github.com/grpc/grpc/releases/tag/release-0_11_1).

C++ and Java are both in the process of releasing 0.12, so at the very least I'd suggest updating to 0.12 when it is available and trying again.

**Comment by ejona86** [comment]
0.12 was just released. Please reopen if it still doesn't work for you.

**Comment by emmenlau** [comment]
Dear ejona,
somehow I don't get this. Could you *please* help to clarify? Not even the *proto* files for the helloworld-example between grpc-0.12.0 and grpc-java-0.12.0 are similar. The files don't have the same name, and they don't have the same content. In Java, rpc SayHello (HelloRequest) returns (HelloResponse), in C++ it returns (HelloReply). I've asked about this before, can you clarify why this is correct, or please help if this example is incorrect?

If interop is a key feature, it would be great to have a consistent example. I'm asking about this since 4 months, would be great if you could take a look please? I would like to build on grpc, but I don't even get helloworld to run. Can you make one example consistent between languages, or explain why it can not be consistent? I think proto files are meta language and shared between implementation languages? Why different return values?

```
 --- thirdparty/grpc-java-0.12.0/examples/src/main/proto/hello_world.proto	2016-01-22 23:32:57.000000000 +0100
+++ thirdparty/grpc-release-0_12_0/examples/protos/helloworld.proto	2016-01-14 19:55:07.000000000 +0100
@@ -29,16 +29,15 @@

 syntax = "proto3";
 
-package helloworld;
+option java_package = "io.grpc.examples";
+option objc_class_prefix = "HLW";
 
-option java_multiple_files = true;
-option java_package = "io.grpc.examples.helloworld";
-option java_outer_classname = "HelloWorldProto";
+package helloworld;
 
 // The greeting service definition.
 service Greeter {
   // Sends a greeting
-  rpc SayHello (HelloRequest) returns (HelloResponse) {}
+  rpc SayHello (HelloRequest) returns (HelloReply) {}
 }
 
 // The request message containing the user's name.
@@ -47,6 +46,6 @@
 }
 
 // The response message containing the greetings
-message HelloResponse {
+message HelloReply {
   string message = 1;
-}
\ No newline at end of file
+}

**Comment by emmenlau** [comment]
Thanks for your great work! But please help. Can you reopen the issue?

**Comment by ejona86** [comment]
@emmenlau, did you try again with 0.12?

While it is unfortunate that the proto files are different, they are actually compatible. The package is the same, the service name is the same, the method name is the same, and the messages have the same fields. I would expect it to work, and I've seen it work.

As I said before, you shouldn't need to modify the protos at all to compile. Have you been able to compile without modifying the protos? How does it currently break?

**Comment by emmenlau** [comment]
Hi! Well I can not even compile, this is the problem. Against which proto file should I compile? Java does not compile against C++ proto, and C++ does not compile against Java proto. I can not make an API with different function definitions, so I'm stuck before the start.

**Comment by ejona86** [comment]
The differences in the proto files are mostly cosmetic. In your own service you can ensure that you use the same proto file, but the proto file differences really shouldn't be a problem; just leave the proto files as-is in each repo and it should work. If you try to change the proto files to match then yes, it will not compile because the class names will have changed.

I completely agree that having the proto files match would be a Good Thing™, but it shouldn't impede your current goal: trying out the hello world. Improving the protos can happen after we've gotten you running.

**Comment by emmenlau** [comment]
I understand you say the examples are different but compatible. But this really breaks what I want to do. I need an example with *one* proto file that defines the API functionality, and a server and client I can compile against this proto file. Even if it works what you suggest, what would it help? Eventually I need to make the changes to get the two examples in sync, and this is what breaks functionality for me. Been there, done that. Now I would need an example that shows how to get the two in sync, because I seem to be unable to get it done :-(

**Comment by emmenlau** [comment]
BTW, I think this is what most people need from interop, so I think fixing the example would not be in vain. And with 0.11 I tried getting Java and C++ in sync and failed for several hours. Maybe stupid mistake by me, or maybe broken? I guess you can do it in 5 min, can you please try?

**Comment by carl-mastrangelo** [comment]
@emmenlau what are you trying to do?  The two proto files are API compatible, so the only way I could imagine something going wrong is with generating Java stubs from the C++ example proto, or C++ stubs from the java one.  The examples are intentionally simple, and specific to the language.  It would be confusing to have java options in the grpc repo when no java stubs will be generated from them.  Likewise, it would also be confusing to have Objective C options in the grpc-java repo, since we aren't making objective C stubs.  It isn't wrong per-se, but it inhibits understanding.  

Is there a particular reason you are keen on having exactly one proto file?

**Comment by emmenlau** [comment]
Hi @carl-mastrangelo. I understand you want to keep examples simple. But in the helloworld example in Java, rpc SayHello (HelloRequest) returns (HelloResponse), in C++ it returns (HelloReply). Why?

**Comment by ejona86** [comment]
I've created #1061 for syncing helloworld.proto.

**Comment by carl-mastrangelo** [comment]
An unfortunate piece of history?  Here is a more important question: does it matter?  The examples do work.  I have always viewed the examples directory as specific to the language, and the interop tests specific to the protocol.  If you want a piece of code showing interoperation between languages, why not use the one we designed and continuously test, as Eric mentioned above?  It's here https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/proto/io/grpc/testing/integration/messages.proto


In a production system, yes, it's good to have just one proto file, but here it needs to be as easy to understand as possible for getting into the language.

**Comment by emmenlau** [comment]
But this is *exactly* my point! For me, it is not easy to understand! The proto files have different names, different return values, different internal definitions between languages. Its not useful for someone that wants to develop interop. I see it is easy for you, but believe its not easy for me. How do I merge them?

**Comment by emmenlau** [comment]
Could you make one helloworld-example that works out of the box interop, in a way how one would program correctly and cleanly with grpc (so with a *single* proto file)?

**Comment by carl-mastrangelo** [comment]
I think your misunderstanding is with the intent of these directories.  hello world needs to be the simplest possible working thing, which does in fact work with itself. 

 You are trying to do something more complicated, and upset that it doesn't work.  Could you please detail what it is exactly that you are trying to do?  If you don't tell us, it's going to be hard for us to see a problem.

**Comment by emmenlau** [comment]
But in what way is it easier to understand the functionality of interoperability based on the helloworld-examples you propose, compared to one that would be consistent in the function signatures? You seem unhappy about my proposal to synchronize them. I am confused as to why the inconsistency is preferable? Can you elaborate where my misunderstanding might be? I was understanding that helloworld-examples should be as easy to comprehend as possible, which in this case seems obstructed.

**Comment by ejona86** [comment]
I just merged in #1382 which syncs the biggest change, HelloResponse vs HelloReply, as well as some smaller bits. It should be possible to use Java's helloworld.proto now in C++ and it work. I'm leaving #1061 open until I sync the java-specific options to grpc/grpc or I get rid of them or it's deemed unnecessary.

**Comment by emmenlau** [comment]
Thanks a lot @ejona86 , I will test it right away!

**Comment by emmenlau** [comment]
Thanks a lot for your work @ejona86 ! Its working for me now! Awesome!

**Comment by ejona86** [comment]
@emmenlau, glad to hear it!
