### ISSUE TITLE
KonigKontext - A globally shared, request scoped, context for JVM based gRPC microservices

### ISSUE THREAD

**Issue by reidbuzby** [grpc/grpc-java#10612]
This is not a feature request, but instead a plug for a new library I've created. 

I've recently created an open source library on top of grpc-java that allows you to propagate a context across microservice boundaries throughout an entire request lifetime. The existing [io.grpc.Context](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html) only propagates a context across API boundaries within the same container and does not cross microservice boundaries.

It's called KonigKontext, check it out here: https://github.com/konigsoftware/konig-kontext!

Example use cases include:

Propagating security principals, or user credentials and identifiers throughout an entire request lifetime across all of your microservices.
Propogating distributed tracing information. Set a request trace id upon receiving a request and later access that id in any downstream microservice.
However, Konig Kontext is built to support any type of context value, so it can be extended to fit any specific use cases as well.

Let me know what you think!

**Comment by ejona86** [comment]
Makes sense. The keys are still explicitly propagated (the client/server interceptor is explicitly passed the key). Looks like your Keys are essentially a Marshaller+Context.Key. So it changes the boilerplate for that use-case.

I don't know how many people will notice it here. You might mention it on the mailing list. https://groups.google.com/g/grpc-io
