### ISSUE TITLE
RetryPolicy for RPC messages?

### ISSUE THREAD

**Issue by jchau207** [grpc/grpc-java#10613]
I tried to enable retry with retryPolicy for my non-stream call, but can't seem to get it to work. I went into the `ManagedChannelImpl` code and seems like the only place where retry with retryPolicy is considered is inside `ClientStream`. 

my proto have this definition:
```
service Signature {
    rpc signBuyApiURL (SignBuyApiURLRequest) returns (SignBuyApiURLResponse);
}

message SignBuyApiURLRequest {
    string url = 1;
}

message SignBuyApiURLResponse {
    oneof response {
        string signature = 1;
        ResponseError error = 2;
    }
}
```

Is there a way to get retryPolicy apply to these calls? If so, can you point me the code that handles the retry logic, so i can further debug why it is not working for me? 

Thank you

**Comment by sanjaypujare** [comment]
Did you take a look at the retrying example at https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/retrying  especially the part about retrying serviceConfig?

**Comment by jchau207** [comment]
> Did you take a look at the retrying example at https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/retrying especially the part about retrying serviceConfig?

Yes, I based my implementation on that example.  If it is my own configuration issue, I would like to debug it but I cannot find the place in `ManagedChannelImpl` that manages the retry mechanism for non stream calls. Would be great if you could point me to the function or module for that.

**Comment by sanjaypujare** [comment]
The code is at https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L526 . It might refer to things like clientStream or retriableStream but the code also applies to pure unary calls. A unary call still involves a request stream and a response stream (with a single message).

**Comment by jchau207** [comment]
Thank you for the guidance.. i managed to trace down my issue which led me to my follow up question:

I am trying to configure my retrypolicy to retry if the deadline exceeded. From the look at of this code, it would never retry because the deadline would always be subsequently exceeded? 

If my analysis is true, Is there a way to achieve my intention and retry if deadline gets exceeded?

**Comment by sanjaypujare** [comment]
> ...
> If my analysis is true, Is there a way to achieve my intention and retry if deadline gets exceeded?

As you can see here https://github.com/grpc/proposal/blob/master/A6-client-retries.md#maximum-number-of-retries "gRPC's call deadline applies across all attempts for a given RPC". And `DEADLINE_EXCEEDED` is only generated at the client side after all retry attempts. So I don't understand what it means or what the point is in "retrying if deadline is exceeded". Unless in your particular situation your server side code generating `DEADLINE_EXCEEDED` status code and you want to make that as one of the `retryableStatusCodes` in the [retry service config](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#retry-policy-capabilities).

**Comment by jchau207** [comment]
> Unless in your particular situation your server side code generating `DEADLINE_EXCEEDED` status code and you want to make that as one of the `retryableStatusCodes` in the [retry service config](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#retry-policy-capabilities).

That is correct, I would like `DEADLINE_EXCEEDED` to be a retryableStatusCode.

Our client is a mobile android device. From what we can see in our error logs, deadline exceeded happens frequently even with-wait-for-ready and setting the deadline to a generous number (> 10s) . It would make sense for us to retry if the grpc request 'times out'.

**Comment by sanjaypujare** [comment]
> deadline exceeded happens frequently even with-wait-for-ready and setting the deadline to a generous number (> 10s)

So there are no retries and the deadline is exceeded with a single attempt, is it? Do you then want a deadline-per-attempt and a deadline-per-call? If you are seeing frequent deadline-exceeded errors, have you looked into network connectivity or server issues? How will retry help in such cases?

**Comment by jchau207** [comment]
> > deadline exceeded happens frequently even with-wait-for-ready and setting the deadline to a generous number (> 10s)
> 
> So there are no retries and the deadline is exceeded with a single attempt, is it? Do you then want a deadline-per-attempt and a deadline-per-call? If you are seeing frequent deadline-exceeded errors, have you looked into network connectivity or server issues? How will retry help in such cases?


Assuming Deadline per attempt means we want a seperate deadline per retry attempt, then yes, that is what I am looking for. 

We have a lot of Instances where we simply don't get any error response until Deadline is hit, regardless how long we set the deadline but subsequent calls would succeed, either grpc is in a confused state, thinking it is ready but it isn',t, or the request gets dropped somewhere on the way. Having retry will increase the likelihood we can get a proper response over the number for max retry attempts.

Network connectivity is always a concern for mobile clients. We have users from Nigeria that gets high latency and high packet loss and OEMs which has overly aggressive power management that basically turns off app's permission to use internet on minimize.

**Comment by sanjaypujare** [comment]
Couple of comments:

- it will be good to solve the underlying network or server issues instead of just using the retry mechanism to improve reliability. "grpc in a confused state" or "request gets dropped somewhere" are vague descriptions but it will be good to troubleshoot and pinpoint the actual problem
- We will need to have stronger justification or use-cases to add support for per-attempt deadline.

**Comment by ejona86** [comment]
> which could be caused by server/client timeouts

It makes no sense to retry if you are saying the timeout is the problem. It would be better to just wait longer. If the server is broken and won't ever return, then do whatever you need to improve the reliability within the datacenter; don't make the client in a bad network resend it.

> dropped request over network

We suggest keepalive to monitor connection health.

It sounds like you might prefer hedging, which uses the same retry subsystem but doesn't cancel the old request and then sees which finishes first. We wouldn't normally encourage that for mobile, but it sounds like hedging is very similar to what you are asking for (and the ways it is different are better than your suggestion).

**Comment by jchau207** [comment]
> It makes no sense to retry if you are saying the timeout is the problem. It would be better to just wait longer. If the server is broken and won't ever return, then do whatever you need to improve the reliability within the datacenter; don't make the client in a bad network resend it.

The questionable thing I have here is: Retry Policy allows capture of "UNAVAILABLE" error code for retry - Which is exactly an indication of "Server is broken and won't ever return" but doesn't allow capture of deadline exceeded which could be a caused by factors beyond just "server is broken". Top candidates are poor network connection between Client and Server, mobile network stability (switching between carriers), mobile OEM power settings (Dropping/re-establishing connection permission on app suspension) and with countries with poor network infrastructure. Some of these causes could be corrected by a simple retry. 

> We suggest keepalive to monitor connection health.

This is another challenge. From our experience keepalives is also a difficult to configure when your users are on mobile. A low keepalive is fine when the user is in a good network infrastructure environment, but  unusable for people in Nigera or users who are on satellite connections, because the "pings" can exceed over 800ms-1000ms, which causes keepalives to be constantly missed.  High keepalives on the other hand, doesn't allow the application to quickly detect when the connection is dropped, when the user are on the move and go through a small tunnel or switching carriers.

> It sounds like you might prefer hedging, which uses the same retry subsystem but doesn't cancel the old request and then sees which finishes first. We wouldn't normally encourage that for mobile, but it sounds like hedging is very similar to what you are asking for (and the ways it is different are better than your suggestion).

I will give this a try, and happy to try out any other suggestions. We have invested a lot of time of effort to make GRPC usable for our mobile client but there are times when it feels like mobile client usecases weren't high priority in GRPC's design.

**Comment by ejona86** [comment]
> Top candidates are poor network connection between Client and Server, mobile network stability (switching between carriers), mobile OEM power settings (Dropping/re-establishing connection permission on app suspension) and with countries with poor network infrastructure.

None of these are per-RPC; they should be handled at the connection-level. And the solution to these is "wait longer" and detect a breakage via keepalive.

> because the "pings" can exceed over 800ms-1000ms, which causes keepalives to be constantly missed.

By default we wait 20 seconds, so it sounds like you have reduced the timeout to something very small.

> High keepalives on the other hand, doesn't allow the application to quickly detect when the connection is dropped, when the user are on the move and go through a small tunnel or switching carriers.

A small tunnel is a "wait longer" case; the connection probably hasn't dropped. I'd hope that switching carriers is noticed in the kernel and it kills the connection. But if not, that doesn't seem to happen continually and a typical conservative keepalive to deal with it as a long-tail seems fine.

**Comment by ejona86** [comment]
> We have invested a lot of time of effort to make GRPC usable for our mobile client but there are times when it feels like mobile client usecases weren't high priority in GRPC's design.

If you are super-serious, I'd recommend HTTP/3 using Cronet. But you'd need to roll out support for HTTP/3 to whatever reverse proxy you use. QUIC's ability to do the equivalent of multipath TCP can be helpful in some of the cases you mention. I'm disappointed multipath TCP rollout has been slow. Note that gRPC is "hands off" when using Cronet, as gRPC sees no connections.

**Comment by ejona86** [comment]
Seems like this is resolved as best as we'd expect. There doesn't seem to be a need to change retries, and hedging is available if you want to be more aggressive. If very interested in performance no poor networks, Cronet should be used. If you end up having specific connectivity trouble with a solution, feel free to open a new issue. If you have trouble using something mentioned here, comment, and this can be reopened.
