### ISSUE TITLE
Issues with proto class naming, and service naming, in grpc-java

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc-java#1062]
I have two problems (or difficulties) when using the helloworld.proto from grpc examples.
(1) The proto-file is named helloworld (lowercase) and contains "package helloworld;" (also lowercase). But the derived grpc java class file is called "Helloworld.java" (first letter uppercase). This breaks my build instructions. In grpc-cpp the file stays lowercase. Why is grpc-java changing the name?
(2) The bigger problem comes from the name of the service rpc method. helloworld.proto advertises the service "rpc SayHello (HelloRequest) returns (HelloReply) {}", note the camel-case! In grpc-cpp the method consistently has the same name. But in grpc-java in HelloWorldServer.java, the method suddenly changes its name to sayHello (note the lowercase first letter). This is quite inconsistent and confusing. Could this be changed? Why is grpc-java meddeling with the casing?

To generate the java code, I'm using latest protobuf 3.0.0-beta-1:
```
/thirdparty/bin/protoc -I="/tmp/Proto" --java_out="/tmp/ProtoGenJava" --java_plugin_out="/tmp/ProtoGenJava" --plugin="protoc-gen-java_plugin=/thirdparty/bin/protoc-gen-grpc-java" "/tmp/Proto/helloworld.proto"

**Comment by carl-mastrangelo** [comment]
These are standard naming conventions.  Proto converts to idiomatic names of the target language.

**Comment by ejona86** [comment]
Yeah, Protobuf already does this sort of thing in Java, and gRPC follows suit. For example, fields are commonly named like `my_field`, and protobuf will have setters and getters be of the style `setMyField()`.

Note, that gRPC doesn't generate a file name Helloworld.java; that is protobuf. All of gRPC-generated files have a "Grpc" suffix and are based on the service name. So for the helloworld example, the gRPC-specific piece is GreeterGrpc.java. Any other files are protobuf, not grpc.

**Comment by emmenlau** [comment]
Thanks for the quick reply, I understand! I will redirect the issue to the protobuf project.
