### ISSUE TITLE
gRPC xDS client stops working after a period of inactivity

### ISSUE THREAD

**Issue by rdesgroppes** [grpc/grpc-java#10632]
- #9632 was unfortunately closed with a [comment](https://github.com/grpc/grpc-java/issues/9632#issuecomment-1317446356) that:
> This seems like a go-control-plane bug to me. [...]

A close issue of gRPC on Node.js received a more favorable followup:
- https://github.com/grpc/grpc-node/issues/2579
- https://github.com/grpc/grpc-node/pull/2580

May I ask what it would take to address it on the gRPC-Java side as well?

**Comment by sergiitk** [comment]
Looking at the grpc-node issue, it has nothing to do with go-control-plane specifically, but fixes a bug that broke restarting LDS watch after channel goes IDLE. This was a regression that only affected the 1.9.0 release.

https://github.com/grpc/grpc-java/issues/9632 is about go-control-plane apparently not returning resources after grpc-java XdsClient goes IDLE and then restarting resource watches after waking up.

**Comment by sergiitk** [comment]
Looking at the grpc-node issue, it has nothing to do with go-control-plane specifically, but fixes a bug that broke restarting LDS watch after channel goes IDLE. This was a regression that only affected the 1.9.0 release.

https://github.com/grpc/grpc-java/issues/9632 is about go-control-plane apparently not returning resources after grpc-java XdsClient goes IDLE and then restarting resource watches after waking up.

**Comment by ejona86** [comment]
It seems the grpc-node fix just makes it behave more correctly/similarly to how grpc-java already behaves. There doesn't seem to be anything to do here. If #9632 is still an issue, then you could make sure an issue is open against go-control-plane.

**Comment by murgatroid99** [comment]
To be clear, the bug in grpc-node was that the client was not *requesting* the resources again after the IDLE timeout. That is a completely different problem than the one in the linked grpc-java issue; they just have similar symptoms and occur in a similar situation.

**Comment by larry-safran** [comment]
As has been specified, what grpc-java is doing at this point is correct and the resolution needs to be with the go-control-plane.  It is understandable how the grpc-node situation made it look like something that should be handled in grpc, but that was a red herring.
Please contact the go-control-plane and encourage them to match the spec.
