### ISSUE TITLE
memory leak in 1.58.0 when retry is open

### ISSUE THREAD

**Issue by spiritlcx** [grpc/grpc-java#10637]
### What version of gRPC-Java are you using?
gRPC version: 1.58.0, retry is open

### What is your environment?

Alibaba Cloud Linux 3.2104
Azul Zulu Prime 23.02.302.0

### What did you expect to see?
When client sends HEADERS request, the server should return HEADERS response immediately, but not delay the response until there is data to send

### What did you see instead?
The server won't return HEADERS response until there is data to send
If the client cannot receive HEADERS response, it cannot release BufferEntry, causing memory leak

### Steps to reproduce the bug
[code.zip](https://github.com/grpc/grpc-java/files/13211093/code.zip)

**Comment by sergiitk** [comment]
unpacked code.zip: https://gist.github.com/sergiitk/a4b58a2fb958191638750b408b1ad421

**Comment by ejona86** [comment]
> the server should return HEADERS response immediately, but not delay the response until there is data to send

That doesn't sound right. The [retry gRFC explicitly says to do the opposite](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#when-retries-are-valid):

> gRPC servers should delay the Response-Headers until the first response message or until the application code chooses to send headers.

> If the client cannot receive HEADERS response, it cannot release BufferEntry, causing memory leak

There is no memory leak, because BufferEntry is bound to the call. If the call exits (e.g., DEADLINE_EXCEEDED) then the memory is freed.

**Comment by spiritlcx** [comment]
> retry gRFC explicitly says to do the opposite

Got it. Thanks very much.

**Comment by spiritlcx** [comment]
Hi,

We use Bidirectional Streaming. Client will send data to server, but server may not send data to client. Should we avoid using retry=true in this case?

**Comment by ejona86** [comment]
What sort of behavior do you want? It's hard to provide any recommendations without knowing what the protocol and objectives are.

You can disable retries. You can adjust `perRpcBufferLimit()` to cap the amount buffered. You can maybe have the server respond with headers sooner.

**Comment by sergiitk** [comment]
Seems like this is resolved as best we can. If there's something more we can help with, comment, and it can be reopened.

**Comment by spiritlcx** [comment]
Thanks very much for the advice. Sorry that I forgot to reply.
