### ISSUE TITLE
Mapping lists of same tpye doesn't work with mapstruct

### ISSUE THREAD

**Issue by aoguzperdahci** [grpc/grpc-java#10642]
### Is your feature request related to a problem?
Yes. The problem is caused by the builder method naming convention in the jar file that created. As you know, the repeated fields in the proto file take "List" suffix at the end of the getter method. But the adder methods doesn't have this suffix. Because of this naming convention mapstruct cannot map the classes if there are more than one lists of the same type (if there is only one list of the same type, it can be match by the type). 

We can look with some sample codes:
![image](https://github.com/grpc/grpc-java/assets/86795767/cf3f87e6-2fae-49f1-9fcc-c97fd1e93592)
Using this proto file I compiled a jar. And the jar contains following codes.
![image](https://github.com/grpc/grpc-java/assets/86795767/fb990019-f30c-43c7-b5b5-6d0c74152e4b)
![image](https://github.com/grpc/grpc-java/assets/86795767/5aa9c199-2805-4305-96bb-3ba2cdd15741)
(Also, same methods for items2List and samplesList)

Then I created this java class:
![image](https://github.com/grpc/grpc-java/assets/86795767/d60ce8c9-4dec-4e9b-92f0-75f4087d3c55)

Now, when I try to map HelloRequestInboundDto to ExternalProto.HelloRequest as the following:
![image](https://github.com/grpc/grpc-java/assets/86795767/f28dab3d-f32d-4d2c-a0cd-b449e406a783)

The generated code:
![image](https://github.com/grpc/grpc-java/assets/86795767/4fd22b3f-0637-4859-aa0f-f577c00bb761)

The problem here is this. Because of the naming convention of grpc-java builder methods adder methods of the fields doesn't match (fields have "List" suffix like items1List, items2List, samplesList but the adder methods doesn't have List suffix like addItems1, addItems2, addSamples and they don't match). When add methods and the fields don't match it tries to get the list and add all items to that list. But this mapping throws exception because getter method of the list returns unmodifiableList and when it tries to add items to that list it throws UnsupportedOperationException. Notice the samplesList mapping is what is suppose to be (it uses adder method of the class not getter) because there is only one kind of adder method that accepts Sample type.

### Describe the solution you'd like
To solve that problem the first thing comes to mind add "List" suffix to add method names. This way field names and the adder method names match and there would be no problem. For example, the filed name is items1List, getter method is already named getItems1List so we can change addItems1 to addItems1List. I copied the jar contents and made this change and it works.

### Describe alternatives you've considered
Also, there is another alternative. If you wouldn't want to change existing method names, this solves the problem too. It's about setter methods. Currently, builder methods only have setter for single item in the list. 
Example:
![image](https://github.com/grpc/grpc-java/assets/86795767/6958d7e2-8ba6-4db4-9532-da487b85258a)

But also there could be setter for the whole list in the builder. Since builder methods only used in the creation of the object, it would totally be okay to have such method. Also, it has to named with "List" suffix.
It could be something like this:
![image](https://github.com/grpc/grpc-java/assets/86795767/cc5c3c2c-fc24-4d33-8418-f133212dc173)

### Additional context
There are issues opened for this in mapstruct but it uses exact match for field name (getter method) and setter or adder method so, I think this issue suppose to be handled here. There is a inconsistency here and "List" suffix could be added adder and setter methods or it could be removed from the getter methods altogether.

**Comment by larry-safran** [comment]
Why didn't you just use `helloresponse1.getSamplesList().add(toSample(samplesList))`?
Note that the objects generated from the Proto file by protoc are maintained by the Proto team, so this can only be handled by them.  https://github.com/protocolbuffers/protobuf
