### ISSUE TITLE
Modifying the Netty HTTP/2 transport pipeline

### ISSUE THREAD

**Issue by jon-signal** [grpc/grpc-java#10649]
Hello! I have a use case where we'd like to tunnel gRPC traffic through an unusual transport, and I'm trying to identify an appropriate place to make that happen. Specifically, we're considering using a WebSocket as a transport for TLS-encrypted HTTP/2 (gRPC) traffic where we'd use binary WebSocket frames to "wrap" TLS packets (or chunks of packets). Please let me acknowledge that this is at least a little gross, and is largely for Science™.

Given full access to the Netty `ChannelInitializer`, I would implement our weird transport by adding some WebSocket handlers "below" the `SslHandler` in the pipeline. I don't see a way to do that through any public interface right now, though (but as discussed in https://github.com/netty/netty/discussions/13687, we may be able to use a feature coming in Netty 4.1.101 to modify the pipeline). I'm wondering if there are other "approved" ways of achieving a similar effect, though. I've taken a look at the proxy detection system, but I don't think that would do quite what we need since the server channel would also need to know how to handle WebSocket frames.

In the absolutely worst case, I recognize that I could just fork the entire Netty HTTP/2 transport and customize the pipeline there, and I could also build an entirely new WebSocket transport, but is there a convenient place to do this kind of thing that I'm just overlooking?

Thanks kindly!

**Comment by larry-safran** [comment]
The easiest approach would be to setup a local proxy server between gRPC and WebSocket.  You can use `LocalChannel` to connect your gRPC server to this proxy server.

**Comment by jon-signal** [comment]
> The easiest approach would be to setup a local proxy server between gRPC and WebSocket.

That makes sense.

As a twist, though (and I really should have mentioned this in the original problem statement): can you think of a good way to preserve the original remote address (whether via [`TRANSPORT_ATTR_REMOTE_ADDR`](https://grpc.github.io/grpc-java/javadoc/io/grpc/Grpc.html#TRANSPORT_ATTR_REMOTE_ADDR) or some other mechanism) from gRPC's perspective? We have a number of use cases that call for IP-based rate limiting, and those wouldn't work as expected if the remote address always appeared to be `localhost`.

Again, thank you!

**Comment by ejona86** [comment]
The remote address will be a LocalAddress. That's a string, so the simplest case is "encode the IP address in the client's LocalAddress." If you have enough control to teach the services to accept a non-InetSocketAddress, that'd be enough as-is. You could also use a ServerInterceptor or ServerTransportFilter to rewrite the LocalAddress back into a InetSocketAddress.

Other ideas: write a ForwardingChannel that delegates to LocalChannel, but returns the addresses you want for localAddress() and remoteAddress(). That has plenty of boilerplate, but probably few lines that "do anything." A discarded option was to use InternalNettyChannelCredentials to implement this as a handshaker. That is very similar to the ChannelInitializer approach, but is very internal. For people doing that sort of thing, it is generally best for the code to live in our repo. For an experiment, that would be a good approach; but bad to depend on.

**Comment by jon-signal** [comment]
This is all extremely helpful. Thank you both!

I'm confident that we can figure things out from here, and will mark this as "closed." If we bump into something surprising or helpful for future readers (beyond what's already been shared here), I'll follow up with additional comments.

**Comment by jon-signal** [comment]
Following up: we've built a prototype and this is all working as hoped. Thanks again!
