### ISSUE TITLE
What's the compatibility between 1.2x and 1.4x?

### ISSUE THREAD

**Issue by gangxie112** [grpc/grpc-java#10645]
Hello,
Recently, we want to upgrade our grpc java from 1.2x to 1.4x. Went through the change logs, it seems that there is no breaking change. But still worried about the compatibility because we could not test it fully. Any one did such upgrade and what's the compatibility?

Thanks.

**Comment by ejona86** [comment]
For stable APIs, they should be 100% compatible. Code using stable APIs from grpc 1.0 should still be working. There is two years of development between, and Hyrum's Law can always come into play. If you successfully recompiled, then there were probably no changes to experimental APIs that impacted you.

If you already ran a basic flow through your app and it seemed to work, I'd assume you are fine.

**Comment by larry-safran** [comment]
Note that we make very strong efforts to keep not only API stability, but also ABI and functional stability.  Many libraries are not overly diligent about this (so your concern is reasonable), but grpc is not one of those.  We even run extensive integration tests for each of the last 10 versions both as client and server and across languages.

Note that the current version is v1.59.0 and with the security fixes it includes I would strongly recommend you upgrade to that.
