### ISSUE TITLE
What to use instead of InternalNotifyOnServerBuild notifyOnBuild ()

### ISSUE THREAD

**Issue by chenwenlong-java** [grpc/grpc-java#10668]
I upgraded from 1.29.0 to 1.59.0 and found InternalNotifyOnServerBuild had been deleted
But I can't find a way to replace it in the 1.59.0, what should I do?

**Comment by ejona86** [comment]
Are you using InternalNotifyOnServerBuild or were you using code that used it?

If you were using it directly, there is no replacement. It had internal in its name to be very clear it wasn't for your use. It was also really broken and incompatible with interceptors. It was removed in v1.30.0, almost 3.5 years ago.

If you were using something that used it (server reflection), try upgrading to a newer version of that component; all usages of it have been removed for quite a while.

**Comment by chenwenlong-java** [comment]
Thanks for the reply, I used the InternalNotifyOnBuild#notifyOnBuild function for notifications, we decided to do away with this function in the new version
