### ISSUE TITLE
Is there a way to go from method descripts to get the request and response types from a service method?

### ISSUE THREAD

**Issue by mattmueller-stripe** [grpc/grpc-java#10666]
Hi there,

Given the following `.proto`:

```proto
message ListServicesRequest {
   // ...
}

message ListServicesResponse {
  // ...
}

service MyService {
  rpc ListServices (ListServicesRequest) returns (ListServicesResponse);
}
```

I was wondering if there's a way to traverse to the `ListServicesRequest` and `ListServicesResponse` from the method descriptors in Java? I'm able to access the methods, but would like to be able to traverse the input and output types.

Thanks!

**Comment by ejona86** [comment]
There's two approaches, which are pretty similar if you are just wanting schema information:
1. `MethodDescriptor.getSchemaDescriptor()`, which returns `ProtoMethodDescriptorSupplier` for protobuf services. It has a method that returns _Protobuf's_ MethodDescriptor which then has `getInputType()` and `getOutputType()`
2. `MethodDescriptor.getRequestMarshaller()` and `getResponseMarshaller()` return instances that implement `PrototypeMarshaller` and `ReflectableMarshaller` for protobuf. `PrototypeMarshaller.getMessagePrototype()` returns the default instance of that particular type (a `Message` in protobuf). You're then free to call `getDescriptorForType()` if you want the protobuf schema information.

For others that may be interested, `ServiceDescriptor.getSchemaDescriptor()` behaves similarly and returns Protobuf's ServiceDescriptor.

**Comment by mattmueller-stripe** [comment]
We were able to get 1. working. Thanks so much for your help!!
