### ISSUE TITLE
Behaviour change in io.grpc.stub.ClientCalls.blockingServerStreamingCall between 1.56 and 1.59

### ISSUE THREAD

**Issue by juliuszsompolski** [grpc/grpc-java#10697]
### What version of gRPC-Java are you using?

Upgrading 1.56.0 to 1.59.0 in https://github.com/apache/spark/pull/43942/files#diff-6f545c33f2fcc975200bf208c900a600a593ce6b170180f81e2f93b3efb6cb3eR94

### What is your environment?

Ubuntu Linux, scala 2.13, JDK 17.

### What did you expect to see?

When calling a server side streaming call on a client blocking stub, the behaviour with 1.56 was that the call would not actually be send to the server until first `.hasNext()` was called.

### What did you see instead?

Now with 1.59 the request seems to be sent as soon as the server side streaming call is called on the stub.

### Steps to reproduce the bug

In 1.59: https://github.com/juliuszsompolski/apache-spark/commit/4cd744a075a58578bd94eee8cebeaf27aceb22ab
```
val iter = client.executePlan(request) // this already sends a request to the server.
```

In 1.56: https://github.com/juliuszsompolski/apache-spark/commit/1a9ed2eddcbb57bb00f996a35fbeef61720881d6
Edit: this actually happened only during the first call, so maybe the channel was not yet initialized yet before the first request, while in 1.59 the channel gets initialized? 
```
val iter1 = client.executePlan(request1)
iter1.hasNext() // only this triggered the request to be sent to server in 1.56
val iter2 = client.executePlan(request2) // but this sends the request to the server.
```

**Comment by juliuszsompolski** [comment]
Question: does this mean that now calling the server side streaming call can throw an error, or will the error be buffered and only thrown upon the first `next()` or `hasNext()`.

Error handling in Apache Spark Spark Connect project depended on the assumption that the errors are only thrown from the `next` / `hasNext` of the iterator, and not from creating the iterator.
I am still investigating if it also had assumptions on the request being lazy (not being sent to server until first `next` / `hasNext`).

Is there a setting that can revert this behaviour change?

**Comment by ejona86** [comment]
https://github.com/grpc/grpc-java/pull/10496 may be related.

**Comment by larry-safran** [comment]
It looks like the new behavior is more appropriate and correct.  Are you just trying to understand what is going on or is there something that you would like us to do in regard to this?

**Comment by HyukjinKwon** [comment]
If this behaviour is considered as a more appropriate and correct:
- Python side should have the same behaviour as well. Python side does not make a request when the streaming call is open (via generator)
- The behaviour would have better be documented officially.

**Comment by juliuszsompolski** [comment]
@larry-safran agreed that the new behavior seems more appropriate and correct. In fact, the old behavior has bitten me in the past (it actually took me some debugging in the past to understand that my server-streaming RPC were not being actually sent from the client until I opened the iterator). But as @HyukjinKwon wrote, it seems that this should be a documented and tested behavior, that should also be consistent across different implementations of GRPC.

**Comment by larry-safran** [comment]
Release notes fro v1.58.0 have been updated to include this behavior change.  Please feel free to file an issue with Python if you would like them to change their behavior.
