### ISSUE TITLE
io.grpc.StatusRuntimeException: INTERNAL: Failed to deserialize response message: Codec(WireError(Utf8Error) )

### ISSUE THREAD

**Issue by LXingio** [grpc/grpc-java#10696]

**Comment by temawi** [comment]
It would be very hard to help with this without additional information. Can you share what your client code looks like when reading the response? Also, how does the server write the response? A full stack trace is also important here.

**Comment by sergiitk** [comment]
Seems we've done as much as we can for now. Once you have more info or questions, comment, and this can be reopened.
