### ISSUE TITLE
okhttp backend not working on Android

### ISSUE THREAD

**Issue by NyCodeGHG** [grpc/grpc-java#10719]
Hi,
I'm currently trying to make [maestro](https://github.com/mobile-dev-inc/maestro) on Android API Level 23.
maestro starts a gRPC server on the Android Device, currently using the netty backend.
This doesn't work on API 23 and I've found out that the netty backend is not supported on Android at all.
I tried switching to the okhttp backend instead (as suggested [here]()) but this gives me the following exception:

```
11:23:15.605  W  Error decoding HTTP/2 frames
                 java.io.EOFException
                 	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
                 	at okio.RealBufferedSource.readByteString(RealBufferedSource.kt:215)
                 	at io.grpc.okhttp.internal.framed.Http2$Reader.readConnectionPreface(Http2.java:111)
                 	at io.grpc.okhttp.OkHttpServerTransport$FrameHandler.run(OkHttpServerTransport.java:569)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                 	at java.lang.Thread.run(Thread.java:818)
```

This is the code I use to start the server
```kotlin
OkHttpServerBuilder.forPort(7001, InsecureServerCredentials.create())
    .addService(Service(uiDevice, uiAutomation))
    .build()
    .start()
```

The client is also created with okhttp like this:
```kotlin
private val channel = OkHttpChannelBuilder.forAddress("localhost", hostPort)
        .usePlaintext()
        .build()
private val blockingStub = MaestroDriverGrpc.newBlockingStub(channel)
```

I also tested this on a more recent Android version (API 33) but it also fails there.
I also tried bundling Conscrypt as mentionend [here](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-on-android), but that also didn't help.

**Comment by ejona86** [comment]
> This doesn't work on API 23 and I've found out that the netty backend is not supported on Android at all.

For curiosity, what broke with Netty in API 23?

> I tried switching to the okhttp backend instead (as suggested [here](https://github.com/grpc/grpc-java/issues/10719))

Yeah, you should use grpc-okhttp. Although the 'here' link is the wrong one (it points to this issue).

> but this gives me the following exception:

When does it give you that exception? It looks like that is just in the server log. That could happen if something other than gRPC contacted that port. What happens on the client-side?

Conscrypt doesn't matter if using plaintext/insecure.

**Comment by ejona86** [comment]
Seems we've done as much as we can for now. Once you have more info or questions, comment, and this can be reopened.
