### ISSUE TITLE
TLS certificate rotation / updating TLS certificates at runtime

### ISSUE THREAD

**Issue by lolski** [grpc/grpc-java#10737]
We'd like to be able to rotate the TLS certificate of a gRPC/Java service at runtime to facilitate certificate refresh without having to restart the gRPC server instance.

It looks like it can be achieved in Python with [dynamic_ssl_server_credentials](https://grpc.github.io/grpc/python/grpc.html#grpc.dynamic_ssl_server_credentials), and in C++ with TlsCredentialsOptions's [watch_identity_key_cert_pairs(...)](https://grpc.github.io/grpc/cpp/classgrpc_1_1experimental_1_1_tls_credentials_options.html) method.

Is there a way to achieve it in gRPC Java?

**Comment by ejona86** [comment]
[`AdvancedTlsX509KeyManager`](https://grpc.github.io/grpc-java/javadoc/io/grpc/util/AdvancedTlsX509KeyManager.html) passed to [`TlsChannelCredentials`](https://grpc.github.io/grpc-java/javadoc/io/grpc/TlsChannelCredentials.Builder.html#keyManager(javax.net.ssl.KeyManager...)).

**Comment by lolski** [comment]
Got it, much thanks.
