### ISSUE TITLE
Should maxOutboundMessageSize be applied to compressed message bytes, as well as uncompressed message bytes?

### ISSUE THREAD

**Issue by jroper** [grpc/grpc-java#10738]
In theory, if I have a receiver that has `maxInboundMessageSize` set to 4MB, and a sender that has `maxOutboundMessageSize` set to 4MB, the sender should always fail fast, and the receiver should never fail due to the inbound message exceeding it's receive size.

However, this isn't true, in cases where compression is used. Compression does not always result in smaller payloads, compression can increase the size of a payload, particularly when compressing random data. Since the `MessageFramer` does not currently check the actual length of the payload against `maxOutboundMessageSize`, a sender that is configured to mirror a receivers max sending size can still send a message that is too large for the receiver to receive, which would be quite surprising behaviour for anyone that encountered it.

Although the likelihood of this happening is low, I think for correctness sake, and because it would be trivial to introduce the check, the payload should also be checked against `maxOutboundMessageSize`, in addition to the uncompressed message data.

**Comment by ejona86** [comment]
`maxOutboundMessageSize` is essentially a hack to _dynamically_ limit the max message size the server sees (and it is on client-side because we have no dynamic configuration on server-side). Configuring it the same to `maxInboundMessageSize` doesn't serve much purpose.

We could add the compressed check, but the difference in size isn't enough to really matter for the purposes of `maxOutboundMessageSize`.

**Comment by jroper** [comment]
Understood. But please take a look at this #10739. Firstly, it fixes a bug where the resource exhausted `StatusRuntimeException` is lost, wrapped in another `StatusRuntimeException` with `Unknown` as the status code. That bug needs to be fixed. The other thing the PR does is moves the message length check from `writeUncompressed` to `writeBufferChain`. The result is that the same message length check is done for compressed and uncompressed payloads when creating the message frame, plus the existing message length check done "prior to" (though it's actually done after by looking at the number of bytes written) compression is still done for compressed messages.

**Comment by YifeiZhuang** [comment]
fixed by https://github.com/grpc/grpc-java/pull/10739
