### ISSUE TITLE
Upgrading to 1.60.0 throws an exception

### ISSUE THREAD

**Issue by kelhelawy** [grpc/grpc-java#10736]
### What version of gRPC-Java are you using?
1.60.0
### What is your environment?
Mac, OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

### What did you expect to see?
That things work, as it was working in 1.59.1
### What did you see instead?
```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@1f99cef8
java.lang.AbstractMethodError: Receiver class io.grpc.netty.shaded.io.grpc.netty.NettyServerStream$Sink does not define or inherit an implementation of the resolved method 'abstract void writeHeaders(io.grpc.Metadata)' of interface io.grpc.internal.AbstractServerStream$Sink.
	at io.grpc.internal.AbstractServerStream.writeHeaders(AbstractServerStream.java:103)
	at io.grpc.internal.ServerCallImpl.sendHeadersInternal(ServerCallImpl.java:145)
	at io.grpc.internal.ServerCallImpl.sendHeaders(ServerCallImpl.java:104)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:377)
....etc
```
I have the following dependencies:
```
<dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <scope>test</scope>
        </dependency>
```
I also tried to add `annotations-api` but didnt work.
This is how I start the server:
```
return ServerBuilder
                .forPort(grpcPort)
                .addService(new AuthImpl(headerKey, headerValue))   # my service
                .directExecutor()
                .build()
                .start();
```

**Comment by toddbaert** [comment]
I'm seeing `java.lang.NoSuchMethodError: io.grpc.NameResolverRegistry.getProviderForScheme`, but it also completely breaks `1.60` for us.

**Comment by ejona86** [comment]
You probably have a grpc-netty-shaded dependency that is pre-1.60. Run `mvn dependency:tree` to find where the old version is coming from, and then probably add an explicit dependency to the newer version in your project. Alternatively, you can use grpc-bom.

**Comment by larry-safran** [comment]
@toddbaert please let us know if this resolved the problem.

**Comment by kelhelawy** [comment]
Thanks @ejona86 ... As you suspected, There was another dependency having grpc-protobuf with an older version, using the bom fixed the issue.

**Comment by toddbaert** [comment]
> @toddbaert please let us know if this resolved the problem.

@larry-safran yep, as I said in [my edit](https://github.com/grpc/grpc-java/issues/10736#issuecomment-1847550469) last week, my problem was indeed mismatched dependencies.
