### ISSUE TITLE
How to set Http2 MultiplexingLimit to 1 over io.grpc.Grpc channel?

### ISSUE THREAD

**Issue by HemanthAnakapalle123** [grpc/grpc-java#10778]
Hi All,

Do we have an option available over io.grpc.Grpc to set Http2 MultiplexingLimit?

**I want to set setHttp2MultiplexingLimit=1**, to have only 1 stream per Connection.

For example, In the case of WebSockets, we have the option - https://vertx.io/docs/apidocs/io/vertx/ext/web/client/WebClientOptions.html#setHttp2MultiplexingLimit-int-

I'm looking for a way to set the same over io.grpc.Grpc channel.

NOTE: Implementation is in Java.

Thanks,
Hemanth

**Comment by YifeiZhuang** [comment]
[NettyServerBuilder.maxConcurrentCallsPerConnection](
https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#maxConcurrentCallsPerConnection(int)).

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
