### ISSUE TITLE
Avoid gRPC message exceeds maximum size error

### ISSUE THREAD

**Issue by noamisachar** [grpc/grpc-java#10775]
I'm using gRPC to send messages from Java to a Python service. Recently I started getting larger messages that sometimes exceed the maximum message size for gRPC. Increasing that size is not possible for me due to lack of resources and timeouts, so I had to implement a chunking mechanism in order to split the large messages.

In Java, I check the message size using getSerializedSize() and if it exceeds the maximum size, I do the chunking. However, I noticed that the value I'm getting from getSerializedSize() is different and much smaller than the one shown in the error "gRPC message exceeds maximum size" which means that I still send messages that exhaust the resources.

For example, how is it possible that getSerializedSize() returns 75274 and the error shows a size of 179651? Both are supposed to show the size in bytes. I also tried getting the size using the length of the byte array, but it is identical to getSerializedSize().

How can I know the actual size gRPC will get before sending the message so I can apply the chunking when I should?

**Comment by YifeiZhuang** [comment]
Could you share detailed logs?

I did an experiment and verified `message.getSerializedSize()` from client request equals the server side received message size. (Java client to Java server)

```
diff --git a/core/src/main/java/io/grpc/internal/MessageDeframer.java b/core/src/main/java/io/grpc/internal/MessageDeframer.java
index c8b250c21..19db2e59d 100644
--- a/core/src/main/java/io/grpc/internal/MessageDeframer.java
+++ b/core/src/main/java/io/grpc/internal/MessageDeframer.java
@@ -29,6 +29,8 @@ import java.io.FilterInputStream;
 import java.io.IOException;
 import java.io.InputStream;
 import java.util.Locale;
+import java.util.logging.Level;
+import java.util.logging.Logger;
 import java.util.zip.DataFormatException;
 import javax.annotation.Nullable;
 import javax.annotation.concurrent.NotThreadSafe;
@@ -41,6 +43,7 @@ import javax.annotation.concurrent.NotThreadSafe;
  */
 @NotThreadSafe
 public class MessageDeframer implements Closeable, Deframer {
+  private static final Logger log = Logger.getLogger(MessageDeframer.class.getName());
   private static final int HEADER_LENGTH = 5;
   private static final int COMPRESSED_FLAG_MASK = 1;
   private static final int RESERVED_MASK = 0xFE;
@@ -385,6 +388,7 @@ public class MessageDeframer implements Closeable, Deframer {

     // Update the required length to include the length of the frame.
     requiredLength = nextFrame.readInt();
+    log.log(Level.INFO, "message header size :" + requiredLength);
     if (requiredLength < 0 || requiredLength > maxInboundMessageSize) {
       throw Status.RESOURCE_EXHAUSTED.withDescription(
           String.format(Locale.US, "gRPC message exceeds maximum size %d: %d",
diff --git a/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java b/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
index 75d9f0369..efa375ba6 100644
--- a/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
+++ b/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java
@@ -504,6 +504,7 @@ public abstract class AbstractInteropTest {
         .setPayload(Payload.newBuilder()
             .setBody(ByteString.copyFrom(new byte[314159])))
         .build();
+    logger.log(Level.INFO, "sending message size" + request.getSerializedSize());

     assertResponse(goldenResponse, blockingStub.unaryCall(request));
```

client log:
```
Running test large_unary
Dec 20, 2023 2:06:29 PM io.grpc.testing.integration.AbstractInteropTest largeUnary
INFO: sending message size271840
```

Server log:
```
Dec 20, 2023 2:12:54 PM io.grpc.internal.MessageDeframer processHeader
INFO: message header size :271840
```

**Comment by noamisachar** [comment]
I don't have specific logs than point at an issue, but the experiment I did was to reduce the max message size to a really low value in order to trigger a Status.RESOURCE_EXHAUSTED. Then I compared the value I have using getSerializedSize() with the value that the Status.RESOURCE_EXHAUSTED shows, and found them to be different. Because of that I can't check if a message exceeds the maximum size before sending it.

**Comment by YifeiZhuang** [comment]
Which gRPC versions are you using? Could you share the client code where you use gRPC, and the server log when it triggers exception `Status.RESOURCE_EXHAUSTED`?  What is your max message size configuration? 
My experiment on master show client message `getSerializedSize()` and the size server sees are the same. So I believe more info is needed find the problem.

**Comment by noamisachar** [comment]
I use versions 1.60.1 in Java and 1.60.0 in Python.
Right after the size check using `getSerializedSize()` I send it to this function that handles the call:
```
private static <InputType, ResultType> ResultType call(
            Function<InputType, ResultType> method
        ,   InputType input
        ,   String forecastPyMethodName
    ) {
        ResultType result = null;
        try {
            result = blockingUnaryCall(getChannel(), METHOD_COMPUTE_TIME_SERIES_CORRELATION_MATRIX, getCallOptions(), request);
        } catch (StatusRuntimeException e) {
            handleGrpcException(e);
        }
        return result;
    }
```

I tried different sizes but the problem happened on 8 MB. I don't have updated logs but in short, the size was lower than 8 MB when I check using `getSerializedSize()` but then I got `Status.RESOURCE_EXHAUSTED: gRPC message exceeds maximum size` with a size different than what I logged before sending the input.

**Comment by noamisachar** [comment]
Hi @YifeiZhuang, is it possible that because of one of these properties I will experience the issues? 
```
grpc.client.enable-keep-alive=true
grpc.client.keep-alive-without-calls=true
grpc.client.negotiation-type=plaintext
```

**Comment by ejona86** [comment]
Keepalive and plaintext can't impact the message size. It seems likely to be an issue in your code. Since it seems `getSerializedSize()` is only available on the built messages, the only ideas  I have is you have an interceptor or channel that messes with the message or that you are passing the message between threads without proper synchronization. That is, other than the obvious "checking the size of the wrong message."

**Comment by YifeiZhuang** [comment]
Closed because there is no response. If you have more information, you can reopen the issue.

**Comment by larry-safran** [comment]
The size of headers must be added to the message size.  Base64 encoding the binary headers will give an accurate size to add to the message size.
