### ISSUE TITLE
The load balancing is ineffective at the beginning of the gRPC request

### ISSUE THREAD

**Issue by gnimnaid** [grpc/grpc-java#10777]
At the initial stage of executing gRPC requests, due to the immediate update of the corresponding picker for each connection upon readiness, this may result in traffic not aligning with expectations. I would like to achieve a similar effect to routing traffic to specific server nodes in a hash-like manner. Is there any way to implement this?

The issue is similar to: "https://github.com/grpc/grpc-java/issues/9936"

**Comment by YifeiZhuang** [comment]
> routing traffic to specific server nodes in a hash-like manner

Is [ring-hash](https://github.com/grpc/proposal/blob/master/A42-xds-ring-hash-lb-policy.md) (xds only), or [session-affinity](https://github.com/grpc/proposal/blob/master/A60-xds-stateful-session-affinity-weighted-clusters.md) (c++ only, youtube introduction available at https://youtu.be/eFkmz1arT5U) close to you need?

Note that the initial behaviour of the LB policy regarding #9936 is a separate topic from we discuss here.

**Comment by gnimnaid** [comment]
> > routing traffic to specific server nodes in a hash-like manner
> 
> Is [ring-hash](https://github.com/grpc/proposal/blob/master/A42-xds-ring-hash-lb-policy.md) (xds only), or [session-affinity](https://github.com/grpc/proposal/blob/master/A60-xds-stateful-session-affinity-weighted-clusters.md) (c++ only, youtube introduction available at https://youtu.be/eFkmz1arT5U) close to you need?
> 
> Note that the initial behaviour of the LB policy regarding #9936 is a separate topic from we discuss here.

Thank you for your response. It's different in my case. I am implementing a custom load balancer based on RoundRobinLoadBalancer. The issue is that when I initialize a subchannel and invoke its start method, if it becomes ready, a GrpcSubChannelPicker is immediately generated to provide the connection. However, this GrpcSubChannelPicker only contains one Ready subchannel. I want to wait until all subchannels are ready before selecting a specific subchannel I desire for routing.

**Comment by YifeiZhuang** [comment]
I see. None of the existing builtin LB policy will do the behaviour as you described. Builtin LB normally immediately start using any ready subchannels. You probably need to delay updating the, e.g. [helper](https://github.com/grpc/grpc-java/blob/master/util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java#L90).

However, any load balancing algorithm, like RR, only works after a period of time when the requests distributes themselves among the backends. So I am curious about the use case where you want the requests to strictly do RR or request routing.

**Comment by gnimnaid** [comment]
> I see. None of the existing builtin LB policy will do the behaviour as you described. Builtin LB normally immediately start using any ready subchannels. You probably need to delay updating the, e.g. [helper](https://github.com/grpc/grpc-java/blob/master/util/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java#L90).
> 
> However, any load balancing algorithm, like RR, only works after a period of time when the requests distributes themselves among the backends. So I am curious about the use case where you want the requests to strictly do RR or request routing.


When dealing with multiple concurrent versions or in a gray release scenario, it is crucial to route traffic strictly to the corresponding service instances. Since all versions of our service are registered in the same environment in the service registry, precise identification of the appropriate instance is required during load balancing. 

I've addressed this issue in a particular way by ensuring that each load balancer corresponds to a single GrpcSubChannelPicker instance. Even after the channel becomes ready, only this specific GrpcSubChannelPicker instance persists, but it updates the internal list of SubChannels. When the initial pickSubchannel is invoked, it sleeps for a period to allow for the complete update of the SubChannel list. However, I acknowledge that this approach may not be considered elegant.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

While the solution could be improved, I think the longer-term solution there is to implement round_robin yourself using a utility. (We have the beginnings of a utility, but it is still changing, so shouldn't be used yet.) We're doing that independent of this issue.
