### ISSUE TITLE
about grpc streaming 

### ISSUE THREAD

**Issue by flying-2077** [grpc/grpc-java#10783]
Can grpc replace client-side streaming or server-side streaming  with bidirectional streaming ? I mean to say，from a functional standpoint，grpc only need to maintain bidirectional streaming.

**Comment by YifeiZhuang** [comment]
Yes, your understanding is correct.
All types of RPCs are bidi streaming in its core. At stub layer there are convenience logic to make client-side or server-side streaming.
We recorded related video see: https://www.youtube.com/watch?v=E3ez34fdC0k&t=12s (starting 3:09 is more relevant)

**Comment by flying-2077** [comment]
Glad to hear that! Thank you.

**Comment by sergiitk** [comment]
We're happy to help! Feel free to re-open if needed.
