### ISSUE TITLE
grpc-binder: How to get the caller's process id on the server?

### ISSUE THREAD

**Issue by CCint3** [grpc/grpc-java#10782]
On the server side, the caller's uid can be obtained in the following ways.

```java
Attributes attributes = call.getAttributes();
Integer uid = attributes.get(BinderTransport.REMOTE_UID);
```

So how to get the caller's process id? Will grpc-binder consider adding `REMOTE_PID` of `Attributes.Key`?

https://github.com/grpc/grpc-java/blob/f67ec2ecd9c79e34c6fb989091dcf8862480e54d/binder/src/main/java/io/grpc/binder/internal/BinderTransport.java#L114C6-L114C6

**Comment by jdcormie** [comment]
No because unfortunately Android doesn't make the remote PID available to us. See https://developer.android.com/reference/android/os/Binder#getCallingPid() "Warning: oneway transactions do not receive PID." The binder transport is built completely on oneway transactions by design.

**Comment by gedanayaranh** [comment]
> No because unfortunately Android doesn't make the remote PID available to us. See https://developer.android.com/reference/android/os/Binder#getCallingPid() "Warning: oneway transactions do not receive PID." The binder transport is built completely on oneway transactions by design.

very thanks your answer.
