### ISSUE TITLE
_java_grpc_library rule: '@@bazel_tools//tools/jdk:toolchain_type' does not have mandatory providers: 'TemplateVariableInfo'

### ISSUE THREAD

**Issue by vorburger** [grpc/grpc-java#10787]
> in toolchains attribute of _java_grpc_library rule //core/lib:core_java_grpc: '@@bazel_tools//tools/jdk:toolchain_type' does not have mandatory providers: 'TemplateVariableInfo'. Since this rule was created by the macro 'java_grpc_library', the error might have been caused by the macro implementation

### What version of gRPC-Java are you using?

I'm not 100% sure, but I'll post a draft PR which reproduces this problem.

### What is your environment?

Bazel 7.0.0 on Linux with Java 17.0.9 compiling for Java 11.

### What did you expect to see?

A working green build when upgrading the Bazel Version from 6.4.0 to 7.0.0.

### What did you see instead?

```bash
$ bazelisk build --verbose_failures //...
ERROR: /home/vorburger/git/github.com/vorburger/enola/core/lib/BUILD:87:18: in toolchains attribute of _java_grpc_library rule //core/lib:core_java_grpc: '@@bazel_tools//tools/jdk:toolchain_type' does not have mandatory providers: 'TemplateVariableInfo'. Since this rule was created by the macro 'java_grpc_library', the error might have been caused by the macro implementation
ERROR: /home/vorburger/git/github.com/vorburger/enola/core/lib/BUILD:87:18: Analysis of target '//core/lib:core_java_grpc' failed
ERROR: /home/vorburger/git/github.com/vorburger/enola/common/common/BUILD:30:11: Expanding template 

common/common/src/test/java/dev/enola/common/io/resource/ErrorResourceTest failed: : Could not evaluate substitution for File:[[<execution_root>]bazel-out/k8-fastbuild/bin]common/common/src/test/java/dev/enola/common/io/resource/ErrorResourceTest.jar: null

ERROR: Analysis of target '//cli:enola' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.231s, Critical Path: 0.02s
INFO: 6 processes: 6 internal.
ERROR: Build did NOT complete successfully
```

The 2nd error may well be completely unrelated to the first error, which this bug is about.

https://github.com/bazelbuild/bazel/issues/18970 seems to be the "cause" of this, and `grpc-java` may need a fix?

### Steps to reproduce the bug

See https://github.com/enola-dev/enola/pull/390

Check that out and run the command above and it should be reproducible.

**Comment by vorburger** [comment]
> What version of gRPC-Java are you using? I'm not 100% sure,

https://github.com/enola-dev/enola/pull/390 now (not originally) uses (hopefully) current `grpc-java` 1.60.1.

The Update of gRPC from 1.54.1 to 1.60.1 seems to also cause other problems (in my project), but at least this proves (I think) that this problem (above) isn't something that only affects `grpc-java` 1.54.1 but also 1.60.1.

**Comment by larry-safran** [comment]
We currently do not support Bazel 7.  However, we would very much appreciate a contribution that would allow both bazel 6 and bazel 7 to function correctly.

**Comment by dgnemo** [comment]
FYI: I was able to successfully use `grpc-java` in Bazel 7 with this configuration:

`WORKSPACE`
```
...
http_archive(
    name = "io_grpc_grpc_java",
    patches = [
        "//patches:grpc_java.patch",
    ],
    sha256 = "be779db38a72a0c693706c433133189538b04979eba1b728eaa21f4fd0f967d8",
    strip_prefix = "grpc-java-1.55.1",
    urls = ["https://github.com/grpc/grpc-java/archive/v1.55.1.tar.gz"],
)
...
```

`//patches:grpc_java.patch`
```
--- java_grpc_library.bzl
+++ java_grpc_library.bzl
@@ -136,1 +136,2 @@
-    implementation = _java_rpc_library_impl,
+    implementation = _java_rpc_library_impl,
+    toolchains = ['@@bazel_tools//tools/jdk:toolchain_type'],
```

I did not try other versions of `grpc-java`, because our repo has several other deps that require 1.55

**Comment by ejona86** [comment]
grpc-java itself builds fine with Bazel 7, so I thought we had some level of Bazel 7 compatibility. What is different about your build vs ours? 9ab35b05de0709c0547e38bb0f2d3805dd5618e2 is related; you can see the TODOs that could only happen after dropping Bazel 5 (which recently happened in 55a9c012c3b27c704d0f5503bb39040df031becd).

**Comment by vorburger** [comment]
Hint to future readers, the following is solved by putting an (empty, duh!) `BUILD` file into the directory with the `*.patch`: 

```
Error in patch: Unable to load package for //tools/patches:grpc_java.patch: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/vorburger/git/github.com/enola-dev/enola/tools/patches
 ```

Unfortunately with the gRPC 1.60.1 that I use in my project, the workaround as-is above causes:

    ERROR: /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/io_grpc_grpc_java/java_grpc_library.bzl:148:5: duplicate keyword argument: toolchains

Comparing [this](https://github.com/grpc/grpc-java/blob/c9b905f071f9a9de6bc39c1495faac8275cbde71/java_grpc_library.bzl#L136) with [that](https://github.com/grpc/grpc-java/blob/cd7ae8b61443fab5a0a737a6e78250669056d2e1/java_grpc_library.bzl#L140), I at first attempted to making `//patches:grpc_java.patch` like this instead (for gRPC 1.60.1 instead of 1.55.1):

```patch
--- java_grpc_library.bzl
+++ java_grpc_library.bzl
@@ -140,1 +140,1 @@
-    toolchains = ["@bazel_tools//tools/jdk:toolchain_type"],
+    toolchains = ['@@bazel_tools//tools/jdk:toolchain_type'],
```

However that doesn't help, and cause the exact same error that I have initially reported.

Which isn't very surprising - this patch just adds an extra `@@` instead of the `@` which is already there in 1.60.1 (but wasn't in 1.55.1 yet), but it looks that (the extra 2nd `@`) isn't actually really required for this; Bazel seems smart enough - note that in the error that I have initially reported it was always already using `@@`.

> FYI: I was able to successfully use grpc-java in Bazel 7 with this configuration:

@dgnemo that's cool, for you on 1.55.1, but... I think this may have nothing to do with the error which I originally reported here for 1.60.1?

> [sergiitk](https://github.com/sergiitk) changed the title in toolchains attribute of _java_grpc_library rule //core/lib:core_java_grpc: '@@bazel_tools//tools/jdk:toolchain_type' does not have mandatory providers: 'TemplateVariableInfo'. Since this rule was created by the macro 'java_grpc_library', the error might have been caused by the macro implementation Bazel 7.0 support

@sergiitk your change of issue title from the specific error message to a generic "Bazel 7.0 support" may be partially contributing to the confusion here?

> What is different about your build vs ours? 

I dunno!

> https://github.com/grpc/grpc-java/commit/9ab35b05de0709c0547e38bb0f2d3805dd5618e2 is related you can see the TODOs that could only happen after dropping Bazel 5 (which recently happened in https://github.com/grpc/grpc-java/commit/55a9c012c3b27c704d0f5503bb39040df031becd).

@ejona86 so...  I'm afraid I don't fully understand what exactly that means... how exactly would I (quote, to try to do [this](https://github.com/grpc/grpc-java/blob/9ab35b05de0709c0547e38bb0f2d3805dd5618e2/java_grpc_library.bzl#L97)) _"add 'toolchain = None' inside the action"_ ? I did briefly try to patch it like this:

```patch
--- java_grpc_library.bzl
+++ java_grpc_library.bzl
@@ -103,1 +103,2 @@
-        use_default_shell_env = True,
+        use_default_shell_env = True,
+        toolchain = None
```

But that didn't seem to help, and still produced the errors originally reported above. (But I'm likely misunderstanding what were getting at with your comment; what exactly is going on here is still out of my Bazel Foo.) If you have a better clue and want to push an (even un-merged) possible diff that I can use (via `http_archive`), I'm happy to try to see if it fixes this problem.

> We currently do not support Bazel 7. However, we would very much appreciate a contribution that would allow both bazel 6 and bazel 7 to function correctly.

@larry-safran if only I knew how to do this... 🤣 (I do no.t)

**Comment by vorburger** [comment]
@ejona86 I've retried without adding (removing) that, and it indeed seems to do the trick and avoids this problem! Thank You so much.

I swear 🤣 originally I ran into that https://github.com/bazelbuild/bazel/issues/18970 and that's why I had it at first.

However with https://github.com/enola-dev/enola/pull/390 as of right now, at 
[`ec355b2`](https://github.com/enola-dev/enola/commit/ec355b20111ef5a62c294134670d748d8d3a9610), I'm back to seeing https://github.com/grpc/grpc-java/issues/10576...
