### ISSUE TITLE
Add protection against attacks using malicious protobuf messages.

### ISSUE THREAD

**Issue by mfronczyk** [grpc/grpc-java#1080]
It'd be good to to be able to specify the maximum message size on wire that the server tries to parse in order to protect from OOM errors.

**Comment by nmittler** [comment]
We already support this: https://github.com/grpc/grpc-java/blob/538cf215f070aeaeac89c9bd6b404fe9b97fbb8a/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L163

**Comment by nmittler** [comment]
Server-side: https://github.com/grpc/grpc-java/blob/f6582d822dffc6bc29bf5743578fb6ccd4c6cb29/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L204
