### ISSUE TITLE
too many pojo object at android 

### ISSUE THREAD

**Issue by louie-wh** [grpc/grpc-java#10814]
Grpc  produce too many POJO object at android and lead to GC every second.
So can POJO object using object pool 。
this is a similar question : https://stackoverflow.com/questions/25138361/pooling-protobuf-pojos

**Comment by ejona86** [comment]
This doesn't seem like a gRPC concern, but instead a protobuf one. There is no object reuse available. Make sure you are using [protobuf lite](https://github.com/protocolbuffers/protobuf/blob/main/java/lite.md) though (a.k.a., "javalite"). It has been optimized for reduced object creation, and affords better optimizations with tools like Proguard.

**Comment by larry-safran** [comment]
Hi @louie-wh, I am assuming that using protobuf lite answered your issue.  If that is not accurate, please feel free to reopen it with further clarifications.
