### ISSUE TITLE
NettyClientStream does not handle netty write data failure promise

### ISSUE THREAD

**Issue by DreamLettuce** [grpc/grpc-java#10849]
### What version of gRPC-Java are you using?
1.26.0 (latest version has the same problem)

### What is your environment?

linux, jdk8

### What did you expect to see?
grpc client throw a exception when netty write data frame failed

### What did you see instead?
grpc client blocking stub hangs forever when netty StreamBufferingEncoder return an unexpected failure promise

### Steps to reproduce the bug
when the client http2 stream id is exhausted(using Integer.MAX_VALUE), netty codec-http2 [StreamBufferingEncoder#writeData](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/StreamBufferingEncoder.java#L209) return a failure promise unexpectly , more details in https://github.com/netty/netty/issues/13805
but grpc [NettyClientStream](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientStream.java#L188)  does not report the failure future, and the grpc blocking stub will block forever.

**Comment by sergiitk** [comment]
Thank you for reporting this! Seems like an interesting case. I'm planning to take care of the issue in NettyClientStream.writeFrameInternal, and check for any other places this issue may affect.

**Comment by ejona86** [comment]
If the stream ids are exhausted, then sending the headers should have failed, and we [do have error handling for that](https://github.com/grpc/grpc-java/blob/b3475a0e4625d518434f7d89eae7965a44a427cf/netty/src/main/java/io/grpc/netty/NettyClientStream.java#L148C29-L148C44). So something else must have been going on in addition (like the headers code in netty didn't properly check for negative IDs).

**Comment by DreamLettuce** [comment]
yeah, the root cause is a netty bug, but i think it is better for grpc to handle this failure case at the same time, we should not suppose that netty never failure when sending data.
