### ISSUE TITLE
OUTBOUND GO_AWAY from client side?

### ISSUE THREAD

**Issue by oraz-cisco** [grpc/grpc-java#10846]
Hi Experts!
We are facing grpc streams getting closed unexpectedly between our client and server. While debugging through the logs, we see that log which is strange:

2024-01-23 18:49:59,858 [grpc-default-worker-ELG-1-18] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x8abef3f7, L:/169.254.128.234:38708 - R:92.79.216.235/92.79.216.235:30649] OUTBOUND GO_AWAY: lastStreamId=2147483647 errorCode=2 length=48 bytes=7265637641646472657373282e2e29206661696c65643a20436f6e6e656374696f6e2072657365742062792070656572

This is the client side... and it is sending a OUTBOUND GO_AWAY? how can that be? does client send GO_AWAY? any info about such behaviour?

Thanks

**Comment by temawi** [comment]
I believe this is expected behavior - the client is acknowledging to the server that it has received the GO_AWAY from it.

@ejona86 correct me if I'm wrong here.

**Comment by ejona86** [comment]
Clients can send GOAWAY. That GOAWAY is not an acknowledgement.

Decoding the hex shows the message:

> recvAddress(..) failed: Connection reset by peer

So the connection was closed by the server. That could be semi-normal in special circumstances, but:

> lastStreamId=2147483647

That is the maximum stream id. So this HTTP/2 connection _needs_ to be replaced with another.

This could potentially be normal stuff and working in an okay way. Or maybe there's a logic error when nearing the max stream id. Are you seeing any RPC failures? What made you look into this?

**Comment by oraz-cisco** [comment]
Thank you for the comments.
We've actually found out that we had duplicate data-ip in the cluster (k8s cluster) and we suspect it caused the issue.
Probably client side created new stream when there was one already, hence server side closed the old one. And that occurred very often. Once the duplicate ip fixed, then the issue was never seen. (before every 20-30 min, and since duplicate ip fixed its more than 10 days with no issue...)
Thanks!

**Comment by ddiger** [comment]
Hi, @oraz-cisco can you please explain more detail how you could find the duplicated ip in the k8s cluster and solve this issue? I have experiencing grpc error with exactly same log with your case from client side. My environment also using k8s cluster (client - lb - istio ingress gateway - sever)

**Comment by oraz-cisco** [comment]
You can use the “kubectl describe nodes” command and verify there are no dup ips (physical or data or internal)
