### ISSUE TITLE
Valid GRPC retries 

### ISSUE THREAD

**Issue by mrueda020** [grpc/grpc-java#10844]
Hi GRPC java team

I have a question on how retry works , I read on the design that to be retry valid the call has not to been committed 
https://github.com/grpc/proposal/blob/master/A6-client-retries.md#when-retries-are-valid
so in my current impletation when my server is down intentionally my grpc call get is retried but in this test I expect that the call is not being made again since it has complete previously.
So going back to the valid retries topic how can I make that my call is committed I check that the clients needs to receive headers for that but  it is not clear how to achieve that.
So anyone could help with some examples on how to make my call committed?

**Comment by larry-safran** [comment]
If you don't want your call to be sent to the server then you can cancel it.

**Comment by mrueda020** [comment]
Is it possible to cancel a retry call? If so,
 do you have an example for it?
Thanks in advance

**Comment by larry-safran** [comment]
This seems to have been addressed.  If not, please add a comment and we can reopen it.
