### ISSUE TITLE
grpc and protobuf version for m2 mac

### ISSUE THREAD

**Issue by AkashKamal** [grpc/grpc-java#10856]
Trying to run a grpc project in mac m2
I am using grpc-netty, grpc-protobuf, grpc-stub - 1.61.0
These are my plugin artifacts
<protocArtifact>
  com.google.protobuf:protoc:3.25.1:exe:${os.detected.classifier}                    
</protocArtifact>
<pluginId>grpc-java</pluginId>
<pluginArtifact>
io.grpc:protoc-gen-grpc-java:1.61.0:exe:${os.detected.classifier}
</pluginArtifact>

While generating the proto classes I am facing issue

@io.grpc.stub.annotations.GrpcGenerated 
In the above code I am facing GrpcGenerated can not be resolved. Any help?

**Comment by YifeiZhuang** [comment]
Not clear what your use case is. Are you using annotation `@ GrpcGenerated ` in your code? Then no no no, it is for grpc internal use only.  See javadoc [GrpcGenerated](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/annotations/GrpcGenerated.html)
> This annotation is used by the gRPC stub compiler to annotate outer classes. Users should not annotate their own classes with this annotation. Not all stubs may have this annotation, so consumers should not assume that it is present.

**Comment by ejona86** [comment]
Seems like you may be using Maven. Maven is probably downgrading `grpc-stub` to an older version. I suggest enabling Maven Enforcer's `requireUpperBoundDeps` (see our examples for an example) and seeing if it notices any unintentional downgrades.

**Comment by ejona86** [comment]
Seems like this should be resolved. If not, comment, and it can be reopened.
