### ISSUE TITLE
Circular dependencies between modules

### ISSUE THREAD

**Issue by slandelle** [grpc/grpc-java#10857]
### What version of gRPC-Java are you using?

1.61.0

### What is your environment?

Unrelated

### What did you expect to see?

Clean design with no circular dependencies between modules.

### What did you see instead?

* grpc-core depends on grpc-util at runtime 
* grpc-util depends on grpc-core at runtime

### Steps to reproduce the bug

Check published poms on maven central:
* https://central.sonatype.com/artifact/io.grpc/grpc-core
* https://central.sonatype.com/artifact/io.grpc/grpc-util

**Comment by ejona86** [comment]
This is not a true circular dependency, but some ecosystem tools can't handle it. Is this one of the Bazel (#10576) or Gradle (#10701) issues?

**Comment by ejona86** [comment]
Independent of whether it was Bazel or Gradle, #10919 should address this.
