### ISSUE TITLE
If you use port 11001 for the SpringBoot gRPC server in the MacOS M2 environment, gRPC communication will not be available.

### ISSUE THREAD

**Issue by K-Diger** [grpc/grpc-java#10852]
### What version of gRPC-Java are you using?

1.16.0

### What is your environment?

MacOS (M2), JDK 17 ZULU, Spring Boot 3.2.1

### What did you expect to see?

If you use port 11001 for the SpringBoot gRPC server in the MacOS M2 environment, gRPC communication will not be available.

### Steps to reproduce the bug

If 11001 is used as the gRPC Server port for one microservice and another microservice client calls this server, the following error occurs.

```text
RPC failed: Status{code=INTERNAL, description=http2 exception, cause=io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
```

**Comment by temawi** [comment]
The error message does not seem related to the server port in any way. Can you confirm that if you **only** change the port to something else it starts working?

**Comment by K-Diger** [comment]
> The error message does not seem related to the server port in any way. Can you confirm that if you **only** change the port to something else it starts working?

Yes, I have confirmed that it only works by changing the port number. Were there any similar cases? Or is port 11001 an overlapping port in my environment

**Comment by temawi** [comment]
One option is also that the server is not receiving proper HTTP2 traffic. Here are a couple of cases with this error where HTTP1 traffic was being used:

- https://stackoverflow.com/questions/73331402/grpc-client-http2exception-first-received-frame-was-not-settings-hex-dump-fo
- https://github.com/grpc/grpc-java/issues/2905

**Comment by ejona86** [comment]
Doesn't seem like we can help any more without additional feedback.
