### ISSUE TITLE
What is intent withDeadlineAfter method in Stub ?

### ISSUE THREAD

**Issue by sangyongchoi** [grpc/grpc-java#10850]
Hi, i has curious intent that withDeadlineAfter method in stub.
I thought this code would apply to deadlineAfter every stub method call.
```kotlin
HelloServiceGrpc.newBlockingStub(channel)
            .withDeadlineAfter(
                deadLineMillis,
                TimeUnit.MILLISECONDS,
            )
```
But it wasn't really the case.
It was like a deadline for the stub itself.
example.
10:00 create stub (with deadline 1hour)
11:01 helloStub.hello method call -> occur error!!

Is this the intention of withDeadlineAfter method in stub ?

**Comment by kitkars** [comment]
You are supposed to use this deadline when you invoke the RPC. If you create the stub with deadline, then this behavior should be expected. You can not make any RPC beyond the deadline.

**Comment by YifeiZhuang** [comment]
Deadline on the stub is the expected intention, see javadoc [withDeadlineAfter](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withDeadlineAfter(long,java.util.concurrent.TimeUnit))

> Returns a new stub with a deadline that is after the given duration from now.

Closing for now. If you have further questions, feel free to reopen.
