### ISSUE TITLE
LB Shutdown Log Level

### ISSUE THREAD

**Issue by Akaame** [grpc/grpc-java#10865]
https://github.com/grpc/grpc-java/blob/20abea47bc5e1b406187f01de839bc1208571696/util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java#L300

Should the level for the log `INFO`? We have recently moved to a newer version of gRPC and observed these log being printed here and there? On our end we opted for a Log Level `ERROR` for anything under `io.grpc`, was wondering if this should be converted to a `DEBUG` log?

Thanks in advance.

**Comment by louie-wh** [comment]
m

**Comment by temawi** [comment]
@larry-safran This log statement does seem too spammy, would e.g. the FINER level be more appropriate?
