### ISSUE TITLE
interop-test, core: retryTest is flaky

### ISSUE THREAD

**Issue by YifeiZhuang** [grpc/grpc-java#10873]
```
> Task :grpc-interop-testing:test

io.grpc.testing.integration.RetryTest > statsRecorded FAILED
    java.lang.NullPointerException
        at io.grpc.testing.integration.RetryTest.assertRpcStatusRecorded(RetryTest.java:248)
        at io.grpc.testing.integration.RetryTest.statsRecorded(RetryTest.java:354)
```

cc. @larry-safran

**Comment by YifeiZhuang** [comment]
Another failure
```
io.grpc.testing.integration.RetryTest > statsRecorde_callCancelledBeforeCommit FAILED
    java.lang.NullPointerException: Measure not found: grpc.io/client/finished_count
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1010)
        at io.grpc.internal.testing.StatsTestUtils$MetricsRecord.getMetricAsLongOrFail(StatsTestUtils.java:103)
        at io.grpc.testing.integration.RetryTest.assertRpcStatusRecorded(RetryTest.java:250)
        at io.grpc.testing.integration.RetryTest.statsRecorde_callCancelledBeforeCommit(RetryTest.java:419)
```

**Comment by larry-safran** [comment]
Are you seeing this on master or other branches?  I created https://github.com/grpc/grpc-java/pull/10858 to try to address this.

**Comment by YifeiZhuang** [comment]
> Are you seeing this on master or other branches? I created #10858 to try to address this.

Both on master.
I am worried if it's related to https://github.com/grpc/grpc-java/pull/10855. I am worried it might fix an issue and reveal another.

**Comment by YifeiZhuang** [comment]
This is on master:
https://github.com/grpc/grpc-java/actions/runs/7745348844/job/21122871515?pr=10876

This is another different failure, also on master:
https://github.com/grpc/grpc-java/actions/runs/7743725552/job/21115786774?pr=10871


```
io.grpc.testing.integration.RetryTest > retryUntilBufferLimitExceeded FAILED
    Wanted but not invoked:
    mockCallListener.onClose(
        <Capturing argument>,
        <any io.grpc.Metadata>
    );
    -> at io.grpc.testing.integration.RetryTest.retryUntilBufferLimitExceeded(RetryTest.java:304)

    However, there were exactly 2 interactions with this mock:
    mockCallListener.onReady();
    -> at io.grpc.PartialForwardingClientCallListener.onReady(PartialForwardingClientCallListener.java:44)

    mockCallListener.onReady();
    -> at io.grpc.PartialForwardingClientCallListener.onReady(PartialForwardingClientCallListener.java:44)
        at app//io.grpc.testing.integration.RetryTest.retryUntilBufferLimitExceeded(RetryTest.java:304)

```

**Comment by larry-safran** [comment]
I suspect that you are right that it uncovered another problem, though it may be just with our test's expectations.  It is annoying that it only seems to show up on the CI tests and not when run locally and one shows up on the `tests (8)` and the other on `tests (11)`

**Comment by YifeiZhuang** [comment]
I have a theory of the root cause. 

The `RetryTest` relies on fakeClock to forward the backoff timer to test retry behaviour. It intercepts the scheduledExecutorService at the transport to schedule its own task, but the real transport receives a no-op task that is executed immediately. 

The fix in #10858 checks whether the retry task can be cancelled, which is the real transport task. In CI, the transport can be slow so sometimes it successfully cancelled the task, while in local environment, it `isCancelled` is always false because the task is mostly already executed. So in CI it may decrement the `inFlightStream` counter, immediately run `closeMasterListener`, but the substream is not closed yet, so we see NPE occasionally.

**Comment by YifeiZhuang** [comment]
I can reproduce the problem locally if I decrement the `inFlightStream` unconditionally.

```
-            if (cancelled) {
-              inFlightSubStreams.decrementAndGet();
-            }
+           inFlightSubStreams.decrementAndGet();

```

And I longer see NPE if I extend the delay on the RetryTest  `eventloop.schedule`

```
--- a/interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
+++ b/interop-testing/src/test/java/io/grpc/testing/integration/RetryTest.java
@@ -137,7 +137,7 @@ public class RetryTest {
             @Override
             public void run() {} // no-op
           },
-          0,
+          1000,
           TimeUnit.NANOSECONDS);
     }
   };
```

**Comment by larry-safran** [comment]
The NPEs are all that the statistics aren't yet present, not that there are inconsistencies in the streams running, but it makes sense to me to change the no-op task to take some small amount of time instead of having it be instantaneous.  I'll add that to PR #10887.

**Comment by larry-safran** [comment]
I had to revert to timeout being 0 as setting it to 1000 caused statsRecorde_callCancelledBeforeCommit to report the missing metric again.
