### ISSUE TITLE
Tidy up Javadoc

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#109]
Need to ensure that Javadoc in the major interfaces and exposed types is of high quality and properly makes of referencing annotations.

Suggest we divide and conquer as follows...

- Channel / Call / Interceptors  @louiscryan
- Transport    @ejona86 
- Stub & Helpers @zhangkun83 
- Builders  @nmittler

**Comment by zhangkun83** [comment]
2nd and 3rd chunks done.

**Comment by nmittler** [comment]
@louiscryan can we close this?

**Comment by louiscryan** [comment]
Yes.
