### ISSUE TITLE
Why `javax.annotation:javax.annotation-api` is being used instead of `jakarta.annotation:jakarta.annotation-api` in the code generation?

### ISSUE THREAD

**Issue by kumsumit** [grpc/grpc-java#10913]
`javax.annotation:javax.annotation-api` has been migrated to `jakarta.annotation:jakarta.annotation-api`.
And it's being updated on `jakarta.annotation:jakarta.annotation-api` destination  only.
But the code generation is still using `javax.annotation:javax.annotation-api`.

Is there specific reason for still using `javax.annotation:javax.annotation-api` ?
If not, I think you should moved to `jakarta.annotation:jakarta.annotation-api`.

**Comment by ejona86** [comment]
`javax.annotation.Generated` used to be part of the JDK. In Java 9 that it was split out. We have no desire to depend on Jakarta and the existing annotation doesn't hurt anything (to our knowledge). For future changes, see #9179.

**Comment by sergiitk** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
