### ISSUE TITLE
Enable tcnative for unit tests in interop-testing; OkHttp should Assume ALPN available

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1092]
That will disable OkHttp tests if you don't have a new enough OpenSSL installed, but Travis will still correctly do the testing.

Depends on #1091

**Comment by ejona86** [comment]
@nmittler, didn't we end up doing this?

**Comment by nmittler** [comment]
@ejona86  Yeah this should already be done .... closing.
