### ISSUE TITLE
com.google.protobuf.RuntimeVersion not found

### ISSUE THREAD

**Issue by SuperMaskv** [grpc/grpc-java#10976]
# Problem
`com.google.protobuf.RuntimeVersion` not found after compiling .proto files to java files.

And I guess that it's a version confliction between protoc and protobuf-java used in grpc-all.

How can I solve this?
# Environment
1. .proto files is in syntax "proto3"
2. using `grpc-all:1.62.2` as project dependencies
3. using `protoc` of version `libprotoc 26.0-rc1`
4. using `protoc-gen-grpc-java` of version `1.62.2-windows-x86_64`

**Comment by YifeiZhuang** [comment]
We called the protoc version in the README.md file for both maven and gradle:
https://github.com/grpc/grpc-java/blob/master/README.md#generated-code

**Comment by oldergod** [comment]
It'd be best to explicitly call that you're not using protoc 4+ though. It's easy to think that you just forgot to update your doc.
