### ISSUE TITLE
grpc-opentelemetry module not published in maven-central

### ISSUE THREAD

**Issue by xvrl** [grpc/grpc-java#10993]
### What version of gRPC-Java are you using?
1.62.2

### What is your environment?
N/A

### What did you expect to see?
I expected to see the grpc-opentelemetry module added as part of https://github.com/grpc/grpc-java/pull/10593
published in maven central/

### What did you see instead?
It doesn't look like there is any io.grpc:grpc-opentelemetry artifact present in maven central.

**Comment by ejona86** [comment]
This is on purpose. It isn't ready yet. More is flowing into it.

**Comment by xvrl** [comment]
thanks for clarifying, any pointers for what's ahead? Even flagged as experimental, this module would still be worthwhile to have.

**Comment by ejona86** [comment]
I don't think it is making the 1.63 release, but I think it will make the 1.64 release.

**Comment by sergiitk** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
