### ISSUE TITLE
Avoid bringing Android-related dependencies when using `grpc-netty-shaded`

### ISSUE THREAD

**Issue by ppatierno** [grpc/grpc-java#11019]
Hello,
I am adding the `grpc-netty-shaded` artifact as dependency to a project.
When running a `mvn dependency:tree`, I can see it's bringing some android-related dependencies while my application won't be targeted for Android:

```shell
[INFO] +- io.grpc:grpc-netty-shaded:jar:1.61.0:runtime
[INFO] |  +- io.grpc:grpc-core:jar:1.61.0:runtime
[INFO] |  |  +- com.google.code.gson:gson:jar:2.10.1:runtime
[INFO] |  |  +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.23:runtime
[INFO] |  |  +- io.grpc:grpc-context:jar:1.61.0:runtime
[INFO] |  |  \- io.grpc:grpc-util:jar:1.61.0:runtime
[INFO] |  +- com.google.guava:guava:jar:32.1.3-android:runtime
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:runtime
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:runtime
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.37.0:runtime
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:2.8:runtime
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.23.0:runtime
[INFO] |  +- io.perfmark:perfmark-api:jar:0.26.0:runtime
[INFO] |  \- io.grpc:grpc-api:jar:1.61.0:runtime
```

As you can see the main ones `com.google.guava:guava:jar:32.1.3-android:runtime` and `com.google.android:annotations:jar:4.1.1.4:runtime`. 
My question is if they are really needed when the application is not targeted for Android. If I could just exclude them at pom level in my application. I noticed there is a `skipAndroid` profile which avoid to build Android related projects for a local build but of course it's unrelated to the above question.
Any suggestions to not bring these dependencies? (unless they are really needed even when Android is not involved at all)

**Comment by ppatierno** [comment]
One more ... the android dependency seems to be used by the `grpc-stub` as well. Again, why this android related stuff is distributed even when not needed? (I mean your application is not running on Android)

**Comment by ppatierno** [comment]
I was wondering why it's not bringing the `32.1.3-jre` version of guava. Of course, I could exclude the `-android` one and adding the `-jre` one as direct dependency in my project to provide it to the grpc jar. But is it really going to work ok then?

**Comment by ejona86** [comment]
For Guava: `-android` is a subset of the `-jre` library. So we are just using the subset. The `-android` version has been a bit more than just "android" a few times over history, like supporting Java 7 longer (it has dropped Java 7 at this point). It is more "the smaller version." "a" sorts before "j" so if you just depend on the `-jre` version it'll be considered a normal library upgrade. There's no problems with using the `-jre` version.

For the various annotations: These are really small, so shouldn't really cause trouble. What issues is it causing for you? If the annotation has [runtime retention](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/annotation/RetentionPolicy.html) then it is better to include the dep, even if most of the time it wouldn't hurt dropping it. Runtime annotations can cause errors when tools use reflection on classes. If the annotation ends up not being used at runtime, then it is never loaded. The android annotation in grpc-core is there to ignore warnings about APIs we know are not available on Android and we have code to avoid.

`skipAndroid` doesn't change the dependencies at all. It just avoids needing to have the Android SDK installed, as it simply doesn't build the android-specific projects.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
