### ISSUE TITLE
Default service config not honored if initial name resolution fails

### ISSUE THREAD

**Issue by temawi** [grpc/grpc-java#11040]
If the name resolution fails we are supposed to rely on the default service config since there is no way to get one via name resolution. This currently only happens if there has been at least one successful name resolution call. If the first name resolution fails, `ManagedChannelImpl` does not apply the service config.

- The default config is applied in [NameResolverListener.onResult()](https://github.com/grpc/grpc-java/blob/f7ee5f3182dddde775069155d17ed93f7270f1ca/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L1749) when a successful response is retried
- In [NameResolutionListener.onError()](https://github.com/grpc/grpc-java/blob/f7ee5f3182dddde775069155d17ed93f7270f1ca/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L1895) we do not apply the default service config.

**Comment by sergiitk** [comment]
Came out of #11042. May be full or partial solution for it.

**Comment by vinodhabib** [comment]
@kannanjgithub added the fix and writing the UT for the fix in progress

**Comment by vinodhabib** [comment]
@kannanjgithub PR raised for the Review, Request you to have a look once.

PR Link - https://github.com/grpc/grpc-java/pull/11368

**Comment by vinodhabib** [comment]
Completed Fix along with UT cases and PR got Approved.

**Comment by vinodhabib** [comment]
Got some more Review points recently from @ejona86 @kannanjgithub working on them.

**Comment by vinodhabib** [comment]
Fixed the recent review points.

**Comment by vinodhabib** [comment]
Fixed the Recent Review point and PR is Ready for Re-review

**Comment by ejona86** [comment]
@vinodhabib, please don't do those PR updates here. Do them on the PR.
