### ISSUE TITLE
OkHttpClientTransport.shutdown() not safe to call if never started.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1108]
If a OkHttpClientTransport is created, and then shutdown without starting, it throws an NPE.  This is surprising behavior because other shutdown methods (such as on ServerImpl) are safe to call shutdown on at any time.

**Comment by madongfly** [comment]
Servers can be shut down by applications, so we don't know when it can be called, but client transport's shutdown is totally under our control, stricter limit is better for exposing bugs.
