### ISSUE TITLE
1.63.0 release notes - jakarta_omit

### ISSUE THREAD

**Issue by panchenko** [grpc/grpc-java#11081]
In the release notes the option is mentioned as `JakartaMode=omit`, but it should be specified as `jakarta_omit`.
https://github.com/grpc/grpc-java/blob/167a2031e29d21710e8790f72a00589fc6333d59/compiler/src/java_plugin/cpp/java_plugin.cpp#L77

**Comment by panchenko** [comment]
Can we change it to 
* generated=javax
* generated=jakarta
* generated=omit
?

**Comment by YifeiZhuang** [comment]
I changed the release note to `jakarta_omit` for a quick fix now.

**Comment by ejona86** [comment]
Let's restrict this issue to just the bad release notes, which are fixed. Discussion about the option name can continue in #11086.
