### ISSUE TITLE
OkHttpClientTransportTest is overly strict in mock verification

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1109]
In the process of adding a test for OkHttpClientTransport, I found that mocked behavior is checked for on every test.  I attempted to add the first test that did not use mocks, but caused the test to fail.  This is because the @ After  annotation in the test does verifications on mocks regardless of the test.

This is a misuse of @ After annotations.  They are not part of the test, but a means to clean up state.  Even if every test does the same verification, it is still not appropriate to put verification code here, because it puts stress on every other test added later on.  Making it hard to add tests is something we do not want.

**Comment by madongfly** [comment]
Is #1110 enough to close this?

**Comment by carl-mastrangelo** [comment]
Yes.   The test cleanliness could still use a lot of work, but I believe this can be closed out.
