### ISSUE TITLE
Enforce coding conventions

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#111]
We have a checkstyle.xml here: https://github.com/grpc/grpc-java/blob/master/checkstyle.xml

This was borrowed from the googleapis java client library (I believe).  We should expand this as needed and enforce the conventions when building.

**Comment by ejona86** [comment]
The current problem with checkstyle is it is a bit too strict as it disallows @link within single-line JavaDoc comment. Its interpretation of at-clauses is different than what I read as at-clauses. I would like to confirm my reading of the style guide and then file a bug on checkstyle if my reading is indeed correct.

https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s7.1.1-javadoc-multi-line
> The single-line form may be substituted when there are no at-clauses present, and the entirety of the Javadoc block (including comment markers) can fit on a single line.

https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s7.1.3-javadoc-at-clauses
> Any of the standard "at-clauses" that are used appear in the order @param, @return, @throws, @deprecated, and these four types never appear with an empty description.

**Comment by nmittler** [comment]
@ejona86 are you referring to our current checkstyle.xml or the checkstyle plugin, itself?

**Comment by ejona86** [comment]
I'm referring to the SingleLineJavadoc module of the latest checkstyle (as can be seen on my branch).

I guess for now we can comment out that module, but I would still like to get it fixed.
