### ISSUE TITLE
is GRPC reflection API generally available?

### ISSUE THREAD

**Issue by haritbe** [grpc/grpc-java#11104]
Hi Team,

We are building a passthrough proxy server to acceept json payloads and invoke grpc services using GRPC reflection api to make a RPC to a backend grpc api internally.

While using the api we noticed the package name for reflection api has "v1alpha". Does this mean that this api is not yet generally available?

_Originally posted by @haritbe in https://github.com/grpc/grpc-java/discussions/11101_

**Comment by panchenko** [comment]
* https://grpc.io/docs/guides/reflection/ currently links to a definition without "alpha", so it's worth regenerating sources here.
* It really depends on the service owner if they provide it or not

**Comment by ejona86** [comment]
I've replied on https://github.com/grpc/grpc-java/discussions/11101 . Looks like #6724 is the tracking issue.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
