### ISSUE TITLE
Retry log on client side

### ISSUE THREAD

**Issue by navch3** [grpc/grpc-java#11119]
How to get gRPC retry logs on client. I am looking for ways to achieve that. I am enabling retries and using RetryPolicy. Can anyone help me find best way to do so? 
1. Can we do this using this header **grpc-previous-rpc-attempts** somehow? I believe this is sent to server only?
2. Is it possible to do so using Interceptor by overriding `start(Listener<RespT> responseListener, Metadata headers)` If yes please redirect me to the example or provide some sample code.
3. Any chance we get an event on retry by adding StreamTracerFactory in CallOptions?
4. Any other possible way? 

Also I had one more question, I am trying to retry when server return NOT_FOUND status code. I used following policy. But seems like its not working by any chance Domain Exception blocked for retry in anyway?
`          retryPolicy:
            maxAttempts: 3
            initialBackoff: 1s
            backoffMultiplier: 2
            retryableStatusCodes: [ "UNAVAILABLE", "ABORTED", "DEADLINE_EXCEEDED", "INTERNAL", "NOT_FOUND" ]`

**Comment by navch3** [comment]
> But seems like its not working by any chance Domain Exception blocked for retry in anyway?
I mean retry is not happening for status code NOT_FOUND. Using retryPolicy I want to retry for this status code. So I wanted to ask is infra blocks retry for such status codes.

>One stream is created for each attempt. So StreamTracers already gives you some visibility into what is going on with retries. In particular, ClientStreamTracer.StreamInfo is provided to ClientStreamTracer.Factory.newClientStreamTracer() and has some information about retries.
Can you point me to an example of its usage or can you please provide a short template to use this. It will be helpful for other as many other people are looking for this capability like https://stackoverflow.com/questions/74591214/how-to-get-grpc-retry-logs-on-client-java-grpc/74620271#74620271 

Thanks for quick response.

**Comment by ejona86** [comment]
> So I wanted to ask is infra blocks retry for such status codes.

Oh, no. We accept whatever values you provide, except for OK.

> Can you point me to an example of its usage

It is an advanced API, and has essentially no guarantees with respect to threading. And it is deep enough into gRPC that internal changes to gRPC can break it at times. So it isn't something I want to encourage many people to use. But for "knowing when another attempt occurs" is not that involved, and you had already seen how to use it with CallOptions. I'm not sure which part is unclear to you.

**Comment by ejona86** [comment]
If you run into trouble with the tracer, feel free to comment again.
