### ISSUE TITLE
Support NPN for OkHttp non-Android path.

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#1114]
This code path may never have a real user, but it will gain some convenience for running our tests against a server that only supports NPN.

**Comment by ejona86** [comment]
Unfortunately that is not possible with Jetty, unless you run on an old JRE 7 _and_ don't support ALPN. The alternative would be to use tcnative, but I don't know how much effort that would be. Netty does actually provide SSLEngine, so maybe not too hard.

@madongfly, what did you have in mind?

**Comment by madongfly** [comment]
I didn't have a certain plan, just a random idea when I see a failure caused by this.

If the priority labels are available, I'd put it as a P3.
