### ISSUE TITLE
Use my own OkHttpClient with OkHttpChannelBuilder

### ISSUE THREAD

**Issue by JJaviMS** [grpc/grpc-java#11156]
Hi, I am developing an app using the GRPC client and I wonder if there is any way to use my own instanciated OkHttpClient with the GRPC client. Something like this:

    OkHttpClient okHttpClient = new OkHttpClient(); 
    ManagedChannel channel = OkHttpChannelBuilder.forAddress(ADDRESS,PORT).setOkHttpClient(okHttpClient).build();

This is intended because OkHttp documentation encourages you to use a shared instance between all your HTTP calls: 

> OkHttp performs best when you create a single OkHttpClient instance and reuse it for all of your HTTP calls
[Source](https://square.github.io/okhttp/5.x/okhttp/okhttp3/-ok-http-client/index.html)

So is there any way to set my already instanced OkHttpClient in a ManagedChannel?

Thanks and best regards

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
