### ISSUE TITLE
Integrate cronet as a grpc Java transport

### ISSUE THREAD

**Issue by zsurocking** [grpc/grpc-java#1116]

**Comment by zhangkun83** [comment]
@zsurocking any progress?

**Comment by perezd** [comment]
Any update on this?

**Comment by ericgribkoff** [comment]
Cronet binaries are now available: https://github.com/GoogleChrome/cronet-sample/blob/master/README.md

We haven't open-sourced the gRPC Cronet transport code yet because (a) using Cronet still requires manually downloading the binaries and adding them to your project dependencies, rather than a Maven Central target and (b) there hasn't been much demand for it.

It would help with prioritization if you could describe your use case for gRPC Cronet.

**Comment by perezd** [comment]
Primarily I'm interested in using it as the primary networking stack for an Android app, some key reasons:

1. Performance (battle tested as part of mobile Chrome browser)
2. Security (builtin boringssl which ensures up to date patches)
3. Uniformity (iOS grpc clients are able to make use of cronet today as well)

**Comment by carl-mastrangelo** [comment]
This should be complete once cronet is present.

A followup item will be to integrate it with build system.

**Comment by kantoniak** [comment]
Is there/Will there be a maven package for cronet I will be able to use with protobuf-gradle-plugin instead of okhttp?

**Comment by ericgribkoff** [comment]
At this time the Cronet libraries have to be manually downloaded using the instructions at https://github.com/GoogleChromeLabs/cronet-sample. Once Cronet team makes jars available on Maven, gRPC will be able to integrate it into the build system and you can use it much as with grpc-okhttp. 

It's also possible that we'll be able to provide a gradle build script that can handle downloading the Cronet library as part of the build process, which would make things a bit easier for gRPC users until Cronet is actually on Maven, but I haven't investigated this yet to know if this is feasible/maintainable.

**Comment by ericgribkoff** [comment]
gRPC Cronet is now available (https://github.com/grpc/grpc-java/pull/3349). As mentioned in the previous comment, there isn't yet integration with a build system, but instructions for its use in your app can be found in the [README](https://github.com/grpc/grpc-java/blob/master/cronet/README.md)
