### ISSUE TITLE
Inquiry on monitoring serialization message of protobuf requests in gRPC-java

### ISSUE THREAD

**Issue by zhangyachen** [grpc/grpc-java#11217]
Dear Team,

I am currently utilizing gRPC-java for our project and I have a specific requirement that I need assistance with.

I am interested in measuring the time it takes to serialize Protobuf requests on the client side. Could you please tell me if there is any built-in monitoring capability in gRPC for this purpose? Alternatively, could you advise which function I might use to log the time taken for this process?

I have posted this topic  on grpc-io, but nobody reply me, sad , haha

Thank you in advance for your support and guidance.

Best regards

**Comment by ejona86** [comment]
Also asked https://groups.google.com/g/grpc-io/c/SRVth8pNKrI

**Comment by temawi** [comment]
We use a tracing library called [PerfMark](https://github.com/perfmark/perfmark) that could be useful to you here.

We define a TraceMark task called `ServerStreamListener.messagesAvailable` in [ServerCallImpl](https://github.com/grpc/grpc-java/blob/8aaace12eb8697a2dd841d2261b0051a1414f0c8/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L316) that mostly deals with deserializing responses. See TraceMark documentation on how to enable the tracing.

If that does not work for you, you can add your own code in [ProtoLiteUtils](https://github.com/grpc/grpc-java/blob/8aaace12eb8697a2dd841d2261b0051a1414f0c8/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java#L168) where the lower-level deserialization code is.

**Comment by zhangyachen** [comment]
Thank you for your replay! Does serialization message also in [ProtoLiteUtils](https://github.com/grpc/grpc-java/blob/8aaace12eb8697a2dd841d2261b0051a1414f0c8/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java#L168) ?

**Comment by zhangyachen** [comment]
> Thank you for your replay! Does **serialization code** also in [ProtoLiteUtils](https://github.com/grpc/grpc-java/blob/8aaace12eb8697a2dd841d2261b0051a1414f0c8/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java#L168) ? we are using grpc-java client , we have added cost time code in grpc-cpp deserialization code : )
> 
> I guess deserialization is some code like parseFrom, but serialization is some code like toByteArray()?

And I also use perfmark, I set `PerfMark.setEnabled(true);` when application starts, and use `      TraceEventViewer.writeTraceHtml();` when application ends. but no html generate in /tmp directory. 

I use grpc-java v1.47.0 tag

**Comment by ejona86** [comment]
It'll probably be one more week until we look at why you aren't seeing HTML output.

**Comment by ejona86** [comment]
Did you resolve the issue with lack of HTML output?

**Comment by zhangyachen** [comment]
> Did you resolve the issue with lack of HTML output?

hi，I have get the cost time in another approach, thank you!
