### ISSUE TITLE
Bazel: support @generated=omit

### ISSUE THREAD

**Issue by ah-edg** [grpc/grpc-java#11226]
### Is your feature request related to a problem?

There is currently no simple way to use the (wonderful) new 1.64.0 feature `@generated=omit` from Bazel. Which leaves Bazel users with a superfluous dependency for a single annotation.

It might be possible to do so with a new toolchain, but that's a lot of effort for a minor feature. If that doesn't work either, it's probably impossible. This might also be related to https://github.com/grpc/grpc-java/issues/11097

### Describe the solution you'd like

Either set it to omit by default or add an option to change it.

https://github.com/grpc/grpc-java/blob/v1.64.0/java_grpc_library.bzl#L95 looks like the right place;  `args.add("--rpc-plugin_opt=@generated={0}".format(<???>))` behind a conditional (only if non-default) should do the trick - with a new attribute in the rules below.

The `..._opt` flag to set the CodeGeneratorRequest.parameter for a plugin is not well documented, but is referenced e.g. here: https://github.com/protocolbuffers/protobuf/issues/4759#issuecomment-396668142 (EDIT: a better reference would be https://github.com/protocolbuffers/protobuf/blob/v26.1/src/google/protobuf/compiler/command_line_interface.h#L107-L175)

It can occur more than once. It might even be worth it to also use this instead of the lite/non-lite toolchains.

### Describe alternatives you've considered

I tried a `.bazelrc` entry with `build --protocopt=--rpc-plugin_opt=@generated=omit` - but that failed. The descriptors are created before the plugin is called, the option is unknown at that point and the command fails.

**Comment by ejona86** [comment]
I think this is mostly infeasible/not worth the effort. Even without the `@Generated` annotation, your dependencies wouldn't change and you'd [still depend on the old j2ee stuff](https://github.com/grpc/grpc-java/blob/8aaace12eb8697a2dd841d2261b0051a1414f0c8/compiler/BUILD.bazel#L38).

Yes, with specific toolchain plumbing that could maybe be managed, but that's a lot of effort for this neverlink=1 dependency. It'd be much easier for someone to just pick up #9179.

**Comment by Hc747** [comment]
Picked up #9179 for you here https://github.com/grpc/grpc-java/pull/11215 :)

**Comment by ejona86** [comment]
@Hc747, please actually read the beginning of #9179. Its title is "Replace javax.annotation.Generated with custom gRPC annotation," which is quite different than that PR.
