### ISSUE TITLE
Investigate using jdk8 Base64 encoder

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1125]
The Guava base64 Coder we are currently using has possible performance issues, and may not be present in some android situations that can't use Guava.  Investigate if the jdk8 speed up is enough to justify using it, or the android native coder.  There appears to be a Guava release that could address these coming up, but we may need a fix sooner.

**Comment by ejona86** [comment]
@carl-mastrangelo, would you be comfortable with us closing this? It seems we are okay with Guava's Base64 with some of the recent changes.

**Comment by carl-mastrangelo** [comment]
I am 1e2% fine with closing this.
