### ISSUE TITLE
The onReadyThreshold property cannot be configured in the application[grpc version: 1.64.0]

### ISSUE THREAD

**Issue by hlx502** [grpc/grpc-java#11289]
1. Although grpc currently supports configuring onReadyThreshold, the withOnReadyThreshold() method is not provided in AbstractStub
![image](https://github.com/grpc/grpc-java/assets/73785906/ec0cd6f2-a2be-4a61-855b-116e418938dd)
2. Because the onReadyThreshold property is not copied in the toBuilder() method of CallOptions. Even if onReadyThreshold is configured in the interceptor, it will be overwritten to null in the end.
![image](https://github.com/grpc/grpc-java/assets/73785906/65e3a611-8dd8-4d1b-8827-20a94d6e71be)

**Comment by ejona86** [comment]
Mind sending a PR? That second part definitely looks like a bug. It doesn't seem stub was discussed earlier; I don't see any evidence it was left out on purpose, other than it wasn't needed/helpful/whatever at the time. It seems fair to include on the stub.

The broken toBuilder() would only matter if something later modified the call options, but gRPC itself will modify the call options at at times...

**Comment by hlx502** [comment]
yes, I sent a PR. Please review it if you have time.
