### ISSUE TITLE
Many DirectByteBuffer with high capacity when use netty shaded client

### ISSUE THREAD

**Issue by cudothanh-Nhan** [grpc/grpc-java#11314]
### What version of gRPC-Java are you using?
1.60.0

### What is your environment?
jdk-18.0.2.1-x64
Linux 3.10.0-1160.76.1.el7.x86_64

### Client intialization?
```
        NettyChannelBuilder.forTarget(target)
            .withOption(ChannelOption.CONNECT_TIMEOUT_MILLIS, timeout)
            .defaultLoadBalancingPolicy("round_robin")
            .keepAliveTime(60, TimeUnit.SECONDS)
            .keepAliveWithoutCalls(true)
            .sslContext(
                GrpcSslContexts.forClient()
                    .trustManager(InsecureTrustManagerFactory.INSTANCE)
                    .build())

;
```

### JVM properties?
`
/zserver/java/jdk-18.0.2.1/bin/java --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true -Dzappname=kiki-asr-streaming-websocket -Dzappprof=production -Dzconfdir=conf -Dzconffiles=config.ini -Djzcommonx.version=LATEST -Dzicachex.version=LATEST -Dzlogconffile=log4j2.yaml -Dlog4j2.configurationFile=conf/production.log4j2.yaml -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -Dlog4j2.immediateFlush=false -Djava.net.preferIPv4Stack=true -XX:+AlwaysPreTouch -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:InitiatingHeapOccupancyPercent=70 -XX:ParallelGCThreads=24 -XX:ConcGCThreads=24 -XX:+ParallelRefProcEnabled -XX:-ResizePLAB -XX:G1RSetUpdatingPauseTimePercent=5 -Dspring.config.location=optional:file:./conf/production.spring.yaml -Dorg.springframework.boot.logging.LoggingSystem=none -jar /zserver/java-projects/kiki-asr-streaming-websocket/dist/kiki-asr-streaming-websocket-1.3.1.jar
`

### What did you expect to see?
Stable number of DirectByteBuffer objects

### What did you see instead?
Increasing number of DirectByteBuffer objects.

This is my OQL to list capacity of about 1,832 objects
![image](https://github.com/grpc/grpc-java/assets/55862577/c7d46573-3a31-4647-8ea5-2655421a4ce5)

This is the GC root references from sample FastThreadLocalThread which contains DirectByteBuffer with capacity about 2MB and there are a lot of object like that
![image](https://github.com/grpc/grpc-java/assets/55862577/ec6420de-c4fa-442c-8048-ac3f12cb8470)

Besides, I noted that there are many DirectByteBuffer which has null cleaner. Is it the intentional impletation of netty.

**Comment by ejona86** [comment]
> Increasing number of DirectByteBuffer objects.

That doesn't tell us much. And you only give us one data point.

Does your machine have many cores? #4317 and #5671 are about many threads. The screenshot shows details of an EpollEventLoop; we would expect there to be a cache there.

**Comment by cudothanh-Nhan** [comment]
I also wonder whether we have limitation on number of DirectByteBuffers inside each subpage area

**Comment by ejona86** [comment]
gRPC [reduces the subpage size to 2 MiB](https://github.com/grpc/grpc-java/blob/5770114d08dcd352f2288ef52d17e1833530323c/netty/src/main/java/io/grpc/netty/Utils.java#L163), to reduce memory. It also reduces the number of threads to number of cores. I think what's hurting here is the number of threads. If we reduced the number of threads by half, would that get into a reasonable state, or are you hoping for even more memory usage redection?

**Comment by cudothanh-Nhan** [comment]
I mean while the size of each subpage is only 2MB, there is also a potential memory pressure when there are many objects of them. Even though if my server only has 1 cores, one eventloop can contains multiple subpage, 2MB each @ejona86

**Comment by cudothanh-Nhan** [comment]
After diving deep inside `netty` implementation, while the number of `PoolChunk` object is stable (48 objects for 48 cores), I have found many `DirectByteBuffer` objects referenced by `PoolThreadCache` (about 1,147 objects as shown in the below image).

![image](https://github.com/grpc/grpc-java/assets/55862577/4be9c347-77dd-4122-bd4e-8dbbfa39c95a)


Given that my GRPC Client use default grpc executor which is, in turn, a cache thread executor.

Is native memory occupied by `DirectByteBuffer` freed after executor thread no longer exist? I think no because I see a lot of `DirectByteBuffer` objects are holding in `PoolThreadCache`

**Comment by cudothanh-Nhan** [comment]
It seems that one PoolThreadCache can contain many `DirectByteBuffer` objects, so that if one `PoolThreadCache` contain 40 `SmallSubPageDirectCaches`, it can consume up to 2MB * 40 = 80 MB native memory.

![image](https://github.com/grpc/grpc-java/assets/55862577/7a0d338a-1d02-4a30-814c-feb25e3d053e)


Am I right?

**Comment by hakusai22** [comment]
@ejona86 Hello, is there any progress on this issue?

**Comment by kannanjgithub** [comment]
You are presenting the state of how memory is handled in grpc, but not necessarily indicative of a problem. There can be optimizations but each with their own trade-offs.
1. Changing the number of threads is one of easier things to do. As mentioned by Eric above, the [number of event loops](https://github.com/grpc/grpc-java/blob/eb4cdf7959795d70c44aa74d572ddc5f8bd2ac5e/netty/src/main/java/io/grpc/netty/Utils.java#L444)  is set to be equal to the number of cores available, but this can be further controlled via the system property io.netty.eventLoopThreads. 

2.  Use heap memory via -Dio.grpc.netty.shaded.io.netty.noPreferDirect=true if your problem is with direct memory so it uses heap memory instead.

3.  Netty also provides a way of specifying a custom allocator via the [ChannelOption.ALLOCATOR](https://netty.io/4.1/api/io/netty/channel/ChannelOption.html#ALLOCATOR) and pass it via the [Channel Builder options](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyChannelBuilder.html#withOption%28io.netty.channel.ChannelOption,T%29) (Although in this case you shouldn't be using grpc netty shaded).

**Comment by kannanjgithub** [comment]
We are aware of the higher than we would like memory usage but we don't see a way to improve it right now in the gRPC server code. And there's the workaround mentioned above in my last comment that one could try.
