### ISSUE TITLE
Difference between adding an interceptor over a Channel vs over a Stub

### ISSUE THREAD

**Issue by juansoft-spain** [grpc/grpc-java#11339]
Hi, sorry to bother. I did a lot of searches in google prior to open this question but I did not find any answer in the _grpc-java_ documentation or in any previous question done in this project.

Short question is, What is the recommended approach about interceptors? In which scenarios assign the interceptor to a channel is better than assign the interceptor to a stub? 

As example, imagine that we want to put an interceptor that writes a log line every time we start an rpc calling or when we receive a response from the server:

1) Over a channel:
```
 private static ManagedChannel buildManagedChannel(String host, Integer port) {
    return ManagedChannelBuilder.forAddress(host, port)
                                                         .usePlaintext()
                                                         .intercept(new LoggingInterceptor())
                                                         .build();
    }
```

2) Over an stub:
```
        this.businessServiceBlockingStub = BusinessServiceGrpc.newBlockingStub(channel)
                .withInterceptors(new LoggingInterceptor());
```

I understand that first approach means that every stub created with that channel has an implicit interceptor. But besides that, there is any other consideration that should be taken?

**Comment by ejona86** [comment]
> Short question is, What is the recommended approach about interceptors? In which scenarios assign the interceptor to a channel is better than assign the interceptor to a stub?

Whichever you prefer.

Some history here: interceptors are basically just a convenience to wrap Channels to produce other Channels. Originally, you'd use ClientInterceptors.intercept() to create a new Channel from an existing Channel. Over time we added convenience methods more places, like the stub and ManagedChannelBuilder.

Configuring ManagedChannelBuilder with interceptors is probably the easiest to manage and most popular. But if you want to do it per-stub, or manually with ClientInteceptors, there's no problem with doing so. Do what works best for you.
