### ISSUE TITLE
Getting gRPC unavailable during services rollout when using client side gRPC load balancing

### ISSUE THREAD

**Issue by archit-harness** [grpc/grpc-java#11351]
Hi @ejona86 we implemented the changes as discussed here - https://github.com/grpc/grpc-java/issues/11151 and it looks load balancing is working fine.
But as mentioned here - https://medium.com/jamf-engineering/how-three-lines-of-configuration-solved-our-grpc-scaling-issues-in-kubernetes-ca1ff13f7f06, we are facing grpc UNAVAILABLE error during rolling updates.

But i don't get one thing - we have preStop hooks on our pods, which ensures pod will be live for 60 sec at least with terminationGracePeriodSeconds of 180sec and as per blog, DNS caches refresh after 30 sec, thus we should not see this error.

We are still seeing those errors, not sure how minReadySeconds will help to mitigate the issue, as I understand the issue happens if DNS returns IP of old pod which is died down, which wont happen for our case if time period is 30sec.

Is there any case which i am missing?

In addition to above, during rollout we are seeing below errors.
a) Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: pipeline-service-headless/:
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused

b) Exception occurred: StatusRuntimeException: UNAVAILABLE: io exception; Cause: NativeIoException: recvAddress(..) failed: Connection timed out

**Comment by jasonmcintosh** [comment]
If I understand what the GRPC-java libraries (and GRPC libraries in general) are doing is (and really looking for confirmation):
Given a LoadBalancer setup using DNS, with 3 hosts.

* RPC call initated via executeCall -> subchannel opened to host1.  RPC sent to host1.  OTHER RPC calls will be routed to other hosts round robin as part of their call.
* IF host1 is NOT available (aka in these cases, it's not even RUNNING at this piont in time) an RPC call to host1 will RETRY on that SAME host vs. switching to "host2".
* External calls for the same exact GRPC request will ALSO be routed to host1 it seems.  E.g. if you're using Spring retry or any of the other similar libraries, a duplicate `blockingUnaryCall(getChannel(), getSubmitTaskV2Method(), getCallOptions(), request);` wil go BACK to that same host, even though it's in a bad state.

The question then becomes how to CHANGE this so "UNAVAILABLE" goes to host2 on retries.  I'm seeing "Hedging" which seems problematic as it's more time delayed retry vs. "Exception" controlled, OR use some sort of custom load balancing.

**Comment by jasonmcintosh** [comment]
Reading more... I think only switches to another host if a retry policy is set? IF the default service policy is overridden not sure if the transparent retries on say a "UNAVAILABLE" connection still happen?

**Comment by ejona86** [comment]
@jasonmcintosh, your comment doesn't seem all that related to the OP's comment. It'd probably be better for you to make your own issue to discuss your specific situation.

But some quick notes:
1. Connection handling is completely separate from RPC handling. The LB policy decides which connections it wants, and then it chooses where to send RPCs on those connections
2. Retry is not "steered." The LB policies we have today do not try to send a second RPC attempt to a different host. They simply "choose a host" like they do for all the other RPCs. So you may get a different host, or you may not. If there's only one host with a connection, then you'll always get that host
3. Server returning UNAVAILABLE is very different than the connection closing. The client still has a working connection when a server returns UNAVAILABLE, so it continues using the connection. Outlier detection and client-side health checking are the main ways to cause RPC response failures to impact the connection health.

**Comment by jasonmcintosh** [comment]
Sorry I'm trying to understand the internals of the communications - this is all related to the same "how is load balancing & failed hosts & retries to hosts being shutdown" handled.  I ALSO put together some tests to try to replicate the behaviors & tests.  I'm seeing oddities.  I'll respond in other issue ticket however.  To note the "UNAVAILABLE" is what we're seeing in the io.grpc response messages when a "Connection Refused" response is returned.  aka https://github.com/grpc/grpc-java/issues/11151#issuecomment-2205173192 this has the stack trace.  

I'll respond more in other thread & share tests I'm trying to replicate on this.

**Comment by ejona86** [comment]
@jasonmcintosh, you are bringing retries into the conversation. Retries should not be necessary for this. I agree they could resolve errors in certain cases, but that is because they will sleep for a while after the RPC failure. We want to resolve these issues without added latency like retry delays. An orderly service rollout should not need retries to avoid errors.

**Comment by ejona86** [comment]
The conversation is continuing in #11151, so closing this.
