### ISSUE TITLE
How to close the netty thread named grpc-default-worker-ELG?

### ISSUE THREAD

**Issue by litst** [grpc/grpc-java#11355]
We are using grpc client in hive which is a long running process, but seems there are many threads named grpc-default-worker-ELG won't close even if the task is done. How can I close these?

**Comment by kannanjgithub** [comment]
When you create NettyClientTransport what values are you [passing](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L113) for keepAliveTimeInNanos, keepAliveTimeoutInNanos and keepAliveWithoutCalls, especially the last one.

**Comment by litst** [comment]
> When you create NettyClientTransport what values are you [passing](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L113) for keepAliveTimeInNanos, keepAliveTimeoutInNanos and keepAliveWithoutCalls, especially the last one.

keepAliveWithoutCalls is false, also there are many file descriptor about eventfd, timerfd won't be released.

**Comment by ejona86** [comment]
grpc-default-worker-ELG are worker network threads in a fixed-size pool. They will exist as long as any channel or server still exists. Once you shut down the last channel/server, they will exit.
