### ISSUE TITLE
What does it mean when GRPC call fails with DEADLINE_EXCEEDED and waiting for connection

### ISSUE THREAD

**Issue by akhileshnirna** [grpc/grpc-java#11364]
I have a GRPC client A and a server B. Client A has timeout set to 400ms. 

Of the requests that resulted in `DEADLINE_EXCEEDED`, most of them were either 
1. `io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 0.399980582s. [closed=[], open=[[remote_addr=localhost/127.0.0.1:10016]]]` OR
2. `io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 0.399783897s. [closed=[], open=[[buffered_nanos=2271463709, waiting_for_connection]]]`

The first error results after the set timeout of 400 ms
The second one, I see majority of them logged with time of 400ms (0.399783897s) but also see a few with 200ms or lower. 

My question is:
1. In what cases do `waiting_for_connection` errors result and what does it mean for most of them to be logged with time equal to set time out of 400ms.
2. I assume the first error occurs because the server failed to respond within stipulated time? Can there be any other possibility?

Any help is appreciated.

**Comment by kannanjgithub** [comment]
1. waiting_for_connection means the timeout happened before a stream could be established with the server over which a  rpc request could be sent.  The value showing as 400ms for them means the stream couldn't be establlished by that time.
2. The first error occurs when a stream to the server is made available but the timeout occurred. Yes it could mean the server failed to respond within the stipulated time or didn't reach the client on time.

**Comment by akhileshnirna** [comment]
Thanks
