### ISSUE TITLE
Publicize ClientTransport

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#1139]
ClientTransport, which is currently internal API, is exposed via the LoadBalancer interface, which is public. ClientTransport needs to be public, and ClientStream also needs to be public because GrpcLoadBalancer will need to make RPC calls and decorate ClientTransport/ClientStream to attach LB tokens.

**Comment by zhangkun83** [comment]
Per offline discussion today, we don't want to make the whole transport API public. Instead, we will keep transport API as internal, and allow plugin developers, transport implementors and other contributors to use the internal API. We will clarify it in the javadoc of `@Internal`.

**Comment by ejona86** [comment]
We're now using generics in the `LoadBalancer` interface and providing some factory methods, such that `ClientTransport` is no longer exposed. Closing.
