### ISSUE TITLE
Does grpc-java fully supports openjdk 11

### ISSUE THREAD

**Issue by Hakai-Shin** [grpc/grpc-java#11391]
As there are differences in Java SE 11 Paid version and OpenJDK 11 with some closed features not available in openjdk , does this affect grpc-java?

**Comment by ejona86** [comment]
We test mostly with Temurin, not OracleJDK. Right now I'm not aware of issues with Temurin, OracleJDK, Zulu, IBM Java. We've had bug reports for some of those years in the past (basically exclusively to TLS), but they were resolved. So I believe people are using them in the wild without trouble.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
