### ISSUE TITLE
Examples fail to build on JDK 22

### ISSUE THREAD

**Issue by Kolyunya** [grpc/grpc-java#11397]
### What version of gRPC-Java are you using?
`v1.65.1`

### What is your environment?
MacOS, Docker, Eclipse Temurin 22.

### What did you expect to see?
[Quickstart example](https://grpc.io/docs/languages/java/quickstart/) builds successfully.

### What did you see instead?
[Quickstart example](https://grpc.io/docs/languages/java/quickstart/) build fails with the following error:

```
Could not open cp_settings generic class cache for settings file '/home/grpc-java/examples/settings.gradle' (/root/.gradle/caches/8.6/scripts/1b3qj4p3vbuoxlg8eny1lupih).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66
```

### Steps to reproduce the bug
```
git clone -b v1.65.1 --depth 1 https://github.com/grpc/grpc-java && \
docker run --rm --mount type=bind,source=$PWD/grpc-java,target=/home/grpc-java --workdir /home/grpc-java/examples eclipse-temurin:22 ./gradlew installDist
```

### Notes
Examples build successfully on JDK 21.

**Comment by ejona86** [comment]
That's just Gradle 8.6 not being compatible with Java 22. Try changing the version in to `examples/gradle/wrapper/gradle-wrapper.properties` to 8.8 or higher, which is the version Gradle started supporting Java 22. I did that recently on master via 64ac792b5e6e57268b69abb6979ca0f389af1d9d ; it'll be part of the next release.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
