### ISSUE TITLE
connection reset using firebase firestore using Php and Html

### ISSUE THREAD

**Issue by McBenedictMarave** [grpc/grpc-java#11405]
i already set up the Authentication for login and it works but when I tried to get the data using Document Id and the field, all I get is 'CONNECTION RESET' or just a plain white result using any browser

<?php
// fetchUserRole.php

require 'firebase.php';

// Example usage:
$userId = 'MZ7ZDlfWp5emv31lIuBr2PvieQh1'; // Replace with your actual user ID
$userRole = getUserRole($userId);

if ($userRole !== null) {
    echo "User Role: $userRole";
} else {
    echo "User not found or role not set.";
}
?>

**Comment by kannanjgithub** [comment]
You should post your question with firebase firestore.
