### ISSUE TITLE
I can't run the android client example.

### ISSUE THREAD

**Issue by fizlrock** [grpc/grpc-java#11419]
I can't run the android client example.
Acted in accordance with https://grpc.io/docs/platforms/android/java/quickstart/
I rechecked the SDK installation several times. 

After (cd android/helloworld; ../../gradlew installDebug) is see:

Execution failed for task ':app:extractIncludeDebugProto'.
> Configuration `:app:debugRuntimeClasspath` contains AndroidX dependencies, but the `android.useAndroidX` property is not enabled, which may cause runtime issues.
  Set `android.useAndroidX=true` in the `gradle.properties` file and retry.

full stack trace: https://gist.github.com/fizlrock/0ef049995ff2337c8a547bf5128a8691

I tried to add a -android.useAndroidX=true parameter, but the command still failed:

https://gist.github.com/fizlrock/717b3c0c7fb8eea48342aded70b6330b

**Comment by kannanjgithub** [comment]
Seeing that you got the error 

>  Unknown command-line option '-n'.

for 

`../../gradlew installDebug -android.useAndroidX=true`

It is not even going as far as trying to execute task ':app:extractIncludeDebugProto' anymore. This way of passing options must be unsupported. Set android.useAndroidX=true in gradle.properties (if it doesn't exist, create one in the root folder, i.e., in the same directory containing build.gradle) instead.

**Comment by fizlrock** [comment]
It work! Thank you)  I think it's worth making a pull request so that it works out of the box.
