### ISSUE TITLE
IS_PETIOLE_POLICY is not used by PickFirstLeafLoadBalancer

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#11413]
From A61 (dual stack):

> Therefore,
pick_first will have an option to support these health signals, and
that option will be used only when pick_first is used as a child policy
underneath a petiole policy.
>
> Note that we do not want either of these mechanisms to actually work
when pick_first is used as an LB policy by itself, so we will implement
this functionality in a way that it can be triggered by a parent policy
such as round_robin but cannot be triggered by an external application.
(For example, in C-core, this will be triggered via an internal-only
channel arg that will be set by the petiole policies.)

In grpc-java, I think that was being implemented as IS_PETIOLE_POLICY. MultiChildLB sets the value (and ClusterManagerLoadBalancer overrides a method so it isn't set), but nothing appears to read it. Clearly either we should read it or remove it.

When PickFirst is used as a top-level policy, there will not be any health producer, so PF doesn't really need to read the flag. And client-side health checking is only enabled within petiole policies like RR. But if outlier detection is in the tree, like with standard xds, then there would be a health producer and PF wouldn't ignore its health reports.

**Comment by YifeiZhuang** [comment]
It looks "IS_PETIOLE_POLICY" can be removed. 
For generic health check, it detects whether there is health producer. If no producer, it is no op. See https://github.com/grpc/grpc-java/pull/10623

**Comment by ejona86** [comment]
OutlierDetection is a producer, but isn't a petiole policy. So it is possible to have a health producer and pick first, without any petiole policy.

**Comment by YifeiZhuang** [comment]
@ejona86  okay, so if OutlierDetection is a producer and used with just pick first leaf policy,  what do we do? We ignore health check producer's health notification and just use the subchannel status change, or we just panic the channel?

**Comment by ejona86** [comment]
We should definitely not panic. We just ignore/turn off the health monitoring. Looks like that's what y'all did (with a WARNING).
