### ISSUE TITLE
MultiChildLb unconditionally calls requestConnection()

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#11411]
https://github.com/grpc/grpc-java/blob/b108ed3ddf08d20926cab1ea4ddd75264aff8c18/util/src/main/java/io/grpc/util/MultiChildLoadBalancer.java#L481-L483

Prior to https://github.com/grpc/grpc-java/commit/044749706a71935756b0abe41727257132b3d171 it was conditional on `reconnectOnIdle() == true`, but it was removed for a reason that is not clear to me.

It seems strange to me that MultiChildLb is calling reconnectOnIdle() at all. That is the responsibility of individual LB policies and has little to do with having multiple children. It is very surprising behavior.

**Comment by larry-safran** [comment]
Note that the method named `reconnectOnIdle` really meant `shouldReconnectOnIdle`.  

ClusterManager and RingHash are the load balancers that don't want to reconnect on idle and they each have their own helper that overrides `updateBalancingState`.  There is a comment on `ChildLbLoadBalancer.updateBalancingState` mentioning that it needs to be overridden it you don't want the reconnect on idle behavior.

**Comment by ejona86** [comment]
:-/ I see it now. So they override it without calling super. That is poor. Yes, I see the comment now, but that is also not at all obvious from RingHashLb and it also assumes you read all of MultiChildLb to see it. updateBalancingState() is literally the only method in ChildLbStateHelper and then you are even supposed to disable it at times...

We should move the `requestConnection()` to the places that need it, as an override to updateBalancingState that calls super().

**Comment by larry-safran** [comment]
The messy part is that `requestConnection` needs to be called before `updateOverallBalancingState()` so that every policy will need their own helper (or we introduce a ReconnectOnIdleMultiChildLoadBalancer w/ matching helper).

**Comment by ejona86** [comment]
> requestConnection needs to be called before updateOverallBalancingState()

Why does it need to be called before? The results of the call are enqueued back into the synchronization context, so calling it before or after are pretty similar. That is to say, updateOverallBalancingState() will see IDLE regardless of when requestConnection is called.

Before MultiChildLb, every LB policy had subchannel listeners. The Helper is the replacement for that, so that seems acceptable. I do see the levels of indirection for them to implement, and it is a bit unfortunate, but I'd much rather optimize clear lines of responsibility for the components.

I'll prepare a PR (after the splitting WRR from RR PR goes in).
