### ISSUE TITLE
Decide how to select a NameResolver for a URI.

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#1142]
We have two options. Currently it's try-and-fail. The other option is keep a map that maps schemes to NameResolvers.

Quote from @ejona86 in #1134 
> My concern about this is that order matters and you won't notice if a scheme is double-registered. It also has no avenues for optimization because the registry is basically knowledge-less.
>We can leave it as-is for now, but we'd need to decide on things before it goes stable.

**Comment by ejona86** [comment]
Marking as long-term milestone, because it doesn't need to happen soon. However, if we end up making NameResolver a stable API, then this will need to addressed.
