### ISSUE TITLE
Make the total headers size limit configurable.

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#1144]
We may want to have our own limit, but before we decide the number, should just remove the current limit.

**Comment by ejona86** [comment]
Instead of a per-header limit, we would have a combined-headers size limit.

**Comment by carl-mastrangelo** [comment]
Isn't that part of the HTTP/2 Options?

**Comment by ejona86** [comment]
If you mean SETTINGS_MAX_HEADER_LIST_SIZE, sorta. It is only advisory, but yeah, we could inforce it when receiving.

Note that SETTINGS_HEADER_TABLE_SIZE is something different and doesn't apply here.

**Comment by madongfly** [comment]
After browsed the netty code with @ejona86, we found the maxHeaderSize used in DefaultHttp2HeadersDecoder is actually acting as SETTINGS_MAX_HEADER_LIST_SIZE, and the default value 8k is also the value we want to apply for gRPC.

**Comment by madongfly** [comment]
Per discussion, we should keep the 8k default limit, but make it configurable.
