### ISSUE TITLE
Release notes for 1.66.0

### ISSUE THREAD

**Issue by jamesalfei** [grpc/grpc-java#11460]
Hello team.

I have noticed that the recent 1.66.0 version was released but there have been no associated release notes created yet for this release.

Release tag: https://github.com/grpc/grpc-java/releases/tag/v1.66.0
No release: https://github.com/grpc/grpc-java/releases

Can we please get these published to consumers of this project can understand what changes have been applied without trawling the commit diff?

Thanks

**Comment by kannanjgithub** [comment]
Release notes have been added.
