### ISSUE TITLE
What is the purpose of animal-sniffer as a runtime dependency?

### ISSUE THREAD

**Issue by daniel-b2c2** [grpc/grpc-java#11481]
I can see that grpc-core library depends on a library called animal-sniffer, this is defined as a runtime dependency.
In my application we are not using anything from this animal-sniffer library directly in code that we've written, it's unclear if it's necessary to include it as a runtime-dependency.
Do I need to include this? What is the consequence of including it or not including it?

**Comment by ejona86** [comment]
`org.codehaus.mojo:animal-sniffer-annotations` is just the annotations of animal sniffer. We use animal sniffer to verify we aren't using unavailable Java or Android APIs. The dependency is _very_ small (a single, empty `@interface`) and the annotation is not preserved at runtime, but you may need it at compile time to prevent javac warnings about missing annotation classes. Maven poms have no way of communicating transitively compile-only.

On Android, the `@interface` will be stripped during compilation as dead code. On non-Android, it wouldn't be loaded at runtime.

**Comment by daniel-b2c2** [comment]
> annotation is not preserved at runtime
> but you may need it at compile time to prevent javac warnings about missing annotation classes

Ok, sounds like if it compiles without it, it's safe to use it?

**Comment by ejona86** [comment]
Even if you get a warning during compilation, I don't think you need it when shipping your app.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
