### ISSUE TITLE
Can it support dynamically determining whether to enable gzip compression based on message size

### ISSUE THREAD

**Issue by brucelwl** [grpc/grpc-java#11485]
Can it support dynamically determining whether to enable gzip compression based on message size ?

**Comment by kannanjgithub** [comment]
The gRPC client cannot make such a decision as to at what size to enable gzip compression that  because the size restriction is on the receiver specified via [ManagedChannelBuilder::maxInboundMessageSize](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html).
