### ISSUE TITLE
./gradlew installDist error com.google.protobuf not found

### ISSUE THREAD

**Issue by lee-light** [grpc/grpc-java#11518]
I tried build, clean and installDist, all ran into the same issue below.
Have this error when running "./gradlew installDist":

Plugin [id: 'com.google.protobuf', version: '0.9.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (No included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.google.protobuf:com.google.protobuf.gradle.plugin:0.9.4')
  Searched in the following repositories:
    maven(https://maven-central.storage-download.googleapis.com/maven2/)
    Gradle Central Plugin Repository

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
