### ISSUE TITLE
Allow turning `BindableService` into a `ServerTransportListener`-like structure

### ISSUE THREAD

**Issue by bsideup** [grpc/grpc-java#11546]
### Is your feature request related to a problem?

Currently, there is no easy way to trigger a gRPC service from an existing HTTP/2 handler.

### Describe the solution you'd like

Expose a way to call a service by calling it with a raw HTTP/2 request. Something like:
```java
ServerBuilder.forFactory(ClientTransportServersBuilder)
```

### Describe alternatives you've considered

A custom server can be implemented, but it requires many steps and operates on low level abstractions (e.g. Netty channels, or Sockets), whereas most modern frameworks have their own HTTP/2 abstractions that can be turned into a `ServerStream`.

### Additional context

https://github.com/bsideup/grpc-bidi uses an existing `ClientCall` and exposes itself (client) as a server. The current implementation requires going through the full pipeline, but all is does is parses the bytes from `ClientCall` without any network stack, and it could use a lean implementation where it simply parses the HTTP/2 request and turns it into a `ServerStream`.

**Comment by bsideup** [comment]
Hi @ejona86! Funny that you mentioned your PR because I've previously submitted https://github.com/grpc/grpc-java/pull/11023 as a continuation of it, and grpc-bidi is basically the end result, extracted so it can be consumed already now (it's been in prod for 6+ months), but I hope to land it in https://github.com/grpc-ecosystem and eventually grpc-java if it gets accepted to the spec :)

Cool idea to look at grpc-servlet, thank you! I will investigate. I _think_ I looked into in-process in the past but there were some issues with it, I could be wrong tho. Let me double check! Thanks for the pointers 👍

**Comment by ejona86** [comment]
> But then you'd need to represent the "existing HTTP/2 request" in terms of the servlet API.

Beware that is doing some heavy lifting. In particular, we use the async APIs. It's more, "that's the only general-purpose HTTP API we support."

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
