### ISSUE TITLE
WARNING: Unable to find Conscrypt

### ISSUE THREAD

**Issue by Bios-Marcel** [grpc/grpc-java#11576]
### What version of gRPC-Java are you using?

grpc-okhttp 1.66

### What is your environment?

Windows 11, x64

### What did you expect to see?

No warnings when using the gRPC-okhttp client.

### What did you see instead?

```
Sep 30, 2024 10:49:52 AM io.grpc.okhttp.internal.Platform getAndroidSecurityProvider
WARNING: Unable to find Conscrypt
```

It seems that the first thing the internal okhttp fork does, is to find the android security provider.
As we are running on Windows, this obviously won't work.

This is where the error occurs:
https://github.com/grpc/grpc-java/blob/master/okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/Platform.java#L288

Given that the application works just fine after this warning, I assume adding a matching security provider on our side would be nonsense.

### Steps to reproduce the bug

Simply use gRPC with transport security on a non-android platform.

**Comment by ejona86** [comment]
It is possible and actually pretty easy to use Conscrypt on Windows. But yes, the log shouldn't be there. https://github.com/grpc/grpc-java/pull/11567 was trying to fix this, but they've not signed the CLA yet and they'd need to fix a bug. If that drags out more we can create an alternative PR to do as I suggest in a comment.

**Comment by Bios-Marcel** [comment]
I see, thanks for the info :)
