### ISSUE TITLE
Need the next build which will be having the protobuf upgrade to 3.25.5

### ISSUE THREAD

**Issue by bharatgoelharness** [grpc/grpc-java#11602]
Need the next build which will be having the protobuf upgrade to 3.25.5

I see there is a commit tp upgrade protobif to 3.25.5 but there is no release after that. When is the next release build? @ejona86

**Comment by ejona86** [comment]
You are free to upgrade protobuf-java in your own dependency tree. You do not need to wait for grpc-java. Add an explicit dependency on protobuf-java with the higher version. (And as always, if using maven, please use Maven Enforcer's `requireUpperBoundDeps`.) This is the same way people are upgrading to protobuf-java 4.x.

**Comment by ejona86** [comment]
1.68.1 is released. For reference: the earlier issue #11542 and the upgrade itself #11543
