### ISSUE TITLE
Support for details in status payloads

### ISSUE THREAD

**Issue by friscoMad** [grpc/grpc-java#11616]
I have not been able to find out a way to recover the details included in a server response status message, it seems that they are not included in grpc.io Status class and thus are not accessible from the StatusException thrown on server errors.
Is there a way to recover and access the details field from the client or using the details field is discouraged.
We were planning on using the recommended payload list from here: https://cloud.google.com/apis/design/errors#error_payloads but if the information can not be retrieved from the client it does not make sense to send.

For context we are using grpc-java 1.66 + grpc-kotlin 1.4.1 but the models are in the grpc-java side.

**Comment by kannanjgithub** [comment]
There is a description field in Status and this is what is set by the gRPC server to add error details ([example](https://github.com/grpc/grpc-java/issues/11611)). Is your client not seeing this field set?

**Comment by ejona86** [comment]
I think @kannanjgithub intended to link to this example:
https://github.com/grpc/grpc-java/blob/99f86835ed8a1c960d532e58b5fd51ec1bb99825/examples/src/main/java/io/grpc/examples/errordetails/ErrorDetailsExample.java#L125

See also [the gRPC guide](https://grpc.io/docs/guides/error/#richer-error-model) that covers discusses the cross-language concepts.

**Comment by friscoMad** [comment]
As I understand over the wire what it is sent is this [model](https://github.com/googleapis/googleapis/blob/8d15dcb4f24cbdc2c3047045bdc7c20ddac78ad4/google/rpc/status.proto#L48) that include the details field with extra information about the error cause.
I was hoping to have access to that information from the client side, as far as I can tell that detail field is not included in the description as expected but is not stored in the io.grpc.Status object.

But after some more exploring it seems that details should be present in the metadata part of the exception and they were not there due to an unrelated bug.
