### ISSUE TITLE
[guice] any examples or docs on how to integrate with google guice?

### ISSUE THREAD

**Issue by peterweb2005** [grpc/grpc-java#11632]
as title
thanks

**Comment by kannanjgithub** [comment]
https://github.com/google/guice/tree/master/examples/guice-demo

Not a gRPC Java specific question however.

**Comment by peterweb2005** [comment]
thanks,
my question is about how `grpc integrate with guice`, which seems has scope problem, but the scope library is very low usage:
https://github.com/morgwai/grpc-scopes

**Comment by kannanjgithub** [comment]
I assume by GrpcImpl object you are referring to the service implementation that you  pass to the GrpcServlet [constructor](https://github.com/grpc/grpc-java/blob/9176b55286c478cc522ec7349311f29fa73d7c18/servlet/src/main/java/io/grpc/servlet/GrpcServlet.java#L51). Yes, what you said should  work.
