### ISSUE TITLE
Is it possible to limit DirectByteBuffer usage?

### ISSUE THREAD

**Issue by santhoshmanikandan** [grpc/grpc-java#11642]
In case of Server-Side streaming where analytics data is streamed back to client, is it possible to configure the maximum size of buffer that can be used by that RPC call? 

Currently I could see that the buffer size keeps on increasing until OOM occurs if client disconnects and server couldn't send back the response. Even though manual flow control is possible for each RPC implementation, looking for an option to tweak it at configuration level or at Interceptor level to make sure such orphaned/rouge RPC calls are discarded in a better way.

**Comment by kannanjgithub** [comment]
Have you tried adding a cancellation handler on the server ([example](https://github.com/grpc/grpc-java/blob/1f159d7899915245e6d3bd48b58b71b428a9e37b/examples/src/main/java/io/grpc/examples/cancellation/CancellationServer.java#L135)) to know when to stop sending the streaming response?

**Comment by ejona86** [comment]
Flow control is important and would limit the memory use dramatically. For the stuck RPCs, I assume you've not enabled keep alive on the server-side. See the [keepalive guide](https://grpc.io/docs/guides/keepalive/). The most important thing is to set `keepAliveTime()`; the other keepalive options aren't needed as often.

**Comment by santhoshmanikandan** [comment]
> For the stuck RPCs, I assume you've not enabled keep alive on the server-side.

KeepAlive is enabled on the server. Following was tested with a single Server Side streaming call where data is sent every 30 seconds.
KeepAliveTime: 5 seconds
KeepAliveTimeout: 1 second
KeepAliveWithoutCalls: False

Standalone java client was killed after 1 minute(2 responses from server). I could see responseObserver.onNext() still doesn't throw any error.

**Comment by santhoshmanikandan** [comment]
> Have you tried adding a cancellation handler on the server ([example](https://github.com/grpc/grpc-java/blob/1f159d7899915245e6d3bd48b58b71b428a9e37b/examples/src/main/java/io/grpc/examples/cancellation/CancellationServer.java#L135)) to know when to stop sending the streaming response?

This requires handling at each RPC level. Is there such an option at Interceptor or TransportFilter level so that those RPC calls can be cancelled/dropped when connection is cancelled?

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
