### ISSUE TITLE
InstantTimeProviderTest.testInstantCurrentTimeNanos is consistently failing

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#11680]
[Inside Google](https://fusion2.corp.google.com/triage/2712179097651820092/5592943177771253760):
```
expected         : 1730533931622822000
but was          : 1730533931609013000
outside tolerance: 10000000
	at io.grpc.internal.InstantTimeProviderTest.testInstantCurrentTimeNanos(InstantTimeProviderTest.java:48)
```

Another arbitrary failure:
```
expected         : 1731147454282900000
but was          : 1731147454264246000
```

@vinodhabib
CC @kannanjgithub

**Comment by ejona86** [comment]
These failures are when running with `--config=tsan`, which runs slower.

**Comment by vinodhabib** [comment]
@ejona86 @shivaspeaks I went through the details and found like below scenarios failed because the given tolerance time of 10 milliseconds exceeded ( I,e first run/failure took 13 milliseconds and second took 18 milliseconds).

As per my Analysis we can update the tolerance value to 50 from 10 milliseconds to resolve this issue, Please confirm?

**Comment by kannanjgithub** [comment]
With 50ms it still failed 3 / 1000 times (Google internal [test run](https://fusion2.corp.google.com/invocations/54cf5dab-39d7-4101-9484-e5a9edf43be3/targets/%2F%2Fthird_party%2Fjava_src%2Fgrpc%2Fcore:src%2Ftest%2Fjava%2Fio%2Fgrpc%2Finternal%2FInstantTimeProviderTest/tests))

With 75ms it still failed but only for 10 / 10000 (Google internal [test run](https://fusion2.corp.google.com/invocations/be49b6b0-190e-43aa-958c-bc81e31abde9/targets/%2F%2Fthird_party%2Fjava_src%2Fgrpc%2Fcore:src%2Ftest%2Fjava%2Fio%2Fgrpc%2Finternal%2FInstantTimeProviderTest/tests)).

I think we can set the tolerance as 75ms.

**Comment by ejona86** [comment]
How about setting it to 100 ms or 1 second, so we don't deal with it again? 75 ms is already too large to notice precision issues, so I'm not sure what we gain by using 75 ms instead of 1 second.

**Comment by ejona86** [comment]
This recently flaked when not running with TSAN. http://sponge2/973b69a4-998c-457f-a496-c49bc8c3eef0

**Comment by kannanjgithub** [comment]
Yes, lets make it 1s. @vinodhabib
