### ISSUE TITLE
s2a: repositories.bzl override does not point to a target

### ISSUE THREAD

**Issue by karanjamutahi** [grpc/grpc-java#11703]
### What version of gRPC-Java are you using?
1.68.1

### What is your environment?

Linux, jdk 23.0.1, bazel version 7.4.1

### What did you expect to see?
@@[io_grpc_grpc_java//s2a](https://github.com/grpc/grpc-java/blob/32f4cf432a5258af64822e3dadde2778f389c260/repositories.bzl#L84) points to a bazel target

### What did you see instead?
There is no target called s2a in @@io_grpc_grpc_java//s2a i.e. @@io_grpc_grpc_java//s2a:s2a

### Steps to reproduce the bug
bazel query @@io_grpc_grpc_java//s2a

We added an override to point io.grpc:grpc-s2a to [@@io_grpc_grpc_java//s2a:s2av2_credentials](https://github.com/grpc/grpc-java/blob/32f4cf432a5258af64822e3dadde2778f389c260/s2a/BUILD.bazel#L82) which is what I think the [gradle](https://github.com/grpc/grpc-java/blob/32f4cf432a5258af64822e3dadde2778f389c260/s2a/build.gradle#L74) build publishes to maven

I think the test mentioned in #3918 can at least bazel query that the values in IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS resolve to a target ?

**Comment by ejona86** [comment]
Are you using s2a? Or did you notice by some other means?

**Comment by ejona86** [comment]
@rmehta19, I think we should rename s2av2_credentials to s2a, as "v2" means nothing to any user (or me) and we rarely get much benefit from fine-grained targets (I think grpc-services is the main exception). If we want to avoid dependencies, we have to put the code in separate packages and artifacts anyway for Maven Central. So we should also swap to using a glob on `src/main/java/io/grpc/s2a/*.java` like we do elsewhere.

**Comment by karanjamutahi** [comment]
> Are you using s2a? Or did you notice by some other means?

We don't. 
A transitive dep complained that it couldn't find it. `com_google_cloud_google_cloud_resourcemanager`

**Comment by ejona86** [comment]
Fixed by #11705
