### ISSUE TITLE
Will grpc-java keep up with the latest final version of netty?

### ISSUE THREAD

**Issue by liujingjun001** [grpc/grpc-java#11704]
the netty released netty 4.2 version, the lastest is [Netty 4.2.0.Beta1 released](https://netty.io/news/2024/11/04/4-2-0-Beta1.html).

if 4.2 final released.

will the grpc-java follow 4.2 finnal version netty? or aways keep in 4.1.xxx final version of netty?

**Comment by kannanjgithub** [comment]
Yes we will upgrade to 4.2 after 4.2 final is released but the time to upgrade varies considerably, depending on the difficulty (there are many Google internal tests to be run and passed). 

Note: If using grpc-netty, you can choose the version of Netty and wouldn't need to wait for us. But there would be a performance regression if you upgrade to 4.1.111+.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
