### ISSUE TITLE
Client-Side Direct Memory Continuously Increases When Server-Side Message Processing is Slow

### ISSUE THREAD

**Issue by jammyMarse** [grpc/grpc-java#11712]
**Description**: 
We are encountering an issue in a bidirectional streaming scenario where the client-side out-of-heap memory continuously grows even though the server-side is slow in processing messages. Our client checks stream.isReady() before sending messages, expecting this method to prevent further messages from being sent if the server is backlogged. However, despite this check, the client's out-of-heap memory keeps increasing. This behavior suggests that messages are not being properly regulated by the stream.isReady() check under certain conditions.

**Steps to Reproduce**:
1. Set up a gRPC server that intentionally delays processing incoming messages.
2. Configure a client to send messages in a loop, checking stream.isReady() before each send.
3. Monitor the client's out-of-heap memory usage.

**Expected Behavior**: The client's out-of-heap memory should not increase significantly, as stream.isReady() should block sending new messages when the server is unable to process them quickly.

**Actual Behavior**: Client out-of-heap memory increases continuously, indicating that stream.isReady() does not effectively prevent message dispatch during slow server response times.

**Environment**:
gRPC version: [1.66.0]
JDK version: [JDK17]

**Comment by ejona86** [comment]
> despite this check, the client's out-of-heap memory keeps increasing

Can you give numbers here? How much memory is out-of-heap?

There are caches involved that don't return the memory immediately because Java is very slow in allocating it. Normal usage patterns would have it grow for a bit and then stop.

How big are you messages? Roughly, like 1 KB, 100 KB, 1 MB?

**Comment by jammyMarse** [comment]
**ClientCallImpl:**
![image](https://github.com/user-attachments/assets/2e54a68a-a407-49d1-a362-39fe361452a0)
**MessageFramer:**
![image](https://github.com/user-attachments/assets/4c6e0c91-3913-46f4-9142-c62ed3deed78)
![image](https://github.com/user-attachments/assets/407fa994-d8d7-4dbb-a60f-f1d689bef9af)
![image](https://github.com/user-attachments/assets/5e878041-212e-4371-9d63-50f8a6e99af8)
**NettyWritableBufferAllocator:**
![image](https://github.com/user-attachments/assets/9c3a3ed7-dc5b-4ca8-a5ef-b8fe7a28fcc0)

**In non-unaryRequest mode, 4096 bytes of off-heap memory will be re-applied for each message**
**If you send small packet requests frequently (for example, 100 bytes each time), a lot of external memory will be wasted, and this 4096 optimization logic will not take effect.**
