### ISSUE TITLE
How to compile .proto files to project folder?

### ISSUE THREAD

**Issue by AlexInCube** [grpc/grpc-java#11711]
I want to compile just the files into the root of the project, but I'm having trouble. I tried to make this code, but it gives an error.
My proto files are above the Java project in the hierarchy, because the Java project is one of the projects in the monorepository.

```
Illegal char <:> at index 81: C:\webprojects\micro-keynadi\apps\eximia-auth\build\generated\source\proto\main\C:\webprojects\micro-keynadi\apps\eximia-auth\src\main\generatedProto
```

```java
plugins {
    id 'java'
    id 'eclipse'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.1.8'
    id 'com.google.protobuf' version '0.9.4'
}

sourceSets {
    main {
        proto {
            srcDir '../../proto'
        }
        java {
            srcDir "${projectDir}/src/main/generatedProto"
        }
    }
}


protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.5"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.68.1'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    outputSubDir = "${projectDir}/src/main/generatedProto"
                }
            }
            task.plugins {
                grpc {
                    outputSubDir = "${projectDir}/src/main/generatedProto"
                }
            }
        }
    }
}
```

**Comment by ejona86** [comment]
`outputSubDir` can't move it to another part of the tree. It is a subdirectory. That's why there's the random broken C: in the middle of the string "...proto\main\C:\webprojects...". I suggest deleting the `outputSubDir` lines

**Comment by ejona86** [comment]
You can use a separate `Sync` or `Copy` task into the folder of your choosing. https://github.com/google/protobuf-gradle-plugin/issues/722 tracks letting it be configured.

**Comment by kannanjgithub** [comment]
The generateProtoTasks plugin uses the default outputSubDir of build/generated/source/proto/main under which it will create a "java" and "grpc" subdirs for the generated sources for the protos and the service respectively.  So in your source sets you need to also replace the paths for Java (for IDEs to pick up) to

        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }

Refer ([example](https://github.com/grpc/grpc-java/blob/7f9c1f39f38647a23f9321fe3ab0f72648055bfa/examples/example-tls/build.gradle#L51)).

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
