### ISSUE TITLE
SIGSEGV from grpc-netty-shaded 1.68+ (possible glibc dependency)

### ISSUE THREAD

**Issue by bcwhite-code** [grpc/grpc-java#11727]
OS type and version:  eclipse-temurin:23-jre-alpine

After updating `grpc-netty-shaded` from 1.66.0 to 1.68.0, I get a SEGV (signal 11) errors from my Cloud-Run app which is based on the `eclipse-temurin:23-jre-alpine` Docker image.

I get this output:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000204b6, pid=1, tid=47
#
# JRE version: OpenJDK Runtime Environment Temurin-23.0.1+11 (23.0.1+11) (build 23.0.1+11)
# Java VM: OpenJDK 64-Bit Server VM Temurin-23.0.1+11 (23.0.1+11, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# C  [libio_grpc_netty_shaded_netty_tcnative_linux_x86_644709796197324429504.so+0x2a154]  netty_internal_tcnative_SSLContext_JNI_OnLoad+0x9c4
#
# Core dump will be written. Default location: Core dumps may be processed with "/wsl-capture-crash %t %E %p %s" (or dumping to /app/core.1)
#
# An error report file with more information is saved as:
# /app/hs_err_pid1.log
[28.981s][warning][os             ] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

I did a lot of bisection to confirm the "shaded_netty" line of the message and it is indeed that package that causes the problem.  The only other change that I wasn't able to test separately was the update of `grpc-util`, also from 1.66 to 1.68.

It works fine when run from the IDE (IntelliJ IDEA) but not from the container.  I believe the latest version of `grpc-netty-shaded` has a hidden dependency on `glibc` (since Alpine is based on `musl libc`) and this seems confirmed because changing the image to `eclipse-temurin:23-jre` (`glibc` based) allows the library to work correctly.

This is preventing me from updating to the latest version of many libraries, including `vertextai` and `aiplatform`.

**Comment by RaymonddC** [comment]
Hi, I already tried to add gcompat. but i got the same issue like this [post](https://github.com/grpc/grpc-java/issues/8751#issuecomment-1112549548)

note: I am trying to add `com.google.cloud:google-cloud-dialogflow-cx:0.64.0` on my project but got the SIGSEGV errors
`SIGSEGV (0xb) at pc=0x00000000000204b6, pid=1, tid=7`
