### ISSUE TITLE
Feature Request: Support for Sending Headers in onCompleted() in gRPC Service

### ISSUE THREAD

**Issue by fatemeAfshani** [grpc/grpc-java#11720]
Description
I have a gRPC endpoint that I call via a REST API. The relevant gRPC service definition is as follows:

```
rpc myEndpoint(SampleRequest) returns (SampleResponse) {  
    option (google.api.http) = {  
      post: "/api/v1/endpoint/sample"  
    };  
}  
```
In my endpoint implementation, I want to set a cookie for the client containing a token after performing some logic checks. However, I currently cannot send headers (metadata) back to the client as needed.

Here is the relevant part of my gRPC service function:

```
override fun myEndpoint(request: SampleRequest, responseObserver: StreamObserver<SampleResponse>) {  
    val (result, token) = checkLogic()  

    responseObserver.onNext(result)  

    val headers = Metadata()  
    headers.put(  
        Metadata.Key.of("Set-Cookie", Metadata.ASCII_STRING_MARSHALLER),  
        "accessToken=$token; Path=/; HttpOnly"  
    )  

    responseObserver.onCompleted()  // Metadata is not sent here  
}
```  

The current implementation of the onCompleted() function in the gRPC library looks like this (from io.grpc/stub/ServerCalls.class):

```
public void onCompleted() {  
    this.call.close(Status.OK, new Metadata());  
    this.completed = true;  
}
```  
I want to know if it's possible for this onCompleted() function to accept metadata as input instead of always sending new Metadata(), like so:

```
public void onCompleted(Metadata metadata) {  
    Metadata effectiveMetadata = metadata == null ? new Metadata() : metadata;  
    this.call.close(Status.OK, effectiveMetadata);  
    this.completed = true;  
}  
```
Attempted Solution
I also tried to override the onCompleted() function in my server interceptor, but that didn't work as intended:

```
@GRpcGlobalInterceptor  
@Component  
class UserInfoInterceptor : ServerInterceptor {  
    private val userIdCtxKey = Context.key<String>("userId")  
    private val userRoleCtxKey = Context.key<String>("role")  

    override fun <ReqT : Any?, RespT : Any?> interceptCall(  
        call: ServerCall<ReqT, RespT>,  
        headers: Metadata,  
        next: ServerCallHandler<ReqT, RespT>  
    ): ServerCall.Listener<ReqT> {  
        val ctx: Context = this.extractUserInfo(headers)  
        val listener = Contexts.interceptCall(ctx, call, headers, next)  

        return object : ForwardingServerCallListener.SimpleForwardingServerCallListener<ReqT>(listener) {  
            override fun onComplete() {  
                val token = TokenStore.getToken()  

                if (token != null) {  
                    val headersToSend = Metadata()  
                    headersToSend.put(Metadata.Key.of("Set-Cookie", Metadata.ASCII_STRING_MARSHALLER), "accessToken=$token; Path=/; HttpOnly")  
                    // Here we need to send the headers, but it’s already completed.  
                }  

                super.onComplete()  
            }  
        }  
    }  
}  
```
I think The reason my interceptor doesn't work is because the response is already completed in my service before I get a chance to add metadata to the headers.

Request
Is it feasible to modify the onCompleted() function to accept metadata, or alternatively, can you suggest a way to send metadata back to the client after the service logic is executed? Any guidance on achieving this would be greatly appreciated.

Additional Information
gRPC Version: io.grpc/grpc-stub version 1.49.0
Language: Kotlin
Thank you for your attention to this matter! I look forward to any updates or potential solutions.

**Comment by kannanjgithub** [comment]
It should already be possible, see [this example](https://github.com/grpc/grpc-java/blob/7f9c1f39f38647a23f9321fe3ab0f72648055bfa/examples/src/main/java/io/grpc/examples/header/HeaderServerInterceptor.java#L48). You should be calling super.sendHeaders.

**Comment by fatemeAfshani** [comment]
Thank you so much! I created another interceptor and overwrote the sendHeaders function, similar to the example you mentioned.

My current issue is that there is no default context for normal ForwardingServerCalls; we only have a context for ForwardingServerCallListener (ContextualizedServerCallListener). Is there a reason why this is not built into the library?

In my code (below), I created a ThreadLocal called CookieStorage to set data in the application and retrieve it in the interceptor. Is this safe? Is there a better way to store data that is only related to a request?


`@GRpcGlobalInterceptor
@Component
class ResponseHandlerInterceptor : ServerInterceptor {

    override fun <ReqT : Any?, RespT : Any?> interceptCall(
        call: ServerCall<ReqT, RespT>,
        headers: Metadata,
        next: ServerCallHandler<ReqT, RespT>
    ): ServerCall.Listener<ReqT> {

        return next.startCall(object : SimpleForwardingServerCall<ReqT, RespT>(call) {
            override fun sendHeaders(responseHeaders: Metadata) {
                val cookieData = CookieStorage.get()
                if (cookieData != null) {
                    responseHeaders.put(Metadata.Key.of("Set-Cookie", Metadata.ASCII_STRING_MARSHALLER), cookieData)
                }
                CookieStorage.clear()
                super.sendHeaders(responseHeaders)
            }

        }, headers)
    }
}`

**Comment by fatemeAfshani** [comment]
it worked, thanks a lot
