### ISSUE TITLE
Compatibility with virtual threads

### ISSUE THREAD

**Issue by danishnawab** [grpc/grpc-java#11726]
I wanted to know the current gRPC-java compatibility with virtual threads (in Java 23).

I plan to configure `io.grpc.ServerBuilder#executor` with a `java.util.concurrent.Executors#newVirtualThreadPerTaskExecutor` but I am mindful of the current limitations of virtual threads regarding `synchronized` blocks where it pins the underlying platform thread [1], which can lead to deadlocks under certain conditions [2].

In issue https://github.com/grpc/grpc-java/issues/9785, there was a discussion that touched upon this:
> might replace some intrinsic locks with full locks

This made me wonder if the usage of `synchronized` blocks within gRPC-java could be susceptible to the same problems. Application code notwithstanding. 

I know that the synchronized pinning problem will go away in Java 24 [3], but I would like to know if we could already start benefitting from virtual threads in Java 23, or should we wait until 24 for the above reason?

[1] https://openjdk.org/jeps/444
[2] https://netflixtechblog.com/java-21-virtual-threads-dude-wheres-my-lock-3052540e231d
[3] https://openjdk.org/jeps/491

**Comment by ejona86** [comment]
There are no known intrinsic locks that need to be replaced. Most of the code is async, so wouldn't need adjustments. The blocking stub uses LockSupport, so should be fine. We've not heard of any problems.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
