### ISSUE TITLE
Idea: Expose Metadata from Status

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1173]
The Status object is almost always created from Metadata; it would be logical to expose the Metadata from status.  This would make it possible to get access to the Trailers from a call without resorting to using Context or an Interceptor.

**Comment by carl-mastrangelo** [comment]
cc: @louiscryan

**Comment by jcanizales** [comment]
I think this is something we should do in all the languages.

**Comment by ejona86** [comment]
> The Status object is almost always created from Metadata

Not quite true. On client-side, it is almost always created from Metadata, on server-side it never is.

That said, something like this could be really helpful. I am a bit worried about how interceptors and such behave if there are two metadata flowing around, and how metadata on server-side will work out. Maybe we should just get rid of the extra trailing metadata argument... but I'm not certain about that.

**Comment by ejona86** [comment]
@carl-mastrangelo, would you agree this is mostly a dup of #681?

**Comment by carl-mastrangelo** [comment]
Yes
