### ISSUE TITLE
XdsTestServer: server_id field not up to spec

### ISSUE THREAD

**Issue by sergiitk** [grpc/grpc-java#11747]
Unless provided via `--server_id` shell argument, XdsTestServer sets `SimpleResponse.server_id` to the default  `"java_server"`:

https://github.com/grpc/grpc-java/blob/921f88ae30e5a4b1d890f3ea7ff709f475a86298/interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java#L87

https://github.com/grpc/grpc-java/blob/921f88ae30e5a4b1d890f3ea7ff709f475a86298/interop-testing/src/main/java/io/grpc/testing/integration/XdsTestServer.java#L330-L332

```console
❯ docker run --rm us-docker.pkg.dev/grpc-testing/psm-interop/java-server:v1.69.x --help
Usage: [ARGS...]
...
  --server_id=STRING  server ID for response.
                      Default: java_server
...
```

However, according to the spec, this field is supposed to be unique per server instance:
https://github.com/grpc/grpc-java/blob/921f88ae30e5a4b1d890f3ea7ff709f475a86298/interop-testing/src/main/proto/grpc/testing/messages.proto#L118-L120

This doesn't seem to break anything now (except the spec :trollface:).
However, since Java's xds test server implementation is considered canonical, we should fix this.

**Comment by sergiitk** [comment]
cc @murgatroid99 @ejona86

**Comment by ejona86** [comment]
From what I can tell, this is completely unused. It looks to be added for pick_first_unary which I don't see any callers for.

I don't think it was implemented incorrectly. All languages behave the same, with a fixed string. I think the documentation is just misleading, saying how it _can_ be used. It's introduction in [C++](https://github.com/grpc/grpc/commit/1d59b25dea44fe0bd66b2345e36d5e6205b77b74) and [Java](https://github.com/grpc/grpc-java/commit/d914e011b02c3a3d8033bf9484ba3b4bd56a41c6) by Gribkoff when he was making the xds interop system, so he would have known the "correct behavior." [Python has the same behavior](https://github.com/grpc/grpc/blob/11b971eea9639d1dd217a5d159f17793bfb74563/src/python/grpcio_tests/tests_py3_only/interop/xds_interop_server.py#L209), but it was implemented later.

For reference, the PR adding it to the test protos: https://github.com/grpc/grpc-proto/pull/51

**Comment by sergiitk** [comment]
Makes sense. Nothing to do then, closing.
