### ISSUE TITLE
Connection window should auto-refill

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#1175]
Consider an application with 2 streams, A and B. A receives a stream of messages and the application pops off one message at a time and makes a request on stream B. However, if receiving of data on A has caused the connection window to collapse, B will not be able to receive any data and the application will deadlock. The only way (currently) to get around this is to use multiple connections for the streams, which would needlessly complicate the application code.

The C implementation already solves the problem by auto-refilling the connection window, so Java and the other languages should just follow suit here.

Created PR https://github.com/netty/netty/pull/4423 in Netty to support configuring the local flow controller to auto-refill.  Until that's in, we should probably just set the connection window to MAX_INT for now.

@louiscryan @ejona86 @ctiller @a11r

**Comment by madongfly** [comment]
Does the `auto-refill` need to respect the window update threshold?

**Comment by nmittler** [comment]
@madongfly I'm not sure exactly what you mean by "window update threshold"? It will still refill after the connection window drops to half full (or half empty if you're a pessimist :)) and when it refills it will restore the full size of the connection window.  It will just perform these checks immediately upon receiving data rather than waiting for the application to consume the bytes.

The stream windows, however, will continue to function as they do today ... window update will not be issued until the application has consumed the bytes.

**Comment by madongfly** [comment]
Thanks Nathan, I wanted to know whether `auto-refill` refills for each message or refills after the consumed tokens exceeds the window update threshold, the window update threshold in this case is `half of the original`. 

I was asking to confirm that OkHttp transport is doing correct, and now it is confirmed.

**Comment by nmittler** [comment]
https://github.com/netty/netty/pull/4423 has been committed. We can pick this up after the next Netty 4.1.x release.
