### ISSUE TITLE
Buffer RPC Calls for when the MAX_CONCURRENT_STREAMS limit is hit.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#118]
The number of concurrent RPC calls we can do is limited by HTTP2's `MAX_CONCURRENT_STREAMS` setting. Currently when using Netty as the client transport, each call made after this limit is reached blocks its calling thread until the number of active streams goes below the maximum again. The blocking is necessary as otherwise Netty would simply reject the stream with a PROTOCOL_ERROR, thus we want to buffer those calls and only pass them to Netty once there is room for new streams again.

Similar to #116 a user would again expect asynchronous behavior here.

The proposed solution to this problem is to remove the before mentioned buffering / blocking from grpc-java and let Netty handle it instead. To do this we will add a new `Http2ConnectionEncoder` implementation to Netty that acts as a decorator to the `DefaultHttp2ConnectionEncoder`. It will intercept calls to `writeHeaders`, `writeData` and `writeRstStream` and buffer all frames of streams that have been created after the maximum streams limit was reached and pass through the others. The encoder will also add a listener to the connection so that when an active stream is closed the next stream from the buffer can be created. A call to `writeRstStream` will cause the buffered stream to be deleted from the buffer. Frames other than HEADERS, DATA and RST_STREAM will be passed directly to the `DefaultHttp2ConnectionEncoder`.

We propose to contribute this change back to Netty as it will likely also be useful for other people using Netty's HTTP2 codec.

**Comment by rschildmeijer** [comment]
As long as the Netty buffer/queue size is exposed in th ePAI and configurable by end users the proposed solution sounds sane.
