### ISSUE TITLE
Can not build grpc-java in Linux Centos 7

### ISSUE THREAD

**Issue by bangph** [grpc/grpc-java#1189]
Hi, I need to build grpc-java in Linux Centos 7 but had a problem, please help

../gradlew java_pluginExecutable
*** Building codegen requires Protobuf version 3.0.0-beta-1
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin
:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp UP-TO-DATE
:grpc-compiler:linkJava_pluginExecutable
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status

:grpc-compiler:linkJava_pluginExecutable FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-compiler:linkJava_pluginExecutable'.
> A build operation failed.
      Linker failed while linking protoc-gen-grpc-java.
  See the complete log at: file:///home/rasdaman/test_server/rasdaman/GRPC/grpc/grpc_java_root/compiler/build/tmp/linkJava_pluginExecutable/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.732 secs

**Comment by carl-mastrangelo** [comment]
*** Building codegen requires Protobuf version 3.0.0-beta-1

Do you have that version of protobuf?

**Comment by bangph** [comment]
yes, I have 

cd third_party/protobuf/
[rasdaman@gonzo protobuf]$ ls -l
total 1944
-rw-rw-r--.  1 rasdaman rasdaman  42332 Nov  5 09:43 aclocal.m4
-rw-rw-r--.  1 rasdaman rasdaman    799 Nov  5 09:40 appveyor.bat
-rw-rw-r--.  1 rasdaman rasdaman    805 Nov  5 09:40 appveyor.yml
-rwxr-xr-x.  1 rasdaman rasdaman   5826 Nov  5 09:43 ar-lib
-rwxrwxr-x.  1 rasdaman rasdaman    983 Nov  5 09:40 autogen.sh
drwxrwxr-x.  2 rasdaman rasdaman   4096 Nov  5 09:40 benchmarks
-rw-rw-r--.  1 rasdaman rasdaman  20006 Nov  5 09:40 BUILD
-rw-rw-r--.  1 rasdaman rasdaman  44954 Nov  5 09:40 CHANGES.txt
drwxrwxr-x.  2 rasdaman rasdaman   4096 Nov  5 09:40 cmake
-rwxr-xr-x.  1 rasdaman rasdaman  45297 Nov  5 09:43 config.guess
-rw-rw-r--.  1 rasdaman rasdaman   4166 Nov  5 09:43 config.h
-rw-rw-r--.  1 rasdaman rasdaman   3759 Nov  5 09:43 config.h.in
-rw-rw-r--.  1 rasdaman rasdaman  59732 Nov  5 10:00 config.log
-rwxrwxr-x.  1 rasdaman rasdaman  72940 Nov  5 10:00 config.status
-rwxr-xr-x.  1 rasdaman rasdaman  35533 Nov  5 09:43 config.sub
-rwxrwxr-x.  1 rasdaman rasdaman 611969 Nov  5 09:43 configure
-rw-rw-r--.  1 rasdaman rasdaman   5782 Nov  5 09:40 configure.ac
drwxrwxr-x.  3 rasdaman rasdaman   4096 Nov  5 10:00 conformance
-rw-rw-r--.  1 rasdaman rasdaman   3924 Nov  5 09:40 CONTRIBUTORS.txt
drwxrwxr-x.  5 rasdaman rasdaman   4096 Nov  5 09:40 csharp
-rwxr-xr-x.  1 rasdaman rasdaman  23566 Nov  5 09:43 depcomp
drwxrwxr-x.  2 rasdaman rasdaman   4096 Nov  5 09:40 editors
drwxrwxr-x.  2 rasdaman rasdaman   4096 Nov  5 09:40 examples
-rwxrwxr-x.  1 rasdaman rasdaman   2984 Nov  5 09:40 generate_descriptor_proto.sh
drwxr-xr-x. 12 rasdaman rasdaman   4096 Nov  5 10:00 gmock
-rw-rw-r--.  1 rasdaman rasdaman    535 Nov  5 09:40 gmock.BUILD
-rwxr-xr-x.  1 rasdaman rasdaman  13997 Nov  5 09:43 install-sh
-rw-rw-r--.  1 rasdaman rasdaman   9537 Nov  5 09:40 INSTALL.txt
drwxrwxr-x.  4 rasdaman rasdaman   4096 Nov  5 09:40 java
drwxrwxr-x.  3 rasdaman rasdaman   4096 Nov  5 09:40 javanano
-rwxrwxr-x.  1 rasdaman rasdaman 298861 Nov  5 10:00 libtool
-rw-rw-r--.  1 rasdaman rasdaman   2131 Nov  5 09:40 LICENSE
-rw-r--r--.  1 rasdaman rasdaman 283474 Nov  5 09:43 ltmain.sh
drwxrwxr-x.  2 rasdaman rasdaman   4096 Nov  5 09:43 m4
-rw-rw-r--.  1 rasdaman rasdaman  78246 Nov  5 10:00 Makefile
-rw-rw-r--.  1 rasdaman rasdaman  50146 Nov  5 09:40 Makefile.am
-rw-rw-r--.  1 rasdaman rasdaman  77813 Nov  5 09:43 Makefile.in
-rwxr-xr-x.  1 rasdaman rasdaman   6873 Nov  5 09:43 missing
drwxrwxr-x.  2 rasdaman rasdaman   4096 Nov  5 09:40 more_tests
drwxrwxr-x.  7 rasdaman rasdaman   4096 Nov  5 09:40 objectivec
-rwxrwxr-x.  1 rasdaman rasdaman   1834 Nov  5 09:40 post_process_dist.sh
-rw-rw-r--.  1 rasdaman rasdaman    294 Nov  5 10:00 protobuf-lite.pc
-rw-rw-r--.  1 rasdaman rasdaman    298 Nov  5 09:40 protobuf-lite.pc.in
-rw-rw-r--.  1 rasdaman rasdaman    313 Nov  5 10:00 protobuf.pc
-rw-rw-r--.  1 rasdaman rasdaman    319 Nov  5 09:40 protobuf.pc.in
-rw-rw-r--.  1 rasdaman rasdaman   2146 Nov  5 09:40 Protobuf.podspec
drwxrwxr-x.  2 rasdaman rasdaman   4096 Nov  5 09:40 protoc-artifacts
drwxrwxr-x.  3 rasdaman rasdaman   4096 Nov  5 09:40 python
-rw-rw-r--.  1 rasdaman rasdaman   6752 Nov  5 09:40 README.md
drwxrwxr-x.  6 rasdaman rasdaman   4096 Nov  5 09:40 ruby
drwxrwxr-x.  5 rasdaman rasdaman   4096 Nov  5 10:04 src
-rw-rw-r--.  1 rasdaman rasdaman     23 Nov  5 10:00 stamp-h1
-rwxr-xr-x.  1 rasdaman rasdaman   3977 Nov  5 09:43 test-driver
-rwxrwxr-x.  1 rasdaman rasdaman   4982 Nov  5 09:40 travis.sh
-rwxrwxr-x.  1 rasdaman rasdaman   6091 Nov  5 09:40 update_file_lists.sh
-rw-rw-r--.  1 rasdaman rasdaman    360 Nov  5 09:40 WORKSPACE

and also installed by 

./autogen.sh
./configure
make
[sudo] make install

**Comment by carl-mastrangelo** [comment]
And the output of the log file?

**Comment by bangph** [comment]
here is log file out GRPC JAVA in compile/build/tmp/linkJava_pluginExecutable.

See file:///home/rasdaman/test_server/rasdaman/GRPC/grpc/grpc_java_root/compiler/build/tmp/linkJava_pluginExecutable/output.txt for all output for linkJava_pluginExecutable.
linking protoc-gen-grpc-java failed.
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status

Finished linkJava_pluginExecutable, see full log file:///home/rasdaman/test_server/rasdaman/GRPC/grpc/grpc_java_root/compiler/build/tmp/linkJava_pluginExecutable/output.txt.

**Comment by bangph** [comment]
I have no idea how to fix this problem, so please give me an advice after you have.

**Comment by carl-mastrangelo** [comment]
/usr/bin/ld: cannot find -lstdc++
do you have libstdc++ ?

**Comment by bangph** [comment]
I think I have installed it before 

yum list libstdc++*
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: ftp.plusline.de
 * epel: vesta.informatik.rwth-aachen.de
 * extras: ftp.plusline.de
 * nux-dextop: li.nux.ro
 * updates: ftp.plusline.de
Installed Packages
libstdc++.i686                                      4.8.3-9.el7                             @base    
libstdc++.x86_64                                    4.8.3-9.el7                             @anaconda
libstdc++-devel.x86_64                              4.8.3-9.el7                             @base    
Available Packages
libstdc++-devel.i686                                4.8.3-9.el7                             base     
libstdc++-docs.x86_64                               4.8.3-9.el7                             base     
libstdc++-static.i686                               4.8.3-9.el7                             base     
libstdc++-static.x86_64                             4.8.3-9.el7                             base

**Comment by bangph** [comment]
Hey,

After install libstdc++static I think it is success, please check log


See file:///home/rasdaman/test_server/rasdaman/GRPC/grpc/grpc_java_root/compiler/build/tmp/linkJava_pluginExecutable/output.txt for all output for linkJava_pluginExecutable.
linking protoc-gen-grpc-java successful.

Finished linkJava_pluginExecutable, see full log file:///home/rasdaman/test_server/rasdaman/GRPC/grpc/grpc_java_root/compiler/build/tmp/linkJava_pluginExecutable/output.txt.

**Comment by bangph** [comment]
Hey, did I take you too much time? it is good right?

**Comment by carl-mastrangelo** [comment]
That looks right.  You can do .gradlew build now and it should print out success.

**Comment by ejona86** [comment]
I'm glad it looks like you were able to get the codegen compiling. Note that generally we would expect you [to use -PskipCodegen=true](https://github.com/grpc/grpc-java/blob/master/README.md), unless you want to modify the codegen or modify one of our protos used in tests.

**Comment by ejona86** [comment]
It looks like the issue was resolved.
