### ISSUE TITLE
Java to Java RPC calls, without the proto IDL files and Proxy apart from stub.

### ISSUE THREAD

**Issue by supercharger** [grpc/grpc-java#1196]
In Java, the builtin RPC mechanism "RMI" and serialization mechanism is very old, and has many severe issues with timeouts, soft versioning, etc. So, with distributed java to java services which happens naturally when the services are evolved over time, the following kind of API is preferred which is a Java Proxy based instead of stub.

``` java

ExampleService exampleService = grpcClientManager.get(ExampleService.class).build();
exampleService.sayHello();

public interface ExampleService {
    public String sayHello();
    public Future<String> sayHi();
}
```

For Java-to-Java calls, Building stubs and IDL files are unintuitive and extra efforts, better to make use of marking the interfaces with annotations.  I searched and found a similarly implemented library called  [Swift](https://github.com/facebook/swift) for Thrift . It would be great if grpc supports annotation based one, 

Ex:https://github.com/facebook/fbthrift/blob/master/thrift/tutorial/java/swift/client/src/main/java/com/facebook/swift/exampleclient/ExampleService.java

I feel it is easier and simple, with Java proxy apart from stub. We will be able to always generate the proto IDL files from the java source for RPC with other languages.

**Comment by ejona86** [comment]
We're not against this idea and have discussed it internally before. But we have a lot of other things that seemed more important, so it's not currently on our road map.

Both protobuf (assuming protobuf) and gRPC would need to we wired up to observe the annotations. I think that is possible using only normal gRPC and protobuf APIs, so you are welcome to experiment.

**Comment by supercharger** [comment]
For this to be effective, gRPC needs to support multiple method parameters.
If we need to rewrite the existing implementation, this feature won't make much sense.

https://groups.google.com/forum/#!topic/protobuf/9JNzY1BMNI4

**Comment by ejona86** [comment]
Not entirely. You can expand the main message into its various fields.

Given:
```
message MessageTransfer {
    required User recipient = 1;
    required ChatMessage msg = 2;
}


service ChatService {
    rpc sendmessage(MessageTransfer) returns (StatusResponse);
}
```

Generate a method like:
```
public StatusResponse sendmessage(User recipient, ChatMessage msg);
```

And then in the generated code you could create MessageTransfer based on the parameters.

**Comment by supercharger** [comment]
Yes, We can wrap the parameters with another type.

Let's say we have following existing interface,
``` java
public interface ExampleService {
    public StatusResponse sendmessage(User recipient, ChatMessage msg);
}
```
To enable this existing interfaces to be RPC enabled, we mark them with annotation. If it ends with that it is really nice. 

``` java
@GrpcService
public interface ExampleService {
    @GrpcMethod
    public StatusResponse sendmessage(User recipient, ChatMessage msg);
}
```
But, as grpc doesn't support multiple parameters, we either has to generate some stub, or modify existing interfaces with wrapper methods ( which will bloat). Also, at the same time, we don't want to change the ***ExampleService client code***. But, the main intention of this feature request ( 1196) is to not to have codegen, or changes.

``` java
@GrpcService
public interface ExampleService {
     \*GrpcMethod is removed, as the wrapper method exposes it.*/
    public StatusResponse sendmessage(User recipient, ChatMessage msg);

      @GrpcMethod
     public StatusResponse sendmessage(MessageTransfer);
}
```
So, Above require changes to ExampleService to accomdate these types ( codegen or manual).

**Comment by ejona86** [comment]
Discussed in IRC and we came up with a suggested approach. Basically, for requests create a Marshaller<Object[]> that marshals uses Coding{Input,Output}Stream directly (or an equivalent), with tags based on the index of the object within the array. That doesn't require creating any "container" classes to represent the arguments.

https://botbot.me/freenode/grpc/2015-11-13/?msg=54071798

**Comment by louiscryan** [comment]
@supercharger I suggest you take a look at the Protostuff library which does a lot of what you want. We talked to them about providing a GRPC binding, they already have their own basic RPC mechanism which would be easy to adapt.

**Comment by supercharger** [comment]
I am able to do java proxy based implementation on top of grpc-java, 
https://github.com/supercharger/grpc-proxy

While I am able to implement multiple parameters in java, the restriction of protobuf makes it hard for other RPC across cross- language.

**Comment by supercharger** [comment]
@louiscryan  I think  to integrate with Grpc, all we need to is use protostuff-runtime to "serialize to inputstream", "deserialize from inputstream" using the http://www.protostuff.io/documentation/runtime-schema/#usage

```java
byte[] protostuff = ProtostuffIOUtil.toByteArray(foo, schema, buffer);
//build inputstream from byte array
```

As for RPC, There is no support from  [protostuff for RPC](https://github.com/protostuff/protostuff/wiki/Rpc-Services) **except that it allows to generate the code** for which we already have Grpc. But, it is very useful in marshalling of java annotated objects to protobuf format which can be used in Grpc.

**Comment by ejona86** [comment]
@supercharger, would it make sense to close this issue now, or is something outstanding?

**Comment by supercharger** [comment]
@ejona86  
Thanks, I am closing this issue.
