### ISSUE TITLE
Resolve whether context cancellation propagates depth-first or breadth-first

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#1206]
Current context cancellation order is unspecified. 

Suggested algorithm is breadth-first so that higher level work is cancelled before lower-level work. The primary reason for this is that if higher-level work is cleanly cancelled then it can cleanly handle / ignore errors bubbling up from the cancellation of lower-level work. In depth-first it would be hard for higher-level work to distinguish between the failure modes bubbling up from lower-level work.

@lukesandberg
@adriancole 
@ejona86

**Comment by ejona86** [comment]
It would be quite a pain to do breadth-first cancellation of contexts. I believe what is being discussed here is order of cancellation _notification_. Basically, whether we want to notify all the listeners for a Context before cancelling child Contexts. (Which I believe we do want to do.)

**Comment by louiscryan** [comment]
Fixed by https://github.com/grpc/grpc-java/commit/73e2a235e799d38fda1b2ac61096f9d4aab2bf11
