### ISSUE TITLE
How should basic LB interact with reconnect

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1212]
If a server is available on both IPv4 and IPv6, then it will have two addresses and we will perform reconnects on the two independently. That doesn't seem too bad. Although if one of them works and the other doesn't some RPCs may occasionally (say, because we got a GOAWAY on the good connection) be routed to the bad IP's transport where it might get "stuck" for a while before erring. This could probably be solved by waiting until transports are healthy before assigning RPCs.

Some hosts have _many_ more IPs, such as google.com which has 11 IPv4 and one 1 IPv6. Having 12 TransportSets each trying to connect with independent backoff seems "not great." It's unclear what the behavior should be though. Maybe combine the backoff between all the IPv4 addresses and pick the next for each attempt?

Note also that there is interaction with #1191, since any TransportSet used once will effectively forever continue trying to connect, even if we have other transports to the same host that are healthy.

**Comment by zhangkun83** [comment]
The most obvious problems that contribute to the maintenance unnecessary connections are:
 1. `SimpleLoadBalancer`'s pick-first implementation doesn't tell `TransportManager` (implemented by `ManagedChannelImpl`) about the abandoned address. The interface is already there (`TransportManager.updateRetainedTransports()`). `SimpleLoadBalancer` needs to use it.
 2. `TransportManager.updateRetainedTransports()` is not implemented. `ManagedChannelImpl` should implement it and close transports of abandoned addresses.

**Comment by zhangkun83** [comment]
`TransportManager.updateRetainedTransports()` assumes that any addresses that do now appear in that least is due for immediate closure. It doesn't work well in cases arbitrary addresses may be given, and we still want to cache their connections for some time. One of such cases is affinity-based routing, where addresses are not given up-front, but on a per-request basis. If `TransportSet` does lazy reconnection, and the channel closes idle `TransportSet`s, it won't be necessary for `LoadBalancer` to tell the channel when to close transports, then we can just remove `updateRetainedTransports()` and use `getTransport()` for warm-up purpose.

Here is my plan:
 1. Make `TransportSet` lazy on reconnection.
 2. Make `ManagedChannelImpl` track `TransportSet` usage and close idle ones. This is to prevent leaking `TransportSet` objects.
 3. Remove `TransportManager.updateRetainedTransports()`. `LoadBalancer` will instead use `getTransport()` to warm-up connections.

Combining the backoff between IPv4 addresses doesn't sound necessary if we have made the above changes, and is more complicated than each address having its own backoff.

**Comment by ejona86** [comment]
After discussion, this is the current plan we're going to mull over:

1. Move pick-first into `TransportSet`. This is to deal with reconnect logic needing to apply to all of the IPs as a whole, instead of individually. We could maybe create a new `SocketAddress` type that lists multiple SocketAddresses within as the key for `TransportManager`.
2. Implement idleness in Channel. `TransportSet` will remain eager (in the future, it might get the _option_ to be lazy)

We could maybe do more fancy things over time, but this looks maybe good enough for a while.

**Comment by zhangkun83** [comment]
The rest of the work is a duplicate of #1191

**Comment by zhangkun83** [comment]
Revise this issue to implement channel idleness, which is needed to prevent leaking `TransportSet`.

**Comment by ejona86** [comment]
Closing this one since the main issue is addressed. I created #1276 for tracking idle support.
