### ISSUE TITLE
Okhttp transport should use resolved address.

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#1215]
Currently, OkHttp transport resolves the host name by itself, the underlying implementation tries all the resolved address one by one, until one connected successfully.

We should only connect with the passed-in resolved address, and shutdown the transport if it can not connect, let the load balance channel layer creates a new transport with a new address.

**Comment by madongfly** [comment]
@ejona86 what do you think?

**Comment by ejona86** [comment]
This is "fine," but I don't think it can happen until we have _some_ ipv4+ipv6 story better than "loop through all the IPs".

Swapping OkHttp to use the address is easy in my mind. The ipv4+ipv6 handling is the harder part.
