### ISSUE TITLE
A failing test deletes Messages.java

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1226]
When running ./gradlew build, if a test fails part way through protobuf-nano/src/generated/test/javanano/io/grpc/protobuf/nano/Messages.java  is deleted.  This causes noise when running git status or other git commands.

**Comment by ejona86** [comment]
Yeah. It's caused by the goo we're doing to clean up previously-generated code before regenerating.

https://github.com/grpc/grpc-java/blob/master/build.gradle#L97

I think implementing google/protobuf-gradle-plugin#33 is the solution, but that isn't implemented.

**Comment by ejona86** [comment]
Fixed by #1691
