### ISSUE TITLE
Grpc fails to build from clean on Windows x64 

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1242]
I suspect that the fix for this is simple, but it's still bad experience to have ```gradle.bat build``` fail on the first run.  I included the log file from trying to build.  The error happens in integration tests with "Received close_notify during handshake"

[log.txt](https://github.com/grpc/grpc-java/files/50006/log.txt)

**Comment by ejona86** [comment]
It's probably due to missing openssl, since the tests are now using tcnative. I'm not sure what way we would want to fix that.

**Comment by ejona86** [comment]
This should have been fixed when we swapped to tcnative-boringssl-static. If it's still an issue this should be reopened.
