### ISSUE TITLE
use maven plugin can not generate service code

### ISSUE THREAD

**Issue by Thinkfly** [grpc/grpc-java#1265]
I use maven plugin(maven-protoc-plugin) for generating grpc code,but i only can generate message.please help me,thx~

command: `mvn protoc:compile`

proto file:

```protobuf
syntax = "proto3";

package com.test;

option java_multiple_files = false;
option java_package = "com.test";
option java_outer_classname = "SMS";
option java_generic_services = true;

message SMSRequest {
    string phone_num = 1;
}

message SMSResponse {
    int32 code = 1;
    string time = 2;
    string message = 3;
}

service SMSService {
    rpc register(SMSRequest) returns (SMSResponse);
}
```

compile info:
```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: osx-x86_64
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test.server.sms.test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-protoc-plugin:0.4.2:compile (default-cli) @ test.server.sms.test ---
Downloading: https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.0.0-beta-1/protoc-3.0.0-beta-1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.0.0-beta-1/protoc-3.0.0-beta-1.pom (5 KB at 1.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.0.0-beta-1/protoc-3.0.0-beta-1-osx-x86_64.exe
Downloaded: https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.0.0-beta-1/protoc-3.0.0-beta-1-osx-x86_64.exe (5481 KB at 525.7 KB/sec)
[INFO] Compiling 1 proto file(s) to /Users/app/Desktop/a/test.server.sms.test/target/generated-sources/protobuf/java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.208 s
[INFO] Finished at: 2015-12-09T01:21:42+08:00
[INFO] Final Memory: 10M/191M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

**Comment by ejona86** [comment]
Do you have the following in your pom.xml in the configuration section for maven-protoc-plugin?

```xml
<pluginId>grpc-java</pluginId>
<pluginArtifact>io.grpc:protoc-gen-grpc-java:0.9.0:exe:${os.detected.classifier}</pluginArtifact>
```

(That is a snippet taken from our [README.md](https://github.com/grpc/grpc-java/blob/master/README.md))

**Comment by Thinkfly** [comment]
Yes, I use this in pom.xml,but i can't generate service code

<dependencies>

        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-all</artifactId>
            <version>0.9.0</version>
        </dependency>

    </dependencies>

    <pluginRepositories>
        <pluginRepository>
            <releases>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </pluginRepository>
        <pluginRepository>
            <id>protoc-plugin</id>
            <url>https://dl.bintray.com/sergei-ivanov/maven/</url>
        </pluginRepository>
    </pluginRepositories>
    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.4.0.Final</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>com.google.protobuf.tools</groupId>
                <artifactId>maven-protoc-plugin</artifactId>
                <version>0.4.2</version>
                <configuration>
                    
                    <protocArtifact>com.google.protobuf:protoc:3.0.0-beta-1:exe:${os.detected.classifier}
                    </protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:0.9.0:exe:${os.detected.classifier}</pluginArtifact>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by ejona86** [comment]
Looking at the [plugin documentation](http://sergei-ivanov.github.io/maven-protoc-plugin/), it seems you need to run `mvn protoc:compile-custom`.

**Comment by Thinkfly** [comment]
It works, thank you~
