### ISSUE TITLE
Fine-tune pick-first logic to honor address order

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#1267]
Naming systems may sort the addresses so that an address that appears earlier has higher priority, which means being closer and/or faster. We may want to take this into consideration when reconnecting.

Today, if a connection was made successfully and later disconnected, we try reconnecting starting from the next address, and if that succeeds we will stick with it while it may be inferior to the first addresses that may also be working.

A better approach could be starting from the first address if we just disconnected from an address that have been working. However, we should be careful of servers that can be connected and even go through TLS handshake, but have trouble serving actual RPCs. We don't want be trapped in such pitfalls. A safe logic may be: start at the beginning of the list only if the previous address has served a reasonable amount of RPC traffic.

**Comment by ejona86** [comment]
`transportReady()` is only called (for both Netty and OkHttp) after we receive the initial HTTP/2 SETTINGS frame, so we should be safe from TLS issues.

Re-starting connecting at the beginning of the list is pretty close to what "normal" applications would do.

**Comment by zhangkun83** [comment]
Resolved by #1490
