### ISSUE TITLE
Java - Write sample code for setting and reading error details

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc-java#1295]
Java issue for https://github.com/grpc/grpc/issues/4543.

**Comment by hsaliak** [comment]
@jcanizales is a test sufficient?

**Comment by jcanizales** [comment]
Yes, that works for the goals of grpc/grpc#4543.

**Comment by ejona86** [comment]
@jcanizales, how is a user expected to find the test?

**Comment by ejona86** [comment]
We do have some tests, [like this one](https://github.com/grpc/grpc-java/blob/master/stub/src/test/java/io/grpc/stub/ClientCallsTest.java#L120).

**Comment by jcanizales** [comment]
Documentation can link to the code in the tests, if it's clear enough to be useful in that respect.

Specifically of that test, it doesn't show how to get an error details proto off the trailers, nor how to set one in the server.

**Comment by jcanizales** [comment]
Hi, please note that the "error details" referred to by this issue (or its parent) aren't the error message, but a binary proto sent in the trailers as "extra details" for handling the error programatically.

**Comment by carl-mastrangelo** [comment]
I don't see that proto in our repo at all, and probably too much effort for this cycle.  Leaving this as 1.1 and unassigning.

**Comment by longXboy** [comment]
https://github.com/grpc/grpc-java/blob/60a0b0c471d720b0546ee3a5b4fa4283635dfbcf/protobuf/src/main/java/io/grpc/protobuf/StatusProto.java
StatusProto has been defined for error details
So,Any Update?

**Comment by ejona86** [comment]
This was done in #2073. It doesn't cover `StatusProto`, but is not what this was referencing.
