### ISSUE TITLE
Use a List in BlankFutureProvider instead of LinkedHashSet

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1296]
Objects added to `blankFutures` are created just before being added, so it is guaranteed there won't be duplicates. The only operations for supporting the API are `add()` and `iterate()`. Thus, `ArrayList` and `LinkedList` are both strictly better than `LinkedHashSet`.

Previously, a ConcurrentHashMap was used which allowed greater concurrency, but since #1292 added guaranteed completion order full synchronization is necessary.

**Comment by carl-mastrangelo** [comment]
Is this on the critical path for making RPCs?  If so, then #1292 should probably be reverted and the tests made able to accept out of order results.

**Comment by ejona86** [comment]
It is on the slow path, before a connection has been established. `GrpclbLoadBalancer` is required to have a "big lock" on the fast path in order to implement round robin. `SimpleLoadBalancer` is using a "big lock" right now, but _should_ be doing only a volatile read in the fast path.

Even if using an `ArrayList`, I would prefer the tests not to depend on completion order because ordering assumptions are _very_ hard to remove later. But I also don't know how much work it would take to fix the test.

**Comment by ejona86** [comment]
I hadn't noticed that there was [`remove()`](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/BlankFutureProvider.java#L81) as well, so using a `List` doesn't make as much sense.
