### ISSUE TITLE
Add interfaces to generated rpc service classes

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-java#1299]
Currently, service stub classes (not sure if it's the best name to call it) generated by gRPC don't implement any interfaces (https://github.com/grpc/grpc-java/blob/59c1a6ae26aaef2efcd7071562689aee0bd1b933/examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java#L17). It makes it impossible to dynamically build server composed of service classes provided in users's app via annotations for example.

I propose we create a `GrpcServiceStub` interface defining at least `bindService` (but we should probably add `newStub`, `newBlockingStub` and `newFutureStub` to it as well) so that we can easily cast `Class` objects to `GrpcServiceStub` and dynamically build server.

Also, it would be nice to add marker interface (``GrpcService`) to the service interfaces (https://github.com/grpc/grpc-java/blob/59c1a6ae26aaef2efcd7071562689aee0bd1b933/examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java#L48) for the same reasons.

What do you think?

cc @jh

**Comment by ejona86** [comment]
This is similar in some ways to #1280.

I'm not quite sure how we can handle the type safety for `GrpcServiceStub`. For the client stubs, the interface can return `Object` and then `newStub` in the implementation simply specifies a more specific class. That _does not_ work with the current API though, because `newStub` and similar are static, so we would need to put these new non-static implementations on a new class. But that can all work.

However, `bindService` would require a generic parameter in the class, which would prevent us from adding more types of service stubs in the future. I guess since these methods would be on some other class the argument to `bindService` could just be `Object`.

**Comment by jhump** [comment]
I think we could handle this just using reflection. For our proprietary RPC, we already have utility code (named `ServiceReflection`) for invoking static methods that are generated on the old proto service classes (those generated directly by protoc). For example, methods like `newStub` and `getDescriptor`.

This capability was dealt with in the old service code (generated by protoc) via the `Service` interface and its `callMethod` method. This made it easy to wire up a service and perform generic dispatch to service interface methods.

A possible solution with GRPC might be to generate an abstract class that implements the main service interface (but does not actually implement any of the methods, hence the class being abstract) and also implements a new interface, e.g. `BindableService`:

```java
// New API in grpc-protobuf
public interface BindableService {
  ServerServiceDefinition bindService();
}

// Generated by GRPC:
public class MyServiceGrpc {

  // blah blah blah

  public interface MyService {
    // blah blah blah
  }

  public static ServerServiceDefinition bindService(MyService serviceImpl) {
    // blah blah blah
  }

  // ---------------------------
  // New generated API. Service Implementations
  // can extend this instead of directly
  // implementing above interface.
  // ---------------------------
  public abstract class BindableMyService
      implements MyService, BindableService {
    @Overrride
    public ServerServiceDefinition bindService() {
      MyServiceGrpc.bindService(this);
    }
  }

  // sort of like newReflectiveService in protoc-generated services
  public static BindableMyService newBindableService(MyService serviceImpl) {
    return new BindableMyService {
      // ...forward all method calls to serviceImpl...
    };
  }
}
```

Admittedly, reflection will likely suffice. In fact, @lukaszx0 and I are discussing how we wire up servers with GRPC that may make this issue moot.

**Comment by ejona86** [comment]
Ah, I guess I follow along now. That can work.

I'm not sure if I see enough value in `newBindableService`, but `bindService` itself seems like it would work well and not cause any trouble. It would also improve the construction patterns with and without injection.

I think the push to have an interface (i.e., `MyService`) was why we didn't consider this before.

**Comment by lukaszx0** [comment]
Solution proposed by @jhump was incorporated in #1634 and landed on master as https://github.com/grpc/grpc-java/commit/f8b71e72b3a596f57752938fb5441f1f5ecda0b6
