### ISSUE TITLE
Status.augmentDescription violates spec

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#1303]
From Justin Rudd on mailing list...

Status.augmentDescription adds a '\n' (byte value 10) to the description of a Status which ends up in the header "grpc-message". But the value of "grpc-message" is dropped because of the method isSpecCompliantAscii in TransportFrameUtil.

I've worked around it by just not using augmentDescription. But I thought you'd like to know.

Also, it would be awesome if Status allowed for adding custom headers.

Thanks!

**Comment by ejona86** [comment]
The spec was changed to support percent-encoding special characters. #1313 is tracking implementing the change which would prevent the error seen here.
