### ISSUE TITLE
Time for the first time a rpc service is used is way longer than that of the following usage.  

### ISSUE THREAD

**Issue by LeeYeeze** [grpc/grpc-java#1304]
Hi
I would first paste my snippet here

    public void testOriginalAPI() {
		ManagedChannel grpcChannel = NettyChannelBuilder.forAddress("127.0.0.1", 60000)
        		.usePlaintext(true)
        		.build();
		
		QueryServiceInterfaceBlockingStub blockingStub =  QueryServiceInterfaceGrpc.newBlockingStub(grpcChannel);
		QueryProtocol.QueryRequest request = QueryProtocol.QueryRequest.newBuilder().setQueryString("hello").build();
		long start = System.currentTimeMillis();
		QueryProtocol.ResultInJson result = blockingStub.queryToJson(request);
		long end = System.currentTimeMillis();
		long duration = end - start;
		System.out.println("Time for first query with original API: " + duration);
		
		start = System.currentTimeMillis();
		result = blockingStub.queryToJson(request);
		end = System.currentTimeMillis();
		duration = end - start;
		System.out.println("Time for second query with original API: " + duration);
	}

And what I got from the output is:
    
    Time for first query with original API: 500ms
    Time for second query with original API: 11ms

It seems that the grpc channel is opened right at the first time it is used.
Is there any way I can get the real connection before I use it to get feedback from server.
Thanks!

**Comment by ejona86** [comment]
Yes, the connection is created only when RPCs are issued. #28 would include a way to "kick" the channel out of idle and start a connection without having to do an RPC; that will be done before 1.0.
