### ISSUE TITLE
how can i use protocol buffer's message toString() method for utf8

### ISSUE THREAD

**Issue by Thinkfly** [grpc/grpc-java#1310]
I want to print protocol buffer's message log in console ,but i use toString() method and get below info.how can i use toString for utf8,thx.

logger.info(xx.toString());

result is:

message: "\347\231\276\345\272\246\345\234\260\345\233\276\350\260\203\347\224\250\345\244\261\350\264\245:\345\205\254\351\246\206,\351\224\231\350\257\257\347\240\201:1"

**Comment by nmittler** [comment]
This is really a protobuf question (not grpc).

If it's a ByteString field, you can use ByteString.toString(UTF_8)
