### ISSUE TITLE
Deadline can fire before stream started

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1343]
In [ClientCallImpl](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L249) the deadline is scheduled before `stream.start()`. However, if the deadline has already elapsed the runnable will be executed immediately and race with the `start`. I've only looked into how OkHttp may be impacted.

I believe [a NullPointerException](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractClientStream.java#L284) would be thrown when trying to notify the stream listener [due to the cancellation](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientStream.java#L259). However, due to #1237 the exception won't be logged. Thus, this will result in a hung stream that never completes with no logging as to what went wrong.

This was discovered due to timeout_on_sleeping_server on android being flaky, because it uses a very small timeout. The test would fail at [awaitCompletion](https://github.com/grpc/grpc-java/blob/master/android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/InteropTester.java#L735).

@carl-mastrangelo, FYI

**Comment by carl-mastrangelo** [comment]
Hmmm, If the stream is cancelled before it is started, it should buffer the cancellation until start is called.  It should always be safe to call cancel, iirc.

**Comment by ejona86** [comment]
I would agree that is how the interface is, but it also is broken in all the transports due to both failure to handle the case and lack of synchronization.

`transportReportStatus` doesn't handle `null` listener. `AbstractClientStream.start` isn't synchronized when setting the listener. Netty [will NPE](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L395) when trying to send RST_STREAM (assuming `transportReportStatus` was already fixed), because `id()` has [not yet been set](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L352). `InProcessTransport` will [also NPE](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/inprocess/InProcessTransport.java#L338).
