### ISSUE TITLE
Overload ProtocolNegotiator.newHandler to accept an authority.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1358]
In the case of a load balanced channel, there is a need to provide a possibly different authority to the backend than the load balancer.  It looks like  ProtocolNegotiator.newHandler would be a good place to add this functionality.

**Comment by carl-mastrangelo** [comment]
@zhangkun83 Is this even feasible with the new LB implementation?  Is it possible to specify a different authority to the loadbalancer than the actual transport?

**Comment by zhangkun83** [comment]
It is. `LoadBalancer2.Helper.createOobChannel()`, which LoadBalancer uses to create its own transports, requires an authority, which is typically different from the backend's authority (the one in the ManagedChannelImpl).

**Comment by carl-mastrangelo** [comment]
Okay.  I'm leaving this as 1.2 since the new API is not part of 1.1

**Comment by ejona86** [comment]
This has been fixed, as part of the LBv2 API.
