### ISSUE TITLE
Update to netty-4.1.0.CR2 for SNI fix

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1398]
We want this:
https://github.com/netty/netty/commit/e220c568232fe9b479e3ac7a5b66f5a97dcc2c39

We are hitting the SNI problem (netty/netty#4746) with tests on GCE.

**Comment by ejona86** [comment]
Due to netty/netty#4856, CR2 isn't probably going to work for us. Bumping to a later grpc release and we'll wait until there is another Netty release.

**Comment by nmittler** [comment]
Fixed by #1461
