### ISSUE TITLE
Interop's deadlineExceeded test is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1399]
```
io.grpc.testing.integration.Http2NettyLocalChannelTest > deadlineExceeded FAILED
    java.lang.AssertionError: expected:<Status{code=DEADLINE_EXCEEDED, description=null, cause=null}> but was:<Status{code=INTERNAL, description=Failed to frame message, cause=io.netty.util.IllegalReferenceCountException: refCnt: 0}>
```

As seen on OS X Travis (since rebuilt):
https://travis-ci.org/grpc/grpc-java/jobs/107847923

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/131230743 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/131551606 (since rebuilt)
```
io.grpc.testing.integration.Http2NettyLocalChannelTest > deadlineExceeded FAILED
    java.lang.AssertionError: Expected deadline to be exceeded
```

**Comment by ejona86** [comment]
Saw it for non-local channel at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/3163/console

```
io.grpc.testing.integration.Http2NettyTest > deadlineExceeded FAILED
    java.lang.AssertionError: Expected deadline to be exceeded
```

**Comment by dapengzhang0** [comment]
Saw it for InProcess channel at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/3169/testReport/junit/io.grpc.testing.integration/InProcessTest/deadlineExceeded/

```
io.grpc.testing.integration.InProcessTest > deadlineExceeded FAILED
    java.lang.AssertionError: Expected deadline to be exceeded
```

**Comment by ejona86** [comment]
Saw it for non-local channel at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/3298/console
```
io.grpc.testing.integration.Http2NettyTest > deadlineExceeded FAILED
    java.lang.AssertionError: Expected deadline to be exceeded
```

**Comment by ejona86** [comment]
Saw it for TransportCompressionTest at https://travis-ci.org/grpc/grpc-java/jobs/228026098

```
io.grpc.testing.integration.TransportCompressionTest > deadlineExceeded FAILED
    java.lang.AssertionError: Expected deadline to be exceeded
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/248969436 (since rebuilt)

```
io.grpc.testing.integration.Http2NettyTest > deadlineExceeded FAILED
    java.lang.AssertionError: Expected deadline to be exceeded
```

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC-Java-PR-Windows/3734/console

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/250925402
```
io.grpc.testing.integration.InProcessTest > deadlineExceeded FAILED
    java.lang.AssertionError: Expected deadline to be exceeded
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/252191601

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/43/
```
io.grpc.testing.integration.InProcessTest > deadlineExceeded FAILED
    java.lang.AssertionError: Expected deadline to be exceeded
```

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/48/
```
java.lang.AssertionError: Expected deadline to be exceeded
	at org.junit.Assert.fail(Assert.java:88)
	at io.grpc.testing.integration.AbstractInteropTest.deadlineExceeded(AbstractInteropTest.java:816)
```

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/49/
```
java.lang.AssertionError: Expected deadline to be exceeded
	at org.junit.Assert.fail(Assert.java:88)
	at io.grpc.testing.integration.AbstractInteropTest.deadlineExceeded(AbstractInteropTest.java:816)
```

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/presubmit/job/windows/123/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/55/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/61/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/65/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/66/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/72/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/77/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/80/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/82/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/89/

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/94/
