### ISSUE TITLE
add pom.xml to examples/

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-java#1414]
Currently there is only gradle build.gralde file.  Add pom.xml please!

**Comment by IamFive** [comment]
check https://github.com/IamFive/grpc-maven-sample, maybe that is what u want.

**Comment by saturnism** [comment]
+1 but would be better if its part of the examples/ dir

**Comment by IamFive** [comment]
I think it's not that easy to create a pom.xml for the examples, the grpc version will changes, but the whole project is build with gradle not maven.

I will create a pull request to see whether they will accept it.

**Comment by saturnism** [comment]
i had a small discussion, i think there is a chance to have a grpc-java-examples repo where it depends on external dependencies just like a regular user would. repo request soon.

**Comment by IamFive** [comment]
that would be nice. ;), with the wrong document, i spent whole day to fix out the how the old maven plugin runs

**Comment by saturnism** [comment]
Me too. I just want a project that worked :D 

I combined both Gradle and Maven build files into a single repo - https://github.com/saturnism/grpc-java-examples
