### ISSUE TITLE
gprc-all is published without sources

### ISSUE THREAD

**Issue by stepancheg** [grpc/grpc-java#1420]
```
# curl -s http://central.maven.org/maven2/io/grpc/grpc-all/0.12.0/grpc-all-0.12.0-sources.jar | jar t
META-INF/
META-INF/MANIFEST.MF
#
```

**Comment by ejona86** [comment]
grpc-all is currently repackaging all the other grpc-* jars. It should really just use normal dependencies in order to not cause duplicate dependency problems. However, I think we're more likely to just delete it.

**Comment by nmittler** [comment]
+1 to deleting it

**Comment by ejona86** [comment]
Just because, if we wanted to make a fat jar of sources, we would add something like:
```gradle
sourcesJar {
    from {
        subprojects.sourceSets.main.allSource
    }
}
```

(I have had a branch with that laying around since Aug 7, 2015...)

**Comment by ejona86** [comment]
Split off #1597 for removing/dealing with grpc-all. This is trivial to fix short-term and doesn't require any decision making.
