### ISSUE TITLE
Context forwarding between client and server?

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#1425]
The comments on the Context object aren't completely clear to me what it forwards and does.  For example, here https://github.com/grpc/grpc-java/blob/6e94cf33db75b652b42fae77d36a4bdd55e9a9dd/core/src/main/java/io/grpc/Context.java#L52 the comment says

```
/**
 * A context propagation mechanism which carries deadlines, cancellation signals,
 * and other scoped values across **API boundaries** and between threads. Examples of functionality
 * propagated via context include:
 * <ul>
 *   <li>Deadlines for a local operation or remote call.</li>
 *   <li>Security principals and credentials.</li>
 *   <li>Local and distributed tracing context.</li>
 * </ul>
 */
```

I've seen the tests for deadline propagation added recently, but I'm working on a tracing context interceptor, and it isn't clear to me if I should expect the information in the context to automatically forward downstream, or if I should be pulling that information out of the context and sending it along in a header?  I've looked at the Client and Server Impls for example, and while things like deadlines propagate and cascade downstream, it not clear to me if/how the arbitrary value objects are supposed to

**Comment by ejona86** [comment]
Context is local-only. gRPC will support auto-transmitting a few precise items, but in general explicit use of Metadata is necessary. For gRPC, we're only planning on directly propagating deadline (but possibly a smaller deadline than the Context has, depending on CallOptions) and cancellation.

For propagating tracing information, you would want interceptors on clients and servers to read/set the appropriate Metadata.

**Comment by jhspaybar** [comment]
Thanks!  Once I get the CLA signed I might tweak the comment in that class a bit to make this more clear.
