### ISSUE TITLE
Use new protoc maven plugin from Maven Central

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-java#1440]
License issue on maven-protoc-plugin has been resolved, and it's now pushed to maven central - yay!
https://github.com/sergei-ivanov/maven-protoc-plugin/issues/11

Should update documentation and/or examples to use the the maven central plugin:
http://search.maven.org/#artifactdetails%7Corg.xolstice.maven.plugins%7Cprotobuf-maven-plugin%7C0.5.0%7Cmaven-plugin

**Comment by ejona86** [comment]
I already did in #1431. Did I forget something?

**Comment by saturnism** [comment]
Oh cool! Didn't realize that was in. Thanks!
