### ISSUE TITLE
Support Unix Domain Socket

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#146]
Should be straightforward enough now that Netty supports it

**Comment by ctiller** [comment]
We should quickly round table addressing schemes. C currently uses
unix:uds_file_name... But I think moving to something more uri like would
be better. Say unix://uds_file_name and tcp://host:port?

**Comment by zhangkun83** [comment]
+1 to unix://uds_file_name. Maybe 3 slashes like file:///path/to/file

**Comment by JakeWharton** [comment]
+1 to three slashes (also know as lack of authority)

**Comment by zhangkun83** [comment]
@iamqizhao and I just had a discussion. He also agrees with three slashes. In the spirit of "lack of authority", we probably need to support ``uds://localhost/path/to/file`` too.

**Comment by ejona86** [comment]
@a11r, what is your view on naming for Unix Domain Sockets?

For the current Netty implementation, I think we may not need a URI at all, since the user could just pass a [DomainSocketAddress that specified the file](https://github.com/netty/netty/blob/master/transport-native-epoll/src/main/java/io/netty/channel/unix/DomainSocketAddress.java).

**Comment by ctiller** [comment]
Question to the three slash crowd:

Given a current working directory of /home/ctiller
And a request to create a server at unix:///foo
What would be the absolute path of the uds name be?

**Comment by zhangkun83** [comment]
I suppose the addresses always indicates absolute paths, so the answer would be "/foo".

**Comment by louiscryan** [comment]
Technically three-slashes is not authority-less, it's that the authority is inferred from the end-user context so it depends how you want to define the semantics of the scheme. If we followed the semantics of 'file' then paths are always absolute and the context is the root of the filesystem.

**Comment by ejona86** [comment]
Note that this conversation applies also to a shared memory transport.

**Comment by ejona86** [comment]
@nmittler, was this fixed as part of #432?

**Comment by nmittler** [comment]
@ejona86 yeah, it is supported now.  I'm modifying the benchmarks to support UDS in #446
