### ISSUE TITLE
TransportSet should reset current index on transportReady

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1476]
If we successfully make a connection to an address, then that should mean the address is good. If it later is disconnected due to GOAWAY or transient failure we should start at the top of the list instead of trying less-desirable IPs.

This can cause errors, but any errors can already be gotten other ways, so it shouldn't be considered a major bug.

**Comment by sduskis** [comment]
Our users are seeing failures because the low priority addresses are getting "Network unreachable" errors.  Can this please be escalated?

**Comment by sduskis** [comment]
Oh, I think I get what you're saying in your second paragraph. This is a problem that's not gRPC specific.  The root of the "Network unreachable" problem, rather than what amounts to applying a bandaid in resetting the TransportSet index.  We'll look more towards the root cause than the bandaid.

**Comment by ejona86** [comment]
@sduskis, #1477 would actually reduce the number of errors you would see, since we would delay failing RPCs until we try all addresses for a host. So you may be more interested in it. It is more of a real fix.

**Comment by sduskis** [comment]
SGTM.
