### ISSUE TITLE
Add flow control sample documentation

### ISSUE THREAD

**Issue by makeyang** [grpc/grpc-java#1479]
flow control mechanism is a little bit hard to understand. can you guys add some test to demonstrate its usage?

**Comment by ejona86** [comment]
That seems reasonable. Were you trying to use `StreamObserver` or `ClientCall`?

**Comment by makeyang** [comment]
ClientCall

**Comment by buchgr** [comment]
I assume you mean an example?

**Comment by ejona86** [comment]
I assumed it was include an example that demonstrates interacting with flow control.

**Comment by hsaliak** [comment]
@zhangkun83 could you help with a flow control example using ClientCall? Having this in the javadoc is sufficient.

**Comment by akhileshkrishnan** [comment]
Hi is there an example of flow control for StreamObserver ?

**Comment by ejona86** [comment]
@akhileshkrishnan, there is the [manualflowcontrol example](https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/manualflowcontrol). If you avoid calling `disableAutoInboundFlowControl()`, then you won't need to call `request()` either. The main piece is `setOnReadyHandler()` and `isReady()`.

**Comment by akhileshkrishnan** [comment]
@ejona86 sorry for the late reply, thanks for the example. I was implementing this by waiting on the StreamObserver object and notifying it accordingly. This is a simpler implementation.
