### ISSUE TITLE
The asynchronous Channel is uncompleted,but I have never used asynchronous Channel

### ISSUE THREAD

**Issue by davieli** [grpc/grpc-java#1481]
The server print the logs as follows,and never stop until the server is shut down:

2016-02-25 19:31:42.664 [grpc-default-worker-ELG-2] ERROR i.netty.handler.codec.http2.Http2ConnectionHandler - Sending GOAWAY failed: lastStreamId '0', errorCode '1', debugData 'HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: '. Forcing shutdown of the connection.
java.nio.channels.ClosedChannelException: null

**Comment by ejona86** [comment]
How frequently is it printed? Is there a monitoring tool or similar that creates a TCP connection and then closes it immediately?

"Sending GOAWAY failed" is a pretty common occurrence and often can be ignored. I'd like to fix netty to no longer log the error, but haven't yet.

**Comment by davieli** [comment]
@ejona86 Thank you! Yes,you are right.That is the Nginx's health check.I have fixed this problem.

**Comment by chenglinjava68** [comment]
I meet  the same  trouble 
Sent GOAWAY: lastStreamId '0', errorCode '1', debugData 'HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 0d0a'. Forcing shutdown of the connection.2016-11-03 

how to resolve it ??

**Comment by carl-mastrangelo** [comment]
0d0a (a.k.a. `\r\n`) looks like it is using HTTP/1.1 instead of http2.  Are you sure you are connecting to the right server?
