### ISSUE TITLE
is server push feature used in anywhere in Grpc-java?

### ISSUE THREAD

**Issue by makeyang** [grpc/grpc-java#1486]
my rpc framework need this feature, so I'd like to reference the implementation of it in Grpc-java, but fail to find it in code. 
can anyone help on this please?

**Comment by ejona86** [comment]
No. We don't support PUSH_PROMISE on either the client or server.

**Comment by makeyang** [comment]
thanks

**Comment by willks** [comment]
I had this requirement as well for a mobile application. I had to solve it in two steps:

1) Implementing Websockets on server and client
    Any save event on server (via Web UI) sends the data to the connected client device if it's connected. 
2) If client device is not connected (e.g. iOS apps backgrounded), the message is pushed via GCP's push/pull any another microservice pushes it to OneSignal (to ensure delivery).

I am using GCP as it has a handy API Gateway which injects identity information as I use Firebase Auth, but I had to roll my own JWT token verifier for the websocket connections, using the same tokens that I use for gRPC. 

I don't know your use-case, but Websockets are probably the way to mitigate this missing feature. I found this Github issue by searching for this specific concern (so I can deprecate my Websocket implementation) but looks like I'm still bound to it. 

Websockets are easy, just use a good JSON library (I use Jackson2)

**Comment by ejona86** [comment]
In gRPC you can use a bidirectional stream in the same basic way you use a websocket. I don't see much need to use websocket there.

It's not clear how people think they need PUSH_PROMISE for RPCs (since it's really only to pre-populate caches), but I imagine people think it may solve "the server needs to call the client" problem. That can be done with bidi streams, but a reverse tunneling approach (grpc/grpc#14101) is likely more natural.

**Comment by willks** [comment]
@ejona86 Hey well yes, I use bidi streaming but the point comes when you call "complete" and then you can't send any more data unless client requests again. Is there a concrete excample on how to do a server push to a specific client (e.g., authenticated clients)? I'd love to see it! Indeed, all my github/google searching has found "it's possible".

**Comment by ejona86** [comment]
@willks, simply don't call onComplete; leave the stream open. That's functionally similar to websockets.

**Comment by willks** [comment]
@ejona86 Well that's a creative solution! I tried it and it worked, even reconnection. Will have to test it more under a clustered scenario but it's looking like I'll use this!
