### ISSUE TITLE
Add CallOptions parameter to newCall()

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#150]
We need robust per-call configuration. For example, if we were to add configuration for specifying whether to retry, where would it go? Such configuration would need to be per-call, so it must go in Channel.newCall() somewhere. MethodDescriptor is where timeout is now, but putting more in MethodDescriptor seems like a long-term disaster. Metadata.Headers is where authority and path are now, but putting retry configuration there would be very odd.

A CallOptions class would be a natural place for per-call configuration, and would actually be a good home for timeout, authority, and path. Removal of timeout from MethodDescriptor would make it so that nobody ever needs to modify the object, which would allow us to greatly simplify the generated code. Authority and path don't really relate to Metadata; they relate to HTTP headers but not GRPC Metadata. Removal of them from Headers means we would remove the Headers/Trailers distinction and just have Metadata. That would also fix the issue where Headers doesn't make sense to send from ServerCall since authority and path are meaningless for response headers.

The main breakage would be with Interceptors, as it would be adding a new parameter.

I'm also uncertain as to whether CallOptions should be final or not. I think we want final, since we don't want that part of the API to be transport-specific, but it could be useful to have transport-specific options such as inbound flow control window.

@louiscryan and @zhangkun83, what do you think?

**Comment by nmittler** [comment]
+1 to CallOptions

I suppose the Channel will also have a CallOptions that will serve as the default for all calls and can be configured when building the Channel?

**Comment by ejona86** [comment]
If Channel has a default, then the best way to deal with that is for Stubs to get that default when constructed. To get the default to the stub we would need some get method on Channel interface, I guess. The alternative would be having to determine if some option has been overridden, which seems more pain than it is worth.

From every angle I look, if an interceptor wants to do something with CallOptions, it needs to happen in the current intercept method, otherwise things get very confusing wrt overriding behavior being different for CallOptions vs Metadata. That means that interceptors shouldn't really be allowed to intercept a Channel.getDefaultCallOptions() method.

But then what do you do if you want to have two different default configurations for one Channel and pass them separate places? We could have a utility (not an interceptor) that would override just getDefaultChannelOptions(). That isn't horrible, but I would have hoped for a bit cleaner of a solution. There are also some difficulties in the Builder, since it is very likely you would want to get() the current options and modify them instead of overriding them wholesale.

So the details still need to be worked out...

**Comment by nmittler** [comment]
@ejona86 I think giving channel a `getCallOptions` (or maybe `getDefaultCallOptions`) method makes sense.

I think if `CallOptions` were passed as a parameter to `Call.start()` then the interceptors should have everything they need.  Interceptors should not have to override the default `CallOptions` from the channel in that case.

**Comment by zhangkun83** [comment]
CallOptions is great to have. Will it be available on the stub layer? If not, users who use generated stub would have to use interceptors to set CallOptions, which would make CallOptions less call-wise but more channel-wise.

**Comment by ejona86** [comment]
I thought we would likely have a copy of each mutation method in AbstractStub. AbstractStub would no longer iterate over all the methods for setTimeout and instead just call withTimeout on the CallOptions.

I notice I failed to mention: I was originally thinking CallOptions would be immutable.

**Comment by louiscryan** [comment]
Why not provide a default call options off MethodDescriptor, particularly
if they are likely to vary per-call?

**Comment by ejona86** [comment]
I wasn't thinking they would vary per-call in the MethodDescriptor-sense. I was thinking that from one call to the next they would vary, but for the same method they would vary and sometimes multiple methods would use the same.

Putting it on MethodDescriptor doesn't really have much value in my mind. These are just the stub's configuration options, but there isn't today any way to communicate that configuration cleanly to Channel.  Also, if put on MethodDescriptor, we would still have to loop through all the MethodDescriptors applying the modification when a stub is reconfigured. I want reconfiguring the stub to be O(1).

**Comment by zhangkun83** [comment]
So, no more
`stub.configureNewStub().setTimeout(...).build()`
just
`stub.withTimeout(...)`

Are we going to remove configureNewStub() all together? Or do we still have
it for configuring interceptors?

On Fri, Feb 27, 2015 at 11:51 AM, Eric Anderson <notifications@github.com>
wrote:

> I thought we would likely have a copy of each mutation method in
> AbstractStub. AbstractStub would no longer iterate over all the methods for
> setTimeout and instead just call withTimeout on the CallOptions.
>
> I notice I failed to mention: I was originally thinking CallOptions would
> be immutable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc-java/issues/150#issuecomment-76460071>.
>



-- 
Kun Zhang | Software Engineer | zhangkun@google.com | +1 (650) 960 6368

**Comment by ejona86** [comment]
I see ```stub.configureNewStub().setTimeout().build()``` as a separate discussion and was going to leave it as-is. Instead, the StubConfigBuilder and the AbstractStub would use a CallOptions internally.

**Comment by ejona86** [comment]
@zhangkun83, I misspoke a bit earlier. Instead of "mutation method in
 AbstractStub" I meant "mutation method in StubConfigBuilder". I had stopped to look up the class name and then forgot to update it the text.

**Comment by zhangkun83** [comment]
Coming back to CallOptions. Throwing out some thoughts.

**Priorities**
Options may be set at multiple locations. When it comes to merging them into the final one, we should probably assume the following order of priority (from highest to lowest):

1. Per-Call
2. Per-Stub (set through ``AbstractStub``)
3. Channel defaults
4. Method defaults (set through proto file)

**Immutability and Transparency**
I believe you all would agree making ``CallOptions`` immutable is beneficial for code health. Every entity that changes the options would need to create a new ``CallOptions``.

The final ``CallOptions`` that is used to make the call will be merged from all layers. Thus each layer has to keep only the values that it has changed, and apply *only* these values when merging with the options from the lower layer. This can be done by making the values *transparent*, i.e., remembering the *unset* state. If a value is *unset*, ``CallOptions`` will return its hard-coded default value when inquired, but it becomes *transparent* when being merged.

I have drafted a [``CallOptions``](https://github.com/grpc/grpc-java/blob/4ec6b02dee783c07a56d5ec81670cb76afca9bf3/core/src/main/java/io/grpc/CallOptions.java) based on this idea.

**Where to Pass Per-Call Options**
@nmittler suggests that we pass ``CallOptions`` to ``Call.start()``. That means the stub layer needs to pull the channel default from ``Channel.getDefaultCallOptions()``, merge it with whatever options the stub layer has got so far, and feed the result to ``Call.start()``. There is a data flow from the channel layer to stub layer then back to channel layer. 

I prefer passing ``CallOptions`` to ``Channel.newCall()``, so the data always flows in one direction. The channel can apply its default options internally, which is not exposed to the upper level. So we have:
```java
interface Channel {
  Call newCall(MethodDescriptor, CallOptions);
}
```
``MethodDescriptor`` will hold the ``CallOptions`` from the proto service definition. The channel applies it before creating the ``Call`` object. The ``Call`` will hold the final ``CallOptions``.

The interceptor can be changed to:
```java
interface ClientInterceptor {
  Call interceptCall(MethodDescriptor, CallOptions);
}
```

**Comment by ejona86** [comment]
Some "quick" notes:
I don't see us having per-call options. I don't see anything in your description that really talks about it further.

No need for a builder for CallOptions. A fluent interface for making modified versions sounds fine (a withTimeout(), for instance).

I agree that having Channel.getDefaultCallOptions() makes the flow weird, and would be happier not to have it. I also prefer passing CallOptions on newCall(), but start() could work.

I'm not excited about CallOptions.apply(). It requires allocation and I'm worried about things outside of Channel using it. I think I would prefer CallOption only be used for newCall(), MethodDescriptor is used for method defaults, and Channel merges the two with its own defaults manually. This is functionally identical to CallOptions.apply(), except that it doesn't require the CallOption, MethodDescriptor, and Channel to support the same configuration fields.

For instance, stream window size could easily be a CallOption, but on Channel it would likely look different in order to be configured similarly to connection window size (which wouldn't be a CallOption), and I would be against having it on MethodDescriptor. Another case would be where CallOption would have a _deadline_, MethodDescriptor would have a  _timeout_, and Channel would have nothing.

**Comment by nmittler** [comment]
@ejona86 
> I don't see us having per-call options
Err .. I'm confused.  You created this issue :)

**Comment by ejona86** [comment]
In reference to:
> Options may be set at multiple locations. When it comes to merging them into the final one, we should probably assume the following order of priority (from highest to lowest):
> 1. Per-Call
> 2. Per-Stub (set through AbstractStub)

What I was trying to convey is we _won't_ support per-call options from a stub; saying that per-call wins out over per-stub should be vacuous, because you will never "combine" the options to each. You either have "per-call" or "per-stub" depending on the interface.

**Comment by zhangkun83** [comment]
> I'm not excited about CallOptions.apply(). It requires allocation and I'm worried about things outside of Channel using it. I think I would prefer CallOption only be used for newCall(), MethodDescriptor is used for method defaults, and Channel merges the two with its own defaults manually. This is functionally identical to CallOptions.apply(), except that it doesn't require the CallOption, MethodDescriptor, and Channel to support the same configuration fields.

I am confused. Are you saying the Channel default options will have different fields from what CallOptions have? But our previous discussion around ``Channel.getDefaultCallOptions()`` assumed that Channel keeps its default options as CallOptions.

> For instance, stream window size could easily be a CallOption, but on Channel it would likely look different in order to be configured similarly to connection window size (which wouldn't be a CallOption)

I don't follow this. What would the window size on Channel look like?

> Another case would be where CallOption would have a deadline, MethodDescriptor would have a timeout ...

I get this part. A ``CallOptions`` is for a particular Call, so it has *deadline*. Options in ``MethodDescriptor`` are more general, so it has *timeout*. ``MethodDescriptor`` originates from proto definition, and can be reconfigured on ``AbstractStub``. Then it is converted to ``CallOptions`` before making a Call.

**Comment by ejona86** [comment]
> But our previous discussion around `Channel.getDefaultCallOptions()` assumed that Channel keeps its default options as CallOptions.

But I'm thinking that `getDefaultCallOptions()` is problematic and want to drop it.

> I don't follow this. What would the window size on Channel look like?

Well, today it is on option on the ChannelBuilder.

> Then it is converted to CallOptions before making a Call.

Where is that done? It needs to be done in the ChannelImpl, as someone can change MethodDescriptor along the interceptor chain. Since it is done in ChannelImpl, I don't think it actually needs to become a CallOptions; it can just be checked manually.

**Comment by zhangkun83** [comment]
I have put what I have got so far in this doc:
https://docs.google.com/document/d/1yglaLqCn60r3M3pUrheOXq-VhETw-iLE32rRwQUhjyY/edit#
