### ISSUE TITLE
Simplify using richer APIs in service implementations

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#1519]
While it is possible for service implementors to interact with richer features like inbound & outbound flow-control today by creating their own io.grpc.ServerCallHandler this is quite cumbersome to do. You would need to completely rewrite how your server was build and could not simply implement the generated service definition any more. In cases where only one of the methods in the service needs more control over flow-control this is quite messy

One proposal is to allow implementers to cast the StreamObserver they receive from the runtime to a richer type that allows for interaction with advanced features. This works for all generated service calls including unary calls.

**Comment by jhspaybar** [comment]
This is becoming increasingly important for us as we write streaming APIs.  It's helpful to know if you should be sending more data when on the server side and streaming out.  It's also nice to know if a client has disconnected since the last time you send an onMessage before calculating the new data and sending it.

**Comment by ejona86** [comment]
@jhspaybar, @louiscryan is actively working on an implementation. It seems it shouldn't be long before a PR gets sent out.

**Comment by jhspaybar** [comment]
Awesome!  Thanks for the update.

**Comment by ejona86** [comment]
@louiscryan, do you consider this done, or do we want to leave it open for client-side?

**Comment by louiscryan** [comment]
I'd like to leave it open for client-side though its a bit less of a
priority there

**Comment by ejona86** [comment]
#1010 actually seems well-suited for client-side. So let's call this one server-side only and close it.
