### ISSUE TITLE
Examples of serving HTTP 1 request with servers running GRPC?

### ISSUE THREAD

**Issue by thefallentree** [grpc/grpc-java#1532]
Hi,

Is there a example of using grpc/underlay netty to serve HTTP1/1 on the same port?

Cheers.

**Comment by ejona86** [comment]
No, we don't provide such an example and it isn't really much of a supported use-case at present. I do know it is possible, but it is a bit tricky and not something I would generally encourage.

Longer-term, with [some upstream Netty API changes](https://github.com/netty/netty/issues/3667) we would hope to support more advanced Netty use-cases, for example, by providing a GrpcHandler.

**Comment by thefallentree** [comment]
Thanks,

We are currently using jetty to serve http needs, and grpc for rpc part. Would there be a problem other than having two I/O stack running at the same time?  (maybe there is even advantage of that )

**Comment by ejona86** [comment]
Having both running shouldn't be too much of a problem. You'll need to configure a port for it to run on, which may be a little annoying, but everything should function.

**Comment by ejona86** [comment]
This seems to be resolved.

**Comment by kuroneko25** [comment]
We actually have a similar need because we run gRPC based services on Google Container Engine and utilize their managed load balancer which uses HTTP health checks by default. This poses a challenge since the load balancer expects to hit the same port to do its HTTP health check. Are there plans to do something similar like https://github.com/grpc/grpc-go/pull/514? If not what is the recommended approach for handling HTTP based health checks?

**Comment by ejona86** [comment]
@kuroneko25, I'd recommend you run an HTTP server on a different port. Sharing with HTTP is a complicated target, and it's a bit unclear where we'll end up (it depends some on the performance of netty/netty#3667 and how we utilize it in grpc)

**Comment by jchapuis** [comment]
Any news on this front? Also would like to expose the REST and grpc endpoints on the same port. Thanks

**Comment by jared2501** [comment]
netty/netty#3667 would be great - would be nice to be able to run gRPC and other HTTP/2 services on the same port.

**Comment by jared2501** [comment]
Ah looks like https://github.com/grpc/grpc-java/issues/3458 is the new, open GH issue tracking this FR
