### ISSUE TITLE
If DNS resolution fails, the Channel is permanently failed

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1546]
We should probably update DnsNameResolver to continue retrying the DNS query until shutdown, at maybe a fixed rate of 1 minute or such. Overall, it's not a superb solution, but it fixes a lot of the problem and is expedient to implement.

**Comment by carl-mastrangelo** [comment]
Exponential back off with an exponent of 0?

**Comment by ejona86** [comment]
Zero is best exponent.
