### ISSUE TITLE
Change the way we pass SSLSession

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-java#1556]
Right now, we're using Netty's channel attributes to pass SSLSession object from one place to another. It was a quick win when adding `ServerCall#attributes()` support.

We want to plumb it through as an argument.

Ref: https://github.com/grpc/grpc-java/pull/1506/files#r56371848

**Comment by lukaszx0** [comment]
@ejona86 feel free to assign it to me, I'll try to find time to refactor this.

**Comment by zhangkun83** [comment]
@lukaszx0 I also have a need to plumb some information from a proprietary `ProtocolNegotiator.Handler` to transport attributes. I figure it should use the same mechanism as how SSLSession is plumbed. How in your mind would the attributes be passed as an argument?

**Comment by lukaszx0** [comment]
Maybe we could add `Attributes attributes()` to `ProtocolNegotiator.Handler` interface and maybe also introduce `abstract GrpcNettyHandler extends AbstractNettyHandler` which would be inherited by both server and client handler and would let us set protocol negotiator handler (`setProtocolNegotiatorHandler(ProtocolNegotiator.Handler)`).

@ejona86 what do you think?

**Comment by zhangkun83** [comment]
If all what we need is passing attributes from ProtocolNegotiator.Handler to AbstractNettyHandler, it doesn't seem necessary to pass the whole ProtocolNegotiator.Handler. How about instead adding a `onProtocolNegotiationCompleted(Attributes)` to the new `GrpcNettyHandler`? Then we don't need to add `attributes()` to `ProtocolNegotiator.Handler`.

**Comment by lukaszx0** [comment]
@zhangkun83 agree. I took a stab at it in #2295.
