### ISSUE TITLE
Move utilities from GrpcUtil from internal package

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-java#1562]
We've collected a bunch of utilities in `GrpcUtil` most of which are used publicly in apps (metadata keys, marshallers) and since `GrpcUtil` is part of `internal` package, we want to either move `GrpcUtil` completely out of it, or split, leaving some of the esoteric stuff like `SHARED_CHANNEL_EXECUTOR` or `TIMER_SERVICE` in internal package and exposing metadata key fields etc. in class from public package.

**Comment by lukaszx0** [comment]
While I was creating this PR, @ejona86 responded in my PR - https://github.com/grpc/grpc-java/pull/1506#issuecomment-197564914. I agree with it and I think this issue becomes irrelevant and can be closed.

**Comment by ejona86** [comment]
Copying from discussion in #1506.

@ejona86 wrote:
> @lukaszx0, GrpcUtil isn't intended to be used except for transport implementations. I've not seen an interceptor yet that needs GrpcUtil, other than things testing our implementation. I don't see the ascii and binary marshallers that you are referring to that should be made public. Which metadata keys are you using? USER_AGENT_KEY is the only one I see that could be generally useful, and I'd suggest just copying it. Instead of TIMEOUT_KEY the plan is to expose the Deadline on Context (and maybe ServerCall). So I really don't see anything that should be made part of our API.

> The only users of internal APIs should be transport implementations, with the one exception of ping().

**Comment by lukaszx0** [comment]
Regarding ServerCall attrs, I've created #1564 which moves them out of internal package.

**Comment by lukaszx0** [comment]
The aforementioned PR has been merged, and as stated in my previous comment, I think I'm on the same page with @ejona86 about other stuff in `GrpcUtil`.

I think this issue can be closed unless you guys feel something needs to be changes in `GrpcUtil`.

**Comment by ejona86** [comment]
SGTM. If someone is using GrpcUtil and thinks it needs to be public this can be reopened.
