### ISSUE TITLE
Error message built with Status exception builder is not serialized properly

### ISSUE THREAD

**Issue by tbak** [grpc/grpc-java#1579]
```java
Status.INTERNAL
                            .withDescription("internal error")
                            .augmentDescription("additional description")
                            .withCause(e)
                            .asRuntimeException()
```
creates an exception with detailedMessage containing '\n' character. In `TransportFrameUtil` this character fails the validation rule `isSpecCompliantAscii`, which results in grpc-message header being silently discarded.

**Comment by ejona86** [comment]
This was resolved with #1517, which will be part of the next release. Basically we've swapped to percent encoding status messages.

If you interop with other languages, you may see %-encoded values instead of decoded values. That will be fixed as other languages adopt to the change.
