### ISSUE TITLE
Update Netty to 4.1.0-CR4

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1581]

**Comment by buchgr** [comment]
are you taking care of this, or should I?

**Comment by ejona86** [comment]
It's up for grabs.

**Comment by buchgr** [comment]
Fixed by #1585

**Comment by carl-mastrangelo** [comment]
Whats new in CR4?

**Comment by ejona86** [comment]
@carl-mastrangelo, at the very least netty/netty#4938. I don't know if we are hitting netty/netty#4965, but it would be good to rule out the possibility.

**Comment by buchgr** [comment]
@carl-mastrangelo and https://github.com/netty/netty/pull/4983 and https://github.com/netty/netty/pull/4974 :smile:  #ShamlessPlug
