### ISSUE TITLE
Provide description to Status used in ClientCallImpl.cancel

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1589]
Right now it is just Status.CANCELLED. We should give it a description so that it is more obvious it was generated locally (such as "Client cancelled call"). This is trivial, except plenty of tests fail, so they need to be updated to just check the Code.

**Comment by buchgr** [comment]
I guess I haven't thought deeply about it. What's the problem with implementing `Status.(equals()|hashCode()` to only use `code`?

**Comment by zhangkun83** [comment]
> What's the problem with implementing Status.(equals()|hashCode() to only use code
So why not include the cause too? I think because there isn't a equality semantic that fits all need, it's better to just do nothing and let the users explicitly check the fields they care.

**Comment by ejona86** [comment]
@zhangkun83, I think @buchgr is talking about something else and may have changed his mind some, in #1580.

This issue should really include cause as well.

**Comment by ejona86** [comment]
Ignore my last comment; I got this one mixed up with #1221.

**Comment by zhangkun83** [comment]
Reopening it to track the deletion of `cancel()`.
