### ISSUE TITLE
Ensure that gRPC Java implementation conforms to standard status codes in gRPC

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc-java#1605]
Error code specification - https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

**Comment by thefallentree** [comment]
We were seeing some INTERNAL error codes

**Comment by ejona86** [comment]
@thefallentree please create a new issue with the error information so that we have something actionable to go on. Note that as far as this issue is concerned, INTERNAL error codes are allowed.

**Comment by nmittler** [comment]
After code inspection, everythin seems correct except for the cases below:

Case | Expected | gRPC-Java
---- | ----- | ----
| Compression mechanism used by client not supported at server | UNIMPLEMENTED | [INTERNAL](https://github.com/grpc/grpc-java/blob/fd8fd517d21165e1ad97a063861ec0790ed2c610/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L90) |
| Server temporarily out of resources (e.g., Flow-control resource limits reached) | RESOURCE_EXHAUSTED | NA |

Status codes that should not be used:

Code | Usage
--- | ---
INVALID_ARGUMENT | [Marshalling JSON](https://github.com/grpc/grpc-java/blob/5c4817723e90b8adb8ed0cf923885df6301ed303/protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java#L91), [Server receives multiple messages for UNARY](https://github.com/grpc/grpc-java/blob/fd8fd517d21165e1ad97a063861ec0790ed2c610/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L236), [Half-closing server stream without a request](https://github.com/grpc/grpc-java/blob/2fbf142a413aa5de01a57bc63730fb339afa23bd/stub/src/main/java/io/grpc/stub/ServerCalls.java#L159) |

**Comment by nmittler** [comment]
@hsaliak  @ejona86 audit is done ... next step is to determine what (if any) issues to create to address the discrepancies.

**Comment by ejona86** [comment]
UNIMPLEMENTED in wrong in the spec; that is not appropriate. We need to have a conversation to fix the spec. JSON failure should swap to INTERNAL. We need a discussion for problems with unary calls.

**Comment by ejona86** [comment]
After lengthy discussion, `UNIMPLEMENTED` is going to stay in the spec for unknown compression type.
