### ISSUE TITLE
Message serialization occurs on transport thread

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1606]
`TransportSet` is calling `setTransport()` [from the `transportReady` notification](https://github.com/grpc/grpc-java/blob/a40b686891920b825171ed90c81fc36d962e75d1/core/src/main/java/io/grpc/internal/TransportSet.java#L338). `setTransport()` eventually ends up [serializing messages](https://github.com/grpc/grpc-java/blob/eccd231/core/src/main/java/io/grpc/internal/DelayedStream.java#L86). This means we are 1) running application-provided code on the transport thread and 2) performing expensive operations on the transport thread. We need to figure out a way to avoid serializing on the transport thread.

One type of option is to use an executor for `setTransport()`. Another type of option would be to actually serialize the message within `DelayedStream`.

**Comment by zhangkun83** [comment]
Pre-serializing the messages means an extra copy and extra memory usage. An executor for `setTransport()` sounds like the better solution.

**Comment by ejona86** [comment]
@zhangkun83 SGTM
