### ISSUE TITLE
Anyone use gRPC in prod evn? please share your practice

### ISSUE THREAD

**Issue by IamFive** [grpc/grpc-java#1622]
As title, please leave your product name, experience, anything you want to share 

thanks

**Comment by thefallentree** [comment]
We are currently using it, you should know ,this repo is only for grpc-java implementation, if you need general answers, you probably need to post in GRPC repo. 

also, people kinda need a reason to reply.

**Comment by carl-mastrangelo** [comment]
Hi @IamFive ,

The best place to discuss this and get answers would be on the public gRPC forum here:  https://groups.google.com/forum/#!forum/grpc-io
