### ISSUE TITLE
javaPluginPath in gradle build does not work for me

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc-java#1625]
I'm building protobuf, grpc and grpc-java all from scratch, but without heavy customization. This mostly works, however grpc-java does only compile and work for me if I patch the gradle build:
```
--- build.gradle.org	2016-03-01 23:39:38.835011070 +0100
+++ build.gradle	2016-03-01 23:39:48.070902802 +0100
@@ -52,7 +52,7 @@
     ext {
         def exeSuffix = osdetector.os == 'windows' ? ".exe" : ""
         protocPluginBaseName = 'protoc-gen-grpc-java'
-        javaPluginPath = "$rootDir/compiler/build/exe/java_plugin/$protocPluginBaseName$exeSuffix"
+        javaPluginPath = "$rootDir/compiler/build/binaries/java_pluginExecutable/$protocPluginBaseName$exeSuffix"
 
         protobufVersion = '3.0.0-beta-2'
         protobufNanoVersion = '3.0.0-alpha-5'
```
I don't know why I seem to need a change in javaPluginPath? Is this due to my custom build of protobuf? I did not make any (intentional) changes to protobuf that would ring a bell...

**Comment by ejona86** [comment]
Are you using the gradle wrapper? Gradle's behavior changed in a recent version. Using ./gradlew should work without issue.

**Comment by emmenlau** [comment]
Thanks for the hint, I did not use gradlew, sorry for that!

**Comment by vans88** [comment]
My situation as follows:
------------------------------------------------------------------------
Detecting the operating system and CPU architecture
------------------------------------------------------------------------
os.detected.name=linux
os.detected.arch=unknown

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/TenFlow/grpc-java/build.gradle' line: 60

* What went wrong:
A problem occurred evaluating root project 'grpc'.
> unknown os.arch: mips64el

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 49.999 secs

Currently, my platform is mips64el, Anyone can tell me how to deal with this errror?
