### ISSUE TITLE
Support OkHttp3?

### ISSUE THREAD

**Issue by njovy** [grpc/grpc-java#1628]
It's been a while since stable OkHttp3 has been released and libraries depending on OkHttp started to support OkHttp3 as well. Is there any plan to support OkHttp3?

**Comment by ejona86** [comment]
We've not discussed it too much. I believe that most gRPC users are still on OkHttp 2. I'm not against moving to OkHttp3, but we wouldn't want to support both versions.

**Comment by adrien-aubel** [comment]
All for Okhttp3 here :)
Okhttp3 has a much improved API and backend, and is obviously where Square is focused at this point.
So this would probably benefit users of Okhttp backend, and reduce overhead for Android apps that already use Okhttp3. For users that didn't upgrade yet to Okhttp3, they'll still get the benefits, but they will have both versions as dependencies (which still works well, all Okhttp3 classes are in `okhttp3` package name, while Okhttp2 classes are in `com.squareup.okhttp`).

**Comment by carl-mastrangelo** [comment]
I have been using OkHttp3 on my own personal projects and I have to agree I like the API of it as well.  It probably won't be as prioritized as Netty since there isn't as much Android demand, but I would be interested in having this in the future.

**Comment by eveliotc** [comment]
Any update here? We would love to start using gRPC but have been using okhttp3 since July last year, fork wouldn't be ideal.

**Comment by ejona86** [comment]
Closing, for same reason as in #2999. I guess comment there if you want, since I describe a possible option. The only way I see it being an improvement for _users_ is by being able to use OkHttp 3's ConnectionSpec. But I've also not heard anyone say that's involved.
