### ISSUE TITLE
io.grpc.StatusRuntimeException: INTERNAL: Failed to frame message

### ISSUE THREAD

**Issue by orian** [grpc/grpc-java#1629]
message Test {
      bytes test = 1;
    }

The above runtime exception is thrown when a field of type `[]byte` is set to `null` and one tries to use it as service argument.

The code is executed on Android. I use protobuf-nano.

Default value for `[]byte` is `com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES`

The error is hard to spot. Is this stated in a documentation? Maybe it should be treated as a default value? Not sure.

**Comment by ejona86** [comment]
This appears to be a nano-proto specific problem, so please file an issue with https://github.com/google/protobuf instead. In general, nano proto strongly favors performance over ease of use.

**Comment by orian** [comment]
Thanks.

**Comment by orian** [comment]
Thanks. I got it. Just want to leave a trail for those to have this problem.
