### ISSUE TITLE
deadlineExceeded interop test is flaky

### ISSUE THREAD

**Issue by zsurocking** [grpc/grpc-java#1632]
intervalUs is used for consecutive responses. We cannot use it for the only response and expect a delay from server sending the response.

**Comment by ejona86** [comment]
It has a delay _before_ the message that included it, so I would disagree

https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#observe-responseparametersinterval_us

**Comment by zsurocking** [comment]
You're right.
As discussed in #1633, the proto definition is a little ambiguous. We're doing it correctly as a client according to the spec. And I'll fix the service implementation instead.
