### ISSUE TITLE
StubConfigTest.testConfigureDeadlineNanoTime is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1646]
```
io.grpc.stub.StubConfigTest > testConfigureDeadlineNanoTime FAILED
    java.lang.AssertionError: 20000000 < 45632697
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.grpc.stub.StubConfigTest.testConfigureDeadlineNanoTime(StubConfigTest.java:116)
```

As seen in (may have been restarted):
https://travis-ci.org/grpc/grpc-java/jobs/121487417
https://travis-ci.org/grpc/grpc-java/jobs/121488444 (20000000 < 24579334)

https://travis-ci.org/grpc/grpc-java/jobs/118573602, which was before assertEquals float vs double fix, so it had:
```
io.grpc.stub.StubConfigTest > testConfigureDeadlineNanoTime FAILED
    java.lang.AssertionError: expected:<1.68848953E13> but was:<1.68849184E13>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:519)
        at org.junit.Assert.assertEquals(Assert.java:609)
        at io.grpc.stub.StubConfigTest.testConfigureDeadlineNanoTime(StubConfigTest.java:114)
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/121306624 (20000000 < 27499937)

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/121710941 (20000000 < 22392102)

**Comment by ejona86** [comment]
Before the recent fix:
https://travis-ci.org/grpc/grpc-java/jobs/120967086 (20000000 < 33037554)

**Comment by ejona86** [comment]
After the recent fix:
https://travis-ci.org/grpc/grpc-java/jobs/122896901 (30000000 < 33627096)

**Comment by ejona86** [comment]
After the fix:
https://travis-ci.org/grpc/grpc-java/jobs/123952408 (30000000 < 34061938)

**Comment by ejona86** [comment]
After the fix: https://travis-ci.org/grpc/grpc-java/jobs/126188391 (30000000 < 38072596)

**Comment by ejona86** [comment]
After the fix: https://travis-ci.org/grpc/grpc-java/jobs/126787462 (30000000 < 37737730)

**Comment by buchgr** [comment]
Interestingly enough the delta seems to increase as we increase the `maxDelta` 😅

**Comment by buchgr** [comment]
hmm. Could it be that a stop the world pause / system jitter is responsible for this? Running this on my old laptop 1 million times, `actualDelta` is between `[700 micros, 1.2 millis]`.

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/127338220 (30000000 < 68869121)
