### ISSUE TITLE
GrpcUtil.getGrpcUserAgent creates a lot of garbage

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1669]
`GrpcUtil.getGrpcUserAgent` creates a lot of garbage based on profiling, showing up in the top 20.  It appears that this call was designed to mostly static and not change per call.

We should find a way to initialize this at channel creation time to make this not so messy.

**Comment by ejona86** [comment]
This appears to have been fixed in #1858 and #1868
