### ISSUE TITLE
Installation fails due to Javadoc errors

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc-java#169]
Installing the library as described in the main README.md fails in the last step, because javadoc finds two errors and exits with status 1 (which makes ./gradlew install sad).

Error 1:

    grpc-java/core/src/main/java/io/grpc/ClientInterceptor.java:51: error: self-closing element not allowed
    17:25:41.937 [ERROR] [system.err]    * <p/>
    17:25:41.937 [ERROR] [system.err]      ^

Error 2:

    grpc-java/core/src/main/java/io/grpc/transport/Stream.java:46: error: reference not found
    17:25:42.326 [ERROR] [system.err]    * {@link StreamListener#messageRead(java.io.InputStream, int)}. No additional messages will be
    17:25:42.328 [ERROR] [system.err]             ^

**Comment by nmittler** [comment]
@jcanizales are you running on Java 8?  I believe this was fixed with #170.

**Comment by nmittler** [comment]
Sorry, I meant #165 ... that should teach me to use github's autocomplete ;)

**Comment by jcanizales** [comment]
I am running on Java 8. I'll check again.

**Comment by ejona86** [comment]
#170 merged.
