### ISSUE TITLE
Android - Not referencing the Request and Response file

### ISSUE THREAD

**Issue by praveen18p** [grpc/grpc-java#1693]
I have imported the project and referring to the android code in examples , below is the build.gradle file I am using .

apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'
//apply plugin: 'java'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "io.grpc.helloworldexample"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        disable 'InvalidPackage', 'HardcodedText'
        textReport true
        textOutput "stdout"
    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0-beta-2'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:0.12.0' // CURRENT_GRPC_VERSION
        }
    }

//    generateProtoTasks {
//        all()*.plugins {
//            grpc {}
//        }
//    }

    generateProtoTasks {
        all().each { task ->
            task.builtins {
                javanano {
                    // Options added to --javanano_out
                    option 'ignore_services=true'
                }
            }

            task.plugins {
                grpc {
                    // Options added to --grpc_out
                    option 'nano'
                }
            }
        }
    }

//    generateProtoTasks {
//        all().each { task ->
//            task.builtins {
//                javanano {
//                    // Options added to --javanano_out
//                    option 'ignore_services=true'
//                }
//            }
//
//            task.plugins {
//                grpc {
//                    // Options added to --grpc_out
//                    option 'nano'
//                }
//            }
//        }
//    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'io.grpc:grpc-okhttp:0.12.0' // CURRENT_GRPC_VERSION
    compile 'io.grpc:grpc-protobuf-nano:0.12.0' // CURRENT_GRPC_VERSION
    compile 'io.grpc:grpc-stub:0.12.0' // CURRENT_GRPC_VERSION
    compile 'javax.annotation:javax.annotation-api:1.2'
}

**I am getting the following error when I am trying to run my code - **

/Users/techjini/Desktop/Projects/VERIHELP/grpc-java/examples/android/app/build/generated/source/proto/debug/grpc/io/grpc/helloworldexample/GreeterGrpc.java
Error:(25, 73) error: cannot find symbol class HelloRequest
Error:(26, 32) error: cannot find symbol class HelloReply
Error:(83, 51) error: cannot find symbol class HelloRequest
Error:(84, 62) error: cannot find symbol class HelloReply
Error:(50, 51) error: cannot find symbol class HelloRequest
Error:(51, 62) error: cannot find symbol class HelloReply
Error:(108, 83) error: cannot find symbol class HelloRequest
Error:(108, 37) error: cannot find symbol class HelloReply
Error:(56, 83) error: cannot find symbol class HelloRequest
Error:(56, 37) error: cannot find symbol class HelloReply
Error:(133, 34) error: cannot find symbol class HelloRequest
Error:(132, 88) error: cannot find symbol class HelloReply
Error:(62, 34) error: cannot find symbol class HelloRequest
Error:(61, 88) error: cannot find symbol class HelloReply
Error:(31, 75) error: cannot find symbol class HelloRequest
Error:(31, 27) error: package io.grpc.protobuf does not exist
Error:(32, 75) error: cannot find symbol class HelloReply
Error:(32, 27) error: package io.grpc.protobuf does not exist
Error:(146, 40) error: cannot find symbol class HelloRequest
Error:(147, 40) error: cannot find symbol class HelloReply
Error:(150, 42) error: cannot find symbol class HelloRequest
Error:(151, 70) error: cannot find symbol class HelloReply
Note: /Users/techjini/Desktop/Projects/VERIHELP/grpc-java/examples/android/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

The GreeterGrpc class is trying to access the package but nano is appended to the package and not able to find it . 

Thanks in Advance ,
Praveen Pandey

**Comment by ejona86** [comment]
Use `option 'nano=true'` instead of `option 'nano'` for grpc-java 0.12. `option 'nano'` is only supported starting in the soon-to-be-released 0.14. 0.14 will still support `option 'nano=true'.

**Comment by praveen18p** [comment]
Thanks ERIC,

I have changed my build.gradle file 

        generateProtoTasks {
        all().each { task ->
            task.builtins {
                javanano {
                    // Options added to --javanano_out
                    option 'ignore_services=true'
                }
            }

            task.plugins {
                grpc {
                    // Options added to --grpc_out
                    //option 'nano'
                    'nano=true'
                }
            }
            task.plugins {
                grpc {
                    // Write the generated files under
                    // "$generatedFilesBaseDir/$sourceSet/grpcjava"
                    outputSubDir = ''
                }
            }
        }
      }

I am still facing the same issue , I am attaching the screenshot , the main issue is in generated/source/proto the GreeterGrpc is not able to find the HelloReply and HelloRequest . How can we generate the proto file to reference the HelloReply and HelloRequest.

Thanks for your response , really appreciate it .

![screen shot 2016-04-21 at 6 53 05 am](https://cloud.githubusercontent.com/assets/14184785/14695230/c8c2c6ae-078d-11e6-975d-34688cf35b90.png)

**Comment by praveen18p** [comment]
Solved thanks a lot :)
