### ISSUE TITLE
Bad ssl setup leads to requests never returning

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-java#1699]
I've shoot myself in a foot by copy-pasting code snippet between client and server code which looked almost identical ;)

I've been trying to make a call from client which was set up as follows:

```java
sslCtx = GrpcSslContexts.configure(SslContextBuilder.forServer(getPrivateKey(), getX509CertificateChain())).build();

channel = NettyChannelBuilder.forAddress(host, port)
        .sslContext(sslCtx)
        .build();
```

Such setup, as you may already noticed,  is obviously incorrect on the *client* and the correct way to do this is to use `SslContextBuilder.forClient` instead of `SslContextBuilder.forServer` like this:

```java
sslCtx = GrpcSslContexts.configure(SslContextBuilder.forClient().keyManager(getPrivateKey(),getX509CertificateChain())).build();
```

This lead to client being broken and handing indefinitely, after making a call, during handshake without throwing any error or other indication or notice of horribly wrong setup. It would be great if we could prevent from making this mistake somehow.

As an aside, would be nice if netty could provide overloaded versions of `forClient` just like it does for `forServer`. I might be missing something because I haven't looked into this deepy, but it doesn't seem that there's anything preventing from that (?).

**Comment by ejona86** [comment]
> As an aside, would be nice if netty could provide overloaded versions of forClient just like it does for forServer. I might be missing something because I haven't looked into this deepy, but it doesn't seem that there's anything preventing from that (?).

The short version `forServer()` isn't for convenience but instead correctness, since it forces servers to provide a key. For clients that isn't necessary, so `forClient()` wasn't overload. That doesn't mean it couldn't have convenience versions though.

**Comment by ejona86** [comment]
It looks like we should check `SslContext.isClient()/isServer()` in `NettyServerBuilder.sslContext()`/`NettyChannelBuilder.sslContext()`. If the type is mis-matched, then we can throw `IllegalArgumentException`.
