### ISSUE TITLE
Decide if io.grpc.Attributes should be marked experimental.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1700]

**Comment by zhangkun83** [comment]
@louiscryan I remember you talked about merging Attributes and Context (or Metadata?). Is it still something you want to do?

**Comment by zhangkun83** [comment]
Talked with @louiscryan. It's not been there long enough and used enough, thus we haven't got enough feedback for it. So will stay experimental.

**Comment by zhangkun83** [comment]
Keep it open until the annotation is removed.

**Comment by ejona86** [comment]
#1764 tracks the annotation being removed.
