### ISSUE TITLE
Tracking issue for messageCompression being experimental.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1703]

**Comment by ejona86** [comment]
This depends on how we are going to migrate from per-message compression to stream compression. The API surface should be the same, but there is a communication aspect to it.

**Comment by carl-mastrangelo** [comment]
Updating this to be a tracking issue.  

Specific usages:

* `ClientCall.setMessageCompression`
* `PartialForwardingServerCall.setMessageCompression`
* `ServerCall.setMessageCompression`

**Comment by larry-safran** [comment]
ATTR_LB_PROVIDED_BACKEND be marked `internal`
TOKEN_METADATA_KEY  could be package private.

Block on EquivalentAddresGroup (#1770) to be marked stable for the last 2.
