### ISSUE TITLE
Tracking Issue for  Context being experimental

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1705]
https://github.com/grpc/grpc-java/issues/262 was closed as fixed (and linked to by the Context.java file), but we still need to determine if we should commit to the API for 1.0.

**Comment by carl-mastrangelo** [comment]
Specific usages:

* `Context`
* `Contexts`

**Comment by ejona86** [comment]
It seems all of this is ready to be marked stable. The one exception is Contexts.statusFromCancelled which should have a new issue opened for it and not be marked stable at this time.

**Comment by hsaliak** [comment]
@carl-mastrangelo can you take over this issue from @louiscryan ?

**Comment by carl-mastrangelo** [comment]
@hsaliak I can, but I'm basically just going to remove the annotation.  I will just assume the API is stable.

**Comment by ejona86** [comment]
@carl-mastrangelo, see my earlier comment, where I said:
> It seems all of this is ready to be marked stable. The one exception is Contexts.statusFromCancelled which should have a new issue opened for it and not be marked stable at this time.
