### ISSUE TITLE
DnsNameResolverFactory should be checked if still Experimental

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1707]

**Comment by carl-mastrangelo** [comment]
Also NameResolverRegistry and NameResolver

**Comment by zhangkun83** [comment]
All NameResolver-related stuff will stay experimental in 1.0.

**Comment by zhangkun83** [comment]
Keep it open until the annotation is removed.

**Comment by ejona86** [comment]
NameResolver and NameResolverRegistry is handled by #1770. DnsNameResolverFactory became a provider and now lives in internal. So there's nothing to stabilize here.
