### ISSUE TITLE
MutableHandlerRegistry and HandlerRegistry need to be checked to see if still Experimental. 

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1709]
These have been around a long time, maybe its time the graduate to stable?

+cc: @louiscryan

**Comment by zhangkun83** [comment]
#1793 internalized the main handler and re-purposed MutableHandlerRegistry and HandlerRegistry for the fallback handlers, which will stay experimental in 1.0. Their experimental status is being tracked by #933.
