### ISSUE TITLE
Integrate with more data format

### ISSUE THREAD

**Issue by AdoHe** [grpc/grpc-java#171]
I don't know whether it is possible to use other data format, not just protobuf, for example avro.

**Comment by ejona86** [comment]
If you ignore service codegen, all you need is to implement [Marshaller](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/Marshaller.java) for use in a [MethodDescriptor](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/MethodDescriptor.java). With a MethodDescriptor, you can then create new calls in [Channel](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/Channel.java) and use our [Stub helper](https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/Calls.java).

All that work is done in the generated code for protobuf, so for a seemless experience you need some sort of codegen most likely. How you would want to represent a service if using some other data format would need a bit of consideration.

**Comment by AdoHe** [comment]
@ejona86 I think the data format should be irrelevant with the transparent layer, user can use other data format to represent a service, for example `avro idl`, I am trying to do this with grpc-java, since our team are using avro now, can you give me a little bit more description?

**Comment by ejona86** [comment]
The data format is mostly irrelevant to the transport layer. However, there does need to be some glue code that converts from the IDL to the transport's needs. For proto-defined services we have a code generator that produces that glue code.

So for the proto IDL:
```proto
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloResponse);
}
```

It produces (simplified):
```java
SAY_HELLO = MethodDescriptor.create(UNARY, "helloworld.Greeter/SayHello", ProtoUtils.marshaller(HelloRequest.PARSER), ProtoUtils.marshaller(HelloReply.PARSER));
public HelloReply sayHello(HelloRequest request) {
  return Calls.blockingUnaryCall(channel.newCall(SAY_HELLO), request);
}
```

That sort of thing is obviously not done for gRPC+Avro IDL. Avro RPCs also have a bit different of a feature set that would need to be mapped (oneway, exceptions, multiple arguments). That seems all doable (from the 3 minutes of looking I've done).

I'm not sure what other information would be helpful to you, as I'm not sure precisely what your goals are (client vs server, how much of gRPC that you want to use, whether this would be a migration or long-term, how "nice" of an experience you hope for, etc)

**Comment by louiscryan** [comment]
If you put what you're working on up in GitHub somewhere we will happily take a look

**Comment by ejona86** [comment]
In #1196 it seemed things worked alright when using Java serialization. If you have more questions at this point feel free to post on this issue or create a new one.
