### ISSUE TITLE
Push Java libraries to Maven central

### ISSUE THREAD

**Issue by ludoch** [grpc/grpc-java#172]
As the majority of Java Developer, I am using Maven and not Gradle...

After compiling my self the protoc tool for Mac, and creating the Route sample Maven project, I am still block with the fact that the 
import io.grpc.ServerImpl;
import io.grpc.stub.StreamObserver;
import io.grpc.transport.netty.NettyServerBuilder;

are nowhere in Maven...

My Current pom is like this, and the protoc generates correct code:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.apphosting.grpc</groupId>
  <artifactId>grpctest</artifactId>
  <version>1.0</version>
  <packaging>jar</packaging>
  <pluginRepositories>
    <pluginRepository>
      <id>dtrott</id>
      <url>http://maven.davidtrott.com/repository</url>
    </pluginRepository>
  </pluginRepositories>  
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>18.0</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>javax.json</groupId>
      <artifactId>javax.json-api</artifactId>
      <version>1.0</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.0.0-alpha-2</version>
    </dependency>

  </dependencies>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>
    
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <source>1.5</source>
          <target>1.5</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.google.protobuf.tools</groupId>
        <artifactId>maven-protoc-plugin</artifactId>
        <version>0.1.10</version>
        <configuration>
          <protocExecutable>/usr/local/bin/protoc</protocExecutable>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>

**Comment by ludoch** [comment]
huhu markdown issue with xml content

**Comment by ludoch** [comment]
<pluginRepositories>
    <pluginRepository>
      <id>dtrott</id>
      <url>http://maven.davidtrott.com/repository</url>
    </pluginRepository>
  </pluginRepositories>  
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>18.0</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>javax.json</groupId>
      <artifactId>javax.json-api</artifactId>
      <version>1.0</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.0.0-alpha-2</version>
    </dependency>

  </dependencies>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>
    
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <source>1.5</source>
          <target>1.5</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.google.protobuf.tools</groupId>
        <artifactId>maven-protoc-plugin</artifactId>
        <version>0.1.10</version>
        <configuration>
          <protocExecutable>/usr/local/bin/protoc</protocExecutable>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

**Comment by ludoch** [comment]
`  <pluginRepositories>
    <pluginRepository>
      <id>dtrott</id>
      <url>http://maven.davidtrott.com/repository</url>
    </pluginRepository>
  </pluginRepositories>  
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>18.0</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>javax.json</groupId>
      <artifactId>javax.json-api</artifactId>
      <version>1.0</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.0.0-alpha-2</version>
    </dependency>

  </dependencies>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>
    
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <source>1.5</source>
          <target>1.5</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.google.protobuf.tools</groupId>
        <artifactId>maven-protoc-plugin</artifactId>
        <version>0.1.10</version>
        <configuration>
          <protocExecutable>/usr/local/bin/protoc</protocExecutable>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
`

**Comment by ludoch** [comment]
```
  <pluginRepositories>
    <pluginRepository>
      <id>dtrott</id>
      <url>http://maven.davidtrott.com/repository</url>
    </pluginRepository>
  </pluginRepositories>  
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>18.0</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>javax.json</groupId>
      <artifactId>javax.json-api</artifactId>
      <version>1.0</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.0.0-alpha-2</version>
    </dependency>

  </dependencies>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>
    
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <source>1.5</source>
          <target>1.5</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.google.protobuf.tools</groupId>
        <artifactId>maven-protoc-plugin</artifactId>
        <version>0.1.10</version>
        <configuration>
          <protocExecutable>/usr/local/bin/protoc</protocExecutable>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

**Comment by ludoch** [comment]
I am working on a PR if nobody is working on this...

**Comment by nmittler** [comment]
FYI, there are snapshot artifacts here: https://oss.sonatype.org/content/repositories/snapshots/io/grpc/

Also, you can use `gradle install` do install to your local maven repository.

**Comment by ejona86** [comment]
This is in part blocked on getting Netty artifacts that we can use. The plan there is to swap to Netty 4.1.

**Comment by benmccann** [comment]
Depends on io.netty:netty-codec-http2:4.1.0.Beta5 being released

**Comment by ejona86** [comment]
Yes, the next Netty 4.1 Beta release. Originally, we were going to wait until Netty 4.1, as then there would be more frequent bug fix releases (not once a year). However, it is true that now that 4.1 is getting close Beta5 would suffice.

**Comment by benmccann** [comment]
I don't suppose it'd be possible to use Netty 4.0.26 would it? I'd love to be able to use grpc, but I have other dependencies that also depend on Netty and none of them are using 4.1 yet since it's in beta, so I'm out-of-luck until 4.1 final is released I'm afraid

**Comment by ejona86** [comment]
As of yet (to my knowledge), HTTP/2 hasn't been backported to Netty 4.0. So no, not at this time.

**Comment by hepin1989** [comment]
@benmccann there is much work to do for backport to 4.0,so keep 4.1,any way ,there will be a 4.1 final later :P.
@ejona86 release date ?

**Comment by nmittler** [comment]
FYI, Netty is leaning toward HTTP/2 support in Netty 4.1+ (https://github.com/netty/netty/issues/3515)

**Comment by benmccann** [comment]
Could we use Netty 4.1.0.Beta4 for the time being until 4.1.0.Beta5 is released? It looks like only a couple lines in NettyClientHandler rely on the beta 5 API.

**Comment by louiscryan** [comment]
There were quite a large number of bug fixes and performance fixes that went in after beta4 was cut so we need to wait for 5 sadly

**Comment by benmccann** [comment]
I asked over there and it sounds like they're quite close to beta 5 or even 4.1.0 final

**Comment by benmccann** [comment]
Think we can do this now that Netty 4.1.0.Beta5 is released and we're grabbing it from Maven?

**Comment by ejona86** [comment]
Yes, certainly. As of today we are only waiting on the few docs-related changes in the 0.7.0 milestone. We would also like #411 to be done, but we wouldn't necessarily delay for it.

**Comment by parsnips** [comment]
Any word on pushing here?

**Comment by ejona86** [comment]
We are still delaying for some Android-related changes. There has been a reasonable amount of investigation.

The plan is that we release 0.7.0 tomorrow, independent of the Android changes. If the Android changes don't make it, then we may release a 0.7.1 later.

**Comment by ejona86** [comment]
So the release didn't happen today. We were ready, but lacked enough time at the end of the day to do it. The plan now is Tuesday morning.

**Comment by ejona86** [comment]
Binaries were pushed to Maven Central on June 26th. This should be resolved.

**Comment by benmccann** [comment]
Woo! Thank you!

**Comment by zhongql** [comment]
i just use eclipse + maven in mac to develop, first define .proto file and mvn compile ,generate gRPC code in target/generated-sources ,i manually copy this files to /src/generated,and writing a client in /main/java, but it don't work, without gradle, how to building, i looked in their readme and Java tutorial ,but also have no idea how to do this for my own client/server

**Comment by ejona86** [comment]
I talked with @zhongql via email and got them working. There was no need to copy the generated files to src/generated.
