### ISSUE TITLE
Please test with broken stream IDs

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc-java#173]
Hi there,
We recently got hit in C with a crash that happened when HTTP/2 stream IDs went unexpected (violating the invariant of increase on a connection) and also aren't prepared for the situation where we approach or cross max stream id (0x7fffffffu). Please check that this case works in Java. If you need some client code to test that, I can let you use the client code that was sent to me.
This is related to C issues: https://github.com/grpc/grpc/issues/946 and https://github.com/grpc/grpc/issues/957

Thanks!
Vijay

**Comment by louiscryan** [comment]
@nmittler I believe there is coverage for this in Netty but we should validate.

**Comment by nmittler** [comment]
Netty's testing definitely covers this. From our perspective, it would look like any other protocol error.

It doesn't look like the OkHttp transport has a test for this, however.
