### ISSUE TITLE
Contexts.statusFromCancelled should be marked experimental

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1737]
I question if any of our users will actually use the method. It can be moved into `io.grpc.internal` or it can be marked Experimental. If there is a use case for it, it'd be good to know, since it didn't come up during review.

**Comment by buchgr** [comment]
hmm. We could move the method to `internal.GrpcUtil`?

**Comment by buchgr** [comment]
hmm meh. there it's probably impossible to detect. I guess it's best to mark it experimental.

**Comment by ejona86** [comment]
In GrpcUtil is fine. I figure there will be a maximum of two users of it: ServerImpl and ManagedChannelImpl/ClientCallImpl. But experimental is also fine for now.
