### ISSUE TITLE
setRemoveOnCancelPolicy is not called

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1745]
https://codecov.io/gh/grpc/grpc-java/src/900f7e1/core/src/main/java/io/grpc/internal/GrpcUtil.java#L405

At least on OpenJDK, `newSingleThreadScheduledExecutor()` [does not return a `ScheduledThreadPoolExecutor`](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/concurrent/Executors.java/#251). The documentation says:
> Unlike the otherwise equivalent newScheduledThreadPool(1) the returned executor is guaranteed not to be reconfigurable to use additional threads.

So maybe we should be using `newScheduledThreadPool(int)` instead. But since that still isn't required to be a `ScheduledThreadPoolExecutor`, maybe we should just construct a `ScheduledThreadPoolExecutor` directly.

**Comment by buchgr** [comment]
good catch!

**Comment by carl-mastrangelo** [comment]
Hmm, I would have expected that the first line of that try would have been covered.

**Comment by ejona86** [comment]
@carl-mastrangelo, it's yellow on the left, so maybe it is only partially covered because the exception. But yeah, I would have expected it as well.

**Comment by carl-mastrangelo** [comment]
Building it ourselves seems fine.
