### ISSUE TITLE
could grpc-java generate jars by modifying gradle files? how?

### ISSUE THREAD

**Issue by qiyang0221** [grpc/grpc-java#175]
I want to package these java files generated by grpc. How could I modify gradle files?

**Comment by louiscryan** [comment]
Do you mean java files generated by protoc from .proto files?

**Comment by qiyang0221** [comment]
no. I want to package these java files generated from .proto files to jars.
So I could conveniently import the jars into my project.

2015-03-10 1:59 GMT+08:00 louiscryan <notifications@github.com>:

**Comment by zhangkun83** [comment]
Please refer to the Gradle documentation, e.g., [Zip task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Zip.html) for how to package files into jars.
