### ISSUE TITLE
Tracking Issue for Plaintext being Experimental. 

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1772]
Specific usages:
- `ManagedChannelBuilder.usePlaintext`

**Comment by dapengzhang0** [comment]
widely used, proposing to next

**Comment by ejona86** [comment]
API review:
* Add new zero-argument overload. Equivalent of `true` today.
* Mark current version Deprecated, and begin migration.

**Comment by igorbernstein2** [comment]
Is there a timeline for this stabilizing? I would like to use this for implementing a bigtable emulator

**Comment by ejona86** [comment]
API review:
 * The zero-arg usePlaintext is good for stabilization.

**Comment by dapengzhang0** [comment]
API is stabilized. The deprecated method `usePlaintext(boolean)` is still there and will be deleted in a year.
