### ISSUE TITLE
Tracking Issue for Target Specification being Experimental.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1773]
Specific usages:
- `ManagedChannelBuilder.forTarget`

**Comment by Chumper** [comment]
Any thoughts on this and how stable it is currently? 
Any plans to disable/change/stable-label this?

**Comment by carl-mastrangelo** [comment]
Unlikely to change.  This was added when name resolvers / load balancing was added, which are unlikely to go away at this point.
