### ISSUE TITLE
Tracking Issue for Method Descriptor being Experimental.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1774]
Specific usages:
- `MethodDescriptor.create`
- `MethodDescriptor.extractFullServiceName`
- `MethodDescriptor.generateFullMethodName`
- `ServerMethodDefinition`
- `ServerServiceDefinition.builder`
- `ServerServiceDefintion.getMethods`
- `ServerServiceDefinition.Builder.addMethod`

**Comment by knok16** [comment]
Hello, guys,
`MethodDescriptor` is parametrized by `<RequestT, ResponseT>` but programmatically it's not possible to get this classes. What do you think about adding 2 getters to `MethodDescriptor` and populating it in generated classes:
- `Class<RequestT> getRequestClass()` / `RequestT getRequestDefaultInstance() //returns new instance each call`
- `Class<ResponseT> getResponseClass()` / `ResponseT getResponseDefaultInstance() //returns new instance each call`

_Let me know if it's wrong thread to discuss it._

**Comment by ejona86** [comment]
@knok16, this issue is for some per-existing methods on MethodDescriptor. Creating a new issue would be appropriate.

**Comment by carl-mastrangelo** [comment]
I propose that methods in MethodDescriptor be made non experimental.  Generated code calls many methods in here.

**Comment by carl-mastrangelo** [comment]
Addressed by #2594
