### ISSUE TITLE
Tracking Issue for Marshaller being Experimental.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1777]
Specific usages:
- `MethodDescriptor.Marshaller`

**Comment by dapengzhang0** [comment]
not ready for 1.1

**Comment by ejona86** [comment]
Exception handling is wonky, but it is exposed in MethodDescriptor. This has been around so long and the issues with it are small. We can introduce an new API by creating a new interface that has the new methods we want, and we can continue making new interfaces for InputStream to implement.

Let's just mark it stable. Among other things, this will help protobuf-nano removal, as the old code will continue working.
