### ISSUE TITLE
Tracking Issue for JSON Marshalling being Experimental

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1786]
Specific usages:
- `ProtoUtils.jsonMarshaller`

**Comment by dapengzhang0** [comment]
not stabilized, keep unscheduled

**Comment by wyaeld** [comment]
Is this still experimental 18 months later?

**Comment by dapengzhang0** [comment]
We will prioritize the discussion about its stabilization.

**Comment by carl-mastrangelo** [comment]
@wyaeld Can you give us a brief snippet of how you would like to use jsonMarshaller?  I mainly added it for use in some examples, but as the doc says, it isn't as battle tested as the regular marshaller.

**Comment by wyaeld** [comment]
Currently just doing some experimentation, but the basic idea was around the use-case of having a client-side front-end built in react, being able to talk to a backend (in this case spring-boot), which was serialising the same data-structures being used by the rest of the services into json for reusability.  We haven't yet done any real testing on the performance impact of this, vs the option of processing protobuf directly with js.  Interested in any feedback from good on pros/cons

**Comment by carl-mastrangelo** [comment]
The current json marshaller is the one [defined for protos](https://developers.google.com/protocol-buffers/docs/proto3#json), not for JSON in general.  If you have preexisting structures, you probably want to make your own marshaller.

**Comment by ejona86** [comment]
API review:
* Not really used. People confuse it with generic JSON. It's mainly for the example. Let's just move it to the example.

As a benefit, that will allow us to drop a dependency of protobuf-utils.
