### ISSUE TITLE
BUG: Attributes broken in 0.14.0

### ISSUE THREAD

**Issue by elandau** [grpc/grpc-java#1798]
Due to a recent change in how attributes are stored it is no longer possible to look up attributes in an incoming request.  There's a fix for this in #1763.

**Comment by zhangkun83** [comment]
@ejona86 @lukaszx0 
This change was done on purpose by #1506. This behavior matches that of the context keys, and is safe from accidental key collisions. Why can't you use the Key object to look up the attribute?

**Comment by elandau** [comment]
We have a NameResolver that receives String attributes from a remote service which allows us to drive the configuration from a central location.  We then create an Attribute.Key<String> from each of these attributes and pass them to the LoadBalancer.  The LoadBalancer looks for well known keys.   With this change any lookup for keys in the LoadBalancer returns null because the Key object created in the name resolver is different from the Key object defined in our LoadBalancer.  So, with the new behavior the is no way for us to drive configuration externally without the NameResolver knowing about all possible keys and introducing another lookup.

I suppose the main issue I have with the new approach is that I'd expect a Key object that has a single string name attribute to treat the name as unique within the Map.  It would be the responsibility of anyone defining a Key to make sure that key names are properly namespaced to avoid collisions.  This would be expected behavior in any configuration system.  Relying on object references seems dangerous and non-intuitive to me.

**Comment by ejona86** [comment]
@elandau, are all your values the same type? There was concern about the unsafe casting we were previously doing.

**Comment by zhangkun83** [comment]
> I'd expect a Key object that has a single string name attribute to treat the name as unique within the Map.

We didn't feel good about using a string as a unique key, because even with namespace conventions it's still fragile and a poorly defined key can collide with others. You get a `ClassCastException` if you are lucky. The worst case is the colliding keys are of the same type and it's hard to notice.

That's why we decided to rely on object reference, and keep the name mainly for debugging purpose.

> Relying on object references seems dangerous and non-intuitive to me

Relying on object references is actually safer, as it provides strong typing that can be checked at compile-time, and free from name collision. The consumer and the producer of a key have to use the same Key object, in which way they are bound together, which makes sure the consumer is reading the key that it intends to read.

Coming back to your use case. It seems what you need is just a `Map<String, String>`. Can you use a `Key<Map<String, String>>` instead?

**Comment by elandau** [comment]
We could use Map<String, String> for our internal configuration but this would complicate configuring things like 'params-default-port' as we would need to special case such configuration using a lookup of the string 'params-default-port' to NameResolver.Factory.PARAMS_DEFAULT_PORT.  This would become more of an issue in the future when additional attributes are added to NameResolver and LoadBalancer implementations.

I understand the desire to make this API type safe but this does make it non-intuitive to use.  If anything I would recommend changing 'name' to 'description' and have Attributes.data be an IdentityHashMap.

**Comment by ejona86** [comment]
@elandau, that's an interesting use-case. I don't think we had that in mind before. How do you handle different types of values? Is your name resolver able to specify the type?

To strongly support this pattern I think we would want to standardize attributes across languages. That may not be a bad idea, but I don't think the other languages have the equivalent of PARAMS_DEFAULT_PORT today. We've also been expecting to use rich types for attribute values; it's unclear if that would cause problems cross-language. If we don't standardize attributes cross-language then it might make most sense to manually map.

I will say that we added `PARAMS_DEFAULT_PORT` to just deal with HTTP vs HTTPS, not considering the name resolver specifying that attribute. The only way I can figure out how you're using that is to specify the attribute before delegating to the `DnsNameResolver`. That makes complete sense; we just hadn't considered that use case. There could maybe be some tweaks to the APIs in light of this, but I'm not sure what they would be.
