### ISSUE TITLE
grpc-all-0.14.0.jar on Maven Central is truncated (only 361 bytes)

### ISSUE THREAD

**Issue by alugowski** [grpc/grpc-java#1805]
grpc-all-0.14.0.jar on Maven Central is truncated and appears corrupted. Note that the "Download the JAR" link on the grpc-java front page points at this corrupt file as well.

grpc-all-0.13.2.jar is 545KB.

see:
http://mvnrepository.com/artifact/io.grpc/grpc-all/0.14.0

**Comment by ejona86** [comment]
grpc-all no longer repackages other projects; now it just depends on them. So it being extremely small is the currently expected behavior.

Are you needing a "fat" jar for integrating into your build system? Or did you just notice the size looked fishy?

**Comment by alugowski** [comment]
Both.

I can change my build system. The change in behavior was not clear, so if someone is used to downloading a .jar directly, such as by following a "Download the JAR" link, then a 361 byte file appears to be a mistake. Maybe a one-line note about the change in the 0.14 release notes would be appropriate? Also downloading this tiny jar is now pointless, so maybe the download link should instead go to the maven page where someone can find the parts?

**Comment by ejona86** [comment]
Yeah, we should update the README. It's not helpful pointing to grpc-all.

I've updated the release notes on GitHub. It's not very prominent, but at least there is hope is seeing it now.
