### ISSUE TITLE
use maven plugin generate grpc code ,why only XXXGrpc.java been generated.

### ISSUE THREAD

**Issue by yinlei212** [grpc/grpc-java#1808]
hi,
i used  maven plugn to compile example helloworld.proto, and i  specialed the <outputDirectory>${basedir}/src/main/java</outputDirectory>, the generated code only contain the GreeterGrpc.java,how can i ,generate 
`AddressBookProtos.java
HelloReply.java
HelloReplyOrBuilder.java
HelloRequest.java
HelloRequestOrBuilder.java
`
at same time.
 thank you .

maven:

```
<plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.5.0</version>
                <configuration>
                    <outputDirectory>${basedir}/src/main/java</outputDirectory>
                    <protocArtifact>com.google.protobuf:protoc:3.0.0-beta-2:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:0.14.0:exe:${os.detected.classifier}</pluginArtifact>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by ejona86** [comment]
This seems a maven plugin specific question; you'd do better asking on [it's repo](https://github.com/xolstice/protobuf-maven-plugin). I would expect the issue is caused by the plugin cleaning the directory before each generation step, as [discussed on StackOverflow](http://stackoverflow.com/questions/7881905/how-to-stop-apache-maven-outputdirectory-to-overwrite-the-folder).

**Comment by cddude229** [comment]
For other users who hit this: https://github.com/xolstice/protobuf-maven-plugin/issues/8 has a work around that was perfect for my use case.
