### ISSUE TITLE
ServerCallStreamObserverImpl should record where cancellation came from

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1824]
Currently a single boolean "cancelled" is set which loses where the observer was cancelled from.

**Comment by ejona86** [comment]
Do servers actually care?

**Comment by ejona86** [comment]
@carl-mastrangelo, ping. Do servers actually care? Right now servers aren't provided with cancellation details.

**Comment by ejona86** [comment]
This didn't end up making too much sense, because the cancellation always comes from the same place and the solution would always make a new exception, even when unnecessary. So just closing.
