### ISSUE TITLE
Deadlines relative to call start

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#1849]
Right now, it's not possible to set a deadline across all calls on a stub, doing something like stub.withDeadline(1, TimeUnit.SECONDS) starts counting right at this point, so when a single stub is injected and shared throughout the application, the deadline is quickly triggered :)

It would be nice to have something like stub.withDeadlineAfterStart(1, TimeUnit.SECONDS) that doesn't trigger until the newCall or start methods are called potentially.  This would allow me to configure my gRPC client with a deadline that is usable by default on all calls and also "correct" for my usage in how it counts down.  Is this something you'd be open to?

**Comment by carl-mastrangelo** [comment]
nit: What you want is a Timeout.  Deadlines are absolute points in time, Timeouts are relative.

**Comment by louiscryan** [comment]
Why not implement an interceptor that customizes the CallOptions passed to
the underlying channel to enforce the desired deadline requirements?

**Comment by jhspaybar** [comment]
Yea, I had considered an interceptor, but thought if there was a Deadline I should just use it.  As it turns out...A timeout isn't a deadline :).  If an interceptor is the proper way to do this, I can just do it that way.

**Comment by ejona86** [comment]
Is it appropriate for all methods of the stub to use the same timeout? It seems they would commonly vary, especially if streaming is involved. @jhspaybar, is that a concern for your case?

**Comment by jhspaybar** [comment]
In general, yes I think it would be a problem, this particular service only has 1 rpc though :).  If we went an interceptor approach though it could be configured in a way that inspects the method and has different timeouts for each.  Given the discussion so far, that certainly seems like the best idea.

**Comment by ejona86** [comment]
Earlier in development we had a per-method timeout that could be specified in the protobuf. We back-peddled from that because the service owner commonly wants to be able to adjust the timeout without needing all clients to be recompiled. So it became a bit of a TODO

**Comment by jhspaybar** [comment]
Closing, the intercept approach worked well.
