### ISSUE TITLE
Mistake in gRPC Basics: Java tutorial

### ISSUE THREAD

**Issue by Alvcohen** [grpc/grpc-java#1850]
http://www.grpc.io/docs/tutorials/basic/java.html#implementing-routeguide

says that we should declare service as:

```java
private static class RouteGuideService implements RouteGuideGrpc.RouteGuide
```

but example file declares service implementation as:

```java
private static class RouteGuideService extends RouteGuideGrpc.AbstractRouteGuide 
```

if class implements RouteGuideGrpc.RouteGuide then the server cannot be created as the next tutorial section says:

```java
server = serverBuilder.addService(new RouteGuideService(features)).build();
```

because our service doesn't extend AbstractRouteGuide and thus doesn't implement BindableService interface.

A tiny problem but causes gRPC first timers like me some headache.

**Comment by ejona86** [comment]
Ah, I see. We hadn't intended to update those docs to use BindableService yet, but due to [some other fixes](https://github.com/grpc/grpc.github.io/commit/936847592cb3d9744b9835e2456e1356ac2acb64) it made its way in without getting fully updated.

**Comment by ejona86** [comment]
For the moment I think I'll have it swap back to calling `RouteGuideGrpc.bindService(new RouteGuideService(features))` and then we can do a later pass to fix the interface->abstract class change.
