### ISSUE TITLE
Metadata trailers are not passed to Status*Exception when using BlockingResponseStream

### ISSUE THREAD

**Issue by dstore-dbap** [grpc/grpc-java#1861]
Hi @nmittler,

thanks for improving the error handling via #1811 and solving #681.

When using blockingStubs on the client the metadata trailers are not passed into the Status*Exception. Your changeset adds this ability to 2 of 3 onClose methods of stub/ClientCalls.java.

Did you just miss to add the trailer handling to the BlockingResponseStream class in https://github.com/grpc/grpc-java/blob/641cb357c68cba5f0d1820973c6a6c0c908dc074/stub/src/main/java/io/grpc/stub/ClientCalls.java#L485 or is there another reason for dropping the trailers in this case?

Regards,
Björn

**Comment by nmittler** [comment]
@dstore-dbap looks like an oversight, thanks for pointing that out!

I rolled PR #1862
