### ISSUE TITLE
Fail-fast mode

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#1863]
According to https://github.com/grpc/grpc/blob/master/doc/fail_fast.md, fail-fast mode is enabled by default. But it didn't say how to disable it.
I couldn't find much resource for fail-fast mode other than the file. Can anyone link me to related example/code/documentation? Thanks!

**Comment by ejona86** [comment]
Java is not doing fail fast nor "non-fail-fast" today. The spec precedes any implementations, since the implementations are supposed to follow the spec. See #1759. Eventually, there will be a method to call on the Stub/CallOptions.
