### ISSUE TITLE
Lots of garbage created by Netty's HPACK encoder

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1872]
Netty takes great pains to not copy data unnecessarily, so it was surprising to find lots of garbage being created in the Hpack encoder.  Specifically, most of it comes from https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/internal/hpack/StaticTable.java#L130

Which creates a new string for most (all?) headers.   We should fix this!

**Comment by carl-mastrangelo** [comment]
+cc: @Scottmitch   FYI.  This might be an easy fix, but I haven't looked into it extensively.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Yes I have been meaning to scrub the hpack code to make the interfaces line up with Netty types a bit more which should help reduce object allocation etc... haven't gotten around to it yet though @normanmaurer - Didn't you have a PR pending at some point related to the HPACK code?

**Comment by normanmaurer** [comment]
@carl-mastrangelo @Scottmitch yes I did some work here and totally forgot about it. Let me finish it and fix this. 👍

**Comment by normanmaurer** [comment]
Expect a  fix this week

**Comment by buchgr** [comment]
@normanmaurer sounds good. let me know if you don't have enough time, then I ll take care. thanks!

**Comment by normanmaurer** [comment]
No worries... Looking into it as we speak

**Comment by Scottmitch** [comment]
Also see https://github.com/netty/netty/issues/3597 for an issue I opened related to this issue a while ago

**Comment by normanmaurer** [comment]
Guys please check https://github.com/netty/netty/pull/5355

**Comment by buchgr** [comment]
Fixed by #1999
