### ISSUE TITLE
grpc tls

### ISSUE THREAD

**Issue by chenzang** [grpc/grpc-java#1874]
We created a server and a client with tls in nodejs. This works. Below is the snippet. 

server code
```
function main() {
   var server = new grpc.Server();
    server.addProtoService(ogury_proto.Data.service, {sendMessage: sendMessage, sendMessageStream: sendMessageStream});
    var key_path = path.join(__dirname, './keys/server.key');
    var pem_path = path.join(__dirname, './keys/server.crt');

    var key_data = fs.readFileSync(key_path);
    var pem_data = fs.readFileSync(pem_path);
    server_creds = grpc.ServerCredentials.createSsl(null,
        [{private_key: key_data,
            cert_chain: pem_data}]);
    server.bind('0.0.0.0:50052', server_creds);
    server.start();
}
```

client code
```
var ca_path = path.join(__dirname, './keys/server.crt');
var ca_data = fs.readFileSync(ca_path);
var client = new ogury_proto.Data(process.env.HOST + ':50052', grpc.credentials.createSsl(ca_data));

```
We want to create a client in java that can communicate with the server in nodejs. But this does work. Below is the code for java client
```
channel = NettyChannelBuilder.forAddress(HOST, PORT)
            .sslContext(GrpcSslContexts.forClient().trustManager(ClientGrpcSimple.class.getResourceAsStream("/server.crt")).build())
            .negotiationType(NegotiationType.TLS)
            .build();
```
The error message server side is 

```
E0525 16:55:46.838418837    6297 ssl_transport_security.c:437] SSL_read returned 0 unexpectedly.
E0525 16:55:46.838446628    6297 secure_endpoint.c:173]      Decryption error: TSI_INTERNAL_ERROR
```
Below is the command to generate our server.key and server.crt

```
# Create private key
openssl genrsa -des3 -out server.key 4096

# Create Certificate Signing Request
openssl req -new -key server.key -out server.csr

# Self sign certificate with our own private key
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

# Decrypt (des3) the private key in order to be used to decrypt ssl messages
openssl rsa -in server.key -out server.key
```
We tried to generate the key and the certificate following this link
https://github.com/grpc/grpc-java/tree/master/testing/src/main/resources/certs
But these commandes don't work, we couldn't follow. 

Could you help us, please?

**Comment by carl-mastrangelo** [comment]
I seem to vaguely recall there being an issue with Java's certificate parsing, which needs to be in a special format not generated by default by openssl.  Can you try the advice given here: (to use PKCS8)

http://stackoverflow.com/questions/11410770/load-rsa-public-key-from-file

**Comment by ejona86** [comment]
Did Java produce any error (or the RPC failed with a status)? Which version of Java were you using? Were you using Jetty ALPN Boot or tcnative?

Closing because the issue has gone stale. With new information it can be reopened.
