### ISSUE TITLE
More flexible SSL configuration API

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#1881]
Today `ServerBuilder.useTransportSecurity` takes two files as parameter. However, sometimes only `InputStream`s for the key and cert files are available. Can we add an API to take two input streams?

**Comment by ejona86** [comment]
We didn't originally because I think tcnative required a File (or we thought it required a File) and we didn't want to save the private key InputStream to a temporary file without the user's knowledge. This may be possible now.

**Comment by zpencer** [comment]
Looks like it is indeed possible now:
http://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#forServer-java.io.InputStream-java.io.InputStream-

**Comment by bidossessi** [comment]
@zpencer Could I ask why your PR was closed? Is something in the works on this issue?

**Comment by ejona86** [comment]
I think with #4316 this was completed. I will note though that we also have the newer Credentials API that also allows using InputStreams but also configuring many more TLS parameters.
