### ISSUE TITLE
added android:shareUserId then io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

### ISSUE THREAD

**Issue by test346508** [grpc/grpc-java#1899]
added android:shareUserId then io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

help...

**Comment by ejona86** [comment]
@zsurocking, do you remember the solution we came up for this?

**Comment by test346508** [comment]
@zsurocking    help...

**Comment by test346508** [comment]
@zsurocking     senior    need you...

**Comment by test346508** [comment]
@zsurocking    senior  ,  i  need  you...

**Comment by ejona86** [comment]
I came across https://github.com/grpc/grpc-java/blob/v0.14.0/core/src/main/java/io/grpc/ManagedChannelProvider.java#L92 , which seems like you shouldn't be having trouble. Everything functions if you remove `android:shareUserId`? If not, it may be a ProGuard issue.

**Comment by zsurocking** [comment]
I don't think I've seen this before... But I agree with @ejona86 , it might be proguard issue. Maybe try to analyze the dex file?

**Comment by ejona86** [comment]
@zsurocking, ah, it was probably madongfly that I discussed it with, then.

**Comment by test346508** [comment]
thanks , @ejona86  @zsurocking   solved,   The version is too old...
