### ISSUE TITLE
Stabilize generated MethodDescriptor API

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1901]
Today, the generated method descriptors are available as fields. This should probably be changed to be behind a method of some sort so that they can be generated lazily (to reduce static class loading time for Android).

**Comment by zpencer** [comment]
Seems like an API related issue, adding tag for easier searching

**Comment by ejona86** [comment]
#3618 adds methods for the fields. After giving a little time to convert code over, the fields can be removed.

**Comment by ejona86** [comment]
API review notes:
* The getFooMethod() methods are fine to stabilize.
* There is some concern about collisions due to CamelCasing vs snake_casing. That may need to be resolved first.
