### ISSUE TITLE
Swap Android docs to Protobuf Lite

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1930]
Protobuf lite is a much nicer API than nano and is very similar API-wise to normal protobuf. We should swap the example to lite instead of nano.

The README should also be swapped to encouraging protobuf-lite for Android instead of protobuf-nano.

**Comment by ejona86** [comment]
This is dependent on #1985. But then #1942 would change the examples.

**Comment by david-cao** [comment]
Since #1985 is upgrading everything to beta-3, technically this should still be happy, since there would only be a redundant `compile 'com.google.protobuf:protobuf-java:3.0.0-beta-3'` in the build.gradle (unless that does break gradle, not well versed enough in it).
