### ISSUE TITLE
Include QuickStart example in documentation

### ISSUE THREAD

**Issue by mykyta-protsenko** [grpc/grpc-java#1945]
Hello,

I wonder if the documentation can be impoved by pulling in quickstart examples from grcp.io? It took me about half an hour to even start experimenting after reading the GitHub documentation - then somebody showed me grpc.io example and it was SO much easier to start learning and experimenting using those examples.

Thank you!

**Comment by ejona86** [comment]
Things should be much better now. Redesigned grpc.io and examples/ in grpc-java is much easier to use.

We should probably add a link to the top of the helloworld/routeguide examples that links to the quickstart/tutorial.
