### ISSUE TITLE
Service implementation running in a different thread than "ServerCall<RespT>.request()"?

### ISSUE THREAD

**Issue by testark** [grpc/grpc-java#1949]
I've implemented a simple `ServerInterceptor` whose intent is to grab the value of an header (a "trace ID") and place it in the MDC upon receiving a request (and to do the reverse when request handling finishes).

However I've noticed that the service implementation itself and the interceptor's `close` method are being run in a thread different than the one that originally runs the interceptor's `request` method. This causes contextual (MDC) information to be lost. These are my service's logs (the UUIDs are the "trace IDs"):

```
[2016-06-17 19:24:05.911] [ grpc-default-executor-0] [HeaderServerInterceptor] [8d0b9de0-b73b-41ad-a8f4-732b6a6997f9] MDC was set.
[2016-06-17 19:24:05.914] [ grpc-default-executor-1] [HeaderServerInterceptor] [5914fc54-f107-4c5f-b647-106537dc393d] MDC was set.
[2016-06-17 19:24:05.915] [ grpc-default-executor-0] [HeaderServerInterceptor] [fae36ee7-a017-44db-ae3e-04b36afd31a4] MDC was set.
[2016-06-17 19:24:05.921] [ grpc-default-executor-0] [HeaderServerInterceptor] [a7f6511d-1206-4639-bdc0-21319343fcb2] MDC was set.

[2016-06-17 19:24:05.946] [ grpc-default-executor-0] [     FooServiceGrpcImpl] [a7f6511d-1206-4639-bdc0-21319343fcb2] Hello from the service implementation!
[2016-06-17 19:24:05.946] [ grpc-default-executor-1] [     FooServiceGrpcImpl] [5914fc54-f107-4c5f-b647-106537dc393d] Hello from the service implementation!
[2016-06-17 19:24:05.946] [ grpc-default-executor-2] [     FooServiceGrpcImpl] [                                    ] Hello from the service implementation!
[2016-06-17 19:24:05.952] [ grpc-default-executor-3] [     FooServiceGrpcImpl] [                                    ] Hello from the service implementation!

[2016-06-17 19:24:07.526] [ grpc-default-executor-3] [HeaderServerInterceptor] [                                    ] Trailers will now be set.
( NullPointerException )
```

My interceptor's implementation is roughly the following:

```java
public final class HeaderServerInterceptor implements ServerInterceptor {
  private static final Logger LOGGER = LoggerFactory.getLogger(HeaderServerInterceptor.class);

  @Override
  public <ReqT, RespT> Listener<ReqT> interceptCall(final MethodDescriptor<ReqT, RespT> method,
                                                   final ServerCall<RespT> call,
                                                   final Metadata headers,
                                                   final ServerCallHandler<ReqT, RespT> next) {
    return next.startCall(method, new SimpleForwardingServerCall<RespT>(call) {
      @Override
      public void request(final int numMessages) {
        final String requestId = headers.get(MetadataKeys.REQUEST_ID_KEY);
        MDC.put(MetadataKeys.REQUEST_ID_KEY_NAME, requestId);
        LOGGER.trace("MDC was set.");
        super.request(numMessages);
      }

      @Override
      public void close(final Status status,
                        final Metadata trailers) {
        final String requestId = MDC.get(MetadataKeys.REQUEST_ID_KEY_NAME);
        LOGGER.trace("Trailers will now be set.");
        trailers.put(MetadataKeys.REQUEST_ID_KEY, requestId); // NPE.
        super.close(status, trailers);
      }
    }, headers);
  }
}
```

Is this an expected behaviour that I should be prepared for, or am I facing some kind of issue on gRPC's side?

**Comment by jhspaybar** [comment]
You need to set the MDC on every callback inbound is my understanding.  I don't unset the MDC, but you could do so if you wanted by removing the map you'd set in a finally block around every super call.  For my use case, I didn't need to worry about unsetting it since I just clobber what was there on the inbound.

```
@Override
	public <ReqT, RespT> Listener<ReqT> interceptCall(
			final MethodDescriptor<ReqT, RespT> method,
			final ServerCall<RespT> call,
			final Metadata headers,
			final ServerCallHandler<ReqT, RespT> next) {
		final Map<String, String> mdcContext = buildMdcContext();
		MDC.setContextMap(mdcContext);

		final Listener<ReqT> original = next.startCall(method, call, headers);
		return new ForwardingServerCallListener.SimpleForwardingServerCallListener<ReqT>(original) {
			@Override
			public void onMessage(final ReqT message) {
				MDC.setContextMap(mdcContext);
				super.onMessage(message);
			}

			@Override
			public void onHalfClose() {
				MDC.setContextMap(mdcContext);
				super.onHalfClose();
			}

			@Override
			public void onCancel() {
				MDC.setContextMap(mdcContext);
				super.onCancel();
			}

			@Override
			public void onComplete() {
				MDC.setContextMap(mdcContext);
				super.onComplete();
			}

			@Override
			public void onReady() {
				MDC.setContextMap(mdcContext);
				super.onReady();
			}
		};
	}
```

**Comment by testark** [comment]
@jhspaybar thank you for your input. However, the result in my scenario seems to be the same. I believe this may be related to the fact that the underlying executor is the (default) cached thread pool. @ejona86 can you please comment on this?

**Comment by ejona86** [comment]
Each callback may happen on a different Thread (from the Executor of the Server, by default a CachedThreadPool). So as @jhspaybar points out, you have to set the thread-local each callback. You should generally also unset it after each callback in a finally, like was mentioned. New callbacks can be added over time and if you don't unset the thread local, you may not notice accidentally using the wrong value.

It may not be a bad idea for grpc to have a new forwarding listener that lets you override `enter()` and `exit()` and calls them for every callback.

**Comment by jhspaybar** [comment]
@ejona86 I'll contribute this back, should I create something like a SimpleForwardingServerCall with a before() and after() method, or should I push this all the way up to the base PartialForwardingServerCall and call before() and after() in all methods with the base class having protected empty implementations?

**Comment by ejona86** [comment]
@jhspaybar, sorry, I just saw this. I'd imagine something like `SimpleForwardingServerCall` that has before() and after(). Putting it in `PartialForwardingServerCall` doesn't seem to provide much benefit.

**Comment by christ258** [comment]
How do you pass header information from the HeaderServerInterceptor to the service .
