### ISSUE TITLE
protoc-gen-grpc-java snapshot doesn't have a mac build published

### ISSUE THREAD

**Issue by bobymicroby** [grpc/grpc-java#1951]
Hi guys, we have tried to switch to the latest snapshot, but unfortunately only our
linux users were successful. Do you have plans to publish the mac snapshots to sonatype
or we should build on our own ?

**Comment by ejona86** [comment]
SNAPSHOTS for codegen only have one OS supported. If we make a snapshot from another OS, then I believe it "hides" the earlier snapshot/OS. I've prepared some changes to push soon that I think restore compatibility with previous codegen versions, which would allow you to use the released version of protoc-gen-grpc-java with snapshot of the rest of grpc-java.

**Comment by ejona86** [comment]
I need to verify, but I think #1954 will make the old codegen work with new library.

**Comment by bobymicroby** [comment]
Great. We have built the codegen locally but will try again with #1954
