### ISSUE TITLE
Android Build Failed with an exception. Could not resolve all dependencies for configuration ':app:protobufToolsLocator_grpc'.

### ISSUE THREAD

**Issue by mausamdoshi** [grpc/grpc-java#1968]
Could not resolve all dependencies for configuration ':app:protobufToolsLocator_grpc'.
> Could not find io.grpc:protoc-gen-grpc-java:0.15.0-SNAPSHOT.
  Searched in the following locations:
      file:/Users/mausam/Documents/Mausam/Android Studio 2.app/Contents/gradle/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/maven-metadata.xml
      file:/Users/mausam/Documents/Mausam/Android Studio 2.app/Contents/gradle/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT.pom
      file:/Users/mausam/Documents/Mausam/Android Studio 2.app/Contents/gradle/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT-osx-x86_64.exe
      https://jcenter.bintray.com/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT.pom
      https://jcenter.bintray.com/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT-osx-x86_64.exe
      file:/Users/mausam/.m2/repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/maven-metadata.xml
      file:/Users/mausam/.m2/repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT.pom
      file:/Users/mausam/.m2/repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT-osx-x86_64.exe
      file:/Users/mausam/Library/Android/sdk/extras/android/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/maven-metadata.xml
      file:/Users/mausam/Library/Android/sdk/extras/android/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT.pom
      file:/Users/mausam/Library/Android/sdk/extras/android/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT-osx-x86_64.exe
      file:/Users/mausam/Library/Android/sdk/extras/google/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/maven-metadata.xml
      file:/Users/mausam/Library/Android/sdk/extras/google/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT.pom
      file:/Users/mausam/Library/Android/sdk/extras/google/m2repository/io/grpc/protoc-gen-grpc-java/0.15.0-SNAPSHOT/protoc-gen-grpc-java-0.15.0-SNAPSHOT-osx-x86_64.exe
  Required by:
      android:app:unspecified

**Comment by kraghu** [comment]
any reason why this happens ?

**Comment by ericgribkoff** [comment]
The *-SNAPSHOT dependencies are only for use if you're [building the code generation plugins](https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin) locally yourself, which is typically not the case and will result in being unable to locate the specified dependencies. You should be depending on a release version of the jar, e.g., 1.4.0. The tagged releases on Github will use the correct dependencies. See https://grpc.io/docs/quickstart/android.html for an example Android app using the v1.4.0 branch.

**Comment by kraghu** [comment]
cool thanks
