### ISSUE TITLE
[proto3] Default value for message is null?

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#1973]
From [this doc](https://developers.google.com/protocol-buffers/docs/proto3#default), default value for message field is null, while from the generated code, it seems the `DEFAULT_INSTANCE` of the message is returned, which is not null.
Is the doc wrong?

**Comment by biran0079** [comment]
According to https://github.com/google/protobuf/issues/359, message field can be `null`. 
It seems to me that protobuf for java is not implemented correctly?

**Comment by jhspaybar** [comment]
For what it's worth, this caught me off guard as well.  I just use the hasX() messages now when I want to test if a message was set or not.  It may be better to open this issue against the protobuf library as well as gRPC just creates a compiler plugin but isn't the core project for how Java protobuf works.

**Comment by biran0079** [comment]
@jhspaybar: I actually meant proto version 3, sorry for confusion. 
`hasX()` method is not even generated in proto3.
It should work correctly for proto2 though.

**Comment by ejona86** [comment]
Requests and responses themselves will be non-`null`, as zero bytes is actually a valid encoding for a message. Nested messages can be `null` though, because field presence is possible in the wire format (since _nested_ messages a length-prefixed). Field presence (`hasx()`) is gone in proto3 for _primitives_ but still exists for _messages_, to align with and gain efficiency in many programming languages (C++, Java, Go, C#).

**Comment by biran0079** [comment]
@ejona86: thanks for the detailed explanation!
I didn't notice that `hasX()` is still present for nested messages. 
There is still one thing I am confused: `getX()` seems never return `null` even when the field "is null". 

```
message TestBool {
  bool inner = 1;
}
message TestWrapper {
  TestBool outer = 1;
}
```
generates 
```java
public TestBool getOuter() {
  return outer_ == null ? TestBool.getDefaultInstance() : outer_;
}
```
Is that intended?

**Comment by ejona86** [comment]
@biran0079, hmmm... I would have expected it to be `null`. But it does appear to be on purpose. That'd be a question for protobuf.

**Comment by biran0079** [comment]
I filed https://github.com/google/protobuf/issues/1718, and it seems the documentation is wrong.

So in proto3, `hasX()` can tell if a message field is set or not, and `getX()` will return the default instance of the proto if unset.
