### ISSUE TITLE
cannot find a NameResolver exception for revision fc5197fbf4ca51bd76484b28e155beb52c0c0a90

### ISSUE THREAD

**Issue by LeeYeeze** [grpc/grpc-java#1982]
@ejona86 @carl-mastrangelo 
I check out the most recent commit, and find out that there is something wrong with channel initialisation.
  
    package com.testbase;

    import io.grpc.internal.ManagedChannelImpl;
    import io.grpc.netty.NettyChannelBuilder;
    import io.grpc.okhttp.OkHttpChannelBuilder;

    public class Demo {
	    public static void main(String[] args) {
		    ManagedChannelImpl wrapped = OkHttpChannelBuilder.forAddress("127.0.0.1", 9999)
      		          .usePlaintext(true)
      		          .build();
	    }
    }

What I get is:
    
    Exception in thread "main" java.lang.IllegalArgumentException: cannot find a NameResolver for     127.0.0.1:9999 (Illegal character in scheme name at index 0: 127.0.0.1:9999)
    at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:257)
	    at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:167)
	    at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:210)
	    at com.testbase.Demo.main(Demo.java:11)

And the same exception for netty transport too. Replacing 127..0.0.1 with localhost doesn't work. It happens on all the IPv4 addresses I try.

**Comment by ejona86** [comment]
Are you using ProGuard? If so, you need rules for NameResolverProvider and DnsNameResolverProvider as seen in 4372ceee

**Comment by LeeYeeze** [comment]
No, I'm not. And when I revert back to an earlier revision, the snippet works again

**Comment by ejona86** [comment]
56a2938830e is probably the breaking change, although you were probably already unable to use `ManagedChannelBuilder.forAddress("127.0.0.1", 9999)`. Is there anything interesting about your build, like using jarjar/shading?

**Comment by LeeYeeze** [comment]
I tried two ways, one is building with maven-assembly the second is put grpc code directly into the same project with the snippet and run it in eclipse, same exception.

**Comment by ejona86** [comment]
Something is going wrong while trying to load name resolvers, specifically the DNS resolver. This is done using ServiceLoader in the JDK, which reads in [this file](https://github.com/grpc/grpc-java/blob/56a2938/core/src/main/resources/META-INF/services/io.grpc.NameResolverProvider) and then does `Class.forName("io.grpc.internal.DnsNameResolverProvider")`.
