### ISSUE TITLE
Provide Code Style definition file

### ISSUE THREAD

**Issue by justinsb** [grpc/grpc-java#201]
Would it be possible to provide the code style definition file you're using with Intellij?

Along these lines: https://www.jetbrains.com/idea/webhelp10.5/exporting-project-code-style-settings.html

This would make it easier to contribute to grpc!

**Comment by ejona86** [comment]
This seems related, but not identical to #111.

**Comment by ejona86** [comment]
@louiscryan, @nmittler, do y'all know the quality of the IntelliJ and Eclipse java-google-style.xml at https://google-styleguide.googlecode.com/svn/trunk/ ? It seems like at least referencing people to those files and making sure they are sane would be a good solution.

**Comment by nmittler** [comment]
I haven't used them yet ... in fact I just noticed they were there this morning :).  Perhaps we should contact the owners? https://code.google.com/p/google-styleguide/people/list

**Comment by ejona86** [comment]
I've known about them because they are older than the style guide itself. It was sort of an awkward situation to not have a public Java style guide but have those files sitting around.

We expect they are better than nothing? We can suggest using them and if there are problems we fix them?

**Comment by nmittler** [comment]
That seems reasonable to me

**Comment by justinsb** [comment]
Thanks.  I'm using the files.  They aren't an exact match for the existing code, but they are very close (I think the main difference is continuation lines).

I have a branch https://github.com/justinsb/grpc-java/tree/codestyle which includes the files and some notes on how to use it with IntelliJ, but right now it probably isn't worth maintaining our own copy of these files.

**Comment by nmittler** [comment]
@ejona86 can we close this?
