### ISSUE TITLE
Custom HostnameVerifier for NettyChannelBuilder 

### ISSUE THREAD

**Issue by leslie-leder** [grpc/grpc-java#2016]
Would it be possible to provide a customizable javax.net.ssl.HostnameVerifier on he client side?
The most http clients provide this feature in order to deal with "generic selfsigned certificates".

Currently I use netty's InsecureTrustManagerFactory, which trusts all certificates not just mine.

```
val sslContext = GrpcSslContexts.forClient()
    .trustManager(InsecureTrustManagerFactory.INSTANCE)
```

**Comment by carl-mastrangelo** [comment]
There are a couple overloads of that method, would one of them work for you? I.e.

```
SslContextBuilder trustManager(File trustCertCollectionFile)
```

**Comment by leslie-leder** [comment]
I'm aware of this one. The problem is the that I have to deal a lot with closed systems where all servers have the same selfsigned certificate. This seems simple. I can instruct the client to trust that certificate. But this is not enough. The certificate doesn't just need to be trusted and valid. It also must be originated from the proper host. Means the certificates distinguished name (dn) must match the host name of the target which is of course not possible in case of one certificate for multiple hosts.

This seem to be a usual (albeit not accurate) setup. So all HTTP (java) clients I know provide a HostnameVerifyer interface in order to intercept SSL hostname validation.

    javax.net.ssl.HttpsURLConnection
      .setHostnameVerifier(HostnameVerifier v)

**Comment by carl-mastrangelo** [comment]
Alternatively, you could implement the TrustManagerFactory, which IIRC lets you have fine control over what gets trusted.  We had implemented that at one point, but scrapped it for some reason that I don't recall.

**Comment by ejona86** [comment]
It sounds like [`overrideAuthority()`](http://www.grpc.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#overrideAuthority-java.lang.String-) would do what you need. We purposefully do not allow you to disable TLS security. overrideAuthority doesn't disable the checks, just basically allows you to easily circumvent DNS restrictions.
