### ISSUE TITLE
Consider doing header processing on Application thread

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2024]
Profiling shows that about 10% of time on the network thread on a spinning benchmark is spent converting from Netty Headers to gRPC Metadata.  This has been optimized recently, and the profiling doesn't include recent Netty changes, but most of the time is actually in the gRPC code!

An idea to fix this would be to punt the conversion of Transport Headers to gRPC Headers onto an application thread, freeing up the network thread.  I don't imagine this would have big CPU savings, but could have a latency spike. 

cc @buchgr  thoughts?

**Comment by buchgr** [comment]
Good idea Carl. I think we should give it a try. I think this might give us a bigger boost in benchmarks than in many real world apps, as the application threads are mostly idle in benchmarks. And just to state the obvious, for direct executor this does not matter :-).

**Comment by carl-mastrangelo** [comment]
This will likely be obsoleted by an alternative header processing optimization (namely, by avoiding it altogether.)
