### ISSUE TITLE
Metadata trailers are not passed to Status*Exception when using ClientCalls.blockingUnaryCall.

### ISSUE THREAD

**Issue by chikei** [grpc/grpc-java#2036]
Trying to write a sample for #1295, but when calling unary rpc method on blocking stub, the trailers are not passed during `ClientCalls.getUnchecked` which is called from [ClientCalls.blockingUnaryCall](https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/ClientCalls.java#L141).

Is this by design or bug ?

Sample code is [here](https://github.com/chikei/grpc-java/commit/ea1ec3f5503a40d39c0ad10360c8a6ecbad46eca), the [blockingCall()](https://github.com/chikei/grpc-java/blob/ea1ec3f5503a40d39c0ad10360c8a6ecbad46eca/examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java#L94) fails but others are good.

**Comment by thesamet** [comment]
@xuwei-k FYI.  No current plan, PR will be welcome.

**Comment by ejona86** [comment]
That's a bug.

[This repackaging of the exception](https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/ClientCalls.java#L208) is losing the trailers. It does seem that [the exception in the future](https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/ClientCalls.java#L411L417) has the trailers.
