### ISSUE TITLE
Need docs on how to run integration test suite

### ISSUE THREAD

**Issue by justinsb** [grpc/grpc-java#204]
It seems that this is the way:

Tab/window/screen 1:
```
./run-test-server.sh 
```

Tab/window/screen 2:
```
./run-test-client.sh --use_test_ca=true --server_host_override=foo.test.google.fr --test_case=empty_unary
./run-test-client.sh --use_test_ca=true --server_host_override=foo.test.google.fr --test_case=large_unary
./run-test-client.sh --use_test_ca=true --server_host_override=foo.test.google.fr --test_case=client_streaming
...
```

Is that correct?

And is there a way to avoid paying the Groovy/Gradle tax for every test?

**Comment by ejona86** [comment]
Yes, that is correct. Note that for Java->Java we already run all the tests via Http2NettyTest. --help is supported, in case that helps.

Yeah, re-running Gradle is a bit weak. We are likely to support CreateStartScripts (like in benchmarks) but haven't gotten to it yet (I just now created #205 for it). I've discussing supporting a comma-delimited list of tests to be run, but, again, haven't done the work for it. Note that the comma-delimited solution we would want all languages to support, as I've been trying to standardize the arguments between the various languages.

(and in related news, I just created https://github.com/grpc/grpc/issues/1045 for better visibility of integration tests)

What do you hope to do with the integration tests?

**Comment by ejona86** [comment]
I see why you are running the integration tests now (for testing #202). Yeah, running them manually like you are is the appropriate way for the moment.

We should probably have a separate section of documentation for tips and tricks for developers. Discussion of the transport API in the current README.md could be moved to that section.

**Comment by justinsb** [comment]
A "development 101" section is a great idea.  I did a super-quick sketch of the stuff I had so far:


```
If you want to contribute, here are some tips to get you going.

Gradle can produce IntelliJ project files: run ```./gradlew idea```

# Code format

Code format is:

Use spaces for tabs
Tab = 2 characters

Editor rulesets:

Intellij: ???

# Coding style

Checkstyle rules are in ???

You can run checkstyle using: ???

# Tests

There is a unit-test suite; run it using:

???


There is an integration test suite; run it using:

????

# Submitting code

Submit code via Pull Requests on Github.

Small pull requests are usually better than big pull requests.

You will need to sign a Google CLA (link???) to contribute.
```


If this is useful I could do a PR (once I flesh it out), or maybe we should just enable the Wiki on this repo?

**Comment by ejona86** [comment]
Checkstyle has just now been put in place. Checkstyle, unit tests, and java-java integration tests are all done in "./gradle build".

We aren't (yet) enabling wiki because it isn't clear what we want on grpc.io and what to be on this wiki.

The submitting code portion should be placed in CONTRIBUTING.md. We should say that we expect "gradle build" to be run, since it checks style and tests.

**Comment by ejona86** [comment]
Partly covered by #216

**Comment by justinsb** [comment]
Thanks.  Adding this into "gradlew test" would be great.  I created a basic JUnit test for Netty with SSL in my PR, though I can't use it yet because ALPN/NPN would need to be on the classpath.

Also, having this run in Travis is great!

If we can get these tests running in JUnit, this meets the "intent" behind my question - I just wanted to be able to run tests that included SSL configurations.
