### ISSUE TITLE
Service is still running when client is killed.

### ISSUE THREAD

**Issue by oranges196** [grpc/grpc-java#2057]
My service queries lot of data by jdbc and sends to client using grpc stream. If I killed the client, the service cant catch a exception, and it still running the circle to query from jdbc and write to stream. I cant find a method to receive a notify that grpc completed. What should I do, please?

**Comment by ejona86** [comment]
Can you provide a code snippet, or approximation of what you are doing? It's important from which method you are sending, and what you sending loop looks like.
