### ISSUE TITLE
Deprecated method warning when upgrading to 0.15.0

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#2063]
I got following warning messages in generated code.
Proto version is `3.0.0-beta-3`.

```mandatory_warning: writeRawVarint32(int) in com.google.protobuf.CodedOutputStream has been deprecated
        output.writeRawVarint32(10);```

**Comment by ejona86** [comment]
It's a protobuf issue: https://github.com/google/protobuf/issues/1596

**Comment by ejona86** [comment]
This may be fixed with beta-4... which was apparently just released. We'll be giving it a try.

You are free to try to bump your proto runtime version and protoc version (continuing to use the same grpc protoc plugin version).
