### ISSUE TITLE
[Question] BlockingResponseStream.hasNext blocks forever

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#2066]
I run into an issue that `BlockingResponseStream.hasNext` occasionally blocks forever while sending response for a streaming RPC. I haven't found any reliable way to reproduce this issue, but following code and comment in `ClientCalls.java` caught my attention:
```java
try {
  // Will block here indefinitely waiting for content. RPC timeouts defend against permanent
  // hangs here as the call will become closed.
  last = waitForNext();
} catch (InterruptedException ie) {
  Thread.currentThread().interrupt();
  throw Status.CANCELLED.withCause(ie).asRuntimeException();
}

```
I am not vary familiar with GRPC codebase. Could someone tell me when is this call going to block and which thread usually unblocks it? What could cause the call being blocked forever?
It seems GRPC does not timeout by default. Should I specify RPC timeout (BTW is timeout the same thing as deadline)?

**Comment by carl-mastrangelo** [comment]
Yes, you should use a deadline if you want the call to eventually stop waiting for a response.  A special deadline thread will cancel the call, which will propagate to that waitForNext() as an exception (not thrown, though).  It will match the check directly below, and be rethrown there.

**Comment by biran0079** [comment]
Thanks for explaining, @carl-mastrangelo! 
I am still not sure why `BlockingResponseStream.hasNext` hangs. 
Should I assume any streaming RPC could indefinitely hang forever with no reason?

**Comment by carl-mastrangelo** [comment]
Yes, you must assume that.  hasNext because it is intended to be used as part of a for-loop (it's an Iterable).  Ideally this kind of discussion should be done on the mailing list over at https://groups.google.com/forum/#!forum/grpc-io .  

I am going to close this issue out.

**Comment by ejona86** [comment]
> Should I assume any streaming RPC could indefinitely hang forever with no reason?

We would expect it to hang if the server stopped sending, and resume if the server resumed.

Today, it could hang if something happened to the connection and isn't used by any other RPCs. This is mainly a problem today when the connection is idle for long periods of time (minutes). We are working on keep-alive support (which will be available for OkHttp in the next release), though, which triggers activity during idle to detect when the connection breaks and fail the RPC.

**Comment by biran0079** [comment]
Thanks for the response, @ejona86.
My use case is a little different I think. My server streams millions of messages in one RPC call, and client occasionally get stuck in the middle of streaming. Server code is very simple and it does call `responseObserver.onCompleted` when RPC finishes. No error is found in server log, and server is able to serve other requests after one client hangs. I use netty channel with ssl.
I moved the discussion into mailing list. Feel free to reply there.
https://groups.google.com/forum/#!topic/grpc-io/d_wCdHQJmd8
