### ISSUE TITLE
How to use load balancer in client side

### ISSUE THREAD

**Issue by AdoHe** [grpc/grpc-java#2074]
FYI. I am writing a client for a service, since this service has multiple instances, so I can get more than one addresses, and I just want to configure those addresses when I construct client. But after scan all the examples, I can't find such example. All examples use `ManagedChannelBuilder.forAddress()` like way to get a `ChannelBuilder`, I did notice that channel builder has a `loadBalancerFactory` method, but I am wondering how to implement a custom load balancer factory and where I can configure those addresses?

**Comment by carl-mastrangelo** [comment]
Hi,

You'll need to use ManagedChannelBuilder.forTarget and install a custom name resolver that can turn that name into addresses.  

These kinds of questions are better answered in our user forum here: https://groups.google.com/forum/#!forum/grpc-io
