### ISSUE TITLE
Update to protobuf-3.0.0

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2086]
Upgrading to Protobuf-3.0.0-beta-4 breaks Lite, since there are no pre-compiled binaries for Lite at that version. GA will have pre-compiled libraries.

**Comment by ankitdimania-eligible** [comment]
protobuf released https://github.com/google/protobuf/releases/tag/v3.0.0

**Comment by ejona86** [comment]
There aren't artifacts yet for Java. I assume those will become available today.

**Comment by ankitdimania-eligible** [comment]
Do you mean https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-java-3.0.0.zip

**Comment by ejona86** [comment]
@ankitdimania-eligible, no. I meant http://search.maven.org/#search%7Cga%7C1%7Cg%3Acom.google.protobuf (which are there now).
