### ISSUE TITLE
Error zero_copy_stream.h file not found during  ../gradlew java_pluginExecutable

### ISSUE THREAD

**Issue by killjason** [grpc/grpc-java#2091]
RUN ../gradlew java_pluginExecutable  got error:
###Error zero_copy_stream.h file not found###
I tried export CXXFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" , but did not work,
ENV as following:
OS: CentOS-7/Mac
protobuf: protoc-3.0.0-beta-4-linux-x86_64
grpc-java:grpc-java-0.15.0
jdk:1.8

**Comment by carl-mastrangelo** [comment]
Thats typically because you are using an older protobuf.  Are you sure you don't have a doppelganger on your LD_LIBRARY_PATH?  Possibly somewhere else on you system?

**Comment by ejona86** [comment]
Can you confirm `/usr/local/include/google/protobuf/io/zero_copy_stream.h` exists? I just did a new build of protobuf-3.0.0-beta4 and see that file and don't have problems during building grpc.

If you're building 0.15.0, is there a reason not to use our pre-built binary? http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22protoc-gen-grpc-java%22

**Comment by killjason** [comment]
@ejona86 
0. I am using the newest protobuf:protobuf-3.0.0-beta4:
![image](https://cloud.githubusercontent.com/assets/2777101/17148737/e1b25716-539a-11e6-89d9-4244eb5189e9.png)
1. the error occurs when i building grpc-java-0.15.0:
    $ cd $GRPC_JAVA_ROOT/compiler
    $ ../gradlew java_pluginExecutable
2. in the maven url you gave above, I downloaded the windows-x86_64.exe, then double click it to run in my windows 7,but it stuck there,the snapshot:
![image](https://cloud.githubusercontent.com/assets/2777101/17148630/85c721f2-539a-11e6-8e8a-901ee3c9cb9b.png)

**Comment by ejona86** [comment]
I thought you were using CentOS-7? Although all the files on Maven end in .exe, they are normal binaries for each platform. Maven Central requires a file extension, so we chose exe.

protoc-gen-grpc-java is a plugin for protoc (also available on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3Acom.google.protobuf%20a%3A%22protoc%22)). It is expecting input from protoc over stdin. Take a look at the [Readme](https://github.com/grpc/grpc-java/blob/master/compiler/README.md) for how to use it.

**Comment by killjason** [comment]
@ejona86 I did the following as the Readme,but still got error:
![image](https://cloud.githubusercontent.com/assets/2777101/17149607/991c07a0-539e-11e6-8411-f936e5a2e91f.png)

**Comment by killjason** [comment]
@ejona86  I got it,chmod the exe to be runnable,then it WORKED, thank you very much~

**Comment by ejona86** [comment]
Could you share `ls -l`? Maybe `chmod +x protoc-gen-grpc-java-0.15.0-linux-x86_64.exe`?

**Comment by ejona86** [comment]
@killjason, excellent. Glad it's working for you now.
