### ISSUE TITLE
Can we please call the thrift module & artifacts 'grift'

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#2099]
@chedeti
@ejona86 

Pretty please!

**Comment by chedeti** [comment]
Is 'grift' finalized ?

**Comment by ejona86** [comment]
The joke works pretty well. I think I'd just want the name to be used in all languages (not just Java).

**Comment by vjpai** [comment]
lgtm.

**Comment by vjpai** [comment]
Need an opinion from @zinuga

**Comment by zinuga** [comment]
I am fine calling it a different name for now to avoid any "mis-interpretations". @jayantkolhe, you ok?

**Comment by dapengzhang0** [comment]
LOL

**Comment by carl-mastrangelo** [comment]
Does someone want to take this?  @dapengzhang0 ?

**Comment by dapengzhang0** [comment]
Close the issue as grift is available at https://github.com/grpc-ecosystem/grift
