### ISSUE TITLE
Fix checkstyle warnings for examples

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#211]
Making example methods private would be easiest, but them being public seemed to be useful in http://www.useopen.net/blog/2015/rpc-performance.html .

getFeature() is also overloaded, and doesn't look like it should be, given that the two methods have different semantics.

**Comment by ejona86** [comment]
@nmittler, what do you think we should do about the getFeature() overloading?

**Comment by nmittler** [comment]
@ejona86 I think you provided the wrong link in the description :)

I think moving the method is sufficient ... I'll roll a PR.

**Comment by nmittler** [comment]
@ejona86 looks like you're already resolving this in #230.  I'm fine with the method re-name in that PR.

**Comment by ejona86** [comment]
@nmittler, sorry, I failed to link the PR in to this issue.

That was actually the link I meant. The benchmark itself isn't without its issues, it did use our client as-is because of the public methods.
