### ISSUE TITLE
build fails with exception v0.15.x :grpc-protobuf-lite:compileJava cannot find symbol

### ISSUE THREAD

**Issue by Jo3McCarthy** [grpc/grpc-java#2116]
Hi, All;

I am forced to work on a Mac OS system and I am simply trying to build the grpc-java examples.

I keep getting a build failure with exception.

Here is the relevant output:
```
:grpc-protobuf-lite:compileJava
/Users/jmc3000/gocode/src/github.com/grpc-java/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java:80: error: cannot find symbol
    final Parser<T> parser = (Parser<T>) defaultInstance.getParserForType();
                                                        ^
  symbol:   method getParserForType()
  location: variable defaultInstance of type T
  where T is a type-variable:
    T extends MessageLite declared in method <T>marshaller(T)
/Users/jmc3000/gocode/src/github.com/grpc-java/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java:129: error: cannot find symbol
          e.setUnfinishedMessage(message);
           ^
  symbol:   method setUnfinishedMessage(T)
  location: variable e of type InvalidProtocolBufferException
  where T is a type-variable:
    T extends MessageLite declared in method <T>marshaller(T)
/Users/jmc3000/gocode/src/github.com/grpc-java/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java:151: error: cannot find symbol
          return (T) instance.getParserForType().parseFrom(serialized, globalRegistry);
                             ^
  symbol:   method getParserForType()
  location: variable instance of type T
  where T is a type-variable:
    T extends MessageLite declared in method <T>metadataMarshaller(T)
3 errors
:grpc-protobuf-lite:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-protobuf-lite:compileJava'.
> Compilation failed; see the compiler error output for details.
```

Any advice would be welcome.

Thanks,

Jo3

**Comment by ejona86** [comment]
If you `git checkout v1.0.0-pre1` you shouldn't need to build grpc-java.

I can't figure out how you are getting those errors though. getParserForType _is_ in MessageLite... I'm stumped. Is there anything interesting about your environment?

**Comment by Jo3McCarthy** [comment]
Hi, Eric;

Thank you very much for the reply.  After I switch to that version, I get back to my other failure, the 100 errors starting with this one:

:compileJava
/Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/helloworld/HelloRequest.java:216: error: cannot find symbol
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                                          ^

Perhaps I need a version of the protobuf that matches the version 1.0.0-pre1 and/or the protoc 3.0.0-beta-3.

I will take it up again tomorrow.

Thanks,

Jo3

Jo3 McCarthy
Senior Java Developer
Lantern Credit, LLC

[cid:image001.png@01D1EC15.F6020190]

d 949-438-7860

Confidentiality Note: This e-mail is intended only for the person to whom it is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. Dissemination, distribution or copying of this e-mail or the information herein by anyone other than the intended recipient, or an employee or agent responsible for delivering the message to the intended recipient, is prohibited. If you have received this e-mail in error, please destroy the original message and all copies.

**Comment by Jo3McCarthy** [comment]
So, I can confirm the presence of the v1.0.0-pre1 protoc jars as well as the 3.0.0-beta-3 jars.  However, I still get the errors above.  For example:

08:44:14.108 [ERROR] [system.err] /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/helloworld/HelloRequest.java:216: error: cannot find symbol
08:44:14.108 [ERROR] [system.err]       com.google.protobuf.GeneratedMessage.BuilderParent parent) {
08:44:14.108 [ERROR] [system.err]                                           ^
08:44:14.109 [ERROR] [system.err]   symbol:   class BuilderParent
08:44:14.109 [ERROR] [system.err]   location: class GeneratedMessage

When I use the command: "jar -tf /Users/jmc3000/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.0.0-beta-3/ed8c2f9a63cfa770292f8173fd0172bdaa014fe3/protobuf-java-3.0.0-beta-3.jar" I can see a listing of all the classes including: com/google/protobuf/GeneratedMessage$BuilderParent.class

What am I doing wrong?

Thanks,

Jo3

**Comment by ejona86** [comment]
What command are you using to compile? Are you using gradlew?

**Comment by Jo3McCarthy** [comment]
From /Users/jmc3000/gocode/src/github.com/grpc-java/examples I am using: "../gradlew installDist -PskipCodegen=true"

My javac is: 1.8.0_92, OS is Darwin Kernel Version 15.5.0 and with full "--debug" on command line, the output of the failed command is this:

08:44:13.562 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -d /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/classes/main -g -sourcepath /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/tmp/compileJava/emptySourcePathRef -classpath /Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-netty/1.0.0-pre1/53094773926bf863daa8faa3ff1175f3f6909ca8/grpc-netty-1.0.0-pre1.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-protobuf/1.0.0-pre1/9e5235fbae40a22fe97a4cd55333b18969ef76cb/grpc-protobuf-1.0.0-pre1.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-stub/1.0.0-pre1/1fb325fdb52b0e5df3aea3a98b0f75119b2a3701/grpc-stub-1.0.0-pre1.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http2/4.1.3.Final/4e68c878d8ae6988eb3425d4fc2c8d3eea69ff39/netty-codec-http2-4.1.3.Final.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-core/1.0.0-pre1/6489670c182cb214cdcbbd7e6508b4f3ac831ce5/grpc-core-1.0.0-pre1.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.0.0-beta-3/ed8c2f9a63cfa770292f8173fd0172bdaa014fe3/protobuf-java-3.0.0-beta-3.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java-util/3.0.0-beta-3/5c39485775c197fc1938e594dc358bfec1c188a0/protobuf-java-util-3.0.0-beta-3.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-protobuf-lite/1.0.0-pre1/8ab07e256e0d9fb3650954f38bc09b5ea258b716/grpc-protobuf-lite-1.0.0-pre1.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http/4.1.3.Final/62fdf3c43f2674a61ad761b3d164b34dbe76e6cc/netty-codec-http-4.1.3.Final.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler/4.1.3.Final/fff45bdc544a4eeceb5b4c6e3e571627af9fdb6/netty-handler-4.1.3.Final.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.0/5871fb60dc68d67da54a663c3fd636a10a532948/jsr305-3.0.0.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.3/5fc52c41ef0239d1093a1eb7c3697036183677ce/gson-2.3.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec/4.1.3.Final/790174576b97ab75a4edafd320f9a964a5473cdb/netty-codec-4.1.3.Final.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.netty/netty-buffer/4.1.3.Final/e507ffb52a1d134679ed244ff819a99e96782dc4/netty-buffer-4.1.3.Final.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport/4.1.3.Final/2f17fe8c5c3b3f90908ed2d0649631a11beb3904/netty-transport-4.1.3.Final.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.1.3.Final/620faa6dd83a08eb607c9d5c077a9b4edde3056b/netty-common-4.1.3.Final.jar:/Users/jmc3000/.gradle/caches/modules-2/files-2.1/io.netty/netty-resolver/4.1.3.Final/fe4ba2ed19e4e8667068e917665f5725ee0290ea/netty-resolver-4.1.3.Final.jar /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/advanced/HelloJsonClient.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/advanced/HelloJsonServer.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/errorhandling/ErrorHandlingClient.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldClient.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/header/CustomHeaderServer.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/header/HeaderClientInterceptor.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/header/HeaderServerInterceptor.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/src/main/java/io/grpc/examples/routeguide/RouteGuideUtil.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/helloworld/HelloReply.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/helloworld/HelloReplyOrBuilder.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/helloworld/HelloRequest.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/helloworld/HelloRequestOrBuilder.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/helloworld/HelloWorldProto.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/Feature.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/FeatureDatabase.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/FeatureDatabaseOrBuilder.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/FeatureOrBuilder.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/Point.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/PointOrBuilder.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/Rectangle.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RectangleOrBuilder.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteGuideProto.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteNote.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteNoteOrBuilder.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteSummary.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteSummaryOrBuilder.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java /Users/jmc3000/gocode/src/github.com/grpc-java/examples/build/generated/source/proto/main/grpc/io/grpc/examples/routeguide/RouteGuideGrpc.java -XDuseUnsharedTable=true

Thanks,

Jo3

**Comment by Jo3McCarthy** [comment]
Slight departure.  Using the instructions in ./examples/README.md to build with maven.  It got to a build exception: java.lang.NoClassDefFoundError: io/grpc/BindableService 

I built from the exact same source tree using a Fedora Linux VM.  It builds and runs perfectly.  However, when I try to execute the same code on the MacOS host, it throws a JNI runtime exception: Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/BindableService

So, Linux compiler and runtime succeed, and Mac OS compiler and runtime each fail separately.

**Comment by ejona86** [comment]
What Javac are you using? It sounds like you consistently have problems loading libraries. You wouldn't happen to be using Java 5, would you?

**Comment by ejona86** [comment]
Closing due to lack of feedback.
