### ISSUE TITLE
How to implement  logging in ClientInterceptor？

### ISSUE THREAD

**Issue by HugeTimor** [grpc/grpc-java#2145]
I want to logging the content of request and response each call. As documentation saying :

> Interface for intercepting outgoing calls before they are dispatched by a Channel.Implementers use this mechanism to add cross-cutting behavior to Channel and stub implementations. 
 
This is my code to add metadata and logging each all :
```
 public static ManagedChannel getChannel() {

        ClientInterceptor attachHeadersInterceptor = MetadataUtils.newAttachHeadersInterceptor(getMetadata());

        ClientInterceptor attachLogInterceptor = new ClientInterceptor() {
            @Override
            public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(
                    MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {

                Log.i(TAG, "request Method: " + method.getFullMethodName() + "\n");
                Log.i(TAG, "request Content: ");
                return next.newCall(method, callOptions.withDeadlineAfter(10, TimeUnit.SECONDS));
            }
        };

        return ManagedChannelBuilder.forAddress(Config.HOST, Config.PORT)
                .intercept(attachHeadersInterceptor, attachLogInterceptor)
                .usePlaintext(true)
                .build();
    }
```

But I don`t know how to get the request and response content  from **method**  or some other object .  

Does anyone know the answer ,thanks !

**Comment by ejona86** [comment]
Wrap `ClientCall` (and the eventual `ClientCall.Listener`), and log when `sendMessage()` and `onMessage()` are called. You can use `ForwardingClientCall` to only implement the methods you care about.

**Comment by HugeTimor** [comment]
Thanks your answer @ejona86 。I implement as below shown。Is it the best practice for logging？

```
ClientInterceptor loggingInterceptor = new ClientInterceptor() {
            @Override
            public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(
                    final MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {

                return new ForwardingClientCall.SimpleForwardingClientCall<ReqT, RespT>(
                        next.newCall(method, callOptions.withDeadlineAfter(10, TimeUnit.SECONDS))) {

                    @Override
                    public void sendMessage(ReqT message) {
                        Log.i(TAG, method.getFullMethodName() + " --- request content: \n"
                                + message.toString());
                        super.sendMessage(message);
                    }

                    @Override
                    public void start(Listener<RespT> responseListener, Metadata headers) {

                        ClientCall.Listener<RespT> listener = new ClientCall.Listener<RespT>() {
                            @Override
                            public void onMessage(RespT message) {
                                Log.i(TAG, method.getFullMethodName() + " --- response content: \n"
                                        + message.toString());
                                super.onMessage(message);
                            }
                        };
                        super.start(listener, headers);
                    }
                };
            }
        };
```

And which is better  cache call in `Channel`  or `Transport` ？I know the `Transport` is use `OkHttp-based  `  in Android , is it cut off `Cache`? if not ,how should i open it ?

**Comment by ejona86** [comment]
> And which is better cache call in Channel or Transport ？I know the Transport is use OkHttp-based in Android , is it cut off Cache? if not ,how should i open it ?

Sorry, I don't follow. Are you asking where to do caching? Doing that in an interceptor would work well, and you wouldn't call `next` if the request was already cached.

**Comment by HugeTimor** [comment]
Sorry, I could not described it clearly. Yes , I want to ask where to do caching .

Our project is an Android app , and the  cache policy is caching first . The rule is return caching response first , at the same time the call will  forward . When the remote response is arrived , `onNext` will be called again . 

![](http://o7mannifh.bkt.clouddn.com/16-8-11/35325070.jpg)

If doing that in an interceptor , how could i write response ? And how to push remote response into cache ?
