### ISSUE TITLE
No NameResolverProviders found via ServiceLoader, including for DNS

### ISSUE THREAD

**Issue by emmenlau** [grpc/grpc-java#2149]
I'm trying to execute a grpc client from Mathworks Matlab. Matlab should be able to execute Java code mostly unmodified. The client works well from plain Java, but fails from Matlab with error:
```
java.lang.IllegalStateException: No NameResolverProviders found via ServiceLoader, including for DNS. This is probably due to a broken build. If using
ProGuard, check your configuration
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at io.grpc.NameResolverProvider$NameResolverFactory.checkForProviders(NameResolverProvider.java:200)
	at io.grpc.NameResolverProvider$NameResolverFactory.getDefaultScheme(NameResolverProvider.java:195)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:384)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:316)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:251)
```

I'm unable to find the error. My code fails here:
```
  String host = ...;
  int port = ...;
  ManagedChannel mChannel = OkHttpChannelBuilder.forAddress(host, port).usePlaintext(true).build();
```
I'm not using ProGuard. The same code used to work with grpc-java-0.14.0. This might be related to issue 1982 ?

**Comment by carl-mastrangelo** [comment]
You can force the name resolver when you build the channel.  In ManagedChannelBuilder, call nameResolver(DnsNameResolverProvider)

**Comment by emmenlau** [comment]
Sorry I fail to understand how this would be done. I'd rather not meddle with the grpc sources because I use the same Java client on several platforms and most of them work. Is there a method I can call to set the DnsNameResolverProvider? I'm currently using
```
ManagedChannel mChannel = OkHttpChannelBuilder.forAddress(host, port).usePlaintext(true).build();
```
how would I need to change that?

**Comment by carl-mastrangelo** [comment]
@emmenlau Like this:

```
ManagedChannel mChannel = OkHttpChannelBuilder.forAddress(host, port)
    .nameResolverFactory(new DnsNameResolverProvider())
    .usePlaintext(true)
    .build();
```

**Comment by emmenlau** [comment]
Works like a charm! Thanks a lot for the nice help, two thumbs up!

**Comment by ejona86** [comment]
Instead of just papering over the problem, we would like to get to the bottom of these sorts of problems. Specifying the name resolver explicitly is only a short-term solution, as it uses internal-only APIs that are free to break at any time.

It looks like [this is the same problem](http://stackoverflow.com/a/13990560/4690866) as encountered here. So it looks like a bug in Matlab; we use `getResource()` which is broken when using Matlab's dynamic path.

**Comment by emmenlau** [comment]
Is there something I can do to help? Should I contact Matlab support? Can you tell me explicitly what to ask from them?

**Comment by ejona86** [comment]
Given the discussion I found, it seems to be a known issue with Matlab. It would be nice if there was some semi-official bug/documentation that we could reference for others having the same issue.

It seems like there are [issues with the dynamic path](http://www.mathworks.com/help/matlab/matlab_external/bringing-java-classes-and-methods-into-matlab-workspace.html#f111131) in general:
> Also, classes on the dynamic path might not behave identical to classes on the static path. If your class does not behave as expected, use the static path.

That documentation sort of ends the discussion, I guess. "Use static path" is the official solution. I saw people mentioning `getResource()` being broken in 2009, so this isn't a new issue.

**Comment by gengjiawen** [comment]
I am using proguard, running into the same problem, what progurad rules should i add to fix the problem?

**Comment by ejona86** [comment]
@gengjiawen, your problem is different, because it is caused by Proguard. Take a look at [the android example](https://github.com/grpc/grpc-java/blob/v1.5.0/examples/android/helloworld/app/proguard-rules.pro). This is the important part:
```
-keep class io.grpc.internal.DnsNameResolverProvider
-keep class io.grpc.okhttp.OkHttpChannelProvider
```

This should no longer be necessary in the upcoming v1.6.0 release because it will include #3241.

**Comment by gengjiawen** [comment]
@ejona86 thanks ,very helper.
