### ISSUE TITLE
Null pointer exception while setting a deadline on a stub

### ISSUE THREAD

**Issue by shishir127** [grpc/grpc-java#2153]
I posted this on the [grpc mailing list](https://groups.google.com/d/msg/grpc-io/7glpkS4zHVc/TOuEJCguAQAJ) too, reposting here because I'm not sure what the right forum is.

I followed directions in this [issue](https://github.com/grpc/grpc-java/issues/1495) to add deadlines to a RPC. But I get a null pointer error.
`java.lang.NullPointerException
 at io.grpc.stub.AbstractStub.withDeadlineAfter(AbstractStub.java:117)`

My code is
`blockingStub.withDeadlineAfter(10, TimeUnit.DAYS).doSomething()`

Can the callOptions here be null by any chance?
```/**
   * Returns a new stub with a deadline that is after the given {@code duration} from now.
   *
   * @see CallOptions#withDeadlineAfter
   */
  public final S withDeadlineAfter(long duration, TimeUnit unit) {
    return build(channel, callOptions.withDeadlineAfter(duration, unit));
  }
```

I'm using the code generated by the protobuf java plugin and the constructor initializes callOptions to CallOptions.DEFAULT, so I'm not sure what's wrong here. Anyone else faced this issue? I'm using protobuf-gradle-plugin:0.7.6.

```/**
   * Constructor for use by subclasses, with the default {@code CallOptions}.
   *
   * @param channel the channel that this stub will use to do communications
   */
  protected AbstractStub(Channel channel) {
    this(channel, CallOptions.DEFAULT);
  }
```

**Comment by buchgr** [comment]
@shishir127 which version of gRPC are you using?

**Comment by shishir127** [comment]
@buchgr I'm using grpc version `0.13.1`

**Comment by buchgr** [comment]
@shishir127 I think to remember that there was some issue with NPE a few months back. Could you please try with 0.15 and reopen this issue if the problem is still there?

Thanks!

**Comment by shishir127** [comment]
@buchgr Still facing this issue with 0.15.

**Comment by buchgr** [comment]
@shishir127 hmm. could you post the exception message and stack trace you are getting now? also sharing a reproducer would be helpful.

**Comment by shishir127** [comment]
@buchgr So I dug a bit deeper and realized mocks were used somewhere during a test setup which was definitely the cause for the NPE 😞 😓  . Sorry for the trouble.

**Comment by buchgr** [comment]
@shishir127 no worries :-). Only thing, next time you report a bug,please include the gRPC version and extra points if you also include a reproducer!

Thanks
