### ISSUE TITLE
Clients should RST_STREAM(NO_ERROR) if not half-closed when receiving trailers

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2163]
This is the client-side version of #2162, to handle the case when intermediaries are in play. Note that the RST_STREAM can be elided if the server sent a RST_STREAM after the EOS=true. But the client can't assume the server will send such a RST_STREAM.

**Comment by ejona86** [comment]
@ericgribkoff, was this resolved?

**Comment by ericgribkoff** [comment]
Yes, OkHttp and Netty (after https://github.com/grpc/grpc-java/pull/4222) clients send a RST_STREAM in this scenario.
