### ISSUE TITLE
point to correct 1.0 proto reference in readme

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc-java#2164]
Our current maven and gradle techniques point to beta3. Change to 1.0?
artifact = "com.google.protobuf:protoc:3.0.0-beta-3"
<protocArtifact>com.google.protobuf:protoc:3.0.0-beta-3:exe:${os.detected.classifier}</protocArtifact>

**Comment by ejona86** [comment]
What are you referring to? Where are you looking? Our README?

**Comment by zinuga** [comment]
yes, readme. inside protobuf-maven-plugin and protobuf-gradle-plugin code snippets.

**Comment by ejona86** [comment]
That's expected. The README will only be updated after we do the release.
