### ISSUE TITLE
grift is experimental

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2170]
Tracking issue for tasks necessary before considering grift (thrift marshalling over grpc) API stable.
- [ ] hear about some usage, to make sure it is satisfactory to users familiar with thrift marshalling
- [ ] codegen'd method signatures should have multiple arguments instead of the single wrapping message (this is probably cross-language)

**Comment by vjpai** [comment]
We'll start a matching tracking issue for C++ after grpc/grpc#7594 is merged.

**Comment by vjpai** [comment]
Superseded by grpc-ecosystem/grift#6
