### ISSUE TITLE
metadata is lost when server sends StatusRuntimeException

### ISSUE THREAD

**Issue by skyao** [grpc/grpc-java#2189]
I would like to send a StatusRuntimeException to the client with some information saved in metadata. like this:

``` java
Metadata trailers = new Metadata();
 trailers.put(EXTENDED_STATUS_KEY, "10001");
StatusRuntimeException e = new StatusRuntimeException(Status.ABORTED, trailers);
 throw e;
```

But when I caught the exception in the client, I found that the metadata in the exception didn't contain this information. I checked the code and found that in class Server.JumpToApplicationThreadServerStreamListener:

``` java
    public void halfClosed() {
      callExecutor.execute(new ContextRunnable(context) {
        @Override
        public void runInContext() {
          try {
            getListener().halfClosed();
          } catch (RuntimeException e) {
            internalClose(Status.fromThrowable(e), new Metadata());
            throw e;
          } catch (Throwable t) {
            internalClose(Status.fromThrowable(t), new Metadata());
            throw new RuntimeException(t);
          }
        }
      });
    }
```

In this method, `Status.fromThrowable(e)` will convert this exception into Status instance, but it won't reuse the metadata saved in the exception. Instead, it create a new empty Metadata.

So in this way, all the data saved in the metadata of StatusRuntimeException is lost.

Yet in class Status I found there is a new method `Metadata trailersFromThrowable(Throwable t)` and it is used in class ServerCalls:

``` java
public void onError(Throwable t) {
      Metadata metadata = Status.trailersFromThrowable(t);
      if (metadata == null) {
        metadata = new Metadata();
      }
      call.close(Status.fromThrowable(t), metadata);
    }
```

I think this is the correct way to handle and pass metadata. 

Please help to confirm it. If so, I would like to pull a request to fix it. 

Thank you !

**Comment by skyao** [comment]
Hi, I pulled a request to fix this issue. 

The code change is very small and straight.

**Comment by ejona86** [comment]
Throwing an exception is an error and discouraged. The normal way to fail is to call `StreamObserver.onError()`. As you saw in `ServerCalls`, `onError()` behaves correctly.

I'm a bit concerned about `ServerInterceptor`s when there is thrown metadata, because interceptors generally won't realize they need to modify such metadata. And I don't really want to cause interceptors to need to modify thrown metadata. That seems likely to cause its own sort of breakage. :-/

I wonder if it would be better to stop checking for `Status*Exception` and instead use `Status.UNKNOWN` unconditionally. That would reduce the confusion.

**Comment by ejona86** [comment]
I talked this over with @zhangkun83 and @louiscryan, and we need to always use `Status.UNKNOWN` if an exception was thrown. This is necessary to make sure interceptors process the status/trailers and to prevent accidental data leakage. This is considered a bug and should be back-ported to v1.0.x.

There is a plan to have a interceptor that can be installed that would convert an exception into a clean status (with trailers), which would also make that status/trailers available to interceptors, but it would be opt-in and include some warnings. Most notably, if a server issues a call to another backend and that call fails (with a StatusRuntimeException), the error may contain information that should not be disclosed with the server's clients. There is not a need to backport the interceptor.

**Comment by skyao** [comment]
OK, I understand.

But sometimes, it is more comfortable for the developers to throw exception during business handling where they want to say "there is something wrong" to the client. 

In fact, I have add a ServerCall.Listener to do what you mean before:

1. catch exceptions 
2. convert it to a customized exception with extended status code and metadata
3. log the exception
4. send the status and metadata to client by method ServerCall.close()

```java
private static class ExceptionListener extends ServerCall.Listener {
    .....
    public void onHalfClose() {
            try {
                this.delegate.onHalfClose();
            } catch (Exception t) {
                ExtendedStatusRuntimeException exception = ExtendedStatusRuntimeException.fromThrowable(t);
                ......
                call.close(exception.getStatus(), exception.getTrailers());
            }
        }
}
```

for this case: "Most notably, if a server issues a call to another backend and that call fails (with a StatusRuntimeException), the error may contain information that should not be disclosed with the server's clients. ".

We will catch all the exceptions when we call a grpc server and map them to our actual business logic, we won't let the StatusRuntimeException go through our server and pass to our client. So in this case, we would like to use our listener or the one you planed.

Thank you so much for you help. In fact, I really don't know that we should use onError() to handle exception at first. This is an important design principle, but I don't get this information before, is there any documentation about it? Or we need to document it?

**Comment by daicoden** [comment]
> if a server issues a call to another backend and that call fails (with a StatusRuntimeException), the error may contain information that should not be disclosed with the server's clients

I'm trying to get error propagation across three services (a -> b -> c).  Clients talk to a.  The goal is if an error is thrown in C, you can see the stack trace in A.  Is there a way to do this currently without passing the responseObserver around?

> There is a plan to have a interceptor that can be installed that would convert an exception into a clean status (with trailers)

Sounds great, any movement on that?
