### ISSUE TITLE
TLS support for OkHttp when not running on Android

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#22]
OkHttp transport current accepts a SSLSocketFactory which when on Android is provided by the OS. For testing when not running on Android we don't have a way to do TLS/ALPN. We need one.

**Comment by ejona86** [comment]
Not required for 0.5.0, but would be nice.

**Comment by ejona86** [comment]
@madongfly, any updates on using TLS outside of Android with OkHttp?

**Comment by madongfly** [comment]
I think @zsurocking picked up my cl and worked on it when I was on vacation, rocking, could you comment on it?

**Comment by madongfly** [comment]
Reopen because after 11d0094e04ec884fb7e2a0670409aff5870b0a53 upgraded Netty to 4.1, the Http2 protocol became to "h2" while OkHttp 2.0 still using "h2-16"

**Comment by swankjesse** [comment]
Use OkHttp 2.3? It uses `h2`.

**Comment by madongfly** [comment]
@swankjesse  yeah, we will upgrade it to 2.3.
