### ISSUE TITLE
Add server-side example for compression

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2204]
We have a [client-side example](https://github.com/grpc/grpc-java/blob/v1.0.0/examples/src/main/java/io/grpc/examples/experimental/CompressingHelloWorldClient.java) but no server. That's probably the best form of documentation for users to figure out how to use it.

**Comment by vinodhabib** [comment]
@kannanjgithub I went through the details and can see the README file already in place as below.
https://github.com/grpc/grpc-java/blob/master/examples/README.md

Hope this is good for closure?
