### ISSUE TITLE
LoadBalancer should not fail wait-for-ready requests when there is an errror

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#2209]
Currently `LoadBalancer` would just call `TransportManager.InterimTransport.closeWithError()`, which fails all requests. We should instead add another method like `enterTransientFailure()`, which is reversible by `exitTrasientFailure()` and only kills current and further fail-fast requests.

`closeWithError()` shall be kept for shutdown, or be renamed to `closeWithShutdown()`.

**Comment by ejona86** [comment]
@zhangkun83, this looks like it was fixed with LBv2 API. Agreed?

**Comment by zhangkun83** [comment]
Yes, it was.
