### ISSUE TITLE
Update to netty 4.1.5.final

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#2224]
Long story short, there was a bug until 4.1.5.final that would cause issues when running inside Tomcat.

**Comment by carl-mastrangelo** [comment]
Tests fail due to duplicate certificates being returned by netty tcnative, I think.

**Comment by carl-mastrangelo** [comment]
@jhspaybar It looks like we are blocked on Netty releasing 4.1.6, which includes a fix to make Netty-tcnative work on windows.

**Comment by jhspaybar** [comment]
@carl-mastrangelo thanks for the update!
