### ISSUE TITLE
https://mvnrepository.com/artifact/io.grpc/grpc-all/1.0.0 dependencies issue

### ISSUE THREAD

**Issue by BelfodilAimene** [grpc/grpc-java#2229]
When i'm working with **grpc-1.0.0** i get the following error: 
`The type io.netty.handler.ssl.SslContextBuilder cannot be resolved. It is indirectly referenced from required .class files`

This problem did not occure when i used **grpc-0.15.0**

Any solutions ?

**Comment by carl-mastrangelo** [comment]
If you are using eclipse, (which seems like the source of the error message) the gradle integration is pretty bad.  You'll need to periodically refresh the Gradle project (or possibly do a clean import) to get it working.

If you aren't using eclipse, can you print the classpath you are using to start java?

**Comment by BelfodilAimene** [comment]
Yes, i'm using Eclipse (on Ubuntu)

**Comment by carl-mastrangelo** [comment]
The reason is because you have an old version of Netty on your classpath.  Eclipse is referencing the wrong jar.  You can fix it by Right clicking on the project and changing the "Build Path" to point to the latest version of Netty.

**Comment by BelfodilAimene** [comment]
Okay, i'll try it

**Comment by BelfodilAimene** [comment]
Small question: What's the last netty version (to use it with grpc 1.0.0). my Netty dependencies are 4.1.3.Final

**Comment by carl-mastrangelo** [comment]
You can look in the build.gradle file in the top most directory to find out.

**Comment by BelfodilAimene** [comment]
Even if i updated the build path. I have now another problem (in runtime now) which is : 

java.lang.ClassNotFoundException: org.apache.tomcat.jni.CertificateRequestedCallback
