### ISSUE TITLE
Jetty ALPN/NPN has not been properly configured with grpc-1.0.0 on windows only

### ISSUE THREAD

**Issue by leslie-leder** [grpc/grpc-java#2230]
I've upgraded grpc java from version 0.15.0 to 1.0.0. now my integration tests - connect real client and server - on windows complain with 

    Jetty ALPN/NPN has not been properly configured 
   
It works properly on Linux (fedora) but not on Windows. 

With version 0.15.0 I was able to run client and server on Windows as well as on Linux and cross connect between Linux and Windows and vice versa.

My Gradle dependencies are: 

  'io.grpc:grpc-all:1.0.0'
  'io.netty:netty-tcnative-boringssl-static:1.1.33.Fork19'

I start the server like so: 

    val scb = SslContextBuilder.forServer(keyCertChainInputStream, keyInputStream)
    GrpcSslContexts.configure(scb)
      .build()
 
Is there something else I need to consider for this migration?

**Comment by leslie-leder** [comment]
I found the problem. With a simultaneous rxnetty upgrade a newer netty version (4.1.5.Final) slipped into the classpath. This provokes a the grpc connection issue on Windows.

**Comment by xamde** [comment]
Which netty version worked for you?
