### ISSUE TITLE
OOM after a bunch of "thread-local buffers freed"

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#2232]
I occasionally observe Java runs out of heap space after a sequence of log lines looks like
```
...
DEBUG [2016-08-30 20:20:19,188] io.netty.buffer.PoolThreadCache: Freed 1 thread-local buffer(s) from thread: grpc-default-executor-3519 [req=null firm=null cred=null ip=null]
DEBUG [2016-08-30 20:20:19,188] io.netty.buffer.PoolThreadCache: Freed 1 thread-local buffer(s) from thread: grpc-default-executor-3534 [req=null firm=null cred=null ip=null]
DEBUG [2016-08-30 20:20:19,189] io.netty.buffer.PoolThreadCache: Freed 1 thread-local buffer(s) from thread: grpc-default-executor-3518 [req=null firm=null cred=null ip=null]
DEBUG [2016-08-30 20:21:13,472] io.netty.buffer.PoolThreadCache: Freed 1 thread-local buffer(s) from thread: grpc-default-executor-3516 [req=null firm=null cred=null ip=null]
DEBUG [2016-08-30 20:21:13,474] io.netty.buffer.PoolThreadCache: Freed 1 thread-local buffer(s) from thread: grpc-default-executor-3526 [req=null firm=null cred=null ip=null]
WARN  [2016-08-30 22:25:26,932] io.grpc.netty.NettyServerHandler: Exception in onHeadersRead() [req=null firm=null cred=null ip=null]
! java.lang.OutOfMemoryError: Java heap space
```
I think the server is under heavy load when this happens.
It seems like the grpc-default-executor created thousands of threads. Is it normal?
Does anyone know what is going on?

**Comment by carl-mastrangelo** [comment]
Yes it is normal, so you need to provide your own exectuor.  The default one is just to get you started.  Provide a ThreadPoolExecutor with a fixed number of threads/

**Comment by biran0079** [comment]
Thanks for the quick reply!
I am still a bit confused why the default cached thread pool executor didn't work well though.

**Comment by carl-mastrangelo** [comment]
The default will create a new thread if all of them are busy.

**Comment by nickdul** [comment]
>so you need to provide your own exectuor. 

how it can be configured in `gRPC 1.6.1`?
looking into `NettyServerBuilder` but cannot find appropriate property...

**Comment by zpencer** [comment]
It is implemented in one of its superclasses as `public final T executor(@Nullable Executor executor)`
