### ISSUE TITLE
sequential reading is guarantee？ when is using client stream service. 

### ISSUE THREAD

**Issue by wu-sheng** [grpc/grpc-java#2241]
```grpc
service ProfileData {
    rpc store (ProfileDataRequest) returns (ServiceResponse) {}
}
```

Server reads list of ProfileDataRequest, it's the same sequence of server and client? When client use only one thread to send ProfileDataRequest.

**Comment by buchgr** [comment]
Hello @wu-sheng ! The `ProfileDataRequest` message is received by the server exactly the same as it was sent by the client. Hope that helps.

**Comment by ejona86** [comment]
I assume there is a missing `stream` keyword before the request type:
```
rpc store (stream ProfileDataRequest) returns (ServiceResponse) {}
```

And yes, order is preserved for streams.

**Comment by wu-sheng** [comment]
@ejona86 , yes,  I miss it.
And thank both og you.
