### ISSUE TITLE
Ping implementation in Netty doesn't handle all error cases.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#2254]
The field [`NettyClientHandler.ping`](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L112) is used to determine whether a `PING` acknowledgement is [outstanding](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L449), as we only allow one PING at a time.

The logic to reset `NettyClientHandler.ping` handles the case where the write of the frame [fails](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L477), we receive a PING [ack](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L632) or the channel gets [closed](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L539).

We need to additionally handle the case in which the write of the PING frame succeeds, the channel remains active and we don't get any valid PING acknowledgement back. This error case may happen for example due to a buggy implementation of the remote endpoint or even packet corruption.  I think we should ensure users that the `PingCallback` is called eventually.

A possible solution may be an automatic re-send of PINGs that don't receive a matching PING ack within some timeout period.

**Comment by ejona86** [comment]
So this is assuming a non-conformant remote endpoint? I definitely don't think we should retry.

With keepalive, we'll eventually kill connections that don't respond to PINGs.

**Comment by buchgr** [comment]
Hmm ok. Keepalive sounds fair. I ll close this then :).
