### ISSUE TITLE
When I use grpc 1.0.0, why javax/annotation package is in my jar?

### ISSUE THREAD

**Issue by wu-sheng** [grpc/grpc-java#2268]
My dependencies like this:

``` xml
    <dependencies>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

And I use **maven-shade-plugin** to package my project, like this

``` xml
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <shade.com.google.source>com.google</shade.com.google.source>
        <shade.com.google.target>com.a.eye.skywalking.protocol.dependencies.com.google</shade.com.google.target>
        <shade.io.netty.source>io.netty</shade.io.netty.source>
        <shade.io.netty.target>com.a.eye.skywalking.protocol.dependencies.io.netty</shade.io.netty.target>
        <shade.io.grpc.source>io.grpc</shade.io.grpc.source>
        <shade.io.grpc.target>com.a.eye.skywalking.protocol.dependencies.io.grpc</shade.io.grpc.target>
    </properties>

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>false</shadedArtifactAttached>
                            <createDependencyReducedPom>true</createDependencyReducedPom>
                            <createSourcesJar>true</createSourcesJar>
                            <shadeSourcesContent>true</shadeSourcesContent>
                            <relocations>
                                <relocation>
                                    <pattern>${shade.com.google.source}</pattern>
                                    <shadedPattern>${shade.com.google.target}</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>${shade.io.netty.source}</pattern>
                                    <shadedPattern>${shade.io.netty.target}</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>${shade.io.grpc.source}</pattern>
                                    <shadedPattern>${shade.io.grpc.target}</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

And my jar in target directory has package **javax/annotation**? Why is this happending?

I provides my pom.xml and jar as attach files for you.
And as my pom define, I relocation io.netty, io.goole, io.grpc. Is this OK? Will Grpc works?

Attach files:
[skywalking-network-2.0-2016.jar.zip](https://github.com/grpc/grpc-java/files/471214/skywalking-network-2.0-2016.jar.zip)
[pom.xml.zip](https://github.com/grpc/grpc-java/files/471215/pom.xml.zip)

**Comment by wu-sheng** [comment]
Further more, I run **mvn dependency:tree**
dependency tree as following:
```
[INFO] com.a.eye:skywalking-network:jar:2.0-2016
[INFO] +- io.grpc:grpc-netty:jar:1.0.0:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.3.Final:compile (version selected from constraint [4.1.3.Final,4.1.3.Final])
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.3.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.3.Final:compile
[INFO] |  |  \- io.netty:netty-handler:jar:4.1.3.Final:compile
[INFO] |  |     +- io.netty:netty-buffer:jar:4.1.3.Final:compile
[INFO] |  |     |  \- io.netty:netty-common:jar:4.1.3.Final:compile
[INFO] |  |     \- io.netty:netty-transport:jar:4.1.3.Final:compile
[INFO] |  |        \- io.netty:netty-resolver:jar:4.1.3.Final:compile
[INFO] |  \- io.grpc:grpc-core:jar:1.0.0:compile (version selected from constraint [1.0.0,1.0.0])
[INFO] |     \- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] +- io.grpc:grpc-protobuf:jar:1.0.0:compile
[INFO] |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  +- io.grpc:grpc-protobuf-lite:jar:1.0.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.0.0:compile
[INFO] |  \- com.google.protobuf:protobuf-java-util:jar:3.0.0:compile
[INFO] |     \- com.google.code.gson:gson:jar:2.3:compile
[INFO] +- io.grpc:grpc-stub:jar:1.0.0:compile
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------------
```

**Comment by ejona86** [comment]
Shading should mostly work. You will need to use ServicesResourceTransformer, but I know there is [a bug](https://issues.apache.org/jira/browse/MSHADE-182) in maven-shade-plugin doesn't relocate service resources correctly. That is fixed, but not yet released. With that bug, `ManagedChannel.forTarget`, `ManagedChannel.forAddress`, and `Server.forPort` won't be able to find a transport. You would have to use `NettyChannelBuilder`, `NettyServerBuilder`, or `OkHttpChannelBuilder` directly. There is also a failure to find DnsNameResolver, which requires manually providing the name resolver to the channel builder.

javax.annotation is being provided by com.google.code.findbugs:jsr305, which you can see in the dependency tree.

**Comment by wu-sheng** [comment]
I have known this bug and looking forward the release to fix this bug.
In my other project , I have to use shell to resolve this problem. Considering your advise, I will use NettyChannelBuilder and NettyServerBuilder directly. 
Thank you for you explaintion.

Further, I have two more questions for you.
Fisrt:
Is `com.google.code.findbugs:jsr305`  necessary in grpc runtime?  Last night, I use `maven-shade-plugin` `include` segment to exclude it. as following config:
```xml
                    <configuration>
                            <artifactSet>
                                <includes>
                                    <include>io.grpc:grpc-*:jar:*</include>
                                    <inclued>io.netty:netty-*:jar:*</inclued>
                                    <inclued>com.google.protobuf:*:jar:*</inclued>
                                    <inclued>com.google.code.gson:gson:jar:*</inclued>
                                    <include>com.google.guava:guava:jar:*</include>
                                </includes>
                            </artifactSet>
```
Does it work for grpc 1.0.0? I do it once in 0.14.0, it seems to work? Can you confirm for me? Why does `com.google.code.findbugs` need in runtime?

Second:
In `ManagedChannelBuilder`,  it get provider by this `ManagedChannelProvider provider = load(getCorrectClassLoader())`. And it will compare `ManagedChannelProvider`s priority. 
OkHttpChannelProvider 
```java
public int priority() {
        return isAndroid()?8:3;
    }
```

NettyChannelProvider
```java
public int priority() {
        return 5;
    }
```

Is this meaning that NettyChannelProvider is recommand in java server j2ee or j2se  enviroment, and OkHttpChannelProvider should use in android? Do these two providers have differences in performance? Why?

**Comment by ascrutae** [comment]
@ejona86 I have same question about com.google.code.findbugs:jsr305 is necessary in grpc runtime. Could you give me an response?

**Comment by ejona86** [comment]
findbugs has annotations. It'd be very easy to accidentally break anything that looks at annotations if you don't include it. But generally it isn't likely used at runtime (and depending on the retention policy of the annotations, it may be safe to remove; but that varies over time).

Yes, Netty is preferred on server and OkHttp on Android. They are optimized differently. For example, NIO isn't very fast on Android and Android doesn't need to be optimized for thousands of RPCs a second (instead preferring lower memory overhead/code).
