### ISSUE TITLE
Investigate if Netty can be used as a server on Android 

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2273]
**Warning: Running a server on android is not officially supported on Android by the gRPC Java team!**  

It may be possible to run a gRPC Java server on android in a limited sense, but we don't do anything to restrict the possibility.  There appears to be a small number of users who do want to run a server for reasons that may be valid.  This issue is to track both interest from the community, as well as possibly being a list of known issues.  

Netty has not been optimized for Android.  gRPC has not been optimized _to be a server_ on android.

**Comment by ejona86** [comment]
I toyed with this in 5d193ad306. TLS won't work, at least on older Android versions, because of a missing interface.

**Comment by buchgr** [comment]
Netty doesn't officially support Android. The Netty team doesn't test their releases on Android. It may work now, but any future release may break Android.

**Comment by buchgr** [comment]
AFAIK Netty doesn't officially support Android. To the best of my knowledge, the Netty team doesn't test their releases on Android? I think some users are running it on Android though.

cc: @normanmaurer

**Comment by carl-mastrangelo** [comment]
One of the major things that would not work out of the box is memory pooling.  The reason for recent commit 48b6c190722a9ba1fea0b1c18f7df8ebbd8ee5a2 is due to Android devices having memory budgets of around 48 MB.  Pooled Byte buffers, which allocate in 16MB chunks for Heap byte bufs won't work well on android.  

Another major issue is what happens when the device goes to sleep?  Does the socket the server is listening on get closed?  We have seen extremely strange behavior that varies between device makers (like shutting down IPv4 sockets, but not IPv6) that would be difficult to make work reliably.

**Comment by lifeng1992** [comment]
I use gomobile to write app, but go-sqlite3 not work well. If grpc can be used as a server on Android, i can call a java function from golang.

**Comment by staypufd** [comment]
@cc buchgr Netty 4.1 now supports Android so grpc may work now. 

http://netty.io/wiki/new-and-noteworthy-in-4.1.html#wiki-h3-3

**Comment by harisvsulaiman** [comment]
@carl-mastrangelo #2227 will grpc work now on android ?

**Comment by jameyhicks** [comment]
We're using GRPC on Android to automate some tests. Works on older Android, but fails to reuse ports in Android 8.

Doing some investigation with ServerSocket, it appears that you have to `setReuseAddress(true)` before binding the socket. I guess I will dig into netty now.

**Comment by jameyhicks** [comment]
On Google Pixel 2, port 50051 seems to be in use by another process, so I switched our grpc server to a different port.

**Comment by AbhishekPantUK** [comment]
I am able to run server in android on port 50051, now how can I run the client from my host machine ? what host address I should provide for Android device, host pc and android device is in different networks and device is connected to host pc via USB. Thanks!

**Comment by jameyhicks** [comment]
Use adb port forwarding and connect to local host and same port on your
host.

On some Android versions I found there was already a GRPC server on port
50051 so I used a different port.

Jamey

**Comment by AbhishekPantUK** [comment]
Thanks Jamey.
It works now.

Abhishek

**Comment by ViswaJag** [comment]
Hi [AbhishekPantUK]/jamey , I was looking for some sample code for gRPC java server on android OS so would point to me if there is any example application available

**Comment by sanjaypujare** [comment]
@ViswaJag you may want to take a look at [`OkHttpTransportTest.newServer`](https://github.com/grpc/grpc-java/blob/master/okhttp/src/test/java/io/grpc/okhttp/OkHttpTransportTest.java#L59)

**Comment by ejona86** [comment]
I would not suggest coping `OkHttpTransportTest.newServer`; it does things you generally shouldn't and some things you can't. Just use `OkHttpServerBuilder`.

Since #9177, there's not been a need to run the Netty server on Android.
