### ISSUE TITLE
QPS client using much more memory than server.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#2278]
I did some benchmarking using the `qps_client` and `qps_server`. Zero bytes payload. I enabled `verbose:gc`. 

When running with 8 channels and 250 concurrent RPCs. On the client, after a young GC our live heap is ~290MiB. The GC logs have a very low volatility +/- 1MiB.

Doubling the concurrent streams to 500, on the client, the live heap more than doubles to 560MiB.
On the server it increases to ~140MiB. Doubling the concurrent streams to 1000, on the client, the live heap again doubles to ~1.1GB and on the server it increases to ~170MB.

I then thought it might be due to the client having to keep stream state  around much longer (until the server responds) and so I enabled streaming rpcs (with 8 channels, 1000 concurrent). Live heap on the client stays the same, on the server it drops to ~30MiB. The used heap on the client is about 2.3GiB before the GC, and 1.1GiB after. The used heap on the server is about 1.3GB before the GC and 30MiB after. So it seems like we keep an additional GiB of data around on the client (or 130KiB per stream).

That data seems to be allocated at the beginning. The first 3 GCs and the last GC on the client

```
(before GC -> after GC)
1GB -> 800.67MB
1.78GB -> 1.08GB
2.08GB -> 1.09GB
...
2.4GB -> 1.09GB
```

The first 3 GCs and the last GC on the server

```
(before GC -> after GC)
1.31GB -> 14.95MB
1.32GB -> 13.53MB
1.31GB -> 12.25MB
...
1.35GB -> 31.30MB
```

The increased memory usage on the client is not due to histograms, cause I commented out the line recording latencies.

I wonder why that is? Is it possibly a small memory leak per RPC? Is that specific to the QPS client or gRPC? Any ideas?

**Comment by buchgr** [comment]
Oh damn. It's actually due to the histograms. We allocate a histogram per RPC. So the scaling makes sense. According to the HdrHistogram docs, it allocates all its memory at the beginning, so the increased initial memory usage makes sense too.

Turns out histogram objects are quite large. I ll change the code to use one histogram per channel.

When I remove the histograms completely, client and server memory usage are about the same.

**Comment by ejona86** [comment]
Seems this was fixed. Closing.
