### ISSUE TITLE
Add injection points to generated code

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#2281]
Protobuf has a concept of injection points that make it possible to extend generated classes with additional methods, implements interfaces, and others.  This has been useful for example to generate setters which take an Optional Java 8 in addition to the standard methods generated when a user uses google.protobuf.StringValue or Int64Value.

A similar feature would be very useful in the generated gRPC code to allow for extension to add interaction models for clients and servers which are not appropriate in core.  For example, I would like to generate RxJava interfaces for client and server, and I'd like them to live in the same area as the other clients.

An example of the type of line in protoc generated files now that allows for this is 
```
 //@@protoc_insertion_point(builder_scope:com.google.protobuf.Int64Value)
```

It would be helpful if there was a class scope insertion point for adding additional client and server interactions models.

**Comment by louiscryan** [comment]
You might not actually need codegen to bind to RxJava. A utility function which consumes the generated MethodDescriptor objects available in the current stubs should allow you to achieve the same effect with strong typing. E.g

Hypothetically

Publisher<ResponseMessage> pub = GrpcRxUtil.createPublisher(MethodDescriptor.SOME_CALL);

Its worthwhile noting here that in GRPC each call is like a bonded-pair of publishers with a shared lifecycle. This is a little different to Rx which Publishers are decoupled message producers. I haven't looked in a while to see if they have formalized a way of representing this relationship between the publisher pairs.

**Comment by jhspaybar** [comment]
Yes, upon further review, this is a better approach for the gRPC code since I don't need the methods on the containing class like I do with the messages themselves.

**Comment by ejona86** [comment]
@jhspaybar, I'll note that those static method descriptors are experimental, and I know we need to change them to methods that do lazy-loading at some point to avoid the static initialization cost (which hurts primarily on Android).
