### ISSUE TITLE
client  set   RoundRobinLoadBalancer fail

### ISSUE THREAD

**Issue by yeyincai** [grpc/grpc-java#2282]
code

that  client is 

```
    managedChannel = NettyChannelBuilder
                .forTarget("server://127.0.0.1:9999,127.0.0.1:8888")
                .nameResolverFactory(new ServerNameResolverProvider())
                .loadBalancerFactory(RoundRobinLoadBalancerFactory.getInstance())
                .usePlaintext(true).build();
```

that  RoundRobinLoadBalancerFactory is fail .

debug   the  code  ,discover  class TransportSet method obtainActiveTransport have a problem

```
final ClientTransport obtainActiveTransport() {
    ClientTransport savedTransport = activeTransport;
    if (savedTransport != null) {
      return savedTransport;
    }
    synchronized (lock) {
      // Check again, since it could have changed before acquiring the lock
      if (activeTransport == null) {
        if (shutdown) {
          return SHUTDOWN_TRANSPORT;
        }
        // Transition to CONNECTING
        DelayedClientTransport delayedTransport = new DelayedClientTransport(appExecutor);
        transports.add(delayedTransport);
        delayedTransport.start(new BaseTransportListener(delayedTransport));
        activeTransport = delayedTransport;
        startNewTransport(delayedTransport);
      }
      return activeTransport;
    }
}
```

the savedTransport  frist is null ,  the second time  is not null ,no execute  find  activeTransport.

**Comment by zhangkun83** [comment]
Since you have stepped into TransportSet, it seems you have got the address resolved.
What error did you get?

**Comment by yeyincai** [comment]
@zhangkun83  yes,find the reason,resolved after   update    onUpdate (List<? extends List<ResolvedServerInfo>> servers),  this servers   size=1,so roundRobinLoadBalancer fail  ,the servers  is goup  SocketAddress

**Comment by ejona86** [comment]
@zhangkun83, what would we like to do with this issue? It's a bit unclear what's wrong to me.

**Comment by zhangkun83** [comment]
Since this issue is over a year old, and the load-balancing code path has changed substantially since then, I don't think we will try to debug that old code. @yeyincai have you tried with the latest gRPC version?
