### ISSUE TITLE
Figure out what names we want for Client Foos vs Server Foos

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#23]
We have Call on both Client and Server. When adding the server, we chose ServerCall as the name of the server-side Call, and discussed renaming the client-side to ClientCall. ClientInterceptor was named based on this idea. However, the rename hasn't happened yet and now some have suggested having the Client names simply lack "Client" (so it would remain "Call"). It seems it has simply been too long since the original discussion for us to remember what was decided.

We need to decide to either prefix Client with Client and Server with Server or only prefix Server with Server. After the decision, whatever needs fixing needs to be fixed.

Note that in the transport we must have ClientStream prefixed with Client, since Stream is a shared interface between Client and Server.

**Comment by nmittler** [comment]
@ejona86 should we just close this? If we want to pick this discussion back up we could do it in another issue.  WDYT?

**Comment by ejona86** [comment]
No, we still need it. We aren't consistent at the moment.
