### ISSUE TITLE
Guarantees around using responseObserver in multiple threads

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#2313]
I was writing a service which takes a stream of Events, and returns a stream of Acks.  In doing so, the Acks can trigger from multiple threads after I've done work and published them to downstream systems.  After sending a bit of load I would get errors that sendHeaders had already been called, and I realized that ServerCalls here https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/ServerCalls.java#L284 is performing a check to see if headers are sent that is not thread safe.

I wanted to get a bit more insight into the expectations for a service which is sending back responses on multiple threads.  Should I just do 
```
synchronized(responseObserver) {
  responseObserver.onNext(ack);
}
```
or should there be more synchronization in the ServerCalls code?  I suspect this was a deliberate choice not to support multi-threaded usage since cancelled *is* volatile while sentHeaders isn't.

Thanks!

**Comment by ejona86** [comment]
Per `ServerCall` and `ClientCall`'s docs:
> Implementations are not required to be thread-safe.

And `StreamObserver` (where thread-compatible means effectively "not thread safe"):
> Implementations are expected to be <a href="http://www.ibm.com/developerworks/library/j-jtp09263/">thread-compatible</a>.

Synchronizing on `responseObserver` is an easy approach. You just have to coordinate with your own code so there's plenty of options.

The reason for non-thread-safe is three fold:
 1. Thread-unsafe is faster to run and easier to implement. If you don't need the thread-safety (common case), why pay the cost?
 2. Making something like `ClientCall`/`ServerCall` thread-safe would be a more complex API and not be able to catch common bugs. For instance, the current API throws if you send a message after calling `halfClose()` (which certainly seems like a bug in the app's code)
 3. Applications sending from multiple threads typically need their own synchronization anyway

**Comment by jhspaybar** [comment]
Awesome answer, and I appreciate you taking the time to explain it. I assumed much of what you said, and your explicitness as to the reasoning is very helpful.

**Comment by ejona86** [comment]
@jhspaybar, oh! I forgot about one: thread-safe would mean all interceptor wrapping would have to be thread-safe. You easily devolve into having many layers each having to do their own synchronization.
