### ISSUE TITLE
SO_BACKLOG 128 enough?

### ISSUE THREAD

**Issue by x1957** [grpc/grpc-java#2321]
In NettyServer there is a hardcode 
```
if (NioServerSocketChannel.class.isAssignableFrom(channelType)) {
      b.option(SO_BACKLOG, 128);
      b.childOption(SO_KEEPALIVE, true);
    }
```
SO_BACKLOG = 128 is enough for every situation?

**Comment by carl-mastrangelo** [comment]
I don't this there is a specific reason.  Were you seeing issues related to it?

**Comment by ejona86** [comment]
In general, we want SO_BACKLOG to be a low as possible while still being large enough to handle bursts and GC pauses. If the server is overloaded and unable to accept new connections, then we _want_ to fail new client connections.

I'd also be interested if you saw any issues.

**Comment by x1957** [comment]
@ejona86 Thanks
