### ISSUE TITLE
ErrorProne compile failure on v1.0.1

### ISSUE THREAD

**Issue by pmbethe09** [grpc/grpc-java#2323]
core/src/main/java/io/grpc/internal/ManagedChannelImpl.java:266: error: [GuardedByChecker] This access should be guarded by 'ManagedChannelImpl.this.lock'; instead found: 'this.lock'
      idleModeTimer.cancelled = true;
                   ^
    (see http://errorprone.info/bugpattern/GuardedByChecker)
1 error

This is for tag v1.0.1 -- it may or may not be fixed @HEAD

**Comment by dapengzhang0** [comment]
@pmbethe09 I confirm this for tag v1.0.1. But did not find this issue at master HEAD

**Comment by pmbethe09** [comment]
sgtm

**Comment by ejona86** [comment]
This was "fixed" on HEAD in d2cc5763, wherein we just tell ErrorProne to ignore it.
