### ISSUE TITLE
Error on run example step "./gradlew installDist"

### ISSUE THREAD

**Issue by mnogono** [grpc/grpc-java#2327]
Due to documentation  [http://www.grpc.io/docs/quickstart/java.html](url)
1. clone git repo
2. run command line `./gradlew installDist`

step number 2 does not work for me, get a compile errors about illegal characters... like `RouteGuideServer.java line 299` this line has greece characters.

to resolve this issue I had to add `set DEFAULT_JVM_OPTS="-Dfile.encoding=utf-8"`
into `gradlew.bat` file and execute command `./gradlew installDist` againe. Can it be resolve in git?

**Comment by yyannekk** [comment]
I faced the same issue on `gradlew build`. Using greece characters seems also quite unusual to me, though it looks nice when doing math stuff.

I was able to compile with modifying /examples/build.gradle by setting `compileJava.options.encoding = 'UTF-8'` ([ref](http://mrhaki.blogspot.de/2012/06/gradle-goodness-set-java-compiler.html)).
Not sure if thats the recommended way.

**Comment by ejona86** [comment]
Yes, setting the encoding to UTF-8 is the proper way. We have that set for our main build, but missed it in the examples build. We'll also need to fix the `pom.xml` so that Maven doesn't break either.
