### ISSUE TITLE
io.grpc.okhttp.OkHttpTransportTest > newStream_duringShutdown is flaky

### ISSUE THREAD

**Issue by Nayana-ibm** [grpc/grpc-java#2328]
We are working on  s390x platform and facing below test failure while building gRPC-java master.
We are using protoc v3.0.2 and v3.0.0-javalite.

```
:grpc-okhttp:checkstyleTest UP-TO-DATE
:grpc-okhttp:test

io.grpc.okhttp.OkHttpTransportTest > newStream_duringShutdown FAILED
    java.lang.AssertionError: Timed out waiting for server stream

129 tests completed, 1 failed, 1 skipped
:grpc-okhttp:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-okhttp:test'.

BUILD FAILED
```

**Comment by ejona86** [comment]
I'm assuming this was a flake.

**Comment by ejona86** [comment]
As seen at https://travis-ci.org/grpc/grpc-java/jobs/197885380 (since rebuilt):
```
io.grpc.okhttp.OkHttpTransportTest > newStream_duringShutdown FAILED
    java.lang.AssertionError: Timed out waiting for server stream
```

**Comment by ejona86** [comment]
As seen at https://travis-ci.org/grpc/grpc-java/jobs/199373949 (since rebuilt):
```
io.grpc.okhttp.OkHttpTransportTest > newStream_duringShutdown FAILED
    java.lang.AssertionError: Timed out waiting for server stream
```

**Comment by ejona86** [comment]
As seen at https://travis-ci.org/grpc/grpc-java/jobs/199019247 (since rebuilt):
```
io.grpc.okhttp.OkHttpTransportTest > newStream_duringShutdown FAILED
    java.lang.AssertionError: Timed out waiting for server stream
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/198158689 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/197355640 (since rebuilt)

**Comment by ericgribkoff** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/204651127

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/205610717 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/205060280 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/207263898 (since rebuilt)

**Comment by dapengzhang0** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/207551609

**Comment by dapengzhang0** [comment]
seen at https://travis-ci.org/grpc/grpc-java/jobs/209920030

**Comment by dapengzhang0** [comment]
Not happening any more for quite a while
