### ISSUE TITLE
ManagedChannelBuilder and URI path routing

### ISSUE THREAD

**Issue by kuroneko25** [grpc/grpc-java#2345]
This may be a silly question but I'm having a hard time figuring out what's going on. I have a couple of gRPC servers sitting behind a load balancer and I have rules set up to route requests based on the path. i.e. myloadbalancerIPaddress:8000/service/serviceA would route to a particular backend server. And on the client side this is what I'm doing:
```
ManagedChannel channel = ManagedChannelBuilder
    .forTarget("ipaddress:8000/service/test-service").usePlaintext(true).build()
```
It seems like the request is always made against ipaddress:8000 without the specified path. Am I doing something wrong here?

**Comment by ejona86** [comment]
All requests go to a fixed path: /serviceName/methodName. In some languages, it may be technically possible to add to the path, it isn't necessarily possible in all languages and it would be generally discouraged.

There are a couple different options for routing:
 1. don't do anything, all backends are equivalent. LB picks one
 2. provide some metadata in each request (which turns into HTTP headers) that the LB uses to direct to a preferred backend. But this is generally "soft" in that any backend could work, but hitting the preferred backend may be more efficient
 3. hostname-based routing, a.k.a., virtual hosting. Give each backend a different name, and the LB can use that name for specific routing. The hostname is automatically obtained from the target name, but can be overridden with `ManagedChannelBuilder.overrideAuthority`
 4. gRPC-based proxy. An implementation of the gRPC service that issues requests to backends based on the request. This is pretty heavy-weight

Probably some others I'm not thinking of. Which one makes the most sense depends on what you are doing.
