### ISSUE TITLE
issue with progaurd minifyEnabled

### ISSUE THREAD

**Issue by Nishant-Pathak** [grpc/grpc-java#2346]
Hello,

First of all, thank you guys for awesome work. Currently, I am using grpc on my android app and it crashes with below trace when minifyEnabled is true in gradle configuration. Is there any specific progaurd rule/ config for this ?

```
E: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact
       at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:127)
       at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:45)
       at com.nishant.starterkit.helloWorld.HelloWorldActivity$GrpcTask.doInBackground(HelloWorldActivity.java:78)
       at com.nishant.starterkit.helloWorld.HelloWorldActivity$GrpcTask.doInBackground(HelloWorldActivity.java:62)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by ejona86** [comment]
See grpc/grpc-java#2207. Basically, there is a bug with how we expected ProGuard to behave. In the short-term you can add some ProGuard configuration. In the long-term it should Just Work™.

**Comment by Nishant-Pathak** [comment]
@ejona86 thanks. will try the workaround and confirm.

**Comment by xuguobiao** [comment]
I am also using grpc on my android app, and using proguard to minify. Recently I got some problems, can someone help? @ejona86 @Nishant-Pathak 

Here are some crash logs I received from my online app.

`
java.lang.NoClassDefFoundError:io.grpc.okhttp.OkHttpChannelBuilder
io.grpc.okhttp.OkHttpChannelProvider.io.grpc.okhttp.OkHttpChannelBuilder builderForAddress(java.lang.String,int)(SourceFile:52)
io.grpc.okhttp.OkHttpChannelProvider.io.grpc.ManagedChannelBuilder builderForAddress(java.lang.String,int)(SourceFile:38)
io.grpc.ManagedChannelBuilder.io.grpc.ManagedChannelBuilder forAddress(java.lang.String,int)(SourceFile:45)
`

`java.lang.NullPointerException:Attempt to invoke virtual method 'com.squareup.okhttp.k$a com.squareup.okhttp.k$a.a(boolean)' on a null object reference
com.squareup.okhttp.ConnectionSpec.void <clinit>()(SourceFile:58)
io.grpc.okhttp.OkHttpChannelBuilder.void <clinit>()(SourceFile:73)
io.grpc.okhttp.OkHttpChannelProvider.io.grpc.okhttp.OkHttpChannelBuilder builderForAddress(java.lang.String,int)(SourceFile:52)
io.grpc.okhttp.OkHttpChannelProvider.io.grpc.ManagedChannelBuilder builderForAddress(java.lang.String,int)(SourceFile:38)
io.grpc.ManagedChannelBuilder.io.grpc.ManagedChannelBuilder forAddress(java.lang.String,int)(SourceFile:45)`

`io.grpc.okhttp.Utils.io.grpc.okhttp.internal.ConnectionSpec convertSpec(com.squareup.okhttp.ConnectionSpec)(SourceFile:80)
io.grpc.okhttp.OkHttpChannelBuilder$OkHttpTransportFactory.io.grpc.internal.ConnectionClientTransport newClientTransport(java.net.SocketAddress,java.lang.String,java.lang.String)(SourceFile:323)
io.grpc.internal.CallCredentialsApplyingTransportFactory.io.grpc.internal.ConnectionClientTransport newClientTransport(java.net.SocketAddress,java.lang.String,java.lang.String)(SourceFile:62)
io.grpc.internal.TransportSet.java.lang.Runnable startNewTransport(io.grpc.internal.DelayedClientTransport)(SourceFile:215)
io.grpc.internal.TransportSet.io.grpc.internal.ClientTransport obtainActiveTransport()(SourceFile:192)
io.grpc.internal.ManagedChannelImpl$3.io.grpc.internal.ClientTransport getTransport(io.grpc.EquivalentAddressGroup)(SourceFile:637)
io.grpc.internal.ManagedChannelImpl$3.java.lang.Object getTransport(io.grpc.EquivalentAddressGroup)(SourceFile:579)
io.grpc.DummyLoadBalancerFactory$DummyLoadBalancer$1.java.lang.Object get()(SourceFile:135)
io.grpc.internal.DelayedClientTransport$2.void run()(SourceFile:262)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:833)
`

**Comment by Nishant-Pathak** [comment]
Try adding below to your proguard-rules.pro:

`-keep class io.grpc.okhttp.OkHttpChannelProvider
`

**Comment by xuguobiao** [comment]
@ @Nishant-Pathak I've added -keep class io.grpc.** {*;} before release, it works fine on all of my own android devices, but still receive the logs above from some android devices.

**Comment by KrishHari** [comment]
@xuguobiao Did you get any solution to the  java.lang.NoClassDefFoundError: io.grpc.ManagedChannelBuilder error ?
