### ISSUE TITLE
The type io.grpc.Deadline cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by adiagarwal29** [grpc/grpc-java#2359]
grpc-all-1.0.0 and grpc-all-1.0.1 are build as blank jars hence it could not resolve to its reference.
Any pointers how to resolve this?

**Comment by ejona86** [comment]
grpc-all has Maven dependencies to other artifacts. Deadline is in grpc-context. If you're using Maven, Gradle, or Ivy, there shouldn't be a problem. But if you're dependency management manually, make sure you depend on grpc-context.

**Comment by adiagarwal29** [comment]
thanks .. It resolved the error..
You mentioned that it can be build using ivy as well.
Could you please share the ivy script, if its already there?

**Comment by ejona86** [comment]
I'm sorry, I don't know Ivy. Based on a quick look at the documentation, it seems like it would be something resembling:

```xml
<ivy-module version="2.0">
    <dependencies>
        <!-- to use grpc-all -->
        <!-- dependency org="io.grpc" name="grpc-all" rev="1.0.1"/-->

        <!-- we suggest using separate artifacts in our README -->
        <dependency org="io.grpc" name="grpc-netty" rev="1.0.1"/>
        <dependency org="io.grpc" name="grpc-protobuf" rev="1.0.1"/>
        <dependency org="io.grpc" name="grpc-stub" rev="1.0.1"/>
    </dependencies>
</ivy-module>
```

**Comment by adiagarwal29** [comment]
thanks for the information..
