### ISSUE TITLE
bindService and cglib

### ISSUE THREAD

**Issue by xiaominger** [grpc/grpc-java#2361]
aService is a cglib proxy class, then I add the service:

serverBuilder.addService(aService.bindService()).

aService.bindService(),the returned ServerServiceDefinition is not what I want because of "this"
http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#aop-understanding-aop-proxies

what should I do?

use grpc v1.0.1

**Comment by ejona86** [comment]
Instead of using a proxy, can you implement a ServerCallHandler and just use the same instance for each method? You might also use `ServerCalls` to get our normal application API.

**Comment by xiaominger** [comment]
thank you,is there an example

**Comment by ejona86** [comment]
No, there's not an example. You can look at the generated code's bindService() for an example of creating a ServerServiceDefinition. You can look at ServerCalls for an example implementation of ServerCallHandler, although I expect your implementation will be pretty different (probably simpler).

**Comment by xiaominger** [comment]
version 0.8,the static bindService is very good......

**Comment by ejona86** [comment]
Even in version 0.8 we would have discouraged using a Proxy and instead use the process I'm describing. It would be much faster, and generally more clear.

**Comment by xiaominger** [comment]
A lot of code will be changed,I want to use proxy temporarily.

**Comment by ejona86** [comment]
I'm sorry the API change impacted you negatively, but we had to make such a change before 1.0 if we were going to do it, because we are providing API stability now. It sounds like your use case can be solved with the existing API, it is just bothersome because you had existing working code.

**Comment by xiaominger** [comment]
I may use ServerInterceptors

**Comment by cr2121** [comment]
@xiaominger I override bindService method and replace `this` with my proxy.
