### ISSUE TITLE
How to use load balancer in gRPC V1.0?

### ISSUE THREAD

**Issue by NeroAo** [grpc/grpc-java#2371]
I see on the gRPC home page said, V 1.0 already has load balancing capabilities,but did not find any relevant examples.Will be in gRPC V1.0 of how to use load balancing?
Where are the loac balancing examples?

Thanks!

**Comment by carl-mastrangelo** [comment]
@NeroAo Hi,

Load balancing is split between the gRPC client and the load balancing server.  The gRPC client currently can get load balancing details from a remote server.   However, a load balancing server has not been written yet.  For the time being, you'll have to make your own.  The service is in the grpclb/ directory.

gRPC team does have on it's roadmap making a simple load balancing server for testing purposes.  It isn't yet written, but it would serve as an example on how to make your own.
