### ISSUE TITLE
client can not connect to server when server has more than 61000 connections.

### ISSUE THREAD

**Issue by wangxingge** [grpc/grpc-java#2387]
I want to test grpc performance, and I have 4 centos6.5, and update configure to allow 2000000 tcp connections.

And i use example of "route_guide" to test, just change logic of "func (s *routeGuideServer) ListFeatures" make it not return and send message to stream each 10 seconds on server side.

It's works well when connect 60000 clients, and all clients can receive message from server.
But i got error like: "2016/10/28 10:50:08 &{0xc8648f4b40}.ListFeatures(_) = _, rpc error: code = 14 desc = grpc: the connection is unavailable".
and some of others client got error like: "2016/10/28 10:50:08 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.204.10.36:10000: getsockopt: connection timed out"; Reconnecting to {10.204.10.36:10000 <nil>}"

I want to know is this a system configure problem or just a bug?

**Comment by ejona86** [comment]
It sounds like you are hitting an fd limit. This isn't likely to be a bug in gRPC. fds (file descriptors) are a scarce resource, and each connection requires an fd. You can maybe bump the limit a bit higher, but it will always be bounded.
