### ISSUE TITLE
Avoiding unbalanced backends with server-side load balancing

### ISSUE THREAD

**Issue by blakeday** [grpc/grpc-java#2395]
One of our use cases is a server-side application which must connect to a pool of backends through a layer 4 load balancer.  By default grpc-java opens only a single, long-lived channel to the backend.  So if we have 4 clients with 4 backends, the best distribution is a single connection from each client to each backend.  

There are two problems with this: 1) each client directly determines the load placed on its backend, and 2) during rolling backend deployments, the connections are redistributed to all backends except the last one deployed.

To work around these issues, I attempted to add client-side load balancing with a list of identical backend endpoints.  After a lot of poking (and finally understanding the existing DnsNameResolver, etc), I realized this wasn't going to work.  Finally I settled on a custom pool of client channels that I use in a round-robin fashion.

Unfortunately even this is imperfect because I need must limit the lifetime of a channel to avoid backends becoming unbalanced for extended periods after backend re-deployment.  Is an interceptor the best (only?) way to achieve a maximum channel lifetime?

@zhangkun83  (I mentioned this issue briefly on IRC a couple of months ago).

**Comment by ejona86** [comment]
The discussion issue for L4 is grpc/grpc#7957. It sounds like for you (1) from that issue would help the "last deployed server gets little traffic". Your LB sounds like (2) from that issue.

The LB API is going to receive a pretty massive overhaul soon, as described in https://github.com/grpc/grpc-java/issues/2211#issuecomment-244151296. We want to allow creating multiple channels to the same backend, but we've been hammering down some harder issues relating to LB.

**Comment by ejona86** [comment]
Netty transport supports max connection age on server-side since 1.3. Round-robin across a pool of channels is fine, although since 1.2 (really sort of 1.1) the LB API can create multiple connections to the same address.
