### ISSUE TITLE
Re-introduce service interfaces

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-java#2398]
Stub interfaces were generated prior to gRPC 1.0. It was since removed and now we are forced to extend a base class.

Interface is the contract for the service - it'd be great to generate the interface as well. If keeping the base abstract class, the base abstract class should implement the interface as well.

**Comment by dapengzhang0** [comment]
The reason for _not_ to introduce service interface is extensibility grpc/grpc#5371, #1469
