### ISSUE TITLE
Jetty ALPN/NPN has not been properly configured

### ISSUE THREAD

**Issue by xiaominger** [grpc/grpc-java#2408]
grpc0.14.0
jdk 1.8
netty-tcnative-boringssl-static 1.1.33.Fork14

when I start server on windows,it prints "Jetty ALPN/NPN has not been properly configured",But it works properly on Linux and MacOs.

**Comment by carl-mastrangelo** [comment]
Can you try upgrading to the latest, there was a Windows loading bug that was fixed in netty tcnative within the past 3 months.

**Comment by ejona86** [comment]
Assuming that updating will fix the problem. If it doesn't please ping this issue.

**Comment by ejona86** [comment]
Assuming that updating will fix the problem. If it doesn't please ping this issue.
