### ISSUE TITLE
how to use serverIntercepter

### ISSUE THREAD

**Issue by xiaominger** [grpc/grpc-java#2411]
grpc1.0.1

how to use serverIntercepter,I want to intercept some of the methods of a service

**Comment by ejona86** [comment]
That is far too broad of a question. You can look at the "header" example in the examples/ directory. In general, interceptors are for cross-cutting features; that is, they are for behavior that is not specific to particular methods.

**Comment by carl-mastrangelo** [comment]
@xiaominger and future readers of this issue:  You can likely get a more specific answer to your questions if you ask in the grpc forum: https://groups.google.com/forum/#!forum/grpc-io
