### ISSUE TITLE
Does gRPC support push notifications from the server to the client

### ISSUE THREAD

**Issue by yine** [grpc/grpc-java#2412]
Does gRPC support push notifications from the server to the client? Client to establish a connection, registration, if the server has to trigger events to the client, through the channel to find the client to send the connection, and then push the message to the specified client.

the example of a stream response: StreamObserver, if I do not call onCompleted method, whether this link can continue to push the message? How to get the designated client channel?

**Comment by ejona86** [comment]
Yes, streaming is a great way to provide server push. The client would start a RPC that would "listen" for events from the server. The server then sends messages at-will. Using server streaming (or bidi) prevents the need for doing long polling and similar hacks.

**Comment by carl-mastrangelo** [comment]
@yine This would be a good question to ask in our support forum https://groups.google.com/forum/#!forum/grpc-io

I am going to close this issue, as there isn't any actionable work to do here.

**Comment by yine** [comment]
Ok, tks, I see.
