### ISSUE TITLE
OkHttpChannelBuilder doesn't work 

### ISSUE THREAD

**Issue by WillSmithInChina** [grpc/grpc-java#2414]
in android high level platform ,OkHttpChannelBuilder works fine, but in android level 17 platform   , it logs out ：

E/GrpcService: java.lang.NoClassDefFoundError: io.grpc.okhttp.OkHttpChannelBuilder

is the everyone meet the same problem ? if you know that, please tell me , thank you guys !

**Comment by carl-mastrangelo** [comment]
@WillSmithInChina  Are you using Progaurd?

**Comment by WillSmithInChina** [comment]
yes , is there anything wrong ?

**Comment by WillSmithInChina** [comment]
@carl-mastrangelo  yes , is there anything wrong ?

**Comment by carl-mastrangelo** [comment]
Are you certain that Progaurd isn't rewriting that files name?  Can you inspect the jar (apk?) to see if it is actually inside?

**Comment by ejona86** [comment]
This doesn't make any sense to me. I know we have issue #2207, which includes a workaround... But this seems different/strange.

**Comment by WillSmithInChina** [comment]
@carl-mastrangelo  @ejona86  that's my fault, OkHttpChannelBuilder works ok！ thank you guys

**Comment by carl-mastrangelo** [comment]
@WillSmithInChina what was the root cause?

**Comment by WillSmithInChina** [comment]
@carl-mastrangelo i don't know ,but now it work fine automatically
