### ISSUE TITLE
a better way to convert to a Plain Ordinary Java Object

### ISSUE THREAD

**Issue by xiaominger** [grpc/grpc-java#2432]
commisson is a model from orm framework,  when provide grpc service like query,I always code like this:
```java
Commisson commission = commissionDao.query(params);
ProductProfit.Builder productProfitBuilder = ProductProfit.newBuilder();
productProfitBuilder.setId(commission.getId());
productProfitBuilder.setProdId(commission.getProductId());
productProfitBuilder .setProdName(commission.getProductName());
........
responseObserver.onValue(productProfitBuilder.build());
```
 
then the client get the response,and get the commision again，because the response is a complicated data，but sometimes we want json or a Plain Ordinary Java Object.
```java
commission.setId(response.getId());
commission.setProdId(response.getProductId())
.........
```
it is a little boring,is there any better way.

**Comment by ejona86** [comment]
That looks like about what we would expect. The builder supports fluent-style where you chain calls together, but that doesn't really change the amount of effort necessary.

**Comment by nishanthvijayan** [comment]
I'm facing a similar problem. Any updates on this? Is there any suggested workaround?
