### ISSUE TITLE
ServerServiceDefinition.addMethod fails incorrectly 

### ISSUE THREAD

**Issue by mavrukin** [grpc/grpc-java#2437]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.1

### What JVM are you using (`java -version`)?
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.
```
public class MyBindableService implements BindableService {

    @Override
    public ServerServiceDefinition bindService() {

        MethodDescriptor<String, String> myMethodDescriptor = MethodDescriptor.create(
                MethodDescriptor.MethodType.UNARY,
                "/mypage",
                new MyRequestMarshaller<>(),
                new MyResponseMarshaller<>());
        ServiceDescriptor myServiceDescriptor = new ServiceDescriptor(
                "/mypage",
                myMethodDescriptor);
        ServerMethodDefinition<String, String> serverMethodDefinition =
                ServerMethodDefinition.create(myMethodDescriptor,
                new MyServerCallHandler());
        return ServerServiceDefinition.builder(myServiceDescriptor).
                addMethod(serverMethodDefinition).build();
    }
}
```

### What did you expect to see?
This works without problem, the server starts up

### What did you see instead?
An error that says the following:
`Exception in thread "main" java.lang.IllegalArgumentException: Service name mismatch. Expected service name: '/mypage'. Actual method name: '/mypage'.
`

The reason for this is rather interesting, here is the code that generates this in addMethod:

```
 /** Add a method to be supported by the service. */
    public <ReqT, RespT> Builder addMethod(ServerMethodDefinition<ReqT, RespT> def) {
      MethodDescriptor<ReqT, RespT> method = def.getMethodDescriptor();
      checkArgument(
          serviceName.equals(MethodDescriptor.extractFullServiceName(method.getFullMethodName())),
          "Service name mismatch. Expected service name: '%s'. Actual method name: '%s'.",
          serviceName, method.getFullMethodName());
      String name = method.getFullMethodName();
      checkState(!methods.containsKey(name), "Method by same name already registered: %s", name);
      methods.put(name, def);
      return this;
    }
```

The problem is that what your outputting as the comparison is not what is actually being compared.  The "extractFullServiceName" method performs the following operation:

```
  public static String extractFullServiceName(String fullMethodName) {
    int index = fullMethodName.lastIndexOf('/');
    if (index == -1) {
      return null;
    }
    return fullMethodName.substring(0, index);
  }
```

Which normalizes in some weird way the method name, but this only happens in the above code to the MethodDescriptor, but not to the serviceName, this leads to a mismatch, and then you print out a wrong mismatch as well.  This is broken.  The other problem, is that even if you passed in just "mypage" for both values, the noramalization results in an empty string while the other one has a full string, and thus the test fails again.

**Comment by zhangkun83** [comment]
We should fix the error message to make it more clear.
