### ISSUE TITLE
Remove RoundRobinLoadBalancerFactory access to RoundRobinServerList

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2440]
io.grpc has been removing references to io.grpc.internal for some time now.  The last of these appears to be `RoundRobinLoadBalancerFactory` which imports from `io.grpc.internal.RoundRobinServerList`

This makes it hard to separate internal details from public interface.  We should remove it.

cc: @zhangkun83

**Comment by zhangkun83** [comment]
We can move RoundRobinServerList to io/grpc/util and tag it with `@Internal`.

**Comment by zhangkun83** [comment]
@carl-mastrangelo `RoundRobinServerList` will not be used by the LBv2 implementations, so it will be deleted along with the v1 implementations. Do you want it to be resolved for 1.1, or are you fine with leaving it as is for now?

**Comment by carl-mastrangelo** [comment]
You can leave it in, since it's in internal.

**Comment by zhangkun83** [comment]
RoundRobinServerList has already been deleted.
