### ISSUE TITLE
Build with Bazel

### ISSUE THREAD

**Issue by pcj** [grpc/grpc-java#2458]
Would be great to be able to build `grpc-java` with Bazel.  It looks like there may some ongoing internal efforts to do this.  Any comment on the scope/challenge of this?  Any help needed from the community?

**Comment by ejona86** [comment]
It's being worked on. java_proto_library is still maturing in Bazel, and is a dependency of any gRPC support. The gRPC support is not public yet, but also maturing. After it is made public, it could probably use some love to be easier to use, so help would be useful then.

In the short-term there is https://github.com/pubref/rules_protobuf .

**Comment by ejona86** [comment]
For reference: http://www.grpc.io/blog/bazel_rules_protobuf

**Comment by ejona86** [comment]
Fixed by #2975
