### ISSUE TITLE
How can I use OpenTracing api in grpc?

### ISSUE THREAD

**Issue by wu-sheng** [grpc/grpc-java#2463]
I am a member of OpenTracing org. I have known gRPC has supported OT spec.

Where is the doc, provide how I can set tracer to gRPC, or other ways?

**Comment by ejona86** [comment]
Maybe https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/java is what you want?

**Comment by wu-sheng** [comment]
Seems yes. Intercepte channel is all I need to be done. Right?

**Comment by ejona86** [comment]
Most likely, but there's a lot more documentation on that page.
