### ISSUE TITLE
http2 reverse proxy

### ISSUE THREAD

**Issue by killjason** [grpc/grpc-java#2470]
imagine there are 10k grpc-clients, they established 10k http2 connections(TCP-connections) with the http2 reverse proxy; then http2 reverse proxy create 10k http2 connections(TCP-connections) to the origin(backend) server.
**Is it possible to reduce the 10k connections between proxy and origin(backend) server?** 
for example, can a connection pool be used in reverse proxy to reduce connections with backend server?

**Comment by carl-mastrangelo** [comment]
Are the targets the same?  I.e. does the backend connected to remain same for each connection?  If so, you can just make a map of target to Channel and look it up.  

If they have the same IP address pool (They all logically are the same set of servers) but have different host names, you can override the hostname on the stub in your proxy.

**Comment by killjason** [comment]
@carl-mastrangelo ,maybe this picture can explain better:
![image](https://cloud.githubusercontent.com/assets/2777101/20802939/940b25d6-b828-11e6-947d-41c0dec30945.png)
this picture is in Nginx blog, Is it possible to do the same thing to reduce connections with backend serevrs using http2-reverse proxy?

**Comment by carl-mastrangelo** [comment]
I think this question is too complicated to answer in a Github issue, and others might like to know the answer as well.  Can you reopen this on our forum?  https://groups.google.com/forum/#!forum/grpc-io

**Comment by killjason** [comment]
@carl-mastrangelo I reopen this in https://groups.google.com/forum/#!topic/grpc-io/fvS1ZkhikaQ
