### ISSUE TITLE
What is the correct way to confirm send is complete? 

### ISSUE THREAD

**Issue by wu-sheng** [grpc/grpc-java#2471]
`onCompleted` means server have proccessed, correct?

My stub is like this
```java
this.spanStorageStub = SpanStorageServiceGrpc.newStub(channel);
```

Will `onError` be called when network unconnected? And when unconnected occurs, wil stub reconnect?

I can not found this demo call to show these features for GRPC.
Can anyone confirm for me?

**Comment by carl-mastrangelo** [comment]
If the RPC completes normally, onCompleted will be called.   If there is an error, onError will be called.  If an RPC has not yet started, it will try to reconnect until it is ready.   If there is a disconnect in the middle of an RPC, it will not be retried.

**Comment by wu-sheng** [comment]
If these is a disconnect in the middle of the rpc, onError will be called, and before next rpc call, will try to reconnect? Right?

**Comment by carl-mastrangelo** [comment]
You will get either an onError callback, or an onCompleted callback, but not both.  If you get an onError callback, your RPC will not be automatically retried.  If you try to send another RPC, it will try to reconnect.  If you are using a load balancer, it will try to use another existing connection if possible.

**Comment by wu-sheng** [comment]
But I at least get one of callbacks, Yes? Even network is down in several minutes.

**Comment by carl-mastrangelo** [comment]
You may not.  If the call is streaming, it may never be "complete" or "failed".  You are guaranteed to get _at most_ 1.  

If the network is down, and you have no outstanding RPCs, you may never find out.  This is a property of TCP.  

If the network is down, and you do have active RPCs, the periodic keep-alive messages will be sent to ensure that you do find out.

**Comment by wu-sheng** [comment]
Keep-live message is easy to implements. 
But in a stream service, in order to avoid outofmemory failure, I want send batch of data and wait the server-side complete its proccess.
What should I do? Set a timeout? After this, I assume its complete?

**Comment by wu-sheng** [comment]
I am afraid, in some reasons, server have low performance, and get slower than usual.
In this case, I try to avoid client memory issues and send data as soon as possible.

**Comment by carl-mastrangelo** [comment]
If you are using a Streaming RPC, your connection will be kept alive.  You can send your batch of data, and then just wait for the RPC to complete.  As long as you have not yet received onCompleted or onError, the connection will be kept alive.

**Comment by wu-sheng** [comment]
In this case, oncomplete will be called, can guarantee? Just wait to complete? Is enough?
Even need grpc auto reconnect?

**Comment by carl-mastrangelo** [comment]
I'm sorry, but I don't understand your question.

**Comment by wu-sheng** [comment]
Sorry. I describe my question again

I am using a Streaming RPC,  will I receive `onCompleted` eventually (because of grpc auto reconnect)?  The client waits for `onCompleted` and send another data, is this the right thing to do? like this:

* before send
```java
SpanStorageClient spanStorageClient = client.newSpanStorageClient(new StorageClientListener() {
            @Override
            public void onError(Throwable throwable) {
                previousSendFinish = true;
                HealthCollector.getCurrentHeathReading(getExtraId()).updateData(HeathReading.ERROR, "Failed to send  span. error message :" + throwable.getMessage());
            }

            @Override
            public void onBatchFinished() {
                previousSendFinish = true;
                HealthCollector.getCurrentHeathReading(getExtraId()).updateData(HeathReading.INFO, " consumed Successfully");
            }
        });
        previousSendFinish = false;
        return spanStorageClient;
```

* after send, and waiting
```java
public void wait2Finish() {
        while (!previousSendFinish) {
            try {
                Thread.sleep(1L);
            } catch (InterruptedException e) {
            }
        }
    }
```

Will `wait2Finish` become a endless loop？

**Comment by carl-mastrangelo** [comment]
wait2Finish could be in an infinite loop if `previousSendFinish` is  not a volatile.  I don't know when `onBatchFinished` will get called, as that isn't gRPC's code.  If it is fired as part of onCompleted, then you will only ever get one or the other, but never both, and never more than than one.

If you don't set a time out, that code may be an endless loop, even if the network is fine.  The server could just never send anything back.

**Comment by wu-sheng** [comment]
Volatile is set for sure. As you said, I will add a timeout to avoid endless loop.
Thank you all.
