### ISSUE TITLE
Proto reflection service: Optimize handling of dynamic services

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc-java#2480]
The initial proto reflection service (https://github.com/grpc/grpc-java/pull/2386) reloads all proto file descriptors for every request. This was done to avoid checking for any service changes within a mutable fallback registry, but should be optimized to avoid re-processing unchanged services.

This likely requires a minor modification in core to enable the reflection service to distinguish between dynamic and static services.

**Comment by ejona86** [comment]
Fixed by #2532
