### ISSUE TITLE
GrpcServerRule is Experimental

### ISSUE THREAD

**Issue by joeyb** [grpc/grpc-java#2488]
This is a tracking issue that will be closed once `GrpcServerRule` exits experimental status.

**Comment by dapengzhang0** [comment]
@ejona86 I'm taking it now

**Comment by dapengzhang0** [comment]
oops, I was referencing to the wrong issue.

**Comment by brunobuss** [comment]
What are the requirements for this to graduate from experimental?

**Comment by dapengzhang0** [comment]
@brunobuss `GrpcServerRule` is superseded with `GrpcCleanupRule` which is more flexible and preferred.  The plan is  that `GrpcServerRule` will be marked `@Deprecated` while not be removed, and that `GrpcCleanupRule` will graduate from experimental.
