### ISSUE TITLE
How to determine different streams are based on the same channel

### ISSUE THREAD

**Issue by Backaway** [grpc/grpc-java#2499]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

`grpc-java-1.0.2`

### What JVM are you using (`java -version`)?

```sh
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.4.el6-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

### What did you do?
If possible, provide a recipe for reproducing the error.

I have a persistent connection (full-duplex) to the server with a StreamObserver (for login and push notification). And I have various unary calls based on the other streams. So if there is a api to judge whether these unary streams and the full-duplex stream are based on the same channel ? 

Purpose: refuse unary calls if the full-duplex stream dose not exists.

**Comment by carl-mastrangelo** [comment]
I don't believe there is an API to do this.  

Why would you like to refuse calls if another stream doesn't exist?

**Comment by ejona86** [comment]
No, there isn't such an API, and such an API is incredibly hard (to do securely) since new RPCs may be on a different connection. Your use case is probably best served with an alternative approach, but I don't know what you're trying to do so I can't propose an alternative.
