### ISSUE TITLE
No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

### ISSUE THREAD

**Issue by AnswerZhao** [grpc/grpc-java#2511]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.2

### What JVM are you using (`java -version`)?
1.8

### What did you do?
If possible, provide a recipe for reproducing the error.
> When building release app, the error is coming: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

**Comment by carl-mastrangelo** [comment]
Can you print out your class path?

**Comment by ejona86** [comment]
Also can you confirm that grpc-okhttp or grpc-netty are in your dependencies? You can use `mvn dependency:tree` if using Maven or `./gradlew dependencies` if using Gradle.

**Comment by Wwarrior1** [comment]
Here is a clue how to build it: http://www.grpc.io/docs/quickstart/java.html
1. Download core from [here](https://github.com/grpc/grpc-java/releases).
2. Our files need to be located into _grpc-java-*/examples/src/main_
 - in _/proto_ we paste our .proto file
 - in _/java/somePackage_ we paste our java files
3. ```cd ../../..``` (go upper to 'examples')
4. Add dependencies in build.gradle
```
...
task newTask(type: CreateStartScripts) {
    mainClassName = 'somePackage.NewTask'
    applicationName = 'new-task'
    outputDir = new File(project.buildDir, 'tmp')
    classpath = jar.outputs.files + project.configurations.runtime
}
applicationDistribution.into('bin') {
  ...
  from(mainServer)
}
```
5. ```./gradlew installDist``` and ```./gradlew dependencies```
6. Run our app in bash (or in cmd similarity). Note: we are still into _grpc-java-*/examples_.
```./build/install/examples/bin/new-task```

**Comment by ejona86** [comment]
@Wwarrior1, hmmm... Dependency-wise, that is identical to the helloworld example. Does the helloworld example work for you before you make any modifications? If so, I'd imagine there is a modification not explicitly mentioned that is causing the breakage.

**Comment by Wwarrior1** [comment]
I tried it now however it fails on:
```
io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2Connection$Endpoint.maxStreams(II)V
```
while using ```compile group: 'io.netty', name: 'netty-codec-http', version: '4.1.9.Final'```

After changing dependency to ```compile group: 'io.netty', name: 'netty-codec-http', version: '5.0.0.Alpha2'``` it seems to be less buggy as only client crashes. Still it doesn't work.
```
WARNING: Runnable threw exception in ChannelExecutor
java.lang.NoClassDefFoundError: io/netty/handler/codec/http2/internal/hpack/Decoder
```

In my program I encounter another error:
```
io.netty.channel.ChannelInitializer exceptionCaught
WARNING: Failed to initialize a channel. Closing: [id: 0xe6805e19, L:/127.0.0.1:55555 - R:/127.0.0.1:34454]
java.lang.NoClassDefFoundError: io/netty/handler/codec/http2/internal/hpack/Decoder
```
I don't know what causes such problems. It is very confusing... I don't know how to resolve this. Maybe connection with other dependencies? Somewhere i read about Guava. Before compiling on Linux, I tried to run my program on Windows using prepared .exe (https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.3.0/) and was getting errors connected with just Guava (I don't remember stacktrace, however it was caused from PARSER.parseFrom(data)). I tried another versions of guava in dependencies but still it doesn't solve the problem.

**Comment by Wwarrior1** [comment]
Are there any previous versions of dependencies which are working? Just as a temporary workaround :)

**Comment by ejona86** [comment]
Glad it's working. The NoSuchMethodError and NoClassDefFoundError are common when using an incompatible version of a library. Closing for now. If you experience other issues you can open a new issue (or post back here if related).

**Comment by mamdouhweb** [comment]
@Wwarrior1 can you elaborate on the solution you followed? I'm having the same problem here and would appreciate some help.

Thanks!

**Comment by Wwarrior1** [comment]
@mamdouhweb I am not working on grpc now. Hovewer, as far as I remember, the problem was while adding too much dependencies which were incompatible each other. I reverted back all new dependecies to stock. Just downloaded the project from github again and (from scratch) builded the project. Follow my 1st comment, it should be helpful. Main concept is to insert own project to examples and compile using its gradle.

Note: the source of the problem I encountered may be another with yours.  If you have to add some dependencies, my solution may be insufficient. The main problem is because of http2 plugin which was (in that moment) still in development.

I don't have any other clues how to overpass this problem. Everything I learned in that time is writtne here. Anyway, good luck with it !

**Comment by mamdouhweb** [comment]
@Wwarrior1 appreciate your feedback. Thanks a lot!
