### ISSUE TITLE
netty-tcnative-boringssl-static and version 1.1.33.Fork19 need which glibc verson

### ISSUE THREAD

**Issue by stoneCrystal** [grpc/grpc-java#2516]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
netty-tcnative-boringssl-static and version 1.1.33.Fork19 need which glibc verson?

### What JVM are you using (`java -version`)?
JDK1.7

### What did you do?
If possible, provide a recipe for reproducing the error.

**Comment by stoneCrystal** [comment]
my application use netty-tcnative-boringssl-static and version 1.1.33.Fork19 , and have the error
**/lib64/libc.so.6: version `GLIBC_2.7' not found**, after upgrade to 2.7, 

have the error
**/lib64/libc.so.6: version `GLIBC_2.10' not found**,

so which glibc version is work? i feel very confuse!!

**Comment by carl-mastrangelo** [comment]
Any reason to not use Fork24?

**Comment by ejona86** [comment]
Closing. Fix should be to use a newer version of tcnative that had a fixed build process. This should already be supported and working today.
