### ISSUE TITLE
How to cause Invalid protobuf byte sequence?

### ISSUE THREAD

**Issue by wu-sheng** [grpc/grpc-java#2517]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.2

### What JVM are you using (`java -version`)?

```
com.blueware.deps.io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at com.blueware.deps.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java) ~[oneapm.jar:2.0]
	at com.blueware.deps.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java) ~[oneapm.jar:2.0]
	at com.blueware.deps.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java) ~[oneapm.jar:2.0]
```

`io.grpc` is renamed by me. How does this exception happen? It happen in only one environment, but I can't tell the diff between this one and others.

Can you give me some tips? How to know, what cause this?

**Comment by carl-mastrangelo** [comment]
It sounds like you are getting garbled data.  What server is your client talking to?  Could you  describe your setup more?

**Comment by wu-sheng** [comment]
This is a very strange thing. My client is a normal grpc client, using blocking stub. Server is also a grpc server, and use the same version grpc lib, which is 1.0.2. I nearly set nothing, but use default config of grpc.

Which setup should I focus, and provide to you?

I have deploy my client and server in many places, nothing happend like this. So I am totally confused.

Maybe, is it possible because of network or firewall, or something else? Or because of too large data to transform?

**Comment by wu-sheng** [comment]
This is my screenshot:
![370b13bca6f49a18d54476556e083c82](https://cloud.githubusercontent.com/assets/5441976/21209054/0072e860-c2ad-11e6-8c02-de5ae33f283f.jpg)

This is OS and JVM info:
![e9f726d1bcd5e8a8ad81e189d3311645](https://cloud.githubusercontent.com/assets/5441976/21209090/2bc0be48-c2ad-11e6-9ce0-75e4191cd7c7.png)

**Comment by carl-mastrangelo** [comment]
Hmm, Tag number of 0 is indeed invalid, but it doesn't say what the invalid bytes were.  Could you turn on frame level debugging?

To do so, make a file with this gist:
https://gist.github.com/carl-mastrangelo/49f6d6a8ff29200fcb7d9e25e473b2d0

Then start up the JVM (the one that's raising an exception) with the flag `-Djava.util.logging.config.file=myLoggingConfigFilePath`  but with the path to the correct file.

It should log a bunch of stuff to the console.  Could you include the output of that?

**Comment by wu-sheng** [comment]
Change the level to io.grpc.netty.NettyServerHandler.level=FINEST,  wait to see what happen.

**Comment by wu-sheng** [comment]
@carl-mastrangelo , A possible cause seems from the `map`, one service contains this message:
```proto
message JarRecord {
    string name = 1;
    string version = 2;
    map<string, string> attributes = 3;
}
```

If I remove this, service goes well, otherwise, exception happened...  
Don't have a clue.

**Comment by carl-mastrangelo** [comment]
It would be really helpful to see those http2 logs.  I think that's the next step to debugging this.

**Comment by wu-sheng** [comment]
Would log setting above help to show log?
I said something wrong. If I remove map, still `invalid sequence`, just no`invalid tag zero` cause.

**Comment by carl-mastrangelo** [comment]
@ejona86 Do you remember the incantation for enabled the hexdump frame logs?  I just tried mine and it didn't work.

**Comment by ejona86** [comment]
```
# Provide this file as value to java.util.logging.config.file system property
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = ALL

.level = ALL
#io.netty.level = INFO

io.grpc.netty.NettyClientHandler = ALL
io.grpc.netty.NettyServerHandler = ALL
```
