### ISSUE TITLE
Review experimental annotations for 1.1

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2518]
We should check all experimental tags, and see if we feel comfortable graduating them to the supported status.

**Comment by dapengzhang0** [comment]
List of APIs proposed to be non-experimental in 1.1
https://github.com/grpc/grpc-java/issues?q=is%3Aopen+is%3Aissue+label%3A%22experimental+API%22+milestone%3A1.1

**Comment by carl-mastrangelo** [comment]
It appears all annotations have been reviewed and issues filed.  Closing this.
