### ISSUE TITLE
What does setting  GRPC  once request  read  time out ? 

### ISSUE THREAD

**Issue by yeyincai** [grpc/grpc-java#2520]
In a production environment ,we should setting once request   time,avoid  cascading failures,so  what does setting  GRPC  once request  read  time out ?

**Comment by ejona86** [comment]
I'm sorry, but I don't understand your question. I'm not sure what you are setting. Are you specifying a deadline? Do you get a particular error message?

**Comment by yeyincai** [comment]
@ejona86  I'm sorry, for example  httpclient   and  webservice ,we can setting read_time_out,it's not  connection time_out,but is  one  request message  that  in the expected time to accept。

**Comment by ejona86** [comment]
gRPC doesn't provide read time outs out-of-the-box. Are you configuring the socket somehow?
