### ISSUE TITLE
ManagedChannelImpl leaves grpc theads unreleased after shudown or shutdownNow

### ISSUE THREAD

**Issue by leslie-leder** [grpc/grpc-java#2525]
Using grpc-1.0.2 & netty-4.1.6-Final with 
 Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
 Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
 Fedora 25 - Linux 64

When using shutdown or shutdownNow on the client channel ManagedChannelImpl grpc threads are not released. This is in my production system as well as in the minimal example I've stripped down, see below. The server is not available and no actual call is done. The code is invoked from scala-2.11.8 but this should not matter. 
If I do the code in a loop more and more threads pile up without going away after some time.

  ```
   val sslContext = GrpcSslContexts.forClient()
      .trustManager(InsecureTrustManagerFactory.INSTANCE)
      .build()
   
    //one additional threadDeathWatcher-1-1

    val channel = NettyChannelBuilder
      .forAddress(MyServer.address, MyServer.port)
      .sslContext(sslContext)
      .build()

    //no additional thread

    val client = MyServerGrpc.newStub(channel)

    //no additional thread    

    channel.shutdownNow();

    //eleven additional grpc-* threads

    channel.awaitTermination(5, TimeUnit.MINUTES)
 
    //succeeds instantly, all grpc-* threads are still there.   
```

**Comment by carl-mastrangelo** [comment]
This may be a bug.  We try to make all threads daemon by default, and auto close any shared threads if the last channel using them terminates.  Can you provide a few stack traces to see what those threads were doing?

 That said, you should *really* provide your own thread pool (by calling `executor()`.  Then, after the channel terminates you can close your thread pool.

**Comment by ejona86** [comment]
Note that this is normal if your application is still using those threads. The Channel considers itself terminated when it has queued all necessary events. If the application is slow processing those events, then there can be a pileup.

That said, it could be a legitimate bug. As Carl mentioned, a thread dump would help a lot.

**Comment by zhangkun83** [comment]
Given the setup you have provided, the shared thread pool is in use. It is managed by `SharedResourceHolder`, which delays the termination of the thread pools by 1 second after the channel is terminated. It's not a bug if you find live threads immediately after `awaitTermination()` returns, but it could be a bug if it's long after that.

**Comment by leslie-leder** [comment]
The threads are created by channel.shutdown. There is no difference if I use an own executor (which I shutdownNow after channel shutdownNow and awaitTermination). 
I see no delayed termination, the threads live until jvm termination.
They are named like so:
```
Thread [grpc-default-worker-ELG-2-1] ... [*-2-8]	
Thread [grpc-default-worker-ELG-3-1] ... [*-3-2]	
...
```
multiple of  the same name:
```
Thread [grpc-shared-destroyer-0]	
Thread [threadDeathWatcher-1-1]	
```

More worse. If I put the whole code block from above into a loop and run it multiple times I've two different behaviors. 

First: just run the loop, the threads from the first creation are reused. They are never closed but don't pile up.

Second: add Thread.sleep(2000) to the end of the loop. Threads are not reused, every loop iteration a new set of those threads is created and never dies.

**Comment by leslie-leder** [comment]
The idea with the thread dump was the right one. 
It was the Eclipse debug view that tricked me. When doing a thread dump after my test loop everything is ok. Eclipse just pretended those threads were still alive.

Sorry & thanks for your time.

**Comment by ejona86** [comment]
The thread creation that you noticed is because the Netty thread pool creates any as-of-yet uncreated threads as part of its shutdown. Pretty silly, but also hasn't been that severe.
