### ISSUE TITLE
Add clearer message when receiving GOAWAY from the server.

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#253]

**Comment by ejona86** [comment]
I thought I did this in https://github.com/grpc/grpc-java/commit/e515c772cd81cc4ee1b6f24c1c36afbaac1c2ebb

**Comment by ejona86** [comment]
My changed message doesn't indicate the error is from a GOAWAY. I think RST_STREAM and GOAWAY will cause identicaly Statuses. That _may_ be appropriate though, given the HTTP/2 semantics.

**Comment by nmittler** [comment]
@ejona86 I think the current code does about as much as we can given what the server is sending.  WDYT? Should we close this?

**Comment by ejona86** [comment]
Yeah, and this problem has gone through multiple different iterations. It will need to be more specific if something still needs to be improved.
