### ISSUE TITLE
Make Deadline test-friendly

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2531]
In its current form, io.grpc.Deadline is not suitable for testing.  It is not possible to create a deadline with an absolute offset, making it impossible to reliably create two relative deadlines.  The only public constructor is `after()` which is actually a timeout!

**Comment by zhangkun83** [comment]
I just find myself in need of this. As mentioned in https://github.com/grpc/grpc-java/pull/2571#issuecomment-322536735, we need a deadline factory. And for the factory approach to work, we need to make everyone use the factory to create `Deadline`s. If `Deadline` were experimental, I would propose deprecating `Deadline.after()`. Can we deprecate a stable API and keep it forever?

**Comment by zhangkun83** [comment]
Alternatively, we can make `Deadline.after()` grab the ticker from the current Context, thus we don't need to break API.

**Comment by carl-mastrangelo** [comment]
@carl-mastrangelo I think we talked about this a long time ago, and my preference was for getting it from the Context.    I implemented a similar pattern in another application I was working on, and it worked out pretty well.

**Comment by zhangkun83** [comment]
Talked with @ejona86 today. His main concern about the Context-based injection doesn't reach everywhere. `ServerImpl` creates the `Deadline` outside of `Context`, and before interceptors are run. `Executor`s would need to be wrapped to make sure the `Context` is attached, and not all `Executor` creation are accessible from the test code.

@ejona86's proposal is to allow the `Ticker` to be set globally. Although it's possible for a `Ticker` to "leak" into unexpected places if the user is not careful enough, we will make `Deadline` throw whenever it finds out its `Ticker` is different from the current one, and we will make it very clear that it's only meant for test code. I am fine with this approach.

**Comment by zhangkun83** [comment]
Because @carl-mastrangelo is strongly against the global approach, I talked with @ejona86 again, and we agreed on explicit passing the `Ticker` on `Deadline` API, basically reviving #2571. We expect anybody who want to make their `Deadline` usage testable will need to use the explicit API.
