### ISSUE TITLE
Acess services from Server

### ISSUE THREAD

**Issue by Chumper** [grpc/grpc-java#2533]
I would like to access all registered services from a build server, in my case the name is enough.

Therefore I need access to the handlerRegistry of the Server [here](https://github.com/grpc/grpc-java/blob/209a32fd1af56885c937b88cf9371acfea9a889d/core/src/main/java/io/grpc/internal/ServerImpl.java#L95) and also an added entry in the interface.

Do you think that is a good idea? 
I am currently writing an etcd service discovery on top of grpc and want to register all services from a server, so I need to access the services.

It would also be a good approach for me if I could add an interceptor/listener to the server that will be called when the server started where I can access those information.

**Comment by ericgribkoff** [comment]
Recently an `@ExperimentalApi getServices()` was added to the Server interface ([link](https://github.com/grpc/grpc-java/blob/bff6506f92e6462abf19bd22cdde83043a1080f5/core/src/main/java/io/grpc/Server.java#L73)) as part of the support for service reflection. ServerImpl's implementation of this method is [here](https://github.com/grpc/grpc-java/blob/bff6506f92e6462abf19bd22cdde83043a1080f5/core/src/main/java/io/grpc/internal/ServerImpl.java#L182). You can see an example of usage in ProtoReflectionService, which also uses a mechanism to register for a callback from the server upon build, seen [here](https://github.com/grpc/grpc-java/blob/bff6506f92e6462abf19bd22cdde83043a1080f5/services/src/main/java/io/grpc/protobuf/service/ProtoReflectionService.java#L73). Will these work for your use case?

Note that all of these additions are experimental, so they may still change at any point in master, and haven't made their way into any releases yet.

**Comment by Chumper** [comment]
Yes, that would be enough for my use case and work perfectly. I would prefer to register a callback and get all services once the server is build, but that should be good for now.
