### ISSUE TITLE
CompositeChannelCredentials for OkHttpChannelBuilder channel

### ISSUE THREAD

**Issue by pauljohnston2009** [grpc/grpc-java#2534]
C++ has composite credentials for the channel, as well as CallCredentials for individual stubs. 
Does grpc-java have something similar?

So far all i've managed to find is the call credentials that can be applied to each stub, but that means I have to manually add it each time I create a stub, rather than just letting the channel handle it.

Is there a better way to do this?

Will something similar to CompositeChannelCredentials  be added to OkHttpChannelBuilder?

**Comment by carl-mastrangelo** [comment]
Stubs are forkable, you can create a stub from another, rather than rewrapping the channel each time.  Does that work for you?

**Comment by pauljohnston2009** [comment]
Thanks, ill look into it.

However forking still means that I have to do it for each stub type initially, rather than just have the channel apply it when I create the stub.

It would just be nicer if the channel could handle the common call metadata, not sure if this is easy to accomplish in the java implementation though.

**Comment by carl-mastrangelo** [comment]
Common call metadata can be done with interceptors.  (and technically credentials can be done this way too, but stub forking is easier for the latter case)

**Comment by pauljohnston2009** [comment]
Thanks, looks like interceptors can do what I want.
