### ISSUE TITLE
Document transport layers (netty vs okhttp)

### ISSUE THREAD

**Issue by benmccann** [grpc/grpc-java#254]
Hi, am I right that there are currently two implementations of the transport layer? Netty and okhttp? I was curious if there are any situations in which one might be preferable to the other as I'm not quite sure why there are two implementations.

**Comment by ejona86** [comment]
Netty is for most usages, and okhttp is for Android. That is implicit today with our examples, but we should make that more clear.

**Comment by benmccann** [comment]
Ah, thanks. That's super helpful context!

I assume usage on Android is mostly as a grpc client. Given that, is the okhttp implementation a client-only? Or is there an okhttp server as well?

**Comment by buchgr** [comment]
@benmccann yes okhttp is only for the client.
