### ISSUE TITLE
Network is unreachable: pubsub.googleapis.com/2607:f8b0:4001:c02:0:0:0:5f:443

### ISSUE THREAD

**Issue by garrettjonesgoogle** [grpc/grpc-java#2541]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.0.1

### What JVM are you using (`java -version`)?

openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102)
OpenJDK 64-Bit Server VM (build 25.102-b01, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

Tried to connect to the gRPC Pub/Sub service.

### What did you expect to see?

A successful connection.

### What did you see instead?

Caused by: java.net.SocketException: Network is unreachable: pubsub.googleapis.com/2607:f8b0:4001:c02:0:0:0:5f:443

### Other info:

* Running in a docker image in Google Compute Engine
* From what I understand, GCE does not support IPv6. But, when using gRPC (through Netty), for some reason it's trying to use IPv6 instead of IPv4.

**Comment by carl-mastrangelo** [comment]
As long as both A and AAAA addresses come back, they should both be added to the LoadBalancer and cycled through.   Are you saying it cannot connect at all, or that you just happen to see an error logged?

**Comment by garrettjonesgoogle** [comment]
I can't connect at all.

**Comment by carl-mastrangelo** [comment]
cc: @zhangkun83

**Comment by zhangkun83** [comment]
@garrettjonesgoogle could you turn on FINE-level logging for `io.grpc` and post the logs?

**Comment by garrettjonesgoogle** [comment]
In an inexplicable turn of events, trying this today didn't cause the network error. I have no idea what happened.

**Comment by ejona86** [comment]
If it happens again, confirm you can connect to the domain via ping.

**Comment by garrettjonesgoogle** [comment]
I did try both `ping` and `curl` to the domain from the docker container and they both worked (they both went through ipv4). I didn't know about `ping6` at the time, but I tried it now and it says "Network is unreachable", which seems expected to me given that GCE doesn't support IPv6.

**Comment by ejona86** [comment]
There's not much to investigate here, so closing. @garrettjonesgoogle, feel free to open this again if you're able to reproduce it again. We'll be interested if gRPC connecting fails but ping works (at the same point in time). I think both ipv4 and ipv6 failed, but we only deliver one of the Statuses so you don't see why the ipv4 failed. I do think the logging Kun mentioned will show them.

@zhangkun83, this is a case where choosing the "correct" (which is impossible to determine) error to propagate to the call is hard. The incomplete error message will probably rear its head some more.
