### ISSUE TITLE
 The version of okhttp is not up-to-date

### ISSUE THREAD

**Issue by trywarrior** [grpc/grpc-java#2549]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.2

### What JVM are you using (`java -version`)?
1.8.0_51

### What did you do?
If possible, provide a recipe for reproducing the error.

grpc used the old version of okhttp 2.5.0

### What did you expect to see?

Update the version of okhttp to the latest version

**Comment by carl-mastrangelo** [comment]
I believe we have vendored copies of OkHttp in our code, which have since been modified.  It may be difficult to update OkHttp.

**Comment by ejona86** [comment]
The code is vendored, which means it doesn't really change much the version in the dependency chain. See #2999
