### ISSUE TITLE
SECURITY.md mutual TLS code snippet out of date

### ISSUE THREAD

**Issue by jorgheymans** [grpc/grpc-java#2555]
FYI the code snippet in the mutual TLS section seems out of date, the method signature of the given ServerInterceptor still references MethodDescriptor

> public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(**MethodDescriptor<ReqT, RespT> method**,    ServerCall<RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {

**Comment by carl-mastrangelo** [comment]
@jorgheymans Want to send a PR?

**Comment by jorgheymans** [comment]
Sure, won't be until end of next though.

**Comment by jorgheymans** [comment]
see  #2597

**Comment by ejona86** [comment]
Fixed in #2597
