### ISSUE TITLE
Can a name resolver handle multiple schemes?

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#2556]
I have a name resolver which itself is backed by a gRPC service which accepts the full URI string and allows for a handful of schemes(think something like eureka:// or eurekas://).  getDefaultScheme can only return a single string, but the newNameResolver call is capable of returning a name resolver for multiple schemes.  What is the proper way to go about doing this?  Should I make two different factories so they each return the defaultScheme appropriately, or can I have a single Factory that returns the insecure or secure scheme only?

**Comment by ejona86** [comment]
Yes, a `NameResolver` can handle multiple schemes. I'm not a strong fan of the `getDefaultScheme()` being on the `NameResolver` interface (I'd rather it be separate), but we're frying bigger fish. We only partially converted to NameResolverProvider; eventually there should be some simple cleanup.

The point of `getDefaultScheme()` is just to choose what scheme should be attempted if no scheme is provided in the target. This is normally "dns", but you could change it for your environment. It is unused if your NameResolver isn't the "primary" one. The "primary" one is the one with the lowest priority. So today it wouldn't be crazy for your name resolver to return "dns", even if it didn't support it.

In the future you _may_ need to split it, depending on how the API tweaks go. But I wouldn't expect it to cause you much pain. But I do think it makes sense to keep it as one factory/implementation today.

**Comment by jhspaybar** [comment]
Thanks for the details!
