### ISSUE TITLE
Which version of android sdk/ios sdk support gRPC.

### ISSUE THREAD

**Issue by hoswey** [grpc/grpc-java#2561]
Hi, which version of android/ios sdk support gRPC, I am sorry I can't find any information in the website.

**Comment by carl-mastrangelo** [comment]
This could be better answered in the forum here: https://groups.google.com/forum/#!forum/grpc-io

I don't know about iOS, but at least for Java we compile down to API level 9.  We depend on Google Play Services for an up to date SSL implementation.
