### ISSUE TITLE
grpc-testing maven package broken

### ISSUE THREAD

**Issue by msteinhoff** [grpc/grpc-java#2574]
### What version of gRPC are you using?

1.0.3

### What JVM are you using (`java -version`)?

1.8.0_77

### What did you do?

I want to use the GrpcServerRule in my junit tests. 

### What did you expect to see?

When I include `testCompile "io.grpc:grpc-testing:1.0.3"` in my dependencies, I can use `GrpcServerRule` and all other classes currently available in the main github repo.

### What did you see instead?

When I include `testCompile "io.grpc:grpc-testing:1.0.3"` in my dependencies, the `GrpcServerRule` and other classes are not there.

The `grpc-testing-1.0.3-sources.jar` file on bintray indeed does not contain those classes.

**Comment by carl-mastrangelo** [comment]
Hmm, GrpcServerRule was added after 1.0.0: https://github.com/grpc/grpc-java/blob/v1.0.x/testing/src/main/java/io/grpc/testing/GrpcServerRule.java


You shouldn't be able to use that at all.  I'm surprised it's present.

**Comment by msteinhoff** [comment]
So does this mean that the rule shouldn't be used by 3rd party code?

**Comment by msteinhoff** [comment]
Hm I see, it is not committed under the v1.0.3 tag. Will this ever be released?

**Comment by carl-mastrangelo** [comment]
yes, soon.  We are actively coordinating the release of the next version.

**Comment by ejona86** [comment]
This is simply a case of a new feature not being released yet. `GrpcServerRule` will be part of the 1.1 release.

**Comment by msteinhoff** [comment]
Thanks for the info.
