### ISSUE TITLE
What's the default value of TCP_NODELAY

### ISSUE THREAD

**Issue by qiuxiafei** [grpc/grpc-java#2575]
What's the default value of TCP_NODELAY in gRPC-java and is there's a way to set this option?

### What version of gRPC are you using?

1.0.1
### What JVM are you using (`java -version`)?

open jdk 1.8

**Comment by ejona86** [comment]
The Netty library defaults to NODELAY, so gRPC inherits the default. We explicitly [enable NODELAY in the OkHttp transport](https://github.com/grpc/grpc-java/blob/v1.0.3/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java#L428). The next release will have [`NettyChannelBuilder.withOption(ChannelOption<T>, T)`](https://github.com/grpc/grpc-java/blob/bff6506/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L149), which you could pass `ChannelOption.TCP_NODELAY`.

**Comment by qiuxiafei** [comment]
thanks, i found that netty enable NODELAY on all os except android.
