### ISSUE TITLE
com.google.protobuf:protoc:3.1.0 generates unusable stubs

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-java#2578]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.3

### What JVM are you using (`java -version`)?
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

### What did you do?
1. Create a new gRPC project latest instruction from gRPC 1.0.3 from master branch https://github.com/grpc/grpc-java
1. Create a .proto file with a message field map<string, string>
1. Generate the stubs

### What did you expect to see?
Expected to see successful stub generating

### What did you see instead?
Error message indicating `serializeStringToMap` method is not found:
```
symbol:   method serializeStringMapTo(com.google.protobuf.CodedOutputStream,com.google.protobuf.MapField<java.lang.String,java.lang.String>,com.google.protobuf.MapEntry<java.lang.String,java.lang.String>,int)
  location: class com.google.protobuf.GeneratedMessageV3
```

### More Information
After much troubleshooting, the README in 1.0.3 tag seem to have the correct combination of protoc version (3.0.2) and gRPC version (1.0.3)
https://github.com/grpc/grpc-java/tree/v1.0.3

However, the master branch has the incorrect combination of protoc version (3.1.0) and gRPC version (1.0.3).  protoc 3.1.0 would generate the incorrect stub source.

**Comment by ejona86** [comment]
Thanks for noticing and reporting. Sorry it bit you.
