### ISSUE TITLE
Distinct status for client channel shutdown

### ISSUE THREAD

**Issue by leslie-leder** [grpc/grpc-java#2579]
grpc-1.0.3

I've a long running server availability monitoring rpc method implemented. The server just sends status messages if it is still alive. This is wrapped into an rxObservable so I can reconnect from client under the hood. But I should do so only if the client (channel) wasn't shutdown.

Unfortunately I get the same status (UNAVAILABLE) - as StatusRuntimeException - in the monitoring stream observer for **server is unavailable** and for **client channel shutdown**. The difference is only the description where I get a message like:

    "channel shutdownnow invoked"

Currently I test the status description if it contains 'channel' && 'shutdown' in order to decide for reconnect or not.

Is there a better way to decide whether the channel is shutdown or the server is just unavailable? Or is there an distinct status planned for both events?

**Comment by ejona86** [comment]
Whatever is shutting down the channel should instruct your code to shut down first. It's the application's job of shutting itself down sanely.

No new status for this case is planned nor likely.

**Comment by leslie-leder** [comment]
Unfortunately I cannot instruct this code to shutdown due to its functional nature. Its just a (scala) function which handles the error case of the monitoring rpc call.
If I need to control this code from outside it means to introduce shared mutable synchronized state. My function would get side effects which I usually try to avoid. 

Is it really that unusual to do different stuff for server unavailable and client shutdown?
At least the description is already different.

Would it also be possible to use ManagedChannel.isShutdown in a StreamObserver?

**Comment by ejona86** [comment]
You can use `ManagedChannel.isShutdown` from within your `StreamObserver` implementation. That is "shared mutable synchronized state" though.

It seems like any RPC isn't pure from a functional standpoint.

**Comment by ejona86** [comment]
If there's more to add, this can be reopened, but for now it doesn't seem any more will happen here.
