### ISSUE TITLE
Investigate Appengine Thread Partitioning

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc-java#2582]
Currently, using gRPC on AppEngine requires a new channel to be created for each request.  Sharing channels across requests would have substantial performance benefit, but would require per-request threading.

**Comment by carl-mastrangelo** [comment]
Isn't that how OkHTTP works?

**Comment by kpayson64** [comment]
Summarizing offline discussion:
OkHTTP uses a new thread for each gRPC request.  However the Executor might try to recycle threads between AppEngine requests.  Using an executor with a core pool size of 0 when on AppEngine should solve this issue.

**Comment by kpayson64** [comment]
There might be more work required, it looks like OkHTTP uses a single read loop:
https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java

**Comment by ejona86** [comment]
OkHttp already had the code for this, but special-cased it to Java 7 GAE. Java 8 GAE is supposed to use Netty, which is where the confusion for this issue came from.
