### ISSUE TITLE
Clarify best practices for sending credentials in ClientAuthInterceptor

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2586]
The replacement for ClientAuthInterceptor, a deprecated but useful class, is GoogleAuthLibraryCallCredentials.  ClientAuthInterceptor has much wider usage, presumably because GoogleAuthLibraryCallCredentials is difficult to use, with no clear examples.  

Some better Javadoc needs to be added to GoogleAuthLibraryCallCredentials, as well, as some extremely easy to read example code.  It should make a convincing argument for why it should be used over ClientAuthInterceptor.

ClientAuthInterceptor has been deprecated in 1.0.x, and is subject to removal.

**Comment by ejona86** [comment]
`GoogleAuthLibraryCallCredentials` in internal. Users use `MoreCallCredentials.from()` instead. This is already documented in the [auth guide](http://www.grpc.io/docs/guides/auth.html#java). Not that I disagree with adding more documentation, but most usages probably pre-date CallCredentials; it was a very late add. And I've seen multiple new usages that were simply copy-pastes of earlier usages.

> It should make a convincing argument for why it should be used over ClientAuthInterceptor.

If we delete ClientAuthInterceptor then it seems weird to include documentation including it. We can certainly include some details in the release notes though.

**Comment by carl-mastrangelo** [comment]
` @deprecated use {@link GoogleAuthLibraryCallCredentials} instead.`  is what it says on ClientAuthInterceptor.  You are saying that is wrong?

**Comment by ejona86** [comment]
`GoogleAuthLibraryCallCredentials` isn't `public`, so yes. It _is_ the actual class that is used, but just isn't exposed with that name. It seems pretty obvious how the mistake in the javadoc was made though.

**Comment by carl-mastrangelo** [comment]
Ok, I have changed the title of this bug.  Right now, the javadoc on CAI is useless and wrong.  It cannot be removed until there is a clear alternative.  The code is the source of truth.

**Comment by ejona86** [comment]
I'm not sure I understand. If we deleted ClientAuthInterceptor today then the broken comment wouldn't be seen.
