### ISSUE TITLE
Any ETA on 1.1.0 Release?

### ISSUE THREAD

**Issue by tmiddlet2666** [grpc/grpc-java#2590]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.1.0-SNAPSHOT

### What JVM are you using (`java -version`)?
1.8

### What did you do?
If possible, provide a recipe for reproducing the error.
N/A

### What did you expect to see?
N/A

### What did you see instead?
N/A

### Question
Is there any ETA for 1.1.0 gprc-java release?
Thanks
Tim

**Comment by carl-mastrangelo** [comment]
Real Soon Now™.   We are cleaning up our API and coordinating across languages to get this out.  I personally expect this to be within the month.

**Comment by tmiddlet2666** [comment]
Thanks, appreciate it.
