### ISSUE TITLE
the benchmark example gives a 2 times better QPS result after add spring-boot to dependency

### ISSUE THREAD

**Issue by killjason** [grpc/grpc-java#2596]
### What version of gRPC are you using?
1.0.3
### What JVM are you using (`java -version`)?
1.8
### What did you do?
I use the bench mark code from https://github.com/grpc/grpc-java/tree/master/benchmarks
I download the code and convert it to a maven project, then run the bench mark with command:

> sudo java -jar benchmark-client.jar --address=10.200.10.17:1024 --duration=10 --channels=10 --outstanding_rpcs=40

the benchmark result is:

> Channels:                       10
Outstanding RPCs per Channel:   40
Server Payload Size:            0
Client Payload Size:            0
50%ile Latency (in micros):     6431
90%ile Latency (in micros):     12991
95%ile Latency (in micros):     16191
99%ile Latency (in micros):     23551
99.9%ile Latency (in micros):   33023
Maximum Latency (in micros):    50175
QPS:                            52874

then I add the spring-boot-starter-web dependency to the benchmark project, and re-run the bench mark:

> sudo java -jar benchmark-client-with-springboot.jar --address=10.200.10.17:1024 --duration=10 --channels=10 --outstanding_rpcs=40

the benchmark result is:

> Channels:                       10
Outstanding RPCs per Channel:   40
Server Payload Size:            0
Client Payload Size:            0
50%ile Latency (in micros):     2239
90%ile Latency (in micros):     4351
95%ile Latency (in micros):     5695
99%ile Latency (in micros):     10175
99.9%ile Latency (in micros):   16511
Maximum Latency (in micros):    28671
QPS:                            149371

### What did you expect to see?
the  QPS results of two benchmarking should be same.
### What did you see instead?
after add spring-boot dependency, it gives a 2 times better QPS result.

**Comment by killjason** [comment]
The reproduce src code:
[benchmark-server.zip](https://github.com/grpc/grpc-java/files/698528/benchmark-server.zip)
[benchmark-client.zip](https://github.com/grpc/grpc-java/files/698529/benchmark-client.zip)
[benchmark-server-with-springboot.zip](https://github.com/grpc/grpc-java/files/698531/benchmark-server-with-springboot.zip)
[benchmark-client-with-springboot.zip](https://github.com/grpc/grpc-java/files/698532/benchmark-client-with-springboot.zip)

**Comment by carl-mastrangelo** [comment]
Doubling the speed sounds a lot like you are messing with you processors clock settings unintentionally.  Is the springboot dependency possibly adding a busy loop?  I.e. something that keeps the processor spinning at 100% frequency?

If you are running on linux, you can easily tell this.  Try running `grep "MHz" /proc/cpuinfo`  while the benchmark is running.

**Comment by killjason** [comment]
@carl-mastrangelo , the cpu MHz does not change when doing benchmarking.(with or without springboot)

> grep "MHz" /proc/cpuinfo
cpu MHz		: 2099.998
cpu MHz		: 2099.998
cpu MHz		: 2099.998
cpu MHz		: 2099.998

**Comment by killjason** [comment]
I figured it out: 
the normal QPS should be 149371, the reason it goes down to 52874 is that I added logback.xml in project, if logbak.xml existed, then need to add following dependencies to avoid QPS getting down:

> <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
            <version>1.7.21</version>
            <exclusions>
                <exclusion>
	            		<groupId>org.slf4j</groupId>
	            		<artifactId>slf4j-api</artifactId>
	            </exclusion>
            </exclusions>
        </dependency>

spring-boot dependencies contains the log4j-over-slf4j dependency.

**Comment by killjason** [comment]
@carl-mastrangelo may be this can be added to the banchmark readme doc? to remind the user who involved logback.xml in the benchmark project?
I am still wondering why the logback.xml  will results in a low QPS results.

**Comment by carl-mastrangelo** [comment]
I don't understand how those dependencies affect gRPC at all.  We avoid making logging stmts whenever possible, and the benchmarks hardly use them.  (and don't use slf4f)

**Comment by killjason** [comment]
close for now.
I will post further info if there is anything new about this.
