### ISSUE TITLE
Add tests for convert non-200 HTTP status codes to GRPC codes

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#26]
The GRPC runtime should handle receiving HTTP2 responses with :status set to something other than 200. The runtime will need to map this to a GRPC status

**Comment by carl-mastrangelo** [comment]
This doesn't feel like blocker for 1.1.  I'm going to punt this to 1.2.  Feel free to move it back.

**Comment by ejona86** [comment]
This was done in #2362.
