### ISSUE TITLE
Tracking issue for TestMethodDescriptors being Experimental

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2600]

**Comment by dapengzhang0** [comment]
Deprecated in v1.8.0, and to be removed at v1.9.0

**Comment by larry-safran** [comment]
> Deprecated in v1.8.0, and to be removed at v1.9.0

This appears to either be talking about other methods that were removed.

**Comment by larry-safran** [comment]
Approved

**Comment by ejona86** [comment]
I think the comment was related to the noop methods, which were replaced by the void methods.
https://github.com/grpc/grpc-java/pull/3619
https://github.com/grpc/grpc-java/pull/3790
