### ISSUE TITLE
Limit Cipher Suites Available

### ISSUE THREAD

**Issue by jamisonhyatt** [grpc/grpc-java#2608]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.1

### What JVM are you using (`java -version`)?
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

### What did you do?
n/a

### What did you expect to see?
n/a

### What did you see instead?
n/a

I'm using  statically linked tcnative via "netty-tcnative-boringssl-static" in my dependencies.  With ServerBuilder as below....

```
ServerBuilder.forPort(config.getPort())
        .addService(healthManager.getHealthService())
        .useTransportSecurity(new File(config.getServerCertPemFile()), 
                                       new File(config.getServerCertPemKeyFile()))
        .addService(authenticationService);
```

How would I limit the cipher suites available to the TLS negotiation to a very specific subset?.  I know I can provide an SSL context to NettyChannelBuilder and NettyServerBuilder but i'm not sure I can limit the available ciphers in there (or if openSSL would even care)

**Comment by carl-mastrangelo** [comment]
I'm closing this as it isn't a gRPC issue.  You need to disable ciphers on the JRE level.  A quick search on Google suggests this:

http://stackoverflow.com/questions/18589761/restict-cipher-suites-on-jre-level

**Comment by jamisonhyatt** [comment]
Thanks.  I saw this SO answer when researching, but I have very little understanding around which parts of the TLS negotiation are being handled by the JRE versus OpenSSL.  That may even be a naive way of stating my naivety :)

**Comment by carl-mastrangelo** [comment]
It looks like you pass `CipherSuiteFilter` to the SslContextBuilder.
