### ISSUE TITLE
does one streamId(>=3) represents one RPC call in the same TCP connection?

### ISSUE THREAD

**Issue by killjason** [grpc/grpc-java#2610]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.1

### What JVM are you using (`java -version`)?
1.8

### What did you do?
Does one streamId(>=3) represents one RPC call in the same TCP connection? I mean:
one streamId only can be used for 1 time RPC call  
OR
one streamId could be used for multiple times RPC calls?

**Comment by carl-mastrangelo** [comment]
stream == call, stream ids are not reused on a connection.  

In the future, asking questions on https://groups.google.com/forum/#!forum/grpc-io  would be more appropriate.  Please submit issues only if there are problems or feature requests.

**Comment by killjason** [comment]
OK,  @carl-mastrangelo , thank you.
