### ISSUE TITLE
Put server address in ClientCall#attributes()

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-java#2613]
It would be very helpful to put the target address into `ClientCall#attributes()`. One of the use cases is the ability to access it in interceptors.

Without first class support for retries, we're using [RetryingInterceptor](https://github.com/grpc/grpc-java/pull/1570/files). We want to be able to write LB logic which in the case of failed attempt, would pick different backed on next call. There's currently no way to achieve that and ability to get information about which address is targeted in given call would solve it (the `RetryingInterceptor` would then append target address to `BACKENDS_TRIED` key in affinity attributes, on every attempt).

/cc @dapengzhang0 @zhangkun83  @kkaneda

**Comment by lukaszx0** [comment]
I'm happy to work on that once #2526 will be merged.

**Comment by lukaszx0** [comment]
I've started digging into this today and while working on it I realized that #2526 might've ship with everything we needed to convey target address to interceptors.

The [`ClientCallImpl#getAttributes`](https://github.com/grpc/grpc-java/blob/d0d2c1e7961aa28e7d0518fc07e560803309c1fa/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L415-L421) in their current form delegate to `stream` which should contain `Grpc.TRANSPORT_ATTR_REMOTE_ADDR` set in [`NettyServerHandler#handlerAdded`](https://github.com/grpc/grpc-java/blob/d0d2c1e7961aa28e7d0518fc07e560803309c1fa/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L171-L173).

I think we have everything we need. @zhangkun83 does that sound about right?

**Comment by zhangkun83** [comment]
@lukaszx0 `NettyServerHandler#handlerAdded` is on server side. What you need is the client-side counterpart of it.

**Comment by lukaszx0** [comment]
Omg, I've confused myself again with server code. Sorry, ignore my previous comment 🤦‍♂️
