### ISSUE TITLE
Context API

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#262]
Ideally it would not be grpc-specific. It would help with things like #174, but could also maybe provide cancellation support to the async stub and deadline propagation.

**Comment by ejona86** [comment]
The thinking on this for a while has been to copy [Go's Context](http://godoc.org/golang.org/x/net/context), but with some Java-specific stuff like using `ThreadLocal` for passing and use type-safe accessors (similar to what we do with Metadata). Important parts of Go's implementation are contexts are immutable and _very_ little is in the API: just cancel, deadline. The rest is via generic "values".

**Comment by louiscryan** [comment]
Will use separate issues for any future work in this area.
