### ISSUE TITLE
ServiceDescriptor constructor is error prone

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2636]
The `ServiceDescriptor(String, Collection<MethodDescriptor<?, ?>)` constructor is error prone.  Getting the generics slightly wrong results in `ServiceDescriptor(String, Object, MethodDescriptor<?, ? ...)` being invoked instead.  This can happen if the second arg is `List<MethodDescriptor<Void, Void>>` for example.

**Comment by ejona86** [comment]
Those constructors are not ExperimentalApi, so we have to address it in some way now.

**Comment by carl-mastrangelo** [comment]
Deprecated sounds appropriate.(an idle threat)

**Comment by ejona86** [comment]
The Object constructor was added since 1.0, so we can mark it as experimental now, except for any issues caused by codegen. And I do think codegen may be using one of them.

**Comment by carl-mastrangelo** [comment]
If code gen is using it, it cant be experimental.  It has either got to be removed, or deprecated.  Else it would break compat.
