### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by adityanp** [grpc/grpc-java#2638]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

Downloaded a master copy of https://github.com/grpc/grpc-java.git on 21st Jan 2017.

### What JVM are you using (`java -version`)?
javac 1.8.0_101

I am facing a similar issue described in 

https://github.com/grpc/grpc-java/issues/1189

I am unable to build. 
Build log  says

linking protoc-gen-grpc-java failed.
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status

I am using Cent OS 7

I have libStd packages installed 

[aditya@centos grpc-java]$ yum list libstdc++*
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
 * base: centos-hcm.viettelidc.com.vn
 * epel: epel.mirror.net.in
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
WandiscoSVN                                                                                                                                             55/55
Installed Packages
libstdc++.x86_64                                                                4.8.5-4.el7                                                          @anaconda
libstdc++-devel.x86_64                                                          4.8.5-4.el7                                                          @anaconda
Available Packages
libstdc++.i686                                                                  4.8.5-11.el7                                                         base     
libstdc++.x86_64                                                                4.8.5-11.el7                                                         base     
libstdc++-devel.i686                                                            4.8.5-11.el7                                                         base     
libstdc++-devel.x86_64                                                          4.8.5-11.el7                                                         base     
libstdc++-docs.x86_64                                                           4.8.5-11.el7                                                         base     
libstdc++-static.i686                                                           4.8.5-11.el7                                                         base     
libstdc++-static.x86_64                                                         4.8.5-11.el7                                                         base  

And

protoc version is "libprotoc 3.1.0"

Please help.

**Comment by ejona86** [comment]
Based on the issue you linked to #1189, try installing libstdc++-static.x86_64. We statically link as much of the binaries as possible, since we [publish them](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22protoc-gen-grpc-java%22) on Maven Central.

Since you are on x86_64, you shouldn't need to build the protoc plugin unless you are modifying grpc-java. Just download the binary from Maven Central.

**Comment by carl-mastrangelo** [comment]
I am going to close this, please reopen if you feel it is still a problem.

**Comment by SanjunLiu** [comment]
if can not find libstdc++, just installing libstdc++-static.x86_64 to fix it, that works for me.thank @ejona86 very much
