### ISSUE TITLE
Decide whether LBv2 should be kept in 1.1

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#2650]
If we do, we could provide a better (non-atomic) migration path for people (implementors) implementing `LoadBalancer`.

During 1.1, we keep the old API intact, and include the v2 API as `LoadBalancer2`. Implementors re-write their LBs with the v2 API, and migrate their customers to their v2 LB. The two versions of LB impls can coexist.

In 1.2, we replace `LoadBalancer` with `LoadBalancer2`, and keep `LoadBalancer2` as an alias to `LoadBalancer` by extending it. The old LB impls stop working. Before switching to 1.2, the implementors must have switched all their customers to the v2 API. During 1.2, they can migrate their customers to the proper `LoadBalancer` name.

In 1.3, we delete `LoadBalancer2`.

The caveat is that it increases the size of Android packages in 1.1. It shouldn't be a significant amount compared with the existing code size. We should at least calculate the exact size and note it in release notes.

If we are going to do this, we should also change the `@Internal` annotations to `@ExeprimentalApi` on the v2 APIs.

**Comment by jhspaybar** [comment]
I had asked for this and would like this very much. Our environment has hundreds of client consumers and soon hundreds or services that can be hard to coordinate an atomic switch across all of them. 

I would be okay as well with needing to opt in to an extra dependency to get this behavior if the jar size is a concern.

**Comment by zhangkun83** [comment]
We are going to try out an approach which will hopefully allow ProGuard to strip out most of the added classes. If that works, we will include it in 1.1

**Comment by zhangkun83** [comment]
Now that the concern for Android has been addressed by #2654, we will include LBv2 in 1.1. I have filed #2656 as the master issue for transitioning.
