### ISSUE TITLE
AbstractInteropTest should not depend on TestUtils

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2651]
PR #2634 accidentally added a dep from src/tests to another src/test directory, which is uncommon.  Shared test library code needs to be under a /testing/ directory in the src/java which can be reused by multiple test suites.

**Comment by zhangkun83** [comment]
The helper method must be under `io.grpc.internal` in order to access package-private method on `AbastractManagedChannelImplBuilder`. This is also unusual since currently all files of the `testing` project are under `io.grpc.internal.testing`.

**Comment by carl-mastrangelo** [comment]
An alternative would be making an "InternalManagedChannelBuilder".
