### ISSUE TITLE
about Netty initChannel

### ISSUE THREAD

**Issue by juaby** [grpc/grpc-java#2655]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.3

### What JVM are you using (`java -version`)?
1.7.0_80

### What did you do?
If possible, provide a recipe for reproducing the error.
no error

### What did you see instead?

when netty client connect netty server,  exec initChannel, and new NettyServerTransport, and new NettyServerHandler...
so in server:
1 conn -----> 1 new NettyServerTransport, and new NettyServerHandler...
2 conn -----> 2 new NettyServerTransport, and new NettyServerHandler...
......
n conn -----> n new NettyServerTransport, and new NettyServerHandler...

in mem, too many new new new ......

Do you understand what I mean?

**Comment by ejona86** [comment]
Each connection creates a NettyServerTransport. That is by design. What is the issue?

**Comment by juaby** [comment]
Too many connections, I worry about wasting memory......

**Comment by carl-mastrangelo** [comment]
@juaby what would you like to happen?

**Comment by ejona86** [comment]
There doesn't seem to be much to do here. We need a per-transport object, and the allocations are pretty core to the design.
