### ISSUE TITLE
grpc-thrift 1.1.1 has not been published to maven repo

### ISSUE THREAD

**Issue by matthewrj** [grpc/grpc-java#2681]
### What version of gRPC are you using?
1.1.1

### What did you do?
Included grpc-all 1.1.1 as a dependency in a maven project

### What did you expect to see?
grpc-all and all dependencies download from maven central

### What did you see instead?
Could not find io.grpc:grpc-thrift:1.1.1.
Searched in the following locations:
         https://repo1.maven.org/maven2/io/grpc/grpc-thrift/1.1.1/grpc-thrift-1.1.1.pom
         https://repo1.maven.org/maven2/io/grpc/grpc-thrift/1.1.1/grpc-thrift-1.1.1.jar

**Comment by carl-mastrangelo** [comment]
This was done intentionally: https://github.com/grpc/grpc-java/commit/4988d8be6b47eb65b3d2c3628dba50c37c991ce6

**Comment by matthewrj** [comment]
The grpc-all pom uses it as a dependency.

On Wed, 1 Feb 2017, 13:27 Carl Mastrangelo <notifications@github.com> wrote:

This was done intentionally: 4988d8b
<https://github.com/grpc/grpc-java/commit/4988d8be6b47eb65b3d2c3628dba50c37c991ce6>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/grpc/grpc-java/issues/2681#issuecomment-276537694>, or mute
the thread

**Comment by dapengzhang0** [comment]
seems need push an empty artifact to 
https://repo1.maven.org/maven2/io/grpc/grpc-thrift/1.1.1/grpc-thrift-1.1.1.pom

**Comment by kuroneko25** [comment]
Are we going to fix this soon?

**Comment by carl-mastrangelo** [comment]
@ejona86 does any of our code depend on grpc-all? i.e. is it as simple as removing thrift from 
```
dependencies {
    compile subprojects
}
```

**Comment by carl-mastrangelo** [comment]
This has been fixed.  Please depend on 1.1.2

**Comment by febzhang** [comment]
1.1.2 not fixed yet.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':thrift:compileClasspath'.
> Could not find io.grpc:grpc-thrift:1.1.2.
  Searched in the following locations:
      https://repo1.maven.org/maven2/io/grpc/grpc-thrift/1.1.2/grpc-thrift-1.1.2.pom
      https://repo1.maven.org/maven2/io/grpc/grpc-thrift/1.1.2/grpc-thrift-1.1.2.jar
      file:/home/dev/.m2/repository/io/grpc/grpc-thrift/1.1.2/grpc-thrift-1.1.2.pom
      file:/home/dev/.m2/repository/io/grpc/grpc-thrift/1.1.2/grpc-thrift-1.1.2.jar
  Required by:
      examples:thrift:unspecified
```
