### ISSUE TITLE
Reflection service can return inconsistent results

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2689]
The service currently calls `serverReflectionIndex.updateMutableIndexIfNecessary()` after receiving each request in the stream. This is not only needless processing, but actually against the point. The reflection API is streaming so that each stream can be independently consistent. This is normally important when a load balancer may direct each request to a different backend. However, in this case it could also handle the mutable nature of the services.

Although `serverReflectionIndex` is `volatile`, it is not assigned in a thread-unsafe way; it could be non-`volatile`. However, I would suggest making `ServerReflectionIndex` immutable and create a new/derivative each time the mutable index is detected to change (probably using locking instead of volatile). I would then suggest checking for updates to the mutable index at the beginning of each RPC (`serverReflectionInfo()`) and then copying the current `ServerReflectionIndex` reference to the `ProtoReflectionStreamObserver`.

**Comment by ericgribkoff** [comment]
I spoke with @dklempner about this. As you're suggesting here, the right thing to do seems to be to take a snapshot of the protobufs at the start of each stream. From a quick chat with @y-zeng, this should also be sufficient to avoid blowing up the grpc_cli tool. There is potentially some wiggle room to return an up-to-date list of the services exported, as long as the view of the protos remains consistent.

It may also be useful, at some future point, to consider adding a mechanism in the API for the service to indicate to clients that the data coming over the stream has become stale - but that's beyond the scope here.

**Comment by ericgribkoff** [comment]
Fixed by https://github.com/grpc/grpc-java/pull/2767
