### ISSUE TITLE
Memory allocation not decreasing as load decreases or moves to zero

### ISSUE THREAD

**Issue by jamisonhyatt** [grpc/grpc-java#2698]
I started down this path because I found the memory leak in 1.0.1 (fixed in 1.0.3) through load testing, but I see something that doesn't appear to behave as it should in 1.0.3.  The memory footprint increases relative to the amount of concurrent requests, but it doesn't appear to ever decrease when load decreases or goes to zero.  This may be expected, but I thought I would bring it up here.

### What version of gRPC are you using?
1.0.3

### What JVM are you using (`java -version`)?
 1.8.0_60-b27

### What did you do?
If possible, provide a recipe for reproducing the error.
Many goroutines (hundreds, thousands) to create concurrent requests in a streaming server.
1. clone the example 1.0.3 branch `git clone -b v1.0.3 https://github.com/grpc/grpc-java.git`
1. navigate to the examples dir
1. build it `./gradlew installDist`
1. run routeguide server `./build/install/examples/bin/route-guide-server`
1. Load test it with 1000 concurrent requests, 5 loops each, for 1 minute. repeat 5 times.
    1. I built a [small go utility](https://github.com/jamisonhyatt/grpc_load_test) to do exactly this, just build and run with `-c 1000` 
1. wait 3-5 minutes for JVM garbage cleanup. 
1. Memory usage will stay around 2GB.
 

### What did you expect to see?
Memory usage increases relative to the number of concurrent requests, and decreases (eventually)  as the load goes to zero, or is completely zero.

### What did you see instead?
Memory usage goes up as expected when handling thousands of concurrent requests, but never decreases as load moves to zero.

**Comment by carl-mastrangelo** [comment]
Will the JVM even GC if it isn't under pressure?  Can you provide the JVM flags you are using?  (`-XX:+PrintFlagsFinal`)

**Comment by luoguohao** [comment]
i also trapped in such situation.

**Comment by ejona86** [comment]
Java won't GC on idle, if you just wait some time. Even under some pressure it may not do a full GC.

There are Netty buffer pools being used. They can increase in size during high load, and may stay large even when load decreases. The buffers are generally direct, so they are limited by `-XX:MaxDirectMemorySize`, and so are frequently limited to less than 2 GB. This may mean that the memory usage is not (entirely) caused by the buffer pool.

**Comment by jamisonhyatt** [comment]
1. I improved the situation using G1 GC.  Whether that has performance implications has yet to be seen.  I was previously using the default JVM settings for 1.8 on OSX. I won't paste them all, cause I don't think it is necessary.

1.  While I'm aware that GC algorithm is complex and nuanced, in this case the memory footprint appears to be specifically tied to the maximum concurrent connections which won't ever "feel pressure" again until a "new maximum" occurs, meaning it only goes 1 way (up.)   In other words, the memory footprint doesn't appear to decrease under any loads after high concurrent connections.  If 1000 concurrent connections bring it to 2GB, I can run it for 2-3 hours after that at 100, 200, 500 (etc) concurrent connections, and the memory usage stays at 2GB.    

I agree that it does seem to be related to netty direct memory usage, because the GC graphs look sawtoothed how one would expect.

I'm okay if you want to close this issue if you don't believe it's tied to grpc, I just thought I'd bring the behavior i'm seeing to your attention.

**Comment by ejona86** [comment]
The GC graphs that you see the sawtooth: what peaks do you see? Also, I think the "heap size" in things like visualvm gives the GC heap, not the total heap. So if the "heap size" isn't decreasing, then I wouldn't expect the externally-visible memory usage to decrease.

If the GC graph shows a small percentage of the external memory usage you see, then I would believe that is direct memory.

**Comment by jamisonhyatt** [comment]
It's the latter, the GC graph shows a much smaller percentage of the actual memory usages listed by the pid.

**Comment by luoguohao** [comment]
I believe that you use lots of direct memory ,and the direct memory only reclaimed  when gc or the maxDirect MemorySize has exceeded ,so what you see is that the heap size with a low capacity will not trigger gc . So I believe that the Resident memory size will drop down slowly after some gc triggered in common situations .
That's my opinion ，maybe incorrect .

**Comment by ejona86** [comment]
Seems like this was solved, in that it was direct memory use. Netty does have [some configuration](https://github.com/netty/netty/blob/e329ca1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L53-L117) knobs (`-Dio.netty.allocator.*`) to configure the behavior.

If a machine has 20 processor threads, it could easily use 2 GB:
8192 (page size) * 2^11 (max order) * 3 (tiny, small, normal) * 40 (numDirectArenas: 2 * number of processor threads) =  2 GB

The easiest ways of reducing that seem to be reducing the numDirectArenas (which may increase contention across threads) or maxOrder (which reduces the allocation chunk size).
