### ISSUE TITLE
Protoc throws error=7, Argument list too long

### ISSUE THREAD

**Issue by amalj** [grpc/grpc-java#2713]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.3

### What JVM are you using (`java -version`)?
1.8.0_66, vendor: Oracle Corporation

### What did you do?
I tried to compile 1886 proto files using maven. 

Getting the following exception

[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project i3grpc-client: An error occurred while invoking protoc. Error while executing process. Cannot run program "target/protoc-plugins/protoc-3.0.2-osx-x86_64.exe": error=7, Argument list too long -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project i3grpc-client: An error occurred while invoking protoc.

Caused by: java.io.IOException: Cannot run program "/target/protoc-plugins/protoc-3.0.2-osx-x86_64.exe": error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:655)
	... 27 more
Caused by: java.io.IOException: error=7, Argument list too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 29 more

**Comment by carl-mastrangelo** [comment]
That is definitely a case we didn't think of.   Can I ask why you are trying to compile so many proto files in a single shot?

**Comment by amalj** [comment]
The project in which I am working is a big system which has millions of users and supports thousands of functionalities. 
Earlier we used to use serialized POJO objects. We are migrating to Protocol Buffers and grpc. 
So there were 1886 POJO's  earlier. Now need to convert this to Protocol Buffer schema. This part it done. Now there are 1886 Protocol Buffer schema files. 

Compiling this throws the exception. Do you have any suggestions on how to make this 1886 Protocol Buffer schema files compile ? I thought of batch processing but feels that its not a good solution and makes maintenance difficult.

**Comment by carl-mastrangelo** [comment]
If they are all part of the same proto package, I would concatenate them.  It is rare to see that many proto files, especially in one directory.  Usually you have anywhere from 1 to 10, even for an enormous project.

**Comment by amalj** [comment]
There are around 70 packages. As you mentioned, will try to concatenate them. Certain packages has around 100 protocol files.  Concatenating is a challenge. Still will try.
One other solution is changing kern.argmax or ARG_MAX parameters. But these are Read Only.

**Comment by amalj** [comment]
Refactored and issue is fixed
