### ISSUE TITLE
TLS handshake failures on android

### ISSUE THREAD

**Issue by MacoChris** [grpc/grpc-java#2720]
### What version of gRPC are you using?

grpc-java 1.1.2

grpc c++ build against OpenSSL 1.0.2k

### What JVM are you using

Android

### What did you do?

I'm creating a channel using the following code:

```java
OkHttpChannelBuilder.forAddress(host, port)
        .connectionSpec(ConnectionSpec.MODERN_TLS)
        .sslSocketFactory(context.getSocketFactory())
        .build();
```

where `context` is generated by:

```java
KeyStore trust_store = KeyStore.getInstance(KeyStore.getDefaultType());
trust_store.load(null);

InputStream input_stream = Cloud.class.getResourceAsStream("resources/EC_CA.crt");

CertificateFactory cert_factory = CertificateFactory.getInstance("X.509");
Certificate cert = cert_factory.generateCertificate(input_stream);
trust_store.setCertificateEntry("cert", cert);

TrustManagerFactory trust_manager_factory = TrustManagerFactory.getInstance(
        TrustManagerFactory.getDefaultAlgorithm());
trust_manager_factory.init(trust_store);
TrustManager[] trust_manager = trust_manager_factory.getTrustManagers();

SSLContext tlsContext = SSLContext.getInstance("TLSv1.2");
tlsContext.init(null, trust_manager, null);

return tlsContext;
```

Where `"resources/EC_CA.crt"` is packaged with our application, and is successfully used successfully for our current internal library.

When the client performs the TLS handshake with the `c++` server, it gets up to the point where it sends the TLS client key exchange/change cipher spec, then the server complains with the line:

```
Handshaking failed: {"created":"@1486967107.222496318","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/transport/security_connector.c","file_line":491}
```

Interestingly, this only occurs on android devices after running ```com.google.android.gms.security.ProviderInstaller.installIfNeeded(getApplicationContext());```. If we don't use play services we see different behaviour depending on API version. Our level 19 and below devices fail out since they lack the devices. The level 21 and above devices successfully connect and communicate with the server, though.

The python grpc implementation does not cause the above issue.

**Comment by carl-mastrangelo** [comment]
The OkHTTP Protocol negotiator has some logic to pick the right ALPN entry point based on the Android API level.  Level 21 is 5.0, and 19 is 4.4.4:

```

      // Decide which TLS Extension (APLN and NPN) we will use, follow the rules:
      // 1. If Google Play Services Security Provider is installed, use both
      // 2. If on Android 5.0 or later, use both, else
      // 3. If on Android 4.1 or later, use NPN, else
      // 4. Fail.
      // TODO(madongfly): Logging.

      // Check if Google Play Services Security Provider is installed.
      Provider provider = Security.getProvider("GmsCore_OpenSSL");
      if (provider != null) {
        tlsExtensionType = TlsExtensionType.ALPN_AND_NPN;
      }

      // Check if on Android 5.0 or later.
      if (tlsExtensionType == null) {
        try {
          Class.forName("android.net.Network"); // Arbitrary class added in Android 5.0.
          tlsExtensionType = TlsExtensionType.ALPN_AND_NPN;
        } catch (ClassNotFoundException ignored) {
          // making checkstyle happy.
        }
      }

      // Check if on Android 4.1 or later.
      if (tlsExtensionType == null) {
        try {
          Class.forName("android.app.ActivityOptions"); // Arbitrary class added in Android 4.1.
          tlsExtensionType = TlsExtensionType.NPN;
        } catch (ClassNotFoundException ignored) {
          // making checkstyle happy.
        }
      }
    ```

That class is light on logging, so something wrong could be happening and not notifying you.  It seems like detection logic may be at fault here.

**Comment by ejona86** [comment]
Hmm... we always suggest using `ProviderInstaller`. It is more up-to-date and frequently fixes important bug fixes that could cause crashes otherwise. It's strange that calling `ProviderInstaller.installIfNeeded()` breaks newer API versions.

Are creating `context` after `installIfNeeded`? If you create it before, then it won't use the provider.

Is this being done on an emulator? I have seen issues with emulators before because they can have old versions of Google Play Services.

Is the problem fixed if you create a separate `context` for gRPC? Some previous versions of Google Play Services had a bug which could break connections when mixing ALPN and non-ALPN connections, like if you used that context for normal HTTP/1.1 in addition to gRPC.

**Comment by MacoChris** [comment]
Stepped through the negotiator's set up, it's choosing the correct `TlsExtensionType` value for each respective device.

---

> It's strange that calling ProviderInstaller.installIfNeeded() breaks newer API versions.

It's breaking every version -- 19 and below failed with a different error before. 

> Is this being done on an emulator? I have seen issues with emulators before because they can have old versions of Google Play Services.

We're testing on:

Pixel XL on Android 7.1.1, 
Samsung S4 on Anrdoid 4.4.2,
Moto G 2nd Gen on Android 6.0,
And various emulators. They're all seeing the same behaviour based on API Level / play services installation.

> Is the problem fixed if you create a separate context for gRPC?

Changed code over to do this, and seeing no changes in behaviour except for the server side's log from the API level 19 devices without play services. It's reporting:

```
E0214 10:24:04.470509200   15321 chttp2_server.c:123]        Handshaking failed: {"created":"@1487031844.470442976","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/transport/security_connector.c","file_line":491}
E0214 10:24:07.551316120   15321 ssl_transport_security.c:947] Handshake failed with fatal error SSL_ERROR_SSL: error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number.
E0214 10:24:07.551475897   15321 chttp2_server.c:123]        Handshaking failed: {"created":"@1487031847.551377200","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.c","file_line":274,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
```

and wireshark is showing that every second connection attempt is attempted using TLS1.0, which gets disconnected immediately. The other connection attempts are kicked off as before, as if running under play services.

---

I'll try to make a minimal reproduction case for both c++ server and java clients, see if it's some odd compatibility issue with the version of OpenSSL we're running, or something totally unrelated in our existing java code.

**Comment by MacoChris** [comment]
After going through reproduction cases I think I've tracked it down to a configuration issue on the c++ server interacting badly with the play-services SSL provider. It's a bit of a goose-chase, but I'm fairly certain the referenced issue is the underlying problem we've hit.

Thanks for your time
