### ISSUE TITLE
How do I call grpc-java server from golang client

### ISSUE THREAD

**Issue by palaiyacw** [grpc/grpc-java#2724]
I have generated the following method from the given `proto` file. As it is mentioned here it uses the combination of `LowerCase of PackageName` and `ServiceName` defined in the proto file.

```
    io.grpc.MethodDescriptor.MethodType.UNARY,
                      generateFullMethodName(
                          "helloworld.Greeter", "SayHello") 
```

to generate the full method name. Now the problem is the same file is being used to generate the client code in `GoLang`. Which take the package name as it is. And it throws the following exception while calling the same method from client : 

```
**Error from GoLang client :**

    2017/02/14 19:16:44 Error occurend : %!(EXTRA *grpc.rpcError=rpc error: code = 12 desc = Method not found: HelloWorld.Greeter/SayHello) <nil>
```

 So, how to generate the full method name as it is in grpc-java  as mentioned in proto file?
 

   ```
public static final io.grpc.MethodDescriptor<io.grpc.examples.helloworld.HelloRequest,
              io.grpc.examples.helloworld.HelloReply> METHOD_SAY_HELLO =
              io.grpc.MethodDescriptor.create(
                  io.grpc.MethodDescriptor.MethodType.UNARY,
                  generateFullMethodName(
                      "helloworld.Greeter", "SayHello"),
                  io.grpc.protobuf.ProtoUtils.marshaller(io.grpc.examples.helloworld.HelloRequest.getDefaultInstance()),
                  io.grpc.protobuf.ProtoUtils.marshaller(io.grpc.examples.helloworld.HelloReply.getDefaultInstance()));
```

**Proto file :**

     syntax = "proto3";
  
    option java_package = "io.grpc.examples.helloworld";
    
    package HelloWorld;
    
    // The greeting service definition.
    service Greeter {
      // Sends a greeting
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }
    
    // The request message containing the user's name.
    message HelloRequest {
      string name = 1;
    }
    
    // The response message containing the greetings
    message HelloReply {
      string message = 1;
    }
```

**Comment by ejona86** [comment]
I'm not sure I understand. The code snippets you provided don't seem to match what I see from the generated code.

I modified examples/src/main/proto/helloworld.proto to have `package Helloworld;`. I saw this output:
```
  public static final io.grpc.MethodDescriptor<io.grpc.examples.helloworld.HelloRequest,
      io.grpc.examples.helloworld.HelloReply> METHOD_SAY_HELLO =
      io.grpc.MethodDescriptor.create(
          io.grpc.MethodDescriptor.MethodType.UNARY,
          generateFullMethodName(
              "HelloWorld.Greeter", "SayHello"),
          io.grpc.protobuf.ProtoUtils.marshaller(io.grpc.examples.helloworld.HelloRequest.getDefaultInstance()),
          io.grpc.protobuf.ProtoUtils.marshaller(io.grpc.examples.helloworld.HelloReply.getDefaultInstance()));
```

That uses `"HelloWorld.Greeter"` for the service name which seems like it would agree with the Go client. Why do your code snippets have lower-case `helloworld.Greeter`?

**Comment by palaiyacw** [comment]
@ejona86  Thanks Eric. My mistake i think :)
