### ISSUE TITLE
dev: Jetty ALPN/NPN has not been properly configured when running tests in IntelliJ

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-java#2728]
Some of the tests depend on jetty alpn agent for TLS stuff which is loaded by gradle for whole test suite but not if you're running a single test in for example an IDE.

I figured out how to hack it:

- Go to `Edit Configurations` for your test in IJ
- Add `-ea -javaagent:/Users/lukasz/.gradle/caches/modules-2/files-2.1/org.mortbay.jetty.alpn/jetty-alpn-agent/2.0.3/89e34338e9214ca753b33f23ccf80a4b5b861bb7/jetty-alpn-agent-2.0.3.jar` in `VM options` field (this assumes jetty-alpn-agent is already cached by gradle).

@ejona86 I wonder if there's more sane and straightforward way to do this?

**Comment by ejona86** [comment]
I wouldn't expect so. Except getting rid of jetty-alpn for the OkHttp tests, via http://conscrypt.org/. Conscrypt has classically been used on Android, but there's been some work to use it on the normal JDK with pre-compiled binaries and the like. I don't know the current status though. We're actually interested in using Conscrypt as an alternative to tcnative as well.

**Comment by dapengzhang0** [comment]
My hack is (using IDEA):
1. Settings -> Build Tools -> Gradle -> Runner -> select Gradle Test Runner
2. View -> Tool Windows -> Gradle -> Edit Run Configuration -> Defaults -> JUnit -> Before lauch -> `+` -> Run Gradle task, enter the task in the build.gradle that sets the javaagent. 

Sept 1 must be taken, otherwise by the default JUnit Test Runner running a single test in IDE will trigger all the tests.

**Comment by lukaszx0** [comment]
> I wouldn't expect so. Except getting rid of jetty-alpn for the OkHttp tests, via http://conscrypt.org/. Conscrypt has classically been used on Android, but there's been some work to use it on the normal JDK with pre-compiled binaries and the like. I don't know the current status though. We're actually interested in using Conscrypt as an alternative to tcnative as well.

Was rather asking if there's more sane way to run tests, not to get rid of jetty-alpn. I was suspecting that there must be an easier way with some Gradle setup - thanks @dapengzhang0 !

For posterity, there's already an [issue for conscrypt ](https://github.com/grpc/grpc-java/issues/1927) integration.

**Comment by qiang-dai** [comment]
This is my way:
1. Edit catalina.sh
`/usr/local/Cellar/tomcat/8.5.3/libexec/bin/catalina.sh`
2. At line 103, add the following
`CATALINA_OPTS="-javaagent:/Library/Tomcat/lib/jetty-alpn-agent-2.0.6.jar"`
3. Restart tomcat
`../bin/shutdown.sh
../bin/startup.sh`
