### ISSUE TITLE
how to generate Grpc class with gradle?

### ISSUE THREAD

**Issue by jeffreyji666** [grpc/grpc-java#273]
grpc example use gradle-plugin-protobuf to generate Grpc class with the following config:

>protobufCodeGenPlugins = ["java_plugin:$javaPluginPath"]
generateProto.dependsOn ':grpc-compiler:java_pluginExecutable'

but this doesn't succeed when I build with gradle, it prompts:
>Could not determine the dependencies of task ':generateProto'.

how to reference grpc complier if I create a stand alone java project with gradle?

**Comment by ejona86** [comment]
We are in the process of making nice plugins that will make this easier, as part of https://github.com/grpc/grpc-java/issues/71.

For your issue, just remove the dependsOn. It is only necessary since the protoc plugin is in the same project.
