### ISSUE TITLE
gradle build failure in proxy environment

### ISSUE THREAD

**Issue by Sudip7** [grpc/grpc-java#2742]
Please answer these questions before submitting your issue.

### What JVM are you using (`java -version`)? : java version "1.8.0_72"

**Forked the master branch** and then tried to build some example codes using instructions given in quick start guide. I am not sure whether I have to install protobuf or any other thing to the local machine. 

I am using windows 7 machine under corporate proxy. Navigated to grpc-java\examples>

then 

gradlew.bat installDist

Expected: Build success

Found: FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find io.grpc:grpc-netty:1.2.0-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.2.0-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.2.0-SNAPSHOT/grpc-netty-1.2.0-SNAPSHOT.pom
      https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.2.0-SNAPSHOT/grpc-netty-1.2.0-SNAPSHOT.jar
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-netty/1.2.0-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-netty/1.2.0-SNAPSHOT/grpc-netty-1.2.0-SNAPSHOT.pom
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-netty/1.2.0-SNAPSHOT/grpc-netty-1.2.0-SNAPSHOT.jar
  Required by:
      project :
> Could not find io.grpc:grpc-protobuf:1.2.0-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.2.0-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.2.0-SNAPSHOT/grpc-protobuf-1.2.0-SNAPSHOT.pom
      https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.2.0-SNAPSHOT/grpc-protobuf-1.2.0-SNAPSHOT.jar
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-protobuf/1.2.0-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-protobuf/1.2.0-SNAPSHOT/grpc-protobuf-1.2.0-SNAPSHOT.pom
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-protobuf/1.2.0-SNAPSHOT/grpc-protobuf-1.2.0-SNAPSHOT.jar
  Required by:
      project :
> Could not find io.grpc:grpc-stub:1.2.0-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.2.0-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.2.0-SNAPSHOT/grpc-stub-1.2.0-SNAPSHOT.pom
      https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.2.0-SNAPSHOT/grpc-stub-1.2.0-SNAPSHOT.jar
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-stub/1.2.0-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-stub/1.2.0-SNAPSHOT/grpc-stub-1.2.0-SNAPSHOT.pom
      file:/C:/Users/nayaksu/.m2/repository/io/grpc/grpc-stub/1.2.0-SNAPSHOT/grpc-stub-1.2.0-SNAPSHOT.jar
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Need assistance for this.

**Comment by dapengzhang0** [comment]
`*-SNAPSHOT` is not in the maven central repo, it should haven been in your local maven repo, if you had built the grpc library by yourself first. Please refer to the first sentence of  [examples/README.md](/grpc/grpc-java/blob/master/examples/README.md)

**Comment by zhangkun83** [comment]
If you do want to build the snapshot version, you have to go through all the steps from [COMPILING.md](/grpc/grpc-java/blob/master/COMPILING.md) to compile protobuf, setup the C++ compilation environments and `gradlew install`.

It's much easier for you to check out a tagged release, e.g., `v1.1.2`, and build examples directly.
