### ISSUE TITLE
Rename java_plugin to protoc-gen-grpc-java

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#276]
This follows [a naming convention](https://github.com/google/protobuf/blob/61477681710871dab2a5832d0d6324aa9b7d7867/src/google/protobuf/compiler/plugin.h#L45) that allows just placing it in PATH and having protoc discover it.

**Comment by zhangkun83** [comment]
I cannot rename the compilation target from ``java_plugin`` to ``protoc-gen-grpc-java``, because the latter is not a valid identifier. I think what we really care is the published artifact, which is currently named ``grpc-compiler``.

**Comment by zhangkun83** [comment]
No, the artifact name doesn't really matter either, because it has the ``<version>-<classifier>`` suffix that is not part of the convention. However, ``protoc-gen-grpc-java`` is still preferable to ``grpc-compiler``.

**Comment by ejona86** [comment]
The artifact name can be something else, but java_plugin isn't the current artifact name either.
