### ISSUE TITLE
Java benchmark driver spams logs

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2789]
Looking at a recent run: https://grpc-testing.appspot.com/view/Performance/job/gRPC_performance_experiment/3856/consoleText

By lines of output, Java is causing 79% _just_ with PrintFlagsFinal. It seems we should [remove the argument](https://github.com/grpc/grpc-java/blob/v1.1.2/benchmarks/build.gradle#L59) or figure out a less spammy solution.

**Comment by carl-mastrangelo** [comment]
Is this causing an issue?  Those flags are relevant in the case of problems, but not useful when working right.

**Comment by ejona86** [comment]
It is causing massive logspam making the logs extremely difficult to use for diagnosing actual issues. When I was saying 79% of lines, that was of total lines across all languages, client+server.
