### ISSUE TITLE
Run examples without console and dependencies

### ISSUE THREAD

**Issue by DVWolfio** [grpc/grpc-java#2800]
Can i use gRPC without some grandle dependencies, and how?
I just want to see how work server and client from https://github.com/grpc/grpc-java/tree/master/examples/src/test/java/io/grpc/examples/helloworld but i can not do it, because i can not find some class-files (import io.grpc.stub.StreamObserver; - for example)

May be is there some description for run examples without consoles?

**Comment by carl-mastrangelo** [comment]
How are you building the example?

**Comment by dapengzhang0** [comment]
before running the examples in the master branch you need run `../gradlew install` to build the gRPC library (the latest-version-SNAPSHOT.jar files) in your local maven repo. For release branches, the gRPC library (release version jars) are in the maven central repo, so you can build examples with maven only.

**Comment by DVWolfio** [comment]
how can i do that? 
Sorry, i am noob. Can you tell more details about it step by step?

**Comment by dapengzhang0** [comment]
@DVWolfio what build tool do you use to manage dependent library? maven?

**Comment by DVWolfio** [comment]
I use IDE Intellij Idea, which can support gradle dependencies, but when i tried do import all that project, IDE said "Connection reset". May be it caused of my proxy, i don't know exact (checking connection in IDE is ok)

And i decided just get only sources (.java) from ../tree/master/examples/src/test/java/io/grpc/examples/helloworld.
But for run that examples i have no another classes. Where i can get it?

**Comment by dapengzhang0** [comment]
@DVWolfio so you are trying to run examples in the master branch. Just follow the steps in the readme of
https://github.com/grpc/grpc-java/tree/master/examples
The first paragraph of it can not be ignored.

**Comment by ejona86** [comment]
@DVWolfio, is there a reason you aren't checking out a release tag? I'd suggest `git checkout v1.1.2`. Both Maven and Gradle should work without trouble there (and their integrations in IDEs). If you are copying the .java files manually, you're going to have a rough time because you'll have to generate code using protoc manually.

**Comment by DVWolfio** [comment]
Excuse me, i installed gradle, and run it, but i dont understand what have i do there and for what ..
Guys, i understand that you are gods of development, but, pls, help me to understand that description:
Http://www.grpc.io/docs/quickstart/java.html

It is said that i must download a copy of examples from Github, but i dont understand, i must do that in gradle console? 

`$ # Clone the repository at the latest release to get the example code:
$ git clone -b v1.0.3 https://github.com/grpc/grpc-java
$ # Navigate to the Java examples:
$ cd grpc-java/examples
`

Or have i must use Linux Console? and if that write, then what have i do, if i work on Windows?
Or is it some another console?

May be, have you some videos with examples for dummies, where all description step by step? Or some forum?

Excuse me again.

**Comment by DVWolfio** [comment]
Hello.
Excuse me for long pause, i don't have enough time for this proj.
I installed console, and tried all steps in [instruction ](http://www.grpc.io/docs/quickstart/java.html)

When i do:
> gradlew installDist

i get error:
> F:\Ds\grpc-java-1.1.x\grpc-java-1.1.x\examples>gradlew installDist
> :extractIncludeProto FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all dependencies for configuration ':compile'.
> \> Could not find io.grpc:grpc-netty:1.1.3-SNAPSHOT.
>   Searched in the following locations:
>       https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.1.3-SNAPSHOT/maven-metadata.xml
>       https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.1.3-SNAPSHOT/grpc-netty-1.1.3-SNAPSHOT.pom
>       https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.1.3-SNAPSHOT/grpc-netty-1.1.3-SNAPSHOT.jar
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-netty/1.1.3-SNAPSHOT/maven-metadata.xml
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-netty/1.1.3-SNAPSHOT/grpc-netty-1.1.3-SNAPSHOT.pom
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-netty/1.1.3-SNAPSHOT/grpc-netty-1.1.3-SNAPSHOT.jar
>   Required by:
>       project :
> \> Could not find io.grpc:grpc-protobuf:1.1.3-SNAPSHOT.
>   Searched in the following locations:
>       https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.1.3-SNAPSHOT/maven-metadata.xml
>       https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.1.3-SNAPSHOT/grpc-protobuf-1.1.3-SNAPSHOT.pom
>       https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.1.3-SNAPSHOT/grpc-protobuf-1.1.3-SNAPSHOT.jar
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-protobuf/1.1.3-SNAPSHOT/maven-metadata.xml
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-protobuf/1.1.3-SNAPSHOT/grpc-protobuf-1.1.3-SNAPSHOT.pom
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-protobuf/1.1.3-SNAPSHOT/grpc-protobuf-1.1.3-SNAPSHOT.jar
>   Required by:
>       project :
> \> Could not find io.grpc:grpc-stub:1.1.3-SNAPSHOT.
>   Searched in the following locations:
>       https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.1.3-SNAPSHOT/maven-metadata.xml
>       https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.1.3-SNAPSHOT/grpc-stub-1.1.3-SNAPSHOT.pom
>       https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.1.3-SNAPSHOT/grpc-stub-1.1.3-SNAPSHOT.jar
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-stub/1.1.3-SNAPSHOT/maven-metadata.xml
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-stub/1.1.3-SNAPSHOT/grpc-stub-1.1.3-SNAPSHOT.pom
>       file:/C:/Users/─ьшЄЁшщ/.m2/repository/io/grpc/grpc-stub/1.1.3-SNAPSHOT/grpc-stub-1.1.3-SNAPSHOT.jar
>   Required by:
>       project :
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 1.965 secs
> 

I used Windows cmd.
what can i do for solve this problem? I used version 1.1.x

**Comment by ejona86** [comment]
The steps are almost identical on Windows, but yes, they were more assuming a Linux console.

The -SNAPSHOT is because you aren't on a release version. You can run `git checkout v1.2.0` to get to the 1.2.0 release. If you followed the steps on the [tutorial](http://www.grpc.io/docs/tutorials/basic/java.html), then the `-b v1.2.0` in the git clone should have done that for you.

You may have an easier time downloading a ZIP of the [v1.2.0 release](https://github.com/grpc/grpc-java/releases/tag/v1.2.0). It can be seen under "Downloads" for a release. This is a direct link for the zip of v1.2.0: https://github.com/grpc/grpc-java/archive/v1.2.0.zip .

**Comment by ejona86** [comment]
And I see what went wrong. You checked out v1.1.x, which is still a branch. If you do `git checkout v1.1.2` then it will checkout the latest release of v1.1.x.
