### ISSUE TITLE
Inner class unit tests in GrpcServerRuleTest look so weird

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#2808]
Should make the inner classes top level classes, and also add `@RunWith(Junit4.class)`

**Comment by ejona86** [comment]
We may be able to set [`scanForTestClasses = false`](https://docs.gradle.org/3.5/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:scanForTestClasses) to prevent this from reoccuring.
