### ISSUE TITLE
Calls.asyncServerStreamingCall requests only one response

### ISSUE THREAD

**Issue by wrwg** [grpc/grpc-java#281]
The method Calls.asyncServerStreamingCall requests only 1 response from the underlying call. The documentation for request(N) states that a call will not deliver more than N responses, so if Call implementations would implement this contract, the resulting server stream would never contain more than one element.

**Comment by nmittler** [comment]
Right, `request(n)` is to provide application-level flow control. The application gets to choose how many messages it wants to receive at once. When it wants to receive more, it calls `request(n)` again. We do this automatically in the generated stubs.

**Comment by ejona86** [comment]
In the async stub we request another message when delivering a message:
https://github.com/grpc/grpc-java/blob/2cad9e60006f50f2dff3c942e68e2a1b1895019d/stub/src/main/java/io/grpc/stub/Calls.java#L276

**Comment by wrwg** [comment]
The semantics if request(n) seems to me rather unclear. Talking with Louis
and looking at the doc comment, it appeared to me it rather represents the
total no of responses, and not to "request n more messages to send". Can
this be please clarified?

If it actually would mean "request n more messages",
Calls.asyncServerStreamingCall can't work like its today, because the call
is hidden inside the method, and an application cannot call 'request(n)'
from the outside.

**Comment by ejona86** [comment]
On Wed, Apr 8, 2015 at 4:04 PM, Wolfgang Grieskamp <notifications@github.com
> wrote:

> The semantics if request(n) seems to me rather unclear. Talking with Louis
> and looking at the doc comment, it appeared to me it rather represents the
> total no of responses, and not to "request n more messages to send". Can
> this be please clarified?
>

It requests the number of responses, at the moment, to be delivered. What
part is unclear in the documentation
<https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/Call.java#L117>
?

If it actually would mean "request n more messages",
> Calls.asyncServerStreamingCall can't work like its today, because the call
> is hidden inside the method, and an application cannot call 'request(n)'
> from the outside.
>

But it does work today.

We request(1) as soon as the call starts. As soon as that requested message
is delivered to StreamObserver.onValue(), then we call request(1) again,
which allows onValue() to be called again. Rinse and repeat for each
message. Eventually there aren't any more messages.

**Comment by wrwg** [comment]
The documentation states: "Requests up to the given number of messages from
the call to be delivered to {@link Listener#onPayload(Object)}. No
additional messages will be delivered."

That's rather ambiguous to me, in particular in an asynchronous programming
model. It doesn't say that you can call it again, whether its accumulating
(e.g. is request(N) && request(M) is the same as request(N+M)), and what
other contracts are related to this. In fact, I had a chat with one of the
original authors of this code and after that my interpretation was that it
means "don't send me more than N messages" instead "send me the next N
messages", which demonstrates the ambiguity.

If it actually means "send me the next N messages", its across with the
philosophy of the stream-observer pattern (Rx), in which data is pushed and
not pulled. It basically makes the object model less suitable for
composition, since as soon as you go up in abstraction layers (e.g. outside
of Calls methods), you lose access to it.

Flow control in the stream-observe pattern should be done instead by
observer blocking, which is compositional over abstraction layers.

On Wed, Apr 8, 2015 at 4:12 PM, Eric Anderson <notifications@github.com>
wrote:

> On Wed, Apr 8, 2015 at 4:04 PM, Wolfgang Grieskamp <
> notifications@github.com
>
> If it actually would mean "request n more messages",
> > Calls.asyncServerStreamingCall can't work like its today, because the
> call
> > is hidden inside the method, and an application cannot call 'request(n)'
> > from the outside.
> >
>
> But it does work today.
>
> We request(1) as soon as the call starts. As soon as that requested message
> is delivered to StreamObserver.onValue(), then we call request(1) again,
> which allows onValue() to be called again. Rinse and repeat for each
> message. Eventually there aren't any more messages.


Ok, got it. So it's correct but in fact kind of degenerated usage if you
are always passing 1. In fact, this discussion makes me believe this method
should be removed, and flow control instead be based just on observer
blocking, what you are effectively doing right now. The semantics related
to request(N) is just too complex and indirect. But it may make sense to
wait and see whether there are actually use cases for it...

**Comment by ejona86** [comment]
On Wed, Apr 8, 2015 at 5:24 PM, Wolfgang Grieskamp <notifications@github.com
> wrote:

> That's rather ambiguous to me, in particular in an asynchronous programming
> model.


Do you have a suggested alternative language that would be more precise?

What if we added:
"If called multiple times, the number of messages able to be delivered will
be the sum of the calls."

If it actually means "send me the next N messages", its across with the
> philosophy of the stream-observer pattern (Rx), in which data is pushed and
> not pulled.


I don't really understand this point. This model is based on
reactive-streams <https://github.com/reactive-streams/reactive-streams-jvm>.
The StreamObserver is based on Rx.

It basically makes the object model less suitable for
> composition, since as soon as you go up in abstraction layers (e.g. outside
> of Calls methods), you lose access to it.
>
> Flow control in the stream-observe pattern should be done instead by
> observer blocking, which is compositional over abstraction layers.
>

Blocking is how you "have access to it" when using StreamObserver.

Ok, got it. So it's correct but in fact kind of degenerated usage if you
> are always passing 1.


Yes, we could have a "requestNextMessage" method instead. *Note that
StreamObserver isn't the only user of these methods.* We expect some
applications to make use of them. Also, we believe there may be a
reactive-streams stub later, which has very similar semantics.

In fact, this discussion makes me believe this method
> should be removed, and flow control instead be based just on observer
> blocking, what you are effectively doing right now.


I don't quite follow, unless you are assuming that StreamObserver is the
only consumer of this interface. Applications can and will use this
interface directly.

The semantics related
> to request(N) is just too complex and indirect. But it may make sense to
> wait and see whether there are actually use cases for it...


Except that this is an API that will have to be stable. We have to choose
and API and stick with it. Right now the API is targeted to the most
advanced users and gives as much power as we are willing to provide.
Simplified APIs are built on top with the stubs.

**Comment by wrwg** [comment]
Thanks Eric for the explanations. I think I understand the intention behind the Call abstraction better now. There needs to be better documentation of the contract of the entire Call object, I open a separate issue for that, and close this one.
