### ISSUE TITLE
How to terminate a service call in ServerInterceptor.interceptCall

### ISSUE THREAD

**Issue by haggag** [grpc/grpc-java#2814]
What is the correct way to terminate a call to a service's method once ServerInterceptor.interceptCall finds that the request is invalid (ex. the client's authentication fails) and wants to stop proceeding with executing the method and return an error to the client?

Should interceptCall return some special listener? or it should throw some sort of Exception indicating an Unauthenticated access?

**Comment by ejona86** [comment]
It should call `serverCall.close()` but still return a listener. Since nothing needs to listen, you can simply return some sort of noop, like `return new ServerCall.Listener() {}`. Note that you would not call `next` in this case.
