### ISSUE TITLE
Capture more information on error for debugging

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2815]
When an error is propagated to the application, it would be useful to have things like server IP address[1], the timeout of the call (deadline - now), and whether the error was generated on the server.

There is other information that gRPC doesn't have direct knowledge of being useful, like tracing ids. Either Metadata would need to be included in full (doesn't sound great to me, since that could include auth tokens) or we could allow interceptors to cheaply supplement the data.

1. Note that retries/hedging make "address" a bit more interesting.

**Comment by jhspaybar** [comment]
I'd also like this information to somehow make it back to load balancers so errors and latency can be used in load balancing decisions.

**Comment by ejona86** [comment]
@jhspaybar, this issue is more for human consumption. I think we'd make it a string or some other unhelpful-for-you form. And the LB doesn't see the status already, and we'd likely put this information "close" to the status. So you'd probably want a separate issue to track it. #2717 tracks the RTT latency, but that's different from the RPC latency.

**Comment by ejona86** [comment]
Languages have overall not "tagged" errors with "local" or "remote" bits and provided remote addresses and such. Since this was filed, gRPC Java [started producing better DEADLINE_EXCEEDED](https://github.com/grpc/grpc-java/pull/5892) errors with much of the context mentioned in this issue.

I'm going to consider this done. If you like this general idea, let's open a new issue and you can describe some about your situation.
