### ISSUE TITLE
ContextStorageOverride unnecessary stacktrace logging

### ISSUE THREAD

**Issue by jorgheymans** [grpc/grpc-java#2827]
(minor)

IMO the printStackTrace during init of io.grpc.Context when no ContextStorageOverride class is found is not really adding anything useful and could be removed. (moreover it jumpscares me each time i start my app in intellij :-)

```   
 try {
      Class<?> clazz = Class.forName("io.grpc.override.ContextStorageOverride");
      newStorage = (Storage) clazz.getConstructor().newInstance();
    } catch (ClassNotFoundException e) {
      if (log.isLoggable(Level.FINE)) {
        // Avoid writing to logger because custom log handlers may try to use Context, which is
        // problemantic (e.g., NullPointerException) because the Context class has not done loading
        // at this point.  The caveat is that in environments stderr may be disabled, thus this
        // message would go nowhere.
        System.err.println("io.grpc.Context: Storage override doesn't exist. Using default.");
        e.printStackTrace();
      }
      newStorage = new ThreadLocalContextStorage();
    } catch (Exception e) {
      error = e;
    }
```

**Comment by zhangkun83** [comment]
This log is meant to provide debug information in case where an expected loading of ContextStorageOverride doesn't happen. The log should only be visible when the log level is on or below `FINE`, with the understanding that application will normally run at at least `INFO` level. Does your app run at `FINE` level?

**Comment by jorgheymans** [comment]
Yes sure it runs on INFO level, I was aware of that. I was just thinking that e.printStacktrace inside of a ClassNotFoundException catch block is not going to give any more information than the err.println above it provides. But looks that it was put there with a purpose so just ignore my noise.
