### ISSUE TITLE
tcp connection do not close, ChannelOutboundBuffer and NettyServerHandler still hold memory 

### ISSUE THREAD

**Issue by JeffZhang02747** [grpc/grpc-java#2840]
### What version of gRPC are you using?
1.2.0

### What JVM are you using (`java -version`)?
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

### What did you do?
I run stress test to hit grpc endpoint a lot and use VisualVM for memory leak detection.
debug message looks fine.
2017-03-17 18:55:12,552 DEBUG [NettyServerHandler] 
----------------INBOUND--------------------
[id: 0x52781f4a, L:/127.0.0.1:8650 - R:/127.0.0.1:64571] SETTINGS: ack=true
2017-03-17 18:55:12,573 DEBUG [NettyServerHandler] 
----------------OUTBOUND--------------------
[id: 0x52781f4a, L:/127.0.0.1:8650 - R:/127.0.0.1:64571] HEADERS: streamId=3, headers=GrpcHttp2OutboundHeaders[grpc-status: 0], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true

After a while I terminate the test and check tcp connection and memory usage.

### What did you see instead?
After I terminate the stress test, I saw those class still hold memory(not releasing any memory after I terminate the test).
io.netty.util.AsciiString	
io.netty.handler.codec.http2.internal.hpack.HeaderField	
io.netty.handler.codec.http2.internal.hpack.Encoder$HeaderEntry	
io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultPropertyKey
io.netty.channel.ChannelOutboundBuffer
io.grpc.netty.WriteQueue
io.grpc.netty.NettyServerHandler
io.grpc.netty.NettyServerTransport
io.grpc.netty.FixedHttp2ConnectionDecoder
io.grpc.netty.NettyServerHandler

I also run the netstat to check the tcp connection.
I notice that even after I terminate the test, the number of tcp connection remained the same, the status are all ESTABLISHED.

### What did you expect to see?
expect to see the tcp connection drop after test terminate. 
expect to see io.grpc and io.netty class release memory.

**Comment by ejona86** [comment]
Can you explain how you "terminate the test"? Are you shutting down the channels?

**Comment by JeffZhang02747** [comment]
Should I shut down the channel on server side manually? wouldn't they get garbage collected?

One reason why I am having this issue is that, my client side is still having grpc 1.0.1 version.
Only my server is 1.2.0.

I am going to upgrade the version of client side to 1.2.0 to see if this could fix the issue.

**Comment by JeffZhang02747** [comment]
io.netty.buffer.UnpooledUnsafeHeapByteBuf	 is increasing its size during test , and not droping the size after the test.

**Comment by ejona86** [comment]
> Should I shut down the channel on server side manually?

No, the server isn't given direct access to the transport (so this is infeasible). I was wondering if the clients shutdown their channels.

> I am going to upgrade the version of client side to 1.2.0 to see if this could fix the issue.

Probably won't impact the server-side behavior too much in this case. But it can be good all-the-same.

> io.netty.buffer.UnpooledUnsafeHeapByteBuf is increasing its size during test , and not droping the size after the test.

Huh. That's strange. I would have expected `PooledUnsafeDirectByteBuf`. I don't know what would be using Unpooled byte buffers, unless you are specifying some netty properties. If it is unpooled, then you should be able to see what class is hanging on to the reference.

**Comment by JeffZhang02747** [comment]
the class hanged on the UnpooledUnsafeHeapByteBuf 
is DefaultHttp2HeadersEncoder contains DefaultHttp2FrameWriter ,
DefaultHttp2FrameWriter contains DefaultHttp2LocalFlowController and DefaultHttp2ConnectionEncoder

**Comment by JeffZhang02747** [comment]
The field of DefaultHttp2HeadersEncoder  is tableSizeChangeOutput

**Comment by ejona86** [comment]
Oh, that's helpful. Okay, so that ByteBuf will be retained for the connection's lifetime. While we may want to change that to reduce idle overhead, we have several other per-connection costs. It sounds like the clients are shutting down their channels.

**Comment by JeffZhang02747** [comment]
so ByteBuf is retrained during connection's lifetime.
The problem I am having is that the channels seems is still alive, not like it is being shutting down.

**Comment by carl-mastrangelo** [comment]
@JeffZhang02747 Can you provide a snippet of how you are shutting down your channel and executor?

**Comment by ejona86** [comment]
TCP keepalive will _eventually_ realize the channels are dead, but you can't easily configure the timeout. We're working on more active configuration where you can specify idle times and keepalive ping times. But still, if you are seeing a lot of these orphaned connections something seems wrong with your clients.

**Comment by JeffZhang02747** [comment]
I upgrade GRPC from 1.0.1 to 1.2.0 for both Client and Server.

The first time after stress test, I did not see the number of tcp connection drop. Continue from the first-time case, I ran the stress test on that, after the second time after stress test, I finally saw the number of tcp connection drop, and the memory holding by WriteQueue,NettyServerHandler and NettyServerTransport also decrease as well.

I have a few questions,
Is there a way on the Server to set the timeout so that server could terminate the tcp connection when timeout?

Right now, is only client able to terminate the connection?

On the client side if no keepalive is configured, do we know when would a client close its connection?

**Comment by ejona86** [comment]
> Is there a way on the Server to set the timeout so that server could terminate the tcp connection when timeout?

At present, no. But we are actively working on it now.

> Right now, is only client able to terminate the connection?

On a single-connection basis, yes.

> On the client side if no keepalive is configured, do we know when would a client close its connection?

If no idleness is configured, then it only closes the connection when shutting down the channel or when the connection fails.

**Comment by ejona86** [comment]
Since 1.3, the server has options for disconnecting idle clients and sending keepalives to test the network connection.
