### ISSUE TITLE
version compatibility: grpc java vs grpc go

### ISSUE THREAD

**Issue by fanminshi** [grpc/grpc-java#2844]
What's the compatibility of  grpc-java and  grpc-go in term of version? 

Suppose that the our service is using grpc-go 1.0.4,  can we upgrade the client to use grpc-java 1.12 without any issue?

**Comment by carl-mastrangelo** [comment]
Yes, they will be wire protocol compatible.  Features not supported by both will not be used.

**Comment by fanminshi** [comment]
@carl-mastrangelo will different versions of go and java grpc always be wire compatible?

**Comment by carl-mastrangelo** [comment]
The versioning of gRPC is called [semantic versioning](http://semver.org/).  All major versions, i.e. the leading number, that are the same will work together.

**Comment by fanminshi** [comment]
@carl-mastrangelo sounds good. Thanks!

**Comment by ejona86** [comment]
The semantic versioning is for our API surface. Wire protocol would probably be maintained with a API version bump. Right now we're maintaining compatibility with versions 1.0 and later. But we recommend using the latest version for each language.
