### ISSUE TITLE
Unimplemented channel state API is not documented as such

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2883]
Until #2292 is resolved, `getState()` and `notifyWhenStateChanged()` always throw `UnsupportedOperationException`. The documentation should call out that it isn't implemented, especially since not even `LoadBalancer` is using the API at this point.

I had thought this was already done, but I couldn't find where.

**Comment by lukaszx0** [comment]
> I had thought this was already done, but I couldn't find where.

Yeah, my bad - I have started it but not finished :/ https://github.com/grpc/grpc-java/pull/2768

**Comment by ejona86** [comment]
> Yeah, my bad - I have started it but not finished

Nah, I wasn't concerned about it being implemented. I was concerned with it not being documented... that it isn't implement. I had thought @zhangkun83 had some documentation mentioning lack of support when the API was added; maybe it got lost in one of the iterations of LoadBalancerV2.
