### ISSUE TITLE
Many TCPIP connectons in established state

### ISSUE THREAD

**Issue by cr22rc** [grpc/grpc-java#2885]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.2.0 The latest I think.
### What JVM are you using (`java -version`)?
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

Linux Fedora 25 client. 
Going to server in docker that is GOLANG 

### What did you do?
On the client I have 9 different types of connections. On 8 of them I reuse the respective  channel for all request (8 different ports/ 8 channels created) Never shutdown. One I do a shutdownNow on the channel after each request, create a new channel for the next request.  The code for the channelBuilder is identical for each except the forAddress/port part.  On all of these there are many requests.  If I stop my client before it terminates and using lsof MANY connections established with the 8 I reuse the channel on. I'm guessing there is one connections per each request.  The one where I shutdown there are none listed 
.
### What did you expect to see?
I expected to see 8 at most TCPIP connections established.  I waited for 10 minutes and not one of the connections were dropped.

### What did you see instead?
From this link https://justpaste.it/15cj4

As said, MANY connections  established  to the same endpoint

All the connections are working just fine sending and receiving back the data as expected. 
So the issue here is just why all these connections ? When and how will they get reclaimed ? Do I need to shutdown the channel after each request and create a new one like the one that's not seeing this issue?

**Comment by cr22rc** [comment]
Unrelated but is there some preferred forum/chat/slack for just asking user questions ?

**Comment by cr22rc** [comment]
I just noticed that to same endpoint port in that listing the source ephemeral port is the same so not sure these are different tcpip connections?  Still wonder when/how the are released.

**Comment by cr22rc** [comment]
no help ?

**Comment by carl-mastrangelo** [comment]
You can ask questions at https://groups.google.com/forum/#!forum/grpc-io

**Comment by ejona86** [comment]
@cr22rc, it looks like the TID (thread ID) is different for each. I don't know how lsof works with threads involved, but since it seems the five-tuple (protocol (i.e., TCP), src ip, src port, dest ip, dest port) is the same for each set of connections, that would generally mean they are the same connection. It seems your process just has 45 threads.

**Comment by cr22rc** [comment]
Thanks for the reply.  Actually it's all on one thread but  I think what's happening is we are using the futureStub (aka async ) So what's happening I think is there is a thread being creating for each of those request. Our futures complete relatively quickly.   My only concern is are these actually being eventually cleaned up?

**Comment by cr22rc** [comment]
@carl-mastrangelo  Thanks in the future I'll ask more question related issues there.

**Comment by ejona86** [comment]
@cr22rc, right now grpc creates Netty threads for you, based on how many cores you have. Those are probably the threads. gRPC does not need a thread per request. If you shutdown all the channels, then those threads will be automatically shutdown.

**Comment by cr22rc** [comment]
My application will be long lived. I don't want to just down channels to clean up resources. I think that's inefficient specially with TLS connections.  I assume that somehow these will get reused or eventually shutdown?

**Comment by ejona86** [comment]
@cr22rc, there does not seem to be an excessive number of TCP connections. It seems it is one per `Channel`, and yes, they are reused. So I see no cause for concern.

The TCP connections are shutdown when you shutdown the Channel. You can also specify an [`idleTimeout()`](http://www.grpc.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#idleTimeout-long-java.util.concurrent.TimeUnit-) to have the Channel automatically close the TCP connection after a period of inactivity.

**Comment by cr22rc** [comment]
Ok thanks for all the good information.  I'll close this as it does not appear right now to be an issue.
