### ISSUE TITLE
AbstractTransportTest is flaky.

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#289]
I've seen several failures of Http2OkHttpTest.pingPong() on Travis, like this one: https://s3.amazonaws.com/archive.travis-ci.org/jobs/57879240/log.txt.

But I couldn't reproduce the same failure in ~30 runs in my local repository.

**Comment by ejona86** [comment]
It probably is. Travis is good at finding races because it is a much weaker machine than what we normally use. Simply because it is different things end up running in a different order, sometimes consistently.

**Comment by madongfly** [comment]
Seem a similar failure for netty:
io.grpc.testing.integration.Http2NettyTest > serverStreamingShouldBeFlowControlled FAILED

https://s3.amazonaws.com/archive.travis-ci.org/jobs/57969751/log.txt

**Comment by madongfly** [comment]
I tried --runs_per_test=5000 in internal but still couldn't reproduce the failure.

**Comment by madongfly** [comment]
Closing this issue because I didn't see the similar failure on Travis for a week after #302 was merged.
