### ISSUE TITLE
Unix Domain Socket: UnsatisfiedLinkError

### ISSUE THREAD

**Issue by MarcMagnin** [grpc/grpc-java#2940]
### What version of gRPC are you using?
1.2.0

### What JVM are you using (`java -version`)?
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### What did you do?
Creating a ManagedChannel on Unix Domain Socket:
```java
Channel channel = NettyChannelBuilder.forAddress(new DomainSocketAddress("/tmp/somesoscket.socket"))
                .eventLoopGroup(new EpollEventLoopGroup())
                .channelType(EpollDomainSocketChannel.class)
                .usePlaintext(true)
                .build();
```

### What did you expect to see?
Successful creation of a ManagedChannel on Unix Domain Socket.

### What did you see instead?
Throwable is launched: 
```
java.lang.UnsatisfiedLinkError: io.netty.shadednetty.channel.epoll.NativeStaticallyReferencedJniMethods.epollin()I
        at io.netty.shadednetty.channel.epoll.NativeStaticallyReferencedJniMethods.epollin(Native Method) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.Native.<clinit>(Native.java:69) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.IovArray.<clinit>(IovArray.java:57) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:54) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
...
java.lang.NoClassDefFoundError: Could not initialize class io.netty.shadednetty.channel.epoll.IovArray
        at io.netty.shadednetty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:54) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
...
```

note: If I use TCP instead, it works: 
```java
Channel channel = ManagedChannelBuilder.forAddress("127.0.0.1", 1234)
```
My netty dependencies are (gradle project): 
 `compile 'io.netty:netty-all:4.1.8.Final'`
 `compile 'io.netty:netty-transport-native-epoll:4.1.8.Final:linux-x86_64'`

I'm shading io.netty to io.netty.shadednetty using shadow plugin as I have other netty dependencies in the project.

**Comment by carl-mastrangelo** [comment]
The epoll native code in netty needs to be shaded too.  When the program starts up, netty should create a temp file that is the shared object of the native code.  If you get a copy of that (usually in /tmp/), you can run `strings` on it and see if the symbols were properly renamed.  They must match the shaded package name in your java code in order for it to work.

**Comment by MarcMagnin** [comment]
Cheers, most of the strings are like:
```
Java_io_netty_channel_unix_FileDescriptor_writeAddress
Java_io_netty_channel_epoll_Native_sizeofEpollEvent
Java_io_netty_channel_unix_Socket_getReceiveBufferSize
Java_io_netty_channel_epoll_Native_splice0
Java_io_netty_channel_unix_Errors_errnoEWOULDBLOCK
Java_io_netty_channel_epoll_Native_setTcpNotSentLowAt
Java_io_netty_channel_epoll_Native_epollin
Java_io_netty_channel_unix_Socket_isKeepAlive
```

Not sure how to shade that too with the shadow plugin..

**Comment by carl-mastrangelo** [comment]
I don't know either, but they should look like:
```
Java_io_netty_shadednetty_channel_unix_FileDescriptor_writeAddress
Java_io_netty_shadednetty_channel_epoll_Native_sizeofEpollEvent
Java_io_netty_shadednetty_channel_unix_Socket_getReceiveBufferSize
Java_io_netty_shadednetty_channel_epoll_Native_splice0
Java_io_netty_shadednetty_channel_unix_Errors_errnoEWOULDBLOCK
Java_io_netty_shadednetty_channel_epoll_Native_setTcpNotSentLowAt
Java_io_netty_shadednetty_channel_epoll_Native_epollin
Java_io_netty_shadednetty_channel_unix_Socket_isKeepAlive
```

**Comment by MarcMagnin** [comment]
Thanks for your help, searching about that...

**Comment by MarcMagnin** [comment]
all good, 
With `relocate 'io.netty', 'shade.io.netty'`, it needed a `System.setProperty("shade.io.netty.packagePrefix", "shade.");` and a rename of `META-INF/native/lib-netty-transport-native-epoll.so` to `META-INF/native/libshade-netty-transport-native-epoll.so`
