### ISSUE TITLE
CallOptions.Key should document that it uses instance equality

### ISSUE THREAD

**Issue by vector090** [grpc/grpc-java#2942]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.2.0.

### What JVM are you using (`java -version`)?
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

Client code wants to add value in CallOptions during grpc call for customized load balancing, similar to:
blockingStub.withOption(CallOptions.Key.of("keyName", "defaultValue"), "actualValue"),
but as the SubchannelPicker.pickSubchannel(PickSubchannelArgs args) wants to retrieve the value:  args.getCallOptions().getOption(CallOptions.Key.of("keyName", "defaultValue"))), it fails to get "actualValue", but get "defaultValue" instead.

### What did you expect to see?
"actualValue"

### What did you see instead?
"defaultValue"

### Cause
Problem is CallOptions.getOption:
    for (int i = 0; i < customOptions.length; i++) {
      if (key.equals(customOptions[i][0])) {

the CallOptions.Key didn't implement hashCode and equals, so even two Key objects with exactly the same values won't match each other.

**Comment by ejona86** [comment]
This is on purpose, as it allows applying visibility scopes to the options. The name is for debugging purposes. It seems the documentation doesn't make this clear.

**Comment by dapengzhang0** [comment]
also document for `Attributes.Key` and `Context.Key`

**Comment by ejona86** [comment]
This was fixed by #2970.
