### ISSUE TITLE
Gradle build points to https with self signed certificate

### ISSUE THREAD

**Issue by ankurg** [grpc/grpc-java#296]
In installation step for grpc-java
./gradlew install
 exec /usr/lib/jvm/jdk1.7.0_51/bin/java -Dorg.gradle.appname=gradlew -classpath <path>/grpc-java/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain install
Downloading https://services.gradle.org/distributions/gradle-2.2.1-all.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching services.gradle.org found.

Work around is to modify gradle/wrapper/gradle-wrapper.properties to change to http.

Should change it permanently?

**Comment by ejona86** [comment]
This should be a temporary issue: http://discuss.gradle.org/t/https-services-gradle-org-has-invalid-certificate/8810

It seems like they just recently swapped out their cert, since the current one was issued on the 7th.

**Comment by ejona86** [comment]
The Gradle issue appears to be resolved now and I'm not seeing the issue any more.
