### ISSUE TITLE
Why is java grpc so slow

### ISSUE THREAD

**Issue by peachyo** [grpc/grpc-java#2971]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
latest java gRPC

### What JVM are you using (`java -version`)?
1.8

### What did you do?
If possible, provide a recipe for reproducing the error.

I created a simple service which does oracle database query.  The client and server code is based on the HelloWorld example. I am running client and server on the same windows pc. The Oracle database is running on a server. 

### What did you expect to see?
On server side, the database query is 51ms, which is good.  On client side, I am getting execution time 400 ms. 
Using go-grpc, I get <70ms and restful using curl is 120ms. 

### What did you see instead?
The execution time from client side is very slow.

**Comment by peachyo** [comment]
Looks like if I keep the connection open, then the next time, it's only 60ms.

**Comment by carl-mastrangelo** [comment]
Can you provide the code you are using to open the channel?

Also, are you timing how long the first RPC takes?  A connection isn't opened until there is an RPC I believe.

**Comment by peachyo** [comment]
Here is the code. The rest are the same as the HelloWorldClient. 

  public void getAcctInfo(String acctNum) {
    AcctInfoRequest request = AcctInfoRequest.newBuilder().setAcctNum(acctNum).build();
    AcctInfoResponse response;
    try {
    	long t = System.currentTimeMillis();
      response = blockingStub.getAcctInfo(request);
      System.out.println("time used: " + (System.currentTimeMillis()-t));
    } catch (StatusRuntimeException e) {
      logger.log(Level.WARNING, "RPC failed: {0}", e.getStatus());
      return;
    }
  }

  public static void main(String[] args) throws Exception {
	  AcctInfoClient client = new AcctInfoClient("localhost", 50051);
    try {
    	for(int i=0; i<5; i++){
      client.getAcctInfo("12345");
    	}
    } finally {
      client.shutdown();
    }
  }

**Comment by carl-mastrangelo** [comment]
That test is flawed.   First, you aren't showing how you actually opened up the channel, specifically with `ManagedChannelBuilder`.   Second, 5 RPCs is not enough get get a representative sample.   You need to send several thousand. The JVM won't even compile your methods until you have called them ~1500 times.   Also, you are doing your RPCs serially, which means that the JVM is idle most of the time.  You need to have several RPCs outstanding, so that the CPU doesn't go to sleep and the process context switch away.  


I am going to close this, since it seems like this is measurement error.

**Comment by peachyo** [comment]
The rest part of the code is copied from HelloWorld example:   
public AcctInfoClient(String host, int port) {
    this(ManagedChannelBuilder.forAddress(host, port).usePlaintext(true));
  }

  AcctInfoClient(ManagedChannelBuilder<?> channelBuilder) {
    channel = channelBuilder.build();
    blockingStub = AcctInfoGrpc.newBlockingStub(channel);
  }

  public void shutdown() throws InterruptedException {
    channel.shutdown().awaitTermination(5, TimeUnit.SECONDS);
  }

My question is why the first RPC call takes so long. When I use curl as a client to send request to the restful service,  I get ~120ms for each request. When I run the java gRPC client, the first rpc call always takes ~400ms.

**Comment by carl-mastrangelo** [comment]
The JVM has to warm up.  Try doing 100,000 RPCs and see if the time doesn't converge to the cURL time.

**Comment by peachyo** [comment]
Ok. Thanks!
