### ISSUE TITLE
sending data using gRPC 

### ISSUE THREAD

**Issue by orrganani** [grpc/grpc-java#2983]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.3.0

### What JVM are you using (`java -version`)?
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.
I tried sending data using gRPC via proxy.
I'm doing this inside a VPN and the proxy is the only way to send data to the outside world

### What did you expect to see?
The message shouldn't reached the server side

### What did you see instead?
A SSLHandshakeException during the protocol negotiation.
This was the error I got:
javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE

It was caught in the ProtocolNegotiators class under method userEventTriggered method.

Thanks

**Comment by ejona86** [comment]
TLS is failing. Are you trying to connect directly to the proxy? Proxies are plain-text, so that would be the cause of the problem.

Instead, you can use the GRPC_PROXY_EXP (EXP for experimental) environment variable like: `GRPC_PROXY_EXP=proxy.example.com:8080`

**Comment by orrganani** [comment]
Allow me to explain my configuration:
The GRPC_PROXY_EXP env variable is set to my.proxy.com:8080 as specified in the grpc-java documentation.

I am able to communicate with other servers via HTTP connections through the proxy with a basic HttpClient like this:

HttpClient httpClient = HttpClientBuilder
        .create()
        .useSystemProperties()
        .setProxy(new HttpHost("my.proxy.com", 8080))
        .build();

This works just fine and I'm able to send requests and get responses.
Unfortunately I'm unable to connect with gRPC

Thanks

**Comment by ejona86** [comment]
Then you may simply have the wrong configuration to communicate with the server (i.e., it wouldn't work if you weren't behind the proxy). Since you are specifying GRPC_PROXY_EXP, that error would be happening after the proxy was successfully connected. So maybe the server you're connecting to is plaintext? Or maybe you have the wrong port?
