### ISSUE TITLE
platform issue

### ISSUE THREAD

**Issue by jeffreyji666** [grpc/grpc-java#299]
I run a grpc java server on Mac OS, it is ok to test it with java client, but error happened on a linux server,and the error is as follows:

>com.google.common.util.concurrent.UncheckedExecutionException: io.grpc.Status$OperationRuntimeException: INTERNAL
	at io.grpc.stub.Calls.getUnchecked(Calls.java:117)
	at io.grpc.stub.Calls.blockingUnaryCall(Calls.java:129)
	at com.engzo.search.protoc.SearchGrpc$SearchBlockingStub.searchForum(SearchGrpc.java:245)
	at com.engzo.search.api.SearchClient.searchForum(SearchClient.java:35)
	at com.engzo.search.api.SearchClient.main(SearchClient.java:76)
Caused by: io.grpc.Status$OperationRuntimeException: INTERNAL
	at io.grpc.Status.asRuntimeException(Status.java:428)
	at io.grpc.stub.Calls$UnaryStreamToFuture.onClose(Calls.java:324)
	at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$3.run(ChannelImpl.java:373)
	at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by madongfly** [comment]
This stack trace didn't tell much useful info, did your server see a corresponding error? if so, please provide the stack trace.

If not, did your server implementation call onError()? this stack trace is identical to the case that server calls onError(). @ejona86, this reminds me that our current Status lack of the ability to present application errors, we currently use INTERNAL for users' onError() call (https://github.com/grpc/grpc-java/blob/b784eb6b72d9c42d6e879e38031bbe491b0126e2/stub/src/main/java/io/grpc/stub/ServerCalls.java#L187), which is too confusion. At least we should add a description to tell the error is from the server app handler.

**Comment by ejona86** [comment]
On Tue, Apr 14, 2015 at 2:58 AM, Xudong Ma <notifications@github.com> wrote:

> If not, did your server implementation call onError()? this stack trace is
> identical to the case that server calls onError(). @ejona86
> <https://github.com/ejona86>, this reminds me that our current Status
> lack of the ability to present application errors, we currently use
> INTERNAL for users' onError() call (
> https://github.com/grpc/grpc-java/blob/b784eb6b72d9c42d6e879e38031bbe491b0126e2/stub/src/main/java/io/grpc/stub/ServerCalls.java#L187),
> which is too confusion. At least we should add a description to tell the
> error is from the server app handler.
>

We purposefully don't propagate generic exceptions to the client, as that
makes it easy to leak server details that the service author don't want
leaked. That is why we only use status messages that were explicitly
provided with Status, as those are meant to be communicated to the client.
As you suggest, we could include a string like "Unknown server error",
which is the same as INTERNAL. Even with the message you will need to look
at server logs. Also note that the line you provided is not related to
automatic exception handling: it is for exceptions manually provided by the
application; ServerImpl has the automatic exception handling
<https://github.com/grpc/grpc-java/blob/b784eb6b72d9c42d6e879e38031bbe491b0126e2/core/src/main/java/io/grpc/ServerImpl.java#L398>
logic.

**Comment by madongfly** [comment]
INTERNAL with an empty message makes me think that the error was happened in gRPC library, we should have a description to tell client the error was happened in application code.

The server logs is needed even with the description, but in case the client user doesn't own the service,  the description can help the user to decide the next step is asking the service owner or consulting gRPC community.

**Comment by ejona86** [comment]
Maybe we should be using UNKNOWN instead for converting from exceptions? @louiscryan

**Comment by ejona86** [comment]
We've swapped from INTERNAL to UNKNOWN for application errors. But we purposefully don't provide more info, as the application needs to decide what information it is willing to expose.

**Comment by smparkes** [comment]
So all throwables turn into UNKNOWN?

What is the model then for exposing information? How does the application go about doing that? Deliver it in-band via onNext?

**Comment by smparkes** [comment]
Ah. I got it: https://groups.google.com/forum/#!msg/grpc-io/a1oROAX_lB4/mbKIB_eYCgAJ

+1/0/-1 on a PR that mentions this in the `StreamObserver` javadocs?

**Comment by ejona86** [comment]
+1 for a PR that mentions that in the `StreamObserver` JavaDocs, but... there will be some effort needed to do it right because there are 4 different cases: client/server x sending/receiving.

**Comment by smparkes** [comment]
Ack.

Maybe this requires a page of its own. It's subtle and important.

I'll hold off and collect notes as I audit our code in all these places for desired behavior, and then draft something.
