### ISSUE TITLE
[Question] How to disable some logs?

### ISSUE THREAD

**Issue by MarcMagnin** [grpc/grpc-java#2994]
### What version of gRPC are you using?
1.2.0

### What JVM are you using (`java -version`)?
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Hi,

How can I disable logging such as the following? 
```
12:15:30.350 [epollEventLoopGroup-2-1] DEBUG io.grpc.netty.NettyClientHandler - 
----------------INBOUND--------------------
[id: 0x15e293c9, L:null - R:/tmp/4449017254441488790.socket] WINDOW_UPDATE: streamId=7, windowSizeIncrement=16384
```
Many thanks,
Marc

**Comment by ejona86** [comment]
That logging isn't enabled by default. You must have some logging configuration enabling it. If you're using a logging.properties file you can include something like `io.grpc.level = INFO`. At runtime you can do something like `Logger.getLogger("io.grpc").setLevel(Level.INFO)` (typing from memory).

**Comment by MarcMagnin** [comment]
Cheers @ejona86 ! I'll take a deeper look. I've already tried different things as you said but I must have done some mistakes.

Thumbs up! You are doing great things guys!
