### ISSUE TITLE
GrpcServerRule doesn't support interceptors

### ISSUE THREAD

**Issue by jebbench** [grpc/grpc-java#2995]
### What version of gRPC are you using?
1.2.0

We have interceptors which catch our internal exceptions and serialize them as GRPC trailers; these are then deserialized on the client and used as the cause on the Status.

There isn't anyway to add interceptors when using the GRPCServerRule and we can't see anyway to set the cause of the Status passed to onError by GRPC.

**Comment by jebbench** [comment]
I've been able to get this working by doing the below:
To set up the server interceptor:
```
this.grpcServerRule.getServiceRegistry().addService(ServerInterceptors.intercept(this.myService, new MyServerInterceptor()));
```
And for the channel:
```
ManagedChannel channel = InProcessChannelBuilder.forName(grpcServerRule.getServerName())
      .directExecutor()
      .intercept(new MyServiceResponseInterceptor())
      .build();
```

A method to support this when using the grpcServer.getChannel() method would be useful.

**Comment by dapengzhang0** [comment]
You can use `stub.withInterceptors(ClientInterceptor ...)` to add client interceptors

**Comment by ejona86** [comment]
You can also call ClientInterceptors directly if you would prefer to pass a Channel to some code.

I guess if you want to pass a ManagedChannel to some code, that would be a problem and GrpcServerRule could maybe be enhanced to support that.
