### ISSUE TITLE
Any plan upgrade to OkHttp 3?

### ISSUE THREAD

**Issue by b95505017** [grpc/grpc-java#2999]
As title.

**Comment by ejona86** [comment]
We didn't really. We've manually "shaded" most of OkHttp that we use such that the okhttp dependency is just for our surface API for specifying TLS settings (via ConnectionSpec).

We could probably have OkHttpChannelBuilder support both ConnectionSpec from OkHttp 2 and 3 simultaneously. It would mean depending on both versions, but when using ProGuard only one would be used.

It's not clear whether that just gives us a "nice feeling" or whether it actually would benefit someone.

**Comment by ejona86** [comment]
It doesn't sound like this provides a tangible benefit, so closing. It'd be easy to convince me otherwise, though. So if this would benefit you, say so and we will consider it. Also mention whether depending on both OkHttp 2 and OkHttp 3 would be a solution for you.

**Comment by kraghu** [comment]
In Android We are so used to okhttp for handling all our rest call needs . It will benefit us from learning point of view.
