### ISSUE TITLE
ConnectivityStateInfo never update when using RoundRobinLoadBalancerFactory

### ISSUE THREAD

**Issue by iamtiancaif** [grpc/grpc-java#3005]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.2.0

### What JVM are you using (`java -version`)?
1.8

### What did you do?
If possible, provide a recipe for reproducing the error.
integrate grpc with spring-cloud-eureka

### What did you expect to see?
I have done it with grpc 1.0.0 and spring-boot 1.5.2.RELEASE.
everything is ok.

### What did you see instead?
But when I try to update grpc to 1.2.0. client can not connect to server.

Then I found the cause.  In class RoundRobinLoadBalancerFactory,   subchannel is initialized as IDLE and never updated.  See https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java#L122  . 
But when client try to connect server, method filterNonFailingSubchannels will retrieve channels of which state is READY.  See https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java#L179 . 

How can I trigger the updating of subchannel's state?

### to reproduce my issue.
1. git clone https://github.com/iamtiancaif/spring-boot-starter-grpc.git
2. install this project to integrate grpc and spring-cloud-eureka.

3. download this project : https://github.com/iamtiancaif/grpc-java-demos/tree/master/springboot
4. build this projects downloaded in step 4, then run them in order of : eureka-server, grpc-server, grpc-client.

Thanks a lot.

**Comment by ejona86** [comment]
How do you know ConnectivityStateInfo isn't being updated? `ManagedChannel.getState(boolean)` [isn't yet implemented](https://github.com/grpc/grpc-java/blob/v1.3.0/core/src/main/java/io/grpc/ManagedChannel.java#L82). It was added for use in the LoadBalancers, but now it isn't even needed there. You can follow #2292 for updates.

The state is updated:
https://github.com/grpc/grpc-java/blob/v1.3.0/core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java#L150

I'll also note that the RoundRobinLoadBalancer isn't the default and I don't see a reference to it in either of the two iamtiancaif repos.

**Comment by iamtiancaif** [comment]
https://github.com/iamtiancaif/spring-boot-starter-grpc/blob/master/grpc-client-autoconfigurer/src/main/java/org/springframework/boot/autoconfigure/grpc/client/DiscoveryClientChannelFactory.java#L41,L58


Hi, I have set channel to use RoundRobinLoadBalancer, see link above.  Why did you say it isn't the default? 

Seems I have some misunderstanding of grpc concept.  Could you guide me some stuff to learn more about grpc ?

**Comment by ejona86** [comment]
Ah, so the code you're using does swap to round robin. I said it isn't the default because it isn't. The code you linked to overrides the default with `.loadBalancerFactory(balancerFactory)`.

But I still don't believe there is an issue here: I showed where round robin does update the state and `getState()` is known to be non-implemented.

**Comment by iamtiancaif** [comment]
Indeed it isn't a bug. Although I don't know what's wrong with it. Another project work well and I switch to it.

Thanks.
