### ISSUE TITLE
java.lang.NoClassDefFoundError: io.grpc.ManagedChannelBuilder

### ISSUE THREAD

**Issue by KrishHari** [grpc/grpc-java#3010]
### What version of gRPC are you using?
v1.3.0

### What JVM are you using (`java -version`)?
1.8.0_45

### What did you do?
I created a library project that sends data to server over GPRC. I tested it as a module dependency on a sample project and it is working fine. When I take the aar file and add it as a dependency on apps, the app is crashing.

### What did you expect to see?
The app should run without crashing as it runs when I add it as a normal module dependency.

### What did you see instead?
I get a crash with trace
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.myapp.tuktuk, PID: 7362
java.lang.NoClassDefFoundError: io.grpc.ManagedChannelBuilder
```

My library project gradle file looks like below 
```
apply plugin: 'com.android.library'
apply plugin: 'com.google.protobuf'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        consumerProguardFiles 'proguard-project.pro'

    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.2.0'
    }
    plugins {
        javalite {
            artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0"
        }
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.3.0' // CURRENT_GRPC_VERSION
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
                grpc {
                    // Options added to --grpc_out
                    option 'lite'
                }
            }
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'io.grpc:grpc-okhttp:1.3.0'
    compile 'io.grpc:grpc-protobuf-lite:1.3.0'
    compile 'io.grpc:grpc-stub:1.3.0'
    compile 'javax.annotation:javax.annotation-api:1.2'
    compile 'com.google.firebase:firebase-messaging:9.8.0'
    compile 'com.google.code.gson:gson:2.8.0'
}

```

**Comment by KrishHari** [comment]
@ejona86 could you help me figure out this ?

**Comment by ejona86** [comment]
Sorry, I don't think I can figure out what's wrong just based on what you've posted. It's quite strange ManagedChannelBuilder is the class having trouble. I've not seen that problem before. I'd suggest seeing if it works without Proguard and looking at `./gradlew dependencies`

**Comment by KrishHari** [comment]
I tried disabling proguard, but that will give me exception as below. 
<img width="804" alt="screen shot 2017-05-22 at 7 30 06 pm" src="https://cloud.githubusercontent.com/assets/10668266/26318897/68846114-3f25-11e7-8217-2ae7ad5b0c69.png">


So I added proguard with following configuration
<img width="394" alt="screen shot 2017-05-22 at 7 30 35 pm" src="https://cloud.githubusercontent.com/assets/10668266/26318879/58ca3032-3f25-11e7-990d-3377f39fb785.png">

**Comment by KrishHari** [comment]
Even after adding -keep class io.grpc.okhttp.OkHttpChannelProvider I get java.lang.NoClassDefFoundError: io.grpc.ManagedChannelBuilder

**Comment by ejona86** [comment]
@KrishHari, to disable ProGuard, did you try setting `minifyEnabled false` for the particular build type in `buildTypes`? You can use [some of our code](https://github.com/grpc/grpc-java/blob/v1.3.0/android-interop-testing/app/build.gradle) as an example.

**Comment by KrishHari** [comment]
@ejona86 I got it resolved right now. it was because of the maven plugin script that uploads the aar. All the dependencies were marked as optional=true in the pom.xml file. And because of that, when we add our library in some application, it was not resolving the optional dependencies.
