### ISSUE TITLE
toString not include the field which type is map?

### ISSUE THREAD

**Issue by k-lam** [grpc/grpc-java#3011]
in my .protobuf file, I have a class like:
message Demo{
	int32 intValue = 1;
	map<string,string> mapValue = 2;
	string stringValue = 3;
}

in my java code, I had put map into mapValue,
but when i call toString(), the field mapValue is excluded.
And I print toString, stringValue return "\123\535\153"
these form is not human readable

Have one method can log all message in human readable form

**Comment by ejona86** [comment]
gRPC doesn't seem involved here. Could you file a bug for https://github.com/google/protobuf instead?

**Comment by k-lam** [comment]
ok, thank you
