### ISSUE TITLE
SECURITY.md references non-existing ServerCall.SSL_SESSION_KEY

### ISSUE THREAD

**Issue by dheldt** [grpc/grpc-java#3013]
The **Security.md** file refers in Section "Mutual TLS" to `ServerCall.SSL_SESSION_KEY` to get a handle to the `SSLSession `in use. 

This constant does neither exist in the current Master (commit 5dc8a124bf642e0df64e7fded0f84dd5adb6ae06 at the time of writing), nor in 
the 1.3.0 release. 

To circumvent, I iterated over all keys and 

```
for (Key<?> key : call.getAttributes().keys()) {
	if (key.toString().equals("ssl-session")) {
		SSLSession sslSession = (SSLSession) call.getAttributes().get(key);
		// ..
	}
}
```

does the trick, but having a proper constant would be nicer and stable. In addition, 

`interceptCall(ServerCall<RespT> call, // ...
`

in the very same session could / should be fixed to 

`interceptCall(ServerCall<ReqT, RespT> call, // ...
`

with kind regards,

daniel heldt

**Comment by carl-mastrangelo** [comment]
@dheldt Thanks for the heads up.  That `Key` is experimental API, and moved in one of the previous releases.  I have sent out a PR to update the doc.
