### ISSUE TITLE
Duplicate headers causes c-core failure

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#3017]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.3.0

### What JVM are you using (`java -version`)?
1.8.0_121

### What did you do?
If possible, provide a recipe for reproducing the error.
I made a server interceptor as follows:

```
    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(final ServerCall<ReqT, RespT> serverCall,
                                                                 final Metadata headers,
                                                                 final ServerCallHandler<ReqT, RespT> next) {
        final Optional<String> targetAlias = resolveRedirectTarget();
        if (!targetAlias.isPresent()) {
            return next.startCall(serverCall, headers);
        }

        final ManagedChannel channel;
        final ClientCall<ReqT, RespT> clientCall;
        try {
            channel = channelFactory.get(targetAlias.get());
            clientCall = channel.newCall(serverCall.getMethodDescriptor(), CallOptions.DEFAULT);
            clientCall.start(new ClientCall.Listener<RespT>() {
                @Override
                public void onHeaders(final Metadata headers) {
                    // Issue is here
                    serverCall.sendHeaders(headers);
                }

                @Override
                public void onMessage(final RespT message) {
                    serverCall.sendMessage(message);
                }

                @Override
                public void onClose(final Status status, final Metadata trailers) {
                    serverCall.close(status, trailers);
                }

                @Override
                public void onReady() {
                    serverCall.request(1);
                }

            }, headers);
            clientCall.request(2);
            serverCall.request(1);
        } catch (final Exception ignored) {
            return next.startCall(serverCall, headers);
        }

        return new ServerCall.Listener<ReqT>(){
            public void onMessage(final ReqT message) {
                clientCall.sendMessage(message);
            }

            public void onHalfClose() {
                clientCall.halfClose();
            }

            public void onCancel() {
                clientCall.cancel("Redirect call was cancelled upstream.", null);
            }

             public void onReady() {
                clientCall.request(1);
            }
        };
    }
```

### What did you expect to see?
A caller of this service to get a response that has been proxied through to a different backend target. 

### What did you see instead?
This works in Java, but not in c-core from the client side.  As a result of forwarding the proxy target response headers, there ends up being 2 entries for "content-type"  Java clients are okay with this, c based clients are not.  I'm not sure who is "right" here as the spec is ambiguous as to the desired behavior if there are multiple headers for the same key(and in this case, their values are identical as well).  My fix for now is to simply send a new Metadata() rather than forwarding headers, but this might lose some custom headers from the proxy target.  I also considered doing a headers.removeAll(GrpcUtil.CONTENT_TYPE/ENCODING_TYPE/ETC) but since those are in the internal package I didn't.  I'm wondering what your thoughts are on how I'm doing this.  Maybe there's even a trick where I could pull this off at a pure bytestream level so my proxy isn't parsing the bytes at all?

**Comment by carl-mastrangelo** [comment]
Is that even thread safe?  Metadata can't really be accessed from two threads simultaneously.

**Comment by jhspaybar** [comment]
In this case the client I have is on a direct executor, so I expect that the Metadata objects at play here are only accessed from a single thread at a time.

**Comment by carl-mastrangelo** [comment]
The direct executor just means they are run on the network thread, not from a single thread.  If the server and client used different threads (which they probably do) it would not be synchronized.

**Comment by jhspaybar** [comment]
Well, empirically it appears threadsafe, but maybe I've just gotten lucky.  If what I'm doing here is just not reasonable I'm okay with that answer as well.  It sounds like maybe I should at a minimum be copying headers and trailers locally and forwarding the copy.

**Comment by ejona86** [comment]
@carl-mastrangelo, that looks thread-safe to me. The Metadata ownership is passed from one thread to the next. (It looks fine to me even without direct executor.)

Java is wrong for sending the duplicate headers. You can fix this for the moment by doing the removeAll like you had mentioned, except just make your own key.

The question is what should grpc-java be doing? There are only two options: 1) remove the user-provided header and 2) let the user-provided header override gRPC's. (1) is what we do elsewhere, and it seems we should simply do the same here. Doing (2) could be possible, but there may be some security implications.

**Comment by ejona86** [comment]
Oh, and I'll note that I think there are other cases where we are broken like this. I know of one proxy user that worked around it (with removeAll), but grpc-java should be able to handle this case out-of-the-box without issue (now, the proxy may need special support for some things, like maybe copying the content-type to some 1st class API, but it shouldn't break with invalid headers).
