### ISSUE TITLE
Excessive Logging?

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#3023]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.3.0

### What did you do?
If possible, provide a recipe for reproducing the error.
Set a deadline in an interceptor higher than context deadline.

### What did you expect to see?
The lower of the two enforced.

### What did you see instead?
The lower of the two enforced, with a lot of logging :)

May 19, 2017 3:39:39 PM io.grpc.internal.ClientCallImpl logIfContextNarrowedTimeout
INFO: Call timeout set to '1999578360' ns, due to context deadline. Explicit call timeout was '4999976265' ns.

Is this intentional to log at INFO, and if so, should I just change my logging config to silence this class?

**Comment by ejona86** [comment]
Updating this to FINE seems good. INFO for every RPC for a pretty normal case seems overboard. Wanna send a PR?

**Comment by jhspaybar** [comment]
Sure, I'll send one in.

**Comment by hsaliak** [comment]
@ejona86 can we close this issue?

**Comment by ejona86** [comment]
Fixed by #3028
