### ISSUE TITLE
hbase-client-1.3.1is protobuf-2.5   conflict with  grpc-1.2.0 is protobuf-3.2  ，so how can  I use this two package in one procket

### ISSUE THREAD

**Issue by niyuelin1990** [grpc/grpc-java#3035]
my pom file:
              
```
  <dependency>
			<groupId>org.apache.hbase</groupId>
			<artifactId>hbase-client</artifactId>
			<version>1.3.1</version>
			<exclusions>
				<exclusion>
					<groupId>io.netty</groupId>
					<artifactId>netty</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
               <dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-protobuf</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-stub</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>3.2.0</version>
		</dependency>
```

hbase-client 's protobuf  conflict with  grpc-1.2.0's  protobuf

**Comment by ejona86** [comment]
Please provide any error message you received.

In general, you should simply use protobuf v3.2. Since 3.0.0-beta-4, protobuf 3.x [is compatible with generated code from 2.5.0 and 2.6.1](https://github.com/google/protobuf/releases/tag/v3.0.0-beta-4).

**Comment by ejona86** [comment]
I assuming the solution of using the newer protobuf works for you. If not, please comment and we can reopen.

**Comment by KarlZhaoQiMing** [comment]
The class com.google.protobuf.LiteralByteString is deleted from 2.6.0, how can protobuf 3.x be compatible with generated code from 2.5.0 and 2.6.1?

**Comment by ejona86** [comment]
@KarlZhaoQiMing, the generated code doesn't use `LiteralByteString`. In fact, [even 2.5.0 didn't have LiteralByteString _as part of the API_](https://github.com/google/protobuf/blob/v2.5.0/java/src/main/java/com/google/protobuf/LiteralByteString.java#L52) (it's package-private). Looking at google/protobuf#1717 and trying to remember what was going on, I'm remembering now that [HBase cheated](https://github.com/apache/hbase/blob/3ed68fd70d7ee187553627998ee39581309296e2/hbase-protocol/src/main/java/com/google/protobuf/HBaseZeroCopyByteString.java#L18) to use it.

I see even in v1.0.0 hbase [can fall-back to avoid HBaseZeroCopyByteString](https://github.com/apache/hbase/blob/rel/1.0.0/hbase-protocol/src/main/java/org/apache/hadoop/hbase/util/ByteStringer.java#L46), but it appears it may not be catching enough exceptions (like `NoClassDefFoundError`).

**Comment by markthegrea** [comment]
Ping!  Having the same trouble here.  Any suggestions?

**Comment by ejona86** [comment]
@markthegrea, I suggest "complain to HBase."

**Comment by mjpitz** [comment]
Opened ticket in HBASE to address package private class reference: https://issues.apache.org/jira/browse/HBASE-21587

**Comment by sduskis** [comment]
@mjpitz and @niyuelin1990, I think that the `hbase-shaded-client` artifact would solve this problem.  Cloud Bigtable (see this [pom.xml](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-hbase/pom.xml#L74)) and apache beam (see this [builder.gradle](https://github.com/apache/beam/blob/master/sdks/java/io/hbase/build.gradle#L44)) use it to avoid this problem.
