### ISSUE TITLE
Netty does not support TLS on Android

### ISSUE THREAD

**Issue by tadblack** [grpc/grpc-java#3041]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Currently i'm using gRPC 1.3.0

### What JVM are you using (`java -version`)?
Using openjdk 1.8.0, Android version 25

### What did you do?
If possible, provide a recipe for reproducing the error.
I'm trying to create a secured server on an android device. To do so i created the following method:

` public ServerAndroid(LogicInfo infoManager, GroupInfo groupInfo)  {
        this.infoManager = infoManager;
        this.groupInfo = groupInfo;
        this.serverListener = ServerListener.NO_LISTENER;

        InputStream certificate = infoManager.getContext().getResources().openRawResource(R.raw.cert);
        InputStream key = infoManager.getContext().getResources().openRawResource(R.raw.key);
        try {

            this.keyserver = File.createTempFile("key", "pem");
            this.cert = File.createTempFile("cert","pem");
            FileUtils.copyInputStreamToFile(certificate, this.cert);
            FileUtils.copyInputStreamToFile(key, this.keyserver);
        } catch (IOException e) {
            e.printStackTrace();
        }

        this.server = ServerBuilder.forPort(LogicConstants.DEFAULT_SERVER_PORT)
                .useTransportSecurity(this.cert, this.keyserver)
                .addService(new InnerServer()).build();

    }`

The thing is, when I compile the project it returns an error "java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured." 
I searched everywhere, and everyone says to run -Xbootclasspath/p:<alp-boot-version.jar>. but I can't do that on Android.
I tried to insert a compile dependencie on gradle (  compile 'org.mortbay.jetty.alpn:alpn-boot:8.1.11.v20170118' ) but when I try to run the project it gives the error:
 Error converting bytecode to dex: Cause: Dex cannot parse version 52 byte code. This is caused by library dependencies that have been compiled using Java 8 or above. If you are using the 'java' gradle plugin in a library submodule add targetCompatibility = '1.7' sourceCompatibility = '1.7' to that submodule's build.gradle file. ...while parsing org/eclipse/jetty/alpn/ALPN.class

### What did you expect to see?
No error.

### What did you see instead?
java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.

**Comment by ejona86** [comment]
The Netty transport (not the Netty project) is not supported on Android. I've seen that it is possible to some degree, but TLS would be broken.

**Comment by tadblack** [comment]
Thank you for the reply.
Do you know any alternative so I can create a secured channel in gRPC?

**Comment by ejona86** [comment]
I believe the C++ server works on Android. May be a pain to build, and is probably not the sort of alternative you would be looking for :).

There's work to bring Conscrypt to the JDK as an alternative to netty-tcnative. That is still a ways away, but afterward it is probably easier to support TLS for Netty server on Android.

**Comment by tadblack** [comment]
It's an alternative nevertheless. ;)
Thank you very much for the replies.
I'm going to close the issue.
Best regards.
