### ISSUE TITLE
Reduce number of flushes

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#305]
Each flush causes its own TCP frame to be written because we Nagle is disabled. Reducing the number of flushes would greatly reduce the number of TCP frames and number of syscalls. Even if performance benchmarks don't show a benefit by reduced flushing, if we are able to see improvements to goodput that would be enough for such an optimization.

Reduce number of flushes, in gRPC and maybe Netty.

May need a batch write API. We have the ability internally already, it is deciding a way to expose it.

Allow hint to delay headers until first data write (could maybe be part of batch API).

**Comment by nmittler** [comment]
@ejona86 At this point, can we call this a dup of #331 and #332?

**Comment by ejona86** [comment]
This issue brings up the topic of a batch API. @louiscryan, do we want an issue open for batch-write support?

**Comment by ejona86** [comment]
A lot has happened on this front in both Netty and gRPC. There is now a WriteQueue in gRPC that reduces the number of times we flush. The http/2 code in Netty now has clearly defined flush model such that it no longer flushes itself (there may be one edge case). Also #502 has batch API discussion which turned into corking PR #996.

There doesn't seem to be a need for this issue any more. If shortcomings are found, we can make a new issue for them.
