### ISSUE TITLE
OverrideAuthorityNameResolverFactory fails to forward NameResolver.refresh()

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#3061]
It seems we should create a `ForwardingNameResolver` and use it in `OverrideAuthorityNameResolverFactory`. Let's keep the new forwarding class internal for now.

**Comment by zpencer** [comment]
Fixed in v1.4.x with https://github.com/grpc/grpc-java/commit/e4f1f398a0f92cc09054c351ea6c5e6816459c77 , will bring this change to master once the server builder PR is merged

**Comment by carl-mastrangelo** [comment]
Does this still need to be done?

**Comment by zpencer** [comment]
This is merged to v1.4.x to make the cut, but I was waiting for #3029 before merging to master. I think I'll just merge it now to close this, since whatever conflict that may arise can be easily fixed.

**Comment by ejona86** [comment]
#3029 is now in master.
