### ISSUE TITLE
maven's grpc plugin is unable to resolve google.protobuf.Empty

### ISSUE THREAD

**Issue by mgenov** [grpc/grpc-java#3127]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0

### What JVM are you using (`java -version`)?
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### protoc version
libprotoc 3.3.0

### Properties

```xml
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <kotlin.version>1.1.2-5</kotlin.version>
    <grpc.version>1.4.0</grpc.version><!-- CURRENT_GRPC_VERSION -->
  </properties>
```

### Plugin definition
```xml
  <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.5.0</version>
        <configuration>
          <protocArtifact>com.google.protobuf:protoc:3.3.0:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
Extensions
```xml
<build>
 <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.4.1.Final</version>
      </extension>
    </extensions>
   ....
</build>
```

### What did you do?
mvn clean compile

### What did you expect to see?
BUILD SUCCESS

### What did you see instead?
[INFO] Compiling 2 proto file(s) to ..../target/generated-sources/protobuf/java
[ERROR] PROTOC FAILED: myservice.proto:40:59: "google.protobuf.Empty" is not defined.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

I'm I able to resolve it or I have to define my own Empty message ? 

**Note** that the google.api.http type is resolved successfully.

**Comment by ericgribkoff** [comment]
This looks like a problem with the configuration of `protobuf-maven-plugin`, not gRPC specifically: the error indicates that protoc cannot find `google.protobuf.Empty`, which would cause protoc to fail with or without the gRPC code generation plugins. https://github.com/google/protobuf/issues/289 indicates that protos for the well-known types (including `Empty`) are included in the protobuf release, but I'm not sure how to make sure `protobuf-maven-plugin` can pick them up.

Unless someone else on the gRPC team has knowledge about this, you might want to try asking on https://github.com/xolstice/protobuf-maven-plugin/issues.

**Comment by mgenov** [comment]
I've submitted an issue at https://github.com/xolstice/protobuf-maven-plugin/issues/28

Thanks for your feedback.
