### ISSUE TITLE
Can I create client Channel from java Socket?

### ISSUE THREAD

**Issue by so61pi** [grpc/grpc-java#3132]
Is there a way to create the `ManagedChannel` from an existing Socket object instead of calling `ManagedChannelBuilder.forAddress(host, port)`?

**Comment by carl-mastrangelo** [comment]
Yes, use [NettyChannelBuilder.forAddress](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L89)

**Comment by so61pi** [comment]
From what I understand, `NettyChannelBuilder.forAddress` uses a `SocketAddress` to connect to a server. What I mean is creating a Channel from an already established [`Socket`](https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html).

**Comment by carl-mastrangelo** [comment]
@so61pi Ah, sorry no.  The transport we support today expect a lot of control over their sockets (like setting non-blocking IO, exclusive access, no concurrency, etc.)  

Can you describe more what you are trying to do?

**Comment by so61pi** [comment]
In our current project, we have an embedded-device (using Linux, apps written in C++) on a car that the web-server (written in Java) can queries the car's data (e.g. speed, engine speed...) then displays them on a web page.

To do that, the embedded-device acts as the gRPC server and the web-server is the client side of gRPC. But the connection between device and web-server is established by the device.

Therefore, I'm looking for a way to create the gRPC client (in the web-server) from an existing connection, but it seems there is no way to do it now.

**Comment by carl-mastrangelo** [comment]
I have heard this called port sharing, and we have something internally that takes similar action.  It isn't impossible with gRPC, but it's off the beaten path.  For servers you can stuff in a ProtocolNegotiator that hooks the netty pipeline and has direct access to the channel.  However for clients there isn't such a similar action.

I wouldn't be opposed if you want to make a patch to add such a feature; I have had need of that in other projects.  It may be more work than a few lines though.

**Comment by ejona86** [comment]
This is less port sharing and closer to reverse tunneling. We've seen the use case a couple times where the roles of client/server are reversed, and it comes up when punching holes in firewalls.

There have been some larger plans to allow this is a quite generic way (by allowing the server to still serve on the port). Your needs are simpler. You could do this with a custom `LocalChannel` proxy on client-side and server-side, but that would require some Netty knowledge (although not technically very much code) but would be able to work in gRPC today.

Netty lets you pass a `SocketChannel` to `NioSocketChannel`'s constructor, but gRPC expects to create the channel using the bootstrap. The same is true for `Socket` to `OioSocketChannel`'s constructor. But I really don't see a way that we could easily plumb that for gRPC.

**Comment by so61pi** [comment]
Well, I should look for another solution for this kind of problem. Thanks for your explanation.
