### ISSUE TITLE
No functional channel service provider found after shading io.grpc 

### ISSUE THREAD

**Issue by jingliucsd** [grpc/grpc-java#3141]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4

### What JVM are you using (`java -version`)?
1.8

### What did you do?

I have a code base that relies on Guava 14.0 and I would also like to use gRPC in my project.
gRPC needs Guava 19.0, which is not compatible with Guava 14.0.

Following some instructions online (https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html), I tried to shade/relocate gRPC library using the following pom.xml file.

I manually rename affected classed in the files that protobuf generates. The project builds fine, but when I ran it, I got the following error msg:

com.shade.io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

As shown in the pom.xml, those dependencies have been added.

If possible, provide a recipe for reproducing the error.

```<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.shade</groupId>
    <artifactId>shade_grpc</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-okhttp</artifactId>
            <version>1.4.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>com.google.common</pattern>
                                    <shadedPattern>com.shade.google.common</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.grpc</pattern>
                                    <shadedPattern>com.shade.io.grpc</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.netty</pattern>
                                    <shadedPattern>com.shade.io.netty</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

### What did you expect to see?

expect it to run without exceptions

### What did you see instead?

 The project builds fine, but when I ran it, I got the following error msg:

com.shade.io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

As shown in the pom.xml, those dependencies have been added.

**Comment by carl-mastrangelo** [comment]
@jingliucsd can you run `unzip -l output.jar` on the file you generated?  There should be a META-INF/services directory which links to the service loader files.

**Comment by ejona86** [comment]
It's [a bug](https://issues.apache.org/jira/browse/MSHADE-229) in the maven-shade-plugin. Upgrade to 3.0 and [enable the `ServicesResourceTransformer`](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#Concatenating_Service_Entries_with_the_ServicesResourceTransformer).

**Comment by jingliucsd** [comment]
@ejona86  really appreciate your help! It works now. 

And I also want to share some unsuccessful efforts I made, just in case someone encountered similar issues in the future.

Merely shading com.google.com may not work. It can solve the "No functional channel service provider found" issue but my program somehow hangs. Seems like some deadlocking issue.
