### ISSUE TITLE
I try to connect to server gRPC with socket NIO but server not response.

### ISSUE THREAD

**Issue by Wkbaf** [grpc/grpc-java#3171]
I try to connect to server gRPC with socket NIO but server not response.
When client gRPC request to socket like that; 
 PRI * HTTP/2.0

SM

 

I am not sure about it. Please help.

**Comment by ericgribkoff** [comment]
There's not enough information here to adequately diagnose the issue. If you click on the 'New Issue' button, you'll see a template describing what information we need to help you. Can you reply here with the answers to the questions in the new issue template?

**Comment by ejona86** [comment]
Closing because we needed more information and there wasn't a response.
