### ISSUE TITLE
com_google_protobuf() and com_google_protobuf_java() are identical

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#3175]
If this was intended, documentation should be added. Otherwise one of them should be removed.
```
def com_google_protobuf():
  native.http_archive(
      name = "com_google_protobuf",
      sha256 = "df77b0e60afcd3d90b2654cd305e61ae8ae2e2281b4d6540c7093da4c4245d75",
      strip_prefix = "protobuf-3.3.1",
      urls = ["https://github.com/google/protobuf/archive/v3.3.1.zip"],
  )

def com_google_protobuf_java():
  native.http_archive(
      name = "com_google_protobuf_java",
      sha256 = "df77b0e60afcd3d90b2654cd305e61ae8ae2e2281b4d6540c7093da4c4245d75",
      strip_prefix = "protobuf-3.3.1",
      urls = ["https://github.com/google/protobuf/archive/v3.3.1.zip"],
  )
```

**Comment by ejona86** [comment]
`com_google_protobuf` chooses the version of protoc to use. `com_google_protobuf_java` chooses the version of the java runtime to use. The choices are independent. These dependencies are necessary for Bazel's java_proto_library. See [the Bazel post for LANG_proto_library support](https://blog.bazel.build/2017/02/27/protocol-buffers.html).

It does seem references within protobuf-lite/BUILD.bazel and examples/BUILd.bazel may be using the wrong name.
