### ISSUE TITLE
Enable Stetho for Android by exposing OkHttpClient

### ISSUE THREAD

**Issue by notnil** [grpc/grpc-java#3176]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0

### What JVM are you using (`java -version`)?
Android's Java

### What did you do?
If possible, provide a recipe for reproducing the error.
N/A

### What did you expect to see?
Can access the underlying OkHttpClient

### What did you see instead?
Can't access the underlying OkHttpClient

**Comment by notnil** [comment]
Stetho  link: http://facebook.github.io/stetho/

**Comment by carl-mastrangelo** [comment]
I may be mistaken, but I don't know if we actually use OkHttpClient.  We grab a lot of the okhttp internals for framing, but I don't see any actual refs to it in our code.

**Comment by ericgribkoff** [comment]
As Carl says, gRPC doesn't use OkHttpClient to manage connections, which is why you are unable to access it to add the Stetho interceptor. As an alternative, it might be possible to re-implement [StethoInterceptor](https://github.com/facebook/stetho/blob/master/stetho-okhttp/src/main/java/com/facebook/stetho/okhttp/StethoInterceptor.java) as a [gRPC interceptor](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ClientInterceptor.java), although I haven't looked deeply into the OkHttp interceptor semantics to be sure this will map correctly to the gRPC concept.

**Comment by notnil** [comment]
Can you recommend any alternatives for debugging gRPC on Android?

**Comment by ericgribkoff** [comment]
What types of issues are you trying to debug? Android Studio has a lot of support built-in, see https://developer.android.com/studio/debug/index.html.

**Comment by carl-mastrangelo** [comment]
If you are running in an emulator, capturing packets on the host machine would be my first start.  If running on an actual device, logcat with gratuitous log statements and usb debugging would be the next bet.

**Comment by notnil** [comment]
So apparently the Android Studio 3.0 preview has a native network inspector that looks a lot like Google chrome's: 

https://developer.android.com/studio/profile/network-profiler.html

This should solve the issue.

**Comment by ericgribkoff** [comment]
@notnil Was the gRPC-related traffic captured in the Android Studio 3.0 network profiler sufficient for your needs? I just gave it a try myself, and it is a very nice tool - but it's designed for displaying full details about files sent/received, so it doesn't currently display stats about individual RPCs, just the aggregate network traffic of the app. 

If that's all you needed, great. If not, feel free to update here with more specifics about what you were looking for. Right now your best bet for RPC-level logging information is what Carl said, just logging the RPCs to logcat, but we can consider adding better support for debugging tools in the future.

**Comment by gengjiawen** [comment]
Integrate with stetho will be great, because it can show the request in realtime.
