### ISSUE TITLE
Remove String allocation in MutableHandlerRegistryImpl.lookupMethod(String).

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#318]
In QPS benchmarks we spend roughly 1% of the total allocations on allocating String objects when doing a `substring` on the method name.
![screenshot from 2015-04-20 14 11 14](https://cloud.githubusercontent.com/assets/1388179/7240604/24c359ca-e767-11e4-9976-b7826bac9be9.png)

**Comment by carl-mastrangelo** [comment]
This appears to be fixed, since there is no more `substring` here or in other parts of the handlers.
