### ISSUE TITLE
CodedInputStream and CodedOutputStream always allocate a fixed 4KB byte array.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#319]
Protobuf's `CodedInputStream` and `CodedOutputStream` always allocate 4KB sized byte arrays in their constructor. For small messages this is overkill and we should investigate if we can reduce this. On QPS benchmarks our heap consists for roughly 30% of those byte arrays. So this can have a big impact for memory usage.

**Comment by carl-mastrangelo** [comment]
This was "fixed" in #2159, which pays one copy in order to avoid two.  There is nothing to do here until the new proto API comes out.
