### ISSUE TITLE
Implement compression interop tests

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc-java#3195]
There are four compression interop tests defined in [interop-test-descriptions.md](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md) but not implemented for Java:

- client_compressed_unary
- client_compressed_streaming
- server_compressed_unary
- server_compressed_streaming

These should be implemented and enabled in [run_interop_tests.py](https://github.com/grpc/grpc/blob/master/tools/run_tests/run_interop_tests.py).

**Comment by ejona86** [comment]
server_compressed_unary and server_compressed_streaming cannot be implemented in Java, because the compressed message flag is not available and we have no want to expose such a feature. Last I heard, the cross-language expectation is that only C++ will implement those tests.

**Comment by ericgribkoff** [comment]
The decision for now was to just implement these on the client-side, because, as @ejona86 points out, Java has no mechanism to implement the [CompressedRequest](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#compressedrequest) server-side feature of the interop test specification, which is necessary for server-side implementation of `client_compressed_unary` and `client_compressed_streaming` (in these tests, the client sends compressed/uncompressed messages and the server must verify the requests are compressed/uncompressed).

The client-side tests in PR #3211 include `server_compressed_unary` and `server_compressed_streaming`, designed to be run against a C++ server implementation that can respond appropriately to the `request_compressed` flag in the request messages. The Java clients cannot actually assert that the server's responses are compressed/uncompressed<sup>[1]</sup>, and https://github.com/grpc/grpc/pull/11739 updates the interop test descriptions to allow for this limitation.

***
[1]: Technically, the Java client could override  `MethodDescriptor.Marshaller#parse(InputStream stream)` to do a `stream instanceof KnownLength` to determine if the message was received compressed (does not implement `KnownLength`) or uncompressed (does implement `KnownLength`), but this is decidedly not an intended use of the API, and it does not add enough value to the test coverage to be worth supporting this type of use.

**Comment by ericgribkoff** [comment]
Closed via #3211.
