### ISSUE TITLE
wired build error in a grpc and protobuf project and the build tool is Basel

### ISSUE THREAD

**Issue by zhexuany** [grpc/grpc-java#3200]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.2

### What JVM are you using (`java -version`)?
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
### What did you do?
If possible, provide a recipe for reproducing the error.
`bazel build `failed after we used `maxInboundMessageSize(max)` used in our project. 

### What did you expect to see?
successfully built since this API was brought since 1.1.0
### What did you see instead?

`bazel build `failed after we used `maxInboundMessageSize(max)` used in our project. 
```
error: cannot find symbol
                        .maxInboundMessageSize(MAX_MSG_SIZE)
                        ^
  symbol:   method maxInboundMessageSize(int)
  location: class ManagedChannelBuilder<CAP#1>
  where CAP#1 is a fresh type-variable:
    CAP#1 extends ManagedChannelBuilder<CAP#1> from capture of ?
```

**Comment by ejona86** [comment]
Maybe you aren't actually using 1.2? For example, maybe you updated the protoc plugin but not the java library?

I just tested this by modifying the helloworld example and building with Bazel (since master now has Bazel support), and it compiled fine. I also agree that the API was added in 1.1.0.

**Comment by zhexuany** [comment]
You are absolutely right. closing this issue.
