### ISSUE TITLE
Improve synchronization of SerializingExecutor.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#322]
We are seeing some contention in `ChannelImpl.obtainActiveTransport()` and `SerializingExecutor`.

![serializing](https://cloud.githubusercontent.com/assets/1388179/7241437/c9678748-e76d-11e4-8c6a-8604223688e7.png)

![obtain](https://cloud.githubusercontent.com/assets/1388179/7241450/dc87a7ea-e76d-11e4-9ac1-7e91aca98c6b.png)

**Comment by ejona86** [comment]
obtainActiveTransport improvement split out into #479.

**Comment by ejona86** [comment]
@louiscryan tried some optimizations in #1050 and wasn't able to see much difference. Our thought right now is that `SerializingExecutor` is "optimal enough", although the class may be changed in the future for larger-scale optimizations.
