### ISSUE TITLE
ClientStreamTracer instances are threadsafe, but mocks of it aren't

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#3240]
In `AbstractInteropTest`,  instances of `ClientStreamTracer` are created using `spy`.  These instances are not thread safe and cause the race detector to complain about it.

ClientStreamTracer and the other stream tracers should probably be marked DoNotMock because the mocks will not be able to fulfill the API.

**Comment by carl-mastrangelo** [comment]
@zhangkun83 ping

**Comment by zhangkun83** [comment]
It's already been fixed by @carl-mastrangelo
