### ISSUE TITLE
"gradlew installDist" gives error No tool chain is available to build for platform 'x86_64':

### ISSUE THREAD

**Issue by gqqnbig** [grpc/grpc-java#3245]
I'm following https://grpc.io/docs/quickstart/android.html

### What JVM are you using (`java -version`)?
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

When I run `$ ./gradlew installDist` on my Windows 10 x64, it throws exception

FAILURE: Build failed with an exception.

> * What went wrong:
> Execution failed for task ':grpc-compiler:compileJava_pluginExecutableJava_pluginCpp'.
> > No tool chain is available to build for platform 'x86_64':
>     - Tool chain 'visualCpp' (Visual Studio): Could not locate a Visual Studio installation, using the Windows registry and system path.
>     - Tool chain 'gcc' (GNU GCC): Could not find C compiler 'gcc' in system path.
>     - Tool chain 'clang' (Clang): Could not find C compiler 'clang' in system path.

But I did install Visual Studio 2017 Preview.

How to fix the issue?

**Comment by ericgribkoff** [comment]
Resolved on the mailing list: https://groups.google.com/forum/#!topic/grpc-io/Bkz4VB1WSsU
