### ISSUE TITLE
Android ClientInterceptor not working to add metadata ?

### ISSUE THREAD

**Issue by kraghu** [grpc/grpc-java#3246]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0 on android .
 compile 'io.grpc:grpc-okhttp:1.4.0'
 compile 'io.grpc:grpc-protobuf:1.4.0'  
 compile 'io.grpc:grpc-stub:1.4.0'

### What JVM are you using (`java -version`)?
java 8

### What did you do?
If possible, provide a recipe for reproducing the error.
I am trying to add a custom header to my grpc call using metadata inside ClientInterceptor. I am unable to send as explained here ,
https://stackoverflow.com/questions/45125601/android-how-to-add-a-custom-header-in-grpc-client
### What did you expect to see?
I am expecting server to recognize this parameter and send extra data items. 

### What did you see instead?
When I use okhttp3 alone and send this as header "Grpc-Match-Metadata", "match.items" with requestbody. i receive the extra data as I expect . But am unable to get any extra items  in grpc call .

===
I might be doing some thing wrong . I appreciate if some one could point to it

**Comment by ericgribkoff** [comment]
At first glance, your code looks to be correctly setting the metadata on the client side. It takes a bit of additional code on the server to access the metadata. Did you follow the server-side code example at https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/header/HeaderServerInterceptor.java?
Also, could you elaborate on what you mean when you say it's working in rest call format? 

To further debug, you can also turn on verbose logging for the server by putting the following text into a `logging.properties` file:

```
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = ALL

.level = FINE
io.grpc.netty.NettyClientHandler = ALL
io.grpc.netty.NettyServerHandler = ALL
```
And running the server with:

```
env JAVA_OPTS=-Djava.util.logging.config.file=logging.properties build/install/examples/bin/hello-world-server
```

Then run the client, and your server-side output should include something like:

```
Jul 16, 2017 11:59:25 AM io.netty.handler.codec.http2.Http2FrameLogger log
FINE: 
----------------INBOUND--------------------
[id: 0x10011f8b, L:/127.0.0.1:50051 - R:/127.0.0.1:49199] HEADERS: streamId=3, headers=GrpcHttp2RequestHeaders[:path: /helloworld.Greeter/SayHello, :authority: localhost:50051, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.4.0, grps-key: primary.secondary, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
------------------------------------
```

Note the `grps-key` value there, indicating the server received the metadata from the client.

**Comment by kraghu** [comment]
@ericgribkoff Thank you for your response. I updated the rest call information in my question. Our server is in go. I am expecting the server to recognize it when i make grpc call like it responds back for okhttp3.  I didnt bother on asking server side thats why. is there a way to enable grpc level logs in android to see what I am sending like you pointed out for server side ?

**Comment by ericgribkoff** [comment]
You can configure the Java logging on Android programmatically. There are nicer ways to do this, but a quick hack is the following code (with appropriate try/catch) before you make your calls to gRPC:

```
String loggingConfig =
    "handlers=java.util.logging.ConsoleHandler\n"
        + "io.grpc.level=FINE\n"
        + "java.util.logging.ConsoleHandler.level=FINE\n"
        + "java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter";
java.util.logging.LogManager.getLogManager()
    .readConfiguration(
        new java.io.ByteArrayInputStream(
            loggingConfig.getBytes(java.nio.charset.StandardCharsets.UTF_8)));
```

However, I still don't understand what you mean about rest calls, or okhttp3. Neither of those are related to gRPC. Is your server actually a gRPC server?

**Comment by kraghu** [comment]
thanks @ericgribkoff  this is helpful.
rest call as in I tried to use non-grpc network call using just okhttp library and it was successful
