### ISSUE TITLE
Determine upper-bound for Netty buffer sizes used in frame

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#325]
As a follow on to

https://github.com/grpc/grpc-java/issues/312

we need benchmarks to determine whether we should be placing an upper-bound on the buffers allocated to the MessageFramer from Netty. We are already setting a lower-bound to page-size (default is 8k) to facilitate buffer object caching within Netty as well as allowing for follow-on writes.

Setting an upper-bound should probably be done by benchmark (unless one already exists)
Above the Netty arena size (currently 16MB) Netty will allocate an Unpooled buffer. Above 32k Netty takes an arena lock to allocate a buffer out of the arena (i.e. it will not cache the buffer itself)

See https://www.facebook.com/notes/facebook-engineering/scalable-memory-allocation-using-jemalloc/480222803919
for the scheme Netty follows

**Comment by ejona86** [comment]
Why do you say:
> We are already setting a lower-bound to page-size (default is 8k)

I don't see where we are doing that.

**Comment by louiscryan** [comment]
Sorry, that should have been 4k. Based on Netty's buffer benchmarks there is no appreciable difference betweekn 4k & 16k buffer allocations when ThreadLocal caching is in effect. There is no throughput difference in the allocator between 4k & 16k buffers so we can happily choose either as our minimum. Going to 64k prevents the thread-local cache from working which is why we see a step in performance,

https://gist.github.com/louiscryan/c5997da99c51b5893a00

**Comment by louiscryan** [comment]
@normanmaurer Hey Norman, got any advice for us on this one. We have the ability to chunk messages to make optimal use of PooledBufferAllocator and we're trying to determine upper and lower bounds on the chunks to maximize efficiency.

We're setting a lower-bound currently to page-size (8k) in part because we would sometimes like to absorb writes that occur after the allocation so having some padding for that can be useful. 

The more interesting question is what to set as an upper-bound.

**Comment by normanmaurer** [comment]
@louiscryan gimme till tomorrow, it's quite late here already and want to think a bit about it :)

**Comment by normanmaurer** [comment]
@louiscryan so I think everything <= 32k is fine as this can be served from the cache by default.

**Comment by nmittler** [comment]
Fixed by #313
