### ISSUE TITLE
Logging all messages using ClientInterceptor

### ISSUE THREAD

**Issue by ccascone** [grpc/grpc-java#3253]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.3.0

### What JVM are you using (`java -version`)?
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

### What did you do?
I'm trying to use interceptor to log all messages sent and received from a client.

The implementation of the ClientInterceptor looks like this

``` java
@Override
public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(MethodDescriptor<ReqT, RespT> methodDescriptor,
                                                           CallOptions callOptions, Channel channel) {
    return new ForwardingClientCall.SimpleForwardingClientCall<ReqT, RespT>(
            channel.newCall(methodDescriptor, callOptions.withoutWaitForReady())) {

        @Override
        public void sendMessage(ReqT message) {
            log.info("*** SENDING GRPC MESSAGE [{}]\n{}:\n{}", deviceId, methodDescriptor.getFullMethodName(),
                     message.toString());
            super.sendMessage(message);
        }

        @Override
        public void start(Listener<RespT> responseListener, Metadata headers) {

            ClientCall.Listener<RespT> listener = new ClientCall.Listener<RespT>() {
                @Override
                public void onMessage(RespT message) {
                    log.info("*** RECEIVED GRPC MESSAGE [{}]\n{}:\n{}", deviceId,
                             methodDescriptor.getFullMethodName(),
                             message.toString());
                    super.onMessage(message);
                }
            };
            super.start(listener, headers);
        }
    };
}
```
The first RPC i request after creating the channel is SayHello from the following service definition:

```protobuf
service DummyService {
    rpc SayHello (DummyMessageThatNoOneWouldReallyUse) returns (DummyMessageThatNoOneWouldReallyUse) {
    }
}

message DummyMessageThatNoOneWouldReallyUse {
}
```

### What did you expect to see?
When executing the SayHello RPC, I expect to see two messages in the log, one with the request message sent and one with the response message received.

### What did you see instead?

I only see the request message, it seems that the execution of the interceptor thread hangs and the response message is never logged/processed.

**Comment by zpencer** [comment]
It looks like the listener you are using is a `new ClientCall.Listener`, you are effectively subclassing the abstract class directly. What you instead want is:
```
ClientCall.Listener<RespT> listener = new ForwardingClientCallListener<RespT>() {
            @Override
            protected Listener<RespT> delegate() {
              return responseListener;
            }

            @Override
            public void onMessage(RespT message) {
              System.out.println("receive: " + message);
              super.onMessage(message);
            }
          };
```

**Comment by ccascone** [comment]
@zpencer thank you! It works now.
