### ISSUE TITLE
Passing CallOptions to ClientStreamTracer.newClientStreamTracer

### ISSUE THREAD

**Issue by elandau** [grpc/grpc-java#3256]
Any thoughts on passing the CallOptions into ClientStreamTracer.newClientStreamTracer?  We have an interceptor chain with roughly 10 interceptors.  The first interceptor sets a MetricsContext and our internal implementation of ClientStreamTracer.Factory on the CallOptions.  Each subsequent interceptor may add tags to the MetricsContext.  MetricsContext is hierarchical so we can have sub contexts for things like retries and hedged requests.  We'd need access the MetricsContext from our ClientStreamTracer implementation.  The contract would look something like, 

```java
public abstract ClientStreamTracer newClientStreamTracer(CallOptions callOptions, Metadata headers);
```

Alternatively, we could track our MetricsContext as described above but only specify the ClientStreamTracer.Factory in the last interceptor.  I'm not sure this approach will work long term as it sounds like your guys are leaning towards setting the ClientStreamTracer.Factory on the channel as opposed to the CallOptions (which I like as it would be more consistent with how things are done on the server).

**Comment by ericgribkoff** [comment]
@zhangkun83 Any thoughts on this?

**Comment by zhangkun83** [comment]
I think passing `CallOptions` to `newClientStreamTracer()` is pretty reasonable. We use `CallOptions` as the vehicle to pass custom information among interceptors and to the `LoadBalancer`. Some information may be interesting to stats and tracing. @ejona86 WDYT?

**Comment by ejona86** [comment]
Doesn't bother me at all, especially since we already expect some tracers to use a `ClientInterceptor` in concert with the `ClientStreamTracer`.

**Comment by zhangkun83** [comment]
I will send a PR very quick.

**Comment by elandau** [comment]
Looks great!  Thanks!
