### ISSUE TITLE
UNAUTHORIZED if Auth Server is down?

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#3267]
We are using `GoogleAuthLibraryCredentials` to authenticate our gRPC calls and we sometimes have the case where the authentication fails, because the auth server is not reachable and then the call fails with `UNAUTHENTICATED` status code.

Some people on my team argue that it should fail with `UNAVAILABLE`, I personally think `UNAUTHENTICATED` makes sense, so that a user can distinquish between a call and auth having gone wrong. However, arguably [1] is not clear about this.

The discussion arose, because of retries. In Bazel, we want to retry certain status codes i.e. `UNAUTHENTICATED` if the server could not be reached, but not if it failed due to wrong credentials. Any thoughts?

cc: @ejona86 @zhangkun83 

[1] https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

**Comment by ejona86** [comment]
@jboeuf, I thought I remembered someone raising this issue before (against another repo, maybe on mailing list?) but couldn't track it down. Is C still doing UNAUTHENTICATED for I/O errors while retrieving auth tokens?

I know several of us felt UNAVAILABLE would be more appropriate when originally implementing, but the decision ended up being to use UNAUTHENTICATED.

**Comment by carl-mastrangelo** [comment]
Maybe SE/SRE can use `addSuppressed` (and throw Java 1.6 under the bus)

**Comment by ejona86** [comment]
@jboeuf, ping. Can we please fail with UNIMPLEMENTED if retrieving an OAuth token fails?

**Comment by jboeuf** [comment]
I'm confused. Do you really want UNIMPLEMENTED in this case?

**Comment by ejona86** [comment]
:( @jboeuf, sorry. That should have been UNAVAILABLE. Too many 'UN's

**Comment by ejona86** [comment]
:( @jboeuf, sorry. That should have been UNAVAILABLE. Too many 'UN's

**Comment by ejona86** [comment]
Okay, we'll swap this over. C is being swapped with grpc/grpc#13322

@dfawley, you may want to do the same.
