### ISSUE TITLE
Why does not implement Comparable for ByteString?

### ISSUE THREAD

**Issue by zhexuany** [grpc/grpc-java#3269]
I am looking for a proper way to make ByteString being comparable. I got one in my mind but it is pretty ugly. It would be super nice if `ByteString` implements Comparable.

**Comment by ericgribkoff** [comment]
`ByteString` is not actually a gRPC class. This question is more appropriate for https://github.com/google/protobuf. You might be able to get what you need with `ByteString#toByteArray` plus [ByteArrayComparator](http://directory.apache.org/mavibot/gen-docs/latest/apidocs/org/apache/directory/mavibot/btree/comparator/ByteArrayComparator.html), or have a look at Okio's [`ByteString#compareTo`](https://github.com/square/okio/blob/master/okio/src/main/java/okio/ByteString.java#L472) implementation.
