### ISSUE TITLE
Possible to use a web browser client ? (ie. gRPC-Web)

### ISSUE THREAD

**Issue by fabm22** [grpc/grpc-java#3271]
### What version of gRPC are you using?
1.4.0
### What JVM are you using?
1.8.0_66
### What did you do?
Tried to use a web client which follows the [gRPC-Web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) api. Specifically, i use the grpc-web client part generated from Typescript [here](https://github.com/improbable-eng/grpc-web).

### What did you expect to see?
Would like to see grpc-java talk successfully with a pure web/browser client.
Is it currently possible ?
Any example available ?

### What did you see instead?
Error in the form of a ```Http2Exception$StreamException```  when calling a grpc endpoint made with grpc-java.

Logs excerpt :   
```
[sandbox] [grpc-default-worker-ELG-4-3] WARN  [2017-07-23 19:41:22.643] i.g.n.NettyServerHandler | Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Content-Type is missing from the request
    at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
    at io.grpc.netty.NettyServerHandler.verifyContentType(NettyServerHandler.java:597)
    at io.grpc.netty.NettyServerHandler.onHeadersRead(NettyServerHandler.java:353)
    at io.grpc.netty.NettyServerHandler.access$500(NettyServerHandler.java:105)
( ..etc..)
``` 

Thanks a lot for any help.

**Comment by ejona86** [comment]
grpc-web is a different API and requires a proxy to convert from it to normal grpc. None of the grpc server implementations support direct access by grpc-web clients.

**Comment by fabm22** [comment]
Thanks a lot for answer. That's what I was getting from all this...
Would you have a particular recommendation for a typical use case of a proxy ?

Thx a lot.

**Comment by ejona86** [comment]
There's a you-have-to-be-whitelisted-to-see-the-code proxy developed by Google/gRPC that you can fill out [a form](https://docs.google.com/forms/u/0/d/15iRDHoP-VBenc4hWgKn7bk7IirJLgs0uh88nw1vi_Hc) (as seen on the official FAQ) to try to get access to. I honestly know little about its state, other than it actually exists and executes (not vaporware).

Alternatively, you can take a look at https://github.com/improbable-eng/grpc-web , and [the blog post](https://improbable.io/games/blog/grpc-web-moving-past-restjson-towards-type-safe-web-apis).

**Comment by fabm22** [comment]
Oh thanks for the heads up about the secret military grade insiders code.  
And yes that is the projet I thought I would give a try, particularly the proxy sub project [grpcwebproxy](https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy)

Thx, closing.
