### ISSUE TITLE
CompositeReadableBuffer and GC overhead

### ISSUE THREAD

**Issue by Gordiychuk** [grpc/grpc-java#3278]
### What version of gRPC are you using?
[master branch](https://github.com/grpc/grpc-java/commit/00fe090ac1e421c393277f8554b851c542319c98)

### What JVM are you using (`java -version`)?
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### What the problem?
Small messages send and receive via gRPC lead to many memory allocation via `CompositeReadableBuffer`. It's top by allocation in benchmark that send 32 bytes request and receive 16 bytes response.

![screenshot from 2017-07-26 19 30 32](https://user-images.githubusercontent.com/10699594/28632732-310f9940-723a-11e7-84c9-39a86ad553a2.png)

I think we can reduce allocation if change logic of this line https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/MessageDeframer.java#L303 because in this place creates temp CompositeReadableBuffer that uncessary https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/CompositeReadableBuffer.java#L51 instead of it we can write at once in target buffer.

**Comment by carl-mastrangelo** [comment]
Please run the benchmarks before and after this change.   You can run them with:

```
cd benchmarks
../gradle jmh
```

Of interest are the TransportBenchmark numbers.

**Comment by Gordiychuk** [comment]
@carl-mastrangelo https://gist.github.com/Gordiychuk/7c38e41b5ad75c914d666c611d9e5ced
