### ISSUE TITLE
Support setting the HTTP/2 flow control window in grpc.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#329]
It would be nice if we could set the HTTP/2 flow control window from grpc in order to be able to do meaningful throughput tests in different environments e.g. two of my cloud VMs have a bandwidth delay product of 485KByte/s (high latency and high bandwidth). So with the default flow control window of 64KB we can theoretically only ever reach 13% of the possible throughput on that network.

Would be nice to also add this as a command line flag to the QPS benchmarks.

@ejona86 @louiscryan @nmittler

**Comment by nmittler** [comment]
@buchgr the client allows you to set the [connection window](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/transport/netty/NettyChannelBuilder.java#L125) and the [initial stream window](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/transport/netty/NettyChannelBuilder.java#L136).  Looks like we just have to do the same thing on the server-side.

**Comment by louiscryan** [comment]
We definitely need something like this. Altering the QpsServer & Client to receive these values one the command line would be very useful too

**Comment by buchgr** [comment]
@nmittler @louiscryan 

I am in the process of updating the QPS stuff. I ll add this to it.

**Comment by louiscryan** [comment]
@buchgr Ping me when you have this so I can get rid of my Netty hacks to do proper testing of write-coalescing

**Comment by buchgr** [comment]
@louiscryan it's in grpc now and is part of the next QPS update.
