### ISSUE TITLE
Correct way to interrupt client call from ServerInterceptor?

### ISSUE THREAD

**Issue by IgorPerikov** [grpc/grpc-java#3298]
### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?
1.8.0_111

### What did you do?
I've made an interceptor that checks call metadata, gets custom token from it and if it's correct - continues the call, otherwise - interrupts it with `Status.PERMISSION_DENIED`. The question is - what is correct way to interrupt call chain in that case? 

my interceptor looks like:
```java
private class AuthInterceptor implements ServerInterceptor {
    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
            ServerCall<ReqT, RespT> call,
            Metadata headers,
            ServerCallHandler<ReqT, RespT> next
    ) {
        byte[] authBytes = headers.get(Metadata.Key.of("auth-bin", Metadata.BINARY_BYTE_MARSHALLER));
        if (isCorrect(authBytes)) {
            return next.startCall(call, headers);
        } else {
            call.close(Status.PERMISSION_DENIED, headers);
            return next.startCall(call, headers); // most questionable part for me
        }
    }

    /* ... */
}
```

as I understand it should be fine, and it seems so. But when I launched `ab -c 50 -n 100000` through my proxy where every request contains wrong token, I can see 1 or 2 log entries from my service that says, that it enters `onNext()` method on server side. My grpc service is defined as:
```proto
service ProductsService {
    rpc createProducts(stream Product) returns (ProductCreationSummary); 
}
```

Server constructing code:
```java
ServerBuilder.forPort(port).addService(new ProductsService()).intercept(new AuthInterceptor()).build();
```

if it's might be a bug, and not just some simple mistake, I'll provide more reproducible codes etc

**Comment by zpencer** [comment]
In the case where you already closed the call, you wouldn't want to invoke the application. So you want to instead do something like this:
```
call.close(Status.PERMISSION_DENIED, headers);
// Return a dummy server call to grpc. Do not allow application to be invoked.
return new ServerCall.Listener<ReqT>() {};
```
