### ISSUE TITLE
grpc-protobuf-lite 1.4.0 not resolve some classes on android

### ISSUE THREAD

**Issue by holysheep** [grpc/grpc-java#3299]
### What version of gRPC are you using?
1.4.0

### What JVM are you using (`java -version`)?
java version "1.8.0_144"

I generated `.proto` file with libprotoc 3.3.2 and followed java `README.md`, where I found notation about using grpc-protobuf-lite or grpc-protobuf-nano instead of grpc-protobuf for android client.

But in fact it won't compile, there are no such classes as `ExtensionRegistry`, `GeneratedMessageV3`, `Descriptors` etc. 
Grpc-protobuf dependency on the other hand works well.

**Comment by ejona86** [comment]
GeneratedMessageV3 is part of full protobuf, not lite. You are probably generating code for full protobuf, not lite. Make sure you are using the javalite protoc plugin. You can take a look at the [android example](https://github.com/grpc/grpc-java/blob/v1.5.0/examples/android/helloworld/app/build.gradle#L28). If you can't find the issue, can you post your build file?

**Comment by holysheep** [comment]
Thanks, didn't notice there is a separate lite generator for that.
