### ISSUE TITLE
Network retries or time outs

### ISSUE THREAD

**Issue by kraghu** [grpc/grpc-java#3304]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0 on Android

### What JVM are you using (`java -version`)?
1.8
### What did you do?
I am trying to add a retry policy. It seems grpc after network failure doesn't re-connect immidiately even when network is back. 

If possible, provide a recipe for reproducing the error.
- disable network n keep on aeroplane mode
- try to run the app 
- enable back network

You will see grpc doesn't connect back even when you retry so many times. it takes for 25-30 secs to retry again. 

### What did you expect to see?
grpc should connect immediately on network availability. I like to know the right amount of time for waiting . 

### What did you see instead?
it never connects back 

Is there a way to configure the retries ? or to get to know the retry connection time ?

**Comment by kraghu** [comment]
Thanks @ericgribkoff for the quick response.  I will wait for this PR .

**Comment by ericgribkoff** [comment]
Ooops, sorry about the incorrect assigning of this issue. Re-assigned to me, will update when it's ready.

**Comment by ejona86** [comment]
Related: https://github.com/grpc/grpc-java/issues/2169

**Comment by ejona86** [comment]
Closing, since this is being handled as part of #2169 (which added an API in 1.8 that should address this) and #3685 (to reduce the impact when not using the new API)
