### ISSUE TITLE
Custom gRPC marshaller for one of the service method

### ISSUE THREAD

**Issue by Gordiychuk** [grpc/grpc-java#3309]
### What version of gRPC are you using?
Latest snapshot https://github.com/grpc/grpc-java/commit/02cb718767fbf01da45ba541a2d6bfa7ad979d40

### What JVM are you using (`java -version`)?
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### What the problem?
I have a grpc service with 9 methods. One of the method very hot because contails many many repeatable objects inside protobuf, instead of deserialize it to proto on server side, I want put request in bynary form to off-head structure, and then process it as batch sequential read from off-head structure. 

For resolve problem describe above I want to override unmarshaller only for one of 9 methods, but generated code not allow do it easy and require copy-past whole generated class(`ServiceImplBase implements io.grpc.BindableService`) as a result adding a new method to my grpc service will bring pain.

To allow easier override marshaller maybe need change signature for generated method
```java
    @java.lang.Override public final io.grpc.ServerServiceDefinition bindService() {
      return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
```

**Comment by ejona86** [comment]
I'd suggest implementing `ServiceImplBase`, except for the one method you want to handle differently. Then call `bindService()` and create a modified `ServerServiceDefinition` based on the result.

Something to the effect of:
```java
ServerServiceDefinition orig = MyServiceImpl.bindService();
ServerServiceDefinition builder = ServerServiceDefinition
    .builder(orig.getServiceDescriptor().getName())
    .addMethod(mySpecialDescriptor, mySpecialImpl);
for (ServerMethodDefinition<?,?> origMethod : orig.getMethods()) {
  if (origMethod.getMethodDescriptor().getFullMethodName().equals(
      mySpecialDescriptor.getFullMethodName())) {
    continue; // skip redefined method
  }
  builder.addMethod(origMethod);
}
return builder.build();
```

**Comment by Gordiychuk** [comment]
bindService final that not allow override behaviour

```java
 @java.lang.Override public final io.grpc.ServerServiceDefinition bindService() {
      return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
          .addMethod(
            METHOD_SERVER_STATUS,
            asyncUnaryCall(
              new MethodHandlers<
                ru.yandex.stockpile.api.ServerStatusRequest,
                ru.yandex.stockpile.api.ServerStatusResponse>(
                  this, METHODID_SERVER_STATUS)))
// othen methods
          .build();
    }
  }
```

**Comment by ejona86** [comment]
I'm not suggesting override. I'm suggesting delegation or standard computation. Either make your own BindableService that delegates then modifies the results, or when adding the service to the server call `bindService()` manually and modify the results.
