### ISSUE TITLE
Throughput: AbstractServerStream does unnecessary flushes

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#331]
@ejona86 @nmittler 

1. AbstractServerStream.writeMessage if no headers have been sent will immediately flush an empty header to the transport, by triggering internalSendFrame(flush = true)

2. In the case of a unary response we don't delay the flush of the framed message to allow the trailers to be flushed at the same time.

Will work on a PR

**Comment by nmittler** [comment]
@louiscryan sgtm ... good find!

**Comment by ejona86** [comment]
#274 manually introduces the optimized flush behavior to OkHttp (because it was missing the flush outright). It would be nice if we could tell the transport to flush or not, since we could even want to batch across RPCs.

**Comment by louiscryan** [comment]
This has been resolved by 

https://github.com/grpc/grpc-java/pull/431
