### ISSUE TITLE
<RequestT,ResponseT>create(...) in MethodDescriptor has been deprecated

### ISSUE THREAD

**Issue by youurayy** [grpc/grpc-java#3332]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?
1.8.0_102

### What did you do?
gradle clean && gradle build

### What did you expect to see?
No deprecation warnings.

### What did you see instead?
```
:compileJavaNote: C:\Users\...\build\generated\source\proto\main\grpc\...\proto\ServerGrpc.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

and/or:

```
:extractIncludeProto
:extractProto UP-TO-DATE
:generateProto UP-TO-DATE
:compileJavaC:\Users\...\build\generated\source\proto\main\grpc\...\proto\ServerGrpc.java:33: warning: [deprecation] <RequestT,Respon
seT>create(MethodType,String,Marshaller<RequestT>,Marshaller<ResponseT>) in MethodDescriptor has been deprecated
      io.grpc.MethodDescriptor.create(
                              ^
  where RequestT,ResponseT are type-variables:
    RequestT extends Object declared in method <RequestT,ResponseT>create(MethodType,String,Marshaller<RequestT>,Marshaller<ResponseT>)
    ResponseT extends Object declared in method <RequestT,ResponseT>create(MethodType,String,Marshaller<RequestT>,Marshaller<ResponseT>)
```

### Relevant Versions
  classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.2'

  compile 'io.grpc:grpc-netty:1.5.0'
  compile 'io.grpc:grpc-protobuf:1.5.0'
  compile 'io.grpc:grpc-stub:1.5.0'
  compile 'io.grpc:grpc-core:1.5.0'
  compile 'io.grpc:grpc-context:1.5.0'
  compile 'io.grpc:grpc-protobuf-lite:1.5.0'
  compile 'io.grpc:protoc-gen-grpc-java:1.5.0'

**Comment by youurayy** [comment]
The generated file in question contains:
```
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.0.3)",
```
Could this be the issue - where to look for a stale grpc protoc plugin?

**Comment by ejona86** [comment]
Look for something like `artifact = 'io.grpc:protoc-gen-grpc-java:1.0.3'` in a `protobuf {}` section of your build file.

**Comment by youurayy** [comment]
Thanks so much, that was it.

One more question:
Does each GRPC version suggest a particular version of Netty core packages? (e.g. I need these for the `async-http-client` library I use for external http requests):

```
  compile 'io.netty:netty-handler:4.1.11.Final'
  compile 'io.netty:netty-codec-http2:4.1.11.Final'
  compile 'io.netty:netty-handler-proxy:4.1.11.Final'
  compile 'io.netty:netty-transport-native-epoll:4.1.11.Final'
```

The 4.1.11 works fine with GRPC 1.5.0, but 4.1.14 will cause GRPC to malfunction (HTTP/2 internal error; goaway).

**Comment by ejona86** [comment]
Closing since changing the protoc artifact fixed the issue.

@youurayy, yes, unfortunately grpc is quite tied to the Netty version because HTTP/2 API is unstable in Netty. We suggest to use the version that our artifacts depend on; while it may be possible to use a different version, we don't test with other versions. #2485 should be the eventual answer to your problem; you'd just use our pre-shaded artifact.
