### ISSUE TITLE
Unable to Publish Message to Pub/Sub due to error No functional channel service provider found

### ISSUE THREAD

**Issue by phanikumarmss** [grpc/grpc-java#3348]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0

### What JVM are you using (`java -version`)?
1.7

### What did you do?
If possible, provide a recipe for reproducing the error.

**No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact**

### What did you expect to see?

I am trying to publish a message from java to Google Pub/Sub

### What did you see instead?

Ending up with error.

**Maven Dependency tree**

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Miracle GCP Pub/Sub Plugin 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.3:tree (default-cli) @ gcppubsub-plugin2 ---
[INFO] gcppubsub-plugin2:gcppubsub-plugin2:hpi:1.0
[INFO] +- com.google.cloud:google-cloud-pubsub:jar:0.20.1-beta:compile
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.3.Final:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.2.1:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.9.2:compile
[INFO] |  |  +- org.json:json:jar:20160810:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.1.12:compile
[INFO] |  +- com.google.cloud:google-cloud-core-grpc:jar:1.2.1:compile
[INFO] |  |  +- io.grpc:grpc-context:jar:1.4.0:compile
[INFO] |  |  \- com.google.api:gax-grpc:jar:0.21.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:0.1.12:compile
[INFO] |  +- com.google.api.grpc:grpc-google-cloud-pubsub-v1:jar:0.1.12:compile
[INFO] |  +- io.grpc:grpc-netty:jar:1.4.0:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.11.Final:compile
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.11.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec:jar:4.1.11.Final:compile
[INFO] |  |  |  \- io.netty:netty-handler:jar:4.1.11.Final:compile
[INFO] |  |  |     \- io.netty:netty-buffer:jar:4.1.11.Final:compile
[INFO] |  |  |        \- io.netty:netty-common:jar:4.1.11.Final:compile
[INFO] |  |  \- io.netty:netty-handler-proxy:jar:4.1.11.Final:compile
[INFO] |  |     +- io.netty:netty-transport:jar:4.1.11.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver:jar:4.1.11.Final:compile
[INFO] |  |     \- io.netty:netty-codec-socks:jar:4.1.11.Final:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.4.0:compile
[INFO] |  \- io.grpc:grpc-auth:jar:1.4.0:compile
[INFO] +- com.google.api:gax:jar:1.4.0:compile
[INFO] |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  +- com.google.auto.value:auto-value:jar:1.2:compile
[INFO] |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.7.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.19.0:compile
[INFO] |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.2.5:compile
[INFO] |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.2.4:compile
[INFO] |  |  |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  |     \- commons-codec:commons-codec:jar:1.4:compile
[INFO] |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.19.0:compile
[INFO] |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  +- com.google.api:api-common:jar:1.1.0:compile
[INFO] |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  \- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] +- com.google.auth:google-auth-library-credentials:jar:0.7.1:compile
[INFO] +- io.grpc:grpc-protobuf:jar:1.4.0:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.4.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.19:compile
[INFO] |  |  \- com.google.instrumentation:instrumentation-api:jar:0.4.2:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.3.1:compile
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.3.1:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:0.1.9:compile
[INFO] |  \- io.grpc:grpc-protobuf-lite:jar:1.4.0:compile
[INFO] +- org.jenkins-ci.main:jenkins-war:war:1.609:test
[INFO] +- org.jenkins-ci.main:jenkins-core:jar:1.609:provided
[INFO] |  +- org.jenkins-ci.plugins.icon-shim:icon-set:jar:1.0.5:provided
[INFO] |  +- org.jenkins-ci.main:remoting:jar:2.50:provided
[INFO] |  |  \- org.jenkins-ci:constant-pool-scanner:jar:1.2:provided
[INFO] |  +- org.jenkins-ci.main:cli:jar:1.609:provided
[INFO] |  +- org.jenkins-ci:version-number:jar:1.1:provided
[INFO] |  +- org.jenkins-ci:crypto-util:jar:1.1:provided
[INFO] |  +- org.jvnet.hudson:jtidy:jar:4aug2000r7-dev-hudson-1:provided
[INFO] |  +- com.google.inject:guice:jar:4.0-beta:provided
[INFO] |  |  +- javax.inject:javax.inject:jar:1:provided
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:provided
[INFO] |  +- org.jruby.ext.posix:jna-posix:jar:1.0.3-jenkins-1:provided
[INFO] |  +- com.github.jnr:jnr-posix:jar:3.0.1:provided
[INFO] |  |  +- com.github.jnr:jnr-ffi:jar:1.0.7:provided
[INFO] |  |  |  +- com.github.jnr:jffi:jar:1.2.7:provided
[INFO] |  |  |  +- com.github.jnr:jffi:jar:native:1.2.7:provided
[INFO] |  |  |  +- org.ow2.asm:asm:jar:4.0:provided
[INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:4.0:provided
[INFO] |  |  |  +- org.ow2.asm:asm-analysis:jar:4.0:provided
[INFO] |  |  |  +- org.ow2.asm:asm-tree:jar:4.0:provided
[INFO] |  |  |  +- org.ow2.asm:asm-util:jar:4.0:provided
[INFO] |  |  |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:provided
[INFO] |  |  \- com.github.jnr:jnr-constants:jar:0.8.5:provided
[INFO] |  +- org.kohsuke:trilead-putty-extension:jar:1.2:provided
[INFO] |  +- org.jenkins-ci:trilead-ssh2:jar:build217-jenkins-8:provided
[INFO] |  +- org.kohsuke.stapler:stapler-groovy:jar:1.236:provided
[INFO] |  |  \- org.kohsuke.stapler:stapler-jelly:jar:1.236:provided
[INFO] |  |     +- org.jenkins-ci:commons-jelly:jar:1.1-jenkins-20120928:provided
[INFO] |  |     \- org.jenkins-ci.dom4j:dom4j:jar:1.6.1-jenkins-4:provided
[INFO] |  +- org.kohsuke.stapler:stapler-jrebel:jar:1.236:provided
[INFO] |  |  \- org.kohsuke.stapler:stapler:jar:1.236:provided
[INFO] |  |     +- javax.annotation:javax.annotation-api:jar:1.2:provided
[INFO] |  |     +- commons-discovery:commons-discovery:jar:0.4:provided
[INFO] |  |     \- org.jvnet:tiger-types:jar:1.3:provided
[INFO] |  +- org.kohsuke:windows-package-checker:jar:1.0:provided
[INFO] |  +- org.kohsuke.stapler:stapler-adjunct-zeroclipboard:jar:1.3.5-1:provided
[INFO] |  +- org.kohsuke.stapler:stapler-adjunct-timeline:jar:1.4:provided
[INFO] |  +- org.kohsuke.stapler:stapler-adjunct-codemirror:jar:1.3:provided
[INFO] |  +- com.infradna.tool:bridge-method-annotation:jar:1.13:provided
[INFO] |  +- org.kohsuke.stapler:json-lib:jar:2.4-jenkins-2:provided
[INFO] |  |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:provided
[INFO] |  +- commons-httpclient:commons-httpclient:jar:3.1:provided
[INFO] |  +- args4j:args4j:jar:2.0.31:provided
[INFO] |  +- org.jenkins-ci:annotation-indexer:jar:1.7:provided
[INFO] |  +- org.jenkins-ci:bytecode-compatibility-transformer:jar:1.5:provided
[INFO] |  |  \- org.kohsuke:asm5:jar:5.0.1:provided
[INFO] |  +- org.jenkins-ci:task-reactor:jar:1.4:provided
[INFO] |  +- org.jvnet.localizer:localizer:jar:1.23:provided
[INFO] |  +- antlr:antlr:jar:2.7.6:provided
[INFO] |  +- org.jvnet.hudson:xstream:jar:1.4.7-jenkins-1:provided
[INFO] |  +- jfree:jfreechart:jar:1.0.9:provided
[INFO] |  |  \- jfree:jcommon:jar:1.0.12:provided
[INFO] |  +- org.apache.ant:ant:jar:1.8.4:provided
[INFO] |  |  \- org.apache.ant:ant-launcher:jar:1.8.4:provided
[INFO] |  +- commons-io:commons-io:jar:2.4:provided
[INFO] |  +- commons-lang:commons-lang:jar:2.6:provided
[INFO] |  +- commons-digester:commons-digester:jar:2.1:provided
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.8.3:provided
[INFO] |  +- javax.mail:mail:jar:1.4.4:provided
[INFO] |  +- org.jvnet.hudson:activation:jar:1.1.1-hudson-1:provided
[INFO] |  +- jaxen:jaxen:jar:1.1-beta-11:provided
[INFO] |  +- commons-jelly:commons-jelly-tags-fmt:jar:1.0:provided
[INFO] |  +- commons-jelly:commons-jelly-tags-xml:jar:1.1:provided
[INFO] |  +- org.jvnet.hudson:commons-jelly-tags-define:jar:1.0.1-hudson-20071021:provided
[INFO] |  +- org.jenkins-ci:commons-jexl:jar:1.1-jenkins-20111212:provided
[INFO] |  +- org.acegisecurity:acegi-security:jar:1.0.7:provided
[INFO] |  |  +- org.springframework:spring-jdbc:jar:1.2.9:provided
[INFO] |  |  |  \- org.springframework:spring-dao:jar:1.2.9:provided
[INFO] |  |  +- oro:oro:jar:2.0.8:provided
[INFO] |  |  \- log4j:log4j:jar:1.2.9:provided
[INFO] |  +- org.codehaus.groovy:groovy-all:jar:1.8.9:provided
[INFO] |  +- jline:jline:jar:0.9.94:provided
[INFO] |  +- org.fusesource.jansi:jansi:jar:1.9:provided
[INFO] |  +- org.springframework:spring-webmvc:jar:2.5.6.SEC03:provided
[INFO] |  |  +- org.springframework:spring-beans:jar:2.5.6.SEC03:provided
[INFO] |  |  +- org.springframework:spring-context:jar:2.5.6.SEC03:provided
[INFO] |  |  +- org.springframework:spring-context-support:jar:2.5.6.SEC03:provided
[INFO] |  |  \- org.springframework:spring-web:jar:2.5.6.SEC03:provided
[INFO] |  +- org.springframework:spring-core:jar:2.5.6.SEC03:provided
[INFO] |  +- org.springframework:spring-aop:jar:2.5.6.SEC03:provided
[INFO] |  +- xpp3:xpp3:jar:1.1.4c:provided
[INFO] |  +- javax.servlet:jstl:jar:1.1.0:provided
[INFO] |  +- com.sun.xml.txw2:txw2:jar:20110809:provided
[INFO] |  |  +- javax.xml.stream:stax-api:jar:1.0-2:provided
[INFO] |  |  \- relaxngDatatype:relaxngDatatype:jar:20020414:provided
[INFO] |  +- commons-collections:commons-collections:jar:3.2.1:provided
[INFO] |  +- org.jvnet.winp:winp:jar:1.22:provided
[INFO] |  +- org.jenkins-ci:memory-monitor:jar:1.9:provided
[INFO] |  +- org.codehaus.woodstox:wstx-asl:jar:3.2.9:provided
[INFO] |  |  \- stax:stax-api:jar:1.0.1:provided
[INFO] |  +- org.jenkins-ci:jmdns:jar:3.4.0-jenkins-3:provided
[INFO] |  +- net.java.dev.jna:jna:jar:4.1.0:provided
[INFO] |  +- org.kohsuke:akuma:jar:1.9:provided
[INFO] |  +- org.kohsuke:libpam4j:jar:1.8:provided
[INFO] |  +- org.jvnet.libzfs:libzfs:jar:0.5:provided
[INFO] |  +- com.sun.solaris:embedded_su4j:jar:1.1:provided
[INFO] |  +- net.java.sezpoz:sezpoz:jar:1.9:provided
[INFO] |  +- org.kohsuke.jinterop:j-interop:jar:2.0.6-kohsuke-1:provided
[INFO] |  |  \- org.kohsuke.jinterop:j-interopdeps:jar:2.0.6-kohsuke-1:provided
[INFO] |  |     \- org.samba.jcifs:jcifs:jar:1.2.19:provided
[INFO] |  +- org.jvnet.robust-http-client:robust-http-client:jar:1.2:provided
[INFO] |  +- org.kohsuke:access-modifier-annotation:jar:1.4:provided
[INFO] |  +- commons-fileupload:commons-fileupload:jar:1.3.1-jenkins-1:provided
[INFO] |  +- org.mindrot:jbcrypt:jar:0.3m:provided
[INFO] |  \- com.jcraft:jzlib:jar:1.1.3-kohsuke-1:provided
[INFO] +- org.jenkins-ci.main:jenkins-test-harness:jar:1.609:test
[INFO] |  +- org.jenkins-ci.main:jenkins-war:jar:war-for-test:1.609:test
[INFO] |  |  +- org.jenkins-ci.modules:instance-identity:jar:1.4:test
[INFO] |  |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.47:test
[INFO] |  |  |     \- org.bouncycastle:bcprov-jdk15on:jar:1.47:test
[INFO] |  |  +- org.jenkins-ci.modules:ssh-cli-auth:jar:1.2:test
[INFO] |  |  +- org.jenkins-ci.modules:slave-installer:jar:1.5:test
[INFO] |  |  +- org.jenkins-ci.modules:windows-slave-installer:jar:1.4:test
[INFO] |  |  +- org.jenkins-ci.modules:launchd-slave-installer:jar:1.2:test
[INFO] |  |  +- org.jenkins-ci.modules:upstart-slave-installer:jar:1.1:test
[INFO] |  |  +- org.jenkins-ci.modules:systemd-slave-installer:jar:1.1:test
[INFO] |  |  \- org.slf4j:slf4j-jdk14:jar:1.7.7:test
[INFO] |  |     \- org.slf4j:slf4j-api:jar:1.7.7:test
[INFO] |  +- org.jenkins-ci.main:maven-plugin:jar:2.7.1:test
[INFO] |  |  +- org.jenkins-ci.plugins:javadoc:jar:1.0:test
[INFO] |  |  +- org.jenkins-ci.main.maven:maven-agent:jar:1.5:test
[INFO] |  |  +- org.jenkins-ci.main.maven:maven-interceptor:jar:1.5:test
[INFO] |  |  +- org.jvnet.hudson:maven2.1-interceptor:jar:1.2:test
[INFO] |  |  +- org.jenkins-ci.main.maven:maven3-agent:jar:1.5:test
[INFO] |  |  +- org.jenkins-ci.main.maven:maven31-agent:jar:1.5:test
[INFO] |  |  +- org.jenkins-ci.main.maven:maven3-interceptor:jar:1.5:test
[INFO] |  |  +- org.jenkins-ci.main.maven:maven31-interceptor:jar:1.5:test
[INFO] |  |  +- org.jenkins-ci.main.maven:maven3-interceptor-commons:jar:1.5:test
[INFO] |  |  +- org.apache.maven:maven-core:jar:3.1.0:test
[INFO] |  |  |  +- org.apache.maven:maven-model:jar:3.1.0:test
[INFO] |  |  |  +- org.apache.maven:maven-settings:jar:3.1.0:test
[INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.1.0:test
[INFO] |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.1.0:test
[INFO] |  |  |  +- org.apache.maven:maven-artifact:jar:3.1.0:test
[INFO] |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.1.0:test
[INFO] |  |  |  +- org.apache.maven:maven-model-builder:jar:3.1.0:test
[INFO] |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.16:test
[INFO] |  |  |  +- org.codehaus.plexus:plexus-utils:jar:3.0.10:test
[INFO] |  |  |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:test
[INFO] |  |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:test
[INFO] |  |  +- org.apache.maven:maven-compat:jar:3.1.0:test
[INFO] |  |  +- org.apache.maven:maven-aether-provider:jar:3.1.0:test
[INFO] |  |  +- org.apache.maven:maven-embedder:jar:3.1.0:test
[INFO] |  |  |  +- org.sonatype.plexus:plexus-cipher:jar:1.7:test
[INFO] |  |  |  \- commons-cli:commons-cli:jar:1.2:test
[INFO] |  |  +- org.eclipse.aether:aether-api:jar:0.9.0.M3:test
[INFO] |  |  +- org.eclipse.aether:aether-impl:jar:0.9.0.M3:test
[INFO] |  |  +- org.eclipse.aether:aether-spi:jar:0.9.0.M3:test
[INFO] |  |  +- org.eclipse.aether:aether-util:jar:0.9.0.M3:test
[INFO] |  |  +- org.eclipse.aether:aether-transport-wagon:jar:0.9.0.M3:test
[INFO] |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M5:test
[INFO] |  |  |  +- javax.enterprise:cdi-api:jar:1.0:test
[INFO] |  |  |  |  \- javax.annotation:jsr250-api:jar:1.0:test
[INFO] |  |  |  \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M5:test
[INFO] |  |  +- com.google.inject:guice:jar:no_aop:4.0-beta:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-http:jar:2.4:test
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-http-shared4:jar:2.4:test
[INFO] |  |  |     \- org.jsoup:jsoup:jar:1.7.1:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-file:jar:2.4:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-ftp:jar:2.4:test
[INFO] |  |  |  \- commons-net:commons-net:jar:3.1:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-ssh:jar:2.4:test
[INFO] |  |  |  +- com.jcraft:jsch:jar:0.1.44-1:test
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-ssh-common:jar:2.4:test
[INFO] |  |  |     \- org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-6:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-ssh-external:jar:2.4:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-provider-api:jar:2.4:test
[INFO] |  |  +- org.apache.maven.reporting:maven-reporting-api:jar:3.0:test
[INFO] |  |  |  \- org.apache.maven.doxia:doxia-sink-api:jar:1.0:test
[INFO] |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.1:test
[INFO] |  |  +- org.jenkins-ci.lib:lib-jenkins-maven-artifact-manager:jar:1.2:test
[INFO] |  |  +- org.jenkins-ci.lib:lib-jenkins-maven-embedder:jar:3.11:test
[INFO] |  |  |  \- org.eclipse.aether:aether-connector-wagon:jar:0.9.0.M2:test
[INFO] |  |  +- org.apache.maven.wagon:wagon-webdav-jackrabbit:jar:2.4:test
[INFO] |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:2.4:test
[INFO] |  |  |  \- org.apache.jackrabbit:jackrabbit-webdav:jar:2.5.2:test
[INFO] |  |  \- org.jenkins-ci:SECURITY-144-compat:jar:1.0:test
[INFO] |  +- org.jenkins-ci.plugins:ant:jar:1.2:test
[INFO] |  +- org.jenkins-ci.plugins:subversion:jar:1.45:test
[INFO] |  |  \- org.jenkins-ci.svnkit:svnkit:jar:1.7.6-jenkins-1:test
[INFO] |  |     +- org.tmatesoft.sqljet:sqljet:jar:1.1.0:test
[INFO] |  |     |  \- org.antlr:antlr-runtime:jar:3.4:test
[INFO] |  |     \- de.regnis.q.sequence:sequence-library:jar:1.0.1:test
[INFO] |  +- org.jenkins-ci.plugins:mailer:jar:1.10:test
[INFO] |  +- org.jenkins-ci.plugins:matrix-auth:jar:1.0.2:test
[INFO] |  +- org.jenkins-ci.plugins:antisamy-markup-formatter:jar:1.0:test
[INFO] |  |  \- org.kohsuke:owasp-html-sanitizer:jar:r88:test
[INFO] |  +- org.jenkins-ci.plugins:matrix-project:jar:1.4.1:test
[INFO] |  |  \- org.jenkins-ci.plugins:script-security:jar:1.13:test
[INFO] |  |     \- org.kohsuke:groovy-sandbox:jar:1.8:test
[INFO] |  +- org.jenkins-ci.plugins:junit:jar:1.2-beta-4:test
[INFO] |  +- org.mortbay.jetty:jetty:jar:6.1.26:test
[INFO] |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:test
[INFO] |  |  \- org.mortbay.jetty:servlet-api:jar:2.5-20081211:test
[INFO] |  +- org.jenkins-ci:test-annotations:jar:1.1:test
[INFO] |  +- org.jvnet.mock-javamail:mock-javamail:jar:1.7:test
[INFO] |  +- junit:junit:jar:4.11:test
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  +- org.jenkins-ci:htmlunit:jar:2.6-jenkins-6:test
[INFO] |  |  +- org.jvnet.hudson:htmlunit-core-js:jar:2.6-hudson-1:test
[INFO] |  |  +- xerces:xercesImpl:jar:2.9.1:test
[INFO] |  |  +- net.sourceforge.nekohtml:nekohtml:jar:1.9.13:test
[INFO] |  |  \- net.sourceforge.cssparser:cssparser:jar:0.9.5:test
[INFO] |  |     \- org.w3c.css:sac:jar:1.3:test
[INFO] |  +- xalan:xalan:jar:2.7.1:test
[INFO] |  |  \- xalan:serializer:jar:2.7.1:test
[INFO] |  |     \- xml-apis:xml-apis:jar:1.3.04:test
[INFO] |  +- org.jvnet.hudson:embedded-rhino-debugger:jar:1.2:test
[INFO] |  +- org.jvnet.hudson:netx:jar:0.5-hudson-2:test
[INFO] |  +- org.easymock:easymock:jar:2.4:test
[INFO] |  +- org.netbeans.modules:org-netbeans-insane:jar:RELEASE72:test
[INFO] |  +- com.github.stephenc.findbugs:findbugs-annotations:jar:1.3.9-1:test
[INFO] |  \- org.codehaus.geb:geb-implicit-assertions:jar:0.7.2:test
[INFO] +- javax.servlet:servlet-api:jar:2.4:provided
[INFO] \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.9:provided
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.913 s
[INFO] Finished at: 2017-08-15T20:22:41+05:30
[INFO] Final Memory: 35M/605M
[INFO] ------------------------------------------------------------------------

**Comment by tswast** [comment]
This is a follow-up to issue https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2341

**Comment by ejona86** [comment]
What environment is this being run in? I see it says "plugin" in "gcppubsub-plugin2". Could there be some classloaders involved?

You may be getting bit by #2375. You can workaround it (see https://github.com/grpc/grpc-java/issues/2375#issuecomment-311506401) by setting the context class loader before calling gRPC for the first time and reverting the context class loader afterward. If that works, then grpc-java 1.6 should fix the problem out-of-the-box.

**Comment by phanikumarmss** [comment]
I am running it with Jenkins and I am not invoking gRPC in my code. gRPC is being invoked somewhere from Google Publish client libraries which is causing the issue.

**Comment by ejona86** [comment]
@phanikumarmss, does "running it with Jenkins" mean "running it as a Jenkins plugin"? If so, then I think that would agree with my classloader/plugin comment.

**Comment by phanikumarmss** [comment]
As specified in #2375 I have added the following code to my application
Thread.currentThread().setContextClassLoader(getClass().getClassLoader());

Now, I am getting **Jetty ALPN/NPN has not been properly configured** error

**Comment by garrettjonesgoogle** [comment]
grpc team - we have multiple reports of the ALPN error on windows-x86_64 (https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2266), including @phanikumarmss . I don't have access to a Windows machine to investigate.

**Comment by phanikumarmss** [comment]
In Linux, I am getting following error

FATAL: com.google.common.util.concurrent.MoreExecutors.platformThreadFactory()Ljava/util/concurrent/ThreadFactory;
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.platformThreadFactory()Ljava/util/concurrent/ThreadFactory;
	at io.grpc.internal.GrpcUtil.getThreadFactory(GrpcUtil.java:496)
	at io.grpc.internal.GrpcUtil$2.create(GrpcUtil.java:460)
	at io.grpc.internal.GrpcUtil$2.create(GrpcUtil.java:453)
	at io.grpc.internal.SharedResourceHolder.getInternal(SharedResourceHolder.java:119)
	at io.grpc.internal.SharedResourceHolder.get(SharedResourceHolder.java:89)
	at io.grpc.internal.SharedResourcePool.getObject(SharedResourcePool.java:50)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:406)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:350)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:139)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:116)
	at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:140)
	at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:79)
	at com.google.cloud.pubsub.v1.Publisher$Builder.build(Publisher.java:625)
	at gcppubsub.gcppubsub.HelloWorldBuilder.createPublisherWithCustomCredentials(HelloWorldBuilder.java:172)
	at gcppubsub.gcppubsub.HelloWorldBuilder.perform(HelloWorldBuilder.java:115)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)

**Comment by jglick** [comment]
Jenkins uses an old (11.x) version of Guava, which is probably your issue. You seem to be using the 2.28 version of the plugin parent POM; more recent versions include an upper bound dependency check, which would highlight this kind of mistake in the `validate` phase.

You can try using the `pluginFirstClassLoader` flag to `maven-hpi-plugin` if you really know what you are doing (it is also possible to shoot yourself in the foot this way).

**Comment by phanikumarmss** [comment]
pluginFirstClassLoader flag with maven-hpi-plugin is not resolving issue @jglick.

**Comment by ejona86** [comment]
@phanikumarmss, with grpc-java 1.4.0 you need to use a 2.x tcnative. I would have expected netty-tcnative 2.0.5.Final to work for you. Are you using a 32 bit or 64 bit JVM?

**Comment by phanikumarmss** [comment]
I am working with 64 bit JVM. @ejona86

**Comment by ejona86** [comment]
@phanikumarmss, would you mind running the [`google-cloud-compat-checker`](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-util/google-cloud-compat-checker) and providing the results?

**Comment by phanikumarmss** [comment]
OS details:
  os.detected.name: windows
  os.detected.arch: x86_64
  os.detected.classifier: windows-x86_64
  os.detected.release: null
  os.detected.release.version: null
JVM details:
  Java version: 1.8.0_121
  Java specification version: 1.8
  JVM bit mode: 64
OpenSSL details:
  open ssl is available: true
  ALPN is supported: true
Checking compatibility...
  [PASS] This OS + architecture is supported.
  [PASS] 64-bit JVM is supported.
  [PASS] Open SSL is available
  [PASS] Open SSL ALPN is supported
Result: UNKNOWN (checker implementation not complete)
  Based on what was checked, nothing was identified that would
  prevent you from using grpc-based APIs.

**Comment by ejona86** [comment]
@phanikumarmss, you bring us such riddles!

So, we're pretty close to running out of possible causes. I can only think that it is caused by 1) the Jenkins environment or 2) the Windows environment that Jenkins is running under.

I had heard someone got gRPC working fine as a Jenkins plugin (after the ContextClassLoader hack). Is there more than one type of Jenkins plugin system? Is your code running on the master or the workers?

How are you running Jenkins? As a windows service? JNLP? Or anything "strange" like under a Cygwin or MSYS2 environment via SSH (this is what some of the Windows workers on [grpc-testing](https://grpc-testing.appspot.com/) are doing...)?

**Comment by phanikumarmss** [comment]
The configurations are working fine on Linux environment but not on windows I believe. I am running it on Jenkins master.

**Comment by ejona86** [comment]
@phanikumarmss, in your plugin, can you call `io.netty.handler.ssl.OpenSsl.unavailabilityCause().printStackTrace();` to look at the failure?
