### ISSUE TITLE
grpc.ssl_target_name_override

### ISSUE THREAD

**Issue by lu4kyd0y** [grpc/grpc-java#3365]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.4.0
### What JVM are you using (java -version)?

Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.
how to set  ChannelOption  grpc.ssl_target_name_override in java
i konw c# like this new ChannelOption(ChannelOptions.SslTargetNameOverride,"name")

**Comment by zhangkun83** [comment]
You can use `ManagedChannelBuilder.overrideAuthority(String authority)`.
