### ISSUE TITLE
How to use the healthcheck service?

### ISSUE THREAD

**Issue by mayday05** [grpc/grpc-java#3366]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?
jdk1.8.0

### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you expect to see?
I want to get the server instantaneous status 。

### What did you see instead?
I have seen the health.proto and  HealthServiceImpl.java  in gRPC 1.5.0，but I don't know how to use it.
Is this part of the code complete? If complete, how the client to get the server healthy status, is there any examples? If not complete, Is it being perfected?

**Comment by zhangkun83** [comment]
You would create a `HealthStatusManager` instance, which you will keep for yourself because with it you can change the health state of your services. Then add the service returned by `HealthStatusManager.getHealthService()` to your server. Clients can then query the state of the server by making RPCs to the service defined in `health.proto`. You can find the general information about gRPC health-checking in this [doc](https://github.com/grpc/grpc/blob/master/doc/health-checking.md).

**Comment by mayday05** [comment]
Thanks for answer me.You mean i have to create the client by myself and query every state of severs？but now I am creating a client kind of LB. How will link client LB and healthCheck together?

**Comment by zhangkun83** [comment]
> You mean i have to create the client by myself and query every state of severs？

Yes, this is my understanding.

> How will link client LB and healthCheck together?

IIUC the health-checking service is meant to be used with a centralized health checker that collects the health states of all backends, which is to be used by the [GRPCLB balancer](https://github.com/grpc/grpc-java/issues/428#issuecomment-115341325) which is a centralized balancing controller that assigns backends to clients.  Only the [client-controller protocol](https://github.com/grpc/grpc-java/blob/master/grpclb/src/main/proto/load_balancer.proto) and the [client library](https://github.com/grpc/grpc-java/blob/master/grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java) are open-sourced. Thus unfortunately it doesn't work out of box. You would have to implement the controller according to the protocol.

Another way of using the health-checking service is to implement your own `ManagedChannel` that creates channels under the hood for each server which send health check requests.

/cc @ejona86

**Comment by ejona86** [comment]
> implement your own ManagedChannel

You'd just implement your own `Channel`. But yeah, annoying.
