### ISSUE TITLE
Grpc android client giving : "Protocol negotiation failed" when using grpc server behind AWS ELB.

### ISSUE THREAD

**Issue by vyasashish** [grpc/grpc-java#3367]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0

### What JVM are you using (`java -version`)?
java version "1.8.0_101"

### What did you do?
If possible, provide a recipe for reproducing the error.
Deploy a grpc C++ server inside  AWS EC2 instance.
Make a ELB with a certificate using  ACM.
Use android client to hit the ELB domain name.

### What did you expect to see?
Excpected response from grpc server

### What did you see instead?
Protocol negotiation failed

**Comment by ericgribkoff** [comment]
Are you using the Google Play Services security provider to make sure you have an up-to-date TLS installation on the Android device? See instructions for Android in [SECURITY.md](https://github.com/grpc/grpc-java/blob/8d6ff4c9b4c2fe42bcb71ae694fbe697511a2a6a/SECURITY.md#tls-on-android). This is especially important on older Android devices.

If the error persists, can you please provide the Android API level you are using? It would also be helpful if you could attempt to connect directly to the gRPC C++ server, without the ELB, and report if that works or experiences the same failure.

**Comment by ejona86** [comment]
Not heard back, so closing. We can reopen if we hear back more.
