### ISSUE TITLE
Client close the TCP conneting When the right end is not reached

### ISSUE THREAD

**Issue by mayday05** [grpc/grpc-java#3373]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
gRPC1.5.0

### What JVM are you using (`java -version`)?
JDK1.8.0

### What did you do?
If possible, provide a recipe for reproducing the error.

I create gRPC client and gRPC server in different host, when I pull the cable to make the server Network inaccessible.
### What did you see instead?
 I find that the client will close the tcp connecting after about 20 seconds,and start to make the subchannel to IDLE and try to reconnect. I have seen some codes,but not to know
Why? How does the client feel disconnected from the server network.

**Comment by zhangkun83** [comment]
Please clarify what the expected behavior is.
