### ISSUE TITLE
Netty{Client/Server}Transport.shutdown() has 5 sec timeout, which does not agree with the spec of the interface

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#3383]
The transport `shutdown()` API specifies that existing streams continue, but the `AbstractNettyHandler` sets a `GRACEFUL_SHUTDOWN_TIMEOUT = SECONDS.toMillis(5)`, so when `Netty{Client/Server}Transport.shutdown()` is called, it actually will kill the existing streams in 5 seconds.

**Comment by zpencer** [comment]
We should be able to set the value to "-1" now that this is supportd in netty:
https://github.com/netty/netty/pull/6954

**Comment by zpencer** [comment]
dup of #3383

**Comment by dapengzhang0** [comment]
@zpencer I think you mean dup of #2907 :)

**Comment by zpencer** [comment]
Ah you are correct, copy/pasted the wrong number
