### ISSUE TITLE
Following gRPC tutorial: Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by elenabdecastro** [grpc/grpc-java#3396]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### What did you do?
I've been following the gRPC java tutorial, after modifying the server and client classes, I tried to compile again with gradlew installDist and I get the following error:

Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### What did you expect to see?
Success compilation

### What did you see instead?
The following error:
Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by elenabdecastro** [comment]
The issue can be solved by deleting the build file in grpc-java\examples. It would be great to upload the documentation in https://grpc.io/docs/quickstart/java.html

Thank you.

**Comment by ejona86** [comment]
Deleting which file? build.gradle? Or the `build/` directory? That doesn't sound right...
