### ISSUE TITLE
 The recommented way to use the gRPC in highly concurrent environments.

### ISSUE THREAD

**Issue by mayday05** [grpc/grpc-java#3397]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
gRPC-1.5.0

### What JVM are you using (`java -version`)?
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.
1、create a gRPC server binding a port  the server side
2、create a gRPC client of singleton pattern
3、start multiple threads to send messages simultaneously using the same client(Using blockingStub)

### What did you expect to see?
I hope that the gRPC able to cope with a certain amount of concurrent pressure

### What did you see instead?
when I use a threads to send messages  using the client, one "send to return" takes about 40ms ;
  when I increase to 20 threads to send messages simultaneously using the same client, what time one "send to return" take increase to about 200ms;  
  I don't think the 20 concurrent  threads would have so big impact .
  Are there any other parameters that need to be configured to improve performance in a concurrent environment? or  recommend way to use gRPC in a concurrent environment better?
  Hope for answers.

**Comment by ejona86** [comment]
gRPC generally adds less than a millisecond of latency (when uncontended). The 40ms sounds very high. How did you get that performance number? Was the Java JIT warmed up? How large is the message and the response? How long does your server application take to process the request into a response? What sort of network are you on. What sort of machine (e.g., number of cores) was the client and server?

You may be interested in [gRPC's performance dashboard](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584).

**Comment by ejona86** [comment]
Closing since no response. If we get more information it can be reopened.
