### ISSUE TITLE
OkHttp does not observe SETTINGS_INITIAL_WINDOW_SIZE

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#341]
It only [observes MAX_CONCURRENT_STREAMS](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java#L527).

**Comment by madongfly** [comment]
I'd take this one as "Support user specified initial window size for okhttp".

**Comment by madongfly** [comment]
This was fixed by #349
