### ISSUE TITLE
google-common-protos are not included in extracted-include-protos

### ISSUE THREAD

**Issue by holysheep** [grpc/grpc-java#3410]
### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?
java version "1.8.0_144"

I don't know either it is protobuf or grpc-lite problem:
using annotation.proto from proto commons throws error, though it is included in libraries folder. 

![screen shot 2017-08-28 at 22 23 31](https://user-images.githubusercontent.com/9785806/29792250-7b7c21ce-8c48-11e7-8049-4cbf2adc0adc.png)

Also, extracted-include-protos (or extracted-protos) build directory does not include anything related with it.

**Comment by ericgribkoff** [comment]
Did you include the jar as a dependency? I don't think it's sufficient to just copy it into the libraries folder, you also have to explicitly add it to the project (this can be done in the gradle file, or by right clicking on the jar in Android Studio and selecting the add dependency option).

Either way, this is probably not a gRPC-related issue. If you've added the jar to your project dependencies and it still isn't working, you may also try asking at https://github.com/googleapis/googleapis.

**Comment by holysheep** [comment]
@ericgribkoff I did not add it myself, It was generated by 
```
com.google.api.grpc:googleapis-common-protos
```
dependency. Just mentioned, that existing class was not recognized by protobuf.
May be it somehow related with this issue https://github.com/google/protobuf/issues/1889 ?

**Comment by ejona86** [comment]
@holysheep, have you tried adding it as a `protobuf` dependency, like mentioned in https://github.com/google/protobuf/issues/1889#issuecomment-261684149 ?
