### ISSUE TITLE
Compiler warnings in bazel

### ISSUE THREAD

**Issue by pgr0ss** [grpc/grpc-java#3412]
### What version of gRPC are you using?

Master at 6164b7b2ee8066c5f047f6ea49c477b6f9e3aba6 (waiting for the bazel naming fixes to be released)

### What JVM are you using (`java -version`)?

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### What did you do?

We have configued a custom java toolchain in bazel so we can catch java warnings:

```
java_toolchain(
  name = "myjava",
  ...
  xlint = [
    "all",
    "-processing",
    "-serial",
  ],
  misc = [
    "-Werror",
  ],
)

# build --java_toolchain=//:myjava
```

But now if we include the grpc-java rules, we get errors.

WORKSPACE:
```
git_repository(
  name = "grpc_java",
  remote = "https://github.com/grpc/grpc-java.git",
  commit = "6164b7b2ee8066c5f047f6ea49c477b6f9e3aba6",
)

load(
  "@grpc_java//:repositories.bzl",
  "grpc_java_repositories",
)

grpc_java_repositories()
```

BUILD:
```
load("@grpc_java//:java_grpc_library.bzl", "java_grpc_library")

java_grpc_library(
  name = "grpc-protobuf",
  srcs = [":proto-library"],
  deps = [":messages-protobuf"],
)
```

```
% bazel build //...
ERROR: /home/admin/.cache/bazel/_bazel_admin/61e657d6884c63362b8b441914a1bc68/external/com_google_protobuf_java/BUILD:609:1: Building external/com_google_protobuf_java/libprotobuf_java.jar (76 source files, 1 source jar) failed: Worker process sent response with exit code: 1.
warning: [options] source value 1.6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified
```

It seems like it's trying to compile protobuf_java using our java toolchain (instead of just pulling in precompiled jars?).

Is there a way to prevent the compilation from using our java_toolchain? Or some other way to leave our warnings on, but not fail on grpc/protobuf?

**Comment by ejona86** [comment]
This actually has little to do with gRPC. Bazel itself depends on [protobuf's `:java_toolchain`](https://github.com/google/protobuf/blob/v3.4.0/BUILD#L838) for `java_proto_library()` support, and the `:java_toolchain` pulls in the runtime dependency of `:protobuf_java`.

gRPC does have the same warning about 1.6 though. I guess we could maybe squelch it with `-Xlint:-options`, though.

**Comment by pgr0ss** [comment]
@ejona86 Thanks for the quick reply. Do you think I should open an issue on protobuf itself then? We are currently using protobufs in our project, but we just use the jars and protoc and don't use their bazel rules (although we've talked about switching).

**Comment by ejona86** [comment]
You can, although I feel this gets more into Bazel territory to figure out what should happen. Maybe we can just discuss here for the moment, since gRPC would have the same problem as protobuf.

I will say that it feels anti-Bazel to use a binary JAR when Bazel is already supported on the other repository.

It looks like the warning is new as of google/protobuf#3235 (Hi, @buchgr!). And I'll pull in @cgrushko, since `proto_lang_toolchain` is in play.

I'm questioning whether this is simply an abuse of `java_toolchain`. Or whether we just fixup Protobuf and gRPC to be warning-free and avoid answering hard questions.

**Comment by ejona86** [comment]
No response... Moving discussion to bazelbuild/bazel#3757
