### ISSUE TITLE
Document CallStreamObserver.request() thread-safety

### ISSUE THREAD

**Issue by bubenheimer** [grpc/grpc-java#3413]
### What version of gRPC are you using?
1.5.0

The javadoc for `CallStreamObserver.request()` makes no statement about thread safety. I see that the applicable implementations call `request()` methods that are documented as thread-safe, and that `CallStreamObserver.request()` is called as if it were thread-safe. I assume that this is meant to be a contract, as otherwise usage would be oddly complicated.

**Comment by carl-mastrangelo** [comment]
StreamObservers are not threadsafe at all.  Do not assume anything about their threadsafety.   It is up to you to synchronize usage.  

Making them threadsafe would unnecessarily slow them down for users who don't need it.

**Comment by bubenheimer** [comment]
Can the documentation be clarified? The documentation makes a statement about StreamObserver methods, but not about the methods added in CallStreamObserver.

Also, the usage pattern of CallStreamObserver.request() is different from StreamObserver methods and I think it needs different treatment to make it usable. In general the inbound message stream calls request() on the outbound message stream. It is the equivalent of calling ClientCall.request(), which is thread-safe.

The API is marked experimental at the moment, so I'd hope this kind of feedback would be taken into account.

**Comment by bubenheimer** [comment]
Also, the current implementation just calls through to the thread-safe ClientCall.request() (which is the behavior I'd generally expect), so I have my doubts the slowdown fears.

**Comment by carl-mastrangelo** [comment]
@bubenheimer CallStreamObserver may be implemented by anyone, even non-grpc code.  ClientCall makes the assertion that implementers should make multiple request() calls safe.  However, it does not follow that our *particular* implementation is threadsafe.

Also to be clear, the ClientCall implementation isn't exactly thread safe.  ClientCall.start() can race with ClientCall.request(), so the amount safety is not as much as it seems.

**Comment by bubenheimer** [comment]
I fail to see the point of having a thread-compatible request(). I'd have to synchronize all calls to CallStreamObserver. That will **really** slow me down.

**Comment by carl-mastrangelo** [comment]
Please read the documentation for Stream Observer:

> Implementations are expected to be thread-compatible

and

> Since individual StreamObservers are not thread-safe, if multiple threads will be writing to a StreamObserver concurrently, the application must synchronize calls.


Please explain what you are doing.

**Comment by bubenheimer** [comment]
My point is that I can commonly make streaming onNext() and onComplete() calls on the _outbound_ StreamObserver from a single thread without needing to use synchronization. But once I incorporate flow control via request() on the _outbound_ StreamObserver, the request() calls would typically come from a different thread, namely the one running onNext() on the _inbound_ StreamObserver. So now I need to synchronize **all** calls to the _outbound_ StreamObserver. Does that clarify my perspective?

**Comment by bubenheimer** [comment]
Really what I want is disable flow control on the client via request(Integer.MAX_VALUE). I looked at where request() is called in the grpc-java implementation, and thought it best to use a similar pattern, by calling request(Integer.MAX_VALUE) once I receive the first message from the server in the inbound onNext(). It seems more efficient to do this little thing if I changed everything to the plain ClientCall interface, but, well, I don't really want to, just to disable flow control. It just doesn't seem right that synchronization would be needed for request() when it's almost necessarily called from a different thread.

**Comment by ejona86** [comment]
To be useful, `request()` must be thread-safe. Yes, we need to update the documentation.

`ClientCall` specifies for `request()`:
> This method is safe to call from multiple threads without external synchronizaton.

We should include something similar in `CallStreamObserver`.

**Comment by bubenheimer** [comment]
Perhaps when updating the documentation for `CallStreamObserver.request()`, a usage-related note could be added for its siblings `disableAutoInboundFlowControl()` and `setOnReadyHandler()`. Their usage situation becomes clearer once the reader comes across the javadoc for `ClientResponseObserver.beforeStart()`, but the usage info on those two methods directly could be more concrete. I recall learning the usage from an issue comment or group post.

To round it out, `isReady()` and `setMessageCompression()` - those actually sound thread-compatible.

**Comment by ejona86** [comment]
> To round it out, isReady() and setMessageCompression() - those actually sound thread-compatible.

Correct. They are not thread-safe.

We should probably just copy the same "Implementations are expected to be thread-compatible" doc to `CallStreamObserver` (and children). Then we just call out in `request()`'s documentation that it is thread-safe. Same approach as in `ClientCall`.
