### ISSUE TITLE
Trying to get a basic Google Cloud Endpoints gRPC project working with an OAuth2.0 auth provider

### ISSUE THREAD

**Issue by julie330** [grpc/grpc-java#3420]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.
We are trying to get  a Google Cloud Endpoints project with gRPC working with an OAuth2.0 authentication provider using ServiceAccountJwtAccessCredentials. 
Below is the relevant piece of my Client code :

```java
/**
 * Reporter Client that requests a response from the {@link ReporterServer}.
*/
public class ReporterClient {
public static void main(String[] args) throws Exception {

    // Create gRPC stub
    String audience =
        "https://reporter.endpoints." + computeProjectId + ".cloud.goog";
    ReporterGrpc.ReporterBlockingStub reporterBlockingStub = new ReporterClient()
        .createReporterStub(cmd.getOptionValue(HOSTPORT_OPTION), audience);

  // Construct request
    GenerateReportRequest request = GenerateReportRequest.newBuilder()
            .setDomain(domain) .setType(type).setObjectName(object).setData(data).build();

    // Send Request to Server
    GenerateReportResponse response = reporterBlockingStub.generateReport(request);
  }
  public ReporterGrpc.ReporterBlockingStub createReporterStub(String hostport, String audience)
      throws Exception {
    HostAndPort value = HostAndPort.fromString(hostport);
    Channel channel = ManagedChannelBuilder.forAddress(value.getHostText(), value.getPort())
        .usePlaintext(true).build();

    return ReporterGrpc.newBlockingStub(channel)
        .withCallCredentials(
            new GoogleAuthLibraryCallCredentials(
                Environment.get().computeEngineServiceAccountJwtAccessCredentials(audience)));
  }
}

/** Constructing credentials */
 public ServiceAccountJwtAccessCredentials withAudience(String audience) {
      // Uri is the audience that is set in ServiceAccountJwtAccessCredentials for the client
      // request to the cloud endpoint api. Eg: https://reporter.endpoints.pojectid.cloud.goog
      try {
        return new ServiceAccountJwtAccessCredentials(
            this.serviceAccountJwtAccessCredentials.getClientId(),
            this.serviceAccountJwtAccessCredentials.getClientEmail(),
            this.serviceAccountJwtAccessCredentials.getPrivateKey(),
            this.serviceAccountJwtAccessCredentials.getPrivateKeyId(), new URI(audience));
      } catch (URISyntaxException e) {
        throw new IllegalArgumentException("Audience value: " + audience + " is not a valid uri");
      }
```
A question concerning this issue has already been asked by me in the google groups here: (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/grpc-io/xP2CHQPwR_s)

### What did you expect to see?
Currently  the audience that  is set by  ServiceAccountJwtAccessCredentials is being overwritten by the above line:     

return ReporterGrpc.newBlockingStub(channel)
        .withCallCredentials(
            new GoogleAuthLibraryCallCredentials(
                Environment.get().computeEngineServiceAccountJwtAccessCredentials(audience)));

So instead of the audience (SERVICE_CONFIGURATION_NAME) that we set, we are obtaining a string like : https://35.195.24.28:80/reporter.Reporter

### What did you see instead?
Did not expect the GoogleAuthLibraryCallCredentials.java to overwrite the audience we set.
We were wondering whether ServiceAccountJwtAccessCredentials class is compatible with CallCredentials class or if there is another wrapper available to pass the ServiceAccountJwtAccessCredentials.

**Comment by ejona86** [comment]
Discussion is currently happening on the mailing list: https://groups.google.com/d/topic/grpc-io/xP2CHQPwR_s/discussion
