### ISSUE TITLE
How to match versions of com_google_protobuf and com_google_protobuf_cc

### ISSUE THREAD

**Issue by drigz** [grpc/grpc-java#3423]
If you want to use grpc-java in the same workspace as compiling C++ protos, you need to make sure the protobuf versions match. If you get the version wrong, your C++ builds fail with "This file was generated by a newer version of protoc".

For example, our WORKSPACE currently contains:

```
# Protobuf for C++ (others are provided by grpc_java_repositories() below)
# If you change the version, check it matches the version in:
# https://github.com/grpc/grpc-java/blob/master/repositories.bzl
http_archive(
    name = "com_google_protobuf_cc",
    sha256 = "542703acadc3f690d998f4641e1b988f15ba57ebca05fdfb1cd9095bec007948",
    strip_prefix = "protobuf-3.4.0",
    url = "https://github.com/google/protobuf/archive/v3.4.0.zip",
)

# grpc java binding
# If you change the version, you might need to change the version for
# com_google_protobuf_cc above.
git_repository(
    name = "grpc_java",
    commit = "32cd4a066040c64cc6d88cb54c04cc1a3702f9a7",
    remote = "https://github.com/grpc/grpc-java.git",
)
```

I couldn't find anyone else who has reported the issue, so I'm hoping to discuss the best way to deal with this here. Options:

1. Manually keep them in sync (as above).
2. Use `omit_com_google_protobuf_*` flags to grpc_java_repositories() and define protobuf repos in the WORKSPACE.
3. Make grpc_java_repositories() define com_google_protobuf_cc.
4. Get Bazel to avoid relying on multiple com_google_protobuf* names for the same google/protobuf repo.

1 is tedious, 2 could break grpc-java and 3 is potential surprising. There is probably a good reason 4 hasn't been done.

Can you think of a better option for this?

**Comment by ejona86** [comment]
I believe 2 is the expected workflow. Yes, it could break when upgrading grpc-java, but that's a bit of your responsibility when upgrading grpc-java. If that doesn't work out, then I think this should be discussed with the Bazel folks, since it would apply to anyone using protobuf (and Bazel integrates multiple parts of protobuf).

**Comment by drigz** [comment]
Thanks, Eric. I'll close this - if I run into any issues, I'll bring it up on bazel-discuss.
