### ISSUE TITLE
NettyChannelBuilder uses Java 1.7 APIs

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#3445]
Intellij complains that NettyChannelBuilder's usage of `InetSocketAddress.getHostString` is Java 1.7

**Comment by ejona86** [comment]
There's really no alternative and users of JDK 6 can avoid the API. InetSocketAddress's toString() is broken for IPv6 and getHostName() can return something untrusted (because it can do a reverse DNS lookup).

**Comment by carl-mastrangelo** [comment]
Are you saying that Netty can use Java 7 apis?  Also, why didn't animal sniffer complain?   Was it muted?

**Comment by ejona86** [comment]
Animal sniffer is checking for Java 7 for Netty. Right now it is a mixed approach: it is possible to use it with JDK 6, but some things are known-broken, like TLS. This `getHostString()` usage is another thing that is simply not possible to do securely without Java 7.

**Comment by ejona86** [comment]
Note we also use [`setEndpointIdentificationAlgorithm`](https://github.com/grpc/grpc-java/blob/0fa2225/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L308), which was added in JDK 7. But for proper security, we have to use it. If someone wants JDK 6 for Netty, they'll need to avoid TLS and passing an InetSocketAddress to Netty. No real other option.
