### ISSUE TITLE
Error of Tutorial example

### ISSUE THREAD

**Issue by xiayank** [grpc/grpc-java#3447]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4

### What JVM are you using (`java -version`)?
java version "1.8.0_111"

### What did you do?
If possible, provide a recipe for reproducing the error.
Follow the [example](https://github.com/grpc/grpc-java/tree/master/examples#maven) of Maven section. Try to run `mvn verify`.

### What did you expect to see?
No ERROR for maven verifying.

### What did you see instead?
```
[ERROR] Failed to execute goal on project examples: Could not resolve dependencies for project io.grpc:examples:jar:1.4.0-SNAPSHOT: The following artifacts could not be resolved: io.grpc:grpc-netty:jar:1.4.0-SNAPSHOT, io.grpc:grpc-protobuf:jar:1.4.0-SNAPSHOT, io.grpc:grpc-stub:jar:1.4.0-SNAPSHOT: Could not find artifact io.grpc:grpc-netty:jar:1.4.0-SNAPSHOT -> [Help 1]
```

I just start to learn gRPC, hope someone can give me some suggestions.
Thanks!

**Comment by ejona86** [comment]
Check out a release tag. So for 1.4:
```
git checkout v1.4.0
```
