### ISSUE TITLE
Attributes.Key equality by name

### ISSUE THREAD

**Issue by pgr0ss** [grpc/grpc-java#3457]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.6.1

### What JVM are you using (`java -version`)?

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### What did you do?

I am using client certificates and trying to verify the name of the caller (e.g. whitelist certain callers of my grpc server). Here is the code I wanted to write in a `ServerInterceptor`:

```java
    SSLSession sslSession = (SSLSession) serverCall.getAttributes().get(Attributes.Key.of("ssl-session"));
```
And then I can use this `SSLSession` to extract info about the caller.

However, this does not work since `Attributes.Key` does not implement equals/hashCode. Instead, I think I have to write something like this:

```java
    Attributes.Key<?> key =
      serverCall.getAttributes().keys().stream()
        .filter(k -> k.toString().equals("ssl-session"))
        .findFirst()
        .get();

    SSLSession sslSession = (SSLSession) serverCall.getAttributes().get(key);
```

Is this intentional behavior? I went to submit a pull request to implement these methods and then discovered there is a test explicitly asserting this behavior:

https://github.com/grpc/grpc-java/blob/ec600feb87b5da620cda2158bcbcd3c582359878/core/src/test/java/io/grpc/AttributesTest.java#L43

This seems related to https://github.com/grpc/grpc-java/issues/2942

**Comment by zpencer** [comment]
This is intentional behavior as discussed on #2942. The way to do what you want is just refer to the Attribute.Key directly. If the key is not publicly visible, then it's probably an internal implementation detail that's hidden on purpose.
```
SSLSession sslSession = serverCall.getAttributes().get(Grpc.TRANSPORT_ATTR_SSL_SESSION)
```
