### ISSUE TITLE
Migrate OS X CI to Kokoro

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#3466]
Travis works quickly. For Linux. But not OS X.

OS X tends to have a long build queue (right now it is at least 3 hours long). This could be fine, except if 5 OS X jobs are queued they starve out Linux builds. This has been a problem since OS X support was added to Travis, so waiting for things to get better doesn't seem a good strategy. Since the "Backlog macOS Builds for Open Source projects" tells a good story on https://www.traviscistatus.com/ , we could notice when things have improved in the future.

In principle it'd be fine to only run on master (not per-PR), but I don't know of any option to do that for Travis. Kokoro shouldn't have any trouble handling our rate of PR builds.

**Comment by dfawley** [comment]
This also impacts grpc-go -- we seem to share travis quota with grpc-java for whatever reason.  Is there anything we can do to decouple them?  If not, we would really appreciate a prioritization of a change here.  Thanks!

**Comment by ejona86** [comment]
Based on https://travis-ci.org/grpc/grpc-java/builds/275962786 the queue today at 9:00 AM was 3.5 hours long when the status page showed 1800 jobs in the queue. It currently has 2250 jobs in the queue; that's an estimated queue length of 4 hours, 20 minutes.

@dfawley, Travis CI quota is org-based. We're both in the grpc org so we share quota. This isn't the first time we've had trouble with the queue. When it's bad like this, feel free to cancel "duplicate" PR jobs and the OS X job.

**Comment by dfawley** [comment]
Thanks @ejona86.  Have we made sure the Travis folks are aware of this situation?

**Comment by ejona86** [comment]
They're quite aware of OS X blocking on Linux builds and the long queue times.

**Comment by ejona86** [comment]
https://blog.travis-ci.com/2017-09-22-macos-update

I'm interested in how this works out. We may swap to Kokoro anyway, but it will be good to see if the Mac queue becomes a bit more sane.

**Comment by ejona86** [comment]
The build queue has been around 25 minutes with around 400 jobs in the queue. That is _substantially_ better, but still a bit high. More importantly, the limiting to 2 jobs allows our Linux jobs to proceed (albeit 3 in parallel instead of 5) even when OS X is backlogged.

**Comment by ejona86** [comment]
The OS X queue was 3.5 hours long today.
