### ISSUE TITLE
The parameter usage of KeepAlive

### ISSUE THREAD

**Issue by mayday05** [grpc/grpc-java#3470]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?
jkd1.8.0

### What did you do?
If possible, provide a recipe for reproducing the error.
 1. create a client and a server in two different virtual machine (machine 1, machine2);
`NettyChannelBuilder nettyChannelBuilder = (NettyChannelBuilder)ManagedChannelBuilder.forTarget(authHost).loadBalancerFactory(lbFactory).nameResolverFactory(nameResolverFactory).usePlaintext(true);channel = nettyChannelBuilder.keepAlive(10, TimeUnit.SECONDS).keepAliveTimeout(10, TimeUnit.SECONDS).build()`

2. call one rpc request and server response success ,then unplug the cable of machine2 to make the network from machine 1 to machine 2 unreachable；
3. call another rpc request after one minute；
### What did you expect to see?
 I want to seen that the client quickly know that the server unreachable;

### What did you see instead?
I seen that the client  throw exception after 10 seconds.

> io.grpc.StatusRuntimeException:UNAVAILABLE: Keepalive failed.The connection is likely gone

  How to use The keepAlive and the keepAliveTimeout, why the second rpc need to wait another 10 seconds to sense the server unreachable. 
  What the keepAlive mechanism I understand is that the client send the ping after the keepAlive time,if the response don't back before the keepAliveTimeout, shuwdown the transport and make the channel 
unavailable.

**Comment by ejona86** [comment]
See [keepAliveWithoutCalls(boolean)](https://grpc.io/grpc-java/javadoc/io/grpc/netty/NettyChannelBuilder.html#keepAliveWithoutCalls-boolean-).

**Comment by mayday05** [comment]
Thanks.this is  which I want to know.

**Comment by princejha95** [comment]
Is there a way by which the channel should remain open for infinite time after server has sent the response to client in case of server side streaming in gRPC java ?
