### ISSUE TITLE
StreamObserver stops receiving messages from server stream after 30 minutes of being silent

### ISSUE THREAD

**Issue by belek** [grpc/grpc-java#3482]
### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
Android

### What did you do?
Android client application with gRPC and backend written on go.
Client starts receiving message from server stream. But if there was no messages during 30 minutes, stream stops receiving messages at all. No logs, errors or crashes was caught by onError() or onCompleted().
By watching logs at server side I can see, that these messages were sent to stream without any errors.

Client code:
```
observer = new StreamObserver<Order>() {
            @Override
            public void onNext(Order value) {
                Log.d(TAG, "observer onNext: " + value);
                handleOrder(value, false);
            }
            @Override
            public void onError(Throwable t) {
                Log.d(TAG, "observer onError: ");
                t.printStackTrace();
            }
            @Override
            public void onCompleted() {
                Log.d(TAG, "observer onCompleted: ");
            }
```

Server code:
```
func (a *API) ActiveOrders(in *empty.Empty, stream pb.Foreman_ActiveOrdersServer) error {
	ctx := stream.Context()
	user, ok := user.FromContext(ctx)
	if !ok {
		return grpc.Errorf(codes.Unauthenticated, "user not found")
	}
	OrdersChan := pubsub.AddActiveOrderReader(user.CabNumber)

	for {
		select {
		case order := <-OrdersChan:
			if err := stream.Send(order); err != nil {
				grpclog.Infof("Foreman.active_orders: cant send order %v", err)
			}
		case <-ctx.Done():
			close(OrdersChan)
			pubsub.LeaveActiveOrderReader(user.CabNumber)
			return ctx.Err()
		}
	}
}
```

### What did you expect to see?
I expect stream still receiving messages even it was inactive for some time.

### What did you see instead?
No messages received.

**Comment by ericgribkoff** [comment]
Thanks for filing an issue. Is it always after exactly 30 minutes of idleness when this problem starts occurring? One thing to check here is that the Android client is actually still connected to the network after this 30 minute gap. What happened when the client tried to send a message on the stream? Or start a new stream?

The [Android Studio 3.0 developer preview](https://developer.android.com/studio/preview/index.html) will let you monitor the device connections with its network profiler tool. It won't show you gRPC-level stats, but it will let you see if the packets sent by the server are actually reaching the Android device.

A couple other potentially helpful things to know:

What emulator or physical device was running the Android client? 

What Android API level?

**Comment by ejona86** [comment]
This is generally caused by the network killing the connection (like a router dropping a NAT port mapping) without sending RSTs. In the absence of writes TCP won't notify us of the breakage. You can workaround and detect such networks by using [OkHttpChannelBuilder.keepAliveTime](https://grpc.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html#keepAliveTime-long-java.util.concurrent.TimeUnit-), which will trigger writes that can 1) trigger the network to keep the connection alive and 2) notice if the connection was killed.
