### ISSUE TITLE
Question: what is used as :path pseudo header

### ISSUE THREAD

**Issue by arunkjn** [grpc/grpc-java#3491]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

I am trying to load balance a grpc service using linkerd service mesh. They mention in the docs that they use the :path pseudo header to proxy the request. I wanted to understand what :path equates to with reference to a proto file definition? Is it {package}.{service}?

**Comment by ericgribkoff** [comment]
The format is {proto package}.{service name}/{method name}. See [appendix A](https://grpc.io/docs/guides/wire.html#appendix-a---grpc-for-protobuf) and the [example](https://grpc.io/docs/guides/wire.html#example) in gRPC's wire spec.

In the future, these types of general gRPC questions are better suited for our [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io).
