### ISSUE TITLE
Need to set keep-alive through ManagedChannelBuilder

### ISSUE THREAD

**Issue by garrettjonesgoogle** [grpc/grpc-java#3493]
For Pub/Sub streaming pull, we need to set keep-alive to prevent connections from being dropped. Unfortunately, this seems to only be available on NettyChannelBuilder (https://github.com/grpc/grpc-java/blob/8ee9fb51837a96b18664241a6875ff155843152b/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L278) and not ManagedChannelBuilder. Can we get a way to set this through ManagedChannelBuilder?

**Comment by garrettjonesgoogle** [comment]
cc @ejona86

**Comment by ejona86** [comment]
@garrettjonesgoogle, you also need the API to be stable (non-ExperimentalApi), right?

**Comment by garrettjonesgoogle** [comment]
If it is going to be used as a default behavior anywhere, then it needs to be non-ExperimentalApi. IIUC, we need to have this used as a default for particular APIs. Maybe we could do a short-term thing where it's possible to turn it on explicitly, and we isolate the code path so that the feature isn't touched if it isn't turned on, so that we can still reference it as ExperimentalApi. I imagine that we will have recurring requests for new features along these lines. What do you think?

**Comment by ejona86** [comment]
@garrettjonesgoogle, if your own API be marked experimental as well, then that could maybe work. Although I think it may also be prone to running into diamond dependency problems.

**Comment by garrettjonesgoogle** [comment]
It would absolutely be prone to such problems, and also using a shaded variant of google-cloud-java wouldn't work, which are pretty significant limitations.
