### ISSUE TITLE
Can not build maven project on Raspberry Pi 2 (Arm32)

### ISSUE THREAD

**Issue by schulz-m** [grpc/grpc-java#3505]
All maven projects were easily built on my macbook but now I can not get them to built on my Raspberry Pi (the culprit seems to be the ARM architecture?!)

### What version of gRPC are you using?
Tried several, also tried to simply build the examples on commit hash "589da07" which seems to be using version 1.7.0. I was also using version 1.5.0. 

### What JVM are you using (`java -version`)?
Pre-installed one on Raspberry Pi:
```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
```

### What did you do?
1. I tried to build the examples on version 1.7.0, where it fails to resolve the dependencies: 
```
[ERROR] Failed to execute goal on project examples: 
Could not resolve dependencies for project io.grpc:examples:jar:1.7.0-SNAPSHOT: 
The following artifacts could not be resolved: io.grpc:grpc-netty:jar:1.7.0-SNAPSHOT, io.grpc:grpc-protobuf:jar:1.7.0-SNAPSHOT, io.grpc:grpc-stub:jar:1.7.0-SNAPSHOT, io.grpc:grpc-testing:jar:1.7.0-SNAPSHOT: 
Could not find artifact io.grpc:grpc-netty:jar:1.7.0-SNAPSHOT
```
2. I tried to build by own example based on earlier tutorials on version 1.5.0, with the plugin from github: `com.github.os72:protoc-jar-maven-plugin` which tells me that ARM is not supported
```
[ERROR] Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.4.0:run (default) on project sila_library: 
Error extracting protoc for version 340: Unsupported platform: linux/arm
```
3. On version 1.5.0 I tried to use the "standard" maven plugin, which similarly doesn't seem to find the fitting architecture in protoc executables:
```
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project sila_library: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:linux-arm_32:3.4.0
```

Are ARM architectures simply not supported for "Java protobuf compilers", or am I missing something?

**Comment by zhangkun83** [comment]
Please refer to the [example README](https://github.com/grpc/grpc-java/tree/master/examples) for how to build the example project. Note you need to
 1. Follow the [COMPILING doc](https://github.com/grpc/grpc-java/blob/master/COMPILING.md) to build Protobuf locally, and
 2. Build and install gRPC by running `./gradlew install` from the project root.

We don't release pre-compiled protoc executable for arm, but you should be able to build it locally and follow the documentation of the plugin of you choice to point to your own protoc executable.

**Comment by schulz-m** [comment]
Thank you for the quick response! Indeed that clears things up for me. Unfortunately the Gradle build of the  [COMPILING doc](https://github.com/grpc/grpc-java/blob/master/COMPILING.md) fails because it can not find the `netty_tcnative` libraries:
```
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_arm_32, netty_tcnative_linux_arm_32_fedora, netty_tcnative]
```
I tried to install the library separately via [Maven](http://netty.io/wiki/forked-tomcat-native.html), but it didn't change the outcome...
Any further hints would be appreciated! I will describe the whole process, once succeeded.

**Comment by zhangkun83** [comment]
It seems netty_tcnative, which is used for security, is not available on arm. You should still run it with plaintext, which the helloworld example does. You may try build your own gRPC codegen only and download the rest of the library from the repo:

```bash
git checkout v1.6.1
./gradlew grpc-compiler:install
```
Then modify the example build files to point to gRPC `1.6.1`. Then you should be able to use the released gRPC along with your own gRPC codegen.

/cc @ejona86

**Comment by ejona86** [comment]
netty_tcnative should compile fine on ARM, but you'd have to compile it yourself. Yes, that's a pain. On the bright side Java 9 was released recently, which avoids the manditory requirement for something like netty_tcnative. But from what I've seen of Java's TLS performance (especially on ARM) in the past, I expect you may still want netty_tcnative.

**Comment by schulz-m** [comment]
Can it be that the build is broken? I recently picked up this issue again and cloned the repository on commit hash `0d594361` - now the `grpc-core:test`is failing with:
```
io.grpc.internal.ManagedChannelImplTest > orphanedChannelsAreLogged FAILED
    java.lang.AssertionError: Not true that <2> is at most <0>
```

**Comment by zpencer** [comment]
I saw that test reported as failing in another thread, so it's a possible lake. Is that the only test that's failing? Can you please try re-running to see if it consistently fails?

**Comment by ejona86** [comment]
That test is a flake: #3534. It's fine to ignore for now; there's some static variables and other tests are triggering it to sometimes fail.

**Comment by schulz-m** [comment]
@zhangkun83 I am not taking up this issue anymore for the forseeable future as we decided to just deploy the JAR directly. Should I reopen the issue when I start working on it again?

**Comment by zhangkun83** [comment]
@schulz-m please leave this issue open and feel free to report back when you make progress.

**Comment by ejona86** [comment]
@zhangkun83, actually, it looks like there's not much on our plate for this. Let's close it and it can be reopened if things don't end up working well.
