### ISSUE TITLE
Identifying the type of Stub after an instance is created

### ISSUE THREAD

**Issue by ramaraochavali** [grpc/grpc-java#3513]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
1.8

Currently once a Stub is generated extending from AbstractStub, there is no way to identify whether is a BlockingStub, FutureStub or simple AsnycStub except from the name which is NOT ideal. Identification of Stub, will help enforce any application level checks such as enforcing deadlines for BlockingStub in the enviornment.

**Comment by ramaraochavali** [comment]
PR for [this](https://github.com/grpc/grpc-java/pull/3512)

**Comment by ejona86** [comment]
Since v1.26.0 stubs have extended a base class of their type (i.e., AbstractBlockingStub, AbstractFutureStub, AbstractAsyncStub).
