### ISSUE TITLE
SSL offload best practice?

### ISSUE THREAD

**Issue by smartwjw** [grpc/grpc-java#3526]
### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
1.8

I've developed a backend API for mobile and desktop application using gRPC, its now ready for online, but I can not find any documents about SSL offloading. 

In traditional HTTP + JSON backend API, we often put a Nginx box between clients and application servers, client talks to Nginx with HTTPS, and Nginx talks to application servers using HTTP. But as [this issue](https://github.com/grpc/grpc/issues/11427) indicates, Nginx doesn't support sending http2 traffic to upstream servers yet, and we can't do the same thing we gRPC APIs.

I've searched a lot, and find [nghttp2](https://nghttp2.org/blog/2015/03/24/proxying-grpc-with-nghttpx/) and [envoy](https://envoyproxy.github.io/), but I do not know whether its mature enough, I want to using something proven robust and stable like Nginx. 

Any suggestions?

**Comment by ejona86** [comment]
nghttp2 is heavily used by many projects. It's probably one of the most heavily-used HTTP/2 implementations. So I don't think there's much concern about it being immature. Envoy uses nghttp2, so the HTTP/2 parts of envoy should be stable.

For a wider range of opinions you may consider emailing [grpc-io@googlegroups.com](https://groups.google.com/forum/#!forum/grpc-io) or searching its history.

**Comment by n0mer** [comment]
@smartwjw nginx since 1.13 supports http/2 with ssl: https://www.nginx.com/blog/nginx-1-13-10-grpc/
