### ISSUE TITLE
SSL Related Methods in  ManagedChannelBuilder 

### ISSUE THREAD

**Issue by ramaraochavali** [grpc/grpc-java#3556]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
1.8

### What did you do?
We use `NettyChannelBuilder` for real world use and `InprocessChannelBuilder` for tests. The problem, if we have to use SSL, we need to typecast the `ManagedChannelBuilder` to `NettyChannelBuilder` and call `sslContext`. However in tests, this fails because `InprocessChannelBuilder` does not have the `sslContext` method. We need to do an instance check and then type cast.
Instead similar to how `usePlainText` has been added to `MangedChannelBuilder`, can we add the following methods to `ManagedChannelBuilder`

1.  `negotiationType(NegotiationType)` - Currently there are two versions of `NegotitationType` enum defined, one in netty module and another in http. Is there a reason to have two? or can we combine them and add it to core?
2.  'sslContext(SslContext)' - This would require adding `netty-handler` module to core as a dependency. In the `AbstractManagedChannelImplBuilder` we can just throw `UnsupportedOperationException`. `NettyChannelBuilder` will continue to have its current implementation and `InProcessChannelBuilder` will just `return this`.
3. `sslSocketFactory(SSLSocketFactory factory)`. In the `AbstractManagedChannelImplBuilder` we can just throw `UnsupportedOperationException`. `OkHttpChannelBuilder` will continue to have its current implementation and `InProcessChannelBuilder` will just `return this`.
 This way we do not have to check for the instance type and cast. Switching between the actual channel builder and `InprocessChannelBuilder` would be very seamless. 
What do you think about this?

**Comment by ejona86** [comment]
`negotiationType(NegotiationType)` should be non-essential; there's alternative and stable APIs to achieve the same behavior. Because you're wanting TLS, you shouldn't even need to call the method.

> 'sslContext(SslContext)' - This would require adding netty-handler module to core as a dependency.

Yep. And that's unacceptable. What settings are you using?

> `sslSocketFactory(SSLSocketFactory factory)`

So you're also using the OkHttp transport? Wouldn't this method throw for Netty?

**Comment by ramaraochavali** [comment]
ok. Since Netty is defaulting`negotiationType' to TLS, this may not be required in general case. But in our use case, we are changing the default to use `usePlainText()` and people who want to use ssl will have to call it specifically.
However, if we change the `sslContext(SslContext)` method implementation to set the negotiationType internally like  below - that is non essential. `sslSocketFactory` method of `OkHttpChannelBuilder` does the same.
` public NettyChannelBuilder sslContext(SslContext sslContext) {
    if (sslContext != null) {
      checkArgument(sslContext.isClient(),
          "Server SSL context can not be used for client channel");
      GrpcSslContexts.ensureAlpnAndH2Enabled(sslContext.applicationProtocolNegotiator());
    }
    this.sslContext = sslContext;
    **this.negotiationType = NegotiationType.TLS;**
    return this;
  }`
I am using the default project settings - do I have to change any thing specific?

We are not using OkHttpTransport at this point. Yes. This will throw for Netty. But if we provide no-op implementation for this in `InprocessChannelBuilder` that just returns this, when it is used will work seamlessly.
So the idea is InprocessChannelBuilder will have both the methods with no-op and Netty will have 'sslContext' and OkHttpTransport will have 'sslSocketFactory' - so tests will run with InprocessTransport seamlessly for both Netty and OkHttp.

**Comment by ramaraochavali** [comment]
@ejona86 Here is the [PR](https://github.com/grpc/grpc-java/pull/3561) that explains the idea

**Comment by ejona86** [comment]
Oh, okay, so you just need to allow the consumer of a builder to swap back from plaintext. In that case let's add a `ManagedChannelBuilder.useTransportSecurity()` (similar to ServerBuilder's method, but without args) method which will reverse the `usePlaintext()`. We should specify that using transport security is the default and only necessary to reverse a previous call to `usePlaintext()`.

For Netty, `useTransportSecurity()` would be the equivalent of `negotiationType(NegotiationType.TLS)`.

**Comment by ramaraochavali** [comment]
Ok. Makes sense for the negotiationtype. I will introduce the `useTransportSecurity() ` method in `ManagedChannelBuilder`.

What about the `sslContext()`  and `sslSocketFactory()`methods adding them to `ManagedChannelBuilder` with no-op implementation for `InprocessChannelBuilder` are you OK with those two methods? This is required when we choose transport security and call sslContext or sslSocketFactory to set it up and want to switch to `InprocessChannelBuilder` for testing. If they are in `ManagedChannelBuilder` we do not have to check instance and type cast.

**Comment by ramaraochavali** [comment]
@ejona86 I simplified further and added the method `trustStore(File)` that is used by `NettyChannelBuilder` to build the `sslContext`. This will remove the dependency of netty-handler on core.  I think with this, we will be able to use `InprocessChannelBuilder` and `NettyChannelBuilder` interchangeably as shown below

```
ManagedChannelBuilder channelBuilder = channelBuilder(destination); // This will construct the right channel builder (Netty or Inprocess) based on destination
channelBuilder.useTransportSecurity();
channelBuilder.trustStore(trustStoreFile); //This will build the ssl context.
```

So after the channelBuilder is built after the first call, I just use the same methods whether I am using `InprocessChannelBuilder` (in tests) or  `NettyChannelBuilder` (in real).
Let me know what you think - if you are OK with this, we can do similar thing for `ServerBuilder`

**Comment by ejona86** [comment]
> What about the sslContext() and sslSocketFactory() methods adding them to ManagedChannelBuilder?

No, let's not add those. Those are too specific to one particular transport.

Specifying trustStore is a better possibility, but I'm still hesitant for it because it seems to specific and hard to mix with other methods. I'll comment on it more in the PR.

**Comment by ramaraochavali** [comment]
A new issue https://github.com/grpc/grpc-java/issues/3713 is created for this. So closing this
