### ISSUE TITLE
How can the server distinguish between "client cancelled" and "client timed out"?

### ISSUE THREAD

**Issue by jjhart** [grpc/grpc-java#3563]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.5.0

### What JVM are you using (`java -version`)?

1.8.0_65

### What did you do?

```
//--------------------------------------------------------------------------------
// CLIENT
//--------------------------------------------------------------------------------
void testDeadlines() {
  TestServiceFutureStub stub = getTestServiceStub()
    .withDeadlineAfter(1000, TimeUnit.MILLISECONDS);

  ListenableFuture<TestMessage> guavaFuture = stub.testMethod(...);

  // wait for future to get a value, and then:

  dbgDeadline("CLIENT", stub.getCallOptions().getDeadline());
}


public static void dbgDeadline(String label, Deadline d) {
  System.out.format("%s: expired=%b usRemaining=%d%n", label, d.isExpired(), d.timeRemaining(TimeUnit.MICROSECONDS));
}
```

On the server, `testMethod` sleeps for 1250 ms, so the RPC times out.  I have also registered a cancellation listener on the call's `Context`:

```
//--------------------------------------------------------------------------------
// SERVER INTERCEPTOR
//--------------------------------------------------------------------------------
public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
  Context.current().addListener(c -> dbgDeadline("SERVER", c.getDeadline()), Runnable::run); // 2nd arg is just a direct executor in calling thread
  ...
}
```

The output is:

```
SERVER: expired=false usRemaining=16793
CLIENT: expired=true usRemaining=-9908
```

I understand why this is the case - the client times out first & sends a cancellation, which the server processes prior to its own (apparently network-padded) Deadline expiring.

For our internal metrics, however, we want to track "the client cancelled the RPC *early*" as distinct from "the client timed out the RPC" (which, for our purposes, is the same as the timeout happening at the server side).

Is this possible?  I don't want to reverse the server's pad-deadline-because-network logic.

It seems like I need to hook into the server code that handles the client's "send cancellation upon timeout" signal, *and* hope that differs from the client's "send cancellation upon cancellation" signal.

**Comment by jjhart** [comment]
I see that the latest grpc-java versions (1.6.1+) have Census integration, so I suspect I'll be using this for the metrics I want to gather.  So this may all be beside the point..

In addition to the `Context.CancellationListener` shown above, I also tried to ascertain deadline-exceeded status via `ServerCall.Listener`.  I may be missing something obvious, but I don't see a spot in the API where the server has visibility into the client's reason for cancelling.  The API of `ServerCall.Listener` doesn't provide access to a client `Status`, and `Context.cancellationCause()` remains null after the client cancels the call.

**Comment by carl-mastrangelo** [comment]
@jjhart Hey,

You should be able to tell if you get a CANCELLED or a DEADLINE_EXCEEDED code.

**Comment by jjhart** [comment]
@carl-mastrangelo Thanks for the reply - where in the API can I see the code?

The `ServerCall.Listener` methods don't have arguments (other than `onMessage`, which doesn't fire for the cancellation).  That leaves me looking at statics (`Context.current()`) or things that I capture when I set up the listener (the `ServerCall`).  Neither of those have accessors that give me a `Status` or `Code`.

**Comment by carl-mastrangelo** [comment]
Oh yeah, you're right.  The core of the problem is that The client sends a RST_STREAM when a deadline fires on the client, as well as when the the application calls close(). The client doesn't send trailers, so there isn't room on the wire for it.  (I thought in my first response the server would create the correct code, but alas it does not).

If you have a streaming RPC, you can add this kind of information into your message to indicate it is shutting down early.  I don't think the library can do this for you.

Are you doing client streaming, server streaming, bidi, or unary calls?

**Comment by jjhart** [comment]
So far, just unary calls.   This is not an major issue, for sure - we won't switch to streaming just to have a place to send out-of-band ex info from the client to the server.  We can also collect the stats on the client side (this is all server-server, so we control both ends) and aggregate from there.

 Mostly I'm glad to hear that I'm not crazy, as I just came up empty after crawling through every hook I could find in both the docs and in the debugger.
