### ISSUE TITLE
Try to allow building java without having to build codegen

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#357]
It may be possible to use the last released codegen binary.

**Comment by zhangkun83** [comment]
Some thoughts:

- Run a continuous build service (e.g., Jenkins) to build codegen and push it to snapshot repo for every commit. We will need three machines (Linux, Mac and Windows) for this.
- Disable ``grpc-compiler`` by default when building the root project. If ``grpc-compiler`` is disabled, other subproject will use the codegen with the same version number as the current code. So if the code is ``SNAPSHOT``, codegen will be from the snapshot repo. This should relieve a lot of pain for most contributors who don't touch the codegen.
- Contributors that do change the codegen must use an option to enable building compiler locally. Alternatively they could install their changed codegen locally.

**Comment by ejona86** [comment]
I thought of another option that I think could work well and isn't hacky: we check in the generated code. We make code generation not part of "compile" and only run it when we are modifying the code generator.

**Comment by zhangkun83** [comment]
This is actually a good idea. Where do you think we should put the generated code? I am thinking ``src/generated/java/``

**Comment by ejona86** [comment]
SGTM.
