### ISSUE TITLE
Grpc fails to build with Windows 7 + MSys2 (with MinGW-W64) + Bazel

### ISSUE THREAD

**Issue by William8915** [grpc/grpc-java#3582]
### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
1.8.0_144

### What did you do?
I was trying to compile a project that depends on `grpc-java`

To reproduce, simply write a bzl file that includes the five lines mentioned later.
Then build the project with Bazel

### What did you expect to see?
I expect to see the project successfully built.

### What did you see instead?
```
ERROR: C:/users/zwjchem/symmpath/kaggle/BUILD:24:1: error executing shell command: 'cp $1 $2' failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/zwjchem/appdata/local/temp/_bazel_zwjchem/ttnpzybf/execroot/symmpath
D:/msys64/usr/bin/bash.exe -c cp $1 $2  bazel-out/msvc_x64-fastbuild/bin/kaggle/api_java_grpc__do_not_reference__srcjar_src.jar bazel-out/msvc_x64-fastbuild/bin/kaggle/api_java_grpc__do_not_reference__srcjar.srcjar.
cp: missing destination file operand after 'bazel-out/msvc_x64-fastbuild/bin/kaggle/api_java_grpc__do_not_reference__srcjar.srcjar'
Try 'cp --help' for more information.
Target //kaggle:job-manager failed to build
____Elapsed time: 58.566s, Critical Path: 6.88s
```

Manually modifying lines 32 to 36 in `java_grpc_library.bzl` solves the issue.

**Comment by carl-mastrangelo** [comment]
Can you show what lines you changed to make it work?

**Comment by William8915** [comment]
---
ctx.action(
      command = "cp $1 $2",
      inputs = [srcdotjar],
      outputs = [ctx.outputs.srcjar],
      arguments = [srcdotjar.path, ctx.outputs.srcjar.path])
---

**Comment by William8915** [comment]
I changed
```
ctx.action(
      command = "cp $1 $2",
      inputs = [srcdotjar],
      outputs = [ctx.outputs.srcjar],
      arguments = [srcdotjar.path, ctx.outputs.srcjar.path])
```
to
```
  ctx.actions.run_shell(
      command = "cp " + srcdotjar.path + " " +ctx.ouputs.srcjar.path,
      inputs = [srcdotjar],
      outputs = [ctx.outputs.srcjar])
```
This is not an elegant fix and I am not sure what's the effect in other systems.

**Comment by ejona86** [comment]
It looks like a bug in Bazel, given that the documentation [explicitly says to use syntax like $1](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#action). Although action is deprecated, actions.run_shell supports the same syntax.

It's not clear what's actually breaking, since it seems like cp is seeing the $2 replaced. Since the error only mentions the .srcjar, that means the .jar and .srcjar are being passed as separate arguments. Since .srcjar is last, it isn't an off-by-one where there is an empty argument first (so $1 == "" and then is ignored as an argument to cp). And since we have the clearly quoted 'cp $1 $2' at the beginning, it isn't being passed wrong either.

**Comment by William8915** [comment]
I agree with @ejona86 's analysis. It covers many aspects of the problem and provides a logical analysis. I have noticed that the same file works perfectly fine in Ubuntu and Mac. It just fails in Windows.

While it is not necessarily a bug in grpc-java and may be a bug in bazel, I believe that it does not harm to modify the code so that it can also run in Windows as well as in *NIX systems. I would thank the development group in advance for all the efforts.

**Comment by William8915** [comment]
Also it can be seen that the actual command being executed is,
`D:/msys64/usr/bin/bash.exe -c cp $1 $2  bazel-out/msvc_x64-fastbuild/bin/kaggle/api_java_grpc__do_not_reference__srcjar_src.jar bazel-out/msvc_x64-fastbuild/bin/kaggle/api_java_grpc__do_not_reference__srcjar.srcjar`

**Comment by ejona86** [comment]
Based on what we're seeing, I think the command is properly quoting the cp:
```
D:/msys64/usr/bin/bash.exe -c 'cp $1 $2' bazel-out/msvc_x64-fastbuild/bin/kaggle/api_java_grpc__do_not_reference__srcjar_src.jar bazel-out/msvc_x64-fastbuild/bin/kaggle/api_java_grpc__do_not_reference__srcjar.srcjar
```

But in that case the command looks correct.

This is still on our plate, until there is a bug filed with Bazel.

**Comment by William8915** [comment]
I am afraid that's not the case. Here are some tests in CentOS,
```
[user@localhost ~]$ bash -c cp $1 $2 a b
cp: missing file operand
Try `cp --help' for more information.
[user@localhost ~]$ bash -c 'cp $1 $2' a b
cp: missing destination file operand after `b'
Try `cp --help' for more information.
[zwjchem@alps ~]$ bash -c 'cp $1 $2 a b' && echo success
success
```

**Comment by ejona86** [comment]
> If  the  -c  option is present, then commands are read from the first non-option
                 argument command_string.  If there are arguments after the command_string,  they
                 are assigned to the positional parameters, starting with $0.

Doh. It is bash _itself_ that is handling the 0 position. Although that does raise the question of why only Windows is broken.

```
$ bash -c 'echo $1 $2' a b
b
$ bash -c 'echo $1 $2' echo a b
a b
```

**Comment by ejona86** [comment]
I've filed a bug against Bazel, so I'm going to close this for now. There is a possible workaround, but I'd worry it breaks other cases due to lack of escaping.
