### ISSUE TITLE
Metadata not being propagated between client adn server

### ISSUE THREAD

**Issue by magpor** [grpc/grpc-java#3600]
Please answer these questions before submitting your issue.

### What did you do?
If possible, provide a recipe for reproducing the error.

### What did you see instead? No metadata available in server interceptor

I am trying to send a subscriber id from the client to the server, both in java.

On the client side 
```
@Override
    public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {
        return new ForwardingClientCall.SimpleForwardingClientCall<ReqT, RespT>(next.newCall(method, callOptions)) {
            @Override
            public void start(Listener<RespT> responseListener, Metadata headers) {
                Metadata metadata = new Metadata();
                metadata.put(KEY, subscriberId);
                headers.merge(metadata);
                super.start(new ForwardingClientCallListener.SimpleForwardingClientCallListener<RespT>(responseListener){},headers);
            }
        };

    }
```
On the server side
```
@Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> serverCall,
                                                                 Metadata metadata,
                                                                 ServerCallHandler<ReqT, RespT> serverCallHandler) {
        System.out.println( metadata.get(SubscriberClientInterceptor.KEY);)
       
        return serverCallHandler.startCall(serverCall, metadata);
    }
```

The value is null and I dont understand why. It is working when running in-memory tests but when deployed no luck.

I see that the header is added to the metadata in the client interceptor but is not available in the server interceptor when printing the keys there are 3 default keys from gRPC

**Comment by zpencer** [comment]
I've copied and pasted your interceptor into the interceptors in `examples/src/main/java/io/grpc/examples/header` on branch `v1.3.x` and I'm able to retrieve the custom value. Can you compare how you're installing the interceptors with the example code for possible differences?

**Comment by magpor** [comment]
Actually, I also got it working in a test but when I start the server and client side in a Jetty container the metadata is lost. Hmm where can I debug to see what metadata is sent?

So this is the way I should do it right? I dont need to think about thread safty or anything here right?

**Comment by magpor** [comment]
Could this have to do with Jetty settings so that it does not allow us to send custom metadata values from Jetty somehow? Might it be a Netty setting or something? Just bouncing ideas since it seems only to happen when running in Jetty

**Comment by zpencer** [comment]
The example I pointed to is thread safe. So this only fails when the client is a jetty HTTP servlet? Does it work if you are not running inside a servlet?

We do not specifically test for compatibility with jetty containers, so I don't know what special restrictions may be there. But grpc creates its own TCP connections so I doubt jetty is interfering. If you want to capture the TCP traffic to verify that the headers are sent, you can disable TLS so that traffic is sent in plain text:
https://github.com/grpc/grpc-java/blob/v1.3.x/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L426

**Comment by magpor** [comment]
I will look at what is sent tomorrow. I agree this should not be affected by Jetty but I am kind of guessing a bit :-) Thanks I will let you know tomorrow

**Comment by magpor** [comment]
So heres the deal.

 When we use  MetadataUtils.attachHeaders(serviceRegistryBlockingStub, metadata); it works but now when setting it in the client interceptor? hmm whats the difference is it a context problem or something maybe?

**Comment by magpor** [comment]
This is how we add the interceptors

 ManagedChannel managedChannel = ManagedChannelBuilder
                .forTarget(String.format(API_REGISTRY_NAME_PATTERN, apiClientProviderDefinition.getApi(), apiClientProviderDefinition.getVersion()))
                .loadBalancerFactory(loadBalancerFactory)
                .nameResolverFactory(apiNameResolverProvider)
                .intercept(clientInterceptors)
                .usePlaintext(true)
                .build();

**Comment by magpor** [comment]
OMG we are idiots :-) Sorry it was our fault completely so lets close this 

Thanks for the help anyways

Magnus
