### ISSUE TITLE
Question:How can I get the a field name?

### ISSUE THREAD

**Issue by dingrui37** [grpc/grpc-java#3622]
For example, I want to get the field name "a", how to do？
```
message ABC {
    uint32 a = 1;
    string b = 2;
    bytes c = 3;
}
```

**Comment by ejona86** [comment]
I'm not sure I understand and this sounds like a protobuf question, but you can use the protobuf reflection API: `ABC.getDescriptor().getField(0).getName()`.

**Comment by dingrui37** [comment]
@ejona86 Thanks
