### ISSUE TITLE
Ranged version in grpc-netty cause maven-metadata download every build.

### ISSUE THREAD

**Issue by smartwjw** [grpc/grpc-java#3634]
### What version of gRPC are you using?
1.7.0

### What JVM are you using (`java -version`)?
java version "1.8.0_144"

I found following maven config in `grpc-netty-1.7.0.pom`:

```xml
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-core</artifactId>
      <version>[1.7.0]</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-codec-http2</artifactId>
      <version>[4.1.16.Final]</version>
      <scope>compile</scope>
    </dependency>
```

Please don't use ranged version.

**Comment by ejona86** [comment]
I assume you're using Maven? This seems like a Maven issue. We need the version to be pinned; other versions are likely to break.

I know Gradle's behavior is to cache the version results for a day, and the check can be disabled using `--offline`.

**Comment by smartwjw** [comment]
Yes, I'm using Maven, IMHO, the best way to pin version is using the exactly version, not the ranged version, eg: `<version>1.7.0</version>` .

**Comment by ejona86** [comment]
How does that pin the version? Maven will freely downgrade or upgrade the version, in a way that is unhelpful enough that most Maven users should use Maven Enforcer to double-check its work. And that syntax is the normal syntax projects use for deps, so there isn't any indication that "we really mean it."
