### ISSUE TITLE
please provide a way to expose client host / ssl certificate information

### ISSUE THREAD

**Issue by pattyshack** [grpc/grpc-java#3639]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.6

### What JVM are you using (`java -version`)?

1.8

### What did you do?
If possible, provide a recipe for reproducing the error.

(This assumes mutual authentication is enable)

In our production environment, we use the tls certificate's common name as the client (/server) identity.  Our servers need access to the the client identity in order to perform application specific ACLs.

### What did you expect to see?

In go/python, the server automatically populates the client's host/cert info into the context, and the information are accessible via:

https://godoc.org/google.golang.org/grpc/peer
https://grpc.io/grpc/python/grpc.html#grpc.ServicerContext

java should provide an equivalent interface for accessing these information.

### What did you see instead?

The information are available within the netty grpc core (SSLEngine.getSession(), but afaik, are not exposed to the user in any way).

**Comment by ericgribkoff** [comment]
I believe these are exposed as gRPC attributes (`TRANSPORT_ATTR_REMOTE_ADDR`, `TRANSPORT_ATTR_SSL_SESSION`) by Netty. These are set [here](https://github.com/grpc/grpc-java/blob/30b59885b7496b53eb17f64ba1d822c2d9a6c69a/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L635) and an example of accessing them is [here](https://github.com/grpc/grpc-java/blob/30b59885b7496b53eb17f64ba1d822c2d9a6c69a/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java#L1650).

**Comment by pattyshack** [comment]
Thanks for pointing this out.  I'll create a ServerInterceptor to extract the information / populate it into Context.

Attributes and Context provide very similar functionality.  It maybe worth while to consolidate Attributes and Context (having a separate Metadata make sense)

**Comment by carl-mastrangelo** [comment]
@pattyshack The API is similar, but the scope is different.  Attributes are a more transport specific thing, while Context is a RPC specific thing.

**Comment by carl-mastrangelo** [comment]
Attributes are intentionally harder to access.  You shouldn't need them in the course of normal usage.

> Perhaps double registering the client info into Attributes and Context is the right thing to do here?

Unfortunately it cannot be.  The Attribute scope is wider, but flatter.  Context is more focused.   Normally there is overlap between them, but it breaks down when there is not.  Two reasons why it would be odd:

1.   Attribute level info is not RPC specific.  If you RPC is created in an interceptor, you have access to the transport level attributes.  (say the SSL certificate).  You can access it, but it may change after you start your RPC.  How?  If the connection fails during `call.start()`, gRPC could retry the call on a different transport with a different cert.  You would have no way of knowing.  Example:
```
call = channel.newCall()
ssl1 = call.getAttributes().get(SSL_KEY);
call.start(...)
ssl2 =  call.getAttributes().get(SSL_KEY);
ssl1 != ss2
```

2. Context level info is not transport specific.  The auth tokens created per RPC may not apply to the connection as a whole.  Consider the case of a proxy.  All of the RPCs comming in may be funneled to a single outgoing connection, even though they all have different auth levels.  It wouldn't make sense to put the context info in the attributes, which are shared among all RPCs.

**Comment by ejona86** [comment]
@pattyshack, as @carl-mastrangelo said:
> Attributes are intentionally harder to access.

This is because the information is low-level. Normal application logic should not be digging into the SSLSession to grab the X500Principal or, by default, have easy access to the remote IP. That makes the authentication code very difficult to audit.

Instead, we expect applications to have a shared interceptor that does authentication and validation and provides a "safe" result to the application handlers. That interceptor then becomes a sort of "policy" that can be audited easily and you then only have to deal with authz in the core application.

If you're just copying values from Attributes to Context, then I agree it's annoying. But we would discourage doing so.

**Comment by pattyshack** [comment]
Thanks for the explaining the design choices.
