### ISSUE TITLE
testing should be a Bazel package

### ISSUE THREAD

**Issue by Ubehebe** [grpc/grpc-java#3643]
Currently, much of the repo is usable as a Bazel external repo through the provided BUILD.bazel files. This allows Bazel users to express dependencies like `@grpc_java//core`.

`testing` should also have a BUILD.bazel file, so that Bazel users use things like GrpcServerRule. (Currently, Bazel users can use this by depending on the `grpc-testing` Maven jar, but depending on both Maven and Bazel versions of grpc-java seems like a bad idea in the long run.)

**Comment by carl-mastrangelo** [comment]
@Ubehebe want to send a PR?

**Comment by Ubehebe** [comment]
Looks like @sconover fixed this last week with https://github.com/grpc/grpc-java/commit/167029610ecba52d1d2ae95af5dc27dd109eb4af. Great!
