### ISSUE TITLE
Bazel: java_grpc_library rules can not be used from another repository (contains fix)

### ISSUE THREAD

**Issue by ah-edg** [grpc/grpc-java#3650]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.7.0
### What JVM are you using (`java -version`)?

openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

Import Bazel rules in a proto repository from another proto repository

### What did you expect to see?

The other repository should be useable with Bazel

### What did you see instead?

Build errors

I traced this here:
https://github.com/grpc/grpc-java/blob/8a9660c7008c20151f38db78fe59a0796083ae11/java_grpc_library.bzl#L31

The error disappeared after changing it from
`+ [src.short_path for src in srcs])`
to
`+ [_path_ignoring_repository(src) for src in srcs])`

The `-I` imports already define aliases, but whatever `src.short_path` produces is prefixed with `../` and the proto-repo workspace name. That directory is not available in the build directory of the importing repo.

After this change, it worked in both the proto repo and the repo importing it.

If required, I can work on a reproducer or provide additional details - @-mention me in that case.
I still hope the description is sufficient... :wink:

**Comment by carl-mastrangelo** [comment]
Want to send a PR?

**Comment by ah-edg** [comment]
I can, but I'd prefer not to. I'm not sure if L10-L12 should also be deleted and I don't want to wait for the CLA dance. This is really minor, just take it; I only want it fixed :grin: 
I'd be very, very thankful for a new release containing it, though...

Overall: Thank you all for this. I need it for Java-Go interop in a single repo and the currently developing ecosystem spearheaded by Google devs (esp. grpc, bazel, go) makes work so much more pleasurable.

**Comment by ejona86** [comment]
It seems like we need a test that does this. I guess our examples don't find it because they aren't doing cross-repo includes.
