### ISSUE TITLE
Don't use SerializingExecutor when running with a direct executor.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#368]
I wanted to know what the impact of the `SerializingExecutor` is when running with a direct executor.

So I did 3 benchmarks, choosing the best out of 3 runs.

##### Direct Executor + Serializing (current master)
```
buchgr@buchgr0:~/Code/grpc-java/benchmarks/build/install/grpc-benchmarks/bin$ ./qps_client --port=33333 --host=localhost --channels=8 --outstanding_rpcs_per_channel=10 --warmup_duration=10s --duration=30s --server_payload=1 --client_payload=1 --directexecutor
Channels:                       8
Outstanding RPCs per Channel:   10
Server Payload Size:            1
Client Payload Size:            1
50%ile Latency (in micros):     669
90%ile Latency (in micros):     1817
95%ile Latency (in micros):     3231
99%ile Latency (in micros):     5727
99.9%ile Latency (in micros):   9255
QPS:                            78642
```

##### Direct Executor + Serializing Executor without synchronized blocks.
```
buchgr@buchgr0:~/Code/grpc-java/benchmarks/build/install/grpc-benchmarks/bin$ ./qps_client --port=33333 --host=localhost --channels=8 --outstanding_rpcs_per_channel=10 --warmup_duration=10s --duration=30s --server_payload=1 --client_payload=1 --directexecutor
Channels:                       8
Outstanding RPCs per Channel:   10
Server Payload Size:            1
Client Payload Size:            1
50%ile Latency (in micros):     655
90%ile Latency (in micros):     1647
95%ile Latency (in micros):     3083
99%ile Latency (in micros):     5679
99.9%ile Latency (in micros):   9607
QPS:                            81500
```

##### Direct Executor only, no Serializing Executor
```
buchgr@buchgr0:~/Code/grpc-java/benchmarks/build/install/grpc-benchmarks/bin$ ./qps_client --port=33333 --host=localhost --channels=8 --outstanding_rpcs_per_channel=10 --warmup_duration=10s --duration=30s --server_payload=1 --client_payload=1 --directexecutor
Channels:                       8
Outstanding RPCs per Channel:   10
Server Payload Size:            1
Client Payload Size:            1
50%ile Latency (in micros):     619
90%ile Latency (in micros):     1096
95%ile Latency (in micros):     1132
99%ile Latency (in micros):     3999
99.9%ile Latency (in micros):   11407
QPS:                            99904
```

So it seems to me that the potential improvement is significant enough to make some changes and not use a `SerializingExecutor` when using direct i.e. by adding an option to the Server / Channel Builders. 
WDYT @nmittler @louiscryan @ejona86 ?

**Comment by nmittler** [comment]
Nice!  SGTM

**Comment by nmittler** [comment]
Should we just make DirectExecutor the default?

**Comment by ejona86** [comment]
No, we can't really make DirectExecutor the default given all the trouble that caused with Stubby in the past. We really want people to opt-in to the "don't block, ever" requirement.

**Comment by louiscryan** [comment]
Impressive!

I'm with Eric on this one. The fact that we have an explicit directive in the builder to use direct executor means that we can still plumb this in just fine.

**Comment by buchgr** [comment]
Would you prefer to add a `DirectExecutor` to grpc and special case this class when set in `Builder.executor(...)` or have an additional option `Builder.directExecutor()`? I would prefer the latter.

**Comment by ejona86** [comment]
I agree with @buchgr's proposal on having a `directExecutor()` on the Builders.

If we wanted our options to be orthogonal, we could have an option `disableSerializedCallbacks()` or some such. We could still have `directExecutor()` which would be the equivalent of calling `executor(directExecutor)` and `disableSerializedCallbacks()`. I don't have many other use cases of `disableSerializedCallbacks()`, though, so I question if it is useful. I've considered fanning out streaming requests to multiple threads. Also an "advanced" direct executor that sets a thread-local or some such.

**Comment by buchgr** [comment]
hmm. is that still of interest or is looking into speeding up `SerializingExecutor` a better idea (i.e. #1050)? I have a lock free version using CAS and a queue from JCTools pushed to a branch somewhere, but if I recall correctly it had some bugs :).

**Comment by louiscryan** [comment]
This is still of interest as a straightforward fix.

A better form of executor striping + JCTools might be the way to go in the
long run but there is probably more performance mileage to be gotten out of
the GRPC Deframer and I have some stuff queued up there.
I believe JCTools released a new version with a bunch of fixes in the SPSC
growable array queue

**Comment by buchgr** [comment]
ok I ll open a PR.
