### ISSUE TITLE
some jars or java files are missing in examples module !!

### ISSUE THREAD

**Issue by KingWang93** [grpc/grpc-java#3700]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
1.8

### What did you do?
when using examples，io.grpc.examples.helloworld.GreeterGrpc；io.grpc.examples.helloworld.HelloReply；
io.grpc.examples.helloworld.HelloRequest;
io.grpc.examples.helloworld.GreeterGrpc.GreeterBlockingStub;
io.grpc.examples.helloworld.GreeterGrpc.GreeterFutureStub;
io.grpc.examples.helloworld.GreeterGrpc.GreeterStub;
these classes are missing.

### What did you expect to see?
no error

### What did you see instead?
no dependencies(examples above)

**Comment by KingWang93** [comment]
it seems that objc_class_prefix is not recognized in the proto file

**Comment by ejona86** [comment]
If you don't see an error, then how do you know the classes are missing? Is the problem that they are unknown to your IDE? If so, that may have been fixed by #3598.

**Comment by nvnobelen** [comment]
The files defining the classes are just not there in the package (ie: Not created on github, completely absent), so the most simple form of problem: File not there.

**Comment by ejona86** [comment]
They are generated by the gradle/maven builds, by protoc. For example, after building with gradle, the files will be under `build/generated/`
