### ISSUE TITLE
Callbacks for analyzing the State of the Channel

### ISSUE THREAD

**Issue by wingoku** [grpc/grpc-java#3721]
It's more of a question rather then an issue. I want to be notified about the channel state every time it changes. However I couldn't find any API for that. The only method that I could find was `notifyWhenStateChanged()`, however the problem is, this method only gets called once. 

Ideally the callback of this method should be called every time the state changes from the current state the channel is in.

The really dirty workaround I have implemented to get notified about the connectivity status is to call 
 `channel.getState(true)` periodically after every X milliseconds. Then I return the state of the channel in my own callback.

Is there a way to figure out when:

1. The client gets disconnects from the server
2. The client is connected with the server
3. The client is able to send messages to the server & receive messages from the server.

**Comment by ejona86** [comment]
After being notified, you need to call `notifyWhenStateChanged()` again to have it notify you again. You might take a look at https://github.com/grpc/grpc-java/issues/3763#issuecomment-352487188 .

It seems like that should be all you need, so closing. If that doesn't work for you, just comment on this issue about what doesn't work and we can re-open it.
