### ISSUE TITLE
FRAME_SIZE_ERROR: 4740180 (Wifi only)

### ISSUE THREAD

**Issue by debase** [grpc/grpc-java#3722]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
gRPC for Android v1.6.1

Hi everyone, 

I am reporting an issue that concerns more than 100 users in our production environment.
It seems to already have been reported on the issue [#2436](https://github.com/grpc/grpc-java/issues/2436) but I am sure I am connecting to the right gRPC server.

Every web API call throws the same FRAME_SIZE_ERROR exception.

Users that reported the issue have different smartphones, Android versions and network provider.
If we ask them to switch from wifi to mobile data, everything works fine. Is there any chance that some wifi routers configuration or network provider cause this issue?

This issue seems to happen since we moved to gRPC from the version 1.2.0

`
Non-fatal Exception: java.io.IOException: FRAME_SIZE_ERROR: 4740180
       at io.grpc.okhttp.internal.framed.Http2.ioException(Http2.java:590)
       at io.grpc.okhttp.internal.framed.Http2.access$200(Http2.java:47)
       at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:137)
       at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:860)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
`

**Comment by carl-mastrangelo** [comment]
Are you sending frames larger than 4MB?

**Comment by debase** [comment]
Hi @carl-mastrangelo, not at all, most of our requests are very lightweight. I really don't understand why it only happens on wifi.

**Comment by carl-mastrangelo** [comment]
@debase One reason is that unexpected data was sent to it.  If you reinterpret the bytes the length reads as '066' in ascii, which looks like some other protocol is being sent to gRPC.  Is it possible some other program on your wifi network is contacting your grpc server?

**Comment by ericgribkoff** [comment]
@debase Can you reproduce the issue? What gRPC language/version are you using for your server implementation? Were able to verify on the server-side if the client failures on wifi are actually reaching your gRPC server?

**Comment by ejona86** [comment]
4740180 is actually "HTT" (it is 0x485454; decimal 48 is '0', but hex 48 in 'H'). So this seems exactly like that other issue.

I wouldn't be surprised if a captive portal or something similar was involved. But there doesn't seem much that we can do on the GRPC-side.

**Comment by ejona86** [comment]
Errr... I guess not captive portal. But maybe a TLS interceptor? I'd sort of expect all the users were on the same network.
