### ISSUE TITLE
UNAVALIABLE status documentation

### ISSUE THREAD

**Issue by oillio** [grpc/grpc-java#3747]
In the documentation for Status.Code there is this (in FAILED_PRECONDITION comment):

> A litmus test that may help a service implementor in deciding
     * between FAILED_PRECONDITION, ABORTED, and UNAVAILABLE:
     * (a) Use UNAVAILABLE if the client can retry just the failing call.
     * (b) Use ABORTED if the client should retry at a higher-level
     * (e.g., restarting a read-modify-write sequence).
     * (c) Use FAILED_PRECONDITION if the client should not retry until
     * the system state has been explicitly fixed.  E.g., if an "rmdir"
     * fails because the directory is non-empty, FAILED_PRECONDITION
     * should be returned since the client should not retry unless
     * they have first fixed up the directory by deleting files from it.

From this, I had assumed that UNAVALIABLE could be used to inform the client that they could retry the call with no regard to possibly modified state.
However, from #1053, it looks like UNAVALIABLE may be sent by the gRPC client if there is a network error during the response, which means the client cannot blindly retry the call.

It would be nice if UNAVALIABLE did guarantee idempotency.  Otherwise, the documentation might be updated to avoid giving the wrong impression.

**Comment by carl-mastrangelo** [comment]
@oillio Yeah, its sad that it got reused.  There was a lot of arguing about which codes should be used for which purpose. 

I think you can define your methods as idempotent in the proto file.  Other wise you're stuck looking at the metadata to see if any modifications actually happened.

**Comment by oillio** [comment]
I'll use the idempotency_level MethodOptions.  Thanks for pointing me to it.
For anyone that runs across this, this is how it is currently defined in descriptor.proto:

>   // Is this method side-effect-free (or safe in HTTP parlance), or idempotent,
  // or neither? HTTP based RPC implementation may choose GET verb for safe
  // methods, and PUT verb for idempotent methods instead of the default POST.
  enum IdempotencyLevel {
    IDEMPOTENCY_UNKNOWN = 0;
    NO_SIDE_EFFECTS     = 1; // implies idempotent
    IDEMPOTENT          = 2; // idempotent, but may have side effects
  }
  optional IdempotencyLevel idempotency_level =
      34 [default=IDEMPOTENCY_UNKNOWN];
