### ISSUE TITLE
ManagedChannel getState/notifyChanged API docs

### ISSUE THREAD

**Issue by dcow** [grpc/grpc-java#3762]
I'm using gRPC 1.7 (on Android) and notice the docs for `ManagedChannel` still say this functionality is unimplemented (and the base implementation throws as it should). However, the `MannagedChannelImpl` (which `OkHttpChannelImpleBuilder` uses) has this implemented. Is this an oversight or on purpose? It caused me to dive into the issues (culminating in https://github.com/grpc/grpc-java/issues/2292) to figure out if this was actually supported yet (I've determined it is). Should the docs be updated to something a little more helpful?

**Comment by carl-mastrangelo** [comment]
We don't own all implementations of ManagedChannel, so we cannot be certain all implementations do.  The only known implementation, ManagedChannelImpl, does implement it.  Using ManagedChannelBuilders written by the gRPC team will implement these methods.

**Comment by carl-mastrangelo** [comment]
@dapengzhang0 Do you know if the Channel state APIs are complete an implemented everywhere?  Can the warning be removed?

**Comment by dapengzhang0** [comment]
The warning should be removed since the API is implemented in the main impl of `ManacheChannel` in the gRPC library.

**Comment by ejona86** [comment]
Fixed by #3768
