### ISSUE TITLE
Can´t build HelloWorld Android project

### ISSUE THREAD

**Issue by jyeonyy** [grpc/grpc-java#3780]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.7.x

### What did you expect to see?
want to activate instruction 'gradlew installDist' 
i referenced and followed this page https://github.com/grpc/grpc-java/blob/master/COMPILING.md and https://github.com/grpc/grpc-java/blob/master/examples/README.md 
but, it doesn't work on my cmd window
what is the problem!?!??????

* What went wrong:
Could not resolve all files for configuration ':protobufToolsLocator_grpc'.
> Could not find io.grpc:protoc-gen-grpc-java:1.7.1-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.7.1-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.7.1-SNAPSHOT/protoc-gen-grpc-java-1.7.1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.7.1-SNAPSHOT/protoc-gen-grpc-java-1.7.1-SNAPSHOT-windows-x86_64.exe
      file:/C:/Users/jiyeon/.m2/repository/io/grpc/protoc-gen-grpc-java/1.7.1-SNAPSHOT/maven-metadata.xml
      file:/C:/Users/jiyeon/.m2/repository/io/grpc/protoc-gen-grpc-java/1.7.1-SNAPSHOT/protoc-gen-grpc-java-1.7.1-SNAPSHOT.pom
      file:/C:/Users/jiyeon/.m2/repository/io/grpc/protoc-gen-grpc-java/1.7.1-SNAPSHOT/protoc-gen-grpc-java-1.7.1-SNAPSHOT-windows-x86_64.exe
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 5s
6 actionable tasks: 1 executed, 5 up-to-date

**Comment by ericgribkoff** [comment]
We suggest checking out a release tag first, e.g., `git checkout v1.7.0`. Then you won't need to install gRPC first. See https://grpc.io/docs/quickstart/android.html for more details.

If you want to first build and install gRPC following the instructions in COMPILING.md, the error you've encountered sounds like you might have built with skipCodegen=true. I believe you'll need to build and install codegen if you're not on a release tag.
