### ISSUE TITLE
You don't have permission to use the application 'protoc-gen-grpc-java-1.7.0-osx-x86_64'

### ISSUE THREAD

**Issue by crilofer** [grpc/grpc-java#3781]
### What version of gRPC are you using?

1.7.0

### What did you expect to see?

I am trying to build my application that uses protocol buffers. But I am getting the error shown in the screenshot attached.

<img width="451" alt="screen shot 2017-11-20 at 10 34 53" src="https://user-images.githubusercontent.com/6973711/33014264-a5cc39d2-cdde-11e7-8222-16a2791514ae.png">

Error:Execution failed for task ':app:generateDebugProto'.

  /.gradle/caches/modules-2/files-2.1/io.grpc/protoc-gen-grpc-java/1.7.0/45f3ff6d2b9cbb9fa327dc6a23dba114e2a8094e/protoc-gen-grpc-java-1.7.0-osx-x86_64.exe: program not found or is not executable
  --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.

Thanks.

**Comment by carl-mastrangelo** [comment]
Hmm, how come the application names dont match between the error text, and the screen you posted?

**Comment by crilofer** [comment]
Sorry, but also using 1.7.0 it's not working.

**Comment by carl-mastrangelo** [comment]
Off the top of my head, could this be on a noexecute disk partition?   Also, does it have the +x bit set?

**Comment by crilofer** [comment]
The file has 777 permissions. I can execute using command line but no output is showing

**Comment by carl-mastrangelo** [comment]
The program is meant to be part of the the protoc compiler, which passes in data through stdin, and reads from stdout.  Running it is enough to see that it works.  

One other thing: the error message you have says `protoc-gen-grpc`  but, all our artifacts are `protoc-gen-grpc-java`.  @zhangkun83 any ideas?

**Comment by crilofer** [comment]
This is my protobuf block
`protobuf {
    protoc {
        path = '/usr/local/bin/protoc'
    }

    plugins {
        javalite {
            artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0"
        }
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.7.0"
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
                grpc {
                    // Options added to --grpc_out
                    option 'lite'
                }
            }
        }
    }
}`

**Comment by zhangkun83** [comment]
See https://github.com/google/protobuf-gradle-plugin/issues/185. Maybe it has something to do with the account setting (parental control, unknown binary lock-down etc). I don't think it's an issue of grpc.
