### ISSUE TITLE
grpc-okhttp 1.8.0 pom file has error, prevents build

### ISSUE THREAD

**Issue by bubenheimer** [grpc/grpc-java#3787]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

### What did you expect to see?
From grpc-okhttp-1.8.0.pom:

    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-core</artifactId>
      <version>1.8.0</version>
      <scope>compile</scope>
    </dependency>

Instead I saw a version number enclosed in brackets, which causes the build to fail:

    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-core</artifactId>
      <version>[1.8.0]</version>
      <scope>compile</scope>
    </dependency>

I checked the JCenter version at https://bintray.com/bintray/jcenter/download_file?file_path=io%2Fgrpc%2Fgrpc-okhttp%2F1.8.0%2Fgrpc-okhttp-1.8.0.pom

There may be 1.8.0 pom files from other grpc-java artifacts with the same problem.

**Comment by bubenheimer** [comment]
The formatting got messed up when posting the issue. Just look for the square brackets in the grpc-okhttp-1.8.0.pom file that I posted the link for.

**Comment by carl-mastrangelo** [comment]
I beleive the brackets means prefer the latest version: https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

**Comment by bubenheimer** [comment]
My Android Gradle builds are failing with 1.8.0 even after explicitly pulling in grpc-core:1.8.0 via a project dependency:

    Unable to resolve dependency for ':app@checkLocalDebug/compileClasspath': Could not find any version that matches io.grpc:grpc-core:[1.8.0].
    
    Could not find any version that matches io.grpc:grpc-core:[1.8.0].
    Versions that do not match:
        1.7.0
        1.6.1
        1.6.0
        1.5.0
        1.4.0
        + 24 more
    Required by:
        project :app > io.grpc:grpc-okhttp:1.8.0

The builds succeed with 1.7.0. I see that 1.7.0 uses the same `[1.7.0]` notation in grpc-okhttp-1.7.0.pom, so that may not be the problem, I also diffed the entire POM and did not see anything suspicious. Was there another potentially relevant change to the way that 1.8.0 is built?

**Comment by bubenheimer** [comment]
Must have been a problem with my local JCenter proxy. I deleted and pulled down the seemingly valid artifacts again, and it's working now. Thanks for the feedback, @carl-mastrangelo

**Comment by bubenheimer** [comment]
This issue has occured with every grpc-java release since 1.8.0 or earlier. I believe it's caused by having the new release artifacts available on JCenter, but without an updated `maven-metadata.xml`. Right now I am able to pull down all 1.12.0 artifacts from JCenter via my proxy by specifying 1.12.0 in my build.gradle, but the build fails because the `maven-metadata.xml` on JCenter is not updated with the 1.12.0 info. I am going to reopen this issue, because this seems quite wrong.

**Comment by carl-mastrangelo** [comment]
CC: @zpencer who has been looking at uploading of artifacts recently.

**Comment by zpencer** [comment]
Our release process publishes to Sonatype OSSRH to release to the Maven Central repository. I'm not too familiar with JCenter, but AFAIK it mirrors Maven Central and we don't have control over when they update their copy. If an up to date `maven-metadata.xml` is all you need, can you see if maven central works? Theirs has the expected 1.12.0:
http://search.maven.org/remotecontent?filepath=io/grpc/grpc-okhttp/maven-metadata.xml

**Comment by bubenheimer** [comment]
The thing is, grpc-java is the only project that I have these issues with, and I've had them with every release since at least 1.8.0. There still is no updated `maven-metadata.xml` on JCenter at this time. It's the standard repo for Android, so I wouldn't be the only one with this problem. It's taking extra long with 1.12.0 it seems. No idea how other projects upload artifacts.

**Comment by carl-mastrangelo** [comment]
@bubenheimer I looked at https://bintray.com/bintray/jcenter/io.grpc%3Agrpc-core/1.8.0#files/io/grpc/grpc-core   and it appears to be up now.  Is it working for you?

**Comment by bubenheimer** [comment]
Yes, it is updated now, thanks. It was refreshed last night, along with other Google-driven projects  from the last weeks (Guava, Dagger). Could Google's Android team be of help in getting JCenter support fixed?

**Comment by ejona86** [comment]
1.13 went to JCenter quickly. We'll continue checking it as part of our release process (#4490), but it doesn't seem there's anything else to do unless it is delayed again.

**Comment by creamsoup** [comment]
1.17.0 and 1.17.1 was not available on JCenter for weeks. Pinged JCenter(Bintray) to fix the sync issue.

They mentioned that "The new versions will be cached in JCenter only if you request them or if you upload them to your Bintray account."

They suggest to follow [sync to central](https://www.jfrog.com/confluence/display/BT/Syncing+with+Third-Party+Platforms). This approach requires sonatype credentials, and we need to publish to JCenter (and sync to central).
