### ISSUE TITLE
Cronet transport Received DATA frame for an unknown stream

### ISSUE THREAD

**Issue by bobbymicroby** [grpc/grpc-java#3797]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.9.0-SNAPSHOT

### What did you expect to see?
Bidi streaming in android works with okhttp transport, but fails with cronet

Every 10 seconds or so after the bidi stream is created and messages are streamed successfully I receive the following exception

```

Sent GOAWAY: lastStreamId '3', errorCode '11', debugData ''. Forcing shutdown of the connection.
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: Nov 25, 2017 9:42:03 AM io.grpc.netty.NettyServerHandler onStreamError
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: WARNING: Stream Error
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 3
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:524)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:185)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:421)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:116)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:353)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:413)
Nov 25 09:42:03 badge-grpc-1 grpc_server[8127]: at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
```

@ericgribkoff Probably you will need a repo with a reproducible code, but I am not sure when I will be able to create it. Anyway, i will create this issue maybe it will help.

**Comment by ejona86** [comment]
@ericgribkoff, is there anything we can do with this?

**Comment by ejona86** [comment]
@ericgribkoff, have we confirmed this is a bug?

**Comment by ericgribkoff** [comment]
I am not able to reproduce this.

@bobbymicroby What Cronet version are you using when this occurs? Are you able to provide some additional details about your client/service (e.g., is it a long-lived stream that should go on indefinitely and instead fails after 10 seconds, or is this error message coming after the bidi stream has concluded?)

**Comment by bobbymicroby** [comment]
@ericgribkoff Hello Eric,

I've built from master, so it was no specific version

It was a long live bidi stream, and it started failing after 30 seconds or so.  In my case the android app sends pings at regular intervals over the stream, but the server responds very rarely. 

I will try with a more recent cronet version and will update you with results.

I am at a family vacation right now, so I guess it will be at least few days from now.

Regards, B.

**Comment by ericgribkoff** [comment]
This bug was not confirmed or reproducible on our side. @bobbymicroby if you are still able to repro this please comment here and we can re-open.
