### ISSUE TITLE
AbstractClientStream - Received data on closed stream

### ISSUE THREAD

**Issue by dhoard-papajohns** [grpc/grpc-java#3810]
Please answer these questions before submitting your issue.

## gRPC version

grpc core 1.7.0

## Synopsis

Using Google Pub/Sub GrpcSubscriberStub for batch pulling of messages per

`https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1661`

I occasionally see the INFO logging message ...

`AbstractClientStream - Received data on closed stream`

My code is not experiencing any exceptions and everything appears to work as expected.

Looking at the code, there is also another INFO logging message ...

`log.log(Level.INFO, "Received trailers on closed stream:\n {1}\n {2}",`

... which appears to be benign as well.

## Resolution

The code / class `AbstractClientStream` should be configurable as to whether this INFO logger messages above are emitted.

**Comment by zpencer** [comment]
The message claims the socket was already closed by the time data and trailers are received. I wonder if this actually happened. ManagedChannel automatically does reconnects, so you may not notice this sort of hiccup as an application.

Is the problem easy to reproduce? Perhaps you can turn on verbose logging and share the logs with us. gRPC uses java.util.logging, so you can create a `log.properties` file. 
```
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
io.grpc.internal.ManagedChannelImpl.level=FINE
io.grpc.netty.NettyClientHandler=FINE
```

Add this flag to your program startup: `-Djava.util.logging.config.file=$ABSOLUTE_PATH_TO_LOG_PROPERTIES`

By the way, you can use the same config file to set `io.grpc.internal.level=WARNING` if the messages are causing a lot of pain right now.

**Comment by dhoard-papajohns** [comment]
I have refactored the code, so don't see this issue.  With the original code, it was only reproduced with high volume traffic, running in GCP App Engine.

Since it's not reproducible, we should probably close it.

**Comment by zpencer** [comment]
Sounds good. Please reopen if you start seeing this again.
