### ISSUE TITLE
Why grpc-java instead of grpc+JNI

### ISSUE THREAD

**Issue by breerly** [grpc/grpc-java#3815]
Is there some background into why grpc-java ended up being created instead of attempting grpc C + JNI bindings? Was performance an issue? Maybe it didn't play well with the concurrency paradigm?

Thanks - this will be insightful.

**Comment by carl-mastrangelo** [comment]
JNI calls are expensive, so they only make sense to do if you will be doing lot's of work inside of them.  The JIT compiler for Java cannot optimize such call sites.   

Also, several platforms (like Appengine at one point) disallow JNI code, which would have prevented gRPC java from running.

**Comment by breerly** [comment]
This thread seems to indicate that gRPC C +JNI is more performant... am I reading that right?

https://groups.google.com/forum/#!topic/grpc-io/a_VntDs0s2w

**Comment by breerly** [comment]
I see, portability is a concern as well.

**Comment by carl-mastrangelo** [comment]
That thread is talking about speed differences between the two implementations.  JNI was not introduced there, so I believe you are reading it incorrectly.   JNI is generally slower than plain java.

Also note, Java had significant performance improvements in late 2016, so any results from that thread are out of date.

**Comment by ejona86** [comment]
Portability was an important driving factor. Shipping binaries (boringssl) with Java has been a huge pain, and we'll be really happy as more people jump on Java 9, such that the binary component is no longer required. Binary components in most other languages, while maybe annoying, is not uncommon.

As far as performance, C# performance is maybe a good comparison to what Java performance might look like if using the C implementation:
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584

I know that C# isn't the same as Java and so would behave differently, but they do share some similar constraints.
