### ISSUE TITLE
Upgrade version for com.google.api.grpc:proto-google-common-protos

### ISSUE THREAD

**Issue by bogdandrutu** [grpc/grpc-java#3821]
Currently the following targets:
* io.grpc:grpc-protobuf
* io.grpc:grpc-example

depend on "0.1.9" version but everywhere else ("com.google.cloud:google-cloud-core" or com.google.api.grpc:proto-google-cloud-XXX") depend on "1.0.1".

The "1.x" version I think should be used in gRPC as well.

**Comment by ejona86** [comment]
In #3765 the version was bumped. Is that what you were wanting? It'd be helpful if you mentioned specific grpc versions and files, because things like io.grpc:grpc-example don't actually exist.

**Comment by bogdandrutu** [comment]
@ejona86 this was in "io.grpc:grpc-protobuf:1.8.0"

**Comment by ejona86** [comment]
Okay. It seems this was already resolved then.
