### ISSUE TITLE
How are gRPC calls mapped to HTTP/2 streams

### ISSUE THREAD

**Issue by ssheng** [grpc/grpc-java#3849]
Where can I find documentation on how gRPC calls are mapped to HTTP/2 streams? More specifically, what are the HTTP/2 setup in the client-streaming, server-streaming, and bidirectional-streaming cases. I tried to run the io.grpc.examples.routeguide example with WireShark attached. However, I wasn't able to find and HTTP/2 frames being exchange.

Thank you very much for you time.

### What version of gRPC are you using?
N/A

### What did you expect to see?
N/A

**Comment by carl-mastrangelo** [comment]
An RPC\* corresponds to one HTTP/2 stream.  All streaming RPCs use the same HTTP/2 stream.  Are you sure you don't have TLS encryption turned on?  That will mask the RPCs in wireshark.

\* This will change slightly when retries are enabled.

**Comment by ssheng** [comment]
Thanks very much for you response. Do you know what key store I should set up to decrypt the frames?

If bidirectional streaming happens on the same HTTP/2 stream using data frames, can frames be potentially buffered/aggregated/cached in the server or intermediaries, causing potential delays and affecting guarantee of delivery?

The last question is around framing of RPCs in the streaming cases. Could you please point me to either code or docs?

Thanks again.

**Comment by carl-mastrangelo** [comment]
@ssheng Generally you can't decode the frames.  The HTTP/2 spec says that only TLS Ciphers with ephemeral keys can be used, which prevents dumping the key somewhere for later reuse.  This is annoying.  The work around would be to disable TLS altogether while you are debugging.

Frames can be buffered, but it isn't so bad a problem.   If you follow the flow control signals (`isReady` and `setOnReadyHandler`, you won't buffer excessively.  These are converted into HTTP/2 Window update messages.

The protocol is specified at: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

**Comment by ssheng** [comment]
@carl-mastrangelo Thanks for your responses. I will continue my research of gRPC. Closing issue.
