### ISSUE TITLE
No ciphers available.

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#385]
With using Http2SecurityUtil.CIPHERS, we are encountering this cipher suites issue, the previous workaround is running with JDK8.

But now this issue is biting Android integration test.

**Comment by ejona86** [comment]
Are you referring to this impacting our internal integration test, or some other test?

**Comment by madongfly** [comment]
Yeah, I meant for our integration test, I ended up using gms security provider.

**Comment by ejona86** [comment]
Did using GMS Security Provider fix the issue?

**Comment by madongfly** [comment]
Yes. I didn't close this issue because it's still a problem with jdk7.

**Comment by ejona86** [comment]
We're not going to solve this for JDK7, except for maybe using OpenSSL, and that won't work for everyone.

[Oracle isn't releasing any more updates to JDK7.](http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html) Calling JDK7 dead and working with JDK8 which has the necessary ciphers seems prudent.

**Comment by madongfly** [comment]
OK, closed it then.
