### ISSUE TITLE
Freshly checked out code does not build in Intellij IDEA

### ISSUE THREAD

**Issue by rmichela** [grpc/grpc-java#3864]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.9.0-SNAPSHOT

Also reproduced with 1.7.0 and 1.8.0 tagged versions, and the past three major releases of Intellij Idea.

### Steps to reproduce
1. Check out the latest grpc-java code to a fresh directory
2. Run `./gradlew idea` to create the Intellij Idea project files
3. Open grpc-java with Idea
4. Attempt to build the project using the `Build -> Build Project` menu

### Expected
Grpc-java builds in Idea

### Actual
1. The `protobuf/test` module does not compile, complaining about missing methods and type mismatches.
2. `io.grpc.netty.shaded.ShadingTest` does not compile, because it cannot locate the shaded netty jar on the Idea classpath.

### Notes
* I was able to fix the `protobuf/test` module compilation by changing `sourcesRoot` to `testSourcesRoot` in protobuf-lite/build.gradle line 63.
* I was able to manually fix `io.grpc.netty.shaded.ShadingTest` by explicitly adding the generated `grpc-netty-shaded-1.9.0-SNAPSHOT.jar` file to the `grpc-netty-shaded_testShadow` module using Intellij's Project Structure screen. This is sub-optimal. I was unable to find a solution using gradle.

**Comment by rmichela** [comment]
Looks like the second part of this defect is a know bug in Idea: https://youtrack.jetbrains.com/issue/IDEA-163411

**Comment by ejona86** [comment]
Thanks for the PR. It looks like there's no fix for the second problem except for waiting for a fix on the shadow or IDEA side :frowning_face:

**Comment by rmichela** [comment]
**Workaround for IDEA users.**

1. `./gradlew :grpc-netty-shaded:build`
2. In IDEA, expand the project tree to find `netty/shaded/src/testShadow`
3. Right-click `testShadow` module and select "Open Module Settings"
4. Find the `grpc-netty-shaded_testShadow` sub-project and select the "Dependencies" tab
5. Click the ➕ at the bottom and select "Jar or directories..."
6. Select the file `netty/shaded/build/libs/grpc-netty-shaded-[version].jar`
7. From the "Build" menu, select "Build Project"

**Comment by zpencer** [comment]
@rmichela out of curiosity, have you tried loading the project into intellij as a gradle project, and then delegating build/run operations to gradle?
I noticed that doing so addresses a lot of weirdness, for example: https://github.com/google/protobuf-gradle-plugin/issues/111

**Comment by rmichela** [comment]
@zpencer I tested your suggestion and it fixes IntelliJ's quirkiness. I added documentation on how to set up IntelliJ in #3958.

**Comment by rmichela** [comment]
The above changes and documentation fixes give enough guidance to get IntelliJ working. Closing.
