### ISSUE TITLE
google/api/annotations.proto no longer available

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#3873]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.3.1

### What did you expect to see?
import "google/api/annotations.proto"; to work

It appears that with grpc 1.3.0 dependencies, we could transitively pick up com.google.api.grpc:proto-google-common-protos at 0.1.6 which published all the protos over here https://github.com/googleapis/googleapis/tree/master/google/api however, newer versions no longer publish the protos, just the generated classes in the jar.  I found https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.api.grpc%22%20AND%20a%3A%22googleapis-common-protos%22 which appears quite old and is missing a number of types.  Unfortunately, the googleapis repo doesn't seem to allow the opening of issues and I'd found a related problem here https://github.com/grpc/grpc-java/issues/3410 where the same import was failing.

Is there an alternate location these protos should be sourced from for imports, or is there a place I can get in touch with the folks who own com.google.api.grpc:proto-google-common-protos to get them to publish proto files into the jar again?

**Comment by carl-mastrangelo** [comment]
cc @garrettjonesgoogle

**Comment by jhspaybar** [comment]
Any insight on this one?  I can obviously copy/paste the files into a gradle project and jar it up for use myself, but wanted to see if there was an officially supported path here before I do so.

**Comment by ejona86** [comment]
This is being handled on the twin issue at googleapis. Once they do a new release we'll want to bump our version.

**Comment by MetaiR** [comment]
any update on this?
I have the same issue

**Comment by ejona86** [comment]
proto-google-common-protos 1.12.0 looks to have the protos included. So upgrading to that should resolve any problems.

**Comment by ejona86** [comment]
We upgraded to 1.12.0 in https://github.com/grpc/grpc-java/pull/5151
