### ISSUE TITLE
How to bypass hostname verification?

### ISSUE THREAD

**Issue by shotahino** [grpc/grpc-java#3880]
There is an example of how to do this for grpc-go in [here](https://github.com/golang/go/issues/21971)
And I'm looking for a similar solution for `grpc-java`.

I had been using overrideAuthority like this when the CN of the server certificate is known.
But I've come to a point where I can no longer keep doing this since the CN is _not_ known beforehand. All I know is the IP address and port number in my use case.

```
  grpc = OkHttpChannelBuilder
            .forTarget("$address:$port")
            .sslSocketFactory(sslcontext.socketFactory)
            .overrideAuthority("xxxxxx")
            .build()
```

**Comment by carl-mastrangelo** [comment]
Did you see the `hostnameVerifier`   method on `OkHttpChannelBuilder` ?

**Comment by ejona86** [comment]
Note that we strongly discourage disabling hostname verification, as it defeats a critical part of the security model of TLS. But it seems this question is answered.

**Comment by dcow** [comment]
I can comment. We are limiting our TLS to ca roots under our control. We will have a custom hostnameverifier that accounts for this to the attack vector that part of the model addresses does not exist for us, or where it does we understand the implications. We will also know the list of CNs we expect a-priori I believe Shota is referring to a debug "use case".
