### ISSUE TITLE
grpc android mutual tls, how to send client certificate and key to server

### ISSUE THREAD

**Issue by 1253062595** [grpc/grpc-java#3887]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
'io.grpc:grpc-okhttp:1.8.0' 
'io.grpc:grpc-protobuf-lite:1.8.0' 
'io.grpc:grpc-stub:1.8.0' 

### What did you expect to see?
I have done the server-side authentication, now I want to do client-side authentication, but I can not find a api to send my client certificate and key to the server, could you please give me some help?

**Comment by ericgribkoff** [comment]
Our android interop test app demonstrates some of the APIs for handling certificates in [TesterOkHttpChannelBuilder](https://github.com/grpc/grpc-java/blob/015b2fffa31995ff7923b4076f9324d464b7d827/android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java). This is mainly used by the app for configuring test certificates. If this isn't what you're looking for, could you provide more detail about what you're trying to accomplish?

**Comment by zpencer** [comment]
I have not tested the steps below, but it looks like it might just work if you configure the SSLContext objects appropriately for mutual TLS and pass them into the client channel and server builders:

For android, the http client library is okhttp which supports mutual tls: https://github.com/square/okhttp/issues/1711

On client side, when you call `ManagedChannelProvider.builderForTarget` or `builderForTarget` on android, cast the builder into `OkHttpChannelBuilder`. On the okhttp builder, there is a method to pass in your own custom `SSLSocketFactory` to the underlying library (okhttp):
https://grpc.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html#sslSocketFactory-javax.net.ssl.SSLSocketFactory-

netty appears to support mutual TLS:
https://github.com/netty/netty/pull/3041

On server side, when you call `ServerProvider.builderForPort`, cast the builder into a `NettyServerBuilder. There is a method to pass in your own `SSLContext` that is configured for mutual TLS to the underlying library (netty):
https://grpc.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#sslContext-io.netty.handler.ssl.SslContext-

Please reopen if you still have problems.
