### ISSUE TITLE
Gradle plugin does not clean before regenerating, causing compile failures

### ISSUE THREAD

**Issue by shevek** [grpc/grpc-java#3893]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.8.0

### What did you expect to see?

The general contract for a gradle plugin is that execution causes the output to be valid with respect to the input. This is essential for gradle's performance and reliability. protoc-gen-grpc-java does not do this, because after a change to a .proto file, it leaves obsolete files lying around in the generated-sources directory. It should remove files which would no longer be generated (see the gradle Sync task), or at worst, delete all files in the target directory before regenerating.

At the very least, given that this task is somewhat difficult to configure and a doFirst block is not trivially obvious, add an example which uses a doFirst to delete generated files.

**Comment by carl-mastrangelo** [comment]
@shevek want to send a PR?

**Comment by shevek** [comment]
See https://github.com/google/protobuf-gradle-plugin/issues/33 and https://github.com/google/protobuf-gradle-plugin/issues/180

**Comment by shevek** [comment]
Workaround:
```
        generateProtoTasks {
                all()*.plugins {
                        grpc {}
                }
                all().each { task ->
                        // println "" + task + " -> " + task.getClass()
                        // println "Output dirs: " + task.allOutputDirs
                        task.doFirst {
                                task.allOutputDirs*.delete()
                        }
                }
        }
```

**Comment by ejona86** [comment]
This issue seems to be a problem with the protobuf-gradle-plugin, not grpc. There's already an issue open against it, so closing.
