### ISSUE TITLE
How to get the ManagedChannel state?

### ISSUE THREAD

**Issue by dingrui37** [grpc/grpc-java#3907]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.3.0

### What did you expect to see?
I want to get state of the ManagedChannel, but this class does not implement the “getState” and “notifyWhenStateChanged” method，how to get the channel state？

**Comment by carl-mastrangelo** [comment]
The ManagedChannel you get back from calling `ManagedChannelBuilder.build()`  will implement the methods.
