### ISSUE TITLE
Any easier way to add method metric for grpc appliction?

### ISSUE THREAD

**Issue by Mailerm** [grpc/grpc-java#3909]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

### What did you expect to see?
I want to add metric monitor to my application,
but i don't kown how and where to add my code is the best way.
is there any method I can hook method before execute and after execute done?
Any suggestion?

**Comment by carl-mastrangelo** [comment]
On the client side you can make a `ClientInterceptor` to record such events.

**Comment by Mailerm** [comment]
it seems on the server side `ServerInterceptor` can only interceptor before method is execute, and i still coudn't kown when my method execute is finish.

**Comment by Mailerm** [comment]
i have try Spring-AOP, but once i add AOP, got error
````java
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
17:13:38.245 ERROR [main] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'tradeServiceImpl' could not be injected as a 'com.chinaroad.platform.service.TradeServiceImpl' because it is a JDK dynamic proxy that implements:


Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.
````

i have enable `spring-boot-starter-aop` and add `spring.aop.proxy-target-class=true`

**Comment by Mailerm** [comment]
Found a solution. Similar to @EnableAsync, setting proxyTargetClass = true fixes the issue:
@EnableMetrics(proxyTargetClass = true)

I Use
https://github.com/dropwizard/metrics
https://github.com/ryantenney/metrics-spring
