### ISSUE TITLE
Unable to execute quick start instructions with jave 1.8.0_121 

### ISSUE THREAD

**Issue by jeffgaer** [grpc/grpc-java#3910]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
following the instructions I attempted to checkout 1.8.0 but got the HEAD instead. I thing that is 1.10.0-SNAPSHOT.

git clone -b v1.8.0 https://github.com/grpc/grpc-java
Initialized empty Git repository in /data/git-grpc/grpc-java/.git/
remote: Counting objects: 58080, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 58080 (delta 5), reused 17 (delta 4), pack-reused 58051
Receiving objects: 100% (58080/58080), 19.97 MiB | 1.15 MiB/s, done.
Resolving deltas: 100% (24395/24395), done.
warning: Remote branch v1.8.0 not found in upstream origin, using HEAD instead

### What did you expect to see?
running gradlew I expected a successful build
it failed as follows

 ./gradlew installDist
Downloading https://services.gradle.org/distributions/gradle-4.3-bin.zip
.....................................................................
Unzipping /home/jgaer/.gradle/wrapper/dists/gradle-4.3-bin/452wx51oxqsia28686mgqhot6/gradle-4.3-bin.zip to /home/jgaer/.gradle/wrapper/dists/gradle-4.3-bin/452wx51oxqsia28686mgqhot6
Set executable permissions for: /home/jgaer/.gradle/wrapper/dists/gradle-4.3-bin/452wx51oxqsia28686mgqhot6/gradle-4.3/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://repo1.maven.org/maven2/com/google/api/grpc/proto-google-common-protos/1.0.0/proto-google-common-protos-1.0.0.pom
Download https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.3.0/protobuf-java-3.3.0.pom
Download https://repo1.maven.org/maven2/com/google/protobuf/protobuf-parent/3.3.0/protobuf-parent-3.3.0.pom

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compressingHelloWorldClient'.
> Could not resolve all files for configuration ':runtime'.
   > Could not find io.grpc:grpc-netty:1.10.0-SNAPSHOT.
     Searched in the following locations:
         https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.10.0-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.10.0-SNAPSHOT/grpc-netty-1.10.0-SNAPSHOT.pom
         https://repo1.maven.org/maven2/io/grpc/grpc-netty/1.10.0-SNAPSHOT/grpc-netty-1.10.0-SNAPSHOT.jar
         file:/home/jgaer/.m2/repository/io/grpc/grpc-netty/1.10.0-SNAPSHOT/maven-metadata.xml
         file:/home/jgaer/.m2/repository/io/grpc/grpc-netty/1.10.0-SNAPSHOT/grpc-netty-1.10.0-SNAPSHOT.pom
         file:/home/jgaer/.m2/repository/io/grpc/grpc-netty/1.10.0-SNAPSHOT/grpc-netty-1.10.0-SNAPSHOT.jar
     Required by:
         project :
   > Could not find io.grpc:grpc-protobuf:1.10.0-SNAPSHOT.
     Searched in the following locations:
         https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.10.0-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.10.0-SNAPSHOT/grpc-protobuf-1.10.0-SNAPSHOT.pom
         https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.10.0-SNAPSHOT/grpc-protobuf-1.10.0-SNAPSHOT.jar
         file:/home/jgaer/.m2/repository/io/grpc/grpc-protobuf/1.10.0-SNAPSHOT/maven-metadata.xml
         file:/home/jgaer/.m2/repository/io/grpc/grpc-protobuf/1.10.0-SNAPSHOT/grpc-protobuf-1.10.0-SNAPSHOT.pom
         file:/home/jgaer/.m2/repository/io/grpc/grpc-protobuf/1.10.0-SNAPSHOT/grpc-protobuf-1.10.0-SNAPSHOT.jar
     Required by:
         project :
   > Could not find io.grpc:grpc-stub:1.10.0-SNAPSHOT.
     Searched in the following locations:
         https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.10.0-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.10.0-SNAPSHOT/grpc-stub-1.10.0-SNAPSHOT.pom
         https://repo1.maven.org/maven2/io/grpc/grpc-stub/1.10.0-SNAPSHOT/grpc-stub-1.10.0-SNAPSHOT.jar
         file:/home/jgaer/.m2/repository/io/grpc/grpc-stub/1.10.0-SNAPSHOT/maven-metadata.xml
         file:/home/jgaer/.m2/repository/io/grpc/grpc-stub/1.10.0-SNAPSHOT/grpc-stub-1.10.0-SNAPSHOT.pom
         file:/home/jgaer/.m2/repository/io/grpc/grpc-stub/1.10.0-SNAPSHOT/grpc-stub-1.10.0-SNAPSHOT.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
1 actionable task: 1 executed

### What version of java 
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
###what OS
Redhat  2.6.32-642.15.1.el6.x86_64

**Comment by ericgribkoff** [comment]
The v1.8.0 tag exists (see the list at https://github.com/grpc/grpc-java/tags) and `git clone -b v1.8.0 https://github.com/grpc/grpc-java` provided works correctly for me. I'm unsure why this wouldn't work for you; after cloning the repository, you can view the available tags with `git tag` and try `git checkout <tag>` again.

**Comment by jeffgaer** [comment]
Got it , thanks
 Jeff

"The inherent vice of capitalism is the unequal sharing of blessings; the inherent virtue of socialism is the equal sharing of miseries." Winston Churchill
