### ISSUE TITLE
Server is receiving requests in the wrong order when multiple requests are sent in a very short time.

### ISSUE THREAD

**Issue by lorensewusu** [grpc/grpc-java#3920]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What did you expect to see?

I have this service
```
service PricingService {
  rpc SubscribeToken(ESPRatesRequest) returns (stream ESPRatesResponse) {}
  rpc UnsubscribeToken(ESPRatesRequest) returns (stream ESPRatesResponse) {}
  rpc SubscribeStream(ESPRatesResponse) returns (stream ESPQuote) {}
  rpc UnsubscribeStream(ESPRatesResponse) returns (stream ESPQuote) {}
}
```

When i make SubscribeToken and UnsubscribeToken calls from the client very quickly, the server does not receive these requests in the same order i sent them.

  
I am sending some data very quickly in my grpc client, using exactly the same thread.

First message
```
2018 Jan 05 16:46:35.820 +0000  -  [unicredit.DedicatedSerialExecutor.ExceedService-<thread:1>] INFO  exceed.api.client.grpc.pricing.PricingClient - processing subscribe
```

Second message
```
2018 Jan 05 16:46:35.821 +0000  -  [unicredit.DedicatedSerialExecutor.ExceedService-<thread:1>] INFO  exceed.api.client.grpc.pricing.PricingClient - processing unsubscribe base_details {
```

However, in my server, i get the messages in the wrong order
The Unsubscribe method call first
```
2018 Jan 05 16:46:35.830 +0000  -  [pool-2-thread-4] INFO  pricing - Unsubscribe token called for <base_details {
```

Then the subscribe method
```
2018 Jan 05 16:46:35.831 +0000  -  [pool-2-thread-6] INFO  pricing - Token request has been made for <base_details {
```

**Comment by carl-mastrangelo** [comment]
For streaming RPCs, messages are gauranteed to be in the order they are sent, but not with respect to the messages of any other RPCs.   gRPC can send the RPCs (and their messages) in any order.  

If you want to make a serial order to each message, you'll have to use a single RPC method, and make the message clarify what you want it to do.  For example:

```
service PricingService {
  rpc ManageSubscription(SubscriptionRequest) returns (stream SubscriptionResponse) {}
}

message SubscriptionRequest {
  oneof request {
    ESPRatesRequest subscribe_token = 1;
    ESPRatesRequest unsubscribe_token = 2;
    ESPRatesResponse subscribe_stream = 3;
    ESPRatesResponse unsubscribe_stream = 4;
  }
}
```

With a similar mux for the `SubscriptionResponse`.

**Comment by lorensewusu** [comment]
Thank you for the explanation/clarification. I will make the changes and see what happens

**Comment by lorensewusu** [comment]
I tried out your proposal, i now have a service like this
`service PricingService {
  rpc TokenRequest(ESPRatesRequest) returns (stream ESPRatesResponse) {}
}`

The ESPRatesRequest message has an action field which is either subscribe or unsubscribe.

Now, with this change, it works most of the time, however, i am seeing a race condition where in some few case, i receive the UNSUBSCRIBE action message first before the SUBSCRIBE.  
This is my log that shows the requests being sent from my client

Sending subscribe
```
2018 Jan 08 14:05:38.019 +0000  -  [unicredit.DedicatedSerialExecutor.ExceedService-<thread:1>] INFO  exceed.api.client.grpc.pricing.PricingClient - processing subscribe base_details {
  base_currency: "USD"
  term_currency: "RUB"
  dealt_currency: "USD"
  tenor: "SPOT"
  trader_user_name: "ChartingUser"
  account: "ChartingAccount"
}
request_id: "USDRUBUSDSPOT1ChartingAccountChartingUser434465139777199"
app_id: "UnicreditUBISIntegration:UUSP0212:FabricPricingAdapter:2018:01:08:14:05:36:743"
platform_id: "UCT"
```

Sending unsubscribe
```
2018 Jan 08 14:05:38.019 +0000  -  [unicredit.DedicatedSerialExecutor.ExceedService-<thread:1>] INFO  com.unicredit.fabric.pricing.real.ExceedPricingEngine - Unsubscribe called for <base_details {
  base_currency: "USD"
  term_currency: "RUB"
  dealt_currency: "USD"
  tenor: "SPOT"
  trader_user_name: "ChartingUser"
  account: "ChartingAccount"
}
request_id: "USDRUBUSDSPOT1ChartingAccountChartingUser434465139777199"
action: UNSUBSCRIBE
app_id: "UnicreditUBISIntegration:UUSP0212:FabricPricingAdapter:2018:01:08:14:05:36:743"
platform_id: "UCT"
>
```

This was sent basically in the same millisecond but i am using the same thread (_unicredit.DedicatedSerialExecutor.ExceedService-<thread:1>_) in sending so the first one definitely get's called first before the UNSUB

But look at what i see in my GRPC server
```
2018 Jan 08 14:05:38.035 +0000  -  [pool-2-thread-2] INFO  pricing - Token request has been made for <base_details {
  base_currency: "USD"
  term_currency: "RUB"
  dealt_currency: "USD"
  tenor: "SPOT"
  trader_user_name: "ChartingUser"
  account: "ChartingAccount"
}
request_id: "USDRUBUSDSPOT1ChartingAccountChartingUser434465139777199"
action: UNSUBSCRIBE
app_id: "UnicreditUBISIntegration:UUSP0212:FabricPricingAdapter:2018:01:08:14:05:36:743"
platform_id: "UCT"
> with action <UNSUBSCRIBE>


2018 Jan 08 14:05:38.039 +0000  -  [pool-3-thread-1] INFO  pricing - Processing UNSUBSCRIBE for request <base_details {
  base_currency: "USD"
  term_currency: "RUB"
  dealt_currency: "USD"
  tenor: "SPOT"
  trader_user_name: "ChartingUser"
  account: "ChartingAccount"
}
request_id: "USDRUBUSDSPOT1ChartingAccountChartingUser434465139777199"
action: UNSUBSCRIBE
app_id: "UnicreditUBISIntegration:UUSP0212:FabricPricingAdapter:2018:01:08:14:05:36:743"
platform_id: "UCT"
>
```


And then the subsscribe
```
2018 Jan 08 14:05:38.035 +0000  -  [pool-2-thread-5] INFO  pricing - Token request has been made for <base_details {
  base_currency: "USD"
  term_currency: "RUB"
  dealt_currency: "USD"
  tenor: "SPOT"
  trader_user_name: "ChartingUser"
  account: "ChartingAccount"
}
request_id: "USDRUBUSDSPOT1ChartingAccountChartingUser434465139777199"
app_id: "UnicreditUBISIntegration:UUSP0212:FabricPricingAdapter:2018:01:08:14:05:36:743"
platform_id: "UCT"
> with action <SUBSCRIBE>

2018 Jan 08 14:05:38.039 +0000  -  [pool-3-thread-1] INFO  pricing - Processing SUBSCRIBE for request <base_details {
  base_currency: "USD"
  term_currency: "RUB"
  dealt_currency: "USD"
  tenor: "SPOT"
  trader_user_name: "ChartingUser"
  account: "ChartingAccount"
}
request_id: "USDRUBUSDSPOT1ChartingAccountChartingUser434465139777199"
app_id: "UnicreditUBISIntegration:UUSP0212:FabricPricingAdapter:2018:01:08:14:05:36:743"
platform_id: "UCT"
>
```


I use a single thread (as you can see from the logs **[pool-3-thread-1]**) to process the messages when they come into the server and you can see from the logs above that we receive the UNSUB before the SUB.

One thing i noticed is that the grpc server gets called with different threads **pool-2-thread-2** and **pool-2-thread-5** could this be causing the issue? I think there might be a race condition somewhere in the grpc code.

**Comment by ericgribkoff** [comment]
You're still sending two separate RPCs, one with a SUB request and one with the UNSUB request. If you want to guarantee two messages are sent (and received) in the same order, they have to be part of the same stream. You would need to do this:

```
service PricingService { 
    rpc TokenRequest(stream ESPRatesRequest) returns (stream ESPRatesResponse) {} 
}
```

And send the sequential sub and unsub requests on the same streaming call. You can see an example of streaming RPCs in our route guide example, described at https://grpc.io/docs/tutorials/basic/java.html

**Comment by lorensewusu** [comment]
Ok, thanks I will try this out and confirm.

**Comment by lorensewusu** [comment]
Thanks for your comments, the issue is resolved.
