### ISSUE TITLE
Create tool to detect accidental consumption of @ExperimentalApi and @Internal APIs

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#3929]
Similar to https://github.com/google/guava-beta-checker

**Comment by ericgribkoff** [comment]
@jyane That's great. Feel free to ping me when it's ready for review and I can help with getting it listed on https://github.com/grpc/grpc-contrib and documented here in the grpc-java repo.

**Comment by jyane** [comment]
Thank you @ericgribkoff.
Of course I can transfer the ownership to grpc-ecosystem, grpc or anywhere.

This is just a report of progress.
Creating tool is almost finished. 
It could detect annotations in tests, but in "real", it could not detect because compiled grpc-java jars were removed annotations.
I'm waiting for merging above PR and then releasing the grpc-java 1.10.0.

**Comment by jyane** [comment]
@ericgribkoff 
It's now ready to review (https://github.com/jyane/grpc-java-api-checker) that works with HEAD of grpc-java.
Should I fill that grpc-ecosystem's forms?

**Comment by ericgribkoff** [comment]
@jyane Looks great. If you're okay with moving this into a top-level grpc repo, we were thinking of creating a new repository along the lines of grpc/grpc-java-api-checker to contain this tool. You will remain an owner and have contributor/commit access to the new repo, and gRPC team can help coordinate releasing the tool onto Maven Central in the `io.grpc` group ID or some variant of this. Let me know if that plan sounds good to you and we will create the new repository. Thanks for working on this!

**Comment by jyane** [comment]
@ericgribkoff 
It sounds great!
Please give me the privileges to transfer the repository.
I will transfer it and change for the grpc organization (License, package name, ...etc).

**Comment by ericgribkoff** [comment]
Hi @jyane -

We just sent you an invite to the `grpc` github organization. It should show up in your email, or you should also be able to accept the invitation by going directly to https://github.com/grpc/. 

Once you're a member, we will create the new `grpc/grpc-java-api-checker` repository. 

As far as license, if you're okay with Apache 2.0 as gRPC uses currently, you can follow the format of our files (for example, https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/BindableService.java#L1) and assign the copyright to "gRPC Authors". In the main directory of the repo, there should then be an `AUTHORS` file containing `Google Inc.` and you as the authors.

**Comment by jyane** [comment]
@ericgribkoff Became a member of grpc! Thanks!

**Comment by ericgribkoff** [comment]
@jyane https://github.com/grpc/grpc-java-api-checker has been created. You should have write access to this repository. Please send a PR with the new code and assign me as a reviewer. Thanks!

**Comment by jyane** [comment]
@ericgribkoff 
Should I add the documentation about grpc-java-api-checker to README.md, due to https://github.com/grpc/grpc-java/issues/3929#issuecomment-359957675 ?

**Comment by ericgribkoff** [comment]
Hi @jyane - yes, that would be great. We don't have a section on API guarantees in README.md, so there might not be an obvious place to put it, but I think a new section (`Tools` or something like that) would be appropriate. It would be great to also have grpc-java-api-checker mentioned in the javadoc for `ExperimentalApi` and `Internal`.

Also, would you be up for sending an email to the grpc.io mailing list to announce grpc-java-api-checker's release? I can help with drafting the email text if you'd like.

Thanks!

**Comment by ejona86** [comment]
@ericgribkoff / @jyane, can this be closed now?

**Comment by ericgribkoff** [comment]
Yes, we can close this
