### ISSUE TITLE
Bump Android targetApiVersion to 26

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#3938]
As will be [required in Play store](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html).

**Comment by carl-mastrangelo** [comment]
Please don't do this yet.  API Level 26 causes internal tests to be flaky.

**Comment by ejona86** [comment]
@carl-mastrangelo, I think you're conflating things: you're talking about which API level is being used for the VM, this is the targetApiVersion to compile against. Older API versions would still be supported. It basically just means the app would have to comply with any newer Android restrictions (which is probably does already).

**Comment by ericgribkoff** [comment]
Bumped to 27 in https://github.com/grpc/grpc-java/pull/3975
