### ISSUE TITLE
server push

### ISSUE THREAD

**Issue by yine** [grpc/grpc-java#3964]
Hello, grpc project team, I want to achieve when the client login system, the server records the client-related information, and then the server can push the message to the specified client at any time, push the message data structure is a variety of types, : Server should get the client connection, from the example you can see only the StreamObserver <T> responseObserver, but the T can only be a fixed type, is there any other way to achieve, please give a reference example, thank you!

**Comment by ericgribkoff** [comment]
I think you will need to make the type T a wrapper around whatever variety of types your server needs to send to the client. If you're using protos, the response message would include the various other types as subfields.

**Comment by ericgribkoff** [comment]
Also, this would be a good type of question to ask in our support forum https://groups.google.com/forum/#!forum/grpc-io

I am going to close this issue, feel free to start up a thread on the mailing list if this needs more discussion.
