### ISSUE TITLE
Most of the functions in AbstractStub should be annotated with @CheckReturnValue

### ISSUE THREAD

**Issue by Hzj-jie** [grpc/grpc-java#3985]
These functions create new instances rather than changing the internal state, e.g.
```stub.withCallCredentials( ... )```
is wrong. One should always use
```stub = stub.withCallCredentials( ... )```

https://github.com/grpc/grpc-java/blob/c90f27f454f59f15fcd1030be5af8c69b0aad42c/stub/src/main/java/io/grpc/stub/AbstractStub.java#L48

**Comment by carl-mastrangelo** [comment]
Static analyzers will fail if the value is not checked, which is likely extremely high at this point.  While the code is probably buggy, I don't think it can reasonably be fixed at this point.
