### ISSUE TITLE
java.lang.NoSuchFieldError: SSL_MAX_RECORD_LENGTH

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#3989]
When running grpc 1.9 with`io.netty:netty-tcnative-boringssl-static:2.0.6.Final` on linux, I got following stacktrace.
```
! java.lang.NoSuchFieldError: SSL_MAX_RECORD_LENGTH
! at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<clinit>(ReferenceCountedOpenSslEngine.java:129) ~[netty-all-4.1.17.Final.jar:4.1.17.Final]
! at io.netty.handler.ssl.OpenSslContext.newEngine0(OpenSslContext.java:49) ~[netty-all-4.1.17.Final.jar:4.1.17.Final]
! at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine(ReferenceCountedOpenSslContext.java:378) ~[netty-all-4.1.17.Final.jar:4.1.17.Final]
! at io.grpc.netty.ProtocolNegotiators$TlsNegotiator$1.handlerAdded(ProtocolNegotiators.java:306) ~[grpc-netty-1.9.0.jar:1.9.0]
! at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606) ~[netty-all-4.1.17.Final.jar:4.1.17.Final]
! ... 19 common frames omitted
```
The error is gone when running with netty-tcnative-boringssl-static:2.0.7.Final.
According to maven, grpc-netty depends on netty-tcnative-boringssl-static:2.0.7.Final. However, I didn't see it in release note. I think dependencies session in 1.9 release note needs update.

**Comment by ejona86** [comment]
You're right. It was updated in SECURITY.md but didn't make it to the release notes. I added it on the "netty upgrade to..." line. I'm sort of sad it feels lost in the noise, but I don't see an easy way to address that.

Thank you for reporting!
