### ISSUE TITLE
Steps to configure Mutual TLS in grpc-java?

### ISSUE THREAD

**Issue by nddipiazza** [grpc/grpc-java#4004]
I created a new HelloWorld with TLS enabled example here: https://github.com/grpc/grpc-java/pull/3992

So far I have only configured TLS. Not mutual TLS.

What would be the steps to enable Mutual Auth in this example?

The script added to https://github.com/grpc/grpc-java/pull/3992/files#diff-1c0f522a61adc59307209c8e0296db49R39 generates the cert files needed.

The grpc-java security.md says to do this:

```java
Server server = NettyServerBuilder.forPort(8443)
    .sslContext(GrpcSslContexts.forServer(certChainFile, privateKeyFile)
        .trustManager(clientCertChainFile)
        .clientAuth(ClientAuth.OPTIONAL)
        .build());
```

OK no problem. But what does the client-side look like?

**Comment by ejona86** [comment]
You just need to specify the `keyManager()` to `SslContextBuilder` on client-side.

Looking at that PR, I see this, which looks basically right.
```
        .sslContext(GrpcSslContexts.forClient()
            .trustManager(new File(trustCertCollectionFilePath))
            .keyManager(new File(certChainFilePath),
                new File(privateKeyFilePath))
            .build())
```

The `certChainFilePath` and `privateKeyFilePath` should both be for the _client_ certificate. The trust manager is only used for verifying the server's certificate.

**Comment by nddipiazza** [comment]
Oh OK. So the inputs to the user would only need to be

Client: `HelloWorldClientTls host port certChainFilePath privateKeyFilePath trustCertCollectionFilePath`
Server: `HelloWorldClientTls host port certChainFilePath privateKeyFilePath [trustCertCollectionFilePath]` (where trustCertCollectionFilePath is only specified when Mutual TLS is desired)

am i understanding that right @ejona86 ?

**Comment by nddipiazza** [comment]
never mind i get it now

**Comment by nddipiazza** [comment]
so the client only needs to specify 

```
.keyManager(new File(certChainFilePath),
                new File(privateKeyFilePath))
```

when mutual auth is desired. i get it now

**Comment by carl-mastrangelo** [comment]
@nddipiazza Several people have asked about TLS so far, and I think the example you made would be really helpful.   Would you consider adding your TLS hello world example?

**Comment by nddipiazza** [comment]
yes it's a PR that i would love to see merged

**Comment by nddipiazza** [comment]
@carl-mastrangelo @ejona86 this is ready for review. i have tested it with both TLS and TLS mutual auth. works.

**Comment by ejona86** [comment]
Seems this is resolved. Closing.
