### ISSUE TITLE
Have LoadBalancers trigger NameResolver.refresh()

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4006]
Today we implicitly refresh the NameResolver when a transport disconnects. But we don't actually know if that disconnect is important. For example, with GRPCLB only the OOB connection to the GRPCLB server really impacts the addresses we use; GRPCLB will be telling us when a service backend should be removed from our list. Thus, the refresh is useless for all disconnections except from the OOB channel.

C today has the LB decide when to refresh. That seems pretty easy to implement in the normal cases and helpful in the complex cases. So we should consider doing the same thing.

Unfortunately, it does cause some problem for migrating existing LB implementations. Maybe if we see the LB manually call refresh() we disable the implicit refreshing we do today. Maybe something else.

CC @zhangkun83

**Comment by zhangkun83** [comment]
Alternatively, we can make ManagedChannelImpl to attach the source NameResolver as an attribute to the EAGs from the NameResolver before passing them to LoadBalancer. Assuming LoadBalancers don't discard the EAG attributes before passing them to `createSubchannel()` and `createOobChannel()`. ManagedChannelImpl can then refresh the source NameResolver whenever an InternalSubchannel is disconnected, whether it's an Subchannel or an OobChannel. By doing this, LoadBalancers don't need to refresh name resolution at all.

To support the service-routing case where a parent balancer creates child NameResolver/LoadBalancer pairs, we'd need to pack the NameResolver/LoadBalancer pair into a class, say "RequestDirector", that would absorb `getNameResolver()` and `NameResolverListenerImpl` (which would include the NameResolver-attaching logic) from `ManagedChannelImpl`.

**Comment by zhangkun83** [comment]
Per offline discussion with @ejona86, @markdroth, @dfawley, we need to expose `refresh()` to LoadBalancers because we want to refresh name resolution when the stream to GRPCLB balancer fails, not only when connection to balancer disconnects.

We will still keep the implicit refresh done by the channel to cover the common case.
