### ISSUE TITLE
"google.api.http" is useless while gen stub, is it possible to use it to gen restful client code?

### ISSUE THREAD

**Issue by darren-fu** [grpc/grpc-java#4019]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

### What did you expect to see?
use protoc and protoc-gen-grpc-java to gen java code.
```proto
syntax = "proto3";
import "google/api/annotations.proto";

option java_multiple_files = false;
option java_package = "df.open.grpc.hello";
option java_outer_classname = "HelloServiceProto";
//package test;
service HelloService {
    rpc sayHello (HelloReq) returns (HelloResp) {
        option (google.api.http) = {
            post: "/v1/example/hello"
            body: "*"
        };
    }
}

message HelloReq {
    string key = 1;
}
message HelloResp {
    string key = 1;
}
```
"google.api.http" is useless while gen stub, **is it possible to use it to gen restful client code?**
just like [https://github.com/grpc-ecosystem/grpc-gateway.git](https://github.com/grpc-ecosystem/grpc-gateway.git).

**Comment by zhangkun83** [comment]
"google.api.http" is an option defined by the grpc-gateway code generator. protoc-gen-grpc-java doesn't use it.
