### ISSUE TITLE
How to get the connection status with the client from the server?

### ISSUE THREAD

**Issue by dingrui37** [grpc/grpc-java#4024]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

### What did you expect to see?
Is it feasible to get the connection status with the client from the server?

**Comment by carl-mastrangelo** [comment]
You can get the state of the `ManagedChannel`, but not of a single connection.  The reason is that the channel may be connected to many servers and we don't expose the status of individual connections.

**Comment by dingrui37** [comment]
The state of `ManagedChannel ` is in the client, I want to ask how to get state in server.

**Comment by carl-mastrangelo** [comment]
It cannot be queried from the Server.  It is not possible to associate a request with a particular connection.  If you want to be certain the client is still present, you can adjust the keep alive settings on the server.
