### ISSUE TITLE
Plumb proxy address through Name Resolver

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4029]
Netty can't handle unresolved addresses. To avoid things like #4027 and any concerns of `ProxySelector`s returning unresolved addresses, we should resolve the address while the NameResolver is running. We then should plumb that result through to the transport.

We should probably have a check on addresses coming from the Name Resolver that verifies the addresses are resolved.

**Comment by zpencer** [comment]
I recall I originally wanted to use the `EquivalentAddressGroup`'s `attributes` field, but it is stripped in a few places:
https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/PickFirstBalancerFactory.java#L132
https://github.com/grpc/grpc-java/blob/master/grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java#L665

Do we ever want to support the scenario where:
- DnsNameResolver resolves a name to several IPs
- each IP has a different proxy

If this makes sense, then EquivalentAddressGroup should not contain List<SocketAddress>, but instead some other class that can hold the SocketAddress as well as some attributes, and can survive flattening.

**Comment by ejona86** [comment]
Proxy being all-or-nothing for the name resolver is fine. We do need to be able to specify different attributes for different addresses, because [that's how GRPCLB addresses are communicated](https://github.com/grpc/grpc-java/blob/v1.10.x/grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java#L108). There is the separate Attributes parameter, but that seems weak.

CC @zhangkun83
