### ISSUE TITLE
Generalize NettyChannelBuilder.maxHeaderListSize to ManagedChannelBuilder

### ISSUE THREAD

**Issue by garrettjonesgoogle** [grpc/grpc-java#4050]
This is necessary for Spanner in google-cloud-java.

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java#L301

**Comment by ejona86** [comment]
API review:
 * change the argument in `maxHeaderListSize(int maxHeaderListSize)` to `bytes` for clarity. Otherwise seems good to add as-is. Default to no-op. Need to mention in the documentation that it is a bit fuzzy, and the implementation can add per-entry overhead accounting.

**Comment by levimatheri** [comment]
We'll have to implement it on okhttp, inprocess and alts channel builders since they all indirectly extend ManagedChannelBuilder. I'm currently working on this

**Comment by ejona86** [comment]
I have this implemented for inprocess, but needed to finish writing tests. I mentioned some problems with implementing it in okhttp in #4567. My current plan was to implement it, but in a way that doesn't protect memory usage (so fully parse the headers, and then complain if they are too large).

I was also tossing around the idea that it should actually be named `maxMetadataSize`.

**Comment by levimatheri** [comment]
Okay. I agree the argument name should change

**Comment by ejona86** [comment]
API review
* Swap name to `maxInboundMetadataSize(int bytes)`
* It is fine for OkHttp to fully load the headers into memory before failing the call when tool large.

**Comment by hzyi-google** [comment]
Hello! Do we have any update on this?

**Comment by ejona86** [comment]
@hzyi-google, no. It got pushed behind the other ALTS work.
