### ISSUE TITLE
HTTP1.x Support for grpc-java

### ISSUE THREAD

**Issue by hanjiezm** [grpc/grpc-java#4067]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

Since grpc server do not support http1 stream, I have to use a web server in my application, for health check and some debug method.

Will it be possible to support this feature? When

**Comment by carl-mastrangelo** [comment]
HTTP/1.1 upgrade might be possible, but using HTTP/1.1 directly would not.   The http protocol does not allow gRPC to multiplex RPCs or do flow control, both of which are needed for normal operation.

**Comment by ejona86** [comment]
@hanjiezm, you're not asking for HTTP/1 for grpc, right? You're asking to be able to do other HTTP/1 traffic on the same port as gRPC, right?

If so, this is likely a duplicate of #3458

**Comment by ejona86** [comment]
Closing as a duplicate of #3458
