### ISSUE TITLE
option to keep stream open after an exception

### ISSUE THREAD

**Issue by Tagar** [grpc/grpc-java#4086]
When an error condition happens, for example, 

> ERROR [2018-02-14 10:39:10,922] ({grpc-default-executor-3} IPythonClient.java[onError]:138) - Fail to call IPython grpc
> io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: io.grpc.netty.NettyClientTransport$3: Frame size 216695976 exceeds maximum: 4194304.
>         at io.grpc.Status.asRuntimeException(Status.java:543)
>         at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
>         at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
>         at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
>         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
>         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
>         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
>         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
>         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> 

it closes the stream.. is there is a way to keep the grpc stream open ?

>  INFO [2018-02-14 10:39:10,923] ({grpc-default-worker-ELG-1-2} AbstractClientStream2.java[inboundDataReceived]:249) - Received data on closed stream
>  INFO [2018-02-14 10:39:10,924] ({grpc-default-worker-ELG-1-2} AbstractClientStream2.java[inboundDataReceived]:249) - Received data on closed stream
>  INFO [2018-02-14 10:39:10,925] ({grpc-default-worker-ELG-1-2} AbstractClientStream2.java[inboundDataReceived]:249) - Received data on closed stream
> 

So application will be more resilient for errors like above.

**Comment by carl-mastrangelo** [comment]
You can configure the maximum frame size on the `ManagedChannelBuilder` and the `ServerBuilder`, but the stream cannot continue when there is an error.

**Comment by Tagar** [comment]
Thanks @carl-mastrangelo 

Can we make this error ignorable? So if a grpc error happens, we don't have to restart whole application. It's an interactive application (Apache Zeppelin), a better user experience would be if a user can see an error, correct his Zeppelin code interactively and try to run that paragraph again. Currently this behavior forces user to restart his "interpreter process". 

We would like to make this exception (and other grps exceptions) optionally ignorable. Is this possible? 

cc @zjffdu

**Comment by carl-mastrangelo** [comment]
The RPC (a.k.a. the stream) cannot continue, but you can start a new RPC.    The Channel will still work.   You can start a new RPC on the existing channel.    Without seeing the code I don't know why a failed RPC would fail the whole application, but that isn't the intended behavior.

**Comment by Tagar** [comment]
@zjffdu would it be possible to have a separate RPC stream invocation for each separate zeppelin paragraph call ? 

thanks @carl-mastrangelo

**Comment by ejona86** [comment]
Note that something else is broken if you're seeing that error. You should not be receiving a frame that large.

**Comment by ejona86** [comment]
@Tagar, oops. I mis-interpreted that message. I thought it was talking about HTTP/2 frames. But it was talking about gRPC frames, so that means the message was simply too large. Thus the steps in apache/zeppelin#2802 are appropriate.

gRPC can easily handle large messages, but un-bounded message sizes impact applications. The default 4 MB limit it to encourage applications to consider what to do for large messages. But bumping the limit works fine from gRPC's perspective.

**Comment by ejona86** [comment]
I've sent out #4106 to improve the message language.
