### ISSUE TITLE
Performance degradation while sharing channel across multiple threads

### ISSUE THREAD

**Issue by Pasick** [grpc/grpc-java#4092]
### What version of gRPC are you using?
1.9.0

### What did you expect to see?
According to previous answers to similar questions (i.e. https://github.com/grpc/grpc-java/issues/3268), the recommended way of handling gRPC channels is to have one channel and to share it across stubs. However, in multi-threaded application I see that this approach causes significant performance degradation. For example, if I share single ManagedChannel across 8 threads and run beenchmark test, I get a test duration of **326531 ms**. In the same time, if I create ManagedChannels inside every thread, the result is completely different: **27748 ms**. Modified files of the HelloWorld example are attached.

Am I doing something wrong? Would you please clarify how can I get the best performance while dealing with channels?

[HelloWorldClient.java.txt](https://github.com/grpc/grpc-java/files/1731043/HelloWorldClient.java.txt)
[HelloWorldServer.java.txt](https://github.com/grpc/grpc-java/files/1731044/HelloWorldServer.java.txt)

**Comment by carl-mastrangelo** [comment]
Try setting the executor on the `ManagedChannelBuilder` and `ServerBuilder` to use a `ForkJoinPool`.

Also, don't measure time with `currentTimeMillis`,   you want to use `nanoTime` which is meant for measuring durations.

**Comment by ejona86** [comment]
Your benchmark has no warm-ups. So the first case is almost guaranteed to be slower, independent of what it is. At the very least class-loading will be happening then. But also the JIT could kick in and make the second case faster as well. Please read up on how to do benchmarks in Java.

Unmodified:
```
Single channel shared across multiple threads
Average duration per thread (ms): 15017
Channel per thread
Average duration per thread (ms): 9494
```

Flipping the cases:
```
Channel per thread
Average duration per thread (ms): 14496
Single channel shared across multiple threads
Average duration per thread (ms): 10342
```
