### ISSUE TITLE
Replace workspace("grpc_java") with workspace(com_github_grpc_grpc_java)

### ISSUE THREAD

**Issue by cgrushko** [grpc/grpc-java#4095]
... or something else more authoritative.

The workspace statement in the `WORKSPACE` file should match the name users are giving the external repositories that import this repo, e.g. 

```
http_archive(
    name = "grpc_java",
    sha256 = "b4c9839b672213686ee9633a6089a913e50b1040d9f7486bd09d17032a2a90d3",
    strip_prefix = "grpc-java-1.10.0",
    urls = [
        "https://github.com/grpc/grpc-java/archive/v1.10.0.zip",
    ],
)
```

However, there's a convention to name a repository by reverse DNS, so something like `com_github_grpc_grpc_java` is more common.

Should we change the statement in the `WORKSPACE` file to `com_github_grpc_grpc_java`?

**Comment by jyane** [comment]
`io_grpc_grpc_java` would be better?

**Comment by cgrushko** [comment]
I'll let the maintainers decide, but - there's nothing at `http://grpc.io/grpc_java`, so it's harder for me personally to guess that name. On the other hand, I don't know what's the convention here.

**Comment by carl-mastrangelo** [comment]
@cgrushko the name is the concatenation of the Maven Group ID and Artifact id:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.grpc%22

I think @jyane  is suggesting this.

**Comment by ejona86** [comment]
:-/ it seems `io_grpc_java` is now "the thing to do." We've not done a release yet with `io_grpc_grpc_java` and `io_grpc_java` is cleaner. So I've opened #4181 for tracking.
