### ISSUE TITLE
GET_MEMOIZED_IS_INITIALIZED method in dynamicMethod unsupported operations

### ISSUE THREAD

**Issue by s4kibs4mi** [grpc/grpc-java#4099]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
`io.grpc:protoc-gen-grpc-java:1.10.0`

### What did you expect to see?

<img width="801" alt="screen shot 2018-02-19 at 12 44 03 pm" src="https://user-images.githubusercontent.com/5650785/36365277-0c5e190a-1573-11e8-9898-cee1f4d4a46d.png">

**Comment by ericgribkoff** [comment]
I believe you're encountering known issues with mixing the javalite and java protobuf runtimes, as in https://github.com/google/protobuf/issues/3879. Can you try out the build configuration from our Android examples (e.g., [here](https://github.com/grpc/grpc-java/blob/master/examples/android/helloworld/app/build.gradle)) and let me know if you still run into any problems?

**Comment by s4kibs4mi** [comment]
@ericgribkoff Solved the issue. Maybe that was the problem..mixing of versions. Thanks for the response.

**Comment by kraghu** [comment]
@ericgribkoff We are facing the same issue . I cant upgrade to 1.10.0 because of the mizing of the javalite and java protobuf runtimes. We dont have protobuf generation handled on the client side. we have server side generating it for us and we pull them using gradle. Our gradle got this 
   ```
 implementation 'io.grpc:grpc-okhttp:1.10.0'
    implementation 'io.grpc:grpc-protobuf:1.10.0'
    implementation 'io.grpc:grpc-stub:1.10.0'
```
How do i fix this ?

**Comment by ericgribkoff** [comment]
@kraghu I'd need more information to fully understand the issue you're encountering. If you are generating the proto code only on the server side, you can/will run into incompatibilities if you try to use this generated code with a newer version of the protobuf library on the client (I believe this is expected). You should generate the protobuf code for the client using the same protobuf version - I think your clients are Android, in which case you should use grpc-protobuf-lite. You can see how this is configured in our example Android clients.
