### ISSUE TITLE
Document grpc-netty-shaded in Troubleshooting guide

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-java#4103]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.9

### What did you expect to see?
[Troubleshooting guide](https://github.com/grpc/grpc-java/issues) should also reference to grpc-netty-shaded for gRPC 1.9+

Also, add additional info re: https://github.com/grpc/grpc-java/issues/4163

**Comment by carl-mastrangelo** [comment]
@saturnism Are you taking this on?

**Comment by saturnism** [comment]
Yeah I'm working on a PR. What should we say if the user is on an unsupported platform, e.g., 32-bit Windows? Are there options at all? Thanks,

**Comment by saturnism** [comment]
@carl-mastrangelo tcnative doesn't have 32bit builds. is the recommendation to:
- build your own tcnative
- use Netty ALPN?

**Comment by saturnism** [comment]
quick ping. if no options, then we'll make it clear in the doc too. Thanks!

**Comment by carl-mastrangelo** [comment]
@saturnism I think we should make it clear that 32 bit windows should use jetty ALPN, or compile netty_tcnative themselves.  It would be too much effort to get 32bit windows builds for netty_tcnative.

**Comment by saturnism** [comment]
Thanks, I'll make that clear in the update!
