### ISSUE TITLE
Windows CI is broken by GitHub HTTPS changes

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4120]
When trying to download protobuf:
```
iwr : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:5
+ & { iwr https://github.com/google/protobuf/archive/v3.5.1.zip -OutFile 
protobuf. ...
+     
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 
  pWebRequest) [Invoke-WebRequest], WebException
   + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 
  ll.Commands.InvokeWebRequestCommand
```

This seems caused by https://githubengineering.com/crypto-removal-notice/ . It's unclear how we should fix it.

**Comment by nicolasnoble** [comment]
Interestingly, while github.com isn't supporting anything else than TLS/1.2, raw.githubusercontent.com still does support TLS/1.0 and TLS/1.1. So doing an `iwr` on https://github.com/ doesn't work, but works on https://raw.githubusercontent.com.

One solution would be to try hitting github's CDN instead of their frontend that is.

**Comment by nicolasnoble** [comment]
Compare:

https://sslanalyzer.comodoca.com/?url=https%3A%2F%2Fgithub.com%2Fgoogle%2Fprotobuf%2Farchive%2Fv3.5.1.zip

with

https://sslanalyzer.comodoca.com/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgrumpycoders%2Fnvm-ps%2Fmaster%2Fnvm.ps1

**Comment by nicolasnoble** [comment]
Found the solution:

```
powershell -c '& { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; iwr https://github.com/google/protobuf/archive/v3.5.1.zip -OutFile protobuf.zip }'
```
