### ISSUE TITLE
Support multiple ports in gRPC Java server

### ISSUE THREAD

**Issue by fiower** [grpc/grpc-java#4134]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Most recent

### What did you expect to see?
Support multiple ports in gRPC Java server.

**Comment by zpencer** [comment]
@fiower can you provide more context about what problem you're trying to solve by exposing multiple ports?

**Comment by carl-mastrangelo** [comment]
Multiple ports is common inside google.  The C implementation of gRPC Java supports it already.
