### ISSUE TITLE
Access the local address of a call from ServerCallHandler

### ISSUE THREAD

**Issue by fiower** [grpc/grpc-java#4135]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
most recent

### What did you expect to see?
After https://github.com/grpc/grpc-java/issues/4134, I'd like to know which port/address the current inbound request comes from.

**Comment by zpencer** [comment]
Would the `authority` be sufficient here?

**Comment by carl-mastrangelo** [comment]
@zpencer in this case it would not.  The server wants to to know what address it was listening on which is not exposed.   The authority would say who the client thinks it is talking to, but that may not include the port.

**Comment by ejona86** [comment]
What is the use-case here? I expect #4134 is related, but what will you do with the address/port? Is this to have like a "admin port" which has different authn/authz/security checking?

**Comment by fiower** [comment]
@ejona86 My use case may not be common -- I'm creating a gRPC proxy which involves differentiating servers which implement the same service with different ports of the proxy. 

@zpencer I guess `authority` would work in my case if I could make sure all address contains port, is it right? But it's kind of indirect and depends on the "host:port" assumption, as @carl-mastrangelo suggested.

**Comment by ejona86** [comment]
@fiower, why not configure your proxy differently between the two ports? Is there some reason making two instances of the proxy service (one for each server/port) would be a problem? I could understand more if you needed the _local ip_, but it sounds like you need the _local port_; that's likely best served in other ways.

I'm not against providing local address information, but it sounds like even if it was available today I would suggest avoid using it for your use-case.

**Comment by ejona86** [comment]
@fiower, friendly ping.

**Comment by fiower** [comment]
@ejona86 Yes, this should work though ideally I'd like to only have one instance of the proxy component. The authority approach would also work in my case.

**Comment by ejona86** [comment]
We've seen another request for this internally at b/116771888. It can be used for security analysis and to create a connection to back the same server for co-hosted protocols other than gRPC.
