### ISSUE TITLE
Provide FakeClock API in io.grpc.testing

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#4141]

**Comment by zpencer** [comment]
Per discussion about guava-testing, maybe we should also investigate whether we can simply use that implementation instead of FakeClock.

**Comment by dapengzhang0** [comment]
`com.google.common.testing.FakeTicker` provides fake ticker. 

`com.google.common.util.concurrent.testing.TestingExecutors` provides `NoOpScheduledExecutorService`

Wondering which class in guava-testing provides `FakeTicker`-based `ScheduledExecutor`.

**Comment by zpencer** [comment]
Ah, the class may be internal only. Search for FakeScheduledExecutorService.

**Comment by dapengzhang0** [comment]
Thanks @zpencer , thank will work at least for us.
