### ISSUE TITLE
Don't require forked tomcat native

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#4148]
On reflection, it seems very strange that an allegedly interoperable network protocol for **Java** requires native code and therefore severely limits the platforms it runs on. This leaks into other software such as the API client libraries at google-cloud-java that have weird not-really-edge conditions such as not running on Android or on the Java 7 App Engine runtime. 

Personal opinion here:
Performance be damned. Interoperability comes first. forked tomcat native should be optional at most. This library should be pure Java and fully functional in any standards-conformant VM.

**Comment by carl-mastrangelo** [comment]
@elharo You are welcome to find an alternative.  gRPC depends on the TLS ALPN extension, which is not supported by Java 8 or below.

Also, you may not realize how damning the performance is.   gRPCs main selling point is performance.  Performance costs people real money, and "damning"  it is akin to overpaying for CPU resources.   Native code has a 20x - 150x speed up for SSL, and we really can't make that compromise for all users.

**Comment by elharo** [comment]
Thanks. That explains a few things, but I'm afraid it just means the hole is even deeper than I feared.

For unrelated reasons, Java 9 adoption in the enterprise is close enough to zero to be a rounding error; and this is not going to change before Java 9 is EOL'd shortly.
Java 10 is not going to improve things.

HTTP 2 is not going to be feasible in Java until Java 11 which is the first long term support release. Maybe next September if we're lucky.

**Comment by carl-mastrangelo** [comment]
As mentioned in our SECURITY.md doc, you can use ALPN boot to hack in ALPN support.   It swaps out the default bootstrap classes for SSL with modified ones.   We test with it, even though we highly recommend against it.   It needs a ton of babying to get it to work.  Not everyone can change out the boot class path, which sounds like AppEngine.

Also, in case you didn't see it, we do test on App Engine JDK7: https://github.com/grpc/grpc-java/tree/master/gae-interop-testing/gae-jdk7

**Comment by ejona86** [comment]
google-cloud-java is choosing not to support GAE Java 7, but gRPC has supported it for a while (albeit, quietly and without clear documentation). Just make sure to use the OkHttp transport. (This isn't really all that weird, when the cloud java stuff was happening Java 7 was already deprecated or similar. The Java 8 environment is also _much_ nicer in that it lifts multiple restrictions.)

We totally have Android support. We do require the Google Play Services Dynamic Security Provider, but this is a best-practice even for normal HTTP/1.

Note that the problems with Java 7 are more severe, in that it also does not support AES GCM, which is required for HTTP/2. And it doesn't even have TLS v1.2 enabled by default (granted, you can enable it with configuration).

We have been working on Conscrypt support as well. Conscrypt is what provides TLS support on Android. It is a binary component similar to netty-tcnative, but it could be used by more software.

Yes, we've been following the changes to the Java version support. But we can't really resolve the issues there. We're "waiting to see" like the rest of the world.

There doesn't seem to be anything that can really be done here. We do work on Java 7 and Java 8 and while we'd love to get ride of the binary component on those versions, it doesn't seem feasible.
