### ISSUE TITLE
fix regression in v1.9.0 where using GRPC_PROXY_EXP with the Netty transport would cause an UnresolvedAddressException is not available in 1.10.0

### ISSUE THREAD

**Issue by arief-hidayat** [grpc/grpc-java#4157]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.10.0

### What did you expect to see?
The following is listed in the release note (
https://github.com/grpc/grpc-java/releases/tag/v1.10.0)
netty: fix regression in v1.9.0 where using GRPC_PROXY_EXP with the Netty transport would cause an UnresolvedAddressException (#4027).

However, i still face the same issue and fix seems not included in this 1.10.0 release.

**Comment by ejona86** [comment]
Does the fix in 1.9.1 work for you? The problem is that it missed the v1.10.x branch cut and failed to be backported, right? (I see the change on master.)
