### ISSUE TITLE
GRPC client uses different threads when it calls client code when Fixed ThreadPool is set

### ISSUE THREAD

**Issue by lorensewusu** [grpc/grpc-java#4162]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.10.0

### What did you expect to see?

I tweaked your example service to have something like this

`rpc RouteChat(stream RequestChat) returns (stream RouteNote) {}`

I have my client callback looking like this 

`    StreamObserver<RequestChat> requestObserver =
        asyncStub.routeChat(new StreamObserver<RouteNote>() {
          @Override
          public void onNext(RouteNote note) {
            info(Thread.currentThread().getName() + " Received note");
          }`

When i set up my channel without setting an executor 

`    channel = ManagedChannelBuilder.forAddress(host, port)
            .usePlaintext(true).build();`

or when i set up my channel with a cachedThreadPool i.e.

`    channel = ManagedChannelBuilder.forAddress(host, port)
            .executor(Executors.newCachedThreadPool())
            .usePlaintext(true).build();`

I make 1 request to the server which sends me a stream of data.

All calls to the client is placed on a single thread everytime see below

`Mar 01, 2018 6:52:19 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: grpc-default-executor-1 Received note
Mar 01, 2018 6:52:20 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: grpc-default-executor-1 Received note
Mar 01, 2018 6:52:20 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: grpc-default-executor-1 Received note
Mar 01, 2018 6:52:20 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: grpc-default-executor-1 Received note
Mar 01, 2018 6:52:20 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: grpc-default-executor-1 Received note`

Which is what i expect.

However, when i set the executor to be a fixed pool like so

`    channel = ManagedChannelBuilder.forAddress(host, port)
            .executor(Executors.newFixedThreadPool(5))
            .usePlaintext(true).build();
    asyncStub = RouteGuideGrpc.newStub(channel);`

Every single response on the same stream request is cycled between the 5 threads i have set, so it moved from 1 for the first tick to 5 and 1 again, in a round robin way. look at my output

`Mar 01, 2018 6:55:03 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: pool-1-thread-1 Received note
Mar 01, 2018 6:55:03 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: pool-1-thread-2 Received note
Mar 01, 2018 6:55:03 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: pool-1-thread-3 Received note
Mar 01, 2018 6:55:03 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: pool-1-thread-4 Received note
Mar 01, 2018 6:55:04 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: pool-1-thread-5 Received note
Mar 01, 2018 6:55:04 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: pool-1-thread-1 Received note
Mar 01, 2018 6:55:04 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: pool-1-thread-2 Received note
Mar 01, 2018 6:55:04 PM io.grpc.examples.routeguide.RouteGuideClient2 info
INFO: pool-1-thread-3 Received note
Mar 01, 2018 6:55:05 PM io.grpc.examples.routeguide.RouteGuideClient2 info`

I expect to be called on the same thread.
Can someone explain to me why this happening and if there is a way i set my own executor without having this behaviour. 
Lastly and most importantly, if it is using different threads in calling me, am i still guaranteed that i will not receive messages concurrently? The whole idea of using a stream is to receive messages in order, i am concerned that with this behavior i might receive messages concurrently and hence might be processed in the wrong order.

**Comment by carl-mastrangelo** [comment]
> I expect to be called on the same thread.

You should not expect this.   Suppose there are only 2 thread in your executor and you have 3 outstanding calls.  Call 1 gets scheduled on thread A, Call 2 gets Scheduled on Thread B, and Call 3 gets scheduled again on thread A.   If Call 2 completes quickly, but Call 1 takes a very long time, Call 3 will be stuck waiting for thread A to become free.  (possibly forever).

Each callback for each call is scheduled by the executor you pass into the channel.  If you do want this behavior, you can make your own Executor which tries to schedule the same call on to the same thread.  

> Lastly and most importantly, if it is using different threads in calling me, am i still guaranteed that i will not receive messages concurrently? 

You may get messages concurrently, but for any given RPC, all messages will happen in order.  All messages (and all other events like headers, and closing), also happen serially per RPC, so there is no chance of accidentally handling the same RPC by different threads at the same time.  (you could of course, intentionally do it).

All callbacks are wrapped in a `SerializingExecutor` which ensures this behavior.

**Comment by lorensewusu** [comment]
Thanks for your detailed reply, can you confirm that although I am being called with different threads, this will be serial so if I haven't finished processing one call the other thread with the next message will not call me.

**Comment by carl-mastrangelo** [comment]
That is guaranteed, assuming you mean the messages of a *single* RPC.   If you have multiple RPCs (i.e. multiple stream observers), you do not have this guarantee.

**Comment by lorensewusu** [comment]
Yes understood.
