### ISSUE TITLE
Massive latency when using grpc on the same machine i.e. network latency is negligible

### ISSUE THREAD

**Issue by lorensewusu** [grpc/grpc-java#4164]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.10.0

### What did you expect to see?
Latency of less than 1 ms

I am running a server which is set up like this
```
ServerBuilder.forPort(port)
                .executor(Executors.newCachedThreadPool())
                .addService(new PricingService(config))
                .build()
                .start();
```

I have service like this 
```
service PricingService {
  rpc SubscribeQuote(stream ESPQuoteRequest) returns (stream ESPQuote) {}
}
```
I have a simple client like this 
```
        ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 8888)
                .usePlaintext(true)
                .executor(Executors.newFixedThreadPool(20))
                .build();
        server = PricingServiceGrpc.newStub(channel).withWaitForReady();
```

Inside the client, i basically log the difference between when the quote was published by the client and when it is received in the client

```                server.subscribeQuote(new StreamObserver<Pricing.ESPQuote>() {
                    @Override
                    public void onNext(Pricing.ESPQuote espQuote) {
                        grpcLatency.addValue(System.currentTimeMillis() - espQuote.getTimers().getApiPublishMillis());
                    }
```

In the client, i make 2 requests and i receive 4 ESPQuote messages per second. I run both the client and server on the same computer and the numbers i am seeing in terms of latency is too big. I expect microseconds maximum but look at what i am seeing at the moment

`Count<1919> Mean<3.905979253777211> Min<0.0> Max<17.0> StdDiv<1.9792049782637602>
Count<1999> Mean<3.841482094990977> Min<0.0> Max<17.0> StdDiv<1.9712545363765366>
Count<2079> Mean<3.792100546921828> Min<0.0> Max<17.0> StdDiv<1.9583069433857152>
Count<2159> Mean<3.7431377013113507> Min<0.0> Max<17.0> StdDiv<1.974710631465047>
Count<2239> Mean<3.6878281062822693> Min<0.0> Max<17.0> StdDiv<1.9706792738137429>
Count<2319> Mean<3.636778690839975> Min<0.0> Max<17.0> StdDiv<1.9613034473220703>
Count<2399> Mean<3.5853814102098767> Min<0.0> Max<17.0> StdDiv<1.9549041605286621>
Count<2479> Mean<3.537715345154542> Min<0.0> Max<17.0> StdDiv<1.9484957897190052>
Count<2559> Mean<3.4961725443659977> Min<0.0> Max<17.0> StdDiv<1.9476655378025411>
Count<2639> Mean<3.4586748986405893> Min<0.0> Max<17.0> StdDiv<1.9351426632736348>
Count<2719> Mean<3.424495698090723> Min<0.0> Max<17.0> StdDiv<1.921892608252186>
Count<2799> Mean<3.3779485434176366> Min<0.0> Max<17.0> StdDiv<1.9206222368282564>
Count<2879> Mean<3.3385210073892906> Min<0.0> Max<17.0> StdDiv<1.915137477382633>
Count<2959> Mean<3.3056342592215593> Min<0.0> Max<17.0> StdDiv<1.9035968628523137>`

1) Am i wrong to say i expect grpc latency to be extremely small i.e. in microseconds
2) Am i doing something wrong, do i need to change the way i am setting up my server and or client?
3) Is grpc a good tool for building a low latency application?

Thanks

**Comment by carl-mastrangelo** [comment]
If you are trying to measure duration, you should use System.nanoTime.  Not only is it more precise, but it never goes backwards in time.  currentTimeMillis is adjusted occasionally by the OS, and is only suitable for telling the current "calendar" time.

Second: mean and stddev are not so useful metrics.   RPCs have a power distribution rather than a normal distribution.  As an approximation, we use an exponential distribution.   What this means to you is that you should pick a metric that reflects the underlying behavior.   I recommend using HdrHistogram (which is optimized for being updated concurrently) for measuring the 50th and 99th percentile latencies.  

Lastly:  you're server builder should also be using a fixed thread pool.

**Comment by lorensewusu** [comment]
It is very easy for me to use NanoTime but i was concerned that because they are running in different processes (albeit) on the same machine I might get incorrect elapsed times. I can change it to nanoTime which is not an issue. In doing that, I realised the numbers are not too different.

I will give you the percentiles and also make the server use a fixed thread pool

**Comment by lorensewusu** [comment]
I have changed the code to use fixed pool for the server, i measure the latency using NanoTime now and also i spit out the percentiles (50, 90, and 99.9).  I am using an aparche library which does the job ok 
http://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/stat/descriptive/DescriptiveStatistics.html 

The results are not too different (especially the 90th + percentile), see below

`Count<1678> Mean<1708239.6382598376> Min<377571.0> Max<1.3896059E7> StdDiv<1193244.1523026729> 50 Percentile<1317754.0> 90 Percentile<3108899.4000000004> 99.9 Percentile<1.3229797040000137E7>
Count<1758> Mean<1676741.494880539> Min<377571.0> Max<1.3896059E7> StdDiv<1177428.8967342102> 50 Percentile<1279192.5> 90 Percentile<3083155.8000000007> 99.9 Percentile<1.3151297840000208E7>
Count<1838> Mean<1657783.9662676745> Min<377571.0> Max<1.9579323E7> StdDiv<1234934.7545323514> 50 Percentile<1261298.5> 90 Percentile<3054025.400000001> 99.9 Percentile<1.4811064504001623E7>
Count<1918> Mean<1626142.924921793> Min<377571.0> Max<1.9579323E7> StdDiv<1219838.2296131875> 50 Percentile<1241046.5> 90 Percentile<3040570.8> 99.9 Percentile<1.4356403384000745E7>
Count<1998> Mean<1597791.7407407435> Min<377571.0> Max<1.9579323E7> StdDiv<1205158.5053435438> 50 Percentile<1222598.0> 90 Percentile<3022648.8000000003> 99.9 Percentile<1.3901742264001157E7>
Count<2078> Mean<1568427.9562079026> Min<377571.0> Max<1.9579323E7> StdDiv<1192354.8845707711> 50 Percentile<1198462.5> 90 Percentile<2999401.6000000006> 99.9 Percentile<1.3818541040000271E7>
Count<2158> Mean<1542866.219647831> Min<377571.0> Max<1.9579323E7> StdDiv<1179190.4200739027> 50 Percentile<1181539.5> 90 Percentile<2975987.2> 99.9 Percentile<1.3740041840000343E7>
Count<2238> Mean<1521024.4459338759> Min<377571.0> Max<1.9579323E7> StdDiv<1165429.8440210803> 50 Percentile<1166004.0> 90 Percentile<2948744.7> 99.9 Percentile<1.3661542640000414E7>
Count<2318> Mean<1497997.943917182> Min<377571.0> Max<1.9579323E7> StdDiv<1153096.461417072> 50 Percentile<1153520.0> 90 Percentile<2910543.7999999993> 99.9 Percentile<1.3583043440000039E7>
Count<2398> Mean<1478222.3298582132> Min<377571.0> Max<1.9579323E7> StdDiv<1140288.0804419864> 50 Percentile<1144087.5> 90 Percentile<2896699.6999999997> 99.9 Percentile<1.350454424000011E7>
Count<2478> Mean<1458211.0964487512> Min<377571.0> Max<1.9579323E7> StdDiv<1128559.5319477846> 50 Percentile<1135904.0> 90 Percentile<2856223.799999999> 99.9 Percentile<1.3426045040000182E7>
Count<2558> Mean<1439263.5926504934> Min<377571.0> Max<1.9579323E7> StdDiv<1117092.7540636633> 50 Percentile<1125916.0> 90 Percentile<2820908.5999999996> 99.9 Percentile<1.3347545840000253E7>
Count<2638> Mean<1421018.8760424373> Min<377571.0> Max<1.9579323E7> StdDiv<1106090.4564190516> 50 Percentile<1118148.5> 90 Percentile<2794747.4> 99.9 Percentile<1.3269046640000325E7>
Count<2718> Mean<1404023.5176600576> Min<377571.0> Max<1.9579323E7> StdDiv<1095226.8743609206> 50 Percentile<1109825.5> 90 Percentile<2761123.3999999994> 99.9 Percentile<1.3190547440000396E7>`

**Comment by carl-mastrangelo** [comment]
Without seeing the server code, I don't know that the latency isn't from the application itself.  Are you measuring how long the server thinks the latency is between getting an ESPQuoteRequest and calling onNext?

**Comment by lorensewusu** [comment]
Find attached my code.

[exceed.zip](https://github.com/grpc/grpc-java/files/1776252/exceed.zip)

The client is the PricingClient . Also i include the server time when i create the message 

`                List<Pricing.ESPQuote.RateStep> rateSteps = rateConfiguration.createVolumeLadder(tenor);
                Pricing.ESPQuote espQuote = Pricing.ESPQuote.newBuilder()
                        .setTimers(Common.Timers.newBuilder()
                                .setApiPublishMillis(System.currentTimeMillis())
                                .setApiPublishNanos(System.nanoTime()))
                        .setBaseDetails(requestPayload.baseDetails)
                        .setStreamId(s)
                        .setCurrencyPair(requestPayload.baseDetails.getBaseCurrency() + requestPayload.baseDetails.getTermCurrency())
                        .setQuoteId(quoteIdGenerator.incrementAndGet() + "")
                        .setGfa(rateConfiguration.getGfa() + "")
                        .addAllVolumeLadder(rateSteps)
                        .build();
                requestPayload.publish(espQuote);`

And then publish it immediately

In the RequestPayload class, this is how the publish method does

`   public void publish(Pricing.ESPQuote espQuote){
        if(streamObserver != null) {
            streamObserver.onNext(espQuote);
            if (publishedFirstPrice.compareAndSet(false, true)) {
                logger.info("Published first price for <{}>", espQuote.getStreamId());
            }
        }
    }`

**Comment by carl-mastrangelo** [comment]
For the record: nanotime is not consistent across JVMs.  You need to compare start and finish times on the client, and not depend on the nanos in the response (except if they were originally from the client).

**Comment by lorensewusu** [comment]
That's why I use current milliseconds in my initial example. I can revert back to milliseconds but the main issue here is the latency

**Comment by carl-mastrangelo** [comment]
Looking at your code, it would be easier if the pom.xml file was included so I could run it in Intellij.  

Also, Are you getting more than 1000 updates per second?  If not, the JVM may not have compiled your methods to the fast JIT code, and it may be interpretting them.   If so, that System.out.println is going to slow you down a lot.

**Comment by lorensewusu** [comment]
I have attached jars with the protos and the pom file with the versions i am using.
[Extra stuff.zip](https://github.com/grpc/grpc-java/files/1776356/Extra.stuff.zip)

I am sending 4 updates per second for each request, considering i have 2 requests that is 8 updates per second. Could you explain what you mean by the jvm not compiling my code to fast JIT, is this something I can configure?

Let me know if you need any more information.

**Comment by carl-mastrangelo** [comment]
You should be able set `-Xcomp` to force compilation.  Generally, the JVM only optimizes code that is run very often (like 1000s of times).   I don't expect 8 QPS to trigger this unless it is run for a very long time.   If you can try turning the QPS up to maybe 1k/s  or thereabouts you would get a more accurate measurement.


As for the nanotime:  Can you make the client put it in the request somewhere, and the server echo it back in the response?  That way the client can make precise measurements.

**Comment by lorensewusu** [comment]
ok, these are things i can try but can you check why i am not able to get below a millisecond for sending 8 updates per second from my server on the same server?

**Comment by carl-mastrangelo** [comment]
It's probably because the code is not being compiled.  By default, the JVM stays in interpreter mode in order to have fast start up time.  It uses tiered compilation to selectively compile functions that are considered "hot" and called often.   There are ~3 levels: C0, C1, and C2.   C0 is no compilation, just interpreter mode.  C1 is compiled code, but without any optimizations.   C2 is fully optimized.

Each level is more expensive to compile, so the JVM avoids compiling it unless it thinks it will be worth it.   IIRC it doesn't even bother unless the function is called at least 1500 times.  That means you either need to turn up the QPS, or let it run for a few hours.   When doing benchmarking of any kind, you need to let the machine warm up.  

As an example: look at your results you posted.   Notice how it seems to be getting faster each line?

**Comment by lorensewusu** [comment]
OK so i have set the -Xcomp flag for both server and client and i am going to run this for a few hours and see what happens.

**Comment by lorensewusu** [comment]
I've run for 1.5hrs with these changes
1) 600 updates per second
2) Added the -Xcomp flag for both server and client

After the long run, i can see the latency is much much better, i am getting 1ms for 99 percentile. Is there anything i can do to get to microseconds?

Also because i am running on my local machine, network latency is very tiny, is there something i have to do to make sure network latency is as low as possible when server and client are run on different servers?

`Count<2370658> Mean<0.5103410108084577> Min<0.0> Max<372.0> StdDiv<2.0796123472964934> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2374658> Mean<0.5103080106683844> Min<0.0> Max<372.0> StdDiv<2.0779630169656573> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2378658> Mean<0.5105000382577806> Min<0.0> Max<372.0> StdDiv<2.0763173729515403> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2382658> Mean<0.5105176655660589> Min<0.0> Max<372.0> StdDiv<2.074678436765515> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2386658> Mean<0.5106579995952913> Min<0.0> Max<372.0> StdDiv<2.0730402616276815> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2390658> Mean<0.510345268960063> Min<0.0> Max<372.0> StdDiv<2.0714144383549478> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2394658> Mean<0.5103183836688958> Min<0.0> Max<372.0> StdDiv<2.069783040054282> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2398658> Mean<0.5103182696320285> Min<0.0> Max<372.0> StdDiv<2.068158725818969> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2402658> Mean<0.5103056698034276> Min<0.0> Max<372.0> StdDiv<2.066537779841183> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2406658> Mean<0.5103791232493916> Min<0.0> Max<372.0> StdDiv<2.064921119187338> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
Count<2410658> Mean<0.5102449206809286> Min<0.0> Max<372.0> StdDiv<2.0633080321498625> 50 Percentile<0.0> 90 Percentile<1.0> 99.9 Percentile<1.0>
`

**Comment by carl-mastrangelo** [comment]
If you want microsecond precision, you need to use System.nanoTime, and you cannot use the remote peer's clock.  It is clear from your results that you are running into sampling issues, so the next step is nanoTime.  

We use it exclusively for all benchmarks.   Also, latency is measured as round trip time (RTT), not from client to server.

**Comment by ejona86** [comment]
There doesn't seem to be a gRPC issue here, just the JIT not being warmed up. Closing.
