### ISSUE TITLE
channel.getState(true) will not reconnect

### ISSUE THREAD

**Issue by tukez** [grpc/grpc-java#4170]
The javadoc for ManagedChannel.getState:
_Gets the current connectivity state. Note the result may soon become outdated.
Parameters:requestConnection if true, the channel will try to make a connection if it is currently IDLE_

However, it attempts to connect only if there has not been an open connection already. After disconnect, channel.getState(true) will not attempt to reconnect (state is IDLE).

### What version of gRPC are you using?
1.9.0

### What did you expect to see?
channel.getState(true) should try to reconnect the channel if the state is idle.

**Comment by ejona86** [comment]
`getState(true)` is only calling `exitIdleMode()`. That is enough to get to READY if in idle mode, but not if the LB and InternalSubchannel are running and have gone IDLE, as it does nothing in that case.

**Comment by ejona86** [comment]
Note that there is a workaround: you can issue a trash RPC on the channel (it doesn't even need to be supported by the backend!). That is still enough to bring it out of IDLE.
