### ISSUE TITLE
Bump to Guava 20

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4176]
We downgraded to Guava 19 in #2751. A lot of time has passed. We really want to get on to the more stable Guava versions.

We want to bump to Guava 20, and if that goes well try to bump further. I think Guava 21 was built with JDK 8 (or some such), so we need to avoid, but the following fixed that.

After we get to Guava 20 we should open a new issue to track upgrading further.

**Comment by rmichela** [comment]
Does gRPC use any Guava APIs that have been deprecated or removed in Guava 21+?

Many of our internal utility libraries depend on Java 8 and use the Java 8 features of Guava 21+. The Guava 19/20+ incompatibility problems have forced us to do uncomfortable things with shading and relocating.

With this change, will gRPC be forward compatible with the latest version of Guava, in case a consumer has to pull a more recent version onto the classpath?

**Comment by ejona86** [comment]
@rmichela, gRPC Java works fine with newer releases of Guava. There's no deprecation warnings when building grpc-java with Guava 24.0-android or 24.0-jre. This is very important to us and will continue to be maintained.

I'll note that gRPC won't upgrade to Guava 21 as it is slightly special, and was built with Java 8. Once we drop Java 6 support we could upgrade to an "android" version starting with Guava 22 which is built with Java 7.
