### ISSUE TITLE
Suggestion to add keyOfProto method to ProtoLiteUtils

### ISSUE THREAD

**Issue by 540Grunkspin** [grpc/grpc-java#4180]
Is there a reason for why *protobuf-lite* doesn't have the `keyForProto` method in the `ProtoLiteUtils`? I seem to be able to implement it as a helper method my self, the same way it is implemented in `ProtoUtils`.

### What version of gRPC are you using?
proto-lite 1.9.0

### What did you expect to see?
A `keyOfProto` method in `PotoLiteUtils`

**Comment by 540Grunkspin** [comment]
Firgured out the reason hehe

**Comment by ejona86** [comment]
`MessageLite` doesn't have `getDescriptorForType()`.

**Comment by ejona86** [comment]
If you're aware of some way to get the message name from a `MessageLite`, I'd be happy to implement the convenience method. But at present I do not believe it is possible. You should create a key manually with a hard-coded key name and a ProtoLiteUtils.metadataMarshaller.
