### ISSUE TITLE
Change Bazel Workspace name to io_grpc_java

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4181]
`io_grpc_java` is what's returned by `getName('io.grpc', 'grpc-java')` as defined by https://github.com/bazelbuild/bazel/blob/0.11.1/tools/build_defs/repo/java.bzl#L86 , as `java_import_external` is replacing `maven_jar`.

CC @carl-mastrangelo, @cgrushko, @jyane

**Comment by ejona86** [comment]
But... that name is assuming maven central, and our maven central name would simply be `io.grpc:grpc` (as that's the prefix of our artifacts). Getting rid of the stuttering from `io_grpc_grpc_java` would be nice though...

**Comment by cgrushko** [comment]
Sorry, I'm confused. What's the output of `getName()`, and what would you prefer? 
Also, `getName()` might have bugs and is probably not authoritative yet.

**Comment by ejona86** [comment]
`io_grpc_java` is the output. It seems the function goes out of its way to remove duplication, and that behavior is described in the java_import_external documentation as well.

And now that I'm looking more, I see C core [is using `com_github_grpc_grpc`](https://github.com/grpc/grpc/blob/v1.10.0/WORKSPACE#L1).

And Bazel is using `io_bazel` and the rules repositories are `io_bazel_rules_*` but buildtools is `com_github_bazelbuild_buildtools`.

**Comment by cgrushko** [comment]
Yeah, it's a mess.
I would personally go for reverse DNS based on github, even for Bazel (which started at http://bazel.io and now we're stuck with `io_bazel`) - it makes things easier to find.
`io_grpc_java` avoids stuttering and also uses http://grpc.io as authority but it's harder for me to guess where it's coming from. Or conversely, after I'd find http://github.com/grpc/grpc-java, it wouldn't be O(1) for me to figure out what the repo name.

**Comment by ejona86** [comment]
I personally see it as weird to have it be based on the git repository location. As evident from history, the repository location changes over time as the hosting environment changes. (Remember, it's been common to change repository systems over time!)

If we're going to have a strong association between the two, I'd feel drawn to have a repository redirect in the website (sort of what's like done for `google.golang.org` which redirects to github when called by git, because Go does have a similar strong association) so we could use `io_grpc_*`. But that's an annoying level of effort to go through for something of such minimal importance as the Bazel workspace name.

[The documentation](https://docs.bazel.build/versions/master/be/functions.html#workspace) simply states that "it should describe the project in reverse-DNS form" and then mentions "if a project is hosted", which don't really describe if it's the website or git repository or something else.

http://grpc.io/grpc-java does point at our `gh-pages` branch, which is how we populate https://grpc.io/grpc-java/javadoc . I guess we could create an index.html so that http://grpc.io/grpc-java doesn't 404 and then continue using `io_grpc_grpc_java`.

**Comment by jyane** [comment]
Yes, I thought concatenating the group id and an artifact name would be better, but in here, it might not.
I didn't know that the `getName('io.grpc', 'grpc-java')` returns `io_grpc_java`(it means `io_grpc_java` is valid for bazel?), so I will respect on @ejona86 and @cgrushko opinion. I'm sorry for my thoughtless.

**Comment by jyane** [comment]
The grpc-java has `java_grpc_library` rules. It is not the same as `grpc-*.jar` on maven, so using maven naming rule is might be weird, IMHO.
Using reverse website DNS (not git) like @ejona86's suggestion might be better.

**Comment by ejona86** [comment]
I've created a redirect from https://grpc.io/grpc-java to github.

It seems the only contenders now are `io_grpc_grpc_java` or `com_github_grpc_grpc_java`. With the redirect, both may be acceptable now. Since io_grpc is more of our identity (including package names) than github, I think I do prefer using a io_grpc prefix. Since the code has `io_grpc_grpc_java` it seems there's no need to change anything more.
