### ISSUE TITLE
ReadableBuffers.BufferInputStream does not release buffer on close()

### ISSUE THREAD

**Issue by srujann** [grpc/grpc-java#4198]
**gRPC Version used: 1.7.0
Netty Version used: 4.1.16.Final
Java version: 1.8.0_161**

Context:
Observed Netty leak detector complaining of bytebuf leaks on the gRPC server configured with Netty Epoll. This occurs more often, a few minutes after the service restarts on a prod machine. Here is the full trace of all 25 access for the bytebuf:
 [netty_buf_leak_trace.txt](https://github.com/grpc/grpc-java/files/1795622/netty_buf_leak_trace.txt)

The most recent access to the leaked bytebuf occurs at `io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:273)` but the bytebuf is actually released here.  Not sure what is causing the leak.

```
 ERROR [2018-03-09 02:25:49,034] io.netty.util.ResourceLeakDetector: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
 Recent access records: 25
 #25:
 	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:273)
 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
 	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
 	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
 	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
 	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
 	java.lang.Thread.run(Thread.java:748)
```

**Comment by carl-mastrangelo** [comment]
@srujann can you try running with `-Dio.netty.leakDetection.level=PARANOID` ?

**Comment by srujann** [comment]
@carl-mastrangelo Attached traces instances of leak captured with PARANOID level debug (they are quite long with lots of access records, so I did not attach all of them).  [netty_leaks_paranoid.txt](https://github.com/grpc/grpc-java/files/1798662/netty_leaks_paranoid.txt)

The last access in these cases happens at either `io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:273)` or `io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:518)`  both of which do release the bytebuf.

**Comment by srujann** [comment]
@ejona86 Thanks for pointing out that message data is not being read. The leaks are due to inputstream not being read due to an Exception when attempting to parse Response in our custom implementation of `Marshaller.parse(InputStream stream)`. We do close the inputstream but it seems that the underlying buffer is not closed  (_even when the stream is owner for the buffer_) as per https://github.com/grpc/grpc-java/blob/f56ac76b353be506688d02c2dcd7c284f9393013/core/src/main/java/io/grpc/internal/ReadableBuffers.java#L105.

Is it feasible to close the underlying buffer when inputstream owning the buffer is closed?

**Comment by srujann** [comment]
The logs I posted earlier are actually leaks from a client but the leak can occur on either client or server when RequestMarshaller or ResponseMarshaller fails to fully read the inputstream when parsing the message.

**Comment by ejona86** [comment]
@srujann, ah! You're right! ReadableBuffers.BufferInputStream.close() isn't overridden to close `buffer`. Yes, that should be fixed.

**Comment by ejona86** [comment]
@jyane, if you're interested in picking up issues, this one should be straight-forward.

It looks like we don't have a test class already for ReadableBuffers, so one would need to be created.

**Comment by jyane** [comment]
@ejona86 Yes :) I'll try.

**Comment by ejona86** [comment]
@jyane, I've added you as a collaborator on grpc-java, so I can assign this to you. You may now have write access to issues (I'm a bit uncertain).

**Comment by jyane** [comment]
@ejona86 Thanks! I've been added as a collaborator, and the permission is just same as a contributor (can't edit issues).

It's just a report of progress:
- Some tests already exists (e.g. [ReadableBuffersByteBufferTest](https://github.com/grpc/grpc-java/blob/8fe313f5981c43123c0cc34e8707f8292bc2e28a/core/src/test/java/io/grpc/internal/ReadableBuffersByteBufferTest.java#L27), [ByteWritableBufferTest](https://github.com/grpc/grpc-java/blob/8fe313f5981c43123c0cc34e8707f8292bc2e28a/core/src/test/java/io/grpc/internal/ByteWritableBufferTest.java#L22)) so I will add other tests.
- I've got what is the problem. Problem is ReadableBuffers.BufferInputStream.close doesn't close `buffer`, I think it should be closed [here](https://github.com/grpc/grpc-java/blob/8fe313f5981c43123c0cc34e8707f8292bc2e28a/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L531).

I will create 2 PRs. 1st is adding tests, 2nd is adding `close`.

**Comment by ejona86** [comment]
@jyane, that call to close in ClientCallImpl is the main place. There are some others (like `GrpcUtil.closeQuietly(MessageProducer)` that's called in the same method), but it's probably not worthwhile to worry about them.
