### ISSUE TITLE
How would one propagate credentials between multiple services

### ISSUE THREAD

**Issue by ensonic** [grpc/grpc-java#4212]
### What version of gRPC are you using?
1.10.0

### What did you expect to see?
We're working on multiple services that call each other. For several reasons among which is auditing, we'd like to use the credentials from an incoming call to any call that is done as part of it. So if e.g. the user calls `ServiceA.function1()` and that in turn calls `ServiceB.function2()`, we'd like to pass the `Metadata` used in the call to `ServiceA.function1()` when making the calls to `ServiceB.function2()`.

So far I've discovered and implemented a `ServerInterceptor` that would let me inspect the metadata passed when calling `ServiceA.function1()` and I tested `.withCallCredentials(new CallCredentials() { ... })` which lets me set `Metadata` on outgoing calls to `ServiceB.function2()`. Now unfortunately those two mechanisms are not coupled. I am making the calls to `ServiceB.function2()` in my `*ImplBase` and all I get there is a `StreamObserver`, but no other context. So I don't see a solid way to store the `Metadata` in the `Interceptor` so that I can access this in the `CallCredentails` (or in the `*ImplBase`).

Did I miss anything? Any suggestions? Please don't hesitate to tell me that this is not how I am supposed to do this, if that is the case.

**Comment by zpencer** [comment]
One solution is to store the information in the `io.grpc.Context` under a custom key/value pair, and running `ServerCallHandler<ReqT, RespT> next` in your new context. Here is a helper utility that makes this pattern easy: https://grpc.io/grpc-java/javadoc/io/grpc/Contexts.html#interceptCall-io.grpc.Context-io.grpc.ServerCall-io.grpc.Metadata-io.grpc.ServerCallHandler- . In your code that calls `ServerB`, you will need to check if there are credential key/values stashed in the context.

**Comment by ensonic** [comment]
Thanks for the suggestions. When you say "the io.grpc.Context" - I don't see this parameter anywhere in the java api (contrary to the go api). To make sure I understand right, your idea is to create a context (https://grpc.io/grpc-java/javadoc/io/grpc/Context.html) in the Interceptor and then retrieve that through Context.current() in the impl when making the call? The connection is done through thread local storage and should be okay since one thread only handles one call at a time.

**Comment by zpencer** [comment]
Correct, `Context` does not show up as any parameters in the usual gRPC methods because it is a thread local. If you application uses multiple threads, the Context API provides utilities to wrap callables, runnables, and even executors to propagate the threadlocal across threads. For example:
* https://grpc.io/grpc-java/javadoc/io/grpc/Context.html#currentContextExecutor-java.util.concurrent.Executor-
* https://grpc.io/grpc-java/javadoc/io/grpc/Context.html#wrap-java.util.concurrent.Callable-

I think you can also implement a `ClientInterceptor` that pulls the values from the context and modifies each call with `callOptions.withCallCredentials()`. This way the propagation is hidden from your application code.

**Comment by ensonic** [comment]
Please consider a sample for this. TBH, the apis docs are not very useful, since the almost never explain how things are to be used and what they do, only what the are (and that should be obvious form the names). Here is what I did in the end:
``` java
public class AuthContext {

  protected static final Context.Key<String> CONTEXT_X_API_KEY = Context.key("x-api-key");
  protected static final Metadata.Key<String> METADATA_X_API_KEY =
      Metadata.Key.of("x-api-key", Metadata.ASCII_STRING_MARSHALLER);
  // more keys
}

public class AuthContextServerInterceptor implements ServerInterceptor {
@Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
      ServerCall<ReqT, RespT> call,
      final Metadata requestHeaders,
      ServerCallHandler<ReqT, RespT> next) {
    Context current = Context.current();

    String metadata = requestHeaders.get(AuthContext.METADATA_X_API_KEY);
    if (metadata != null) {
      current = current.withValue(AuthContext.CONTEXT_X_API_KEY, metadata);
    }
    // repeat for each header ...
    return Contexts.interceptCall(current, call, requestHeaders, next);
  }
}

public class AuthContextClientInterceptor implements ClientInterceptor {
  @Override
  public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(
      MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {

    return next.newCall(
        method,
        callOptions.withCallCredentials(
            new CallCredentials() {
              @Override
              public void applyRequestMetadata(
                  MethodDescriptor<?, ?> methodDescriptor,
                  Attributes attributes,
                  Executor executor,
                  MetadataApplier metadataApplier) {
                executor.execute(
                    () -> {
                      try {
                        Metadata headers = new Metadata();

                        String metadata = AuthContext.CONTEXT_X_API_KEY.get();
                        if (metadata != null) {
                          headers.put(AuthContext.METADATA_X_API_KEY, metadata);
                        }
                        // repeat for other keys ...
                        metadataApplier.apply(headers);
                      } catch (Throwable e) {
                        metadataApplier.fail(Status.UNAUTHENTICATED.withCause(e));
                      }
                    });
              }

              @Override
              public void thisUsesUnstableApi() {}
            }));
  }
}
```
My service1 now creates the service2 like this:
``` java
Service2Grpc.newBlockingStub(channel).withInterceptors(new AuthContextClientInterceptor());
```

What I am a bit concerned are two things:
1. Context.withValue(): there is no api to first collect the values and then add them in one go. Context.withValues() would ideally take a Map
2. stability of CallCredentials(), but I guess thats what it is

If you have any comments on this example, please let me know.

**Comment by zpencer** [comment]
For performance reasons, we try to encourage users to keep the size of context small. If you know ahead of time the set of items you are interested in, I would recommend copying them into fields of a POJO. Also, if the fields are all absent in the metadata, then there is no need to call `Contexts.interceptCall`, you can simply return `next.startCall(...)`.
