### ISSUE TITLE
Hints for a Custom Marshaller(KnownLength vs Drainable)

### ISSUE THREAD

**Issue by srujann** [grpc/grpc-java#4214]
Using gRPC version **1.7.0** with Netty Epoll transport.

I am using a custom marshaller for non-proto messages. For `InputStream` provided by `Marshaller.stream(message)`, currently I don't have a way to provide length of the message without serializing it. So, I have these two options:

1. Support `KnownLength` by serializing the message to `byte[]` which would be helpful in reducing the number of `ByteBuf` allocations (in `MessageFramer` when draining the message to `OutputStream`) as length is known. But this approach loses the benefit of `Drainable`, where we would be copying the `byte[]` to `OutputStream`. 

2. Don't support `KnownLength` and support only `Drainable` to avoid additional copy when draining  to `OutputStream`. But this may lead to lot more `ByteBuf` allocations as message length is not known. (Due to using`BufferChainOutputStream` in `MessageFramer`).

Could you share your thoughts on which approach provides lower latency? (Especially if we have large messages of 10 MB or so.)

**Comment by carl-mastrangelo** [comment]
@srujann We have not benchmarked this part of the code seriously in a while,  since we were waiting on Protobuf changes in 3.5 to come in.  Now that they have landed, the shortcut-interfaces you see here may not provide as much benefit, so I don't want to say anything definitively about them.

**Comment by srujann** [comment]
@carl-mastrangelo If we are not using protobuf, these interfaces would still be useful, right? I will try to run some benchmarks with these combinations and see which one works out better.

**Comment by ejona86** [comment]
@srujann, since you can't easy obtain the length, I'd suggest not implementing KnownLength. I'd suggest implementing Drainable if it is the more "natural" interface for your serialization logic, and if it avoids allocating temporary byte[]s. Basically, do what's natural/cheap and let gRPC handle the rest.

**Comment by ejona86** [comment]
It seems this is answered reasonably for now. @srujann, comment more if you need more help on this topic and we can reopen. Closing.
