### ISSUE TITLE
Uncaught exception in server when client is killed

### ISSUE THREAD

**Issue by tukez** [grpc/grpc-java#4232]
### What version of gRPC are you using?
1.10.0

### What did you expect to see?
Client connection closing uncleanly is a common occurrence, so I expect it not to throw exceptions.

When I kill my client, I see uncaught exceptions in server side (not random). The exceptions does not seem to break anything (can't tell for sure though), but they are being caught in my thread pools uncaught exception handler. Client is doing streaming calls (server streaming and bidi streaming).

Note: I'm using https://github.com/salesforce/reactive-grpc stubs on top of protobuf stubs, if it makes a difference.

```
0: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
1: 	at io.grpc.Status.asRuntimeException(Status.java:517)
2: 	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272)
3: 	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:38)
4: 	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
5: 	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
6: 	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
7: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:282)
8: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:684)
9: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
10: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
11: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by carl-mastrangelo** [comment]
Canceled is a valid status code from the server side, so nothing is wrong.   The client was abruptly shutdown, but thats always possible in network conditions.   Instead of killing the client, consider calling shutdown() and awaitTermination on the ManagedChannel.

**Comment by tukez** [comment]
@carl-mastrangelo I don't quite follow your answer. Are you saying that the uncaught exception is expected in the server side when the client is killed? Expected exceptions seems like an oxymoron to me.

> Instead of killing the client, consider calling shutdown() and awaitTermination on the ManagedChannel.
The problems here is that the server can't control the client. I think misbehaving client should not cause exceptions to be thrown on the server side (imo).

**Comment by carl-mastrangelo** [comment]
@tukez I think you are seeing an artifact of the API rather than a bug.  StreamObservers match RxJava Observers, which require that errors be Exceptions.  When the server notices the connection goes away, the server stub finds out by getting an exception sent to the `onError` method.  

If you think that this is not an error, you can choose to ignore.   For example, you can do something like:

```
@Override
public void onError(Throwable t) {
  s = Status.fromThrowable(t):
  if (s.getCode() != Status.Code.CANCELLED) {
    // something actually bad happened.
  }
}
```

**Comment by tukez** [comment]
@carl-mastrangelo Ok, I see what's happening now. The exception is not actually thrown from that stack, it's just created there. Then an actual exception happens on the Reactor side, it's wrapped and thrown. In the end it's unwrapped and given to the thread's uncaught exception handler (even it's not an actually uncaught exception). There is no problem here, at least not on grpc side. Thanks for the help.
