### ISSUE TITLE
Flag to relax compression interop tests

### ISSUE THREAD

**Issue by raboof** [grpc/grpc-java#4240]
As discussed in #3195, since some implementations don't have access to the message compression flags, tests that rely on that cannot be exercised.

Would it be useful to add a flag that disables test steps that rely on this capability?

With such a flag, we could for example run `client_compressed_unary` against the Java server. The first call in that test would be skipped (as that requires the server to be able to inspect the message flags), but determining whether the subsequent calls succeed would still be useful.

**Comment by carl-mastrangelo** [comment]
@raboof if this affects more than java, a change would be needed for all implementations (i.e. grpc and grpc-go)

Does this only affect the grpc java tests?

**Comment by ejona86** [comment]
I think I'd prefer just creating a new test that doesn't do the initial server feature check. Say, `client_compressed_unary_novalidate`

**Comment by ejona86** [comment]
@raboof, feel free to send a PR with the test addition. We can provide guidance for pieces that are unclear.

**Comment by raboof** [comment]
Done in #4279
