### ISSUE TITLE
message Empty is defined twice in interop-testing sub-project

### ISSUE THREAD

**Issue by 2m** [grpc/grpc-java#4241]
Message `Empty` is once defined in the `interop-testing` sub-project itself:

https://github.com/grpc/grpc-java/blob/95917b8f280115bdb946e455151034a2650f48a6/interop-testing/src/main/proto/io/grpc/testing/integration/empty.proto#L22-L30

And then again pulled in from `protobuf-java`

https://github.com/google/protobuf/blob/d6a17aadeb6fc306d3d8c3b5c07edc41f6bc551e/src/google/protobuf/empty.proto#L43-L52

via the dependency chain: `grpc-interop-testing` -> `grpc-protobuf` -> `protobuf-java-util` -> `protobuf-java`

This becomes a problem when generating grpc classes using ScalaPB as it tries to place both under the [same package and the same name](https://github.com/scalapb/ScalaPB/issues/243#issuecomment-279769902).

I would expect `interop-testing` to not define `Empty` message and use the one from  `protobuf-java` instead. Would that be possible to change?

**Comment by carl-mastrangelo** [comment]
This is due to the C api needing its own copy, iirc because Ruby  / JS didn't have the well known types.   I would prefer to use the proper Empty if possible, but it may break when interoperating with C wrapped languages. 

This is my vague recollection of why the correct type isn't used.   Not sure how to change it now, since it would break interop tests.

**Comment by ejona86** [comment]
The empty.proto is broken:

```
package grpc.testing;

option java_package = "com.google.protobuf";
```

It's in the correct protobuf package, but the java package is wrong. It should be in `io.grpc.testing.integration`.

**Comment by jyane** [comment]
@ejona86 Is it means like this? https://github.com/grpc/grpc-java/compare/master...jyane:fix-empty-package

**Comment by ejona86** [comment]
@jyane, yep, exactly like that. Send that as a PR and I'll merge it!

Normally we should always make changes to the "canonical" version first, which would _eventually_ in grpc/grpc-proto. For now, most of the "canonical" versions are in grpc/grpc. But [as we can see](https://github.com/grpc/grpc/blob/v1.10.1-pre1/src/proto/grpc/testing/empty.proto) we've already diverged here.

It would be good to send a PR to grpc/grpc as well to add the `java_package` option, but I won't require it is updated first (which normally I would).

**Comment by jyane** [comment]
> Normally we should always make changes to the "canonical" version first, which would eventually in grpc/grpc-proto. For now, most of the "canonical" versions are in grpc/grpc. But as we can see we've already diverged here.

Using grpc/grpc-proto is quite reasonable for me. It means eventually the chance of resolving #4097.

> It would be good to send a PR to grpc/grpc as well to add the java_package option

I'll do once my PR was merged.
