### ISSUE TITLE
Android Java: Duplicate Zip Entry in Gradle with another library using GRPC in com.google.protobuf

### ISSUE THREAD

**Issue by apollow** [grpc/grpc-java#4263]
### What version of gRPC are you using?
I'm using GRPC version 1.10.0.

### What did you expect to see?
I'm getting an issue with 

`Warning:Exception while processing task java.io.IOException: Can’t write [/Users/apollow/Documents/my-app/app/build/intermediates/transforms/proguard/production/release/0.jar] (Can’t read [/Users/apollow/Documents/my-app/app/build/intermediates/classes/production/release(;;;;;;**.class)] (Can’t read [com] (Can’t read [google] (Can’t read [protobuf] (Can’t read [Any$1.class] (Duplicate zip entry [com/google/protobuf/Any$1.class]))))))`

while compiling release + signed versions as opposed to debug versions.

We are rolling our own GRPC end and we have another library using GRPC:

... config ...
```
    buildTypes {
        debug {
            debuggable true
            jniDebuggable true
            minifyEnabled true
            // heap is disabled for debug to allow for instant run to work
            // will need to enable heap here and disable instant run to test heap
            ext.heap = ["enabled": false]
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            ext.heap = ["enabled": false]
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

... dependencies ...
```
    // GRPC
    compile 'io.grpc:grpc-okhttp:1.10.0'
    // CURRENT_GRPC_VERSION
    compile 'io.grpc:grpc-protobuf-lite:1.10.0'
    // CURRENT_GRPC_VERSION
    compile 'io.grpc:grpc-stub:1.10.0'
    // CURRENT_GRPC_VERSION
    compile 'javax.annotation:javax.annotation-api:1.2'
    // Heap Analytics dependency
    implementation ('com.heapanalytics.android:heap-android-client:0.5.2') {
        exclude group: 'com.google.protobuf', module: 'protobuf-lite'
    }
```

Here's the dependency tree following exclusion of group:

+--- io.grpc:grpc-okhttp:1.10.0
|    +--- io.grpc:grpc-core:[1.10.0] -> 1.10.0
|    |    +--- io.grpc:grpc-context:1.10.0
|    |    +--- com.google.code.gson:gson:2.7 -> 2.8.2
|    |    +--- com.google.guava:guava:19.0 -> 23.4-android (*)
|    |    +--- com.google.errorprone:error_prone_annotations:2.1.2
|    |    +--- com.google.code.findbugs:jsr305:3.0.0 -> 1.3.9
|    |    +--- io.opencensus:opencensus-api:0.11.0
|    |    |    \--- com.google.guava:guava:19.0 -> 23.4-android (*)
|    |    \--- io.opencensus:opencensus-contrib-grpc-metrics:0.11.0
|    |         \--- io.opencensus:opencensus-api:0.11.0 (*)
|    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    \--- com.squareup.okio:okio:1.13.0
+--- io.grpc:grpc-protobuf-lite:1.10.0
|    +--- io.grpc:grpc-core:1.10.0 (*)
|    +--- com.google.protobuf:protobuf-lite:3.0.1
|    \--- com.google.guava:guava:19.0 -> 23.4-android (*)
+--- io.grpc:grpc-stub:1.10.0
|    \--- io.grpc:grpc-core:1.10.0 (*)
+--- com.heapanalytics.android:heap-android-client:0.5.2
+--- javax.annotation:javax.annotation-api:1.2
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

Normally an exclusion of the group would work for the com.google.protobuf, but it doesn't appear to be working.

If you need more snippets of my project, let me know.

#

**Comment by ejona86** [comment]
If you're using lite, then because of google/protobuf#1889 libraries may be manually building and including Any. But if two libraries build the Any then you get a collision. This doesn't seem to involve gRPC.

**Comment by apollow** [comment]
@ejona86 Thanks for the input, we resolved the issue by explicitly putting
implementation 'com.google.protobuf:protobuf-lite:3.0.1' on our end.

**Comment by ejona86** [comment]
Huh. I don't know how that fixed it. But since it seems you found a solution, closing the issue.
