### ISSUE TITLE
Caused by: io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException: Header size exceeded max allowed size (8192)

### ISSUE THREAD

**Issue by JLofgren** [grpc/grpc-java#4284]
### What version of gRPC are you using?
1.10.0

### What did you expect to see?
This error occurs when a Java client attempts to send a header larger than 8192 bytes when connected to a server that did not explicitly specify a SETTINGS_MAX_HEADER_LIST_SIZE in its settings frame.  (Note this cannot be replicated using a grpc-java server because netty always specifies a SETTINGS_MAX_HEADER_LIST_SIZE.)

The expected result is no error - the client should send the large header to the server.

The HTTP/2 spec [Settings section](https://tools.ietf.org/html/rfc7540#section-6.5) says:
1) SETTINGS parameters are not negotiated; **they describe characteristics
   of the sending peer, which are used by the receiving peer.**
2) SETTINGS_MAX_HEADER_LIST_SIZE (0x6):  .... **The initial value of this setting is unlimited.**

These statements indicate that if the server does not specify any SETTINGS_MAX_HEADER_LIST_SIZE, then the client should place no limit on the sending header size. However, netty is enforcing a default max header size on both sent and received headers.  And to boot, there does not seem to be any way to specify or disable the client sender header limit through the grpc-java API.  NettyChannelBuilder has the maxHeaderListSize method, but this only specifies the SETTINGS_MAX_HEADER_LIST_SIZE for the receive path.

I think the proper fix would be for netty to not enforce any limit on client sent header size if the server has not specified a SETTINGS_MAX_HEADER_LIST_SIZE.

I am looking for a long-term fix for this issue and short-term workaround if anyone has an idea. Thanks!

**Comment by ejona86** [comment]
Created netty/netty#7825

**Comment by JLofgren** [comment]
@ejona86 Does anything need to be done to make sure the netty fix will make it into the next java-grpc release?

**Comment by ejona86** [comment]
No, but it may not make the next release. It will make a "soon" gRPC release. Sometimes unrelated problems in the Netty release will prevent us from upgrading.

Something would only need to be done if we were wanting to backport a fix/workaround.

**Comment by ejona86** [comment]
1.13.x upgraded Netty. This should be fixed.
