### ISSUE TITLE
How to implement username/password authentication. Python client, Java server.

### ISSUE THREAD

**Issue by dshylov** [grpc/grpc-java#4296]
I'm trying to figure out how to authenticate with username/password when I create a connection and nothing found. 
So, my questions:
1) How to create a server with username/password authentication on java server?
2) How should python client connect to it?

**Comment by carl-mastrangelo** [comment]
@dshylov it depends on what kind of security you want.   gRPC is request oriented, so your client would have to authenticate every request.   We have out of the box support for Google related OAuth2 tokens using `MoreCallCredentials` though this is not password based like you want.

You probably need to hash the username and password and store it somewhere, and include it with the request.   However, I would suggest doing something like using a JWT, which allows the server to verify the client without passwords ever being sent.   You can send the JWT in the `Metadata`.

The full answer is more complex and depends heavily on what you want to do, so you'll need to figure out what you want exactly first.  I'd also suggest asking in our [public forum](https://groups.google.com/forum/#!forum/grpc-io) where you can get more nuanced answers.

**Comment by ericgribkoff** [comment]
This was also asked and answered on StackOverflow: https://stackoverflow.com/questions/49628137/how-to-implement-grpc-username-password-authentication-python-client-java-serv/49657885#49657885.

Closing for now. @dshylov, feel free to reopen if you have further questions on this topic.
