### ISSUE TITLE
Provide more detailed information on OpenCensus spans

### ISSUE THREAD

**Issue by steveniemitz** [grpc/grpc-java#4312]
I had made some modifications to gRPC that I'm running in a local fork which have been very useful for debugging network issues, performance etc.  I wanted to start a discussion of adding more useful tracing information into gRPC.

Currently the only information provided comes from the ClientCallTracer, which simple marks the start/end of a call, along with message send/recv events.

I've additionally instrumented the netty transport (via `NettyClientStream`) to annotate the send operation span with:
- Header send queued
- Header send complete
- Frame queued
- Frame sent
- Request called
- Headers received
- Trailers received

Specifically the frame queued and frame sent annotations are very helpful for debugging network congestion on the client end.  Would this kind of tracing be useful for others?  I can clean up my code and submit a pull request if so.

**Comment by ericgribkoff** [comment]
cc @zhangkun83 @bogdandrutu

**Comment by zhangkun83** [comment]
cc @ejona86 

@steveniemitz, Did you make the netty transport call OpenCensus directly? We probably don't want to do that. We could, instead, add something like `transportEvent()` on `StreamTracer` for the netty transport to call, and the OpenCensus StreamTracers in gRPC would pass those events on to OpenCensus Spans.

**Comment by steveniemitz** [comment]
Yeah I did.  I was just experimenting around to get something going.  I agree in a real implementation the OpenCensus tracing should be decoupled from the actual transports.
