### ISSUE TITLE
Reconnect wait time? 

### ISSUE THREAD

**Issue by Necropaw** [grpc/grpc-java#4327]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.11.0

### What did you expect to see?
Some way to configure a delay before a reconnect may happen.

### Details

We are currently running our applications in a kubernetes cluster and using services to point to the gRPC server:

`client-pod -> service (IP: 192.168.0.1) -> server-pod (IP: 192.168.0.10)`

When the `server-pod` is terminated, it sends a `GO AWAY` to the client and kubernetes spawns a new pod.

`client-pod -> service (IP: 192.168.0.1) -> server-pod2 (IP: 192.168.0.11)`

If in between the `GO AWAY` and the start of `server-pod2` the client-pod tries to connect, the kubernetes service forwards the request to the old pod (IP: 192.168.0.10) and the client-pod has to wait for a socket timeout around 2min before it can reconnect. 

Do you know of a way to configure the client to wait after a `GO AWAY` before trying to reconnect? The waiting time would be very short (like 5s).

Log: 
[grpc-call.log](https://github.com/grpc/grpc-java/files/1893916/grpc-call.log)

**Comment by zpencer** [comment]
I do see some code related to tuneable reconnection policies in ExponentialBackoffPolicy but unfortunately I can't find any public APIs for configuring this. I'll double check with my team to see if this is the appropriate to expose.

**Comment by ejona86** [comment]
No, we don't allow the backoff policy to be configured. In this case, it seems there's a network black hole, which really should be fixed.

#1943 would help reduce the impact here, as it would limit the initial (failed) reconnect to 20 seconds.

**Comment by Necropaw** [comment]
And this is more a kubernetes issue as an grpc issue: https://github.com/kubernetes/kubernetes/issues/48719
https://github.com/kubernetes/kubernetes/issues/38456

**Comment by ejona86** [comment]
@Necropaw, thanks for the k8s links. We'll take this also as an implicit vote to fix #1943 (as the point of that issue is to avoid huge slowdowns when the network is broken, such as you were experiencing).
