### ISSUE TITLE
Access to TLS client and server certificates

### ISSUE THREAD

**Issue by sebtomba** [grpc/grpc-java#4348]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Newest

### What did you expect to see?

I have a very specific problem. We want to build a GRPC service with mutual TLS. We don't care about (client or server) certificate validation. However, for both client and server we want to have the ability to fetch the others party certificate.
In other words:
a)  If I'm a server I want to learn about the certificate that the client is using when negotiating a TLS connection.
b) If I'm the client I want to learn about the certificate of the server.

We solved the problem from the server side with a `ServerInterceptor` (see example project https://github.com/sebtomba/grpc-example).
We are however struggling on the client side.

## Questions
1. Does the grpc-java API allow to fetch the server certificate?
2. If it doesn't allow, how we would have to modify grpc-java to allow it? We are happy to contribute with a PR :) We just need a little help.
3. How can we disable the certificate verification? (We are using self-signed certificates on both sides)

**Comment by carl-mastrangelo** [comment]
The server can access the client side certs by accessing the ServerCall.getAttributes(), and look for the `TRANSPORT_ATTR_SSL_SESSION` key.   I believe you can do the ClientCall as well, waiting until `onHeaders` as been called.

**Comment by sebtomba** [comment]
Great! I figured it out. This is what I did:
1. Created a `SslSessionClientInterceptor` which implements `ClientInterceptor`
2. Created a `SslSessionClientCallInterceptor` which extends `ClientCall` and is a wrapper for a client call.
3. Created an `InterceptionListener` which implements `ClientCall.Listener` and is a wrapper for a listener
4. `InterceptionListener.onHeaders` has then access to `ClientCall.getAttributes()`
5. `SslSessionClientCallInterceptor.start()` creates an `InterceptionListener`
6. `SslSessionClientInterceptor.interceptCall()` creates a `SslSessionClientCallInterceptor`
7. `NettyChannelBuilder.intercept(new SslSessionClientInterceptor())`

Now:
**How can we disable the certificate verification, both on server and client side?**
Client and server are allowed to use any kind of certificate (f.e. self-signed) and there should be no verification of the cert-chain. We are identifying the peers only by their public key.

**Comment by sebtomba** [comment]
To disable certificate validation you need to set
```
.trustManager(InsecureTrustManagerFactory.INSTANCE)
```

**Comment by carl-mastrangelo** [comment]
@sebtomba You might consider asking these kinds of questions on StackOverflow, where it would be more discoverable.

**Comment by sebtomba** [comment]
@carl-mastrangelo I asked the question here because you described a server-side `SSLSession` interception in your [SECURITY.md](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#mutual-tls). You might consider describing a client-side interception as well there. Or even adding an abstract client interceptor for this particular use case.
