### ISSUE TITLE
Build Failures

### ISSUE THREAD

**Issue by kpk5679** [grpc/grpc-java#4350]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
master DGRPC_VERSION=1.12.0-SNAPSHOT

### What did you expect to see?
Whenever i am building the grpc-java master, i am getting following error.

{code}
* What went wrong:
Execution failed for task ':grpc-compiler:compileJava_pluginExecutableJava_pluginCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling java_generator.h.
      C++ compiler failed while compiling java_plugin.cpp.
      C++ compiler failed while compiling java_generator.cpp.
  See the complete log at: file:///C:/dev/grpc-java-master/compiler/build/tmp/compileJava_pluginExecutableJava_pluginCpp/output.txt
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 50s
71 actionable tasks: 59 executed, 12 up-to-date
{code}

I took trace of the build and gotten following info.

{code}
See file:///C:/Users/prac/Documents/GitHub/grpc-java/compiler/build/tmp/compileJava_pluginExecutableJava_pluginCpp/output.txt for all output for compileJava_pluginExecutableJava_pluginCpp.
compiling java_generator.h failed.
C:\Users\prac\Documents\GitHub\grpc-java\compiler\src\java_plugin\cpp\java_generator.h:8:10: fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory
 #include <google/protobuf/io/zero_copy_stream.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

compiling java_plugin.cpp failed.
In file included from C:\Users\prac\Documents\GitHub\grpc-java\compiler\src\java_plugin\cpp\java_plugin.cpp:8:0:
C:\Users\prac\Documents\GitHub\grpc-java\compiler\src\java_plugin\cpp\java_generator.h:8:10: fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory
 #include <google/protobuf/io/zero_copy_stream.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

compiling java_generator.cpp failed.
In file included from C:\Users\prac\Documents\GitHub\grpc-java\compiler\src\java_plugin\cpp\java_generator.cpp:1:0:
C:\Users\prac\Documents\GitHub\grpc-java\compiler\src\java_plugin\cpp\java_generator.h:8:10: fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory
 #include <google/protobuf/io/zero_copy_stream.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Finished compileJava_pluginExecutableJava_pluginCpp, see full log file:///C:/Users/prac/Documents/GitHub/grpc-java/compiler/build/tmp/compileJava_pluginExecutableJava_pluginCpp/output.txt.

{code}
 

I was expecting google/protobuf artifacts to be included as part of the project.

Am i missing something in this? I am pretty new in this and googling the topic did not get any useful info.

**Comment by ejona86** [comment]
To compile the grpc codegen you need protobuf to be installed with headers available. COMPILING.md talks about how to configure it.

But most users shouldn't need to compile the codegen, even if making changing to gRPC. There are binaries available on Maven Central (referenced from the main README.md) and you can disable codegen compilation if making other changes to grpc-java (referenced in COMPILING.md).

**Comment by kpk5679** [comment]
Well, i was on jdk1.8.0_144 where i was getting errors.

By degrading the version to jdk1.7.0_25 built the code in examples but the root directory it throws 

{code}
ava.lang.UnsupportedClassVersionError: net/ltgt/gradle/errorprone/ErrorPronePlugin : Unsupported major.minor version 52.0
{code}


When i referred following link for the error : https://github.com/google/error-prone/issues/369, it says 

2.0.6 requires users to run JDK 8, but if i am on JDK8 it does not build the project at all.

**Comment by ejona86** [comment]
Are you just trying to try out the examples? If so, check out a release commit (`git checkout v1.11.0`) and there's no need to build the main project.

Day-to-day, we use Java 8 to build the main project. I thought it didn't build with Java 7.

**Comment by ejona86** [comment]
When on Java 8, what error do you get? The protoc error in the initial post shouldn't be impacted by Java 7 vs Java 8 as it is C++ code.

**Comment by ejona86** [comment]
Closing due to no response. @kpk5679, feel free to comment and we can reopen.
