### ISSUE TITLE
AbstractManagedChannelImplBuilder#executorPool set, but never used

### ISSUE THREAD

**Issue by jpitz** [grpc/grpc-java#4367]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.11.0

### What did you expect to see?
I specified a custom executor, but noticed no changes on the client. After starting to investigated, I noticed that the executor that is set with executor() is never used in the AbstractManagedChannelImplBuilder#build method. Instead, it grabs the shared pool and uses that instead.

Snippet from source:
```
  @Override
  public ManagedChannel build() {
    return new ManagedChannelOrphanWrapper(new ManagedChannelImpl(
        this,
        buildTransportFactory(),
        // TODO(carl-mastrangelo): Allow clients to pass this in
        new ExponentialBackoffPolicy.Provider(),
        SharedResourcePool.forResource(GrpcUtil.SHARED_CHANNEL_EXECUTOR),
        GrpcUtil.STOPWATCH_SUPPLIER,
        getEffectiveInterceptors(),
        CallTracer.getDefaultFactory()));
  }
```

**Comment by ejona86** [comment]
This was discussed some in #4368, but the short of it is the executor you pass to the builder is used: https://github.com/grpc/grpc-java/blob/v1.11.0/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L528

This usage of SHARED_CHANNEL_EXECUTOR is on purpose, although we have slowly been trying to figure out ways to avoid the hard-coded executors while also not exposing too much of our internals.
