### ISSUE TITLE
follow up changes of opencensus

### ISSUE THREAD

**Issue by jyane** [grpc/grpc-java#4381]
[MonitoringService](https://github.com/grpc/grpc-java/blob/a47266ea4ac380f0b4c50c8f7ca1f1f53d3edb00/services/src/main/java/io/grpc/services/MonitoringService.java) seems to be outdated because `com.google.instrumentation` was already changed to `io.opencensus.instrumentation`.
`com.google.instrumentation` is still defined at [build.gradle](https://github.com/grpc/grpc-java/blob/a47266ea4ac380f0b4c50c8f7ca1f1f53d3edb00/build.gradle#L206) so it was not failed on compilation time.

Was it not updated on this PR?
ref: https://github.com/grpc/grpc-java/pull/3204

**Comment by ejona86** [comment]
Hmm... I don't know. I do know there were separate parts for tracing and stats.

@bogdandrutu, do you know if these should have been updated? @zhangkun83 is OOO for a while.
