### ISSUE TITLE
Examples dont work when updating the example WORKSAPCE file to released versions

### ISSUE THREAD

**Issue by mtaliaf** [grpc/grpc-java#4438]
I ran into this when building a simple bazel/grpc app but have verified that I run into the same issue in the provided examples.  If you update the WORKSPACE file in examples/ to use 

```
git_repository(
    name = "io_grpc_grpc_java",
    remote = "https://github.com/grpc/grpc-java.git",
    tag = "v1.11.0",
)
```
as opposed to 
```
local_repository(
    name = "io_grpc_grpc_java",
    path = "..",
)
```
you get errors like this
`ERROR: /Users/mtaliaf/workspace/grpc-java/examples/BUILD.bazel:31:1: no such package 'protobuf': BUILD file not found on package path and referenced by '//:hello_streaming_java_grpc'
`
What is the proper way to reference grpc-java in our workspace file?

### What version of gRPC are you using?
v1.11.0

### What did you expect to see?
bazel clean --expunge && bazel build //examples/...
This command to build the examples.

**Comment by mtaliaf** [comment]
FWIW this seems to be a regression in 1.11.0, if I downgrade to 1.10.0 and update the references to io_grpc_grpc_java -> grpc_java everything seems to work.

**Comment by carl-mastrangelo** [comment]
I _think_ this may be working as intended, even though its wrong.  There is a comment saying the tag needs to be set for released versions:

https://github.com/grpc/grpc-java/blob/master/examples/WORKSPACE#L4

@cgrushko ideas?

**Comment by cgrushko** [comment]
From `git_repository`'s doc [1]:

    Warning: this rule has several limitations. We recommend using http_archive instead for more robust and secure performance.

First thing I'd try is to use

```
http_archive(
    name = "io_grpc_grpc_java",
    # sha256 = "update",
    strip_prefix = "grpc-java-1.11.0",
    urls = [
        "https://github.com/grpc/grpc-java/archive/v1.11.0.zip",
    ],
)
```

My guess is that `git_repository` doesn't place the downloaded git repo in the right directory, or completely fails to download it because of a tag mismatch. 

[1] - https://docs.bazel.build/versions/master/be/workspace.html#git_repository

**Comment by mtaliaf** [comment]
Ah it was fixed with https://github.com/grpc/grpc-java/commit/ef030abe6b82a9b861f27818bb7b5bde9f457261

Where yall planning on doing a patch release with this commit or should I just wait for 1.12?

**Comment by carl-mastrangelo** [comment]
@mtaliaf I believe 1.12 was released earlier this week, can you use that instead?

**Comment by mtaliaf** [comment]
SGTM
