### ISSUE TITLE
ManagedChannelBuilder.maxInboundMessageSize(int max) is still ExperimentalApi.

### ISSUE THREAD

**Issue by doubleknd26** [grpc/grpc-java#4451]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
- Currently, we used version 1.0.3
- We have a plan to change version 1.10.0

### What did you expect to see?
Depending on it (https://github.com/grpc/grpc-java/issues/2307), I tried to use NettyChannelBuilder to adjust maxMessageSize in version 1.0.3.
But NettyChannelBuilder.maxMessageSize is @ExperimentalApi.

So, I tried to use version 1.10.0 depending on https://github.com/grpc/grpc-java/pull/2382
In version 1.10.0, we can use ManagedChannelBuilder.maxInboundMessageSize(int max), but It also @ExperimentalApi.

It's really hard to use experimentalApi in real service.
So, Could you please confirm it?
I hope we can use ManagedChannelBuilder.maxInboundMessageSize as a non experimentalAPI ASAP.

Best regards,

**Comment by carl-mastrangelo** [comment]
The method you would like was made standard about 2 weeks ago in https://github.com/grpc/grpc-java/pull/4399

It should be stable as of the recent 1.12.0 release.
