### ISSUE TITLE
grpc-java-api-checker complains about imports of @ExperimentalApi

### ISSUE THREAD

**Issue by bubenheimer** [grpc/grpc-java#4456]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.11.0
grpc-java-api-checker 1.1.0

### What did you expect to see?
Don't flag imports of `@ExperimentalApi` types. I don't see a way to disable that kind of check:

    > Task :grpcservice:compileJava
    MyClass.java:16: error: [GrpcExperimentalApi] @ExperimentalApi should not be used in application code
    import io.grpc.stub.ServerCallStreamObserver;
                       ^
        (see "https://github.com/grpc/grpc-java/issues/1788")

**Comment by carl-mastrangelo** [comment]
cc: @jyane @ericgribkoff

**Comment by bubenheimer** [comment]
I guess checking for `@Internal` makes the most sense in application code at this time.

grpc-java is not the only thing I'm using errorprone for. For a workaround I was hoping to just use

    -Xep:GrpcExperimentalApi:OFF

but that does not work.

**Comment by ericgribkoff** [comment]
`-Xep:GrpcExperimentalApi:OFF` works for me as part of build.gradle's `options.compilerArgs`. Could you post a repro for generating that InvalidCommandLineOptionException error?

**Comment by bubenheimer** [comment]
Sorry, my bad, that command-line option does work. I have a complex multi-module errorprone setup, as errorprone is flaky for Android builds.

**Comment by ericgribkoff** [comment]
Glad that worked. Re your earlier comment: 

> I guess checking for @Internal makes the most sense in application code at this time.

Correct. The primary intended use for grpc-java-api-checker is for libraries depending on gRPC, with a secondary use case of applications that want to avoid using our internal APIs as well: there's a bit of a blurb about this at the end of our [README](https://github.com/grpc/grpc-java#tools).

**Comment by jyane** [comment]
@ericgribkoff Thanks!
