### ISSUE TITLE
Could not find any version that matches io.grpc:grpc-core:[1.12.0]

### ISSUE THREAD

**Issue by mmoehring** [grpc/grpc-java#4460]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.12.0

### What did you expect to see?
A successful build when switching from 1.11 to 1.12.

Using gradle 3.5.1 with the java-library plugin.
When switching from version 1.11 to to 1.12 build fails at the task "extractIncludeProto" with message

    > Could not find any version that matches io.grpc:grpc-core:[1.12.0].
     ...
      Required by:
          project : > io.grpc:grpc-netty:1.12.0

The library grpc-core does get pulled in but somehow not recognized. Adding an explicit implementation/dependency to grpc-core makes the build work again.

**Comment by carl-mastrangelo** [comment]
@mmoehring Are you using jcenter?

**Comment by mmoehring** [comment]
Yes, indeed. And switching to maven central solves the problem.
According to the Bintray marketing, "Bintray is already a super-set of Maven Central" ;-),
so what did I miss?

**Comment by carl-mastrangelo** [comment]
Not sure, there was a similar issue that came up last week: https://github.com/grpc/grpc-java/issues/3787   I'm not really sure how to search jcenter (like you can search maven central), so I can't tell what versions it does have.

**Comment by mmoehring** [comment]
Yeah, the search ui is a challenge but as far as I can version 1.12 seems to be complete. Examples:

web ui:
https://bintray.com/bintray/jcenter/io.grpc%3Agrpc-netty
https://bintray.com/bintray/jcenter/io.grpc%3Agrpc-core
... etc ...

alternative:
https://jcenter.bintray.com/io/grpc/

**Comment by ericgribkoff** [comment]
#4490 adds checking the JCenter repos as part of our release process. JCenter should (and does, eventually) mirror our packages from Maven Central. If there continue to be issues with delays, we can try to reach out to bintray to see if there's any way we can speed up or initiate the sync process when we do a new release.

**Comment by ericgribkoff** [comment]
Closing this for now. Feel free to re-open if additional delays with packages on JCenter become a problem.
