### ISSUE TITLE
Netty ObjectCleanerThread keeps high CPU

### ISSUE THREAD

**Issue by thermosym** [grpc/grpc-java#4495]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.11.0

### What did you expect to see?
One Netty thread keeps high CPU usage. The following is highest CPU usage related jstack info

"ObjectCleanerThread" #28 daemon prio=1 os_prio=0 tid=0x00007f19c6fb1800 nid=0x1a4e runnable [0x00007f193219d000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.util.Recycler$WeakOrderQueue$Head.run(Recycler.java:264)
        at io.netty.util.internal.ObjectCleaner$AutomaticCleanerReference.cleanup(ObjectCleaner.java:143)
        at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:62)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by carl-mastrangelo** [comment]
@thermosym Approximately how many RPCs per second are you handling?  Also, are you using OpenJDK?

**Comment by thermosym** [comment]
@carl-mastrangelo Actually the load is not high, approximately 10 rpc/s. I'm using Oracle JDK 1.8.0_161

**Comment by carl-mastrangelo** [comment]
That's unusual, Are you running with any custom recycler flags?  Like `io.netty.recycler.maxCapacityPerThread` or `io.netty.recycler.maxSharedCapacityFactor` ?  

Also, there was a change in netty to make the recycler use a dedicated cleaner thread, but I don't recall which version of Netty it was in.  (1.11.0 uses Netty 4.1.22).   
@normanmaurer  would have a better idea of what debugging info would be needed to solve this.

**Comment by normanmaurer** [comment]
@carl-mastrangelo this may be related to https://github.com/netty/netty/commit/3ec29455af9642f6b20d7a309d3b6fb19c49b819 which is included since 4.1.24.Final ?

**Comment by carl-mastrangelo** [comment]
@normanmaurer That may be it.  We are still on 4.1.22 on our current release.  I can bump us to 4.1.25, In the mean time, @thermosym can you use gRPC 1.10.0 ?

**Comment by normanmaurer** [comment]
@carl-mastrangelo this looks more like netty 4.1.23.Final which has the bug I mentioned before:

https://github.com/netty/netty/blob/netty-4.1.23.Final/common/src/main/java/io/netty/util/Recycler.java#L264

**Comment by carl-mastrangelo** [comment]
@normanmaurer thanks for the input.  I bumped to 4.1.25
