### ISSUE TITLE
unfair thread pool allocation for stream clients

### ISSUE THREAD

**Issue by wjackson** [grpc/grpc-java#4516]
### What version of gRPC are you using?

Server: Java: 1.12.0
Client: Python: 1.12.0

### What did you expect to see?

Fair sharing of the server's thread pool among clients.

### Description

I have a service that can be modeled like this:

```
service Pinger {
    rpc Ping(stream PingRequest) returns (stream PingResponse) {} 
}

message PingRequest {
    int work_millis = 1; // simulate work by sleeping for this many millis
}

message PingResponse {
}
```

Each individual client uses a a single RPC to ping infinitely and process responses as they arrive. I was surprised to find that thread pool resources don't seem to be shared fairly among clients in this situation.

Here's the experiment I ran:

#### Server

- Java
- gRPC version: 1.12.0
- Executor with 1 thread

#### Clients

- Python
- grpcio==1.12.0
- count: 2 (1 per process)
- 1 rpc per client
- work_millis = 1000
- Send PingRequests as fast as possible without waiting for replies (flow control kicks in right away)
- Print on response

The first client gets a steady stream of responses (1 per second) and the 2nd client never gets a response.

Is that the expected behavior?

I explored this a bit further using a `ServerInterceptor`. I found that the first client dominates the executor's task queue with many more calls to `onMessage()` than I would expect given the docs for `ServerCall.request`:

> Requests up to the given number of messages from the call to be delivered to ServerCall.Listener.onMessage(Object). Once numMessages have been delivered no further request messages will be delivered until more messages are requested by calling this method again.

https://grpc.io/grpc-java/javadoc/io/grpc/ServerCall.html#request-int-

That's not what I observe though. Instead I see two calls to `ServerCall.Listener.onMessage` for every one `ServerCall.request(1)`.

If I delay the extra `onMessage()` in my interceptor such that only one `onMessage()` per `ServerCall` at a time is given to the executor, then I get the client behavior I originally expected: both clients see responses in a round-robin way.

I can use my `ServerInterceptor` to get the behavior I want but I'm nervous about deviating from the standard behavior. Also, maybe this a bug that needs to be reported?

Any advise or info is appreciated.

**Comment by carl-mastrangelo** [comment]
Can you give a snippet of your Service implementation?

**Comment by wjackson** [comment]
I put together example code and couldn't reproduce the problem. That led me to realize the project with the problem has a server interceptor it uses for tracing. Its request() implementation has a bug where it makes two calls to super.request() instead of one. So nothing to see here. False alarm.
