### ISSUE TITLE
Use property instead of static FQCN for ContextStorageOverride

### ISSUE THREAD

**Issue by drx777** [grpc/grpc-java#4543]
Is there a reason, why you don't use a property which can be set to identify the overriding class for `Context.Storage`? As it is one is required to create a class in package io.grpc.override in one's own package. This may even cause unresolvable collisions if multiple overrides were to be used.

see: https://github.com/grpc/grpc-java/blob/8f51c2731929ac104706f3f33f689c1cc2e4cd8d/context/src/main/java/io/grpc/Context.java#L137

Could this be something like (would be BC):

    Class<?> clazz = Class.forName(
      System.getProperty("grpcContextStorageOverride", "io.grpc.override.ContextStorageOverride"));

So I can do

    System.setProperty("grpcContextStorageOverride", "my.project.module.ContextStorageOverride");

Or am I missing something here?

**Comment by carl-mastrangelo** [comment]
System properties are JVM scoped, while classes are classloader scoped.   If running gRPC in servlets, they would all have to share the same system property.
