### ISSUE TITLE
High latency establishing new connection and sending first request

### ISSUE THREAD

**Issue by nkrode** [grpc/grpc-java#4559]
I'm seeing extremely high latency establishing new connection and sending in the first request (simple ping/pong). It's taking ~ 80 ms to just do the initial handshake,HTTP2 settings exchange etc. 

Here's a Wireshark capture of the packets between a grpc client and server running on the same host and you can see the actual RPC request is made ~ 100ms. 

![image](https://user-images.githubusercontent.com/2081311/41279724-1c316f4a-6de2-11e8-85a9-018c14042222.png)

Not sure If I have something misconfigured, just wanted to confirm if this is normal?

### What version of gRPC are you using?
1.12.0

**Comment by carl-mastrangelo** [comment]
Is it possible that you are measuring the Java running in interpretted mode?  Usually the JIT doesn't kick in for this stuff until it has been under load for some time.

**Comment by nkrode** [comment]
No, I tested after warming up the server and client with close to 500k iterations over 10 mins period. 

Ignoring the latency, currently I'm curious if wireshark capture shows redundant packets being exchanged? Is it normal to exchange WINDOW_UPDATE and SETTINGS 2-3 times between the server and client before the RPC request is made?

**Comment by nkrode** [comment]
👍 closing

**Comment by nkrode** [comment]
I tested this with HelloWorld Server and client from examples. Looks the same, takes about 68ms to issue the RPC call, admittedly I didn't warm up the code, no JIT kicking in, even then a 68ms handshake time to establish a connection on cold start seems excessively high, don't you think?

<img width="1863" alt="image" src="https://user-images.githubusercontent.com/2081311/41310039-337329ac-6e35-11e8-88ab-17ac6b9f09da.png">

**Comment by carl-mastrangelo** [comment]
I don't think so.  The class loading and initialization requires disk access time, syscalls, etc. You might consider running `strace` on your binary to see when exactly the reads and writes are being fired.  You can also use the `perf` tool to measure things like page faults and cycle counters.  Honestly I don't think wireshark is the ideal tool to diagnose this.

**Comment by nkrode** [comment]
Sounds good, will try those.
