### ISSUE TITLE
ManagedChannelBuilder does not expose NettyChannelBuilder.maxHeaderListSize()

### ISSUE THREAD

**Issue by hzyi-google** [grpc/grpc-java#4563]
Please answer these questions before submitting your issue.

### What version of gRPC are you using? 
master

### What did you expect to see?
Is there a reason that this method is not exposed? Or, if I want to restrict the `MAX_HEADER_LIST_SIZE`, is there a way to configure that through `ManagedChannelBuilder` or anywhere else?

**Comment by dapengzhang0** [comment]
Want to send us a PR to add it and implement OkHttpChannelBuilder?

**Comment by hzyi-google** [comment]
Sure, I would be glad to prepare a PR.

**Comment by ejona86** [comment]
This is a duplicate of #4050. We'd still be happy to receive a PR.
