### ISSUE TITLE
How to count  number  of active connection  in grpc?

### ISSUE THREAD

**Issue by zoat** [grpc/grpc-java#4573]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
   <groupId>io.grpc</groupId>
            <artifactId>grpc-netty</artifactId>
            <version>1.12.0</version>

	Server server = ServerBuilder
				.forPort(2000)
				.addService(new TServiceImpl()).build();

### What did you expect to see?
I want o be able to know in  my TServiceImpl  the number of  active  connection

**Comment by carl-mastrangelo** [comment]
@zoat You can count them using a `ServerTransportFilter`.    

In the future, would you mind asking questions on StackOverflow so that the answers are more widely visible?  Thanks!

**Comment by zoat** [comment]
Ok thankc
