### ISSUE TITLE
Abnormal asc files in v1.12.0 artifacts in maven central

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#4574]
We noticed some anomaly of io.grpc v1.12.0 artifacts uploaded to maven repo

1) Some asc files like https://repo.maven.apache.org/maven2/io/grpc/grpc-okhttp/maven-metadata.xml.asc were added in 2018-05-07, and they are in binary format instead of text.  (ASC files should normally be text files)

2) Some asc files in the '1.12.0' directory like https://repo.maven.apache.org/maven2/io/grpc/grpc-okhttp/1.12.0/grpc-okhttp-1.12.0-javadoc.jar.asc are in binary format. But in other version directories like https://repo.maven.apache.org/maven2/io/grpc/grpc-okhttp/1.11.0/grpc-okhttp-1.11.0-javadoc.jar.asc, these files are in text format.

This might be the reason that io.grpc v1.13.0 artifacts were failed to be uploaded to maven central.
[screenshot](https://drive.google.com/open?id=1_kcIk40MPB-hx0otkTgIZLBt_OPpHUIf)

**Comment by ejona86** [comment]
So we think (1) is causing the release to fail. Normally, those asc files should not exist for maven-metadata.xml, as we don't generate that (or rather, it is modified by ossrh to list all the versions available). OSSRH has rules to prevent modifying .asc files, for security. Things "worked fine" for v1.12.0, except now we've got these trash asc files that can't be cleaned up and can't be replaced.

I think we'll need to avoid signing the maven-metadata.xml for the 1.13.0 to advance.

Note that fixing (2) can maybe be delayed. The signatures are valid although they should really be in ascii form, as that's what the .asc extension stands for.

When verifying signatures currently on maven central:
```
$ gpg -v --verify maven-metadata.xml.asc 
gpg: assuming signed data in 'maven-metadata.xml'
gpg: Signature made Mon 07 May 2018 02:57:03 PM PDT
gpg:                using RSA key D9C565AA72BA2FDD
gpg: using pgp trust model
gpg: BAD signature from "grpc-java-team-sonatype <grpc-java-team-sonatype@google.com>" [unknown]

$ gpg -v --verify grpc-core-1.12.0.pom.asc 
gpg: assuming signed data in 'grpc-core-1.12.0.pom'
gpg: Signature made Mon 07 May 2018 02:57:06 PM PDT
gpg:                using RSA key D9C565AA72BA2FDD
gpg: using pgp trust model
gpg: Good signature from "grpc-java-team-sonatype <grpc-java-team-sonatype@google.com>" [unknown]
```

I'm thinking we should change the release script to use these additional params to find: `-not -name maven-metadata.xml -not -name "*.sha1" -not -name "*.md5"`

**Comment by ejona86** [comment]
To solve (2), we just need to pass `-a` to gpg

**Comment by ejona86** [comment]
Passing `-a` fixes the file extension and means we don't need to pass `-o {}.asc` (without -a it defaults to .sig, as is appropriate).
