### ISSUE TITLE
java server:Stream 3 sent too many headers EOS: false

### ISSUE THREAD

**Issue by linjson** [grpc/grpc-java#4581]
error:
java.lang.IllegalStateException: Stream 3 sent too many headers EOS: false

### What version of gRPC are you using?
grpc version:1.12.0
### What did you expect to see?
StreamObserver can send message at the same time in the threadPool
### My code
how do i modify this code
```java
ExecutorService executor = new ThreadPoolExecutor(
            3, 10, 300, TimeUnit.SECONDS,
            new LinkedBlockingQueue<Runnable>());
//this method happen 3 times at the same time
private void send(){
	executor.submit(new Runnable() {
	    @Override
	    public void run() {
	        HelloReply reply = HelloReply.newBuilder().setMessage("send").build();
	        responseObserver.onNext(reply);
	      
	    }
	});
}


```

**Comment by dapengzhang0** [comment]
You should not call `onNext()` concurrently with the same `responseObserver`. Here's part of the javadoc of [`StreamObserver`](https://grpc.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html):
```
Since individual `StreamObserver`s are not thread-safe, if multiple threads will be
writing to a ` StreamObserver` concurrently, the application must synchronize calls.
```

**Comment by linjson** [comment]
Thank you
