### ISSUE TITLE
Remove extraneous maven-metadata.xml*.asc files in maven repo

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#4583]
We closed #4574, but in maven repo, there are still some maven-metadata.xml*.asc files, which are not in ascii format and should be removed.

**Comment by ejona86** [comment]
@dapengzhang0, we can't delete the asc files from Maven Central. This seems infeasible. How did you imagine this could be done?

**Comment by dapengzhang0** [comment]
I have no idea. Seems not possible.
