### ISSUE TITLE
Plumb lb contextual info to transport creation

### ISSUE THREAD

**Issue by zpencer** [grpc/grpc-java#4590]
For channels that use ALTS and grpclb, there are several connection types:
* connecting to a grpclb service with an oob channel: use ALTS
* connecting to an address returned by grpclb: use ALTS
* connecting to an address returned by the initial DNS query: use TLS

ALTS relies on the connection type to determine which type of negotiation to use. This info needs to be plumbed to the ProtocolNegotiator.

cc @jiangtaoli2016 @ejona86

**Comment by ejona86** [comment]
This will be resolved by #4603, #4617, and #4619

**Comment by jiangtaoli2016** [comment]
This is awesome. Thanks @ejona86 !
