### ISSUE TITLE
your REDME demo is error

### ISSUE THREAD

**Issue by WilliamShoww** [grpc/grpc-java#4610]
I want to try use this tools by MVN. So I use your REDME demo but my MVN can't find 
 `<dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>1.13.1</version>
     </dependency>`
and
`
<groupId>org.xolstice.maven.plugins</groupId>
 <artifactId>protobuf-maven-plugin</artifactId>
 <version>0.5.1</version>
`
I don't known which version  plugin match which version protobuf.
My protobuf version is 2.5

**Comment by zpencer** [comment]
I checked out the tag release `v1.13.1` and was able to run `mvn clean compile`. The dependencies were downloaded from maven.org and the examples built fine. Can you double check your maven configuration?

Verified packages exist on maven.org :
[grpc-protobuf 1.13.1](http://search.maven.org/#artifactdetails%7Cio.grpc%7Cgrpc-protobuf%7C1.13.1%7Cjar)
[protobuf-maven-plugin 0.5.1](http://search.maven.org/#artifactdetails%7Corg.xolstice.maven.plugins%7Cprotobuf-maven-plugin%7C0.5.1%7Cmaven-plugin)

**Comment by ejona86** [comment]
No response, so closing. @WilliamShoww, if things are still broken for you, you can reply back on this issue.
