### ISSUE TITLE
Decide whether gRPC will use options in proto for methods

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#462]
It would be possible to attach options, such as compression and default timeout, to methods. @a11r was thinking that we wouldn't have such options, but @louiscryan had been thinking we would. It doesn't seem we feel too strongly one way or the other, but we just need to get consensus and move forward.

**Comment by zhangkun83** [comment]
@a11r, @louiscryan and me talked today, and agreed that we would not have options in protos at all. For now we will have APIs to set the options (mainly timeout). For the future there will be a need for a service config delivery mechanism that delivers options from service providers to the client, while that mechanism won't be proto files.

**Comment by wrwg** [comment]
Delivering config options exclusively via a service provider is restricting
what we could do with such options, because it only works at runtime, not
at compile time. It seems to me a bit unusual with an approach which is
otherwise so heavily based on static metadata and compilation.

I think a better model would be having static options in protos with the
potential for having some of them being overridden by runtime config
discovery. The principle would be that every option available a runtime can
also be set statically in the proto (but not necessarily the other way
around).

Such a model could be mostly hidden from the grpc runtime. There would be
the abstract concept of a config provider in a given call context, and from
where it obtains its data is opaque.


-- 
*W*olf*g*an*g*

**Comment by zhangkun83** [comment]
I am not convinced that the proto should be the primary place for options. Most options are not as static as method signatures. For example, window size is most likely to be decided by the service provider. There can be multiple providers for the same service, with different window sizes. Another example is timeout, which is either decided by the client and can vary from call to call, or decided by the service provider by an expectation based on the actual implementation.

**Comment by wrwg** [comment]
I've not said that proto should be primary source for options. I've said it
should not be excluded to be such a source, referring to what you wrote
before: "[we] agreed that we would not have options in protos at all. "



-- 
*W*olf*g*an*g*

**Comment by zhangkun83** [comment]
>The principle would be that every option available a runtime can
also be set statically in the proto (but not necessarily the other way
around).

You are suggesting proto should have the *complete* set of options, while other places (like runtime) do not necessarily do. That's what I meant by proto being the primary source. My point is that most options are not as static as other stuff in the proto, e.g., method signatures, so what would we gain by putting options in the proto if they are likely to be altered at runtime?

**Comment by wrwg** [comment]
Static metadata should be the primary source of declaring what options are
available and what are their defaults. In proto-based APIs that would
naturally be proto, but it doesn't has to be.  This is independent of
whether the options are set at runtime or not. There needs to be a place
where this is declared in a language-independent fashion.

As it comes to what is set at runtime and what not, I think you are making
the power-user scenario the primary one, which may have negative impact on
usability. Most cases will just work fine with defaults as defined by an
API provider, as experience at Google with stubby shows. We should support
overriding such defaults, but don't force everybody into the more complex
solution of a runtime configuration.

There are also cases where I think it is questionable that runtime
configuration is even desired. Let's take auth requirements. I have a hard
time to imagine a client which has to dynamically adopt to auth
requirements being a good developer experience. Rather, I would like to
have the auth requirements formulated in static metadata (and in
documentation), so I can set up everything ahead of time, and have compile
time tools helping me with it.

-- 
*W*olf*g*an*g*

**Comment by ejona86** [comment]
@louiscryan, can you share the status of this decision?

**Comment by louiscryan** [comment]
We have chosen not to implement option pre-configuration from proto
compilation for the moment. We do not have the tooling in place to do this
nor do we have sufficiently strong use-cases to warrant the work at the
moment. We have been careful to design the runtime configuration API to
allow for defaults to be provided by codegen when and if we decide to add
support in the compiler.
