### ISSUE TITLE
ManagedChannel.getState() throwing a N

### ISSUE THREAD

**Issue by jeffgaer** [grpc/grpc-java#4624]
Please answer these questions before submitting your issue.

**Comment by jeffgaer** [comment]
trying to call shutdown on a ManagedChannel but getting an exception. Stack trace shown below
2018-07-09 11:20:14,325 DEBUG [com.ticomgeo.ftc.client.FTCClient] (EE-ManagedExecutorService-singleThreaded-Thread-1) exception in disconnect Not implemented: java.lang.UnsupportedOperationException: Not implemented
        at io.grpc.ManagedChannel.getState(ManagedChannel.java:87)
        at com.ticomgeo.ftc.client.FTCClient._disconnect(FTCClient.java:173)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)

The code causing the exception is shown below:

 LOG.debug("==============RETURN FROM SHUTTING DOWN MANAGED CHANNEL" + channel.getState(false));

De-compiling the class with intellij it looks like the exception coded into the class

import java.util.concurrent.TimeUnit;

public abstract class ManagedChannel extends Channel {
    public ManagedChannel() {
    }

    public abstract ManagedChannel shutdown();
    public abstract boolean isShutdown();
    public abstract boolean isTerminated();
    public abstract ManagedChannel shutdownNow();
    public abstract boolean awaitTermination(long var1, TimeUnit var3) throws InterruptedException;
    public ConnectivityState getState(boolean requestConnection) {
        throw new UnsupportedOperationException("Not implemented");
    }
    public void notifyWhenStateChanged(ConnectivityState source, Runnable callback) {
        throw new UnsupportedOperationException("Not implemented");
    }
}

I am getting the instance of  the ManagedChannel as follows:

 channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build();

**Comment by dapengzhang0** [comment]
@jeffgaer Is it calling `getState()` explicitly `at com.ticomgeo.ftc.client.FTCClient._disconnect(FTCClient.java:173)`? 

`ManagedChannelImpl.getState(boolean)` is not implemented until v1.6.1. So it is expected to throw `UnsupportedOperationException: Not implemented ` in v1.1.2

**Comment by jeffgaer** [comment]
Yes, I was calling it explicitly. I was confused by the documentation, it says available since 1.1.0, but I guess that just means the method exists, not that it is implemented. 
   
   -    
getState
   @ExperimentalApi(value="https://github.com/grpc/grpc-java/issues/4359")
public ConnectivityState getState(boolean requestConnection)Gets the current connectivity state. Note the result may soon become outdated.      
      - Parameters:
         - requestConnection - if true, the channel will try to make a connection if it is currently IDLE
      - Throws:
         - UnsupportedOperationException - if not supported by implementation
      - Since:
         - 1.1.0

 

    On Monday, July 9, 2018, 2:50:19 PM CDT, ZHANG Dapeng <notifications@github.com> wrote:  
 
 
@jeffgaer Is it calling getState() explicitly at com.ticomgeo.ftc.client.FTCClient._disconnect(FTCClient.java:173)?

ManagedChannelImpl.getState(boolean) is not implemented until v1.6.1. So it is expected to throw UnsupportedOperationException: Not implemented in v1.1.2

**Comment by carl-mastrangelo** [comment]
@jeffgaer ManagedChannel is an abstract class, so we can't say when subclasses implement it.
