### ISSUE TITLE
Conflig between netty-transport-native-epoll and netty-tcnative-boringssl-static

### ISSUE THREAD

**Issue by thuannt-uit** [grpc/grpc-java#4634]
Hi all,

I am doing service as connector using `grpc 1.13.1` with the following roles:
- Handle requests from apps (as server side)
- Categorize requests, after that forwarding through other services (as client side).

Between the connector that calls the other services through the domain gateway, nginx uses ssl

The problem encountered conflict when:
- Server side uses lib:
```maven
       <dependency>
            <groupId> io.netty </ groupId>
            <artifactId> netty-transport-native-epoll </ artifactId>
            <version> 4.1.17.Final </ version>
            <classifier> linux-x86_64 </ classifier>
       </ dependency>
```
- Client side uses ssl lib
```maven
        <dependency>
            <groupId> io.netty </ groupId>
            <artifactId> netty-tcnative-boringssl-static </ artifactId>
            <version> 2.0.7.Final </ version>
        </ dependency>
```
and the error is  
```java
code = UNAVAILABLE ', description = Channel closed while performing the negotiation protocol
```
How do I fix the error described above
Thanks

**Comment by ejona86** [comment]
grpc 1.13 should use netty-tcnative-boringssl-static version 2.0.8.Final and netty-transport-native-epoll 4.1.25.Final. See the table at https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty

**Comment by thuannt-uit** [comment]
I try to use as you comment, grpc 1.13 use netty-tcnative-boringssl-static version 2.0.8.Final or later and netty-tcnative-boringssl-static version 2.0.8.Final or later also work well. 

Now, i use netty-tcnative-boringssl-static version 2.0.12.Final and netty-transport-native-epoll 4.1.26.Final for my service. 

Thanks
