### ISSUE TITLE
getExtension can get values in android

### ISSUE THREAD

**Issue by kiddot** [grpc/grpc-java#4640]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.13.1
### What did you expect to see?
rspPacket.getExtension(RoomsvrCommmsg.cMDCREATEROOMRSP); the server had sent, but i can not get the values. can anyone help me? I use in android! (use golang as server)

**Comment by carl-mastrangelo** [comment]
You probably need to use `ProtoLiteUtils.setExtensionRegistry`

**Comment by kiddot** [comment]
ExtensionRegistryLite extensionRegistryLite = ExtensionRegistryLite.newInstance();
RoomsvrCommmsg.registerAllExtensions(extensionRegistryLite);
ProtoLiteUtils.setExtensionRegistry(extensionRegistryLite);

@carl-mastrangelo  the code is right? thanks!

**Comment by kiddot** [comment]
@carl-mastrangelo can you give the example of extension ? thanks

**Comment by carl-mastrangelo** [comment]
@kiddot Yup, that's right.
