### ISSUE TITLE
Please update tests w.r.t new releases

### ISSUE THREAD

**Issue by chaitanya9186** [grpc/grpc-java#4648]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.13.2

### What did you expect to see?
The tests are not up-to date. 

For E.g.
InProcessChannelBuilder.forName(serverName).directExecutor().build() will not be compiling.

**Comment by zhangkun83** [comment]
Could you provide steps to reproduce the issue and paste the error message here?

**Comment by ejona86** [comment]
We run the examples/tests continually as we make changes. Everything seems to work. Without error message or more details there's not more we can do.

@chaitanya9186, if you provide more information we can re-open this issue.
