### ISSUE TITLE
Netty for Header to deal with

### ISSUE THREAD

**Issue by christ258** [grpc/grpc-java#4678]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.12.0

### What did you expect to see?
Problem solving

Hi，I am using GRPC with Netty. Now I want to process the Header passed by the client side, in the HeaderServerInterceptor. But this Header, which I also want to use in specific services, could you please tell me how to get it in specific services?

**Comment by carl-mastrangelo** [comment]
@christ258 can you clarify if you are doing this client side or server side?

**Comment by christ258** [comment]
Server, used Netty, I can get the Header in the HeaderServerInterceptor, but the HeaderServerInterceptor does not execute on a single thread, so the Header data is not passed into the service.

**Comment by christ258** [comment]
For example, if I get Header content from the RouteGuideService service？

**Comment by carl-mastrangelo** [comment]
HeaderServerInterceptor is an example that shows how to access it.   It always executes on the executor you provide when building the server.   We don't synchronize it because some people do not need synchronization.    

Can you what code you are working with?   Also, what are you trying to do?

**Comment by christ258** [comment]
Thank you for reply. For example, I have an RPC service class, RouteGuideService. When the server gets the request, I want to get this Header in the RPC method within this service class.

**Comment by carl-mastrangelo** [comment]
@christ258 Ok I see.  In that case what you should do is extract the header in the `HeaderServerInterceptor`, and put it in the `Context`.   You'll need to define your own `Context.Key` to put it in the context.  From the Service, you can then call `Context.current()` to get the header back out.  This only works with the non-blocking stubs currently.

**Comment by christ258** [comment]
I see that ThreadLocal is stored as a unique identifier in the Context, but in the HeaderServerInterceptor, its threads are not one-to-one

**Comment by christ258** [comment]
I got it, Thanks
