### ISSUE TITLE
Tracking issue for StatusRuntimeException

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#4683]

**Comment by carl-mastrangelo** [comment]
Notes from discussion:

* Using Status.asException does the same thing, but not objectively better
* Several users of both constructor and static factory
* Considered making the ctor protected, so that the default construction is sans- trailers, but extenders can still call it.

Decision: Seems okay as is.

**Comment by ejona86** [comment]
API review:
 * We should stabilize Status.asException(Metadata). Yes, it is two ways of doing the same thing, but has been around a long time and doesn't hurt much.

**Comment by temawi** [comment]
Fixed in #10322.
