### ISSUE TITLE
How to close or not display gRPC internal logs?

### ISSUE THREAD

**Issue by dxf1122** [grpc/grpc-java#4698]
How to close or not display gRPC internal logs?

**Comment by dapengzhang0** [comment]
You can disable java logging (in general, not grpc specific) either by

- configuration:

  Add a JVM option `-Djava.util.logging.config.file=./logging.properties`
  and in the `logging.properties` file include the following line
  `io.grpc.internal.level = OFF`

or 

- in program:
  ```java
  LogManager.getLogManager().getLogger("").getHandlers().forEach(
      handler -> handler.setFilter(
          logRecord -> !logRecord.getLoggerName().contains("io.grpc.internal")));
  ```

**Comment by dxf1122** [comment]
Log4j  configuration:

<logger name="io.grpc">
	<level value="ERROR"></level>
</logger>
