### ISSUE TITLE
[Question] "grpc-netty-shaded doesn't work with epoll"

### ISSUE THREAD

**Issue by imweijh** [grpc/grpc-java#4713]
Hi
From https://github.com/HubSpot/grpc-netty-shaded-epoll
> grpc-netty-shaded-epoll
> When using grpc, you can use grpc-netty-shaded in order to avoid netty conflicts. Unfortunately, it doesn't work with epoll. This repo builds a shaded version of netty-transport-native-epoll with the packages relocated the same way that grpc-netty-shaded expects.
> 

So if I use grpc-netty-shaded in linux machine that will hurt performance ?

**Comment by imweijh** [comment]
https://stackoverflow.com/questions/23465401/why-native-epoll-support-is-introduced-in-netty
seem the default NIO is use epoll too , so I should not worry about it too much.

another google find this:
https://groups.google.com/forum/#!topic/grpc-io/tznetG4A6sw

**Comment by carl-mastrangelo** [comment]
@imweijh I guess I forgot about that answer.   I am going to close it because I think it covers the issue.

**Comment by imweijh** [comment]
Thanks
