### ISSUE TITLE
Upgrade appengine-plugins-core from 0.3.9

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#4714]
Somewhere in the build tree this happens:

```
Download https://jcenter.bintray.com/com/google/cloud/tools/appengine-plugins-core/0.3.9/appengine-plugins-core-0.3.9.jar
```

I happened to notice this in the output of ./gradlew check

1. 0.3.9 is very out of date
2. That library was never intended to be used outside a few very specific projects.

Need to figure out how this gets pulled in; and if it makes sense we need to upgrade it. I'm surprised 0.3.9 still works against App Engine server side, and if it does I doubt it will very much longer.

**Comment by elharo** [comment]
OK, I suspect this is how it got pulled in:

```
Download https://jcenter.bintray.com/com/google/cloud/tools/appengine-gradle-plugin/1.3.5/appengine-gradle-plugin-1.3.5.jar
```

That dependency is legit, but it does need to be upgraded to 2.0. I'm checking on the status of that.

**Comment by ejona86** [comment]
2.0 is still RC. We'd want to wait until it is final.

**Comment by ejona86** [comment]
There's a 0.6.4 version it looks like. I keep having trouble when looking up versions because there is another plugin for appengine that's different.

**Comment by ejona86** [comment]
Doh. Right. The appengine-plugins-core plugin pulls it in, and we probably don't want to refer to it directly.

**Comment by zpencer** [comment]
It looks like 1.3.5 is the latest stable release, so I'll check again for 2.0 when it is out of rc. This should be a simple change. https://search.maven.org/search?q=g:com.google.cloud.tools%20AND%20a:appengine-gradle-plugin&core=gav

**Comment by elharo** [comment]
2.4.1 is out and stable. Is this still an issue?

**Comment by ejona86** [comment]
Looks like I already upgraded it to 2.x in https://github.com/grpc/grpc-java/commit/026673cff5622c997da45a71d72e143dfe9443ff . So this is fixed.
