### ISSUE TITLE
compile broken by protos

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#4715]
This happens on both Mac OS X and Linux with a clean checkout with `.gradlew check`:

```
> Task :grpc-compiler:compileJava_pluginExecutableJava_pluginCpp
In file included from /Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_plugin.cpp:8:
/Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

/Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

In file included from /Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_generator.cpp:1:
/Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by elharo** [comment]
Per @ejona86 "That's a problem with 1) not having protobuf headers available or 2) having too old a version of protobuf." 

In my case, I think it's likely 1. However why is this happening? This feels like the build system is not  as self-contained and hermetic as it should be.

**Comment by ejona86** [comment]
Please read our COMPILING.md document. I strongly suggest using `-PskipCodegen=true` which avoids building the C++ components.

There are C++ components involved here. If you want a hermetic build system for them, build with Bazel. Otherwise, yes, you will live in the wonderful world of C dependency fun.

**Comment by elharo** [comment]
Thanks. Probably worth adding a pointer to this doc to CONTRIBUTING.md.
