### ISSUE TITLE
GKE: Support for a bazel rule to generate api_descriptor.pb

### ISSUE THREAD

**Issue by mtaliaf** [grpc/grpc-java#4722]
Are there any plans on adding a rule to generate the api_descriptor.pb thats required to uses grpc on GKE Endpoints.

Its described in the "Configuring the protocol buffer" of [endpoints/docs/grpc/configure-endpoints](https://cloud.google.com/endpoints/docs/grpc/configure-endpoints)

If there is I have built one and can submit a PR but im not really sure where to put it.

**Comment by dapengzhang0** [comment]
Is the `api_descriptor.pb` something like the `foo-descriptor-set.proto.bin` output file of the [proto_library()](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library) rule?

**Comment by mtaliaf** [comment]
Im sure that its similar but it doesnt appear to have the same flags as is required by protoc when producing it.  Mainly
--include_imports \
--include_source_info \

Im not an expert on what exactly is produces by proto_library() but this is my understanding.

**Comment by dapengzhang0** [comment]
I'm not sure [grpc/grpc-java](/grpc/grpc-java) is the right repository for this rule, at least it seems not for java only. Git repos like [grpc-ecosystem](/grpc-ecosystem) or [GoogleCloudPlatform](/GoogleCloudPlatform) might be better choices.
