### ISSUE TITLE
getFullMethodName return different value in Java and Go.

### ISSUE THREAD

**Issue by ParadiseHell** [grpc/grpc-java#4726]
I want to put a signature which contains method name in the headers, but I different value in Jva and Go.

**/com.example.Server/Method** in Go.
**com.example.Server/Method** in Java.

Grpc version : 1.13.2

**Comment by sheng** [comment]
Yep, I think it should have a leading slash.

Check these out:

- [Go](https://github.com/grpc/grpc-go/blob/43d1787a0c69bbee488da207f010368a8f4d980d/tap/tap.go#L31)
- [C#](https://github.com/grpc/grpc/blob/5253c8f9a899450397a5e46e4923d01ac9a66a27/src/csharp/Grpc.Core/Method.cs#L171)
- [Python](https://github.com/grpc/grpc/blob/7542ba6e0caee740f124dc25706287fd62f546d8/src/python/grpcio/grpc/_common.py#L112)

Although the return value of this method in Java doesn't make people misunderstand. But using it to generate a signature can cause problems (the signatures generated by the client and the server are inconsistent).

**Comment by dapengzhang0** [comment]
In the proposal https://github.com/ejona86/grpc/blob/ea6facf634569727b0e44099d66e9fba1046019d/doc/PROTOCOL-SEMANTICS.md#appendix-a-call-abnf
the full method name semantic is without leading slash.

Or course, if you interpret the full method name as the HTTP/2 `:path` header as in https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests, then it must come with a leading slash.

**Comment by dapengzhang0** [comment]
It's always easy to normalize the return value to the form you want.
`if (!fullMethodName.startsWith("/")) { fullMethodName = "/" + fullMethodName; }`

If you want cross-language/platform data, you can use service reflection https://github.com/grpc/grpc/blob/master/doc/server-reflection.md
