### ISSUE TITLE
Certificates pinning

### ISSUE THREAD

**Issue by BulatMukhutdinov** [grpc/grpc-java#4747]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.14.0

### What did you expect to see?
Hi! I couldn't find any documentation about certificate pinning. I found some [thread](https://github.com/grpc/grpc-java/pull/3205) about it  but I failed to have any progress further on that. Can you provide a link, please?

**Comment by carl-mastrangelo** [comment]
Hi @BulatMukhutdinov ,

We don't use pinning ourselves, so we don't have a lot of experience with it.   I think this would get a better answer and more visibility if you posted it on StackOverflow or on the grpc-io forum.    

Without seeing your code I can't really give any pointers, but I would still suggest asking there first.
