### ISSUE TITLE
Add unix domain socket name resolver for Netty

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4750]
This is likely blocked on #3085.

**Comment by carl-mastrangelo** [comment]
The design requirements are unclear for this, so reassiging.

**Comment by ejona86** [comment]
Make a NameResolver that would use the `unix` scheme, for use with Netty. It seems any unclear design requirements are part of #3085, which I already said was likely a blocker.

**Comment by ejona86** [comment]
Fixed by #9113
