### ISSUE TITLE
ALTS: release handshaker service channel if it is not used.

### ISSUE THREAD

**Issue by jiangtaoli2016** [grpc/grpc-java#4755]
In current ALTS java implementation, we create a shared ALTS thread and a gRPC channel to the handshaker service when we build ALTS channel. The channel to the handshaker service will already be there until application exit. It is more efficient if we can ref count the channel and free this gRPC channel if nobody is using it.

Note that ALTS C++ code does the same resource management: creates a thread and a channel to the handshaker service and only destroys them during grpc shutdown. https://github.com/grpc/grpc/blob/master/src/core/tsi/alts_transport_security.cc#L53

**Comment by zpencer** [comment]
@jiangtaoli2016 any updates on this one?

**Comment by srini100** [comment]
@jiangtaoli2016, can this issue be closed since https://github.com/grpc/grpc-java/pull/5210 is merged?

**Comment by jiangtaoli2016** [comment]
Yes, Let's close this.
