### ISSUE TITLE
Doc seems to be self-contradicting on CallStreamObserver.disableAutoInboundFlowControl

### ISSUE THREAD

**Issue by tferi** [grpc/grpc-java#4772]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
looking at master HEAD

### What did you expect to see?
See https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/CallStreamObserver.java#L80-L93

Given that last paragraph I'd expect to see SERVER_STREAMING (1 request to * responses) to be affected on the server and CLIENT_STREAMING (* requests to 1 response) on the client, since these are the ones that have one inbound message.

SERVER_STREAMING has multiple inbound messages from the client's perspective and the same is true for CLIENT_STREAMING from the server's point of view, so listing those in the `<ul>` contradicts the part above.

**Comment by zpencer** [comment]
This looks like an error in the docs. Client streaming streaming on client side and server streaming on server side are the cases where disabling inbound flow control should take no effect.
