### ISSUE TITLE
ClientCallImpl.toString() could be more helpful

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#4776]
ClientCall current only prints out the method descriptor, which is not so helpful.  It would be useful to include some more detail.  Here are some ideas:

* The deadline
* whether the call has been started, half closed, or cancelled
* whether initial headers have been received, or trailers recieved
* what was the context for the call
* the channel id of the call
* if the channel has a subchannel assigned, the subchannel id or remote host name
* Security level (if available)
* Wait for ready or not

These would be useful when printing out the call, or including the call details in error messages, or generally.

**Comment by carl-mastrangelo** [comment]
cc @zhangkun83

**Comment by carl-mastrangelo** [comment]
Getting some thoughts down after talking with a few people:

* initial deadline and time remaining  are useful.  
* representing the string a a textproto would be terse and human readable.  It could be parsed automatically
* include the channelid or socketid (per channelz) in the string, which can be grepped for in the INFO level logs  This would alleviate putting a lot of debug info into the string, as it could be queried via channelz
* RPC state would be useful, possible as short string (headerssent|messagesent|closesent|headersrecv|messagesrecv|closerecv) 
* Include the call string in the StatusRuntimeException produced by io.grpc.stub would be nice, possibly in the exception's message (not the status's)

**Comment by bgguna** [comment]
I can pick up this issue and create a PR. This is going to be my first PR to this community so if anything is incorrect, please shout out.

**Comment by ejona86** [comment]
Closing, since nobody's found a need for this recently.

I don't think most of the details mentioned are a great idea, as they expose internals I'd rather not expose and require thread-safety to implement. The exceptions would be deadline and wait-for-ready; those would be fine, but given the improvements to DEADLINE_EXCEEDED error reporting I'm not sure it adds much value at this point.
