### ISSUE TITLE
grpc server executor is not populating java.lang.Error to logging framework

### ISSUE THREAD

**Issue by gdong42** [grpc/grpc-java#4792]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

v1.14.0

### What did you expect to see?

Whenever any `java.lang.Error` occurs, e.g. `NoSuchMethodError`, it gets logged by logging framework at least.

A bit explanation:
from https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/SerializingExecutor.java#L117-L136

```
      while ((r = runQueue.poll()) != null) {
        try {
          r.run();
        } catch (RuntimeException e) {
          // Log it and keep going.
          log.log(Level.SEVERE, "Exception while executing runnable " + r, e);
        }
      }
```

Above executor only catches `RuntimeException` and logs it to underlying logger. However, when an error occurs, e.g. `NoSuchMethodError` due to some incompatible dependencies the service implementation uses, the error could not be caught and logged, thus causing
1. the loop break while runQueue might still have remaining elements
2. the Error could not be logged, and fallbacks to `ThreadGroup`'s default uncaught behavior, which is  to print it to `System.err`

The first consequence might be debatable as the framework does handle the remaining in the end, it seems. Although I would say throwing Errors would be quite usual from user code, thus it might be also reasonable to not break the loop and just "Log it and keep going".

The second one IMHO is having a severe impact. People often look at the log output instead of std err for long-running service. Above code will throw the Error all the way up, very likely there will be no other catches, making the error only print to console, making this error miss in any logging files, or other error reporting system like Sentry. We recently encountered such a case, very difficult to locate the throwing errors without any logs.

So can we also catch Errors and recover from it? Or at least log the error and re-throw it maybe, if you think recovering the error does not make sense.

**Comment by zhangkun83** [comment]
@ejona86, I wonder if we should just change `RuntimeException` to `Throwable`.

**Comment by ejona86** [comment]
Real quick; still need to look at this more, but sending before I leave for the day.

I purposefully didn't catch Error in order to let it pass to the Thread's UncaughtExceptionHandler. I'd be semi-happy to just call the UncaughtExceptionHandler directly, but it is unclear if that would cause problems (it is technically against the API, but it seems like "nobody would care.")

> I'm pretty sure we we rely on this for unit tests, since AssertionError can break through.

In unit tests either it will be thrown on a separate thread (and thus not fail the test), or it will propagate _through_ the serializing executor to the top of the testing thread. So if we swap this to `catch Error` it could potentially make unit tests worse.

**Comment by gdong42** [comment]
> @gdong42 Are you setting an uncaught exception handler on the threads you are providing?

@carl-mastrangelo No, I think we are not. Am I suppose to set one? grpc-java framework is managing the thread group, so not sure how to set that on user side.

**Comment by gdong42** [comment]
> I'll point out that the definition of an Error is "a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch." Thus "log it and keep going" seems a strange approach.

Generally it's true for application development, but still not fully convinced in framework development scenarios. E.g. 1: servlet container, E.g. 2: I see a lot `Error` catching in https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ServerImpl.java , and I think it's reasonable to do that in some cases. It's also not uncommon to see catching Throwable statements in framework code.

> As a rule we don't log and rethrow. It produces confusion in logs because it makes it seem an event happened more times than it actually did.

The problem now is that it *never* logs the error except to System.err. Not likely to produce confusion if we log it with logger only once.

Anyway, I'll go ahead and add a default global handler through `Thread.setDefaultUncaughtExceptionHandler()` on our side as suggested. Thanks for all the advices. I admit that handing it on user's side or grpc side is debatable. Feel free to close the issue if you think user is responsible to do that.

**Comment by ejona86** [comment]
> I see a lot Error catching in https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ServerImpl.java , and I think it's reasonable to do that in some cases.

All of those re-throw. Most are an alternative to this pattern:

```java
boolean success = false;
try {
  doWork();
  success = true;
} finally {
  if (!success) {
    cleanUp();
  }
}
```

One of them _appears_ similar to "log and rethrow," except we know that the exception doesn't go anywhere with the `stream.close()`. It is mainly included to be helpful when debugging (with a debugger) and _maybe_ for statistics.

> The problem now is that it never logs the error except to System.err. Not likely to produce confusion if we log it with logger only once.

With your particular configuration. The default is for logs to go to System.err.

There's an important distinction in all this: if we log, then applications get no control over what to do. If we throw then application can configure things some to their own extent. You are optimizing for letting a user (that is, a person) see the output in your configuration where System.err is unavailable. We are optimizing for letting the application (that is, a program) see the output.

> I admit that handing it on user's side or grpc side is debatable. Feel free to close the issue if you think user is responsible to do that.

I honestly would love a better solution here, which works for both use-cases. However, to date I've not found a clear solution.

Thank you for reporting all the same! It's been a while since I've considered the fact the default UncaughtExceptionHandler writes to System.err instead of logging. And I am still _very_ interested in finding a better solution here.

**Comment by gdong42** [comment]
@ejona86 Thanks for the detailed explanation, I see your point.

@carl-mastrangelo yes, we would like to use a custom executor as you suggested. Could you please confirm, is the following correct way to do what I intend?

```java
// create server:

        NettyServerBuilder builder = NettyServerBuilder.forAddress(
                new InetSocketAddress(InetAddresses.forString(getAddress()), getPort()))

        .executor(GRPC_EXECUTOR_RESOURCE.create());    // <==  use custom executor

```
```java
  // define executor in another utility class
  public static final Resource<ExecutorService> GRPC_EXECUTOR_RESOURCE =
      new Resource<ExecutorService>() {
        private static final String NAME = "grpc-executor";

        @Override
        public ExecutorService create() {
          return Executors.newCachedThreadPool(getThreadFactory(NAME + "-%d", true));
        }

        @Override
        public void close(ExecutorService instance) {
          instance.shutdown();
        }

        @Override
        public String toString() {
          return NAME;
        }
      };

  public static ThreadFactory getThreadFactory(String nameFormat, boolean daemon) {
    if (IS_RESTRICTED_APPENGINE) {
      @SuppressWarnings("BetaApi")
      ThreadFactory factory = MoreExecutors.platformThreadFactory();
      return factory;       // we are not running on GCP, so I assume keeping this logic does not do harm
    } else {
      return new ThreadFactoryBuilder()
          .setDaemon(daemon)
          .setNameFormat(nameFormat)
          .setUncaughtExceptionHandler(   // <==  this is the handler we would like to use
              (t, e) -> logger.error("Exception in thread \"" + t.getName() + "\" ", e))
          .build();
    }
  }
```

Above code is copied from grpc-core, I merely redefine them to insert the exception handler. Not sure if it's the correct usage?

Thanks in advance.

**Comment by ejona86** [comment]
@gdong42, Resource is "internal"; you shouldn't use it directly. You can ignore `IS_RESTRICTED_APPENGINE == true`.

The shortest form would look like:
```java
ExecutorService executor = Executors.newCachedThreadPool(
    new ThreadFactoryBuilder()
        .setDaemon(true)
        .setNameFormat("somethread-%d")
        .setUncaughtExceptionHandler(
              (t, e) -> logger.error("Exception in thread \"" + t.getName() + "\" ", e))
        .build());
```

However, note that if you have another executor already, you can "wrap" it to handle the throwables:
```java
final ExecutorService someExecutor = ...;
Executor executor = new Executor() {
    @Override
    public void execute(final Runnable runnable) {
      someExecutor.execute(new Runnable() {
        @Override public void run() {
          try {
            runnable.run();
          } catch(Throwable t) {
            logger.error("Exception", t);
          }
        }
      });
    }
};
```
