### ISSUE TITLE
Move Channelz to io.grpc

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4796]
`io.grpc.internal.Channelz` is used to coordinate between the transport and the channelz service. Since that's coordination across artifacts/components putting that in internal hides an important API. Generally internal is just a "util" of classes that could be shaded into each transport without major issues.

The moved class can be marked `@Internal` without bothering me at this point.

**Comment by carl-mastrangelo** [comment]
I personally don't want `@Internal` to  exist.   It isn't enforced, or enforceable, and history has shown is routinely violated.  Something strong is needed to keep Channelz from being used by outside packages.

**Comment by ejona86** [comment]
That isn't an argument against moving it to `io.grpc`. I mentioned `@Internal` just to point out I don't really care what form it looks like in `io.grpc`.
