### ISSUE TITLE
Dynamic certificate rotation

### ISSUE THREAD

**Issue by luengnat** [grpc/grpc-java#4798]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.9.0

### What did you expect to see?
We use mTLS to perform the authentication between client and server. To make thing secure, we decide to roll over the certificate for both client and server very often. Is there a good mechanism to dynamically rotate the certificate without restarting either client or server?

**Comment by ejona86** [comment]
I just answered https://stackoverflow.com/a/52067504/4690866 which is similar. I'm not aware of anything that makes this easy, but it may not be _too_ hard.

**Comment by ejona86** [comment]
I do feel like I'm missing something, though, because it seems to be an equal pain to inject a [X509ExtendedKeyManager](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/X509ExtendedKeyManager.html). I thought there was a more straight-forward way of doing this. Anyway, this is mostly a Java thing.

**Comment by luengnat** [comment]
SslContextBuilder is not extensible so it is quite more complicated to achieve that easily

**Comment by ejona86** [comment]
Use SslContextBuilder like normal, but then wrap the result in your own delegating SslContext. When you need to change it out, build a new instance with SslContextBuilder and begin delegating to it instead from within your earlier SslContext instance.

**Comment by zhangkun83** [comment]
@luengnat, did @ejona86's solution work for you?
