### ISSUE TITLE
Netty 4.1.30.Final

### ISSUE THREAD

**Issue by njhill** [grpc/grpc-java#4800]
I'm sure this is on your guys' radar but would be great if it could be included in the next release!

**Comment by zhangkun83** [comment]
It's not in the upcoming 1.15 release due by Sep 10.

**Comment by njhill** [comment]
Updated now that 4.1.30.Final is released. I hope this can be included in 1.16!

**Comment by carl-mastrangelo** [comment]
@njhill @ejona86 Found this bug recently in Netty:   https://github.com/netty/netty/pull/8332/files

Not sure if we will wait another release

**Comment by njhill** [comment]
Ah, thanks @carl-mastrangelo. That bug looks like it has been there for a while though and is presumably present in the currently-used 4.1.27.Final.

Assuming that's the case and that 1.16 will happen before netty 4.1.31.Final is released, there would still be significant benefit i.m.o. to updating given the fixes and performance improvements in the last 3 releases (I'm interested in particular in the fix for the  epoll regression in 4.1.27.Final).

**Comment by ejona86** [comment]
@carl-mastrangelo, yeah, the bug in that PR is present in the current version we are using, so it shouldn't prevent us upgrading.
