### ISSUE TITLE
Issue NoSuchMethodError: io.grpc.MethodDescriptor

### ISSUE THREAD

**Issue by Myron530** [grpc/grpc-java#4811]
Please answer these questions:

get this problem when starting.
Caused by: java.lang.NoSuchMethodError: io.grpc.MethodDescriptor$Builder.setSampledToLocalTracing(Z)Lio/grpc/MethodDescriptor$Builder;

### What version of gRPC are you using?
grpc v:1.6.1
protoc version: 3.3.0

### What did you expect to see?
If you konw how to solve this problem please tell me.

**Comment by Myron530** [comment]
just import this to maven pom.xml, so have bad error when staring.
        <dependency>
            <groupId>net.devh</groupId>
            <artifactId>grpc-server-spring-boot-autoconfigure</artifactId>
        </dependency>

**Comment by Myron530** [comment]
done.
maven pom.xml grpc-server-spring-boot-autoconfigure include grpc-services 1.10.1
so switch grpc's version to 1.10.1

**Comment by carl-mastrangelo** [comment]
Hi @Myron530 

I believe you need to use a  later version.   It appears that you are using later stubs with an earlier grpc-core dependency.

**Comment by Myron530** [comment]
@carl-mastrangelo yep, thanks.
