### ISSUE TITLE
findBugs will fail if we don't check the return value of Context.attach().

### ISSUE THREAD

**Issue by songy23** [grpc/grpc-java#4817]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.14

### What did you expect to see?

Not forced to check the return value of `Context.attach()`.

Upgrading to gRPC v1.14.0 broke our `findBugs` check, because in 1.14.0 `Context.attach()` is annotated with `@CheckReturnValue`. We have to use a work around to pass the `findBugs` check. See https://travis-ci.org/census-instrumentation/opencensus-java/jobs/422665965#L601 and https://github.com/census-instrumentation/opencensus-java/pull/1404#discussion_r214448178.

/cc @bogdandrutu

**Comment by zhangkun83** [comment]
`CheckReturnValue` is intended. If you ignore the return value, you are not attaching/detaching the context in the intended way, and your code is error-prone.

**Comment by songy23** [comment]
Got it, thanks for the explanation. I filed https://github.com/census-instrumentation/opencensus-java/issues/1407 to follow up on OpenCensus side.
