### ISSUE TITLE
How to use grpc in osgi environment now?

### ISSUE THREAD

**Issue by dingrui37** [grpc/grpc-java#4822]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

### What did you expect to see?
Is there any bundle version of gRPC now? or how to convert .

**Comment by ejona86** [comment]
If this is about grpc-core+grpc-context not getting along, #2727 is still open and the issue to track for that. If this is about more directly supporting OSGi packaging, that would be #1565.
