### ISSUE TITLE
Broken pipe - Debug logging - Openshift

### ISSUE THREAD

**Issue by chsi13** [grpc/grpc-java#4827]
gRPC version : 1.13.1

I'm using gRPC via the spring boot starter (https://github.com/LogNet/grpc-spring-boot-starter).

I forward to you this issue : https://github.com/LogNet/grpc-spring-boot-starter/issues/92

I see lot of exceptions (log as debug level) when I deployed a gRPC server on openshift.

Any idea ?

**Comment by dapengzhang0** [comment]
I have no knowledge about openshift. How do you deploy the starter on openshift? Did you enable HTTP/2 on openshift?

**Comment by chsi13** [comment]
Communication between pods is working when use grpc communication. I have To enable debug logging to see these stack. However seems not really normal. Maybe I have To forward issue to openshift

**Comment by ejona86** [comment]
Looking at the logs, "Connection reset by peer" and "Broken pipe" are pretty normal events in many circumstances when the connection is closed. That is why they are logged at the debug level. This is just normal TCP handling, because of confusion/difficulty between shutdown() and close() and how those interact between graceful TCP close and RST.

**Comment by chsi13** [comment]
I opened this issue because I only saw this behavior inside openshift not in local environment- containerized or not

**Comment by ejona86** [comment]
@chsi13, if RPCs were failing with those errors then I'd be more concerned. The environment can influence how frequently you see them.

**Comment by chsi13** [comment]
@ejona86, I was a little worried only because these stack happened in loop fashion in logs . But thanks for info. Will continue as-is

**Comment by ejona86** [comment]
@chsi13, oh, a loop fashion! On server-side... There's a couple scenarios that could cause it, but I think it is most likely health checking tools to see whether your server is healthy. They tend open a TCP connection and then immediately close it. If the loop doesn't appear to stop, then there may be a problem.

**Comment by chsi13** [comment]
Humm... you're right on kubernetes I define readiness and liveness probes that check the availability of the service by open a tcp connection to port 6565...
