### ISSUE TITLE
Use default java keystore , when running unit test from intellij

### ISSUE THREAD

**Issue by dzonekl** [grpc/grpc-java#4854]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
   grpcVersion = '1.13.1'

### What did you expect to see?
I Expect the jvm trusted store to be used, when loaded with self-signed certificate. 

#### load certificate with keytool

Loading a self-signed, certificate like this: 

`keytool -keystore cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias my-alias -file my-cert.crt`

#### Unit test error

Then creating a default stub without ssl context:

`        ManagedChannel channel =
                onChannelBuild(ManagedChannelBuilder.forAddress("my.host.nl", 443))
                        .build();
`
Running the unit test from Intellij. 

`Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)`

#### loading an SSLcontext

From the example "HelloWorldClientTls", I load the certificate (After conversion to .pem), and then the test is executed properly without Exception. 

### Question

Is this expected behaviour and simply the fact that the unit test in IntelliJ is not using the jvm default keystore? If so, why do you provide an example to load an SSL context with a Netty builder?

**Comment by dapengzhang0** [comment]
>I Expect the jvm trusted store to be used, when loaded with self-signed certificate.

but your command 
```
keytool  -importcert -keystore cacerts -file my-cert.crt
```

only creates a file named "cacerts" in current directory. How does it become a JVM default keystore?
