### ISSUE TITLE
Allow custom NameResolvers to support CONNECT Proxies

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4858]
This requires `ProxySocketAddress` being public. It seems we'll also need to inject `ProxyDetector` to NameResolvers.

**Comment by ejona86** [comment]
API review discussion:
ProxyDetector to return SocketAddress; Rename ProxySocketAddress to HttpConnectProxySocketAddress. Implement equality and toString(). Merge ProxyParameters into HttpConnectProxySocketAddress. Use Builder for HttpConnectProxySocketAddress

Related: #5279

**Comment by creamsoup** [comment]
i believe this is fixed by #5344
