### ISSUE TITLE
accidental complication error happend problem

### ISSUE THREAD

**Issue by jeffreyji666** [grpc/grpc-java#486]
I compile my grpc project, sometimes it is ok but sometimes it has the following compilation error:

>
XXXXGrpc.java:22: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SearchRequest.PARSER),
                          ^
XXXXGrpc.java:23: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SearchResponse.PARSER));
                          ^
XXXXGrpc.java:28: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SearchRequest.PARSER),
                          ^
XXXXGrpc.java:29: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SearchResponse.PARSER));
                          ^
XXXXGrpc.java:34: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SearchRequest.PARSER),
                          ^
XXXXGrpc.java:35: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SearchResponse.PARSER));
                          ^
XXXXGrpc.java:40: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SearchRequest.PARSER),
                          ^
XXXXGrpc.java:41: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SearchAllResponse.PARSER));
                          ^
XXXXGrpc.java:46: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SuggestRequest.PARSER),
                          ^
XXXXGrpc.java:47: error: package io.grpc.protobuf does not exist
          io.grpc.protobuf.ProtoUtils.marshaller(com.engzo.search.protoc.SuggestResponse.PARSER));

sometimes ok sometimes not. very weird.

**Comment by zhangkun83** [comment]
It will be helpful if you can share your project, or at least ``build.gradle``.

**Comment by ejona86** [comment]
It seems you are missing a compile dependency on grpc-java. If you share important parts of your `build.gradle` we could point out what is missing. If not able, then make sure you double-check the main README.md. Closing until we get more information.
