### ISSUE TITLE
Segfault when  LoggingAppender is configured in logback.xml in google-cloud-java

### ISSUE THREAD

**Issue by JesseLovelace** [grpc/grpc-java#4878]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.13.1/1.15.0

### What did you expect to see?
Netty starting and terminating correctly

A user reported an issue with a system crash in google-cloud-java when starting Netty with LoggingAppender configured:
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3455

After recreating the issue and looking into the logs, it's a Sigsegv in native code outside the VM (
[See the log file attached](https://github.com/grpc/grpc-java/files/2417187/hs_err_pid11025.2.log)).

We tried updating all of the dependencies to 1.15.0 but that didn't fix it, the stack trace suggests it's an error in native code, so we're pretty sure it's not an issue with any Java code but some kind of issue with the binding configuration in grpc.

**Comment by zpencer** [comment]
Closing this, since it appears to be a netty issue.
