### ISSUE TITLE
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available

### ISSUE THREAD

**Issue by jags1** [grpc/grpc-java#4879]
I am getting following error in MAC where as same java spring boot application(pub/sub,spanner) is running fine in windows for my other colleagues:
nested exception is java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available

Ran the compatibility checker output is as below:

OS details:
os.detected.name: osx
os.detected.arch: x86_64
os.detected.classifier: osx-x86_64
os.detected.release: null
os.detected.release.version: null
JVM details:
Java version: 1.8.0_171
Java specification version: 1.8
JVM bit mode: 64
OpenSSL details:
open ssl is available: false
ALPN is supported: false
Checking compatibility...
[PASS] This OS + architecture is supported.
[PASS] 64-bit JVM is supported.
[FAIL] Open SSL is NOT available
Open SSL Unavailability cause:
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-osx-x86_64, netty-tcnative]
at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:178)
at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:403)
at io.netty.handler.ssl.OpenSsl.(OpenSsl.java:85)
at com.google.cloud.compatchecker.GoogleCloudCompatChecker.check(GoogleCloudCompatChecker.java:58)
at com.google.cloud.compatchecker.GoogleCloudCompatChecker.main(GoogleCloudCompatChecker.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
at java.lang.Thread.run(Thread.java:748)
[FAIL] Open SSL ALPN is NOT supported
Result: FAIL
Your environment is not supported by Forked Tomcat Native.
See http://netty.io/wiki/forked-tomcat-native.html for details.
This means that you won't be able to use grpc-based APIs, but
http1-based APIs should still work.

Any suggestion please how to fix the issue?

Gradle dependencies:
+--- org.springframework.boot:spring-boot-starter-web:2.0.0.RELEASE
| +--- org.springframework.boot:spring-boot-starter:2.0.0.RELEASE
| | +--- org.springframework.boot:spring-boot:2.0.0.RELEASE
| | | +--- org.springframework:spring-core:5.0.4.RELEASE
| | | | --- org.springframework:spring-jcl:5.0.4.RELEASE
| | | --- org.springframework:spring-context:5.0.4.RELEASE
| | | +--- org.springframework:spring-aop:5.0.4.RELEASE
| | | | +--- org.springframework:spring-beans:5.0.4.RELEASE
| | | | | --- org.springframework:spring-core:5.0.4.RELEASE ()
| | | | --- org.springframework:spring-core:5.0.4.RELEASE ()
| | | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | | +--- org.springframework:spring-core:5.0.4.RELEASE ()
| | | --- org.springframework:spring-expression:5.0.4.RELEASE
| | | --- org.springframework:spring-core:5.0.4.RELEASE ()
| | +--- org.springframework.boot:spring-boot-autoconfigure:2.0.0.RELEASE
| | | --- org.springframework.boot:spring-boot:2.0.0.RELEASE ()
| | +--- org.springframework.boot:spring-boot-starter-logging:2.0.0.RELEASE
| | | +--- ch.qos.logback:logback-classic:1.2.3
| | | | +--- ch.qos.logback:logback-core:1.2.3
| | | | --- org.slf4j:slf4j-api:1.7.25
| | | +--- org.apache.logging.log4j:log4j-to-slf4j:2.10.0
| | | | +--- org.slf4j:slf4j-api:1.7.25
| | | | --- org.apache.logging.log4j:log4j-api:2.10.0
| | | --- org.slf4j:jul-to-slf4j:1.7.25
| | | --- org.slf4j:slf4j-api:1.7.25
| | +--- javax.annotation:javax.annotation-api:1.3.2
| | +--- org.springframework:spring-core:5.0.4.RELEASE ()
| | --- org.yaml:snakeyaml:1.19
| +--- org.springframework.boot:spring-boot-starter-json:2.0.0.RELEASE
| | +--- org.springframework.boot:spring-boot-starter:2.0.0.RELEASE ()
| | +--- org.springframework:spring-web:5.0.4.RELEASE
| | | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | | --- org.springframework:spring-core:5.0.4.RELEASE ()
| | +--- com.fasterxml.jackson.core:jackson-databind:2.9.4
| | | +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
| | | --- com.fasterxml.jackson.core:jackson-core:2.9.4
| | +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.4
| | | +--- com.fasterxml.jackson.core:jackson-core:2.9.4
| | | --- com.fasterxml.jackson.core:jackson-databind:2.9.4 ()
| | +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.4
| | | +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
| | | +--- com.fasterxml.jackson.core:jackson-core:2.9.4
| | | --- com.fasterxml.jackson.core:jackson-databind:2.9.4 ()
| | --- com.fasterxml.jackson.module:jackson-module-parameter-names:2.9.4
| | +--- com.fasterxml.jackson.core:jackson-core:2.9.4
| | --- com.fasterxml.jackson.core:jackson-databind:2.9.4 ()
| +--- org.springframework.boot:spring-boot-starter-tomcat:2.0.0.RELEASE
| | +--- javax.annotation:javax.annotation-api:1.3.2
| | +--- org.apache.tomcat.embed:tomcat-embed-core:8.5.28
| | +--- org.apache.tomcat.embed:tomcat-embed-el:8.5.28
| | --- org.apache.tomcat.embed:tomcat-embed-websocket:8.5.28
| | --- org.apache.tomcat.embed:tomcat-embed-core:8.5.28
| +--- org.hibernate.validator:hibernate-validator:6.0.7.Final
| | +--- javax.validation:validation-api:2.0.1.Final
| | +--- org.jboss.logging:jboss-logging:3.3.0.Final -> 3.3.2.Final
| | --- com.fasterxml:classmate:1.3.1 -> 1.3.4
| +--- org.springframework:spring-web:5.0.4.RELEASE ()
| --- org.springframework:spring-webmvc:5.0.4.RELEASE
| +--- org.springframework:spring-aop:5.0.4.RELEASE ()
| +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| +--- org.springframework:spring-context:5.0.4.RELEASE ()
| +--- org.springframework:spring-core:5.0.4.RELEASE ()
| +--- org.springframework:spring-expression:5.0.4.RELEASE ()
| --- org.springframework:spring-web:5.0.4.RELEASE ()
+--- org.springframework.boot:spring-boot-starter-actuator:2.0.0.RELEASE
| +--- org.springframework.boot:spring-boot-starter:2.0.0.RELEASE ()
| +--- org.springframework.boot:spring-boot-actuator-autoconfigure:2.0.0.RELEASE
| | +--- org.springframework.boot:spring-boot-actuator:2.0.0.RELEASE
| | | --- org.springframework.boot:spring-boot:2.0.0.RELEASE ()
| | +--- org.springframework.boot:spring-boot-autoconfigure:2.0.0.RELEASE ()
| | +--- com.fasterxml.jackson.core:jackson-databind:2.9.4 ()
| | +--- org.springframework:spring-core:5.0.4.RELEASE ()
| | +--- org.springframework:spring-context:5.0.4.RELEASE ()
| | --- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.4 ()
| --- io.micrometer:micrometer-core:1.0.1
| +--- org.hdrhistogram:HdrHistogram:2.1.10
| --- org.latencyutils:LatencyUtils:2.0.3
+--- org.springframework.boot:spring-boot-starter-security:2.0.0.RELEASE
| +--- org.springframework.boot:spring-boot-starter:2.0.0.RELEASE ()
| +--- org.springframework:spring-aop:5.0.4.RELEASE ()
| +--- org.springframework.security:spring-security-config:5.0.3.RELEASE
| | +--- org.springframework.security:spring-security-core:5.0.3.RELEASE
| | | +--- org.springframework:spring-aop:5.0.4.RELEASE ()
| | | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | | +--- org.springframework:spring-context:5.0.4.RELEASE ()
| | | +--- org.springframework:spring-core:5.0.4.RELEASE ()
| | | --- org.springframework:spring-expression:5.0.4.RELEASE ()
| | +--- org.springframework:spring-aop:5.0.4.RELEASE ()
| | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | +--- org.springframework:spring-context:5.0.4.RELEASE ()
| | --- org.springframework:spring-core:5.0.4.RELEASE ()
| --- org.springframework.security:spring-security-web:5.0.3.RELEASE
| +--- org.springframework.security:spring-security-core:5.0.3.RELEASE ()
| +--- org.springframework:spring-aop:5.0.4.RELEASE ()
| +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| +--- org.springframework:spring-context:5.0.4.RELEASE ()
| +--- org.springframework:spring-core:5.0.4.RELEASE ()
| +--- org.springframework:spring-expression:5.0.4.RELEASE ()
| --- org.springframework:spring-web:5.0.4.RELEASE ()
+--- org.springframework.boot:spring-boot-starter-data-jpa:2.0.0.RELEASE
| +--- org.springframework.boot:spring-boot-starter:2.0.0.RELEASE ()
| +--- org.springframework.boot:spring-boot-starter-aop:2.0.0.RELEASE
| | +--- org.springframework.boot:spring-boot-starter:2.0.0.RELEASE ()
| | +--- org.springframework:spring-aop:5.0.4.RELEASE ()
| | --- org.aspectj:aspectjweaver:1.8.13
| +--- org.springframework.boot:spring-boot-starter-jdbc:2.0.0.RELEASE
| | +--- org.springframework.boot:spring-boot-starter:2.0.0.RELEASE ()
| | +--- com.zaxxer:HikariCP:2.7.8
| | | --- org.slf4j:slf4j-api:1.7.25
| | --- org.springframework:spring-jdbc:5.0.4.RELEASE
| | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | +--- org.springframework:spring-core:5.0.4.RELEASE ()
| | --- org.springframework:spring-tx:5.0.4.RELEASE
| | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | --- org.springframework:spring-core:5.0.4.RELEASE ()
| +--- org.hibernate:hibernate-core:5.2.14.Final
| | +--- org.jboss.logging:jboss-logging:3.3.1.Final -> 3.3.2.Final
| | +--- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final
| | +--- org.javassist:javassist:3.22.0-GA
| | +--- antlr:antlr:2.7.7
| | +--- org.jboss:jandex:2.0.3.Final
| | +--- com.fasterxml:classmate:1.3.0 -> 1.3.4
| | +--- dom4j:dom4j:1.6.1
| | --- org.hibernate.common:hibernate-commons-annotations:5.0.1.Final
| | --- org.jboss.logging:jboss-logging:3.3.0.Final -> 3.3.2.Final
| +--- javax.transaction:javax.transaction-api:1.2
| +--- org.springframework.data:spring-data-jpa:2.0.5.RELEASE
| | +--- org.springframework.data:spring-data-commons:2.0.5.RELEASE
| | | +--- org.springframework:spring-core:5.0.4.RELEASE ()
| | | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | | --- org.slf4j:slf4j-api:1.7.25
| | +--- org.springframework:spring-orm:5.0.4.RELEASE
| | | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | | +--- org.springframework:spring-core:5.0.4.RELEASE ()
| | | +--- org.springframework:spring-jdbc:5.0.4.RELEASE ()
| | | --- org.springframework:spring-tx:5.0.4.RELEASE ()
| | +--- org.springframework:spring-context:5.0.4.RELEASE ()
| | +--- org.springframework:spring-aop:5.0.4.RELEASE ()
| | +--- org.springframework:spring-tx:5.0.4.RELEASE ()
| | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | +--- org.springframework:spring-core:5.0.4.RELEASE ()
| | --- org.slf4j:slf4j-api:1.7.25
| --- org.springframework:spring-aspects:5.0.4.RELEASE
| --- org.aspectj:aspectjweaver:1.8.13
+--- nl.topicus:spanner-jdbc:1.0.8
+--- nl.topicus:spanner-hibernate:0.7
+--- org.hibernate:hibernate-java8:5.0.11.Final
| +--- org.jboss.logging:jboss-logging:3.3.0.Final -> 3.3.2.Final
| --- org.hibernate:hibernate-core:5.0.11.Final -> 5.2.14.Final ()
+--- io.springfox:springfox-swagger2:2.8.0
| +--- io.swagger:swagger-annotations:1.5.14
| +--- io.swagger:swagger-models:1.5.14
| | +--- com.fasterxml.jackson.core:jackson-annotations:2.8.7 -> 2.9.0
| | +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
| | --- io.swagger:swagger-annotations:1.5.14
| +--- io.springfox:springfox-spi:2.8.0
| | --- io.springfox:springfox-core:2.8.0
| | +--- net.bytebuddy:byte-buddy:1.7.9 -> 1.7.10
| | +--- com.google.guava:guava:20.0
| | +--- com.fasterxml:classmate:1.3.4
| | +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
| | +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE
| | | +--- org.springframework:spring-beans:4.0.9.RELEASE -> 5.0.4.RELEASE ()
| | | +--- org.springframework:spring-context:4.0.9.RELEASE -> 5.0.4.RELEASE ()
| | | +--- org.springframework:spring-aop:4.0.9.RELEASE -> 5.0.4.RELEASE ()
| | | --- org.slf4j:slf4j-api:1.7.10 -> 1.7.25
| | --- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE
| | +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE ()
| | --- org.slf4j:slf4j-api:1.7.10 -> 1.7.25
| +--- io.springfox:springfox-schema:2.8.0
| | +--- io.springfox:springfox-core:2.8.0 ()
| | --- io.springfox:springfox-spi:2.8.0 ()
| +--- io.springfox:springfox-swagger-common:2.8.0
| | +--- io.swagger:swagger-annotations:1.5.14
| | +--- io.swagger:swagger-models:1.5.14 ()
| | +--- io.springfox:springfox-spi:2.8.0 ()
| | +--- io.springfox:springfox-schema:2.8.0 ()
| | +--- io.springfox:springfox-spring-web:2.8.0
| | | +--- org.reflections:reflections:0.9.11
| | | | +--- com.google.guava:guava:20.0
| | | | --- org.javassist:javassist:3.21.0-GA -> 3.22.0-GA
| | | +--- com.google.guava:guava:20.0
| | | +--- com.fasterxml:classmate:1.3.4
| | | +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
| | | +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE ()
| | | +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE ()
| | | --- io.springfox:springfox-spi:2.8.0 ()
| | +--- com.google.guava:guava:20.0
| | +--- com.fasterxml:classmate:1.3.4
| | +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
| | +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE ()
| | --- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE ()
| +--- io.springfox:springfox-spring-web:2.8.0 ()
| +--- com.google.guava:guava:20.0
| +--- com.fasterxml:classmate:1.3.4
| +--- org.slf4j:slf4j-api:1.7.24 -> 1.7.25
| +--- org.springframework.plugin:spring-plugin-core:1.2.0.RELEASE ()
| +--- org.springframework.plugin:spring-plugin-metadata:1.2.0.RELEASE ()
| --- org.mapstruct:mapstruct:1.2.0.Final
+--- io.springfox:springfox-swagger-ui:2.8.0
| --- io.springfox:springfox-spring-web:2.8.0 ()
+--- io.micrometer:micrometer-registry-datadog:1.0.2
| +--- io.micrometer:micrometer-core:1.0.2 -> 1.0.1 ()
| +--- org.slf4j:slf4j-api:1.7.25
| --- org.apache.commons:commons-text:1.2
| --- org.apache.commons:commons-lang3:3.7
+--- net.logstash.logback:logstash-logback-encoder:5.0
| +--- ch.qos.logback:logback-core:1.2.3
| --- com.fasterxml.jackson.core:jackson-databind:2.9.4 ()
+--- net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1
| +--- org.springframework.boot:spring-boot-starter-web:2.0.0.RELEASE ()
| --- ch.qos.logback:logback-access:1.2.3
| --- ch.qos.logback:logback-core:1.2.3
+--- io.opencensus:opencensus-api:0.14.0
| +--- io.grpc:grpc-context:1.12.0
| --- com.google.guava:guava:20.0
+--- io.opencensus:opencensus-exporter-trace-stackdriver:0.14.0
| +--- io.opencensus:opencensus-api:0.14.0 ()
| +--- com.google.auth:google-auth-library-credentials:0.9.1
| --- com.google.cloud:google-cloud-trace:0.49.0-beta
| +--- com.google.cloud:google-cloud-core:1.31.0 -> 1.35.0
| | +--- com.google.guava:guava:20.0
| | +--- joda-time:joda-time:2.9.2 -> 2.9.9
| | +--- com.google.http-client:google-http-client:1.23.0
| | | --- org.apache.httpcomponents:httpclient:4.0.1 -> 4.5.5
| | | +--- org.apache.httpcomponents:httpcore:4.4.9
| | | --- commons-codec:commons-codec:1.10 -> 1.11
| | +--- com.google.api:api-common:1.6.0
| | | --- com.google.guava:guava:19.0 -> 20.0
| | +--- com.google.api:gax:1.28.0
| | | +--- com.google.guava:guava:20.0
| | | +--- org.threeten:threetenbp:1.3.3
| | | +--- com.google.auth:google-auth-library-oauth2-http:0.9.1
| | | | +--- com.google.auth:google-auth-library-credentials:0.9.1
| | | | +--- com.google.http-client:google-http-client:1.19.0 -> 1.23.0 ()
| | | | +--- com.google.http-client:google-http-client-jackson2:1.19.0
| | | | | +--- com.google.http-client:google-http-client:1.19.0 -> 1.23.0 ()
| | | | | --- com.fasterxml.jackson.core:jackson-core:2.1.3 -> 2.9.4
| | | | --- com.google.guava:guava:19.0 -> 20.0
| | | --- com.google.api:api-common:1.6.0 ()
| | +--- com.google.protobuf:protobuf-java-util:3.5.1
| | | +--- com.google.protobuf:protobuf-java:3.5.1
| | | +--- com.google.guava:guava:19.0 -> 20.0
| | | --- com.google.code.gson:gson:2.7 -> 2.8.2
| | +--- com.google.api.grpc:proto-google-common-protos:1.11.0
| | | --- com.google.protobuf:protobuf-java:3.5.1
| | --- com.google.api.grpc:proto-google-iam-v1:0.12.0
| | +--- com.google.protobuf:protobuf-java:3.5.1
| | +--- com.google.api:api-common:1.5.0 -> 1.6.0 ()
| | --- com.google.api.grpc:proto-google-common-protos:1.11.0 ()
| +--- com.google.cloud:google-cloud-core-grpc:1.31.0 -> 1.35.0
| | +--- com.google.auth:google-auth-library-credentials:0.9.1
| | +--- com.google.cloud:google-cloud-core:1.35.0 ()
| | +--- com.google.guava:guava:20.0
| | +--- com.google.protobuf:protobuf-java:3.5.1
| | +--- com.google.protobuf:protobuf-java-util:3.5.1 ()
| | +--- io.grpc:grpc-protobuf:1.12.0
| | | +--- io.grpc:grpc-core:1.12.0
| | | | +--- io.grpc:grpc-context:1.12.0
| | | | +--- com.google.code.gson:gson:2.7 -> 2.8.2
| | | | +--- com.google.guava:guava:20.0
| | | | +--- com.google.errorprone:error_prone_annotations:2.1.2
| | | | +--- io.opencensus:opencensus-api:0.11.0 -> 0.14.0 ()
| | | | --- io.opencensus:opencensus-contrib-grpc-metrics:0.11.0
| | | | --- io.opencensus:opencensus-api:0.11.0 -> 0.14.0 ()
| | | +--- com.google.protobuf:protobuf-java:3.5.1
| | | +--- com.google.guava:guava:20.0
| | | +--- com.google.protobuf:protobuf-java-util:3.5.1 ()
| | | +--- com.google.api.grpc:proto-google-common-protos:1.0.0 -> 1.11.0 ()
| | | --- io.grpc:grpc-protobuf-lite:1.12.0
| | | +--- io.grpc:grpc-core:1.12.0 ()
| | | --- com.google.guava:guava:20.0
| | +--- io.grpc:grpc-context:1.12.0
| | +--- io.grpc:grpc-netty-shaded:1.12.0
| | | --- io.grpc:grpc-core:[1.12.0] -> 1.12.0 ()
| | +--- io.grpc:grpc-stub:1.12.0
| | | --- io.grpc:grpc-core:1.12.0 ()
| | +--- io.grpc:grpc-auth:1.12.0
| | | +--- io.grpc:grpc-core:[1.12.0] -> 1.12.0 ()
| | | --- com.google.auth:google-auth-library-credentials:0.9.0 -> 0.9.1
| | --- com.google.api:gax-grpc:1.28.0
| | +--- com.google.api:gax:1.28.0 ()
| | +--- io.grpc:grpc-stub:1.10.1 -> 1.12.0 ()
| | +--- io.grpc:grpc-auth:1.10.1 -> 1.12.0 ()
| | +--- io.grpc:grpc-protobuf:1.10.1 -> 1.12.0 ()
| | +--- com.google.guava:guava:20.0
| | +--- org.threeten:threetenbp:1.3.3
| | +--- com.google.auth:google-auth-library-oauth2-http:0.9.1 ()
| | +--- com.google.auth:google-auth-library-credentials:0.9.1
| | +--- com.google.api.grpc:proto-google-common-protos:1.0.0 -> 1.11.0 ()
| | --- com.google.api:api-common:1.6.0 ()
| +--- com.google.api.grpc:proto-google-cloud-trace-v1:0.14.0
| | +--- com.google.protobuf:protobuf-java:3.5.1
| | +--- com.google.api:api-common:1.5.0 -> 1.6.0 ()
| | --- com.google.api.grpc:proto-google-common-protos:1.11.0 ()
| +--- com.google.api.grpc:proto-google-cloud-trace-v2:0.14.0
| | +--- com.google.protobuf:protobuf-java:3.5.1
| | +--- com.google.api:api-common:1.5.0 -> 1.6.0 ()
| | --- com.google.api.grpc:proto-google-common-protos:1.11.0 ()
| +--- io.grpc:grpc-netty-shaded:1.10.1 -> 1.12.0 ()
| +--- io.grpc:grpc-stub:1.10.1 -> 1.12.0 ()
| --- io.grpc:grpc-auth:1.10.1 -> 1.12.0 ()
+--- io.opencensus:opencensus-impl:0.14.0
| +--- io.opencensus:opencensus-api:0.14.0 ()
| +--- io.opencensus:opencensus-impl-core:0.14.0
| | +--- io.opencensus:opencensus-api:0.14.0 ()
| | --- com.google.guava:guava:20.0
| --- com.lmax:disruptor:3.4.1
+--- nl.topicus.spanner.flyway:flyway-core:0.1.0
+--- org.springframework.cloud:spring-cloud-gcp-starter-pubsub:1.1.0.M1
| +--- org.springframework.cloud:spring-cloud-gcp-starter:1.1.0.M1
| | +--- org.springframework.cloud:spring-cloud-gcp-core:1.1.0.M1
| | | +--- com.google.cloud:google-cloud-core:1.35.0 ()
| | | +--- org.springframework:spring-core:5.0.7.RELEASE -> 5.0.4.RELEASE ()
| | | +--- org.springframework:spring-context:5.0.7.RELEASE -> 5.0.4.RELEASE ()
| | | --- org.slf4j:slf4j-api:1.7.25
| | +--- org.springframework.cloud:spring-cloud-gcp-autoconfigure:1.1.0.M1
| | | +--- org.springframework.boot:spring-boot-autoconfigure:2.0.3.RELEASE -> 2.0.0.RELEASE ()
| | | +--- org.springframework.cloud:spring-cloud-gcp-core:1.1.0.M1 ()
| | | --- org.slf4j:slf4j-api:1.7.25
| | +--- org.springframework.boot:spring-boot-starter:2.0.3.RELEASE -> 2.0.0.RELEASE ()
| | --- org.slf4j:slf4j-api:1.7.25
| +--- org.springframework.cloud:spring-cloud-gcp-pubsub:1.1.0.M1
| | +--- com.google.cloud:google-cloud-pubsub:1.35.0
| | | +--- com.google.cloud:google-cloud-core:1.35.0 ()
| | | +--- com.google.cloud:google-cloud-core-grpc:1.35.0 ()
| | | +--- com.google.api.grpc:proto-google-cloud-pubsub-v1:1.17.0
| | | | +--- com.google.protobuf:protobuf-java:3.5.1
| | | | +--- com.google.api:api-common:1.6.0 ()
| | | | +--- com.google.api.grpc:proto-google-common-protos:1.11.0 ()
| | | | --- com.google.api.grpc:proto-google-iam-v1:0.12.0 ()
| | | +--- com.google.api.grpc:grpc-google-cloud-pubsub-v1:1.17.0
| | | | +--- io.grpc:grpc-stub:1.10.1 -> 1.12.0 ()
| | | | +--- io.grpc:grpc-protobuf:1.10.1 -> 1.12.0 ()
| | | | --- com.google.api.grpc:proto-google-cloud-pubsub-v1:1.17.0 ()
| | | +--- io.grpc:grpc-netty-shaded:1.12.0 ()
| | | +--- io.grpc:grpc-stub:1.12.0 ()
| | | +--- io.grpc:grpc-auth:1.12.0 ()
| | | --- com.google.auto.value:auto-value:1.4
| | +--- org.springframework.cloud:spring-cloud-gcp-core:1.1.0.M1 ()
| | --- org.slf4j:slf4j-api:1.7.25
| --- org.slf4j:slf4j-api:1.7.25
+--- org.springframework.integration:spring-integration-core:5.0.3.RELEASE
| +--- org.springframework:spring-core:5.0.4.RELEASE ()
| +--- org.springframework:spring-aop:5.0.4.RELEASE ()
| +--- org.springframework:spring-context:5.0.4.RELEASE ()
| +--- org.springframework:spring-messaging:5.0.4.RELEASE
| | +--- org.springframework:spring-beans:5.0.4.RELEASE ()
| | --- org.springframework:spring-core:5.0.4.RELEASE ()
| +--- org.springframework:spring-tx:5.0.4.RELEASE ()
| +--- org.springframework.retry:spring-retry:1.2.2.RELEASE
| +--- io.projectreactor:reactor-core:3.1.5.RELEASE
| | --- org.reactivestreams:reactive-streams:1.0.2
| --- io.micrometer:micrometer-core:1.0.1 (*)
--- org.projectlombok:lombok:1.16.18

**Comment by jags1** [comment]
Windows user java version - 1.8.0_45 and no issue with windows.

**Comment by carl-mastrangelo** [comment]
Did you try adding a dependency on netty-tcnative?

**Comment by zpencer** [comment]
@jags1 you can look at this doc for more details on how to add netty-tcnative:
https://github.com/grpc/grpc-java/blob/master/SECURITY.md
