### ISSUE TITLE
Server returns batches of `Half-closed without a request` responses to client

### ISSUE THREAD

**Issue by mkaminski1988** [grpc/grpc-java#4890]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.11

### What did you expect to see?
We expect to see no error message, or at least a better explanation about what is occurring.

These errors seem to correlate with increased latency. We have a Finagle client that connects to Envoy, which forwards to requests to the gRPC service. I've dug through the code and don't really understand how this situation would arise.

**Comment by carl-mastrangelo** [comment]
Is it possible envoy is sending a RST_STREAM to the gRPC server after timing out?  Do you have a timeout/deadline in your Envoy configuration?

**Comment by ejona86** [comment]
I don't think RST_STREAM could cause this. This is simply there was no request message for a unary call. That would happen if the request body was dropped by a proxy.

**Comment by zhangkun83** [comment]
Can you provide repro steps, such as a docker image?

**Comment by mkaminski1988** [comment]
Thanks for getting back to me. Will follow up later this week

**Comment by ejona86** [comment]
@mkaminski1988, friendly ping.

**Comment by ejona86** [comment]
@mkaminski1988, friendly ping. This is likely a proxy issue, but we can help diagnose what is going wrong and work with Envoy or whoever else. But being able to reproduce it would be necessary.

**Comment by mkaminski1988** [comment]
Sorry to leave you hanging. I determined the cause to be the client hanging up before the server could respond. Thanks everyone.
