### ISSUE TITLE
CallCredentials interface, 2nd edition

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#4901]
Security level and authority are parameters required to be passed to applyRequestMetadata(). We will wrap them, along with MethodDescriptor and the transport attributes, to a first-class object `RequestInfo`, which is more clear to the implementers than via `Attributes`.

`ATTR_SECURITY_LEVEL` will be moved to the internal `GrpcAttributes` and annotated as `TransportAttr`, because transports are required to set it, but no user is actually reading them from
`{Client,Server}Call.getAttributes()`.

`ATTR_AUTHORITY` should be removed, because no transport is overriding it.

This is an API-breaking change because `CallCredentials` is `interface`. It will be changed to abstract class, so that further API changes can be done in multiple steps without breaking implementations.

The CallCredentials name is stabilized, thus it must be the name of the new interface. We will take the following steps to finish the change.

1. Introduce `CallCredentials2`, which is the new API, which implements the old `CallCredentials`. Change all stock implementations to it. Deprecate the old `CallCredentials`.
2. Make a release, and ask all implementations (including [FirestoreCallCredentials](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreCallCredentials.java)) to implement `CallCredentials2` instead.
3. Replace `CallCredentials` with `CallCredentials2`, keeping `CallCredentials2` as an alias.
4. Make a release, and ask all implementations (including FirestoreCallCredentials) to switch back to the name `CallCredentials`.
5. Delete the alias `CallCredentials2`

During the whole process, the name `CallCredentials` stays usable, and we require no change in code that passes `CallCredentials` objects along.

/cc @ejona86

**Comment by ejona86** [comment]
As discussed some in https://github.com/grpc/grpc-java/issues/5002#issuecomment-433531077, it is fine if CallCredentials implementations _don't_ migrate to CallCredentials2 and just accept the breakage when it comes with 1.17.0.

**Comment by carl-mastrangelo** [comment]
@zhangkun83 ping on this.  Can it be marked complete?

**Comment by zhangkun83** [comment]
The only remaining item is "5. Delete the alias CallCredentials2"

**Comment by carl-mastrangelo** [comment]
@zhangkun83 I think this should get some attention, as it has been on the todo list for a while.

**Comment by ejona86** [comment]
We should have a few releases before removing CallCredentials2, since #5216 was only recent.

**Comment by ejona86** [comment]
CallCredentials2 delete is being reverted in #8475

**Comment by ejona86** [comment]
CallCredentials2 re-delete was in #8572
