### ISSUE TITLE
Mutual TLS instructional code in Readme is wrong.

### ISSUE THREAD

**Issue by isheff** [grpc/grpc-java#4905]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
[1.15](https://github.com/grpc/grpc-java/tree/7d455964f601ce9d3bdd57e79f0c7b0c065b2ce3)

### What did you expect to see?
Example code in the [Readme](https://github.com/grpc/grpc-java/blob/7d455964f601ce9d3bdd57e79f0c7b0c065b2ce3/README.md) should compile without errors?

### What did you see?
Errors ranging from a simple missed semicolon, to a method that doesn't exist, and an undefined variable.

#### More specifically:

While trying to implement Mutual TLS and retrieve the client credentials serverside, I followed the [Readme](https://github.com/grpc/grpc-java/blob/7d455964f601ce9d3bdd57e79f0c7b0c065b2ce3/README.md) instructional example, which (amongst other things), suggests a `ServerInterceptor`, specifically:
```java
public final static Context.Key<SSLSession> SSL_SESSION_CONTEXT = Context.key("SSLSession");

@Override
public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<RespT> call, 
    Metadata headers, ServerCallHandler<ReqT, RespT> next) {
    SSLSession sslSession = call.attributes().get(Grpc.TRANSPORT_ATTR_SSL_SESSION);
    if (sslSession == null) {
        return next.startCall(call, headers)
    }
    return Contexts.interceptCall(
        Context.current().withValue(SSL_SESSION_CONTEXT, clientContext), call, headers, next);
}
```

This doesn't actually compile. Errors include:
  - There is no semicolon at the end of the first return line.
  - `ServerCall` requries 2 type arguments, not 1.
  - `ServerCall.attributes` does not exist.
  - `clientContext` is an undefined variable.

### Proposed Fix
Perhaps the example code in the [Readme](https://github.com/grpc/grpc-java/blob/7d455964f601ce9d3bdd57e79f0c7b0c065b2ce3/README.md) can be changed to the following, which does compile:
```java
import static io.grpc.Grpc.TRANSPORT_ATTR_SSL_SESSION;

import javax.net.ssl.SSLSession;

import io.grpc.Context;
import io.grpc.Contexts;
import io.grpc.Metadata;
import io.grpc.ServerCall;
import io.grpc.ServerCallHandler;
import io.grpc.ServerInterceptor;

/**
 * A ServerInterceptor which for each call, adds to the current context the sslContext featuring client authentication stuff.
 * The Key for this is SSL_SESSION_CONTEXT, and its type is SSLSession.
 */
public class MutualTLSContextInterceptor implements ServerInterceptor {

  /** The key for the SSLSession (featuring client authentication stuff) in the gRPC current context */
  public final static Context.Key<SSLSession> SSL_SESSION_CONTEXT = Context.key("SSLSession");

  /**
   * For each call made to the server, extract the sslSession, and add it to the gRPC current context.
   * @param call object to receive response messages
   * @param  headers which can contain extra call metadata from
   *                 ClientCall.start(io.grpc.ClientCall.Listener<RespT>, io.grpc.Metadata),
   *                 e.g. authentication credentials.
   * @param next - next processor in the interceptor chain
   * @return listener for processing incoming messages for call, never null.
   */
  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, 
                                                               Metadata headers,
                                                               ServerCallHandler<ReqT, RespT> next) {
    SSLSession sslSession = call.getAttributes().get(TRANSPORT_ATTR_SSL_SESSION);
    if (sslSession == null) {
      return next.startCall(call, headers);
    }
    return Contexts.interceptCall(
      Context.current().withValue(SSL_SESSION_CONTEXT, sslSession), call, headers, next);
  }
}
```

**Comment by carl-mastrangelo** [comment]
@isheff Want to send a PR?

**Comment by isheff** [comment]
@carl-mastrangelo I submitted pull request https://github.com/grpc/grpc-java/pull/4926 , which makes the naive change.

**Comment by zpencer** [comment]
I would like to do a minor clean up on HelloWorldTLS, so I'll add the your updated interceptor while I do that.

**Comment by isheff** [comment]
The[ current documentation](https://github.com/grpc/grpc-java/blob/2f50d88678a4491a07cca97d366bd919f8535720/SECURITY.md) still has this problem.

A[ relevant PR](https://github.com/grpc/grpc-java/pull/4926) was closed for inactivity, with @ejona86 stating the proposed changes were [too large](https://github.com/grpc/grpc-java/pull/4926#pullrequestreview-177461024). 

Any progress?

**Comment by ejona86** [comment]
Sent out #5444
