### ISSUE TITLE
how to set default window size in okhttp?

### ISSUE THREAD

**Issue by wangdingwei** [grpc/grpc-java#4921]
how to set default window size in okhttp?

**Comment by zhangkun83** [comment]
@ejona86, it doesn't seem possible, right?

**Comment by creamsoup** [comment]
currently, it is not possible to change the default window size (64k) in okhttp. 
supporting this is not hard, but I want to ask why you want to increase the window size? in typical android environment, we don't expect to change this value. but if there's valid use case, we can consider exposing it.
