### ISSUE TITLE
Configure repo to recognize Googlers as CLA approved

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#4924]
Specifically, if a user is a member of google or GoogleCloudPlatform on Github, they should not need to sign a separate CLA.

**Comment by ejona86** [comment]
Googlers don't need to/shouldn't sign a CLA. They should only log in to the CLA page with their Google account.

Being a member of Google or GCP orgs on GitHub does not mean someone is a Googler. So this doesn't seem feasible.
