### ISSUE TITLE
[question] Why does grpc-all depend on protobuf-nano not protobuf-lite

### ISSUE THREAD

**Issue by honnix** [grpc/grpc-java#4934]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.15.1

### What did you expect to see?
As I understood, `grpc-protobuf-lite` should be preferred over `grpc-protobuf-nano` for Android. Also I understand that `grpc-all` is not recommended to depend on, instead of it's better to explicitly depend on necessary parts.

My question is why `grpc-all` depends on `grpc-protobuf-nano` not `grpc-protobuf-lite`. Is it because of backward compatibility?

Thanks.

**Comment by ejona86** [comment]
It depends on both, because grpc-protobuf depends on grpc-protobuf-lite. It doesn't depend _explicitly_ on grpc-protobuf-lite because grpc-protobuf excludes the protobuf-lite dependency and uses full protobuf instead.

And yes, Nano is dead; lite is the proper one to use.
