### ISSUE TITLE
too many exec threads keep memory leak

### ISSUE THREAD

**Issue by shibo420** [grpc/grpc-java#4935]
hi

i use grpc which version is 1.11.0 
when i test the server's stablity ,make about 16000 connects ,there are too many exec threads to handle message ,moreover, the memory used  80%, it's very slowly ,and memory  keeps growth

could you give some solutions about this issue?

think you~

**Comment by carl-mastrangelo** [comment]
@shibo420 Are you using Netty, or OkHTTP?  Did you make sure to set the `Executor` on your `ServerBuilder` and `ManagedChannelBuilder` ?

**Comment by ejona86** [comment]
@shibo420, friendly ping.

**Comment by ejona86** [comment]
Closing due to non-reply. If we get more information we can reopen.

**Comment by shibo420** [comment]
thanks for you reply .i try it
