### ISSUE TITLE
Loading service providers from a hard-coded list only works with non-shaded netty version

### ISSUE THREAD

**Issue by nbransby** [grpc/grpc-java#4982]
Isn't this missing the shaded package name?

https://github.com/grpc/grpc-java/blob/b64cde1488a69559386a56a4a809d2e6046c4c18/core/src/main/java/io/grpc/ManagedChannelProvider.java#L112

**Comment by ejona86** [comment]
We don't officially support Netty on Android, which is where the hard-coded list is used. You're saying:
1. You're on Android
2. You want to use Netty
3. You need to use shaded Netty

It would be easy to add another check for grpc-netty-shaded, but it's also an exceedingly rare use-case. If you want it, would you mind sending a PR?

**Comment by nbransby** [comment]
At this point in time I am fine using non-shaded Netty but if that changes I will make a PR, Thanks
