### ISSUE TITLE
1.13.2 - 1.15.1: 0.18.0 Bazel build fails - OkHttpClientTransport access guard failure

### ISSUE THREAD

**Issue by btbuxton** [grpc/grpc-java#4985]
### What version of gRPC are you using?
The problem occurs on version 1.13.2 through 1.15.1 of gRPC. Using bazel 0.18.0 on OpenJDK 10. The output of bazel info is at end of this issue.

### What did you expect to see?
No build error in bazel. The workaround for now is to put 'build --javacopt="-XepDisableAllChecks"' in .bazelrc or on command line

### This is the output of the build error that is seen:

ERROR: /private/var/tmp/_bazel_bbuxton/ca0a0f1185548889895b36bee140b99b/external/io_grpc_grpc_java/okhttp/BUILD.bazel:1:1: Building external/io_grpc_grpc_java/okhttp/libokhttp-class.jar (35 source files) failed (Exit 1)
external/io_grpc_grpc_java/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java:350: error: [GuardedBy] This access should be guarded by 'this.lock', which is not currently held
        transportTracer);
        ^
    (see https://errorprone.info/bugpattern/GuardedBy)

$ bazel version
WARNING: failed to raise resource limit 8 to 32768: Invalid argument
WARNING: Processed legacy workspace file /Users/bbuxton/git/services/sfdc-bazel/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
Build label: 0.18.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 15 08:33:10 2018 (1539592390)
Build timestamp: 1539592390
Build timestamp as int: 1539592390

$ bazel info
java-runtime: OpenJDK Runtime Environment (build 9.0.7.1+1) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 9.0.7.1+1, mixed mode) by Azul Systems, Inc.
max-heap-size: 3817MB
release: release 0.18.0

bazel build rule:
git_repository(
    name = "io_grpc_grpc_java",
    remote = "https://github.com/grpc/grpc-java.git",
    commit = "6657c310947bc61fcc579e31de2c3c113bc238b3", # 1.15.1
    # commit = "1b185c8c98796ae6456afb61b135a2d94c687fc4", # 1.13.2
)
load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")

grpc_java_repositories(
    omit_com_google_api_grpc_google_common_protos=False,
    omit_com_google_auth_google_auth_library_credentials=False,
    omit_com_google_code_findbugs_jsr305=True,
    omit_com_google_code_gson=True,
    omit_com_google_errorprone_error_prone_annotations=True,
    omit_com_google_guava=True,
    omit_com_google_protobuf=True,
    omit_com_google_protobuf_javalite=True,
    omit_com_google_protobuf_nano_protobuf_javanano=False,
    omit_com_google_truth_truth=False,
    omit_com_squareup_okhttp=False,
    omit_com_squareup_okio=False,
    omit_io_netty_buffer=True,
    omit_io_netty_common=True,
    omit_io_netty_transport=True,
    omit_io_netty_codec=True,
    omit_io_netty_codec_socks=True,
    omit_io_netty_codec_http=True,
    omit_io_netty_codec_http2=True,
    omit_io_netty_handler=True,
    omit_io_netty_handler_proxy=True,
    omit_io_netty_resolver=True,
    omit_io_netty_tcnative_boringssl_static=False,
    omit_io_opencensus_api=False,
    omit_io_opencensus_grpc_metrics=False,
    omit_junit_junit=True,
    omit_org_apache_commons_lang3=True,
)

**Comment by dapengzhang0** [comment]
This issue is fixed by #4965.
