### ISSUE TITLE
Shaded source jars do not contain any files

### ISSUE THREAD

**Issue by rdingwell** [grpc/grpc-java#5028]
The source jars that are associated with the gprc-netty-shaded packages do not contain any source files.  Seeing how the package names are rewritten when the jar is created this makes it extremely difficult to debug issues when using libraries that make use of the shaded jar.   

### What version of gRPC are you using?
Seems to apply to any version of shaded jars

### What did you expect to see?
a jar file that contains the source code for the classes contained in the shaded jar, with the same package renaming that occurs in the classes jar

**Comment by ejona86** [comment]
Yes, it is a problem. I looked into it some earlier and it seems hard to fix. The rewriting tools work on bytecode, not on source code.

It seems like this would require https://github.com/johnrengelman/shadow/issues/41 . Apparently the maven shade plugin can provide a feature like this, but it doesn't seem a Gradle plugin does.

Without our tooling supporting this, this seems infeasible (at least from the perspective of grpc-java).
