### ISSUE TITLE
how to handle "DEADLINE_EXCEEDED"

### ISSUE THREAD

**Issue by kiddot** [grpc/grpc-java#5034]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.13.1

### What did you expect to see?
sometime i will meet the exception when i try to request ; how to handle it ? thanks
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9996417917ns ;

**Comment by carl-mastrangelo** [comment]
@kiddot You will need to either retry the request in a backoff loop, or fail and retry at a higher layer.   If you provide more details about  your usage, we can give you a better answer.

**Comment by kiddot** [comment]
@carl-mastrangelo thanks
