### ISSUE TITLE
UINT32 data converion is taking the value as integer.

### ISSUE THREAD

**Issue by K-urien** [grpc/grpc-java#5040]
### What version of gRPC are you using?
protobuf-java-3.1.0.jar

### What did you expect to see?
in proto file filed is mentioned as UINT32 and the value after  DynamicMessage.parseFrom(,); coming as integer and its wrong;

**Comment by K-urien** [comment]
![image](https://user-images.githubusercontent.com/44828240/48113063-27b99d80-e27f-11e8-840b-5afe1ad5b2ca.png)

**Comment by carl-mastrangelo** [comment]
@K-urien can you show us your proto?

Also, this probably should be on the [protobuf-mailing list](https://groups.google.com/forum/#!forum/protobuf), since gRPC isn't really involved in the proto code.
