### ISSUE TITLE
Broken null check in MetadataUtils

### ISSUE THREAD

**Issue by ST-DDT** [grpc/grpc-java#5045]
https://github.com/grpc/grpc-java/blob/a7196eb3117df0bfec58578e3179197d4e1f4a69/stub/src/main/java/io/grpc/stub/MetadataUtils.java#L68

Should be 
````java
this.extraHeaders = checkNotNull(extraHeaders, "extraHeaders");
````

**Comment by carl-mastrangelo** [comment]
@ST-DDT Yep, that's a bug.  Want to send a PR?

**Comment by ST-DDT** [comment]
Done
