### ISSUE TITLE
"unknown enum constant" warnings when building with Bazel

### ISSUE THREAD

**Issue by drigz** [grpc/grpc-java#5046]
If I run `bazel build //...` in grpc-java at HEAD (or v1.16.1) I see many warnings like this:

```
INFO: From Building core/libinternal.jar (110 source files):
warning: unknown enum constant ReflectionSupport$Level.FULL
  reason: class file for com.google.j2objc.annotations.ReflectionSupport$Level not found
```

This was discussed on https://github.com/bazelbuild/bazel/issues/6414 and is due to a missing compile-time dependency of guava on j2objc.

### What version of gRPC are you using?
HEAD

### What did you expect to see?
No warnings when building.

**Comment by carl-mastrangelo** [comment]
cc: @ericgribkoff
