### ISSUE TITLE
Move BufferingHttp2ConnectionEncoder upstream to Netty

### ISSUE THREAD

**Issue by Scottmitch** [grpc/grpc-java#506]
[BufferingHttp2ConnectionEncoder](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/transport/netty/BufferingHttp2ConnectionEncoder.java) is solving a relatively generic use case.  I would like to explore the possibility of this class being extracted out of gRPC and contributed upstream to Netty.

**Comment by nmittler** [comment]
@Scottmitch yep, this has been on our TODO list for a while :)

**Comment by nmittler** [comment]
FYI, created Netty PR https://github.com/netty/netty/pull/3856

**Comment by nmittler** [comment]
Resolved by Netty PR https://github.com/netty/netty/pull/3856.  We will absorb this change after Netty releases 4.1.Beta6.
