### ISSUE TITLE
Remove Census dependency from grpc-core

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#5076]
Census is an implicit dependency today and automatically enables itself if Census is included on the classpath. This was because that behavior was a "requirement."

I've since learned that other languages didn't implement that "requirement." If we kicked census out of grpc-core, it would be possible to add grpc-context back into grpc-core to resolve #2727 and #3522 and similar. (The general idea here is that internal could also be moved out of grpc-core, so Context-only users don't pull in as much code.)

Unfortunately that puts us in a bit of a bind for existing users, as they will probably expect that they can enable Census classloader-wide without code changes to each call site.

A possible solution to that is to provide a global interceptor API, where we allow exactly one call to a method that sets the global interceptors that are used for all Channels. The expectation is that this method would be called in main().

Another option is to add a grpc-census artifact that grpc-core looks for and uses if available via reflection. That would certainly be easier for users to update.

**Comment by ejona86** [comment]
Since this was filed, we split grpc-api out of grpc-core. So this no longer has impact on context-only users. Although we still want it because the Census dependency does cause trouble and feels wrong to be in core. For example removing the dependency could be a solution to #5510.

**Comment by bogdandrutu** [comment]
@ejona86 this can be closed now I think.

**Comment by ejona86** [comment]
This was fixed by #6577
