### ISSUE TITLE
Conflict with protobufJava

### ISSUE THREAD

**Issue by SephirothLT** [grpc/grpc-java#5082]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.16.1
### What did you expect to see?
![image](https://user-images.githubusercontent.com/20485889/48880337-f201e080-ee4a-11e8-8c18-53c4a09ebbc2.png)

**Comment by zhangkun83** [comment]
@SephirothLT, what exactly error you are seeing? From the screenshot I don't see any problem. Different versions of protobuf-java may be pulled in because of dependencies, but a competent build system (such as Gradle or Maven) will resolve this.

**Comment by SephirothLT** [comment]
Thanks ，I have solved this problem!
