### ISSUE TITLE
Java Examples Version 1.18.0-SNAPSHOT fail to build

### ISSUE THREAD

**Issue by camposjorge** [grpc/grpc-java#5083]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Trying to use the grpc-java example with maven version 1.18.0-SNAPSHOT

### What did you expect to see?
Running the command the documentation states it should work. Although the 1.18.0-SNAPSHOT version is nowhere to be found in public repositories.

Do I need to build GRPC from scratch myself in order to use it?

```
$ mvn verify
$ # Run the server
$ mvn exec:java -Dexec.mainClass=io.grpc.examples.helloworld.HelloWorldServer
$ # In another terminal run the client
$ mvn exec:java -Dexec.mainClass=io.grpc.examples.helloworld.HelloWorldClient
```
Error:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building examples 1.18.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for io.grpc:grpc-netty-shaded:jar:1.18.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for io.grpc:grpc-protobuf:jar:1.18.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for io.grpc:grpc-stub:jar:1.18.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for io.grpc:grpc-alts:jar:1.18.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for io.grpc:grpc-testing:jar:1.18.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for io.grpc:grpc-netty:jar:1.18.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.371 s
[INFO] Finished at: 2018-11-22T08:59:00-08:00
[INFO] Final Memory: 10M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project examples: Could not resolve dependencies for project io.grpc:examples:jar:1.18.0-SNAPSHOT: The following artifacts could not be resolved: io.grpc:grpc-netty-shaded:jar:1.18.0-SNAPSHOT, io.grpc:grpc-protobuf:jar:1.18.0-SNAPSHOT, io.grpc:grpc-stub:jar:1.18.0-SNAPSHOT, io.grpc:grpc-alts:jar:1.18.0-SNAPSHOT, io.grpc:grpc-testing:jar:1.18.0-SNAPSHOT, io.grpc:grpc-netty:jar:1.18.0-SNAPSHOT: Could not find artifact io.grpc:grpc-netty-shaded:jar:1.18.0-SNAPSHOT -> [Help 1]
```

It simple doesn't work because the grpc version on public repositories is 1.16.1. 
So my question is: Is there a repository address which I can use in the pom.xml file to download the dependencies version 1.18.0-SNAPSHOT or do I really need to build it from scratch?

I also tried downgrading the version of GRPC in the pom file to 1.16.1 with no avail, some classes are missing.

The main page of the github page states to use the version 1.16.1 but the examples simple don't work with it.

**Comment by dapengzhang0** [comment]
@camposjorge xxx-x.x.x-SNAPSHOT is NEVER in the maven central repository, so if you are building **examples** from **master** branch, you need first build the entire *grpc library* and install it in your local maven repository, which is not straightforward. So as the first paragraph of `examples/README` says:

```
The examples require grpc-java to already be built.
You are strongly encouraged to check out a git release tag,
since there will already be a build of grpc available.
Otherwise you must follow COMPILING.
```

unless you are making contributions to grpc, you are strongly encouraged to check out a git release tag and then build examples.

**Comment by yuanwy** [comment]
It doesn't work for me. what should I resolve?

**Comment by sanjaypujare** [comment]
@yuanwy can you paste the error and logs?
