### ISSUE TITLE
package too big

### ISSUE THREAD

**Issue by caizhibiao** [grpc/grpc-java#5084]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.10.0

### What did you expect to see?
compress the code ,discard the useless code

I am using grpc 1.10.0
    compile 'io.grpc:grpc-stub:1.10.0'
    compile 'io.grpc:grpc-okhttp:1.10.0'
    compile 'io.grpc:grpc-protobuf-lite:1.10.0'

as you know ,it contains below jars:
okhttp-2.5.0.jar'
okio-1.13.0.jar'
guava-19.0.jar'
gson-2.7.jar'
jsr305-3.0.0.jar'
however, guava is too big , which is 2.2M. I am consider whether can provide a small guava that can be use.

**Comment by dapengzhang0** [comment]
@caizhibiao is it possible to use ProGuard shrinker to remove unused code and reduce your app size?

**Comment by ejona86** [comment]
If you care about size, you need to use ProGuard or similar. Most of Guava will be removed by the dead code elimination pass.

**Comment by ejona86** [comment]
Closing, because it is known that ProGuard or similar is necessary. If that doesn't work, @caizhibiao please comment again and we can reopen.
