### ISSUE TITLE
java_grpc_library output for maven

### ISSUE THREAD

**Issue by adibrastegarnia** [grpc/grpc-java#5091]
Hello, 

I used java_grpc_library to generate a grpc library for a project. I can use it in a bazel based project. My question is If want to publish it into the maven central repository what should I publish? I published a .jar file with a suffix (do_not_reference) but it doesn't detect it.

Thanks,
Adib

**Comment by carl-mastrangelo** [comment]
I think there may need to be a little more massaging of the data to get it to work.  The gRPC Jar should include just the stub `.class` files.  However, it has a dependency on the Protobuf jars, which include the proto `.class` files.  To combine these two together, you can define a `java_binary` rule, which will combine all the dependent jars.  You can refer to this jar as `foo_deploy.jar`, if the target name is `:foo`.

You can use  a  [genrule](https://docs.bazel.build/versions/master/be/general.html) to depend on the deploy jar, and then rename the jar appropriately.

**Comment by adibrastegarnia** [comment]
Thanks for your response. I will look into that.

**Comment by ejona86** [comment]
It seems this has been resolved.
