### ISSUE TITLE
Add example using #transportExecutor to apply Android socket tagging

### ISSUE THREAD

**Issue by MatFl** [grpc/grpc-java#5093]
### What version of gRPC are you using?
v1.16.1

On Android 8 (Oreo) devices the GRPC connections get closed when strict mode is enabled in the app.

> java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
> at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2012)
> at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
> at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
> at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
> at libcore.io.IoBridge.socket(IoBridge.java:667)
> at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
> at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
> at java.net.Socket.createImpl(Socket.java:484)
> at java.net.Socket.<init>(Socket.java:441)
> at java.net.Socket.<init>(Socket.java:248)
> at io.grpc.okhttp.OkHttpClientTransport$2.run(OkHttpClientTransport.java:467)
> at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
> at java.lang.Thread.run(Thread.java:764)

The same issue is logged for OkHTTP but they have not found a real solution so far:
https://github.com/square/okhttp/issues/3537
The workaround which they suggested does not apply to GRPC because for non-TLS sockets GRPC is not using a SocketFactory: https://github.com/grpc/grpc-java/blob/e7e88a9af81dd07d6ba5a6376391781fcaa9389c/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java#L494

**Comment by ericgribkoff** [comment]
Thanks for opening this issue. gRPC OkHttp does indeed support running with traffic stats in strict mode, via the following configuration:

gRPC's `OkHttpChannelBuilder` has a [`#transportExecutor`](https://grpc.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html#transportExecutor-java.util.concurrent.Executor-) method that lets you provide the executor service for transport operations, including creating the initial socket. The default executor used is created [here](https://github.com/grpc/grpc-java/blob/3ff4790212ec321bf47ad394d3dfb1a1c2ea0c75/okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java#L131), but if you replace this with your own `ThreadPoolExecutor` subclass, you can override its [`#beforeExecute`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#beforeExecute(java.lang.Thread,%20java.lang.Runnable)) method and set the traffic stats (e.g., [TrafficStats#setThreadStatsTag](https://developer.android.com/reference/android/net/TrafficStats#setThreadStatsTag(int))) there.

I will add such an executor to one of our Android examples to make this easier for future searchers to find.

**Comment by MatFl** [comment]
Thanks, I am looking forward to the example.

**Comment by voidzcy** [comment]
Please refer to examples/android/strictmode.

**Comment by ejona86** [comment]
Fixed by #5527
