### ISSUE TITLE
UNAVAILBLE "End of stream or ioexception"

### ISSUE THREAD

**Issue by pavanyadav** [grpc/grpc-java#5094]
DnsNameResolverProvider dnsNameResolverProvider = new DnsNameResolverProvider();

        channel = AndroidChannelBuilder.forAddress(host, port) // this is on by default
                .loadBalancerFactory(RoundRobinLoadBalancerFactory.getInstance())
                .nameResolverFactory(dnsNameResolverProvider)
                .usePlaintext(true).build();

I am getting "End of stream or ioexception" whenever i am trying to call any function from proto file

**Comment by carl-mastrangelo** [comment]
What language is the remote gRPC server written in?  Are there any proxies in the way?

**Comment by zhangkun83** [comment]
Not heard from OP yet. Closing it. Please re-open if you have additional information.
