### ISSUE TITLE
netty: Add test for h2c Upgrade

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#5102]
As discussed in #4612, `ProtocolNegotiatorsTest.httpProxy_completes` may be a good template.

**Comment by waveywaves** [comment]
@ejona86 I have started working on this. Anything I need to keep in mind before I start ?

**Comment by waveywaves** [comment]
@ejona86 I would like to work on this. Anything I need to keep in mind before I start ?

**Comment by ejona86** [comment]
Hmm... @carl-mastrangelo, was this done in #5341?

**Comment by carl-mastrangelo** [comment]
I thought it was, but that PR text doesn't mention `h2c` anywhere.   @waveywaves was the linked PR similar to what you were thinking?

**Comment by waveywaves** [comment]
Didn't know that there was already a merged PR on this @ejona86 . @carl-mastrangelo is there anything else I can help on, wrt this issue ?

**Comment by ejona86** [comment]
#5341 looks to have fixed this. It has HttpServerUpgradeHandler and all. Marking this fixed.
