### ISSUE TITLE
When does grpc support okhttp 3.0 

### ISSUE THREAD

**Issue by YilinYuan** [grpc/grpc-java#5103]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
grpc 1.6.1

### What did you expect to see?
grpc-okhttp of  grpc 1.6.1  contains okhttp 2.5.0 ,but I want to use okhttp 3.0 because I need use it for  andriod glide.     I can't compaile different  okhttp's version  for andriod 's app

**Comment by dapengzhang0** [comment]
There is no problem to use okhttp 3.0 and grpc-okhttp-1.6.1 in the same app. That is because grpc-okhttp manually shaded all necessary okhttp2 code that could conflict with okhttp3. Refer to discussions in #2999, #2549, #1628
