### ISSUE TITLE
Make proxy configuration channel specific

### ISSUE THREAD

**Issue by idelvall** [grpc/grpc-java#5113]
We are using gRPC in a java agent that is attached to our customers JVMs. The agent communicates via gRPC to our server for sending app usage metrics. 

The principal contract for our agent is to not adding any side effect into the instrumented application.

We have faced a customer environment, where the outgoing gRPC connection needs to go though a HTTPS proxy, in order to reach the internet. The customer application, on the other hand, establishes outgoing HTTP connections inside their local network that don't go though that proxy.

Given that gRPC proxy configuration is done via the standard system properties (https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html) that are system wide, we are unable to properly configure the gRPC client to use the proxy without adding the (terminal) side effect of forcing the other HTTP outgoing connections to go though that proxy.

This could be solved if the proxy configuration could be done specific to the gRPC channel.

- Any idea if/on-how i can make this work right now?
- Would you consider reducing the scope of the configuration to the channel instead using system wide configuration? If yes, i could work on it if you give me some guidance

Note: Proxy authenticator config is also system wide

### What version of gRPC are you using?
1.13.1

**Comment by idelvall** [comment]
Ok I was able to resolve this. I answer myself so maybe someone can benefit from this in the future.

After looking at the code I realized that this can be achieved by two means:
- By passing a `ProxySocketAddress` to the channel builder, for example via [`NettyChannelBuilder.forAddress(SocketAddress serverAddress)`](https://github.com/grpc/grpc-java/blob/b5acbedd55ff80142c5480e210cf452d81fdaf00/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L93)
- Or preferably, by registering (via the system loader mechanism) a custom [`DnsNameResolverProvider` ](https://github.com/grpc/grpc-java/blob/b7dc501bbe2a71273b782931d0e96d528946300a/core/src/main/java/io/grpc/internal/DnsNameResolverProvider.java) with max priority (`10`)  that uses a custom proxy detector, rather than the default one `GrpcUtil.getDefaultProxyDetector()` (that is configured via the system-wide standard parameters).

**Comment by idelvall** [comment]
If that information is accurate and complete, it would be a good idea to add it to the documentation

**Comment by idelvall** [comment]
Thanks, yes that is exactly the same issue. I will resume this effort and work on a PR

**Comment by zhangkun83** [comment]
Closed in favor of #5279
