### ISSUE TITLE
Could not find io.grpc:grpc-netty:1.18.0-SNAPSHOT.

### ISSUE THREAD

**Issue by sanjaypujare** [grpc/grpc-java#5115]
Please answer these questions before submitting your issue.

### What version of gRPC are you using? 
Latest HEAD

### What did you expect to see?
build to succeed. Why are we using SNAPSHOT versions here?

**Comment by creamsoup** [comment]
similar question was discussed before (#5083) which i think answers your question.

**Comment by sanjaypujare** [comment]
Hmmm, I was thinking if I am an app developer just using grpc-java (but not modifying it) I should be able to build examples without having to build grpc-java. In fact https://github.com/grpc/grpc-java/blob/master/COMPILING.md specifically says:

Building is only necessary if you are making changes to gRPC-Java.

which is a bit misleading in this context. But I can understand why the examples and grpc-java lib have to be in sync ie. we find it convenient to update dependent examples as soon as we make changes to grpc-java instead of waiting for the change to get into a release branch
