### ISSUE TITLE
Make ServerBuilder and ManagedChannelBuilder one time use

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#5139]
Calling ServerBuilder.build() multiple times has unclear expected results.   We should document that builders are one-time use unless specifically called out.

**Comment by carl-mastrangelo** [comment]
It is possible to support multiple builds, but it may be infeasible, due to shared state on the builders.

**Comment by ejona86** [comment]
We can't "change" the these APIs at this point. We do generally support multi-build, but it is something that frequently is broken without care (e.g., Binder, XdsServer).
