### ISSUE TITLE
Support for custom status codes

### ISSUE THREAD

**Issue by dconnelly** [grpc/grpc-java#515]
io.grpc.Status seems to be restricted to the built-in status codes provided, although javadoc suggests that new status codes can be used as long as they are not conflicting. Adding a factory method such as "Status.forCode" should be possible although this would require that the status code type be changed from an enum to integer constant. This may be a small price to pay for the added flexibility.

**Comment by ejona86** [comment]
Status is for a canonical status used by all gRPC servers and will only rarely be added to. I think you saw the comment "If new codes are added over time they must choose a numerical value that does not collide with any previously used value." This comment is not referring to applications adding codes, but gRPC as a whole adding new codes. The current set of codes should be able to appropriately describe almost any application status in a generic way.

For custom status information, use Metadata.

**Comment by dconnelly** [comment]
I assume a custom ServerInterceptor is required to set Metadata on a response. For convenience, would it make sense to allow Metadata to be attached to Status{Runtime}Exception?

**Comment by ejona86** [comment]
We could have Status-specific metadata attached to the Status, but I think at least @louiscryan doesn't think that gains too much. However, soon we hope to have a Context API (https://github.com/grpc/grpc-java/issues/262) that would be available via ThreadLocal and could be used by a ServerInterceptor to propagate information to the application.
