### ISSUE TITLE
NoClassDefFoundError: io/opencensus/trace/MessageEvent$Type

### ISSUE THREAD

**Issue by incogniro** [grpc/grpc-java#5160]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
<grpc.version>1.16.1</grpc.version>

### JDK on OSX
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28, mixed mode)

### What did you expect to see?

Receive the following exception when sending a message:

Exception in thread "main" java.lang.NoClassDefFoundError: io/opencensus/trace/MessageEvent$Type
	at io.grpc.internal.CensusTracingModule$ClientTracer.outboundMessageSent(CensusTracingModule.java:284)
	at io.grpc.internal.StatsTraceContext.outboundMessageSent(StatsTraceContext.java:181)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:161)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:53)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:422)
	at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
	at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:282)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:189)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:127)
	at pushnotification.PushNotificationServiceGrpc$PushNotificationServiceBlockingStub.notify(PushNotificationServiceGrpc.java:178)
	at pushnotification.PushNotificationClient.forward(PushNotificationClient.kt:56)
	at ApplicationHost.send(ApplicationHost.kt:103)
	at ApplicationHost.main(ApplicationHost.kt:90)
Caused by: java.lang.ClassNotFoundException: io.opencensus.trace.MessageEvent$Type
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more

However I can lookup and find the dependency for MessageEvent in: Maven: io.opencensus:opencensus-api:0.12.3

**Comment by zhangkun83** [comment]
Can you run `mvn dependency:tree` and post the printed trees that contain `opencensus`?

**Comment by incogniro** [comment]
[INFO] |  +- com.google.cloud:google-cloud-core-http:jar:1.31.0:compile
[INFO] |  |  +- (com.google.cloud:google-cloud-core:jar:1.31.0:compile - omitted for duplicate)
[INFO] |  |  +- com.google.auth:google-auth-library-credentials:jar:0.9.1:compile
[INFO] |  |  +- (com.google.auth:google-auth-library-oauth2-http:jar:0.9.1:compile - omitted for conflict with 0.9.0)
[INFO] |  |  +- (com.google.http-client:google-http-client:jar:1.23.0:compile - omitted for duplicate)
[INFO] |  |  +- com.google.oauth-client:google-oauth-client:jar:1.23.0:compile
[INFO] |  |  |  +- (com.google.http-client:google-http-client:jar:1.23.0:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.google.code.findbugs:jsr305:jar:1.3.9:compile - omitted for conflict with 3.0.1)
[INFO] |  |  +- (com.google.guava:guava:jar:20.0:compile - omitted for conflict with 25.1-android)
[INFO] |  |  +- com.google.api-client:google-api-client:jar:1.23.0:compile
[INFO] |  |  |  +- (com.google.oauth-client:google-oauth-client:jar:1.23.0:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.google.http-client:google-http-client-jackson2:jar:1.23.0:compile - omitted for conflict with 1.19.0)
[INFO] |  |  +- com.google.http-client:google-http-client-appengine:jar:1.23.0:compile
[INFO] |  |  |  \- (com.google.http-client:google-http-client:jar:1.23.0:compile - omitted for duplicate)
[INFO] |  |  +- com.google.http-client:google-http-client-jackson:jar:1.23.0:compile
[INFO] |  |  |  +- (com.google.http-client:google-http-client:jar:1.23.0:compile - omitted for duplicate)
[INFO] |  |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  |  +- com.google.http-client:google-http-client-jackson2:jar:1.23.0:compile
[INFO] |  |  |  +- (com.google.http-client:google-http-client:jar:1.23.0:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile - omitted for conflict with 2.4.4)
[INFO] |  |  +- com.google.api:gax-httpjson:jar:0.42.0:compile
[INFO] |  |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.0:compile - omitted for conflict with 3.0.1)
[INFO] |  |  |  +- (com.google.api:gax:jar:1.25.0:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.google.code.gson:gson:jar:2.7:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.google.guava:guava:jar:20.0:compile - omitted for conflict with 25.1-android)
[INFO] |  |  |  +- (org.threeten:threetenbp:jar:1.3.3:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.google.http-client:google-http-client:jar:1.23.0:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.google.auth:google-auth-library-oauth2-http:jar:0.9.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.google.auth:google-auth-library-credentials:jar:0.9.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.google.api:api-common:jar:1.5.0:compile - omitted for duplicate)
[INFO] |  |  +- io.opencensus:opencensus-api:jar:0.11.1:compile
[INFO] |  |  |  +- (com.google.errorprone:error_prone_annotations:jar:2.2.0:compile - omitted for conflict with 2.1.3)
[INFO] |  |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.grpc:grpc-context:jar:1.16.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.google.guava:guava:jar:19.0:compile - omitted for conflict with 25.1-android)
[INFO] |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.11.1:compile
[INFO] |  |     +- (com.google.errorprone:error_prone_annotations:jar:2.2.0:compile - omitted for conflict with 2.1.3)
[INFO] |  |     +- (com.google.code.findbugs:jsr305:jar:3.0.1:compile - omitted for duplicate)
[INFO] |  |     +- (io.opencensus:opencensus-api:jar:0.11.1:compile - omitted for duplicate)
[INFO] |  |     \- (com.google.guava:guava:jar:19.0:compile - omitted for conflict with 25.1-android)

and

[INFO] +- io.grpc:grpc-protobuf:jar:1.16.1:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.16.1:compile
[INFO] |  |  +- io.grpc:grpc-context:jar:1.16.1:compile
[INFO] |  |  +- (com.google.code.gson:gson:jar:2.7:compile - omitted for duplicate)
[INFO] |  |  +- (com.google.errorprone:error_prone_annotations:jar:2.2.0:compile - omitted for duplicate)
[INFO] |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:compile - omitted for duplicate)
[INFO] |  |  +- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile - omitted for duplicate)
[INFO] |  |  +- (com.google.guava:guava:jar:26.0-android:compile - omitted for conflict with 27.0-jre)
[INFO] |  |  +- (io.opencensus:opencensus-api:jar:0.12.3:compile - omitted for conflict with 0.11.1)
[INFO] |  |  \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.12.3:compile
[INFO] |  |     +- (com.google.errorprone:error_prone_annotations:jar:2.2.0:compile - omitted for duplicate)
[INFO] |  |     \- (io.opencensus:opencensus-api:jar:0.12.3:compile - omitted for conflict with 0.11.1)

**Comment by zhangkun83** [comment]
It's unfortunate that Maven's not smart at resolving dependency conflicts.
