### ISSUE TITLE
Client fails if server does not support ALPN ext

### ISSUE THREAD

**Issue by dbainbri-ciena** [grpc/grpc-java#5167]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
        <properties>
		<grpc.version>1.17.1</grpc.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-protobuf</artifactId>
			<version>${grpc.version}</version>
		</dependency>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-stub</artifactId>
			<version>${grpc.version}</version>
		</dependency>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-core</artifactId>
			<version>${grpc.version}</version>
		</dependency>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-netty</artifactId>
			<version>${grpc.version}</version>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative-boringssl-static</artifactId>
			<version>2.0.20.Final</version>
			<classifier>${os.detected.classifier}</classifier>
		</dependency>
	</dependencies>

### What did you expect to see?
The server to which I am attempting to connect does not support ALPN or NPN. When using other language bindings such as Go I can still connect to this server. With the Java language binding it reports a it cannot negotiate an application protocol. This seems to be because of a check in `grpc-java/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.userEventTriggered` that does `NEXT_PROTOCOL_VERSIONS.contains(handler.applicationProtocol()`. 

Because the server does not support negotiation, `handler.applicationProtocol()` return null (i think) and thus the connection fails. If I comment out this check and then the connect succeeds and everything works; which is the behavior I am seeing in other language bindings.

I have attempted to configure the negotiator using `ApplicationProtocolConfig.DISABLED` and custom settings on an `ApplicationProtocolConfig` instance, but all changes seem to have no effect.

Is there a way to configure around this, of does the Java binding simply have a different behavior?

**Comment by carl-mastrangelo** [comment]
Using ALPN is a hard requirement of HTTP/2.  See https://tools.ietf.org/html/rfc7540#section-3.4

**Comment by dbainbri-ciena** [comment]
Not really debating if ALPN is a hard requirement or not, but there do seem to be differences in how the language bindings handle the case when the server does not support ALPN. Today, it seems, that most of the language bindings silently move past it, where most are Go and Python. The Java binding does not.

I guess I will interpret your answer as "this is not going to change for the Java binding". Thanks.

**Comment by dbainbri-ciena** [comment]
One further comment. I am only having this issue when I create a TLS connection. For plaintext this is not an issue.

**Comment by carl-mastrangelo** [comment]
@dbainbri-ciena The problem is that without that ALPN string, we can't start speaking HTTP/2 to the server.  We would have to do HTTP/1.1 Upgrade, which doesn't currently exist.

Not sure why the other languages aren't failing, I believe they aren't spec compliant.

**Comment by dbainbri-ciena** [comment]
@carl-mastrangelo Thanks.

**Comment by carl-mastrangelo** [comment]
Out of curiosity, what TLS server are you using that doesn't support ALPN?

**Comment by dbainbri-ciena** [comment]
The TLS server is on a hardware device. I am not sure what they are actually using for their implementation. "Negotiating" with them now over that. Basically doing gNMI to the device.
