### ISSUE TITLE
Add ALPN setting path for Android older than 5.0

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#520]
OkHttp only support setting ALPN on Android 5.0+ since 2.3

**Comment by ejona86** [comment]
We need to backport this fix to 0.7.x

**Comment by madongfly** [comment]
Seems this is v0.7.2, @ejona86 @nmittler 

Do we want to update the release description to mention this fix?

**Comment by ejona86** [comment]
Yes please. Please also reply to @nmittler's release email on grpc-io and note the change.

**Comment by madongfly** [comment]
Done.
