### ISSUE TITLE
No such property: javaCompilerTask for class: com.android.build.gradle.internal.variant.TestVariantData.

### ISSUE THREAD

**Issue by lichao315** [grpc/grpc-java#5211]
Please answer these questions before submitting your issue.

### implementation 'io.grpc:grpc-okhttp:1.19.0-SNAPSHOT' // CURRENT_GRPC_VERSION
    implementation 'io.grpc:grpc-protobuf-lite:1.19.0-SNAPSHOT' // CURRENT_GRPC_VERSION
    implementation 'io.grpc:grpc-stub:1.19.0-SNAPSHOT' // CURRENT_GRPC_VERSION

###When I run the Android demo, AndroidStudio reports an error:No such property: javaCompilerTask for class: com.android.build.gradle.internal.variant.TestVariantData.

my Project's gradle.build:
dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.5"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

How can I solve this problem?

**Comment by ericgribkoff** [comment]
Can you try upgrading your `protobuf-gradle-plugin` to at least 0.8.6? This looks like the known issue reported [here](https://androidstudio.googleblog.com/2018/06/android-studio-32-beta-2-available.html).

**Comment by zhangkun83** [comment]
No update from reporter yet. Assuming upgrading protobuf-gradle-plugin will work. Closing the issue. If the issue still occurs, please file a bug to [the plugin](https://github.com/google/protobuf-gradle-plugin).
