### ISSUE TITLE
Possible to use custom executor on server side?

### ISSUE THREAD

**Issue by jhaber** [grpc/grpc-java#5215]
### What version of gRPC are you using?

1.12.0

### What did you expect to see?

A way to have an RPC run using a different executor on the server side.

For some background, we have gRPC services where some methods are known to return quickly and other methods are slow and inherently blocking. We have the server configured to use a fixed size thread pool, so there is a risk of these slow RPCs saturating the thread pool and starving the quicker RPCs. Our approach when implementing these slow RPCs has been to manually dump work into a separate thread pool to unblock the gRPC thread. 

I was looking to make a custom proto method option to indicate that a method should use a dedicated thread pool, and then respect this option with an interceptor. However, I didn't see an easy way with the `ServerInterceptor` interface to move an RPC to a different executor (the way you can on the client side using `CallOptions#withExecutor`). I assume this is because handling the incoming RPC requires choosing an executor and must happen before the `ServerInterceptor` chain can run?

Does this use-case make sense? Any pointers? Thanks in advance

**Comment by carl-mastrangelo** [comment]
If you use something like Guava's sequentialExecutor, you can forward all callbacks from the ServerCall.Listener to another threadpool.  From gRPC's point of view, callbacks for a single RPC are guaranteed to be fired in order on the executor, and without reentrancy.

**Comment by jhaber** [comment]
👍  Thanks for the suggestion, I ended up with something like this:
https://gist.github.com/jhaber/8ef94683fca18d64be09c7ed10a0b571

It's a bit error-prone because you need to propagate the context, serialize callbacks, close the call on exception, and possibly even more subtleties that I didn't account for. Going to close the issue since this seems to work, but if gRPC had a built-in way to do this I think it would be useful.
