### ISSUE TITLE
java_grpc_library- import not found 

### ISSUE THREAD

**Issue by adibrastegarnia** [grpc/grpc-java#5225]
Hello, 

I have almost a similar problem that is discussed here: 
https://github.com/grpc/grpc-java/issues/4896

But I didn't understand the final solution. I have a protobuf that defines services and also imports some other protobufs. I can generate the proto_library without any problem but when I use it in grpc_proto_library, it gives me the import not found or file not found. I use proto_source_root in my proto_library.

**Comment by zhangkun83** [comment]
This seems to be a duplicate of #4896

**Comment by adibrastegarnia** [comment]
@zhangkun83 
It was closed so I opened a new one. The solution that is proposed there requires to change the code. Is there any better solution
