### ISSUE TITLE
How do I create a grpc over local socket (unix domain socket)

### ISSUE THREAD

**Issue by avnerbarr** [grpc/grpc-java#5238]
I want to create a grpc server over local host - i guess using a local domain socket would be prefereable. I saw some places that say to do:

**Comment by carl-mastrangelo** [comment]
You can use `localhost` by using the normal `ServerBuilder.forPort`, which is the easiest.  Domain sockets are more complicated, but you can try out DomainSocketAddress with the NettyServerBuilder.

In the future, could you ask questions like this on StackOverflow or on our [Support Forum](https://groups.google.com/forum/#!forum/grpc-io)
