### ISSUE TITLE
Unable to execute Java GRPC TLS client with 1.17.1 or 1.19.0-SNAPSHOT

### ISSUE THREAD

**Issue by eenov8** [grpc/grpc-java#5240]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Tried using 1.17.0 and 1.19.0-SNAPSHOT

### What did you expect to see?
I have a GRPC server running successfully behind an envoy Load Balancer secured using X.509 based certs/keys.
I am facing a problem while creating the client for same.

Maven repository gives the option to use till 1.17.1 and the example shown on GRPC-JAVA Git suggest bumping to 1.17.3-SNAPSHOT or 1.19.0-SNAPSHOT.

I have tried using both the options i.e. 1.17.1 (maven) and 1.19.0-SNAPSHOT (MASTER branch checkout and local build/install)

Steps Performed for build/install 1.19.0-SNAPSHOT:

- Checked out Master branch of grpc-java code
- Used the flag skipcodegen=true
- ./gradlew build and then install

For 1.19.0-SNAPSHOT test, my pom properties are like below:

```
<properties>
                <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
                <grpc.version>1.19.0-SNAPSHOT</grpc.version><!-- CURRENT_GRPC_VERSION -->
                <protoc.version>3.5.1-1</protoc.version>
                <netty.tcnative.version>2.0.20.Final</netty.tcnative.version>
                <!-- required for jdk9 -->
                <maven.compiler.source>1.8</maven.compiler.source>
                <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```

Assuming, this will install the required jars in my local maven repository, tried running my client as:

Error is:

> [ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:compile-custom (default) on project grpc: Missing:
> [ERROR] ----------
> [ERROR] 1) io.grpc:protoc-gen-grpc-java:exe:linux-x86_64:1.19.0-SNAPSHOT
> [ERROR]
> [ERROR] Try downloading the file manually from the project website.

Looks like the protoc-gen-grpc-java dependency is still not getting added.

Now, tried to use the 1.17.1, my pom is

```
<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<grpc.version>1.17.1</grpc.version><!-- CURRENT_GRPC_VERSION -->
		<protobuf.version>3.5.1</protobuf.version>
		<protoc.version>3.5.1-1</protoc.version>
		<netty.tcnative.version>2.0.7.Final</netty.tcnative.version>
		<!-- required for jdk9 -->
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
</properties>
```
Here, I am getting the error

> Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project grpc: An exception occured while executing the Java class. Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available

Any suggestions what I might be doing wrong here.

AJ

**Comment by eenov8** [comment]
Did some more search, referred https://github.com/grpc/grpc-java/tree/master/compiler to manually compile and install the protoc dependency to local maven.
However, now hitting another issue:

> WARNING: RPC failed: Status{code=UNKNOWN, description=null, cause=java.lang.Exception: Failed ALPN negotiation: Unable to find compatible protocol.
>         at io.grpc.netty.ProtocolNegotiators$BufferUntilTlsNegotiatedHandler.userEventTriggered(ProtocolNegotiators.java:687)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
>         at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
>         at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1537)
>         at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
>         at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
>         at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
>         at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
>         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.lang.Thread.run(Thread.java:748)
> }

**Comment by eenov8** [comment]
Looks like by envoy.yaml was missing some configuration related to ALPN protocol handling: alpn_protocols: "h2". Now the GRPC client is failing without any error:

> WARNING: RPC failed: Status{code=UNIMPLEMENTED, description=null, cause=null}
> [WARNING] NOTE: 3 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
> [WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.my.App,maxpri=10]
> java.lang.IllegalThreadStateException
>         at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
>         at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:321)
>         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

**Comment by carl-mastrangelo** [comment]
Any reason to set `skipcodegen` ?   We mostly don't use that flag.

**Comment by ejona86** [comment]
I answered this [on StackOverflow](https://stackoverflow.com/a/54190040/4690866). @eenov8, if things still aren't working you can provide updated comments here.
