### ISSUE TITLE
gradle build meeting problem org.gradle.api.internal.tasks.DefaultTaskInputFilePropertySpec cannot be cast to org.gradle.api.tasks.TaskInputs

### ISSUE THREAD

**Issue by hui-x-chen** [grpc/grpc-java#5243]
Please answer these questions before submitting your issue.

✗ gradle build
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/chenhui/Go/src/github.com/scripts/sdksamples/CarDealer/java/huchchen/tmp/grpc-java/build.gradle' line: 33

* What went wrong:
A problem occurred evaluating root project 'grpc'.
> Failed to apply plugin [id 'net.ltgt.apt']
   > org.gradle.api.internal.tasks.DefaultTaskInputFilePropertySpec cannot be cast to org.gradle.api.tasks.TaskInputs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

### What version of gRPC are you using?
➜  grpc-java git:(3134daf47) ✗ git checkout v1.15.0
HEAD is now at 3134daf47 Bump version to 1.15.0

**Comment by hui-x-chen** [comment]
I am using mac platform

**Comment by dapengzhang0** [comment]
@hui-x-chen What gradle version are you using? You may try the gradle wrapper `gradlew` shipped with grpc-java in github repo:

```
./gradlew build
```

instead of 
```
gradle build
```

**Comment by ejona86** [comment]
Closing since gradlew should fix the problem. @hui-x-chen, if things are still not working comment and we can re-open.
