### ISSUE TITLE
Support NPN on Android when Play Services Security Provider (PSSP) not available

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#526]
Attempts and their fallbacks:

1. If installed, use PSSP with ALPN and NPN
2. If on Android 5.0 or later, use ALPN and NPN
3. If on Android 4.1 or later, use NPN
4. Fail or let the application author install some alternative security provider (e.g., build and ship Conscrypt themselves)

**Comment by ejona86** [comment]
@madongfly What is the status of this?

**Comment by madongfly** [comment]
I'm pending on the manual test, when I use the 4.x Android without PSSP, the default ciphers can not work, I tried several ciphers, but haven't found any one works.

**Comment by ejona86** [comment]
Using `ConnectionSpec.MODERN_TLS` directly (or mutate it slightly) doesn't work?

**Comment by madongfly** [comment]
Fixed by #591
