### ISSUE TITLE
Expose ProtoReflectionService as Bazel target

### ISSUE THREAD

**Issue by perezd** [grpc/grpc-java#5262]
Doesn't seem like its accessible by anything but gradle currently. Would be nice to add a BUILD.bazel file which exposes it.

**Comment by carl-mastrangelo** [comment]
Might be tricky, since the .proto targets are defined in another git repo.  Keeping them in sync has been difficult.  Otherwise, seems like a reasonable feature request.

**Comment by perezd** [comment]
Looking at it, a WORKSPACE dependency would be all thats needed for the build target. Alternatively, the BUILD file could generate the protos based on the copies locally, either approach is feasible I'd imagine.

If you want me to I can take a stab at a PR?

**Comment by jyane** [comment]
I think this issue is same as https://github.com/grpc/grpc-java/issues/4097

**Comment by dapengzhang0** [comment]
Close as duplicate to #4097
