### ISSUE TITLE
Verify Protocol Negotiation completed

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#527]
It seems if neither ALPN nor NPN occur/available we just happily continue connecting and think that negotiation occurred. We should instead check that the protocol negotiated and fail if it didn't.

**Comment by nmittler** [comment]
@ejona86 is this still an issue?

**Comment by ejona86** [comment]
Yes. This is related to `SelectorFailureBehavior.FATAL_ALERT`, in that it will only be fatal if ALPN/NPN is used in the first place. If the remote doesn't support ALPN/NPN, the connection continues unabated.

**Comment by nmittler** [comment]
As discussed with @ejona86 offline.  It sounds like the solution to this is 2 parts:

1. Break the connection when the SSL handshake succeeds but `SslHandler.applicationProtocol()` is `null`.  I'm not sure at the moment if this method is supported in 4.1.0.beta5, if not we'll need to wait for the next release of netty.
2. Change the failure modes of the protocol negotiation to match the [HTTP/2 example in Netty](https://github.com/netty/netty/blob/master/example/src/main/java/io/netty/example/http2/helloworld/client/Http2Client.java#L76).

**Comment by nmittler** [comment]
Fixed by #932
