### ISSUE TITLE
why maxConcurrentStreams  in NettyClientHandler is set to 0?

### ISSUE THREAD

**Issue by psxbmbb** [grpc/grpc-java#5271]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.16.0

### What did you expect to see?
I'm confused why maxConcurrentStreams  in NettyClientHandler is set to 0?

**Comment by carl-mastrangelo** [comment]
MaxConcurrentStreams on the client is the number of streams the *server* can initiate to the client, which are roughly the same as PUSH_PROMISE.  gRPC doesn't use server initiated streams, so the number doesn't matter.
