### ISSUE TITLE
Tracking issue for ProxyDetector being experimental

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#5279]
ProxyDetector, ProxyParameters, ManagedChannelBuilder.proxyDetector

These APIs were added for #5113

**Comment by ejona86** [comment]
Some tweaks to the current API:
* We need a new document about proxy configuration for end user consumption. We can then link to it within our Javadoc
* ProxyDetector should be made an abstract class
* Tweak documentation of MCB.proxyDetector to mention NR has to support it, and that's mainly DNS. Mention the default uses ProxySelector/Authenticator
* Open up new issue (done) and change annotation in code to match

**Comment by ejona86** [comment]
There is some concern about ProxyParameters being too CONNECT-specific. It couldn't be used for SOCKS, for example.

The ProxyParameters.Builder should maybe be using set in its method names, to match most of our other Builders (TODO: verify that is the case).

**Comment by dapengzhang0** [comment]
An external sercase in #7043

**Comment by dengshenyu** [comment]
This commit would treat socks proxy as a http proxy,  and then use HTTP CONNECT method to proxy by the socks proxy. This should not be happened.

**Comment by ejona86** [comment]
@dengshenyu, there is no "this commit". This is an issue, not a PR. And this API looks fine because `ProxyDetector` can only use the type  `HttpConnectProxiedSocketAddress` today. But I think I see what you're saying. The ProxySelector adapter [doesn't verify Proxy.Type.HTTP](https://github.com/grpc/grpc-java/blob/80f1be03f0dc347125765bd9360848f221a7f174/core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java#L243). Please file a new issue for that or send a PR.
