### ISSUE TITLE
Bazel building is broken with protobuf<3.6.1.3 

### ISSUE THREAD

**Issue by Reflexe** [grpc/grpc-java#5310]
### What version of gRPC are you using?
1.18.0

### What did you expect to see?
Bazel build is working; currently it is broken since old protobuf versions uses the removed `REPOSITORY_NAME` and `PACKAGE_NAME` (see https://github.com/protocolbuffers/protobuf/commit/af4810663bf1fb2388e88ad9038b80551aefd6da).

### Solution
Bump protobuf to 3.6.1.3?

**Comment by ejona86** [comment]
This will be fixed by #5310. That PR should not block users, as you can manually specify the newer version.
