### ISSUE TITLE
Contributing guideline points to a dead/old link for google java style guide

### ISSUE THREAD

**Issue by arajitsamanta** [grpc/grpc-java#5313]
**Issue Description**
While going through  CONTRIBUTING.md file observed that clicking on style guide link returns 404 

### What version of gRPC are you using?
v1.18.x

### What did you expect to see?
Clink on **Google Java Style Guide.** should open the java style guide page.

**Solution**
Dead Link: https://google-styleguide.googlecode.com/svn/trunk/javaguide.html
New Link: https://google.github.io/styleguide/javaguide.html

**Comment by carl-mastrangelo** [comment]
Want to send a PR?

**Comment by arajitsamanta** [comment]
@carl-mastrangelo 
Sure. I will assign this to myself and fix it.

**Comment by arajitsamanta** [comment]
@carl-mastrangelo 
Should the PR go to default base(master) or v1.18.x branch?

**Comment by carl-mastrangelo** [comment]
master, or both.  We typically dont backport too far (else we would end up with 18 commits for each doc change).

**Comment by arajitsamanta** [comment]
Change is merged to master. Closing this issue.
