### ISSUE TITLE
Why are multiple deps for java_grpc_library deprecated?

### ISSUE THREAD

**Issue by perezd** [grpc/grpc-java#5314]
https://github.com/grpc/grpc-java/blob/master/java_grpc_library.bzl#L105

I don't see any reason for this and actually I feel like its probably not advisable. In my scenario I have 2 java_proto_library instances, my service definition and my model objects that the service is composed of. I require the ability to define both as deps for this to work.

Reading the source, it looks like this list gets added to as well, so I really don't see why this limitation is here without any docs. I would propose we remove this check, WDYT?

**Comment by perezd** [comment]
Also based on the docs, I understand this doesn't necessarily do anything with my non-service protos, but I'm not positive the underlying java_library will compile without a reference to both java proto library deps I have defined.

**Comment by ejona86** [comment]
We want/expect a 1:1 correspondence between proto_library and java_grpc_library. The reason that multiple deps are allowed today is to workaround strict_deps issues, where you had to specify all the directly used deps.

I have a version that works around the strict_deps within java_grpc_library, so users don't need to worry about it any more. So after a period to allow migration, I do plan on enforcing that check and causing build failures if more than one dep is specified.

(You can see a newer version of the rule at https://github.com/ejona86/grpc-java/tree/bazel-dex . It keeps hitting incompatibilities internally that I've been fighting one-by-one. But that's more of the future of the rule.)

**Comment by perezd** [comment]
OK I understand, but I don't think this addresses my use case of a service proto java target having a dependency on a non-service java proto. How would we address this given this limitation?

**Comment by ejona86** [comment]
@perezd, see #5342. That should avoid the need to specify multiple deps.

**Comment by perezd** [comment]
Sorry for being slow here but I'm not seeing how this resolves the issue. It looks like that change takes the transitive proto sources being passed into the srcs arg of the rule, but won't it still require java analogs for compile time? 

To be clear this is the example I have:

```
proto_library(
   name = "resource",
   srcs = ["resource.proto"],
)

proto_library(
  name = "resource_service",
  srcs = ["resource_service.proto"],
  deps = [":resource"],

java_proto_library(
  name = "resource_java",
  deps = [":resource"],
)

java_proto_library(
  name = "resource_service_java",
  deps = [":resource_service"],

java_grpc_library(
  name = "resource_service_java_grpc",
  srcs = [":resource_service"],
  deps = [
    ":resource_java",
    ":resource_service_java",
  ],
```

How will this need to change given the PR you cited?

**Comment by ejona86** [comment]
You would do:
```bzl
java_grpc_library(
  name = "resource_service_java_grpc",
  srcs = [":resource_service"],
  deps = [":resource_service_java"],
)
```

`resource_service_java` actually has `resource_java` as an implicit dependency (due to the magic of aspects a `java_proto_library` will cause its transitive dependencies to be generated; actually it isn't a dependency on `resource_java`, but something equivalent).

Technically, you wouldn't even need the `resource_java` target for `java_grpc_library`. However, your _application_ would need `resource_java` in order to reference any of the messages within.

**Comment by perezd** [comment]
OK that is good to know, I'll experiment with this and get back to you if I run into any issues!
