### ISSUE TITLE
Upgrade Mockito dependency to version 2

### ISSUE THREAD

**Issue by suztomo** [grpc/grpc-java#5319]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
io.grpc:grpc-testing:1.17.1

### What did you expect to see?
To use Mockito version 2.

As of now grpc-java project uses mockito 1.9.X. The last release of 1.9.X is [1.9.10 in 2014](https://github.com/mockito/mockito/releases/tag/v1.10.19).

https://github.com/grpc/grpc-java/blob/ef6b6169f80d14c35775a04daf9f375bd82ce2d4/build.gradle#L236

Would you upgrade the dependency to mockito 2.24.0?
[Mockito upgrade guilde from 1.10 to 2.X](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#incompatible-changes-with-110)

## Background

I'm trying to clean up grpc-related conflicting/outdated dependencies. (Example https://github.com/spring-cloud/spring-cloud-sleuth/issues/1186)

**Comment by carl-mastrangelo** [comment]
In progress in https://github.com/grpc/grpc-java/pull/5219

We can't use 2 yet, as the dependency is not available yet inside.

**Comment by suztomo** [comment]
Thank you for response. I'm in no hurry. I will check the status again later (Maybe in April)
