### ISSUE TITLE
Set custom metadata with value from response body

### ISSUE THREAD

**Issue by mayank-dixit** [grpc/grpc-java#5330]
***
Question: How do I access `headers.put()` and `responseBody` at one place in interceptCall?
***

This is what I Intend to do:
 - Generate image url at `/myapi/user/1/image`

This is how I tried:
 - I generated AWS s3 url (temporary) and tried sending 302 at that url. That was the general practise in HTTP server as well.

This is the Blocker:
 - No such concept as 302 redirect in grpc

This is the alternative I thought of:
 - I'll send my response with 200. But I'll set a custom metadata called `location` with the url present in response body. My [Http proxy server](https://github.com/grpc-ecosystem/grpc-gateway) could check when response metadata has `location` set, respond 302 REDIRECT with metadata value.

This is how I tried:
 - Created custom interceptor that implements `ServerInterceptor`
 - Overrode `interceptCall` and tried setting body to metadata

This is the Blocker:
 - I'm unable to get hold of `setMetdata()` and `responseBody` at one place together.
 - sendHeaders is the place where I'm able to set header as shown in [HeaderServerInterceptor](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/header/HeaderServerInterceptor.java#L48) example.
- onMessage is the place where I can access `responseBody`.
- Can't find one place where I can do both!

**Comment by carl-mastrangelo** [comment]
gRPC (the library) doesn't handle any of the 300 error codes (302, 301, 307, 308, etc.).  There isn't really a webpage or URL that gRPC application should go to.  You can add headers to the response and access the response messages by using a `ServerInterceptor`, and making your own `ServerCall` and `ServerCall.Listener`.   By delegating to the "next" ServerCall in the interceptor, you can change the response, or delay it, or pretty much anything.   We don't have any direct examples of what you are trying to do, but take a look at `CompressionTest` and the interceptors in there.
