### ISSUE TITLE
Tracking issue for Server.getListenSockets() being experimental

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#5332]
Usage:

* `Server.getListenSockets()`

**Comment by YifeiZhuang** [comment]
It looks `OkHttpServer` and `InProcessServer` does not implement `Server` (they implement [InternalServer](https://github.com/grpc/grpc-java/blob/ccf91018285cf112c0cc287cd9f1ef6ad161717e/core/src/main/java/io/grpc/internal/InternalServer.java#L32) instead, ), so they does not implement `getListenSockets`. Is it a UX concern that this API only works for netty transport, but not for OkHttp and InProcess transport?

**Comment by larry-safran** [comment]
Approved for stabilization.

**Comment by YifeiZhuang** [comment]
> It looks `OkHttpServer` and `InProcessServer` does not implement `Server` (they implement [InternalServer](https://github.com/grpc/grpc-java/blob/ccf91018285cf112c0cc287cd9f1ef6ad161717e/core/src/main/java/io/grpc/internal/InternalServer.java#L32) instead, ), so they does not implement `getListenSockets`. The `InternalServer` interface has `getListenerSocketAddress` and `getListenSocketStats`. Is it a UX concern that this API only works for netty transport, but not for OkHttp and InProcess transport?

`OkHttpServer` in transport. ServerImpl is built from `OkHttpServerBuilder` that implements `Server`, and `OkHttpServer.getListenSocketAddresses` returns listener sockets.
