### ISSUE TITLE
Java 11: cannot find symbol javax.annotation.Generated

### ISSUE THREAD

**Issue by giacomotontini** [grpc/grpc-java#5343]
gRPC 1.18
protoc 3.6.1
 [Related issue](https://github.com/grpc/grpc-java/issues/3633)
These workaround for java 9 seems to be no longer working for java 11. Anyone faced this issue before?
```
if (JavaVersion.current().isJava9Compatible) {
        // Workaround for @javax.annotation.Generated
        // see: https://github.com/grpc/grpc-java/issues/3633
        compile("javax.annotation:javax.annotation-api:1.3.2")
    }
```

**Comment by ejona86** [comment]
Adding the compile dependency should work. I'd expect it is `JavaVersion.current().isJava9Compatible` that is broken, as that is for the JRE running Gradle, not the version of the JDK used to compile.

**Comment by carl-mastrangelo** [comment]
Closing for now, please reopen if this is still an issue.
