### ISSUE TITLE
configurable jitter in maxConnectionAge

### ISSUE THREAD

**Issue by ramaraochavali** [grpc/grpc-java#5366]
### What version of gRPC are you using?
1.3.0

### What did you expect to see?

We have a gRPC streaming service that supports long running streams. We want to have `maxConnectionAge` on them. The current issue we are facing is, `NettyServerBuilder` adds hardcoded +/- 10% jitter on the connection age passed. In our case, we would like have to more wider range as these are long running streams.

The proposal is to add a overloaded `maxConnectionAge` method with jitter% as additional argument.

Is this some thing that is acceptable?

**Comment by creamsoup** [comment]
I don't see how wider jitter can solve your problem. Are you trying to balance out number of connections per server? can you provide little more detail why it can solve your problem?

Meanwhile, have you consider [maxConnectionAgeGrace](../blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L409)?. maxConnectionAgeGrace controls how long the existing streams can live after the max connection age is reached. This allows the old long lived streams can live on the old connection while new streams won't be accepted to that old connection.

**Comment by ramaraochavali** [comment]
>  Are you trying to balance out number of connections per server?
Yes. That is one of our motivations. We want to balance number of connections per server over a period of time.

> can you provide little more detail why it can solve your problem?
We have 3 instances of the server and around 1500 clients connecting to these three servers (all long running streams having a persistent connection). We have configured `maxConnectionAge` as 30 min and `maxConnectionAgeGrace` as 1 sec - Around 30 mins time we see a flood of disconnects and reconnects for around 3 -5 mins. We want to see if we can widen the jitter so that these disconnects/reconnects can spread across.

> Meanwhile, have you consider [maxConnectionAgeGrace](../blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L409)?
Yes. As explained above we did. Do think increasing it will help - since it is a persistent connection with single bidi stream going on - not sure if it would really help much.

**Comment by ST-DDT** [comment]
> Around 30 mins time we see a flood of disconnects and reconnects for around 3 -5 mins.

This looks like you start all the clients and the server at the same time. Usually the client (re-)connect attempts automatically scatter themselves.

I would try to scatter the reconnects in the clients and not on the server. However, if you wish to scatter them some more, you could change the maxConnectionAge + grace to 15min each and randomly close/complete the requests using server interceptors (i.e. close one (x) random request per minute or so).

**Comment by ramaraochavali** [comment]
> This looks like you start all the clients and the server at the same time. Usually the client (re-)connect attempts automatically scatter themselves.

No. We do not start all of them at the same time. We will not restart servers and just client (re-)connect them selves. 

> I would try to scatter the reconnects in the clients and not on the server

This is what we also want to do to. Our servers are long running.

**Comment by creamsoup** [comment]
I think you can use smaller `maxConnectionAge` and higher `maxConnectionAgeGrace`. With this configuration, there won't have as many reconnects as the alternative way since the `maxConnectionAgeGrace` is higher. Hopefully some of the existing streams on the connection have chance to finish within the grace time. Overtime, smaller `maxConnectionAge` will help to balance number of connections per server. 
You can achieve this with higher jitter, but you have to pay for reconnection over-head. Your specific use case may vary, but I think this should work. Is this something you can consider?

**Comment by ramaraochavali** [comment]
> I think you can use smaller `maxConnectionAge` and higher `maxConnectionAgeGrace`

Do you think reducing our current `maxConnectionAge` to some thing like 15min and increase `maxConnectionAgeGrace` to some thing 10min would help? If it helps we can certainly try. But is it not same as setting `maxConnectionAge` to 25min and `maxConnectionAgeGrace` to less than a min? or are you saying that lower `maxConnectionAge` would help to balance number of connections per server better?

> Hopefully some of the existing streams on the connection have chance to finish within the grace time

This is not the case for us. The clients have a persistent connection open and with single stream where messages are exchanged - basically long poll from client, the stream closes only when either the client disconnects for some reason or client shutsdown (which never happens in our case).

**Comment by creamsoup** [comment]
certainly lower `maxConnectionAge` will help to balance the number of connections per server. Higher jitter will help spread the reconnect little bit faster. like @ST-DDT mentioned, after while the reconnect attempts should automatically scatter themselves. 
Let say 10min `maxConnectionAge`. 1st connection timeouts will occur 9~11min time window. 2nd generation of connections will be timed out around 18min to 22min time window from the server start time (note: they are not evenly distributed yet). after a while, they should be well spread. At least 5 iterations to be widely spread with bell curve like distribution. Eventually, uniformly distributed. if you are not seeing this pattern, that sounds to me a bug.
`maxConnectionAgeGrace` can help to reduce the number of reconnect since it gives more time to wrap up after the `maxConnectionAge` reached. So, I still suggest to try `maxConnectionAgeGrace`.

**Comment by ramaraochavali** [comment]
>  1st connection timeouts will occur 9~11min time window. 2nd generation of connections will be timed out around 18min to 22min time window from the server start time (note: they are not evenly distributed yet).
Let us assume we have 3 server instances and 1500 clients and we set `maxConnectionAge`. Are you saying that in the 1st connection timeouts only part of 1500 clients are expected to reconnect? We are seeing all 1500 clients are reconnecting. And on reconnection we exchange bunch of messages leading servers to behave sluggishly during the period. We want to spread the reconnections out so that all 1500 wont try to reconnect at the 9-11 min interval.  One thing I was wondering was should we choose the maxConnectionAge randomly across all three server instances instead of a fixed maxConnectionAge for all of them? The idea is the clients connected to server1 will form a group etc so that we do not have these mass reconnections.

>  Eventually, uniformly distributed. if you are not seeing this pattern, that sounds to me a bug.
Here is our connected client graph for the last 6 hours. Is this in line with your expectations? This is a test env so you see  less clients.
<img width="409" alt="screen shot 2019-02-21 at 10 53 25 am" src="https://user-images.githubusercontent.com/17204904/53145679-25c5e100-35c7-11e9-87ca-afa8b7a48bb8.png">

Agree with `maxConnectionGrace`. Will use that - Do you think 1s is reasonable or increasing it is better?

**Comment by creamsoup** [comment]
I don't see anything out of ordinary from the graph. 
For the `maxConnectionGrace`, 1s is close to nothing i would consider much bigger number. As long as you understand the trade offs of `maxConnectionGrace`, you can use much higher number (or lower). The obvious trade off is higher `maxConnectionGrace` reduces number of reconnect, but as a result it may delay re-balancing connections. Optimal value is depends on your traffic pattern, so I can't give you a concrete number.

**Comment by ramaraochavali** [comment]
Ok. Great. 

We will experiment with increasing the `maxConnectionGrace` and decreasing the `maxConnectionAge`.

One final question, What do you think about each server choosing its random maxConnectionAge and Grace - would it help ?

**Comment by creamsoup** [comment]
I wouldn't use random values. it won't solve the issue (you can use lower `maxConnectionAge` if you really want to see rebalance happening more frequently), but it makes things more complicated. That being said, it can certainly achieve what you originally requested.

**Comment by creamsoup** [comment]
i'll close this issue for now, please feel free to reopen if you have further questions.

**Comment by ramaraochavali** [comment]
Sure. If `maxConnectionAge` and `maxConnectionAgeGrace` tuning as discussed above does not help our use case, are you OK to make jitter configurable?

**Comment by creamsoup** [comment]
yeah, if that doesn't help please reopen and let us know your findings. we can make decision at that point.
