### ISSUE TITLE
Error When Compiling grpc-java

### ISSUE THREAD

**Issue by ochowie** [grpc/grpc-java#537]
When I try to compile grpc-java I get the following error:

8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
"#include `<`google/protobuf/io/zero_copy_stream.h`>`
         ^
1 error generated.
:grpc-compiler:compileJava_pluginExecutableJava_pluginCpp FAILED

libprotoc is version 3.0 and it is currently installed in /usr/local/lib and I've tried this on Linux and Mac OSX.

**Comment by zhangkun83** [comment]
It's been resolved: https://groups.google.com/d/msgid/grpc-io/ee47b5e3-4a78-4253-802b-4245e2f43762%40googlegroups.com?utm_medium=email&utm_source=footer
