### ISSUE TITLE
StreamObserver.onError not called on android when network switches to Roaming

### ISSUE THREAD

**Issue by samratshekhar** [grpc/grpc-java#5375]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.18.0

### What did you expect to see?
**StreamObserver.onError** getting called when network type changes to **Roaming**

### Actaul observation
On android, for bidirectional streaming, if the user has not acrtivated **Connect to data services when roaming** and if the network type is switched to roaming, **StreamObserver.onError** isn't called. As a fallback, I tried creating a new RPC stub on the existing ManagedChannel, but to no avail. Only when I created a brand new channel along with a new stub, did the **StreamObserver.onError** was called the next time.

**Comment by dapengzhang0** [comment]
>On android, for bidirectional streaming, if the user has not acrtivated **Connect to data services when roaming** and if the network type is switched to roaming, **StreamObserver.onError** isn't called. As a fallback, I tried creating a new RPC stub on the existing ManagedChannel, but to no avail. Only when I created a brand new channel along with a new stub, did the **StreamObserver.onError** was called the next time.

This sounds like when switched to roaming but with no data services, the pre-existing socket isn't closed by the system, but becomes a black hole. To get rid of black hole problem in general, you can set a [keepAliveTime](https://grpc.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html#keepAliveTime-long-java.util.concurrent.TimeUnit-) and [keepAliveTimeout](https://grpc.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html#keepAliveTimeout-long-java.util.concurrent.TimeUnit-) on your channel builder.

**Comment by ejona86** [comment]
It may also be a good idea to use [AndroidChannelBuilder](https://github.com/grpc/grpc-java/blob/master/android/src/main/java/io/grpc/android/AndroidChannelBuilder.java) which can listen for such events from Android.

**Comment by ejona86** [comment]
Haven't heard back if the approaches suggested worked or were acceptable, so closing. It can be reopened if we hear back.
