### ISSUE TITLE
Add ClientInterceptors "inside" ChannelImpl

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#538]
This is an alternative to #64. 

It could be useful to have a set of interceptors "inside" ChannelImpl. These interceptors would always be used. The could be immutable and added via a `AbstractChannelBuilder.addInterceptor()` or maybe mutated added after creation on ChannelImpl. Today, adding after creation doesn't cause issues since only `interceptCall` is part of `ClientInterceptor`. However, if any other methods were added to the interface it could easily cause problems.

There are two main use cases:
 1. Simple users who don't want to maintain as many object references. Adding to the inside of `ChannelImpl` means they don't need to maintain both a ChannelImpl reference and the topmost `Channel` reference, as they could be the same object. These are simpler scenarios that only have one chain of interceptors.
 2. Auth construction factory. Authentication commonly needs a combination of transport and Metadata configuration. For example, using TLS (optionally with client certificates) and then OAuth. The auth mechanism can change in the environment, for example, by not using TLS if the server is on the same trusted network. Having a single Auth-aware factory would be easier to use, as is the design of [google-auth-library-java](https://github.com/google/google-auth-library-java).

The feature would have the downfall of having multiple ways of doing what appears to be the same thing (via `ClientInterceptors` and via the `AbstractChannelBuilder`). It would increase user code's (unnecessary) dependency on `ChannelImpl`, because they wouldn't be forced to use `Channel`. It might also encourage a few users to create multiple `ChannelImpl`s to keep things "simple."

**Comment by zhangkun83** [comment]
In Use Case 2, are you envisioning an auth Channel builder (the said "factory") that installs auth interceptors into ChannelImpl. Since the interceptors now can access transport configuration, they are easier to implement than the decorative ones we have today? How does today's auth interceptors access the transport configuration?

**Comment by ejona86** [comment]
@zhangkun83, I was envisioning more of a factory or config method that would return a ChannelBuilder. The interceptors would not have access to the transport configuration. Auth interceptors today don't have access to the transport configuration, so we simply rely on the user configuring things correctly.

```java
// This is a real API in google-auth-library-java
Credentials creds = GoogleCredentials.getApplicationDefault();
AbstractChannelBuilder builder = ClientAuth.newChannelBuilder(creds, "localhost:443");
...
// Maybe better; it could have generics for type pass-through
NettyChannelBuilder builder = ClientAuth.configure(
    NettyChannelBuilder.forName(...));
// builder would now likely have OAuth interceptor ready for use and be configured to use TLS.
// In other circumstances, it could be configured for plaintext or client certificates, etc.
```

**Comment by johnbcoughlin** [comment]
This occurred to me as a way to add timeout headers as well, FWIW.

**Comment by ejona86** [comment]
In discussion offline, it seems that although discussing this topic led to many other related discussions, everyone was okay with this change. I'll move forward to supporting adding interceptors only to the AbstractChannelBuilder.
