### ISSUE TITLE
bazel: export `:internal` from `:inprocess` 

### ISSUE THREAD

**Issue by Reflexe** [grpc/grpc-java#5385]
### What version of gRPC are you using?
master

### What did you expect to see?
`examples`'s tests compiles.  Currently, it does not since a few supertypes of `inprocess` lives on the `internal` package which `inprocess` depends on but does not `export` it. The solution is simple: 
```
--- core/BUILD.bazel	
+++ core/BUILD.bazel	
@@ -18,6 +18,9 @@
         "src/main/java/io/grpc/inprocess/*.java",
     ]),
     visibility = ["//visibility:public"],
+    exports = [
+        ":internal",
+    ],
     deps = [
         ":core",
         ":internal",
```

**Comment by carl-mastrangelo** [comment]
`:internal` will not be exported, because it's internal.

**Comment by Reflexe** [comment]
`AbstractManagedChannelImplBuilder` is the superclass of `InProcessChannelBuilder` which is not internal. You can't export `InProcessChannelBuilder` without `AbstractManagedChannelImplBuilder`.

**Comment by carl-mastrangelo** [comment]
@Reflexe I don't see why not.  `AbstractManagedChannelImplBuilder` being a super class of `InProcessChannelBuilder` is an implementation detail, done out of conveniences.  You can't really call any methods on `InProcessChannelBuilder` that are not also `ManagedChannelBuilder`.  For all purposes, `InProcessChannelBuilder` extends `ManagedChannelBuilder`. 

In bazel, a dependency is different than an export.  You can depend on something, without exporting it for others.

**Comment by Reflexe** [comment]
It was my bad; apparently kotlin with bazel won't import `deps` if there're super classes. I'll ask there about that. Thank you very much.
