### ISSUE TITLE
NettyServerBuilder protected stat setters?

### ISSUE THREAD

**Issue by perezd** [grpc/grpc-java#5386]
https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L237

Wondering why these are protected and not public? Especially given this is a final class, who are those for? Should I be able to set those as a public user of the NettyServerBuilder?

**Comment by dapengzhang0** [comment]
This has been an API for internal use. Main reason is we didn't have a reasonable external usecase that it has to be public yet.

**Comment by perezd** [comment]
OK, I guess its reasonable since I assume this really is a no-op unless opencensus-impl is present at runtime?

**Comment by dapengzhang0** [comment]
> this really is a no-op unless opencensus-impl is present at runtime
Correct.

**Comment by perezd** [comment]
Thanks for the clarification!

**Comment by carl-mastrangelo** [comment]
I think these should probably be package private to make the intent clear

**Comment by carl-mastrangelo** [comment]
Well, they are inherited, so maybe they have to be present.
