### ISSUE TITLE
[question] proper publish-subscribe pattern using grpc

### ISSUE THREAD

**Issue by zagorulkinde** [grpc/grpc-java#5392]
Hello, i'm trying to implement pub sub pattern using grpc but i'm confusing a bit about how to do it properly.

my proto:  `   rpc call (google.protobuf.Empty) returns (stream Data);`

client:

 ```
asynStub.call(Empty.getDefaultInstance(), new StreamObserver<Data>() {
          @Override
          public void onNext(Data value) {
            // process a data

          @Override
          public void onError(Throwable t) {
           
          }

          @Override
          public void onCompleted() {
          
          }
        });

    } catch (StatusRuntimeException e) {
      LOG.warn("RPC failed: {}", e.getStatus());
    }

    Thread.currentThread().join();
```

server service: 

```
public class Sender extends DataServiceGrpc.DataServiceImplBase implements Runnable {
  private final BlockingQueue<Data> queue;
  private final static HashSet<StreamObserver<Data>> observers = new LinkedHashSet<>();

  public Sender(BlockingQueue<Data> queue) {
    this.queue = queue;
  }

  @Override
  public void data(Empty request, StreamObserver<Data> responseObserver) {
    observers.add(responseObserver);
  }

  @Override
  public void run() {
    while (!Thread.currentThread().isInterrupted()) {
      try {
        // waiting for first element
        Data data = queue.take();
        // send head element
        observers.forEach(o -> o.onNext(data));
       
      } catch (InterruptedException e) {
        LOG.error("error: ", e);
        Thread.currentThread().interrupt();
      }
    }
  }
}

```

How to remove clients from global observers properly? How to received some sort of a signal when connection drops?  
How to manage client-server reconnections? How to force client reconnect when connection drops? 

Thanks in advance!

**Comment by ejona86** [comment]
> How to remove clients from global observers properly? How to received some sort of a signal when connection drops?

These are the same basic question: how do you know when the RPC is cancelled on server-side.

Out-of-the-box, the `StreamObserver<Data>.onNext()` will throw if the call is cancelled. This was the only way that gRPC was _guaranteed_ to notify the application of the cancellation.

A nicer approach is to cast the `StreamObserver` to `ServerCallStreamObserver` and call [`setOnCancelHandler(Runnable)`](https://grpc.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#setOnCancelHandler-java.lang.Runnable-). The Runnable will be called when the RPC is cancelled.

Another option is to use [Context.addListener()](https://grpc.io/grpc-java/javadoc/io/grpc/Context.html#addListener-io.grpc.Context.CancellationListener-java.util.concurrent.Executor-). It's basically equivalent to the cancel handler but a bit more annoying from a threading perspective.

> How to manage client-server reconnections? How to force client reconnect when connection drops?

These are the same basic question: how do you know the RPC completed/cancelled on client-side.

On client-side, make sure to handle `onError()` and `onCompleted()`. If your server never calls `onCompleted()`, then `onCompleted()` should not be called (but you probably want to turn it into an error, in case it happens).

There is no need to handle _reconnections_, as the Channel will do this automatically. But you would need to handle _retries_ of the RPC. It would be a good idea to use exponential backoff if you get continued failures, and you may be interested in using [`asyncStub.withWaitForReady().call(...)`](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md) which delays the RPC until a connection is available.

**Comment by zagorulkinde** [comment]
Thank you Eric for clarification!
