### ISSUE TITLE
MoreExecutors.platformThreadFactory() for java8 on app engine?

### ISSUE THREAD

**Issue by igorbernstein2** [grpc/grpc-java#5404]
I don't have good understanding about app engine restrictions, but a Bigtable customer recently ran into an issue because the Cloud Bigtable client did not use `MoreExecutors.platformThreadFactory()` for java8 on app engine (only for java7). It seems like grpc-java has a similar issue:

https://github.com/grpc/grpc-java/blob/2a3e0616ffbcbcaea1838b03035d784c11f6ae80/core/src/main/java/io/grpc/internal/GrpcUtil.java#L78-L80

https://github.com/grpc/grpc-java/blob/2a3e0616ffbcbcaea1838b03035d784c11f6ae80/core/src/main/java/io/grpc/internal/GrpcUtil.java#L577-L581

Should IS_RESTRICTED_APPENGINE be updated to include 1.8 for executor creation?

**Comment by carl-mastrangelo** [comment]
I don't believe so.  AppEngine 7 had a different runtime altogether that put lots of restrictions on threads.  AppEngine with Java 8 does not have such restrictions (its a full JVM).

**Comment by igorbernstein2** [comment]
Thanks!
