### ISSUE TITLE
received message twice in provider side during performance testing?

### ISSUE THREAD

**Issue by wenmingwei** [grpc/grpc-java#5428]
### version 1.16.1
I am using Client-Side RoundRobinLoadBalancing, met an issue
invoke gRPC call once, but received same message in provider side twice during performance testing.

Had anyone met this before?
Or is this an known issue?

Thank you very much.

**Comment by ejona86** [comment]
@wenmingwei, did you receive it twice as two separate RPCs, or as a single RPC? gRPC will not duplication messages by default, so I would check whether you have a bug in an interceptor.

**Comment by wenmingwei** [comment]
@ejona86 I checked performance testing client, it has an un-thread-safe usage of Message.Builder

Applogy for rasing this issue.
