### ISSUE TITLE
Make Channel hierarchy more meaningful

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#545]
@nmittler wrote on [issue 64](https://github.com/grpc/grpc-java/issues/64#issuecomment-112221220):
> I think the problem here is that the term "channel" ~= "transport", but "interceptor" != "transport". I think it would be better to provide a more abstract interface that is responsible for creating calls and then all of these "things" would implement/extend that. Something like this:
> 
>```java
> interface CallFactory {
>    Call newCall(MethodDescriptor method);
> }
>```
>```java
> class MyInterceptor implements CallFactory {
>     ...
> }
>```
>```java
> interface Channel extends CallFactory {
>     ...
>     void shutdown();
> }
>```
>```java
> class ChannelImpl implements Channel {
>     ...
> }
>```

Discussion continued further. This issue is for these class renames/additions.

**Comment by ejona86** [comment]
I felt that this reorganization should occur after we know whether `ChannelImpl` will handle load balancing. If "there is only one" `Channel` implementation, then I would just assume not having the `Channel` interface.

Also, almost every interface should be an abstract class, so we can add to it later.

**Comment by nmittler** [comment]
I believe some of this work can be done now, before we make any decisions about Channel being an interface or a concrete class. Certainly the interceptors can be reworked since they'll be unaffected by that decision.

**Comment by ejona86** [comment]
How would the interceptors be changed? Them implementing `CallFactory` wasn't ideal. That's what we used to have and we moved away from it. The current design of having a separate interface for interceptors is working better.

If interceptors do implement CallFactory, then we would need a Factory for intercepting CallFactorys, or something else.

**Comment by ejona86** [comment]
Lots of offline discussion. Agreement:
* Leave Interceptor as-is
* Create a new ManagedChannel that extends Channel
* ManagedChannel has all public methods that ChannelImpl has today
* Create a new ManagedChannelBuilder, based on AbstractChannelBuilder, but without a dependency on ChannelImpl (and no methods implemented)
* AbstractChannelBuilder and ChannelImpl move to internal

Ditto all the above for server-side.
