### ISSUE TITLE
grpc-compiler artifact not found

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#5451]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.19.0

### What did you expect to see?

      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-compiler</artifactId>
        <version>1.19.0</version>
      </dependency>

is in the BOM. However there seems not to be any such artifact on Maven Central.

**Comment by ejona86** [comment]
Fixed by #5455
