### ISSUE TITLE
When having multiple clients with their own stream request observers invoking a server grpc method , after one client receives onError , call is terminated for all other clients 

### ISSUE THREAD

**Issue by mathuvenkat** [grpc/grpc-java#5457]
Please answer these questions before submitting your issue.
### What version of gRPC are you using?
1.7.0

### What did you expect to see?
Client 1 -> rpc a on server A , server streams status back
Client 2 -> rpc a on server A , server throws onError() to client 2
Client 1 stops receiving futher messages , the call is closed.
I expected that only Client 2 will not receive any more messages , but client 1 will continue to .
How can we manage multiple threads/ clients in this scenario ?
Sorry if this is a very basic question, I did research a lot but could not find relevant solutions.

I have a code where there are multiple threads , executing the same rpc  method  ( server streaming) , within which a new channel/stub is constructed to the same gRPC server.
The clients keep receiving data through onNext of the request observer, until one of them throws an error and results in an onError() invocation. 
StreamObserver documentation mentions that after OnError() further calls cannot be made, but in this case , there are multiple clients , each with their own streamobserver object. 
What is the best way to handle this ?

```java 
Runnable syncForService = new Thread() {
               @Override
               public void run() {
                  try {
                     invokeSyncOnService(service, gRPCport);
                  } catch (Throwable e) {
                     buildInvokeExceptionStatus(service, e);
                  }
               }
            };

 private void invokeSyncOnService(String service, int gRPCport)
         throws Exception {
      
      // new channel , asyncstub for every thread. 
         ManagedChannel channel = NettyChannelBuilder.forAddress(url.getHost(), foreignPort).
                 .build();
         Channel channelWithHeader = ClientInterceptors.intercept(channel,
                 interceptor);
         SyncableStub asyncStub = SyncableGrpc.newStub(channelWithHeader)
                 .withCallCredentials(callCreds);

    //...
      for (String replicaUriStr : replicas) {
         final AtomicBoolean isCallCompleteOrErrored = new AtomicBoolean(false);

         StreamObserver<DataChunk> streamObserver =
               new StreamObserver<DataChunk>() {
                  @Override
                  public void onNext(DataChunk dataChunk) {
                     byte[] res = dataChunk.getData().toByteArray();
                        if (res.length > 0) {
                           //...
                            }
                  }

                  @Override
                  public void onError(Throwable t) {
                     _log.error("onError invoked on initiateSync ", t);
                  }

                  @Override
                  public void onCompleted() {
                     _log.info("/initiate call completed for " + service);
                  }
               };

            asyncStub.initiateSync(request, streamObserver);   //-----> server streams status
         
    
      }
   }

```

**Comment by mathuvenkat** [comment]
@carl-mastrangelo - Sorry to tag you directly , does this get assigned automatically ? Was curious if its something quick that one of you can spot , as to what the problem is.
Thanks
Mathangi

**Comment by carl-mastrangelo** [comment]
@mathuvenkat Your expectation is correct, but without seeing the server code I am not sure I can help much.  

Make sure that your Stream Observers are only accessed from a single thread, or else you synchronize before using them between multiple threads.  As long as requests are independent of each other, the StreamObservers should not interact.   It would be helpful to know if you are doing `UNARY` or streaming RPCs, too.

**Comment by mathuvenkat** [comment]
Thank you very much for the response. 
In the code above , what I have is multiple threads invoke the "invokeSyncOnService" , within which a new StreamObserver is instantiated. So each thread gets its own. 
I've also added the server code - the initiateSync method is the streaming rpc , this is the method that 2 threads called , one was expected to fail and the other to continue streaming and complete , but failed after one of them went into onError  . 
I'm trying to understand what should be synchronized here. Trying out few options. 

//Proto
rpc initiateSync (Info) returns (stream DataChunk) {}

//server code
	//grpc server rpc method 
	   @Override
	   public void initiateSync(com.vmware.sync.Info request,
	         io.grpc.stub.StreamObserver<DataChunk> responseObserver) {
	      
	      try {
	         ObserveSessionProgress sessionProgressObs = new ObserveSessionProgress(responseObserver);
	         orchestrator.getSessionProgress().addObserver(sessionProgressObs);
	         responseObserverMap.put(responseObserver, sessionProgressObs);
	         
	         } catch { // } 
	        
	  }

	private class ObserveSessionProgress implements Observer {
		io.grpc.stub.StreamObserver<DataChunk> _responseObserver;

		public ObserveSessionProgress(io.grpc.stub.StreamObserver<DataChunk> responseObserver) {
			_responseObserver = responseObserver;
		}

		@Override
		public void update(Observable o, Object arg) {
			updateSessionStatus(_responseObserver, val);
		}

	}

	private void updateSessionStatus(io.grpc.stub.StreamObserver<DataChunk> responseObserver, String sessionId,
			SyncStageProgress stageProgress) {
		// ....
		responseObserver.onNext(DataChunk.newBuilder().setData(status.toByteString()).build());
	}

//client code
public void invokeSyncOnService{
 //instantiate new channel, stub
// Instantiate new stream observer 
StreamObserver<DataChunk> streamObserver =
               new StreamObserver<DataChunk>() {
                  @Override
                  public void onNext(DataChunk dataChunk) {}
                
                  @Override
                  public void onError(Throwable t) {
                     _log.error("onError invoked on initiateSync ", t);
                  }
               };
//invoke the rpc
            asyncStub.initiateSync(request, streamObserver); 
}
