### ISSUE TITLE
publishToMavenLocal failed in checkArtifacts

### ISSUE THREAD

**Issue by voidzcy** [grpc/grpc-java#5465]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
master-HEAD SNAPSHOT 1.20

### What did you expect to see?
When I try to build master 1.20 on Mac, ./gradlew build -PskipCodegen=false succeeded while ./gradlew publishToMavenLocal failed at grpc-compiler:checkArtifacts.

Here is the error output:

Task :grpc-compiler:checkArtifacts FAILED

Checking format of build/artifacts/java_plugin/protoc-gen-grpc-java.exe
Format=x86_64

Checking dependencies of build/artifacts/java_plugin/protoc-gen-grpc-java.exe
Checking for expected dependencies ...
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
Checking for unexpected dependencies ...
        /usr/local/lib/libprotoc.17.dylib (compatibility version 18.0.0, current version 18.0.0)
        /usr/local/lib/libprotobuf.17.dylib (compatibility version 18.0.0, current version 18.0.0)
ERROR: found unexpected dependencies (listed above).

**Comment by ejona86** [comment]
Hmm... what version of Mac are you building on? Did you build protobuf yourself?

Try building protobuf with `--disable-shared` passed to configure.

**Comment by ejona86** [comment]
It looks like our COMPILING documentation should be updated to include --disable-shared. Previously we only checked the dependencies before uploading to Maven Central, but now we are checking it for maven local as well. So I guess we're just finding places there were using shared libraries even though we don't use them normally.

**Comment by voidzcy** [comment]
I rebuilt protobuf with `--disable-shared` option passed to configure. The problem still exists and the output is the same as above. 

Here is my Mac version:

ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

**Comment by ejona86** [comment]
Where did you install to? Is it possible the old .so's or such are still laying around?

We test on Mac OS X 10.13. _Maybe_ XCode 10.1.

**Comment by ejona86** [comment]
Oh, looks like you installed to /usr/local. Hmm... May be a bit of a pain to test.

**Comment by ejona86** [comment]
Confirmed things are now working. It may have just needed a `gradlew clean` after using `--disabled-shared`. #5470 will improve the documentation.
