### ISSUE TITLE
Server shutdown, client see different errors

### ISSUE THREAD

**Issue by BlueStalker** [grpc/grpc-java#5468]
This is the issue I originally posted on https://github.com/grpc/grpc-go/issues/2679

What version of gRPC are you using?
1.19.0

What version of Go are you using (go version)?
go version go1.11.4 linux/amd64

What operating system (Linux, Windows, …) and version?
Linux, 4.14.97-90.72.amzn2.x86_64

What did you do?
If possible, provide a recipe for reproducing the error.

It's bidi stream, and the client is do thing just like: (I open multiple stream inside the same go client).
```
go func() {
    for {
      in, err := RequestStream.Recv()
    }
  }()
```
and server side is java, using 1.17.1, and the server side code,it just normally send stuffs into stream, and everthing is ok, and when I do engine.shutdown() in server side,
I see the above code received different kinds of err, some of them is
```
rpc error: code = Unavailable desc = transport is closing
```
and some are:
```
rpc error: code = Canceled desc = context canceled,
```
and In my go code, I didn't seem to do cancel to the stream, why I got some cancel errors?

**Comment by dapengzhang0** [comment]
When the grpc server is shutting down, the client will see UNAVAILABLE for new rpcs (In which case the request has not been processed by the server side); if the connection is closed, existing rpcs (In which case the request has been (partially) processed by the server) may see CANCELLED. Both are expected behavior.

**Comment by dapengzhang0** [comment]
@BlueStalker Some questions: Did you set a deadline on client side? If you turn on logging on server side, can you see any CANCELLED status and description in the log? What does `engine.shutdown()` do, did you have any shutdown hook to gracefully shutdown grpc servers?

**Comment by BlueStalker** [comment]
@dapengzhang0 I will first appreciate for your kindly reply. The actual problem I want to debug is:
our server and client are in bidi stream, and clients are not sending any requests to the server before server shutdown be called. and the client opens multiple streams to server.

In our server log, before invoking ```io.grpc.Server#shutdown```, in our server logs, we do see server are sending responses to the multiple client streams (we print the logs after we call responseObserver.onNext().
Then ```io.grpc.Server#shutdown``` called, 

then in our client logs, as I mentioned in the first thread, during 
```
in, err := RequestStream.Recv()
```
some of the client stream we saw ``` code = Unavailable desc = transport is closing```
and some of them ``` code = Canceled desc = context canceled ```,
and the interesting thing is, looks like the "Unavailable" stream successfully got all the response from server, while, the "canceled" one are losing response.

We don't want to lose any messages from server, do you have any suggestions? 

Some interesting thing is: it looks like if I update both client and server from 1.17 to 1.19, I can not reproduce this problem, at least for several tries. Is this an existing known issue?

**Comment by dapengzhang0** [comment]
`io.grpc.Server#shutdown()` does not let any existing streams fail. `io.grpc.Server#shutdownNow()` does. So what shutdown hook is in your `engine.shutdown()` matters. If you just call `io.grpc.Server#shutdown()` and then let the system abruptly quit everything, then any weird thing can happen. One of the right ways to gracefully shutdown grpc server is to call `grpcServer.shutdownNow().awaitTermination();`

**Comment by BlueStalker** [comment]
Thanks a lot for these suggestions! And grpcServer.shutdownNow().awaitTermination() looks very promising in our testing!
Just wondering, you were talking about the shutdown hook in engine.shutdown(), do you mean JVM shutdown hook or shutdown hook inside grpc java server? Would you please to provide the doc link for this shutdown hook? I would like to learn details about it. Thanks a lot!

**Comment by dapengzhang0** [comment]
Never mind. @BlueStalker As you didn't say what your `engine.shutdown()` is, I though you were using App Engine.

**Comment by dapengzhang0** [comment]
@BlueStalker Feel free to reopen if the problem persists.
