### ISSUE TITLE
Customise code generation to not include final methods

### ISSUE THREAD

**Issue by hpehl** [grpc/grpc-java#5471]
### What version of gRPC are you using?

1.18.0

### What did you expect to see?

I use grpc-java as part of the [quarkus-grpc-extension](https://github.com/hpehl/quarkus-grpc-extension). The extension enables to use grpc-java in Quarkus. One of the extension's feature is to use CDI in gRPC services. gRPC services and interceptors should be singletons and my first attempt to make them `@ApplicationScoped` failed due to a final method in the generated service code (final on `bindService()`). This makes it hard to create a dynamic proxy. 

It would be great if one could customise the code generation in a way that the user can control whether he wants to have final methods or not.

**Comment by ejona86** [comment]
Why does `@ApplicationScoped` require a dynamic proxy?

Customizing the code generation is not an option. All users must see the same generated code, to prevent dependency hell.

**Comment by dapengzhang0** [comment]
>Customizing the code generation is not an option. All users must see the same generated code, to prevent dependency hell.

Agree. You might want to define a wrapper class that delegates relevant methods to an instance of the generated class, and make the wrapper class a proxyable bean; but not to modify the generated code.

**Comment by hpehl** [comment]
> Why does `@ApplicationScoped` require a dynamic proxy?

That's an implementation detail of the CDI implementation in Quarkus. 

> Customizing the code generation is not an option. All users must see the same generated code, to prevent dependency hell.

Agree. Using a wrapper is one option. For my use case I found another one using scope `@Dependent` inside a bean with scope `@ApplicationScoped`.

**Comment by carl-mastrangelo** [comment]
@hpehl 

>It would be great if one could customise the code generation in a way that the user can control whether he wants to have final methods or not.

If you are open to the idea, gRPC Stubs have annotations on the MethodDescriptors which allows annotation processors to automatically consume them.  You could produce your own stubs using gRPC's in your Java code, if you wanted.
