### ISSUE TITLE
Invalid UTF-8 ByteString generated for uint64 greater than value 55903.

### ISSUE THREAD

**Issue by vihangpatil** [grpc/grpc-java#5482]
In a _nested_ `message`, setting `uint64`  to value greater than `55903` causes `ByteString` of `message` to be invalid `UTF-8`.

Issue is reproduced using a sample project - https://github.com/vihangpatil/grpc-issues

Details are in the README.md of this project.  But, for a quick reference for the important files:
 * [Proto file - grpc.proto](https://github.com/vihangpatil/grpc-issues/blob/master/src/main/proto/grpc.proto)
 * [JUnit test case](https://github.com/vihangpatil/grpc-issues/blob/master/src/test/kotlin/dev/vihang/issues/grpc/GrpcByteStringUtf8Test.kt)

### What version of gRPC are you using?
 - Gradle Protocol Buffers Plugin - `id "com.google.protobuf" version "0.8.8"`
 - protoc - `com.google.protobuf:protoc:3.7.0`
 - gRPC Java dependencies - `io.grpc:grpc-*:1.19.0`

### What did you expect to see?
`ByteString` to of `message` to be a valid UTF-8.

**Comment by carl-mastrangelo** [comment]
Why would you expect encoding a proto to produce UTF-8?   It's a binary format.   Only `string` fields contained within protos are UTF-8.
