### ISSUE TITLE
Setting a deadline for a long-lived streaming stub

### ISSUE THREAD

**Issue by danotorrey** [grpc/grpc-java#5498]
We are using an implementation of bi-directional gRPC streaming, and are interested in setting an appropriate deadline for each request. The stub is used for a long-lived/high throughput stream.

When using unary, I know we could create a new stub for each request, then use it for the unary request.

However, with streaming, the stub is used for lots and lots of requests. Is there a way to set the deadline for an existing stub on on a message by message basis? I did not see anything for streaming deadlines in the examples https://github.com/grpc/grpc-java/tree/master/examples.

In our code, we are using `requestStreamObserver.onNext(requestMessage)` to queue up each message for sending.

**Comment by danotorrey** [comment]
Is there any known performance impact from setting a deadline like this for our high throughput scenario?

```
this.stub = stub.withDeadlineAfter(this.requestTimeout, TimeUnit.MILLISECONDS);
requestStreamObserver.onNext(requestMessage);
```

**Comment by carl-mastrangelo** [comment]
Hi,

Deadlines aren't used often on streaming calls.  You can set a deadline per message, but it's a little more difficult to do.  You will need to for the stub with a `ClientInterceptor`, which sets a timer for each message, and cancels it each time a message is received.   I made a similar example for doing connection timeouts, but you can use it as a starting point:

https://github.com/carl-mastrangelo/grpc-java/commit/4a31a589c98f5f9c6f87206a6cb3c8d43b136924

You will need to override the `onMessage` method of the listener.

**Comment by danotorrey** [comment]
Thank you @carl-mastrangelo! This is exactly what we needed.

**Comment by danotorrey** [comment]
Thank you for the example @carl-mastrangelo. This worked perfectly for our implementation.
