### ISSUE TITLE
I would like to contribute a streaming timeout/deadline example

### ISSUE THREAD

**Issue by danotorrey** [grpc/grpc-java#5507]
I recently talked to @carl-mastrangelo about how to add timeout/deadline support for bi-directional gRPC streaming (see https://github.com/grpc/grpc-java/issues/5498). The solution works great. I would like to contribute an example for how to do this to the [Examples](https://github.com/grpc/grpc-java/tree/master/examples) area of this repository. I wanted to check with the grpc-java team first before submitting a PR to make sure you are good with this. The main idea is to provide an example that others can benefit from when using streaming. The documentation for gRPC says that deadlines are important (to avoid the default internal possibly indeterminate timeouts), so I think it would be good to include a sample that others could work from.

Please let me know what you think. If in agreement, I will draft and submit a PR.

**Comment by carl-mastrangelo** [comment]
SGTM.  You can see a recent PR that added an example.  You can follow the pattern (file location, name, etc.) here: https://github.com/grpc/grpc-java/commit/128409000ae9cff5b31b16851626471cbb2b9b6d
