### ISSUE TITLE
Update GoogleAuthLibraryCallCredentials to use non deprecated constructor in google-auth-library-java

### ISSUE THREAD

**Issue by kolea2** [grpc/grpc-java#5513]
In google-auth-library-java, we will be removing a deprecated constructor in ServiceAccountJwtAccessCredentials: https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java#L109

This is currently used in GoogleAuthLibraryCallCredentials: https://github.com/grpc/grpc-java/blob/1ed196c585da22ef8c10331b8cb6521298a9e671/auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java#L270 which throws an exception when removed: https://github.com/grpc/grpc-java/blob/1ed196c585da22ef8c10331b8cb6521298a9e671/auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java#L229

This implementation will need to be changed to be compatible with future versions of the auth library.

**Comment by sduskis** [comment]
@kolea2, I please see #5509
