### ISSUE TITLE
Android Interopt Test is breaking due to mockito upgrade

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#5523]
See https://github.com/grpc/grpc-java/pull/5484#issuecomment-478637238

cc @TimvdLippe

**Comment by TimvdLippe** [comment]
Could you provide some instructions on how I can debug this issue? We should be able to fix this by updating the Android tooling.

**Comment by TimvdLippe** [comment]
I think you need to update https://github.com/grpc/grpc-java/blob/d8b5d84ce7a418e6e011233416194a087ff2ede1/android-interop-testing/build.gradle#L9 to at least version 3.3.0

Also note that Dexmaker is NOT deprecated and is intended to be used as mockmaker on Android.

**Comment by dapengzhang0** [comment]
@TimvdLippe  From this link (I'm not sure whether you have access to)
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fjava%2Fmaster%2Fbranch%2Fandroid-interop
Click trigger build. This will build android-interop test for a branch or a commit sha. Unfortunately this is not part of presubmit.

**Comment by TimvdLippe** [comment]
I can inspect the results but have no permission to trigger a new build. I do think https://github.com/grpc/grpc-java/issues/5523#issuecomment-478651626 should fix the issue.

**Comment by dapengzhang0** [comment]
Move to milestone 1.21 because android-interop-testing is not published to maven.

**Comment by dapengzhang0** [comment]
v1.20.x is also failing.
https://sponge.corp.google.com/target?id=523826f1-a75e-4172-89f6-2b9d82d8b9d9&target=grpc%2Fjava%2Fv1.20.x%2Fbranch%2Fandroid-interop&searchFor=

I believe #5544 will fix that, no need to bump android gradle plugin and protobuf gradle plugin and all that.
