### ISSUE TITLE
Let Netty decide number of threads for default NioEventLoopGroup

### ISSUE THREAD

**Issue by mpnewcomb** [grpc/grpc-java#5551]
netty/src/main/java/io/grpc/netty/Utils.java:

DefaultEventLoopGroupResource decides the default parallelism for the NioEventLoopGroup if numEventLoops is 0. Please let Netty decide that because we can override the value with a property (io.netty.eventLoopThreads) instead of in code. Please let 0 (the default) pass through.

Thanks,
Michael

**Comment by carl-mastrangelo** [comment]
@mpnewcomb don't we do that already?

**Comment by mpnewcomb** [comment]
Utils.java#193
`      int parallelism = numEventLoops == 0
          ? Runtime.getRuntime().availableProcessors() * 2 : numEventLoops;`

**Comment by carl-mastrangelo** [comment]
Filed https://github.com/grpc/grpc-java/pull/5585
