### ISSUE TITLE
ClientCall errors does not finally invoke ClientCall.Listener.onClose()

### ISSUE THREAD

**Issue by ravirajj** [grpc/grpc-java#5576]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

v1.19.0

### What did you expect to see?

`ClientCall.Listener.onClose()` should be invoked when there is a ClientCall error for unary calls.

When there is an exception thrown by `call.sendMessage()` or `call.halfClose()` within `asyncUnaryRequestCall()` (See https://sourcegraph.com/github.com/grpc/grpc-java/-/blob/stub/src/main/java/io/grpc/stub/ClientCalls.java#L276:37), it results in `cancelThrow()` calling `ClientCall.cancel()` and scheduling a stream closed task (i.e. `ClientCall.Listener.onClose`) on the executor.  However, the exception propagates up to `futureUnaryCall ` and `blockingUnaryCall` which catches it again, calls `cancelThrow()` again but never drains the executor within the try-catch block (See https://sourcegraph.com/github.com/grpc/grpc-java/-/blob/stub/src/main/java/io/grpc/stub/ClientCalls.java#L123-146).  Thus `ClientCall.cancel()` is called but not `ClientCall.Listener.onClose()` on client call errors.

Is `ClientCall.Listener.onClose()` expected to be called whenever the client call terminates?  Is dropping the `ClientCall.Listener.onClose()` call a bug or expected behaviour?

**Comment by ejona86** [comment]
Fix was reverted in #5641

**Comment by ejona86** [comment]
See cl/245431681 for information about the failing test.
