### ISSUE TITLE
Using grpc with TLS

### ISSUE THREAD

**Issue by YiuRULE** [grpc/grpc-java#558]
Hello,

I'm working on grpc in android, and I want to use a self signed certificate.
```
OkHttpChannelBuilder.forAddress(mHost, mPort)
.sslSocketFactory(TestUtils.getSslSocketFactoryForCertainCert(TestUtils.loadCert("my_cert")))
.build();
```

But when I want to send request, a exception of type io.grpc.StatusRuntimeException is throw.
It's the good way to initialise TLS in grpc ?

**Comment by ejona86** [comment]
Can you provide the backtrace from the `StatusRuntimeException`?

**Comment by ejona86** [comment]
Closing since no response. Feel free to provide part of the backtrace and we can reopen diagnosing the issue.
