### ISSUE TITLE
client side proxy when using ManagedChannelBuilder.forTarget()

### ISSUE THREAD

**Issue by anusha-hv** [grpc/grpc-java#5600]
Please answer these questions before submitting your issue.

### What version of gRPC are you using? 
I have been using 1.16.1 version. Now upgraded to 1.20.0 version. 
The machine where am running the client side ie, ManagedChannelBuilder.forTarget(serveraddress)  call is used is proxy enabled. 
I get an error saying "Channel closed while trying to CONNECT through proxy"

I can read the proxy address from environment variable http_proxy.  
For example : http_proxy="10.9.3.2.9090" and my target Address = "10.45.6.1:7070" (ie grpc server is running on another machine)
How do i make the grpc allow this proxy and send request to the target Address. 

### What did you expect to see?
I need a sample example. I see a proxydetector that is available but not sure about the usage of it since the method takes a single address.  

I am new to grpc.  Need help.

**Comment by ejona86** [comment]
Your setup previously worked with 1.16 and broke when upgraded to 1.20? grpc-java does not observe the `http_proxy` environment variable. It observes Java's proxy settings, which generally implies you should specify `-Dhttps.proxyHost=example.com` and `-Dhttps.proxyPort=8080` on the command line to java (before any -jar or class name to run).

If you want to override Java's default behavior for proxy detection, call [ProxySelector.setDefault()](https://docs.oracle.com/javase/8/docs/api/java/net/ProxySelector.html#setDefault-java.net.ProxySelector-). If you need to override the proxy for a single channel, like within a library, that's when to use ProxyDetector.

**Comment by anusha-hv** [comment]
@ejona86 No issues with the upgrade of grpc as such. Let me explain the problem in detail. 
My product is a war which has the GRPC client and is deployed on Tomcat . Since it is deployed on tomcat, i have the proxy settings http.proxyHost=10.194.10.21 http.proxyPort=3128 in  catalina.properties of tomcat. 

My GRPC server is a jar that runs on the machine with proxy enabled. 
 Whenever a call goes from the grpc client (part of war deployed on tomcat) to grpc server , I get an error on the client side saying ""Channel closed while trying to CONNECT through proxy".
Unable to resolve this. Need help.

**Comment by ejona86** [comment]
Ah, okay. Then I think the only problem is you need to set _https_.proxyHost/proxyPort instead of/in addition to _http_. gRPC only supports the HTTP Connect proxy protocol, which is what is used with _https_, so independent of whether you are using TLS or plaintext in gRPC you need to set the _https_ configuration.

**Comment by anusha-hv** [comment]
@ejona86   I already have the https configuration too along with http configuration in catalina.properties of tomcat. I have both http.proxyHost=10.194.10.21 http.proxyPort=3128 and https.proxyHost=10.194.10.21  https.proxyPort=3128 in catalina.properties of tomcat (grpc client) . I am using plaintext in grpc. 

I get the same error "Channel closed while trying to CONNECT through proxy".

**Comment by ejona86** [comment]
@anusha-hv, sorry. It should have been clear to me that the configuration was working, since "Channel closed while trying to CONNECT through proxy" implies that gRPC tried to use the proxy.

The proxy closed the connection without responding with an error. So it is unclear what is wrong. It may be that your proxy doesn't support CONNECT or that it is missing your server from some whitelist of servers to forward to. For the first, you could check by using HTTPS through the proxy (not grpc, just some "plain" https client).

I'd suggest looking over the proxy server's configuration. If you can check the proxy's logs or enable more debugging logs, you might be able to discover what's wrong.

**Comment by anusha-hv** [comment]
@ejona86 one thing i noticed. When i use localhost:port_number on client side, even with client's side proxy enabled, i don't see this issue.I have both grpc client(war) and grpc server(jar) running on the same machine. Everything works fine when i use localhost. 
Instead of localhost, if i use the hostname or the machine IP , I get the same error "Channel closed while trying to CONNECT through proxy". I have both my grpc client and server on the same machine.

**Comment by ejona86** [comment]
Proxies commonly have whitelists for allowed hosts. There may be another reason. But again, you will have to debug your proxy; it's not something we can really help with.

If you provide a tcpdump (or the plain-text output, since it is HTTP/1) of the communication from grpc to the proxy, I could look at it to confirm that gRPC is behaving as expected and see if the proxy provides any hint as to what is wrong. But this would be more of a double-check.

**Comment by anusha-hv** [comment]
Hi @ejona86 i tried  a sample example with grpc-java client and server on the proxy enabled machine.  Both are independent jars . instead of the localhost, i used the IP and port . I did not provide the proxy flags as well while running the jars. It all works fine.  
Now when the client is part of an existing war deployed in tomcat(which uses HTTP 1.1) , it complains telling "Channel closed while trying to CONNECT through proxy" even after having the the proxy flags defined in tomcat.

**Comment by ejona86** [comment]
> Ideally it should not be bothered with gRPC client server communication.

Oh, so you want to disable the proxy just for gRPC? If you can configure your code specifically for this environment, you can disable the proxy in gRPC with [`ManagedChannelBuilder.proxyDetector()`](https://grpc.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#proxyDetector-io.grpc.ProxyDetector-):

```java
managedChannelBuilder.proxyDetector(new ProxyDetector() {
  @Override ProxiedSocketAddress proxyFor(SocketAddress addr) {
    return null;
  }
});
```

**Comment by anusha-hv** [comment]
Hi @ejona86  Am sorry , please Ignore my previous comment
Even with the sample application with simple grpc client and server (both are jars) ,when i specify the flags -Dhttps.proxyHost=10.194.10.21 Dhttps.proxyPort=3128 in the commandline , i get the same error which says "channel closed while connecting through proxy" while running the grpcClient.jar .
Like you suggested, I am attaching the dump captured via wireshark of the actual problem (with client deployed on tomcat). Let me know if there is anything else i can try. 

[dumptobeshared2.zip](https://github.com/grpc/grpc-java/files/3126107/dumptobeshared2.zip)

**Comment by ejona86** [comment]
@anusha-hv, it was as I suspected: the proxy is just hanging up. That means I just have to guess what could be going wrong. It is strange that the proxy doesn't respond with anything to the CONNECT request. And then 10 seconds after the CONNECT request the client sends... something more. I don't recognize what it sends. But at _that_ point is when the proxy disconnects.

There is one successful CONNECT handshake in the dump, from something non-gRPC. It does show a 200 OK response from the proxy with just the HTTP CONNECT request. It takes .6 seconds for the reply.

So the riddle is why is there a 10 second gap. Could it be that the proxy can't connect to the destination machine?

**Comment by anusha-hv** [comment]
@ejona86 , I have both my grpc client(deployed on tomcat as war) and my grpc server (as jar) on the same machine. So am not sure when you say proxy can't connect to the destination machine.
 I missed out sending the logs. Whenever the proxy is enabled for the grpc client,  i can see this in the logs. 
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while trying to CONNECT through proxy
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)

**Comment by ejona86** [comment]
All signs point to "debug the proxy." The client knows nothing. There's no more help we can provide, unless you want to avoid using the proxy with gRPC.

**Comment by ejona86** [comment]
Closing since there's not much more we can help with. If there's some more information provided that makes it seem like it's a gRPC bug instead of a proxy configuration issue, comment and it can be reopened.
