### ISSUE TITLE
Question: how to set Status details?

### ISSUE THREAD

**Issue by theangrydev** [grpc/grpc-java#5616]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.20.0

### What did you expect to see?
As per https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto I would expect `io.grpc.Status` to have the same `repeated google.protobuf.Any details = 3;` functionality but I can't find out how to do this in Java.

Could you please advise on how to achieve using this details field? Thanks

**Comment by ejona86** [comment]
See if https://stackoverflow.com/a/48750825/4690866 helps.

**Comment by carl-mastrangelo** [comment]
io.grpc.Status is a special casing of two fields in google.rpc.Status.   The repeated Any's are just individual headers in gRPC.

**Comment by theangrydev** [comment]
Thanks for the information @carl-mastrangelo @ejona86
