### ISSUE TITLE
Bidirectional streaming RPC

### ISSUE THREAD

**Issue by xxxxpenny** [grpc/grpc-java#5631]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.18.0

### What did you expect to see?
```java
        AtomicReference<StreamObserver<HelloRequest>> ref = new AtomicReference<>();


        StreamObserver<HelloReply> reply = new StreamObserver<HelloReply>() {
            @Override
            public void onNext(HelloReply value) {
                System.out.println(value.getMessage());
            }

            @Override
            public void onError(Throwable t) {
                try {
                    TimeUnit.SECONDS.sleep(1);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                r.run();

            }

            @Override
            public void onCompleted() {

            }
        };

        r = () -> ref.set(serviceStub.sayHello3(reply));

        StreamObserver<HelloRequest> helloRequestStreamObserver = serviceStub.sayHello3(reply);
        ref.set(helloRequestStreamObserver);

        int count = 0;
        while (true) {
            ref.get().onNext(HelloRequest.newBuilder().setName(count + "").build());
            TimeUnit.SECONDS.sleep(1);
            count++;
        }
```
I use bidirectional streaming rpc, and I reconnect when `reply` invoke `onError()`, then update the `helloRequestStreamObserver` ref.

I lost request, it's ok, because  ref update util reconnect success. this are some solution to avoid losing request?

**Comment by creamsoup** [comment]
basically the code snippet is ignoring when server is sending error. it ignored the message that failed and move over, so the message is lost. 
if you are not ignoring `onError`, you should be able to retry the failed message.

**Comment by xxxxpenny** [comment]
> basically the code snippet is ignoring when server is sending error. it ignored the message that failed and move over, so the message is lost.
> if you are not ignoring `onError`, you should be able to retry the failed message.

emm, How to get the failed message to retry, I can't find the method.

**Comment by creamsoup** [comment]
when `onError` is called the last attempted message is the message need to be retried. The example code you provided is not structured in a way that it is hard to get the last attempted message. Mainly, because the StreamObserver is stateless and can't signal the loop if it failed or not (missing error handling).

**Comment by creamsoup** [comment]
closing the issue due to inactivity.
