### ISSUE TITLE
GC friendly long live server streaming

### ISSUE THREAD

**Issue by Gordiychuk** [grpc/grpc-java#5636]
In my application, I use server streaming, when client send request and receive responses until connection will not close(days or more). At heapdump i found that initial request never released until stream not close.

https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/ServerCalls.java#L132
![Screenshot from 2019-04-25 17:06:10](https://user-images.githubusercontent.com/10699594/56742163-e493ae00-677c-11e9-9223-b9e144403084.png)

Why not release it as only method was invoked at this place https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/ServerCalls.java#L171

**Comment by ejona86** [comment]
Fixed by #5638
