### ISSUE TITLE
grpc-protobuf-lite not working with com.google.cloud:google-cloud-bigtable

### ISSUE THREAD

**Issue by suztomo** [grpc/grpc-java#5644]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.20.0

### What did you expect to see?

The use of `io.grpc:grpc-protobuf-lite` and `com.google.cloud:google-cloud-bigtable` should not raise `NoSuchMethodError`.

-------

While I was checking the compatibility of google libraries, I found `grpc-protobuf-lite` has classes that are not compatible with many GCP-related libraries (the list noted below), including `com.google.cloud:google-cloud-bigtable:jar:0.84.0-alpha`.

Example project to reproduce this issue: https://github.com/suztomo/protobuf-lite-vs-bigtable shows:

```
java.lang.NoSuchMethodError: com.google.protobuf.UnsafeByteOperations.unsafeWrap([B)Lcom/google/protobuf/ByteString;
    at com.google.cloud.bigtable.data.v2.models.Range$ByteStringRange.prefix (Range.java:363)
    at com.google.cloud.bigtable.data.v2.models.Range$ByteStringRange.prefix (Range.java:336)
    at suztomo.App.main (App.java:14)
```

For `grpc-protobuf-lite`, I only found this sentence in the doc:

> For Android client, use grpc-okhttp instead of grpc-netty-shaded and grpc-protobuf-lite instead of grpc-protobuf
from [grpc-java documentation](https://github.com/grpc/grpc-java)

# Questions

- Would you explain the difference between `grpc-protobuf` and `grpc-protobuf-lite`?
- Do you think the incompatibility between `io.grpc:grpc-protobuf-lite` and `com.google.cloud:google-cloud-bigtable` is something that needs to be fixed (probably for Android apps accessing GCP services)?

# Incompatible Libraries

Other libraries that seem not compatible with `grpc-protobuf-lite` includes: `com.google.cloud:google-cloud-automl:jar:0.84.0-beta`, `com.google.cloud:google-cloud-bigquerydatatransfer:jar:0.84.0-beta`, `com.google.cloud:google-cloud-container:jar:0.84.0-beta`, `com.google.cloud:google-cloud-datastore:jar:1.66.0`, and `com.google.cloud:google-cloud-speech:jar:0.84.0-beta`.

**Comment by creamsoup** [comment]
The main differences between regular `protobuf` and `protobuf-lite` is binary size and mobile optimization. Protobuf-lite's binary size is around an order of magnitude smaller (according to protobuf doc), but some features are not available. See [protobuf option section](https://developers.google.com/protocol-buffers/docs/proto3#options) for more details. Also, [this doc](https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md) mentions about compatibility between regular protobuf vs lite.

`io.grpc:grpc-protobuf-lite` is basically using `protobuf-lite` aka protobuf for android. `com.google.cloud:google-cloud-bigtable` [doesn't supports android](https://github.com/googleapis/google-cloud-java#supported-platforms). If you think the `google-cloud-bigtable` should support android, you can create a feature request. Or, consider firebase as the doc suggests.

If you have to use the google-cloud-bigtable library and okay with much larger binary size, I believe you can still use regular protobuf on android (you can't depend on both `protobuf` and `protobuf-lite`).

**Comment by suztomo** [comment]
Thank you for quick response with detailed answers.

> com.google.cloud:google-cloud-bigtable doesn't supports android

I’ve missed this part. I think I will stop checking compatibilities between grpc-protobuf-lite and GCP java libraries. Closing this issue.

**Comment by elharo** [comment]
We should probably figure out if that's true for all google-cloud-java libraries. If so, we should simply drop protobuf-lite from cloud-oss-bom.
