### ISSUE TITLE
Rely on ChannelFactory in NettyServer instead of dynamic classes

### ISSUE THREAD

**Issue by perezd** [grpc/grpc-java#5649]
Reading up on what it takes to support Graal native image compilation for gRPC, most of the incompatibilities are in the Netty tier (not the responsibility of this repo), but here's a low hanging fruit item:

They suggest using a ChannelFactory when working with ServerBootstrap to prevent unecessary reflective instantiation, something like this:
https://gist.github.com/cstancu/ee36a5b4911775e8eafb240c8db36942#file-netty-svm-httpserver-httphelloworldserver-java

I spotted #5460 as well which talks about Netty things, but the article I'm including also shows that this sort of thing can be sideloaded/managed externally from this repo. The change I am suggesting however would impact the ServerBuilder API a bit, but I think it might be a good one long term anyhow, WDYT?

More info @ this article:
https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692

**Comment by perezd** [comment]
For reference, `channelType` is passed in as a `Class<? extends ServerChannel>` today.

**Comment by creamsoup** [comment]
I also prefer to use `channelFactory`. However, there are few issues I can think of.
There is [one reference](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServer.java#L160) that checks `channelType` to set some SocketOptions. Those options can be blindly set if we decided to use `channelFactory`.
The other issue is we can't just remove the old API (`channelType`), we could mark it deprecated and use `ReflectiveChannelFactory` just like `NettyChannelBuilder`. Although this approach doesn't really removes the reflection.

**Comment by ejona86** [comment]
We added `channelFactory` to NettyChannelBuilder. Is the request to add the same to NettyServerBuilder? That seems easy.

By default we'd still be using the ReflectiveChannelFactory (either directly, or indirectly by providing a Class that Netty instantiates).

> They suggest using a ChannelFactory when working with ServerBootstrap to prevent unecessary reflective instantiation

Can you link do the documentation you are reading? What is the reason they provide to avoid reflection?

**Comment by perezd** [comment]
It's outlined in that article I linked. Specific advice for GraalVM native
image construction for Netty.

**Comment by perezd** [comment]
And yes, ideally it'd be possible to provide a ChannelFactory which is passed directly through to server bootstrap to prevent reliance on reflective classes.

**Comment by ejona86** [comment]
I see where it talks about needing to add a configuration file for the reflection.

So it seems there's two easy changes that would be good:
1. Add `NettyServerBuilder.channelFactory()`
2. Implement our own ChannelFactory for the default Nio{,Server}Channel

I see no reason to deprecate or remove `channelType()`. It will continue to use reflection, and that's okay.

**Comment by perezd** [comment]
totally fair, I should not have said "instead", my apologies. I think this sounds like a solid path forward. There's definitely no reason to deprecate, both options seem useful to a broader audience.

**Comment by ejona86** [comment]
@perezd, the thing about `channelType()` was mainly in response to @creamsoup's comment.

**Comment by ejona86** [comment]
@perezd, we'd be happy to accept a PR for this. With f4fb7b40c it should now be pretty easy. In `NettyServerBuilder` pass a `channelFactory` to `NettyServer` instead `channelType` (which we do in `NettyChannelBuilder` already). Updating tests will probably be most annoying.

NettyChannelBuilder.DEFAULT_CHANNEL_FACTORY should probably also be updated, and that's still not hard, but starts touching some epoll reflection goo.
