### ISSUE TITLE
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available

### ISSUE THREAD

**Issue by yyl719133368** [grpc/grpc-java#5655]
Description in this issue...
https://github.com/googleapis/cloud-bigtable-client/issues/2140

**Comment by ejona86** [comment]
It is normal for Conscrypt and Jetty ALPN to fail.

In the output, this is the important area:
```
Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64480984008753957383.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64480984008753957383.so)
```

And stripping out more of it:
```
Error loading shared library libcrypt.so.1
```

This is a missing runtime dependency. You need to run [`apk update && apk add libc6-compat`](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty) within the container.

**Comment by MrStobbart** [comment]
I could solve a similar issue by using jdk11 instead of 8 as ALPN is available by default in Java 11
