### ISSUE TITLE
Remove MoreThrowables as stated in TODO

### ISSUE THREAD

**Issue by NickUfer** [grpc/grpc-java#5660]
### What version of gRPC are you using?
1.20

I've found a class in grpc-core by @ejona86 which should be deleted when Guava 20+ is being used. The class is still being used and we are now using guava 26, so I think this could be refactored or the TODO removed.
Merge Request: https://github.com/grpc/grpc-java/pull/2751
Class: https://github.com/grpc/grpc-java/blob/d50c8d4ec1fb05a55c8a166c804dc8c37559c23e/core/src/main/java/io/grpc/internal/MoreThrowables.java

**Comment by creamsoup** [comment]
thanks for finding that out, @NickUfer. Do you want to make a PR?

**Comment by NickUfer** [comment]
Good idea. At the first look I thought this would be too heavy for me and I would probably just break something but actually it seems to be easy.

**Comment by ejona86** [comment]
This was fixed in #5662. I purposefully made it easy to delete :-)
