### ISSUE TITLE
Occasional spikes of 500ms-2s latency on sending from java grpc client to java grpc server

### ISSUE THREAD

**Issue by jschlather** [grpc/grpc-java#5661]
### What version of gRPC are you using?
1.16

I previously filed https://github.com/grpc/grpc-go/issues/2788 with grpc-go after noticing a large gap between outbound data and inbound window updates. After matching up debug logging on the client and the server, I was able to determine that the requests seem to just not be making it to the server for awhile. For instance below is a debug message from the grpc java client, followed by the corresponding read on the grpc service.

```
2019-05-02 02:11:10.932 [vitess-eventloop-1-1] DEBUG h.v.io.grpc.netty.NettyClientHandler - [id: 0x94a48f60, L:/192.168.102.2:31090 - R:{REDACTED}] OUTBOUND DATA: streamId=9043 padding=0 endStream=true length=518 bytes={REDACTED}
I0502 02:11:11.588269      44 logutil.go:31] log: http2: Framer 0xc005553340: read DATA flags=END_STREAM stream=9043 len=518 data={REDACTED}
```

It seems to be the case that for a small period of time 500ms-2s, no outbound data will be received by the server and then all of it will be received at once. I was wondering if you had any thoughts on what could be causing this or how we could further debug the issue. It seems like one avenue would be to write a custom `Http2OutboundFrameLogger` that adds a timer to the channel future on outbound data being sent.

**Comment by ejona86** [comment]
Those two log statements are _really_ helpful. My initial thought is it looks like packets are getting lost and you're having to wait on retransmits. Although I wouldn't expect 500ms-2s of a wait unless 1) the network was actually down for a period or 2) you are on a high round-trip-time link (500ms would be an eternity for a <1ms ping Ethernet link, for example).

Me personally, I'd fire up wireshark on the machine running grpc-java (or tcpdump and bring the dump into Wireshark). Wireshark would show retransmits, and if using plaintext [can decode the gRPC traffic](https://stackoverflow.com/a/55055296/4690866). I could also look for anything "funny" when things break.

I'd assume you'd already know if a Java GC takes 500ms-2s for your application.

That message is logged right before we do the write syscall. So a custom logger probably wouldn't show very much.

**Comment by zhangkun83** [comment]
According to grpc/grpc-go#2788, it sounds like a TCP layer latency problem. Closing it.
