### ISSUE TITLE
Define and use SubchannelPoolHelper

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#5674]

**Comment by dapengzhang0** [comment]
@zhangkun83 , the new design  go/grpc-xds-lb-policy-design#heading=h.krx7r69l2drb is to use LoacalityMap and to mark a time and mark a "last used" timestamp. Seems the timestamped map approach for caching is more general than CachedSubchannelPool.

**Comment by zhangkun83** [comment]
The design calls out for delaying shutdown of locality maps (which contains child LBs) for lower priorities when locality maps for high priorities become ready. That is different from the case where backend addresses are removed from one locality and later added back on, and `CachedSubchannelPool` is expected to reduce the unnecessary tear-down and reconnect of subchannels. Is it no longer a case in xDS now?

**Comment by dapengzhang0** [comment]
It may still be the case. Will confirm from @markdroth .

There are three scenarios that may need delayed shutdown or subchannel caching:
1. delayed shutdown for low priority localities when a higher priority locality becomes READY.
2. Eds response removes a locality.
3. Eds response removes one of the backends from an existing locality. (RR child balancer handling backend list changes).

1. and 2. are specified in the spec already.

**Comment by markdroth** [comment]
Yes, I think we still want caching of individual subchannels for case 3.

**Comment by dapengzhang0** [comment]
Close as obsolete.
