### ISSUE TITLE
Simplify example-gauth with our recommendations

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#5677]
Instead of `GoogleCredentials.fromStream()`, use `GoogleCredentials.getApplicationDefault()`. We can comment where to put the JSON file and what environment variable to set if they want it somewhere else. We then would note that the JSON file is unnecessary on Google platforms.

Remove `refreshAccessToken()` and its comment. This will be done automatically when necessary.

GOOGLE_AUTH_EXAMPLE.md would require being updated to match.

**Comment by ejona86** [comment]
See also: https://grpc.io/docs/guides/auth/

**Comment by dapengzhang0** [comment]
>We can comment where to put the JSON file and what environment variable to set if they want it somewhere else. 

What about android client? https://stackoverflow.com/questions/55843782/grpc-error-sample-c-code-not-working-cpp-docs-samples

**Comment by ejona86** [comment]
@dapengzhang0, the C++ Android client? That's completely separate and uses different APIs. I think it uses the same environment variables and the APIs look similar, though. I'd have to look at https://grpc.io/docs/guides/auth/ to see what APIs to use in C++.

**Comment by dapengzhang0** [comment]
Regardless of Java or C++, setting environment variables on Android device (not emulator) seems difficult. For java, there is no `System.setenv()` for Android, but only [`getenv`](https://developer.android.com/reference/java/lang/System.html#getenv()).

**Comment by dapengzhang0** [comment]
People have to put the JSON file and set the environment variable if the client calling `GoogleCredentials.getApplicationDefault()` in not running in GCE.

**Comment by sanjaypujare** [comment]
@dapengzhang0 but that's no worse than the current example, is it not? I think @ejona86 's point is that within GCP you don't need to do anything (like installing the JSON file) and that might be useful for some people who will use the example as their starting point to develop GCP client apps.

**Comment by ejona86** [comment]
Oh, I see what you are saying. In general Android is completely different since it doesn't use service accounts. The APIs we document here are for service accounts.

**Comment by vinodhabib** [comment]
Looking into this ticket and Analysis in progress

**Comment by vinodhabib** [comment]
Changes are done and PR raised for Review
