### ISSUE TITLE
Fedora Fix for Netty-Shaded

### ISSUE THREAD

**Issue by JohnPucciarelli** [grpc/grpc-java#5688]
### What version of gRPC are you using?
1.20

### What did you expect to see?
I was unable to get `grpc-netty-shaded` or `grpc-netty` (+ the classifier) working on Fedora 30.

This is the error I encountered when using `netty-shaded`:
```
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
```

And here's the error I encountered when using `grpc-netty` + the fedora classifier:
```
Caused by: java.lang.UnsatisfiedLinkError: libcrypt.so.1: cannot open shared object file: No such file or directory
```

I was able to workaround this issue by creating a sym-link for `libcrypt.so.1`:
```
ln -s /usr/lib64/libcrypt.so /usr/lib64/libcrypt.so.1
```

Creating this link solved the issue for me. 
Note: you might need to install `openssl-devel`.

Leaving this here in-case it helps someone in the future.

**Comment by ejona86** [comment]
@JohnPucciarelli, it looks like you should install the `libxcrypt-compat` package. We can add a note for that in our security.md

**Comment by ejona86** [comment]
FYI @normanmaurer

**Comment by ejona86** [comment]
For the record: I reproduced this locally in a docker container and installing `libxcrypt-compat` corrected the problem.

**Comment by JohnPucciarelli** [comment]
@ejona86 thanks for the help!

**Comment by normanmaurer** [comment]
@ejona86 thanks... let me also add a note to netty-tcnative
