### ISSUE TITLE
Implement timeout/deadline in Channel

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#57]

**Comment by johnbcoughlin** [comment]
@ejona86 would it make sense for me to pick this up at the moment?

**Comment by ejona86** [comment]
@johnbcoughlin, feel free. None of us are actively working on it.

There are two parts to this, and feel free to do them separately or only the one that interests you. Both will use the timeout on MethodDescriptor for now, but that will change with #150. Right now though, just use MethodDescriptor's timeout. Internally, we want to use deadlines instead of timeouts if possible, and with #150 our API will likely change to deadlines.

One part is to communicate the provided deadline/timeout via the [Timeout header](https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md#requests). That should probably happen in ChannelImpl before propagating to the transport, but others may have different opinions of that.

The other part is to set a timer to timeout the RPC. That will probably be a ScheduledExecutor and will make use of the cancellation logic, except with a different status. It would probably make sense to use a single ScheduledExecutor for all ChannelImpls, maybe via SharedResourceHolder.

**Comment by johnbcoughlin** [comment]
Great, thank you for the detailed guidance!

**Comment by johnbcoughlin** [comment]
@ejona86 revisiting this ticket for the second part. Using a different status for the timeout/deadline cancellation seems non-trivial. If the Channel layer is to own timeout handling, then the `ClientStream` interface needs another method or parameter, perhaps `cancel(Status reason)`, or even `cancelForDeadline()`. What do you foresee being the easiest way to go here?

**Comment by ejona86** [comment]
@johnbcoughlin, yes, I see the need to add to the transport. The transport changes aren't trivial, but still seem pretty easy.

I think both `cancel(Status)` and `cancelForDeadline()` are similar in complexity, in that in both cases the transport would probably pass around a `Status` internally. `cancelForDeadline()` is the "smaller" interface, and prevents abuse, but we would only be preventing abuse from ourselves. So I probably would lean toward adding `ClientStream.cancel(Status)`, likely by just adding the argument to the current cancel method.

"Cancelling" with a status code not `CANCELLED` may seem slightly weird to some, but I don't think it would cause too much trouble. The documentation mention that the only intended status codes are `CANCELLED` and `DEADLINE_EXCEEDED` in order to make the method's objective more clear.

`AbstractClientStream.sendCancel()` would get a `Status` argument. For Netty, I would probably add a `Status` field to `CancelStreamCommand` and use the field [when calling `transportReportStatus()`](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/transport/netty/NettyClientHandler.java#L321). For OkHttp, you would just use the `Status` immediately [when calling `finishStream()`](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java#L213).

**Comment by ejona86** [comment]
Implementation completed as part of #576.
