### ISSUE TITLE
Are Interceptors are executed in an unintuitive order?

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#570]
```
// interceptor1 is run before interceptor2
ClientInterceptors.intercept(channel, interceptor1, interceptor2);

// interceptor2 is run before interceptor1
channel = ClientInterceptors.intercept(channel, interceptor1);
channel = ClientInterceptors.intercept(channel, interceptor2);
```

This seems like it would get really confusing if you call intercept multiple times with multiple interceptors each time:
```
channel = ClientInterceptors.intercept(channel, interceptor2,
                                                interceptor1);
channel = ClientInterceptors.intercept(channel, interceptor4,
                                                interceptor3);
```

It seems the first interceptor listed should most likely be the interceptor nearest the library. If there was a single mutable interceptor list then the current behavior would make more sense.

Note that on server-side the application and library are reversed, so reversing the order would make the first interceptor nearest the application.

**Comment by ejona86** [comment]
This has implications with #538 as well, as it will use a builder and accumulate interceptors in a list before calling `intercept()`:
```
builder
    .intercept(interceptor4,
               interceptor3)
    .intercept(interceptor2,
               interceptor1)
    .build();
```

**Comment by nmittler** [comment]
Yup ... +1 to using a builder. Perhaps we should create a builder for an interceptor chain as well and do away with `ClientInterceptors.intercept()` altogether?

**Comment by ejona86** [comment]
No, I wasn't suggesting to use a builder like it seems you are. I was doing the builder in relation to #538; that builder is an AbstractChannelBuilder.

I don't see how using a builder instead of intercept() solves any problem listed in this issue.

**Comment by nmittler** [comment]
I understand, I was suggesting that you also you a builder for the interceptor chain itself.  Then you can have methods like `builder.addFirst(i)`, `builder.addLast(i)`.

**Comment by ejona86** [comment]
It sounds like your builder is becoming a List... What is wrong with providing a list to intercept, like you can do now?

**Comment by nmittler** [comment]
Was just thinking that it might be more clear from a readability point of view as:

builder.addLast(i1).addLast(i2).addLast(channel).build();

rather than:

intercept(channel, i2, i1);

**Comment by ejona86** [comment]
i2 _is_ "last," but what does "last" mean. It doesn't seem to aid at all.

**Comment by ejona86** [comment]
Your second code should have been:

```
intercept(channel, i1, i2);
```

**Comment by nmittler** [comment]
not sure how `last` is ambiguous :/

**Comment by ejona86** [comment]
To take the example: `intercept(channel, i1, i2)`. i2 is `last`, but when is it run relative to i1?

If you have:

```
channel = builder.forChannel(channel). addLast(i1).addLast(i2).build();
channel = builder.forChannel(channel). addLast(i3).addLast(i4).build();
```

i3 and i4 were added after i1 and i2, but they would executed before i1 and i2.

Because of the interception pattern we use, adding interceptors _prepends_ them; it makes them executed first. So that confuses what "last" is; last to execute or last to be added?

**Comment by nmittler** [comment]
Last would certainly be execution order (i.e. the order they are in when the chain is finally built). We don't need the method `addLast` we could only have `addFirst` so that it's clear that we're prepending in all cases.

**Comment by ejona86** [comment]
In offline discussion, we all agreed it made sense to reverse the order of execution of the interceptors provided to intercept(). After the change, the last interceptor will be run first.
