### ISSUE TITLE
ServerServiceDefinition.getMethods should return a Collection

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#572]
Right now it has a return type of ImmutableList, which 1) requires a specific Guava implementation and 2) there is no need for order of the methods. For instance, in the current implementation we _could_ use methodLookup.values().

Note that having "Collection" as the return type but actually returning an ImmutableList is fine though.

I could be convinced that returning a List or Set is appropriate, but if we return Collection now we could actually change to using a List or Set in the future and remain API compatible (since the class is final).

**Comment by zhangkun83** [comment]
Resolved by #611
