### ISSUE TITLE
NPE in DelayedClientTransport

### ISSUE THREAD

**Issue by rsgowman** [grpc/grpc-java#5729]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.16.1 (but also appears to be present in master)

### What did you expect to see?
No NullPointerException in DelayedClientTransport.java

### Description
We (Firestore) have had a few reports of a NPE within DelayedClientTransport.java. (https://github.com/firebase/firebase-android-sdk/issues/428).

Looking at the stacktrace, it seems as though `picker` is null here: https://github.com/grpc/grpc-java/blob/57043233bf5aecce92f0c6629b6ac46d9393ce8c/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L149

Examining that function further, it seems as though picker is set here and here:
https://github.com/grpc/grpc-java/blob/57043233bf5aecce92f0c6629b6ac46d9393ce8c/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L139-L142
https://github.com/grpc/grpc-java/blob/57043233bf5aecce92f0c6629b6ac46d9393ce8c/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L165

In the first case, there's a null check that protects it, but there isn't in the second case. Should there be?

(All links to the 1.16.1 tag, but the code looks effectively the same in master wrt this issue.)

**Comment by ejona86** [comment]
I'll note that we would expect this failure to be rare. It appears to require creating an RPC exactly when gRPC makes a channel idle due to idleTimeout() (which defaults to 30 minutes), and for the Channel to not be READY.

**Comment by rsgowman** [comment]
The report we got said "Users said that everytime they open app it will crash immediately" which doesn't seem like it would mesh with a 30 minute timeout. Is there any other possible way this could be null? (Is there anyway to misuse the API that could cause this to occur more frequently?)

FWIW, at least two users have run into this.

**Comment by ejona86** [comment]
I figured it out. Firebase is using [AndroidChannelBuilder](https://github.com/firebase/firebase-android-sdk/blob/4e9246843f4dc8bcde9a55781a4a4add4cd7b088/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java#L124). When AndroidChannelBuilder is notified the network is changing, it triggers idle mode:

https://github.com/grpc/grpc-java/blob/b7fb3c2e93564a78ca8484c6be32c5912839bdec/android/src/main/java/io/grpc/android/AndroidChannelBuilder.java#L327-L329

The point of that is to disconnect from wifi/mobile and re-connect on mobile/wifi. But it's easy to see how that notification could be concurrent with an RPC.

**Comment by rsgowman** [comment]
Thanks Eric!
