### ISSUE TITLE
any options to show the detail of timeout?

### ISSUE THREAD

**Issue by ronyongxian** [grpc/grpc-java#5732]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.14.0

### What did you expect to see?
solve problem

client use java, server use c, and %0.1 of totol millions of reqeusts timeout. 

error log like:  'RPC failed Status: Status{code=DEADLINE_EXCEEDED, description=deadline exceeded after 19697316ns, cause=null}  | io.grpc.StatusRuntimeException:DEADLINE_EXCEEDED: deadline exceeded after 19697316ns'. 

but found less than 1 millionseconds is cost in server side. would like to know if any optional configs to show the detail of timeout in client side, like which part cost most of the time?

or any other suggestion to solve this problem?

appreciate if any help.

**Comment by voidzcy** [comment]
`ChannelLogger` logs events for RPC steps (name resolution, load balancing, etc) on listeners (e.g., when `NameResolverListener` [receives name resolution result](https://github.com/grpc/grpc-java/blob/e6c8534f10d938566a62e38792a74032955e6c82/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L1327)). You can attach a log handler to show log records with higher time resolution. Then you can briefly gauge the amount of time it takes at each step.

**Comment by dapengzhang0** [comment]
The deadline 19697316ns is less than 20 millis, that's so small and probably within network latency or jvm warm-up.

**Comment by ronyongxian** [comment]
> `ChannelLogger` logs events for RPC steps (name resolution, load balancing, etc) on listeners (e.g., when `NameResolverListener` [receives name resolution result](https://github.com/grpc/grpc-java/blob/e6c8534f10d938566a62e38792a74032955e6c82/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L1327)). You can attach a log handler to show log records with higher time resolution. Then you can briefly gauge the amount of time it takes at each step.

how to attach a log handler? or any example? thank you

**Comment by voidzcy** [comment]
Basically via Java's logging configuration file (`logging.properties`) and format log record's timestamp with high resolution. But this only provides a brief gauge of gRPC events logged and by no means to be accurate for measuring the time it takes for each part (especially for such a fine granularity). However, this could give you detailed information for things happening on client side and you may be able to find if there is anything going wrong. In terms of your deadline exceeded failure for 19697316ns, it is likely to be network latency and you may want to try with a larger deadline.

@ejona86 
Are there any more advanced profiling for inner-RPC timing available now?

**Comment by zhangkun83** [comment]
Because your deadline is very short, your will be very sensitive to any network slowness and reconnection. It should be possible to differentiate between those two cases, by exposing the current states of the channel. Stay tuned with #4740.
