### ISSUE TITLE
how to build Any Object ?  Any any = Any.newBuilder().build(); 

### ISSUE THREAD

**Issue by billy1999** [grpc/grpc-java#5733]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
proto3

### What did you expect to see?
Any any = Any.newBuilder().build();
How to set value to any,
Is there some method like  any.put("k","v") ?

**Comment by voidzcy** [comment]
`Any` type allows users to pack and unpack arbitrary type values in a typesafe manner (with `pack()` and `unpack()` methods). There is some small examples in protobuf's [Javadoc](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Any).

This is a Protobuf usage question. I would suggest looking at protobuf [forum](http://groups.google.com/group/protobuf).
