### ISSUE TITLE
Service config does not support integers

### ISSUE THREAD

**Issue by Yopi** [grpc/grpc-java#5756]
### What version of gRPC are you using?
1.20

### What did you expect to see?
From the [A6 client retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#retry-policy-capabilities) proposal it looks fairly clear that e.g. `maxAttempts` should be an integer. It wouldn't really make sense for it to not be a whole number anyway. 

In the [ManagedChannelBuilder](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java#L381) it's just not allowed.

**Comment by voidzcy** [comment]
Service config is really a JSON object, in which numerical values are of _Number data type_. There is no strict distinction between integers and fractions in JSON (by definition, it is double-precision floating-point format in JavaScript). So it makes sense to parse numbers as `Double`. We could have used [JsonNumber](https://docs.oracle.com/javaee/7/api/javax/json/JsonNumber.html) for that. But this does not bring us benefits and using `Double` for number types does not cause anything troublesome.

**Comment by dapengzhang0** [comment]
Using java Double type for json numbers in the argument is specified in the javadoc of the API [ManagedChannelBuilder#defaultServiceConfig()](https://github.com/grpc/grpc-java/blob/v1.20.0/core/src/main/java/io/grpc/ManagedChannelBuilder.java#L562)
