### ISSUE TITLE
How to enable TLS in android client

### ISSUE THREAD

**Issue by sai3010** [grpc/grpc-java#5761]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.20
### What did you expect to see?
Android client must send the client certificate along with the request. 
Need some reference or code snippet on how to add TLS in grpc android.

**Comment by voidzcy** [comment]
You can take a look at [example-tls](https://github.com/grpc/grpc-java/tree/master/examples/example-tls) for using TLS in gRPC. For Android specific, please refer to [this guide](https://www.appfoundry.be/blog/2014/11/18/Google-Play-Services-Dynamic-Security-Provider/).

**Comment by sai3010** [comment]
I already have a certificate. I just want to add it to the android client grpc.

**Comment by voidzcy** [comment]
That should be similar to the [client code in exmaple-tls](https://github.com/grpc/grpc-java/blob/c242fc82456eb0e406348b498956a9f318e48001/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java#L44). Use your cert to build a `SslContext` for the channel. Everything else should be quite same as the example, except you would need Play Services Dynamic Security Provider for Android.

**Comment by ejona86** [comment]
For OkHttp, you need to [specify your own SSLSocketFactory in the builder](https://grpc.github.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html#sslSocketFactory-javax.net.ssl.SSLSocketFactory-). The easiest way to get a `SSLSocketFactory` is to configure `SSLContext` and then call [`sslContext.getSocketFactory()`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLContext.html#getSocketFactory--). Look online for how to create a KeyManager with your client cert to pass to SSLContext.init() (e.g., https://stackoverflow.com/a/28921026/4690866).

**Comment by ejona86** [comment]
Seems the question was answered. Closing.
