### ISSUE TITLE
OkHttpClientTransport.start should be async

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#578]
Connecting should be run in an executor. The main problem is that we currently can't create the `frameWriter` (an AsyncFrameWriter) until we have connected. The `frameReader` doesn't seem to be as big of an issue as we can just delay executing `clientFrameHandler`.

We could try to use the same SerializingExecutor that is used inside AsyncFrameWriter. We would need to lazily initialize some things used on that thread, but we would be able to guarantee that the connection is started before real writes occur and they would be automatically queued.

This would fix the true problem that is causing #577.

**Comment by madongfly** [comment]
#577 was fixed already, and this is not the real reason of it, what's the other purposes of doing this?

**Comment by ejona86** [comment]
It is required by the API, and is useful to users. All calls into our API should be async, otherwise an async application can't use it without hacks.
