### ISSUE TITLE
JCenter not up-to-date

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#5782]
Looking at https://jcenter.bintray.com/io/grpc/, I see:

Have 1.21.0:
all, api, auth, context, core, netty, netty-shaded, okhttp, protobuf-lite, protobuf-nano, protobuf, services, stub, testing, protoc-gen-grpc-java

Missing 1.21.0:
alts, android, benchmarks, bom, grpclb, interop-testing

I'm going to give it another day. If they don't show up I'll file _yet another_ issue with JCenter.

**Comment by ejona86** [comment]
I didn't include grpc-testing-proto in the list, because it was weird and I needed to look into it a bit more. I checked Maven Central and it looks normal. It is missing v1.19.0, 1.20.0, and now 1.21.0. https://jcenter.bintray.com/io/grpc/grpc-testing-proto/

**Comment by ejona86** [comment]
Now have 1.21.0: android, bom
Still missing 1.21.0: alts, benchmarks, grpclb, interop-testing
(And of course, testing-proto)

Well... that's progress. Give it another day?

**Comment by ejona86** [comment]
Now have 1.21.0: alts, grpclb
Still missing 1.21.0: benchmarks, interop-testing
(And of course, testing-proto)

Seems it's time to file an issue.

**Comment by ejona86** [comment]
Interop-testing and benchmarks now showing up. That leaves just testing-proto.

**Comment by creamsoup** [comment]
also all of v1.22.0s are still missing. i'll file a bug for them.

**Comment by creamsoup** [comment]
jcenter has libs-release-bintray (https://repo.jfrog.org/artifactory/libs-release-bintray/io/grpc/) which has all the missing stuff (seems like this is the central cache). 

so if the original jcenter (https://jcenter.bintray.com/io/grpc/) doesn't have the file. the jcenter redirects to libs-release-bintray. so even if we don't see it from jcenter ui. users can download from the jcenter. I ran a script to download all the new versions. I purposely didn't trigger missing testing-proto artifacts to see if this triggers jcenter to update the jcenter artifactory (and most importantly the ui) or not.

**Comment by ejona86** [comment]
So in further testing, it seems most files are seeing updates appropriately, but not maven-metadata.xml. Since we use versions like `[1.22.0]` for grpc-core and grpc-api, maven/gradle download the maven-metadata.xml for the version list. Since the maven-metadata.xml is old, maven/gradle don't find a compatible version. Explicitly listing grpc-core and grpc-api as dependencies can cause gradle (dunno about maven) to avoid needing to download maven-metadata.xml. Using the BOM did not change gradle's behavior.

**Comment by creamsoup** [comment]
I reported the pinned version issue to the support of jcenter. 

even though we released 2 new versions (1.22.0, 1.22.1) and explicitly requested artifacts to hint the jcenter, nothing is added. even the testing-proto is still at the 1.18.0. i'll keep an eye on it.

**Comment by creamsoup** [comment]
up to dated (up to 1.21.1):
all, api,  context, core, netty, okhttp, protobuf-lite, protobuf, services, stub, protoc-gen-grpc-java

missing 1.21.1:
alts, android, auth, benchmarks, bom ,grpclb, interop-testing, netty-shaded, protobuf-nano, testing

missing update since 1.18.0:
testing-proto

**Comment by ejona86** [comment]
This problem has continued virtually for every release. We have a pretty good understanding of which types of files fail to be updated in JCenter. There does not seem to be any real options available to resolve this. This was worked around in #7291. Closing since we aren't planning to spend additional time tracking this.

We suggest users that like JCenter should have JCenter as their first repository so it will be used most heavily, but have mavenCentral as a fallback in case JCenter is out-of-date.
