### ISSUE TITLE
How to specify IP address using ServerBuilder

### ISSUE THREAD

**Issue by zxwing** [grpc/grpc-java#5791]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.21.0

### What did you expect to see?

The ServerBuilder only provides forPort() method to bind the server on a port, however, I want to specify the IP to listen instead of 0.0.0.0.  Is there an official way to do it? I googled but nothing useful found.

**Comment by carl-mastrangelo** [comment]
You can use the NettyServerBuilder, which has methods for binding to a specific SocketAddress
