### ISSUE TITLE
Implement timeout/deadline in Server

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#58]

**Comment by ejona86** [comment]
At least at this point, we won't cancel the call on the server-side. Servers would expect clients to cancel when the deadline expires.

**Comment by ejona86** [comment]
Aaaand, now it seems we will handle the timeout on both client/server; both will set a timer to kill the RPC when the deadline expires.

The concern was that "things can go wrong" on the client-side, or with the TCP connection. It is more conservative to enforce the deadline on both client/server.

We actually don't care too much about this for grpc-java. We are just planning to copy what is done for the grpc C core. I don't see a tracking issue on that repo at the moment though.

**Comment by ejona86** [comment]
From #542:
@ejona86:
>@johnbcoughlin:
>>just out of curiosity, what is the idea behind a server-api?

> I think we don't have very many choices: 1) we can add a `getDeadline()` to `ServerCall`. 2) we could expose `TIMEOUT_KEY` and just force accessing it from `Metadata`. `ServerImpl` will need to access it from `Metadata` in order to set up timers (assuming that happens in #58) and configure Context in #262. I expect (1) may be preferred, but not much discussion has happened.

**Comment by ejona86** [comment]
@carl-mastrangelo, you likely will want to take a look at #57 because it highly relates to what needs to be done here.

**Comment by hbchai** [comment]
Any idea what this will look like in terms of the Java service interface? Is a new context object going to be introduced to provide access to the deadline?

**Comment by ejona86** [comment]
No, we've not defined how the deadline would be exposed. I figured we may just add a method to `ServerCall` like `getDeadline`. The Context API currently has its own deadlines; we would make sure to copy the deadline from the call to the Context. The Context API isn't also quite done yet.

**Comment by ejona86** [comment]
Still left to do is implement `NettyServerStream.cancel(Status)`. It should send a RST_STREAM with HTTP/2 error code CANCEL.

**Comment by johnbcoughlin** [comment]
I'll pick this one up if no one else is working on it!

**Comment by ejona86** [comment]
@johnbcoughlin, please do!

**Comment by ejona86** [comment]
Last piece added in #669. All done!
