### ISSUE TITLE
what does "excessive buffering internally" mean in io.grpc.internal.StreamListener::onReady ?

### ISSUE THREAD

**Issue by likesprite** [grpc/grpc-java#5805]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

io.grpc:grpc-core:1.3.0

### What did you expect to see?

There is a  concept of "Stream" in grpc ,but i can't understand some description on "Stream". When reading docs on io.grpc.internal.StreamListener , I saw words like "without requiring excessive buffering internally" . Is "excessive buffering" the same as memory?

**Comment by carl-mastrangelo** [comment]
Yes.    In the future, you should ask questions like this on StackOverflow, since the answer will be easier to find by others.
