### ISSUE TITLE
The Android Helloworld sample doesn't work on Android 9

### ISSUE THREAD

**Issue by anaselhajjaji** [grpc/grpc-java#5807]
### What version of gRPC are you using?
I'm using the Android Helloworld sample, gRPC version 1.21.0

### What did you expect to see?
The Hello world should work as it is for previous versions of Android, it works fine in Android 8.

The call : HelloReply reply = stub.sayHello(request);
Throws the exception : io.grpc.StatusRuntimeException: UNAVAILABLE

**Comment by carl-mastrangelo** [comment]
Any other detail about what happened?  An error message or stack trace perhaps?

**Comment by voidzcy** [comment]
I jus tried it with Android Studio's emulator on API level 28 and it worked fine for me on localhost.

**Comment by anaselhajjaji** [comment]
> I jus tried it with Android Studio's emulator on API level 28 and it worked fine for me on localhost.

I'm not testing on localhost. I have an Android device on the network. You can also try to use the IP Address of the server instead of localhost, does this work?

**Comment by anaselhajjaji** [comment]
It was an error on my side... sorry. It's working now.
