### ISSUE TITLE
Error zero_copy_stream.h file not found during ./gradlew installDists

### ISSUE THREAD

**Issue by ubuntudroid** [grpc/grpc-java#581]
When running `./gradlew installDists` I receive the following error message:

```
In file included from /Users/me/projects/grpc-java/compiler/src/java_plugin/cpp/java_generator.cpp:1:
/Users/Sven.Bendel/projects/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^
```

Am I missing something? I am just trying to get the example server up and running via run-test-server.sh.

**Comment by ubuntudroid** [comment]
Totally my fault, missed the Mac hint in the readme telling me to make the following call:

`export CXXFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"`

This did the trick. So RTFM, past self!^^

**Comment by ejona86** [comment]
Hmm... It would have been possible to use `-PskipCodegen=true` to avoid the need to build the code generator. Maybe we should add that as a hint somewhere.

With what you were doing, were you wanting to build the code generator?

**Comment by ubuntudroid** [comment]
Nope, just wanted to build the server. I think I saw that flag being
mentioned somewhere on the gradle plugin page if I'm not mistaken.

Eric Anderson <notifications@github.com> schrieb am Di., 30. Juni 2015
17:28:

**Comment by ejona86** [comment]
So did you learn of `./gradlew installDists` from `run-test-server.sh`? If so, do you think it would have been helpful for the client and server test scripts to suggest using `-PskipCodegen=true`?

**Comment by ubuntudroid** [comment]
Yes, this would definitely be helpful!

Eric Anderson <notifications@github.com> schrieb am Di., 30. Juni 2015
23:10:

**Comment by ejona86** [comment]
I just merged a change that suggests using -PskipCodegen in the test scripts.

Thanks for filing the issue!

**Comment by ubuntudroid** [comment]
Great, thank you! :)

Eric Anderson <notifications@github.com> schrieb am Mi., 1. Juli 2015 22:47:

**Comment by killjason** [comment]
I got the same problem when RUN ../gradlew java_pluginExecutable
I tried export CXXFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" , but did not work,
ENV as following:
OS: CentOS-7/Mac
protobuf: protoc-3.0.0-beta-4-linux-x86_64
grpc-java:grpc-java-0.15.0
jdk:1.8
