### ISSUE TITLE
How to start servcie with different impl class

### ISSUE THREAD

**Issue by hyz951226** [grpc/grpc-java#5814]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.18.0

### What did you expect to see?

I'm a rookie.Now,I have a DemoServer with lots of method.Those method could be classifid according to certain rules.
#### For Example
This is protobuf
``` protobuf
 server DemoServer {
   rpc methodA1 (request) returns (response){}
   rpc methodA2 (request) returns (response){}
   rpc methodB1 (request) returns (response){}
   rpc methodB2 (request) returns (response){}
 }
```
There are Servers.
``` java
 ServerA extends DemoServiceGrpc.DemoServiceImplBase {
    @Override
    methodA1 ( ) {...}
    @Override
    methodA2( ) {...}
 }
```

``` java
 ServerB extends DemoServiceGrpc.DemoServiceImplBase {
    @Override
    methodB1 ( ) {...}
    @Override
    methodB2( ) {...}
 }
```
When I addService and start,they are don't work.
``` java
   .addService( new ServerA ( ) )
   .addService( new ServerB ( ) )

```

**Comment by likesprite** [comment]
Maybe these code can help you : "   server.awaitTermination(); " .  But I'm not able to explain it. What I can associat with is the daemon attribute in  java.Lang.Thread

**Comment by likesprite** [comment]
ignore what i said upon. I just tried my idea and failed.   There is a good news that I found another way.

just provide two " server impl"  in one "server service definition".

for example , you can override serverA::bindService by  modifying  
` addMethod( methodb1 ***  this **)  .addMethod(methodb2 ** this**` to
`  ServerB serverBImpl = ** ; addMethod(methodb1 *  serverBImpl)  .addMethod(methodb2 *** serverBImpl **) `


add just  invoke io.grpc.Server:: addService(new ServiceA() )   "   ServiceA is the service which you override  the method bindService  "

it works

**Comment by carl-mastrangelo** [comment]
Is this resolved?   I'm having a little trouble understanding what you are saying.

**Comment by hyz951226** [comment]
> ignore what i said upon. I just tried my idea and failed. There is a good news that I found another way.
> 
> just provide two " server impl" in one "server service definition".
> 
> for example , you can override serverA::bindService by modifying
> ` addMethod( methodb1 *** this **) .addMethod(methodb2 ** this**` to
> ` ServerB serverBImpl = ** ; addMethod(methodb1 * serverBImpl) .addMethod(methodb2 *** serverBImpl **)`
> 
> add just invoke io.grpc.Server:: addService(new ServiceA() ) " ServiceA is the service which you override the method bindService "
> 
> it works

Sorry,I am confused about what's addMethod mean.It's mean I have to new a class in another instance?I‘m not good at English.Hope you'll understanding.

**Comment by likesprite** [comment]
I think you are good at Chinese because I saw much Chinese words in your personal page.

如果要从技术上解决你的问题：
1、你可以重写implBase的addMethod方法，但是这部分的代码是proto自动编译生成的，改动很大。
（addMethod方法返回的serviceDefinition才是最终注册到grpc服务上的接口，addMethod方法默认会注册pb文件中定义的全部接口，所以才会有 unimplement 异常，说接口方法未实现）
2、你可以使用代理。在ServerA中持有一个ServerB的对象，重写methodB1、methodB2直接 代理到serverB的方法中。

更好的办法是从业务的角度去拆分接口。
3、最好的方法是修改你的pb文件，想下面这样：
` server DemoServerA {
   rpc methodA1 (request) returns (response){}
   rpc methodA2 (request) returns (response){}
 }
 server DemoServerB {
   rpc methodB1 (request) returns (response){}
   rpc methodB2 (request) returns (response){}
 }`

**Comment by ran-su** [comment]
Is this resolved?
@hyz951226 for your initial question, as @likesprite suggested, ServerServiceDefinition may be the thing you are looking for.
For the addMethod() related question, here may not be the best place to ask. I believe there are places with users native to your language can be more helpful to you. We recognize there are a lot of gRPC users that not fluent in English and we are trying to figure out a way(eg. improve docs quality in other languages, etc) to better help them.

**Comment by hyz951226** [comment]
Thanks a lot.
