### ISSUE TITLE
Gradle plugin outputs different filenames on different linux distributions

### ISSUE THREAD

**Issue by pupper68k** [grpc/grpc-java#5819]
### What version of gRPC are you using?
1.20.0

### What did you expect to see
Project in question is here: https://gitlab.com/whom/jobserv

Project builds correctly on Arch and Debian.
Outputs build/distributions/JobServ.tar on Arch Linux and build/distributions/jobserv.tar on Debian.
(Notice the change from CamelCase to all lowercase)
This is not the end of the world, but an annoyance for anyone who needs to handle that tar as part of their build process.

**Comment by carl-mastrangelo** [comment]
Which gradle plugin?

**Comment by pupper68k** [comment]
I am using com.google.protobuf however it occurs to me that this issue is a lot more relevant to the Gradle application plugin. If so, sorry for the superfluous issue.

**Comment by voidzcy** [comment]
That's part of `distTar` task in the Distribution plugin (which is implicitly applied by the Application plugin). By default the tar is created at `$buildDir/distributions/${project.name}-${project.version}.«ext»`, where your `project.name` is `jobserv`. I would try creating a `settings.gradle` file in your project directory and add `
rootProject.name = 'jobserv'` in it to avoid your issue on Arch Linux.

**Comment by ejona86** [comment]
Seems like a gradle issue. Closing.
