### ISSUE TITLE
Update protobuf dependency to v3.8.0

### ISSUE THREAD

**Issue by andreamlin** [grpc/grpc-java#5828]
Please answer these questions before submitting your issue.
The [google-cloud-java](https://github.com/GoogleCloudPlatform/google-cloud-java) generated clients are generated with a tool that uses protobuf v3.8.0, which contains bug fixes. Clients compiled with protoc v3.8.0 have changes that are not backwards-compatible with protobuf v3.7.1, namely the `UnusedPrivateParameter`. 

It will be a similar story with other users who are pinned to the lastest protobuf version.

### What version of gRPC are you using?
v1.21.0

### What did you expect to see?
Dependency on protobuf v3.8.0.

**Comment by ejona86** [comment]
google-cloud-java should simply depend on protobuf 3.8.0. Why is anything else necessary?

Since google-cloud-java is how clients pull in gRPC, things should "just work." But even if there's another dependency to protobuf in the dep tree, Maven google-cloud-java users should already be using `requireUpperBoundDeps`, which would catch any version downgrading by Maven.

**Comment by carl-mastrangelo** [comment]
FYI, both the lite and non-lite 3.8.0 artifacts were released.  I think we should upgrade if possible, even if @andreamlin can solve this issue independently.

**Comment by andreamlin** [comment]
cc +@sduskis

**Comment by ST-DDT** [comment]
[Protobuf v3.9.1](https://github.com/protocolbuffers/protobuf/releases/tag/v3.9.1) has been released. Maybe we could directly update to the latest version.

**Comment by carl-mastrangelo** [comment]
@ST-DDT I just updated to 3.9.0, but you are welcome to bump it again.  You can probably even copy my PR #6007

**Comment by ST-DDT** [comment]
3.9.1 doesn't contain any improvements for java (at least if you trust the changelog), so there is probably no need to. I should have checked the current version before commenting here,
