### ISSUE TITLE
Is there any possibility to add custom NameResolver.Listener to Channel?

### ISSUE THREAD

**Issue by st0rmr1der1994** [grpc/grpc-java#5831]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.20.0

### What did you expect to see?
I am trying to implement some offline-first functionality. And when device re-establishing network connection it takes some time for `NameResolver` to resolve a host for my previously built `ManagedChannel`. 
Thus, I need to know when I'll be able to send gRPC calls without following failure:
`io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host %name%` 

I expect to see a possibility to add extra listener for `NameResolver` and postpone my calls to the point of time when `NameResolver.Listener#onAddresses` will be called.

 Is there any in v1.20.0 or in the most recent?

**Comment by carl-mastrangelo** [comment]
You can use ManagedChannel#notifyWhenStateChanged   with a runnable to indicate when the channel has an ready transport.

**Comment by ejona86** [comment]
You can also use [`stub.withWaitForReady()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withWaitForReady--) to have the RPCs not be sent until the channel is ready. This is similar to using notifyWhenStateChanged.

It sounds like your code is notified when the network comes online. You can notify gRPC via [`ManagedChannel.resetConnectBackoff`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannel.html#resetConnectBackoff--) which can trigger the channel to reconnect more promptly.

**Comment by zhangkun83** [comment]
Seems the question has been answered. Closing it.
