### ISSUE TITLE
[Bazel] java_rpc_toolchain does not respect Java toolchain flags 

### ISSUE THREAD

**Issue by pshabunia0epam** [grpc/grpc-java#5841]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.21

### What did you expect to see?

I build gRPC code with Bazel using Remote Build Execution (RBE) and I have to use a custom jdk8 toolchain [[.bazelrc snippet](https://gist.github.com/pshabunia0epam/0901b3267518ad7b6d99c1a73c5ebe69)]. Java toolchain flags don't seem propagated to the `java_rpc_toolchain` rule as it declares a [fixed dependency](https://github.com/grpc/grpc-java/blob/745aa0a2f570d74e7d7fe0c72334c24e21b8ab17/java_grpc_library.bzl#L46) on the default Java toolchain, which is jdk10 for Bazel v0.25.0. I believe this is the primary reason contributing to the following error returned by Bazel:

```
Unrecognized VM option 'CompactStrings'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Please let me know if I can do anything else to enforce a custom Java toolchain for Bazel gRPC rules.

**Comment by ejona86** [comment]
Seems this is related to b/134447584 (probably the same report to RBE). My current thinking is java_grpc_library should use `@bazel_tools//tools/jdk:current_java_toolchain`. When I exported java_grpc_library for Bazel that target didn't exist, so I just used `:toolchain`. I'll want to figure out the easiest way to test it.

**Comment by ejona86** [comment]
I've received confirmation my understanding is correct.

**Comment by pshabunia0epam** [comment]
b/124447584 indeed.
Thanks for taking care of this!

**Comment by ejona86** [comment]
It actually appears this was a regression introduced by #5618 in v1.21.

**Comment by pshabunia0epam** [comment]
Hi again,

I cannot see this issue in the scope of the upcoming 1.22 milestone
https://github.com/grpc/grpc-java/milestone/35?closed=1

It is scheduled for "Next" milestone, but I'm not sure when it will be available. Can you please shed some light on it?

**Comment by ejona86** [comment]
Nothing should remain closed in the Next milestone. That's a signal it needed to be updated. It made it in before the 1.22 branch cut (but it was a bug fix, so it could have still be backported if it hadn't). There was also a backport to 1.21 in #5891.
