### ISSUE TITLE
How to determine whether a server is ok?

### ISSUE THREAD

**Issue by User979269852** [grpc/grpc-java#5854]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.19.0

### What did you expect to see?
I used the pick_first load balance when I create a etcd client with 3 entrypoints, when docker paused the etcd container which one was used by etcd client,grpc cannot detect the situation and change connection to the good one, I wander how do grpc determine whether the server is ok?which part is about this?I am a new bird and is hard for me to find out the related part.Thank you very much

**Comment by dapengzhang0** [comment]
If the backend the client is currently connecting to fails explicitly, then the client will pick an available new backend for the next RPC. But if the backend the client is currently connecting to is just not responding, then the client may not know it's not working and will not change to a new backend. To solve this issue, you might want to use keep-alive. See APIs in https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html
