### ISSUE TITLE
response.toString() returning empty String for a default responses

### ISSUE THREAD

**Issue by ptrckdev** [grpc/grpc-java#5869]
Please answer these questions before submitting your issue.

#### What version of gRPC are you using?
1.21.0

#### What did you expect to see?
`alive: false` in my console
Instead I am getting a empty String when printing my response Object which only contains default values.

#### What did you try to do?

I am currently just playing around with gRPC to prepare myself for production use and found some strange behavior when trying to print my response objects.

I had this issue with a more complex message but it also happens with a minimal case.

Basically if you have a

`message PingResponse {`
`    bool alive = 1;`
`}`

and return it to the client with `alive = false` and try to print the response you just get a empty string. If you set `alive = true` it correctly writes down the value of the field in your console as:  `alive: true`

Note: Directly accessing the field still works. `response.getAlive()` returns `false`, so there is nothing wrong with the message itself, but with the toString() method.

This behavior does not only happen with boolean values but also if you return the first value of a enum, so I would assume with every default value?

Is it expected behavior to return an empty string for a default message or is this a bug?

**Comment by ptrckdev** [comment]
Okay so I did some digging and I think the issue it in the `getAllFields()` method of `GeneratedMessageV3.java` as it just returns an empty map for my `PingResponse` which the `toString()` method eventually ends up calling to print out the field values.

This now seems more like a real issue and not only a negligible printing issue, does it?

Because there we are implementing the `getAllFields()` method from the `MessageOrBuilder.java` interface which in the java doc comments states "Returns a collection of all the fields in this message which are set and their corresponding values. [...]".

This issue also occurs when I'm not only "just" sending back the response with un-set values on my server but actively calling `setAlive(false)` on the builder.

Now, if I am not completely on the wrong track here, if it is an issue, it's one of protobuf and not gRPC, correct?

Would appreciate your help anyways so clear my confusion 🤔

**Comment by dapengzhang0** [comment]
Yes, this is really protobuf's issue/feature. See https://cheind.wordpress.com/2011/12/22/protocol-buffers-display-non-present-fields-with-textformat/
