### ISSUE TITLE
Add dependency on grpc-core to the main README.md

### ISSUE THREAD

**Issue by baltiyskiy** [grpc/grpc-java#5881]
The "Download" section starts with a Maven pom file excerpt containing some dependencies. Note that grpc-netty-shaded doesn't include some classes that are available in grpc-core, for example, `io.grpc.internal.AbstractServerImplBuilder`. I suggest to add dependency on grpc-core to avoid confusion. 
(I've spent quite some time trying to figure out why example-tls builds with Maven but my project doesn't... Turned out the difference is that my project uses netty-shaded.)

**Comment by ejona86** [comment]
grpc-netty-shaded [depends on grpc-core](https://search.maven.org/remotecontent?filepath=io/grpc/grpc-netty-shaded/1.21.0/grpc-netty-shaded-1.21.0.pom). I don't know why Maven would have trouble finding AbstractServerImplBuilder.

The main set of examples `examples/` does depend on grpc-netty-shaded. Was your problem during compilation or during execution?

**Comment by baltiyskiy** [comment]
During compilation.
Here's how you can reproduce the problem:
- Take `example-tls` with Maven (it depends on `grpc-netty`, not `grpc-netty-shaded`).
- Change `pom.xml` to depend on `grpc-netty-shaded`.
- Fix the packages to point to shaded packages ( `s/import io.grpc.netty/import io.grpc.netty.shaded.io.grpc.netty`/`, `s/import io.netty/import io.grpc.netty.shaded.io.netty/`).
- Compile.

Observe:
```
[ERROR] X:\src\grpc-java\examples\example-tls\src\main\java\io\grpc\examples\helloworldtls\HelloWorldServerTls.java:[69,35] error: cannot access AbstractServerImplBuilder
[ERROR]   class file for io.grpc.internal.AbstractServerImplBuilder not found
X:\src\grpc-java\examples\example-tls\src\main\java\io\grpc\examples\helloworldtls\HelloWorldClientTls.java:[63,32] error: cannot access AbstractManagedChannelImplBuilder
```

**Comment by ejona86** [comment]
I couldn't reproduce, with Maven 3.6.1 nor 3.5.2.

I checked out v1.20.0. I made these changes:
```diff
diff --git a/examples/example-tls/pom.xml b/examples/example-tls/pom.xml
index 58a1d128e..bc546840d 100644
--- a/examples/example-tls/pom.xml
+++ b/examples/example-tls/pom.xml
@@ -49,7 +49,7 @@
     </dependency>
     <dependency>
       <groupId>io.grpc</groupId>
-      <artifactId>grpc-netty</artifactId>
+      <artifactId>grpc-netty-shaded</artifactId>
     </dependency>
     <dependency>
       <groupId>io.netty</groupId>
diff --git a/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java b/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java
index c4c87c7d9..3c8bda069 100644
--- a/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java
+++ b/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java
@@ -21,11 +21,11 @@ import io.grpc.StatusRuntimeException;
 import io.grpc.examples.helloworld.GreeterGrpc;
 import io.grpc.examples.helloworld.HelloReply;
 import io.grpc.examples.helloworld.HelloRequest;
-import io.grpc.netty.GrpcSslContexts;
-import io.grpc.netty.NegotiationType;
-import io.grpc.netty.NettyChannelBuilder;
-import io.netty.handler.ssl.SslContext;
-import io.netty.handler.ssl.SslContextBuilder;
+import io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts;
+import io.grpc.netty.shaded.io.grpc.netty.NegotiationType;
+import io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder;
+import io.grpc.netty.shaded.io.netty.handler.ssl.SslContext;
+import io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder;
 
 import javax.net.ssl.SSLException;
 import java.io.File;
diff --git a/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldServerTls.java b/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldServerTls.java
index 58e1ed0d6..b7f6a5c49 100644
--- a/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldServerTls.java
+++ b/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldServerTls.java
@@ -20,12 +20,12 @@ import io.grpc.Server;
 import io.grpc.examples.helloworld.GreeterGrpc;
 import io.grpc.examples.helloworld.HelloReply;
 import io.grpc.examples.helloworld.HelloRequest;
-import io.grpc.netty.GrpcSslContexts;
-import io.grpc.netty.NettyServerBuilder;
+import io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts;
+import io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder;
 import io.grpc.stub.StreamObserver;
-import io.netty.handler.ssl.ClientAuth;
-import io.netty.handler.ssl.SslContextBuilder;
-import io.netty.handler.ssl.SslProvider;
+import io.grpc.netty.shaded.io.netty.handler.ssl.ClientAuth;
+import io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder;
+import io.grpc.netty.shaded.io.netty.handler.ssl.SslProvider;
 
 import java.io.File;
 import java.io.IOException;
```

```
$ mvn clean compile
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.19
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 19
[INFO] os.detected.release: debian
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
[INFO] 
[INFO] ------------------------< io.grpc:example-tls >-------------------------
[INFO] Building example-tls 1.20.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ example-tls ---
[INFO] Deleting /usr/local/google/home/ejona/clients/grpc-java/examples/example-tls/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ example-tls ---
[INFO] 
[INFO] --- protobuf-maven-plugin:0.5.1:compile (default) @ example-tls ---
[INFO] Compiling 1 proto file(s) to /usr/local/google/home/ejona/clients/grpc-java/examples/example-tls/target/generated-sources/protobuf/java
[INFO] 
[INFO] --- protobuf-maven-plugin:0.5.1:compile-custom (default) @ example-tls ---
[INFO] Compiling 1 proto file(s) to /usr/local/google/home/ejona/clients/grpc-java/examples/example-tls/target/generated-sources/protobuf/grpc-java
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example-tls ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /usr/local/google/home/ejona/clients/grpc-java/examples/example-tls/src/main/resources
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ example-tls ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /usr/local/google/home/ejona/clients/grpc-java/examples/example-tls/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.593 s
[INFO] Finished at: 2019-06-18T17:14:53-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by baltiyskiy** [comment]
I was using v1.21.0.

**Comment by baltiyskiy** [comment]
I can make an example project for you if that helps.

**Comment by ejona86** [comment]
> I was using v1.21.0.

Doh. I even knew it had to be v1.21.0 because we thought we knew how this might happen once we read the reproduction case.

So the problem is that grpc-netty-shaded has a runtime (not compile) dependency on grpc-core. Before 1.21, grpc-stub, grpc-proto, and many other artifacts had a compile dependency on grpc-core. In v1.21 that was swapped to a compile dependency on (the brand-new) grpc-api.

Technically, none of this is a problem/bug, because grpc-netty-shaded wasn't intended to be used via any API of its own and I don't want to encourage people referencing its shaded classes. In our own examples grpc-netty-shaded is a runtime dependency and not directly referenced from the code.

But I do understand some users are referencing the classes anyway and the error isn't a clear signal of anything.

**Comment by baltiyskiy** [comment]
Thanks for looking into this and for the quick resolution!

I'd like to clarify a few things:

> grpc-netty-shaded wasn't intended to be used via any API of its own and I don't want to encourage people referencing its shaded classes. 

So I read this as "I'm not expected to reference shaded classes". In my application, I must use TLS and grpc-netty-shaded. It follows that I need to reference `NettyChannelBuilder`, and it's only available in the shaded package. If this is not the expected way, then what's the expected one?

**Comment by ejona86** [comment]
@baltiyskiy, basic usages of TLS can use the io.grpc API. Clients use TLS by default and servers can call useTransportSecurity(File/InputStream, File/InputStream). If you need mTLS or to tweak the TLS settings, then my expectation was that you'd need `grpc-netty`. `grpc-netty-shaded` was intended for users that didn't need to know they were using Netty, and were just using the io.grpc APIs.

**Comment by baltiyskiy** [comment]
Well, `example-tls` already uses more than `io.grpc` APIs ;) We're in the same situation.
As for `grpc-netty-shaded` --- we need to use it because we're already using Akka which uses netty at another version under the hood. 
My concern is that you might be looking at the usage of stuff like `NettyChannelBuilder` with `grpc-netty-shaded` as "unexpected" or "unsupported". I hope to use this as the opportunity to communicate that there are valid use cases where you need it :)

**Comment by ejona86** [comment]
> Well, example-tls already uses more than io.grpc APIs

And that's okay. It is using the non-shaded version.

> As for grpc-netty-shaded --- we need to use it because we're already using Akka which uses netty at another version under the hood.

In which case ideally you'd shade grpc-netty or akka yourself. I know it's a PITA to do that, so I can understand being lazy and not doing so. It can also be hard if needing to use both in the same part of the application.

But actually... Akka seems to use Netty 3. That was in the `org.jboss.netty` package unlike `io.netty` used in Netty 4. I guess the only problem is they have the same artifact name in Maven Central, so package managers will only pull in one. That's unfortunate.

> My concern is that you might be looking at the usage of stuff like NettyChannelBuilder with grpc-netty-shaded as "unexpected" or "unsupported".

I do consider it unsupported, but not really unexpected. But it's also not something I'm actively trying to break. Since the Netty APIs are unstable _anyway_, I'm not sure it makes a difference in practice. There will be very few problems that break users using the shaded APIs directly that _don't_ break "normal" grpc-netty-shaded users. You just so happened to find one of them :-).

**Comment by baltiyskiy** [comment]
Thanks for the answer, Eric.
