### ISSUE TITLE
Inconsistent error code conversion with gRPC cpp

### ISSUE THREAD

**Issue by legendtang** [grpc/grpc-java#5916]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.21.0

### What did you expect to see?
The HTTP to gRPC status code conversion is not consistent between Java & C++ implementations.
https://github.com/grpc/grpc/blob/master/src/core/lib/transport/status_conversion.cc#L82
https://github.com/grpc/grpc-java/blame/master/core/src/main/java/io/grpc/internal/GrpcUtil.java#L305

As https://github.com/envoyproxy/envoy/issues/4735#issuecomment-432056484 mentioned, gRPC C Core maps 429 to RESOURCE_EXHAUSTED but Java maps 429 to UNAVAILABLE.

**Comment by dapengzhang0** [comment]
Java is following the doc https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md in the gRPC C core's repo. Did you file an issue to gRPC C core

**Comment by legendtang** [comment]
> Java is following the doc https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md in the gRPC C core's repo. Did you file an issue to gRPC C core

I think that link is not indexed from 2 years ago. I found another newer link https://github.com/grpc/grpc/blob/master/doc/statuscodes.md and it seems gRPC C core follows this document in the latest implementation.

I do submit another issue https://github.com/grpc/grpc/issues/19094 to gRPC C core about this document.

**Comment by ejona86** [comment]
The http-grpc-status-mapping is the correct document. The statuscodes doc is the wrong reference. I've started a conversation to fix them.
