### ISSUE TITLE
benchmark/ has two README.md's

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#594]
The readme at "benchmarks/src/jmh/java/io/grpc/benchmarks/netty/README.md" is in the java source directory, which seems a poor place for a readme. It should be integrated into the README.md at "benchmarks/README.md"

**Comment by carl-mastrangelo** [comment]
This isn't really a blocker for 1.1.  Moving to unscheduled.

**Comment by RiyaTyagi** [comment]
@ejona86 
I have integrated the two README.md and created a pull request. Can you please review my request? Let me know if any changes are required.

**Comment by ejona86** [comment]
This was fixed by #5931.
