### ISSUE TITLE
//compiler:grpc_java_plugin no longer visible

### ISSUE THREAD

**Issue by aaliddell** [grpc/grpc-java#5942]
### What version of gRPC are you using?
v1.21.0

### What did you expect to see?
Prior to 745aa0a2f570d74e7d7fe0c72334c24e21b8ab17, the `//compiler:grpc_java_plugin` target was publicly visible for use by external bazel workspaces. This allowed use of the protoc plugin in Bazel workspaces that use grpc-java as a dependency, in particular the rules_proto rules. Since this commit, it it no longer possible.

Is there a particular motivation for marking it as non-public?

**Comment by ejona86** [comment]
Why do you need `//compiler:grpc_java_plugin`? Users should generally be using `java_grpc_library` which uses the public `//compiler:java_grpc_library_toolchain`.

**Comment by aaliddell** [comment]
For the cross-language [rules_proto](https://github.com/stackb/rules_proto), which relies on the relevant upstreams exposing their plugins for the compilation aspect to invoke protoc with. Presently this is stuck with an outdated version of grpc-java, as moving past this commit hides the plugin required. The standard `grpc/grpc` plugins are exposed publicly as so: https://github.com/grpc/grpc/blob/df998f70239ec80af7d9af7133f9c0757e952f39/BUILD#L471-L511

These rules provide an alternative implementation of `java_grpc_library`, along with a bunch of other languages that don't presently have their own implementation. As such, using the toolchain isn't really feasible without special-casing the aspect implementation and declaration for the Java gRPC rules only.

**Comment by ejona86** [comment]
I see, rules_proto. Okay, I'll re-expose the compiler.

`grpc/grpc` is using `default_visibility = ["//visibility:public"]`. That's not something to copy.

**Comment by aaliddell** [comment]
Ok, thanks for understanding!

**Comment by ejona86** [comment]
@aaliddell, do you need a patch release with this fix, or are you happy pointing to a commit in a release branch?

**Comment by aaliddell** [comment]
I can point to a commit for now and will grab the next release when there’s something more substantial changed that requires a version bump. Thanks
