### ISSUE TITLE
How to set up header in grpclb?

### ISSUE THREAD

**Issue by lmhaoye** [grpc/grpc-java#5963]
### What version of gRPC are you using?
1.21.0

### What did you expect to see?
Use instructions for setting up custom headers in grpclb
I want to send grpclb server with custom header information, such as metadata containing x-server-name: ABC

Thank you for your help.

**Comment by zhangkun83** [comment]
grpclb has well-defined client-side behavior, and it sounds like you want to change that. Why do you want grpclb to send extra headers?

**Comment by lmhaoye** [comment]
@zhangkun83 Thank you for your reply；
Because our LB service (Go) needs to verify the customized header information, our Java service needs to meet the requirements. Is there any way to customize the metadata information of LB request?

**Comment by lmhaoye** [comment]
> grpclb has well-defined client-side behavior, and it sounds like you want to change that. Why do you want grpclb to send extra headers?

for example
Go can set metadata: [https://github.com/grpc/grpc-go/blob/3910b873d3/resolver/resolver.go#L91](https://github.com/grpc/grpc-go/blob/3910b873d3/resolver/resolver.go#L91)
```
        // Metadata is the information associated with Addr, which may be used
	// to make load balancing decision.
	Metadata interface{}
```

**Comment by ejona86** [comment]
@dfawley, how is gRPCLB seeing custom metadata in Go?

**Comment by dfawley** [comment]
The field referenced allows the resolver to attach arbitrary data to addresses to be seen by the balancer.  If it is a metadata.MD, that metadata is added to all RPCs sent to that address.  (This feature is how our grpclb balancer adds the "lb-token" metadata header to backend RPCs).

@lmhaoye in Go clients, do you have a custom name resolver adding this metadata to your LB addresses?

**Comment by lmhaoye** [comment]
@dfawley Yes, our go client has a custom name resolver

**Comment by zhangkun83** [comment]
@lmhaoye, grpclb never intended to allow NameResolver to pass arbitrary metadata to be sent to the balancer. It is accidental that gRPC Go does allow this. Strictly speaking, with this additional metadata, the policy is no longer "grpclb", but your own custom policy. In Java, you could wrap grpclb and some other core APIs to achieve what you want:

```java
@EquivalentAddressGroup.Attr
static final Attributes.Key<Metadata> ADDITIONAL_METADATA = Attributes.Key.create("additional_metadata");
...

class MetadataAttachingClientCall extends ForwardingClientCall {
  private final ClientCall delegate;
  private final Metadata additionalMetadata;

  @Override protected ClientCall delegate() {
    return delegate;
  }

  @Override public void start(Listener<RespT> responseListener, Metadata headers) {
    headers.merge(additionalMetadata);
    delegate().start(responseListener, headers);
  }
}
...

class MetadataAttachingChannel extends ManagedChannel {
  private final ManagedChannel delegate;
  private final Metadata additionalMetadata;

  @Override public ClientCall newCall(MethodDescriptor method, CallOptions callOptions) {
    return new MetadataAttachingClientCall(delegate.newCall(method, callOptions), additionalMetadata);
  }

  // Delegate all other methods
}
...

class CustomGrpclbLoadBalancerProvider extends LoadBalancerProvider {
  @Override public String getPolicyName() {
    return "custom_grpclb";
  }

  @Override public LoadBalancer newLoadBalancer(final Helper helper) {
    Helper customHelper = new ForwardingLoadBalancerHelper() {
        @Override protected Helper delegate() {
          return helper;
        }

        @Override public ManagedChannel createOobChannel(EquivalentAddressGroup eag, String authority) {
          Metadata additionalMetadata = eag.getAttributes().get(ADDITIONAL_METADATA);
          return new MetadataAttachingChannel(deleget().createOobChannel(eag, authority), additionalMetadata);
        }
    }
    LoadBalancerProvider grpclbProvider = LoadBalancerRegistry.getDefaultRegistry().getProvider("grpclb");
    return grpclbProvider.newLoadBalancer(customHelper);
  }
}

```

**Comment by lmhaoye** [comment]
@zhangkun83 ok, thanks a lot
