### ISSUE TITLE
Using GrpcCleanupRule leads to java.lang.NoSuchMethodError (thrown by  io.grpc.NameResolver$Factory.newNameResolver() ) when class extending ...ImplBase takes an Interface constructor parameter

### ISSUE THREAD

**Issue by mancini0** [grpc/grpc-java#6000]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.22.1

### What did you expect to see?
I did not expect my unit tests to throw
java.lang.NoSuchMethodError from inside io.grpc.NameResolver$Factory.newNameResolver(...)

Here is a repo with instructions on how to reproduce the issue:
https://github.com/mancini0/bazel-grpc-playground

**Comment by mancini0** [comment]
This also seems to affect GrpcServerRule

**Comment by carl-mastrangelo** [comment]
Hi,

The breakage is because of https://github.com/stackb/rules_proto/blob/master/deps.bzl#L327


They are using an old version of gRPC.  They will need to update, or you can use gRPC's provided rules.

**Comment by carl-mastrangelo** [comment]
As a followup that would have made this easier to diagnose, I have filed an issue here:

https://groups.google.com/forum/#!topic/bazel-discuss/BqUKQSfYbPs

**Comment by mancini0** [comment]
Thank you, this works fine with the grpc provided rules.
