### ISSUE TITLE
Unable to upgrade to protobuf 3.9.0

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#6008]
https://github.com/grpc/grpc-java/pull/6007/

In this PR, I am trying to upgrade to the latest Protobuf.  However, Bazel cannot build gRPC due to a dependency apparently missing from Proto:

```
INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at ~/.cache/bazel/_bazel15825dc7be7dc6b301110c34402201fa/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /DEFAULT.WORKSPACE.SUFFIX:199:1
ERROR: ~/.cache/bazel/_bazel/15825dc7be7dc6b301110c34402201fa/external/com_google_protobuf/BUILD:150:1: no such package '@zlib//': The repository '@zlib' could not be resolved and referenced by '@com_google_protobuf//:protobuf'
ERROR: Analysis of target '//compiler:grpc_java_plugin' failed; build aborted: no such package '@zlib//': The repository '@zlib' could not be resolved
INFO: Elapsed time: 0.202s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 16 targets configured)

```

It appears the root cause of this is https://github.com/protocolbuffers/protobuf/commit/f313b9ccf7434e04d233ad2f519affc78a9e26a8  which attempts to avoid using `bind()`.   The alternative, `if not native.existing_rule("zlib")`, has documentation that warns:  

> Note: If possible, avoid using this function. It makes BUILD files brittle and order-dependent.

I believe there is some ordering mismatch between when the zlib rule is defined and used.   Attempting to move the `bind()` call up in the gRPC repositories.bzl file causes other failures, so it isn't clear what needs to change to fix this.

cc @ejona86 @acozzette

**Comment by ejona86** [comment]
Ah, this usage of `native.existing_rule`. I have seen this before. It's pretty common and seems to be generally preferred to the use-an-arg-to-disable-it that we are using now in repositories.bzl. I'll note that it is common in WORKSPACE files (and things they include), not in BUILD files.

All that needs to be done is for us to update our repositories.bzl to rename zlib (since I think we only named it net_zlib because of protobuf) or to use their protobuf_deps() (and remove our zlib reference).

**Comment by carl-mastrangelo** [comment]
> protobuf_deps()

Unclear how to use this, since we conditionally load their repo.    I can't call `load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")`  in repositories.bzl.   Adding it to the end of the WORKSPACE file does work, but then we unconditionally load it.

**Comment by acozzette** [comment]
Actually what's wrong with calling protobuf_deps() in your WORKSPACE file? Doesn't the WORKSPACE file already load protobuf and zlib unconditionally, since it calls `grpc_java_repositories()` without overriding any of the default parameters?

**Comment by carl-mastrangelo** [comment]
@acozzette yup that works.  I think you should update `guava`, `gson`, and `error_prone_annotations` in your protobuf file to match zlib, but that can be done separately.

**Comment by carl-mastrangelo** [comment]
Fixed in https://github.com/grpc/grpc-java/pull/6007
