### ISSUE TITLE
Differences between setting Metadata to Channel and using CallCredentials in stub

### ISSUE THREAD

**Issue by miguelpark** [grpc/grpc-java#6010]
on the title
*channel -> stub

-----‐------

I wonder what differences are between them.
It looks working in same way, is there any expected benefit using stub.withCallCredentials instead of setting Metadata to stub?

**Comment by carl-mastrangelo** [comment]
Metadata doesn't have any conditional logic, where as CallCredentials can get a token at the time needed.  Also, CallCredentials has access to the Transport's Attributes, to allow it to check if the channel is secure before sending.
