### ISSUE TITLE
StatusRuntimeException: INTERNAL: Panic! This is a bug!

### ISSUE THREAD

**Issue by lburgazzoli** [grpc/grpc-java#6020]
When running this [test](https://github.com/etcd-io/jetcd/blob/master/jetcd-osgi/jetcd-karaf/src/test/java/io/etcd/jetcd/osgi/ClientServiceChecks.java) against grpc 1.22.1, an exception because of an internal bug is raised

### What version of gRPC are you using?
1.22.1

### What did you expect to see?

```
Caused by: java.util.concurrent.ExecutionException: io.etcd.jetcd.shaded.io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.etcd.jetcd.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531)
	at io.etcd.jetcd.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:492)
	at io.etcd.jetcd.Util.lambda$toCompletableFutureWithRetry$2(Util.java:141)
	... 3 more
```

**Comment by creamsoup** [comment]
@lburgazzoli i downgraded the version 1.20.0, but the error still exists. 

I ran the test, I found error message below. it usually means `META-INF` is missing when shading grpc jar. you may want to change shading configuration in the parent `pom.xml`.

```
Caused by: java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
```

**Comment by lburgazzoli** [comment]
`META-INF/services/io.grpc.LoadBalancerProvider` is part of the shaded jar but if grpc-java leverage ServiceLoader to discover implementation, then it won't work on OSGi.

Is there a way to programmatically register load balancers ?

**Comment by lburgazzoli** [comment]
Ok, just found a workaround but it is practically not possible to register an instance of the round robin load balancer as all the related classes are package private, is there any reason for that ?

**Comment by creamsoup** [comment]
@lburgazzoli  i am not sure what workaround you are talking about. the fix should be look like this in the `jetcd-all/pom.xml`
add following to shade plugin configuration

```xml
<transformers>
  <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
</transformers>
```

also parent `pom.xml` add same thing

```xml
<executions>
    <execution>
        <goals>
            <goal>shade</goal>
        </goals>
        <configuration>
            <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
            </transformers>
        </configuration>
    </execution>
</executions>
```

this will copy missing `META-INF/`, see [maven plugin page](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html) for more details.

**Comment by creamsoup** [comment]
FYI. since I already have a fix. I created a [PR](https://github.com/etcd-io/jetcd/pull/610).

**Comment by creamsoup** [comment]
the PR is merged. closing the issue.
