### ISSUE TITLE
Using netty-tcnative with openssl-fips.  How can I verify that grpc is running with fips enabled?

### ISSUE THREAD

**Issue by Andrew-Lev** [grpc/grpc-java#6035]
I am running grpc-netty-1.18 with netty-tcnative 2.0.20 on CentOS Linux release 7.6.1810.  This is all in a docker.  I need to verify that its running in FIPS mode.  

I've gone and built the dynamic netty-tcnative with OpenSSL 1.0.2-fips, and I do see it reporting  that it using the expected version in the logs. 
> DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative using native library: OpenSSL 1.0.2k-fips

For reference these are the jars being used:
grpc-netty-1.18.0.jar
netty-tcnative-2.0.20.Final-linux-x86_64.jar

I see APR logs stating that fips mode was successfully entered.
> [WrapperSimpleAppMain] INFO  org.apache.catalina.core.AprLifecycleListener - Successfully entered FIPS mode

Everything seems to work as intended and I dont see any errors, but I also dont see any way to get info on whether grpc is running with FIPS mode

On load I see log output about a bunch of cipher suite mappings, default cipher suites, and supported protocols.  I know some of the loaded cipher suites are not fips compliant, but Im not sure if that log output would be different with fips enabled or not.

I've tried passing  io.netty.internal.tcnative.SSL.fipsModeSet(1) but I dont see any difference in the log output.

Is there some conclusive way determine whether grpc is running in a fips compliant mode?

**Comment by carl-mastrangelo** [comment]
Would you be okay if `io.netty.internal.tcnative.SSL.fipsModeSet` returned the value from OpenSSL?

**Comment by Andrew-Lev** [comment]
Yes that would work.

**Comment by carl-mastrangelo** [comment]
Ok in that case, file a bug at https://github.com/netty/netty-tcnative  since this doesn't seem gRPC specific.  You can cross link the issue with this one.
