### ISSUE TITLE
DNSNameResolver ignore targetURL.

### ISSUE THREAD

**Issue by gsjessicaman** [grpc/grpc-java#6036]
###What version of gRPC are you using?
1.22.1

### What did you expect to see?
The authority part of the target URL passed from client is used to form part of the DNS host and port when it looks up the SRV and TXT records.

Here is the start:

  DnsNameResolver(@Nullable String nsAuthority, String name, Args args,
      Resource<Executor> executorResource, Stopwatch stopwatch, boolean isAndroid) {
    Preconditions.checkNotNull(args, "args");
    // TODO: if a DNS server is provided as nsAuthority, use it.
    // https://www.captechconsulting.com/blogs/accessing-the-dusty-corners-of-dns-with-java
    this.executorResource = executorResource;
    // Must prepend a "//" to the name when constructing a URI, otherwise it will be treated as an
    // opaque URI, thus the authority and host of the resulted URI would be null.
    URI nameUri = URI.create("//" + checkNotNull(name, "name"));

From this point onward the authority obtained from the targetUri passed to this constructor is lost. Therefore if we want to use an alternative DNS server from the default one, the current code doesn't work.

In the code where it looks up the SRV record:

     List<String> grpclbSrvRecords =
          recordFetcher.getAllRecords("SRV", "dns:///" + grpclbHostname);

Given that "grpclbHostname" is the service name passed from the client with prefix _grpclb._tcp. there is no way I can use a different DNS server other than the underlying one for the host where the code is executed.

For example, this is what I want to be able to do:

   public HelloWorldClient(String host, int port) {
        this(ManagedChannelBuilder
                .forTarget("myowngrpclb://dnshost:dnsport/helloworld.testdomain.com")
                .usePlaintext());

Even though I have the SRV record for _grpclb._tcp.helloworld.testdomain.com defined in "dnshost:dnsport", the code fails to find it.

**Comment by ejona86** [comment]
grpc-java does not support the authority part of the dns scheme. We use libc's A and AAAA lookup, which does not support using alternative dns servers. Although SRV/TXT lookup could potentially use the authority, we really want to use the same dns server as used for A/AAAA.
