### ISSUE TITLE
grpc调用过程出现ATTR_SECURITY_LEVEL问题

### ISSUE THREAD

**Issue by puritykid** [grpc/grpc-java#6037]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
2.3.0

### What did you expect to see?
Exception in thread "grpc-default-executor-0" java.lang.NoSuchFieldError: ATTR_SECURITY_LEVEL

**Comment by ran-su** [comment]
It looks like a dependency version issue. By the way, the latest gRPC java version is v1.22.1. We may be able to help you further once you provide more and accurate information.

**Comment by puritykid** [comment]
thanks！I found  that some packages dependencies are not imported! now my question is resolved.

**Comment by ran-su** [comment]
closing since issue is resolved.
