### ISSUE TITLE
BufferingHttp2ConnectionEncoder does not shutdown properly on channelInactive

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#605]
@nmittler 

There is a nasty race condition during the handling of channelInactive in NettyClientHandler which goes a bit like this....

1. NettyClientHandler.channelInactive -> for each active stream report closure to GRPC
2. NettyClientHandler.channelInactive -> Http2ConnectionHandler.channelInactive -> Http2ConnectionHandler.BaseDecoder.channelInactive -> for each active stream call close -> BufferingHttp2ConnectionEncoder.Http2ConnectionAdapter.onStreamClose -> try creating new stream -> adds stream to active list (OOPS! this stream is never closed)

This reproduces for NettyClientTransportTest.bufferedStreamsShouldBeClosedWhenTransportTerminates with 5.0beta5.

Having streams being created as a side-effect of channel inactivation is undesirable. Potential fixes include
- Reorder teardown in Http2ConnectionHandler.BaseDecoder.channelInactive so encoders are closed() before streams are closed.
- Make BufferedHttp2ConnectionEncoder check channel.isActive() when trying to create streams.

**Comment by nmittler** [comment]
@louiscryan I've already been working on a fix for this.  See #590

**Comment by nmittler** [comment]
NOTE: this has been fixed in Netty.  We'll get the fix when we upgrade to Netty 4.1.beta6 (as soon as it is released).

@normanmaurer any thoughts on timeline for beta6?
