### ISSUE TITLE
Does gRPC Testing support JUnit5?

### ISSUE THREAD

**Issue by horiadruliac** [grpc/grpc-java#6053]
### What version of gRPC are you using?
1.21.0

Does gRPC Testing support JUnit5?

**Comment by creamsoup** [comment]
we are using junit 4 for various reasons.
afaik, JUnit5 has Vintage TestEngine which can run junit 3 and 4. See [junit documentation](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-running) for more details.
