### ISSUE TITLE
Need to know how NettyServerBuilder allocates memory to the buffer

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc-java#6067]
Question copied from https://github.com/grpc/grpc/issues/19887

If i increase the inbound max message size at server side to be 1GB by NettyServerBuilder, how will the memory be allocated to buffer?

Will complete 1GB be allocated to the messaging buffer or will it be lazy allocation meaning only that only that much memory will be allocated , that is needed by object.

For example : If i set NettyServerBuilder.maxMessageSize(MAX_MESSAGE_SIZE), where MAX_MESSAGE_SIZE = 1GB

Then if client sends 500 MB object , will complete 1GB memory will be allocated or simply 500 MB memory will be allocated to the buffer ?

cc @RSoodAMAT

**Comment by carl-mastrangelo** [comment]
> If i increase the inbound max message size at server side to be 1GB by NettyServerBuilder, how will the memory be allocated to buffer?

In chunks, between 4K and 1MB.

> Will complete 1GB be allocated to the messaging buffer or will it be lazy allocation meaning only that only that much memory will be allocated , that is needed by object.

lazily

> Then if client sends 500 MB object , will complete 1GB memory will be allocated or simply 500 MB memory will be allocated to the buffer ?


It's more complicated than this because there is overhead per frame.  The fewer frames sent, the less overhead.

**Comment by ejona86** [comment]
This was discussed in https://groups.google.com/d/topic/grpc-io/o03BhDvJeC8/discussion .
