### ISSUE TITLE
Convert Alts to use new protocol Negotiator style

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#6074]
* TsiHandshakeHandler needs to extend ProtocolNegotiationHandler
* AltsProtocolNegotiator needs to be modified to work for both clients and servers.

**Comment by creamsoup** [comment]
>AltsProtocolNegotiator needs to be modified to work for both clients and servers.

@carl-mastrangelo can you clarify this? I am wondering why `AltsProtocolNegotiator` needs to be modified to work for both? most of PNs have both client / server PN.

**Comment by carl-mastrangelo** [comment]
I recall that KickNegotiationHandler could be removed.

**Comment by creamsoup** [comment]
@carl-mastrangelo okay thanks. sounds like the #6104 will resolve both.
