### ISSUE TITLE
grpc-java v1.23.0 should use which version netty-transport-native-epoll ?

### ISSUE THREAD

**Issue by imweijh** [grpc/grpc-java#6094]
### What version of gRPC are you using?
grpc-java v1.23.0

### What did you expect to see?
For HTTP2 DoS vulnerability, should I use netty-transport-native-epoll  v4.1.39 or v4.1.38( The grpc-java v1.23.0 use v4.1.38 netty) ？

**Comment by dapengzhang0** [comment]
Use netty v4.1.38 for grpc-java v1.23.0. See the table in https://github.com/grpc/grpc-java/blob/master/SECURITY.md 

The DoS vulnerability fix is embedded in grpc-java v1.23.0 (dd1315f11d3ca4e6ecbbf98be1ca1f68d1addb7e)

**Comment by imweijh** [comment]
Thanks
