### ISSUE TITLE
While grpc server occurred request parsing error, server application layer was not noticed

### ISSUE THREAD

**Issue by nicklaus4** [grpc/grpc-java#6108]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.16.1 version

### What did you expect to see?
While grpc server occurred request parsing error (pb incompatible normally), application layer was not notified, gprc framework just close current stream and then send a SendResponseHeadersCommand frame but not a cancelStream frame. Can anyone answer the two questions above? thx

**Comment by voidzcy** [comment]
Not quite understand your questions. But maybe here is what you are looking for:

When a request parsing error occurs on server side at https://github.com/grpc/grpc-java/blob/c9177b2327c8c424af7889d2306a4c767455f10b/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L299, an runtime exception is thrown and caught in `ServerStreamListener` at https://github.com/grpc/grpc-java/blob/c9177b2327c8c424af7889d2306a4c767455f10b/core/src/main/java/io/grpc/internal/ServerImpl.java#L775. It closes the stream by sending out trailers at https://github.com/grpc/grpc-java/blob/c9177b2327c8c424af7889d2306a4c767455f10b/core/src/main/java/io/grpc/internal/AbstractServerStream.java#L126. Sending trailers are sending a `SendResponseHeadersCommand` (see https://github.com/grpc/grpc-java/blob/c9177b2327c8c424af7889d2306a4c767455f10b/netty/src/main/java/io/grpc/netty/NettyServerStream.java#L182).

**Comment by nicklaus4** [comment]
> Not quite understand your questions. But maybe here is what you are looking for:
> 
> When a request parsing error occurs on server side at
> 
> https://github.com/grpc/grpc-java/blob/c9177b2327c8c424af7889d2306a4c767455f10b/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L299
> 
> , an runtime exception is thrown and caught in `ServerStreamListener` at
> https://github.com/grpc/grpc-java/blob/c9177b2327c8c424af7889d2306a4c767455f10b/core/src/main/java/io/grpc/internal/ServerImpl.java#L775
> 
> . It closes the stream by sending out trailers at
> https://github.com/grpc/grpc-java/blob/c9177b2327c8c424af7889d2306a4c767455f10b/core/src/main/java/io/grpc/internal/AbstractServerStream.java#L126
> 
> . Sending trailers are sending a `SendResponseHeadersCommand` (see
> https://github.com/grpc/grpc-java/blob/c9177b2327c8c424af7889d2306a4c767455f10b/netty/src/main/java/io/grpc/netty/NettyServerStream.java#L182
> 
> ).

what i mean is when parsing error occurred, grpc service cannot aware it

**Comment by voidzcy** [comment]
Yes, the service doesn't aware.

**Comment by nicklaus4** [comment]
got it
