### ISSUE TITLE
Netty server terminated - k8s readiness probe using gprc-health-probe

### ISSUE THREAD

**Issue by kubesure** [grpc/grpc-java#6112]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.21.0
### What did you expect to see?
A successful test by GRPC-health-probe on a k8s readiness probe.
###### 

A java grpc service when queried by a k8s readiness probe with a grpc-health-probe gives a netty exception netty server gives a io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated. The same service runs fine when used with outside k8s with docker

docker run -p 50051:50051 bikertales/publisher:v0.2
grpc-health-probe -addr=:50051 

The grpc server code (https://github.com/kubesure/publisher/blob/master/src/main/java/io/kubesure/publish/App.java)

deployment yaml (https://github.com/kubesure/helm-charts/blob/master/publisher/templates/deployment.yaml)

grpc-health-probe is build using go get

Minikube 1.2.0 k8s 1.15
 
Works fine with Go GRPC in k8s but with Java GRPC this error occurs.

**Comment by voidzcy** [comment]
We would appreciate more detailed stacktrace to look into this.

**Comment by ejona86** [comment]
Can you please provide the exception you see?

**Comment by kubesure** [comment]
The exception it throws is just io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated.
Can you explain how to generate a detailed trace, I will provide it.

**Comment by ejona86** [comment]
`io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated` is not an exception. That is the logging location. There should be a "Transport failed" message and an exception. https://github.com/grpc/grpc-java/blob/65321b5a6743f2089b581ab6a086ae4dffd83431/netty/src/main/java/io/grpc/netty/NettyServerTransport.java#L199

**Comment by ran-su** [comment]
I tried your image and deployed with `kubectl run k8s-health-probe --image=bikertales/publisher:v0.2 --port=50051`, I did not see any issue. Am I missing something?
I got: 
`go/bin/grpc-health-probe -addr=192.168.64.2:31131`
`status: SERVING`
192.168.64.2:31131 is the address `minikube service` gives.

env:
minikube version: v1.4.0
kubectl version:
Client "v1.14.6"
Server "v1.16.0"
Platform:"linux/amd64"

**Comment by kubesure** [comment]
Testing on,

Minikube 1.0.0    kubectl: v1.14.1 Server: v1.14.0  Platform:"linux/amd64"  
Minikube  v1.2.0 kubectl: v1.15.0 Server: v1.15.0 Platform:"linux/amd64" 

On the both version get the same erorr. However, on doing a health check its always gives a serving.

grpc-health-probe -addr=172.17.0.28:50051status: SERVING

deploy the pods with a chart [publisher](https://github.com/kubesure/helm-charts/tree/master/publisher)
 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 02, 2019 5:53:23 AM io.kubesure.publish.App start
INFO: Server started, listening on 50051
Oct 02, 2019 5:54:39 AM io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
        at io.grpc.netty.shaded.io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)

But, running this command does not result in error, 

 kubectl run k8s-health-probe --image=bikertales/publisher:v0.2 --port=50051
 k logs k8s-health-probe-86d446b6db-f9sw4 k8s-health-probe

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 02, 2019 6:10:43 AM io.kubesure.publish.App start
INFO: Server started, listening on 50051

The netty error could be due to probe getting disconnected.

**Comment by ejona86** [comment]
So the publisher is causing the problem? We don't have k8s experience, so it isn't clear how to test that.

But you also provided the full error. This is the important part:
```
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
```

Connection reset by peer is pseudo-normal. The client shouldn't generally RST the connection and instead close it gracefully, but there's not any real harm done and there's nothing for the server to do about it. We actually [have that error squelched](https://github.com/grpc/grpc-java/blob/2bc8c452f311a408be116e2c399f44db2f52cd72/netty/src/main/java/io/grpc/netty/NettyServerTransport.java#L55). grpc-java v1.21.0 used `equals()` when comparing the strings, but v1.22.0 and later use `contains()`. Upgrading your grpc-java version should make the error "go away" (it'll still be happening, but it will be logged at FINE instead of INFO).

**Comment by kubesure** [comment]
Thanks will upgrade.
