### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path

### ISSUE THREAD

**Issue by qiangwen** [grpc/grpc-java#6115]
Please answer these questions before submitting your issue.

**Comment by ran-su** [comment]
I found something on netty, the discuss there may be helpful. https://github.com/netty/netty-tcnative/issues/331

**Comment by ejona86** [comment]
This is not enough information to help. You would need to provide the backtrace and causal chain as well (it would be fine to remove your own classes from the backtrace).

Closing, since nothing happened with this in a week. We can reopen if more details are provided.
