### ISSUE TITLE
com.google.errorprone:error_prone_annotations:pom:2.3.3-SNAPSHOT

### ISSUE THREAD

**Issue by ijliym** [grpc/grpc-java#6133]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
grpc-java 1.23.0

### What did you expect to see?

Maven compile occurs `Could not find artifact com.google.errorprone:error_prone_annotations:pom:2.3.3-SNAPSHOT`

**Comment by ran-su** [comment]
I don't see use of errorprone:2.3.3-SNAPSHOT in grpc-java.

**Comment by ran-su** [comment]
Closing, since there is no response for a week.
