### ISSUE TITLE
Add copy method to NameResolverRegistry

### ISSUE THREAD

**Issue by ST-DDT** [grpc/grpc-java#6153]
### What version of gRPC are you using?

grpc-java 1.23.0

### The problem

2 applications in the same JVM (tomcat) define a custom ´SelfNameResolverProvider` that maps the client name `self` to
the own application. If both applications add it to the registry then the second one will mistakenly connect to the first application.

### Possible Workaround

Create new (empty) registries and populate them with "well-known" `NameResolverProvider`s.
Drawback: All providers must be known at compile time and any later additions won't be picked up from the classpath.

### Suggested fix/improvement

Add a `copy()`, `clone()` or `initializeDefaults()` method to the registry that allows creating safe copies/independent instances of the registry that still contains the default/expected providers.

**Comment by ejona86** [comment]
Tomcat should be using a separate ClassLoader for each app, so each app would have its own globals. That would only break if grpc was being exported by Tomcat itself, which would be a bug.

I'm not against having a copy()-like method, but it seems the wrong solution to this problem.

**Comment by ST-DDT** [comment]
I used the tomcat as an example. If you place  some common/shared libs inside the libs folder then Afaict Tomcat loads them with his own cl which saves  some RAM and thus causes this issue.

I had this issue during integration tests where I start the application multiple times.
https://github.com/yidongnan/grpc-spring-boot-starter/commit/ac7a2a7a52a6f4b997ba5a881643599b08b0bce6
I fixed my tests by ensuring that I cleanup the registry after each test, but that only works as long as my test/the application with my lib isn't run concurrently, but that isn't in my hand.

Maybe a `addDefaults()` method would be better as it ensures a clean state of the registry. Another alternative would be a RO access to the contained NameResolverProviders. Then I could copy them myself.

**Comment by ejona86** [comment]
What does your SelfNameResolverProvider do? Why is "self" not "self"? How should one half of the application know which half it is in? Typically ClassLoader is how that would work, to differentiate singletons. Are you wanting to provide NameResolverRegistry to ManagedChannel?

**Comment by ST-DDT** [comment]
> What does your SelfNameResolverProvider do? Why is "self" not "self"? How should one half of the application know which half it is in?

The `SelfNameResolverProvider` resolves the name for grpc-netty-client to connect to the grpc-netty-server that was started as part of the same `ApplicationContext` (spring application).
It works similar to the InProcessServer` but without changing the actual way of connecting. If you use different ways then there is a risk that you might miss an interceptor on either the client or server side.

It's purpose is to allow zero config connections to itself, mainly for cases where the server port is randomized such as tests and environments with cloud discovery. See also https://github.com/yidongnan/grpc-spring-boot-starter/issues/174#issue-399522935

````java
@GrpcClient("self")
private TestServiceBlockingStub selfStub;
````

It's intentionally designed using only grpc features to avoid additional dependencies both internally and library wise.

> Typically ClassLoader is how that would work, to differentiate singletons.

Unfortunately for tests this isn't true. They start and stop the application multiple times, but all use the same singletons. Is there an `@Fork` annotation for tests?

> Are you wanting to provide NameResolverRegistry to ManagedChannel?

If the user doesn't specify a specific `NameResolver.Factory`, then I default to using the registry.
[NettyChannelFactory#newChannelBuilder()](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/NettyChannelFactory.java#L76)

**Comment by ejona86** [comment]
> It works similar to the InProcessServer` but without changing the actual way of connecting.

I'd suggest making it even more similar to InProcessServer: giving each running server a name. You can use an integer and increment it for each server or use a UUID. Although honestly, at that point I don't see any difference to just specifying the address directly (e.g., "127.0.0.1:theport") and avoiding any custom name resolver.

An alternative would be to construct the self resolver differently each time, so that you can have multiple registered. But then you'd need to refer to them by "self1", "self2", etc. Again, I don't really see any advantage over passing the address directly.

> Unfortunately for tests this isn't true.

Yeah, the problem seems you're using a singleton that isn't a singleton. You can run your tests serially, which should work.

In our own tests when we really, really need to test a singleton we use [StaticTestingClassLoader](https://github.com/grpc/grpc-java/blob/master/context/src/test/java/io/grpc/StaticTestingClassLoader.java), but it is a PITA to get the regex correct and to work out a nice communication method between the code within the ClassLoader and the test outside.

None of those are great for a library.

**Comment by ran-su** [comment]
If it is a Spring application, you can get a new instance each time by set the bean's scope to prototype.

**Comment by ST-DDT** [comment]
> > It works similar to the InProcessServer` but without changing the actual way of connecting.
> 
> I'd suggest making it even more similar to InProcessServer: giving each running server a name. You can use an integer and increment it for each server or use a UUID. Although honestly, at that point I don't see any difference to just specifying the address directly (e.g., "127.0.0.1:theport") and avoiding any custom name resolver.

As mentioned above I would like to avoid dependencies between the server and the client. The client doesn't know the port of the server beforehand. The name resolver is my way of passing that information from the server to the client via a (more or less) predictable way. I cannot use random values there as I somehow need to transfer them between the server and the client part. If I could then I could use the port directly.

> > Unfortunately for tests this isn't true.
> 
> Yeah, the problem seems you're using a singleton that isn't a singleton. You can run your tests serially, which should work.

That class has an public constructor so I don't consider it a singleton, but there is a special (half singleton) instance that contains the actual instances I need, but I don't have access to them.
For now I avoided the problem by de-registering the name resolver on application shutdown.
However if this ever happens for real applications then I don't have a choice and have to replicate the entire logic of the registry myself. (Which I hope to avoid)

> If it is a Spring application, you can get a new instance each time by set the bean's scope to prototype.

Unfortunately not, because the instance is "created" from a static method/field and thus it would return the same bean nevertheless. This request is about adding a method that allows me to be independent of said instance and return new instances as needed (that still contain the default entries).

[`GrpcClientAutoConfiguration#grpcNameResolverRegistry(...)`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java#L119)

**Comment by ejona86** [comment]
> I cannot use random values there as I somehow need to transfer them between the server and the client part.

Don't try to transfer it between server and client. Instead, generate the random value and then pass it to both the client and server. This is what we suggest for the in-process transport, when a fixed name doesn't work. If you can create a new Registry instance and pass it around as needed, then you should be able to do it with a random value. Although I'd agree at that point specifying the host address stops working.

Some details to help you understand why I'm arguing the way I am: I plan to delete ManagedChannelBuilder.nameResolverFactory. Adding the NameResolverRegistry was to allow people to avoid using ManagedChannelBuilder.nameResolverFactory. While we have prepared our internals to allow users to inject NameResolverRegistry instances, that is not currently exposed and we were going to take a "wait and see" approach to see if it was actually necessary.

**Comment by ST-DDT** [comment]
> > I cannot use random values there as I somehow need to transfer them between the server and the client part.
> 
> Don't try to transfer it between server and client. Instead, generate the random value and then pass it to both the client and server.

The server port is defined in the server config, and if it is explicitly set to random, then it will decide on the port using a free port. Unless I add a new component that is available to both client and server (adds a new dependency), there is no way to share this value between both.

> Some details to help you understand why I'm arguing the way I am: I plan to delete ManagedChannelBuilder.nameResolverFactory.

This is a **very** important information for me.
Because currently I don't set the registry directly in there and instead I map them with my client configuration.

The process works like this:

1) A field with a `@GrpcClient("<name>")` annotation gets [injected](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java#L80)
2) The injection factory takes the `<name>` and [creates a channel](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/NettyChannelFactory.java#L74) with the name.
3) The [ConfigMappedNameResolverFactory](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/ConfigMappedNameResolverFactory.java#L80) reads said name and uses it to lookup the actual (configurable) address, which it then delegates to the internal name resolver (by default the registry). 

Example: `foobar` (from code) -> `disovery:///foobar.prod` (from config) -> [`10.11.12.13:1337`, ...] (from web-service)

The configuration for the actual target address can be configured via file, classpath resource, startup parameter, environment variable or cloud config.

I don't use the config directly as the name is used in multiple places, such as logs. There also was another place, but I don't remember it right now (I might be completely wrong here).

If I cannot control the main resolver any more, then I need some way to pass something with the channel that allows my name resolvers to detect that they should resolve that incoming address. Currently I have 3 name resolvers that are application context dependent: config, discovery, self
The config one can potentially be removed (now that the registry exists), but the other ones still have that issue. Alternatively I could just declare it as a limitation of grpc-java (which I'm kind of doing already).

**Comment by ejona86** [comment]
If you can pass along NameResolverFactory, then you can pass along a string.

I didn't see any usages of SelfNameResolver nor any callers of newChannelBuilder(). It seems like those would be plumbed manually by your users. Instead of passing along an object, you can pass along a string (mirroring GrpcServerAutoConfiguration.selfNameResolverFactory()):

```
static int counter;
static Map<String, GrpcServerProperties> map;

// to register
String name = "/" + counter++;
map.put(name, grpcServerProperties);
return "self://" + name;

// in the SelfNameResolverFactory (although, honestly, it may be better to do this in 
GrpcServerProperties properties = map.get(targetUri.getPath());
return new SelfNameResolver(properties, args);
```

But alternatively, you could make all three depend on a registered "application context id", similar to what was done with the GrpcServerProperties for self. And then you'd use names like `self://config3` and `discovery://config3/foobar.prod`. GrpcClientBeanPostProcessor already has access to the ApplicationContext, so you could register the context very early (to choose the id; although you could even do two-phase if you needed where you choose the id early and then later register the context once you have it).

**Comment by ejona86** [comment]
Where does this stand? @ST-DDT, did my suggestion end up working for you? Or do you still see it as causing you lots of problems?

**Comment by ST-DDT** [comment]
I haven't had time to actually implement it yet, but for the `self` name this might work.
As for the `config` I need to replace it with one that use the actual address instead of the name.

Is [`forName(String)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyChannelBuilder.html#forTarget-java.lang.String-)'s `name` parameter used for anything else than the name resolution via `NameResolver`? (to avoid breaking subtle things)
Is there a planned milestone or release in which you change this functionality? (for planning)

**Comment by ejona86** [comment]
> Is forName(String)'s name parameter used for anything else than the name resolution via NameResolver?

No. The NameResolver gets to fully-define the semantics of it. The only output that grpc uses is the result of `NameResolver.getServiceAuthority()`.

> Is there a planned milestone or release in which you change this functionality?

If you mean removing the ability to specify a NameResolver.Factory on the ManagedChannelBuilder, no. It doesn't hurt us too much; I'm mainly worried about users using it and getting entrenched in a particular design. We should probably put `@Deprecated` on it, but we can leave it around for a while. However, if a year from now it was still there, I would be sad.

NameResolver.Factory itself is going to be removed, as it isn't necessary any more. But again, it can be marked deprecated and just "sit" for a while to give time to migrate.

There are some other features that are planned that won't work if you use NameResolver.Factory (like https://github.com/grpc/grpc-java/issues/3085), but I don't think any of those would be surprising (that they don't work).

**Comment by ST-DDT** [comment]
Thanks for the details.

I'll adjust our implementation then.
