### ISSUE TITLE
During shutdown, Netty should gracefully wait for RPCs to complete before terminating the connection

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#616]
Currently it is just calling "channel.close();" which brings down the TCP connection and cleans up all the RPCs.

**Comment by nmittler** [comment]
@ejona86 not sure I understand ... calling `close` on the Netty channel will wait for any outstanding RPCs to complete before the actual channel close occurs. What behavior are you expecting here?

**Comment by ejona86** [comment]
Arg. I forgot about that behavior _again_. That confuses me once a month.

Closing. It is behaving correctly. FYI @madongfly
