### ISSUE TITLE
Question: prevent auto-cancellation

### ISSUE THREAD

**Issue by tommyulfsparre** [grpc/grpc-java#6160]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
`1.23.0`

### What did you expect to see?

When RPC finish a second RPC using a Future stub with a forked Context should not cascade cancellation. 

We have a use-case where we want to fire and forget an additional RPC when the first RPC finish. I have tried to reproduce that here: [ContextResource.java#L62](https://github.com/tommyulfsparre/grpc-context-debug/blob/master/src/main/java/com/grpc/grpccontextdebug/ContextResource.java#L62). What we see is the second RPC will be cancelled with  `io.grpc.StatusRuntimeException: CANCELLED: io.grpc.Context was cancelled without error`.

 
Replacing [fireAndForgetWithListenableFuture](https://github.com/tommyulfsparre/grpc-context-debug/blob/master/src/main/java/com/grpc/grpccontextdebug/ContextClient.java#L84) with [fireAndForget](https://github.com/tommyulfsparre/grpc-context-debug/blob/master/src/main/java/com/grpc/grpccontextdebug/ContextClient.java#L64) has the expected behaviour of preventing the cascading cancellation. 
What would the "correct" way of using a forked Context with a future stub be? I tried to find an example but came up short.

**Comment by ejona86** [comment]
In `fireAndForget()`, you have:
```java
    Context.current().fork().run(
        () -> asyncStub.withDeadlineAfter(2, TimeUnit.SECONDS).fireAndForget(req, streamObserver));
```

But you don't have something similar in `fireAndForgetWithListenableFuture()`. You need something similar to:
```java
    final ListenableFuture<FireAndForgetResponse> future =
        Context.current().fork().call(
            () -> futureStub.withDeadlineAfter(2, TimeUnit.SECONDS).fireAndForget(req));
```

**Comment by tommyulfsparre** [comment]
Right, I was hoping to achieve it with an executor like in [ExecutorUtils.java](https://github.com/tommyulfsparre/grpc-context-debug/blob/master/src/main/java/com/grpc/grpccontextdebug/ExecutorUtils.java#L20) on the stub but it didn't work. Will go with your suggestion instead, thanks!
