### ISSUE TITLE
Question fro ManagedChannelImpl.getNameResolver 

### ISSUE THREAD

**Issue by yezi924** [grpc/grpc-java#6164]
### I guess this is a bug  in ManagedChannelImpl.getNameResolver ?
```java
  // It doesn't look like a URI target. Maybe it's an authority string. Try with the default
      // scheme from the factory.
try {
        targetUri = new URI(nameResolverFactory.getDefaultScheme(), "", "/" + target, null);
      } catch (URISyntaxException e) {
        // Should not be possible.
        throw new IllegalArgumentException(e);
      }
```
### this target should be set in host other than path？

**Comment by creamsoup** [comment]
that particular code block is trying to resolve non standard name. There are tests go through that code path such as following

class: ManagedChannelImplGetNameResolverTest
* validTargetStartingWithSlash
* validAuthorityTarget
* validTargetWithInvalidDnsName
* validIpv6AuthorityTarget
* validTargetNoResovler
* validIpv4AuthorityTarget

if you think any of those tests are wrong, please let us know
