### ISSUE TITLE
Long running request got cancelled when sending a message from server

### ISSUE THREAD

**Issue by dwegn** [grpc/grpc-java#6166]
#### Server (Java)
From Maven:
io.grpc:grpc-netty - 1.21.0

#### Client (C#)
From nuget:
- GRPC.Core 1.20.1.0
- Google.Protobuf 3.7.0.0
- grpc_csharp_ext.x64.dll (SHA256 Hash E618BAD510A1F99E804E8C3628251A9E84F5487AC2B0D8ABFBF42C0B321167B1)
- grpc_csharp_ext.x86.dll (SHA256 Hash B74C22A582F487D1BFC1B003B0D9E12F90FAE459C82FC6F2455E43892C8A08B2)
- user-agent: grpc-csharp/1.20.1 grpc-c/7.0.0 (windows; chttp2; godric)

### What did you do?
We implemented a service that receives a request from a gRPC client and then waits for a condition to trigger which can take up to several hours. When this condition is finally triggered, the gRPC server sends a message to the client and completes the connection.

```
streamObserver.onNext( response );
streamObserver.onCompleted();
```

The server uses keep alive heartbeating with a keepalive time of 30sec.

```
NettyServerBuilder
                .forAddress( localAddress )
                .keepAliveTime( 30, TimeUnit.SECONDS )
...
```

Now the problem is that when the server finally reached the condition and wants to send a message, we catch the following exception:

```
[2019-09-09 14:26:36,031] [ERROR] [XYZ] [XYZ] CANCELLED: call already cancelled
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
        at io.grpc.Status.asRuntimeException(Status.java:524)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:339)
```

The client uses the async API without setting a deadline or headers, without using a CancellationToken and without Context Propagation.

### What did you expect to see?

As we can see that the heartbeats are working fine, our expectation is that the server can send messages using the streamObserver and the call us not CANCELLED.

We were able to reproduce this issue and to create a network capture (I removed the heartbeats):
```
13	5.781939	[client]	[server] 	GRPC	778	WINDOW_UPDATE[1], HEADERS[3]: POST /xyz, WINDOW_UPDATE[3], DATA[3] (GRPC) (PROTOBUF), HEADERS[5]: POST /xyz, WINDOW_UPDATE[5], DATA[5] (GRPC) (PROTOBUF), HEADERS[7]: POST /xyz, WINDOW_UPDATE[7], DATA[7] (GRPC) (PROTOBUF), WINDOW_UPDATE[0], PING[0], HEADERS[9]: POST /xyz, WINDOW_UPDATE[9], DATA[9] (GRPC) (PROTOBUF), WINDOW_UPDATE[0]
843	7616.610003	[server] 	[client]	HTTP2	107	HEADERS[9]: 200 OK, DATA[9]
844	7616.613049	[server] 	[client]	GRPC	94	RST_STREAM[9], HEADERS[9] (GRPC) (PROTOBUF)
```

The RST_STREAM message has Error code CANCEL(8).

**Comment by dapengzhang0** [comment]
What language is your client? How does your client send request and handle response?

**Comment by zhangkun83** [comment]
Can you confirm whether the client/server StreamObserver get the CANCELLED notification before the server tries to finish the RPC?

**Comment by chrjohn** [comment]
Sorry for the delay. We will prepare a reproducer for this problem shortly.

**Comment by chrjohn** [comment]
The "long running request" was not the root cause, so I have opened https://github.com/grpc/grpc-java/issues/6323 to not cause any confusion.
