### ISSUE TITLE
tracking issue to backport proxy handler fix (#6159)

### ISSUE THREAD

**Issue by creamsoup** [grpc/grpc-java#6167]
when the #6159 is verified, backport to 1.22, 1.23 and 1.24

**Comment by ran-su** [comment]
The fix need to be backported to 1.24 too, since the branch was cut last week.

**Comment by creamsoup** [comment]
thanks @ran-su updated the note.

**Comment by creamsoup** [comment]
all 3 versions are backported, but not yet released.
