### ISSUE TITLE
Guava 26-android conflicts with runtime dependencies 

### ISSUE THREAD

**Issue by zcharli** [grpc/grpc-java#6168]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.23.0
Java 11.0.3

### What did you expect to see?
I do not expect to see `java.lang.NoSuchFieldError: JAVA_LOWER_CASE` which is part of the `CharSet` object from guava JRE.

The guava 26-android version conflicts with my current runtime environment since it does not have the field above. I have guava 23 JRE in my runtime that needs to be supported. Gradle automatically picks the higher version number to load during runtime. I am able to easily override the guava version used for my project by specifying
```compile ('com.google.guava:guava:23.0') { force = true }```
However, every upstream client that depends on my library needs to force their guava up the chain (we all use lower versions). 

Does anyone know of a way that I can forcefully set the guava version for my library while maintaining the versions as well for upstream consumers of my library? I hate to tell everyone using my library to add `{ force = true }` to their guava dependency. 

I don't need android support, so if there is away to drop android guava completely and replace it with the jre version of guava, that could be an acceptable solution.

**Comment by creamsoup** [comment]
we are only using guava stable APIs to avoid such issues. Non stable (beta) APIs are subject to change;API using beta API is not stable by default. There seems like a bit of history related to `JAVA_LOWER_CASE`, but the API is actually deprecated beta in earlier versions including 23.

For libraries, we highly recommend to use **only stable API**s to avoid such issue. To temporarily fix the issue, I can think of couple ways (not very ideal solutions). 

* repackage/shade gRPC's guava.
* or, exclude gRPC's guava dependency in gradle to use other transient dependency guava (v23). in this case, make sure guava is in the dependency tree.

**Comment by zcharli** [comment]
Is your first suggestion related to modifying the gRPC's POM file?
Could you give me an example of how to perform your second suggestion?

**Comment by creamsoup** [comment]
the exclusion of transitive dependency can be performed on your `pom.xml` or `build.gradle`. See examples below

for gradle
```gradle
dependencies {
  implementation('io.grpc:grpc-core:1.24.0') {
     exclude group: 'com.google.guava', module: 'guava' 
  }
}
```

for maven
```xml
 <dependency>
  <groupId>io.grpc</groupId>
  <artifactId>grpc-core</artifactId>
  <version>1.24.0</version>
  <exclusions>
    <exclusion>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </exclusion>
  </exclusions> 
</dependency>
```

I didn't actually test, so it may contain typo.

**Comment by zcharli** [comment]
Thanks!
