### ISSUE TITLE
How does IOS call the GRPC server based on NettyServerBuilder

### ISSUE THREAD

**Issue by crixusshen** [grpc/grpc-java#6174]
How does IOS call the GRPC server based on NettyServerBuilder? thanks

**Comment by creamsoup** [comment]
all gRPC implementation use same wire protocol based on HTTP2. as long as IOS grpc use same protocol, I hope it does, it should be able to communicate with java (or any gRPC official implementation) gRPC server.

if you are curious, you can read [http2 spec](https://http2.github.io/http2-spec/).
