### ISSUE TITLE
API to add constraints on SSL for key size

### ISSUE THREAD

**Issue by adityavikasd** [grpc/grpc-java#6204]
### Is your feature request related to a problem? Please describe.
I have a gRPC server which is using mutual TLS and I want to reject connections from clients who have a public key size less than 2048 bits.

### Describe the solution you'd like
There should be an API in the `SslContextBuilder` class to set SSL key size related constraints 

### Describe alternatives you've considered
I was able to achieve the same using a `ServerInterceptor` by doing something like this
```java
public class SSLInterceptor implements ServerInterceptor {
    @Override
    public <ReqT, RespT> Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
        try {
            SSLSession sslSession = call.getAttributes().get(Grpc.TRANSPORT_ATTR_SSL_SESSION);
            RSAPublicKeyImpl pk = (RSAPublicKeyImpl) sslSession.getPeerCertificates()[0].getPublicKey();
            if (pk.getModulus().bitLength() < 2048) {
                // reject call
            }
            // proceed with the call
        } catch (SSLPeerUnverifiedException e) {
            // do something
        }
        ...
    }
}
```
This is a bad way to do it because

 1. The validation is being done after the connection is already
    established.
 2. The validation is only triggered when a request/call is made.
 3. Every single call involves an extra overhead of validation.
 4. In case of a validation failure, only the call is rejected but not the connection to the client.

In an ideal scenario

 1. The validation is done during the connection establishment phase. (or some point during the creation of the channel between client and server)
 2. The validation failure would prevent the connection from being created and not set it up and disconnect later.
 3. A client is only validated once per session and all the calls made during that session do not incur any overhead.

**Comment by ejona86** [comment]
I think you need to provide a `javax.net.ssl.TrustManagerFactory` to Netty's `SslContextBuilder`. You'd probably want to implement `X509ExtendedTrustManager`, do your check, and then delegate to a "real" implementation for the rest of the cert chain checking.

You can do something like this to get the default-configuration `TrustManagerFactory`:
```java
TrustManagerFactory tmf = TrustManagerFactory.getInstance(
    TrustManagerFactory.getDefaultAlgorithm());
tmf.init((KeyStore) null);
// loop through tmf.getTrustManagers() checking for one implementing X509TrustManager
```

**Comment by adityavikasd** [comment]
Could you please guide me on how to add my own implementation of the `X509ExtendedTrustManager` to the default `TrustManagerFactory`? Or creating a new `TrustManagerFactory` which returns my `X509ExtendedTrustManager` when `tmf.getTrustManagers()` is called?

**Comment by ejona86** [comment]
I would not suggest making your implementation the default TrustManagerFactory. If you were okay with doing that, then you should configure `jdk.certpath.disabledAlgorithms` instead.

**Comment by adityavikasd** [comment]
I get it. But, changing the `jdk.certpath.disabledAlgorithms` would affect all the Java apps that use the same jdk installation. I'm trying to make this validation happen for one app only. 

My struggle here is with passing the custom `X509ExtendedTrustManager` into the Netty's `SslContextBuilder`

The `SslContextBuilder::trustManager()` method only takes a `TrustManagerFactory` and not a `TrustManager[]`. I'm trying to figure out how to plug in this newly created `TrustManager` into the `SslContextBuilder` via a  `TrustManagerFactory`

**Comment by sanjaypujare** [comment]
> I get it. But, changing the `jdk.certpath.disabledAlgorithms` would affect all the Java apps that use the same jdk installation. I'm trying to make this validation happen for one app only.
> 

I found some references about security-overrides per JVM instance. Not sure if you can make them work for your JDK installation:

https://dzone.com/articles/how-override-java-security
https://serverfault.com/questions/793546/disallow-jvm-system-security-policy-settings-override

**Comment by ejona86** [comment]
@adityavikasd, I'd suggest making your own TrustManagerFactory. It seems you could extend TrustManagerFactory and override all the methods, delegating to another instance, except for getTrustManagers() in which you would write custom logic to return your trust manager instead of the default one.

The other potential option is to implement TrustManagerFactorySpi. You will still need to delegate to a real instance, so maybe create one with something like `(TrustManagerFactorySpi) Security.getProvider("JSSE").getService("TrustManagerFactory", TrustManagerFactory.getDefaultAlgorithm()).newInstance(null)`. I'd probably start with providing the "real" Provider to the TrustManagerFactorySpi.

I've never done any of that before, but they seem like avenues try. I realize that the Java API is quite opaque, but it's also all we have.

**Comment by adityavikasd** [comment]
Thanks for the help. I was able to implement this. By creating my own `TrustManagerFactorySp`, `TrustManagerFactorySpi` and `TrustManager`. 

The Java security API seem so twisted though!
