### ISSUE TITLE
how can I know the channel is inactive in the grpc server.

### ISSUE THREAD

**Issue by xiaochaohit** [grpc/grpc-java#6209]
Hi
  I'm here for the help of grpc usage.
  When I working on grpc netty server in java. Do I have a way to know if the netty channel between client and server is inactive?
  The scenario is that I want to clean some resources (for instance, the TCP connection between my service and database etc.) if the server side detects the channel in between is inactive.
  

The code below describes how I created the grpc service:
```
Server grpcServer = NettyServerBuilder
                    .forAddress(new DomainSocketAddress(uds))
                    .bossEventLoopGroup(bossGroup)
                    .workerEventLoopGroup(workGroup)
                    .channelType(EpollServerDomainSocketChannel.class)
                    .addService(service)
                    .build()
                    .start();
```
Basically what I found in the source code is:
```
 public void channelInactive(ChannelHandlerContext ctx) throws Exception {
    try {
      if (keepAliveManager != null) {
        keepAliveManager.onTransportTermination();
      }
      if (maxConnectionIdleManager != null) {
        maxConnectionIdleManager.onTransportTermination();
      }
      if (maxConnectionAgeMonitor != null) {
        maxConnectionAgeMonitor.cancel(false);
      }
      final Status status =
          Status.UNAVAILABLE.withDescription("connection terminated for unknown reason");
      // Any streams that are still active must be closed
      connection().forEachActiveStream(new Http2StreamVisitor() {
        @Override
        public boolean visit(Http2Stream stream) throws Http2Exception {
          NettyServerStream.TransportState serverStream = serverStream(stream);
          if (serverStream != null) {
            serverStream.transportReportStatus(status);
          }
          return true;
        }
      });
    } finally {
      super.channelInactive(ctx);
    }
  }
```
However, it only handles the situation when (e.g.) the client shuts down abruptly while doing the request to the server. **What I really needs is our server is able to detect the channel's inactivity in-between anytime rather than the only or limited scenarios like above. **

If there is any feature or method I can use fitting for my need?

Thanks!

**Comment by creamsoup** [comment]
`ManagedChannel` provides APIs for channel status changes via `ConnectivityState.notifyWhenStateChanged()`. Also, `ManagedChannel.getState()` API might be handy. Status change to `ConnectivityState.IDLE` might be what you want to use.

**Comment by xiaochaohit** [comment]
> `ManagedChannel` provides APIs for channel status changes via `ConnectivityState.notifyWhenStateChanged()`. Also, `ManagedChannel.getState()` API might be handy. Status change to `ConnectivityState.IDLE` might be what you want to use.
Thanks for your reply！
        I found the APIs document of the `ManagedChannel`. I found it usage for client side, but I really want to know is the channel inactive status in server side.

**Comment by creamsoup** [comment]
sorry for the late response. I am having trouble understanding your question, please correct me if i am misinterpreting your question.

There are some reasons why we don't expose server status etc. if your purpose is purely resource management, why not using resource pool (object/connection pool)? it is hard to imagine you want to manage resource tied to channel's lifecycle (maybe possible in the server interceptor?).
 
can you describe your use case little more in detail?

**Comment by zhangkun83** [comment]
I think you are looking for `NettyServerBuilder.maxConnectionIdle()`.

**Comment by sanjaypujare** [comment]
I noticed you are using `EpollServerDomainSocketChannel` which creates child channel of type `EpollDomainSocketChannel` and that one supports [`isInputShutdown`](https://netty.io/4.1/api/io/netty/channel/epoll/AbstractEpollStreamChannel.html#isInputShutdown--) or [`isShutdown`](https://netty.io/4.1/api/io/netty/channel/epoll/AbstractEpollStreamChannel.html#isShutdown--) . Does that work (assuming you can get to these objects)?

**Comment by zhangkun83** [comment]
Assuming the question has been answered, closing now. If you need more clarification, feel free to reopen it.
