### ISSUE TITLE
netty-tcnative-boringssl-static version compatibility with 1.24.0

### ISSUE THREAD

**Issue by BenFradet** [grpc/grpc-java#6218]
Hello,

I'm curious as to what would be the continuation of the compatibility matrix exposed in this section: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty for grcp-netty 1.24.0.

Thanks,

**Comment by dapengzhang0** [comment]
Should be the same as 1.23.0.

1.23.x- | 4.1.38.Final | 2.0.25.Final
-- | -- | --

`1.23.x-` means 1.23 and later unless otherwise explicitly stated.
