### ISSUE TITLE
Mutual TLS with client hostname validation

### ISSUE THREAD

**Issue by jspeiser** [grpc/grpc-java#6235]
I've found a lot of information online about hostname validation on the client side, but is there a way for the server to verify the client's hostname when using mutual TLS? I'm currently building my server with something like:

```java
Server server = NettyServerBuilder
        .forPort(port)
        .sslContext(GrpcSslContexts.forServer(cert, key)
                .trustManager(new File("/path/to/root/crt"))
                .clientAuth(ClientAuth.REQUIRE)
                .build())
        .addService(new Service())
        .build();
```

**Comment by dapengzhang0** [comment]
We have examples for mutual TLS
https://github.com/grpc/grpc-java/tree/v1.24.0/examples/example-tls#hello-world-example-with-tls-with-mutual-auth

**Comment by sanjaypujare** [comment]
On the client side, the client makes an outbound connection request to a hostname which can be matched against the name (DN?) in the certificate presented by the server.

On the server side, the server just receives an incoming connection request from some client and there is no way to match the DN in the cert against any name.

**Comment by jiangtaoli2016** [comment]
It is common for client to verify server's hostname matches server's certificate (hostname verification). gRPC has build-in hostname verification support by default.

On server side, if server wants to validate client identity (hostname or other identity), it is authorization. In grpc-java, you can get security information from attributes `getAttributes().get(Grpc.TRANSPORT_ATTR_SSL_SESSION)`, then you verify client identity by yourself.

**Comment by jspeiser** [comment]
Thank you @jiangtaoli2016, that seems like what I need. How can I use `getAttributes()`, though? What class does it belong to?

**Comment by jiangtaoli2016** [comment]
Here is an [example](https://www.codota.com/code/java/methods/io.grpc.ServerCall/getAttributes).

**Comment by jspeiser** [comment]
Thank you for the clarification. The example that you gave comes from the grpc-spring-boot-starter library, I believe, and it's unclear to me how that applies to my code. Is there a way to inject something like that into the `sslContext` somehow?

**Comment by jiangtaoli2016** [comment]
@ejona86 please advice.

**Comment by ejona86** [comment]
@jspeiser, what you are needing is more authorizing the client which is not handled in `sslContext`. Instead, use a ServerInterceptor and the attributes will be available on the passed `call`.

**Comment by jspeiser** [comment]
Ah, a ServerInterceptor is exactly what I needed. Thank you! :)
