### ISSUE TITLE
file transfer using grpc stream

### ISSUE THREAD

**Issue by otmanel31** [grpc/grpc-java#6259]
Hi,

I'm currently sending file from server to client using grpc. This files could have a size of few kilobytes to 50megabytes. 

Below my proto example:

> service FileDownloader{
    rpc downloadFile(data) returns (stream file);
}
message data{
	string id= 1;
}
message file{
	bytes binary = 1;
	string name = 2;
}

So i use stream to get my file ....
As explained in [this tutorial](https://codelabs.developers.google.com/codelabs/cloud-grpc-java/index.html?index=..%2F..index#4) and official tutorial etc, we should use async stub in client side in order to get chunk that are sent by server. 
My first question is how to wait properly as this call is async ? 
Then, When my client call my grpc remote method, i feel my app is stuck when i'm wrting to ByteSink file. Server is sending chunk on first call (or first iteration or hasNext() call on blocking stub)  without any flow control on each chunk during loop ... or without waiting onNext iteration from client ... So server is sending data, client begin to write few kilobytes and then client is stuck and server continue to send is data until he finishes, but client is still stuck  on writing in byteSink file. This error occured only from remote server. When i run the server locally, the download is OK. 
**Any idea about what is happening ?** 
Initialy ,i worked with blockingStub, then i tried asyncStub ...and if i didn't had a sleep in server side, i cannot load correctly all bytes. Also, when i send file that had  1mb size, i face same issue.
Currently,  i'm sending between 8 to 16ko but the download is very slow .... 
Below piece of code of my server  code:
```java
InputStream inputstream = // from some file	

//int bufferSize = 1024 * 1024; // 1mo
int bufferSize = 8192;
byte[] buffer = new byte[bufferSize];
int tmp = 0;
// send stream to client, file (inpustream) could be chunked
com.********.*****.File.Builder builder = File.newBuilder();
builder.setName(objectName);
//ByteArrayOutputStream bos = new ByteArrayOutputStream();
while ((tmp = inputstream.read(buffer, 0, bufferSize)) != -1) {
	LOGGER.info("In chunker: {}", tmp);
        ByteString byteString = ByteString.copyFrom(buffer, 0, tmp);
	File m = builder.setBinary(byteString).build();
	Thread.sleep(80); // if not set, on first iteration in client side, all chunks are sent without any control on flow .... 
	responseObserver.onNext(m);
}
responseObserver.onCompleted();
```

then piece of code of client related call:
```java
public boolean downloadFile(String id, String updateRepoFolder) {

		String id= "someId";
		boolean downloaded = false;
		AtomicBoolean d = new AtomicBoolean(false);
		grpcConnect();

		Data data = Data.newBuilder().setId(id).build();

		FileDownloader stub = FileDownloader.newStub("channel");
		
		Path pathDestFolfer = Paths.get(updateRepoFolder);
	
		StreamObserver<File> respObserver = new StreamObserver<File>() {	
			Path f;
			String fileName = null;
			ByteSink byteFile = null;
			int i = 0;

			@Override
			public void onNext(File value) {
				
				LOGGER.info("Incoming File .... ");
				if (i == 0) {
					// if first time create file
					fileName = value.getName();
					try {
						f = Files.createFile(pathDestFolfer.resolve(fileName));
						byteFile = com.google.common.io.Files.asByteSink(f.toFile(), FileWriteMode.APPEND);
						byteFile.write(value.getBinary().toByteArray());
					} catch (IOException e) {
						e.printStackTrace();
					}
					i++;
				}else {
					// NOT FIRST TIME
					try {
						byteFile.write(value.getBinary().toByteArray());
					} catch (IOException e) {
						e.printStackTrace();
					}
				}
				
			}	

			@Override
			public void onError(Throwable t) {
				LOGGER.error("An error occured during downloading binary: " + t.getCause());
				grpcDisconnect();
			}

			@Override
			public void onCompleted() {
				LOGGER.info("download finished!");
				grpcDisconnect();
				//downloaded = true;
				d.set(true);
			}
		};
		if (Files.exists(pathDestFolfer)) {
			try {
				stub.downloadCore(ccm, respObserver);
				//downloaded = true;
			}catch (StatusRuntimeException  e) {
				LOGGER.error("RPC failed: {0}", e.getStatus());
				return d.get();
			}
		} else {
			LOGGER.error("repository not found");
		}
		while (d.get() != true) {
			// wait onCompleted called
			LOGGER.info("waiting ....");
                        // and do stuff
		}
		//grpcDisconnect();
		
		return d.get();
	}
```

**Comment by voidzcy** [comment]
Please provide us a fully reproducible example. 

Your server shouldn't be necessary to sleep between each call to `responseObserver.onNext(m)`. What do you mean by 
> on first iteration in client side, all chunks are sent without any control on flow .... 
?

Also, how do you know your client is stuck on writing the the `ByteSink`?

**Comment by zhangkun83** [comment]
The `StreamObserver` interface is non-blocking and doesn't provide back pressure for outbound data. In order to give the server the back pressure, you need to cast the `StreamObserver` that the server uses to send the data to `ServerCallStreamObserver`, and observe the "ready" bit. Something like this:
```java
public StreamObserver<Data> downloadCore(final StreamObserver<File> responseObserver) {
  ServerCallStreamObserver<File> serverCallStreamResponseObserver =
      (ServerCallStreamObserver<File>) responseObserver;
  serverCallStreamObserver.setOnReadyHandler(new Runnable() {
      public void run() {
        sendUntilNotReady(serverCallStreamResponseObserver);
      }
  });
  sendUntilNotReady(serverCallStreamResponseObserver);
}

private void sendUntilNotReady(ServerCallStreamObserver<File> serverCallStreamResponseObserver) {
  while (serverCallStreamResponseObserver.isReady()) {
    serverCallStreamResponseObserver.onNext(... /* next chunk */);
  }
}
```
