### ISSUE TITLE
Disabled tests in io.grpc.xds.sds.trust.SdsX509TrustManagerTest need to be re-enabled

### ISSUE THREAD

**Issue by sanjaypujare** [grpc/grpc-java#6274]
Many tests in io.grpc.xds.sds.trust.SdsX509TrustManagerTest read from files that fail with blaze (internal failure). Need to fix by using resources

**Comment by sanjaypujare** [comment]
#6273 disables the tests

**Comment by creamsoup** [comment]
resolved by #6281
