### ISSUE TITLE
Service Service cannot generate ServiceGrpc.java file

### ISSUE THREAD

**Issue by yuan-hy** [grpc/grpc-java#6282]
Hello, I would like to ask, my proto file definition is correct, I want to add the service RandomService in the service.proto of the benchmark module, but did not generate the RandomServiceGrpc.java file. Thank you！

**Comment by zhangkun83** [comment]
Assuming you added the "RandomService" to `benchmarks/src/main/proto/grpc/testing/services.proto`, if you run
```
./gradlew grpc-benchmarks:build
```
You should find `RandomServiceGrpc.java` under `benchmarks/build/generated/source/proto/main/grpc/io/grpc/benchmarks/proto/`
