### ISSUE TITLE
grpc-java android wear OS

### ISSUE THREAD

**Issue by cfmaley3** [grpc/grpc-java#6337]
I'm using grp-java in an android app and i have been asked to migrate the app for android wear OS.  Will grpc-java work on Android wear OS?

thanks

chris

**Comment by ran-su** [comment]
It should work. Based on my understanding of Wear OS. If the Wear OS device has wifi/cellular connection itself, it will directly talk to your server, if it's not the Wear OS will handle your request through the bluetooth connected cell phone.

**Comment by voidzcy** [comment]
From [this answer](https://support.google.com/wearos/thread/57130?msgid=59403), Android Wear is a platform on top of Android OS. So the connectivity monitoring should still come from Android OS. You should be able to migrate as apps running on normal Android.

**Comment by ran-su** [comment]
Closing. Can be reopen if there is any additional question.
