### ISSUE TITLE
INTERNAL: REJECTED_SEMAPHORE_EXECUTION 

### ISSUE THREAD

**Issue by welkinbai** [grpc/grpc-java#6353]
I got this error code.but I don't understand meaning of REJECTED_SEMAPHORE_EXECUTION 
Cloud you explain why my grpc client call got this code(REJECTED_SEMAPHORE_EXECUTION)? Thank you.

io.grpc.StatusRuntimeException: INTERNAL: REJECTED_SEMAPHORE_EXECUTION 
#011at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230) 
#011at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211) 
#011at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144) 

version:
java 8
grpc 1.0.3

**Comment by sanjaypujare** [comment]
Possibly this exception happened on the server side and returned to the client? Can you check on the server side (logs etc)?

**Comment by welkinbai** [comment]
yes, I found reason. Thanks
