### ISSUE TITLE
gRPC SSL / https support for Android application

### ISSUE THREAD

**Issue by anttilehtonen** [grpc/grpc-java#6374]
Is there any example related to building Android application that should communicate with https gRPC server?
I have managed to create C# application that successfully communicates with Node JS localhost server and credential code is:
 
                var caCert = ResourceLoader.GetEmbeddedResource("certificates/ca.crt");
                var clientCert = ResourceLoader.GetEmbeddedResource("certificates/client.crt");
                var clientKey = ResourceLoader.GetEmbeddedResource("certificates/client.key");
                var ssl = new SslCredentials(caCert, new KeyCertificatePair(clientCert, clientKey));
                // var ssl = new SslCredentials();

                ChannelCredentials credentials = aInSecure ? ChannelCredentials.Insecure : ssl;
                _channel = new Channel(aTargetAddress, credentials);
`
Server code is:

```
const cert_chain = [{
    cert_chain: fs.readFileSync('./server.crt'),
    private_key: fs.readFileSync('./server.key')
  }]
  const ssl_creds = grpc.ServerCredentials.createSsl(fs.readFileSync('./ca.crt'), cert_chain, true)
  const creds = SECURE ? ssl_creds : grpc.ServerCredentials.createInsecure()
  server.bind(`0.0.0.0:${port}`, creds);

```
In grpc-java side I have tried OkHttpChannelBuilder, AndroidChannelBuilder and NettyChannelBuilder but I have not found solution to make communication work yet.

**Comment by anttilehtonen** [comment]
I think my issue could be solved if I found out how @golil fixed his issue https://github.com/grpc/grpc-java/issues/5071

**Comment by ejona86** [comment]
You need to provide grpc with an `SSLSocketFactory` via `okHttpChannelBuilder.sslSocketFactory()`. For that, create a `SSLContext` and call `getSocketFactory()`. The `sslContext.init()` method is where you provide the client certificate (as a `KeyManager`) and the CA certificate (as a `TrustManager`). You'd need to create two `KeyStore`s (one for client cert/key, one for CA cert) and then `init()` the `KeyManagerFactory`/`TrustManagerFactory` with those key stores. There's other documentation online.

**Comment by anttilehtonen** [comment]
Thanks @ejona86 . I think I have been close trying like that but maybe I have missed something. I will try some more!
Maybe the error is related to creating client crt keystore with only client.crt like this:
`                InputStream certIS = resources.openRawResource(R.raw.client_crt);
                X509Certificate cert = (X509Certificate) cf.generateCertificate(certIS);
                ks.setCertificateEntry("client", cert);
`
Should I add the private key to same keystore?

**Comment by ejona86** [comment]
That looks roughly right. Except instead of using `setCertificateEntry()` for the client-certificate/key you should use `setKeyEntry()` where you pass both the key and cert; so yes, they both go in one keystore but as a single call. `setCertificateEntry()` is right for the ca certificate (on a second keystore).

**Comment by anttilehtonen** [comment]
Thank you @ejona86 . Now code compiles but it still does not quite work in emulator environment, maybe I am missing something. Below are the methods used in channel builder class. 

Server reports this kind of error that is quite new:
`
E1106 08:25:14.057000000  7452 ssl_transport_security.cc:1238] Handshake failed with fatal error SSL_ERROR_SSL: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN.
`

`

    private static byte[] getBytesFromInputStream(InputStream is) throws IOException {
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        byte[] buffer = new byte[0xFFFF];
        for (int len = is.read(buffer); len != -1; len = is.read(buffer)) {
            os.write(buffer, 0, len);
        }
        return os.toByteArray();
    }

    // build a key store from a set of raw certificates
    private static KeyStore createKeyStore(Resources resources, int certsId, boolean ca) {
        KeyStore ks = null;
        try {
            CertificateFactory cf = CertificateFactory.getInstance("X.509");
            if (ca) {
                ks = KeyStore.getInstance(KeyStore.getDefaultType());
                ks.load(null, null);
                InputStream certIS = resources.openRawResource(R.raw.ca_crt);
                X509Certificate cert = (X509Certificate) cf.generateCertificate(certIS);
                ks.setCertificateEntry("ca", cert);
            } else {
                ks = KeyStore.getInstance("AndroidKeyStore");
                ks.load(null, null);
                InputStream certIS = resources.openRawResource(R.raw.client_crt);
                Certificate cert = cf.generateCertificate(certIS);
                InputStream privateKeyIS = resources.openRawResource(R.raw.client_pkcs8);
                byte[] privateKeyBytes = RNGrpcChannelBuilder.getBytesFromInputStream(privateKeyIS);
                KeyFactory kf = KeyFactory.getInstance("RSA");
                PrivateKey privateKey = kf.generatePrivate(new PKCS8EncodedKeySpec(privateKeyBytes));
                Certificate[] certChain = new Certificate[1];
                certChain[0] = cert;
                ks.setKeyEntry("client", privateKey, null, certChain);
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return ks;
    }

    public static ManagedChannel build(String host, int port, Resources resources,
        @Nullable String serverHostOverride) {
        KeyStore ca = RNGrpcChannelBuilder.createKeyStore(resources, R.array.certs, true);
        KeyStore client = RNGrpcChannelBuilder.createKeyStore(resources, R.array.certs, false);
        OkHttpChannelBuilder channelBuilder =
            OkHttpChannelBuilder.forAddress(host, port);
        if (serverHostOverride != null) {
            // Force the hostname to match the cert the server uses.
            channelBuilder.overrideAuthority(serverHostOverride);
        }
        try {
            channelBuilder.negotiationType(io.grpc.okhttp.NegotiationType.TLS);
            channelBuilder.useTransportSecurity();
            channelBuilder.sslSocketFactory(getSslSocketFactory(ca, client));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        return channelBuilder.build();
    }

    private static SSLSocketFactory getSslSocketFactory(KeyStore ca, KeyStore client)
    throws Exception {
        KeyManagerFactory kmf =
            KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        String password = "";
        kmf.init(client, password.toCharArray());

        // initialize trust manager factor from certs keystore
        TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        tmf.init(ca);

        // initialize SSL context from trust manager factory
        SSLContext context = SSLContext.getInstance("TLS");
        context.init(kmf.getKeyManagers(), tmf.getTrustManagers(), new SecureRandom());

        // return socket factory from the SSL context
        return context.getSocketFactory();
    }


`

I have started to wonder if client could work without certificates and I would just be able to use code like:
`
channel = ManagedChannelBuilder.forAddress(host, port).build();
`
But would this require something from the server?

**Comment by ejona86** [comment]
SSLV3_ALERT_CERTIFICATE_UNKNOWN means the server failed the TLS connection due to _something_ wrong with the certificate. The code looks fair though.

Note that `channelBuilder.negotiationType(io.grpc.okhttp.NegotiationType.TLS);` is the same as `channelBuilder.useTransportSecurity();` and neither should be necessary since that is the default. (But I understand they were probably added when things were broken and you were just hoping they would help.)

**Comment by anttilehtonen** [comment]
Thanks again @ejona86 .
Good to know that I am almost there even if it does not work.
I use almost same certificates with C# client where they work.
The difference though is that certificates are created using CN=localhost .
Maybe I should add something to make it work with Android ( I know host is 10.0.2.2 ). 
Also I couldn't make key entry with client_key.key but I needed to convert it to pkcs8 format using command:

`openssl pkcs8 -topk8 -inform PEM -outform DER -in client_key.key -out client_pkcs8.key -nocrypt`

Here is server.cnf that is used in key generation:

``
[ req ]
distinguished_name = dn
req_extensions     = SAN

[ dn ]

[ SAN ]
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
IP.1 = 10.0.2.2`
``

And here is how certs are created in gen_certs.bat.
`set s="/C=FI/ST=Helsinki/L=Helsinki/O=Test/OU=Client/CN=localhost"
set ca="/C=FI/ST=Helsinki/L=Helsinki/O=Test/OU=Client/CN=ca"

openssl genrsa -passout pass:1111 -des3 -out ca_key.key 4096
openssl req -passin pass:1111 -new -x509 -days 365 -key ca_key.key -out ca_crt.crt -subj  %ca% -config server.cnf
echo Remove passphrase from ca key:
openssl rsa -passin pass:1111 -in ca_key.key -out ca_key.key

openssl genrsa -passout pass:1111 -des3 -out server_key.key 4096

openssl req -passin pass:1111 -new -key server_key.key -out server.csr -subj  %s% -config server.cnf

echo Self-sign server certificate:
openssl x509 -req -passin pass:1111 -days 365 -in server.csr -CA ca_crt.crt -CAkey ca_key.key -set_serial 01 -out server_crt.crt
echo Remove passphrase from server key:
openssl rsa -passin pass:1111 -in server_key.key -out server_key.key

openssl genrsa -passout pass:1111 -des3 -out client_key.key 4096
openssl req -passin pass:1111 -new -key client_key.key -out client.csr -subj  %s%
echo Self-sign client certificate:
openssl x509 -passin pass:1111 -req -days 365 -in client.csr -CA ca_crt.crt -CAkey ca_key.key -set_serial 02 -out client_crt.crt
echo Remove passphrase from client key:
openssl rsa -passin pass:1111 -in client_key.key -out client_key.key

openssl pkcs8 -topk8 -inform PEM -outform DER -in client_key.key -out client_pkcs8.key -nocrypt
`

**Comment by anttilehtonen** [comment]
I managed to make it work in localhost environment. I needed to sign client crt against server.cnf file so indeed it was due to Android emulator having 10.0.2.2 as IP address.

openssl x509 -passin pass:1111 -req -days 365 -in client.csr -CA ca_crt.crt -CAkey ca_key.key -set_serial 02 -out client_crt.crt -extensions SAN -extfile server.cnf

**Comment by hellokid1111** [comment]
> Thank you @ejona86 . Now code compiles but it still does not quite work in emulator environment, maybe I am missing something. Below are the methods used in channel builder class.
> 
> Server reports this kind of error that is quite new:
> `E1106 08:25:14.057000000 7452 ssl_transport_security.cc:1238] Handshake failed with fatal error SSL_ERROR_SSL: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN.`
> 
> `
> 
> ```
> private static byte[] getBytesFromInputStream(InputStream is) throws IOException {
>     ByteArrayOutputStream os = new ByteArrayOutputStream();
>     byte[] buffer = new byte[0xFFFF];
>     for (int len = is.read(buffer); len != -1; len = is.read(buffer)) {
>         os.write(buffer, 0, len);
>     }
>     return os.toByteArray();
> }
> 
> // build a key store from a set of raw certificates
> private static KeyStore createKeyStore(Resources resources, int certsId, boolean ca) {
>     KeyStore ks = null;
>     try {
>         CertificateFactory cf = CertificateFactory.getInstance("X.509");
>         if (ca) {
>             ks = KeyStore.getInstance(KeyStore.getDefaultType());
>             ks.load(null, null);
>             InputStream certIS = resources.openRawResource(R.raw.ca_crt);
>             X509Certificate cert = (X509Certificate) cf.generateCertificate(certIS);
>             ks.setCertificateEntry("ca", cert);
>         } else {
>             ks = KeyStore.getInstance("AndroidKeyStore");
>             ks.load(null, null);
>             InputStream certIS = resources.openRawResource(R.raw.client_crt);
>             Certificate cert = cf.generateCertificate(certIS);
>             InputStream privateKeyIS = resources.openRawResource(R.raw.client_pkcs8);
>             byte[] privateKeyBytes = RNGrpcChannelBuilder.getBytesFromInputStream(privateKeyIS);
>             KeyFactory kf = KeyFactory.getInstance("RSA");
>             PrivateKey privateKey = kf.generatePrivate(new PKCS8EncodedKeySpec(privateKeyBytes));
>             Certificate[] certChain = new Certificate[1];
>             certChain[0] = cert;
>             ks.setKeyEntry("client", privateKey, null, certChain);
>         }
>     } catch (Exception e) {
>         throw new RuntimeException(e);
>     }
>     return ks;
> }
> 
> public static ManagedChannel build(String host, int port, Resources resources,
>     @Nullable String serverHostOverride) {
>     KeyStore ca = RNGrpcChannelBuilder.createKeyStore(resources, R.array.certs, true);
>     KeyStore client = RNGrpcChannelBuilder.createKeyStore(resources, R.array.certs, false);
>     OkHttpChannelBuilder channelBuilder =
>         OkHttpChannelBuilder.forAddress(host, port);
>     if (serverHostOverride != null) {
>         // Force the hostname to match the cert the server uses.
>         channelBuilder.overrideAuthority(serverHostOverride);
>     }
>     try {
>         channelBuilder.negotiationType(io.grpc.okhttp.NegotiationType.TLS);
>         channelBuilder.useTransportSecurity();
>         channelBuilder.sslSocketFactory(getSslSocketFactory(ca, client));
>     } catch (Exception e) {
>         throw new RuntimeException(e);
>     }
>     return channelBuilder.build();
> }
> 
> private static SSLSocketFactory getSslSocketFactory(KeyStore ca, KeyStore client)
> throws Exception {
>     KeyManagerFactory kmf =
>         KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
>     String password = "";
>     kmf.init(client, password.toCharArray());
> 
>     // initialize trust manager factor from certs keystore
>     TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
>     tmf.init(ca);
> 
>     // initialize SSL context from trust manager factory
>     SSLContext context = SSLContext.getInstance("TLS");
>     context.init(kmf.getKeyManagers(), tmf.getTrustManagers(), new SecureRandom());
> 
>     // return socket factory from the SSL context
>     return context.getSocketFactory();
> }
> ```
> 
> `
> 
> I have started to wonder if client could work without certificates and I would just be able to use code like:
> `channel = ManagedChannelBuilder.forAddress(host, port).build();`
> But would this require something from the server?

Can you please explain the 
```java
if (serverHostOverride != null) {
        // Force the hostname to match the cert the server uses.
        channelBuilder.overrideAuthority(serverHostOverride);
    }
```
part? i dont quite understand what is the serverHostOverride

**Comment by ejona86** [comment]
Lots of time with a test certificate it will use a "fake" hostname and you may contact the server via an IP address or similar. overrideAuthority lets you use the server's "real" hostname (say, "localhost") or IP in the `forAddress()` to use to connect but then set the certificate's "hostname" in `overrideAuthority`. It is an alternative to disabling hostname verification.
