### ISSUE TITLE
gRPC client to use a proxy server with traffic between the client and proxy server encrypted as well

### ISSUE THREAD

**Issue by patsonluk** [grpc/grpc-java#6399]
### Is your feature request related to a problem?
As implemented in #5173, we could call `ManagedChannelBuilder.proxyDetector` to specify a custom `ProxyDetector` that returns a `ProxiedSocketAddress`.

The current concrete class `HttpConnectProxiedSocketAddress` contains `proxyAddress`, `targetAddress`, `username` and `password` and does NOT specify whether the traffic between the gRPC client and proxy server be encrypted or not.

By tracing through the code and the calls in netty, it appears that the traffic between gRPC client and the proxy server is NOT encrypted, though via `HTTP CONNECT` the gRPC client and the destination server DO established a secured channel.

As described in [here](https://security.stackexchange.com/questions/61334/does-an-https-proxy-encrypt-traffic-between-proxy-client-and-server-for-http-req/61336#61336), there are 2 things about `https proxying`:
1. a proxy which knows the "CONNECT" verb and is able to forward connections to a ultimate SSL-powered target server;
2. a proxy which is itself a SSL server and will engage in SSL with the client, to protect requests and responses when they transit between client and proxy.

So it appears that gRPC currently support the point 1. but have no support for point 2.?

### Describe the solution you'd like
Ideally we should be able to specify the proxy server as a URL (or some way to indicate whether the client and the proxy should have traffic encrypted between them) instead of just a socket address with no protocol attachment. 

Then the code logic should perform proper handshake as shown in the Go lang example - which supports a proxy server URL, which has a protocol part `http` vs `https` for the proxy server as well (not just the destination), and it performs proper TLS handshakes between the client and the server as seen in [here](https://github.com/golang/go/blob/2566e21f243387156e8e7f2acad0ce14d9712bbc/src/net/http/transport.go#L1438)

### Describe alternatives you've considered
I must admit that I am not a networking expert and I have mostly been just looking into netty/grpc/java code to see what options can we have out there from code level.

I am not sure if I can configure netty directly to achieve my goal, netty implemented [HttpProxyHandler](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/HttpProxyHandler.java) which gRPC client code eventually triggers, but unfortunately from my understanding, that HttpProxyHandler does not encrypt traffic between the gRPC client and proxy server neither.

I do not see any trivial alternatives, please help :)

### Additional context
Is gRPC intended to use `https`/handshake with the proxy server too ? (not just the destination server). As based on the code in [here](https://github.com/idelvall/grpc-java/blob/da6c6dd788124a9dca77f86bef48863658dcbf47/core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java#L250) and the comment in [here](https://github.com/idelvall/grpc-java/blob/da6c6dd788124a9dca77f86bef48863658dcbf47/core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java#L162), it might want to support it? But again, I am quite new to all these so I could just be misreading the details.

Many thanks in advance!!

**Comment by ejona86** [comment]
There can be quite a bit of confusion between what all the http vs https stuff means. It can be whether TLS is used to the backend, it can imply the HTTP proxy protocol (e.g., CONNECT), and it can also be whether TLS is used to the proxy.

gRPC does not currently support using TLS when talking to the proxy. This is normally not much of a problem because it only leaks the Proxy-Authentication header that is used when establishing the connection.

gRPC does not support TLS to the proxy because most systems didn't seem to support it. For example, Java itself does not support using TLS to connect to the proxy nor do web browsers (to my knowledge).

**Comment by ejona86** [comment]
Closing since no response.
