### ISSUE TITLE
Have grpc-protobuf-lite depend on protobuf-javalite, not protobuf-lite

### ISSUE THREAD

**Issue by bubenheimer** [grpc/grpc-java#6405]
### What version of gRPC-Java are you using?
1.25.0, 1.24.2

### What did you expect to see?
My understanding is that with more recent protobuf versions the Java Lite code generation requires a different approach and is compatible with com.google.protobuf:protobuf-javalite artifacts as opposed to the old com.google.protobuf:protobuf-lite:3.0.1 artifacts. The current grpc-protobuf-lite still depends on the old com.google.protobuf:protobuf-lite:3.0.1, yet the current grpc artifacts generally use recent protobuf versions. I expected to see a dependency on the new protobuf-javalite artifact instead. Or would a new grpc-protobuf-javalite artifact be more appropriate?

**Comment by ejona86** [comment]
This is more a question of when will grpc upgrade to depend on the newer javalite version. Already if using javalite you need to make sure your protoc (plugin) version matches the .jar version; 3.9 generated code is not guaranteed compatible with 3.10 runtime. It is true today that you need to exclude the protobuf-javalite dependency if using a newer version, but grpc-protobuf-lite itself is okay with either dependency.

I've been watching javalite to determine an appropriate time to bump the version. I've spoken to protobuf team about its current state as well. I got really close to swapping for 3.10, but I was waiting for some issues to be ironed out. For example, I was expecting some documentation to resolve https://github.com/protocolbuffers/protobuf/issues/6565. I was mainly wanting to avoid pushing people to the new version while it was a rocky road.

But it'd be really easy to update the version when things are ready.

**Comment by bubenheimer** [comment]
Thank you for the explanation and additional pointers, I had been doubtful that excluding the dependency would suffice. I successfully went to grpc 1.25.0 from 1.21.0 in my builds now after the long-standing blocker https://github.com/grpc/grpc-java/issues/6217 was resolved.

**Comment by ejona86** [comment]
Based on https://github.com/protocolbuffers/protobuf/issues/6867, it seems #6565 is no longer an issue, although the issue is still open. We could upgrade.
