### ISSUE TITLE
I made a "gzip request" to server ,but there isn't a "gzip response" to be returned.

### ISSUE THREAD

**Issue by luoyexiaohe** [grpc/grpc-java#6406]
I use java to had a "gzip request" to server ,the code is list:
stub.withCompression("gzip");
but the response i had is not a "gzip response".
I readed the others Issues that I found one whitch means ,it needn't a "gzip response" to be sent for a client use gzip to had a request . So , what should I do to right my options ? I want a "gzip resopnse" to be sent for a "gzip request" ?
thank you.

**Comment by sanjaypujare** [comment]
Check the doc https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withCompression-java.lang.String- which says 

> this is the compressor used by the stub to compress messages to the server. To get compressed responses from the server, set the appropriate DecompressorRegistry on the ManagedChannelBuilder.

On the server side use [`compressorRegistry`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerBuilder.html#compressorRegistry-io.grpc.CompressorRegistry-).

**Comment by luoyexiaohe** [comment]
> Check the doc https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withCompression-java.lang.String- which says
> 
> > this is the compressor used by the stub to compress messages to the server. To get compressed responses from the server, set the appropriate DecompressorRegistry on the ManagedChannelBuilder.
> 
> On the server side use [`compressorRegistry`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerBuilder.html#compressorRegistry-io.grpc.CompressorRegistry-).

thank  you ,sir. what should I do to sure it is a "gzip request" ?

**Comment by sanjaypujare** [comment]
> thank you ,sir. what should I do to sure it is a "gzip request" ?

I thought you got the request compressed with "gzip" and your issue was with responses which is where the 2 links I gave would be useful.

**Comment by luoyexiaohe** [comment]
> > thank you ,sir. what should I do to sure it is a "gzip request" ?
> 
> I thought you got the request compressed with "gzip" and your issue was with responses which is where the 2 links I gave would be useful.

thanks
