### ISSUE TITLE
2 way SSL with Grpc and netty [Android]

### ISSUE THREAD

**Issue by hellokid1111** [grpc/grpc-java#6412]
(using grpc version 1.24.0 and nettychannelbuilder)
I have looked at this [issue](https://github.com/grpc/grpc-java/issues/5761) and used the code provided by @voidzcy in the example, but i have encoutered a problem regarding my device not being able to detect my certificates who are under the "raw" fodler, and i got this error:
" Caused by: java.security.cert.CertificateException: could not find certificate file: server.pem"
i then tried to add my own Sslcontext, but couldnt figure out how to make it 2 way ssl (server certificate, client certificate, and client key), with Grpc.

Update:
I have used:
```java
SslContext sslContext = GrpcSslContexts.forClient().trustManager(getResources().openRawResource(R.raw.server)).keyManager(getResources().openRawResource(R.raw.client), getResources().openRawResource(R.raw.key)).build();
```
while having the files server.crt client.crt and key.key in my "raw" folder, but i get this error now:
"io.grpc.StatusRuntimeException: UNKNOWN: Channel Pipeline: [WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]"

Update: 
I have checked the stack trace and it says :
"java.lang.RuntimeException: ALPN unsupported. Is your classpath configured correctly? For Conscrypt, add the appropriate Conscrypt JAR to classpath and set the security provider. For Jetty-ALPN, see http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting"
But at the begging of my activity i wrote 
```java
Security.insertProviderAt(Conscrypt.newProvider(), 1);
```
and added "classpath 'com.google.gradle:osdetector-gradle-plugin:1.4.0'" to my classpath in gradle
I also tried usuing Play Services Dynamic Security Provider and still the same error occurs.

**Comment by dapengzhang0** [comment]
It seems Conscrypt is not usable for Netty in Android https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/Conscrypt.java#L59

I'm curious why do you decide to use netty rather than okhttp in Android?

**Comment by hellokid1111** [comment]
@dapengzhang0 I am using netty over okhttp, because im not getting the data from an http source, but rather straight from my local server i implemented in my other pc, another reason is, because i haven't found a way to implement a 2 way ssl with okhttp, where netty has a little more documentation.

**Comment by hellokid1111** [comment]
Say i switch to okhttp, how do i implement the 2 way ssl with the files i stated above?
and ty for replying this quick.

**Comment by dapengzhang0** [comment]
>Say i switch to okhttp, how do i implement the 2 way ssl with the files i stated above?

For 2 way ssl using okhttp, would the discussions in https://github.com/grpc/grpc-java/issues/3887 help?

**Comment by ejona86** [comment]
See also https://github.com/grpc/grpc-java/issues/6374

**Comment by hellokid1111** [comment]
> > Say i switch to okhttp, how do i implement the 2 way ssl with the files i stated above?
> 
> For 2 way ssl using okhttp, would the discussions in #3887 help?

This doesnt seem to be a 2 way ssl, maybe im missing something ?
Cant seem to see the code in which you enter the key provided beforehand by the server.
From what i understand, i can use the SslContext i built as so
```java
SslContext sslContext = GrpcSslContexts.forClient().trustManager(getResources().openRawResource(R.raw.server)).keyManager(getResources().openRawResource(R.raw.client), getResources().openRawResource(R.raw.key)).build();
```
and then call "getSocketFactory()" is that correct?
Sorry i just cant seem to understand how to set the 3 files in my device.

**Comment by voidzcy** [comment]
```java
SslContextBuilder builder = GrpcSslContexts.forClient();
if (trustCertCollectionFilePath != null) {
  builder.trustManager(new File(trustCertCollectionFilePath));
}
if (clientCertChainFilePath != null && clientPrivateKeyFilePath != null) {
  builder.keyManager(new File(clientCertChainFilePath), new File(clientPrivateKeyFilePath));
}
```

Is this what you are looking for?

**Comment by dapengzhang0** [comment]
@hellokid1111 I don't quest understand what you meant by "build the 3 files into that SSLContext".
Just copying the 3 files as a raw resource file in `res/raw/` directory does not work for you?

**Comment by hellokid1111** [comment]
> @hellokid1111 I don't quest understand what you meant by "build the 3 files into that SSLContext".
> Just copying the 3 files as raw resources file in `res/raw/` directory does not work for you?

What i mean is, I have 3 files i got from the sever, the server certificate (self signed), the client certificate (so the server can authorize the client), and the client key.
From reading the responses in this thread, I saw the best practice is to create an SSLcontext and then pass it to OkHttpchannelbuilder, so it will do the 3 way SSL for me.
I cant seem to find the code for doing so (using the 3 files I stated above).

**Comment by hellokid1111** [comment]
> ```java
> SslContextBuilder builder = GrpcSslContexts.forClient();
> if (trustCertCollectionFilePath != null) {
>   builder.trustManager(new File(trustCertCollectionFilePath));
> }
> if (clientCertChainFilePath != null && clientPrivateKeyFilePath != null) {
>   builder.keyManager(new File(clientCertChainFilePath), new File(clientPrivateKeyFilePath));
> }
> ```
> 
> Is this what you are looking for?
> 
> Edit: Oops, that's for Netty. For Android, have you tried the approach in [TesterOkHttpChannelBuilder](https://github.com/grpc/grpc-java/blob/master/android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java)?

Hey, ty for answearing, this is correct for netty, and from what I saw here I should start using okHttp as stated by @dapengzhang0 , the code you provided, i cant seem to understand where do you initialize the 3 files there ( i can only see you using the server certificate there, but not the client certificate and client key, if you have an example like the one you provided, but for okHttp channelbuilder i'd really appericiate it, thanks (if im wrong and the code you provided will actually work for the 3 files, id like to hear an exaplnation as to why ).
Btw even if im not using Http i should still use Okhttp over netty?

**Comment by voidzcy** [comment]
You would need to create a keystore file from your certs and keys (via `keytool` or `openssl`), and then use that for `KeyManagerFactory` and `TrustManagerFactory`.

```java
KeyManagerFactory keyManagerFactory =
    KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
keyManagerFactory.init(keystore, password.toCharArray());

TrustManagerFactory trustManagerFactory =
    TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
trustManagerFactory.init(keystore);

SSLContext sslContext = SSLContext.getInstance("TLS");
sslContext.init(
    keyManagerFactory.getKeyManagers(),
    trustManagerFactory.getTrustManagers(),
    new SecureRandom());
```

**Comment by hellokid1111** [comment]
> You would need to create a keystore file from your certs and keys (via `keytool` or `openssl`), and then use that for `KeyManagerFactory` and `TrustManagerFactory`.
> 
> ```java
> KeyManagerFactory keyManagerFactory =
>     KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
> keyManagerFactory.init(keystore, password.toCharArray());
> 
> TrustManagerFactory trustManagerFactory =
>     TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
> trustManagerFactory.init(keystore);
> 
> SSLContext sslContext = SSLContext.getInstance("TLS");
> sslContext.init(
>     keyManagerFactory.getKeyManagers(),
>     trustManagerFactory.getTrustManagers(),
>     new SecureRandom());
> ```
Thanks for answearing again !
How exactly do i create the keystores files and keys? 
Do you have an article/guide on how to do so? 
Sorry im new to SSL.

**Comment by voidzcy** [comment]
You can either do that with `keytool` or `openssl` command as mentioned in [this guide](http://xacmlinfo.org/2014/06/13/how-to-keystore-creating-jks-file-from-existing-private-key-and-certificate/). Or you can do it programmatically in Java with [code like this](https://github.com/grpc/grpc-java/issues/6374#issuecomment-550166965). Please read #6374, there is plenty of information there.

**Comment by hellokid1111** [comment]
Ill try it, thank you ! ill report if i encounter any problem !

> You can either do that with `keytool` or `openssl` command as mentioned in [this guide](http://xacmlinfo.org/2014/06/13/how-to-keystore-creating-jks-file-from-existing-private-key-and-certificate/). Or you can do it programmatically in Java with [code like this](https://github.com/grpc/grpc-java/issues/6374#issuecomment-550166965). Please read #6374, there is plenty of information there.

**Comment by hellokid1111** [comment]
I have tried reading and using the Issue you suggested and encountered [this] (https://github.com/grpc/grpc-java/issues/6374#issuecomment-553769393)

**Comment by dapengzhang0** [comment]
Similar question found in https://stackoverflow.com/questions/58751708/creating-a-2-ways-ssl-handshake-tls-using-grpc-in-android-client

**Comment by alyosha** [comment]
know you guys probably have a crazy backlog but an example using `okhttp` in the `example-tls` directory would be nice

**Comment by voidzcy** [comment]
> know you guys probably have a crazy backlog but an example using `okhttp` in the `example-tls` directory would be nice

Using TLS for `okhttp` is essentially the same from gRPC's perspective. The only pain is we (and okhttp) do not provide a utility for building a custom `SSLContext`, which involves reading certificate and private key PEM files, creating `KeyStore`, etc. Doing these steps by hand is non-trivial, but there are plenty of resources online for references.

**Comment by ejona86** [comment]
This seems responded to. If there's more discussion that needs to happen comment and we can reopen.

**Comment by namgk** [comment]
Hi there,

I'm looking at the approach here:

https://github.com/grpc/grpc-java/blob/master/android-interop-testing/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java

I'm wondering how to do this in Android? What are the gradle dependencies that let me to import these classes?

```
import io.grpc.ChannelCredentials;
import io.grpc.Grpc;
import io.grpc.InsecureChannelCredentials;
```

**Comment by voidzcy** [comment]
Those are recent changes that have not been released yet. Please look at [version 1.32.0](https://github.com/grpc/grpc-java/blob/v1.32.2/android-interop-testing/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java).
