### ISSUE TITLE
Build grpc-all fat jar after making changes

### ISSUE THREAD

**Issue by ankitshubham97** [grpc/grpc-java#6418]
I am trying to build a fat jar of grpc-all for version 1.22.1. I am able to do it by executing the following gradle script:
```
repositories {
    mavenCentral()
}

// Plugin to enable all java related tasks in gradle.
apply plugin: 'java'

// Base name of jar file.
archivesBaseName = 'grpc-all-1.22.1'

def LIB_DIR = "/home/ankit/software/build"

task makeLibDir() {
  def libDir = new File(LIB_DIR)
  outputs.dir libDir
  doFirst {
    if (!libDir.exists()) {
      libDir.mkdirs()
    }
  }
}

clean {
  delete "$LIB_DIR/$archivesBaseName" + ".jar"
}

jar {
  destinationDir = file(LIB_DIR)
  from {
    (configurations.runtime).collect {
      it.isDirectory() ? it : zipTree(it)
    }
  }
}

// Task dependencies.
jar.dependsOn makeLibDir

configurations.all {
  exclude group: 'com.google.protobuf', module: 'protobuf-java'
}

// Add all the dependencies here that should be included in fat jar file.
dependencies {
  compile group: 'io.grpc', name: 'grpc-all', version: '1.22.1'
}
```
This actuallly builds the fat jar from the remote maven repository. I want this:

Make some code changes in the grpc java (https://github.com/grpc/grpc-java), branch v1.22.1 and then build uber jar reflecting those changes. How can this be done? I have already cloned https://github.com/grpc/grpc-java to my local machine at /home/ankit/grpc-java

**Comment by dapengzhang0** [comment]
You need build grpc-java library in maven local, and modify you /home/ankit/software/build.gradle file

```gradle
repositories {
    mavenLocal() // add this before any other repo
    mavenCentral()
}
...
```

After editing, run the commands:
```sh
cd /home/ankit/grpc-java
git checkout v1.22.1
# make your change, then
# build grpc-java library in maven local.
./gradlew publishMavenPublicationToMavenLocal

# build fat jar
cd /home/ankit/software
./gradlew jar
```

**Comment by ankitshubham97** [comment]
@dapengzhang0 Thank you! It worked. Just to add a note for other people who come here: If you are looking to build 1.13.x, then use `./gradlew install` instead of` ./gradlew publishMavenPublicationToMavenLocal`
