### ISSUE TITLE
what would happen if my service is printing this log : io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!    

### ISSUE THREAD

**Issue by Zhuliuer666** [grpc/grpc-java#6422]
_My service is printing this error:_
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug! 
Caused by: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

according to the log , I have increased my jvm config:  xms from 502m to 1024m, xmx from 1024m to 4096m, this exception log is going away from my service.

**My question is : how to reproduce this exception in other environment. and what  thing would be caused by this error log (like the service is down or something else), as  we didn't find any service down accident and didn't receive any error report from out client. especially cannot reproduce this ,even with loadtest
Can someone help answer my question?**

**Comment by dapengzhang0** [comment]
This seems an open question. You might want to use some java profiling tool to see what part of your application is consuming too much memory first.

**Comment by Zhuliuer666** [comment]
@dapengzhang0  but I cannot reproduce this exception at my local, so I don't know how to debug the memory usage.

I want to know if this exception would terminate my service or is this just a reminder.

**Comment by dapengzhang0** [comment]
The root cause is memory exhausted, not a grpc problem. It just happened to fail at grpc stack. Next time when the memory is exhausted, it could fail at any other random place.
