### ISSUE TITLE
How to throttling in server-side (not the manual flow control version)?

### ISSUE THREAD

**Issue by liujiawinds** [grpc/grpc-java#6426]
I'm wondering how you guys to deal with the problem which the client-side's produce rate is greater than the server-side's consume rate.

In my case, that lead to a OOM eventually.

Is there a simple way to implement a throttling in server-side when I can't change the client-side's code.

Here is a [issue](https://github.com/yidongnan/grpc-spring-boot-starter/issues/298) I raised at another repo.

**Comment by dapengzhang0** [comment]
What type of RPC is of your concern? Only unary RPC or it could be client side streaming?

**Comment by dapengzhang0** [comment]
You can
- use `NettyServerBuilder.maxConcurrentCallsPerConnection` to limit concurrent calls

- slow down to respond so that each request takes a little longer to get response.

**Comment by liujiawinds** [comment]
I'm using bidi streaming. 
Manual flow control, I think it will be much slower that normal streaming for the extra communications.

So I choose a work around that throttling the in the client-size with a semaphore.

**Comment by liujiawinds** [comment]
By the way, I'm wondering why default http2 flow control window is not working. 
Is it a connection scope parameter ?

@dapengzhang0

**Comment by dapengzhang0** [comment]
@liujiawinds That is not connection scope, it is stream/request scope, not for back pressure coming from high QPS.

>By the way, I'm wondering why default http2 flow control window is not working.
Is it a connection scope parameter ?

**Comment by h4yin** [comment]
> @liujiawinds That is not connection scope, it is stream/request scope, not for back pressure coming from high QPS.
> 
> > By the way, I'm wondering why default http2 flow control window is not working.
> > Is it a connection scope parameter ?

@dapengzhang0 
Not explain why the http2 flow control doesn't work.
Or would you explain why not for high QPS. 
Many thx.
