### ISSUE TITLE
Grpc over Bluetooth RfComm ?

### ISSUE THREAD

**Issue by jishindev** [grpc/grpc-java#6427]
I was wondering if it was possible to use grpc over bluetooth to connect two devices? I tried using the bluetooth device mac id as the host but that clearly doesn't appear to work. 

Using this - 
``` 
val controlChannel = AndroidChannelBuilder.forAddress(remoteDevice.address, 1)
                    .usePlaintext().build()
```
Gives -
```
java.lang.IllegalArgumentException: Invalid host or port: DD:A6:72:CF:14:1D 1
     at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:481)
Caused by: java.net.URISyntaxException: IPv6 address too short at index 3: //[DD:A6:72:CF:14:1D]:1
```

**Comment by kptlronyttcna** [comment]
I'm also interested in this.

**Comment by ran-su** [comment]
The way I can think of to achieve this is have a proxy that re-route the connection through bluetooth. I know that WearOS has one of this proxy, but I don't think it is open sourced.

**Comment by dapengzhang0** [comment]
I'm not familiar with bluetooth RfComm, but AndroidChannel only supports HTTP/2 over TCP over standard address, if the `remoteDevice.address` is not a TCP endpoint with a standard address that the bluetooth service is converted to, it won't work.

**Comment by sanjaypujare** [comment]
I am not familiar with RfComm on Android either but looking at [BluetoothSocket](https://developer.android.com/reference/android/bluetooth/BluetoothSocket.html) and [BluetoothServerSocket](https://developer.android.com/reference/android/bluetooth/BluetoothServerSocket.html) and creating these for [RfComm](https://developer.android.com/reference/android/bluetooth/BluetoothDevice.html#createRfcommSocketToServiceRecord(java.util.UUID)), it looks like supporting the Bluetooth transport might not be that difficult.

**Comment by jishindev** [comment]
Thanks @sanjaypujare and others for the response.
Could you may be give any pointers on how we can achieve this ?

**Comment by sanjaypujare** [comment]
This would involve enhancing `io.grpc.okhttp.OkHttpChannelBuilder` (specifically `io.grpc.okhttp.OkHttpChannelBuilder.OkHttpTransportFactory`) and possibly `io.grpc.android.AndroidChannelBuilder` to add support for BluetoothSocket since they supposedly behave like a regular network socket.

To correct my earlier statement, I don't know how difficult or easy this will be.

**Comment by peterwangpd** [comment]
Looks we met the same situation. Is it also feasible to use BluetoothServerSocket with NettyChannelBuilder? Thanks very much!

**Comment by jishindev** [comment]
@peterwangpd , As @dapengzhang0 mentioned 

> AndroidChannel only supports HTTP/2 over TCP over standard address, if the remoteDevice.address is not a TCP endpoint with a standard address that the bluetooth service is converted to, it won't work.

So had to go with Protobuf serialization over Socket IO streams and custom routing until BluetoothSocket support is added.

**Comment by ejona86** [comment]
I not sure we will add native bluetooth support. But there may be other options.

It looks like you can use [`OkHttpChannelBuilder.socketFactory()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html#socketFactory-javax.net.SocketFactory-) and just provide an implementation that uses RfComm. Your factory will probably ignore the host/address. Or maybe you just encode the mac in the host/address. But doh, BluetoothSocket doesn't actually implement Socket, so you'd need to make an adapter.

Netty really wants nio Channels. There is OioSocketChannel though. You would need to implement a ChannelFactory (pass to grpc [via the builder](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#channelFactory-io.netty.channel.ChannelFactory-)) that calls `new OioSocketChannel(socket)`. It would need the same Socket adapter as client-side.

**Comment by ejona86** [comment]
Since bluetooth support really needs a server on Android as well, and we don't support Netty on Android (even if it may happen to work), I think it is probably best to close this.

If we had a server on Android, we'd probably be able to accept a contribution to add RfComm support in `grpc-android` or some such (using the approach I outlined before). It is pretty annoying that `RfComm` isn't a socket, though.
