### ISSUE TITLE
How to get the  server address when call complete?

### ISSUE THREAD

**Issue by CodingSinger** [grpc/grpc-java#6428]
Hello, everyone,
I'm first use grpc-java, how can i get the server address when client complete one request if success or not?
i want statistics the error count of every server.
can anyone help me? 
thanks

**Comment by CodingSinger** [comment]
i try to use the clientInterceptor, but i can't kown how to fetch  the address.

**Comment by dapengzhang0** [comment]
You can use 
```java
clientCall.getAttributes().get(Grpc.TRANSPORT_ATTR_REMOTE_ADDR)
```

after a response is received in clientInterceptor.

**Comment by dapengzhang0** [comment]
Did the request reach the server? If no connection was established, it could be null. Also, if you read the attribute from a different thread, you need proper synchronization otherwise you may read a null value.

**Comment by CodingSinger** [comment]
yes, I'm sure the client get the correct response from server and it doesn't get the the attribute from a different thread also. 
But I try `server.getAttributes().get(Grpc.TRANSPORT_ATTR_REMOTE_ADDR) `on ServerInterceptor,it works well.

**Comment by dapengzhang0** [comment]
I tried the client side using client interceptor and `clientCall.getAttributes().get(Grpc.TRANSPORT_ATTR_REMOTE_ADDR)`, and found it works for both Netty and OkHttp transports. (Only `InProcessTransport` is not working .This feature was not implemented for inprocess transport yet). If you still have problem, can you share your code for your interceptor and getting the attributes?

**Comment by dapengzhang0** [comment]
Close due to inactivity.
