### ISSUE TITLE
why client  send data failed when server invoke the onComplete?

### ISSUE THREAD

**Issue by CodingSinger** [grpc/grpc-java#6432]
Consider the following gRPC scenario:

1. Client opens bidi-stream to server and starts sending data
2. Server invoke the onComplete ,so closes the response stream and sends the status trailers (translates to sending http2.END_STREAM)
3. Client continues to send data

if follow the http2-spec,the client is allowed to continue to send data that is processed by the server.But I just tested and the client invoke onNext to send data will throw the exception and log
`call was half-closed`.

how to explain this case?

**Comment by dapengzhang0** [comment]
When grpc server invokes onComplete, the http2 stream is closed. Any data the client tries to send after that will not be sent because the stream is already closed.
