### ISSUE TITLE
The grpc-cronet Android library build produces an empty aar

### ISSUE THREAD

**Issue by MaartenR** [grpc/grpc-java#6447]
### What version of gRPC-Java are you using?

1.25.0

### What is your environment?

Android
Target/compile SDK version is 28.

### What did you expect to see?

I expected to be able to use the `CronetChannelBuilder` class, but I wasn't.

### What did you see instead?

Upon opening the aar file downloaded from [maven central](https://mvnrepository.com/artifact/io.grpc/grpc-cronet/1.25.0) I noticed there were no classes included and the file has a size of 543 bytes.

### Steps to reproduce the bug

Running the grpc-cronet build with gradlew produces an aar that is practically empty.

As far as I can tell the line `minifyEnabled true` in the release build causes all Java classes to be left out of the final aar. Because this is a library and there is no entry point all code is considered dead. I also think `proguardFiles` should be replaced with `consumerProguardFiles` in the release build configuration for an Android library.

When running into this issue we started to doubt whether grpc-cronet was actually meant to be released on maven central yet. It is however recommended to use cronet for gRPC on Android [here](https://developer.android.com/guide/topics/connectivity/grpc).

Am I missing something here? I couldn't really believe grpc-cronet has had 4 releases published to maven central, the first almost two months ago, with the actual product being in an unusable state.

**Comment by voidzcy** [comment]
Thanks for reporting this. We've created #6448 to fix it.
