### ISSUE TITLE
Cannot find symbol makeImmutable() and isMutable() at compile time

### ISSUE THREAD

**Issue by andremann** [grpc/grpc-java#645]
Hi,

I tried to compile my proto with Maven using the configuration reported in the how-to:
```
      <configuration>
        <protocArtifact>com.google.protobuf:protoc:3.0.0-alpha-3.1:exe:${os.detected.classifier}</protocArtifact>
        <pluginId>grpc-java</pluginId>
        <pluginArtifact>io.grpc:protoc-gen-grpc-java:0.7.1:exe:${os.detected.classifier}</pluginArtifact>
      </configuration>
```
However I managed to get it work only changing to alpha-2
```
<protocArtifact>com.google.protobuf:protoc:3.0.0-alpha-2:exe:${os.detected.classifier}</protocArtifact>
```

**Comment by ejona86** [comment]
@zhangkun83.

I think we accidentally prematurely updated the documentation to suggest using the newer protoc, since our protoc plugin appears like it was compiled with alpha 2.

**Comment by zhangkun83** [comment]
Presumably these errors are from java compilation. It's more like that the protoc version mismatches the protobuf runtime. Are you using the same version of protobuf?

**Comment by ejona86** [comment]
@zhangkun83, given our documentation, he most likely pulled in proto as a transitive dependency, so it is probably alpha 2 of the runtime. I think our current documentation would be encouraging such a mismatch.

**Comment by andremann** [comment]
Right. From Maven I import `io.grpc:grpc-all:0.7.1` which in turns happens to pull protobuf alpha-2 (just noticed in mvn dependencies hierarchy)
