### ISSUE TITLE
using gRPC 1.25.0 cause epoll io pending tasks increased to several hundred

### ISSUE THREAD

**Issue by nicklaus4** [grpc/grpc-java#6461]
using gRPC 1.25.0 cause epoll io pending tasks increased from less than 10 to several hundred

i see netty 4.1.42 refine the epoll impl，cound it be a reason to interpret this..there is no further informations

**Comment by creamsoup** [comment]
for 1.25.0 release we didn't change anything possibly impact epoll other than the netty version bump. it is probably related to one of the epoll optimization on netty side as you pointed out. few changes (possibly the rescheduling change) could affect the behavior you described. 
Are you seeing any performance impact?

**Comment by njhill** [comment]
@nicklaus4 would you be able to try with netty 4.1.43.Final? The easiest way to do this is by using `netty-bom` since grpc-java uses a subset of netty modules.

Do you see the same thing if using NIO and then upgrading grpc?

**Comment by ran-su** [comment]
Closing since there was no more information. If more information is provided we can reopen.
