### ISSUE TITLE
How to put data to Server and then get data back

### ISSUE THREAD

**Issue by hamroune** [grpc/grpc-java#6467]
HI every one, I'm playing with Flight Server and I want to send (do_put) some data table to server, then the server do some computation and after completion (for the moment just Sync operation) I want to resend back the result as a Table again. 

> client (send data) - > server (compute) - > client (get 

> response).

I can't find in the last version the possibility to attach data into an action! 
My question is may be naive but it will en light me for the possibility to interact seamlessly with all my micro-services.
Thanks in advance

**Comment by hamroune** [comment]
Sorry this is the wrong place, the question is for Apache Arrow Flight.
Sorry for that

**Comment by sanjaypujare** [comment]
closing
