### ISSUE TITLE
Client health check in Bidirectional streaming

### ISSUE THREAD

**Issue by mohammadnejad** [grpc/grpc-java#6468]
In Bidirectional streaming in server side, how I can check that the client connection is ok or not? for example I want to know when client internet be disconnect.

**Comment by sanjaypujare** [comment]
Take a look at https://github.com/grpc/grpc-java/issues/6456 that talks about using `Context.current().isCancelled()` .

**Comment by mohammadnejad** [comment]
> Take a look at #6456 that talks about using `Context.current().isCancelled()` .

The solution in the post when client internet be disconnect is not good. Because I have multi clients with bidirectional streaming and all clients streaming be close with this solution.

**Comment by sanjaypujare** [comment]
That's not true. For each client (connection) there is a separate stream and a separate context. So `Context.current().isCancelled()` correctly reflects the cancellation state for that one client.

**Comment by mohammadnejad** [comment]
Yes, this was my mistake. with keepalivetime and keepalivetimeout my problem is solved. thanks
