### ISSUE TITLE
DEADLINE_EXCEEDED is triggered after header continuation frame is received

### ISSUE THREAD

**Issue by jaankoi** [grpc/grpc-java#6484]
### What version of gRPC-Java are you using?
1.25

### What is your environment?
Client: Android
Server: Windows running C++ version of gRPC

### What did you expect to see?
HTTP/2 implementation in OkHttp library has hard coded frame size of 16384 bytes. In case server is sending a response with trailers that won't fit to max frame size, the frame is split on server side to headers frame and continuation frame. These frames should be then read on client side and stream should get closed. 

### What did you see instead?
In case the server sends headers frame and continuation frame, gRPC-java implementation will read the frames, but it doesn't handle the end of stream correctly and therefore it keeps on waiting for more data. Finally DEADLINE_EXCEEDED error is triggered after the configured timeout since there will never be more data coming as server already sent everything.

### Steps to reproduce the bug
1. Make a request from Android client to server
2. Send response (e.g. error) from server with large trailing metadata so that all data won't fit to OkHttp's max frame size (16384 bytes)
3. Android client receives the data, but will keep on waiting more and original request will finally fail with DEADLINE_EXCEEDED error

**The problem is on below code:**
```java
private void readHeaders(Handler handler, int length, byte flags, int streamId)
     throws IOException {
    if (streamId == 0) throw ioException("PROTOCOL_ERROR: TYPE_HEADERS streamId == 0");

    boolean endStream = (flags & FLAG_END_STREAM) != 0;

    short padding = (flags & FLAG_PADDED) != 0 ? (short) (source.readByte() & 0xff) : 0;

    if ((flags & FLAG_PRIORITY) != 0) {
        readPriority(handler, streamId);
        length -= 5; // account for above read.
    }

    length = lengthWithoutPadding(length, flags, padding);

    List<Header> headerBlock = readHeaderBlock(length, padding, flags, streamId);

    handler.headers(false, endStream, streamId, -1, headerBlock, HeadersMode.HTTP_20_HEADERS);
}
```

Here the `readHeaderBlock` method reads the header frame and the continuation frame correctly and updates the member variable `continuation` with flags from the continuation frame. However, in the above code `endStream` is already evaluated based on the flags received from the first frame, which will not have the `FLAG_END_STREAM`. So the `endStream` will never be true if there is a continuation frame and this will cause that client will keep on waiting for more data.

**Solution proposal:**

```java
private void readHeaders(Handler handler, int length, byte flags, int streamId)
     throws IOException {
    if (streamId == 0) throw ioException("PROTOCOL_ERROR: TYPE_HEADERS streamId == 0");

    short padding = (flags & FLAG_PADDED) != 0 ? (short) (source.readByte() & 0xff) : 0;

    if ((flags & FLAG_PRIORITY) != 0) {
        readPriority(handler, streamId);
        length -= 5; // account for above read.
    }

    length = lengthWithoutPadding(length, flags, padding);

    List<Header> headerBlock = readHeaderBlock(length, padding, flags, streamId);

    boolean endStream = (continuation.flags & FLAG_END_STREAM) != 0;

    handler.headers(false, endStream, streamId, -1, headerBlock, HeadersMode.HTTP_20_HEADERS);
}
```

Instead of evaluating `endStream` immediately from flags received on first frame, flags should be evaluated after reading the header block in which case `continuation.flags` should always have the flags for the whole response. This way the stream end is received correctly and client will not keep on waiting for more data.

**Comment by ericgribkoff** [comment]
Thanks for reporting and diagnosing this. What gRPC server language are clients connecting to?

It sounds like the client is receiving an initial HEADERS frame without END_STREAM or END_HEADERS set, and the CONTINUATION frame contains the END_STREAM flag, which is then ignored by the OkHttp client. If this is a correct description of the behavior you're observing, I'm not clear that it's a client problem rather than a non-compliant server:

The CONTINUATION frame does not have an END_STREAM flag according to the HTTP/2 spec (https://http2.github.io/http2-spec/#CONTINUATION).  The discussion from https://github.com/http2/http2-spec/issues/228 and the description of the END_STREAM flag for HEADERS frames (https://http2.github.io/http2-spec/#HEADERS) indicates that the initial HEADERS stream should still have the END_STREAM flag set, even when followed by continuation frames.

**Comment by jaankoi** [comment]
Clients are connecting to C++ gRPC server.

Based on that specification it does sound that the client is working correctly, but server is behaving incorrectly. Without knowing the details it sounded that the server was working correctly as it was setting the END_STREAM flag on the last frame...

On server side the call stack for setting the flags for initial HEADERS frame:
```
MFServer.exe!finish_frame(framer_state * st, int is_header_boundary, int is_last_in_stream) Line 101	C++
MFServer.exe!add_header_data(framer_state * st, grpc_slice slice) Line 162	C++
MFServer.exe!add_wire_value(framer_state * st, wire_value v) Line 359	C++
MFServer.exe!emit_lithdr_noidx_v(grpc_chttp2_hpack_compressor * c, unsigned int unused_index, grpc_mdelem elem, framer_state * st) Line 437	C++
MFServer.exe!hpack_enc(grpc_chttp2_hpack_compressor * c, grpc_mdelem elem, framer_state * st) Line 488	C++
MFServer.exe!grpc_chttp2_encode_header(grpc_chttp2_hpack_compressor * c, grpc_mdelem * * extra_headers, unsigned __int64 extra_headers_size, grpc_metadata_batch * metadata, const grpc_encode_header_options * options, grpc_slice_buffer * outbuf) Line 710	C++
MFServer.exe!`anonymous namespace'::StreamWriteContext::FlushTrailingMetadata() Line 544	C++
MFServer.exe!grpc_chttp2_begin_write(grpc_chttp2_transport * t) Line 618	C++
```

Implementation of finish_frame in hpack_encoder.cc:
```C
/* finish a frame - fill in the previously reserved header */
static void finish_frame(framer_state* st, int is_header_boundary,
                         int is_last_in_stream) {
  uint8_t type = 0xff;
  type = st->is_first_frame ? GRPC_CHTTP2_FRAME_HEADER
                            : GRPC_CHTTP2_FRAME_CONTINUATION;
  fill_header(
      GRPC_SLICE_START_PTR(st->output->slices[st->header_idx]), type,
      st->stream_id, current_frame_size(st),
      static_cast<uint8_t>(
          (is_last_in_stream ? GRPC_CHTTP2_DATA_FLAG_END_STREAM : 0) |
          (is_header_boundary ? GRPC_CHTTP2_DATA_FLAG_END_HEADERS : 0)));
  st->stats->framing_bytes += kDataFrameHeaderSize;
  st->is_first_frame = 0;
}
```

For the initial HEADERS frame `add_header_data` is calling `finish_frame` like `finish_frame(st, 0, 0);` so that will result flags being set as 0.

Then for the CONTINUATION frame the call stack is:
```
MFServer.exe!finish_frame(framer_state * st, int is_header_boundary, int is_last_in_stream) Line 104	C++
MFServer.exe!grpc_chttp2_encode_header(grpc_chttp2_hpack_compressor * c, grpc_mdelem * * extra_headers, unsigned __int64 extra_headers_size, grpc_metadata_batch * metadata, const grpc_encode_header_options * options, grpc_slice_buffer * outbuf) Line 717	C++
MFServer.exe!`anonymous namespace'::StreamWriteContext::FlushTrailingMetadata() Line 544	C++
MFServer.exe!grpc_chttp2_begin_write(grpc_chttp2_transport * t) Line 618	C++
```
And in this case both parameters `is_header_boundary` and `is_last_in_stream` are 1, so both flags END_STREAM and END_HEADERS are set.

**Comment by ericgribkoff** [comment]
Thanks again for reporting this issue, and the very detailed analysis of both Java and C++'s behavior. Since this looks like an HTTP/2 spec violation on the C++ server side, I've opened https://github.com/grpc/grpc/issues/21436 (with references back to the excellent diagnosis contained here). I think it's appropriate to mark this issue on gRPC Java as closed, since the bug and fix will need to be handled on the gRPC C++ repository; if you have any concerns about closing this  issue please comment here and I can certainly reopen the bug.
