### ISSUE TITLE
DEADLINE_EXCEEDED errors when routing to partner AWS NLB via nginx proxy

### ISSUE THREAD

**Issue by ashishthukral** [grpc/grpc-java#6497]
### What version of gRPC-Java are you using?
1.19.0

### What is your environment?

Linux - Java 8

### What did you expect to see?
Successful response

### What did you see instead?
We have setup a Java Client and have configured timeout for **2300ms**. 
The app is deployed on AWS and it connects to an internal nginx proxy, which then further routes the calls outbound to the partner. 
The requests hit partner's AWS NLB. For about 2-3% of the calls, we see **_io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 2299956907ns_**

Here is the Spring bean definition

        @Bean
        ManagedChannel managedChannel() {

        return NettyChannelBuilder.forAddress(host, port)
                .negotiationType(NegotiationType.TLS)
                .keepAliveTimeout(300, TimeUnit.SECONDS)
                .idleTimeout(300, TimeUnit.SECONDS)
                .build();
       }

And the usage

               EmployeeServiceBlockingStub stub = EmployeeServiceGrpc.newBlockingStub(managedChannel);

               response = stub.withDeadlineAfter(2300, TimeUnit.MILLISECONDS).process(request);

As a suggestion from our partner and following https://medium.com/tenable-techblog/lessons-from-aws-nlb-timeouts-5028a8f65dda#2a20

we updated nginx proxy **/proc/sys/net/ipv4/tcp_keepalive_time** == **300s**, but this seems to have no effect

Any ideas on what might be going on and what can we try further?

### Steps to reproduce the bug

Use Java client, to connect to Partner AWS via nginx proxy from our AWS instance

**Comment by ejona86** [comment]
How long do the requests normally take? If your 90th percentile takes 2.3 seconds, then 10% failure rate would be expected.

Does increasing the timeout decrease the error rate? Or does it seem that 10% of the requests get "hung" for a very long time?

grpc-java v1.23.0 enhanced the client to provide more details when the deadline is exceeded. You may consider upgrading the client and seeing what additional details it provides in the status.

**Comment by ashishthukral** [comment]
> How long do the requests normally take? If your 90th percentile takes 2.3 seconds, then 10% failure rate would be expected.
> 
> Does increasing the timeout decrease the error rate? Or does it seem that 10% of the requests get "hung" for a very long time?
> 
> grpc-java v1.23.0 enhanced the client to provide more details when the deadline is exceeded. You may consider upgrading the client and seeing what additional details it provides in the status.

our p95 is 700ms, i bumped up the grpc version to latest 1.25.0. do we need to enable any other setting to print out additional information as u mentioned about enhancement since 1.23.0 ?

with bump though, we will have to wait 1-2 weeks before it gets deployed to our prod to observer behavior.

**Comment by ejona86** [comment]
How can your p95 be 700ms if 10% of the calls fail with DEADLINE_EXCEEDED after 2.3s? Is your p95 excluding failing RPCs?

The additional information is provided in the Status description, so it will naturally be shown in the StatusRuntimeException like the 2299956907ns is presented now.

**Comment by ashishthukral** [comment]
> How can your p95 be 700ms if 10% of the calls fail with DEADLINE_EXCEEDED after 2.3s? Is your p95 excluding failing RPCs?
> 
> The additional information is provided in the Status description, so it will naturally be shown in the StatusRuntimeException like the 2299956907ns is presented now.

sorry mistakenly added 10% based on some stale metrics, its about 2-3% failure requests. updated ticket description as well.

**Comment by ejona86** [comment]
What I am trying to ask: is it possible these 2-3% of failures are legitimate? How likely is it that the server really didn't have a response in time? Given 700ms for p95, it seems possible but it's unclear to me how likely.

There are two-ish easy ways to find out: 1) look at the long-tail of succeeding requests and see how many of them are near your timeout 2) increase the timeout and see if the error rate drops.

**Comment by ashishthukral** [comment]
> What I am trying to ask: is it possible these 2-3% of failures are legitimate? How likely is it that the server really didn't have a response in time? Given 700ms for p95, it seems possible but it's unclear to me how likely.
> 
> There are two-ish easy ways to find out: 1) look at the long-tail of succeeding requests and see how many of them are near your timeout 2) increase the timeout and see if the error rate drops.

so for the failed requests, partner says, they dont have any record of those txns even at their AWS NetworkLoadBalancer, so we are unsure what happens to these requests..

**Comment by ejona86** [comment]
> they dont have any record of those txns even at their AWS NetworkLoadBalancer, so we are unsure what happens to these requests

Okay. So the additional error details in the newer grpc library may help with that.

**Comment by ashishthukral** [comment]
> > they dont have any record of those txns even at their AWS NetworkLoadBalancer, so we are unsure what happens to these requests
> 
> Okay. So the additional error details in the newer grpc library may help with that.

alright thanks, will keep u posted whatever we find..

**Comment by ejona86** [comment]
@ashishthukral, did you end up finding out more information?
