### ISSUE TITLE
Consider making Channel/Server abstract classes

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#65]
They were interfaces previously because of the bane of Service and the need to extend Abstract*Service in ChannelImpl/ServerImpl. Now that Service is gone from those APIs, we could swap to using abstract classes to give us greater ability to add to the APIs in the future.

**Comment by nmittler** [comment]
@ejona86 what's the state of this?

**Comment by ejona86** [comment]
For me, the answer is, "yes, make them abstract classes." But I've not done it.
