### ISSUE TITLE
Implement oauth2_auth_token

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#650]
I don't know if any API additions need to be done to make this use case easy.

https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#oauth2_auth_token

**Comment by ejona86** [comment]
@anthmgoogle, making our own `Credentials` for a raw and fixed `AccessToken` isn't too hard. But are you planning on adding something similar soon to google-auth-library-java?

**Comment by anthmgoogle** [comment]
Yes. I already updated OAuth2Credentials to take an AccessToken from a derived class. I think the best thing would be to convert this to a concrete class that throws a helpful error if you try to refresh it after the token expires. Let me know the timeframe where this is required.

In the short term, if you pick up 0.2.0, you can pass the toke to a UserCredential.

**Comment by ejona86** [comment]
@anthmgoogle, oh, extending `OAuth2Credentials` and throwing an exception is fairly easy, and even isn't _that_ ugly for a user to do. We can go with that, until such a solution is in google-auth-library-java. There is a strong push to be Beta by at worst end-of-August, and this is something we are doing for Beta.

The solution you mentioned is "good enough" for me though if it isn't done in that time frame.

**Comment by madongfly** [comment]
@anthmgoogle, could you update the [maven central](http://search.maven.org/#search%7Cga%7C1%7Cgoogle-auth-library-oauth2-http)?

**Comment by anthmgoogle** [comment]
0.2.0 should be pushed to the Sonatype repository accessible by maven right now. Let me know if there is any trouble getting this. GRPC-java also needs this to get at the JwtAccess credentials, so updating that version dependency is a good thing to do.

I will work on the temporary access token scenario shortly, but this would come in 0.3.0.

**Comment by madongfly** [comment]
I never pushed an artifact before, so I'm wondering if it's normal that a newly pushed artifact can not be seen after 6 hours?
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':grpc-auth:compile'.
> Could not find com.google.auth:google-auth-library-oauth2-http:0.2.0.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.2.0/google-auth-library-oauth2-http-0.2.0.pom
      https://repo1.maven.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.2.0/google-auth-library-oauth2-http-0.2.0.jar
      file:/usr/local/google/home/simonma/.m2/repository/com/google/auth/google-auth-library-oauth2-http/0.2.0/google-auth-library-oauth2-http-0.2.0.pom
      file:/usr/local/google/home/simonma/.m2/repository/com/google/auth/google-auth-library-oauth2-http/0.2.0/google-auth-library-oauth2-http-0.2.0.jar
  Required by:
      io.grpc:grpc-auth:0.8.0-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

**Comment by anthmgoogle** [comment]
Actually, it should have been pushed a few days ago. But I don't see it with this query either:
https://oss.sonatype.org/#nexus-search;quick~com.google.auth
We'll take a look to see if we can work this out.
@garrettjonesgoogle.

**Comment by anthmgoogle** [comment]
We are working on fixing this. We also have a pull request out for the temporary credentials, so we should be able to include that in a published version soon.

**Comment by anthmgoogle** [comment]
Update: 0.2.0 should be back in the repository now although it does not contain the temporary access token scenario. The PR for that is pending and we can do another release if it is blocking.
