### ISSUE TITLE
NameResolver.Listener2 confusing javadocs

### ISSUE THREAD

**Issue by ST-DDT** [grpc/grpc-java#6523]
I'm not sure in which issue type this fits best.

### What version of gRPC-Java are you using?

1.25.0

### What did you see instead?

The javadocs on [`io.grpc.NameResolver.Listener2`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/NameResolver.java#L313) are confusing because on one hand it states:

> ````
> This is a replacement API of {@code Listener}. However, we think this new API may change
> again, so we aren't yet encouraging mass-migration to it. It is fine to use and works.
> ````

Which sounds like we shouldn't use it yet. On the other hand, the other method is marked for removal (for a version a few months ago)

> ````
> @deprecated This will be removed in 1.22.0
> ````

So is it going to be removed soon?

Related to #1770

**Comment by ran-su** [comment]
The `onAddresses()` might be removed some time in the near future, so do not use it in your new code. Other APIs can be used, but please remember the entire `NameResolver` is experimental.
