### ISSUE TITLE
Q: How to declare rpc method without input and returns messages?

### ISSUE THREAD

**Issue by nickdul** [grpc/grpc-java#653]
is it possible to define **rpc** method without *input* and *returns* messages? 
something like:
```
    service myservice {
        rpc heartbeat() {}
    }
```

**Comment by carl-mastrangelo** [comment]
I am not sure if that is possible, but the proto3 spec provides the "Empty" message for such cases:

```
 service Foo {
       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
   }
```

https://github.com/google/protobuf/blob/master/src/google/protobuf/empty.proto#L44

**Comment by ejona86** [comment]
Protobuf doesn't allow "void" argument or return message. Using `Empty` is the canonical alternative.

I will note, if you think you _may_ want arguments or return values in the future, make a new message that simply has no fields. That way you can add new fields when you need to and not break any application code. `Empty` is great for when you will never want arguments or return values.

**Comment by nickdul** [comment]
i see your point 
thanks everyone for explanation
