### ISSUE TITLE
repositories.bzl uses http (not https)

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#6536]
I see a lot of lines like this:

        server_urls = ["http://central.maven.org/maven2"],

If we're actually resolving these they're going to stop working on January 15, 2020. 

I'm not 100% sure this matters, but just in case I wanted to raise the issue.

**Comment by ejona86** [comment]
Source: https://central.sonatype.org/articles/2019/Apr/30/http-access-to-repo1mavenorg-and-repomavenapacheorg-is-being-deprecated/

Yes, we will want to fix this.
