### ISSUE TITLE
Update protobuf to 3.11.4

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#6542]
### What version of gRPC-Java are you using?

1.26.0

**Comment by ran-su** [comment]
It looks like protobuf 3.11.2 was released couple days ago, but the latest version is still not showing in those repos. I'll wait couple days for it to show up, hopefully we can directly upgrade to 3.11.2.

**Comment by mattdkerr** [comment]
the current version for protobuf is now 3.11.4

**Comment by ejona86** [comment]
We upgraded to 3.11.0 in #6476, and we are on pretty recent 3.17.2 now.
