### ISSUE TITLE
Supplying Servername (TLS+SNI)

### ISSUE THREAD

**Issue by obipawan** [grpc/grpc-java#6551]
Hi, our team has a grpc server written in go setup behind a HAP and we need to provide a `serverName` for the tls+sni configuration. We have go clients and Android clients. With go, it's possible to supply the servername like so
`grpc.WithTransportCredentials(credentials.NewTLS(&tls.Config{ServerName: "host"}))` and that works.
However, I'm unable to figure out how to supply the `serverName` equivalent on android beyond `ManagedChannelBuilder#useTransportSecurity` and that doesn't seem to be working. Please help

**Comment by sanjaypujare** [comment]
Have you looked at ManagedChannelBuilder#overrideAuthority ?

**Comment by obipawan** [comment]
I did, that didn't seem to help as well. I get a 504 on this.

**Comment by obipawan** [comment]
The `ManagedChannelBuilder#overrideAuthority` does indeed work. The issue was related to our HAP config which had a short timeout and since our case was based on long lived connections, the clients got a 504. Closing this, thanks for all the help folks
