### ISSUE TITLE
Feature request: Add com.google.rpc.Status in a javalite variant

### ISSUE THREAD

**Issue by glerchundi** [grpc/grpc-java#6554]
I think the title is self-explanatory but in case it isn't we're building a client for Android devices where we extensively using WKT (solved by the `protobuf-lite` library) and some protos pertaining to google (`com.google.rpc.*`).

We would like to have the lite variant in order to be used on Android devices. Is it possible? Is this the correct place to ask for it? Pointing to @ejona86 as, as far i can see, you're the one answering these kind of questions! :D

Thanks in advance!

**Comment by glerchundi** [comment]
Cross referencing #4695 as it is probably related and a friendly cc for @carl-mastrangelo in order to be aware of this issue.

**Comment by carl-mastrangelo** [comment]
cc: @ericgribkoff

**Comment by ejona86** [comment]
`com.gogole.rpc.Status` is provided by `com.google.api.grpc:proto-google-common-protos`, not grpc directly. Lite's generated code must match the version of the runtime being used, which makes it poor/useless to provide pre-generated code for it.

However, it isn't _too_ bad to generate the code yourself, like (along with the [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin/)):
```
dependencies {
  protobuf 'com.google.api.grpc:proto-google-common-protos:1.17.0'
}
```

It _looks like_ `StatusProto` may work with lite protobuf, but you'd have to exclude full protobuf to use it and it may be a bit temperamental. It's really hard to have any library using lite today, and not really possible if that library exposes protobuf in its API.

**Comment by glerchundi** [comment]
Thanks for the quick response @ejona86 and for pointing others @carl-mastrangelo.

Following your advices we think that the most sane way to solve this was to generate those dependencies not present in public libraries by ourselves.

But i'm a little bit concerned about a sentence in your comment above. I'm referring to this: "Lite's generated code must match the version of the runtime being used".

Why is this required? We have a centralized specification repository we use to generate all the required languages code from this single source of truth. Keeping those versions equal (generator and runtime) requires a lot of effort due to the required process automation or people/manual coordination. If this is a hard requirement, how is this then possible to have a `protobuf-javalite` with pregenerated WKT code?

Thanks in advance!

**Comment by ejona86** [comment]
> Keeping those versions equal (generator and runtime) requires a lot of effort due to the required process automation or people/manual coordination.

I don't disagree, but this is [a protobuf java lite restriction](https://github.com/protocolbuffers/protobuf/blob/v3.11.2/java/lite.md). Lite is not providing API/ABI guarantees, and that extends to the generated code. I expect that _most_ impacts generated code. Part of the problem is that retaining backward compatibility can prevent future optimizations, and Android users really want code size/performance optimizations. You can open an issue on protocolbuffers/protobuf.

**Comment by creamsoup** [comment]
per @ejona86's comment, please open the issue on the related protobuf repo and mention this issue if necessary.
