### ISSUE TITLE
how to user custom picker in RoundRobinLoadBalancer

### ISSUE THREAD

**Issue by qingbozhang** [grpc/grpc-java#6571]
hi, I want to write a weighted round robin LoadBalancer.
I want to reuse RoundRobinLoadBalancer and change the SubchannelPicker(`ReadyPicker`), but The class is protected and final cannot extend.
how to change it at runtime or another way do this ?

**Comment by voidzcy** [comment]
If you want to use `RoundRobinLoadBalancer` without modification, you can use the default [`LoadBalancerRegistry`](https://github.com/grpc/grpc-java/blob/6b04fc18f30deb3519c389fe457b99cf5a8d99d0/api/src/main/java/io/grpc/LoadBalancerRegistry.java#L100) with `getProvider("round_robin")`. I don't think there is a way to extend/change its implementation to do something else, you will need to implement your own weighted round robin.

**Comment by qingbozhang** [comment]
okay. I have been implemented a new LB. it worked now.  Thanks.

**Comment by eugeniyk** [comment]
@qingbozhang do you want to share your implementation somewhere?
