### ISSUE TITLE
Android grpc app Gradle build experience needs improvement

### ISSUE THREAD

**Issue by bubenheimer** [grpc/grpc-java#6573]
It does not really seem possible to have decent quality Gradle builds for grpc-based Android apps that use certain common 3rd party protobuf types. It also is time-consuming to find appropriate workarounds to make builds succeed anyway. In my case I only use three pretty common 3rd party types,

_google/protobuf/empty.proto_
_google/protobuf/timestamp.proto_
_google/rpc/status.proto_

as well as corresponding standard APIs to manipulate the types from Java programmatically:

_com.google.protobuf.util.Timestamps_
_io.grpc.protobuf.StatusProto_

The types and APIs are available from certain Gradle artifacts,

_com.google.api.grpc:proto-google-common-protos_
_com.google.protobuf:protobuf-java-util_
_io.grpc:grpc-protobuf_

but in the end I can't get successful builds if I use the artifacts. Instead I have to manually copy a bunch of the classes I need plus dependencies from the artifacts into my project.

There is a combination of aggravating factors preventing normal build configs:

1. protobuf-javalite: the artifacts are generally built with full protobuf-java, no javalite build available, even though the types I need are perfectly compatible with javalite and fairly common in the first place.
2. The artifacts are big and some of the stuff gets in the way of javalite, and also sometimes overlaps with protobuf-generated classes.
3. The Android R8 tool, used for code optimization and obfuscation, is very particular about duplicate code, and does not work well with artifacts protobuf'ed with the gradle-protobuf-plugin when some classes also come in via some other regular Gradle dependency. The problem is with protobuf'ed classes showing up in the project's build output and coming in via dependencies at the same time.

I've experimented at length with excluding transitive dependencies and protobuf'ing dependencies instead of pulling them in normally, but was forced to manually copy _google.rpc.status.proto_, _io.grpc.protobuf.StatusProto_, _com.google.protobuf.util.Timestamps_, and _com.google.protobuf.util.Durations_. I will have to keep them in sync with new releases of their corresponding artifacts.

One thing that may help could be a review of common 3rd party types and common 3rd party artifacts with an eye on creating new or more comprehensive javalite-based artifacts.

I've created a little sandbox project to test things out: https://github.com/bubenheimer/protobufr8duplicates

**Comment by ericgribkoff** [comment]
Related issue (for `StatusProto`): https://github.com/grpc/grpc-java/issues/6554

Thanks for supplying the sandbox project. I believe the closing of https://github.com/protocolbuffers/protobuf/issues/1889 signalled a partial improvement here, in that some (but it appears not all) of the well-known types' generated code is now packaged with the latest protolite release.

**Comment by bubenheimer** [comment]
Thanks for the quick response and linking those related issues. I am well aware of the various approaches described, I've been battling this problem for years. Periodically some protobuf- or grpc-related tool or library changes and I revisit the problem, just to find that it's still broken or broken for other reasons now. A more recent complication is the R8 tool, which makes protobufing external dependencies questionable.

This is definitely one of my top build headaches, if not the single top one.

**Comment by bubenheimer** [comment]
From my perspective, this is what's needed to resolve the issues:

grpc-protobuf-lite needs io.grpc.protobuf.StatusProto (easy). Just to be clear, there is another distinct StatusProto class, com.google.rpc.StatusProto, which is just generated from status.proto. On the other hand, the grpc StatusProto is a standalone utility class.

Create a protobuf-java-util-lite with Timestamps.java, Durations.java (harder)
Create proto-google-common-protos-lite for status.proto, Status.java (harder)

**Comment by ericgribkoff** [comment]
Sorry for the delay. I filed https://github.com/protocolbuffers/protobuf/issues/7094 to figure out why `duration.proto` is not in `protobuf-javalite-3.11.1`. As best I can tell, the two well-known types you reference (`empty` and `timestamp`) include both their generated classes and the `.proto` source files in the latest javalite release.

As for:

> grpc-protobuf-lite needs io.grpc.protobuf.StatusProto (easy). Just to be clear, there is another distinct StatusProto class, com.google.rpc.StatusProto, which is just generated from status.proto. On the other hand, the grpc StatusProto is a standalone utility class.

I don't think this is actually easy for gRPC, as a library, to do. `io.grpc.protobuf.StatusProto` depends on `com.google.rpc.StatusProto`, the generated Java classes which are only released in an artifact that depends on full protobuf, not protolite. I believe that there was an external tracking issue for this somewhere, filed quite a while ago, but this may have just been an email thread with the maintainers of that dependency. I'm having trouble locating it now. #6554 includes further discussion about this.

Similarly, the lack of `com.google.protobuf.util.Timestamps` and `com.google.protobuf.util.Durations` in the javalite artifact is not specific to gRPC. This part of the issue should probably end up as an issue on the protobuf repository.

**Comment by bubenheimer** [comment]
Thanks for the investigation!

**Comment by ericgribkoff** [comment]
I'm going to mark this closed since I think https://github.com/protocolbuffers/protobuf/issues/7094 on the protobuf repo covers everything that can be done to improve this.
