### ISSUE TITLE
Setting max threads

### ISSUE THREAD

**Issue by wihl** [grpc/grpc-java#6597]
I would like to be able to cap the maximum number of threads the grpc Java library uses. Right now, it defaults to 2 threads per CPU. If there are multiple processes on a 64 CPU machine, then many superfluous threads are generated reducing performance. While there appears to be a means to set this, behind the scenes, it is set to a static with a limit = 0, meaning unlimited.

**Comment by voidzcy** [comment]
I am assuming you are asking for limiting the number of networking threads. For netty (seems this is what you are looking at), the default is [`NettyRuntime.availableProcessors()`](https://github.com/grpc/grpc-java/blob/1cefe851e18babff3e7eb2ad5ebaf4bee6324b4f/netty/src/main/java/io/grpc/netty/Utils.java#L376-L385). Previously it was `NettyRuntime.availableProcessors() * 2` but #6439 reduced it by a half and the change was in 1.26 release. Back to your question, you can either configure `io.netty.eventLoopThreads` system property or call [`NettyChannelBuilder#evenLoopGroup(...)`](https://github.com/grpc/grpc-java/blob/1cefe851e18babff3e7eb2ad5ebaf4bee6324b4f/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L223) to override the default event loop with thread limiting. For Okhttp, you can do the similar via [`OkhttpChannelBuilder#transportExecutor(...)`](https://github.com/grpc/grpc-java/blob/1cefe851e18babff3e7eb2ad5ebaf4bee6324b4f/okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java#L159).

**Comment by galkoren** [comment]
Hi. Thanks.
I found that property :)
The actual property for grpc is "io.grpc.netty.shaded.io.netty.eventLoopThreads".

**Comment by wihl** [comment]
@voidzcy Thanks for your explanation. Should be all set.
