### ISSUE TITLE
Change AbstractTransportTest to propagate server delay in request

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#661]
Commit https://github.com/grpc/grpc-java/commit/3e26b993ce90901b32faa1b8b855abfdc2153bc6#diff-cf14d5396f1bd6ab4bcf9c37e7756356R143 introduced the use of an `AtomicLong` to manage server delay and also created a server delay interceptor.  Neither of these are needed since the integration test request messages support propagating server delay.

**Comment by johnbcoughlin** [comment]
Feel free to assign this to me, I'll clean up. I missed the server delay propagation originally :)

**Comment by nmittler** [comment]
@johnbcoughlin that would be great, thanks! Github isn't letting me assign it to you but I'll be happy to review your PR.

**Comment by ejona86** [comment]
@nmittler I think we need to add him to the grpc org. I'll make sure an invite gets sent out.

**Comment by jayantkolhe** [comment]
Added @johnbcoughlin and assigned him this issue

**Comment by nmittler** [comment]
Thanks @jayantkolhe!

**Comment by ejona86** [comment]
Resolved in 1ac64bd
