### ISSUE TITLE
gRPC seems to treat socksProxyHost as httpProxy

### ISSUE THREAD

**Issue by fireduck64** [grpc/grpc-java#6613]
### What version of gRPC-Java are you using?

Latest from master: b8474d61c966f60cc0bad4e5abaca351e90afc9d

### What is your environment?

Linux 5.0.0-37-generic
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

bazel version
Build label: 2.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:30:18 2019 (1576758618)
Build timestamp: 1576758618
Build timestamp as int: 1576758618

### What did you expect to see?

I expected gRPC to respect system properties:
socksProxyHost
socksProxyPort

and use socks to connect to remote hosts

### What did you see instead?

gRPC appears to send HTTP proxy commands (rather than SOCKS) commands

### Steps to reproduce the bug

java -DsocksProxyHost=localhost -DsocksProxyPort=9112 <something that used grpc to try to connect>

For a socks proxy, you can use tor or ssh -D for a simple setup.

Or in fact, nc -l -k 9112

Example log from nc:

CONNECT snow-a.1209k.com:2348 HTTP/1.1
host: snow-a.1209k.com:2348

CONNECT snow-de1.snowblossom.org:443 HTTP/1.1
host: snow-de1.snowblossom.org:443

CONNECT snow-a.1209k.com:2338 HTTP/1.1
host: snow-a.1209k.com:2338

CONNECT snow-tx1.snowblossom.org:2348 HTTP/1.1
host: snow-tx1.snowblossom.org:2348

CONNECT snow-tx1.snowblossom.org:2338 HTTP/1.1
host: snow-tx1.snowblossom.org:2338

CONNECT snow-tx1.snowblossom.org:80 HTTP/1.1
host: snow-tx1.snowblossom.org:80

Note: those ports and hosts are what I am trying to connect to with gRPC.  Something that starts with the string "CONNECT" is an HTTP proxy command, not a SOCKS command.  SOCKS uses a binary protocol and expects the first byte to be the SOCKS version. 

If I use tor, it gives the following error:
Jan 16 13:05:06.000 [warn] Socks version 67 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)

67 = 'C', which is not surprising since gRPC is attempting to send "CONNECT".

When java is configured as above:
java -DsocksProxyHost=localhost -DsocksProxyPort=9112
(and pointed to a real SOCKS proxy rather than nc) parts of my program that just java.net.URL connection work properly (using the proxy).

This seems to be a repeat of #5600, but I am certain this isn't a proxy configuration problem.

**Comment by fireduck64** [comment]
Related to: https://github.com/grpc/grpc-java/issues/5279

**Comment by dapengzhang0** [comment]
We are not planning to support SOCKS proxy, see https://github.com/grpc/grpc-go/issues/707#issuecomment-246515115

**Comment by fireduck64** [comment]
Would there be interest if I do the work?  I am pretty sure I am going to need SOCKS for my workload and it won't be much more effort for me to submit a PR.  I've already implemented a SOCKS server for another part of my project.

**Comment by fireduck64** [comment]
I was a Google SRE/SWE for 5 years, but I never did get java readability.  I haven't actually found the part that uses the proxied socket address object to make contact, but assuming that isn't deep in narnia I should be able to handle this.  I'll send a PR if I get it working.
