### ISSUE TITLE
Increasing message size in bazel with java_grpc_library

### ISSUE THREAD

**Issue by Jdban** [grpc/grpc-java#6625]
How do we increase the message size limit when building with `java_grpc_library` through `bazel`?

I see suggestions about setting `maxMessageSize` but I'm not sure where we would implement that.
Thanks!

**Comment by ejona86** [comment]
You mean the maximum size you can send over a Channel/Server? That is not impacted by the generated code.

Use the builds to configure what your client/server is willing to receive:
https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#maxInboundMessageSize-int-
https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerBuilder.html#maxInboundMessageSize-int-

**Comment by Jdban** [comment]
Yeah. Got it, thanks
