### ISSUE TITLE
StatusRuntimeException trailers not sent to client

### ISSUE THREAD

**Issue by cbornet** [grpc/grpc-java#6683]
### What version of gRPC-Java are you using?

1.27.0

### What is your environment?

Linux, java 8

### What did you expect to see?

Trailers attached to a thrown `StatusRuntimeException` by a server implementation are passed to the client.

### What did you see instead?
The trailers are not passed.

### Steps to reproduce the bug
* Clone this little sample project https://github.com/cbornet/grpc-status-trailers
* Package :  ̀mvn package`
* Execute : `java -jar target/simple-grpc-server-1.0-SNAPSHOT.jar`

It should print `test`. It prints `null` instead.
If you uncomment the `onError` call and comment the `throw` line then it works.

In https://github.com/grpc/grpc-java/blob/v1.27.0/core/src/main/java/io/grpc/internal/ServerImpl.java#L558 we see that empty Metadata are set when closing the call instead of using the ones from the Status exception.

**Comment by creamsoup** [comment]
This is intended behavior. the Metadata is gone by the time gRPC catches the exception. the correct way is the commented line.

**Comment by cbornet** [comment]
But why ? I find it very useful to throw exceptions from the implemented methods and let the ServerCall catch it and close with error. As far as I know it's a regular way to send a status exception and it would be great to have the metadata also propagated.

**Comment by creamsoup** [comment]
no, it is not us. java throwing away the local variable. when we catch the exception the local variable is not available.

what you are asking is

```java
Object method() {
  Object wantToPass = new Object();
  throw new Exception();
}

void test() {
  try {
    method();
  } catch (Exception e) {
    // somehow access the wantToPass local variable in other method
  }
}
```

**Comment by creamsoup** [comment]
Sorry about not reading carefully, I wouldn't except to see the server throwing `RuntimeStatusException` =(

The try-catch block in `SeverImpl` is for catching general unhandled exceptions, not really intended to catch `StatusException` or `StatusRuntimeException`. Those exceptions should be handled by server developers by calling `onError`. We do not encourage to throwing exception in the server code (same applies to client). This is not a best practice in general, and known exceptions should be handled.

I understand why you raise this issue, but this is misuse of API imo.

**Comment by cbornet** [comment]
The javadoc doesn't discourage throwing exceptions : https://github.com/grpc/grpc-java/blob/v1.27.0/api/src/main/java/io/grpc/Status.java#L47

**Comment by cbornet** [comment]
Closing as duplicate of #2189. Sorry for missing that one when looking for my issue. It's clearer now and `TransmitStatusRuntimeExceptionInterceptor` is what I was looking for (safe for my use-case).
Thanks for your time.
