### ISSUE TITLE
possible to chain CallCredentials, or use multiple instances?

### ISSUE THREAD

**Issue by mattnworb** [grpc/grpc-java#6722]
I might be missing something obvious, but it seems that there is no way to use multiple CallCredentials instances (I am looking in grpc-java 1.26.0) with a client stub.

The use case I am thinking of is that we have library code which offers a CallCredentials implementation which sets a header for "service name", and I'd like to pair this with https://github.com/grpc/grpc-java/blob/bb37524750fa4923f7dc390f5f961602b46b3790/auth/src/main/java/io/grpc/auth/MoreCallCredentials.java.

Since AbstractStub.withCallCredentials(..) overwrites the credentials instance on each call, my first naive idea was to write a small CallCredentials implementation which just calls each of the two CallCredentials instances in order:

```java
  @Override
  public void applyRequestMetadata(final RequestInfo requestInfo, final Executor appExecutor,
                                   final MetadataApplier applier) {

    for (CallCredentials callCredentials : allCallCredentials) {
      callCredentials.applyRequestMetadata(requestInfo, appExecutor, applier);
    }
  }
```

This is not allowed as each CallCredentials implementation calls `applier.apply(..)` or `applier.fail(..)`, and `io.grpc.internal.MetadataApplierImpl` throws an exception when either method is called after it has been "finalized".

Is there no supported way in the CallCredentials design to be able to use multiple classes at runtime? It seems like this would force people into combining all of the credential logic that they want to attach to their client stub into one implementation - or in other words, composition is not possible.

**Comment by ericgribkoff** [comment]
I think you can accomplish this by implementing your own `ConsolidatingMetadataApplier` that merges the metadata from each call to apply, then (when all call credentials are "done") invokes `applier.apply()` on the original `applier` supplied by the gRPC library. I'm not an expert in the call credentials API, but it seems like a built-in composition solution from gRPC would be difficult as, generally, credentials types could step on/overwrite each other and I wouldn't expect composition of arbitrary credentials to be valid.

**Comment by mattnworb** [comment]
> I'm not an expert in the call credentials API, but it seems like a built-in composition solution from gRPC would be difficult as, generally, credentials types could step on/overwrite each other and I wouldn't expect composition of arbitrary credentials to be valid.

I think that is a fair point, especially if each CallCredentials type wanted to set the same headers. Thinking about my use case some more, it might be a strange fit for a CallCredentials implementation that we are setting a header name that isn't 'authorization' but instead another name, and that would probably be best modeled as something that is not an implementation of CallCredentials.
