### ISSUE TITLE
How do I set the GRPC_ARG_KEEPALIVE_TIME_MS parameter on the server?

### ISSUE THREAD

**Issue by BalzGuenat** [grpc/grpc-java#6738]
Make sure you include information that can help us understand your question. -->

By default, the `GRPC_ARG_KEEPALIVE_TIME_MS` parameter is set to 2h on the server. How can I change this?

**Comment by andrm** [comment]
I use this:
`
// implementation of the service:
 MyService boxService = new MyService();
NettyServerBuilder nettyBuilder = NettyServerBuilder.forPort(ssl_port)
                    .permitKeepAliveWithoutCalls(true)
                    .permitKeepAliveTime(5, TimeUnit.SECONDS)
                    .sslContext(sslContext);
 nettyBuilder.addService(boxService);
 Service ssl_server =  nettyBuilder
                    .build();`
