### ISSUE TITLE
Is there a way to access MethodOptions from ServerInterceptor's interceptCall method?

### ISSUE THREAD

**Issue by zixunjian** [grpc/grpc-java#6740]
I saw [this issue](https://github.com/grpc/grpc-java/issues/2423) and someone commented that it's been "fixed". But after following the link I'm still unsure about how it can be done.

**Comment by dapengzhang0** [comment]
You can use `ServerCall.getMethodDescriptor()` to get the `MethodDescriptor`. And call `MethodDescriptor.getSchemaDescriptor()` to get `io.grpc.protobuf.ProtoMethodDescriptorSupplier` if the service is a proto generated service.

**Comment by zixunjian** [comment]
Thanks, that worked.
