### ISSUE TITLE
Add an API for injection-frameworks/spring-boot to create stubs of a specific type

### ISSUE THREAD

**Issue by ST-DDT** [grpc/grpc-java#6744]
### Is your feature request related to a problem?

I want to automatically inject stubs into beans/components without having to create them explicitly.
Currently I use reflection to invoke the factory methods/constructors, but that broke unnoticed for me. So I would like to have an API that is future proof (and extensible).

### Describe the solution you'd like

A method in the grpc-java API library, that can be used to create the stubs for me, so that I don't need to guess the way to do it:

````java
public static <T extends AbstractStub<T>> T createStub(Class<T> stub, Channel channel);
````

### Additional context

I'm using spring-boot v2 as dependency injection framework
[grpc-spring-boot-starter - compatibility fix for 1.26.0+](https://github.com/yidongnan/grpc-spring-boot-starter/pull/328/files#diff-bccc7431d600984610957495b23143ffR209-R276)

````java
try {
    // First try the public static factory method
    final String methodName = deriveStubFactoryMethodName(stubType); // using the new intermediate classes as disambiguator
    final Class<?> enclosingClass = stubType.getEnclosingClass();
    final Method factoryMethod = enclosingClass.getMethod(methodName, Channel.class);
    return stubType.cast(factoryMethod.invoke(null, channel));
} catch (final Exception e) {
    try {
        // Use the private constructor as backup
        final Constructor<T> constructor = stubType.getDeclaredConstructor(Channel.class);
        constructor.setAccessible(true);
        return constructor.newInstance(channel);
    } catch (final Exception e1) {
        e.addSuppressed(e1);
    }
    throw new BeanInstantiationException(stubType, "Failed to create gRPC client", e);
}
````

**Comment by dapengzhang0** [comment]
I'm not sure I understood your FR. We can not know what a stub implementation in general will look like, and we can't even assume a stub implementation has a no-arg constructor. So I don't think grpc-library will provide such API. It seems framework developers can achieve this all by themselves using current stable public APIs in grpc library. There is no need to use grpc internal APIs so it could be future proof.

**Comment by ejona86** [comment]
@ST-DDT, can you explain more how this happened:
> Currently I use reflection to invoke the factory methods/constructors, but that broke unnoticed for me.

If you are using stable API, it should be stable (modulo reflection issues like getDeclaredMethod vs getMethod).

**Comment by ejona86** [comment]
I don't think we want to get into the business of using reflection for something like this. If we added a factory method to the stub itself, would that suffice? I've thought for a while that `MyStub stub = MyStub.newStub(channel)` would be nicer than the current `MyStub stub = MyGrpc.newStub(channel)`. We would probably use the same method name for all stub types. The stubs are now extending a different base class based on their type (e.g., AbstractBlockingStub), so if you need to limit your code to only certain stub types you can with `Class<? extends AbstractBlockingStub<?>>` generics.

The breakage itself should have been a one-time thing, since you are now on stable API (excepting something major like a v2 API). Yes, deprecations will be missed, but the API itself won't be removed (and very-well supported, given the number of users calling those APIs today).

**Comment by ST-DDT** [comment]
> I've thought for a while that MyStub stub = MyStub.newStub(channel) would be nicer than the current MyStub stub = MyGrpc.newStub(channel). 

I agree, although having two factory methods might be confusing as well.
Unfortunately I still have to maintain compatibility to those classes that are generated with an older version of grpc and thus don't have the nice methods.

> We would probably use the same method name for all stub types.

This is a requirement, otherwise I still need to guess the factory method name depending on the class.

> The breakage itself should have been a one-time thing, since you are now on stable API (excepting something major like a v2 API).

Well, only as long as there is no "better" way. For compatibility reasons, I still need to support old variants up to a certain extend.

**Comment by ejona86** [comment]
> Unfortunately I still have to maintain compatibility to those classes that are generated with an older version of grpc and thus don't have the nice methods.

So it sounds like my suggestion doesn't help much.

I don't think there is much concern with the current approach, as it is using stable APIs. Let's keep things at the status quo. If it breaks _again_ there is something else happening that should be considered. If there is a "better" way in the future it will probably only be to receive more arguments or expose a new API, so it is unlikely that a reflection utility would be able to make use of it either. (As it would need to be updated to receive another argument or return a different class.)

I'll note that the "silent" breaking could be discovered with a test. Granted, you'd need to consistently test with the latest version of grpc-java to notice a breakage.
