### ISSUE TITLE
RELEASING is out of date

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#6760]
It surprising that it matters which system is used to deploy to Maven Central, but leaving that aside I doubt anyone at Google is still deploying with Windows 7 or   Mac OS X 10.12.6

```
We deploy GRPC to Maven Central under the following systems:

    Ubuntu 14.04 with Docker 13.03.0 that runs CentOS 6.9
    Windows 7 64-bit with Visual Studio
    Mac OS X 10.12.6

Other systems may also work, but we haven't verified them.
```

**Comment by creamsoup** [comment]
the system it builds doesn't really matter except the protoc binary. okay, maybe not even for the protoc binary for most people, it is FYI.
quoted part of the doc is not updated for a while. You are right about the os x, we are using `10.14.6` . i'll update the doc. but, windows 7 is still used. Windows 7 is provided by kokoro (or, windows server 2016 if this matters).

**Comment by dapengzhang0** [comment]
Mac version is updated. We currently don't have plan to update window version.
