### ISSUE TITLE
Include grpc-android and grpc-android-interop-testing in main build

### ISSUE THREAD

**Issue by voidzcy** [grpc/grpc-java#6775]
Mentioned in https://github.com/grpc/grpc-java/pull/6132#issuecomment-572724007, dependencies in grpc-android and grpc-android-testing are not synced with the main build. We should maintain them using the same versions of dependencies.

**Comment by voidzcy** [comment]
For grpc-android-testing, it needs the codegen plugin as well. We would either need to check in the generated code (i.e., similar to what grpc-services is doing) or build it only when both `skipCodegen` and `skipAndroid` are `false`. Or leave it as is since it is special. What do you think? @ejona86

**Comment by ejona86** [comment]
Do like we do elsewhere: check in the grpc-generated code.

**Comment by voidzcy** [comment]
All done.
