### ISSUE TITLE
Lint error: Duplicate platform classes

### ISSUE THREAD

**Issue by mwolffalonso** [grpc/grpc-java#6782]
Hello, trying to use this library in order to connect to GCP and when trying to build the apk it gives me the following Lint errors:

../../build.gradle: commons-logging defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar.
../../build.gradle: httpclient defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar.
There are a number of libraries that duplicate not just functionality of the Android platform but using the exact same class names as the ones provided in Android -- for example the apache http classes. This can lead to unexpected crashes.

To solve this, you need to either find a newer version of the library which no longer has this problem, or to repackage the library (and all of its dependencies) using something like the jarjar tool, or finally, rewriting the 
[reports.zip](https://github.com/grpc/grpc-java/files/4268164/reports.zip)

code to use different APIs (for example, for http code, consider using HttpUrlConnection or a library like okhttp).
Note: This issue has an associated quickfix operation in Android Studio and IntelliJ IDEA.
To suppress this error, use the issue id "DuplicatePlatformClasses" as explained in the Suppressing Warnings and Errors section.

**Comment by creamsoup** [comment]
our dependencies includes those libraries are not only for android, so just upgrading will not work. jarjar will increase the binary size. best bet is using the provided ones. I am not an Android expert, so their might be a better option. if anyone knows please comment.

in any case, can you exclude those libraries?

```
configurations {
    all {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }
}
```

**Comment by creamsoup** [comment]
i believe suggested answer should fix it. feel free to reopen if it doesn't fix the issue.

**Comment by mwolffalonso** [comment]
Thanks sorry for my lack of response, I had leave GCP TTS as it does not have Spanish wavenet voice.

⁣Gracias,
Saludos,
Martin.​
