### ISSUE TITLE
Custom transport for REST, Soap, ...

### ISSUE THREAD

**Issue by Ben-Barron** [grpc/grpc-java#6789]
We like the interfaces grpc provides and would like to use them to communicate to our legacy services too over REST, SOAP (and TCP for that matter)

We are aware of the proxy that already exists for REST - but it doesn't work for us.

We want to use as much of "vanilla" GRPC as possible and provide as light an integration as possible so we can reuse all the existing goodies that have been built into the framework (such as the opencensus integration)

Picking REST as an example for this question. I've had a poke around and the plan is to:
-  annotate the proto service definition using the existing HttpRule annotation  (https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#google.api.HttpRule)
- implement AbstractManagedChannelImplBuilder overriding buildTransportFactory() to return a REST based TransportFactory and add a REST ClientInterceptor.
- implement AbstractClientStream with useGet=true which will allow us to use the writeHeaders payload to send the request and then use the listener on the TransportState for the response.
- the Rest ClientInterceptor would change the message serializer/deserializer to use JsonFormat from protbuf utils and add the HttpRule instance to the metadata which is pulled from the MethodDescriptor so it can be pulled out by the Transport.

My questions are:
- are we on the right path here for how the framework is designed to work with new transports?
- are there any gotchas that might catch us out with the method we've chosen above.

**Comment by sanjaypujare** [comment]
Since you talked about "legacy REST services" it looks like your use case is gRPC client talking to a REST server. The [HttpRule](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#grpc-transcoding) reference is really for the opposite direction. So I don't know if it helps for your use case (and then removing it in the transport from metadata as you mention in the 4th bullet)

**Comment by Ben-Barron** [comment]
@sanjaypujare Yes, I am referring to a generated GRPC client talking to a REST server. Perhaps I am missing something here but HttpRule contains all the information one would need to make the REST request - what made you question whether it was possible?

**Comment by sanjaypujare** [comment]
@Ben-Barron since you talked about legacy REST services I wasn't sure if the google.api.http annotation would be enough to let you generate any kind of legacy REST request. It seems possible with GET requests containing only path and query parameters but I wasn't sure.

**Comment by sanjaypujare** [comment]
@Ben-Barron it will be good to share your progress or update once you are able to make it work.

**Comment by sanjaypujare** [comment]
Closing for now. Reopen if needed
