### ISSUE TITLE
Resource leak exception in logs

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-java#6796]
### What version of gRPC-Java are you using?
1.21.0
### What is your environment?
CentOS Linux release 7.6.1810
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-linux64) (build 25.212-b04, mixed mode)

### What did you expect to see?
No errors
### What did you see instead?
```
LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce the bug
Found by internal load testing

The only thing we do is set a bounded thread pool executor that sends out usage metrics. A test project is available on GitHub.
https://github.com/asarkar/kotlin/blob/master/grpc-learning/src/main/kotlin/org/asarkar/greeting/server/GreetingServer.kt#L47

**Comment by creamsoup** [comment]
i think this is due to the executor.

**Comment by asarkar** [comment]
@creamsoup You mean this is due to the thread pool being full? How's that related to resource leak?

**Comment by creamsoup** [comment]
yes, the listener unset exception is kind of assertion error. at this point, anything can happen.

**Comment by asarkar** [comment]
Then I suggest logging a message clearly why the listener is unset. As it stands today, the message is vague and gives no indication to what is wrong.

**Comment by creamsoup** [comment]
"listener unset" can only happen if there is a race condition and/or unhandled exception. under this condition, it is possible to have some unreleased resources. if it still happens after the "listener unset" is fixed, it is clearly a bug.
btw, i was under assumption that you are also seeing the exception in the same run. did you see the exception?

**Comment by creamsoup** [comment]
@asarkar, if it was from same run this is just red herring. you can report this bug (or reopen) if you can reproduce this bug when the other issue is resolved.
