### ISSUE TITLE
Gradle Build not executing properly

### ISSUE THREAD

**Issue by ncioj10** [grpc/grpc-java#6825]
Currently I'm trying to set up a demo project for gRPC. 
I'm encountering a problem regarding the generated code.

My gradle file is attached. I've tried Gradle 5.6 and Gradle 6.0. 

The errors persist:

`error: cannot find symbol
      UnusedPrivateParameter unused) {
      ^
  symbol:   class UnusedPrivateParameter
  location: class PatientRequest
`

` error: no suitable method found for internalBuildGeneratedFileFrom(String[],FileDescriptor[])
      .internalBuildGeneratedFileFrom(descriptorData,
      ^
    method FileDescriptor.internalBuildGeneratedFileFrom(String[],FileDescriptor[],InternalDescriptorAssigner) is not applicable
      (actual and formal argument lists differ in length)
    method FileDescriptor.internalBuildGeneratedFileFrom(String[],Class<?>,String[],String[],InternalDescriptorAssigner) is not applicable
      (actual and formal argument lists differ in length)
`

`error: method does not override or implement a method from a supertype
  @java.lang.Override
`

I hope there is a fix.
Best,
Nicolas

**Comment by ncioj10** [comment]
My build.gradle
[build.gradle](https://github.com/grpc/grpc-java/files/4331146/build.txt)

**Comment by voidzcy** [comment]
There is some problem with your protobuf dependency. Try with a clean build if you have modified your dependencies recently. Your provided buildscript contains minimal configuration and nothing seems to be wrong. Our [example's buildscript](https://github.com/grpc/grpc-java/blob/v1.28.x/examples/build.gradle) looks similar to yours and it works well. If you still cannot get it work, try running `./gradlew dependencies` and post your output to see what is going on.

**Comment by ericgribkoff** [comment]
I'm going to mark this closed since we haven't heard back from the original poster yet. Feel free to respond further and I can reopen it if necessary.

**Comment by ncioj10** [comment]
Sorry for the late reply, I didn't see this. I continued using the example buildscript as basis and that worked. It might be a problem with the intellij integrations, but I couldn't pin it down precisely.
