### ISSUE TITLE
Avoid sharing classes in test scope between multiple modules

### ISSUE THREAD

**Issue by voidzcy** [grpc/grpc-java#6847]
Example: [`FakeClock`](https://github.com/grpc/grpc-java/blob/master/core/src/test/java/io/grpc/internal/FakeClock.java) is a utility class for unit testing. However, it is in `grpc-core`'s test scope but used for cross modules. This is problematic as build tools may not pull test sources to a dependent module. We have [hacks in build files](https://github.com/grpc/grpc-java/blob/master/xds/build.gradle#L39) to force pulling it into classpath for test scope.

We should eliminate such usages before having more and more such hacks ([`grpc-rls`](https://github.com/grpc/grpc-java/blob/8d4240f4800f20de0e5f0b7c213577b3c0324f93/rls/build.gradle#L17) started doing it). They should be put into `grpc-testing` module and compiled into the artifact as a utility for tests. If they are not intended for users, we can annotate them as `Internal`.

**Comment by voidzcy** [comment]
Some other usages: 

- [`StaticTestingClassLoader`](https://github.com/grpc/grpc-java/blob/master/context/src/test/java/io/grpc/StaticTestingClassLoader.java) in `grpc-context`.
- [`ForwardingTestUtil`](https://github.com/grpc/grpc-java/blob/master/api/src/test/java/io/grpc/ForwardingTestUtil.java) in `grpc-api`.
- [`IntegerMarshaller`](https://github.com/grpc/grpc-java/blob/master/api/src/test/java/io/grpc/IntegerMarshaller.java) in `grpc-api`.
- [`StringMarshaller`](https://github.com/grpc/grpc-java/blob/master/api/src/test/java/io/grpc/StringMarshaller.java) in `grpc-api`.


Btw, some utility classes in test scope can be package-private to avoid its access being hacked. Such as 

- [`ReplacnigClassLoader`](https://github.com/grpc/grpc-java/blob/master/api/src/test/java/io/grpc/ReplacingClassLoader.java) in `grpc-api`.
- [`ForwardingScheduledExecutorService`](https://github.com/grpc/grpc-java/blob/master/api/src/test/java/io/grpc/ForwardingScheduledExecutorService.java) in `grpc-api`.

**Comment by ejona86** [comment]
Do not move more things to grpc-testing. This exposes it to users and we know users use it when they copy our unit tests. Things in internal in grpc-testing today would be candidates for _removing_.

For this sort of change, I would want the test code to not published on Maven. That can be done by having a new module that we simply disable publishing.

But in general, we are choosing between evils here. Putting all the test utilities together brings in unnecessary dependencies and means things like grpc-context depend on grpc-core for testing which resembles a circular dependency. We can either keep our dependency tree cleaner from cycles or we use more traditional dependencies; it is hard to have both (without having 2x the projects, to have a -test project for each existing project). Honestly, the cycles concern me more than the small ickiness of the hack. I would strongly prefer to reduce our usage of grpc-testing and lean more heavily into our existing practice, especially in places like [grpc-api](https://github.com/grpc/grpc-java/blob/8d4240f4800f20de0e5f0b7c213577b3c0324f93/api/build.gradle#L26).

To date, the dependency hack has been simple, effective, and not causing problems. It is also very natural in Bazel.

**Comment by dapengzhang0** [comment]
The current internal apis (io.grpc.internal.*) in maven artifacts are the necessary because other public API (e.g. io.grpc.netty) can not run without them. The test utils for our own test usage does not qualify to be internal apis in maven artifacts, because they are not needed at anyu for external users, just junk in the binaries.  The "correct" way to do would be to create a separate test util module for our own test and we never publish it in maven artifacts, but that's overkill.

**Comment by voidzcy** [comment]
Got it. Closing.
