### ISSUE TITLE
http2 on openshift

### ISSUE THREAD

**Issue by elmartinno** [grpc/grpc-java#6860]
Hi everybody,
do you have somebody experience with grpc on openshift? Is possible to configure there a http2 protocol? Thanks

**Comment by ejona86** [comment]
I don't think any of us have any experience with openshift. I don't know who would be able to help. You might try [grpc-io@googlegroups.com](https://groups.google.com/g/grpc-io) and see if you have better luck. Sorry.

**Comment by elmartinno** [comment]
Thanks for response, I have one more question: is needed to set somewhere that i want to use http2 in my java app, or grpc will use http2 default and its not needed to setup?

**Comment by sanjaypujare** [comment]
grpc uses http2 and needs no setup https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
