### ISSUE TITLE
RoundRobinLoadBalancer hangs on subchannels creation

### ISSUE THREAD

**Issue by yann9** [grpc/grpc-java#6914]
### What version of gRPC-Java are you using?
1.23.0
### What is your environment?
Linux  4.9.0-8-amd64  Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
### What did you expect to see?
LoadBalancer will not hangs on subchannels creation
### Steps to reproduce the bug
1. RoundRobinLoadBalancer handle resolved addresses (140+ addresses)
2. RoundRobinLoadBalancer hangs with 158ms before enter READY state  

logs:  (show only one address, omit other 140+ addresses)

```

April 8th 2020, 18:28:47.017   [Channel<1>: (test.service.example)] Exiting idle mode 
April 8th 2020, 18:28:47.018   [Channel<1>: (test.service.example)] Resolved address: [[ [[/172.23.82.208:9000]/{}], ........], config={}
........
........
April 8th 2020, 18:28:47.019   [Channel<1>: (test.service.example)] Child Subchannel started
........
April 8th 2020, 18:28:47.019   [Subchannel<1803>: (test.service.example)] Subchannel for [[[/172.23.82.208:9000]/{}]] created
........
........
........
April 8th 2020, 18:28:47.101   [Subchannel<1803>: (test.service.example)] CONNECTING as requested
........
April 8th 2020, 18:28:47.101   [NettyClientTransport<1943>: (/172.23.82.208:9000)] WaitUntilActive started
........
April 8th 2020, 18:28:47.101   [Subchannel<1803>: (test.service.example)] Started transport NettyClientTransport<1943>: (/172.23.82.208:9000) 
........
April 8th 2020, 18:28:47.102   [id: 0xbad360c1, L:/172.23.90.136:53068 - R:/172.23.82.208:9000] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
........
April 8th 2020, 18:28:47.102   [id: 0xbad360c1, L:/172.23.90.136:53068 - R:/172.23.82.208:9000] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192} 
........
April 8th 2020, 18:28:47.102   [NettyClientTransport<1943>: (/172.23.82.208:9000)] WaitUntilActive completed
........
April 8th 2020, 18:28:47.102   [id: 0xbad360c1, L:/172.23.90.136:53068 - R:/172.23.82.208:9000] INBOUND SETTINGS: ack=false settings={}
........
April 8th 2020, 18:28:47.103   [id: 0xbad360c1, L:/172.23.90.136:53068 - R:/172.23.82.208:9000] INBOUND SETTINGS: ack=true
........
April 8th 2020, 18:28:47.103   [id: 0xbad360c1, L:/172.23.90.136:53068 - R:/172.23.82.208:9000] OUTBOUND SETTINGS: ack=true
........
........
April 8th 2020, 18:28:47.103   [Subchannel<1803>: (test.service.example)] READY
........
........
April 8th 2020, 18:28:47.173   [Channel<1>: (test.service.example)] Entering READY state
........
........
April 8th 2020, 18:28:47.175   [id: 0xbad360c1, L:/172.23.90.136:53068 - R:/172.23.82.208:9000] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=19
April 8th 2020, 18:28:47.175   [id: 0xbad360c1, L:/172.23.90.136:53068 - R:/172.23.82.208:9000] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=19 bytes=000000000e0a0c326433633861366536633861
April 8th 2020, 18:28:47.175   [id: 0xbad360c1, L:/172.23.90.136:53068 - R:/172.23.82.208:9000] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: test.service.example, :path: /test.service.example.v1.Call/Infos, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.23.0 , grpc-accept-encoding: gzip, grpc-timeout: 42629551n] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
```

**Comment by dapengzhang0** [comment]
The channel takes 158ms to get READY, but why do you say RoundRobinLoadBalancer is hanging? I don't see any evidence. RoundRobinLoadBalancer.handleResolvedAddresses() returns in a few ms, a lot earlier than the channel get READY.

**Comment by yann9** [comment]
```
April 8th 2020, 18:28:47.019   [Subchannel<1803>: (test.service.example)] Subchannel for [[[/172.23.82.208:9000]/{}]] created
........
........
........
April 8th 2020, 18:28:47.101   [Subchannel<1803>: (test.service.example)] CONNECTING as requested
```
Please see the log above，`Subchannel<1803>` start creation until request connecting elapsed 82ms, I think some thing happened, hangs or blocking? In my production environment. Channel deadline are typically around 200ms，but channel spent most time for waiting balancer get READY，only a short time left to finish gRPC calls.

**Comment by dapengzhang0** [comment]
It takes time for the channel to get READY, the first blocking RPC is blocked during that period, but the balancer is not hanging. If you want the RPC deadline not to include the period before channel getting READY, you can first wait the channel to be READY then call your first RPC, then the RPC will response instantaneously, like below.
```java
CountDownLatch latchUntilChannelReady = new CountDownLatch(1);
ConnectivityState currentChannelState = managedChannel.getState(true);
if(currentChannelState != ConnectivityState.READY) {
  managedChannel.notifyWhenStateChanged(
      currentChannelState, latchUntilChannelReady::countDown)
}
latchUntilChannelReady.await();
// call the first RPC now
```

**Comment by yann9** [comment]
This seems like a solution,Is there any others solution?  Like async batch create subchannel in balancer etc, Wait the channel to be READY then call the RPCs will cause huge code refactor…

**Comment by dapengzhang0** [comment]
Suchchannel creation in balancer is already async to the RPC. You can add code for wait channel to be READY right after you create the channel from  the channel builder. Normally you just create the channel only once.

**Comment by yann9** [comment]
Okay,  I will try it. But I think there is a same issue like channel enter idle mode and then call RPCs balancer will recreate subchannels.

**Comment by yann9** [comment]
@dapengzhang0 

> a same issue like channel enter idle mode and then call RPCs balancer will recreate subchannels.

Is there any suggestion?

**Comment by dapengzhang0** [comment]
>Is there any suggestion?

Seems you are asking for setting a "deadline" around 200ms but this "deadline" should not include the time for channel getting READY.  In general we don't have anything for that other than manually waiting for channel to become READY (as in https://github.com/grpc/grpc-java/issues/6914#issuecomment-612100338) before issuing each call. 

A possible solution is: instead of setting a Deadline for the Stub, use an interceptor for the stub, and let the interceptor wait for channel to become READY first and then issue a call with a deadline.

```java
class WaitForChannelReadyInterceptor implements ClientInterceptor {
  final ManagedChannel managedChannel;

  @Override
  <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(
      MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {
    waitForChannelReady();
    // issue a call with a deadline
    return next.newCall(method, callOptons.withDeadlineAfter(200, ms))
  }

  private void waitForChannelReady() {
    ConnectivityState currentChannelState = managedChannel.getState(true);
    while (currentChannelState != ConnectivityState.READY) {
      CountDownLatch latchUntilChannelReady = new CountDownLatch(1);
      managedChannel.notifyWhenStateChanged(
          currentChannelState, latchUntilChannelReady::countDown)
      boolean expired = !latchUntilChannelReady.await(someTimeout);
      if (expired) return;
    }
   }
  }
}
```

The downside of this approach is that every time you call something like `stub.sayHello()`, it will block until the channel to become READY. But if all your RPCs are blocking unary calls, then that won't cause a problem.

**Comment by ejona86** [comment]
Closing because the question seems answered. If not, comment and we can reopen.
