### ISSUE TITLE
Bug / FR: Shaded Netty artifact doesn't include Netty-Epoll or Netty tcnative

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#6917]
### What version of gRPC-Java are you using?
1.20

### What is your environment?
Linux / Mac

Netflix uses the shaded netty jar in its gRPC applications.   This jar helps avoid netty conflicts, but fails to load Netty Epoll/KQueue, as well as Netty TCnative.   This results in subpar performance of gRPC, notably in allocation profiling.  I think this is nearly a bug, since these libraries should likely be the default, and it's difficult to enable them with the shaded artifacts.  Thus, I am suggesting that these deps be shaded and included for developer convenience.

If this is not feasible, it would be really helpful to include some example code showing how grpc users can do this themselves (perhaps in ALTS / GCP artifacts?)

**Comment by dapengzhang0** [comment]
I think v1.20 does include tcnative, but it does not include epoll (v1.28.0 does).

Note that even it includes them, they may not work for all system because shading doesn't relocate JNI very well.

```sh
$ ./gradlew grpc-netty-shaded:shadowJar

$ jar tvf netty/shaded/build/libs/grpc-netty-shaded-1.20.0.jar | grep tcnative
     0 Thu Apr 09 16:48:20 PDT 2020 io/grpc/netty/shaded/io/netty/internal/tcnative/
   399 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/Buffer.class
  3713 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/Library.class
  9112 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/CertificateVerifier.class
   654 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/SSLTask.class
  3929 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/NativeStaticallyReferencedJniMethods.class
   206 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/SniHostNameMatcher.class
  7015 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/SSL.class
   668 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/CertificateRequestedCallback.class
  1282 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/SessionTicketKey.class
   561 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/CertificateCallback.class
  1106 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/CertificateCallbackTask.class
  3533 Fri Mar 01 18:35:50 PST 2019 io/grpc/netty/shaded/io/netty/internal/tcnative/SSLContext.class
2504823 Fri Mar 01 19:55:56 PST 2019 META-INF/native/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64.so
2330112 Fri Mar 01 19:55:56 PST 2019 META-INF/native/io_grpc_netty_shaded_netty_tcnative_windows_x86_64.dll
2471140 Fri Mar 01 19:55:56 PST 2019 META-INF/native/libio_grpc_netty_shaded_netty_tcnative_osx_x86_64.jnilib
     0 Thu Apr 09 16:48:20 PDT 2020 META-INF/maven/io.netty/netty-tcnative-boringssl-static/
 25185 Fri Mar 01 19:42:10 PST 2019 META-INF/maven/io.netty/netty-tcnative-boringssl-static/pom.xml
   131 Fri Mar 01 19:55:58 PST 2019 META-INF/maven/io.netty/netty-tcnative-boringssl-static/pom.properties
```

**Comment by carl-mastrangelo** [comment]
@dapengzhang0 It may be present in the jar, but I can confirm that it is not actually used.  Netty should have support for loading shaded native libraries.   I think it may not be so much work to get it wired up correctly.

**Comment by dapengzhang0** [comment]
I can verify that the shaded tcnative is working on my local machine. How to verify if epoll is working?

**Comment by ejona86** [comment]
@creamsoup also tested that epoll worked, since we are using it for TCP_USERTIMEOUT. So we have tested epoll works. We could maybe add a test to [ShadingTest](https://github.com/grpc/grpc-java/blob/master/netty/shaded/src/testShadow/java/io/grpc/netty/shaded/ShadingTest.java) to notice if there is an issue, but right now there is no indication something is broken.

**Comment by carl-mastrangelo** [comment]
@ejona86 ok.   I did some more digging and a library on our side is disabling it.  

I kind of recall a recentish version of gRPC using Conscrypt by default.  If this works in the shaded version then I think there is nothing more to do here.

**Comment by ejona86** [comment]
Yeah, a recentish version will use Conscrypt if it is on the classpath, not requiring it to be added to the list of providers. That should work without issue with grpc-netty-shaded.

**Comment by ejona86** [comment]
It seems like this is resolved (or likely to be). It can be reopened if that's not the case.
