### ISSUE TITLE
How to support existing REST APIs written in Java

### ISSUE THREAD

**Issue by sk1188** [grpc/grpc-java#6919]
We have a microservices written in java where we have exposed REST APIs being consumed by  various clients.We want to migrate to gRPC while supporting the old clients.
I came across the **grpc-gateway**  but it has to be implemented in Go which I don't want to use.
So how to support existing REST APIs written in Java ?

**Comment by sanjaypujare** [comment]
Have you looked into this https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#grpc-transcoding and [HttpRule](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#google.api.HttpRule)?

There is a related issue https://github.com/grpc/grpc-java/issues/6789 that you might find useful

**Comment by sk1188** [comment]
@sanjaypujare  Thanks for the pointers. Transcoding HTTP/JSON to gRPC will surely solve my problem.
I have made the changes to .proto file 
`service GreetService{
	//unary
	rpc Greet(GreetRequest) returns (GreetResponse){
		 option (google.api.http) = {
		    get: "/v1/{num}"
		};
	};
}`

But unable to find any pointers on how to deploy the REST endpoints on the local machine / prod.

**Comment by sanjaypujare** [comment]
Sorry, just realized there is no code in grpc-java that will do the transcoding and host the endpoints. So the options you have are:
- use the grpc-gateway as a proxy (you did say you didn't want to use it)
- check if there is a 3rd party solution like an OSS library that works with grpc-java the way you want.

**Comment by ejona86** [comment]
Seems like the question is answered. If not, please post a comment and we can reopen.
