### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by juanpedromoreno** [grpc/grpc-java#6926]
[mu-scala](https://github.com/higherkindness/mu-scala) is a Scala wrapper atop of gRPC. Currently, it's at gRPC 1.28.x and we've observed performance degradation. [Details here](https://github.com/higherkindness/mu-scala/issues/870).

As you can see in the comparative, the big hop happened with the 1.27.x release, with this new feature:

> netty: set -Dio.grpc.netty.useCustomAllocator=true by default (#6528). This causes grpc to use a different Netty allocator by default which is configured to allocate in smaller chunks which may reduce memory usage by 8x on lightly loaded systems. Performance benchmarks show virtually no change with any potential slowdowns hidden in the noise (~1%). See also #6407. If you notice problems, set the property to false and file an issue

I’ve tried to revert it back (using that java system property to false) but nothing changed apparently, so the problem may be somewhere else :thinking_face: . I didn’t check the okhttp version though.

Am I missing something? Could you please point me out to any other grpc benchmarking reference? Thanks.

**Comment by sanjaypujare** [comment]
@zhangkun83, do you have any comments?

**Comment by zhangkun83** [comment]
It appears the key passed to `getProperty()` is modified to `io.grpc.netty.shaded.io.grpc.netty.useCustomAllocator` by the shader. @juanpedromoreno can you try setting that property instead and see if the performance restores?

@ejona86, how can we avoid shading that property key?

**Comment by ejona86** [comment]
Netty-shaded uses shaded property names. That's just how Netty works. I don't see that as a bug, and it is probably a bad idea to try and avoid it, since the different instances of Netty can behave differently.

**Comment by juanpedromoreno** [comment]
Thanks for your comments.

@zhangkun83 I've tried by setting `io.grpc.netty.shaded.io.grpc.netty.useCustomAllocator` as `false` in my micro-benchmarks, and apparently, the results are quite similar.

I've tried by providing it in two different ways:

- Passing the system property with `-Dio.grpc.netty.shaded.io.grpc.netty.useCustomAllocator=false`, and, 
- Directly in the code: `System.setProperty("io.grpc.netty.shaded.io.grpc.netty.useCustomAllocator", "false")`

However, the performance didn't restore :(

**Comment by zhangkun83** [comment]
I have pushed a snapshot build with #6930 to the snapshot repo.
Please try adding:
```gradle
maven {
  url 'https://oss.sonatype.org/content/repositories/snapshots/'
}
```
to your `repositories {}`, and look for the logs added in that PR. That will tell us whether the property is correctly read. Because it's FINE-level logging, you'll need a logging config file like this:
```
handlers=java.util.logging.ConsoleHandler
io.grpc.netty.level=FINE
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
```
and pass the config file to `-Djava.util.logging.config.file=<config-file-name>`

**Comment by juanpedromoreno** [comment]
Hi @zhangkun83, thanks for your help.

I spent several hours today making sure that my Scala program is able to show the gRPC `java.util.logging` messages, but I failed :(, even trying to re-send all of them to my logback setup, by using dependencies like:

```
"org.slf4j" % "log4j-over-slf4j" % "1.7.30",
"org.slf4j" % "jul-to-slf4j" % "1.7.30",
"org.slf4j" % "jcl-over-slf4j" % "1.7.30",
"org.slf4j" % "slf4j-api" % "1.7.30",
"ch.qos.logback" % "logback-core" % "1.1.8",
"ch.qos.logback" % "logback-classic" % "1.1.8"
```

Anyway, independently if set `false` or `true` in the next system properties:

```
System.setProperty("io.grpc.netty.shaded.io.grpc.netty.useCustomAllocator", "false")
System.setProperty("io.grpc.netty.useCustomAllocator", "false")
```

Netty is always using the pooled allocator. See [this output ](https://gist.github.com/juanpedromoreno/9b5147022a865f221752560ab05d389b) as an example, concretely at [the line 41](https://gist.github.com/juanpedromoreno/9b5147022a865f221752560ab05d389b#file-example-out-L41). That's making me think that the provided system properties are not being taken into account 🤔

**Comment by zhangkun83** [comment]
Sorry, it seems my upload was not successful, despite that `./gradlew uploadArchives` succeeded. That's why you don't see the relevant logs. @ejona86 is there something else I need to do to upload a snapshot?

**Comment by ejona86** [comment]
@zhangkun83, we no longer use `uploadArchives` since we swapped to the newer publish plugin. Use `./gradlew publish` instead.

**Comment by zhangkun83** [comment]
I have uploaded the snapshot and verified that it works. @juanpedromoreno could you please try again?

**Comment by juanpedromoreno** [comment]
Thanks, now I'm able the logs you introduced.

### Using `customAllocator = true`

```scala
System.setProperty("io.grpc.netty.shaded.io.grpc.netty.useCustomAllocator", "true")
```

```bash
DEBUG - Using custom allocator: forceHeapBuffer=false, defaultPreferDirect=true
DEBUG - Creating allocator, preferDirect=true
DEBUG - Forcing maxOrder=8
DEBUG - Using custom allocator: forceHeapBuffer=false, defaultPreferDirect=true
```

### Using `customAllocator = false`

```scala
System.setProperty("io.grpc.netty.shaded.io.grpc.netty.useCustomAllocator", "false")
```

```bash
DEBUG - Using default allocator
DEBUG - -Dio.grpc.netty.shaded.io.netty.leakDetection.level: simple
DEBUG - -Dio.grpc.netty.shaded.io.netty.leakDetection.targetRecords: 4
DEBUG - -Dio.netty.allocator.numHeapArenas: 32
DEBUG - -Dio.netty.allocator.numDirectArenas: 32
DEBUG - -Dio.netty.allocator.pageSize: 8192
DEBUG - -Dio.netty.allocator.maxOrder: 11
DEBUG - -Dio.netty.allocator.chunkSize: 16777216
DEBUG - -Dio.netty.allocator.tinyCacheSize: 512
DEBUG - -Dio.netty.allocator.smallCacheSize: 256
DEBUG - -Dio.netty.allocator.normalCacheSize: 64
DEBUG - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
DEBUG - -Dio.netty.allocator.cacheTrimInterval: 8192
DEBUG - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
DEBUG - -Dio.netty.allocator.useCacheForAllThreads: true
DEBUG - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
DEBUG - -Dio.netty.allocator.type: pooled
DEBUG - -Dio.netty.threadLocalDirectBufferSize: 0
DEBUG - -Dio.netty.maxThreadLocalCharBufferSize: 16384
DEBUG - Using default allocator
```

Let me recheck the benchmarks. I'll be back with the results :)

**Comment by juanpedromoreno** [comment]
Hi all, in the end, I've re-written my benchmarks code. Basically, I've replaced the in-process server by a "real" server. Benchmarking is now slower in general terms, but they are more accurate, and the performance has been restored. Thanks so much for your help and time.

**Comment by zhangkun83** [comment]
@juanpedromoreno, did you still need to set the system property in order to restore the performance?

**Comment by juanpedromoreno** [comment]
No, I didn't. I'm getting quite similar results using `true` and `false` for the `customAllocator` system property, so I left the default value. Thanks.
