### ISSUE TITLE
happens-before in StreamObserver

### ISSUE THREAD

**Issue by cangencer** [grpc/grpc-java#6929]
It's not clear to me what concurrency guarantees are provided in `StreamObserver`. For example given below where the observer is converted to a future:

```java
private static class Observer<R> implements StreamObserver<R> {
    private final CompletableFuture<R> future;

    private volatile R value ;

    Observer() {
        this.future = new CompletableFuture<>();
    }

    @Override
    public void onNext(R value) {
        this.value = value;
    }

    @Override
    public void onError(Throwable t) {
        future.completeExceptionally(GrpcUtil.translateGrpcException(t));
    }

    @Override
    public void onCompleted() {
        future.complete(value);
    }
}
```

Given that `onError`/`onNext`/`onCompleted` may be called from different threads, is there a _happens-before_ relationship (according to the Java Memory Model) between subsequent calls to the observer or not, assuming the observer is not shared between multiple calls? This is not documented anywhere. If there is a happens-before, then the `volatile` on `value` is redundant, if not, then it would be required.

**Comment by sanjaypujare** [comment]
Used for incoming messages, `onCompleted` (or  `onError`) is the last method called as the documentation of `StreamObserver` says which implies `onNext` happens-before `onCompleted` or `onError` when called from the same event loop. But let me ask @ejona86 to comment about guarantees.

**Comment by ejona86** [comment]
StreamObserver is documented to be not-thread-safe. So there is always a strict ordering to the callbacks.

Note that gRPC provides a Future stub, so you don't need to implement any StreamObserver→Future conversion. It does not use any synchronization for the callbacks (StreamObserver is a small shim on top of ClientCall.Listener, so behave similarly):
https://github.com/grpc/grpc-java/blob/9618af90e5a28904d3d7f451bab82f3dbf21e4cf/stub/src/main/java/io/grpc/stub/ClientCalls.java#L468-L504

**Comment by cangencer** [comment]
@ejona86 Yes I also noted those classes and lack of `volatile` on the fields shared between callbacks. From my understanding, the callbacks may be invoked from different threads, so you're saying that somewhere else in the stack a happens-before is ensured between subsequent calls to the `Listener`? Otherwise you may have a data race (i.e. observing partially constructed response objects).

**Comment by ejona86** [comment]
@cangencer, yes, there is a happens-before, which is always mandatory when calling non-thread-safe code. I understand that lacking a happens-before would cause bugs, and so when I say it is being handled as a non-thread-safe code I mean that we have done the things necessary. If we failed to do so, it would be a bug.

**Comment by cangencer** [comment]
thanks! closing this.

**Comment by mtopolnik** [comment]
I would add to this that it would be very helpful if the Javadoc of `StreamObserver` explicitly mentioned the existence of _happen-before_ between callback invocations. This way you refer to the concept straight from the Java Language Specification and there is no doubt left.

**Comment by ejona86** [comment]
That's looking at it the wrong way. We don't define what the callers have to do, we define what is required of an implementation. And an implementation can ignore thread-safety, but should be aware that ThreadLocals can be inconsistent. To make that safe, the caller has to synchronize. The most precise language of the style you are asking for would be "StreamObserver callers must be _sequentially consistent_." But that is just going to get misunderstood.

"Implementations are not required to be thread-safe (but should be thread-compatible)" (which includes a link) is very clear. And if it wasn't it repeats itself from the opposite viewpoint "Since individual StreamObservers are not thread-safe, if multiple threads will be writing to a StreamObserver concurrently, the application must synchronize calls."

**Comment by mtopolnik** [comment]
>StreamObserver callers must be sequentially consistent.

This is pretty much equivalent to stating there's a _happens-before_ between calls, though. Here are the relevant quotes from the [JLS](https://docs.oracle.com/javase/specs/jls/se11/html/jls-17.html#jls-17.4.5):

>When a program contains two conflicting accesses (§17.4.1) that are not ordered by a happens-before relationship, it is said to contain a data race.
>
>A program is _correctly synchronized_ if and only if all sequentially consistent executions are free of data races. If a program is correctly synchronized, then all executions of the program will appear to be sequentially consistent (§17.4.3).

As an implementor, I know what I have to do when I know the guarantees provided by the caller side. "Not thread-safe" can mean a lot of things and it doesn't give me the exact guideline on what scenarios I have to protect from. There is no steadfast, precise definition of "thread-safe", but there is of _happens-before_.

**Comment by mtopolnik** [comment]
So, a simple sentence like "each call may come from a different thread, but all calls will be ordered by _happens-before_ gives me the clearest idea of the concurrent environment I am coding agains.
