### ISSUE TITLE
Is it possible to run gRPC service inside a tomcat container ? 

### ISSUE THREAD

**Issue by sk1188** [grpc/grpc-java#6933]
I have a Spring Boot application running on a tomcat server with a few REST endpoints exposed.

As gRPC can be deployed as a standalone service , it manages it’s own connections and port. Wouldn’t it be problematic to go with this approach of running it on a tomcat server ?

**Comment by creamsoup** [comment]
there was an effort to provide a layer on top of servlet api to use gRPC server.
you may find  #1621 and the implementation #4738 useful. 

cc @dapengzhang0 who drove the effort

**Comment by dapengzhang0** [comment]
If you don't share the gRPC port with REST port, then there is no problem at all. There are also tools to manage gRPC with spring boot (e.g. https://github.com/yidongnan/grpc-spring-boot-starter) .

**Comment by ejona86** [comment]
Seems like the question is answered. If it isn't, comment and we can reopen.
