### ISSUE TITLE
Add ability to change backoff policy

### ISSUE THREAD

**Issue by jared2501** [grpc/grpc-java#6952]
The gRPC Go APIs allow you to configure the exponential backoff policy, can we get the APIs same APIs in java? There is in fact a [TODO](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java#L514) to add this feature!

Use case is that I'm running a set of services locally. I would like to set the maximum retry backoff to 5 seconds, since there's no chance of causing excessive load to any sort of cluster.

**Comment by creamsoup** [comment]
this was discussed not too long ago. IIRC we decided to remove the TODO, but it didn't happen.

please see #6873 for more details.

**Comment by ejona86** [comment]
The TODO was removed in #6953

**Comment by ejona86** [comment]
I think there will need to be an argument made why this is necessary. It would be good to know in what cases the backoff is necessary (why is the server inaccessible) and how did you choose 5 seconds? It'd also be good to know how long the server will typically be inaccessible.

**Comment by ejona86** [comment]
Closing due to lack of a reply. We'd be happy to reopen if we get some more information.
