### ISSUE TITLE
SSLException: handshake timed out due to long java GC pauses and default handshake timeout being 10 secs

### ISSUE THREAD

**Issue by pynandan** [grpc/grpc-java#6971]
We have a service which establishes 1000s of ssl based grpc connections to our backend servers, while trying to process a lot of other data. Due to this we encounter long java GC pauses, sometimes >10 secs.

The default handshake timeout is 10 secs (https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L413) 
As a result of this, we encounter multiple handshake timeout errors in the order 1000s as well. Is there a reason why this is not exposed to the client? so that the caller can change the value.

Is there any other alternative approach to solve this and not encounter so many handshake timeouts. May be an interceptor and queue up the requests if the handshake is not complete?

**Comment by voidzcy** [comment]
GC pauses > 10 secs, that's very long. There is no way to work around SSL handshake timeout. Even if requests are queued, there is no way to retry the handshake. See if @ejona86 has any thought.

**Comment by ejona86** [comment]
We don't expose knobs like this because there are thousands of such knobs and they can be implementation-specific, which means we then ossify the implementation. The other reason is you are the first person that has opened an issue about it.

Generally our approach is to dynamically adapt to situations like this, so users don't have to deal with hard-coded numbers. This could be handled as part of https://github.com/grpc/grpc-java/issues/1943, which would increase the timeout with each attempt.

It'd be good to understand a bit more about the behavior of these 1000s of connections. Are these short-lived connections, or are they created en masse at your service start, or something else? Channels automatically reconnect, and it seems the reconnect is likely to succeed. This TLS timeout would seem to mostly be a problem if the channel is intended to be used once and then destroyed.

**Comment by ejona86** [comment]
> May be an interceptor and queue up the requests if the handshake is not complete?

That sounds very similar to [`withWaitForReady()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withWaitForReady--). See https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md for its definition. Basically, it is saying you are willing to wait for a good connection, even if it looks like there are problems creating a connection. Normally after the TLS handshake failure the channel would go into TRANSIENT_FAILURE and fail any queued RPCs.

**Comment by ejona86** [comment]
> Due to this we encounter long java GC pauses, sometimes >10 secs.

One other thing. Is ">10 secs" meaning something like "11 seconds" or things like "30 seconds"?

**Comment by pynandan** [comment]
@ejona86 Yes, tried waitForReady earlier, but that does not work since the RPC still fails on TRANSIENT_FAILURE states. Right now, we throw away the client on any ssl error. I guess one other option is to not do that.

Yes, these channels are long lived and encounter these issues only during startup, when service is loaded with other initialization processes, and hence GC is in the order of 10-15 secs.

**Comment by pynandan** [comment]
What is the default retry logic for channel reconnection, cant seem to find them? Is there any way to change them if at all?

**Comment by ejona86** [comment]
> Yes, tried waitForReady earlier, but that does not work since the RPC still fails on TRANSIENT_FAILURE states

No it doesn't. The _only_ thing it does differently is _not_ failing on TRANSIENT_FAILURE. From [wait-for-ready.md](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md):

> gRPC implementations MAY provide a per-RPC option to not fail RPCs as a result of the channel being in TRANSIENT_FAILURE state. Instead, the implementation queues the RPCs until the channel is READY. This is known as "wait for ready."

If you are still seeing failures with waitForReady enabled, something else may be at play.

> Right now, we throw away the client on any ssl error. I guess one other option is to not do that.

Yes, definitely do not do that. gRPC reconnects with exponential backoff as defined in [connection-backoff.md](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md). grpc-java doesn't _exactly_ follow that algorithm, but it mostly follows it. The main thing grpc-java fails to do is _limit_ the connect time (it could go on for minutes when we want it to stop after 20 seconds).

> Yes, these channels are long lived and encounter these issues only during startup

Ah, okay. Then yeah, if you avoid re-creating the Channels they should fix themselves.

If your service can avoid receiving traffic its your dependencies are "ready," you can use [`managedChannel.getState(true)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannel.html#getState-boolean-) along with [`notifyWhenStateChanged()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannel.html#notifyWhenStateChanged-io.grpc.ConnectivityState-java.lang.Runnable-) to "prep" the channels and learn when they are successfully connected.

**Comment by pynandan** [comment]
> No it doesn't. The _only_ thing it does differently is _not_ failing on TRANSIENT_FAILURE. From [wait-for-ready.md](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md):
> 
> >

You are right, it does look like it works as expected. My bad.

> Yes, definitely do not do that. gRPC reconnects with exponential backoff as defined in [connection-backoff.md](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md). grpc-java doesn't _exactly_ follow that algorithm, but it mostly follows it. The main thing grpc-java fails to do is _limit_ the connect time (it could go on for minutes when we want it to stop after 20 seconds).
> 
> >

Does that mean that once this is fixed, after 20 secs, there would be no retries? and no way to reset and start the retry all over again?

> If your service can avoid receiving traffic its your dependencies are "ready," you can use [`managedChannel.getState(true)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannel.html#getState-boolean-) along with [`notifyWhenStateChanged()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannel.html#notifyWhenStateChanged-io.grpc.ConnectivityState-java.lang.Runnable-) to "prep" the channels and learn when they are successfully connected.

Thats a good idea. We already use [`notifyWhenStateChanged()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannel.html#notifyWhenStateChanged-io.grpc.ConnectivityState-java.lang.Runnable-) for debugging and metrics on channel state transitions.

**Comment by ejona86** [comment]
> Does that mean that once this is fixed, after 20 secs, there would be no retries? and no way to reset and start the retry all over again?

No. The doc is a bit hard to read, but basically as we exponentially backoff we'll get to a point where we are waiting ~30 seconds between retry attempts. Each attempt would be able to use all of that that time, so the timeout will grow with each attempt until it gets 2 minutes for the attempt. (There are some details involved, like whether _TLS for one connection_ would get all of that time, but there is purposefully an increasing of the timeouts when things look bad.)

**Comment by pynandan** [comment]
Thanks for the explanation.

Also, reading through the discussion here - https://github.com/grpc/grpc-java/pull/6873 , is the recommendation to use `ManagedChannel.resetConnectBackoff()` if we wanted to retry sooner than what the backoff policy provides?

`ChannelLogger: [Subchannel<240331>: (....)] TRANSIENT_FAILURE (UNAVAILABLE(io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0])). Will reconnect after -12,575,119,575 ns`

Since the current policy is 1 secs initial wait, we are seeing it retry immediately as shown above (its negative due to ~12 secs GC pause). But would like to have a way to retry immediately if the wait time was something else. What is the recommendation?

**Comment by ejona86** [comment]
`resetConnectBackoff()` is intended for cases where "you know something that gRPC doesn't." The most obvious case of that is on Android where the OS notifies the application when network interfaces change. If a new network interface comes online, that's a strong signal that things may be operational again. So `resetConnectBackoff()` isn't well suited to your case.

Because of the negative retry time, the channel _would_ retry immediately. We choose when we will retry based on when we _started_ the previous attempt, so if that attempt takes a long time due to a GC, that does not penalize when the retry will occur (other than being stuck in the previous attempt due to GC). (We still only do one attempt at a time, so a long attempt can delay the retry, but we don't do any extra sleep()s for the backoff if enough time has passed.)

**Comment by voidzcy** [comment]
Based on discussions going on, I suspect you should be able to make RPCs successfully with `waitForReady()` as transport retries immediately after the first failure due to GC. 

FWIW, for how the reconnection works, you can look at implementations in [`InternalSubchannel`](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/InternalSubchannel.java), especially things in [`TransportListener`](https://github.com/grpc/grpc-java/blob/d605faafc39d1bf6568a1016364fee5b77c7c02c/core/src/main/java/io/grpc/internal/InternalSubchannel.java#L533).

**Comment by pynandan** [comment]
@ejona86 I was able to tweak with a few more configurations and found that the SSL handshake of some connections were blocking others, and this made it worse by the fact the default no. of event loop threads = no. of cores. I changed that and saw good improvement.

But I had a follow up question - Now I see that there is direct memory initialization contention now during startup ie, mainly in `io.netty.buffer.PoolArena::allocate`

I changed these default values to these - 

`-Dio.netty.allocator.maxOrder=7 -Dio.netty.eventLoopThreads=216 -Dio.netty.allocator.numHeapArenas=216 -Dio.netty.allocator.numDirectArenas=216 -Dio.netty.handler.ssl.openssl.useTasks=true`

This seems to improve it quite a bit.

Do you have any other suggestions? Is 1M chunk size or even smaller good? We have some traffic patterns which can go up to 20M+ payloads.

**Comment by ejona86** [comment]
> found that the SSL handshake of some connections were blocking others, and this made it worse by the fact the default no. of event loop threads = no. of cores. I changed that and saw good improvement.

Interesting. Any "blocking" should be CPU-bound, so increasing number of event loops shouldn't increase the rate. I guess the "costly" parts of the handshake were delaying the "cheap" parts of the handshake.

> -Dio.netty.handler.ssl.openssl.useTasks=true

With this option is there still a gain by using more event loops? And for the record, I'd only expect this option to do anything starting in grpc-java v1.27.0.

> But I had a follow up question - Now I see that there is direct memory initialization contention now during startup ie, mainly in io.netty.buffer.PoolArena::allocate
>
> I changed these default values to these -
> -Dio.netty.allocator.maxOrder=7

CC @zhangkun83 

Interesting. That _reduces_ the max order from grpc's default of 8 (Netty's default is 11). It's not clear to me how that would end up helping, but I'm not _that_ familiar with Netty's allocator. 

20 MB payloads will get split by grpc into multiple 1 MB buffers for the outbound path, and incoming path will be based on the read() chunk size which will be measured in KB.

**Comment by pynandan** [comment]
This is what I am running with - 
GRPC version: 1.29.0
Netty version: 4.1.48.Final

Also we use BouncyCastle which unfortunately has some `synchronized` blocks which are run during the TLS handshake. This is what causes contention in the IO thread. Offloading it helps it quite a bit.

> Interesting. That _reduces_ the max order from grpc's default of 8 (Netty's default is 11). It's not clear to me how that would end up helping, but I'm not _that_ familiar with Netty's allocator.

What I was seeing is contention in this method where there are synchronized blocks - 
[PoolArena::allocate](https://github.com/netty/netty/blob/ff6d2e4949caaa573ac693562de42aaefa42fee3/buffer/src/main/java/io/netty/buffer/PoolArena.java#L175)
My guess was reducing the chunk size could reduce the time spent in these synchronized blocks and hence reduce contention. Saw some improvement, ~10% I would say in reduction of each time for each IO thread getting blocked. Any other suggestions are welcome.

> Also, is there any way to warm up the thread local PoolThreadCache?

Any suggestions on this?

**Comment by ejona86** [comment]
> Also, is there any way to warm up the thread local PoolThreadCache?

I don't believe so, other than doing an RPC. When using the default allocator, you could allocate and free something using the Netty API.

I have been considering for a while using unpooled heap buffers for small outbound messages. But that's subtle performance work.
