### ISSUE TITLE
wrong version on readme?

### ISSUE THREAD

**Issue by jhc0025** [grpc/grpc-java#6975]
Hello.
I think there is a small failure on gradle non-Android dependencies readme.md

This are the gradle dependencies writted on documentation:
```java
implementation 'io.grpc:grpc-netty-shaded:1.29.0'
implementation 'io.grpc:grpc-protobuf:1.29.0'
implementation 'io.grpc:grpc-stub:1.20.0'
```

shouldn't be version **1.29.0** all of them?
Fixing this in my gradle file have solved a lot of cannot find symbol java errors

Best regards
Nacho.

**Comment by sanjaypujare** [comment]
Yes, that seems to be a typo and needs to be fixed
