### ISSUE TITLE
bidi-stream flow control

### ISSUE THREAD

**Issue by xuanyimo** [grpc/grpc-java#6983]
## Problem:

We use grpc bidi-stream in product.

Server -> client data rate about 800MiB/s

It will be OOM , if client consume lower(whatever reason).

## How to control stream memory size ?

I test manual flow control , It is too slow . 

I use ServerCallImpl#isReady() judge stream if can execute onNext().

But  in file grpc-java/core/src/main/java/io/grpc/internal/AbstractStream.java 
```java
   @VisibleForTesting
    public static final int DEFAULT_ONREADY_THRESHOLD = 32 * 1024;
    private boolean isReady() {
      synchronized (onReadyLock) {
        return allocated && numSentBytesQueued < DEFAULT_ONREADY_THRESHOLD && !deallocated;
      }
    }
```

The `DEFAULT_ONREADY_THRESHOLD` is not enough, my single msg about 80KiB, how can i configure this.

**Comment by voidzcy** [comment]
How significant is the slowness for manual control flow? 800 MB/s for 80KB messages, which is 100k ops/s. This seems to be fine for okhttp. For netty, we are currently having some issues that causes it being slower than okhttp (see #6685 and #6696). Did you try turning the flow control window ([OkhttpChannelBuilder#flowControlWindow()](https://github.com/grpc/grpc-java/blob/d605faafc39d1bf6568a1016364fee5b77c7c02c/okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java#L237) or [NettyChannelBuilder#flowControlWindow](https://github.com/grpc/grpc-java/blob/d605faafc39d1bf6568a1016364fee5b77c7c02c/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L253))?

**Comment by xuanyimo** [comment]
1. 800 MB/s for 80KB messages, which is 10k ops/s probably.
2. The problem I considered is the app will OOM when client consume slowly. If I judge `streamObserver.isReady()` can stop the memory allocated infinity. I want let it to OOM.


I will try NettyChannelBuilder#flowControlWindow.

**Comment by voidzcy** [comment]
Oops, you are right, that's 10k ops/s...

I am confused with what you are seeking for. You said your app runs into OOM as the client consumes data slower than server sends, then you tried with manual flow control to solve the OOM problem. Does that not work well or something? What do you mean by you "want let it to OOM"?

**Comment by xuanyimo** [comment]
Ok. Let's check the code:

```java

public void sendData(Object data) {
    if (streamObserver.isReady()) {
        streamObserver.onNext(data);
    } else {
        log.warn("Server stream is full.")
        streamObserver.onComplete();
    }
}

```


The condition `isReady()` can control the memory increment. When the code runs in product,
the log "Server stream is full" was printed all the time. So I consider if the size of `DEFAULT_ONREADY_THRESHOLD` have an influence on it.

The threshold is 32K, single msg size is 80K. The  method `isReady()` will return  false very two times .

**Comment by voidzcy** [comment]
Unfortunately, there is no way for adjusting the buffer size for manual back pressure control. #5433 was opened and https://github.com/grpc/proposal/pull/135 was sent out for discussion, while there hasn't been much progress on it. There might be some other open questions blocking the proposal.

 Given that, you could implement some manual back pressure control logic by ignoring the `isReady` flag for some amount (this is allowed, as documented for [`isReady()`](https://github.com/grpc/grpc-java/blob/d605faafc39d1bf6568a1016364fee5b77c7c02c/stub/src/main/java/io/grpc/stub/CallStreamObserver.java#L65)).

**Comment by voidzcy** [comment]
Closing this issue now. Details and progress of controlling back pressure window is tracked in #5433.
