### ISSUE TITLE
Will there be a flag for generating CompletableFuture methods in the future?

### ISSUE THREAD

**Issue by deanorderly** [grpc/grpc-java#6986]
Coming from twitter with extensive 'scala.Future' use which is just like java's CompletableFuture, I had a question on the roadmap...

I am wondering the roadmap of java-grpc generation and if non-streaming, simple request-response methods will in the future be able to use CompletableFuture like so (perhaps via a grpc gradle plugin configuration change?)...

public CompletableFuture<GrpcResponse> method(GrpcRequest request);

such that synchronous generation is NO LONGER needed.  if you want sync, you can then call it like so

method(request).get(); //synchronous

and otherwise, it is async so I would call it like this

method(request).thenApply( s -> //this is called asynchronously or synchronously if the future is resolved FAST enough which won't happen in remote systems )

thanks,
Dean

**Comment by voidzcy** [comment]
`CompletableFuture` is only introduced since Java 8, while currently we support minimum of Java 7. We use `StreamObserver` of responses to do unary calls asynchronously, from the beginning of gRPC design. Moving to `CompletableFuture` is a big API jump, we do not foresee such a move in the near future.

**Comment by deanorderly** [comment]
interesting.  didn't oracle end of life java 7 in 2015 five years ago?

**yup...definitely a big api jump, agreed.**  I was only wondering as webpieces is completely wired with CompletableFutures and we keep integrating with each libraries own version of CompletableFuture.  netty has one, gRPC has one, etc. etc.

**Comment by deanorderly** [comment]
@voidzcy closing this out.
