### ISSUE TITLE
Tracking issue for ServerCall.getServer()

### ISSUE THREAD

**Issue by voidzcy** [grpc/grpc-java#6989]
Introducing this API to expose the `Server` instance that dispatches the call on `ServerCall` interface. Services that need to access the server (e.g., ProtoReflectionService) can obtain the server reference with a server interceptor, without the callback logic of `NotifyOnServerBuild`.

**Comment by ejona86** [comment]
API review:
 * Question returning null (0 strong votes) vs UnsupportedOperationException (2 votes) (some fine either way). May not know what is best until we get more usage
 * Why not expose Server through Context? Could use an internal Key. It is not as nice to use a private API, but there is uncertainty what others may need. So we can keep it internal until need arises and then we have be more informed for the API design.
 * Decision: put it in Context for now. That is strictly better than the current (broken) InternalNotifyOnServerBuild and solves the immediate issue
