### ISSUE TITLE
Quick question on url path of gRPC protocol...

### ISSUE THREAD

**Issue by deanorderly** [grpc/grpc-java#6995]
@ejona86 @voidzcy as I assume you know this off the top of your head.  On the simple helloworld server (I have the example working of course), I don't see a way to modify the base url that grpc comes in on.  Does grpc have to be the root?  I mean for example, is all grpc protobuf binary forced to come in over https://{host}/ ? 

I think the full url of an endpoint from what I have seen is 

https://{host}/{grpcFullMethod}

where a proto file of package orderly.something and a service called AuthApi and a method called authorize would be

https://{host}/orderly.something.AuthApi/authorize

do I have this correct?  

Oh, and one more thing.  I then assume the content type MUST be specified to application/grpc ?

I was not sure looking at this  https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
which has application/grpc+proto vs. application/grpc+json.

thanks,
Dean

**Comment by ejona86** [comment]
> https://{host}/{grpcFullMethod}

Yes, that's correct. See `:path` (HTTP/2's version of the path in the request line of HTTP/1) https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests

> I then assume the content type MUST be specified to application/grpc

Yes. We currently throw away anything after a `+` in the content-type.

> which has application/grpc+proto vs. application/grpc+json

All implementations should "accept" those, but don't have to do anything with them. That was a feature that was never implemented, until grpc-go implemented it thinking it was implemented elsewhere.

Right now there is no way in grpc-java's client to change the content-type sent. The server would be free to special-case +proto vs +json and decode the bytes differently. As long as json clients used the +json, things could work out fine.

**Comment by deanorderly** [comment]
ah, ok, sweet, thanks @ejona86 .  I may then route application/grpc+json to my json plugin for grpc and then route application/grpc+proto to my weekend hackathon on the binary plugin.

thanks!!!!  I really appreciate all the help you gave me!!

**Comment by deanorderly** [comment]
oh and it helps that we have a client too so I will add it to our client.
