### ISSUE TITLE
Investigate excessive flushing in Netty

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#7]
Determine ways to reduce number of flushes we perform. For example, if the header frame is being sent, flushing afterward is generally a waste since a DATA frame typically follows. We want methods that allow smart semi-automatic flushing or using knowledge from application layer.

**Comment by rschildmeijer** [comment]
@ejona86 would something like a AutoFlushingWriteBatcher[1] be too generic and would apply "smart batching" too often?

[1] https://github.com/spotify/netty-zmtp/blob/master/src/main/java/com/spotify/netty/handler/queue/AutoFlushingWriteBatcher.java

**Comment by ejona86** [comment]
@rschildmeijer, it looks like that one just does regular flushes based on a timer. That wouldn't work for us because it would introduce latency.

Instead, we looked at something more akin to [BetterWriteWithAtomic](https://github.com/stepancheg/netty-td/blob/master/src/com/github/stepancheg/nettytd/BetterWriteWithAtomic.java). As I mentioned though, performance may have improved, but it was mostly lost in the noise. Thus, we are going to focus on other things and then revisit the flushing.

**Comment by rschildmeijer** [comment]
@ejona86 it is regular flusher based on a timer on steroids. If writes are sparse no additional latency will be added.

The functionality is based on the following statement: if mean_time_between_sends < mean_time_to_send, then applying smart batching will improve throughput and reduce netty flush calls.

So consider it and benchmark. Might be worth it in your case. Start with a non default setting(?)

Based on Todds work: https://qconsf.com/sf2012/dl/qcon-sanfran-2012/slides/ToddMontgomery_RunningWithTheDevilMechanicalSympatheticNetworking.pdf

**Comment by nmittler** [comment]
@ejona86 @louiscryan I think this is a dup of #331, #332, and #305.  Can we close this?

**Comment by ejona86** [comment]
I'd like to leave this open until we integrate fixes for https://github.com/netty/netty/issues/3670, which currently doesn't have any other associated issue in gRPC.

**Comment by louiscryan** [comment]
Issue in Netty has now been resolved.
