### ISSUE TITLE
netty should use BDP by default 

### ISSUE THREAD

**Issue by creamsoup** [grpc/grpc-java#7007]
Since now we expose Netty{Channel,Server}Builder#initialWindowUpdate via #6979. We should use it by default.
We probably need to use smaller windowSize than current `DEFAULT_FLOW_CONTROL_WINDOW` 1MB.

**Comment by wujun8** [comment]
@creamsoup Using old versions, from which version manually enable BDP is suggested?
```
    InternalHandlerSettings.enable(true);	
    InternalHandlerSettings.autoWindowOn(true);
```

**Comment by ejona86** [comment]
> We probably need to use smaller windowSize than current DEFAULT_FLOW_CONTROL_WINDOW 1MB.

We will want to reduce the window size, but for now let's keep the initial window size the same. Then over the course of a few releases we could reduce it down to ~64K, which will align with the other languages and greatly reduce the amount of buffering in many systems.

**Comment by ejona86** [comment]
@wujun8, the PR mentioned was just recently merged. It isn't available in a release yet. The next release is [scheduled for June 2nd](https://github.com/grpc/grpc-java/milestone/43).

**Comment by wujun8** [comment]
[**@ejona86**](https://github.com/ejona86) commented on [2020年5月7日 GMT+8 上午12:10](https://github.com/grpc/grpc-java/issues/7007#issuecomment-624742348 "2020-05-06T16:10:36Z - Replied by Github Reply Comments"):
> [@wujun8](https://github.com/wujun8), the PR mentioned was just recently merged. It isn't available in a release yet. The next release is [scheduled for June 2nd](https://github.com/grpc/grpc-java/milestone/43).

I noticed in other libs using grpc, they never enable the BDP switch, if I manually enable BDP, is it OK in old versions? Doing like this in static block:
```
    InternalHandlerSettings.enable(true);	
    InternalHandlerSettings.autoWindowOn(true);
```

**Comment by creamsoup** [comment]
Those internal APIs shouldn't be used by users hence it is internal. It may not work correctly in some environments (that's why the change has some other stuff in it). Unfortunately, java doesn't block you from using it. If you use it, you are on your own.
