### ISSUE TITLE
my grpc-java server has only one tcp connection!

### ISSUE THREAD

**Issue by gdonlyathw** [grpc/grpc-java#7036]
when i test performance of grpc-java server, i find that:   
anyway，my server only has one connection!    the test command is:
ghz  --insecure --proto xxx.proto --call xxx.Service/apply -d '{"name":"sss"}'  -c 10000 -z 900s -t 15s --connections 10000  xxx.xxx.xxx.xxx:80

**Comment by gdonlyathw** [comment]
netstat -nap | wc -l

**Comment by ericgribkoff** [comment]
I think your question is about why your load test program (`ghz`) appears to only be establishing one connection. This would be more appropriate to ask over at https://github.com/bojand/ghz. I'm going to mark this closed as I don't see anything to be done/answered from the grpc java side, as I'm not that familiar with ghz or how its options are applied.

**Comment by gdonlyathw** [comment]
> I think your question is about why your load test program (`ghz`) appears to only be establishing one connection. This would be more appropriate to ask over at https://github.com/bojand/ghz. I'm going to mark this closed as I don't see anything to be done/answered from the grpc java side, as I'm not that familiar with ghz or how its options are applied.

NO，ghz is support establish  many connections,  the same server by grpc-python already   established many connections, but  grpc-java only established  one connection.
