### ISSUE TITLE
How to read stats from census module? 

### ISSUE THREAD

**Issue by arbazkhan002** [grpc/grpc-java#7037]
Hi,
This is more of a user question. Given grpc-census package captures stats by default via CensusStats module, how do I retrieve them? I see that it internally adds server call interceptors which record events but I am not sure how can I expose them or export them elsewhere.

Thanks, in advance.

**Comment by voidzcy** [comment]
You would need to create a [Exporter](https://opencensus.io/exporters/) on client/server that sends stats/tracing to the monitoring system. You can find simple [examples](https://opencensus.io/guides/grpc/java/) in Census documentation. Basically, gRPC already does the RPC instrumentation for you (with grpc-census in runtime classpath), you only need to export it.

**Comment by arbazkhan002** [comment]
@voidzcy I used ZPages to see traces from CensusStats module but no traces show up on the webpage (added prometheus stats collector as well)

```
...
import io.opencensus.contrib.grpc.metrics.RpcViews
import io.opencensus.contrib.zpages.ZPageHandlers
import io.opencensus.exporter.stats.prometheus.PrometheusStatsCollector
import io.opencensus.exporter.trace.jaeger.JaegerTraceExporter
import io.opencensus.exporter.trace.logging.LoggingTraceExporter
import io.prometheus.client.exporter.HTTPServer
....

         ...
         fun main(args: Array<String>) {
           ...
            setupStatsAndExporter()
            // Launch grpc server
            val serverBuilder = NettyServerBuilder
                .forPort(ServiceConfig.PORT)
                .executor(grpcServerThreadPool)
                .addService(myService)
                .addService(ProtoReflectionService.newInstance())
                .maxConnectionAge(ServiceConfig.MAX_CONNECTION_AGE, TimeUnit.SECONDS)
           ...
        }
```
```
        private fun setupStatsAndExporter() {
            RpcViews.registerAllGrpcViews()
            LoggingTraceExporter.register()
            PrometheusStatsCollector.createAndRegister()
            HTTPServer(9091, true)
            ZPageHandlers.startHttpServerAndRegisterAll(9090)
            logger.info("ZPages server starts at localhost:" + 9090)
        }
```

<img width="1555" alt="Screen Shot 2020-05-13 at 5 20 20 PM" src="https://user-images.githubusercontent.com/3316242/81879108-a19aa900-953e-11ea-8c7b-fad41f8228e0.png">

I was seeing examples where devs had put in tags, trace and spans to their service methods which then show up but I was looking to fetch stats/trace from grpc's core methods ie what CensusStats is collecting (latency, message-sizes, send and receive events).

**Comment by voidzcy** [comment]
The usage looks alright. Your zPage is already showing something, isn't it?

**Comment by arbazkhan002** [comment]
That zPage is showing calls made to itself on /statsz and /tracez endpoints but nothing related to stats and traces for the calls made to gRPC server. From what I see, [CensusStatsModule](https://github.com/grpc/grpc-java/blob/master/census/src/main/java/io/grpc/census/CensusStatsModule.java) collects call-level stats and traces for the gRPC server to be reported to opencensus.

For elaboration, look at the screenshot below for the tracez endpoint under server/server_latency view. There are no stats reported for that view while I did send bunch of requests to the server. I see the same for all other views.
<img width="2510" alt="Screen Shot 2020-05-13 at 9 13 43 PM" src="https://user-images.githubusercontent.com/3316242/81892716-aa9c7200-9560-11ea-8da0-ef2efc4cc1a7.png">

**Comment by voidzcy** [comment]
Something might have changed for zPage. Could you please open an issue in [Opencensus repo](https://github.com/census-instrumentation/opencensus-java) for how to use it? We do not have much expertise using it.
