### ISSUE TITLE
Is it possible to manage managedChannel and stub by dynamically changing EquivalentAddressGroup of NameResolver.Factory?

### ISSUE THREAD

**Issue by sungwonkim-muhayu** [grpc/grpc-java#7042]
Is it possible to manage managedChannel and stub by dynamically changing EquivalentAddressGroup of NameResolver.Factory?

I want to load balance by dynamically allocating the grpc server using spring eureka and grpc
on client application.

Below is the code of name resolver...

```
public NameResolver newNameResolver(URI notUsedUri, NameResolver.Args args) {
        return new NameResolver() {
            @Override
            public String getServiceAuthority() {
                return "authority";
                // TODO: 2020-05-15 구현 필요 
            }

            public void start(Listener2 listener) {
                listener.onResult(ResolutionResult.newBuilder().setAddresses(equivalentAddressGroups).setAttributes(Attributes.EMPTY).build());
            }

            public void shutdown() {
                // TODO: 2020-05-15 로직 구현 필요 
            }
        };
    }
```

Below is the code to build a managed channel...
--eureka Name ResolverFactory is extended class from NameResolver.Factory

```
channel = ManagedChannelBuilder
                .forTarget("service")
                .nameResolverFactory(eurekaNameResolverFactory)
                .defaultLoadBalancingPolicy("round_robin")
                .usePlaintext()
                .build();

eurekaLoadBalancerServiceBlockingStub = rekaLoadBalancerServiceGrpc.newBlockingStub(channel);
eurekaLoadBalancerServiceStub = EurekaLoadBalancerServiceGrpc.newStub(channel);
eurekaLoadBalancerServiceFutureStub = EurekaLoadBalancerServiceGrpc.newFutureStub(channel);
```

Sorry for lack of English proficiency. Thank you for your understanding.

**Comment by sungwonkim-muhayu** [comment]
I will fill it out properly and post it again. Sorry.

**Comment by sungwonkim-muhayu** [comment]
I implemented it by dynamically generating a resolver, but I am wondering if there is a function already written.

**Comment by dapengzhang0** [comment]
>I wonder if there is a function already written.

I don't think there is anything for dynamically changing EAG already written.

**Comment by sungwonkim-muhayu** [comment]
Thanks for the answer.

There may be some misunderstanding because English is not good enough.

I am using the new EAG to create a channel and stub, then switching the old channel and stub to update the EAG.

In fact, I doubt that this is the right way ...

Is it possible to add the ability to dynamically update the EAG?

It is necessary for some users to add the function to the library, but I am curious about the idea that it may be overspecified by the developer.

**Comment by dapengzhang0** [comment]
I think you can keep a reference of `listener`, and call `listener.onResult()` with the new EAG whenever you need an update.

**Comment by sungwonkim-muhayu** [comment]
Your answer helped me. 
Thank you.
