### ISSUE TITLE
Support for proto3 field presence

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc-java#7051]
Proto3 introduced the `optional` syntax to support [field presence](https://github.com/protocolbuffers/protobuf/blob/v3.12.0/docs/field_presence.md) tracking in [release 3.12.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0). We need to add support in our grpc protoc plugin.

See [this doc](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md#signaling-that-your-code-generator-supports-proto3-optional) for more details. Basically we need to add a function `GetSupportedFeatures()` to our grpc protoc plugin to mark our compliance.

Please plan to do this in the next release. If not, please let me know. Thanks!

**Comment by stanley-cheung** [comment]
FYI, grpc/grpc PR: https://github.com/grpc/grpc/pull/22998

**Comment by dapengzhang0** [comment]
Do we want the protoc flag `--experimental_allow_proto3_optional` on by default?

**Comment by stanley-cheung** [comment]
Yes please turn it on by default. At first I thought the flag only applies to `protoc`. Looks like it applies to the plugin as well (i.e. will fail the plugin if .proto has the new syntax and the flag is not passed in)? Then yes we do want to turn on the flag by default. Thanks!

**Comment by dapengzhang0** [comment]
Fixed by #7052 and #7054 . Backported to v1.30.x with #7058 .
