### ISSUE TITLE
GRPC access logs

### ISSUE THREAD

**Issue by QeyCoder** [grpc/grpc-java#7056]
I'm migrating my application to **grpc**. Everything working fine but for latency plotting I need access log in tomcat but I'm unable to generate access log. The only solution I found so far is the server interceptor. Doesn't **grpc** support access logging just like we have in tomcat if yes how to enable?

`127.0.0.1 - - [18/May/2020:13:06:28 +0530] "POST /app/api/v1.0/search HTTP/1.1" 200 1931396 1938`

**Comment by sanjaypujare** [comment]
There is something called `BinaryLog` that can be set from a server builder https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractServerImplBuilder.java#L162

You might be able to use this as an access log.

There is a post on StackOverflow that has some solutions as well https://stackoverflow.com/questions/47155084/intercepting-logging-requests-and-responses-in-grpc

**Comment by ejona86** [comment]
BinaryLog is not a good fit for this use-case. An interceptor would be ideal. https://stackoverflow.com/a/56999548/4690866 is most similar to what you are asking for.

**Comment by QeyCoder** [comment]
Thanks @ejona86  @sanjaypujare  Archived this with interceptor
