### ISSUE TITLE
how to benchmark grpc services?

### ISSUE THREAD

**Issue by gdonlyathw** [grpc/grpc-java#7075]
for rest services, we can use many soft to benchmark, how to benchmark grpc services?
I want to compare grpc and rest service at QPS/avg Latency.

**Comment by creamsoup** [comment]
I heard good things about [ghz](https://ghz.sh/). it supports metrics like QPS and percentile latency.

**Comment by gdonlyathw** [comment]
> 我听说过有关[ghz的](https://ghz.sh/)好消息。它支持QPS和百分位数延迟等指标。

thanks

**Comment by ejona86** [comment]
Closing, since it seems this is resolved. It can be reopened if necessary.
