### ISSUE TITLE
is service side StreamObserver noblocking ?

### ISSUE THREAD

**Issue by roycarser** [grpc/grpc-java#7076]
is service side StreamObserver noblocking ?
we using netty in current project,is it a good idea call onNext/onError/onComplete in netty's IO threads to improve performance

```

class MyGrpcService  {
    
    @Override
    public void rpc(Request request, StreamObserver ob) {
        Channel nettyChannel = ();
        nettyChannel.dosomthing().addListener(
            //run in netty's IO thread, must be noblocking
            (f)->ob.onNext()/ob.onCompleted())/ob.onError();
        )
    }
}
```

**Comment by creamsoup** [comment]
As long as the implementation of StreamObserver it not blocking, it is safe to execute the observer from netty eventloop. One thing to keep in mind is that the StreamObserver is not thread safe and it shouldn't be concurrently called.

It is hard to say without knowing rest of the system what is best for performance. I would recommend to run benchmarks.

**Comment by ejona86** [comment]
To clarify: The StreamObservers returned by gRPC from the stub are async. StreamObservers themselves don't _have_ to be async, so someone else could implement one that blocked.

This question seems answered, closing. If not, comment and it can be reopened.
