### ISSUE TITLE
How to get metrics of GRPC methods in a ServerInterceptor

### ISSUE THREAD

**Issue by obvionaoe** [grpc/grpc-java#7082]
Hi, I'm trying to get the time it takes for the GRPC method to run, including all the logic inside the method(database queries, s3 object retrieval, etc.), and the status code it returns (2xx,3xx,4xx, etc.).

Currently I have this Interceptor implementation:

```java
@GRpcGlobalInterceptor
public class Interceptor implements ServerInterceptor {

    private final Logger logger = Logger.getLogger(Interceptor.class);

    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
        String methodName = call.getMethodDescriptor().getFullMethodName();

        long startTime = System.currentTimeMillis();

        ServerCall.Listener<RespT> methodCall = next.startCall(call, headers);

        long endTime = System.currentTimeMillis();

        logger.log(Level.INFO, "Running method '" + methodName + "'");
        logger.log(Level.INFO, "Took " + (endTime - startTime) + " ms")
        //logger.log(Level.INFO, "Response code: $responseCode")

        return methodCall;
    }
}
```

But the time being logged is always the same and is not including my database queries, as these are being made after this time is calculated and logged.

For the status code, I couldn't find any indication that it was possible to get.

How would I go about doing this?

### Additional Info

My project is using GRPC version 1.20.0, I'm mentioning this in case these features might've been added in a newer release.

Thanks

**Comment by creamsoup** [comment]
`startCall` is an async method so the behavior you described is correct.
to intercept the response you can use `SimpleForwardingServerCall` to intercept `sendMessage`.
you can also intercept the `close` to get `Status`. gRPC Status is different than regular http status code. see [javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/Status.html) for the detail.


```java
  @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
        String methodName = call.getMethodDescriptor().getFullMethodName();
        long startTime = System.currentTimeMillis();
        logger.log(Level.INFO, "Running method '" + methodName + "'");
        return next.startCall(
            new SimpleForwardingServerCall<ReqT, RespT>(call) {
              @Override
              public void sendMessage(RespT message) {
                super.sendMessage(message);
                long endTime = System.currentTimeMillis();


                logger.log(Level.INFO, "Took " + (endTime - startTime) + " ms")
                //logger.log(Level.INFO, "Response code: $responseCode")
              }
            },
            headers);
    }
```

**Comment by obvionaoe** [comment]
Thank you very much, I would suggest maybe adding a few comments to the examples you have so it is clearer about the function of the ServerInterceptor and the SimpleForwardingServerCall classes!
