### ISSUE TITLE
Is ServerCall.close() always called?

### ISSUE THREAD

**Issue by obvionaoe** [grpc/grpc-java#7088]
Hi, basically the title is self explanatory, I want to know if `ServerCall.close()` is always called after any rpc

Thanks

**Comment by creamsoup** [comment]
yes, it should be called in normal flow. 
it may not be called if the server call is terminated due to unhandled exception. For example, if the server method implementation throws exception or `ServerInterceptor` throws exception instead of calling `close()`. those are not a normal cases.

**Comment by obvionaoe** [comment]
ok, thanks for the information
