### ISSUE TITLE
connection reset by peer when using Firebase

### ISSUE THREAD

**Issue by Amosss** [grpc/grpc-java#7092]
**I'm using Firestore that is using gRPC java behind the scenes**

I got the following error:
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception 
at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531) 
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:512) 
at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83) 
at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62) 
at com.app.API3.apiName(API3.java:2685) <<<< **this is my code**
```

The stacktrace ends with this
**Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer**

Does that mean there was a connection problem between my server and FireStore server? A connection error somewhere else? How can I know what was causing it?

Thanks

**Comment by creamsoup** [comment]
just from the exception it is hard to know what causes the "Connection reset by peer". all we know is the remote peer closed the connection. 
you may need to work with firestore/firebase to figure this out. btw, how often do you see this error?

**Comment by Amosss** [comment]
Obviously they say it's not their problem and gave me a "limitation" reason so I proved them wrong using this stacktrace. Before going back to them, I wanted to make sure here, what can be the reasons.

You wrote "the remote peer closed the connection" so assuming I'm the caller, the peer in this case would be Firestore server, no? Meaning the problem is that they shut the connection on me, I understand it correctly?

In the past I got it from time to time so I added a "re-call" to my own API to overcome this, usually it's one time error and the next calls are ok so it was quiet for a long time. Now suddenly I got it in a new scenario, in the middle of a batch update to Firestore.

**Comment by creamsoup** [comment]
@Amosss yes, the remote peer is the firestore server.

it is good practice to implement retry logic. Anyways, it is possible to have some misbehaving components in the middle such as proxy or firewall. Anything can close connection in between can cause the "connection reset by peer". so, it is hard to pin point what is the cause. Usually it is from the remote end, but hard to ignore the other possibilities.

**Comment by Amosss** [comment]
Thank you very much for your answer. I thought I covered all the scenarios but I guess I have at least one more to cover :)

**Comment by trajano** [comment]
@creamsoup I am getting something similar, is retry logic adding the following to the builder?

        final ManagedChannelBuilder<?> builder = ManagedChannelBuilder.forAddress(serverInfo.getHostname(), 6565)
            .usePlaintext()
            .enableRetry() // <--
            .maxRetryAttempts(5); // <--

Because I am still getting the error
