### ISSUE TITLE
alts: Running on GKE gVisor gives error "ALTS is only allowed to run on Google Cloud Platform"

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc-java#7099]
I'm running a Java server in a faily minimal docker image on GKE on GCP, and trying to receive a request via ALTS that yields the odd error that "ALTS is only allowed to run on Google Cloud Platform".

https://github.com/grpc/grpc-java/blob/c777e0856327de03225bb3bdd9660001950f87e3/alts/src/main/java/io/grpc/alts/AltsChannelBuilder.java#L114 currently tries to read `/sys/class/dmi/id/product_name`, which doesn't exist in the minimal container image I'm using.

Should there be an alternative model for not early erroring-out for Kubernetes containers, or is the requirement that Kubernetes always re-expose the Node's `/sys` mount to the Pods ([`hostPath` docs](https://kubernetes.io/docs/concepts/storage/#hostpath)) so that this business logic can continue to work?

FTR, gVisor aka GKE Sandbox doesn't allow `hostPath` mounts, so the best I can do at the moment appears to fake it with my own hack file.

See also https://github.com/grpc/grpc-go/issues/3666

**Comment by voidzcy** [comment]
@creamsoup I am not quite familia with ALTS, can you please take a look for this?

**Comment by Capstan** [comment]
This looks like it's specifically caused by turning on the GKE Sandbox. Perhaps gVisor hides this directory.

**Comment by creamsoup** [comment]
i am only aware of having this check, but i am not sure who/what should provide `/sys/class/dmi/id/product_name`. @jiangtaoli2016, original author, might have a better idea.

**Comment by jiangtaoli2016** [comment]
There is a separate email discussion going on.

**Comment by ejona86** [comment]
Did the email discussion complete? Can this be closed?

**Comment by Capstan** [comment]
Sadly, no; it petered out. It's related to determining whether the GCE/GKE Metadata service should be available due to some bad behavior that happens around trying to probe its availability. There's a discussion as to whether gVisor should be emitting its own DMI product name that could be an alternate valid value. That last saw any commentary on Jun 9th.

I am currently using a workaround by creating a [Kubernetes ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object) as a volume to work around the issue.

**Comment by ejona86** [comment]
There doesn't seem to be anything gRPC can do for this. Any conversations should continue, but I'm going to close this bug because it doesn't provide any value. Once the platform has a solution that gRPC can use, then we can have a bug tracking its implementation.
