### ISSUE TITLE
How can I use the .proto file to generate the code for one request and one response

### ISSUE THREAD

**Issue by RobertoHuang** [grpc/grpc-java#7157]
![image](https://user-images.githubusercontent.com/20842825/85537248-619f0980-b646-11ea-9161-60fecc9101de.png)

I saw the above description in the official documentation

but after experimenting, I found the code I generated through the plugins for ways 1 and 2 is the same

![image](https://user-images.githubusercontent.com/20842825/85537865-ee49c780-b646-11ea-97fc-307a93d0001d.png)

environment:  java1.8 maven plugins: protobuf-maven-plugin version 0.6.1

**Comment by ejona86** [comment]
The async API (StreamObserver) _looks_ the same for unary and server-streaming RPCs. That's because it is a callback API and the only difference is how many times onNext() is called. The blocking API looks different between the two cases (blocking function call vs Iterator).

**Comment by RobertoHuang** [comment]
I can't understand why unary needs to add an observer？

**Comment by RobertoHuang** [comment]
I still need to call onnext() and onComplate() manually when using unary

**Comment by ejona86** [comment]
StreamObserver is not directly chosen based on the cardinality (unary vs streaming). The same API works for both. Instead, the API provides _asynchronous_ operation.

Now if the RPC has a single request (unary or server-streaming), the expectation is that the client has the request immediately available at the start of the call. So in those cases the client provides the request immediately when starting the call and the service receives it when the call starts. There's no need for asynchronously passing the request. But the response will happen "at some point in the future" so it must be delivered asynchronously. And the StreamObserver is used to deliver those events.

**Comment by RobertoHuang** [comment]
Thank you very much
