### ISSUE TITLE
How to recompile grpc-netty-shaded with a local snapshot version of Netty?

### ISSUE THREAD

**Issue by dzou** [grpc/grpc-java#7161]
Hey all, I am experimenting with setting up a project using `grpc-netty-shaded` compiled as a native image using GraalVM.

Right now I want to experiment with making some changes to netty and then seeing the effect of the changes in my application.

How do modify the compilation of the `grpc-netty-shaded` project to use my local version of netty? For example, I want `grpc-netty-shaded` to compile with my local version of `io.netty:netty-handler:4.1.51.Final-SNAPSHOT` that I built locally rather than  `io.netty:netty-handler:4.1.48` in Maven Central.

Right now I've tried tinkering with changing the versions specified in https://github.com/grpc/grpc-java/blob/master/repositories.bzl but there appears to be no effect.

**Comment by dapengzhang0** [comment]
grpc-netty-shaded is not built with bazel or using repositories.bzl.

To recompile grpc-netty-shaded you need 

```sh
git clone https://github.com/grpc/grpc-java.git
cd grpc-java
# modify any source code as you need, 
# modify ./netty/build.gradle and ./netty/shaded/build.gradle to change dependencies as you need
# publish to maven local
./gradlew :grpc-netty-shaded:publishMavenPublicationToMavenLocal -PskipCodegen=true -PskipAndroid=true
```

Then the recompiled grpc-netty-shaded will be available in maven local repository  ~/.m2/repository/io/grpc/grpc-netty-shaded/

**Comment by dzou** [comment]
Thanks @dapengzhang0 . You rock.
