### ISSUE TITLE
How to consume metadata headers in the actual call?

### ISSUE THREAD

**Issue by robbdimitrov** [grpc/grpc-java#7178]
This is the [header example](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/header/CustomHeaderServer.java) server, but the header isn't used in the service, just in the interceptor.

```java
private static class GreeterImpl extends GreeterGrpc.GreeterImplBase {

    @Override
    public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
      HelloReply reply = HelloReply.newBuilder().setMessage("Hello " + req.getName()).build();
      responseObserver.onNext(reply);
      responseObserver.onCompleted();
    }
  }
```

There's no information in the docs. My use case includes passing `authorization` + `device-uuid` headers
to the grpc calls.

In go/python and other grpc implementations the headers reside in Context which is passed as a parameter to the call.

Any help will be appreciated!

**Comment by sanjaypujare** [comment]
That is as designed. The service implementation only receives what the client-stub sent (`HelloRequest`). The metadata is  added outside of the client-stub (client-interceptors) and so is available to server-interceptors (such as for processing authn/authz info) so the service implementation code only deals with business logic related to the client-request. You can view it as separation of concerns and a better model than exposing metadata via Context to service implementation code.

**Comment by robbdimitrov** [comment]
@sanjaypujare Thank you for the response!

If the aim is to have clear separation, is there a good practice/example of getting the `userId` from an `authorization` header or some other parameter passed via header to the grpc call in order to use it in the business logic?
