### ISSUE TITLE
Remove All Deprecated Classes before Beta

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#718]
There are a number of classes in core that are Deprecated.  Since it will likely be impossible to remove them later without breakage, they should be removed now.

**Comment by jayantkolhe** [comment]
Please fix other beta issues before tackling this.

**Comment by carl-mastrangelo** [comment]
The last two deprecated classes are Metadata.Headers and Metadata.Trailers.   The comment for this PR says to remove them before beta, but per our deprecation policy, we cannot delete these until after a major release.  

This means we would have to do a quick major release just before beta, and then go to beta.   Alternatively, the title of this Issue can be changed to "remove before GA".  Lastly, we could just break the rules and remove them right now before beta.

@ejona86 : thoughts?

**Comment by ejona86** [comment]
> but per our deprecation policy, we cannot delete these until after a major release.

I don't agree with that. Anything marked stable can't be removed, but we can claim that things marked Deprecated in the beta release will be removed. It's about being clear what is and is not stable. As long as we are clear, it's okay.

That said, if it is only Metadata.Headers and Trailers, I can live with removing them now.

**Comment by carl-mastrangelo** [comment]
They were deprecated in 0.9.0-SNAPSHOT, which would not give them a major release before removal.  If you don't care about this, then away they go.
