### ISSUE TITLE
grpc-okhttp gets gRPC response slowly when request/response are large

### ISSUE THREAD

**Issue by vsbogd** [grpc/grpc-java#7208]
### What version of gRPC-Java are you using?

grpc-java version 1.27.0

### What is your environment?

Android, API version 24
Linux, OpenJDK Runtime Environment (build 1.8.0_242-b08)

### What did you expect to see?

I use gRPC to upload large amount of data (10 Mb) to server and receive same data back. I expect that request and response will be delivered to and from server in same time taking into account network connection throughput is symmetric.

### What did you see instead?

Response is delivered from service by 8 times slower when `okhttp` is used. Moreover delay ratio depends on message size. With `netty` both request and response take similar time. 

### Steps to reproduce the bug

1. Download and unpack jar file: [grpc-okhttp-test-jar.zip](https://github.com/grpc/grpc-java/files/4920001/grpc-okhttp-test-jar.zip)
2. Upload one copy of the jar file to the remote host.
3. Run remote copy as server:
```
java -cp grpc-okhttp-test-jar-with-dependencies.jar test.TestService <port>
```
4. Run local copy as client:
```
java -cp grpc-okhttp-test-jar-with-dependencies.jar test.TestClient <remote_host> <port> <size>
```
5. Check timestamps

My results, server is located in US Amazon, client is located in Russia, client uses `grpc-okhttp`:
```
java -cp grpc-okhttp-test-jar-with-dependencies.jar test.TestClient <server-ip> 12345 10
before call:	1594743735988
after call:	1594743831877
request  time: 10205 ms
response time: 85684 ms
```

Same locations, same server, client uses `grpc-netty-shaded`:
```
java -cp grpc-okhttp-test-jar-with-dependencies.jar test.TestClient <server-ip> 12345 10
before call:	1594743972464
after call:	1594743991484
request  time: 8620 ms
response time: 10400 ms
```

Application source code:
[grpc-okhttp-test.zip](https://github.com/grpc/grpc-java/files/4920241/grpc-okhttp-test.zip)
To build it use `mvn package`.

**Comment by ejona86** [comment]
This is probably related to flow control. Try setting [`OkHttpChannelBuilder.flowControlWindow()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html#flowControlWindow-int-) to 1 MB.

The default window size is 64 KB for OkHttp. This is commonly quite appropriate for connections over the internet and on mobile. On your tests, you probably co-locate the client and server and the network involved there has different behaviors. Since you say 8x as slow, then the bandwidth-delay product (BDP) between the client and server is probably 512 KB. Any window less than 512 KB will see a proportional drop in performance.

**Comment by vsbogd** [comment]
> This is probably related to flow control. Try setting OkHttpChannelBuilder.flowControlWindow() to 1 MB.

I played with it for a while. Increasing it to 1 Mb unfortunately doesn't work at all. Client doesn't receive response and it is reproducible even in unit test from the code attached. `netty` works well as before. Decreasing it to 32 Kb improves timings a bit for `okhttp` but not resolves the issue. 

In fact I can collect and share network traffic dump if it helps.

**Comment by ejona86** [comment]
Oh, you need [grpc-java v1.28.0 or later](https://github.com/grpc/grpc-java/releases/tag/v1.28.0) for the client. Earlier versions had a completely busted `OkHttpChannelBuilder.flowControlWindow()` implementation. "okhttp: fix incorrect connection-level flow control handling at beginning of connection"

**Comment by vsbogd** [comment]
> Oh, you need grpc-java v1.28.0 or later for the client. E

Thanks @ejona86, upgrading to `v1.28.0` plus using large flow control window solves the issue. 
Any thoughts on why `netty` performs better without manual window tuning?

**Comment by vsbogd** [comment]
Closing it as my problem more or less resolved. But there is a question why manual flow control tuning is required for `okhttp` and not required for `netty`.

**Comment by ejona86** [comment]
Netty defaults to 1 MB currently. It also has BDP-monitoring logic that will increase the window if appropriate. We only recently enabled the BDP-monitoring logic, and have plans to reduce the default down to 64 KB.

If you need this setting for production, we'd be interested in what sort of network environment is being used. If this is just for testing, then it's not as surprising.

**Comment by vsbogd** [comment]
@ejona86, thanks again for the answer. Looks like this difference in default window sizes is the reason why I see such asymmetric throughput between server and client.

Yes, we are going to use it in production. Client is supposed working on Android device (it is the reason why `okhttp` is the only officially supported way of doing things). At the moment server is located at US Amazon node. We don't have multi-regional service setup, so throughput from different locations is critical as Android clients will be located in different regions. Network conditions can be very different. Android device can be connected via mobile network or WiFi and even LAN and it can be very far from server.

In most of tests we made Android emulator was used so client accessed network via LAN or WiFi. I didn't compare throughput via mobile network and LAN but I can give it a try and share results here.

**Comment by ejona86** [comment]
Whether connected via WiFi or LAN doesn't really matter. The ISP speed is generally what decides this (as it is normally the bottleneck in terms of latency and throughput). And high throughput ISP service generally means lower latency (it is a coincidence of economics); 64 KB is actually reasonably appropriate for things from local Ethernet (two machines on the same switch), to cable modems, to age-old land-line modems. Communication between data centers is generally where we see 64 KB is a poor value, especially cross-continental.

But it makes sense that a single-zone server being used world-wide would need a higher value, as the ISP is no longer the sole predominant contributor of latency.
