### ISSUE TITLE
Hide AbstractManagedChannelImplBuilder from public API

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#7211]
Transport implementations extend `io.grpc.internal.AbstractManagedChannelImplBuilder` to obtain most of their builder implementations. However, this leaks to the user in the Javadoc and with an `api` dependency in Gradle. The Javadoc in particular is a confusing mess because it isn't clear what is stable, experimental, and internal. Since we don't generate `io.grpc.internal` Javadoc and since the extending class "shadows" the base `ManagedChannelBuilder`, it also means the user is unable to click links to get to documentation for a large number of its methods. We should avoid extending AbstractManagedChannelImplBuilder in public (non-internal) classes.

To do this, we should extend ForwardingChannelBuilder instead (probably extending the Simple* version, which would need to be created). Transport implementations would create a AbstractManagedChannelImplBuilder and forward to it. We don't want to remove (useful) public methods in this process and break users, so we should make sure that there aren't any stray public methods in AbstractManagedChannelImplBuilder that would be dropped in the process.

The only abstract method in AbstractManagedChannelImplBuilder is `buildTransportFactory()`. We should probably inject that method in the constructor and convert the class to concrete, non-abstract. To simplify migration we can create ManagedChannelImplBuilder as a shim on top of AbstractManagedChannelImplBuilder. The shim could override some protected methods and make them public. It can also provide a setter for the checkAuthority override used by things like NettyChannelBuilder. Once all classes (external and internal) are migrated we can remove AbstractManagedChannelImplBuilder and combine it with the shim. If some classes still extend ManagedChannelImplBuilder that may be okay, but we should try to avoid such inheritance if possible.

The same should be done for AbstractServerImplBuilder.

**Comment by sergiitk** [comment]
Re-opening because `io.grpc.internal.AbstractManagedChannelImplBuilder` and `io.grpc.internal.AbstractServerImplBuilder` were re-added back to the class hierarchy to fix broken ABI backward compatibility in #7564.

**Comment by ejona86** [comment]
#7552 discusses some options to resolve.

**Comment by ejona86** [comment]
API review meeting notes (concerning ABI issue):
* Three rough approaches: Keep current API, break users/ABI, redefine methods in top-level class (keeping them forever), hacks (aka class rewriting as shown in #7552)
 * GoogleDefaultChannelBuilder → ForwardingChannelBuilder
    * Keep current API (it needs to be stable), but create new ForwardingChannelBuilder2 that has correct generics for new code to use. Discussed other names, but just adding 2 seemed most straight-forward for users
 * NettyChannelBuilder → AbstractManagedChannelImplBuilder
   * Strong consensus that we want to change the API and that we want to help users to avoid pain. Consensus for doing "hacks". Nobody preferred bridge-method-injector over the "manual" rewriting. The manual method has less concern about issues that bridge-method-injector may have and it avoids adding the annotations as a temporary dependency

**Comment by ejona86** [comment]
https://github.com/grpc/grpc-java/pull/7834 is providing a bridge to get users off the internal name. After enough releases/time, we can proceed on this again.
