### ISSUE TITLE
How to get a notification in server side when a connected client disconnected

### ISSUE THREAD

**Issue by shiyiyue1102** [grpc/grpc-java#7216]
Hi All,I am using gRPC-java to build  a Long Connection framework between client and server ,Now I want to get a notification in server side  when a  connected client disconnected ,then I can do something related to the client .

I have searched  in internet several days  , but I have not get any effective results.

Has anyone has the same question and could get me some instructions ?

Best regards.

**Comment by ejona86** [comment]
The server is not informed about the connection life of a client. It is only informed of the RPCs. You should use an RPC's lifetime instead of the connection lifetime.

**Comment by shiyiyue1102** [comment]
we want to  replace http with gRPC as a new communication protocol  between  client and server in nacos (https://nacos.io/en-us/ ),  nacos is a dynamic service discovery, configuration and service management platform, it's  informed  
 of the connection lifetime，and sensitive to real time . Now we have consider using heart detection mechanism to expel the expire client in server ,but we should  consider the balance between the cost and real-time.
Could you give me some suggestions in my situation?

**Comment by ejona86** [comment]
> it's informed of the connection lifetime

I'm saying that is not a thing in gRPC (at least our libraries). In the face of load balancing, connection lifetime is generally meaningless. Instead, we suggest using RPC lifetime. You can use a streaming RPC if it helps. RPCs are allowed to last as long as the TCP connection they are on.

I don't know your requirements nor your architecture. You say you are considering a heart(beat) detection mechanism, but that doesn't explain what you are doing now. I'd have to know more of your current approach to provide suggestions. You may get ideas from the discussion in #7180.

**Comment by ejona86** [comment]
Closing since there's not more information to go deeper. Streaming RPCs can definitely fulfill the role of learning when a client goes away. This can be reopened if there's more information provided.

**Comment by shiyiyue1102** [comment]
> Closing since there's not more information to go deeper. Streaming RPCs can definitely fulfill the role of learning when a client goes away. This can be reopened if there's more information provided.

Thank you . Recently， I found  out that  the interface of "io.grpc.ServerTransportFilter" can satisfied my requirements.

**Comment by ejona86** [comment]
@shiyiyue1102, be wary of using ServerTransportFilter for that use. Your ServerTransportFilter needs to really work regardless of whether it is called once-per-connection or once-per-RPC (although obviously once-per-connection would be more efficient). gRPC makes no guarantees when it will replace old connections/create additional connections.
