### ISSUE TITLE
'./gradlew build' fails because of missing plugin dependency

### ISSUE THREAD

**Issue by raboof** [grpc/grpc-java#7217]
When aopalliance is not already in the cache, I get:

```
./gradlew build
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'grpc'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find aopalliance:aopalliance:1.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/aopalliance/aopalliance/1.0/aopalliance-1.0.pom
       - https://dl.google.com/dl/android/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.pom
     Required by:
         project : > com.google.osdetector:com.google.osdetector.gradle.plugin:1.4.0 > gradle.plugin.com.google.gradle:osdetector-gradle-plugin:1.4.0 > kr.motd.maven:os-maven-plugin:1.4.0.Final > org.apache.maven:maven-plugin-api:3.2.1 > org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5 > org.sonatype.sisu:sisu-guice:3.1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

Adding maven central to the plugin repo's in `settings.gradle` solves the problem. I'd be happy to PR, but I'm not sure if that's the 'right' solution.

**Comment by ejona86** [comment]
Hmm... I just re-ran our Travis-CI without any cache, and it was fine. It runs Maven between `./gradlew assemble` and `./gradle check` (which is mostly the rest of 'build'), so maybe it wouldn't notice this.

But I just deleted ~/.m2 and and ~/.gradle/caches on my machine, and ran with `./gradlew build -PskipCodegen=true -PskipAndroid=true` and it completed fine. I re-ran with `--no-parallel` (after cleaning the caches) and it also worked. I also tried just running `./gradlew buildEnvironment` (after cleaning the caches) and it also worked.

Looking at the error, it is very believable that it'd be an issue. I'm surprised to think about osdetector's dependencies being in the plugin repository (I'd expect them in Maven Central). But actually, maybe this was just a temporary glitch? I am able to download the POM without issue from https://plugins.gradle.org/m2/aopalliance/aopalliance/1.0/aopalliance-1.0.pom .

**Comment by raboof** [comment]
> But actually, maybe this was just a temporary glitch? I am able to download the POM without issue from https://plugins.gradle.org/m2/aopalliance/aopalliance/1.0/aopalliance-1.0.pom .

Huh, I'm fairly sure I checked that wasn't there when I had this problem.

Must've been a glitch indeed, no such problem on master now
