### ISSUE TITLE
ProtocolNegotiators bypass SslContext.newHandler

### ISSUE THREAD

**Issue by srushingiv** [grpc/grpc-java#7223]
https://github.com/grpc/grpc-java/blob/557da62305b7b4499300f9b201a25b44fa0d60ef/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L177

https://github.com/grpc/grpc-java/blob/557da62305b7b4499300f9b201a25b44fa0d60ef/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L353

This prevents any ability for subclasses of SslContext to provide custom or wrapped SslHandlers.

Instead, call the appropriate sslContext.newBuilder methods.

**Comment by ejona86** [comment]
Why are you wanting a custom or wrapped SslHandler?

**Comment by ejona86** [comment]
Closing since there was no additional information. If information is provided we can reopen.

**Comment by ejona86** [comment]
On client-side we can't use `newHandler()` because we must call [`setEndpointIdentificationAlgorithm("HTTPS")`](https://github.com/grpc/grpc-java/blob/1411e6f61e6e2d3e7f846b8d89bc8926617bf0dc/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L350) to actually authenticate the server.
