### ISSUE TITLE
Ability to create a CallContext with retry settings

### ISSUE THREAD

**Issue by skuruppu** [grpc/grpc-java#7228]
### Is your feature request related to a problem?
In [googleapis/java-spanner](https://github.com/googleapis/java-spanner), we're investigating the possibility of letting users set per-request timeout and retry settings.

Currently, the timeouts and retry settings are set at the time of client creation when the UnaryCallable is created ([example](https://github.com/googleapis/java-spanner/blob/ca99446f2ff594727d1624fc309736efbc443da6/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerStub.java#L471)). If we want to specify per-request timeouts, you can pass in something like `CallContext.withCallOptions(CallOptions.withDeadline())` to the RPC call. But there is no equivalent option for retry settings.

### Describe the solution you'd like
If `CallContext` or `CallOptions` includes a `withRetrySettings()` method, then this can be accomplished.

### Describe alternatives you've considered
The only solution we have right now is to ask the customer to create multiple clients where each client has different retry settings set. But this doesn't resolve all use cases because some customers have requested the ability to programatically change the retry setting in their applications. Instantiating and managing multiple clients can be tedious.

**Comment by ejona86** [comment]
Can you explain more about the customer needs that would cause the retry settings to be different per-call?

I'll also note that java-spanner should not be using the built-in retry, as it is experimental.

**Comment by skuruppu** [comment]
> Can you explain more about the customer needs that would cause the retry settings to be different per-call?

The specific ask from my understanding was to configure some types of requests to `ExecuteSql` to retry and but not to configure retries for the rest. There are a variety of different types of queries that you can run using the `ExecuteSql` and `ExecuteStreamingSql` RPCs (e.g. read-only, updates, inserts). In some applications, it makes sense to retry some of those and perhaps not for some others.

> I'll also note that java-spanner should not be using the built-in retry, as retry is experimental.

I believe we're using the [gax-java RetrySettings](http://googleapis.github.io/gax-java/1.8.0/apidocs/com/google/api/gax/retrying/RetrySettings.html) rather than built-in retries. But I don't know how gax-java implements this internally.

**Comment by ejona86** [comment]
Okay. If the feature just needs to _disable_ retries on a per-RPC basis, that's not too hard.

But you'll need to file an issue against gax-java (internally or externally), since that's the API you are using.

**Comment by dapengzhang0** [comment]
@skuruppu If you are the service owner, a workaround of your problem would be let the server decide if a particular request can be retried based on custom request headers, and if server doesn't want the request to retry, the server and send a response trailer with a negative [pushback](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#pushback).

**Comment by skuruppu** [comment]
Sorry for the slow response.

@ejona86, I will follow up with the customer to see if that might help.

@dapengzhang0, that's an interesting proposal and we didn't know we could do that. I will propose this to my team and see what they say.

**Comment by ejona86** [comment]
Closing since there is nothing to do in the short-term. But it was useful to have this issue as we do try to follow gax's retry feature set, as they would like to migrate to ours eventually.
