### ISSUE TITLE
com.google.common.base.Suppliers$NonSerializableMemoizingSupplier cannot be cast to java.util.function.Supplier when using Grpc in Gradle plugin for Android app

### ISSUE THREAD

**Issue by vsbogd** [grpc/grpc-java#7229]
### What version of gRPC-Java are you using?

grpc-java version 1.28.0

### What is your environment?

Arch Linux, JDK version 1.8.0_242, Gradle 5.4.1, Android API 24+

### What did you expect to see?

I wrote custom Gradle plugin which uses `grpc-protobuf` 1.28.0 as a dependency. I use this plugin to build an Android application so both my plugin and `com.android.application` are used at the same time. I expect my application will be built successfully.

### What did you see instead?

Build fails with error:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > com.google.common.base.Suppliers$NonSerializableMemoizingSupplier cannot be cast to java.util.function.Supplier
```

### Steps to reproduce the bug

Add the following line into `buildscript/dependencies` section of the top level `gradle.build`
```gradle
buildscript {
  dependencies {
    classpath 'io.grpc:grpc-protobuf:1.28.0'
  }
}
```
For example clone any simple android app:
```sh
git clone https://github.com/codepath/intro_android_demo.git
cd intro_android_demo/
sed -i "/dependencies/a classpath 'io.grpc:grpc-protobuf:1.28.0'" build.gradle
./gradlew build
```

The root cause seems to be `grpc-protobuf` uses `com.google.guava:guava:28.1-android` as dependency [see pom](https://repo1.maven.org/maven2/io/grpc/grpc-protobuf/1.28.0/grpc-protobuf-1.28.0.pom). Android version of Guava `Supplier` class doesn't inherit `java.util.function.Supplier` I believe because it is not compatible to Android API below 21. When `grpc-protobuf` is used as dependency in Gradle plugin Gradle resolves guava to `android` version instead of `jre` one and it conflicts with requirements of Gradle Android plugin.

**Comment by vsbogd** [comment]
As a workaround you can exclude Guava `-android` and include `-jre` version:
```xml
  <dependencies>
    ...
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-protobuf</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <!-- version 28.1 corresponds to the grpc version 1.28.0 -->
      <version>28.1-jre</version>
    </dependency>
    ...
  </dependencies>
```

**Comment by ejona86** [comment]
This is a classpath problem. It won't be solved by gRPC itself. The workaround may be necessary, but I hope you find a better solution.

I _think_ that if you use Gradle's newer plugin syntax that each plugin is given its own ClassLoader, so different plugins can have different dependencies.

**Comment by vsbogd** [comment]
@ejona86, thanks again, yes you are right that it is typical classpath conflict. I was confused by two different versions (`-android` and `-jre`) of `guava` but in fact it doesn't change anything.

Unfortunately I didn't found anything about Gradle plugin syntax which allows classpath isolation. Gradle documentation still references it as future work https://guides.gradle.org/designing-gradle-plugins/#minimizing_the_use_of_external_libraries.
