### ISSUE TITLE
TLS handshake fails when using client certificate and OkHttpChannelBuilder

### ISSUE THREAD

**Issue by behradanalui** [grpc/grpc-java#7248]
Hi I am using OkHttpChannelBuilder and sslSocketFactory with client certificate for mutual TLS authentication. From wireshark i can see server send Certificate Request but Client responds with a certificate of size 0.

My Client Certificate is store is KeyStore and I can verify Client Certificate CN is same as DN in Server Certificate Request.

I am using grpc 1.30.2 on Android 9 and 10. 

My basic question is if OkHttpChannelBuilder supports sending client certificate with cutom trust manager?

**Comment by voidzcy** [comment]
All of these should be configured in the `SSLContext` that used to create the `SSLSocketFactory` passed into OkHttpChannelBuilder. https://github.com/grpc/grpc-java/issues/6374#issuecomment-550166965 contains fair amount of information for using okhttp with mutual TLS, make sure your `SSLContext` is configured correctly.

**Comment by behradanalui** [comment]
Thanks, @voidzcy . That was super helpful. Mutual handshake seems to be working fine now.
