### ISSUE TITLE
Synchronous grpc C++ server and asynchronous grpc java client for bidirectional streaming RPC

### ISSUE THREAD

**Issue by sridharprasath** [grpc/grpc-java#7252]
Hello all,

In my application, I had to use bidirectional streaming RPC. My teammate has implemented synchronous API (for C++ server) on the server side. On the client side also, he has used synchronous API for bidirectional streaming in C++.

Now, I have to do that for android client. But I have read that, android client does not support synchronous method for bidirectional streaming. So, I am using asynchronous android client with synchronous c++ server. How does it affect the performance?

As far as now, I can see some of the responses are missing from the server when I call the RPC continuously. Is it because of the mismatch between the methods used by the client(android-asynchronous) and server(C++ synchronous)? Or is is related to some other problem? I would need your valuable suggestions

**Comment by ericgribkoff** [comment]
Using synchronous API on the server and async on the client will not cause any problems. Using async API on the Android client will not hurt performance.

> As far as now, I can see some of the responses are missing from the server when I call the RPC continuously. Is it because of the mismatch between the methods used by the client(android-asynchronous) and server(C++ synchronous)? Or is is related to some other problem?

We would never expect to have missing responses. Can you provide more details about what is happening here? How are you seeing that some responses are missing?

**Comment by sridharprasath** [comment]
@ericgribkoff  Thank you for the response. I found that the responses are missing from the server since I request the RPC continuously. I tried to introduce a delay between RPC request(of 1000 milliseconds) and now the server is accepting the request. 

So, basically, now I am requesting the server for every second. If its less than a second(or less than some timeperiod), the server leaves out the request

**Comment by ericgribkoff** [comment]
Thanks for the reply. What do you mean by responses are missing from the server? It is unlikely - as in, it would be a serious bug in gRPC - that the server is actually sending responses that your client is not receiving. Can you help confirm that there's not some aspect of your server or client implementation that results in these messages not being sent by your server application layer - or else ignored by your client application - when you are sending frequent requests? We have many applications that far exceed 1 QPS, and messages should never be dropped in the way it seems you are describing.

**Comment by sridharprasath** [comment]
@ericgribkoff  I found out what the problem is... basically, I have to attach an image via grpc request.. earlier , I was doing it in a wrong way.. I was searching through the folder('for' loop) and make a grpc call within that 'for' loop...so grpc is called everytime an image is found.. so single GRPC call for single image..

But that's not the way I should be doing it.   First , I have to find all the images in that folder and add them to an array list of images... So basically, now I have a stream of images... Now I can call the grpc a single time(with the stream of images) outside the loop and it works perfectly fine now...

**Comment by ericgribkoff** [comment]
Great, glad the issue is resolved. I'll mark this as closed. If anything comes up related to the original issue feel free to comment here again and we can reopen.
