### ISSUE TITLE
Alts on Android

### ISSUE THREAD

**Issue by Xtizainy** [grpc/grpc-java#7268]
I have an application with client on Android and gRPC communication to backend. My backend runs on VM in Compute Engine. When I am trying to use alts builder I am getting 'ALTS is only allowed to run on Google Cloud Platform' error on client.

### What version of gRPC-Java are you using?
1.30.2

**Comment by ericgribkoff** [comment]
As the error message says, currently ALTS is only supported on GCP VMs (see https://grpc.io/docs/guides/auth/alts/ for more background info). Android apps should use TLS to connect to your backends.
