### ISSUE TITLE
How to pass custom variables inside a single grpc request

### ISSUE THREAD

**Issue by darknessp** [grpc/grpc-java#7269]
How to pass custom variables inside a single grpc request, like RequestContextHolder in SpringMVC, and make sure that the scope of these values is restricted to this request?

**Comment by dapengzhang0** [comment]
You might want to use [io.grpc.Context](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html)

**Comment by ejona86** [comment]
Seems this is answered. Closing. If it is not resolved, comment and it can be reopened.
