### ISSUE TITLE
Android example: use Maven Central as fall back

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-java#7276]
This was discussed out-of-band with @ejona86. We'd like to be able to advertise the latest `grpc-java` version on [grpc.io](https://grpc.io), as soon as the version is released (e.g., https://github.com/grpc/grpc.io/pull/374). We can't do that right now because of the Android-Java examples depending solely on JCenter; an issue which we hit before (https://github.com/grpc/grpc.io/issues/317, https://github.com/grpc/grpc.io/pull/318).

More context: https://github.com/grpc/grpc.io/pull/374#issuecomment-666572531

**Comment by ejona86** [comment]
Related: https://github.com/grpc/grpc-java/issues/5782
