### ISSUE TITLE
Upgrade netty to 4.1.51.Final

### ISSUE THREAD

**Issue by shahmirn** [grpc/grpc-java#7279]
### Is your feature request related to a problem?

We're trying to use Google Secret Manager and its corresponding Java library in a micronaut project, and when trying to compile it to a native image using GraalVM, running into issues regarding GenericJson, which when worked around, results in errors related to grpc and grpc-netty-shaded
 
### Describe the solution you'd like

https://netty.io/news/2020/07/09/4-1-51-Final.html

mentions some changes to accommodate openssl and GraalVM

I believe upgrading the netty version that grpc is using should help alleviate the issues I'm running into.

**Comment by ejona86** [comment]
This was done in #7358
