### ISSUE TITLE
grpc-okhttp/grpc-netty gets gRPC response slowly from grpc android server

### ISSUE THREAD

**Issue by andyliumstar** [grpc/grpc-java#7286]
**What version of gRPC-Java are you using?**
grpc-java version 1.27.0~1.31.0

**What is your environment?**
Android, API version 25
Android okhttp/netty client
Android netty server

**What did you expect to see?**
I use grpc-netty  client and server in the same android phone/emulator but different processes，I think a request & reponse should not take more than 5 ms.

**What did you see instead?**
A small request & response takes an average of 20ms, change the client channel to okhttp does not help.

**Steps to reproduce the bug**
1. just use the Helloworld demo(server stream)
2. android grpc-netty server response the request immediately and call onCompleted
3. client receive the onCompleted call but takes 20 ms after request sended

**Comment by ejona86** [comment]
We don't support grpc-netty on Android. It may function, but Netty is not tuned at all for Android. For "proper" Android server support we'd write a new server based on grpc-okhttp.

You may be interested in following https://github.com/grpc/proposal/pull/191

**Comment by ejona86** [comment]
You may be suffering from just context-switching costs. You can do a _test_ using `directExecutor()` on both the client and server and seeing what performance you get. If `directExecutor()` makes the performance considerably better, then the performance loss is due to swapping between threads which would generally be necessary unless you are _very_ focused on latency and willing to deal with higher maintenance costs or you are doing more of a toy or super-simple RPC that you can respond to _very_ quickly (think: memcached).

**Comment by andyliumstar** [comment]
We are using both  linux and  android grpc server， the clients on linux or android may access both servers。 So BinderChannel will not help and we've actually used it just on android environment。

**Comment by andyliumstar** [comment]
I am wondering when grpc-okhttp server will be released

**Comment by andyliumstar** [comment]
> We don't support grpc-netty on Android. It may function, but Netty is not tuned at all for Android. For "proper" Android server support we'd write a new server based on grpc-okhttp.
> 
> You may be interested in following [grpc/proposal#191](https://github.com/grpc/proposal/pull/191)

We are using both linux and android grpc server， the clients on linux or android may access both servers。 So BinderChannel will not help and we've actually used it just on android environment。

**Comment by andyliumstar** [comment]
> You may be suffering from just context-switching costs. You can do a _test_ using `directExecutor()` on both the client and server and seeing what performance you get. If `directExecutor()` makes the performance considerably better, then the performance loss is due to swapping between threads which would generally be necessary unless you are _very_ focused on latency and willing to deal with higher maintenance costs or you are doing more of a toy or super-simple RPC that you can respond to _very_ quickly (think: memcached).

`directExecutor()` does not help, so I am wondering when grpc-okhttp server will be released?

**Comment by ejona86** [comment]
Nobody has started working on a grpc-okhttp server and nobody is currently planning on starting (in this quarter or so). But it is something that there has been interest in doing eventually.

There's probably ways to tune Netty so it works better (just via configuration), but we won't spend our resources into such an investigation. We've not looked at all, so there's probably some easy wins avaliable. It would start with learning 1) the baseline TCP latency to expect and 2) where additional latency is being added. Sources of slowdown could be 1) high allocation rate 2) java.nio (vs java.io) 3) Netty configuration (which type of buffers to use, which event loop, etc).

I will note that the C++ server is supported on Android.

**Comment by ejona86** [comment]
Seems there's nothing more to do at present. We would expect weak performance for a Java server on Android.
