### ISSUE TITLE
`rules_proto_grpc` Bazel rules fail to compile with Bazel 3.4.1 due to errorprone GuardedBy failures.

### ISSUE THREAD

**Issue by rickwebiii** [grpc/grpc-java#7297]
### What version of gRPC-Java are you using?
1.24.x

### What is your environment?

Windows, but should fail on all OSs.

### What did you expect to see?
The [GRPC rules](https://github.com/rules-proto-grpc/rules_proto_grpc) consume io_grpc_grpc_java at 62e8655f1bc4dfb474afbf332ca7571c1454e6ef, which doesn't contain change d3c77f2d870baf8c8340890eb5aed590a5f3940c. As such, newer versions of Bazel fail to compile GRPC due to GuardedBy static analysis failures in errorprone, and thus the rules are worthless.

I attempted to simply upgrade the version they were using to 1.25.x, but this caused other failures.

**Comment by rickwebiii** [comment]
This bug isn't directly related to GRPC itself (other than the fact you can't compile v1.24.x with Bazel 3.4.1), but cherry-picking d3c77f2d870baf8c8340890eb5aed590a5f3940c is a simple way to fix these GRPC [rules](https://github.com/rules-proto-grpc/rules_proto_grpc).

I've made a [pull request](https://github.com/grpc/grpc-java/pull/7291) that cherry-picks this change into the v1.24x. The cherry-picked change only suppresses the offending static analysis rules and doesn't appear to have any functional changes.

If this isn't the right solution, we can do something else.

**Comment by sanjaypujare** [comment]
CC @dapengzhang0 since he committed the original commit https://github.com/grpc/grpc-java/commit/d3c77f2d870baf8c8340890eb5aed590a5f3940c

**Comment by dapengzhang0** [comment]
Resolved by #7291
