### ISSUE TITLE
RetriableStream only retries error on first call

### ISSUE THREAD

**Issue by neilstevenson** [grpc/grpc-java#7308]
### What version of gRPC-Java are you using?

`1.32.0-SNAPSHOT`

### What is your environment?

MacOS, 10.15

### What did you expect to see?

A client can have a channel to a server and make multiple calls for a call type which is retryable. For a transient error, such as `UNAVAILABLE` any of these calls could fail - the first, the second, the third - and should be retried.

### What did you see instead?

Retry occurs if the first call returns `UNAVAILABLE`.
Retry does not occur if the first call succeeds and the second call gets `UNAVAILABLE`.

### Steps to reproduce the bug

I think this line is to blame, https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/RetriableStream.java#L785

If the first call fails, when `closed(Status, RpcProgress, Metadata)` is called, `state.winningSubstream` is null and it will be `RpcProgress.PROCESSED`, resulting in a call to `makeRetryDecision(status, trailers)`.

If the second or subsequent call fails, `state.winningSubstream` is not null, and the retry logic is bypassed.

**Comment by sanjaypujare** [comment]
@dapengzhang0 can you comment on the `RetriableStream` code cited?

**Comment by dapengzhang0** [comment]
>Retry does not occur if the first call succeeds and the second call gets UNAVAILABLE.
> I think this line is to blame, https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/RetriableStream.java#L785

Each call is independent, so the first call being successful does not affect the second call's `state.winningSubstream`. If you look at the retry example in https://github.com/grpc/grpc-java/tree/master/examples#basic-examples, calls are randomly failing and they can retry regardless whether the first call is successful. Can please you provide exact steps how to reproduce the issue?

**Comment by neilstevenson** [comment]
You can make this occur by amending the [retrying example](https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/retrying), so that it uses [hello_streaming.proto](https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/hello_streaming.proto)

You need to make three changes

(1) [retrying_service_config.json](https://github.com/grpc/grpc-java/blob/master/examples/src/main/resources/io/grpc/examples/retrying/retrying_service_config.json)
Add the following so these the specified calls are part of the retry configuration
```
        {
          "service": "manualflowcontrol.StreamingGreeter",
          "method": "SayHelloStreaming"
        },
```

(2) [RetryingHelloWorldServer.java](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldServer.java)
Add a class to handle async calls 
```
  static class StreamingGreeterImpl extends io.grpc.examples.manualflowcontrol.StreamingGreeterGrpc.StreamingGreeterImplBase {
      AtomicInteger retryCounter = new AtomicInteger(0);
      
      @Override
      public StreamObserver<io.grpc.examples.manualflowcontrol.HelloRequest> 
          sayHelloStreaming(StreamObserver<io.grpc.examples.manualflowcontrol.HelloReply> responseObserver) {
          StreamObserver<io.grpc.examples.manualflowcontrol.HelloRequest>  streamObserver
              = new StreamObserver<io.grpc.examples.manualflowcontrol.HelloRequest>() {
              @Override
              public void onNext(io.grpc.examples.manualflowcontrol.HelloRequest request) {
                  int count = retryCounter.incrementAndGet();
                  if (random.nextFloat() < UNAVAILABLE_PERCENTAGE) {
                    logger.info("Returning stubbed UNAVAILABLE error. count: " + count);
                    responseObserver.onError(Status.UNAVAILABLE
                        .withDescription("Greeter temporarily unavailable...").asRuntimeException());
                  } else {
                    logger.info("Returning successful Hello response, count: " + count);
                    io.grpc.examples.manualflowcontrol.HelloReply reply = 
                            io.grpc.examples.manualflowcontrol.HelloReply.newBuilder().setMessage("Streaming hello " + request.getName()).build();
                    responseObserver.onNext(reply);
                  }
              }

              @Override
              public void onError(Throwable t) {
                  throw new RuntimeException(t);
              }

              @Override
              public void onCompleted() {
                  responseObserver.onCompleted();
              }
            };
            return streamObserver;
      }
  }
```
and change the `start()` method so it is called:
```
  private void start() throws IOException {
    /* The port on which the server should run */
    int port = 50051;
    server = ServerBuilder.forPort(port)
        .addService(new GreeterImpl())
        .addService(new StreamingGreeterImpl())
        .build()
        .start();
```

(3) [RetryingHelloWorldClient.java](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldClient.java)
Three changes here,
(3a) Make the counters static
```
private static final AtomicInteger totalRpcs = new AtomicInteger();
private static final AtomicInteger failedRpcs = new AtomicInteger();
```
(3b) Add an asynchronous stub use with the streaming call
```
  private static io.grpc.examples.manualflowcontrol.StreamingGreeterGrpc.StreamingGreeterStub asyncStub;

  public RetryingHelloWorldClient(String host, int port, boolean enableRetries) {

    ManagedChannelBuilder<?> channelBuilder = ManagedChannelBuilder.forAddress(host, port)
        // Channels are secure by default (via SSL/TLS). For the example we disable TLS to avoid
        // needing certificates.
        .usePlaintext();
    if (enableRetries) {
      Map<String, ?> serviceConfig = getRetryingServiceConfig();
      logger.info("Client started with retrying configuration: " + serviceConfig);
      channelBuilder.defaultServiceConfig(serviceConfig).enableRetry();
      channelBuilder.maxRetryAttempts(100);//TODO Not sure if needed
    }
    channel = channelBuilder.build();
    blockingStub = GreeterGrpc.newBlockingStub(channel);
    asyncStub = io.grpc.examples.manualflowcontrol.StreamingGreeterGrpc.newStub(channel);
    this.enableRetries = enableRetries;
  }
```
(3c) Change `main()` to make asynchronous calls
```
  public static void main(String[] args) throws Exception {
    boolean enableRetries = !Boolean.parseBoolean(System.getenv(ENV_DISABLE_RETRYING));
    final RetryingHelloWorldClient client = new RetryingHelloWorldClient("localhost", 50051, enableRetries);
    ForkJoinPool executor = new ForkJoinPool();

    /*
    for (int i = 0; i < 50; i++) {
        final String userId = "user" + i;
        executor.execute(
            new Runnable() {
              @Override
              public void run() {
                client.greet(userId);
              }
            });
      }
      */
    
    int MAX = 20;
    final CountDownLatch finishLatch = new CountDownLatch(MAX);
    
    StreamObserver<io.grpc.examples.manualflowcontrol.HelloReply> responseObserver
        = new StreamObserver<io.grpc.examples.manualflowcontrol.HelloReply>() {
        @Override
        public void onNext(io.grpc.examples.manualflowcontrol.HelloReply response) {
            logger.log(Level.INFO,"Greeting: {0}", new Object[]{response.getMessage()});
            finishLatch.countDown();
        }

        @Override
        public void onError(Throwable t) {
          logger.log(Level.INFO,"RPC failed: {0}", new Object[]{Status.fromThrowable(t)});
          failedRpcs.incrementAndGet();
          finishLatch.countDown();
        }

        @Override
        public void onCompleted() {
        }
      };

    StreamObserver<io.grpc.examples.manualflowcontrol.HelloRequest> requestObserver = 
              asyncStub.sayHelloStreaming(responseObserver);
    
    for (int j = 0; j < MAX; j++) {
          final String userId2 = "streamer" + j;
          io.grpc.examples.manualflowcontrol.HelloRequest request = 
                  io.grpc.examples.manualflowcontrol.HelloRequest.newBuilder().setName(userId2).build();
          requestObserver.onNext(request);
          totalRpcs.incrementAndGet();
    }
      
    // Max backoff 30s per req
    if (!finishLatch.await(5, TimeUnit.MINUTES)) {
        logger.log(Level.WARNING,"SayHelloStreaming did not finish within 5 minutes");
      }
    requestObserver.onCompleted();
    
    executor.awaitQuiescence(100, TimeUnit.SECONDS);
    executor.shutdown();
    client.printSummary();
    client.shutdown();
  }
```

<><><><>

Because the server failure is random, you might need to run it a few number of times to see the problem.

If the server decides to select `UNAVAILABLE` on the very first call, you see this retried.
If the server selects `UNAVAILABLE` for a later call, it is not retried.

I'm viewing it that the fact the call is async instead of blocking shouldn't affect whether it is retried.
Either way, the behaviour I observe is inconsistent, calls should always be retried or never be retried if async.

Let me know if you see and agree with my reproduction of the issue, and if there's any way I can help clarify further.

**Comment by dapengzhang0** [comment]
@neilstevenson That's expected behavior. If a request receives a response message and then fails, it does not retry. See the [retry spec#when-retries-are-valid](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#when-retries-are-valid)

**Comment by dapengzhang0** [comment]
Let me clarify. A streaming RPC can send multiple request messages and receives multiple response messages, but during the life cycle of the streaming RPC, it is considered as ONE call. "multiple calls" in the description should be "multiple request messages" in our terminology. It the call has received one response message, then it must have received the response header, and therefore the call is _commited_ and can not be retried by the retry spec.

**Comment by neilstevenson** [comment]
Understood. This may perhaps be unclear in the documentation.

What I think you're saying is if a service has a temporary fault such as [here](https://developers.google.com/maps-booking/reference/grpc-api/status_codes) "_14 | UNAVAILABLE | The service is currently unavailable.  This is most likely a  transient condition, which can be corrected by retrying with a backoff._" then an async client has open a fresh channel ?

If so, happy for it to be closed as not-an-issue

**Comment by neilstevenson** [comment]
Ok, thanks @dapengzhang0 . Am closing as "_user error_". Might be worth a documentation call-out but it's not a fault.
