### ISSUE TITLE
Add "set" and "add" method prefixes to AbstractChannelBuilder (e.g. addInterceptor)

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#731]
Our API is currently not consistent between how builders are implemented.  Considering the pervasiveness of the set, get, add, with, and other prefixed methods of Proto and the existing stubby implementations, consistency should be swing towards these style methods.

Also, AbstractServerBuilder should be changed likewise

**Comment by ejona86** [comment]
This did not have full agreement, but we did agree we needed to discuss it.

**Comment by carl-mastrangelo** [comment]
I did a survey of the public, non-static mutator methods.  So far it looks like with is generally winning, with second place of (set|add).*   There are a few oddities such as ServerServiceDefinition having a builder, but ServerMethodDefinition not.  Also the Status.augmentDescription doesn't quite fit into a bucket.  "ctor" means Constructor, and doesn't appear to be inline with the other methods.



AbstractChannelBuilder
*  executor -> set
*  intercept -> addAll
*  userAgent -> set
  
AbstractServerBuilder
*  ctor -> set
*  executor -> set
*  addService
  
CallOptions
*  withAuthority
*  withDeadlineNanoTime
*  withDeadlineAfter
*  withCompressor

ChannelImpl
*  setDefaultCompressor
  
Context
*  withCancellation
*  withDeadlineNanoTime
*  withDeadlineAfter
*  withValue
*  withValues
*  addListener
*  removeListener
  
Metadata
*  put
*  remove
*  removeAll
*  merge
  
MutableHandlerRegistry
*  addService
*  removeService
  
MutableHandlerRegistryImpl
*  addService
*  removeService
  
ServerImpl
*  setTerminationRunnable
    
ServerMethodDefinition
*  withServerCallHandler
  
ServerServiceDefinition.Builder
*  ctor -> set
*  addMethod
  
Status
*  withCause
*  withDescription
*  augmentDescription

**Comment by nmittler** [comment]
@ejona86 @carl-mastrangelo what if we generally follow these rules (at least for this issue):

*Builder/rebuilder methods:*
setters should be called "withXXX"
adding to a collection should be called "addXXX"

*Non-builder methods:*
setters should be called "setXXX"

With these rules, the only required changes would be `AbstractChannelBuilder`, `AbstractServerBuilder`.

Also, should setting of the default compressor be moved to `AbstractChannelBuilder`, so that it's immutable in `ChannelImpl`?

`ServerImpl.setTerminationRunnable` needs to be removed (just created #884) ... this was missed in the previous work to remove termination runnables.

**Comment by ejona86** [comment]
I'm _very_ confused.

I don't follow how with* is an alternative to set*. One creates a new object, and one is a mutator. We can't use with* on methods that mutate. That would be 100% backwards, as with* was chosen to distinguish it from a mutator method.

> with second place of (set|add).*

There are only two instances of set*: setDefaultCompressor and setTerminationRunnable. How is that second place?

> ServerImpl
> * setTerminationRunnable

This was always package-private, so should not factor into the discussion.

>  "ctor" means Constructor

How does ctor even factor into this?

**Comment by nmittler** [comment]
@ejona86 Is there a standard naming convention that establishes that `withXXX` always results in a new object? Do you have a reference?

In the past I've seen `withXXX` methods mutate, simply as a way of distinguishing them as fluent setters.

**Comment by carl-mastrangelo** [comment]
with* is an alternative to builders, and is a method for setting a value on an object (even if it is a new object).  with* is shorthand for foo.toBuilder().set*().build();  Therefore it merits mention with the set / add methods.

Constructor is another method of setting values.  The constructors mentioned are public.  Both with* style and builder style are different ways of constructing an object.  directly using the Constructor, notably with existing add, set, and direct methods is yet another way of setting up an object.

This is a survey of public object construction on our interface.

**Comment by nmittler** [comment]
That convention seems fine:  use `set` on builders, use `with` for rebuilders.

**Comment by ejona86** [comment]
Or the convention we appear to be doing today: no prefix on builders, `with` for "rebuilders".

**Comment by ejona86** [comment]
In further discussion, it was agreed that it might make sense to rename addMethod and addService to registerMethod and registerService (or even just "register"), but none of us felt very strongly. So we are just choosing to leave it as-is.
