### ISSUE TITLE
Upgraded embededd OkHttp library to latest version, 3.14.9

### ISSUE THREAD

**Issue by mformetal** [grpc/grpc-java#7324]
### Is your feature request related to a problem?

Not necessarily a problem, but the app I work in uses Retrofit, which as of creating this PR uses version `3.14.9` of `OkHttp`: https://github.com/square/retrofit/blob/master/build.gradle#L7. 

### Describe the solution you'd like

I'd like to see if upgrading `grpc-java`'s version of `OkHttp` to `3.14.9` causes any breaking changes.

### Describe alternatives you've considered

I've excluded the embedded version of `OkHttp` that `grpc-okhttp` brings in, but it was requested of me to try and get the library aka `grpc-java` to upgrade internally.

**Comment by sanjaypujare** [comment]
@mformetal can you clone and build grpc-java yourself after upgrading the okhttp version (from the current 2.7.4) to 3.14.9 and see if causes any breaking changes? You can then share your findings here.

**Comment by voidzcy** [comment]
No, we don't have short-term plan for upgrading to okhttp3, it is a different implementation not a simple version bump. There shouldn't be a problem depending on both okhttp2 and okhttp3. You can see more information in #6119.
