### ISSUE TITLE
Delete ChannelEssentials

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#733]
Since ChannelEssentials only affects transports, it should likely be deleted.

**Comment by ejona86** [comment]
It is not directly deletable. We would have to find alternative ways to pass the information around. It could easily be marked @ Experimental or maybe even @ Internal (which is an annotation we could use a couple different places)

**Comment by zhangkun83** [comment]
Technically `@Experimental` and `@Internal` are the same. Both mean we don't guarantee any API stability at all. For now I am just adding `@Experimental` to it, and if we figure we need separate annotations, `@Experimental` gives us the freedom to change it to other annotation any time.

**Comment by nmittler** [comment]
@zhangkun83 I think if all we want to say is that we don't guarantee API stability, then `@Internal` is more appropriate.  I could see classes being marked as both `@Internal` and `@Experimental`, where the latter annotation is a note to ourselves that we haven't ironed out all the details, or we're just trying something out.  I think both annotations are useful, although I would expect `@Internal` to be used more in practice ... specifically for the purpose of identifying API instability.

**Comment by zhangkun83** [comment]
> @zhangkun83 I think if all we want to say is that we don't guarantee API stability, then @Internal is more appropriate.

IMO `@Experimental` in a public API package means it's still public, but we may change it or remove it. `@Internal` in a public API package means we intend to make it internal, it just unfortunately has to reside in the public package. The difference between them are whether we expect users to use them. Based on that, `@Internal` is probably appropriate for `ChannelEssential`.

**Comment by nmittler** [comment]
@zhangkun83 ah ok ... agreed.  I was under the impression that you were eliminating our use of `@Internal`.  But yes, if it's public then `@Experimental` makes sense to me.

**Comment by zhangkun83** [comment]
Resolved by #837

**Comment by nmittler** [comment]
Woot! 2 birds with one PR! :)
