### ISSUE TITLE
Observer setOnReadyHandler semantics wrt GRPC thread

### ISSUE THREAD

**Issue by devinrsmith** [grpc/grpc-java#7361]
I've got a situation where I think I'm using the observer setOnReadyHandler correctly, but may be running into potential concurrency issues due to running on the GRPC thread.

```java
    private final ServerCallStreamObserver<Response> observer;

    public Demonstrate(ServerCallStreamObserver<Response> observer) {
      this.observer = observer;
    }

    /** must be done on the GRPC thread before returning */
    void init() {
      observer.setOnReadyHandler(this::onReady);
    }

    void execute() throws InterruptedException {
      waitForReady();
      observer.onNext(Response.newBuilder().build());
      
      waitForReady();
      observer.onNext(Response.newBuilder().build());
      
      observer.onCompleted();
    }

    synchronized void onReady() {
      notify();
    }

    synchronized void waitForReady() throws InterruptedException {
      while (!observer.isReady()) {
        wait();
      }
    }
```

If `execute()` is run on the GRPC thread, it gets stuck on the second call to `waitForReady()`. It works correctly if executing on a new thread. For testing, I'm using the *default* and not the direct executor, since `waitForReady()` is a blocking op.

I've got a full test rig setup. https://github.com/devinrsmith/grpc-handlers

**Comment by ericgribkoff** [comment]
cc @ejona86

**Comment by ejona86** [comment]
setOnReadyHandler "is guaranteed that execution of the Runnable is serialized with calls to the 'inbound' StreamObserver." That also includes the `demonstrate(Request, StreamObserver)` call which I guess is unclear. It's a shame we don't have a clear name for that executor. So what's happening is gRPC is enqueuing the call to `this::onReady` behind the call to `demonstrate(Request, StreamObserver)`. That's working exactly as we want, but it does mean blocking causes trouble.

If blocking, the cancellation callback also is troublesome, but you can use Context if necessary. For flow control there's no alternative callback if you want to block the normal executor.

All you probably want is a blocking API, where sending blocks. Hmm...

**Comment by ejona86** [comment]
I think the only easy solution here is to use a separate thread for execute(). You were originally expecting the onReady() callbacks to use a separate thread, so it's not really any different to make the separate thread yourself, as there will still be two threads.

I think it may be possible to enhance server-side to allow something like [ThreadlessExecutor](https://github.com/grpc/grpc-java/blob/7009c1a863944a07ab6f5a2ccb7741d48f274777/stub/src/main/java/io/grpc/stub/ClientCalls.java#L711) to allow blocking methods to run the executor. But that would take some effort, and would probably need a blocking server-side stub API to wrap up the magic.

**Comment by tbcdns** [comment]
I am trying to do something similar, but using a Semaphore:

```java
public void getRecords(RecordRequest request, StreamObserver<Record> responseObserver) {
    ServerCallStreamObserver<Record> scso = (ServerCallStreamObserver<Record>) responseObserver;

    Semaphore semaphore = new Semaphore(0);
    scso.setOnReadyHandler(semaphore::release);

    while(!scso.isCancelled()) {
        if (!scso.isReady()) {
            try {
                semaphore.acquire();
            } catch (InterruptedException e) {
                // pass
            }
        }
        scso.onNext(Record.newBuilder().build());
    }

    scso.onCompleted();
}
```

Basically, the goal is simply to block until isReady is true and send data until the client stops the request.

I know using a Semaphore is probably not the best way to do it, but do you see a way to make this example working? 
Thanks!

**Comment by ejona86** [comment]
@tbcdns, the same answer applies to you: do the blocking on a separate thread.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by lulu2panpan** [comment]
I think it is a bug，because the "runQueue" in class "SerializingExecutor" can cause Memory Leak，the queue size will continuously increased, but have no chance to release.

**Comment by ejona86** [comment]
@lulu2panpan, it isn't clear exactly what you're talking about, but it seems different than this issue. Please open a separate issue to discuss. I will say that I believe your assertion is inaccurate on two accounts, but we'd need to discuss more to understand your situation.

**Comment by ejona86** [comment]
@lulu2panpan, ah, I see this is part of #7839. And yes, you're seeing something similar as discussed here. But let's discuss on #7839.
