### ISSUE TITLE
more questions on GRPC retry

### ISSUE THREAD

**Issue by zhouxdd** [grpc/grpc-java#7363]
grpc-java version 1.31.0

Does GRPC retry works by using `enableRetry()`? I am referring to this documentation: https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html and this example: https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldClient.java

If it works I have two questions:
1. Do I need to make a service config or simply add the `enableRetry()` option can work as well?
2. How do I view the logs of the retry if a retry is being invoked? (do I need to add an interceptor to capture the logs)
3. Is the retry included in the scope of `withDeadlineAfter` or it will reset the deadline?

**Comment by ericgribkoff** [comment]
1. You'll need a service config so the client knows which errors are retryable, along with other parameters like how many retries to attempt.
2. I'll have to let @dapengzhang0 answer this one.
3. All retry attempts are included in the scope of the deadline. Copying from the [spec](https://github.com/grpc/proposal/blob/master/A6-client-retries.md):
> gRPC's call deadline applies across all attempts for a given RPC. For example, if the specified deadline for an RPC is July 23 9:00:00pm PDT the operation will fail after that time regardless of how many attempts were configured or attempted.

**Comment by dapengzhang0** [comment]
As for 2. The interceptor can not intercept the intermediate retry attempts that is not visible to the client. You may use `ClientStreamTracer.inboundTrailers(Metadata trailers)` or `StreamTracer.streamClosed(Status status)` to "intercept" the failed intermediate attempts, and you may need `CallOptions withStreamTracerFactory(ClientStreamTracer.Factory factory)` to inject your stream tracer.

**Comment by ericgribkoff** [comment]
I'm going to mark this as closed since I think all questions have been answers. @zhouxdd if you have any followup items to discuss feel free to comment here and we can reopen.
