### ISSUE TITLE
How to skip host name validation with the OkHTTP channel

### ISSUE THREAD

**Issue by gnarea** [grpc/grpc-java#7388]
Hello,

I'm porting my gRPC client from the Netty channel to OkHTTP so I can use it on Android. This client is connecting to a gRPC server over TLS, but the server is on a private network and uses a self-signed certificate. In Netty, I can do the following have the host name verification disabled:

```
GrpcSslContexts.forClient()
            .trustManager(InsecureTrustManagerFactory.INSTANCE)
            .build()
```

That'll give me an SSL context that I can pass to `NettyChannelBuilder.forAddress(...).useTransportSecurity()..sslContext(insecureTlsContext)`. How can I do something like this with the OkHTTP channel?

I've managed to get something to work by cheating and using Netty's `InsecureTrustManagerFactory.INSTANCE`, but it doesn't make sense to have the Netty channel as a dependency just for this. Also, I read on `SECURITY.md` that it's a bad idea to have both.

**Comment by voidzcy** [comment]
> This client is connecting to a gRPC server over TLS, but the server is on a private network and uses a self-signed certificate.

You can use [`ManagedChannelBuilder#overrideAuthority`](https://github.com/grpc/grpc-java/blob/396dca3a1631024472ba747e32f635a4ef9575d2/api/src/main/java/io/grpc/ManagedChannelBuilder.java#L178) for self-signed certificate. Bypassing hostname verification completely makes TLS provide no value and you should just use plaintext.

**Comment by ericgribkoff** [comment]
You can also see a complete example of configuring a test cert in our Android interop client [here](https://github.com/grpc/grpc-java/blob/c29ad76daea0d17637fefcab4dbfd9ef8cb84ebc/android-interop-testing/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java#L51)

**Comment by gnarea** [comment]
Thank you both for the pointers! :+1:
