### ISSUE TITLE
Add SOCKS proxy support

### ISSUE THREAD

**Issue by gmale** [grpc/grpc-java#7398]
### Is your feature request related to a problem?
I'm unable to leverage network privacy using gRPC.

### Describe the solution you'd like
As a developer on the cutting edge of privacy technology, which is surging in popularity lately, I'd like to use gRPC with SOCKS5 proxies in order to privately connect with servers without revealing my private information, like IP, to the server. Ideally, using gRPC would not result in the leakage of other private information like the timing of communication, and data about the graph of who is communicating.

_TL;DR: privacy is a big deal and increasingly more relevant. It's a good time for gRPC to be more compatible with SOCKS proxies._

### Describe alternatives you've considered
gRPC [doesn't work with the common alternative](https://github.com/grpc/grpc-java/issues/5998) for network privacy: Tor.

### Additional context
This topic was mentioned many times[ 4 years ago](https://github.com/grpc/grpc-java/issues/2193#issuecomment-242211519) but times have changed and it is probably worthwhile to revisit those decisions. Major advances are happening in the area of network privacy.

**Comment by jrhee17** [comment]
Shameless plug (I recently contributed heavily to armeria's client-side proxy implementation)

If you are open to using alternative grpc libraries, you might also want to try out [armeria](https://github.com/line/armeria) which supports SOCKS[4][5] with gRPC.

```
ClientFactory clientFactory =
                     ClientFactory.builder()
                                  .proxyConfig(ProxyConfig.socks5(socksProxyServer.address()))
                                  .build()
```

**Comment by dapengzhang0** [comment]
> This topic was mentioned many times[ 4 years ago](https://github.com/grpc/grpc-java/issues/2193#issuecomment-242211519) but times have changed and it is probably worthwhile to revisit those decisions. Major advances are happening in the area of network privacy.

See also grpc/grpc-go#707 (comment)

**Comment by ejona86** [comment]
I've not used Tor, but it seems to have the option [HTTPTunnelPort](https://2019.www.torproject.org/docs/tor-manual.html.en#HTTPTunnelPort) that enables HTTP CONNECT support. Would that not work for gRPC?

**Comment by ejona86** [comment]
It seems gRPC is already compatible with Tor via HTTP CONNECT, so closing. If I'm mistaken, comment, and it can be reopened.
