### ISSUE TITLE
libio_grpc_netty_shaded_netty_tcnative_osx_x86_64.jnilib not signed

### ISSUE THREAD

**Issue by liamsharp** [grpc/grpc-java#7404]
### What version of gRPC-Java are you using?

1.31.1

### What is your environment?

macOS

### What did you expect to see?
The file grpc-netty-shaded-1.31.1.jar/META-INF/native/libio_grpc_netty_shaded_netty_tcnative_osx_x86_64.jnilib being signed.
### What did you see instead?
That it's not signed.
### Steps to reproduce the bug
Submit a package to Apple for Notarization containing grpc-netty-shaded-1.31.1.jar. The Notarization process will fail, with the following being reported:

    {
      "severity": "error",
      "code": null,
      "path": "MyApp-1.0-alpha-1.dmg/My App.app/Contents/Java/lib/grpc-netty-shaded-1.27.1.jar/META-INF/native/libio_grpc_netty_shaded_netty_tcnative_osx_x86_64.jnilib",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
    }

I've worked around this by extracting the libio_grpc_netty_shaded_netty_tcnative_osx_x86_64.jnilib out of the jar, signing it, then replacing it in the jar before sending off to Apple. I think ideally the binary should be signed as part of the build phase of the

**Comment by sanjaypujare** [comment]
@liamsharp I believe this should be handled in the netty build. Can you file an enhancement request there?

**Comment by liamsharp** [comment]
@sanjaypujare No problem, and thanks for looking at this. Could you point me in the right direction of where to file the issue please with a link?

**Comment by sanjaypujare** [comment]
> @sanjaypujare No problem, and thanks for looking at this. Could you point me in the right direction of where to file the issue please with a link?

This link  https://github.com/netty/netty/issues/new/choose

**Comment by liamsharp** [comment]
@sanjaypujare thanks, filed [here](https://github.com/netty/netty/issues/10569)

**Comment by ejona86** [comment]
I have high confidence that if Netty signs their binaries that it would "just work" with gRPC. The only case that wouldn't be true is if renaming files breaks the signing. I'm going to close this. If things don't work out like we're hoping then it can be reopened or we can open an new issue.
