### ISSUE TITLE
De I need to shutdown and re-create a ManagedChannel.shutdown() for recovery from StreamObserver.onError()

### ISSUE THREAD

**Issue by GlenGeng** [grpc/grpc-java#7442]
Hey, thanks for looking this question!

In our java application, we create a `ManagedChannel`, and an async stub from that channel, in order to do streaming calls.

When `StreamObserver.onError()` is called, we did some recovery work, including:
1. call `ManagedChannel.shutdown()`
2. re-create the channel from `NettyChannelBuilder`
3. re-create the async stub from the channel.
4. re-create a `StreamObserver<OurRequest>` from the async stub.

However, according to the doc of channel: 
`
A virtual connection to a conceptual endpoint, to perform RPCs. A channel is free to have zero or
many actual connections to the endpoint based on configuration, load, etc.
`

And the question:
https://github.com/grpc/grpc-java/issues/3268#issuecomment-317484178

shutdown and re-create channel seems not very necessary.

My question is, when `StreamObserver.onError()` is invoked, are `step 1,2,3`  needed for the recovery? or We can reuse the the channel and stub, just need `step 4` to re-create the `StreamObserver`, which means starting a new RPC on a previously opened channel by re-creating a `StreamObserver `?

Thanks!

**Comment by voidzcy** [comment]
Yes, you don't need to recreate the channel (and stub) for starting a new RPC call. The overhead for creating a channel is big.

Receiving `StreamObserver.onError()` only indicates that specific RPC has been terminated. The connection should be still there. So you can definitely start new RPCs on the existing connection.

**Comment by GlenGeng** [comment]
Thanks very much ! @voidzcy

**Comment by GlenGeng** [comment]
I've another question about the api `ManagedChannel.resetConnectBackoff()`. Is it safe to call this method on a healthy channel ?

In our environment, we have some lazy restart server process, in which case client needs detect this ASAP. We would like to let `StreamObserver.onError()` to call `ManagedChannel.resetConnectBackoff()` to handle this situation.  

I wonder will this call on the healthy channel have side effect ?

Thanks!

**Comment by voidzcy** [comment]
Your use case might be similar to #6473 if I understood it correctly. `ManagedChannel.resetConnectBackoff()` could be used to exit the channel connection backoff early. But be aware that

> `resetConnectBackoff()` is intended for cases where "you know something that gRPC doesn't." The most obvious case of that is on Android where the OS notifies the application when network interfaces change. If a new network interface comes online, that's a strong signal that things may be operational again.

In your case,
> In our environment, we have some lazy restart server process, in which case client needs detect this ASAP.

How does the client know the server process has restarted and should go for a reconnection? If there isn't a strong signal but just guessing the service is back, I doubt this would be a good usage (what if the server process is still not ready?) and letting it backoff might be better. But, you can still have this a try.

> I wonder will this call on the healthy channel have side effect ?

No, it won't do anything if the channel state is not `TRANSIENT_FAILURE` (aka, not in backoff). Also, you can check the channel state via `ManagedChannel.getState()`.

**Comment by GlenGeng** [comment]
Thanks @voidzcy for pointing out  #6473. Thanks @creamsoup for the clarification.

> if the server restarts, client tried to reconnect with exponential backoff. depends on the timing, it can wait a few more attempts which can be order of seconds to tens of seconds.

> if the client do some sort of busy waiting, it can achieve near immediate connection. this will have the same problem of busy waiting; wasting a lot of resources (cpu, network, etc). if there are many clients doing this behavior, this is essentially attacking the server.

> ManagedChannel#resetConnectBackoff could be used to accelerate the reconnect (not highly recommended, please read the javadoc).

In our situation, the num of clients is limited (3 or 5), and we do want clients to do some busy waiting. 

This is a raft implementation, leader (as the client) needs suppress restarted followers (as the server) from timeout and triggering new election by sending heartbeats.

Glad to hear that `ManagedChannel.resetConnectBackoff()` is a no-op for channel in non-backoff state.

We would like to let ` StreamObserver.onError()` to call `ManagedChannel.resetConnectBackoff()` as one of the recovery step: for non-backoff state channel, it would be a no-op; for backoff state channel, it will trigger an immediate re-connect to avoid restarted followers from timeout.

**Comment by voidzcy** [comment]
Sounds fair.

**Comment by GlenGeng** [comment]
Sure, go ahead!
