### ISSUE TITLE
De I need to shutdown and re-create a ManagedChannel.shutdown() for recovery from StreamObserver.onError() 

### ISSUE THREAD

**Issue by GlenGeng** [grpc/grpc-java#7449]
Hey there! Thanks for looking at this question!

This is a follow up question from https://github.com/grpc/grpc-java/issues/7442

I wonder if there were cases where `ManagedChannel` should be recreated. Or `ManagedChannel` is totally self-recoverable, `ManagedChannel.resetConnectBackoff()` is enough for the recover task upon network jitters ?

**Comment by GlenGeng** [comment]
Checked `ConnectivityState`: `TRANSIENT_FAILURE`  can handled by `ManagedChannel.resetConnectBackoff()`, `SHUTDOWN` is triggered by `ManagedChannel.shutdown()` which should be called by application , `CONNECTING`, `READY`, `IDLE` should not need intervention from application layer.

**Comment by voidzcy** [comment]
A channel can be used throughout the lifetime of the application. There shouldn't be a case that the application needs to shut down and recreate it.

**Comment by GlenGeng** [comment]
Thanks @voidzcy ! 
It is very helpful, simply the usage of application level coding.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
