### ISSUE TITLE
Maybe remove Server and rename ServerImpl

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#745]
It may be worth keeping Server as a base to ServerImpl (in order to add methods later on like getServerAddress)

This was a contentious issue, but needs to be resolved before going beta.

**Comment by ejona86** [comment]
If we want, we can easily remove `Server` and add it back as necessary. But if we do that, `ServerImpl` would need to keep its current name. To rename `ServerImpl` we would need to agree we would _never_ have a `Server` base class.

**Comment by ejona86** [comment]
We agreed to just leave it as it is, since it is unclear whether we need `Server` in the future. Removing the empty class is nice, but then it was felt that `ServerImpl` needed to be renamed. Since we couldn't agree to rename `ServerImpl`, leaving it all as-is was the agreement.
