### ISSUE TITLE
how to cancel a subscribe

### ISSUE THREAD

**Issue by BLOODButter** [grpc/grpc-java#7462]

**Comment by ejona86** [comment]
@BLOODButter, can you provide more information?

**Comment by BLOODButter** [comment]
> @BLOODButter, can you provide more information?
I want to implement such a function：When my client ask for a subscribe，my server will continue to return data in a fixed period. When my client sends another request to stop this subscribe，the server stopped sending data.The function onComplete doesn't seem to meet my needs. What should I do?

**Comment by ejona86** [comment]
There's two main options:
1. Use bidi streaming. The client could then either use `onComplete()` to stop the subscription or send a second message
2. Use RPC cancellation. You can use a server-streaming RPC and the client will cancel it to stop the subscription. In Java, that can most easily be done via the Future stubs but isn't that much harder with the async stubs using `ClientResponseObserver` to be able to call `ClientCallStreamObserver.cancel()`.
