### ISSUE TITLE
How do I use CronetChannelBuilder with localhost (i.e. plaintext)?

### ISSUE THREAD

**Issue by namgk** [grpc/grpc-java#7464]
It seems like CronetChannelBuilder doesn't support plaintext channel right?

How do I test it with non-ssl localhost server?

Thanks

**Comment by voidzcy** [comment]
You cannot use plaintext with Cronet, it's not supported. TLS is a builtin part in QUIC (you can think of QUIC as an all-in-one implementation of TCP+TLS+HTTP/2 using UDP). The TLS key exchange is built into the QUIC initial handshake process.

**Comment by ejona86** [comment]
Plaintext may be supported in cronet itself, but it only supports HTTP/2 over TLS and the APIs we use require HTTP/2.

For testing, you can use [`X509Util.addTestRootCertificate()`](https://chromium.googlesource.com/chromium/src/net/+/512b5be9a0a11a1709e60ee094b1e162ebd24525/android/java/src/org/chromium/net/X509Util.java#285). The target name will need to match the TLS certificate. To tell Cronet to connect to a different address than the one on the TLS certificate, you can configure Cronet to map certain names to the test server's address:

```
cronetEngineBuilder.setExperimentalOptions(
    "{\"HostResolverRules\": {\"host_resolver_rules\": \"MAP * localhost:1234\"}}");
```

That, however, requires using [`ExperimentalCronetEngine.Builder`](https://chromium.googlesource.com/chromium/src/+/lkgr/components/cronet/android/api/src/org/chromium/net/ExperimentalCronetEngine.java#136) with the "it can be removed at any time" restriction.

You are free to use our [test certificates](https://github.com/grpc/grpc-java/tree/master/testing/src/main/resources/certs).

**Comment by namgk** [comment]
Very good information, thank you very much.
