### ISSUE TITLE
What is the correct Kubernetes health status for channel state TRANSIENT_FAILURE?

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-java#7465]
The [Javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/ConnectivityState.html#TRANSIENT_FAILURE) states:

> Channels in this state will eventually switch to the CONNECTING state and try to establish a connection again.

Which of [Kubernetes liveness and readiness check](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) does this map to? I believe the application is alive but not accepting requests, not down, but I can see someone arguing the other way.

**Comment by ejona86** [comment]
We aren't experts on Kubernetes, but I believe it cooresponds to "live but not ready." There's a connectivity error, but there's no reason to believe replacing the pod will improve the situation; it is an OS/network problem not an application one. Assuming the Channel is for a required dependency, then without the channel the pod is not ready to service requests.

**Comment by asarkar** [comment]
That is my understanding too, Thank you @ejona86 for agreeing with me.
