### ISSUE TITLE
Build Error: This version of %1 is not compatible with the version of Windows you're running

### ISSUE THREAD

**Issue by logicatmidod** [grpc/grpc-java#7486]
### What version of gRPC-Java are you using?
protoc-gen-grpc-java:1.4.0

### What is your environment?
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
**JDK 1.8**

**Windows 10**

### What did you see instead?
[ERROR] C:\Users\1527992\Documents\repository\ace\SOFTWARES\gprc-demo\src\main\proto\HelloService.proto [0:0]: --grpc-java_out: protoc-gen-grpc-java: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

### Steps to reproduce the bug

PROROC VERSION DOWNLOADED: protoc-3.13.0-windows-x86_64.exe

MAVEN LOGS:
C:\Users\1527992\Documents\software\jdk1.8.0_65\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\1527992\Documents\repository\ace\SOFTWARES\gprc-demo "-Dmaven.home=C:\Users\1527992\Documents\software\IntellijLatest\IntelliJ IDEA 2020.2.2\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Users\1527992\Documents\software\IntellijLatest\IntelliJ IDEA 2020.2.2\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Users\1527992\Documents\software\IntellijLatest\IntelliJ IDEA 2020.2.2\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Users\1527992\Documents\software\IntellijLatest\IntelliJ IDEA 2020.2.2\lib\idea_rt.jar=49657:C:\Users\1527992\Documents\software\IntellijLatest\IntelliJ IDEA 2020.2.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\1527992\Documents\software\IntellijLatest\IntelliJ IDEA 2020.2.2\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\Users\1527992\Documents\software\IntellijLatest\IntelliJ IDEA 2020.2.2\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2020.2.2 clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[INFO] 
[INFO] ---------------------< com.example.gprc:gprc-demo >---------------------
[INFO] Building gprc-demo 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ gprc-demo ---
[INFO] Deleting C:\Users\1527992\Documents\repository\ace\SOFTWARES\gprc-demo\target
[INFO] 
[INFO] --- protobuf-maven-plugin:0.6.1:compile (default) @ gprc-demo ---
[INFO] Compiling 1 proto file(s) to C:\Users\1527992\Documents\repository\ace\SOFTWARES\gprc-demo\target\generated-sources\protobuf\java
[INFO] 
[INFO] --- protobuf-maven-plugin:0.6.1:compile-custom (default) @ gprc-demo ---
[INFO] Compiling 1 proto file(s) to C:\Users\1527992\Documents\repository\ace\SOFTWARES\gprc-demo\target\generated-sources\protobuf\grpc-java
[ERROR] PROTOC FAILED: --grpc-java_out: protoc-gen-grpc-java: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**[ERROR] C:\Users\1527992\Documents\repository\ace\SOFTWARES\gprc-demo\src\main\proto\HelloService.proto [0:0]: --grpc-java_out: protoc-gen-grpc-java: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.**

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.519 s
[INFO] Finished at: 2020-10-06T13:55:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile-custom (default) on project gprc-demo: protoc did not exit cleanly. Review output for more information. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ericgribkoff** [comment]
That version of protoc-gen-grpc-java is over three years old. Can you try with a more recent version (like `v1.32.1`) and see if the error persists?

**Comment by ejona86** [comment]
Closing since we didn't hear back. If we hear back, we can reopen.
