### ISSUE TITLE
The different between Retry policy and Hedge Policy

### ISSUE THREAD

**Issue by ducoppa** [grpc/grpc-java#7513]
I have read the documentation : https://github.com/grpc/proposal/blob/master/A6-client-retries.md . I kind of confuse different of hedge policy and retry policy. I wonder when i enable ```Retry Policy``` if the first RPC is fail, the second will be send to the same address? Can you distinguish those two policies to help me.

**Comment by dapengzhang0** [comment]
The difference between retry and hedge:
In retry, the client can attempt to send request for multiple times but each retry attempt can not start until the previous attempt fails with a retriable status. Whereas hedging enables aggressively sending multiple copies of a single request without waiting for an earlier attempt's response.

> I wonder when i enable Retry Policy if the first RPC is fail, the second will be send to the same address?

Not necessarily the same address, the second attempt selects an address independently from previous attempt. So based on the [load balancing policy](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md) the client is using, it may choose a different address.

**Comment by ducoppa** [comment]
> The difference between retry and hedge:
> In retry, the client can attempt to send request for multiple times but each retry attempt can not start until the previous attempt fails with a retriable status. Whereas hedging enables aggressively sending multiple copies of a single request without waiting for an earlier attempt's response.
> 
> So for one RPC, at any particular moment, there could be at most one active attempt in the retry case, and there could be multiple active attempts in the hedging case.
> 
> > I wonder when i enable Retry Policy if the first RPC is fail, the second will be send to the same address?
> 
> Not necessarily the same address, the second attempt selects an address independently from previous attempt. So based on the [load balancing policy](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md) the client is using, it may choose a different address.

So, if one of subchannels disconnected. gRPC client will be resolve again, and refresh connection. Am i understand correctly?

**Comment by dapengzhang0** [comment]
> So, if one of subchannels disconnected. gRPC client will be resolve again, and refresh connection. Am i understand correctly?

The channel is alway doing re-connecting in the background (you don't need manually enable it)(see [GRPC Connection Backoff Protocol](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md)). And that _connection "retry"_ is independent of the [RPC retry](https://github.com/grpc/proposal/blob/master/A6-client-retries.md).
