### ISSUE TITLE
Request timeout for OkHttpChannelBuilder

### ISSUE THREAD

**Issue by hazcod** [grpc/grpc-java#7529]
Hi, is there a way for us to set a request titmeout for OkHttpRequestBuilder?
```java
    public GRPCClient(final SSLSocketFactory sslFactory, final String host, final int port)
    {
        this(
            OkHttpChannelBuilder
            .forAddress(host, port)
            .sslSocketFactory(sslFactory)
            .keepAliveWithoutCalls(true)
            .useTransportSecurity()
            .build()
        );
    }

    GRPCClient(ManagedChannel channel)
    {
        this.channel = channel;
        this.blockingStub = ProxyGrpc.newBlockingStub(channel);
    }
```

**Comment by sanjaypujare** [comment]
> Hi, is there a way for us to set a request titmeout for OkHttpRequestBuilder?
>...

You mean `OkHttpChannelBuilder`... You can set a [deadline](https://github.com/grpc/grpc-java/blob/master/context/src/main/java/io/grpc/Deadline.java#L25) (which is an absolute point in time i.e. current time + timeout) on each call with a deadline:
```
blockingStub.withDeadlineAfter(timeout, TimeUnit.SECONDS).yourCall();
```

**Comment by hazcod** [comment]
Thank you @sanjaypujare , I've opted for Stackoverflow [for my other questions](https://stackoverflow.com/questions/64412105/debugging-java-grpc-flatbuffers).
