### ISSUE TITLE
Accessing the server from inside a call in order to implement a "shutdown" rpc

### ISSUE THREAD

**Issue by abusalimov** [grpc/grpc-java#7530]
Hi!

Is it possible to access the Server instance from a call handler so that it can request graceful shutdown of the server?

I would expect it to be available through the current Context, and even found the corresponding Key definition, but it turns out to be package private, and has a comment suggesting to file an issue:
```java
public abstract class Server {

  /**
   * Key for accessing the {@link Server} instance inside server RPC {@link Context}. It's
   * unclear to us what users would need. If you think you need to use this, please file an
   * issue for us to discuss a public API.
   */
  static final Context.Key<Server> SERVER_CONTEXT_KEY =
      Context.key("io.grpc.Server");

...
```

Is there maybe another way to implement a "Shutdown()" rpc? I could of course resort to having a global variable holding the Server instance, which is a singleton anyway, but would very much like to avoid doing that.

Thank you.

**Comment by sanjaypujare** [comment]
An alternative to using global variable is to "inject" the server instance into the call handler (assuming the handler is used only once):
```
       GreeterImpl greeterImpl = new GreeterImpl();
       server = NettyServerBuilder.forPort(port)
                .addService(greeterImpl)
                .build()
                .start();
       greeterImpl.setServer(server);
```
When the handler (`greeterImpl` above) receives the `shutdown()` RPC it can call shutdown on the server instance.

But a client telling a server to shutdown seems like an unusual pattern.

**Comment by abusalimov** [comment]
Right, that's what I ended up with too, thank you!

It is unusual, I agree, we use gRPC to establish IPC with a child process (the child is the server and the parent is the sole client), so in our case it's OK for the child to be told to shut down.

**Comment by sanjaypujare** [comment]
I am assuming that satisfies your requirement and you don't need to explore further - or open an issue for `SERVER_CONTEXT_KEY` accessibility. In that case please close this issue.
