### ISSUE TITLE
Apply package name shading to native-image config files in grpc-netty-shaded

### ISSUE THREAD

**Issue by dzou** [grpc/grpc-java#7540]
The `grpc-netty-shaded` JAR provides several config files under the `resources/META-INF` dir:

![image](https://user-images.githubusercontent.com/3209274/96633135-aed67380-12e6-11eb-980f-f701e954cc50.png)

I.e. `native-image.properties` and `reflection-config.json` in the screenshot.

Inside these config files, the library writers reference Netty package classes, and it would be very useful if these classes could also have their packages renamed during the shading process.

For example `META-INF/native-image/io.netty/codec-http/native-image.properties` is currently this:

```
Args = --initialize-at-build-time=io.netty \
       --initialize-at-run-time=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder
```

But it should be updated to this:

```
Args = --initialize-at-build-time=io.grpc.netty.shaded.io.netty \
       --initialize-at-run-time=io.grpc.netty.shaded.io.netty.handler.codec.http.HttpObjectEncoder,io.grpc.netty.shaded.io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.grpc.netty.shaded.io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder
```

These files and settings are used by Oracle's [GraalVM compiler](https://www.graalvm.org/reference-manual/native-image/) to assist in the ahead-of-time compilation process. The original library writers added it in so that it would work with native image building.

### Is your feature request related to a problem?

Yes, this will greatly contribute to the internal effort of getting [Google Cloud Java client libraries compatible with GraalVM native image compilation](https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support).

There is significant user interest from Native image app developers for this feature (Quarkus, Micronaut, Spring + GraalVM).

### Describe the solution you'd like

Is it possible to extend the shading process to apply package name updates to config files under `META-INF/native-image/`?

### Describe alternatives you've considered

Users can duplicate configuration on their own manually, but this runs the risk of going out of sync with the Netty repo when changes are made.

cc/ @meltsufin

**Comment by sanjaypujare** [comment]
cc @ejona86

**Comment by ejona86** [comment]
It appears https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/ is the documentation for this format.

It seems this will need a custom Transformer, potentially along with a Relocator to rework the folder structure. https://imperceptiblethoughts.com/shadow/configuration/merging/ . Ideally that code would be in the Shadow plugin so it can be reused by others.

**Comment by dzou** [comment]
> It appears https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/ is the documentation for this format.
> 
> It seems this will need a custom Transformer, potentially along with a Relocator to rework the folder structure. https://imperceptiblethoughts.com/shadow/configuration/merging/ . Ideally that code would be in the Shadow plugin so it can be reused by others.

Hey, I would like to contribute to this. Could you provide some more guidance on where the Transformer code would live, and how try testing out the shading logic?

**Comment by ejona86** [comment]
Initially the transformer code would probably live in https://github.com/grpc/grpc-java/blob/master/netty/shaded/build.gradle , but we should consider upstreaming it.

Here's the documentation for the shadow plugin: https://imperceptiblethoughts.com/shadow/configuration/merging/
