### ISSUE TITLE
Contextualized listeners chain support

### ISSUE THREAD

**Issue by jvmlet** [grpc/grpc-java#7544]
Currently, ContextualizedServerCallListener can be built only with  `ServerCall<ReqT, RespT> call`,
`Metadata headers` and `ServerCallHandler<ReqT, RespT> next` parameters which are used to create the  **wrapped** listener.
This allows to propagate context to the method implementation.

However, it's impossible to have another listener with access to the context.
Please expose ContextualizedServerCallListener to accept custom listener as the input argument :

In server interceptor : 
````
 @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
            ServerCall<ReqT, RespT> call,
            Metadata headers,
            ServerCallHandler<ReqT, RespT> next) {

var listener = new SimpleForwardingServerCallListener(next.startCall(call, headers)){
 @Override
  public void onMessage(ReqT message) {
    Context.current().... // listener has access to context as well 
  }
}
return Contexts.interceptCallWithContext(myCtx,listener) //new method
}
````

This will allow to build  contextualized chain of `contextualizedServerCallListener ->listener1->listener2->listenerN->methodCall`

instead of  only `contextualizedServerCallListener ->methodCall`

**Comment by sanjaypujare** [comment]
cc @ejona86

**Comment by voidzcy** [comment]
I think you can achieve the same outcome of having multiple `ServerCall.Listener`s access to the context by intercepting the `ServerCall` multiple times while with the outermost Interceptor providing the context.

**Comment by jvmlet** [comment]
Thanks @voidzcy, this might work. I'm proposing to have straightforward API.

**Comment by jvmlet** [comment]
The current interceptor API does not guarantee the invocation order and you have to be grpc developer / grpc team member to know that outmost interceptor is invoked first

**Comment by voidzcy** [comment]
Interceptors by definition never run in parallel, there is always an oder. It should be a fair requirement for users to know how the ordering works, especially for those mutating the call context and applying multiple custom interceptors. If they are completely unaware of the ordering, they are likely to get something wrong. The [`ServerInterceptors.intercept(...)` Javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerInterceptors.html#intercept-io.grpc.ServerServiceDefinition-java.util.List-) has some implication for the interceptor ordering.

Context is just ThreadLocal, or you can think of it as *global* for intercepted calls as the chain of interceptors run in the same thread. So there isn't really a propagation problem.

IMO, the main problem with your API proposal is that `ServerCall.Listener` should always be associated with its `ServerCall` that creates it. They should run in the same context/scope. If you want your listener to run in a context, you should also run the corresponding `ServerCall` in that context.

**Comment by ejona86** [comment]
> However, it's impossible to have another listener with access to the context.

@jvmlet, why do you need this? This seems strange to me. It would probably be helpful to describe what you are trying to do in your interceptor so we can help guide your approach.

**Comment by jvmlet** [comment]
@ejona86 , suppose I'm developing infrastructure for the dev department and I want them to concentrate on writing business logic  **only** (grpc service implementation), all other aspects, like:
* logging
* cache handling
* collecting metrics  
*  resolving additional arguments to be accessible in grpc methods (via context) - analog to Spring's MVC argument resolver

should be seamlessly provided to them. All these has to be contextual also and  user (`Authentication`) - specific.

So the design is to have interceptor that authenticates and authorizes the call, builds the chain of  listeners  described above and return top-level contextualized listener with `Authentication` object

**Comment by ejona86** [comment]
> So the design is to have interceptor that authenticates and authorizes the call, builds the chain of listeners described above and return top-level contextualized listener with Authentication object

You can do those things as interceptors. But if you aren't going to call the `next` Channel, then you aren't an interceptor. You're more of a stub, especially because you don't want to use the generated code to pass Authentication object explicitly to the app.

I suggest you do logging, cache handling, and make additional arguments accessible via context all within interceptors. But implement ServerCallHandler directly for the very last step before the application. You can then call the application with whatever arguments you want. You can take a look at ServerCalls and the generated code as an example of how to make stub.

**Comment by jvmlet** [comment]
Thanks @ejona86. What kind of tasks would you implement in  listener If all the above you suggest to implement in interceptors?

**Comment by ejona86** [comment]
I think this is the part I didn't fully understand:

> return top-level contextualized listener with Authentication object

It sounded like you wanted to pass the `Authentication` object explicitly to the service, like as an method argument. If it is just going to be stored in Context, then you could do everything as an interceptor.

**Comment by jvmlet** [comment]
@ejona86, my initial proposal was to provide API  to create Contextualized listener from another listener, so the  wrapped listener will have acess to the attributes in context.
Currently you provide API  to create contextualized listener only from call, next and headers variables. 
Being able to wrap the listener as contextualized allows access to context attributes.
