### ISSUE TITLE
gRPC server instantly resets stream for requests to one API after some time

### ISSUE THREAD

**Issue by Sovietaced** [grpc/grpc-java#7563]
Hi all. We are using java-grpc version 1.23.0 (EDIT: have noticed the same behavior in 1.32.2) and we are seeing some unusual behavior. After some amount of time of responding to requests normally our gRPC server will start sending `OUTBOUND RST_STREAM` in response to requests to only one of our APIs. The requests seems to make it to the Netty layer but never make it to our API implementation. Does anyone have an idea why this might be happening?

Some observations
* This only happens to one of our microservices (in a mesh of many)
* This only happens to a single API call on the server  

In the logs I see error codes 5 and 8 I believe are HTTP 2 error codes for stream closed and cancel.

Logs below following streamId=279535 (newer messages first FYI)
```

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] OUTBOUND RST_STREAM: streamId=279535 errorCode=8

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] OUTBOUND RST_STREAM: streamId=279535 errorCode=5

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=3936313438...

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=6e655f6964...
  
  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] OUTBOUND RST_STREAM: streamId=279535 errorCode=5

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] OUTBOUND RST_STREAM: streamId=279535 errorCode=5

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=756465223a...

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=7b226c616e...

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=3a34302e34...

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=7469747564...

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=3a2d37392e...

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=5b5d2c2270...

  | Oct 27, 2020 @ 16:50:10.396 | 23:50:10.396 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] OUTBOUND RST_STREAM: streamId=279535 errorCode=5

  | Oct 27, 2020 @ 16:50:10.395 | 23:50:10.395 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND DATA: streamId=279535 padding=0 endStream=false length=16384 bytes=223a5b5d7d...

  | Oct 27, 2020 @ 16:50:10.395 | 23:50:10.395 [grpc-default-worker-ELG-1-5-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x7d76ec40, <REDACTED>] INBOUND HEADERS: streamId=279535 headers=GrpcHttp2RequestHeaders[:path: /<redacted>, :authority: <redacted>, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.23.0, grpc-accept-encoding: gzip, grpc-timeout: 9999m, x-forwarded-proto: http, x-request-id: 82adf366-4b45-498e-b045-6e2966229aba, x-envoy-expected-rq-timeout-ms: 9999, x-b3-traceid: 849550ef8ae3ed3ea4d053bc28cb210d, x-b3-spanid: 5c805424f4592f87, x-b3-parentspanid: a4d053bc28cb210d, x-b3-sampled: 0] padding=0 endStream=false
```

**Comment by voidzcy** [comment]
Do you get any gRPC error or exception?

**Comment by Sovietaced** [comment]
> Do you get any gRPC error or exception?

There is no exception on the server side at all. The client eventually receives `UNAVAILABLE` gRPC error code. 

```
io.grpc.StatusRuntimeException: UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: remote reset
```

I will note that we are using Istio proxies on both the client and the server. The issue doesn't seem to happen on another environment where we have disabled the proxy on the server side. I'm still looking for some clarity as to why the server would still exhibit this behavior though.

**Comment by voidzcy** [comment]
@ejona86 Do you have any thoughts for this?

**Comment by ejona86** [comment]
> UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: remote reset

That doesn't look like a grpc-java error message, so I think a proxy or the application service is generating that.

I'm not concerned about errorCode=5, as that happens during normal network races. I'd have to see what happened before `OUTBOUND RST_STREAM: streamId=279535 errorCode=8` on that stream to see what is going on. But because it doesn't show up in the error message, it apparently can't matter too much.

I think we may send errorCode=5 when a service throws an exception. Maybe the service first provided a clear error and then crashed afterward.

**Comment by Sovietaced** [comment]
> That doesn't look like a grpc-java error message, so I think a proxy or the application service is generating that.

Yes, it is most likely the Istio proxy that is setting that message. 

> I'm not concerned about errorCode=5, as that happens during normal network races. I'd have to see what happened before `OUTBOUND RST_STREAM: streamId=279535 errorCode=8` on that stream to see what is going on. But because it doesn't show up in the error message, it apparently can't matter too much.

The logs are taken from elastic search so they are in DESC timestamp order. Everything below that is what was going on with the stream. Unless you mean something else. 

> I think we may send errorCode=5 when a service throws an exception. Maybe the service first provided a clear error and then crashed afterward.

I can take a look to see if there is anything unusual going on at the point at which it stops working. Otherwise, we wrap all our requests with a helper function that would log any issues. ie. 

```
/**
   * Wrapper that will safely catch any expected or unexpected exceptions and return a response to the client.
   *
   * @param responseObserver the response observer to set the response on
   * @param logger the logger to use for logging any errors
   * @param producer the lambda which produces the response
   */
  public static <R> void doHandleRequest(
      final StreamObserver<R> responseObserver,
      final Logger logger,
      final ThrowingProducer<R> producer
  ) {
    try {
      responseObserver.onNext(producer.produce());
      responseObserver.onCompleted();
    } catch (final StatusException | StatusRuntimeException e) {
      logger.error(e.getMessage(), e);
      responseObserver.onError(e);
    } catch (final Exception e) {
      logger.error("Encountered unexpected exception", e);
      responseObserver.onError(Status.INTERNAL
          .withCause(e)
          .asException()
      );
    }
  }
```

Additionally, I had added some trace level logging and confirmed that our API implementation was not even being reached.

**Comment by Sovietaced** [comment]
Some additional observations. 

The stream resets _do not happen to all requests_. It appears that some of the requests succeed while others result in stream resets. I have lots of requests both succeeding and being instantly reset in the same second, on the same pod, on the same container. The behavior doesn't seem to be deterministic yet. This would imply that the service has not crashed. 

Below are two distinct requests (different request sizes) and I can follow each of their streams in the logs. The request that fails is reported as 200 UR (upstream reset) by the Istio Proxy. 
```
  | Oct 27, 2020 @ 18:33:38.092 | [2020-10-28T01:33:32.408Z] "POST /<redacted> HTTP/2" 200 - "-" "-" 71174 119 73 72 "-" "grpc-java-netty/1.32.2" "cdf5ead5-e430-4633-a96a-50dc9494870b" "<redacted>" ...


  | Oct 27, 2020 @ 18:33:38.092 | [2020-10-28T01:33:34.222Z] "POST /<redacted> HTTP/2" 200 UR "-" "-" 309705 0 4 - "-" "grpc-java-netty/1.32.2" "6b103079-57c2-4edb-8b56-b2040e82df94" ...

```

**Comment by ejona86** [comment]
> The logs are taken from elastic search so they are in DESC timestamp order.

Oh, sorry, I missed that. Okay, then that log is useful. It is strange to see STREAM_CLOSED as the first RST_STREAM. I'd expect the CANCEL to be first. Maybe there's some weird RST reordering going on in the server library.

I took the liberty of further redacting the logs. The DATA seemed to include data you might not have wanted to share (it was hex-encoded ASCII).

The very first inbound DATA frame doesn't look right. There's two issues with it: 1) it appears to be JSON instead of a gRPC frame and 2) it looks like it was started in the middle (`":[]},"updated_epoch_ms":`...)

I think gRPC is trying to parse the gRPC frame and seeing it is either wrong (the first byte should normally be 0x00 or 0x01) or too large of a message (defaults to 4 MB). The message length would be interpreted as 0x3a5b5d7d which is about a GB.

The [server should have logged a WARNING](https://github.com/grpc/grpc-java/blob/80631db7a8ecf0c3d548c88a69b323dec8acf032/netty/src/main/java/io/grpc/netty/NettyServerStream.java#L219).

The gRPC server uses RST_STREAM instead of providing a clear error message to user for threading reasons (basically, if the application is sending at the same time as receiving the error, sending a clean error message can truncate messages).

**Comment by Sovietaced** [comment]
> I took the liberty of further redacting the logs. The DATA seemed to include data you might not have wanted to share (it was hex-encoded ASCII).

Thank you :)

> I think gRPC is trying to parse the gRPC frame and seeing it is either wrong (the first byte should normally be 0x00 or 0x01) or too large of a message (defaults to 4 MB). The message length would be interpreted as 0x3a5b5d7d which is about a GB.

I think I may have stripped off one message prior, my fault. Here is another stream that failed and it looks like the original `INBOUND DATA` looks correct (leading 0x00). 

```
Oct 27, 2020 @ 18:33:41.639	01:33:41.639 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] INBOUND DATA: streamId=1019 padding=0 endStream=false length=16384 bytes=....
	viaduct-2
	Oct 27, 2020 @ 18:33:41.639	01:33:41.639 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] OUTBOUND RST_STREAM: streamId=1019 errorCode=5
	viaduct-2
	Oct 27, 2020 @ 18:33:41.639	01:33:41.639 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] OUTBOUND RST_STREAM: streamId=1019 errorCode=5
	viaduct-2
	Oct 27, 2020 @ 18:33:41.639	01:33:41.639 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] OUTBOUND RST_STREAM: streamId=1019 errorCode=8
	viaduct-2
	Oct 27, 2020 @ 18:33:41.639	01:33:41.639 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] INBOUND DATA: streamId=1019 padding=0 endStream=false length=16384 bytes=323039393836323335342c226c6f6e676974756465223a2d37392e393834303733393039363733327d2c7b226c61746974756465223a34302e34353232333739...
	viaduct-2
	Oct 27, 2020 @ 18:33:41.639	01:33:41.639 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] INBOUND DATA: streamId=1019 padding=0 endStream=false length=16384 bytes=...
	viaduct-2
	Oct 27, 2020 @ 18:33:41.639	01:33:41.639 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] OUTBOUND RST_STREAM: streamId=1019 errorCode=5
	viaduct-2
	Oct 27, 2020 @ 18:33:41.639	01:33:41.639 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] INBOUND DATA: streamId=1019 padding=0 endStream=false length=15999 bytes=...
	viaduct-2
	Oct 27, 2020 @ 18:33:41.638	01:33:41.638 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] INBOUND HEADERS: streamId=1019 headers=GrpcHttp2RequestHeaders[:path: /<redacted>, :authority: <redacted>, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.32.2, grpc-accept-encoding: gzip, grpc-timeout: 9999m, x-forwarded-proto: http, x-request-id: 6c3584ec-49f8-4ba7-b3f0-9059a0a0f011, x-envoy-expected-rq-timeout-ms: 9999, x-b3-traceid: 9f240701ae3dd63a02851fb92fc24127, x-b3-spanid: ec49c65043097d47, x-b3-parentspanid: 02851fb92fc24127, x-b3-sampled: 0] padding=0 endStream=false
	viaduct-2
	Oct 27, 2020 @ 18:33:41.638	01:33:41.638 [grpc-default-worker-ELG-1-6-] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - [id: 0x3f9452f2, <redacted>] INBOUND DATA: streamId=1019 padding=0 endStream=false length=16384 bytes=00012422340a80ac040a2466653138663064382d373935642d343562642d393563662d3665316530326434353135371215<redacted>....
```

The reason you are seeing some JSON in the data is because one of our fields is string that holds a JSON string.

**Comment by ejona86** [comment]
Ah, excellent. Yeah, that looks much better (although there still seems to be some reordering going on, whatever). That message has a size of 0x01242234 = 19 MB. That's larger than the default allowed size of 4 MB. If the server hasn't increased the maximum message size, then that would likely be the cause of the failure. I don't know why you don't see the warning on your server-side logs though.

**Comment by Sovietaced** [comment]
> Ah, excellent. Yeah, that looks much better (although there still seems to be some reordering going on, whatever). That message has a size of 0x01242234 = 19 MB. That's larger than the default allowed size of 4 MB. If the server hasn't increased the maximum message size, then that would likely be the cause of the failure. I don't know why you don't see the warning on your server-side logs though.

Brilliant thank you! Looks like we had set a limit of 10MB that is obviously getting exceeded now. I'll look into why those size limit exceeded messages aren't appearing and updated the issue accordingly.

**Comment by ejona86** [comment]
@Sovietaced, I am sorry you didn't get a better error message. The server-side warning is weak but generally "good enough." I do wish we could deliver a clear error message to the client, but I'll just say it isn't a simple discussion.
