### ISSUE TITLE
gRPC client blocks indefinitely

### ISSUE THREAD

**Issue by sourav-jha** [grpc/grpc-java#7579]
### What version of gRPC-Java are you using?

- 1.25.0

### What is your environment?

- Linux

- Java 11 x64

### What did you expect to see?
On restarting the gRPC server we expect all the client connections to close. But this doesn't seem to happen.
### What did you see instead?
The connection on the client-side remains as it is, for some client requests we got 
```CANCELLED: io.grpc.Context was cancelled without error ```, After that all the requests got blocked indefinitely. 
Note: We have DNS for load balancing.
### Steps to reproduce the bug

1. Start a gRPC server. 
2. Make some calls to gRPC server through the client.
3. Try simultaneously restarting the server.
4. Try making new calls to the server using the client mentioned in 2.

**Comment by ejona86** [comment]
> Try simultaneously restarting the server.

What does "restart" mean to you? Did you shutdown the `io.grpc.Server`? Did you restart the process? Did you restart the machine?

If the TCP shutdown was abrupt (like the machine crashed), then you would need to have keepalive enabled via ManagedChannelBuilder to detect the broken connections.

**Comment by sourav-jha** [comment]
in our case it was abrupt.

**Comment by sourav-jha** [comment]
In our case, it wasn't abrupt.

**Comment by ejona86** [comment]
@sourav-jha, how did you "restart" the server?

**Comment by ejona86** [comment]
There's not enough information at the moment. Comment with the restart details and we can reopen the issue.
