### ISSUE TITLE
RetriableStream backoff algorithm

### ISSUE THREAD

**Issue by ccreeten** [grpc/grpc-java#7591]
Hi there, I have a question about the implementation of the RetriableStream. I am trying to configure a gRPC client using a retryPolicy. If I for example configure it to try 5 times, with an initial backoff of 2s and max of 10s, multiplier two, it can result in a set of backoffs looking like:
```
Retrying with backoff 1107ms
Retrying with backoff 106ms
Retrying with backoff 6929ms
Retrying with backoff 545ms
```
I would have expected it to go in a generally more incremental direction. It seems that for each iteration the next backoff is taken from a range (0, nextBackoff):
```
backoffNanos = (long) (nextBackoffIntervalNanos * random.nextDouble());
nextBackoffIntervalNanos = Math.min(
    (long) (nextBackoffIntervalNanos * retryPolicy.backoffMultiplier),
    retryPolicy.maxBackoffNanos);
```
Is this expected behaviour? Shouldn't instead some small amount of jitter be applied instead? Thanks!

**Comment by ericgribkoff** [comment]
cc @dapengzhang0

**Comment by ccreeten** [comment]
I have searched a bit more, and found a google groups discussion about this where it is mentioned that it was explicitly chosen for this implementation, referring to the 'full jitter' implementation here: [](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/).

**Comment by dapengzhang0** [comment]
@ccreeten We implemented the backoff algorithm documented here https://github.com/grpc/proposal/blob/master/A6-client-retries.md#exponential-backoff. 

```
actual backoff = random(0, min(exponential backoff, max backoff))
```

I can agree that the algorithm in the aws document in your comment

```
temp = min(exponential backoff, max backoff)
actual backoff = temp/2 + random(0, temp/2)
```

make more sense in some cases.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
