### ISSUE TITLE
grpc Client-Streaming Java Client gets io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 503

### ISSUE THREAD

**Issue by bettafish15** [grpc/grpc-java#7607]
I have a grpc Nodejs server behind a HAproxy and client-streaming rpc java maven. 
When i run the java client it return an error:

io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 503
invalid content-type: text/html
headers: Metadata(:status=503,cache-control=no-cache,content-type=text/html)
DATA-----------------------------
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

I already test a rpc client streaming with Nodejs and it worked. 

My java client code:

```java
public class App {
    public static void main(String[] args) throws InterruptedException {
        WebRTCStats stat = WebRTCStats.newBuilder().setUserId("abc").build();
        SendWebRTCStats(stat);
    }

    public static void SendWebRTCStats(WebRTCStats stat) throws InterruptedException {
        ManagedChannel channel = ManagedChannelBuilder.forTarget("rtcstats1.sohatv.vn:443").useTransportSecurity()
                .build();
        ClientGrpc.ClientStub stub = ClientGrpc.newStub(channel);

        StreamObserver<Stat.Status> responseObserver = new StreamObserver<Stat.Status>() {
            @Override
            public void onNext(Stat.Status status) {

            }

            @Override
            public void onError(Throwable t) {
                t.printStackTrace();
            }

            @Override
            public void onCompleted() {
                System.out.print("complete");
            }
        };
        StreamObserver<WebRTCStats> requestObserver = stub.sendWebRTCStats(responseObserver);
        try {
            // Send numPoints points randomly selected from the features list.

            requestObserver.onNext(stat);
            // Sleep for a bit before sending the next one.

        } catch (RuntimeException e) {
            // Cancel RPC
            requestObserver.onError(e);
            throw e;
        }
        // Mark the end of requests
        requestObserver.onCompleted();

        // Receiving happens asynchronously

    }
}
```

My NodeJS server:
```js
const PROTO_PATH = './stat.proto';
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
const fs = require('fs');
const tcp = require('./using.js');

let packageDefinition = protoLoader.loadSync(PROTO_PATH);

let protoDescriptor = grpc.loadPackageDefinition(packageDefinition);

const server = new grpc.Server();


server.addService(protoDescriptor.Client.service, {
    SendWebRTCStats: async (call, callback) => {
        call.on('data', value => {
            console.log(value);
            tcp.sendLog("test", value);
        });

        call.on('end', () => {
            callback(null, { status: 'success' });
        })
    },
});

let credentials = grpc.ServerCredentials.createSsl(
    fs.readFileSync('ca.cer'), [{
    cert_chain: fs.readFileSync('cer.crt'),
    private_key: fs.readFileSync('cer_key.key')
}], false);

server.bind("0.0.0.0:443", credentials);
console.log("Server running at 443");
server.start();
```

Can this problem occurs by different implementations of different libraries of language in GRPC?

**Comment by ericgribkoff** [comment]
The 503 error code you're getting back does not seem to be coming from a gRPC server, as best I can tell. Any response from a gRPC server should include a grpc-status header field. Instead I would think that a proxy between your client and the server is terminating the connection with the 503 error code.

You say that a Node client worked with this setup. Are you sure that the Node client was going through the same proxies as your Java client? If so, could it be that your Java client is using a different definition of the proto service than the Node client/server, which (depending on how your proxy is configured) could result in the proxy terminating the connection for the Java client? It could also be helpful to debug if you could determine if your Java client can communicate directly with the server, without the proxy in the middle.

> Can this problem occurs by different implementations of different libraries of language in GRPC?

It's possible, but it would a bug and something we would fix. We have interop tests to verify that all languages are compatible. What versions of the gRPC libraries are you using for the clients and server?

**Comment by bettafish15** [comment]
@ericgribkoff  
So i removed the haproxy between them and let the Java client and nodejs server talking directly through Grpc. When i connected using no TLS it worked! yay ! But when i try to use TLS on NodeJS server then java client connected failed. This is the error on NodeJS server:
```
E1111 09:03:49.061000000 23708 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
```
Does Java grpc and NodeJS grpc have different TLS implementation or i am doing wrong something?

**Comment by ericgribkoff** [comment]
I'm not sure. There was [this issue](https://github.com/grpc/grpc/issues/20858) reported on the gRPC core repo a while ago, but the poster did not reply back with/if it was resolved. Just a guess, but this [StackOverflow](https://stackoverflow.com/questions/56482941/configuring-proton-for-ssl-tls-throwing-openssl-wrong-version-number-and-grpc) post suggests that you might get this error if the client is not actually using TLS - are you sure the Java client is configured to use TLS and not plaintext when trying to connect?

**Comment by bettafish15** [comment]
@ericgribkoff according to my understanding, the useTransportSecurity() is forcing Java client to use TLS right? I changed it to use transportSecurity and it led to 
```
unable to find valid certification path to requested target
```
but i guess it is that i havent imported the certs into certs store yet.

**Comment by ericgribkoff** [comment]
`useTransportSecurity()` is actually a server-side option. Both the server and client need to be using TLS for the connection to work.

The default for a Java client is actually to use TLS. As long as you're not invoking `usePlaintext()` on the Java channel builder, TLS should be used. You can see a brief example of how TLS is configured for Java [here](https://grpc.io/docs/guides/auth/#with-server-authentication-ssltls-5). You may need to configure your Java channel to accept the cert provided by the server as shown, but even if not, that should result in a much more helpful error (e.g., cert invalid in the error status returned by the Java client).

**Comment by bettafish15** [comment]
@ericgribkoff omg thanks so much for your help. The problem go away when i use forTarget() without port, my proxy and my client is fine . I am wasted whole day for this haha
