### ISSUE TITLE
io.netty.channel.epoll.Native.epollWait0 Takes up most of the CPU

### ISSUE THREAD

**Issue by shiyiyue1102** [grpc/grpc-java#7608]
I send 15000 tps from clients in my loader testing,then I found my server's cpu up to 95%

top:
![image](https://user-images.githubusercontent.com/20452676/98667508-6cee9980-2389-11eb-825c-51ab7fb54c6b.png)
jstack info for the top threads :

![image](https://user-images.githubusercontent.com/20452676/98667581-898ad180-2389-11eb-9ab0-888593ec3391.png)

grpc-java version is : 1.24.0  （grpc-netty shaded ）
![image](https://user-images.githubusercontent.com/20452676/98668132-6a407400-238a-11eb-923e-eaad93f1f3e8.png)

 **is it normal that this native method take up most of the cpu?**

**Comment by ejona86** [comment]
Those stack traces show epollWait. That's the stack trace of an _idle_ thread. That stack trace does not generate any CPU utilization until an event comes and returns from the kernel. So it is appropriate that many threads are sitting there not contributing toward CPU usage.

**Comment by sanjaypujare** [comment]
This [Stackoverflow post](https://stackoverflow.com/questions/47630538/epoll-wait-consume-too-much-cpu) discusses something similar. Please read the comments at the bottom.

**Comment by shiyiyue1102** [comment]
> Those stack traces show epollWait. That's the stack trace of an _idle_ thread. That stack trace does not generate any CPU utilization until an event comes and returns from the kernel. So it is appropriate that many threads are sitting there not contributing toward CPU usage.

You mean that epoolWait is not a CPU-consuming operation, but other operations  that not showed in the stacktrace in the same thread？

**Comment by ejona86** [comment]
I'm saying the stack traces you showed showed no CPU usage. Either other threads are using CPU or you missed the point where those threads were using CPU.

**Comment by shiyiyue1102** [comment]
> I'm saying the stack traces you showed showed no CPU usage. Either other threads are using CPU or you missed the point where those threads were using CPU.

Thank ,I have found the actual cpu usage via Arthas profiler .
