### ISSUE TITLE
NPE when getting remote address

### ISSUE THREAD

**Issue by LeoBarykin** [grpc/grpc-java#7625]
Hello!
I have implemented a metric in grpc server to track incoming connections using transportFilter API.
It works good on local machine, but having deployed my app into openshift I faced strange warn messages with NPE.
The code which throws exception:
transportAttrs.get(TRANSPORT_ATTR_REMOTE_ADDR)
Any idea why it can happen?
I attached the log.
[connection-metric-log.txt](https://github.com/grpc/grpc-java/files/5548059/connection-metric-log.txt)

Thank you.

**Comment by dapengzhang0** [comment]
The `transportAttrs` is null until the transport is READY, if you call `transportAttrs.get()` before READY is happening, you will see NPE. Implementer should avoid calling `transportAttrs.get()` before READY. See the `@param transportAttrs` description in the  javadoc

```java
  /**
   * Called when a transport is terminated.  Default implementation is no-op.
   *
   * @param transportAttrs the effective transport attributes, which is what returned by {@link
   * #transportReady} of the last executed filter.
   */
  public void transportTerminated(Attributes transportAttrs) {
  }
```

**Comment by LeoBarykin** [comment]
@dapengzhang0 thank you for your answer. 
If I understand you right, transportTerminated() can be called without transportReady() before it, e.g. id handshake fails, only transportTerminated() is executed?

**Comment by dapengzhang0** [comment]
> If I understand you right, transportTerminated() can be called without transportReady() before it, e.g. id handshake fails, only transportTerminated() is executed?

Correct.
