### ISSUE TITLE
Flake: Cannot transition phase from STATUS to MESSAGE

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#765]
As seen in https://travis-ci.org/grpc/grpc-java/builds/74499477:
```
io.grpc.testing.integration.Http2NettyLocalChannelTest > deadlineExceeded FAILED
    java.lang.AssertionError: expected:<Status{code=DEADLINE_EXCEEDED, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.lang.IllegalStateException: Cannot transition phase from STATUS to MESSAGE}>
```

Not much to go on. This can just track occasions that we see it.

**Comment by ejona86** [comment]
Other occurrences:
https://travis-ci.org/grpc/grpc-java/builds/74456246
https://travis-ci.org/grpc/grpc-java/builds/74162145

**Comment by carl-mastrangelo** [comment]
Perhaps a race between the deadline executor and the actual response.  If the deadline is reached, the transport will be put in STATUS right?

**Comment by ejona86** [comment]
@carl-mastrangelo, yes I think you are right.

This is caused by deadline-caused cancel() failing future messages that are written. We either need to not change the outboundPhase for cancel() or remove outboundPhase() outright, since ClientCallImpl checks state.

https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractClientStream.java#L296

**Comment by ejona86** [comment]
I've not seen this in a while. @carl-mastrangelo, did we end up fixing this?

**Comment by carl-mastrangelo** [comment]
@ejona86 I don't believe so.
