### ISSUE TITLE
Confusing about ManagedChannelBuilder.forAddress 

### ISSUE THREAD

**Issue by Adol1111** [grpc/grpc-java#7650]
I have two grpc client.
1. one use custom nameresolver and priority > DNSNameResolver `ManagedChannelBuilder.forTarget("my-resolver:///service")`
2. one use default nameresolver. `ManagedChannelBuilder.forAddress(ip, port)`. I expect  it will call DNSNameResolver，but in fact, it call custom resolver.

this is ok
```
ManagedChannel channel = ManagedChannelBuilder.forAddress(ip,port)
                .nameResolverFactory(new DnsNameResolverProvider())
                .build()
```

```
ManagedChannel channel = ManagedChannelBuilder.forAddress("dns:///ip:port")
                .build()
```

 It's  very confusing for `ManagedChannel.forAddress`. The behavior will be changed by register NameResolverProvider.

**Comment by voidzcy** [comment]
You should avoid using the `nameResolverFactory()` API, it is [being deprecated](https://github.com/grpc/grpc-java/blob/2bf5ef54dabbbfc0881a4ef3122eabc1f6bdde5c/api/src/main/java/io/grpc/ManagedChannelBuilder.java#L218-L223). The Java service provider approach is the preferred way.

**Comment by Adol1111** [comment]
@voidzcy I see`nameResolverFactory` is being deprecated. 

But if only use `forAddress`，it don't call DNSNameResolver for sure.  
The only way is use `ManagedChannelBuilder.forTarget("dns:///ip:port")` instead.

So I think `forAddress` API shoud be deprecated or convert  ip + port  to "dns:///ip:port" internal.

**Comment by Adol1111** [comment]
```
if (targetUri != null) {
      NameResolver resolver = nameResolverFactory.newNameResolver(targetUri, nameResolverArgs);
      if (resolver != null) {
        return resolver;
      }
      // "foo.googleapis.com:8080" cause resolver to be null, because "foo.googleapis.com" is an
      // unmapped scheme. Just fall through and will try "dns:///foo.googleapis.com:8080"
    }

    // If we reached here, the targetUri couldn't be used.
    if (!URI_PATTERN.matcher(target).matches()) {
      // It doesn't look like a URI target. Maybe it's an authority string. Try with the default
      // scheme from the factory.
      try {
        targetUri = new URI(nameResolverFactory.getDefaultScheme(), "", "/" + target, null);
      } catch (URISyntaxException e) {
        // Should not be possible.
        throw new IllegalArgumentException(e);
      }
      NameResolver resolver = nameResolverFactory.newNameResolver(targetUri, nameResolverArgs);
      if (resolver != null) {
        return resolver;
      }
    }
```

This API use `nameResolverFactory.getDefaultScheme()` not dns. Sometimes it will call other NameResolver if it priority is higher than dns nameresolver

**Comment by voidzcy** [comment]
> This API use nameResolverFactory.getDefaultScheme() not dns. Sometimes it will call other NameResolver if it priority is higher than dns nameresolver

You are right. `forAddress()` is one of the oldest APIs of gRPC, before NameResolvers became pluggable. Yes, it uses the scheme of the resolver with the highest priority. This might be a bit surprising and we put some [doc on `forTarget()`](https://github.com/grpc/grpc-java/blob/2bf5ef54dabbbfc0881a4ef3122eabc1f6bdde5c/api/src/main/java/io/grpc/ManagedChannelBuilder.java#L60-L61):

> We recommend libraries to specify the schema explicitly if it is known, since libraries cannot know which NameResolver will be default during runtime.

It may surprise users, but not necessarily be broken. We'd also generally recommend using priorities lower than DNS for custom resolvers to preserve the default behavior for `forAddress()`. But if you know what's going on, it's safe to use higher priorities. Anyway, it's more recommended to use `forTarget()` with advanced usages such as providing custom resolvers.

**Comment by Adol1111** [comment]
Thanks for your answer.

**Comment by sanjaypujare** [comment]
@Adol1111 can this issue be closed?

**Comment by Adol1111** [comment]
yes，of course
