### ISSUE TITLE
Full method name should be consistent with that from Protobuf

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-java#7651]
Given method `Greet`:
```
package com.example;

service GreetingService {
    rpc Greet(com.example.GreetRequest) returns (com.example.GreetResponse) {};
}
```

The [com.google.protobuf.Descriptors.MethodDescriptor.getFullName](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Descriptors.MethodDescriptor.html#getFullName--) returns `com.example.GreetingService.Greet`, but [io.grpc.MethodDescriptor.generateFullMethodName](https://grpc.github.io/grpc-java/javadoc/io/grpc/MethodDescriptor.html#generateFullMethodName-java.lang.String-java.lang.String-) returns `com.example.GreetingService/Greet`. This is super confusing, and also error prone when making calls using low level `ClientCalls` API. For example, the [gRPC CLI](https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md#list-methods) expects method name as `com.example.GreetingService.Greet`.

### What version of gRPC-Java are you using?
1.33.1

### What is your environment?
JDK 11

### What did you expect to see?
The full name should be consistent with that from Protobuf.

### What did you see instead?
They don't match.

**Comment by sanjaypujare** [comment]
Couple of comments:

- the gRPC generated full method name is better since the "/" clearly demarcates the method name from the service name.
- even if we want to match Protobuf it's going to cause backward compatibility issues for existing users of `io.grpc.MethodDescriptor.generateFullMethodName` (and probably others)

So I don't think there is much we can do at this point. What do you think?

**Comment by asarkar** [comment]
Unless the API can be changed in the next major version, I will have to grudgingly agree with you. Good thing is, `io.grpc.MethodDescriptor` is unlikely to be used directly by a lot of people.

**Comment by sanjaypujare** [comment]
So I am going to close this issue since there is nothing actionable here. But if you think of something you can add a comment and we can reopen the issue.
