### ISSUE TITLE
direct memory leak detected via ResourceLeakDetector

### ISSUE THREAD

**Issue by shiyiyue1102** [grpc/grpc-java#7655]
Hi ,I use biStream model to send messages to client from server,But I found en error throw  after a few minutes, `OutOfDirectMemoryError("failed to allocate " + capacity + " byte(s) of direct memory (used: " + (newUsedMemory - (long)capacity) + ", max: " + DIRECT_MEMORY_LIMIT + ')');`   at  `io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent#incrementMemoryCounter,.`
then I detect memory leak via use ResourceLeakDetector 

```
Recent access records: 
#1:
	io.grpc.netty.shaded.io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:616)
	io.grpc.netty.shaded.io.grpc.netty.NettyWritableBuffer.write(NettyWritableBuffer.java:35)
	io.grpc.internal.MessageFramer.writeRaw(MessageFramer.java:290)
	io.grpc.internal.MessageFramer.access$400(MessageFramer.java:43)
	io.grpc.internal.MessageFramer$OutputStreamAdapter.write(MessageFramer.java:377)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:3005)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:3013)
	com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1373)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2801)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2775)
	com.google.protobuf.Any.writeTo(Any.java:349)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2855)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2824)
	com.alibaba.nacos.api.grpc.auto.Payload.writeTo(Payload.java:179)
	com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:82)
	io.grpc.protobuf.lite.ProtoInputStream.drainTo(ProtoInputStream.java:52)
	io.grpc.internal.MessageFramer.writeToOutputStream(MessageFramer.java:269)
	io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:230)
	io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:168)
	io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:141)
	io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:53)
	io.grpc.internal.ServerCallImpl.sendMessageInternal(ServerCallImpl.java:167)
	io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:149)
	io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:351)
	com.alibaba.nacos.core.remote.grpc.GrpcConnection.sendRequestNoAck(GrpcConnection.java:61)
	com.alibaba.nacos.core.remote.grpc.GrpcConnection.sendRequestInner(GrpcConnection.java:91)
	com.alibaba.nacos.core.remote.grpc.GrpcConnection.asyncRequest(GrpcConnection.java:129)
	com.alibaba.nacos.core.remote.RpcPushService.pushWithCallback(RpcPushService.java:55)
	com.alibaba.nacos.config.server.remote.RpcConfigChangeNotifier$RpcPushTask.run(RpcConfigChangeNotifier.java:162)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	java.lang.Thread.run(Thread.java:756)
Created at:
	io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:123)
	io.grpc.netty.shaded.io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:51)
	io.grpc.internal.MessageFramer.writeRaw(MessageFramer.java:287)
	io.grpc.internal.MessageFramer.access$400(MessageFramer.java:43)
	io.grpc.internal.MessageFramer$OutputStreamAdapter.write(MessageFramer.java:377)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:3005)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:3013)
	com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1373)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2801)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2775)
	com.google.protobuf.Any.writeTo(Any.java:349)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2855)
	com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2824)
	com.alibaba.nacos.api.grpc.auto.Payload.writeTo(Payload.java:179)
	com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:82)
	io.grpc.protobuf.lite.ProtoInputStream.drainTo(ProtoInputStream.java:52)
	io.grpc.internal.MessageFramer.writeToOutputStream(MessageFramer.java:269)
	io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:230)
	io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:168)
	io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:141)
	io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:53)
	io.grpc.internal.ServerCallImpl.sendMessageInternal(ServerCallImpl.java:167)
	io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:149)
	io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:351)
	com.alibaba.nacos.core.remote.grpc.GrpcConnection.sendRequestNoAck(GrpcConnection.java:61)
	com.alibaba.nacos.core.remote.grpc.GrpcConnection.sendRequestInner(GrpcConnection.java:91)
	com.alibaba.nacos.core.remote.grpc.GrpcConnection.asyncRequest(GrpcConnection.java:129)
	com.alibaba.nacos.core.remote.RpcPushService.pushWithCallback(RpcPushService.java:55)
	com.alibaba.nacos.config.server.remote.RpcConfigChangeNotifier$RpcPushTask.run(RpcConfigChangeNotifier.java:162)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	java.lang.Thread.run(Thread.java:756)
```

grpc-version: 1.24.0 

 max direct memory size : 4G
Cound any one give me some instruction? It is a bug or not ?

**Comment by sanjaypujare** [comment]
Couple of things to do: 
- can you use the latest gRPC release v1.33.1 ?
- are you able to verify your client is draining the stream appropriately?

**Comment by shiyiyue1102** [comment]
> Couple of things to do:
> 
> * can you use the latest gRPC release v1.33.1 ?
> * are you able to verify your client is draining the stream appropriately?

Ok,I will try to use v1.33.1 and see if this memory leak occurs still .
 By the way ,is it related to the client? In my opinion, the message framer create the byte buffer and send it to the write queue，netty should release the byte buffer both in normal case and abnormal case to avoid memory leak, such as channel closed ，high client load，etc...

**Comment by sanjaypujare** [comment]
> ...netty should release the byte buffer both in normal case and abnormal case to avoid memory leak, such as channel closed ，high client load，etc...

Are you implying an issue in netty then?

**Comment by shiyiyue1102** [comment]
> > ...netty should release the byte buffer both in normal case and abnormal case to avoid memory leak, such as channel closed ，high client load，etc...
> 
> Are you implying an issue in netty then?

It seems that something works exception in Bidirectional streaming In high load push scenarios
 , I have tried "Simple RPC" but not detect memory leak.

**Comment by shiyiyue1102** [comment]
> > > ...netty should release the byte buffer both in normal case and abnormal case to avoid memory leak, such as channel closed ，high client load，etc...
> > 
> > 
> > Are you implying an issue in netty then?
> 
> It seems that something works exception in Bidirectional streaming In high load push scenarios
> , I have tried "Simple RPC" but not detect memory leak.

read data from server via “Simple RPC” model ,  not detect memory leak
![image](https://user-images.githubusercontent.com/20452676/100051270-77636580-2e56-11eb-8da6-9629dbbca5bb.png)
not detect memory leak
![image](https://user-images.githubusercontent.com/20452676/100051349-a679d700-2e56-11eb-9838-11a3dec4e985.png)
700M  Direct Memory used and not increasing.
![image](https://user-images.githubusercontent.com/20452676/100051679-67985100-2e57-11eb-923c-57f8621cf409.png)

push data to client  via “ Bidirectional streaming ” model ,  detect memory leak
2.5G Direct Memory used and increasing till running out of memory 
![image](https://user-images.githubusercontent.com/20452676/100052303-95ca6080-2e58-11eb-849c-a324c1f7e8b2.png)

![image](https://user-images.githubusercontent.com/20452676/100052380-c5796880-2e58-11eb-8c29-fc68c67f9a5f.png)

**Comment by shiyiyue1102** [comment]
It seems that I have found the problem, it is because the method StreamObserver#next() is not Thread Safe. If it is called  by multi thread, the filed "buffer" of theMessageFramer will be overwrite and thus result in the memory leak.  
I   use StreamObserver#onNext inner "synchronized" and memory leak disappear

**Comment by sanjaypujare** [comment]
> It seems that I have found the problem, it is because the method StreamObserver#next() is not Thread Safe. If it is called by multi thread, the filed "buffer" of theMessageFramer will be overwrite and thus result in the memory leak.
> I use StreamObserver#onNext inner "synchronized" and memory leak disappear

Can you include snippets of your code change or point to the patch/diiff? Not clear where you made the code change.

**Comment by shiyiyue1102** [comment]
> > It seems that I have found the problem, it is because the method StreamObserver#next() is not Thread Safe. If it is called by multi thread, the filed "buffer" of theMessageFramer will be overwrite and thus result in the memory leak.
> > I use StreamObserver#onNext inner "synchronized" and memory leak disappear
> 
> Can you include snippets of your code change or point to the patch/diiff? Not clear where you made the code change.

My code:
![image](https://user-images.githubusercontent.com/20452676/100174980-80147400-2f08-11eb-903c-ce29ab0b4ee9.png)
MessageFramer#buffer
![image](https://user-images.githubusercontent.com/20452676/100175211-ea2d1900-2f08-11eb-817c-85686b152c7b.png)

In my scene，StreamObserver#next() may be call by multithread, it may cause memory leak without "synchronized"

**Comment by sanjaypujare** [comment]
> ...
> In my scene，StreamObserver#onNext() may be called by multithreads, it may cause memory leak without "synchronized"

You are expected to do this as per the comment here: https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/StreamObserver.java#L32

So I don't think this is an issue in the gRPC library.

**Comment by shiyiyue1102** [comment]
> > ...
> > In my scene，StreamObserver#onNext() may be called by multithreads, it may cause memory leak without "synchronized"
> 
> You are expected to do this as per the comment here: https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/StreamObserver.java#L32
> 
> So I don't think this is an issue in the gRPC library.

Ok,Thanks.
