### ISSUE TITLE
Grpc transfers a large amount of data files, which takes up a lot of memory  buff/cache

### ISSUE THREAD

**Issue by yangxh0306** [grpc/grpc-java#7656]

**Comment by yangxh0306** [comment]
I use grpc to transfer a large amount of data files. I find that it takes up a lot of buff / cache on the server. How can I limit it?

**Comment by sanjaypujare** [comment]
Have you considered using flow control on the server as explained here https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java to limit

**Comment by yangxh0306** [comment]
> 你有没有使用服务器的流量控制视为解释这里https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java到限制

Thank you for your advice. I'll give it a try

**Comment by ejona86** [comment]
This seems likely to be resolved. If it turns out not to be, comment, and it can be reopened.
