### ISSUE TITLE
thread hangs and cannot exit

### ISSUE THREAD

**Issue by wwulfric** [grpc/grpc-java#7691]
### What version of gRPC-Java are you using?

1.26.0 

### What is your environment?

linux, jdk8

### What did you see instead?
Thread is hanging.

jstack log:
```
"http-nio-8080-exec-12" #72 daemon prio=5 os_prio=0 tid=0x00007f0468003800 nid=0x1994 waiting on condition [0x00007f04440ba000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c1af8908> (a io.grpc.stub.ClientCalls$ThreadlessExecutor)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:681)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:133)
```

error log:
```
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
```

### Steps to reproduce the bug

I've read some issues(#7362, #7579, #5286, #7635), but cannot figure out the reason. It's very difficult to reproduce it.

In my env, it seems because of unexpected channel.shutdown:

``` java
## Thread1
blockingUnaryCall();
...
channel.shutdownNow();

## Thread2
blockingUnaryCall();
```

Thread1 and Thread2 hold the same channel. Thread1 shutdown channel unexpectedly. Is it possobile that Thread2 will hang?

**Comment by ejona86** [comment]
I don't think those issues you linked to are clearly related. The PR was for a bug that was never released. #7635 could be related, but I'd expect to see other errors in the log.

1.26.0 is a year old. You should try a newer version for us to provide more support. It isn't useful for us to dig into that old of a version.

Calling shutdownNow should cause any blocking calls to return (and throw). It should not cause them to hang. You can try calling `channel.awaitTerminated()` after the `shutdownNow()` to double-check that the channel is able to shut down; if there was any problem during shutdown, then it could impact RPCs.

**Comment by wwulfric** [comment]
```
[2020-11-24 21:15:29 WARN ] [XA-2] {io.netty.channel.nio.NioEventLoop:539}-Unexpected exception in the selector loop.
java.lang.NoSuchMethodError: io.netty.channel.nio.NioEventLoop.initialNanoTime()J
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:799)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
```

Grpc 1.26 introduces netty 4.1.42, which is conflicted with 4.1.38 introduced by my sources. And it will cause NoSuchMethodError occasionally. Is it the possible reason?

**Comment by ejona86** [comment]
If you see `Error`s of any sort, then that could easily be the cause. That particular one looks very nasty. You need to resolve that. Swapping from `grpc-netty` to `grpc-netty-shaded` may be the easiest approach.

**Comment by ejona86** [comment]
Seems like this should be once the version selection is resolved. If not, comment, and it can be reopened.

**Comment by fangxlmr** [comment]
Though this is a relatively old issue, I'd like to ask @wwulfric did you find anything? I encountered the same issue and I found out it's hard to reproduce as well.

Here is the story:
I use `ScheduledThreadPoolExecutor.scheduleWithFixedDelay` to setup a scheduled task sending heartbeat to a NameService, like:
```Java
                ScheduledThreadPoolExecutor ex = new ScheduledThreadPoolExecutor(2);
                ex.scheduleWithFixedDelay(() -> {
                    try {
                        // Sending heartbeat
                        nameService.heartbeat();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }, 5, 5, TimeUnit.SECONDS);
```

whereas `heartbeat` utilize grpc unary blocking call, which in turn looks like 

```Java
NameServiceGrpc.NameServiceGrpcBlockingStub stub = NameServiceGrpc.newBlockingStub(channel);
stub.heartbeat();  // This is where it hangs forever
```

Here is what from `jstack`
```java
"pool-12-thread-1" #111 prio=5 os_prio=0 cpu=233.72ms elapsed=6835.70s tid=0x00007fb66a9aa000 nid=0xd1 waiting on condition  [0x00007fb6074cd000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x0000000092930000> (a io.grpc.stub.ClientCalls$ThreadlessExecutor)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:194)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:731)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
	at com.exeample.pb.NameServiceGrpc$NameServiceBlockingStub.heartbeat(NameServiceGrpc.java:431)
```

I use gradle with relatively new grpc dependency as 
```gradle
dependencies {
    implementation 'io.grpc:grpc-netty-shaded:1.35.0'
    implementation 'io.grpc:grpc-protobuf:1.35.0'
    implementation 'io.grpc:grpc-stub:1.35.0'
}
```

My question is:
In what situation, grpc-java `blockingStub` calls will blocking forever?

**Comment by fangxlmr** [comment]
Found out someone has encountered a similar issue https://github.com/grpc/grpc/issues/15889 in Python server, but the grpc-java client will recived `Unavailable` error code directly when server is unreachable unlike Python's client do.

**Comment by wwulfric** [comment]
@fangxlmr I didn't solve it. This problem is not repeatable after I upgrade netty version. Why grpc hanging still remains a mistery to me

**Comment by fangxlmr** [comment]
> @fangxlmr I didn't solve it. This problem is not repeatable after I upgrade netty version. Why grpc hanging still remains a mistery to me

Hi @wwulfric , thanks for replying. And BTW can you recall which netty version did you upgrade up to?
I'm currently using `io.grpc:grpc-netty-shaded:1.35.0`.

**Comment by wwulfric** [comment]
> Hi @wwulfric , thanks for replying. And BTW can you recall which netty version did you upgrade up to?
> I'm currently using `io.grpc:grpc-netty-shaded:1.35.0`.

@fangxlmr Grpc 1.26 introduces netty 4.1.42, which is conflicted with 4.1.38 introduced by my sources

**Comment by ejona86** [comment]
@fangxlmr, this issue was specifically about the NoSuchMethodError; if you don't see that then you suffering from a different problem. The problem experienced here should only occur when using `grpc-netty` with Netty getting downgraded or maybe mixing Netty versions between modules; it shouldn't happen with `grpc-netty-shaded`. The problem here _wasn't_ "the old netty had a bug."

**Comment by fangxlmr** [comment]
I see. Thanks
