### ISSUE TITLE
can't compile java_grpc_library

### ISSUE THREAD

**Issue by cristifalcas** [grpc/grpc-java#7695]
### What version of gRPC-Java are you using?\
1.34.0

### What is your environment?

Mac jdk 11

### What did you expect to see?
Define a `java_grpc_library` rule and use it

### What did you see instead?
When I define a `java_grpc_library` rule, I get this error with 1.33 and 1.34:

```
ERROR: /private/var/tmp/_bazel_cfalcas/856dc74a4318774eeb1496e4c7291b94/external/io_grpc_grpc_java/compiler/BUILD.bazel:18:13: no such package '@com_google_guava_guava//jar': The repository '@com_google_guava_guava' could not be resolved and referenced by '@io_grpc_grpc_java//compiler:java_grpc_library_deps__do_not_reference'
```

**Comment by ejona86** [comment]
You need to use `maven_install` in your WORKSPACE to load maven dependencies (or define them manually yourself). I suggest you take a look at [the example's WORKSPACE](https://github.com/grpc/grpc-java/blob/master/examples/WORKSPACE).

**Comment by cristifalcas** [comment]
thank you
