### ISSUE TITLE
Is there a better way to add multiple Services to GRPC-Server?

### ISSUE THREAD

**Issue by mithunnambiar** [grpc/grpc-java#7716]
Every time we add a new Service to the GRPC-Java Server we have to add another .addService(new MyServiceX). 
Something like this:
```
Server grpc-server = ServerBuilder.forPort(port)
                .addService(new Service1()).addService(new Service2()).addService(new Service3())...addService(new ServiceX()).
                .build()
                .start();
```

And we need to add a lot of services to our GRPC server.
Is there a better way to add all the services in one go?

**Comment by sanjaypujare** [comment]
Suggest a better API that you would like to see to add multiple services.

**Comment by voidzcy** [comment]
Users would by any means need to enumerate each of services when creating them. I don't think adding another API such as `addServices(List)` makes value. Users could probably refactor their own code to use it more elegantly. For example, they can instantiate the ServerBuilder on the very top, add one service each time creating it.

**Comment by ejona86** [comment]
@mithunnambiar, it is unclear if your issue is creating the services, or adding them to the builder.

If the services are in a list, then you can just call addService in a loop:

```java
ServerBuilder builder = ServerBuilder.forPort(port);
for (BindableService service : someList) {
    builder.addService(service);
}
Server server = builder.build().start();
```

That code is pretty clean, so I think I agree the current builder API is probably fine. But I wonder if the user wants more of a DI approach where the services are automatically discovered. I think there's gRPC integration available for both Spring Boot and Dagger.

**Comment by mithunnambiar** [comment]
Thanks Eric for this code. My issue is about creation of services, as we have around 20+ services planned.
And adding a .addService() every time would be to change the GRPC-server file, which we don't want every developer who adds a new service to do.

The below code does make sense:
for (BindableService service : someList) {
    builder.addService(service);
}

But should "someList" be an object of an Abstract Class from which all new Services need to be extended?

**Comment by mithunnambiar** [comment]
Ok..I think this would work for us:
        ArrayList<BindableService> allServices = new ArrayList<>();
        allServices .add(new Service1());
        ..
       allServices .add(new Service22());
        for (BindableService service : allServices ) {
            builder.addService(service);
        }

Thanks!

**Comment by ejona86** [comment]
Great! Closing since it seems this is resolved. If not, comment and we can reopen.
