### ISSUE TITLE
GRPC Stream Server message deliver slows donw if rate of dataproduced is  below 30 m/s 

### ISSUE THREAD

**Issue by Saurya1001** [grpc/grpc-java#7727]
In my usecase i use server side stream and used async stub when i produced data ie call onNext per 30m/s or slow the lag is increased to reach the data to client ?
What will be the reason for this

**Comment by ericgribkoff** [comment]
I'm not sure I understand the question fully: when you invoke `onNext` less frequently you see increased network lag? How are you determining that the slowdown is happening when the data is going from client->server and not just because you're calling onNext less frequently? Could you post some of the observed delays you're seeing?

**Comment by Saurya1001** [comment]
i am invoking onNext more frequently like 20 millisecound per invoke.I can see the lags my stats are below:
lessThan5ms ---55%  , between5And10ms --- 15% , morethan10ms ----30%
maxLatency:56 ms
  Below are my server code 
public void sayHelloStreaming(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
    		// TODO Auto-generated method stub
    		for(int i=0;i<2000;i++) {
    			HelloReply rpl=HelloReply.newBuilder().setMessage(""+System.currentTimeMillis()).build();
    			responseObserver.onNext(rpl);
    			try {
					Thread.sleep(20);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
    		}
    		responseObserver.onCompleted();
    	}

And at client side i do the subtraction of current time and find lag 
NOTE:Both programme i run on single machine

**Comment by ericgribkoff** [comment]
In general this type of simple loop, executed only 2k times, combined with `System.currentTimeMillis`, is not going to get anything close to accurate benchmarking information. I'm not an expert on benchmarking but I would view anything that includes calls to Thread.sleep like this as somewhat suspect as well. You can see how gRPC Java's internal benchmarks are constructed at https://github.com/grpc/grpc-java/tree/master/benchmarks and [this thread](https://github.com/grpc/grpc-java/issues/7381) gives a decent overview of the challenges of going even from a properly-constructed benchmark to actual conclusions about real performance.

What executor are you using for your server?

**Comment by ericgribkoff** [comment]
FWIW, I modified our RouteGuideServer example to add a 20 ms sleep in its `listFeatures` and did not observe any unexpected latency increase for messages received by the client. This isn't a particularly precise test, but it suggests that there is some other issue leading to the behavior you're observing, most likely outside of gRPC library itself - at least, we would need more detailed performance data to indicate some kind of problem within gRPC.

**Comment by ericgribkoff** [comment]
Going to mark this as closed for now. @Saurya1001 if there's anything else to discuss here please post on this issue and we can reopen.
