### ISSUE TITLE
Netty Version Combinations table update

### ISSUE THREAD

**Issue by smcvb** [grpc/grpc-java#7729]
I was wondering whether the _version combination_ table [here](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty) is still being updated. As it stands, I am maintaining a project which uses both `grpc-netty` and `netty-tcnative-boringssl-static`, which both have seen recent releases with versions above the last mentioned.

For clarity, the table currently shares the match between `1.32.x-` of `grpc-netty` to `2.0.31.Final` of `netty-tcnative-boringssl-static`, whereas the most recent release of `grpc-netty` is `1.34.1`.

Should I simply be patient and wait for upgrading, or has the table not been updated for some time?
Thanks in advance for any advice on this topic!

**Comment by ejona86** [comment]
The table is still being updated and is current. 1.32.x- is an "open" range which includes 1.34.1. Yes, gRPC has not upgraded to newer versions yet; there's some TLSv1.3 issues that cropped up which I have a fix ready to resolve, but we noticed some instability in a large test suite that we've not looked into yet (https://github.com/grpc/grpc-java/issues/7430).

**Comment by smcvb** [comment]
Gotcha, thanks @ejona86! Was in doubt about this as I would've assumed `grpc-netty` to state `1.3[2-x].x` I guess. But it's the `-` at the end which signals the steps further of course. Thanks for clarifying this!

**Comment by smcvb** [comment]
The problem/question has been addressed from my perspective. Hence I'll close this issue (for now).
