### ISSUE TITLE
avoid split big data frame by WeightedFairQueueByteDistributor.allocationQuantum

### ISSUE THREAD

**Issue by firebook** [grpc/grpc-java#7760]
### Is your feature request related to a problem?
When we send big data frame(100K) to server(concurrent stream in one connection), gRPC java client will split data frame to multiple data frames. In some case(reduce latency time), we don't want to split the data frame. After test, we found allocationQuantum of WeightedFairQueueByteDistributor will affect, but gRPC java client just set 16K to this parameter, and we can't change it through config.

### Describe the solution you'd like
We can change WeightedFairQueueByteDistributor allocationQuantum through config.

**Comment by sanjaypujare** [comment]
Basically asking for [this](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L152) hardcoding to be replaced by a configurable value:
```
dist.allocationQuantum(16 * 1024); // Make benchmarks fast again.
```

Do you want it settable from the `NettyChannelBuilder` or a common system property?

**Comment by ejona86** [comment]
Have you tried hard-coding a different value and benchmarking?

We've tested increasing the quantum size multiple times and didn't see performance benefits (latency nor throughput) and may it cause regressions. After we introduce the adaptive cumulator it should allow this type of optimization, but that cumulator was reverted in #7669. My expectation here is to auto-adjust the quantum size to a fixed latency based on the throughput of the connection, which we can easily extract from the BDP code. Similarly, we could increase the maximum frame size.

**Comment by ejona86** [comment]
@firebook, you've not shared any evidence to show this change will have a performance improvement. We have plans to increase it, but our own benchmarks show that increasing it currently has little or negative impact.

I'm going to close this. If you share evidence or reason to believe it will help, we can reopen.
