### ISSUE TITLE
MessageIOException occurs when building grcp-core:test

### ISSUE THREAD

**Issue by pinxiong** [grpc/grpc-java#7767]
An `MessageIOException` occurred when I download the source code of [grpc-java](git@github.com:grpc/grpc-java.git) to build it. More details are as follows:

- Operating System: Windows 10
- JDK: openjdk 1.8.0_265
- What I did:

  1. create  $project-root$/`gradle.properties` file
  2. add `skipAndroid=true` and `skipCodegen=true` in `gradle.properties` file
  3. using cmd to run `gradlew build`  
  4. I still couldn't find the solution after visited [stackoverflow](https://stackoverflow.com/) and [docs.gradle.org](https://docs.gradle.org/6.5.1/userguide/java_testing.html#sec:test_execution)

- Exception snapshot
![MessageIOException occurs when building grcp-core test](https://user-images.githubusercontent.com/7067417/103258641-e6d9f100-49d0-11eb-92f2-f4c93ac694e3.png)

**Could someone help me?**

**Comment by sanjaypujare** [comment]
This is indeed strange but seems unrelated to gRPC. I found a similar issue https://github.com/gradle/gradle/issues/7802 but no solution there. Couple of questions:

- is this happening consistently or only once a while?
- have you looked into the contents of hs_err_pid24416.log file? That might give you a clue?
- try upgrading Windows or try another machine.
- what does the Chinese text for IOException say?

**Comment by voidzcy** [comment]
It may be caused by https://github.com/gradle/gradle/issues/14094, do you have windows hotspot sharing turned on? https://github.com/gradle/gradle/issues/14094#issuecomment-700612298 says turning it off solves the problem.

**Comment by pinxiong** [comment]
> This is indeed strange but seems unrelated to gRPC. I found a similar issue [gradle/gradle#7802](https://github.com/gradle/gradle/issues/7802) but no solution there. Couple of questions:
> 
> * is this happening consistently or only once a while?
> * have you looked into the contents of hs_err_pid24416.log file? That might give you a clue?
> * try upgrading Windows or try another machine.
> * what does the Chinese text for IOException say?

Thanks for your reply!

This exception  happens every time, and this is my first time to download the source code and build it.

I have attached the file [hs_err_pid24416.log](https://github.com/grpc/grpc-java/files/5749758/hs_err_pid24416.log) , which I replace some sensitive information.

I think it's not a good idea to try upgrading Windows or try another machine.

"远程主机强迫关闭了一个现有的连接。" means that **an existing connection was forcibly closed by the remote host.**

Thanks for your help again!

**Comment by sanjaypujare** [comment]
Does the [comment](https://github.com/grpc/grpc-java/issues/7767#issuecomment-751959391) address your issue? If yes, then let us know so we can close the issue

**Comment by pinxiong** [comment]
> It may be caused by [gradle/gradle#14094](https://github.com/gradle/gradle/issues/14094), do you have windows hotspot sharing turned on? [gradle/gradle#14094 (comment)](https://github.com/gradle/gradle/issues/14094#issuecomment-700612298) says turning it off solves the problem.

Thanks for your help!

However, I use a desktop, so I don't have windows hotspot.

**Comment by pinxiong** [comment]
> Does the [comment](https://github.com/grpc/grpc-java/issues/7767#issuecomment-751959391) address your issue? If yes, then let us know so we can close the issue

Very sorry to tell you that it still doesn't work. What I've tried are as follows:

1. remove `.gradle` file and then try to rebuild
2. upgrade gradle's version to 6.7.1 and then try to rebuild
3. downgrade gradle's version to 5.6 and then try to rebuild

I'v no idea to solve this problem. Also, I cannot confirm that this problem is about `gradle`.

What I wanna do is build `grpc-java` to **obtain source codes of 'grpc' for Java language** and then **konw how `grpc` works, which I hope I can debug the source codes**.

Could you help me?

**Comment by sanjaypujare** [comment]
This is definitely not a problem with grpc-java so one thing you can do is to build without tests - add `-x test` to your gradle command line.

It does seem related to networking on your Windows computer. Once all artifacts have been downloaded in a previous build try disabling networking and see if your build *with* tests enabled works or not.

**Comment by pinxiong** [comment]
> This is definitely not a problem with grpc-java so one thing you can do is to build without tests - add `-x test` to your gradle command line.
> 
> It does seem related to networking on your Windows computer. Once all artifacts have been downloaded in a previous build try disabling networking and see if your build _with_ tests enabled works or not.

Thanks for your help!

This problem is really about `gradle`, because the new exception occurred when I do upgrade about `gradle` .

I've opened an bug to `gradle`. gradle/gradle#15665

It doesn't work that the method to ignore the _test cases_ for downloading all artifacts and then build try disabling networking.

Now, I'll close this issue before.

Thanks again!

**Comment by mayspb** [comment]
I faced the same problem on another project: error message was similar.
Problem was resolved by downgrading java version from 1.8.0_271 (Oracle Corporation 25.271-b09) to 1.8.0_251 (Oracle Corporation 25.251-b08).

**Comment by pinxiong** [comment]
> I faced the same problem on another project: error message was similar.
> Problem was resolved by downgrading java version from 1.8.0_271 (Oracle Corporation 25.271-b09) to 1.8.0_251 (Oracle Corporation 25.251-b08).

Thank you very much! I'll try.
