### ISSUE TITLE
Ask to access onMessage to parse message to get key json ( example try to get code code : 400, code 600)

### ISSUE THREAD

**Issue by dumihi** [grpc/grpc-java#7768]
My response likes 
evi.grpc.GetFollowingResponse@d0d1daea
    status {
      code: 601
      message: "Token expired"
    }
I want to get the code value, so I try to parse it from message, but it nothing can help me excepting i cast it to my model GetFollowingResponse. I have many getAPi with model response so it is not correct
  
override fun onMessage(message: RespT) {
                                message // need to get code value from message
                                )

**Comment by sanjaypujare** [comment]
Sorry I have not understood the problem. Can you explain with an example?

**Comment by dumihi** [comment]
My resonse when access token is expired has format
evi.grpc.GetFollowingResponse@d0d1daea
status {
code: 601
message: "Token expired"
}
This response will receive onMessage in message at interceptor
I could not find any way to get code 601 from message. If i catch message i will handle log out feature

**Comment by sanjaypujare** [comment]
If I understand correctly you want the gRPC [Status](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/Status.java#L56). `onMessage` only gets your payload messages (i.e. part of your RPC response proto). To receive status you will need to provide [`onClose`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ClientCall.java#L151) in your response-listener in your client-interceptor. Something like this:
```
        @Override
        public void start(Listener<RespT> responseListener, Metadata headers) {
          super.start(new ForwardingClientCallListener.SimpleForwardingClientCallListener<RespT>(responseListener) {

            @Override
            public void onClose(Status status, Metadata trailers) {
              // process status here
              super.onClose(status, trailers);
            }
          }, headers);
        }
```

**Comment by ejona86** [comment]
@dumihi, I'd just expect you to do `getFollowingResponse.getStatus().getCode()`

**Comment by dumihi** [comment]
@sanjaypujare In my case, backend send response in onMessage, onClose always return Status with success code = 0. I think this Status on onClose just show status of calling api process,  it does not show specific backend code
@ejona86 it is just not only FollowingResponse but also many types of response in project

**Comment by dumihi** [comment]
It seem RespT is a generic type so it is impossible to get code what i expect. With Retrofit we can get code of response easier than Grpc

**Comment by sanjaypujare** [comment]
Oh, okay, it seems my understanding was wrong and it looks like you want to access fields of your actual response as @ejona86 suggested.

`RespT` is a generic type and you will have to cast it to `GetFollowingResponse` in order to access its fields since type inference is not possible. Like this:

```
            @Override
            public void onMessage(RespT message) {
              GetFollowingResponse getFollowingResponse = (GetFollowingResponse)message;
              getFollowingResponse.getStatus().getCode()
              // ....processing
              super.onMessage(message);
            }
```

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

I'll make one note that if there's an error you should really close with a gRPC Status. If you need additional error information you can include that in the Metadata of the StatusRuntimeException, which corresponds to trailers Metadata for interceptors.
