### ISSUE TITLE
Unable to build grpc-java in v1.34.1

### ISSUE THREAD

**Issue by anksv** [grpc/grpc-java#7775]
### What version of gRPC-Java are you using?
v1.34.1

### What is your environment?

os.detected.name=windows
os.detected.arch=x86_64
os.detected.version=6.3
os.detected.version.major=6
os.detected.version.minor=3
os.detected.classifier=windows-x86_64

### What did you expect to see?
Unable to build in examples folder

### What did you see instead?
> Task :generateProto FAILED
:generateProto (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 4.324 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: --grpc_out: protoc-gen-grpc: Plugin failed with status code 3221225506.

### Steps to reproduce the bug

Steps:
1, git clone -b v1.34.1 https://github.com/grpc/grpc-java
2, cd grpc-java/examples
3. gradlew installDist

Seems like issue with url "https://maven-central.storage-download.googleapis.com/maven2/"

**Comment by anksv** [comment]
Seems like issue with url "https://maven-central.storage-download.googleapis.com/maven2/"

**Comment by anksv** [comment]
> Task :generateProto
Deleting stale output file: C:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\build\generated\source\proto\main
Downloading https://maven-central.storage-download.googleapis.com/maven2/io/grpc/protoc-gen-grpc-java/1.34.1/protoc-gen-grpc-java-1.34.1-windows-x86_64.exe to C:\Users\Ankur.Verma\AppData\Local\Temp\gradle_download5913740253260516136bin
Caching disabled for task ':generateProto' because:
  Build cache is disabled
Task ':generateProto' is not up-to-date because:
  Task has failed previously.
Resolved artifact: C:\Users\Ankur.Verma\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.12.0\cd96504a98ca07e0895c6ae525aaa7590e882dc3\protoc-3.12.0-windows-x86_64.exe
Resolved artifact: C:\Users\Ankur.Verma\.gradle\caches\modules-2\files-2.1\io.grpc\protoc-gen-grpc-java\1.34.1\d940003446363d84a5b2bc79ee7b282bc7eb7fb0\protoc-gen-grpc-java-1.34.1-windows-x86_64.exe
[C:\Users\Ankur.Verma\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.12.0\cd96504a98ca07e0895c6ae525aaa7590e882dc3\protoc-3.12.0-windows-x86_64.exe, -IC:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\src\main\proto, -IC:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\build\extracted-protos\main, -IC:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\build\extracted-include-protos\main, --java_out=C:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\build/generated/source/proto/main/java, --plugin=protoc-gen-grpc=C:\Users\Ankur.Verma\.gradle\caches\modules-2\files-2.1\io.grpc\protoc-gen-grpc-java\1.34.1\d940003446363d84a5b2bc79ee7b282bc7eb7fb0\protoc-gen-grpc-java-1.34.1-windows-x86_64.exe, --grpc_out=C:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\build/generated/source/proto/main/grpc, C:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\src\main\proto\hello_streaming.proto, C:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\src\main\proto\helloworld.proto, C:\Users\Ankur.Verma\MyGit\grpc\grpc-java\examples\src\main\proto\route_guide.proto]

**Comment by sanjaypujare** [comment]
What seems to be the problem with "https://maven-central.storage-download.googleapis.com/maven2/" ? If you are talking about 
```
Downloading https://maven-central.storage-download.googleapis.com/maven2/io/grpc/protoc-gen-grpc-java/1.34.1/protoc-gen-grpc-java-1.34.1-windows-x86_64.exe 
```

it works for me i.e. it downloaded for me

**Comment by anksv** [comment]
I think site was down for few moments , now its up
