### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected.

### ISSUE THREAD

**Issue by leonchen83** [grpc/grpc-java#7776]
### What version of gRPC-Java are you using?

`1.34.1`

### What is your environment?

Linux erebor-dev 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### What did you expect to see?
no leak
### What did you see instead?

```
21-01-04 15:48:24.393 ERROR[system.jetcd.executor-2 ResourceLeakDetector.reportTracedLeak:319]LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
  io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:385)
  io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
  io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
  io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
  io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
  io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
  io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:780)
  io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
  io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
  io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to reproduce the bug

not occur very often.

code
```
final NettyChannelBuilder builder = forTarget("etcd");
builder.eventLoopGroup(new NioEventLoopGroup(2, new DefaultThreadFactory("pool-name")));
builder.channelType(NioSocketChannel.class);
...
```

**Comment by sanjaypujare** [comment]
Thanks for reporting. Do you think it's related to using the `NioSocketChannel` channelType? What happens if you use the default (`EpollSocketChannel`)?

**Comment by voidzcy** [comment]
Why the stacktrace shows you are using epoll while the code snippet is using NIO? Can you try running with `-Dio.netty.leakDetection.level=PARANOID`?

**Comment by leonchen83** [comment]
@sanjaypujare 
we changed `NioSocketChannel` to `EpollSocketChannel`. for now it works fine. 
@voidzcy 
yes. it shows epoll but we use above code actually.

**Comment by voidzcy** [comment]
We are not able to dig into your codebase to see what's happening there. Please describe your use case and under what circumstances the leakage happens. If possible, a minimal reproducible example would be great. Also, try running with `-Dio.netty.leakDetection.level=PARANOID` when you are able to reproduce it. It should give the information for where the leaked buffer is used.
