### ISSUE TITLE
how to get the connect channel  on the server side

### ISSUE THREAD

**Issue by 1122wucheng** [grpc/grpc-java#779]
on the server side ,how to get the netty connect channel?I want to hold all the connected channels in my service. because
1: I want broadcast message to client
2: use username/password authentication by my server only once when the client connects for the first time.

**Comment by ejona86** [comment]
Today we don't support getting the channel on the server-side. There are some cases where we might begin exposing it (client side certificates, allowing users to close idle connections, etc), but the ones you present aren't really part of the intended use cases.

1. Even if you had the channel, you wouldn't be able to send a message to the client. All responses on the server need to go through a call that the client started. The best solution to this is that clients start a server-streaming or bidi-streaming RPC and that RPC is simply long-lasting. The server keeps a list of all such RPCs and when an event you want to broadcast occurs you loop through the list and send the message.

2. Performing authentication on the entire connection based on a request is fragile. Doing so properly would require direct support within gRPC and requires making assumptions about the network. There are not yet plans to support something like that, or the similar NTLM/SPNEGO. To implement this on top of gRPC, you would need to know when gRPC creates new connections on the client side as well, which is also not exposed. Instead, I'd suggest you provide username/password each RPC, but cache the authentication result on the server-side.

**Comment by xinqianli** [comment]
Thanks @ejona86 . I suppose, thru tcp connection based authentication, it may simplify the code implementation for some use cases, such that for massive users app, when server-side caches the authentication ticket per RPC, we have to consider how to design a cache system that might be in-process/off-heap/central.

**Comment by ejona86** [comment]
@xinqianli, I'd just assume you do in-process, since that is pretty similar to storing it per-connection.

**Comment by 1122wucheng** [comment]
thanks @ejona86 . I take your suggestion “provide username/password each RPC”. on the client-side. put username/password in metadata by Interceptor, on the server-side, authentication by "io.grpc.ServerInterceptor", if authentication failed, how it return the header only or forward another gRPC method?

**Comment by ejona86** [comment]
The server interceptor could:

```java
public <Req, Resp> ServerCall.Listener<Req> interceptCall(
    String method, ServerCall<Resp> call, Metadata.Headers headers,
    ServerCallHandler<Req, Resp> next) {
  boolean success = authenticateRequest(headers);
  if (success) {
    next.startCall(method, call, headers);
  } else {
    call.close(Status.UNAUTHENTICATED, new Metadata.Trailers());
  }
}
```

Note that if there was a failure, `next` is not called. That means if the client is not authenticated the interceptor would prevent your Service from receiving the RPC.

**Comment by 1122wucheng** [comment]
thanks @ejona86

**Comment by rsmilyanov** [comment]
Hello @ejona86 ,

I want to make a server side user authorization check with server interceptor.
On the example you mentioned above method interceptCall must return a `ServerCall.Listener<Req>` as per the java doc of the interface.

Currently I am calling `call.close(Status.UNAUTHENTICATED, headers)` and returning an empty `ServerCall.Listener<ReqT>`. Client side is being notified onError event and this seems to be fine now.
My question is what I am supposed to return in case the user is not authorized?  Is it fine to have an empty ServerCall.Listener being returned? 

Thanks in advance!

**Comment by ejona86** [comment]
@rsmilyanov, yes, it's fine to return a noop `ServerCall.Listener`. Since you called `close()` already, it's true you don't care much about the callbacks. Note that there may be _other_ interceptors that do care, so they will end up wrapping your listener in a new one that does something (so returning a noop listener isn't completely useless).

The interceptor is _not required_ to call `next`. If it doesn't call `next`, then the service won't be called.

**Comment by rsmilyanov** [comment]
@ejona86, thanks for your comment.
I will not have any other interceptors - it will be just one interceptor that checks whether the user is logged in or not.

**Comment by anhldbk** [comment]
@ejona86 : In bi-directional streaming, with `in-polite` unauthenticated clients, invoking `call.close` is not enough to close connections. How can I forcefully close them?

**Comment by ejona86** [comment]
@anhldbk, this issue has little to do with your question. But in short, you can't forcefully close a connection based on an RPC. You can only kill RPCs. I also don't know what you mean by `in-polite`.

**Comment by anhldbk** [comment]
@ejona86 Sorry for the unclear question above. When I use an interceptor to authenticate clients (in bi-directional streaming scenarios), if unauthenticated clients refuse to shutdown their channels, how can I forcefully close connections and reclaim opened file descriptors? 

Here's the code for the interceptor (assuming that I reject all gRPC calls)
```java
@Override
public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
    ServerCall<ReqT, RespT> call,
    final Metadata requestHeaders,
    ServerCallHandler<ReqT, RespT> next) {

	call.close(Status.CANCELLED, requestHeaders);
	return new ServerCall.Listener() {

	};

}
```

**Comment by ejona86** [comment]
@anhldbk, as I said, you can't. And I'd expect it'd be a bad idea from a load and proxy perspective. You can use the options like [maxConnectionAge](https://grpc.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#maxConnectionAge-long-java.util.concurrent.TimeUnit-) and [maxConnectionIdle](https://grpc.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#maxConnectionIdle-long-java.util.concurrent.TimeUnit-) (see [this](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md#proposal) for more details), but those apply to all clients.

**Comment by anhldbk** [comment]
@ejona86 I see. Thank you for your advice.
