### ISSUE TITLE
How to set connection timeout by OkHttpChannelBuilder?

### ISSUE THREAD

**Issue by andyliumstar** [grpc/grpc-java#7824]
How to set connection timeout by OkHttpChannelBuilder in a java client?

**Comment by voidzcy** [comment]
Can you describe your use case so we can get sense on what _timeout_ you really want?

_Connection timeout_ is a vague concept in gRPC, and it is intentionally made to be so. We do not control the timeout for the underlying socket to make a connection to the remote peer, we manage the timeout (auto-increase) between failures of establishing connections.

If you are really sure the socket connection timeout is the thing you want, you may [supply a SocketFactory](https://github.com/grpc/grpc-java/blob/2a62de0559a503286ddc6ccd95b45e0a1f8a100a/okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java#L239) to OkHttpChannelBuilder that creates socket with [`new Socket()`](https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#Socket()) + [`connect(timeout)`](https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#connect(java.net.SocketAddress,%20int)). But that probably won't solve your application's problem.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
