### ISSUE TITLE
How do you get the certchain when it is under 'resources'? 

### ISSUE THREAD

**Issue by camroe** [grpc/grpc-java#7844]
I am trying to get a 'secure' server running and am having some simple issues, totally due to me lack of understanding but still. :)   I can get a plain-text version of my grpc server running and I can get a 'secure' version running as well if I use a java configuration like this ...
```java
    if (secureServer) {
      // __----------START SECURE SERVER
      //Read files from resource directory application.properties
      //change "secure.host" in application.properties to the host in target environment: localhost, linux, or some other
      log.info("Secure Server on " + secureServer + ":" + securePort);
      String certFileName = "vbp-grpc/" + secureHost + "/server.crt";
      String pemFileName = "vbp-grpc/" + secureHost + "/server.pem";

      File certFile = getCertFile(PocApplication.class, certFileName);
      File pemFile = getCertFile(PocApplication.class, pemFileName);

      server = NettyServerBuilder.forPort(securePort)
        .addService(vehicleService)
        .addService(paymentService)
        .useTransportSecurity(certFile, pemFile)
        .permitKeepAliveWithoutCalls(true)
        .permitKeepAliveTime(5, TimeUnit.SECONDS)
        .build();
      //------------ END SECURE SERVER
```
But when trying to do it using configuration properties I keep getting the exception

org.springframework.context.ApplicationContextException: Failed to start bean 'shadedNettyGrpcServerLifecycle'; nested exception is java.lang.IllegalArgumentException: certificateChain path cannot be null or blank
<<<SNIP>>>
Caused by: java.lang.IllegalArgumentException: certificateChain path cannot be null or blank

I get the plaintext server running then change the following properties in application properties
```
#Secure or Plaintext?
grpc.server.security.enabled=true
#If secure is true then the following should be set as well.
grpc.server.security.certificateChain=file:/vbp-grpc/localhost/server.crt
grpc.server.security.privateKey=file:/vbp-grpc/localhost/server.key
#Should be equal to 46001 for PlainText or 50054 for Secure
grpc.server.port=50054
```
I have tried several combination of changing the 'file' and 'classpath' protocol and the '/' or not in front of the file name.
```grpc.server.security.certificateChain=file:/vbp-grpc/localhost/server.crt```
like
```
1. grpc.server.security.certificateChain=file:/vbp-grpc/localhost/server.crt
2. grpc.server.security.certificateChain=file:vbp-grpc/localhost/server.crt
3. grpc.server.security.certificateChain=classpath:/vbp-grpc/localhost/server.crt
4. grpc.server.security.certificateChain=classpath:vbp-grpc/localhost/server.crt
```
All of which fail.  What am I doing wrong?  My directory structure in my IntelliJ project is as follows.

 └── src
│       ├── main
│       │   ├── java
│       │   │   └──  ......... 
 └── resources
│       │       ├── application.properties
│       │       └── vbp-grpc
│       │           ├── localhost
│       │           │   ├── ca.key
│       │           │   ├── server.crt
│       │           │   ├── server.csr
│       │           │   ├── server.key
│       │           │   └── server.pem

**Comment by dapengzhang0** [comment]
Seems the `grpc.server.security.certificateChain` configuration property you are using is from [grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter) (We don't know about the detail). You might file the issue there instead. cc @ST-DDT

**Comment by camroe** [comment]
Right! Thanks - closing here and opening there. ;)
