### ISSUE TITLE
Encountering UNAVAILABLE: Network closed for unknown reason after making successful requests

### ISSUE THREAD

**Issue by Sovietaced** [grpc/grpc-java#7851]
### What version of gRPC-Java are you using?
1.24.1 (I can reproduce the issue with 1.35.0 though)

### What is your environment?
OpenJDK 11 running on AWS EKS 1.17 with Istio 1.6.5

### What did you expect to see?

Ideally I would like my outgoing requests to work 😄 . Realistically it would be helpful if the exception thrown by the gRPC layer was more actionable/debuggable. All I have to work with is `UNAVAILABLE: Network closed for unknown reason`.

### What did you see instead?

We have a service which runs and periodically makes requests to other services to ensure they are working correctly. When the service boots up it generates a bunch of gRPC channels and GRPC client wrapper objects. During the initial test run the gRPC requests work completely normally. After roughly 15 minutes the second run begins and we start to see issues on some of the gRPC channels which are using mTLS and going through an AWS NLB. 

With debug logging enabled I see every attempted request write OUTBOUND HEADERS followed by OUTBOUND DATA. Immediately afterwards the request throws an UNAVAILABLE gRPC status runtime exception with no additional cause. It seems that requests continue with the same `streamId` and exhibit the same failing behavior. 

We see the following exception which is not very helpful.
```
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at <redacted>APIBlockingStub.<redacted>
	at <redacted>
	at <redacted>
	at <redacted>
	at io.kotlintest.runner.jvm.TestCaseExecutor$executeTest$supervisorJob$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(TestCaseExecutor.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

After enabling DEBUG level logging I discovered that I only see outgoing outbound traffic and the code almost immediately throws an exception. 

> {"@timestamp":"2021-01-28T05:31:19.534Z","log.level":"DEBUG","log.logger":"io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler","message":"[id: 0x90347537, L:/<redacted> - R:<redacted>] INBOUND DATA: streamId=9 padding=0 endStream=false length=6450 bytes=<redacted>","process.thread.name":"grpc-default-worker-ELG-1-13"}

10 minutes later the second run starts after successfully receiving data...

> {"@timestamp":"2021-01-28T05:42:55.774Z","log.level":"DEBUG","log.logger":"io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler","message":"[id: 0x418af442, L:/<redacted> - R:<redacted>] OUTBOUND HEADERS: streamId=9 headers=GrpcHttp2OutboundHeaders[:authority: <redacted>, :path: <redacted>, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.24.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false","process.thread.name":"grpc-default-worker-ELG-1-11"}
> {"@timestamp":"2021-01-28T05:42:55.774Z","log.level":"DEBUG","log.logger":"io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler","message":"[id: 0x418af442, L:/<redacted> - R:<redacted>] OUTBOUND DATA: streamId=9 padding=0 endStream=true length=8 bytes=<redacted>","process.thread.name":"grpc-default-worker-ELG-1-11"}

Outgoing data continues to be sent for other requests and exceptions continue for each respective request
> {"@timestamp":"2021-01-28T05:42:55.817Z","log.level":"DEBUG","log.logger":"io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler","message":"[id: 0x1c72dc4b, L:/<redacted> - R:<redacted>] OUTBOUND HEADERS: streamId=9 headers=GrpcHttp2OutboundHeaders[:authority: <redacted>, :path: <redacted>, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.24.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false","process.thread.name":"grpc-default-worker-ELG-1-12"}

### Steps to reproduce the bug

It is not immediately obvious how to reproduce the bug. The issue started happening to us recently.

From my observations the issue only occurs with mTLS connections and they must be idle or alive for a certain amount of time before they start exhibiting issues. We have non mTLS, TLS connections where this issue does not occur at all. I simply find it very frustrating to debug this issue given the exception is thrown from `grpc-java`. 

Thank you for your time!

**Comment by sanjaypujare** [comment]
> After roughly 15 minutes the second run begins and we start to see issues on some of the gRPC channels which are using mTLS and going through an AWS NLB.

Do you mean only the second run requests (after 15 minutes) go thru the NLB and not the first run requests? In that case may be the issue is with the NLB?  AWS NLS supports TLS termination but not mTLS so you must be using NLB in pass-through mode where mTLS terminates at the actual backend. Can you generate debug logs at the backend to see if they generate any errors?

**Comment by Sovietaced** [comment]
> Do you mean only the second run requests (after 15 minutes) go thru the NLB and not the first run requests? In that case may be the issue is with the NLB? AWS NLS supports TLS termination but not mTLS so you must be using NLB in pass-through mode where mTLS terminates at the actual backend. Can you generate debug logs at the backend to see if they generate any errors?

The first run of requests and the second run of requests both go through the AWS NLB. Our AWS NLB is not terminating TLS, it is doing TLS pass through and our TLS is actually terminated at an Istio secure gateway. 

I will have to do some more investigation to see if the request is even making it past the client's istio proxy. I have verified that the requests certainly don't make it to the server's istio-proxy since there are no access logs of the request (we have access logs turned on cluster wide). 

While I'm here I will update this issue with some additional findings. This issue seems to be completely related to timing. If our interval between runs is set to 1 hour (as it has historically been set) we do not see any issues. If the interval between runs is set to 5 minutes we can easily reproduce the issue. I have not tinkered enough to discover what the breaking point is but I think this is still a helpful data point.

I'll have to do some more digging.

**Comment by sanjaypujare** [comment]
> The first run of requests and the second run of requests both go through the AWS NLB. Our AWS NLB is not terminating TLS, it is doing TLS pass through and our TLS is actually terminated at an Istio secure gateway.
> 
> I will have to do some more investigation to see if the request is even making it past the client's istio proxy. I have verified that the requests certainly don't make it to the server's istio-proxy since there are no access logs of the request (we have access logs turned on cluster wide).

In that case mTLS originates at the client's istio proxy and *not* at the gRPC client application, right? AFAIK that's the most common configuration since client app to client proxy needs to be plaintext for various reasons. If the request arrives at the client proxy but does not go beyond then this issue has nothing to do with the gRPC Java library unless I am missing something. Based on what's happening at the client proxy you may need to file this with istio/envoy.

> 
> While I'm here I will update this issue with some additional findings. This issue seems to be completely related to timing. If our interval between runs is set to 1 hour (as it has historically been set) we do not see any issues. If the interval between runs is set to 5 minutes we can easily reproduce the issue. I have not tinkered enough to discover what the breaking point is but I think this is still a helpful data point.

This is interesting as I can't think of anything that can be caused by 5 min vs 1 hour interval in gRPC but is quite possible with the istio proxy.

**Comment by Sovietaced** [comment]
> In that case mTLS originates at the client's istio proxy and _not_ at the gRPC client application, right? AFAIK that's the most common configuration since client app to client proxy needs to be plaintext for various reasons. If the request arrives at the client proxy but does not go beyond then this issue has nothing to do with the gRPC Java library unless I am missing something. Based on what's happening at the client proxy you may need to file this with istio/envoy.

In our case the gRPC client application uses mTLS. mTLS at the istio proxy layer depends on destination of the traffic. To be clear, this is a service which is effectively running smoke tests. It sits inside the service mesh but exercises APIs via publicly accessible IP addresses. So when the traffic hits the client proxy its sent as cluster passthrough. It then arrives back at the ingress gateway where mTLS is terminated and then istio mTLS is used between the istio ingress gateway and the destination service. 

Here is a simplified diagram of it leaving/entering the service mesh. 
(app -> client proxy -> egress gateway) -> (ingress gateway -> server) 

The reason I have filed an issue with the gRPC library is for a few reasons. 
1. Its not clear that the client proxy is even showing any outgoing requests. 
2. The exception message is not actionable (this seems like a bug). 

> This is interesting as I can't think of anything that can be caused by 5 min vs 1 hour interval in gRPC but is quite possible with the istio proxy.

From my experience, the istio proxy should not be doing anything to the TCP connections unless it receives a configuration update from Istio that requires some hitful behavior to process. This used to be more frequent with older versions of Istio but this type of needless TCP connection closing was fixed long before the version of Istio that we're using.

**Comment by sanjaypujare** [comment]
> ...
> Here is a simplified diagram of it leaving/entering the service mesh.
> (app -> client proxy -> egress gateway) -> (ingress gateway -> server)

Thanks for the illustration. I think sending mTLS traffic via istio proxies in TCP pass-thru mode is kind of dicey.

> 
> The reason I have filed an issue with the gRPC library is for a few reasons.
> 
> 1. Its not clear that the client proxy is even showing any outgoing requests.

Have you ruled out the client-proxy closing the inbound TCP connection? May be it is enforcing some timeout config for idle connections? 

> 2. The exception message is not actionable (this seems like a bug).

The error message was `Network closed for unknown reason` and this happens when the channel goes inactive (presumably closed by the peer). There might be scope for improving the wording to indicate "peer closed the connection" (if that was the case) but I think it's quite actionable and it strongly points to the client-proxy closing the connection.

> 
> > This is interesting as I can't think of anything that can be caused by 5 min vs 1 hour interval in gRPC but is quite possible with the istio proxy.
> 
> From my experience, the istio proxy should not be doing anything to the TCP connections unless it receives a configuration update from Istio that requires some hitful behavior to process. This used to be more frequent with older versions of Istio but this type of needless TCP connection closing was fixed long before the version of Istio that we're using.

This strongly points towards the client proxy closing the connection (even if it's a new version it's possible some config is doing that). Can you rule that out by using debug logs?

**Comment by Sovietaced** [comment]
> Have you ruled out the client-proxy closing the inbound TCP connection? May be it is enforcing some timeout config for idle connections?

No, I'll have to spend some time enabling logs there and further debugging it. However, if the client-proxy is closing the inbound TCP connection then gRPC shouldn't continue sending messages for new RPCs down this blackhole right? I would think it should establish a new TCP connection once it encounters this issue.

**Comment by sanjaypujare** [comment]
> No, I'll have to spend some time enabling logs there and further debugging it.

Wireshark or tcpdump could be useful: you just need to run it on the client app side and get the tcp dump to see who closed the connection. Also can you move to the latest version (1.35.0) of gRPC Java so the stack traces have the latest line numbers?

> However, if the client-proxy is closing the inbound TCP connection then gRPC shouldn't continue sending messages for new RPCs down this blackhole right? I would think it should establish a new TCP connection once it encounters this issue.

Yes, gRPC should be doing that. However I don't see gRPC attempting to send new RPCs on closed connections from your logs. Is it possible a bunch of connections closed around the same time?

**Comment by Sovietaced** [comment]
> Yes, gRPC should be doing that. However I don't see gRPC attempting to send new RPCs on closed connections from your logs. Is it possible a bunch of connections closed around the same time?

The last log in the OP is a request for a different RPC on the same stream ID that occurs roughly 40ms after the previous traffic was blackholed. I'll have to see if I can reproduce logs with a larger time delta.

**Comment by sanjaypujare** [comment]
Okay I see the same "streamId=9" being used in the last OUTBOUND HEADERS log message (apparently after the connection was closed).  And I can't explain that - @ejona86 any clues?

**Comment by ejona86** [comment]
I think that other streamId=9 has to be on a different connection.

> During the initial test run the gRPC requests work completely normally. After roughly 15 minutes the second run begins and we start to see issues on some of the gRPC channels which are using mTLS and going through an AWS NLB.

I expect the "network" (maybe k8s in this case) is killing this idle connection. 15 minutes of inactivity can cause that. I'm a bit surprised the error message didn't say "connection reset by peer", but it is really annoying to test this case so the error flow may be a bit less than ideal. But in any case, the client really doesn't know why the connection closed.

There's two choices: enable keepalive or set a lower idle timeout. The difference is [discussed briefly on StackOverflow](https://stackoverflow.com/a/57930958/4690866). For keepalive, see [gRFC A8 client-side keepalive](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md) for some details, but it would involve setting something like [`managedChannelBuilder.keepAliveTime(5, MINUTES)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#keepAliveTime-long-java.util.concurrent.TimeUnit-). Keepalive causes activity on the connection to let the network know the TCP connection should be kept alive. Idle timeout shuts down unused channels when they aren't being used. It can be configured with [`managedChannelBuilder.idleTimeout(5, MINUTES)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#idleTimeout-long-java.util.concurrent.TimeUnit-). For both options, the precise time (5 minutes here) would need to be discovered for your specific environment. It may be documented. Since you're in a datacenter and the time between calls is 15 minutes and the RPC is not latency-sensitive, I can't provide a blanket statement as to which option is more appropriate.

**Comment by sanjaypujare** [comment]
> I think that other streamId=9 has to be on a different connection.

Yes, if it's a different RPC it can't be the same streamId on the same connection. We should also include some kind of ID for the TCP connection.

**Comment by ejona86** [comment]
> We should also include some kind of ID for the TCP connection.

We do. "id: 0x1c72dc4b" vs "id: 0x418af442". It looks a bit weird in this JSON format; with other formatters it is more obvious.

**Comment by sanjaypujare** [comment]
> > We should also include some kind of ID for the TCP connection.
> 
> We do. "id: 0x1c72dc4b" vs "id: 0x418af442". It looks a bit weird in this JSON format; with other formatters it is more obvious.

Oh, I saw the key `"message"` preceding that as in `"message":"[id: 0x1c72dc4b, L:/ - R:]` so I thought it is some kind of a message identifier but then followed the ending double-quote to realize what's going on.

**Comment by Sovietaced** [comment]
> I expect the "network" (maybe k8s in this case) is killing this idle connection. 15 minutes of inactivity can cause that. I'm a bit surprised the error message didn't say "connection reset by peer", but it is really annoying to test this case so the error flow may be a bit less than ideal. But in any case, the client really doesn't know why the connection closed.
> 
> There's two choices: enable keepalive or set a lower idle timeout. The difference is [discussed briefly on StackOverflow](https://stackoverflow.com/a/57930958/4690866). For keepalive, see [gRFC A8 client-side keepalive](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md) for some details, but it would involve setting something like [`managedChannelBuilder.keepAliveTime(5, MINUTES)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#keepAliveTime-long-java.util.concurrent.TimeUnit-). Keepalive causes activity on the connection to let the network know the TCP connection should be kept alive. Idle timeout shuts down unused channels when they aren't being used. It can be configured with [`managedChannelBuilder.idleTimeout(5, MINUTES)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#idleTimeout-long-java.util.concurrent.TimeUnit-). For both options, the precise time (5 minutes here) would need to be discovered for your specific environment. It may be documented. Since you're in a datacenter and the time between calls is 15 minutes and the RPC is not latency-sensitive, I can't provide a blanket statement as to which option is more appropriate.

I think I have figured out what is going on after debugging a similar issue where other teams were instead encountering IO exceptions (connection reset by peer). For some reason, other teams were getting clearer exception messages than our team was 🤷. 

I think the reason why I was encountering this issue comes down to making requests to an AWS NLB. An AWS NLB has an immutable idle timeout of 350 seconds. After this point, an AWS NLB will send a TCP RST to old connections that make new requests. 

The reason why we didn't see this issue when our tests ran every hour is because of the `idleTimeout` configuration on the `ManagedChannelBuilder`. I have not confirmed, but I suspect that after 350 seconds of inactivity the AWS NLB would toss our connection. Then after 30 minutes of inactivity our clients would simply close the idle connections on the client side. So when tests would run every 60 minutes or so the clients would always be using fresh connections. When tests would run every 10 minutes or so (between 350 seconds and 30 minutes) we would see an issue. 

I have experimented locally with using client side and server side keepAlive and idle timeout configurations and those work quite well. Unfortunately our production environment involves the AWS NLB and Istio/Envoy proxies. After some testing it appears that the Istio/Envoy proxy will not forward the keep alive pings (which is reasonable). It is also not completely clear if the GO AWAY messages are getting forwarded correctly because I have only seen failures on those messages. 

So I'll need to continue looking into ways to enforce idle timeouts both at the application level and at the proxy level to ensure clients have a good user experience. There doesn't seem to be much information on this subject so I might poke the Istio/Envoy folks. Thanks all.

**Comment by ejona86** [comment]
> After some testing it appears that the Istio/Envoy proxy will not forward the keep alive pings (which is reasonable). It is also not completely clear if the GO AWAY messages are getting forwarded correctly because I have only seen failures on those messages.

L7 ("HTTP") proxies do no propagate GOAWAYs and PINGs, as those are point-to-point not end-to-end. There's typically no 1:1 relationship between the inbound and outbound connections in L7 proxies. The "server" in this picture is the Envoy, not your actual backend.
