### ISSUE TITLE
how to use bazel to build protoc-gen-grpc-java

### ISSUE THREAD

**Issue by shouhuanxiaoji** [grpc/grpc-java#7855]
Question: I want to build protoc-gen-grpc-java with bazel
Operating System: Debian buster
ARCH: mips64el
Description: When I type bazel build ... in compiler directory,it said 
ERROR: error loading package '': Extension file not found. Unable to load file '@bazel_tools//tools/build_defs/repo:jvm.bzl': file doesn't exist or isn't a file.

**Comment by ejona86** [comment]
What version of grpc-java are you trying to build, and what version of Bazel?

repositories.bzl contained an unused-for-a-while reference to jvm.bzl that was removed in https://github.com/grpc/grpc-java/commit/c329aad2bc972c109540d473a94083669e660b8f (v1.34.0).

**Comment by shouhuanxiaoji** [comment]
bazel 0.50 and grpc-java github master.
should I need a newer version of bazel?

**Comment by sanjaypujare** [comment]
With the latest grpc (post 1.34.0) you shouldn't have this issue since  jvm.bzl ref was removed as mentioned by @ejona86

**Comment by shouhuanxiaoji** [comment]
I will try, thanks

**Comment by ejona86** [comment]
I think you'll find you need to use at least Bazel 1.0.1. Anything after that should be fine; I tried Bazel 4.0 earlier today without trouble. I think 1.0.1 is necessary for parts of java_grpc_library.bzl.

**Comment by ejona86** [comment]
There doesn't appear to be more we can do on our end. I'm confident that things will start working with our suggestions. If not and there's still issues, comment, and this can be reopened.
