### ISSUE TITLE
package 'com.google.protobuf...' does not exist

### ISSUE THREAD

**Issue by josipMar** [grpc/grpc-java#7866]
I'm trying to implement gRPC to my project and when I do everythig as you did in your Hello World example, I keep getting 'package com.google.protobuf. ...' does not exist and 'can not find symbol ...'

I added this line to my project gradle:
    classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.14"

And to my app gradle I added:
    apply plugin: 'com.google.protobuf'

And in dependencies:
    implementation 'io.grpc:grpc-okhttp:1.35.0' // CURRENT_GRPC_VERSION
    implementation 'io.grpc:grpc-protobuf-lite:1.35.0' // CURRENT_GRPC_VERSION
    implementation 'io.grpc:grpc-stub:1.35.0' // CURRENT_GRPC_VERSION
    implementation 'org.apache.tomcat:annotations-api:6.0.53'
    implementation 'com.google.protobuf:protobuf-javalite:3.12.1'

And this one as well:

protobuf {
    protoc { artifact = 'com.google.protobuf:protoc:3.12.1' }
    plugins {
        grpc { artifact = 'io.grpc:protoc-gen-grpc-java:1.35.0' // CURRENT_GRPC_VERSION
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java { option 'lite' }
            }
            task.plugins {
                grpc { // Options added to --grpc_out
                    option 'lite' }
            }
        }
    }
}

Can someone tell me if I did something wrong or the issue is on your side?

**Comment by sanjaypujare** [comment]
The [README](https://github.com/grpc/grpc-java/blob/master/README.md) was recently updated to clarify a few things for Android vs non-Android builds. Pls check that for your environment - is it Android?

**Comment by josipMar** [comment]
Yep, it's Android... I'll go over the README again then. Thanks

**Comment by josipMar** [comment]
Hi @sanjaypujare  I still have the same issue... this is what I followed:

For Android client, use grpc-okhttp instead of grpc-netty-shaded and grpc-protobuf-lite instead of grpc-protobuf:

implementation 'io.grpc:grpc-okhttp:1.35.0'
implementation 'io.grpc:grpc-protobuf-lite:1.35.0'
implementation 'io.grpc:grpc-stub:1.35.0'
compileOnly 'org.apache.tomcat:annotations-api:6.0.53' // necessary for Java 9+


For Android protobuf-based codegen integrated with the Gradle build system, also use protobuf-gradle-plugin but specify the 'lite' options:

plugins {
    id 'com.google.protobuf' version '0.8.14'
}

protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:3.12.0"
  }
  plugins {
    grpc {
      artifact = 'io.grpc:protoc-gen-grpc-java:1.35.0'
    }
  }
  generateProtoTasks {
    all().each { task ->
      task.builtins {
        java { option 'lite' }
      }
      task.plugins {
        grpc { option 'lite' }
      }
    }
  }
}


I have everything the same as described here and my project simply can not resolve the 'com.google.protobuf' package

**Comment by sanjaypujare** [comment]
It will be good if you can paste the whole output. Also retry a clean build.

**Comment by josipMar** [comment]
Hi @sanjaypujare  I created a brand new project and set everything inside the gradle as it is set in your hello world project:
https://github.com/grpc/grpc-java/blob/6db928a791827f7754a9cd24d96eaf7d33975224/examples/android/helloworld/app/build.gradle#L36-L42

Now I created a proto file which looks like this:

_`syntax = "proto3";
option java_package = "com.testproject.proto";
option java_outer_classname = "RadioInfo";
import "google/protobuf/timestamp.proto";

service RadioInfo {
    rpc GetInfo (RadioInfoRequest) returns (stream RadioInfoResponse) {}
}
message RadioInfoRequest {
    string client_name= 1;
}
message RadioInfoResponse {
    string name = 1;
    string unit = 2;
    uint64 min_value = 3;
    uint64 max_value = 4;
    oneof value {
        bool bool_value = 5;
        google.protobuf.Timestamp timestamp_value = 6;
    }
}`_


I added protoc.exe (version 3.12.1) inside my project and when I try to generate the proto file using following command:

    _`protoc.exe proto/radio_info.proto --java_out=src/main/java/`_

I get this as an output:

    _`C:\Users\myuser\StudioProjects\MyApplication\app>protoc.exe proto/radio_info.proto --java_out=src/main/java/
google/protobuf/timestamp.proto: File not found.
proto/radio_info.proto:4:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
proto/radio_info.proto:19:9: "google.protobuf.Timestamp" is not defined.`_

**Comment by sanjaypujare** [comment]
Couple of things:
- did it download `protobuf-javalite-3.12.1.jar` based on your dependency list?
-  do you see `google/protobuf/timestamp.proto` in your directory tree?

**Comment by josipMar** [comment]
Yes, jar file is downloaded, I can see it under External libraries..
Not sure what you mean by directory tree... Should it be auto generated somewhere inside my project or under library directory? When I click to open Timestamp, it opens a timestamp.proto file which is located inside the **protobuf-javalite-3.12.0-sources.jar**, under google/protobuf/   destination.

Seems like it's recognizeable, but when I try to generate the proto file, it's saying: Import "google/protobuf/timestamp.proto" was not found or had errors.

Can this 2nd option be the case? that it actually WAS found but it had errors? Not sure what I should look for...

**Comment by sanjaypujare** [comment]
I don't think the 2nd one ("...or had errors") is the case. The file was not found. Not sure why but will get back to you later.

**Comment by voidzcy** [comment]
> `_protoc.exe proto/radio_info.proto --java_out=src/main/java/_`

This protoc invocation is wrong. It needs included protos (i.e, the `-I` flag) and also has things to do with the paths of source protos with included protos. You should not try to invoke protoc on you own, just run Gradle build, the protobuf-gradle-plugin has automated things for you.

**Comment by josipMar** [comment]
Ok, if I understood right, protoc invocation is wrong, I should simply run the Gradle build and class should be generated?
If so, this is currently not working, let me just show you what I have set up..

In my .proto file I have this:

`syntax = "proto3";
option java_package = "com.example.myapplication";
option java_outer_classname = "RadioInfo";
import "google/protobuf/timestamp.proto";`


And inside my app gradle:

protobuf {
    protoc { artifact = 'com.google.protobuf:protoc:3.12.0' }
    plugins {
        grpc { artifact = 'io.grpc:protoc-gen-grpc-java:1.35.0' // CURRENT_GRPC_VERSION
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java { option 'lite' }
            }
            task.plugins {
                grpc { // Options added to --grpc_out
                    option 'lite' }
            }
        }
    }
}


Based on:
option java_package = "com.example.myapplication";
option java_outer_classname = "RadioInfo";

Should this RadioInfo class be generated in the destination specified by java_package?

**Comment by voidzcy** [comment]
Please format your code snippet.

> I should simply run the Gradle build and class should be generated?

Yes.
Did you get any error? By default the generated code should be in `$buildDir/generated/source/proto`. You can find more information for how code is generated by protobuf0-gradle-plugin in its [README](https://github.com/google/protobuf-gradle-plugin).

**Comment by voidzcy** [comment]
Closing. If you are still encountering problems while using Gradle to automate your build, it can be reopened.
