### ISSUE TITLE
option java_multiple_files doesn't generate multiple files.

### ISSUE THREAD

**Issue by Mcfloy** [grpc/grpc-java#7873]
### What version of gRPC-Java are you using?
Using the snippet code from the README.md file for maven.
* grpc-netty-shaded | grpc-protobuf | grpc-stub : `1.35.0`
* annotations-api : `6.0.53`
* os-maven-plugin: `1.6.2`
* protobuf-maven-plugin: `0.6.1`
* com.google.protobuf: `3.12.0`
* io.grpc: `1.35.0`

### What is your environment?

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\apache-maven-3.6.3\bin\..
Java version: 13.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\jdk-13.0.2
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

### What did you expect to see?
After using the command `mvn clean compile`,
I should expect to see several java files generated as my .proto file does have `option java_multiple_files = true;` in it.

### What did you see instead?
After using the command `mvn clean compile`,
I end up with a single java file containing several subclasses.

### Steps to reproduce the bug
* Generate a new maven project
* Create a .proto file (in my case in the folder `src/main/proto`) containing multiple things. I did used the following example:
```proto
syntax = "proto3";
option java_multiple_files = true;
package com.mcfloy.grpc.hello;

message HelloRequest {
  string firstName = 1;
  string lastName = 2;
}

message HelloResponse {
  string greeting = 1;
}

service HelloService {
  rpc hello(HelloRequest) returns (HelloResponse);
}
```
* Type the command `mvn compile` or `mvn clean compile`
* Inspect the `target/generated-sources/protobuf/grpc-java` folder, you should have your package name and only one java class like this.
![image](https://user-images.githubusercontent.com/10086193/107116718-83679c80-6875-11eb-95df-1ef5817fc67b.png)

It's worth noting that we can still use the generated files for extending the services, but I would rather use separate java files if I can.

The grpc.io website doesn't mention this option in the documentation and I can't find it with some research. Is it an experimental feature ?
The original website I used as a guideline: https://www.baeldung.com/grpc-introduction
Beside the outdated pom.xml that doesn't contain a fix for java 8+ annotations (you can use the pom.xml from the README.md that is correct), the rest of the tutorial is nearly accurate if we don't mind using `HelloServiceGrpc.HelloServiceImplBase` instead of `HelloServiceImplBase` in our code.
The fact that the tutorial use `HelloServiceImplBase` without the single class seems to indicate this is a regression bug.

**Comment by sanjaypujare** [comment]
Can you also specify 
```
option java_package = "com.mcfloy.grpc.hello";
```

in your proto file?

**Comment by Mcfloy** [comment]
I specified the option mentioned in my proto file and it doesn't seem to change the behavior.

Actually I didn't checked the `target/generated-sources/protobuf/java` folder that contains the `HelloRequest` and `HelloResponse` in separate files, so my bad for that having found that before creating this issue.

I'm still wondering if `HelloServiceImplBase` should be in a separate file or not, is this related to a paradigm the team choose ?

As I might have not understood correctly the way this option work, I'll close this ticket but can you include a description of the option mentioning it does not include the services in the .proto files please ?

**Comment by sanjaypujare** [comment]
I cannot say anything about the tutorial you cited (https://www.baeldung.com/grpc-introduction) but it looks like the service stub (`HelloServiceImplBase`) is always generated in the "outermost Java class" regardless of the "java_multiple_files" option. This is handled by the `protoc-gen-grpc-java` plugin and I can cite the following links:

https://grpc.io/docs/languages/java/generated-code/ (there is no mention of the "java_multiple_files" option)
https://stackoverflow.com/questions/38488073/protocal-buffers-arent-generating-service-stubs
