### ISSUE TITLE
Add Channel Interface

### ISSUE THREAD

**Issue by joaoeudes7** [grpc/grpc-java#7889]
Is there an interface for a Channel?

### Is your feature request related to a problem?
I'm always frustrated when need implement multiples channels in a project, and don't have how create a instance in DI of Channel

### Describe the solution you'd like
Create a interface to Channel and add reference in ManagedChannel

**Comment by voidzcy** [comment]
> Create a interface to Channel and add reference in ManagedChannel

Can you describe more about what you are looking for? Some code snippet would be helpful.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
