### ISSUE TITLE
PooledByteBufAllocator has type mismatch due to updated dependency

### ISSUE THREAD

**Issue by edtbl76** [grpc/grpc-java#7901]
### What version of gRPC-Java are you using?
1.35.0

### What is your environment?

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7

### What did you expect to see?
Can't start netty server. 

### What did you see instead?
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:140)

### Steps to reproduce the bug
```
LIne 140 -> return ByteBufAllocatorPreferDirectHolder.allocator
points to Line 92 and 93 ->
private static final class ByteBufAllocatorPreferDirectHolder {
    private static final ByteBufAllocator allocator = createByteBufAllocator(true);
  }
createByteBufAllocator() rusns from 148 - 173. 

on 172, there is a call that fails to compile: 
PooledByteBufAllocator.defaultUseCacheForAllThreads());
```

This points to io.netty.buffer#PooledByteBufAllocator
It looks like this used to be an int, but they've changed it to a boolean. In the short term you can probably backrev your 
dependency.

**Comment by edtbl76** [comment]
I'm getting around this w/ some gradle-fu:
configurations.all {
    resolutionStrategy.eachDependency {
        if (it.requested.group == "io.netty") {
            it.useVersion "${nettyVersion}"
        }
    }
}

However, the problem is that grpc-netty seems to pull in every netty-* module individually regardless of whether or not it is used. It might be useful to clean up some of the dependencies or if the entire project is needed, use io.netty:netty-all to create simpler dependency management for transitive dependency overrides.

**Comment by voidzcy** [comment]
Looks you have versions misalignment for netty dependencies in your project. You have to use the same version for all netty dependencies.

**Comment by njhill** [comment]
@edtbl76 just use the netty BOM: https://docs.gradle.org/current/userguide/dependency_management.html#sec:align_bom_platform

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by edtbl76** [comment]
Sorry for the delay. I was using the bom. All of the netty versions were the same.

**Comment by ejona86** [comment]
@edtbl76, you were using the bom _before_ the [`eachDependency` workaround](https://github.com/grpc/grpc-java/issues/7901#issuecomment-780201419)?

BOMs make it easy to _upgrade_ a set of dependencies, and they are convenient to avoid specifying versions in your code. But they aren't great for _forcing_ a version in Gradle. I mention my findings at https://github.com/grpc/grpc-java/issues/7583 . Specifically, you'd have to use `enforcedPlatform()` but that will silently _downgrade_ packages without a way to turn that into a failure (that I saw). What I'd hope is a way to say "use these versions, and fail if they aren't the newest." That way you'd know when it is necessary to upgrade the BOM.

**Comment by edtbl76** [comment]
I was. I think that I came to the same conclusion. (I claim some ignorance in terms of Gradle, so I probably could have overlooked something). I just scanned your findings, and I'd like to give that a shot. I'll report back. I'm going to close this, because this is for a side project (I don't want it to tie up your queue due to my inactivity)

**Comment by GrapeBaBa** [comment]
Also meet this issue
