### ISSUE TITLE
io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport.connections - Transport failed

### ISSUE THREAD

**Issue by sunjiongjiong** [grpc/grpc-java#7940]
1、Go call grpc of Java

2、Go version: google.golang.org/grpc v1.36.0

3、grpc-java version: net.devh     grpc-server-spring-boot-starter     2.4.0.RELEASE

4、Complete the call and report an error: An existing connection was forcibly closed by the remote host
![9e8cd9fb1fdbe1fc2e284946d9133e7](https://user-images.githubusercontent.com/21102071/110056106-29d18f80-7d99-11eb-83e1-a8e515a07d09.png)

**Comment by sanjaypujare** [comment]
I assume the 
![image](https://user-images.githubusercontent.com/14166415/110163359-c6e5f580-7da4-11eb-96bc-80ff54dddda8.png) message means "An existing connection was forcibly closed by the remote host"

Which means the Go client side closed the connection for some reason and we would like to see the logs on the Go side to see why it did that. Can you increase the logging level on the Go side and paste the messages here?

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
