### ISSUE TITLE
Does enableRetry enable transparent retries and how to disable it?

### ISSUE THREAD

**Issue by hijerusalem** [grpc/grpc-java#7947]
snippet1
```
ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 8000)
                .keepAliveWithoutCalls(true)
                .disableRetry()
                .usePlaintext()
                .build();

```

snippet2
```
ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 8000)
                .keepAliveWithoutCalls(true)
                .usePlaintext()
                .build();

```

When building a channel, if I call `disableRetry` or  don't call `enableRetry`, does [transparent retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#transparent-retries) will be disabled?

**Comment by sanjaypujare** [comment]
I think the answer is yes but @dapengzhang0 should confirm

**Comment by dapengzhang0** [comment]
Currently transparent retry is not enable by default. So only `enableRetry()` will enable it. `disableRetry` will disable retry as well as transparent retry.
