### ISSUE TITLE
Compiling and testing the codegen raspberry 4

### ISSUE THREAD

**Issue by nkaramolegos** [grpc/grpc-java#7949]
I am trying to compile gRPC Java Codegen Plugin for Protobuf Compiler in PI4
I run:
1) _../gradlew java_pluginExecutable -Pprotoc=/usr/local/bin/protoc -PskipAndroid=true_ -> BUILD SUCCESSFUL
2) _../gradlew test -Pprotoc=/usr/local/bin/protoc -PskipAndroid=true_ -> BUILD SUCCESSFUL
3) I don't know how to run protoc --plugin= .. command. Specifically, I don't know what all this envs should be. So I skip it (**Is this problem?**)
4) _../gradlew publishToMavenLocal -PskipAndroid=true -Pprotoc=/usr/local/bin/protoc_  -> Assertion failed:  "elf64-littleaarch64" == "elf64-little"
File "check-artifact.sh", line 63

FAILURE: Build failed with an exception.
So I change the line 63 in the chech-artifact.sh to _assertEq "$format" "elf64-littleaarch64" $LINENO_ (**Is this problem?**)
and the build is successful

How can I confirm that the codegen is installed to Maven local repository to use it from an other application?

**Comment by nkaramolegos** [comment]
Ok. I thinkg that I fine. I can find the grpc in the io directory. Thank you

**Comment by nkaramolegos** [comment]
I am trying to build v1.23.0 to pi4. When I run: ./gradlew test -Pprotoc=/usr/local/bin/protoc -PskipAndroid=true

I have this error:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-compiler:generateTestLiteProto'.
> Could not resolve all files for configuration ':grpc-compiler:protobufToolsLocator_javalite'.
   > Could not find protoc-gen-javalite-linux-aarch_64.exe (com.google.protobuf:protoc-gen-javalite:3.0.0).
     Searched in the following locations:
         https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/protobuf/protoc-gen-javalite/3.0.0/protoc-gen-javalite-3.0.0-linux-aarch_64.exe

**Comment by sanjaypujare** [comment]
> I am trying to build v1.23.0 to pi4. When I run: ./gradlew test -Pprotoc=/usr/local/bin/protoc -PskipAndroid=true
> 
> I have this error:
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':grpc-compiler:generateTestLiteProto'.
> 
> > Could not resolve all files for configuration ':grpc-compiler:protobufToolsLocator_javalite'.
> > Could not find protoc-gen-javalite-linux-aarch_64.exe (com.google.protobuf:protoc-gen-javalite:3.0.0).
> > Searched in the following locations:
> > https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/protobuf/protoc-gen-javalite/3.0.0/protoc-gen-javalite-3.0.0-linux-aarch_64.exe
> 
> At this version I see that there is no support for ARM64. Should I cherry pick the changed files on this PR #6496 ?

That's your best bet. Or try to use the latest version. Why do you want to use v1.23.0 ? That's too old to get any support.

**Comment by nkaramolegos** [comment]
For some reason fabric-chaincode-java ask for this version. I will try to make it work with a newer one.

**Comment by ejona86** [comment]
Pre-built protoc-gen-grpc-java binaries have been uploaded to Maven Central since 1.26.0. I'd strongly suggest using a newer version of gRPC and using the pre-built binaries. You shouldn't need to run the grpc-java build at all for your environment.

**Comment by ejona86** [comment]
Seems there's nothing more for us to do at the moment. We do support the platform, but only on newer versions. We won't be enhancing the older versions, so there's not much avenue for changing stuff on our side.

If that's not the case or if you have trouble upgrading gRPC, comment and we can reopen.
