### ISSUE TITLE
Unable to compile gRPC codegen plugin

### ISSUE THREAD

**Issue by dasotong** [grpc/grpc-java#797]
Hi, 

I encounter the following error when I tried to do a gradle build from windows command line.

D:\grpc-java-master\compiler>..\gradlew java_pluginExecutable
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\grpc-java-master\compiler\build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'compiler'.
> Could not find property 'libraries' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@5e746d37.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.01 secs

Do I need to explicitly set the classpath in order for Gradle to understand property 'libraries'?

**Comment by ejona86** [comment]
The point of `skipCodegen=true` is to not build the compiler. If you want to build the compiler, you need `-PskipCodegen=false` (or remove the `skipCodegen=true` line from your `gradle.properties`).
