### ISSUE TITLE
how to force trigger refresh dns list?

### ISSUE THREAD

**Issue by waylink** [grpc/grpc-java#7975]
version: 1.32.0
env: k8s + 8*centos7.4
dress: dns:///example.my.company

Error：
1.When only one centos_1 cpu is hight_load, but not dead > 30min;
2.grpc server at centos_1 has many instance, these grpc server connection is not closed;
3.These grpc server instance all request were over dead_line,  can't service >30min, ;
3.But at this time, nslookup is excluded centos_1 grpc server instance;

by the way

How can I force trigger refresh dns list at client side?

Or What can I do in this exception?

**Comment by ejona86** [comment]
The client refreshes DNS when connections close. So you will want to use [MAX_CONNECTION_AGE](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#maxConnectionAge-long-java.util.concurrent.TimeUnit-) on the server-side to trigger the client to refresh DNS and connect to different backends.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
