### ISSUE TITLE
jcenter is going away

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#7990]
Used in about nine places:

https://github.com/grpc/grpc-java/search?q=jcenter

These should all be replaced with `maven()`

**Comment by ejona86** [comment]
Seems https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ is what you are referring to. JCenter was the default for Android projects. Seems the recommendation is to [swap to Maven Central](https://developer.android.com/studio/build/jcenter-migration).

**Comment by elharo** [comment]
yep, exctly
