### ISSUE TITLE
ClusterResolverLoadBalancer's "UNAVAILABLE: No usable endpoint" not very useful

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#7996]
In b/183205647 a tester saw the error "UNAVAILABLE: No usable endpoint". That is an extremely unhelpful error, except that it has a unique string that can be looked up in the code. It isn't even obvious it is an xDS error. We should improve the error message, at least to something like "UNAVAILABLE: No EDS resources exist for clusters: c1, c2, c3" (or something more appropriate).

**Comment by sanjaypujare** [comment]
Should we have consistent error reporting for all languages? We try to have consistent APIs across languages so error reporting should be thought of along the same lines

**Comment by ejona86** [comment]
C still says only "failed to connect to all addresses" if it can't contact the server; it doesn't say connection refused, or no route to host, or even certificate failure (although it prints out a separate error in this case). There are different expectations for relying on (debug) logs. Aligning even non-xDS error messages would be a huge amount of work. I'm not against the idea, but I wouldn't delay this work on such an effort.

**Comment by sanjaypujare** [comment]
> ...I wouldn't delay this work on such an effort.

Yes, we shouldn't block on that effort. But I was wondering what message other languages produce for this situation and whether we can match that if that happens to be better. But looks like that's not the case and consistency of error messages will be a huge effort.

**Comment by ejona86** [comment]
Error message improved by #8176
