### ISSUE TITLE
Optimize buffer usage in MessageFramer

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#8]
We currently allocate a large non-direct buffer per stream due to MessageFramer, only to copy immediately out of it. We should instead write directly to the transport-native buffer, which will cause us to have a WriteableBuffer or some such like our current Buffer class that is ready-only.

**Comment by buchgr** [comment]
> Using a new buffer each time means that MessageFramer won't need to be closed when the Call is closed, which turns out to be quite helpful from a threading perspective since MessaegFramer is currently run within the application thread and so we can't clean it explicitly without making it thread-safe.

@ejona86 I am currently working on this and I was wondering how you thought piggy-backing the END_STREAM flag would work without close/dispose and a new buffer on every write?

**Comment by ejona86** [comment]
I think it is reasonable to assume a flush/close/dispose will always be coming.

**Comment by buchgr** [comment]
so we still need the flush/close/dispose on the MessageFramer to behave the same as they did until know, correct?

**Comment by ejona86** [comment]
Basic flow (but, of course, with framing mixed in):
```java
void write(blah) {
  while (blah.moreToWrite()) {
    if (buffer != null && buffer.full()) flush();
    if (buffer == null) buffer = alloc();
    writeAsMuchAsPossible(buffer, blah);
  }
}

void flush() {
  if (buffer != null) {
    send(buffer);
    buffer = null;
  }
}
```

In that code if the message is precisely the size of the buffer then it isn't flushed. That is more "optimal" but doesn't really matter. I wrote it like that here since I think that is what the current code is doing.

**Comment by buchgr** [comment]
@ejona86 ahh got ya. yeah that's what I thought. thank you! :-).

**Comment by ejona86** [comment]
The "idle" state will be there is no buffer. When a message is sent, a flush/close _must_ be coming basically immediately after. So dispose() would only be necessary in case of exception or something. We wouldn't need to call dispose() to clean up when the stream is torn down (which I can't remember if we are doing now, since the current buffer is on the heap)

**Comment by buchgr** [comment]
@ejona86 I was just thinking. What's the point of having a `WritableBuffer` and `ReadableBuffer`, why not simply extend the existing buffer with a write method? Basically all we want to do is abstract from Netty's `ByteBuf` and OkHttp's `Buffer`.

**Comment by ejona86** [comment]
We could, and considered it. The main problem is that the API becomes a lot more interesting when you can read and write at the same time. Consider what be necessary to use JDK's ByteBuffer in such a circumstance.

All very doable, but it seemed keeping them separate was no more work, simpler, and had no real deficiencies.
