### ISSUE TITLE
RPCs should fail with UNAUTHENTICATED if fetching auth token returns HttpResponseException

### ISSUE THREAD

**Issue by arithmetic1728** [grpc/grpc-java#8003]
This caused issue: https://github.com/googleapis/gax-java/issues/965

## Description

The following is what happens.

1. If refresh token is invalid, then auth lib will throw an `HttpResponseException` like the following
```
com.google.api.client.http.HttpResponseException: 400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error": "invalid_request",
  "error_description": "Could not determine client ID from request."
}
```

2. [auth lib then passes the exception](https://github.com/googleapis/google-auth-library-java/blob/master/credentials/java/com/google/auth/Credentials.java#L114) to a `callback`
```
protected final void blockingGetToCallback(URI uri, RequestMetadataCallback callback) {
    Map<String, List<String>> result;
    try {
      result = getRequestMetadata(uri);
    } catch (Throwable e) {
      callback.onFailure(e);   <========= here
      return;
    }
    callback.onSuccess(result);
  }
```

3. callback is handled by the following code in grpc-auth [GoogleAuthLibraryCallCredentials.java](https://github.com/grpc/grpc-java/blob/master/auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java#L138)

```
public void onFailure(Throwable e) {
        if (e instanceof IOException) {         <=============== here
          // Since it's an I/O failure, let the call be retried with UNAVAILABLE.
          applier.fail(Status.UNAVAILABLE
              .withDescription("Credentials failed to obtain metadata")
              .withCause(e));
        } else {
          applier.fail(Status.UNAUTHENTICATED
              .withDescription("Failed computing credential metadata")
              .withCause(e));
        }
      }
```

Note that `HttpResponseException` is subclass of `IOException`, but we shouldn't retry on `HttpResponseException`. So the correct implementation would be:
```
public void onFailure(Throwable e) {
        if ((e instanceof IOException) && !(e instanceof HttpResponseException)) {         <=============== here
          // Since it's an I/O failure, let the call be retried with UNAVAILABLE.
          applier.fail(Status.UNAVAILABLE
              .withDescription("Credentials failed to obtain metadata")
              .withCause(e));
        } else {
          applier.fail(Status.UNAUTHENTICATED
              .withDescription("Failed computing credential metadata")
              .withCause(e));
        }
      }
```

**Comment by voidzcy** [comment]
This is actually identical to #6808.

I am in favor of the argument that we shouldn't be looking at the `HttpResponseException` as mentioned in https://github.com/grpc/grpc-java/issues/6808#issuecomment-604222507:

> The HttpResponseException exception is very awkward for gRPC to dig into, as it is part of google-http-java-client which is an implementation detail of google-auth-library-java. It is unclear how this would be resolved; it would probably need enhancements to the google-auth-library-java API

But returning a status code other than `UNAVAILABLE` to avoid applications retrying RPCs seems legitimate to me. I'd also agree the `RequestMetadataCallback.onFailure()` API for returning most failures as an `IOException` is quite limited.

Besides that, the security team is arguing that you should probably use alternatives other than downloading service account keys (see https://github.com/grpc/grpc-java/issues/6808#issuecomment-662056695). That could avoid you getting into this problem.

**Comment by ejona86** [comment]
Let's keep this discussion in #6808.
