### ISSUE TITLE
XdsNameResolver does not handle resource revoked and then recovered correctly

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#8009]
If LDS resource is revoked, the xds lbs will be shutdown and switch to empty service config and pick_first, but when exactly the same resource is recovered after revocation, [`shouldUpdateResult`](https://github.com/grpc/grpc-java/blob/v1.36.0/xds/src/main/java/io/grpc/xds/XdsNameResolver.java#L632-L658) is always false, and therefore `updateResolutionResult()` is never called and new service config is never generated.

**Comment by YifeiZhuang** [comment]
Looks it can be triggered by real customer use case of duplicate api listener: https://docs.google.com/document/d/1CM3QdAnV0cCd1NiKRj9gSz8Pt38JHPMYme8SJB1fEEw/edit?resourcekey=0-s8rSM-pJenGSrSvSC8EH-A#heading=h.m4q15cl5wja5

Added test #26065
