### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by SagarHuli** [grpc/grpc-java#8034]
### What version of gRPC-Java are you using?
grpc-java-1.35.0
### What is your environment?

Windows 10, jdk-1.8
### What did you expect to see?
grpc server up and running with no warnings 
### What did you see instead?
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### Steps to reproduce the bug
Implement a grpc service 
Run the service and when the server accepts the grpc request from client, it responds with above warnings

**Comment by dapengzhang0** [comment]
It seems you have an old version of protobuf installed. Might be related to https://github.com/protocolbuffers/protobuf/issues/3781
Is there any version number of protobuf shown after this message?
```
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
```

e.g.  
```
(file:/Users/test/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.4.0/b32aba0cbe737a4ca953f71688725972e3ee927c/protobuf-java-3.4.0.jar)
```

**Comment by dapengzhang0** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
