### ISSUE TITLE
Does not build on FreeBSD

### ISSUE THREAD

**Issue by tarkhil** [grpc/grpc-java#8049]
### What version of gRPC-Java are you using?
freshly cloned
### What is your environment?

FreeBSD  12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

### What did you expect to see?
build the library
### What did you see instead?
`FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/src/grpc-java/all/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':grpc-all'.
> A problem occurred configuring project ':grpc-gae-interop-testing-jdk8'.
   > Failed to notify project evaluation listener.
      > Unknown OS: FreeBSD
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`
### Steps to reproduce the bug
gradle build on FreeBSD

**Comment by dapengzhang0** [comment]
Were you able to build with the gradle wrapper `./gradlew` in the project directory and skip codegen and android?
```
./gradlew build -PskipCodegen=true -PskipAndroid=true
```
?

**Comment by tarkhil** [comment]
No
`
Starting a Gradle Daemon (subsequent builds will be faster)
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/src/grpc-java/all/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':grpc-all'.
> A problem occurred configuring project ':grpc-gae-interop-testing-jdk8'.
   > Failed to notify project evaluation listener.
      > Unknown OS: FreeBSD
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
`
Where is a list of known OSes?

**Comment by dapengzhang0** [comment]
Does the build fail at any sub-project other than ':grpc-gae-interop-testing-jdk8'. Say, build a single sub-project
```
./gradlew :grpc-api:build -PskipCodegen=true -PskipAndroid=true
```

If still failing, could you run with `--stacktrace --debug` to provide more log. I don't have a FreeBSD env to reproduce. 

FreeBSD is not officially supported. While we can provide our best effort, you may also get help from community by asking in [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io).

**Comment by tarkhil** [comment]
Is Java supposed to be multi-platoform?...

**Comment by dapengzhang0** [comment]
> Is Java supposed to be multi-platoform?...

There are some subprojects that call JNI native code might be platform-dependent and may not work well in FreeBSD without custom setup. As least `:grpc-gae-interop-testing-jdk8` is not supposed to run in FreeeBSD. Does building a single subproject such as `:grpc-api` work?

**Comment by tarkhil** [comment]
Well... actually all I need to build is a java-tron, which uses protoc-gen-grpc - so I need to build only it.

I'm not a Java developer, and whatever I could google does not help me.

`
root@coins:/usr/local/src/grpc-java # gradle -q projects -PskipAndroid=true
  * Skipping the build of Android projects because skipAndroid=true
*** Building codegen requires Protobuf version 3.12.0
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/src/grpc-java/all/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':grpc-all'.
> A problem occurred configuring project ':grpc-gae-interop-testing-jdk8'.
   > Failed to notify project evaluation listener.
      > Unknown OS: FreeBSD
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)
      > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
root@coins:/usr/local/src/grpc-java #
`
I cannot even get list of projects

**Comment by ejona86** [comment]
> which uses protoc-gen-grpc - so I need to build only it.

That is the compiler/ folder (:grpc-compiler project).

> \> java.lang.NullPointerException (no error message)
>
>Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

It would be helpful to know where the NullPointerException is happening. Please run with `--stacktrace` and provide one of the stack traces.

That said, I think this is the most likely to explain what is happening:

> Unknown OS: FreeBSD

Normally I'd say that is part of the os-detector plugin that is used to determine the classifier for the protoc-gen-grpc binary. But "Unknown OS" isn't in the source of the plugin and the gae project doesn't use that plugin.

So maybe this is an issue of the gae plugin itself? That would be surprising, but isn't impossible. We might need to see the tail end of `--info` or `--debug` runs. Debug output is a lot to dig through, though...

As a quick work-around, try commenting out the two references to `:grpc-gae-interop-testing-jdk8` in `settings.gradle`.

grpc-all pulling in gae looks to be a bug. Created #8082 to address.

**Comment by dapengzhang0** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
