### ISSUE TITLE
[Help wanted] io.grpc.okhttp.OkHttpClientTransportTest fails in Mac and GitHub Actions

### ISSUE THREAD

**Issue by suztomo** [grpc/grpc-java#8080]
In master, I cannot build :grpc-okhttp module because OkHttpClientTransportTest fails in my Mac (Mac OS 11.2.3) and GitHub Actions ([link](https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1982/checks?check_run_id=2328386670)). 

```
suztomo-macbookpro44% git log -1                                                                  
commit d4fa0ecc07495097453b0a2848765f076b9e714c (HEAD -> master, origin/master, origin/HEAD)
Author: Chengyuan Zhang <chengyuanzhang@google.com>
Date:   Mon Apr 12 14:55:31 2021 -0700
...(omit)...
suztomo-macbookpro44% cat gradle.properties 
skipCodegen=true
skipAndroid=true
suztomo-macbookpro44%  ./gradlew cleanTest :grpc-okhttp:test --tests=io.grpc.okhttp.OkHttpClientTransportTest
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

> Task :grpc-okhttp:test

io.grpc.okhttp.OkHttpClientTransportTest > proxy_200 FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at io.grpc.okhttp.OkHttpClientTransportTest.proxy_200(OkHttpClientTransportTest.java:1876)

io.grpc.okhttp.OkHttpClientTransportTest > proxy_500 FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at io.grpc.okhttp.OkHttpClientTransportTest.proxy_500(OkHttpClientTransportTest.java:1933)

io.grpc.okhttp.OkHttpClientTransportTest > proxy_immediateServerClose FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at io.grpc.okhttp.OkHttpClientTransportTest.proxy_immediateServerClose(OkHttpClientTransportTest.java:1989)

68 tests completed, 3 failed

> Task :grpc-okhttp:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-okhttp:test'.
> There were failing tests. See the report at: file:///Users/suztomo/grpc-java/okhttp/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
58 actionable tasks: 3 executed, 55 up-to-date
```

The build works fine in my Debian machine. (I also see this repository has setup Travis CI enabled.)

```
suztomo@suztomo:~/grpc-java$  ./gradlew cleanTest  :grpc-okhttp:test --tests=io.grpc.okhttp.OkHttpClientTransportTest
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

BUILD SUCCESSFUL in 5s
58 actionable tasks: 2 executed, 56 up-to-date
```

Therefore I think I'll need to setup something for the failing environment to make the test pass.

While I continue to dig further, I appreciate if anyone know the prerequisite for OkHttpClientTransportTest.

**Comment by suztomo** [comment]
Variables at `Socket sock = serverSocket.accept();` line.

<img width="1354" alt="Screen Shot 2021-04-13 at 10 04 41" src="https://user-images.githubusercontent.com/28604/114565934-c102f000-9c3f-11eb-8859-029c0da3b502.png">

**Comment by sanjaypujare** [comment]
I tried this test on my Mac (same version Mac OS 11.2.3) and it works. I am trying to think what could be different about your setup but I just wanted to provide this datapoint.

**Comment by sanjaypujare** [comment]
I found this https://stackoverflow.com/questions/18704273/serversocket-accept-method-blocks-even-after-connection-is-established which says "It is possible to have one process bind to 127.0.0.1 and another to bind to 0.0.0.0" (same port)

Is it possible you have some other app listening on 127.0.0.1:portX and the test binds to 0.0.0.0:portX (which will succeed) ?but the accept blocks as described in the post?

**Comment by ejona86** [comment]
Looks like you are running it from within Maven? That's the only strange thing I see in your setup. Since it fails on both github actions and your mac, that seems to be the more likely cause than the platform.

So the question is, what is weird about how Maven/whatever is executing gradle? Looking at the source though, I don't know what tools you are using. What is this file? https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1982/files#diff-1f8a32a8bff636c0a20d528c031fd9bdc237f2794d6689b99964de7e32050122

**Comment by suztomo** [comment]
@sanjaypujare Thank you for reference. I checked `telnet localhost 80`, `telnet 0.0.0.0 80`, `telnet 127.0.0.1 80` and they don't connect (`Connection refused`).

> "It is possible to have one process bind to 127.0.0.1 and another to bind to 0.0.0.0" (same port)

I'll check the possibility.

@ejona86  Thank you for response. For the GitHub Actions, yes I use Maven (strange setup). But for reproducing the problem in Mac, I don't use Maven. The gradle command ` ./gradlew cleanTest :grpc-okhttp:test --tests=io.grpc.okhttp.OkHttpClientTransportTest` fails.

**Comment by sanjaypujare** [comment]
> @sanjaypujare Thank you for reference. I checked `telnet localhost 80`, `telnet 0.0.0.0 80`, `telnet 127.0.0.1 80` and they don't connect (`Connection refused`).
> 
> > "It is possible to have one process bind to 127.0.0.1 and another to bind to 0.0.0.0" (same port)
> 
> I'll check the possibility.

This seems unlikely because the port picked by the test is dynamic. May be the issue on the client side - it is not connecting?

> 
> @ejona86 Thank you for response. For the GitHub Actions, yes I use Maven (strange setup). But for reproducing the problem in Mac, I don't use Maven. The gradle command ` ./gradlew cleanTest :grpc-okhttp:test --tests=io.grpc.okhttp.OkHttpClientTransportTest` fails.

**Comment by ejona86** [comment]
@suztomo, can you try making this change to the test and then looking at the report in `okhttp/build/reports/tests/test/index.html` afterward (click through to the class, and then click "Standard output")?

```patch
diff --git a/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java b/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
index 0994bc900..2c063cfc5 100644
--- a/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
+++ b/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
@@ -1985,6 +1985,12 @@ public class OkHttpClientTransportTest {
         transportTracer,
         false);
     clientTransport.start(transportListener);
+    org.mockito.Mockito.doAnswer(new org.mockito.stubbing.Answer<Void>() {
+      @Override public Void answer(org.mockito.invocation.InvocationOnMock invocation) {
+        System.out.println(Arrays.asList(invocation.getArguments()));
+        return null;
+      }
+    }).when(transportListener).transportShutdown(any(Status.class));
 
     Socket sock = serverSocket.accept();
     serverSocket.close();
```

**Comment by suztomo** [comment]
@ejona86 Thanks! The test report didn't generate any "Standard output".

<img width="1355" alt="Screen Shot 2021-04-13 at 18 23 07" src="https://user-images.githubusercontent.com/28604/114628765-655b5580-9c85-11eb-8201-0a5e3a32807d.png">

Command invocation for my reference: https://gist.github.com/suztomo/7566afa849dd4b987aa8428b5f564c04

**Comment by ejona86** [comment]
Strange. That means the client is still trying to connect. It's like the local connection has blackholed itself (like a firewall). Increase the test timeout to 60-120 seconds or so and let's see what happens:
https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java#L150

Also try forcing the server to sit on localhost only, and see if that improves things (note we are only changing one test; two of them would still fail, but maybe this one would start passing):
```diff
diff --git a/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java b/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
index 0994bc900..a13dd83ed 100644
--- a/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
+++ b/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
@@ -1963,7 +1963,7 @@ public class OkHttpClientTransportTest {
 
   @Test
   public void proxy_immediateServerClose() throws Exception {
-    ServerSocket serverSocket = new ServerSocket(0);
+    ServerSocket serverSocket = new ServerSocket(0, 0, InetAddress.getLoopbackAddress());
     InetSocketAddress targetAddress = InetSocketAddress.createUnresolved("theservice", 80);
     clientTransport = new OkHttpClientTransport(
         targetAddress,
```

**Comment by suztomo** [comment]
@ejona86 `new ServerSocket(0, 0, InetAddress.getLoopbackAddress())` solved the problem!

Now `proxy_immediateServerClose` succeeds:

```
suztomo-macbookpro44% git diff                                                                                
diff --git a/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java b/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
index 0994bc900..b59aea9c1 100644
--- a/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
+++ b/okhttp/src/test/java/io/grpc/okhttp/OkHttpClientTransportTest.java
@@ -1963,7 +1963,7 @@ public class OkHttpClientTransportTest {
 
   @Test
   public void proxy_immediateServerClose() throws Exception {
-    ServerSocket serverSocket = new ServerSocket(0);
+    ServerSocket serverSocket = new ServerSocket(0, 0, InetAddress.getLoopbackAddress());
     InetSocketAddress targetAddress = InetSocketAddress.createUnresolved("theservice", 80);
     clientTransport = new OkHttpClientTransport(
         targetAddress,
@@ -1985,6 +1985,12 @@ public class OkHttpClientTransportTest {
         transportTracer,
         false);
     clientTransport.start(transportListener);
+    org.mockito.Mockito.doAnswer(new org.mockito.stubbing.Answer<Void>() {
+      @Override public Void answer(org.mockito.invocation.InvocationOnMock invocation) {
+        System.out.println(Arrays.asList(invocation.getArguments()));
+        return null;
+      }
+    }).when(transportListener).transportShutdown(any(Status.class));
 
     Socket sock = serverSocket.accept();
     serverSocket.close();
suztomo-macbookpro44%  ./gradlew cleanTest  :grpc-okhttp:test --tests=io.grpc.okhttp.OkHttpClientTransportTest
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

> Task :grpc-okhttp:test

io.grpc.okhttp.OkHttpClientTransportTest > proxy_200 FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at io.grpc.okhttp.OkHttpClientTransportTest.proxy_200(OkHttpClientTransportTest.java:1876)

io.grpc.okhttp.OkHttpClientTransportTest > proxy_500 FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at io.grpc.okhttp.OkHttpClientTransportTest.proxy_500(OkHttpClientTransportTest.java:1933)

68 tests completed, 2 failed

> Task :grpc-okhttp:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-okhttp:test'.
> There were failing tests. See the report at: file:///Users/suztomo/grpc-java/okhttp/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s

```

This time standard output captured the invocation argument:


```
[Status{code=UNAVAILABLE, description=Failed trying to connect with proxy, cause=java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at io.grpc.okhttp.OkHttpClientTransport.readUtf8LineStrictUnbuffered(OkHttpClientTransport.java:731)
	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxySocket(OkHttpClientTransport.java:680)
	at io.grpc.okhttp.OkHttpClientTransport.access$1100(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:559)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
}]
```

@ejona86 @sanjaypujare Thank you for your help in troubleshooting!

**Comment by sanjaypujare** [comment]
> @ejona86 @sanjaypujare Thank you for your help in troubleshooting!

But what's the solution? I am surprised using the loopback address works but IPADDR_ANY (`0.0.0.0`) does not. So this needs further investigation to actually make it work for you, right?

**Comment by suztomo** [comment]
@sanjaypujare I enriched my analysis above. I think the problem was that the client was trying to create a socket to address 0.0.0.0, while the address 0.0.0.0 is not meant to be used as a destination.

**Comment by sanjaypujare** [comment]
> @sanjaypujare I enriched my analysis above. I think the problem was that the client was trying to create a socket to address 0.0.0.0, while the address 0.0.0.0 is not meant to be used as a destination.

So the test will need to be fixed to not use 0.0.0.0 as the target in the client but 127.0.0.1? But curious if this caused a problem on your Mac because it has multiple interfaces or is it something else?

**Comment by suztomo** [comment]
I'm not sure why destination 0.0.0.0 works for certain machines. (In my Debian machine, the address 0.0.0.0 works fine.)

**Comment by sanjaypujare** [comment]
> My Mac is a normal MacBook Pro. It has wifi connection.
> 
> I'm not sure why destination 0.0.0.0 works for certain machines. (In my Debian machine, the destination address 0.0.0.0 works fine for the OkHttp test.)

I found some more info https://superuser.com/questions/1307050/how-does-the-os-resolve-a-request-to-connect-to-0-0-0-0 but again it doesn't explain the behavior difference between your Mac and my Mac
