### ISSUE TITLE
Generated annotation Java11

### ISSUE THREAD

**Issue by EzxD** [grpc/grpc-java#8086]
### What is your environment?
MacBook m1 Jdk 11

### What did you expect to see?
Generated annotation from javax.annotation.processing.Generated

### What did you see instead?
@javax.annotation.Generated

that's my build file
```gradle
plugins {
    id "com.google.protobuf" version "0.8.15"
    id "java"
}

group 'net.rangemc.ms.user'
version '1.0-SNAPSHOT'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
}

def grpcVersion = '1.37.0'
def protobufVersion = '3.12.0'
def protocVersion = protobufVersion

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'

    // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
    compile group: 'com.google.protobuf', name: 'protobuf-java', version: protobufVersion

    // https://mvnrepository.com/artifact/io.grpc/grpc-all
    compile group: 'io.grpc', name: 'grpc-all', version: grpcVersion
}

sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protocVersion}"
    }

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }

    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}
```

**Comment by sanjaypujare** [comment]
Couple of things:

- [README](https://github.com/grpc/grpc-java/blob/master/README.md) and [COMPILING](https://github.com/grpc/grpc-java/blob/master/README.md) talk about requiring JDK8 and working with JDK 7 in terms of source/target compatibility.
- the [protobuf Java plugin](https://github.com/grpc/grpc-java/tree/master/compiler) is based on the above to generate JDK7 level Java source code and hence it generates  `@javax.annotation.Generated`. The plugin doesn't respect your sourceCompatibility setting in the gradle file nor is there a way to pass an option to it for Java source level.

The plugin will be modified to generate  `@javax.annotation.processing.Generated` only when grpc's JDK minimum version requirement is changed to JDK11.

Let me know if you have other suggestions.

**Comment by EzxD** [comment]
Is there a way for me to change the grpc´s JDK minimum version? If so how can I change it?

**Comment by sanjaypujare** [comment]
> Is there a way for me to change the grpc´s JDK minimum version? If so how can I change it?

This is for the team to decide based on community asks and once decided we will have to make whatever changes are needed to move to the new JDK version.

If you just want to try it out in your local workspace you may consider changing https://github.com/grpc/grpc-java/blob/master/compiler/src/java_plugin/cpp/java_generator.cpp#L1203 to use `javax.annotation.processing.Generated` and using your local plugin as described in the [README](https://github.com/grpc/grpc-java/tree/master/compiler#readme).

You can also consider enhancing the code to pass an option to the plugin to indicate the target JDK version and contributing that code.

**Comment by EzxD** [comment]
thanks.
Hopefully they add soon support for more

**Comment by norrisjeremy** [comment]
Why not just stop creating the `@Generated` annotation entirely?
It doesn't really serve any purpose, other than make people's life more difficult when they are using modern Java.

**Comment by sanjaypujare** [comment]
> Why not just stop creating the `@Generated` annotation entirely?
> It doesn't really serve any purpose, other than make people's life more difficult when they are using modern Java.

That's debatable. In our ecosystem specially the annotation is useful because of proto generated code.

If the annotation was useless the Java community would have removed it or marked it deprecated.

**Comment by norrisjeremy** [comment]
> > Why not just stop creating the `@Generated` annotation entirely?
> > It doesn't really serve any purpose, other than make people's life more difficult when they are using modern Java.
> 
> That's debatable. In our ecosystem specially the annotation is useful because of proto generated code.
> 
> If the annotation was useless the Java community would have removed it or marked it deprecated.

But it _has_ been removed starting with Java 9. I would think that's a pretty clear indicator that it ought to be removed.

**Comment by norrisjeremy** [comment]
FYI, something I've seen other projects do is simply define their own `@Generated` annotation that mimics the old `javax.annotation.Generated` annotation and just us it instead. That way they can gain the benefits of having some sort of `@Generated` annotation, that works both with Java 8 and Java 9+.

**Comment by norrisjeremy** [comment]
Also, the base `protoc` compiler itself doesn't stick `@Generated` on the classes it generates. All it does it stick a comment at the top of the file:
```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xxx.proto
```

**Comment by sanjaypujare** [comment]
Pls see my [comment above](https://github.com/grpc/grpc-java/issues/8086#issuecomment-820528334). You are welcome to create a PR that addresses the issue in a backward compatible way.
