### ISSUE TITLE
ServerWrapperForXdsTest.delegateStartError_shutdown is flaky

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#8092]
https://fusion2.corp.google.com/invocations/4eeb906e-33e6-43c5-b626-c8e2b5feb305/targets/%2F%2Fthird_party%2Fjava_src%2Fgrpc%2Fxds:src%2Ftest%2Fjava%2Fio%2Fgrpc%2Fxds%2FServerWrapperForXdsTest;config=f93d366d8be3e6c1414d755c50d7e98feb61b5ab565348b1a10addcfa01fccd1/tests

```
ServerWrapperForXdsTest.delegateStartError_shutdown 
value of: getCurrentServingState()
expected: SHUTDOWN
but was : ENTER_SERVING
	at io.grpc.xds.ServerWrapperForXdsTest.delegateStartError_shutdown(ServerWrapperForXdsTest.java:259)
```

As confirmed by @sanjaypujare 

>It's quite possible a flake - there is
```
Thread.sleep(100L);
```
>on line 257
Either I should increase the sleep time or find another way to make it less flaky and deterministic

**Comment by ejona86** [comment]
Fixed by #8333.
