### ISSUE TITLE
ServerCall attributes for security accounting

### ISSUE THREAD

**Issue by pmartinou** [grpc/grpc-java#8125]
For implementing server-side access control, we retrieve the Authentication information using a `ServerInterceptor`.
In addition to the client credentials (retrieved from the _headers_ `Metadata`), we need the client's address.

The '_remote-addr_' `Attribute `is provided using the `ServerCall`'s `getAttributes`.
However, this API is marked experimental, and the presence of the '_remote-addr_' attribute is nowhere guaranteed.

Is there a reliable way to determine the client's remote address, as it is an important information for security control and accounting ?

**Comment by voidzcy** [comment]
> this API is marked experimental

`Attributes` is marked as experimental, it's been used widely inside Google, we can look into stabilizing it (after resolving some minor issue regarding [Attributes.Key](https://github.com/grpc/grpc-java/issues/1764#issuecomment-348630514)).

> the presence of the 'remote-addr' attribute is nowhere guaranteed

It inherently works in that way, as retrieving remote address is transport-dependent (e.g., inprocess vs netty) and can never be guaranteed. In general, you should always be able to get the remote address. But in terms of guarantee, that's a too strong specification. For access control use cases, we'd suggest to fail the call if the 'remote-addr' attribute is not present.

**Comment by pmartinou** [comment]
OK, thanks.
