### ISSUE TITLE
Aarch64 tests are flaky due to being slow

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#8135]
StressTestClientTest timeout:
https://source.cloud.google.com/results/invocations/4c46506b-04f8-491c-8296-10ee52efab4b
BinlogHelperTest deadline out-of-range:
https://source.cloud.google.com/results/invocations/3dc3f62d-553e-45dd-a707-9be40dd0498d

There was also one tool failure, but I'm guessing that was a kokoro issue so let's ignore it for now:
https://source.cloud.google.com/results/invocations/24378087-f7a9-470a-8d38-06ff4a20101f/targets

There have been 6 runs, so that puts failure rate at 2 out of 5 so far. We've had plenty of "tests execute excruciatingly slow" issues in the past that took a long time to resolve. I'm concerned this may just be the tip of the iceburg.

CC @jtattermusch

**Comment by jtattermusch** [comment]
Since the tests are running under an userspace emulator, the execution speed is much slower than if you executed the tests on real hardware.
While having tests flake is definitely concerning, on the other hand the emulated tests serve as a good way of seeing whether the tests are too timing dependent (which is something that's always good to know).

One random idea that could help: if the tests are currently running in parallel, perhaps the flakiness would be reduced if we only let run one test at a time (not sure how well the emulator can cope with parallelism).

**Comment by ejona86** [comment]
> While having tests flake is definitely concerning, on the other hand the emulated tests serve as a good way of seeing whether the tests are too timing dependent

We have some tests that are timing dependent on purpose. Like deadline handling and BDP monitoring. Emulating time is too hard for those yet too much fuzziness in the result and the test becomes useless.

> One random idea that could help: if the tests are currently running in parallel, perhaps the flakiness would be reduced if we only let run one test at a time

When I was investigating the TLS problem, I saw that builds were being run serially. So I think this is already the case.

**Comment by ejona86** [comment]
StressTestClient timeout:
https://source.cloud.google.com/results/invocations/31e59957-a1b7-4ae2-b525-6d89f4d1679e

**Comment by ejona86** [comment]
BinlogHelperTest:
https://source.cloud.google.com/results/invocations/ed70b200-a5e0-4e86-9968-54d0791c465b

Seeing just these two repeat gives me some hope that maybe we won't see too many other tests also have timing problems.

**Comment by ejona86** [comment]
BinlogHelperTest:
https://source.cloud.google.com/results/invocations/7604f72d-81c6-479b-94b3-b13df865665c

**Comment by ejona86** [comment]
StressTestClientTest timeout and Http2NettyTest DEADLINE_EXCEEDED:
https://source.cloud.google.com/results/invocations/3ba40007-5112-4f66-90f1-68c321fa4db0

**Comment by ejona86** [comment]
StressTestClientTest timeout and NettyFlowControlTest largBdp flake
https://source.cloud.google.com/results/invocations/d8a4644f-02d4-4607-9237-47f558eba9c7

**Comment by ejona86** [comment]
StressTestClientTest timeout:
https://source.cloud.google.com/results/invocations/253c1e54-fc68-4c97-8713-56564582640a

**Comment by ejona86** [comment]
StressTestClientTest timeout (even with 10 s, not 5 s):
https://source.cloud.google.com/results/invocations/f647898c-b447-4afd-9169-9851ab3511c4
