### ISSUE TITLE
HelloWorld example referencing to io.grpc.stub.Calls.asyncUnaryCall

### ISSUE THREAD

**Issue by dasotong** [grpc/grpc-java#814]
Hi, 

I tried to create a new project to include the HelloWorld example provided in the git,

All else is fine, except that GreeterGrpc is referencing to:
io.grpc.stub.Calls.asyncUnaryCall
io.grpc.stub.Calls.blockingUnaryCall
io.grpc.stub.Calls.futureUnaryCall.

I am referencing to the following libraries which I have built using the grpc-java and protobuf-3.0.0-alpha-3.1:
grpc-protobuf-0.8.0-SNAPSHOT.jar
protobuf-java-3.0.0-alpha-3.1.jar
guava-18.0.jar
grpc-all-0.8.0-SNAPSHOT.jar

I did a search and understand that the missing classes are existent in grpc-all-0.7.1.jar. 

How can I overcome this problem? I want to be able to generate classes from .proto files that are compatible with the above libraries. 

Appreciate any advice or help.

**Comment by madongfly** [comment]
The gRpc codegen plugin has been changed in 0.8.0, you'll need to regenerate the code.

**Comment by ejona86** [comment]
Or you can copy the new generated code from git, since we check it in.

**Comment by ejona86** [comment]
If you still can't get it working add a comment, and we can reopen the issue.
