### ISSUE TITLE
Add class-retention @GrpcGenerated annotation to generated types

### ISSUE THREAD

**Issue by groakley** [grpc/grpc-java#8158]
### Is your feature request related to a problem?

Static analyzers (e.g. lint checks and proguard) would like to reliably detect that code has been generated by gRPC in order exclude it from some types of validation. Currently, gRPC-generated types are annotated with the `@Generated` annotation, but this only has `SOURCE` retention and is unavailable to these analyzers.

### Describe the solution you'd like

Additionally add an `@GrpcGenerated` annotation with `CLASS` retention to generated types.

### Describe alternatives you've considered

Currently we inspect generated code for anticipated naming schemes and structure (e.g. endsWith("Grpc") & contains X fields) in order to determine if it is grpc-generated. Obviously this is fragile and relies on implementation details that it shouldn't.

### Additional context
There is prior art for this kind of annotation in [Dagger](https://github.com/google/dagger/blob/master/java/dagger/internal/DaggerGenerated.java) and `AutoFactory` (coming soon).

**Comment by groakley** [comment]
Thanks for the tip, I will update what we have now to look for those. Given the existing `@RpcMethod` annotation, maybe something like a `@RpcService` would make more sense on the top-level *Grpc class?

**Comment by dapengzhang0** [comment]
> Given the existing @RpcMethod annotation, maybe something like a @RpcService would make more sense on the top-level *Grpc class?

I think `@RpcService` will be like `@RpcMethod`, nothing emphasizing generated code, or prohibiting non-generated usage. If we end up adding an annotation, it would be named something like `@GrpcGenerated ` for this feature request as originally proposed.

**Comment by ejona86** [comment]
> I think @RpcService will be like @RpcMethod, nothing emphasizing generated code, or prohibiting non-generated usage.

@dapengzhang0, note that RpcMethod has this in its documentation:

> This annotation is used by the gRPC stub compiler to annotate MethodDescriptor getters. Users should not annotate their own classes with this annotation.

**Comment by dapengzhang0** [comment]
>> This annotation is used by the gRPC stub compiler to annotate MethodDescriptor getters. Users should not annotate their own classes with this annotation.

Then inspecting for `@RpcMethod` is less fragile than I thought.
