### ISSUE TITLE
INTERNAL: error in frame handler in Android

### ISSUE THREAD

**Issue by papanmanna** [grpc/grpc-java#8164]
Configuration:

   implementation 'io.grpc:grpc-okhttp:1.37.0'
    implementation ('io.grpc:grpc-protobuf:1.37.0') {
        exclude group: 'com.google.api'
        exclude group: 'com.google.protobuf.GoGoProtos', module: "protobuf-java"
        exclude group: 'com.google.protobuf.AnyProto', module: "protobuf-java"
        exclude group: 'com.google.protobuf.AnyOrBuilder', module: "protobuf-java"
    }
    implementation 'io.grpc:grpc-stub:1.37.0'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    
Stacktrace:

 Status{code=INTERNAL, description=error in frame handler, cause=java.io.IOException: FRAME_SIZE_ERROR: 4740180
	at io.grpc.okhttp.internal.framed.Http2.ioException(Http2.java:597)
	at io.grpc.okhttp.internal.framed.Http2.access$200(Http2.java:48)
	at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:138)
	at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:1101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
}

**Comment by dapengzhang0** [comment]
This looks exactly like #2436: 
>That frame size error means that you are using HTTP/1.1. 4740180 in hex is 48 54 54, which is "H T T". I believe you are connecting to the wrong server, or your server is not using gRPC.

**Comment by papanmanna** [comment]
the grpc server is okay. It can be connected from web client. In Android I'm using 

```
ManagedChannelBuilder.forAddress(GRPC_SAAGE_MAIN, PORT_SAAGE_MAIN)
                        .usePlaintext()
                        .build();
```

**Comment by papanmanna** [comment]
> Looks like this question was cross-posted to https://stackoverflow.com/questions/67493428/internal-error-in-frame-handler-in-android

@ejona86 , can you help me out from this issue?

**Comment by dapengzhang0** [comment]
@papanmanna A couple of questions:

> the grpc server is okay. It can be connected from web client. 

What is your web client that connected to the grpc server? Is it a grpc client on a PC device, or a grpc-web client or HTTP client?

Is there any proxy in the network between your grpc server and the android device? The android grpc client is receiving HTTP/1.1 frame. That's not HTTP/2 frame that grpc server should respond with.
