### ISSUE TITLE
grpc-default-executor threads stop processing tasks: how can we troubleshoot in such situation?

### ISSUE THREAD

**Issue by suztomo** [grpc/grpc-java#8174]
Do you know a good way to troubleshoot "grpc-default-executor" threads' status?

In https://github.com/apache/beam/pull/14768#issuecomment-840576342, when I tried to upgrade Beam's vendored (shaded) gRPC dependency to 1.37.0 (or [1.36](https://github.com/apache/beam/pull/14474)) from gRPC 1.26.0, I observed that some tests (GrpcLoggingServiceTest or BeamFnLoggingServiceTest randomly) do not finish. Borrowing [Kenn's words](https://lists.apache.org/thread.html/rb6babdf847c5f1fbfcb36716d769b5c94d3754fbb4eae53d7e25ceab%40%3Cdev.beam.apache.org%3E), BeamFnLoggingServiceTest does the followings:

- start a logging service
- set up some stub clients, each with onError wired up to release a countdown latch
- send error responses to all three of them (actually it sends the error in the same task it creates the stub)
- each task waits on the latch

(GrpcLoggingServiceTest has similar structure)

Unfortunately it occurs only in Beam's CI Jenkins environment (which takes ~1 hour to finish). I cannot reproduce the problem locally.

From the observation of [the trace log](https://github.com/apache/beam/pull/14768#issuecomment-840576342) and [the previous thread dump](https://gist.github.com/suztomo/64b36fd7c7e011666cbc8f99d1079ed7), it seems that grpc-default-executor threads stop processing tasks (the thread dump showed no "grpc-default-executor" threads in the JVM when the test was waiting for the them to count down a CountDownLatch) and one of the latches are not counted down. This results in the test threads waiting forever for the remaining latch. I cannot tell why the "grpc-default-executor" threads stop working (disappear?).

Do you know how to troubleshot such situation?

**Comment by sanjaypujare** [comment]
> it seems that grpc-default-executor threads stop processing tasks (the thread dump showed no "grpc-default-executor" threads in the JVM when the test was waiting for the them to count down a CountDownLatch) 

I am a bit confused: are you saying there are no "grpc-default-executor" threads or the threads are there but there are no tasks to process or the threads have stopped processing tasks?

**Comment by suztomo** [comment]
Thank you for response. There were no "grpc-default-executor" threads ([the thread dump](https://gist.github.com/suztomo/64b36fd7c7e011666cbc8f99d1079ed7)) when the tests got hung.

**Comment by sanjaypujare** [comment]
Oh, so based on this, it is a regression from 1.26.0 to 1.37 (or 1.36). Would it be possible to pass a [custom executor](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#executor-java.util.concurrent.Executor-) to your channel builder and see what the behavior is?

It is unclear why there are no "grpc-default-executor" threads but it is concerning. Let me look into it a bit more.

**Comment by suztomo** [comment]
"Logging client failed unexpectedly." and "CANCELLED: client cancelled" are expected messages in the test. After these messages, the service should call corresponding method (to count down the latches) for the exceptions.

**Comment by sanjaypujare** [comment]
> "Logging client failed unexpectedly." and "CANCELLED: client cancelled" are expected messages in the test. After these messages, the service should call corresponding method (to count down the latches) for the exceptions.
> 
> Trying the executor option.

One more thing you may want to try is to catch all `Throwable`s in your `onError`, log them and see if that was the issue. It is possible that because of an unrelated behavior change between 1.26 to 1.37 there is an uncaught exception that causes the thread to exit/die.

**Comment by suztomo** [comment]
With the executor option ([commit](https://github.com/apache/beam/pull/14768/commits/d19e32437a83d50233cfde5c9412ee5a1af1b91f)), GrpcLoggingServiceTest passes, but BeamFnLoggingServiceTest failed.

**Comment by sanjaypujare** [comment]
> With the executor option ([commit](https://github.com/apache/beam/pull/14768/commits/d19e32437a83d50233cfde5c9412ee5a1af1b91f)), GrpcLoggingServiceTest passes, but BeamFnLoggingServiceTest failed.

What about modifying your `onError` to make sure you catch all exceptions and log them?

**Comment by suztomo** [comment]
Thanks. Let me try that.

**Comment by suztomo** [comment]
I tried catching Throwable in onError ([commit](https://github.com/apache/beam/pull/14768/commits/cf73ac1720d633ca2236d00df7743468fb2f71ec)) but the method succeeded.

```
suztomo-macbookpro44% grep 'onError succeeded'  17724.log
    14:37:16.420 [grpc-default-executor-1] DEBUG o.a.b.r.f.logging.GrpcLoggingService - onError succeeded
    14:37:16.423 [grpc-default-executor-2] DEBUG o.a.b.r.f.logging.GrpcLoggingService - onError succeeded
    14:37:16.430 [grpc-default-executor-3] DEBUG o.a.b.r.f.logging.GrpcLoggingService - onError succeeded
    14:52:04.255 [grpc-default-executor-6] DEBUG o.a.b.r.d.w.f.l.BeamFnLoggingService - onError succeeded
    14:52:04.255 [grpc-default-executor-3] DEBUG o.a.b.r.d.w.f.l.BeamFnLoggingService - onError succeeded
    14:52:04.255 [grpc-default-executor-0] DEBUG o.a.b.r.d.w.f.l.BeamFnLoggingService - onError succeeded
```

**Comment by sanjaypujare** [comment]
> I tried catching Throwable in onError ([commit](https://github.com/apache/beam/pull/14768/commits/cf73ac1720d633ca2236d00df7743468fb2f71ec)) but the method succeeded.
> 

To summarize:
- you are using a custom executor now and that allows one test to pass but another test is still failing
- based on the latest commit it looks like there are no uncaught exceptions happening in `onError`

Is your test failing because of disappearing threads still? If that's the case and you are using a custom executor would you be able to instrument it to see why threads are disappearing?

**Comment by suztomo** [comment]
That's right. Now it's my custom executors that is responsible to count down the latches. Let me add more logging.

**Comment by sanjaypujare** [comment]
> That's right. Now it's my custom executors that is responsible to count down the latches. Let me add more logging.

The executor (ThreadFactory) is yours and the `onError` code executed is also yours. This is unlikely to be a gRPC issue then. But it will be good to know what the root cause is.

**Comment by suztomo** [comment]
The thread that I created from my custom executor for the `InProcessChannelBuilder` is not there when I got the thread dump (It's after 27 minutes the Jenkins console stopped showing progress).

https://gist.github.com/suztomo/bb1bf0137e391f472075baeb622328e2

Next question: what happened to the thread?

**Comment by suztomo** [comment]
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html#newCachedThreadPool() says:

> Threads that have not been used for sixty seconds are terminated and removed from the cache. 

Maybe this is why I didn’t see the thread names in the thread dump.

Next question: why had the thread been idle for 60 seconds (without counting down the latches)?

**Comment by sanjaypujare** [comment]
> Maybe this is why I didn’t see the thread names in the thread dump.
> 
> Next question: why had the thread been idle for 60 seconds (without counting down the latches)?

So the [doc for onError](https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/StreamObserver.java#L54) says 

"May only be called once and if called it must be the last method called. In particular if an exception is thrown by an implementation of `onError` no further calls to any method are allowed."

So after processing `onError` you need to re-initiate the RPC for your next `onError` in order for your count-down latch to proceed. But I can't explain the difference in behavior between 1.26 and 1.36 .

**Comment by suztomo** [comment]
Thank you for the document. In the test, the `onError` is the last call for each thread. https://github.com/apache/beam/pull/14474/commits/070550d00c4b8a6aac53008b6214846d16486453#r633667135

**Comment by sanjaypujare** [comment]
Okay, but then you should have another RPC following that which would trigger the next `onError`. And that's the only way the count-down latch will reach zero.

**Comment by suztomo** [comment]
Thanks. I think I'm getting the idea; `onError` may be called once per a gRPC server, not per a StreamObserver.

**Comment by suztomo** [comment]
The test creates 3 tasks. Each task creates a channel, creates the service stub, and calls the `logging` RPC ([link](https://github.com/apache/beam/commit/070550d00c4b8a6aac53008b6214846d16486453#diff-809eab8eefcff8e1fc63dbd8312d781d2087a7c0f08e54cd4570f46d2bafe0c4R153)). 3 tasks, 3 stubs, and 3 RPCs. Therefore now I think the existing test implementation should work.

**Comment by suztomo** [comment]
Given a [bidirectional streaming](https://grpc.io/docs/languages/java/basics/#bidirectional-streaming-rpc) RPC `stub.m()` and `responseObserver` and `requestObserver`

```
StreamObserver<...> requestObserver = stub.m(responseObserver);
```

Is it guaranteed that calling `requestObserver.onError(exception)` invokes `responseObserver`'s `onError()` handler?

**Comment by sanjaypujare** [comment]
> Given a [bidirectional streaming](https://grpc.io/docs/languages/java/basics/#bidirectional-streaming-rpc) RPC `stub.m()` and `responseObserver` and `requestObserver` such that
> 
> ```
> StreamObserver<...> requestObserver = stub.m(responseObserver);
> ```
> 
> Is it guaranteed that calling `requestObserver.onError(exception)` invokes `responseObserver`'s `onError()` handler?

It is a "short-circuit" as described here https://github.com/grpc/grpc-java/issues/7558#issuecomment-724553726. See the whole issue for a detailed discussion of this. If you have any questions/comments regarding the behavior feel free to add them in that issue.

**Comment by suztomo** [comment]
As per the comment,

> Information passed to client's outbound onError() is never transmitted to the server, server side only sees the cancellation. ... The ClientCall.Listener is immediately notified with CANCELLED status including the original cause.

The listener (onError) should be called immediately.

**Comment by suztomo** [comment]
Update: a new fix to the test fixed the problem. (I don't know why it is better; to me it does the same thing)

https://github.com/apache/beam/pull/14833/files/eec26f54c3f811cf3610094da7c442ed6636e7ea#r635504461

If the problem recurs, I will reopen this. @sanjaypujare , thank you for the help.
