### ISSUE TITLE
SdsX509TrustManager throws when encountering unknown SAN type

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#8182]
https://github.com/grpc/grpc-java/blob/e5d0e9d9a8d672fbf16773bbd638cb8a0467e873/xds/src/main/java/io/grpc/xds/internal/sds/trust/SdsX509TrustManager.java#L155-L162

This puts far too strict of restrictions on the SAN, as it prevents using any other types. Instead, unknown types should be ignored.

The method signature of `verifyOneSanInList()` already returns boolean, so it seems this will be easy.

**Comment by sanjaypujare** [comment]
Good catch. Yes a cert can use multiple name-types in its SAN list and we should just ignore the name-types we don't support.
