### ISSUE TITLE
Client Interceptor close not be triggered if call is successful

### ISSUE THREAD

**Issue by jackycdc** [grpc/grpc-java#8187]
I create a client interceptor try to do some clean up task in `onClose(Status status, Metadata trailers)` method once the bi-directional call complete.
What I observed is, `onClose(Status status, Metadata trailers)` will be trigged when call failed (server return an error), but it will not be triggered if call is successful. It looks like `ClientStreamListener.close` not be invoked.
Is there any way I could have opportunity to know bi-directional call complete regardless successful or failed.

Here is my Interceptor:
`public class TestClientInterceptor implements ClientInterceptor {

    @Override
    public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(final MethodDescriptor<ReqT, RespT> method,
                                                               final CallOptions callOptions,
                                                               final Channel next) {
        return new EndpointConsumeClientCall<ReqT, RespT>(next.newCall(method, callOptions)) {

            @Override
            public void start(Listener<RespT> responseListener, Metadata headers) {
                super.start(
                    new ForwardingClientCallListener.SimpleForwardingClientCallListener<RespT>(responseListener) {
                        @Override
                        public void onHeaders(Metadata headers) {
                            super.onHeaders(headers);
                        }

                        @Override
                        public void onClose(Status status, Metadata trailers) {
                            System.err.println("TestClientInterceptor.close");
                            super.onClose(status, trailers);
                        }

                        @Override
                        public void onMessage(RespT message) {
                            super.onMessage(message);
                        }
                    },
                    headers);
            }

            @Override
            public void cancel(@Nullable String message, @Nullable Throwable cause) {
                super.cancel(message, cause);
            }
        };

    }`

**Comment by sanjaypujare** [comment]
Are you sure `onClose(Status status, Metadata trailers)` doesn't get called in case of normal completion? The [documentation](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ClientCall.java#L140) seems to imply it always gets called.

**Comment by jackycdc** [comment]
Yes, I am pretty sure `onClose` not be called. Here is the log I get, the first call is failed, then move to next subchannel.

TestClientInterceptor.interceptCall
picker input list size: 1
key Test channel : 127.0.0.1:50000
TestClientInterceptor.close
------------------
TestClientInterceptor.interceptCall
picker input list size: 3
key OMS channel : 127.0.0.1:50002

there is no "TestClientInterceptor.close" for the second call. The breakpoint is not trigged in IDE for the second call. 
any comments?

**Comment by cfredri4** [comment]
@jackycdc you likely have an issue somewhere. If you have other interceptors in the chain, try removing them.

`onClose` is always called in all my interceptors. e.g.:

```
public class TestClientInterceptor implements ClientInterceptor {
    
    @Override
    public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(final MethodDescriptor<ReqT, RespT> method,
            final CallOptions callOptions,
            final Channel next) {
        return new ForwardingClientCall.SimpleForwardingClientCall<ReqT, RespT>(next.newCall(method, callOptions)) {
            
            @Override
            public void start(Listener<RespT> responseListener, Metadata headers) {
                super.start(
                    new ForwardingClientCallListener.SimpleForwardingClientCallListener<RespT>(responseListener) {
                        @Override
                        public void onHeaders(Metadata headers) {
                            super.onHeaders(headers);
                        }
                        
                        @Override
                        public void onClose(Status status, Metadata trailers) {
                            System.out.println("TestClientInterceptor.close: " + status);
                            super.onClose(status, trailers);
                        }
                        
                        @Override
                        public void onMessage(RespT message) {
                            super.onMessage(message);
                        }
                    },
                    headers);
            }
            
            @Override
            public void cancel(String message, Throwable cause) {
                super.cancel(message, cause);
            }
        };
    }
}
```

Prints:  `TestClientInterceptor.close: Status{code=OK, description=null, cause=null}`

**Comment by jackycdc** [comment]
@cfredri4 Thanks, let me double check it and update here after it. For now, I only have this one customized client interceptor work with gRPC build in retry enabled.

**Comment by jackycdc** [comment]
Thanks
