### ISSUE TITLE
Support for `s390x` (`s390_64`) machine architecture

### ISSUE THREAD

**Issue by joschi** [grpc/grpc-java#8191]
### Is your feature request related to a problem?

The protobuf compiler `protoc` supports a few non-x86 machine architectures such as `aarch64`, `ppcle`, and `s390x` which are not supported by the gRPC plugin `protoc-gen-grpc-java`:
![protoc - supported architectures](https://user-images.githubusercontent.com/43951/118984260-98c48a80-b97d-11eb-9c80-8ea798c8f40d.png)

### Describe the solution you'd like

It would be great if gRPC-Java supported the same machine architectures as Protocol Buffers out of the box.

With `aarch64` there's already a non-x86 architecture supported by gRPC-Java and maybe support for the other machine architectures could be implemented in the same way.

**Comment by sanjaypujare** [comment]
> It would be great if gRPC-Java supported the same machine architectures as Protocol Buffers out of the box.

I suspect it is going to be demand based as opposed to just matching the Protocol Buffers functionality. Is there a pointer to what specific changes are needed to support s390x? You could also contribute a PR to add that support.

**Comment by joschi** [comment]
> Is there a pointer to what specific changes are needed to support s390x? You could also contribute a PR to add that support.

Unfortunately I neither have experience with the s390x architecture nor do I know exactly what would have to be changed specifically in gRPC-Java.

My naive assumption is that a similar approach like the one taken for `aarch64` support might work:
https://github.com/grpc/grpc-java/pull/6441

**Comment by ejona86** [comment]
We tend to have these other architectures be user contributions because we can't test them. So if you contribute a change, at least we know it works for one user.

**Comment by kiwi1969** [comment]
Since sept 2020 grpcjava works on IBM JVM using IBMJSEE2 on S390x with pull #7422

Is the issue here now resolved?

**Comment by ejona86** [comment]
This issue is about protoc binaries for running the build on an s390x machine. With #7422 you can compile on another machine easily and deploy on s390x, but it is still annoying to run protoc as part of the build.

**Comment by ejona86** [comment]
Fixed by #9455
