### ISSUE TITLE
Support for SocketAddress with ChannelCredentials in NettyChannelBuilder

### ISSUE THREAD

**Issue by cfredri4** [grpc/grpc-java#8195]
### Is your feature request related to a problem?
ChannelCredentials is nice. I'm creating channels via SocketAddress and would like to be able to use it.

### Describe the solution you'd like
Support for SocketAddress with ChannelCredentials in NettyChannelBuilder. Have made pull request #8194 

### Describe alternatives you've considered
Not opening pull request #8194 😉

**Comment by ericgribkoff** [comment]
Fixed by https://github.com/grpc/grpc-java/pull/8194 (thanks!)
