### ISSUE TITLE
How to enabled Netty ChannelHandlers that provide JDK Flight Recorder events

### ISSUE THREAD

**Issue by klaraward** [grpc/grpc-java#8197]
In https://github.com/netty/netty/pull/9777, I've been working on JDR Flight Recorder (JFR) events for Netty, mainly be creating a new channel handler.
What would be a good way to easily enable this for users of gRPC?

**Comment by klaraward** [comment]
Ping @ejona86

**Comment by ejona86** [comment]
Does enabling it via system property sound fair?

**Comment by ejona86** [comment]
The biggest question is whether this functionality needs to be enabled without a code change when wanted. That is, whether it should be off most of the time to reduce resource usage and when you need it you turn it on. Or whether it is just on all the time for users that are interested.

**Comment by klaraward** [comment]
We will probably want to enable it with (typesafe) config from our end, so being able to enable it from code would work better for us.

**Comment by ejona86** [comment]
Okay, then the worst-case solution is to add an API to NettyChannelBuilder to enable the handler. Although this handler we want to be close to the network, which does go against the normal way of things. We can either have [WBAEH add it](https://github.com/grpc/grpc-java/blob/087d7bc7d5a6127deffe54cfa9f184e4e2eda218/netty/src/main/java/io/grpc/netty/WriteBufferingAndExceptionHandler.java#L59) with [values passed from NettyClientTransport](https://github.com/grpc/grpc-java/blob/087d7bc7d5a6127deffe54cfa9f184e4e2eda218/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L250), or we put the adding logic in a ProtocolNegotiator (that delegates to the real negotiator). A ProtocolNegotiator is how we add handlers like this normally, but those handler normally provide some value in the handshake. I'm leaning toward the protocol negotiator.

We do this sort of "delegating" protocol negotiator a couple places, but the [HTTP CONNECT proxy support](https://github.com/grpc/grpc-java/blob/087d7bc7d5a6127deffe54cfa9f184e4e2eda218/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L706-L710) is probably the simplest that I can show you. It will be some annoying boilerplate, but won't be technically difficult.

**Comment by klaraward** [comment]
Thanks for looking into how to enable this, have not had much time to work on this lately but will get to it 👍

**Comment by leikang123** [comment]
> 在[netty/netty#9777 中](https://github.com/netty/netty/pull/9777)，我一直在为 Netty 处理 JDR Flight Recorder (JFR) 事件，主要是创建一个新的通道处理程序。
> 为 gRPC 用户轻松启用此功能的好方法是什么？
I need to customize the Netty API and enable it on the channel. Can I try it?

**Comment by ejona86** [comment]
The Netty change is not yet committed and we'll need to upgrade Netty after the release, so it seems this is still a ways out. Let's close this for the while and reopen (if necessary) when things get closer. You can comment if you have more questions and we can reopen.
