### ISSUE TITLE
Can't get hello-world-client to connect

### ISSUE THREAD

**Issue by jdavies** [grpc/grpc-java#8199]
I just cloned the project according to the docs in the official quick start guide. I can start the hello-world-server just fine
```
jeffdavies@jdavies-rmbp16 examples % ./build/install/examples/bin/hello-world-server
Listening for transport dt_socket at address: 5005
May 24, 2021 10:24:44 AM io.grpc.examples.helloworld.HelloWorldServer start
INFO: Server started, listening on 50051
```

I then open a second terminal window on my mac and execute the command to start the client. As you can see I get an ```Address already in use``` message. Any idea what I'm doing wrong? I have tried turning off my firewall also, just in case. Same results.

```
jeffdavies@jdavies-rmbp16 examples % ./build/install/examples/bin/hello-world-client
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
jeffdavies@jdavies-rmbp16 examples % java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

**Comment by sanjaypujare** [comment]
It's the JDWP listener socket conflict. Looks like you are using the same port for server and client. Can you use a different port number for the client? Check this out https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/introclientissues005.html to specify a port number

**Comment by jdavies** [comment]
Thanks. I think its important to note that these port numbers are the ones directly from the GitHub project, not numbers I choose. If the port numbers are the root cause, I would ask the gRPC maintainers to fix the hello world app, since noobs like me will expect it to work out of the box. :)

**Comment by sanjaypujare** [comment]
Let me clarify: the port numbers for JDWP are not mentioned in the grpc example docs. These must have been set by you as the default options using JAVA_OPTS (or similar) for all your Java build/run commands. The option looks like this

```
-Xrunjdwp:transport=dt_socket,address=8888,server=y,suspend=y
```

JDWP is for remote debugging of Java apps. I don't suppose you want to enable that option for the grpc hello world program.

**Comment by sanjaypujare** [comment]
Can you please check your JAVA_OPTS env variable? The use of JDWP is happening because of your preset env variable and not because of our docs/apps. Closing for now. Pls comment and we can reopen

**Comment by jdavies** [comment]
Yep, you're right. My JAVA_OPS declare 
```
-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
```

And that port must have been being used by another system at the time. After a cold start, it is working fine. Thank you for your help!
