### ISSUE TITLE
GRPC Interceptor

### ISSUE THREAD

**Issue by No-Silver-J** [grpc/grpc-java#8203]
Is there an example of a GRPC Interceptor to uniformly handle things like exceptions and so on

**Comment by ericgribkoff** [comment]
This type of question would be better suited for discussion on the [grpc-io mailing list](https://groups.google.com/g/grpc-io), with more details about what exactly you mean by uniformly handling things. But you can also check out https://github.com/salesforce/grpc-java-contrib/tree/master/contrib/grpc-contrib/src/main/java/com/salesforce/grpc/contrib/interceptor, which looks like it may not have been updated in a while but contains a number of examples of different interceptors, along with the examples in the grpc-java repository itself.
