### ISSUE TITLE
Xds interop client hiccups with invalid EDS + "XdsUpdateClientConfigureService.Configure"

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc-java#8213]
### What version of gRPC-Java are you using?

v1.37.1

### What is your environment?

PSM K8s framework

### What did you expect to see?

The xDS client constantly sends RPC with or without `XdsUpdateClientConfigureService.Configure`.

### What did you see instead?

After received `XdsUpdateClientConfigureService.Configure`, the client seems stopped sending any traffic, and there isn't any error log.

This behavior only occur when TD sends several empty EDS update and EDS update without IP before sending valid EDS. If the TD resources exist for longer period of time, there won't be any problem.

### Steps to reproduce the bug

1. Create new set of TD resources;
2. Wait for the xDS config to populate, and a client channel become READY;
3. According to client logs, the RPCs status are OK;
3. Invoke `XdsUpdateClientConfigureService.Configure`;
4. Invoke `LoadBalancerStatsService.GetClientStats` to get an RPC distribution;
4. All RPCs in the LoadBalancerStatsResponse appears to be failed.

Critical log lines:

```
I0526 13:01:10.242523 139747633039168 grpc.py:59] RPC XdsUpdateClientConfigureService.Configure(request=ClientConfigureRequest({'types': ['EMPTY_CALL']}), timeout=5, wait_for_ready=True)
I0526 13:01:10.296534 139747633039168 grpc.py:59] RPC LoadBalancerStatsService.GetClientStats(request=LoadBalancerStatsRequest({'numRpcs': 50, 'timeoutSec': 1200}), wait_for_ready=True, timeout=1200)
I0526 13:01:12.336451 139747633039168 xds_url_map_testcase.py:386] Received LoadBalancerStatsResponse from test client 10.88.2.55:
{
  "numFailures": 50
}
```

Full log: https://gist.github.com/lidizheng/caa52b4870b2d9d9ad66402acb7653fd

Client log:

![image](https://user-images.githubusercontent.com/7394928/119727329-01e94980-be27-11eb-9d73-e746000ff199.png)

**Comment by dapengzhang0** [comment]
@lidizheng What is `TestEmptyCallToAlternativeBackends` doing? Can you share its code?

Is the problem still there in the latest version of grpc?

**Comment by lidizheng** [comment]
I have made our test framework more tolerant, so I haven't watch for this behavior for a while. Let's close it until there is a new case.
