### ISSUE TITLE
Can gRPC ensure client receive at most one response for each request in simple RPC ?

### ISSUE THREAD

**Issue by aaron-ai** [grpc/grpc-java#8220]
As I mentioned above. If I disable auto retry in client, can gRPC ensure client receive at most one response for each request in simple RPC ?

**Comment by sanjaypujare** [comment]
With auto retry gRPC will retry the request so regardless of that one should always get at most one response for unary or client-streaming RPCs. See [this](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L159) .
