### ISSUE TITLE
Endless empty message were sent by Netty server and caused OOM.  

### ISSUE THREAD

**Issue by MingningShao** [grpc/grpc-java#8223]
> version: 1.11.0

> problem: lots of empty message(length=0) sent by Netty Server and caused OOM.

> Logs:

_OUTBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=2147483647, INITIAL_WI
OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
INBOUND SETTINGS: ack=false settings={HEADER_TABLE_SIZE=0, ENABLE_PUSH=0, INITIAL_WI
OUTBOUND SETTINGS: ack=true
INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=2147418112
INBOUND HEADERS: streamId=1 headers=GrpcHttp2RequestHeaders[:path: /istio.mcp.v1alph
INBOUND DATA: streamId=1 padding=0 endStream=false length=949 bytes=00000000260a0012
INBOUND SETTINGS: ack=true
OUTBOUND HEADERS: streamId=1 headers=GrpcHttp2OutboundHeaders[:status: 200, content-
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=861 bytes=00000003010ac90
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=5716 bytes=000000164f0aed
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=15042 bytes=0000003a690a8
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=79 bytes=000000004a0a1753
INBOUND DATA: streamId=1 padding=0 endStream=false length=148 bytes=000000004f0a0012
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=79 bytes=000000004a0a1753
INBOUND DATA: streamId=1 padding=0 endStream=false length=90 bytes=00000000550a00122
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=84 bytes=000000004f0a1753
INBOUND DATA: streamId=1 padding=0 endStream=false length=263 bytes=00000000550a0012
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=91 bytes=00000000560a1753
INBOUND DATA: streamId=1 padding=0 endStream=false length=61 bytes=00000000380a00122
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=83 bytes=000000004e0a1753
INBOUND DATA: streamId=1 padding=0 endStream=false length=68 bytes=000000003f0a00122
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=83 bytes=000000004e0a1753
INBOUND DATA: streamId=1 padding=0 endStream=false length=60 bytes=00000000370a00122
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=65536 bytes=0000012d6b0a9
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=23350 bytes=5f3336350a160
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=
OUTBOUND DATA: streamId=1 padding=0 endStream=false length=0 bytes=_

>Dose it a bug or wrong usage ?

> What happened ?

**Comment by ejona86** [comment]
This looks to be the same as https://stackoverflow.com/questions/67781875/netty-server-send-endless-empty-messagelength-0-and-caused-oom

As I said on that question, this looks like a bug, but 1.11 is too old for us to investigate. Please upgrade and see if the bug continues.

**Comment by ejona86** [comment]
If the issue continues after upgrading to a newer version, post a comment and we can reopen.
