### ISSUE TITLE
Grpc delay in sending response after onNext is called

### ISSUE THREAD

**Issue by nimit95** [grpc/grpc-java#8232]
I used APM to trace my grpc request. In each of trace the requests I could see the time taken by actual computation and the overhead of the grpc was the same. Concretely, my application is taking 1-1.5ms for computation, while the grpc's overhead  seems to be 2-3 ms

I am trying to figure out the reason for the same. I enabled the debug logs and found this error 
1. [nioEventLoopGroup-3-3] DEBUG io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler  - [id: 0xe88baa10, L:/0:0:0:0:0:0:0:1:5000 ! R:/0:0:0:0:0:0:0:1:59386] Sending GOAWAY failed: lastStreamId '1', errorCode '2', debugData 'Connection reset by peer'. Forcing shutdown of the connection.
java.io.IOException: Broken pipe
I don't think I am doing anything in the code so that such an error may appear. I do some computation and then call the onNext method. How can I debug the reason further?

2.For the server I am adding the following to my server -
`               .bossEventLoopGroup(bossGroup)
                .workerEventLoopGroup(workerGroup)
                .executor(Executors.newFixedThreadPool(32))`
  Is there a documentation around how each might affect the times before and after rpc call execution.

3. If I am doing some heavy computational work before onNext, is there any different strategy that I can use. Currently, just doing the work and then calling onNext with response.

**Comment by sergiitk** [comment]
Hey @nimit95!

Regarding  grpc overhead measurement with APM traces. Could you clarify two things: (a) was the JVM warmed up for the benchmark? (b) What's the latency between the server and the client?

1) Re: DEBUG `Sending GOAWAY failed` - this is normal. It's a DEBUG level message
2) The `bossEventLoopGroup`'s only job is to `accept()` new connections. The second one, `workerEventLoopGroup`, handles the traffic of the accepted connection once the boss accepts the connection and registers the accepted connection to the worker. These are specific to Netty, here's [the docs](https://netty.io/wiki/user-guide-for-4.x.html#writing-a-discard-server). Here's a [good explanation](https://stackoverflow.com/a/42422045/11697987) of the executor, and how it plays with `workerEventLoopGroup`. And there's a decent breakdown in this grpc.io group:
> There are three main threadpools that gRPC Java uses in Server mode:
> 
> * Boss Event Loop Group  (a.k.a. bossEventLoopGroup() )
> * Worker Event Loop Group ( a.k.a. workerEventLoopGroup() )
> * Application Executor (a.k.a. executor() )
> 
> The Boss group can be the same as the worker group.  It's purpose is to accept calls from the network, and create Netty channels (not gRPC Channels) to handle the socket.   Effectively, this is the thread pool that calls listen() and accept().   
> 
> Once the Netty channel has been created it gets passes to the Worker Event Loop Group.  This is the threadpool dedicating to doing socket read() and write() calls.  This is often called the "network thread".   In addition to doing the direct reads and writes, it can also do small amounts of processing, such as turn a collection of bytes into an HTTP/2 request, or do SSL / TLS encryption.  The main thing to know about this group is that it must never block.  That is, it cannot call wait(), or sleep(), or await results from a Future, or things like that.  The reason is that doing this prevents the worker thread (the "event loop") from servicing other requests.
> 
> 
> The last thread group is the application executor, also called the "app thread".  This is where the gRPC stubs do their main work.  It is for handling the callbacks that bubble up from the network thread.  For example, when a packet comes in, the worker thread decrypts it, decodes the HTTP/2 code, and then notifies the app thread that data has arrived.  It immediately goes back to doing other network work.  The App thread notices that there is data available, and converts the data into (usually) a Protobuf, and then invokes your stub.   
> 
> Note that the Application executor could have no threads at all.  This would make the network thread immediately do the work of handling the request.   On the builder this is the directExecutor() function.   The reason for using this is that it saves a thread hop from worker event loop to the app thread, or about 15 microseconds.  In very latency sensitive environments this is a good idea.  However, it makes it very easy to accidentally do blocking work, which is deadlock prone.   It is rarely correct to do.
> 
> 
> As for usages:   Most people should use either reuse the same boss event loop group as the worker group.   Barring this, the boss eventloop group should be a single thread, since it does very little work.  For the app thread, users should provide a fixed size thread pool.  By default, we use an unbounded cached threadpool, but this is just for safety.  It is not the most efficient, and can be dangerous in some circumstances.  It just happens to be the safest default, given no other information.       
> — https://groups.google.com/g/grpc-io/c/LrnAbWFozb0/m/VYCVarkWBQAJ 
3) Looks like you're doing it right. One thing to watch out for is whether the thread pool size is enough for the amount of processing you do, and if anything gets blocked.

**Comment by nimit95** [comment]
(a) was the JVM warmed up for the benchmark? Yes, it was, from the APM screen I was debugging some 20% taking higher time higher than average

(b) What's the latency between the server and the client? It was small like 1-2ms. But how could this affect the time? Since the workerEventLoopGroup will be doing the write and that would be asynchronous I believe(Since netty is async I/O). 

Thanks a ton for this information! Now I can see the difference between these 3 event groups clearly. 

3.  Now I am thinking there can be scenarios where workerEventLoopGroup will be doing work faster than the executor, hence speed mismatch. Is there anything that I can do to quantify the mismatch?. One experiment I performed was to take a hello world grpc server, and then my server. Load test to see the difference in QPS. 
4. I will experiment with increasing the thread pool size for workers and decreasing the boss level group. I am pretty sure nothing is blocking on the executor thread except the heavy calculation. Is there a way to double-check if the executor thread is getting blocked with anything else? (Might sound basic 😅 )

**Comment by ejona86** [comment]
> from the APM screen I was debugging some 20% taking higher time higher than average

That sounds fairly normal. The average is the average, so of course many will be above the average, especially if there's a small tail. You mentioned 1-1.5ms and 2-3 ms earlier; is that the average numbers or this "20% taking higher time" numbers?

> What's the latency between the server and the client? It was small like 1-2ms. But how could this affect the time?

What specific points in time are you measuring? The client will see any latency caused by the network. What you call "grpc overhead" may partly be "network overhead."

> Sending GOAWAY is fine but the IO Exception after that worried me. Forcing shutdown of the connection. java.io.IOException: Broken pipe

It isn't a concern. It just means that the remote had _also_ closed the TCP connection. The way the code is written, I think a TCP closure can _cause_ the GOAWAY+close log failure you saw. It is normal from our perspective.

> Now I am thinking there can be scenarios where workerEventLoopGroup will be doing work faster than the executor, hence speed mismatch.

This would be quite normal as workerEventLoopGroup only does the HTTP/2 processing whereas the executor is doing the actual application work. Why is this an issue?

**Comment by ejona86** [comment]
Seems like we've provided the information we can with the information provided. If there's more to discuss, comment, and it can be reopened.
