### ISSUE TITLE
Prevent using metadata with invalid keys

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#824]
We should restrict the characters that are permitted in keys, as we have no way to send many characters (like colon, unicode, etc).

**Comment by johnbcoughlin** [comment]
i'll pick up this one, if you have a definitive reference of what characters are valid :)

**Comment by ejona86** [comment]
Heh. So you expect us to know what we want?

I've been discussing with some people here what should be permitted. I think we would be fine with being overly-restrictive and maybe opening it up later.

RFC 7230 §3.2 defines a field-name to be a token. A token is defined in §3.2.6:
```
                                          ...  Delimiters are chosen
from the set of US-ASCII visual characters not allowed in a token
(DQUOTE and "(),/:;<=>?@[\]{}").

  token          = 1*tchar

  tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                 / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                 / DIGIT / ALPHA
                 ; any VCHAR, except delimiters
```

It seems like we should be at least as restrictive as that. I wouldn't mind ALPHA / DIGIT / "-". But let me try to get some agreement over here.

**Comment by ejona86** [comment]
So in talking with people here, nobody really cares. Everyone was fine agreeing to `ALPHA / DIGIT / "-"` (and each person suggested `"_"`, but I convinced them it wasn't really any more useful for a "basic set").  We would want to make it clear we may allow extra characters in the future.

**Comment by ejona86** [comment]
Oh, and FYI: I am pretty certain we are using ":" at least [one place](https://github.com/grpc/grpc-java/blob/572f4332a75367e0d0e1cb096198839b68787670/core/src/main/java/io/grpc/internal/Http2ClientStream.java#L66) that will interfere here. I'm pretty certain any tricks are only used for internal data passing and never sent on the wire (a.k.a., abusing Metadata).

We have two options: 1) don't check for ":" and instead just document that it shouldn't be used; in the future we fix the cases that use it and then start enforcing it, 2) replace the string with a "grpc-" prefix and maybe make it more ugly (e.g., "grpc-status-that-should-only-be-used-internally").

In either case, we only want to limit what is sent. We don't want to error if we receive another character, because they are valid for HTTP/2 and they may be valid for gRPC in the future. The best way to accomplish this seems to be just to limit the [`Metadata.Key` constructor](https://github.com/grpc/grpc-java/blob/572f4332a75367e0d0e1cb096198839b68787670/core/src/main/java/io/grpc/Metadata.java#L464) and throw an exception if an invalid character is used.

**Comment by carl-mastrangelo** [comment]
Another option: Make the restriction on ":" enforced inside the the static "of" Key constructor.  This would allow Key to special case a few psuedo headers internally, and block all outside uses it.

**Comment by ejona86** [comment]
@carl-mastrangelo, said:
> This would allow Key to special case a few psuedo headers internally, and block all outside uses it.

How would internal code be differentiated from outside code? A new package-private factory method? That wouldn't work for `Http2ClientStream`, as it is in a different package. Mark the method as `@Internal`? Yeah, that seems like it would work well.

**Comment by carl-mastrangelo** [comment]
@ejona86 The number of pseudo headers is very limited, they could be public static member variables of Metadata (or Key).  A private constructor could be used to create them.

**Comment by ejona86** [comment]
@carl-mastrangelo, okay. That sounds fine. If they were marked `@Internal`, that would sound fine.

**Comment by johnbcoughlin** [comment]
SG! Thanks for the clarification.

**Comment by ejona86** [comment]
I just updated my comment above. "_" has been added, because C core discovered tests that were using it, and they were expected to be just the tip of the iceberg.

**Comment by ejona86** [comment]
@johnbcoughlin, FYI, we're looking at making a beta release at the end of the week (_maybe_ early next week). If the change isn't done, we may just add documentation and add verification in a patch release.

**Comment by ejona86** [comment]
@zhangkun83 to update docs for beta.. And then assign back to @johnbcoughlin

**Comment by carl-mastrangelo** [comment]
I am changing the assignee to myself, since I need this to move forward with compression.

**Comment by ejona86** [comment]
@carl-mastrangelo, is this done now?

**Comment by carl-mastrangelo** [comment]
@ejona86 99.9% done.  There is still a corner case when using a leading ":" in the key, which we use for authority propagation.  It's probably safe to close this out.
