### ISSUE TITLE
why the protoc-gen-grpc-java  pre-compiled binaries all in the format of exe？

### ISSUE THREAD

**Issue by sunshinelulu** [grpc/grpc-java#8246]
![image](https://user-images.githubusercontent.com/12216518/121285627-4be72a80-c911-11eb-8a25-752b346c444c.png)

i need a protoc-gen-grpc-java pre-compiled binaries for mac os，i see osx but it is in the format of exe？

**Comment by sanjaypujare** [comment]
They are just named as `.exe` but if you run the `file` command on a file you'll see the appropriate file type. e.g.
```
file protoc-gen-grpc-java-1.34.0-osx-x86_64.exe 
protoc-gen-grpc-java-1.34.0-osx-x86_64.exe: Mach-O 64-bit executable x86_64
```

**Comment by ejona86** [comment]
See also https://github.com/grpc/grpc-java/issues/6023#issuecomment-519625487

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
