### ISSUE TITLE
Add timing to QPS Client.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#83]
Currently the Java and C++ versions of the QPS Client allow one to perform a fixed number of calls. When using them for benchmarking I think it would make much more sense if we could tell the client to hit the server for some period of time (i.e. 30 minutes) i.e. `1 million calls` just mean something completely different on GCE, Prod and your local workstation.

WDYT @vjpai . If you agree, I could also come up with a PR for the C++ version.

**Comment by ejona86** [comment]
Should we make an issue on grpc repo for this and reference this issue for details?

**Comment by vjpai** [comment]
So, the C++ QPS test has changed since before and now it already is based
on time rather than # of RPCs. Maybe it should be configurable (right now
it's fixed at 15 seconds of active time)

**Comment by ejona86** [comment]
Configurable makes sense, but if it is already based on time, then it seems this issue is fully resolved. A feature request for making C++ QPS time configurable can be on grpc repo.
