### ISSUE TITLE
Server streaming flow controlling

### ISSUE THREAD

**Issue by gunjasal** [grpc/grpc-java#8320]
Hi,

Questions in brief: 
* Can I apply `manual flow control` in server streaming scenario?
* Can `setOnReadyHandler()` be used in server streaming scenario?

gRPC version
* server: grpc-java 1.34.1

I'm trying to implement server streaming flow control refering to [manual flow control example](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java). And upon description of [`ServerCallStreamObserver.disableAutoRequest()`](http://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#disableAutoRequest--) it is said:
> Swaps to manual flow control where no message will be delivered to StreamObserver.onNext(Object) unless it is `request()` ed.

However as I understand, `disableAutoRequest()` shouldn't be used for server streaming as mentioned in doc:
> ... this method will have no effect. This is true for: ... MethodDescriptor.MethodType.SERVER_STREAMING operations.

so that upon my understanding neither `disableAutoRequest()` nor `request()` shouldn't be used in server streaming scenario. And if my understanding is correct, this means I can't use `manual flow control` in server streaming scenario.

So I read couple of github issues more and found that there was a [guide](https://github.com/grpc/grpc-java/issues/1479#issuecomment-420710220):
> If you avoid calling disableAutoInboundFlowControl(), then you won't need to call request() either. The main piece is setOnReadyHandler() and isReady().

So I was thinking to implement `setOnReadyHandler()`, however `ServerCallStreamObserver.setOnReadyHandler()` has a description:
> On server-side it may only be called during the initial call to the application, before the service returns its StreamObserver.

which I understand this method should be used in _bidi-streaming_ or _client streaming_ scenario only; as server streaming doesn't returns its StreamObserver.

Do I have correct understanding? If not can you provide a short snippet for server streaming flow control?
So far, I've just applied `isReady()` like below:
```
synchronized (streamObserver) {
    ServerCallStreamObserver<V> serverCallStreamObserver = (ServerCallStreamObserver<V>) streamObserver;

    if (!serverCallStreamObserver.isCancelled()) {
        if (serverCallStreamObserver.isReady()) {
            streamObserver.onNext(value);
        } else {
            log.info("isReady failed"); // just to check how many isReady() fails
        }
    }
}
```

Thanks!

**Comment by leikang123** [comment]
I think this is fine. The original application is really good.
Hope the author considers!

**Comment by ericgribkoff** [comment]
> Hi,
> 
> Questions in brief:
> 
> * Can I apply `manual flow control` in server streaming scenario?

Yes, but since there's only one message from the client, there is no back-pressure to _apply_ on the server-side (since only one message, the initial request, is ever received). Instead, the client provides the back-pressure and the server must respect it.  In the terminology of the manual flow control example, the roles of the client and server are swapped: for server-streaming, the client must set up a "back-pressure-aware consumer for the response stream" and the server must set up a 
"back-pressure-aware producer for the response stream".

> * Can `setOnReadyHandler()` be used in server streaming scenario?

Yes (see below)

> 
> gRPC version
> 
> * server: grpc-java 1.34.1
> 
> I'm trying to implement server streaming flow control refering to [manual flow control example](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java). And upon description of [`ServerCallStreamObserver.disableAutoRequest()`](http://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#disableAutoRequest--) it is said:
> 
> > Swaps to manual flow control where no message will be delivered to StreamObserver.onNext(Object) unless it is `request()` ed.
> 
> However as I understand, `disableAutoRequest()` shouldn't be used for server streaming as mentioned in doc:
> 
> > ... this method will have no effect. This is true for: ... MethodDescriptor.MethodType.SERVER_STREAMING operations.
> 
> so that upon my understanding neither `disableAutoRequest()` nor `request()` shouldn't be used in server streaming scenario. And if my understanding is correct, this means I can't use `manual flow control` in server streaming scenario.
> 
> So I read couple of github issues more and found that there was a [guide](https://github.com/grpc/grpc-java/issues/1479#issuecomment-420710220):
> 
> > If you avoid calling disableAutoInboundFlowControl(), then you won't need to call request() either. The main piece is setOnReadyHandler() and isReady().
> 
> So I was thinking to implement `setOnReadyHandler()`, however `ServerCallStreamObserver.setOnReadyHandler()` has a description:
> 
> > On server-side it may only be called during the initial call to the application, before the service returns its StreamObserver.
> 
> which I understand this method should be used in _bidi-streaming_ or _client streaming_ scenario only; as server streaming doesn't returns its StreamObserver.

It can still be used for server-streaming, although I can see why the reference to a returned StreamObserver makes that confusing (under-the-hood, all of unary/client-streaming/server-streaming/bidirectional-streaming are all implemented via a single bidirectional-streaming mechanism, so you can think of server-streaming as implicitly "returning" a no-op stream observer).

> 
> Do I have correct understanding? If not can you provide a short snippet for server streaming flow control?
> So far, I've just applied `isReady()` like below:
> 
> ```
> synchronized (streamObserver) {
>     ServerCallStreamObserver<V> serverCallStreamObserver = (ServerCallStreamObserver<V>) streamObserver;
> 
>     if (!serverCallStreamObserver.isCancelled()) {
>         if (serverCallStreamObserver.isReady()) {
>             streamObserver.onNext(value);
>         } else {
>             log.info("isReady failed"); // just to check how many isReady() fails
>         }
>     }
> }
> ```
> 
> Thanks!

**Comment by gunjasal** [comment]
@ericgribkoff thank you for you reply,

I read your message couple of times and think I got the idea.

Thanks!

**Comment by leikang123** [comment]
You are welcome! Good luck!&nbsp;



发自我的iPhone


------------------ Original ------------------
From: YeongMin ***@***.***&gt;
Date: Fri,Jul 16,2021 3:17 PM
To: grpc/grpc-java ***@***.***&gt;
Cc: leikang123 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [grpc/grpc-java] Server streaming flow controlling (#8320)





 
@ericgribkoff thank you for you reply,
 
I read your message a couple of times and think I got the idea.
 
Thanks!
