### ISSUE TITLE
gRPC Java Server Same StreamId for two different TCP Connections

### ISSUE THREAD

**Issue by abhilash93** [grpc/grpc-java#8321]
**Testing Use Case Java**

- Local gRPC Server on port 4740
- Local gRPC Client1 dialin to 4740
- Local gRPC Client2 dialin to 4740

For client1 after initial handshake (Magic packet, setting) on StreamId=0, StreamId=3 is assigned for RPC calls exchange.
For client2 after initial handshake (Magic packet, setting) on StreamId=0,  same **StreamId=3** is assigned for RPC calls exchange.

I have attached the pcap file screen shot **No.201** data packet from client1 and **No.209** from client2 are using the same streamId=3 on the gRPC java server

**gRPC Java Version**: <grpc.version>**1.27.1**</grpc.version>
**NettyServerBuilder Configs**:
keepAliveTime(appProperties.getMaxConnectionIdleTime(), TimeUnit.SECONDS).permitKeepAliveWithoutCalls(true)

**Is there any option in nettyBuilder to have different streamId for connection from different clients?**

I am thinking due to this some of the client(example: client1)stale TCP connection is not getting closed as client2 is active on streamID=3. Please suggest.

<img width="1187" alt="client1pcap_ss" src="https://user-images.githubusercontent.com/2215140/125325154-9db71200-e30e-11eb-87e5-ce948302aa33.png">
<img width="1375" alt="client2pcap_ss" src="https://user-images.githubusercontent.com/2215140/125325205-ab6c9780-e30e-11eb-8c9b-57609db9a0bd.png">

**Comment by ericgribkoff** [comment]
gRPC uses the HTTP/2 stream ID, and these are unique within a given HTTP/2 session, but not across multiple connections: see https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#stream-identification.

Closing this as I believe the above answers the question fully. If there's anything else to note here, please comment again and I can reopen. Thanks.
