### ISSUE TITLE
Common interface for generated async stub and ServiceImplBase

### ISSUE THREAD

**Issue by idelvall** [grpc/grpc-java#8322]
### Is your feature request related to a problem?
My server has multiple gRPC services running on the same VM. I would like to reuse the same client logic I have build on top of the stubs (higher level methods, error handling, retries, ...) for using in inter-service calls in the server side (within the same VM). 

### Describe the solution you'd like
If the generated gRPC classes for the async stub (client-side) and ServiceImplBase (server-side) would implement the same interface, it would be easier/cleaner for me to create a ServiceLoader for my client code, returning the appropiate implementation depending on the case (client-side based on async stub, server-side based on ServiceImplBase).

I would be happy to contribute to this.

### Describe alternatives you've considered
Using server-side the regular stubs pointing to localhost, but I don't like the unnecessary marshalling and transport involved in it.

**Comment by ericgribkoff** [comment]
cc @ejona86

**Comment by ejona86** [comment]
> If the generated gRPC classes for the async stub (client-side) and ServiceImplBase (server-side) would implement the same interface

We _must not_ use interfaces, as we still support Java 7 and adding a method to an interface breaks existing code. We're interested in adding interfaces for services when we drop Java 7 support, but I don't think we'd do this.

> it would be easier/cleaner for me to create a ServiceLoader for my client code, returning the appropiate implementation depending on the case

Easier than what? It would seem the in-process transport should work well for you needs.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
