### ISSUE TITLE
dependencies conflicts

### ISSUE THREAD

**Issue by lfz757077613** [grpc/grpc-java#8332]
The dependencies of protobuf-java and error_prone_annotations are conflicted as below:
![image](https://user-images.githubusercontent.com/16242100/126191231-6a9fc302-fadc-46cf-a946-dc687575fb00.png)
![image](https://user-images.githubusercontent.com/16242100/126191371-001265a5-b921-4658-be98-b60b5302269b.png)

**Comment by ejona86** [comment]
Can you explain what your screenshots mean and what is wrong with error_prone_annotation 2.4.0 and protobuf-java 3.17.2?

**Comment by ejona86** [comment]
Oh, that is 1.39.0, so is probably because gRPC no longer ensuring dependencyConvergence. Please see the release notes. If you want to continue using dependencyConvergence, you have to manage the fallout on your own. We suggest requireUpperBoundDeps instead.

**Comment by lfz757077613** [comment]
> Oh, that is 1.39.0, so is probably because gRPC no longer ensuring dependencyConvergence. Please see the release notes. If you want to continue using dependencyConvergence, you have to manage the fallout on your own. We suggest requireUpperBoundDeps instead.

Thanks for reply. I have used dependencyManagement to avoid the conflicts. But I think it's not good to force grpc users to manage the dependencies in grpc, especially when users use "grpc-bom" to import the grpc dependency

**Comment by ejona86** [comment]
Dependency management chooses versions; that is fine and seems a bit neither here nor there. What is wrong with using error_prone_annotation 2.4.0 and protobuf-java 3.17.2? As in, why is there red in that screenshot? Those are the versions that would naturally be used by Maven based on the screenshots, as they are higher in the dependency tree and Maven uses a breadth-first search to determine the version to use.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
