### ISSUE TITLE
context time out

### ISSUE THREAD

**Issue by LostZG** [grpc/grpc-java#8335]
I'm creating a blocking stub :

blockingStub = MyGrpc
        .newBlockingStub(channel);
and then I start calling method in a loop:

for (int i=0; i<100; i++) blockingStub..withDeadlineAfter(timeOut, TimeUnit.SECONDS).doSomething();

but i got DEADLINE_EXCEEDED: context timed out   When the timeout period has not expired

**Comment by dapengzhang0** [comment]
Is your code sending the `doSomething()` RPCs part of another grpc service implementation that handles an incoming request? If there is another deadline for the incoming request of the other grpc service, then sending `doSomething()` RPCS while handling that request is executed in a Context with the other deadline. If that deadline expires earlier, then you will see context timed out.

**Comment by LostZG** [comment]
Are you talking about the GRPC timeout delivery?
the params of this grpc service are Array，i try write code like this today:
blockingStub..withDeadlineAfter(timeOut, TimeUnit.SECONDS).doSomething([0,1....,98,99]);
and then i got success. but if i write in a loop like before:
for (int i=0; i<100; i++) blockingStub..withDeadlineAfter(timeOut, TimeUnit.SECONDS).doSomething([i]);
 i still got context timed out .  I think this problem seems to be different from you.

**Comment by dapengzhang0** [comment]
Is your code running under some existing Context? Can you try to print the following debug information before your for loop?

```java
"Current context deadline is: " + Context.current().getDeadline()
```

**Comment by dapengzhang0** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
