### ISSUE TITLE
Does grpc support adding more compression algorithms

### ISSUE THREAD

**Issue by skyguard1** [grpc/grpc-java#8348]
In this issue https://github.com/grpc/grpc-java/issues/1704 discusses the issue of data compression. It seems that grpc does not intend to continue to do more work on data compression, but `Compressor` is used in `MessageFramer.writeCompressed()`, does grpc java encourage or allow the addition of more compression algorithms, such as `brotli` and `zstd` to improve compression performance, or continue to maintain the current compression algorithm without intending to do more work? thanks

**Comment by ejona86** [comment]
The current `Compressor` API can be used to add support for more compressors. Although this is specific to Java and not available in all languages (maybe just Go). That said, I think it was wrong to expose the API, but it hasn't been important enough to fight to remove it or fight to stabilize it.

If you are interested in other algorithms, especially brotli and zstd, I'd suggest you consider a cross-language effort. Brotli and zstd can be interesting for many users. There's a related discussion at https://github.com/grpc/grpc/issues/26460, so I don't think you are alone.

**Comment by skyguard1** [comment]
I understand, so more research is needed if want to add the new compression algorithm, thanks

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
