### ISSUE TITLE
awaitTermination() should throw an exception when start() is not be called

### ISSUE THREAD

**Issue by fredsuvn** [grpc/grpc-java#8349]
### What version of gRPC-Java are you using?
1.39.0
### What is your environment?

Windows10 X64 OracleJDK8
### What did you expect to see?
`server.awaitTermination()` throw an exception when `server.start()` was not called.
### What did you see instead?
`server.awaitTermination()` is valid and block current thread, but the services are not actually start.
### Steps to reproduce the bug
```
io.grpc.Server server = NettyServerBuilder.forPort(6565).addService(new GreeterImpl()).build();
//server.start();
// Server is not started but awaitTermination() still block current thread.
server.awaitTermination();
```

**Comment by ejona86** [comment]
Hmm... interesting. Yeah, it would generally be weird to awaitTermination() on a non-started server. But it isn't completely wrong, as you can start the server (from another thread) and eventually shut it down and awaitTermination() will unblock at that point.

Seems there isn't any situation that awaitTermination() is documented to throw IllegalStateException.

If this were a newer API I would seriously entertain the idea that we should throw, but it isn't immediately clear to me whether we'd want to go with that approach. I can't say we considered it when originally implementing it; the implementation naturally doesn't care that start() hasn't been called, and I don't remember discussing/thinking about it explicitly.

But this is a pretty old API, and that would technically be a breaking change. It seems this problem wouldn't impact many people, and it is possible some users are depending on the behavior. Prohibiting awaitTermination before start just helps make i the case the caller has a bug, but it seems you're going to notice no matter what so the benefit seems low.

We can think about this a bit more, but I expect we won't want to make such a change. Right now it seems like this is only a problem with "I forgot to call start() and wish it was easier to notice that." If this behavior caused a bigger issue for you, please tell us so we can gauge how big of an issue this is.

**Comment by ejona86** [comment]
Initial implementation: aeeebb7cdbdefadcf4e200974e8ef504fae05756
The API is mirroring ExecutorService, but ExecutorService doesn't have a start().

**Comment by ejona86** [comment]
API review:
 * Leave as-is (non-throwing), but document awaitTermination/shutdown/shutdownNow is okay to be called before start(/shutdown) has been called

One interesting thing we realized in the API review was that shutdown() is happy to be called before start(). That is a method that would be more important to throw before awaitTermination(). Yet shutdown also is pretty strongly defined; it immediately shuts down and becomes terminated. This is a thread-safe API, and minimizing the known state when calling the API tends to be advantageous.
