### ISSUE TITLE
Failed to resolve com_google_protobuf_javalite

### ISSUE THREAD

**Issue by electricmind007** [grpc/grpc-java#8353]
### What version of gRPC-Java are you using?
3c24dc6fe1b8f3e5c89b919c38a4eefe216397d3

### What is your environment?

Linux - Redhat 7.7, Java 1.8

### What did you expect to see?
A successful resolution of com_google_protobuf_javalite

### What did you see instead?
 java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip] to /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/com_google_protobuf_javalite/384989534b2246d413dbcd750744faab2607b516.zip: GET returned 404 Not Found
ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/io_grpc_grpc_java/protobuf-lite/BUILD.bazel:1:13: no such package '@com_google_protobuf_javalite//': java.io.IOException: Error downloading [https://github.com/google/protobuf/archive/384989534b2246d413dbcd750744faab2607b516.zip] to /home/jenkins/.cache/bazel/_bazel_jenkins/5179c138f504d5cc88845edd18541adb/external/com_google_protobuf_javalite/384989534b2246d413dbcd750744faab2607b516.zip: GET returned 404 Not Found and referenced by '@io_grpc_grpc_java//protobuf-lite:protobuf-lite'

### Steps to reproduce the bug
When resolving the internal deps, the above issue occurs.

**Comment by ejona86** [comment]
The google/protobuf → protocolbuffers/protobuf redirect broke yesterday, which caused the problem. The redirect has since been fixed by protobuf. Note that newer versions of grpc reference protocolbuffers/protobuf directly so were not impacted.

Cross-linking to https://github.com/protocolbuffers/protobuf/issues/8840

**Comment by ejona86** [comment]
If this is still a problem, comment and I'll reopen. But things are working for me today.
