### ISSUE TITLE
xds: NPE on server-side when bootstrap lacking server_listener_resource_name_template

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#8373]
```
Exception in thread "main" java.lang.NullPointerException
	at io.grpc.xds.XdsClientWrapperForServerSds.start(XdsClientWrapperForServerSds.java:137)
	at io.grpc.xds.internal.sds.ServerWrapperForXds.start(ServerWrapperForXds.java:116)
	at io.grpc.examples.helloworldxds.XdsHelloWorldServer.main(XdsHelloWorldServer.java:72)
```

I used an old bootstrap generator, so it didn't have `xds_v3` as well and there was no log message.

CC @YifeiZhuang

**Comment by sanjaypujare** [comment]
The PR https://github.com/grpc/grpc-java/pull/8333 has a fix for this but this probably needs to be fixed in 1.40 and backported to previous couple of releases.

**Comment by YifeiZhuang** [comment]
It looks we should only allow `xds_v3`. PR https://github.com/grpc/grpc-java/pull/8333 looks correct behaviour: validates during server start. It would notify `.onNotServing` with `Status.UNAVAILABLE` if not v3 or empty listenerTemplate.

**Comment by sanjaypujare** [comment]
Yes. I will create a PR for master, 1.40.x, 1.39.x and 1.38.x

**Comment by ejona86** [comment]
> It would notify .onNotServing with Status.UNAVAILABLE if not v3 or empty listenerTemplate.

Since this is a permanent failure, it seems throwing an IOException would be a bit better. But just logging to not serving is okay and gets the job done.
