### ISSUE TITLE
It is strongly recommended to reduce some internal classes. The code looks too chaotic

### ISSUE THREAD

**Issue by brucelwl** [grpc/grpc-java#8384]
It is strongly recommended to reduce some internal classes. The code looks too chaotic,

for example

https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java

**Comment by ejona86** [comment]
What do you mean "reduce"? Do you mean "simplify"?

ManagedChannelImpl is one of the most "noisy" classes as it is the glue of the majority of the API. It's essentially the backbone. There's some smaller changes I'd like to do to make certain data flows more clear, but the amount of code and complexity would essentially remain the same. Some things could move to a different file, but the overall complexity would remain the same.

No concrete suggestions were made, so closing. If you have a concrete suggestion, comment and we can reopen.

**Comment by brucelwl** [comment]
Yes, I just think the same as you, some things could move to a different file, this will not make a java file very bloated, and may be more convenient for others to view the source code!
