### ISSUE TITLE
Method grpc.health.v1.Health/Watch is unimplemented

### ISSUE THREAD

**Issue by guoyucheng** [grpc/grpc-java#8385]
server 
```java
HealthStatusManager healthStatusManager = new HealthStatusManager();
serverBuilder.addService(healthStatusManager.getHealthService());
healthStatusManager.getHealthService();
```
client
```java
  Map<String, Object> configMap = new HashMap<String, Object>() {{
            put("healthCheckConfig", new HashMap<String, Object>() {{
                put("serviceName", "");
            }});
        }};
  builder.defaultServiceConfig(configMap);
```

```
八月 05, 2021 6:01:24 下午 io.grpc.ChannelLogger log
非常详细: [Subchannel<3>: (User.ZkNameResolverProvider)] READY
八月 05, 2021 6:01:24 下午 io.grpc.ChannelLogger log
非常详细: [Subchannel<3>: (User.ZkNameResolverProvider)] CONNECTING: Starting health-check for ""
2021-08-05 18:01:29.677 ERROR 24433 [        ] --- [ault-executor-0] .g.p.s.HealthCheckingLoadBalancerFactory 419    : Health-check with [[[/10.220.8.xx:50052]/{}]] is disabled. Server returned: Status{code=UNIMPLEMENTED, description=Method grpc.health.v1.Health/Watch is unimplemented, cause=null}
八月 05, 2021 6:01:29 下午 io.grpc.ChannelLogger log
详细: [Subchannel<3>: (User.ZkNameResolverProvider)] Health-check disabled: Status{code=UNIMPLEMENTED, description=Method grpc.health.v1.Health/Watch is unimplemented, cause=null}
八月 05, 2021 6:01:29 下午 io.grpc.ChannelLogger log
非常详细: [Subchannel<3>: (User.ZkNameResolverProvider)] READY (no health-check)
八月 05, 2021 6:01:29 下午 io.grpc.ChannelLogger log
非常详细: [Channel<1>: (UserGrpc.ZkNameResolverProvider)] Entering READY state with picker: ReadyPicker{list=[SubchannelImpl{delegate=Subchannel<3>: (User.ZkNameResolverProvider)}]}
```

![image](https://user-images.githubusercontent.com/4794514/128357057-9ffb9de0-9bac-4548-8755-95a34bfada85.png)

why grpc.health.v1.Health/Watch is unimplemented ?

**Comment by dapengzhang0** [comment]
Seems you set default service config without round-robin load balancing policy to channel. Did you call `defaultLoadBalancingPolicy()` as well?

Did you call `disableServiceConfigLookUp()`? If not, the default service config can be overridden by any service config in the name resolution result. It seems your channel chose round-robin load balancing policy, so does that mean that your name resolution result contains a service config with round-robin policy? If that is the case, your default service config is overridden, and the `healthCheckConfig` in it is gone.

**Comment by guoyucheng** [comment]
> Seems you set default service config without round-robin load balancing policy to channel. Did you call `defaultLoadBalancingPolicy()` as well?
> 
> Did you call `disableServiceConfigLookUp()`? If not, the default service config can be overridden by any service config in the name resolution result. It seems your channel chose round-robin load balancing policy, so does that mean that your name resolution result contains a service config with round-robin policy? If that is the case, your default service config is overridden, and the `healthCheckConfig` in it is gone.

Thanks  i use  disableServiceConfigLookUp()  now it work
