### ISSUE TITLE
large file transfer with gRPC

### ISSUE THREAD

**Issue by manor-parmar** [grpc/grpc-java#8389]
I have C++ gRPC client and Java gRPC server. 
Is gRPC right choice to transfer large files (>50 megabytes) with client side streaming ? 
Why I am asking this is because gRPC is meant for small message transfer between microservices, right ?

Do we have any comparison between HTTP/1.1 multipart upload vs gRPC streaming in terms of performance and RTT ?

**Comment by dapengzhang0** [comment]
gRPC streaming does not natively support multipart upload or resume from breakpoint, unless you implement it on the application level/small messages level or there is some library supporting it. So it might not be a good choice for large file transfer on an unreliable network. You can also post a discussion topic on [grip.io community](https://groups.google.com/g/grpc-io) if you did not do so, as it is not Java language specific.
