### ISSUE TITLE
How do I specify a specific IP address for the GRPC server

### ISSUE THREAD

**Issue by youyuancode** [grpc/grpc-java#8419]
example：add ip
server = ServerBuilder.forPort(port)
               .ip(?)
                .addService(greeterServer)
                .addService(invokeServer)
                .executor(executor)
                .build()
                .start();

**Comment by ejona86** [comment]
There isn't a stable API to do so. You need to pass an `InetSocketAddress` to [`NettyServerBuilder.forAddress()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#forAddress-java.net.SocketAddress-io.grpc.ServerCredentials-).

**Comment by youyuancode** [comment]
ok
