### ISSUE TITLE
how to set the value of method "setSampledToLocalTracing" when code generated

### ISSUE THREAD

**Issue by brucelwl** [grpc/grpc-java#8424]
How to configure the value of dynamically generated code ``setSampledToLocalTracing(false)`` to be false

![image](https://user-images.githubusercontent.com/13413715/130126688-e81a396e-a989-406e-a03f-55eccde0ecdf.png)

here is my proto file
```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.bruce.grpc.proto.service";
option java_outer_classname = "RpcServiceProto"; 

message HelloRequest {
  string greeting = 1;
  repeated bytes data = 2;
  string serial_type = 3;
}

message HelloResponse {
  string reply = 1;
  repeated bytes data = 2;
  string serial_type = 3;
}

service HelloService {
  rpc SayHello(HelloRequest) returns (HelloResponse);
}

```

**Comment by sanjaypujare** [comment]
> How to configure the value of dynamically generated code `setSampledToLocalTracing(false)` to be false

It looks like it is hardcoded to `true` by the java plugin https://github.com/grpc/grpc-java/blob/master/compiler/src/java_plugin/cpp/java_generator.cpp#L445 so unfortunately it is not configurable (@ejona86 any ideas?)

What's the reason you want to set it to `false`? May be there are other ways?

**Comment by ejona86** [comment]
Why do you want `setSampledToLocalTracing(false)`? The reason for that API is to avoid unbounded sampling of dynamically-determined methods. Because there is a limited amount of generated code, there are a limited number of methods that could be sampled.

**Comment by brucelwl** [comment]
Maybe I misunderstood. I want to turn off sampling completely

**Comment by sanjaypujare** [comment]
> Maybe I misunderstood. I want to turn off sampling completely

Or do you want to turn off tracing? Turning off sampling could also mean all RPCs are traced.

**Comment by ejona86** [comment]
setSampledToLocalTracing doesn't enable tracing itself. Typically you "don't include grpc-census as a runtime dependency" and there won't be any tracing.

**Comment by brucelwl** [comment]
thanks
