### ISSUE TITLE
API to eagerly send headers from a service

### ISSUE THREAD

**Issue by andrewparmet** [grpc/grpc-java#8434]
I'd like to conditionally send headers from my server to a client at the beginning of a call. I have constructed an interceptor that will invoke `ServerCall.sendHeaders()`, and the client does receive those headers. My confusion is that after sending the headers the call will always immediately fail when the server tries to send a message, since `ServerCallStreamObserverImpl` always tries to send headers again in its implementation of `onNext()`:

```java
// ...
if (!sentHeaders) {
  call.sendHeaders(new Metadata());
  sentHeaders = true;
}
call.sendMessage(response);
```

I've solved this by returning a "header-dropping" forwarding ServerCall from my interceptor:
```java
public class MetadataSendingInterceptor implements ServerInterceptor {
  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
    ServerCall<ReqT, RespT> call,
    Metadata headers, 
    ServerCallHandler<ReqT, RespT> next
  ) {
    if (shouldSendHeaders()) {
      call.sendHeaders(customResponseHeaders());
      return next.startCall(
          new SimpleForwardingServerCall<ReqT, RespT>(call) {
            @Override public void sendHeaders(Metadata headers) {
              // these headers should always be empty per the snippet above
            }
          },
          headers
      );
    } else {
      return next.startCall(call, headers);
    }
  }
}
```

Is this the recommended practice or is there a way to indicate that gRPC should not proceed to attempt to send back empty headers?

I also realize that I'll have to consolidate any future interceptors that want to send back metadata as well since obviously any downstream attempts to send metadata will fail with or without this no-op - either the call will terminate or I'll be dropping it.

Thanks!

**Comment by sanjaypujare** [comment]
Take a look at the example code https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/header/HeaderServerInterceptor.java .  The code there can be modified for your use-case as:

```
  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
      ServerCall<ReqT, RespT> call,
      final Metadata requestHeaders,
      ServerCallHandler<ReqT, RespT> next) {
    return next.startCall(new SimpleForwardingServerCall<ReqT, RespT>(call) {
      @Override
      public void sendHeaders(Metadata responseHeaders) {
        if (shouldSendHeaders()) {
          responseHeaders.merge(customResponseHeaders());
        }
        super.sendHeaders(responseHeaders);
      }
    }, requestHeaders);
  }
```

The above is the right way to do it.

**Comment by andrewparmet** [comment]
Interesting - so there's no intended way to eagerly respond with headers before sending the first message from the server to the client?

**Comment by sanjaypujare** [comment]
The code is doing exactly that. There is no `sendMessage` anywhere in the code but only `sendHeaders` is overridden to add (merge) your customHeaders and *then* calls `super.sendHeaders(responseHeaders)` as opposed to `call.sendHeaders()` which is what your code was doing.

**Comment by andrewparmet** [comment]
Right, but won't the application need to call `onNext()` with a response in order to trigger the snippet I pasted which actually does call `sendHeaders()`? Rephrased slightly, my question is asking whether it's possible for a client to receive headers without the server needing to send a response message at all, or if I need to modify my protocol to move that information from headers to the first response message.

**Comment by sanjaypujare** [comment]
Oh sorry I missed your initial comment where you pasted the snippet from `ServerCallStreamObserverImpl`.

From your 2 messages:
> ... if I need to modify my protocol to move that information from headers to the first response message.

> ...there's no intended way to eagerly respond with headers before application logic sends the first message from the server to the client?

Any application data should really be sent as response message(s) instead of as Metadata. The Metadata should really be about "metadata" of the call or the transport and so on.

In terms of timing `ServerCallStreamObserverImpl` sends the headers and the first response message together and I don't know if that's by design (e.g. mandated by http2 spec). Let me do some digging and I'll update this issue.

**Comment by sanjaypujare** [comment]
Okay so I discussed this internally and there is no absolute requirement to send the headers and the first response together so your code might be a way to do it. However I would like to know what the use case is. If that is something common it would be nice for gRPC to provide hooks for an application to trigger sending headers. Can you give details of your use case?

**Comment by andrewparmet** [comment]
I've done some digging in my code as well since it was an inconsistency between gRPC servers that surfaced this issue. One server is running grpc-kotlin, and it [_does_ send metadata eagerly](https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/ServerCalls.kt#L214). The other is running grpc-java and does not, which was an issue when I was using the same client code to interact with both - I had assumed I'd receive metadata eagerly always.

My use case is that the server needs to verify client configuration before continuing the call. The client sends its configuration via a header, and then the server responds with a signature via a header that the client will use in all future calls over that channel.

I assumed with eager headers that I'd get the signal about the client's configuration validity before the server might have any response to send back. There can be periods of many minutes between the beginning of the call and the first "business logic" response, and I want to get the client into a valid state as quickly as possible so that it can send valid requests, which depend on the signature.

I could pull that exchange into the protocol, but I wanted to keep the application business logic as simple as possible given the natural complexity of bidi streams (Have I received the config yet? Where does that handling code live, since it's cross-cutting with regard to business logic?), and felt that the exchange did match the notion of "metadata" provided by headers.

**Comment by sanjaypujare** [comment]
> Thanks for looking into it! I've done some digging in my code as well since it was an inconsistency between gRPC servers that surfaced this issue. One server is running grpc-kotlin, and it [_does_ send metadata eagerly](https://github.com/grpc/grpc-kotlin/blob/master/stub/src/main/java/io/grpc/kotlin/ServerCalls.kt#L214). The other is running grpc-java and does not, which was an issue when I was using the same client code to interact with both - I had assumed I'd receive metadata eagerly always.

Yes one of the things I discovered is that not all languages have the same behavior. Especially in case of sending headers - Java seems to be alone in not sending headers early or not giving any control to the application.

> 
> My use case is that the server needs to verify client configuration before continuing the call.

So is that for *each* call or just first call on the connection? 

> The client sends its configuration via a header, and then the server responds with a signature via a header that the client will use in all future requests over that channel.

You say "channel" but note that a channel is different from a (TCP) connection which is different from an (http2) stream. Your description implies that the signature is used by the client only on all future "request messages" in the call (i.e. stream) as opposed to all future RPCs on the channel or connection.

> 
> I assumed with eager headers that I'd get the signal about the client's configuration validity before the server might have any response to send back. There can be periods of many minutes between the beginning of the call and the first "business logic" response, and I want to get the client into a valid state as quickly as possible so that it can send valid requests, which depend on the signature.

So your main requirement is that the server needs to be able to send the computed signature ASAP without having to wait for the first application response (which could take several minutes). That makes sense. What I would suggest in this case is for the server application to send an empty/pseudo-empty response just to be able to send the signature in the headers. This first response could be a message indicating an application level acknowledgement of the initial request.

> 
> I could pull that exchange into the protocol, but I wanted to keep the application business logic as simple as possible given the natural complexity of bidi streams (Have I received the config yet? Where does that handling code live, since it's cross-cutting with regard to business logic?), and felt that the exchange did match the notion of "metadata" provided by headers.

Yes, it seems to be the correct use of metadata here.

> The pattern you suggested above (merging metadata) does work - the issue then becomes when `call.sendHeaders()` is called by gRPC internally.

Just want to make sure the signature exists for the lifetime of a call (stream) and not a connection or channel as you implied above

**Comment by andrewparmet** [comment]
Thanks for the confirmation. Interesting to hear about yet other languages - I had only looked into grpc-java and grpc-kotlin since I'm on the JVM.

Sorry, let me be more precise with my language: the signature the client receives is tied to its configuration, which may exist indefinitely. The client persists the signature on disk and it is used for every request for this bidi streaming call, and all subsequent invocations of the call, which are done over the same Channel or subsequent Channels constructed with the same client configuration. Eventually the client's configuration may change, at which point the client will open a new call without a signature and the server will redo the config-signature "handshake" when it receives the call with no signature in the client headers.

You understand our requirement correctly. One of the options we're discussing is exactly what you suggested - to send a blank response to force the signature exchange process from grpc-java. This doesn't change the application logic substantially since we can just ignore the blank message. One day, if grpc-java allows us to eagerly send those headers, we can drop that step. Alternatively we may port that server to grpc-kotlin and get eager header delivery that way.

We're also considering using the snippet from my original post and being careful about sending any future metadata since we would not need to change the protocol.

Do you think we'll ever have the option (or default) of eager header delivery in grpc-java?

**Comment by andrewparmet** [comment]
Now that I think about it, it may make more sense to pull the exchange into a separate unary call.

I also have a secondary purpose for eager header exchange, which is that their receipt is "evidence" that a call is successfully opened in the event that we do wait for those several minutes before the application has a response for them. This use case can also be addressed with the blank first message, either to force headers to be sent or simply to send a first message.

**Comment by ejona86** [comment]
> grpc-kotlin sends headers immediately by default

All implementations should not eagerly send headers by default. This was defined in [the retries gRFC](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#when-retries-are-valid):

> gRPC servers should delay the Response-Headers until the first response message or until the application code chooses to send headers. If the application code closes the stream with an error before sending headers or any response messages, gRPC servers should send the error in Trailers-Only.

That said, as @sanjaypujare mentioned, it'd not be a big deal to add a method to allow force-flushing the headers.

> I could pull that exchange into the protocol, but I wanted to keep the application business logic as simple as possible given the natural complexity of bidi streams

Why not model this configuration handshake as a CallCredential, where you'd do a RPC before the other RPCs just to get this signature? That would be cross-cutting and wouldn't require specific RPC behavior for your service methods. You wanted to put this logic in an interceptor since it was cross-cutting, but requiring every RPC method to eagerly send headers means RPC behavior is changed for this header; that seems like a serious deficiency.

**Comment by sanjaypujare** [comment]
> ...
> You can propose an API for using this option in this issue (or a separate issue) and then it can be discussed.

@andrewparmet are you still interested in pursuing this (since it has been more than a month since we last discussed it)? If you propose an API, we will discuss/debate the API internally and then respond accordingly. If the proposal looks good we will look into a plan to implement the new API based on priority or urgency.

**Comment by andrewparmet** [comment]
I am still interested but put aside the work that depends on this since we had a workaround.

I discovered we're also using header receipt as evidence of establishing a connection with the server to reset an exponential backoff parameter. Is it possible to learn about that connection state in grpc-java without eagerly sending headers from the server? If so, we don't need to send headers eagerly.

If not - and our calls against grpc-kotlin make the assumption that this is a good indicator - then we'd want an API to let us do that from grpc-java.

As far as I know the only place we can interact with the call is from the ServerInterceptor where we can return a custom ServerCall.Listener. Ultimately we want to trigger the headers to be sent when `startCall()` is invoked by ServerImpl in `startWrappedCall()`. I could imagine a new callback method added to ServerCall.Listener:

```java
public abstract void onStart(Metadata headers);
```

in which we can call `sendHeaders(headers)`. If called from `onStart()`, the implementation would have to prevent the call in ServerCalls.ServerCallStreamObserverImpl so that it doesn't attempt to send the headers again.

This change will also interact with grpc-kotlin. As far as I know it uses the same server implementation as grpc-java, and by default its ServerCallHandler will try to send headers again. ServerCallImpl strongly defends against this possibility by throwing an exception if anyone tries to do that, so maybe it has to drop the call instead with a `sentHeaders` flag.

This approach would fix the issue in ServerCalls.ServerCallStreamObserverImpl as well but would look odd in a naive implementation: its own `sentHeaders` flag would be `false`, `sendHeaders(new Metadata())` would be ignored, and then `sentHeaders` would be set to true.

**Comment by sanjaypujare** [comment]
> I discovered we're also using header receipt as evidence of establishing a connection with the server to reset an exponential backoff parameter. Is it possible to learn about that connection state in grpc-java without eagerly sending headers from the server? If so, we don't need to send headers eagerly.

Connection state is at connection level - you mean the call (stream) state for the current call at the client side? You can use `io.grpc.ClientCall.Listener` and receive the state with `onHeaders(Metadata)` when the server has sent (or would have sent) the headers. Looking at https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ClientStreamListener.java#L34 (which is ultimately responsible for calling `ClientCall.Listener.onHeaders`) it says 

"Note that transports are not required to call this method if no header information is received, this would occur when a stream immediately terminates with an error and only `closed(io.grpc.Status, RpcProgress, Metadata)` is called."

This tells me that for non-error cases you would still see the callback `onHeaders()` even if no actual headers were sent which is what you are looking for IIUC.

> 
> If not - and our calls against grpc-kotlin make the assumption that this is a good indicator - then we'd want an API to let us do that from grpc-java.
> 
> As far as I know the only place we can interact with the call is from the ServerInterceptor where we can return a custom ServerCall.Listener. Ultimately we want to trigger the headers to be sent when `startCall()` is invoked by ServerImpl in `startWrappedCall()`. I could imagine a new callback method added to ServerCall.Listener:
> 
> ```java
> public abstract void onStart(Metadata headers);
> ```
> 
> in which we can call `sendHeaders(headers)`. If called from `onStart()`, the implementation would have to prevent the call in ServerCalls.ServerCallStreamObserverImpl so that it doesn't attempt to send the headers again.

Just to clarify the `headers` parameter of your `onStart()` is the headers from the client to the server and the `headers` argument in your `sendHeaders(headers)` is a different value because these are server headers to the client, is that correct?

> 
> This change will also interact with grpc-kotlin. As far as I know it uses the same server implementation as grpc-java, and by default its ServerCallHandler will try to send headers again. ServerCallImpl strongly defends against this possibility by throwing an exception if anyone tries to do that, so maybe it has to drop the call instead with a `sentHeaders` flag.
> 
> This approach would fix the issue in ServerCalls.ServerCallStreamObserverImpl as well but would look odd in a naive implementation: its own `sentHeaders` flag would be `false`, `sendHeaders(new Metadata())` would be ignored, and then `sentHeaders` would be set to true.

Okay. Let me propose this for an internal discussion and see where it goes. Thanks for the propposal.

**Comment by andrewparmet** [comment]
> Connection state is at connection level - you mean the call (stream) state for the current call at the client side?

Yes, I mean call state. This is exactly the issue at hand - headers aren't being sent early enough from grpc-java. We can sit idle until the load balancer rebalances our connection and we'll interpret it as a server-side error. An immediately terminated stream is OK to not send us headers, since we'll get the onError callback and know the call failed.

> ```java
> public abstract void onStart(Metadata headers);
> ```

I actually meant for these to be server headers to be sent to the client since the client headers are already made available via `ServerInterceptor.interceptCall()`. The call would be analogous to `sendHeaders(Metadata headers)`. ServerImpl would call `onStart()` with new metadata just like `sendHeaders()` is today, and the listener would be free to override `onStart()` to merge headers or send them eagerly.

Perhaps that's more than necessary and ambiguous, but I thought it might be necessary if multiple SeverCall.Listeners override the method.

**Comment by sanjaypujare** [comment]
> > Connection state is at connection level - you mean the call (stream) state for the current call at the client side?
> 
> Yes, I mean call state. This is exactly the issue at hand - headers aren't being sent early enough from grpc-java. We can sit idle until the load balancer rebalances our connection and we'll interpret it as a server-side error. An immediately terminated stream is OK to not send us headers, since we'll get the onError callback and know the call failed.

Okay. Without server side changes you won't actually get the indication you want even with the `ClientCall.Listener.onHeaders()` approach I suggested.

> 
> > ```java
> > public abstract void onStart(Metadata headers);
> > ```
> 
> I actually meant for these to be server headers to be sent to the client since the client headers are already made available via `ServerInterceptor.interceptCall()`. The call would be analogous to `sendHeaders(Metadata headers)`. ServerImpl would call `onStart()` with new metadata just like `sendHeaders()` is today, and the listener would be free to override `onStart()` to merge headers or send them eagerly.
> 
> Perhaps that's more than necessary and ambiguous, but I thought it might be necessary if multiple SeverCall.Listeners override the method.

Okay, got it. Will update this after the internal discussion.

**Comment by ejona86** [comment]
It looks like a bug for kotlin about this behavior already exists: https://github.com/grpc/grpc-kotlin/issues/272

**Comment by andrewparmet** [comment]
That feels like the right solution. I wonder how that could be used from the Kotlin implementation given that the `StreamObserver` isn't exposed to be up-cast.

**Comment by ejona86** [comment]
API review notes:
 * Seemed there was a tendency to want to expose Metadata to the application (vs just triggering them happening). Would probably imply someone would ask to send trailers for OK response. Not so bad. But could it also open the door to receive Metadata on client-side stubs?
 * Has complications with server-side unary response optimization where the headers and message can be delayed until trailers (to all go out in one packet)

That second part is subtle, because we currently don't have that optimization on server-side. But we have left it open as an opportunity and we do do it on client-side. We do believe it would provide good performance gains (reduced CPU usage), but it has some implementation trickiness.

We don't really talk about that batching/delaying optimization, since the stubs don't expose any way to notice the difference. This might make what I'm talking about more clear (yes, it is a random unmerged PR): https://github.com/grpc/grpc/pull/15460/files#diff-41c9953d9fe6c8de05c451793d56f85edcec4985f940e02c01b515705ef5bad4R124

But for that reason, we probably only want this `sendHeaders()` API to trigger headers to be sent immediately for streaming RPCs. We don't want to support sending unary response headers eagerly.

@andrewparmet, are you needing this for unary RPCs?

> Is it possible to learn about that connection state in grpc-java without eagerly sending headers from the server?

[`ManagedChannel.getState()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannel.html#getState-boolean-)/`notifyWhenStateChanged()` might be what you are looking for. That tracks whether the channel has a connection and basically communicates the likelihood that sending an RPC has any chance of working.

**Comment by andrewparmet** [comment]
> are you needing this for unary RPCs?

My intent was to use this only for bidirectional streaming RPCs (it has the same utility in server streaming RPCs). My main use case is to see whether the server has accepted the call, which is a long-lived subscription.

A special “accepted” response object can also play this role and doesn’t require any special implementation trickery across languages like it does now, so I have a workaround for the time being (or possibly forever since perhaps that’s the clearer implementation). That response would trigger headers anyways.

I’ll probably pull the complicating issue - the config exchange - into a separate unary call. 

> That tracks whether the channel has a connection

Ultimately we may want to do auth (or circuit-breaking) before considering the call open, so I’m not sure channel state is what we’re after since we’ll be connecting to a proxy. 

Thanks for the update!

**Comment by andrewparmet** [comment]
We're no longer in need of this API. Thanks all.
