### ISSUE TITLE
gRPC exporting TLS keys -supported version combos

### ISSUE THREAD

**Issue by MWoscek** [grpc/grpc-java#8460]
Im following the following guide to export TLS keys for my gRPC traffic:
https://gitlab.com/wireshark/wireshark/-/wikis/How-to-Export-TLS-Master-keys-of-gRPC

But when adding the newWireSharkSslMasterKeyHandler(), the TLS connection fails with a key length error, so adding the  newWireSharkSslMasterKeyHandler()  is causing a corruption of the initial key exchange.
ctx.pipeline().addBefore(ctx.name(), null, SslMasterKeyHandler.newWireSharkSslMasterKeyHandler());

The first question is: what are the actual supported combination versions listed here that support the above guide?:
https://github.com/grpc/grpc-java/blob/master/SECURITY.md

Im using the following combo:
grpc_version = 1.35.0
boringssl_static_version = 2.0.36.Final

**Comment by sergiitk** [comment]
Hey @MWoscek, take a look at the discussion here: https://github.com/grpc/grpc-java/issues/7199.

**Comment by MWoscek** [comment]
I verified the  newWireSharkSslMasterKeyHandler() is getting in the pipeline and executing as I am failing the [if (masterKey.getEncoded().length != 48)] in the WiresharkSslMasterKeyHandler with the "An invalid length master key was provided."

Now I didn't expect to go down this rabbit hole verifying key lengths. 
Anyone run into this?

**Comment by sergiitk** [comment]
I see there's a similar issue here: https://github.com/netty/netty/issues/10957

**Comment by MWoscek** [comment]
@sergiitk 
Thanks! That was the answer as I am now enforcing TLS v1.2 the key len matches the WiresharkSslMasterKeyHandler.  
Also in setting the .protocols("TLSv1.2") for both the Server and Client side for the call to SslContextBuilder, my assumption of boringSSL was inclorrect, the original developers enforced openSSL (.sslProvider(SslProvider.OPENSSL))

I am now logging the master keys:

**Comment by sergiitk** [comment]
Great! Happy this helped.
