### ISSUE TITLE
Overload the equals method of Key

### ISSUE THREAD

**Issue by skw0rm** [grpc/grpc-java#8501]
### What version of gRPC-Java are you using?
Master branch

### What is your environment?

windows

### What did you expect to see?

when call Key.equals, it compare the debugString of Key, but not the memory address.

### What did you see instead?
override the equals method of Key

**Comment by dapengzhang0** [comment]
@skw0rm Which Key are you referring to? `CallOptions.Key`, `Context.Key`, or `Attributes.Key`. In general, these Keys are identified by its reference. We can have two totally different Key instances with `debugString`s that happen to be the same.

On the contrary, `Metadata.Key` can be identified by its name across programming languages and across client and server. However, `Metadata.Key` overload equals by comparing its name and its class name.

**Comment by skw0rm** [comment]
> @skw0rm Which Key are you referring to? `CallOptions.Key`, `Context.Key`, or `Attributes.Key`. In general, these Keys are identified by its reference. We can have two totally different Key instances with `debugString`s that happen to be the same.
> 
> On the contrary, `Metadata.Key` can be identified by its name across programming languages and across client and server. However, `Metadata.Key` overload equals by comparing its name and its class name.

@dapengzhang0 Thanks for your reply。 Actually, I want to use the RingHashLoadbalancer，but the code of RingHashLoadBancer means that I must use XdsNameResolver resolver? Can I use other nameresolver when use RingHashLoadbalancer?

```
 Long requestHash = args.getCallOptions().getOption(XdsNameResolver.RPC_HASH_KEY);
      if (requestHash == null) {
        return PickResult.withError(RPC_HASH_NOT_FOUND);
      }
```

**Comment by dapengzhang0** [comment]
> Actually, I want to use the RingHashLoadbalancer，but the code of RingHashLoadBancer means that I must use XdsNameResolver resolver? Can I use other nameresolver when use RingHashLoadbalancer?

I filed #8513 to track the feature. 

As for the origin issue of overloading equals for Key, we won't do that.
