### ISSUE TITLE
Could not find TLS ALPN provider 

### ISSUE THREAD

**Issue by gautamnaha** [grpc/grpc-java#8512]
I am using grpc-netty 1.38.1 , netty-handler 4.1.52.Final , netty-tcnative-boringssl-static 2.0.34.Final , and I am getting the below error - 

java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available

I am using the versions as mentioned in the table here (https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty)

Should I use different versions of the libraries ?

This is in Jdk 1.8 specifically zulujdk_8_21_0_2

**Comment by dapengzhang0** [comment]
Can you please post the full log of failure/stack trace? Did you see ClassCastException as in #7907?

**Comment by dapengzhang0** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
