### ISSUE TITLE
Getting below error on local machine after every few min.

### ISSUE THREAD

**Issue by andazk0555** [grpc/grpc-java#8515]
io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated
INFO: Transport failed
java.net.SocketException: Connection reset

**Comment by ejona86** [comment]
What version of gRPC are you using? SocketExceptions have been at a lower log level than INFO since v1.30.0, which is over a year old.

**Comment by dapengzhang0** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
