### ISSUE TITLE
Heap pollution by HpackEncoder$HeaderEntry

### ISSUE THREAD

**Issue by Gordiychuk** [grpc/grpc-java#8535]
I have multiple(500k) long living(1h+) server streaming. I see in head dump, that dominant resource its ```HpackEncoder$HeaderEntry``` that was send to server. After send to server they stay in heap until streaming not end. Is is really necessary keep in memory headers by HpackEncoder after encoded and send them? 

![image](https://user-images.githubusercontent.com/10699594/133984823-11a57648-da5b-4956-8c85-ba4b8508ba76.png)
![image](https://user-images.githubusercontent.com/10699594/133984927-392f8731-d84c-4b63-903d-1b9d45713536.png)
![image](https://user-images.githubusercontent.com/10699594/133984716-f8a409a0-f920-459b-b060-3a89f35765f5.png)

**Comment by sanjaypujare** [comment]
As far as I can see `NettyClientHandler` instantiates `io.netty.handler.codec.http2.DefaultHttp2LocalFlowController` and all of the header handling is done by that Netty class. You probably have a valid case optimizing memory usage but the fix should be in Netty unless I am missing something, is that right?

**Comment by ejona86** [comment]
Looks like it is retained by [`HpackEncoder.headerFields`](https://github.com/netty/netty/blob/aa21ec05004ab93173c76b1135446aa0c0c0fca9/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackEncoder.java#L68). That is the dynamic header table used by hpack. It is essentially the equivalent of the "gzip window." It is limited in size, but will be per-connection. And it will cause objects to outlive Eden.

I'm not sure how much there is to do about it. It could be disabled. It could be reduced in size. But I believe the current algorithm might not try at all at figuring out which headers are important and instead just keeps the last X bytes of headers.

**Comment by ejona86** [comment]
@Gordiychuk, in answer to your question "Is is really necessary keep in memory headers by HpackEncoder after encoded and send them?" the answer is "yes, mostly." How do you want to proceed?

It'd be fine to add a Netty{Client,Server}Builder API to reduce the HPACK table size. Maybe there could even be a feature to "drop" the compression context by setting the size to zero after a period of no headers. These are being kept for both sending and receiving, so we could even drop the sending context without writing to the wire, potentially (but this is probably hard to wire in the Netty API).

**Comment by Gordiychuk** [comment]
I mean that maybe it is possible do something like this https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractClientStream.java#L159-L160 where on grpc side we understand that headers not necessary anymore and call clear method like this https://github.com/netty/netty/blob/aa21ec05004ab93173c76b1135446aa0c0c0fca9/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackEncoder.java#L463 through all wrapper classes.

**Comment by ejona86** [comment]
@Gordiychuk, I don't think you're following. These headers are part of the HPACK table that belongs to the _connection_. HPACK compresses by referring to previously-used headers from previous requests. So throwing away the headers 1) in the decoder has to warn the encoder that headers are about to be thrown away and 2) reduces the compression rate.

**Comment by Gordiychuk** [comment]
Ok, I think in that case we can close current issue. Anyway I will fix it on my side by make multiplex by hand through the less amount of streams.

**Comment by ejona86** [comment]
@Gordiychuk, you will need to reduce the number of connections, not streams, to reduce this overhead.

Closing since this seems normal. For posterity, there are potential memory optimizations available, at the cost of network usage, but it doesn't seem we need to tackle those at this time.
