### ISSUE TITLE
gRPC clients always send grpc-accept-encoding header as Gzip

### ISSUE THREAD

**Issue by BuddhiWathsala** [grpc/grpc-java#8542]
I noticed that the gRPC Java clients always send `grpc-accept-encoding=gzip` whether I enabled Gzip compression or not. Is this the intended behaviour?.

AFAIU, the reason for this behaviour is `DEFAULT_INSTANCE` of the `CompressorRegistry` is using `Gzip` as the first parameter.

https://github.com/grpc/grpc-java/blob/e4a13778e00aa03d1a9ee5cd2cfd6023d1b4f778/api/src/main/java/io/grpc/CompressorRegistry.java#L33

I couldn’t find such a statement in the gRPC compression [spec](https://github.com/grpc/grpc/blob/master/doc/compression.md). Moreover, the gRPC Go language clients don't do such a thing.

**Comment by sanjaypujare** [comment]
Pls look at the issue #1704 "They may exist, even independent of turning off compression for public release."

Just curious if this is causing any problems and what the problem is

**Comment by ejona86** [comment]
> I noticed that the gRPC Java clients always send grpc-accept-encoding=gzip whether I enabled Gzip compression or not.

What do you mean by "enabled Gzip compression or not"? This is the list of decompressors that are supported, not the compressor being used.

> Moreover, the gRPC Go language clients don't do such a thing.

They have multiple compression APIs, so it may take some investigation to figure out why. Maybe you have to import google.golang.org/grpc/encoding/gzip so it will register itself?

**Comment by BuddhiWathsala** [comment]
Yes, I think here the way Java is implemented is correct. I'll look more into the Go side.
