### ISSUE TITLE
Be more strict in the NameResolver.Factory javadocs 

### ISSUE THREAD

**Issue by ST-DDT** [grpc/grpc-java#8543]
### Is your feature request related to a problem?

It's related to a problem/change of behavior of the `NameResolverRegistry` introduced in https://github.com/grpc/grpc-java/pull/8323
Due to that change the `NameResolver`s will only be invoked if their `getDefaultScheme()` matches the specified scheme.
I previously watched for/used both the "default" scheme and an alias.

### Describe the solution you'd like

Please change the javadocs to contain a hint, that the scheme used in the `newNameResolver` must be the same and only as the default scheme (or at least that no other schemes will be checked).

### Describe alternatives you've considered

Add a new method that assumes that the check has already been done, with the `newNameResolver` being implemented to do the checks and then invoke the new method. Later that method should be marked as final to disallow invalid behavior.

````java
@Nullable
public final NameResolver newNameResolver(URI targetUri, NameResolver.Args args) {
    if (getDefaultScheme().equals(targetUri.getScheme())) {
        return createNameResolver(targetUri, args);
    }
    return null;
}

@NotNull
protected abstract NameResolver createNameResolver(URI targetUri, NameResolver.Args args);
````

**Comment by sanjaypujare** [comment]
@YifeiZhuang assigned to you to address it. CC @ejona86

**Comment by YifeiZhuang** [comment]
https://github.com/grpc/grpc-java/pull/8323 changed the behavior at `NameResolverRegistry` to only look up the matching scheme at `nameResolverProvider` `getScheme()` based on targetUri scheme.  Previously it loops through all the registered providers. This is the way we wanted to encourage people to use, specified in [javadoc](https://github.com/grpc/grpc-java/pull/8323/files#diff-8ee41df66e0ac66212b9f30d25732907602619555320b7cd922da122fc914dedR55-R56).

How does your `newNameResolver()` that does the scheme check prevent what kind of breakages introduced by the change in https://github.com/grpc/grpc-java/pull/8323?

**Comment by ejona86** [comment]
> Please change the javadocs to contain a hint, that the scheme used in the newNameResolver must be the same and only as the default scheme (or at least that no other schemes will be checked).

I think this is where we are trying to get to. But I think today we were expecting there were going to be NameResolvers supporting older versions of gRPC and they would still need the scheme check. If you are okay with requiring a newer version of gRPC, then I guess you have _close_ to the guarantee you want already.

I believe the exception is [`ManagedChannelBuilder.nameResolverFactory()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#nameResolverFactory-io.grpc.NameResolver.Factory-). Once that is dead, then I think NameResolvers will be in a fairly regular world.

**Comment by ejona86** [comment]
I've added a note to #7133 that we should update the javadoc when we remove `nameResolverFactory()`. I think that addresses the concern here. @ST-DDT, speak up if I'm mistaken. Updating the doc is good, but _slightly_ premature right now.
