### ISSUE TITLE
performance test, client and server cpu utilisation did not exceed 70%, qps did not exceed 7K

### ISSUE THREAD

**Issue by sodaRyCN** [grpc/grpc-java#8549]
jdk version: 1.8.0_192-b12
grpc version: 1.40.0

i use porotc and grpc plugin to generated pb file to get req\res\grpc-service definition java file .

in my project, grpc client base on spring cloud gateway, grpc server base on spring-boot-server.

two server process  deploy on 8 core vm, client deploy on 4 core 8G docker and docker deploy on vm.

grpc server just use @GrpcServer on myclass that extend grpc.bindableservice ,  and set grpc port in spring.yaml , and there no other config.  

grpc client like that build channel ； for the same target server , diff thread use the same one client and channle build future stub.

public class DemoGrpcClient {
  private final ManagedChannel channel;
  protect DemoGrpcClient() {
        ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(core, core, 10L, TimeUnit.SECONDS,
                new LinkedBlockingQueue<>(10000),
                new ThreadFactoryBuilder().setDaemon(true).setNameFormat("nacos-grpc-client-executor-%d")
                        .build());
        threadPoolExecutor.allowCoreThreadTimeOut(true);
        channel = ManagedChannelBuilder
                .forAddress(host, port)
                .compressorRegistry(CompressorRegistry.getDefaultInstance())
                .decompressorRegistry(DecompressorRegistry.getDefaultInstance())
                .keepAliveTime(6 * 1000 * 1000, TimeUnit.MILLISECONDS)
                .executor(threadPoolExecutor)
                .defaultLoadBalancingPolicy("round_robin")
                .usePlaintext()
                .maxInboundMessageSize(DEFAULT_MAX_INBOUND_MESSAGE_SIZE)
                .disableRetry()
                .disableServiceConfigLookUp()
                .build();
}

public DTO doRpc(req) {
    MasaServiceGrpc.newFutureStub(channel).invoke(req);
    .....
}
}
performance test with wrk result like below，wrk initiate request by http mode to my grpc client , and grpc client transfer request to grpc server and get response to wrk.

![image](https://user-images.githubusercontent.com/35725024/134321596-358f3024-cd68-4025-919b-729f16f05102.png)

client cpu utilisation did not exceed 70%, qps did not exceed 7K,  two server cpu both about 50%.

ping latency client vm bettew server client about 0.2ms
![image](https://user-images.githubusercontent.com/35725024/134328021-0b5f14ac-7c10-424a-b792-696725ff79e1.png)

1、how to set client or server config to improve my project performance;
2、what's different  between use @GrpcServer and nettyserverbuild.xxxx

**Comment by sodaRyCN** [comment]
grpc client and server jvm option is :

server -Xms2g -Xmx2g -Xmn1g -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -XX:MaxGCPauseMillis=50  -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=1g -XX:-UseLargePages -XX:-UseBiasedLocking

**Comment by sodaRyCN** [comment]
yeah, latency number include :
'wrk  --<http-request>-- grpc client(spring cloud gateway) ---<grpc>--- grpc server---<grpc>--- client ---<http>--- wrk'

when i use all http,  qps is 10K/s, client cpu is 350%.
'wrk  --<http>-- client(spring cloud gateway) ---<http>--- server---<http>--- client ---<http>--- wrk'

in grpc case, client just transfer body to grpc dto and then invoke grpc bind server. transfer body is fast.

wrk \ grpc client\ grpc server running on different machine.

server process each rpc like that

**Comment by sanjaypujare** [comment]
> ... but in client, many time get the replay about 3~5ms

Sorry I didn't understand that. Could you clarify that?

It looks like we can eliminate any latency in the server method (and overall gRPC server side processing). But I would also like to eliminate any measurement issues related to use of wrk. Also are you trying to compare the all http number of 10K qps vs 7 K qps with grpc?

**Comment by sodaRyCN** [comment]
... but in client, many time get the replay about 3~5ms

I mean many times, it's cost 3-5ms between client start request and get server replay.  i watch that server deal the request just cost about 0.2 ms (record enter server methd and leave time).

and ping latency client vm bettew server client about 0.2ms
https://user-images.githubusercontent.com/35725024/134328021-0b5f14ac-7c10-424a-b792-696725ff79e1.png


i trying to compare the all http number of 10K qps vs 7 K qps with grpc, beacuse i think use grcp mode would imporve my project performance

**Comment by sodaRyCN** [comment]
thanks for u. @sanjaypujare

i reslove it.

in my case, i use spring cloud gateway as my grpc client (for some reason, i must provide external HTTP services). so i should use reactor stream code to process grpc request and response instead of use countdownLatch or other synchronization tool.

in reactor,  grpc client cpu utilisation is 90%, qps is 12K/s in 4C8G docker on vm.
