### ISSUE TITLE
Best practise for logging

### ISSUE THREAD

**Issue by elenigen** [grpc/grpc-java#8557]
We adopted gRPC java for a critical app and we are struggling on the best approach to log the important information in a single line:
- Response time
- Status
- Error details

Most of our API doesn't have to deal with streams, so for these queries we just use the `ServerInterceptor` with `ServerCall` for logging. When we look at the documentation for the `close`:
> If you wish to know when the call is actually completed/closed, you have to use Listener#onComplete or Listener#onCancel instead.

Question #1. If we look at the documentation, we are advised to rely on `onCancel` & `onComplete` to calculate the response time, but these methods are not providing the status as a parameter, so we cannot log that information?

As a workaround, we were thinking to extract the status from the `close` and keep it until `onComplete` or `onCancel` is invoked, but if I understand correctly, there are 3 different possible scenarios:

- (1) `close` (2) `onComplete` 
- (1) `close` (2) `onCancel`
- (1) `onCancel` (2) Optional: `close`

So even if we would like to extract the status from the `close` and keep it until the `onComplete` or `onCancel` is invoked, the fact that `onCancel` could be invoked before break that workaround.

Question #2. Currently, we use the `close` method to do the logging, but we also noticed that when a client lately was unstable and very slow to accept the response, it impacted our response time, so it's not clear to us how to calculate the response time once the response is ready on our side, no matter if the client is available to consume it or not?

<details>
<summary>ServerInterceptor documentation</summary>

```java
/**
 * The call was cancelled and the server is encouraged to abort processing to save resources,
 * since the client will not process any further messages. Cancellations can be caused by
 * timeouts, explicit cancellation by the client, network errors, etc.
 *
 * <p>There will be no further callbacks for the call.
 */
public void onCancel() {}

/**
 * The call is considered complete and {@link #onCancel} is guaranteed not to be called.
 * However, the client is not guaranteed to have received all messages.
 *
 * <p>There will be no further callbacks for the call.
 */
public void onComplete() {}

/**
 * Close the call with the provided status. No further sending or receiving will occur. If {@link
 * Status#isOk} is {@code false}, then the call is said to have failed.
 *
 * <p>If no errors or cancellations are known to have occurred, then a {@link Listener#onComplete}
 * notification should be expected, independent of {@code status}. Otherwise {@link
 * Listener#onCancel} has been or will be called.
 *
 * <p>Since {@link Metadata} is not thread-safe, the caller must not access (read or write) {@code
 *  trailers} after this point.
 *
 * <p>This method implies the caller completed processing the RPC, but it does not imply the RPC
 * is complete. The call implementation will need additional time to complete the RPC and during
 * this time the client is still able to cancel the request or a network error might cause the
 * RPC to fail. If you wish to know when the call is actually completed/closed, you have to use
 * {@link Listener#onComplete} or {@link Listener#onCancel} instead. This method is not
 * necessarily invoked when Listener.onCancel() is called.
 *
 * @throws IllegalStateException if call is already {@code close}
 */
public abstract void close(Status status, Metadata trailers);
```
</details>

**Comment by ejona86** [comment]
> If we look at the documentation, we are advised to rely on onCancel & onComplete to calculate the response time, but these methods are not providing the status as a parameter, so we cannot log that information?

If onCancel is called, then the RPC was cancelled. If onComplete was called then the Status passed to ServerCall.close() was used.

> the fact that onCancel could be invoked before break that workaround

I don't see why. `onCancel()` can always behave the same way, independent of whether close() was called.

> we also noticed that when a client lately was unstable and very slow to accept the response, it impacted our response time

Right, so this depends on your definition of "response time." If you want to include it leaving any local buffers, then yes, slow clients will slow things down. If you want to measure _your service's response time_ (excluding grpc), then measure the time before close() is called. But then you wait until onComplete() to make that time "official."

**Comment by elenigen** [comment]
Thanks for the feedback!

> If onCancel is called, then the RPC was cancelled. If onComplete was called then the Status passed to ServerCall.close() was used.

From what I understand, the `onComplete()` is invoked only on a `isOK` situation, which means all the other statuses not being `OK` would end up in the cancel category? So it would be important to know what was the status before converting it into a cancel and to have the reason.

> I don't see why. onCancel() can always behave the same way, independent of whether close() was called.

Again, if we want to know the original status before being converted into cancel, then our only chance is to capture it from the `close()`, but if this function is never called, then how to know what happened?

>  then measure the time before close() is called

Actually, we are currently doing this:
```kotlin
        val nextCall = object : SimpleForwardingServerCall<ReqT, RespT>(call) {
            override fun close(status: Status, metadata: Metadata) {
                stopWatch.stop()
                super.close(status, metadata)
            }
        }
```
So we calculate the time before invoking the `close()` from the `super` and it looks like it's impacted by slow clients, so when you say even before that, then where exactly are you talking about?

**Comment by ejona86** [comment]
> From what I understand, the onComplete() is invoked only on a isOK situation

No, it is invoked any time `serverCall.close()` ends the RPC and that processing completed successfully. The status code (OK, or otherwise) passed to `close()` has no impact on if it is called.

Cancellation is when the RPC is thrown away before the service completes or before the service's responses are sent. This is I/O failures and client-cancellation.

> So we calculate the time before invoking the close() from the super and it looks like it's impacted by slow clients, so when you say even before that, then where exactly are you talking about?

Why do you think it is impacted by slow clients? Clearly the close() call itself isn't impacted by slow clients because you didn't call `super` in your code. If you are doing streaming, then you may be slowed sending many messages by slow clients, as you are waiting for `isReady() == true`. But for unary, there should not be any slowdown.

**Comment by ejona86** [comment]
Unclear if resolved, but nothing outstanding for us to help with. If not resolved, comment, and it can be reopened.
