### ISSUE TITLE
Cancel a blocking call BEFORE deadline?

### ISSUE THREAD

**Issue by namgk** [grpc/grpc-java#8569]
Hi there,

I know that I can set a deadline for a blocking call with something like

```
...
.newBlockingStub(channel)
.withDeadlineAfter()
...
```

How do I proactively cancel this call BEFORE the deadline?

Thanks

**Comment by ejona86** [comment]
You can either interrupt the thread or use `io.grpc.Context`. Interruption is inherently racy, so isn't great for cancelling just the rpc. Context would look like:

```java
try (CancellableContext c = Context.current().withCancellation()) {
  // pass 'c' to another thread. Call c.cancel(...) to cancel the RPC
  stub.doRpc();
}
```
