### ISSUE TITLE
MessageDeframer stalled logic needs review

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#857]
Currently there is a bug that results in the MessageDeframer not being stalled when stream is being closed (in error scenarios), resulting in the stream listener not being called immediately.  Specific lines of review include:

return unprocessed.readableBytes() > 0 || (nextFrame != null && nextFrame.readableBytes() > 0);

And a proposed change (WIP):

      stalled = (unprocessed.readableBytes() == 0);

      if (endOfStream) {
        if (!stalled) {
          listener.endOfStream();
        } else if (nextFrame != null || nextFrame.readableBytes() > 0) {//FIXME
          // We've received the entire stream and have data available but we don't have
          // enough to read the next frame ... this is bad.
          throw Status.INTERNAL.withDescription("Encountered end-of-stream mid-frame")
              .asRuntimeException();
        } else if (stalled) {
        }
      }

**Comment by nmittler** [comment]
The proposed change looks right to me, given the current logic.  I'm wondering if we should also provide a `cancel` method to handle the case of `RST_STREAM` more explicitly. WDYT?

**Comment by ejona86** [comment]
@nmittler, how would a `cancel` method be different than the currently-existing `close`?

**Comment by nmittler** [comment]
@ejona86 `close` should work as well ... we just need to make sure that it's ok to call `close` more than once.

**Comment by carl-mastrangelo** [comment]
Looking more at the Deframer Listener, I am not sure the stalled logic is the source of the supposed bug.  The Listener provides two methods:


    /**
     * Called when end-of-stream has not yet been reached but there are no complete messages
     * remaining to be delivered.
     */
    void deliveryStalled();

    /**
     * Called when the stream is complete and all messages have been successfully delivered.
     */
    void endOfStream();

deliveryStalled() makes it seem like things are still in progress, there just isn't any more work to do at the time it is called.  endOfStream() says things are complete and everything is successful.  Neither should be called in the event of a stream reset, since neither deal with error scenarios.

  
Even if the Deframer stalling logic needs some work, I think the actual bug was fixed in #864.  Getting a reset in the middle of receiving a message is always going to result in a stalled deframer, which then causes ACS to never close the Stream Listener.  I think the bad logic is actually in ACS.

**Comment by nmittler** [comment]
@carl-mastrangelo sounds good ... thanks for investigating!  Let's discuss offline and see if we can clean this up a bit.

**Comment by ejona86** [comment]
> deliveryStalled() makes it seem like things are still in progress, there just isn't any more work to do at the time it is called.

@carl-mastrangelo, no. "when end-of-stream has not yet been reached" is there to distinguish it from endOfStream. "no complete messages remaining to be delivered" is referring to flow control. Zero complete messages would be "no complete messages remaining to be delivered." "Remaining to be delivered" is referring to `request()`; if `request()` would immediately cause more messages to be delivered, then the deframer is not stalled.

> Neither should be called in the event of a stream reset, since neither deal with error scenarios.

Neither might be be called _immediately_, but `deliveryStalled()` should be called when the input is drained, because that is "no complete messages remaining to be delivered".

**Comment by ejona86** [comment]
Fixed by @carl-mastrangelo in #869.
