### ISSUE TITLE
:grpc-protobuf:test fails frequently on Travis.

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#859]

**Comment by ejona86** [comment]
This seems caused by #836. I assume it is running out of memory.

Example runs (starting with #836):
https://travis-ci.org/grpc/grpc-java/builds/76701177
https://travis-ci.org/grpc/grpc-java/builds/76693113

**Comment by ejona86** [comment]
[stackoverflow](http://stackoverflow.com/questions/18524574/java-program-terminate-with-java-result-137) talks about return code 137 being caused by a SIGKILL to Java, which lines up with it likely being OOM.

**Comment by nmittler** [comment]
Yup, that's the new test ... it's creating a 100MB proto so that it can verify that we support protos greater than the default of 64MB.  I can try lowering this a bit to see if that eliminates the flakes.
