### ISSUE TITLE
ManagedChannel never terminates with shutdown/shutdownNow

### ISSUE THREAD

**Issue by Joj3j** [grpc/grpc-java#8640]
### What version of gRPC-Java are you using?
1.31.1
### What is your environment?

As a Kubernetes pod running /linux
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

### What did you expect to see?
Waits for the channel to become terminated, giving up if the timeout is reached.
### What did you see instead?
ManagedChannel.isTerminated() always return true after 100 or more tries shutdown()/shutdownNow()

### Steps to reproduce the bug

The issue gets reproduced intermediate and when observed the thread hangs. The channel stop is called using the following snippets.

        try
        {       
            channel.shutdown();     
            while (!channel.isTerminated())
            {
          
                try
                {
                    channel.awaitTermination(5, TimeUnit.SECONDS); 
                }
                catch (InterruptedException e)
                {
                    stopChannelLogger.warn(name + " GRPC channel client "+ clientId + " wait interrupted", e);
                }
                channel.shutdownNow();
            }
        }
        catch (Throwable e)
        {
            stopChannelLogger.warn(name + " GRPC channel client "+ clientId + " termination failed, will retry", e);
        }

**Comment by ejona86** [comment]
Note: calling shutdownNow() multiple times won't help at all.

This may be the same as b/183340374. In it I found a bug relating to GOAWAYs where the connection wouldn't be closed. I know it was an issue with `shutdown()` and not `shutdownNow()`, but I don't recall if calling `shutdown()` triggered the bug and _prevented_ `shutdownNow()` from working properly. I think the code that caught the problem didn't call `shutdownNow()` at all, so I might not have looked into that.

@Joj3j, I don't know if it makes sense for your system, but you might be able to workaround this problem by avoiding the initial `shutdown()` (basically calling `shutdownNow()` after a sleep).

What is the relationship between this shutdown and the last RPCs? Is it likely there was a period (say, greater than 10-30 seconds) without any RPCs before the channel shutdown was triggered? What server is being used here and are you using any proxies?

**Comment by Joj3j** [comment]
@ejona86 Thanks for the suggestion. I can try the sleep and shutdownNow() .
The grpc server is another app running in k8s. The shutdown is initiated when the server connection needs reintialization. There can be RPC calls happening before/during this termination.
Is later version of the library has a fix for this shutdown issue.

**Comment by ejona86** [comment]
> Is later version of the library has a fix for this shutdown issue.

If shutdownNow-without-an-earlier-shutdown works, then that means you are probably hitting the bug I saw earlier. It isn't an easy fix, but also not a super-hard one. Mostly annoying.

If you see problems with shutdownNow by itself, then you may have discovered some other issue and we'd need to investigate more.

In either case, sleep+shutdownNow() looks like an okay workaround. The only problem it'd introduce is it will delay shutdown even if there are no outstanding RPCs. I'm not saying that is acceptable, but lets you limp along instead of this permanent hang.

**Comment by Joj3j** [comment]
I will go with this solution for the short term.

If a fix is available for this issue, please do update here with the library version.

Cheers

**Comment by ejona86** [comment]
> I will go with this solution for the short term.

Does that mean the workaround I suggested is working for you? So it seems the problem is within shutdown() causing a hang?

**Comment by Joj3j** [comment]
The issue occurs again with sleep(3s) +shutdownNow() . 
channel.isTerminated() returns false after 1000 of tries.

**Comment by ejona86** [comment]
That means this is a unique issue and would need further investigation.

**Comment by Joj3j** [comment]
Seems unique, we are using this version for more than a year. It starts appearing recently and is very frequent in this k8 env.
Enabling any logs help here.

**Comment by ejona86** [comment]
Oh, I missed it was that old of a version. In that case, we probably won't look into this any more unless you reproduce it on a more recent version.

The behavior I'm aware about is related to GOAWAYs, so it is possible a proxy or a server changed in your deployment and is now triggering the unwanted behavior.

**Comment by Joj3j** [comment]
We use the same version for both client and server to keep it bug-free.
Following is the current version used.

grpcVersion = '1.31.1' // CURRENT_GRPC_VERSION
protobufVersion = '3.13.0' // CURRENT_GRPC_VERSION
nettyVersion = '4.1.51.Final'

Let me know the latest stable versions for these ones, considering this issue, I can plan an upgrade for these ones.

**Comment by ejona86** [comment]
You are free to use the latest versions of grpc and protobuf. For Netty, see the table at https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty for the suggested version.

**Comment by Joj3j** [comment]
Ok. I will look into this later. Thanks.
As a workaround ,I'm narrowing down the need of shutdown with limited retries.

**Comment by ejona86** [comment]
Seems like there's not much more we can do. If you see the issue with a more recent version of gRPC, comment, and it can be reopened.
