### ISSUE TITLE
CsdsService not properly synchronized with XdsClient

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#8642]
Consider this code from CsdsService:
https://github.com/grpc/grpc-java/blob/a46560e4fc9ec4771dc7824055d23f1301dc1e3d/xds/src/main/java/io/grpc/xds/CsdsService.java#L152-L155

The initial issue is that `getSubscribedResourcesMetadata()` and `getCurrentVersion()` have no synchronization:
https://github.com/grpc/grpc-java/blob/14eb3b265f84a89f5c33a90b048c4f9c2bf70286/xds/src/main/java/io/grpc/xds/ClientXdsClient.java#L1842-L1848
https://github.com/grpc/grpc-java/blob/a46560e4fc9ec4771dc7824055d23f1301dc1e3d/xds/src/main/java/io/grpc/xds/AbstractXdsClient.java#L257-L258

That is _bad_. However, the xdsClient API itself is insufficient for CSDS because those two method calls need to be atomic; even if each of those methods were thread-safe the version needs to match the resources returned.

**Comment by sergiitk** [comment]
Good catch. Thank you.

**Comment by dapengzhang0** [comment]
#8675 removed `getCurrentVersion()`, but `getSubscribedResourcesMetadata()` is still unsynchronized.

**Comment by sergiitk** [comment]
Yes, this is resolved. Apparently `Fixes` notation didn't work in a comment: https://github.com/grpc/grpc-java/pull/8795#issuecomment-1002807744.
