### ISSUE TITLE
Server not accepting requests after update from 1.41.0 to 1.42.0

### ISSUE THREAD

**Issue by augi** [grpc/grpc-java#8674]
After upgrading from `1.41.0` to `1.42.0`, our services stopped receiving requests, and logging following INFO message:
* `[id: 0x84be72e8, L:/172.21.223.199:8080 - R:/172.21.225.64:58430] ignoring DATA frame for stream RST_STREAM sent.`
* sourceClassName: `io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener`
* sourceFileName: `defaulthttp2connectiondecoder.java`
* sourceMethodName: `shouldIgnoreHeadersOrDataFrame`
* sourceLineNumber: `648`

We think that it could be caused by the following changes:
* [netty: Requests with Connection header are malformed](https://github.com/grpc/grpc-java/commit/192688f1f22c93632aaf598f895cf33ca84eeec0)
* [dep: bump netty to 4.1.63.Final and tcnative to 2.0.38.Final](https://github.com/grpc/grpc-java/commit/25022f6846ec1fdd8003789cba32d4ca981c3171)

As we are running our workload also in a legacy environment where proxies don't handle HTTP/2 100% correctly, the issue is probably in the `Connection` header.

### Is your feature request related to a problem?
Connections with the `Connection` header are refused.

### Describe the solution you'd like
Make this validation configurable, so have a new method in `ServerBuilder` class 🙏 

### Describe alternatives you've considered
Remove this validation completely.

### Additional context
Unfortunately, this is a critical issue for us that blocks us from updating gRPC libraries 😢 
> My guess why netty doesn't reject the connection with the `Connection` header is that there are still too many _legacy_ workloads that could be broken by this change.

**Comment by ejona86** [comment]
> ignoring DATA frame for stream RST_STREAM sent.

This log is after-the-fact. Whatever went wrong probably happened beforehand. I will say I am surprised to learn it is being logged at INFO.

> our services stopped receiving requests

What do clients see? Is this a hang? Is it an error? What error message?

> As we are running our workload also in a legacy environment where proxies don't handle HTTP/2 100% correctly, the issue is probably in the Connection header

It seems that is a guess/hypothesis. But the only evidence is that "it broke during update," which is still pretty weak. You can enable low-level logging for Netty by enabling FINE logs for `io.grpc.netty.NettyServerHandler` (grpc-netty) and/or `io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler` (grpc-netty-shaded).

It seems very strange calling an HTTP/2 implementation "legacy." If it does turn out to be the Connection header, then we might provide a workaround, but we make sure that the broken HTTP/2 implementation is also being updated with a fix. It's not clear to my why the Connection header would even be present, unless the proxy is converting HTTP/1 requests to HTTP/2, which isn't a typical deployment.

Disallowing the Connection header was noticed/fixed for security reasons as part of [A41 xDS RBAC](https://github.com/grpc/proposal/blob/master/A41-xds-rbac.md). Unfortunately the Connection header has to be fully parsed when present and can impact other headers.

**Comment by augi** [comment]
> > our services stopped receiving requests
> 
> What do clients see? Is this a hang? Is it an error? What error message?

There is a proxy between clients and servers, so clients can see just a `502` from the proxy (and also the proxy reported `502` for upstream).

> > As we are running our workload also in a legacy environment where proxies don't handle HTTP/2 100% correctly, the issue is probably in the Connection header
> 
> It seems that is a guess/hypothesis. But the only evidence is that "it broke during update," which is still pretty weak. You can enable low-level logging for Netty by enabling FINE logs for `io.grpc.netty.NettyServerHandler` (grpc-netty) and/or `io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler` (grpc-netty-shaded).

Agree! I will investigate this issue more deeply NBD. My guess/hypothesis goes from my experience, when we tried to use Envoy proxy, and Envoy wasn't able to talk with the legacy proxy due to `Connection` header presence.

Thank you for your response, I will let you know how my investigation goes! 👍

**Comment by ejona86** [comment]
> and Envoy wasn't able to talk with the legacy proxy due to Connection header presence.

I see. If you did nothing at that point except decide to "not use Envoy," then yeah, I think this is coming around to bite you again. This is why we make sure that implementations get fixed when we put in workarounds, as bad HTTP/2 behavior like that is toxic to the ecosystem. How much time do you think you'd need to get the proxy fixed?

**Comment by augi** [comment]
Yeah, I used nginx that seems to be more relaxed. I'm pretty sure this will bite us again but unfortunately, usage of the _legacy proxy_ is out of my control, so I'm just trying to do my best to overcome this situation.

I escalated this issue but I'm sure that the potential fix will take at least weeks.

I will investigate the issue more deeply tomorrow and maybe try to propose a fix that could help if someone other would be in the same situation 🙏

**Comment by ejona86** [comment]
We can provide a system property or environment variable to disable the new validation. And then we just coordinate to determine a reasonable amount of time to leave it in place.

**Comment by augi** [comment]
I executed an experiment and it is as expected:
* I enabled `DEBUG` logging on `io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler` and I can see `connection: close` in `headers=GrpcHttp2RequestHeaders`. I was using grpcurl to invoke requests, and the requests went through our _legacy proxy_.
* We are using [grpc_health_probe](https://github.com/grpc-ecosystem/grpc-health-probe) for healthchecking and it works correctly as it talks with the application/container directly.

**Comment by augi** [comment]
I spent some time trying to find a way how to _override_ the validation (even with reflection) and without success 😢 

So I would like to kindly ask you, @ejona86, if it would be possible to provide a new system property or environment variable to disable the `Connection` header validation 🙏 

Or if you know a way how to manipulate any `NettyServerHandler` created, it could be sufficient - then I could e.g. wrap existing `FrameListener` with an implementation that would remove the `Connection` header 🤔

**Comment by ejona86** [comment]
The system property `io.grpc.netty.disableConnectionHeaderCheck` will be available. Note that it will be `io.grpc.netty.shaded.io.grpc.netty.disableConnectionHeaderCheck` for grpc-netty-shaded.

**Comment by augi** [comment]
Thank you very much, very appreciated! 🙏

**Comment by augi** [comment]
We've updated to the latest version with the system property enabled and it works like a charm. Thank you for the quick workaround! 👍
