### ISSUE TITLE
GRPC induces NoSuchFieldError with build() on unused message in proto file

### ISSUE THREAD

**Issue by Groostav** [grpc/grpc-java#8678]
### What version of gRPC-Java are you using?
GRPC 1.37.0, Protobuf 3.18.0

### What is your environment?
Windows, Azul OpenJDK 13, 

### What did you expect to see?
no exceptions; builder returns a normal instance
OR
A custom error "this message type has been removed at runtime for the optimization CODE_SIZE; please rerun with SPEED"

### What did you see instead?
```
java.lang.NoSuchFieldError: internal_static_package_Unused_fieldAccessorTable
	at package.Unused.internalGetFieldAccessorTable(Unused.java:41)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
	at com.google.protobuf.GeneratedMessageV3.isInitialized(GeneratedMessageV3.java:207)
	at package.Unused$Builder.build(Unused.java:296)
```

### Steps to reproduce the bug

1. create a proto file 
   ```
   syntax = "proto3";

   option optimize_for = CODE_SIZE;

   service Thingy {
     rpc function (Input) returns (Output)
   }

   message Input {}
   message Output {}

   message Unused {}
   ```

2. write some code
   ```
   var builder = Unuused.newBuilder();
   try { builder.build() }
   catch(NoSuchFieldError e) { e.printStackTrace() }
   ```

**Comment by Groostav** [comment]
Ah, I was under the impression that using optimizeFor = SPEED fixedf the problem, but it does not, it does change the shape a little; the NoSuchFieldError is no down stack from a different location.

This is.. not good for me.

**Comment by ejona86** [comment]
This looks to be a protobuf issue. Please file an issue at https://github.com/protocolbuffers/protobuf instead.

**Comment by Groostav** [comment]
The problem was gradle and its copying of an output to a cache.
