### ISSUE TITLE
How to add a new mechanisms in java?

### ISSUE THREAD

**Issue by SamYuan1990** [grpc/grpc-java#8679]
according to https://grpc.io/docs/guides/auth/#extending-grpc-to-support-other-authentication-mechanisms
it seems we are able to add a customer authentication mechanisms for grpc.
May I know how to do the same for java?

Following the sample in links above, how should I add the customer authentication mechanisms as reading data from header?

and another question, any limitation for customer authentication mechanisms ?

**Comment by ejona86** [comment]
The equivalent API in grpc-java is [`CallCredentials`](https://grpc.github.io/grpc-java/javadoc/io/grpc/CallCredentials.html). It's also possible to implement a `com.google.auth.Credentials` along with [`MoreCallCredentials`](https://grpc.github.io/grpc-java/javadoc/io/grpc/auth/MoreCallCredentials.html).

These APIs are only for adding bearer tokens to requests. They can't do handshaking nor implement transport-level security.

**Comment by SamYuan1990** [comment]
so, which means if the new mechanisms can be implemented via 
```
public abstract void applyRequestMetadata(CallCredentials.RequestInfo requestInfo,
                                          Executor appExecutor,
                                          CallCredentials.MetadataApplier applier)

Parameters:
requestInfo - request-related information
appExecutor - The application thread-pool. It is provided to the implementation in case it needs to perform blocking operations.
applier - The outlet of the produced headers. It can be called either before or after this method returns.
```
then I am able to make the implementation and injection ?

**Comment by SamYuan1990** [comment]
If answer for question above is yes, could you please help guide me with file(*.java) in this project with test case?
