### ISSUE TITLE
DEADLINE_EXCEEDED when using sleep

### ISSUE THREAD

**Issue by cjmcgraw** [grpc/grpc-java#8682]
Current configuration:

grpcVersion = 1.42.0
operatingSystem = Ubuntu 20.10 / docker / jdk17

Issue: 

I have gRPC server running. Using a java client to connect to it, and send requests. The following code for the client:

```java

public class DnsTesterClient {
  public static void main(String[] args) throws Exception {
    System.out.println("Starting script");
    ManagedChannel channel = ManagedChannelBuilder
        .forTarget("test_server_1:50051")
        .usePlaintext()
        .build();

    DnsTester dnsTester = new DnsTester(channel);
    try {
      String response = dnsTester.call("request - initial");
      for (int i = 0; i < 15; i++ ) {
        response = dnsTester.call("request - " + i);
      }
    } finally {
      channel.shutdownNow().awaitTermination(5, TimeUnit.SECONDS);
    }
    System.out.println("Finished script");
  }

  static public class DnsTester {
    private final Channel channel;
    private final TestServerGrpc.TestServerBlockingStub stub;
    private final String callerId;
    public DnsTester(Channel channel) {
      this.channel = channel;
      this.stub = TestServerGrpc
              .newBlockingStub(channel)
              .withDeadlineAfter(500, TimeUnit.MILLISECONDS)
              .withWaitForReady();
      this.callerId = "123";
    }

    public String call(String callerName) {
      long start = System.nanoTime();
      CallRequest request = CallRequest.newBuilder()
              .setCallerId("123")
              .setCallerName(callerName)
              .build();

      CallResponse response = stub.callServer(request);
      long end = System.nanoTime();
      String output = response.getMessage();
      System.out.println("request took " + Long.toString((end - start) / 1_000_000 ) + " ms");
      return output;
    }
  }
}
```

This is the output of this executing: 
![image](https://user-images.githubusercontent.com/4107771/140972824-13a07e79-a721-4303-9ddd-bc8f2256e404.png)

Now if I add in a sleep. I see unexpected `DEADLINE_EXECEEDED` exceptions after the initial request.

```java
      ...
      
      String response = dnsTester.call("request - initial");
      for (int i = 0; i < 15; i++ ) {
        response = dnsTester.call("request - " + i);
        Thread.sleep(1000);
        // also happens with TimeUnit.SECONDS.sleep(1);
      }
      
      ...
```

I then see the following during execution:

![image](https://user-images.githubusercontent.com/4107771/140973201-35829691-4efa-4f94-b911-74d83066e13f.png)

Notice that it still executes the initial request and then the second request (which all happen before the sleeps). But then the sleep causes the deadline to be exceeded.

### What did you expect to see?
I don't expect a deadline exceeded exception

### What did you see instead?
There is a deadline exceeded execption

### Steps to reproduce the bug
Run the described code above against a simple server.

Is this expected? It appears to be a bug, and I want to ensure that this library will not block if other threads are busy doing work.

If this isn't a bug. How can I ensure that other work does not cause `DEADLINE_EXCEEDED` exceptions in the above code?

**Comment by Sophia60** [comment]
> Current configuration:
> 
> 
> 
> grpcVersion = 1.42.0
> 
> operatingSystem = Ubuntu 20.10 / docker / jdk17
> 
> 
> 
> Issue: 
> 
> 
> 
> I have gRPC server running. Using a java client to connect to it, and send requests. The following code for the client:
> 
> 
> 
> ```java
> 
> 
> 
> public class DnsTesterClient {
> 
>   public static void main(String[] args) throws Exception {
> 
>     System.out.println("Starting script");
> 
>     ManagedChannel channel = ManagedChannelBuilder
> 
>         .forTarget("test_server_1:50051")
> 
>         .usePlaintext()
> 
>         .build();
> 
> 
> 
>     DnsTester dnsTester = new DnsTester(channel);
> 
>     try {
> 
>       String response = dnsTester.call("request - initial");
> 
>       for (int i = 0; i < 15; i++ ) {
> 
>         response = dnsTester.call("request - " + i);
> 
>       }
> 
>     } finally {
> 
>       channel.shutdownNow().awaitTermination(5, TimeUnit.SECONDS);
> 
>     }
> 
>     System.out.println("Finished script");
> 
>   }
> 
> 
> 
>   static public class DnsTester {
> 
>     private final Channel channel;
> 
>     private final TestServerGrpc.TestServerBlockingStub stub;
> 
>     private final String callerId;
> 
>     public DnsTester(Channel channel) {
> 
>       this.channel = channel;
> 
>       this.stub = TestServerGrpc
> 
>               .newBlockingStub(channel)
> 
>               .withDeadlineAfter(500, TimeUnit.MILLISECONDS)
> 
>               .withWaitForReady();
> 
>       this.callerId = "123";
> 
>     }
> 
> 
> 
>     public String call(String callerName) {
> 
>       long start = System.nanoTime();
> 
>       CallRequest request = CallRequest.newBuilder()
> 
>               .setCallerId("123")
> 
>               .setCallerName(callerName)
> 
>               .build();
> 
> 
> 
>       CallResponse response = stub.callServer(request);
> 
>       long end = System.nanoTime();
> 
>       String output = response.getMessage();
> 
>       System.out.println("request took " + Long.toString((end - start) / 1_000_000 ) + " ms");
> 
>       return output;
> 
>     }
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> This is the output of this executing: 
> 
> ![image](https://user-images.githubusercontent.com/4107771/140972824-13a07e79-a721-4303-9ddd-bc8f2256e404.png)
> 
> 
> 
> Now if I add in a sleep. I see unexpected `DEADLINE_EXECEEDED` exceptions after the initial request.
> 
> 
> 
> ```java
> 
>       ...
> 
>       
> 
>       String response = dnsTester.call("request - initial");
> 
>       for (int i = 0; i < 15; i++ ) {
> 
>         response = dnsTester.call("request - " + i);
> 
>         Thread.sleep(1000);
> 
>         // also happens with TimeUnit.SECONDS.sleep(1);
> 
>       }
> 
>       
> 
>       ...
> 
> ```
> 
> 
> 
> I then see the following during execution:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/4107771/140973201-35829691-4efa-4f94-b911-74d83066e13f.png)
> 
> 
> 
> Notice that it still executes the initial request and then the second request (which all happen before the sleeps). But then the sleep causes the deadline to be exceeded.
> 
> 
> 
> ### What did you expect to see?
> 
> I don't expect a deadline exceeded exception
> 
> 
> 
> ### What did you see instead?
> 
> There is a deadline exceeded execption
> 
> 
> 
> ### Steps to reproduce the bug
> 
> Run the described code above against a simple server.
> 
> 
> 
> 
> 
> 
> 
> Is this expected? It appears to be a bug, and I want to ensure that this library will not block if other threads are busy doing work.
> 
> 
> 
> If this isn't a bug. How can I ensure that other work does not cause `DEADLINE_EXCEEDED` exceptions in the above code?

**Comment by ejona86** [comment]
A deadline is a precise point in time. A timeout is a duration. gRPC uses deadlines, not timeouts. So this call to `withDeadlineAfter()` says that all RPCs on that stub need to complete within 500 ms _of when that method is created_:
```java
      this.stub = TestServerGrpc
              .newBlockingStub(channel)
              .withDeadlineAfter(500, TimeUnit.MILLISECONDS)
              .withWaitForReady();
```

Instead, set the deadline when you do the RPC:
```java
      CallResponse response = stub.withDeadlineAfter(500, TimeUnit.MILLISECONDS)
                                  .callServer(request);
```

**Comment by sergiitk** [comment]
Note that this also explains the behavior with two RPCs passing, and third one failing

```java
      // Total deadline 500ms
      String response = dnsTester.call("request - initial");  // 143ms < 500 ms
      for (int i = 0; i < 15; i++ ) {
        response = dnsTester.call("request - " + i);  // first request: 2 ms. ~145ms < 500 ms
        Thread.sleep(1000);
        // after the first iteration ~1145ms > 500ms
      }
```

So on the second iteration, and the third RPC exceeds the deadline.

**Comment by cjmcgraw** [comment]
Well egg on my face then :-)

Thanks @ejona86  and @sergiitk  I appreciate your thoroughness. Sorry for my misunderstanding!

**Comment by sergiitk** [comment]
No worries, we're happy to help. When I was looking into this, `withDeadlineAfter` behavior wasn't immediately clear to me too. We'll look into making the docs clarify this point better.
