### ISSUE TITLE
reflection.proto v1 is ready now，v1alpha can be update

### ISSUE THREAD

**Issue by letuer** [grpc/grpc-java#8707]
grpc-services contains deprecated `v1alpha/reflection.proto`。Few hours ago, `grpc/grpc` project accept PR [#27957](https://github.com/grpc/grpc/pull/27957) , add [`v1/reflection.proto`](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1/reflection.proto). 
So I think we can update this file.

**Comment by letuer** [comment]
#6724

**Comment by letuer** [comment]
Duplicate of #6724

**Comment by ejona86** [comment]
That grpc/grpc PR doesn't actually do anything that interesting. Yes, it adds the proto, but it isn't actually using the proto yet and still relying on the old version.

**Comment by dapengzhang0** [comment]
Close this issue and let's keep tracking updates in #6724
