### ISSUE TITLE
If I want to implement my own monitoring and control refreshing grpc connections, such as server address changes and client monitoring  and refresh in real time. Do you have any good opinions?

### ISSUE THREAD

**Issue by FanForerver** [grpc/grpc-java#8717]

**Comment by letuer** [comment]
Hi. Can you ask questions in English here? Please translate it into English with google. Grammar is not required to be completely correct, just to be understood by more people.

I think you need a `service register center`，google it.
See: 
* Chinese：https://www.cnblogs.com/haha12/p/11532910.html
* English：https://microservices.io/patterns/service-registry.html

**Comment by FanForerver** [comment]
> Hi. Can you ask questions in English here? Please translate it into English with google. Grammar is not required to be completely correct, just to be understood by more people.
> 
> I think you need a `service register center`，google it. See:
> 
> * Chinese：https://www.cnblogs.com/haha12/p/11532910.html
> * English：https://microservices.io/patterns/service-registry.html

我们不需要注册中心，我们将使用k8s

**Comment by dapengzhang0** [comment]
Google translation of the title:

> Excuse me, I want to implement my own monitoring and control refreshing grpc connections, such as server address changes and client monitoring (such as through the configuration center and spring framework) and refresh in real time. Do you have any good opinions?

Translation of the above comment

> We don't need service register center, we will use k8s
