### ISSUE TITLE
AppScan vulnerabilities reported from 'grpc' code

### ISSUE THREAD

**Issue by Preeti214** [grpc/grpc-java#8718]
Hi,

Can you please review below AppScan vulnerabilities reported in GRPC code and let us know if any plan to fix these or if these are false positives. 

Issue type:: Cryptography.InsecureAlgorithm
API:: java.security.MessageDigest.getInstance(String):MessageDigest
Caller::
1) io.grpc.netty.shaded.io.netty.handler.codec.http.websocketx.WebSocketUtil$1.initialValue():MessageDigest:39 - getInstance("MD5")
2)io.grpc.netty.shaded.io.netty.handler.codec.http.websocketx.WebSocketUtil$2.initialValue():MessageDigest:52
3)io.grpc.netty.shaded.io.netty.handler.ssl.util.FingerprintTrustManagerFactory$1.initialValue():MessageDigest:85
getInstance("SHA1")

Thank you,
Preeti.

**Comment by cfredri4** [comment]
These are shaded Netty classes, should be reported here: https://github.com/netty/netty

**Comment by dapengzhang0** [comment]
These should be false positive. 

1) and 2) won't be executed by grpc as it does not use websocket. 3) is only in a very old version of netty, not in the version of netty that the latest grpc is currently using.

**Comment by Preeti214** [comment]
Thank you for confirming !
