### ISSUE TITLE
Huh. I don't know how that fixed it. But since it seems you found a solution, closing the issue.

### ISSUE THREAD

**Issue by vincenlee** [grpc/grpc-java#8721]
Huh. I don't know how that fixed it. But since it seems you found a solution, closing the issue.

_Originally posted by @ejona86 in https://github.com/grpc/grpc-java/issues/4263#issuecomment-377035590_

I’m using  google speech to text library  that involve the grpc ,when I upgrade the grpc to 1.32.2 ,will lead to this error ,if I remove the protobuf-java lib only use the protobuf-lite   will receive the error  from gradle ：Execution failed for task ':audio_text_lib:generateGoogleConsumerComGlobalReleaseProto'.
> protoc: stdout: . stderr: google/protobuf/descriptor.proto: File not found.
  google/api/annotations.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
  google/api/annotations.proto:26:8: "google.protobuf.MethodOptions" is not defined.

Because the protobuf-java has descriptor.proto but  protobuf-lite doesn't have ,How I resolved it

**Comment by dapengzhang0** [comment]
Can you provide the `build.gradle` file?

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
