### ISSUE TITLE
Jmh Benchmarks don't work

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#873]
$ gradle :grpc-benchmarks:jmh

Trying to run that results in a bunch of errors printed out to the screen.

**Comment by nmittler** [comment]
It seems that this was introduced by commit: 35cabd0b82c1b1cbaa5094a09a5d36854605ee95.  A call to `Call.halfClose()` was added, which is breaking the `AbstractBenchmark.startFlowControlledStreamingCalls`, which was calling `call.halfClose()` manually.  It's a bit of a mystery as to why this hasn't caused a problem with anyone until now :/.

**Comment by ejona86** [comment]
Given that the benchmarks were added after 35cabd0, which is from Jun _2014_, it seems that commit could not have been the cause of the failure.

**Comment by nmittler** [comment]
Yup that's right ... so the question is:  how did they ever work? :/
