### ISSUE TITLE
Server-side streaming and client process callback synchronization

### ISSUE THREAD

**Issue by nakarinh14** [grpc/grpc-java#8737]
Hello, I am testing gRPC server-side streaming with a client async stub and got a question about how client process callbacks 

From the documentation it's stated that no onNext can be sent after onComplete signal is sent from the server, but I am not sure does client wait for all remaining onNext callbacks to finish before executing/processing the onComplete callback.

Or simply stated, can onComplete callback execution happens on client async stub while the client is still processing the final onNext callback?

**Comment by ejona86** [comment]
StreamObserver is not a thread-safe API, so gRPC cannot call `onComplete()` while `onNext()` is still running. So gRPC instead buffers/blocks the onComplete callback waiting for the onNext to return. The server is free to call `onComplete()` on its side whenever, and that will be delivered after any earlier `onNext()` calls to the client (i.e., onComplete and onNext are ordered).

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
