### ISSUE TITLE
How can the server proactively disconnect the client?

### ISSUE THREAD

**Issue by rui-randolph** [grpc/grpc-java#8740]
In some cases, the server needs to close unauthorized client connections. However, I did not find a way for the server to actively disconnect the client. How do I disable the TCP connection of the grpc on the server?

**Comment by YifeiZhuang** [comment]
Not sure how you are implementing the authorization. If you are using a server interceptor, you can close the `ServerCall` inside the interceptor:
https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerInterceptor.html

or you can call .onCompleted on the server StreamObserver, like in the example:
https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java#L87

**Comment by ejona86** [comment]
If doing transport-level authentication (like mTLS), then you can require a valid client certificate and if the client can't provide one the connection will disconnect.

But it sounds like you are doing per-RPC authentication. There's no way to kill the connection for per-RPC authentication failures. Instead, fail the RPC. When using per-RPC authentication, the connection isn't tied to any particular client (e.g., there could be a proxy involved), and disconnecting the client probably would just cause extra load as the client will probably reconnect.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
