### ISSUE TITLE
libssl.so.1.0.0 cannot open shared when upgrading netty to 4.1.69.Final and tcnative to 2.0.44.Final

### ISSUE THREAD

**Issue by sleepyGeek** [grpc/grpc-java#8743]
Hi Good Day!
We just upgrade our netty version to 4.1.69.FInal, the upgrade tcnative to 2.0.44.Final..
After this, we are encountering the following issue... Any thoughts what could I been missing?
Thanks...

        Suppressed: java.lang.UnsatisfiedLinkError: /ugbu-server/temp/libnetty_tcnative_linux_x86_644324736481246331020.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
                at java.lang.ClassLoader$NativeLibrary.load(Native Method)
                at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
                at java.lang.Runtime.load0(Runtime.java:810)
                at java.lang.System.load(System.java:1086)
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:301)
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:202)
                at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
                ... 11 more
                Suppressed: java.lang.UnsatisfiedLinkError: /ugbu-server/temp/libnetty_tcnative_linux_x86_644324736481246331020.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
                        at java.lang.ClassLoader$NativeLibrary.load(Native Method)

**Comment by ejona86** [comment]
What are you upgrading from?

The io.netty:netty-tcnative package requires openssl of the right version to be installed on the machine. You have to manage the differences between fedora-like distros and non-fedora-like distros. Getting it working will be specific to your environment. That is why we recommend netty-tcnative-boringssl-static, which doesn't need openssl installed on the machine.

**Comment by sleepyGeek** [comment]
Hi @ejona86 , thank you for replying..
I'm just new is using this jar, I'm sorry if I was not able to provide enough information about this..

But, we are basically upgrading our netty-tcnative to netty-tcnative-2.0.44.Final-linux-x86_64.jar from netty-tcnative-2.0.25.Final-linux-x86_64.jar...

After upgrading, we are now encountering  "libssl.so.1.0.0: cannot open shared object file: No such file or directory"... 
As of the current time, we don't have libssl.so.1.0.0 but we have libssl.so.1.0.2 installed in our box... 
Not sure what I'm missing here, but it appears that it is looking for libssl.so.1.0.0 instead of the latest libssl.so.1.0.2...

Thanks...

**Comment by ejona86** [comment]
> from netty-tcnative-2.0.25.Final-linux-x86_64.jar

2.0.25 also depends on libssl.so.1.0.0. I expect you're changing something else as part of the upgrade that is causing the trouble. (e.g., netty-tcnative wasn't previously being used because you have some other dependency that satisfied the need.)

**Comment by sleepyGeek** [comment]
hmm, so it appears that it has hard dependency on libssl.so.1.0.0...
Will try to check other configuration... The only thing that we did is we upgrade netty libraries, to 4.1.69, and netty-tcnative to 2.0.44.Final... Thanks..

**Comment by ejona86** [comment]
@sleepyGeek, note that we recommend using the boringssl-static version of netty-tcnative so you don't have to deal with this sort of issue. The main reason to use the openssl-powered version is so that a distro-level upgrade can fix a security issue, for users that upgrade their distro for security but have harder trouble rebuilding their java binaries.

**Comment by ejona86** [comment]
Seems like this is resolved as much as it can be. If not, comment, and it can be reopened.
