### ISSUE TITLE
Pseudo header :protocol support

### ISSUE THREAD

**Issue by Blue-Hope** [grpc/grpc-java#8755]
I am implementing websocket-over-http/2, and I use envoy proxy to send http/2 request to server using grpc-java.

Referring [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#websocket-over-http-2-or-http-3-hops), when envoy sends an http/2 request, it bootstraps the websocket connection to http/2 using the header :protocol, which seems to be due to [rfc8441](https://datatracker.ietf.org/doc/html/rfc8441).

I wonder if the netty handler of grpc java handles the :protocol pseudo header (in my case, of course, an illegal error occurred), and I wonder how I can control this pseudo header without an error.

If pseudo header :protocol is not supported, I wonder if it will be added

**Comment by ejona86** [comment]
grpc-java does not support websocket-over-http/2, so the :protocol pseudo header is useless for it. It isn't clear how "websocket-over-http/2" is related to "send http/2 request to server" but I expect you'll need some conversion proxy that converts from your specialized protocol to something grpc understands.

**Comment by Blue-Hope** [comment]
ah thanks
