### ISSUE TITLE
How to get header in ClientInterceptor from response with ListenableFuture-style stub?

### ISSUE THREAD

**Issue by MrCoderYu** [grpc/grpc-java#8771]
The server responsed header,but in ListenableFuture-style stub,the ClientInterceptor runs in grpc ThreadpoolExecutor;
How can I get the header in current Thread? thanks

**Comment by sergiitk** [comment]
In simple case, you can use [`MetadataUtils.newCaptureMetadataInterceptor()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/MetadataUtils.html#newCaptureMetadataInterceptor-java.util.concurrent.atomic.AtomicReference-java.util.concurrent.atomic.AtomicReference-) helper to get the headers.

```java
AtomicReference<Metadata> headersCapture = new AtomicReference<>();
AtomicReference<Metadata> trailersCapture = new AtomicReference<>();
TestServiceGrpc.TestServiceFutureStub futureStub =
    TestServiceGrpc.newFutureStub(channel).withInterceptors(
        MetadataUtils.newCaptureMetadataInterceptor(headersCapture, trailersCapture));
Future<SimpleResponse> future = futureStub.unaryCall(request);
SimpleResponse response = future.get(5, TimeUnit.SECONDS);
Metadata headersMetadata = headersCapture.get();
```

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
