### ISSUE TITLE
Set Minimum Guava version to 18.0

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#879]
Google internally was stuck using Guava 14.0 for legacy reasons, but it appears that the restriction has been lifted.  We should set the minimum supported guava version to 18 since the older one had bugs and  performance issues.

**Comment by benmccann** [comment]
Maybe this is already done? https://github.com/grpc/grpc-java/blob/master/build.gradle#L126

**Comment by ejona86** [comment]
It's more for things like [Objects.toStringHelper](https://github.com/grpc/grpc-java/blob/6e0651643e010560c9b2555075fdf3ff3ff1a1dd/core/src/main/java/io/grpc/CallOptions.java#L160). We are using older APIs in some places for Guava 14 compatibility.
