### ISSUE TITLE
grpc forward

### ISSUE THREAD

**Issue by jacy450** [grpc/grpc-java#8793]
Can grpc  forward similar to http. Now I want to control the path of the interface call based on the information in the metadata.
such as I request /greet/hello
if metadata is {"flag": "true"}, I forward to /greet/hello
if metadata is {"flag":"false"}, I forward to /greet/hello2

**Comment by JintaoXIAO** [comment]
I think grpc can't do this or will support this neither.
for your case "/greet/hello" and "/greet/hello2" are two different services wrapped by two different "MethodDescriptor", so maybe you can do this in your own business logic.

**Comment by sanjaypujare** [comment]
@JintaoXIAO is correct. You'll have to make internal calls to achieve "forwarding".

**Comment by ejona86** [comment]
Such a thing is possible with gRPC, but would be discouraged as the method name is semantically important. If you used a generic HTTP proxy (that supports HTTP/2), you could do a rewrite like that. You can do similar things without a proxy, although it would vary depending on whether you want to do it on client or server. But again, would be heavily discouraged.

In the past, there's generally an alternative pattern that aligns better with grpc for these sorts of problems. Can you share more what the `flag` is for?

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
