### ISSUE TITLE
Retry policy doesn't work with coroutines

### ISSUE THREAD

**Issue by UDarya** [grpc/grpc-java#8796]
### What version of gRPC-Java are you using?
1.43.1

### What is your environment?
MacOS, Java 11

### Steps to reproduce the bug

Here you can find a detailed explanation. I have exactly the same problem.

**Comment by sanjaypujare** [comment]
Can you provide an example to reproduce the issue? How are you using coroutines here?

**Comment by UDarya** [comment]
Server code with coroutines:

`class NotificationGrpcService(private val notificationService: NotificationService) :
    NotificationGrpcKt.NotificationCoroutineImplBase() {

    var retryCounter = AtomicInteger(0)

    private val log = LoggerFactory.getLogger(this.javaClass)
    private val UNAVAILABLE_PERCENTAGE = 0.9f
    private val random = Random()

    override suspend fun sendPush(request: SendPushNotificationRequest): SendPushNotificationResponse {
        log.info("Received a call on method sendPushNotification with payload -> $request")

        val count: Int = retryCounter.incrementAndGet()
        if (random.nextFloat() < UNAVAILABLE_PERCENTAGE) {
            log.info("Returning stubbed UNAVAILABLE error. count: $count")
            throw StatusException(Status.UNAVAILABLE.withDescription("Method notification.Notification.SendPush is unavailable"))
        } else {
            log.info("Returning successful Hello response, count: $count")

            return SendPushNotificationResponse.newBuilder().setMessage("success").build()
        }
    }
}`

Client
`public class RetryingHelloWorldClient {
    static final String ENV_DISABLE_RETRYING = "DISABLE_RETRYING_IN_RETRYING_EXAMPLE";

    private static final Logger logger = Logger.getLogger(RetryingHelloWorldClient.class.getName());

    private final boolean enableRetries;
    private final ManagedChannel channel;
    private final GreeterGrpc.GreeterBlockingStub blockingStub;
    private final NotificationGrpc.NotificationBlockingStub blockingStubNotification;
    private final AtomicInteger totalRpcs = new AtomicInteger();
    private final AtomicInteger failedRpcs = new AtomicInteger();

    protected Map<String, ?> getRetryingServiceConfig() {
        return new Gson()
                .fromJson(
                        new JsonReader(
                                new InputStreamReader(
                                        RetryingHelloWorldClient.class.getResourceAsStream(
                                                "retrying_service_config.json"),
                                        UTF_8)),
                        Map.class);
    }

    /**
     * Construct client connecting to HelloWorld server at {@code host:port}.
     */
    public RetryingHelloWorldClient(String host, int port, boolean enableRetries) {

        ManagedChannelBuilder<?> channelBuilder = ManagedChannelBuilder.forAddress(host, port)
                // Channels are secure by default (via SSL/TLS). For the example we disable TLS to avoid
                // needing certificates.
                .usePlaintext();
        if (enableRetries) {
            Map<String, ?> serviceConfig = getRetryingServiceConfig();
            logger.info("Client started with retrying configuration: " + serviceConfig);
            channelBuilder.defaultServiceConfig(serviceConfig).enableRetry();
        }
        channel = channelBuilder.build();
        blockingStub = GreeterGrpc.newBlockingStub(channel);
        blockingStubNotification = NotificationGrpc.newBlockingStub(channel);
        this.enableRetries = enableRetries;
    }

    public void push() {
        SendPushNotificationRequest request = SendPushNotificationRequest.newBuilder().setCustomerId(UUID.randomUUID().toString()).setMessage("sdasd").setTitle("asdad").build();
        SendPushNotificationResponse response = null;
        StatusRuntimeException statusRuntimeException = null;
        try {
            response = blockingStubNotification.sendPush(request);
        } catch (StatusRuntimeException e) {
            failedRpcs.incrementAndGet();
            statusRuntimeException = e;
        }

        totalRpcs.incrementAndGet();

        if (statusRuntimeException == null) {
            logger.log(Level.INFO, "Greeting: {0}", new Object[]{response.getMessage()});
        } else {
            logger.log(Level.INFO, "RPC failed: {0}", new Object[]{statusRuntimeException.getStatus()});
        }
    }

    public static void main(String[] args) throws Exception {
        boolean enableRetries = !Boolean.parseBoolean(System.getenv(ENV_DISABLE_RETRYING));
      final RetryingHelloWorldClient client = new RetryingHelloWorldClient("localhost", 50051, enableRetries);
      
      client.push();

    }
}
`

Retry Police config

`{
  "methodConfig": [
    {
      "name": [
        {
          "service": "notification.Notification",
          "method": "SendPush"
        }
      ],

      "retryPolicy": {
        "maxAttempts": 5,
        "initialBackoff": "0.5s",
        "maxBackoff": "30s",
        "backoffMultiplier": 2,
        "retryableStatusCodes": [
          "UNAVAILABLE", "UNIMPLEMENTED"
        ]
      }
    }
  ]
}
`

Server code without coroutines:
`class NotificationGrpcService(private val notificationService: NotificationService) :
    NotificationGrpc.NotificationImplBase() {

    var retryCounter = AtomicInteger(0)

    private val log = LoggerFactory.getLogger(this.javaClass)
    private val UNAVAILABLE_PERCENTAGE = 0.9f
    private val random = Random()

    override fun sendPush(
        request: SendPushNotificationRequest?,
        responseObserver: StreamObserver<SendPushNotificationResponse>?
    ) {
        log.info("Received a call on method sendPushNotification with payload -> $request")

        val count: Int = retryCounter.incrementAndGet()
        if (random.nextFloat() < UNAVAILABLE_PERCENTAGE) {
            log.info("Returning stubbed UNAVAILABLE error. count: $count")
            responseObserver!!.onError(Status.UNAVAILABLE.withDescription("Method notification.Notification.SendPush is unavailable").asRuntimeException())
        } else {
            log.info("Returning successful Hello response, count: $count")
            responseObserver!!.onNext(SendPushNotificationResponse.newBuilder().setMessage("success").build())
            return responseObserver.onCompleted()
        }
    }
}
 `

I copied code from here: [https://github.com/grpc/grpc-kotlin/issues/277](url)
I have the same issue with my code. I can add it as well if it will help

**Comment by sanjaypujare** [comment]
It will be helpful for you to fill in details in the issue template. For this issue the only useful info was in the title. We really need to know things like "What did you expect to see?"  "What did you see instead?" and then detailed "Steps to reproduce the bug". 

For example are you able to get retry to work with some combination of grpc java client and server?

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
