### ISSUE TITLE
When the relase include Netty 4.1.68+

### ISSUE THREAD

**Issue by jackycdc** [grpc/grpc-java#8827]
Hi gRPC team,
I saw https://github.com/grpc/grpc-java/issues/8617 been closed.
In the latest 1.43.2, the netty version still is 4.1.63.Final (it is 4.1.72.Final in master branch). 
May I know when will have a release to include the 4.1.68+ version of netty?

**Comment by ejona86** [comment]
It is scheduled for 1.44.0, planned for two weeks. But there is no need to wait on us. See my comments in #8803.
