### ISSUE TITLE
How can the gRPC client create socket connect When create stub or channel

### ISSUE THREAD

**Issue by zt9788** [grpc/grpc-java#8838]
I want create socket connectoin when create stub or channel  
version: 1.43.2
demo:
```
       NettyChannelBuilder builder = (NettyChannelBuilder)((NettyChannelBuilder)NettyChannelBuilder.forAddress("xxxx",1234).usePlaintext().
                        keepAliveWithoutCalls(true).directExecutor();
        ManagedChannel ch = builder.build();
        //==> I want to create scoket connect here or channel build 
        ServiceGrpc.ServiceBlockingStub stub = ServiceGrpc.newBlockingStub(ch).withWaitForReady();        
        //===> I test gRPC will create connect in call some method
        stub.grpcPing(request.newBuilder().build());
```

**Comment by sergiitk** [comment]
Short answer: use [io.grpc.ManagedChannel#getState](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannel.html#getState-boolean-) with `requestConnection` set to `true`.

Long answer: take a look at this great note by @markdroth on why it might not be a good idea, and why it's better to react to individual RPC failures:  https://stackoverflow.com/questions/64484690/grpc-cpp-how-can-i-check-if-the-rpc-channel-connected-successfully

**Comment by zt9788** [comment]
Thank you for your reply!
For some historical reasons, I use the common pool2 to  create grpc client,but when add pool there is have no connection(NettyChannelBuilder.build()).
I try to use channel.getState(true) but sometimes there have connect ,sometimes is not? Should i  set other propteries in NettyChannelBuilder?

**Comment by dapengzhang0** [comment]
@zt9788 

You may need to use `ManagedChannel.notifyWhenStateChanged()` together with `channel.getState(true)` to block until connection is READY.

For example (warning: just an silly example, maybe bad in worst scenario)

```java
private CountdownLatch latch = new CountdownLatch(1);

private void ping() {
  checkState();
  latch.await();
  // make new RPC now
}
``` 

```java
private void checkState() {
  ConnectivityState state = channel.getState(true);
  if (state != READY || state != SHUTDOWN) {
    ManagedChannel.notifyWhenStateChanged(state, ::checkState)
  } else {
    latch.countDown();
  }
}
```

**Comment by ejona86** [comment]
Seems like this is likely resolved. If not, comment, and it can be reopened.

**Comment by zt9788** [comment]
I just get this message ,thanks very much.
