### ISSUE TITLE
AndroidChannel fails to reconnect after block

### ISSUE THREAD

**Issue by litclimbing** [grpc/grpc-java#8850]
I'm having issues with Firestore (which uses gRPC) not connecting after a device is locked and was able to track it down to here.

https://github.com/grpc/grpc-java/blob/a35336c15fe3235b14a16af117515e113c8d5cee/android/src/main/java/io/grpc/android/AndroidChannelBuilder.java#L297

It seems that the network callback needs to override the onBlockedStatusChanged() function and reconnect when the blocked parameter is false.

I'm seeing onAvailable() only called when my app initially starts but onBlockedStatusChanged() is called with true when it has been idle for a while and false when it comes back up. This was tested on Android 12.

**Comment by litclimbing** [comment]
For what it's worth, I made a local fork and added the hook. I then forced Firebase to use the updated version and it fixed my issue.

`    /** Respond to changes in the default network. Only used on API levels 24+. */
    @TargetApi(Build.VERSION_CODES.N)
    private class DefaultNetworkCallback extends ConnectivityManager.NetworkCallback {
      @Override
      public void onAvailable(Network network) {
        delegate.enterIdle();
      }
      @Override
      public void onBlockedStatusChanged (Network network, boolean blocked) {
        if (!blocked)
          delegate.enterIdle();
      }
    }`

**Comment by dapengzhang0** [comment]
@litclimbing Can you send out a PR for the fix?
