### ISSUE TITLE
Interceptors skipped when the client aborts

### ISSUE THREAD

**Issue by stefanfrings2** [grpc/grpc-java#8868]
I'm using io.grpc 1.43.2 on a Kubernetes Cluster with Linux, OpenJDK 11.0.13 64 bit, using Spring Boot framework. To generate Java code I used the Maven plugin org.xolstice.maven.plugins/protobuf-maven-plugin with io.grpc:protoc-gen-grpc-java 1.4.0 and com.google.protobuf:protoc:3.3.0.

My issue is that my GRPC service functions are sometimes called without executing the related interceptors first.

I created a GRPC service inside a Spring Boot application that needs some interceptors:
```
Server server = ServerBuilder.forPort(grpcPort)
  .addService(ServerInterceptors.intercept(grpcService, grpcTokenInterceptor, headerInterceptor, grpcRequestContextInterceptor))
  .addService(ProtoReflectionService.newInstance())
  .build();
server.start();
```
All 4 classes (grpcService, grpcTokenInterceptor, headerInterceptor, grpcRequestContextInterceptor) output a debug message before doing any work. Normally I can see proper order of calls in the log:
```
2022-01-26T10:07:56.414+0000 com.mvneco.ecobc.payment.facade.grpc.GrpcRequestContextInterceptor interceptCall()
2022-01-26T10:07:56.414+0000 com.mvneco.ecobc.payment.facade.grpc.GrpcHeaderInterceptor interceptCall()
2022-01-26T10:07:56.414+0000 com.mvneco.ecobc.payment.facade.grpc.GrpcHeaderInterceptor interceptCall()
2022-01-26T10:07:56.419+0000 com.mvneco.ecobc.payment.facade.grpc.GrpcService getVoucherInfo()
```

When my **grpcTokenInterceptor** produces an exception due to bad input, then I can see a nice stack trace which shows the interceptors:
```
com.mvneco.ecobc.payment.facade.grpc.GrpcTokenInterceptor.interceptCall(GrpcTokenInterceptor.java:54)
io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
com.mvneco.ecobc.payment.facade.grpc.GrpcHeaderInterceptor.interceptCall(GrpcHeaderInterceptor.java:57)
io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
com.mvneco.ecobc.payment.facade.grpc.GrpcRequestContextInterceptor.interceptCall(GrpcRequestContextInterceptor.java:34)
io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:703)
io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:406)
io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:615)
io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)
io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:834)
```

When my **grpcService** produces an exception, I get this stack trace which shows how the service function gets called:
```
com.mvneco.ecobc.payment.facade.grpc.GrpcService.getVoucherInfo(GrpcService.java:109)
mvneco.ecobc.payment.PaymentGrpcServiceGrpc$MethodHandlers.invoke(PaymentGrpcServiceGrpc.java:1044)
io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:340)
io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)
```

Everything is fine until here. The interceptoprs and the service are called in the expected order.

But during load-tests, my **grpcService** is sometimes called without interceptors. Then my class aborts with an exception due to missing data from the interceptors that have not been called. In these few cases, the log shows that the interceptors have not been executed:
```
2022-01-26T10:07:56.311+0000 com.mvneco.ecobc.payment.facade.grpc.GrpcService getVoucherInfo()
```

This is the first message of the affected thread (after program start).

I repeated the load test several times and it seems that the issue happens only 1x on the first message per thread. But not always, only sometimes. Some threads produce the error 1x while other threads work fine at the same time.

My guess: Maybe the trigger of that issue is that the network connection got reset by the client, before the message got processed by the server. See attached screenshot of a network trace which we created on the server:

![tcpdump](https://user-images.githubusercontent.com/36876920/151166616-1ab7fc13-cdf2-483e-8b59-ebbf4cd8ffa3.png)

Now I'm stuck here. I'm not sure if this is a bug on server side, or client side or a misunderstanding of myself.

How can I find out why my interceptors have not been executed? Is there any condition that must be fulfilled?
I tried to find the answer in the source code but failed. 

It would be great if you can help me to analyze this issue further. My biggest problem is that it happens only seldom and only during load tests. I did not find a way to trigger the issue manually.

**Comment by stefanfrings2** [comment]
I found out that `Context.current().isCancelled()` returns false when this happens.

**Comment by ejona86** [comment]
Architecturally it is not possible for your interceptors to be skipped. Interceptors wrap your service and become the service passed to `addService()`, essentially. I expect that if you produced a stack trace for the broken cases you'd see the stack looks correct.

Those log statements could be quite easy to misread, because there is no way to associate the logs _per RPC_. It just says "this interceptor was run" but without associating it with a call.

> I repeated the load test several times and it seems that the issue happens only 1x on the first message per thread.

We have seen reports of slower processing of the first message on a thread due to Netty ByteBuffer caching initialization. So what you may be seeing here is a timing difference that perturbs something else in the code. And this would also perturb the logs, making them harder to read.

> Then my class aborts with an exception due to missing data from the interceptors that have not been called.

"missing data" sounds like you are passing data between interceptors. How are you doing that? Given the problem you are facing, I'd expect you are probably using a ThreadLocal. If using ThreadLocal, see https://stackoverflow.com/a/56842315/4690866 . If you explain your specific ThreadLocal usage, we can maybe recommend alternative patterns.

**Comment by stefanfrings2** [comment]
> there is no way to associate the logs per RPC. It just says "this interceptor was run" but without associating it with a call.

Interesting point. I thought the can be associated the the thread ID.

> you are passing data between interceptors. How are you doing that?

Via a custom Request scope in Spring, which is a ThreadLocal variable. I will follow your link to StackOverflow.

**Comment by stefanfrings2** [comment]
It work fine now. Instead of Spring request context, I do now use the GRPC Context class to pass over data from the interceptors to the service implementation.

In my interceptor:
```
@Autowired
private ConfigurableBeanFactory beanFactory;  //From Spring framework

@Autowired
private CurrentRequest currentRequest;  // A custom bean with @RequestScope

// Create a request scope for Spring
MyRequestAttributes requestAttributes = new MyRequestAttributes();
RequestScope requestScope = new RequestScope();
RequestContextHolder.setRequestAttributes(requestAttributes);
beanFactory.registerScope(WebApplicationContext.SCOPE_REQUEST,requestScope);

// Store some data in currentRequest
currentRequest.getRemoteIp(...);
currentRequest.getTraceId(...);
currentRequest.getRequestId(...);
currentRequest.setAccessToken(...);

// Copy the request scope to GRPC context. This is needed to pass it over to the GrpcService.
Context ctx = Context.current()
    .withValue(AdditionalGrpcConstants.SPRING_REQUEST_ATTRIBUTES, requestAttributes)
    .withValue(AdditionalGrpcConstants.SPRING_REQUEST_SCOPE, requestScope);

return Contexts.interceptCall(ctx, serverCall, headers, serverCallHandler);
```

In my service implementation, I do this on each incoming request:
```
// Replace the Spring request scope by the correct one from GRPC context (which was created by GrpcRequestContextInterceptor).
MyRequestAttributes requestAttributes = AdditionalGrpcConstants.SPRING_REQUEST_ATTRIBUTES.get();
RequestScope requestScope = AdditionalGrpcConstants.SPRING_REQUEST_SCOPE.get();
RequestContextHolder.setRequestAttributes(requestAttributes);
beanFactory.registerScope(WebApplicationContext.SCOPE_REQUEST, requestScope);

// Also replace logger context to avoid using wrong data from previous request
LogBuffer.clear();
MDC.clear();
MDC.put("X-Real-IP", currentRequest.getRemoteIp());
MDC.put("X-Trace-ID", currentRequest.getTraceId());
MDC.put("X-Request-ID", currentRequest.getRequestId());
```

After that, I have a valid Spring request Scope and can access all request scoped objects as usual in a Spring Weg application.

Explanation:

RequestContextHolder and ConfigurableBeanFactory are part of the Spring framework. They hold the attributes of each request in ThreadLocal variables. Most service functions of my application can be called via both GRP and REST, therefore I want to re-use some Spring specific stuff also in the GRPC facade. Both facades do finally call the same implementation.

MyRequestAttributes class is a simple HashMap which is used by the Spring framework under the hood to store beans that are annotated with @RequestScope or @SessionScope. In a Spring Web application, this class instance would be provided by the Spring framework, but fin case of GRPC I need to provide my own one.

CurrentRequest is a custom bean annotated with @RequestScope. I use it to make some common data available to the whole application. The remoteIp, traceId, requestId and accessToken above are only examples. The real application has some more attributes in this class.

Because the CurrentRequest bean is annotated with @RequestScope, Spring replaces each access via "currentRequest" by a generated "getCurrentRequest()" method, which gets it from the requestScope, which effectively gets it from requestAttributes. In case of GRPC, they are passed over from interceptor to the service via GRPC Context, so I always access the right instance which belongs to the current request.

Our load-test runs successfully now.
