### ISSUE TITLE
A significant percentage of Client calls fail randomly.

### ISSUE THREAD

**Issue by umapriyadarsi** [grpc/grpc-java#8876]
Majority of the calls from client to server work just fine. However, a significant percentage of the client calls are failing on the client side with the following exception:

![image](https://user-images.githubusercontent.com/3054787/151757401-296d86c7-aa29-4a88-bb68-2a7509aaa534.png)

![image](https://user-images.githubusercontent.com/3054787/151758428-7d0ac825-7281-4e8d-b806-0bc40f4f6662.png)

Both my client and server are running on the same machine with the same set of dependencies(both use grpc-java 1.43.1 , same jdk 17 etc.)

This is how the workflows looks like:
1. Client makes a unary request and server responds in a stream.
2. The request is split into multiple sub-tasks on the server. Each sub-task is actually a class implementing Callable interface. The thread on which the RPC request from client landed, invokes these list of sub-tasks classes using a ThreadPoolExecutor : 
Future future = dispatchController.execute(Context.current().wrap(taskImpl));

As is evident, I have also wrapped the taskImpl(implements Callable interface) with Context method. (Based on the point 5, I trust doing this is right?)

3. The "main" thread(upon which the client RPC request landed) then goes into ... .wait()
synchronized (LOCK_OBJ) {
	TASK_RUN_STATUS = 3;;//all tasks done
	. . .
	. . .
	. . .
	while(...){
		. . .
		Future future = dispatchController.execute(Context.current().wrap(taskImpl));
		TASK_RUN_STATUS = 1;//tasks triggered
		. . .
	}
	. . .
	. . .
	. . .
	if(TASK_RUN_STATUS == 1){
		CmpsLogger.TASKS.log(Level.INFO,"going into wait");
		while (TASK_RUN_STATUS == 1){
			LOCK_OBJ.wait();
		}
		CmpsLogger.TASKS.log(Level.INFO,"wait over");
		checkAndPopulateNewTasks(curTasks);// TODO: monitor for long running tasks.
	}
}

4. The taskImpl(implementing Callable interface) is designed to notify the "main" thread after it finishes it's workflow, as follows:
	synchronized (LOCK_OBJ){
            if (TASK_RUN_STATUS == 1){
                TASK_RUN_STATUS = 2;//incoming task impl notifying
                CmpsLogger.TASKS.log(Level.INFO,"notifying");
                LOCK_OBJ.notify();
            }
        }

5. The taskImpl also sends messages/responses to the client from the executor thread using onNext(...) method of StreamObserver. 
My **suspicion** based on my observations is that, the requests which fail are due to this. 
The point to note here is that, on the server side, there are no exceptions or errors. The error or exception is seen solely on the client side(unless I have missed something on the server side logs).

6. To test it further, I added the client call in a loop of 100 runs, to see how many succeed and how many fail. I would get results like this:
successCount : 86 failureCount 14|
successCount : 73 failureCount 27|
successCount : 74 failureCount 26|
successCount : 82 failureCount 18|
successCount : 94 failureCount 6|

Either this is a bug, or I am missing something.
Any pointers on how to proceed would help.

Before raising this issue, I have also checked on the following answers by @ejona86 and @carl-mastrangelo 
https://groups.google.com/g/grpc-io/c/1Y1C1QMqsFc
https://stackoverflow.com/questions/57110811/grpc-random-cancelled-exception-on-rpc-calls
https://stackoverflow.com/questions/43511228/grpc-future-callback-got-exceptionstatusruntimeexception-cancelled

### What version of gRPC-Java are you using?
I assume it is 1.43.1 based on the following:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/3054787/151758300-f3d91f56-c79f-4f84-ad1a-ff9a9182fc8d.png">

### What is your environment?
M1 MacOS Monterey

JDK 17
jre % ./bin/java -version
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)

proto3

### What did you expect to see?
successCount : 100 failureCount 0|

### What did you see instead?
successCount : 86 failureCount 14|

### Steps to reproduce the bug
Don't have one right now. I hope the problem description with the workflow should be a good start?

**Comment by dapengzhang0** [comment]
Looks like the response data is corrupted. 

```
The taskImpl also sends messages/responses to the client from the executor thread using onNext(...) method of StreamObserver.
```

Can you double check and make sure that `onNext()` is invoked sequentially, not concurrently on multiple threads?

**Comment by umapriyadarsi** [comment]
@dapengzhang0 I made a few changes which ensure that only thread at a time invokes `onNext()`. and that seems to solve the case.

On further thought, it does make sense that messages are sent sequentially and not concurrently.

However, wouldn't it benefit to do this synchronization on the framework level? I.E how would it be, if concurrent method calls to invoke `onNext()` are synchronised by StreamObserver, since sequential invocations seems to be the only right way to do it?

**Comment by dapengzhang0** [comment]
> However, wouldn't it benefit to do this synchronization on the framework level? I.E how would it be, if concurrent method calls to invoke onNext() are synchronised by StreamObserver, since sequential invocations seems to be the only right way to do it?

We don't support sending messages concurrently. If we synchronized `onNext` in the library, it will randomly reorder concurrent messages, and may also hide application's bug.

**Comment by umapriyadarsi** [comment]
Thanks, that solves my query.. closing this issue.

**Comment by ejona86** [comment]
> how would it be, if concurrent method calls to invoke onNext() are synchronised by StreamObserver, since sequential invocations seems to be the only right way to do it?

Since the application almost always needs to synchronize _itself_ to send messages in a clearly-defined order (also including things like onComplete() and onError()), we don't think _everyone_ should pay the cost of gRPC doing the synchronization for the few cases that could partly work with built-in synchronization.

**Comment by umapriyadarsi** [comment]
@ejona86 right on. I agree, considering these points as well.
