### ISSUE TITLE
How  to enable PerfMark in grpc-java?

### ISSUE THREAD

**Issue by haojinming** [grpc/grpc-java#8893]
I'm using grpc-java to do my project, and some perfmance jittery occur in my project. I see PerfMark is one useful tool to debug performance problem. However I did not find how to enable and ouput html report.
Could someone help explain  this?

**Comment by sanjaypujare** [comment]
These links have the documentation:

https://www.perfmark.io/
https://github.com/perfmark/perfmark

Hope that helps.

**Comment by haojinming** [comment]
These helps a lot, thanks.
