### ISSUE TITLE
gRPC-Java to support QUIC

### ISSUE THREAD

**Issue by larspaulsen** [grpc/grpc-java#8897]
gRPC-Java to support QUIC

### Use case(s) - what problem will this feature solve?
By gRPC-Java supporting QUIC the following primary goals will be achieved:

1. Elimination of head-of-line issue.
2. Seamless switching between underlying IP infrastructure, such as Cellular and Wi-Fi media.
3. Support of zero round-trip connection reestablishment.

### Proposed Solution
gRPC-Java to support QUIC

### Alternatives Considered
None

### Additional Context
gRPC .NET 6 already provides support for QUIC:
https://devblogs.microsoft.com/dotnet/http-3-support-in-dotnet-6/#grpc-with-http-3

.NET Implemented 'Proposal':
https://github.com/JamesNK/proposal/blob/jamesnk/http3/G2-http3-protocol.md

**Comment by sanjaypujare** [comment]
The proposal you cite is already a "grfc": https://github.com/grpc/proposal/blob/master/G2-http3-protocol.md and provides guidance for language implementations. So it is just a matter of prioritization for grpc-java to do this. (CC @ejona86)

> ...
> gRPC .NET 6 already provides support for QUIC: https://devblogs.microsoft.com/dotnet/http-3-support-in-dotnet-6/#grpc-with-http-3

The link above has this: "gRPC over HTTP/3 is not yet a standard, and is [proposed](https://github.com/grpc/proposal/pull/256) by the .NET team."  - not sure if the implementation is complete.

**Comment by ejona86** [comment]
For many years there's been gRPC over QUIC (pre-HTTP/3) on mobile via Cronet. gRPC servers generally don't support QUIC, but in such settings you already want a reverse proxy for load balancing and that proxy can convert from QUIC to HTTP/3. So if you want this on mobile, which is the "killer app for HTTP/3", then "it's pretty much already there." The main use case for (2) is for mobile, so this seems already satisfied.

(3): 0-RTT would benefit only a subset of applications and requires additional changes. When using 0-RTT the initial requests can be replayed, which is not secure for many RPCs. 0-RTT is only appropriate for "safe" (changes no state) RPCs. gRPC would need to pick up the work again to support GET in addition to the normal POST. (There was earlier work to support PUT, for reduced RTT, but it was abandoned after the replay considerations.) Nothing prohibits this work from moving forward again with our current level of QUIC support.

QUIC does provide reduced RTT connection establishment and configurable head-of-line blocking. But it is a serious task to implement and probably needs HTTP/2 as a fallback. In time, it may not be too hard to experiment with HTTP/3 via Netty (we need some sizable changes in grpc-java to get there, though, but those are independent of QUIC). But it's unclear how much we'll invest in it.

This is a long-term item, and mostly cross-language (as far as "do we want to spend the effort"). I'm closing this in favor of the existing cross-language issue grpc/grpc#19126.

**Comment by larspaulsen** [comment]
My bad, I should have written HTTP/3 in the header of the feature request, I thus corrected wording above.

**Comment by ejona86** [comment]
Meh. It's mostly all the same for these discussions. Anything that supported QUIC before the rename generally is following along with QUIC+HTTP/3. I only pointed out "pre-HTTP/3" to make clear there's been support for quite a while.
