### ISSUE TITLE
io.grpc.xds.XdsServerWrapperTest.shutdown_inflight is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#8908]
https://github.com/grpc/grpc-java/runs/5130391288 had a surprising failure. This run was for the 1.43.x branch, but the test looks the same as master, thus filing.

```
io.grpc.xds.XdsServerWrapperTest > shutdown_inflight FAILED
    org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
    Boolean cannot be returned by shutdown()
    shutdown() should return Server
    ***
    If you're unsure why you're getting above error read on.
    Due to the nature of the syntax above problem might occur because:
    1. This exception *might* occur in wrongly written multi-threaded tests.
       Please refer to Mockito FAQ on limitations of concurrency testing.
    2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
       - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.
        at io.grpc.xds.XdsServerWrapperTest.shutdown_inflight(XdsServerWrapperTest.java:271)
```

Seems like the "This exception *might* occur in wrongly written multi-threaded tests." explanation is most likely.

If this remains the only flake we see, then we shouldn't spend too much time on it. But it is probably worth a glance and then we can close the issue. We can reopen this issue if it happens more often.

CC @sanjaypujare

**Comment by ejona86** [comment]
Haven't seen this recently. I don't see evidence that we fixed the test, but maybe a mockito upgrade fixed the problem.

**Comment by kumarakshays** [comment]
> Haven't seen this recently. I don't see evidence that we fixed the test, but maybe a mockito upgrade fixed the problem.

Yes @ejona86 even I am unable to reproduce this issue even after running the complete test class(XdsServerWrapperTest.shutdown_inflight) in my local environment for 1000 times (by using a for loop) it is working as expected and I don't see any test failures/flaky.
