### ISSUE TITLE
Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed

### ISSUE THREAD

**Issue by trajano** [grpc/grpc-java#8927]
### What version of gRPC-Java are you using?
```
❯ mvn dependency:tree | grep grpc
[INFO] +- io.grpc:grpc-protobuf:jar:1.35.0:compile
[INFO] |  +- io.grpc:grpc-api:jar:1.35.0:compile
[INFO] |  |  \- io.grpc:grpc-context:jar:1.35.0:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:2.0.1:compile
[INFO] |  +- io.grpc:grpc-protobuf-lite:jar:1.35.0:compile
[INFO] +- io.grpc:grpc-stub:jar:1.35.0:compile
[INFO] +- io.zipkin.brave:brave-instrumentation-grpc:jar:5.13.2:compile
[INFO] +- io.grpc:grpc-netty-shaded:jar:1.35.0:runtime
[INFO] |  \- io.grpc:grpc-core:jar:1.35.0:runtime
```

### What is your environment?

Linux in Docker

### What did you expect to see?

No errors

### What did you see instead?
```
io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.Status.asRuntimeException(Status.java:534)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
(No further stack trace to indicate the cause)

### Steps to reproduce the bug

I've been using GRPC for a while now, I saw this error when I started to do "streaming".  The weird part is the messages are successfully received and processed on both ends, but this error comes up on the client and no error indicated on the server.

I built a channel like this (I tried to the point where there is no interceptor code so I got the error you see above) but I do use 

```
    public ManagedChannel buildChannel(ServerInfo serverInfo) {
        return ManagedChannelBuilder.forAddress(serverInfo.getHostname(), 6565)
            .usePlaintext()
            .enableRetry()
            .maxRetryAttempts(5)
            .build();
    }
```

Server side (took out my interceptors which I use for tracing and logging)

```
        final ServerBuilder<?> serverBuilder = ServerBuilder
            .forPort(grpcPort);

        threadPool = Executors.newFixedThreadPool(threadPoolSize);
        serverBuilder.executor(threadPool);
        serverBuilder.maxInboundMessageSize(messageLimitInBytes);

        for (final BindableService bindableService : bindableServices) {
            serverBuilder.addService(
                    bindableService,
            );
        }
        server = serverBuilder.build();
        server.start();
```

I'm tried to see if I can create a small test scenario for this in https://github.com/trajano/grpc-chunker-java  which I have a test for but it is not manifesting

https://github.com/trajano/grpc-chunker-java/blob/b3a80af42071b82ae7763b5ab48ed7e85ef0b1a0/src/test/java/net/trajano/grpcchunker/withproto/GrpcStreamTest.java#L45-L58

I looked through https://github.com/grpc/grpc-java/issues?q=io.grpc.StatusRuntimeException%3A+UNKNOWN but I didn't see anything that matches what I have exactly.

**Comment by ejona86** [comment]
The gRPC client library doesn't generate a status like that. That is being delivered from the server. The server is the component that should know what is going on.

The most common case for this I've seen is when the server throws an exception. But that would also be logged.

**Comment by trajano** [comment]
Took a bit to find but because the server was steraming as well it went on even after it got an error.  So I made the change to throw an exception 

https://github.com/trajano/grpc-chunker-java/blob/a69612e3dabda42e8508ead7bcf82c86d37129f5/src/main/java/net/trajano/grpcchunker/DechunkingStreamObserver.java#L114-L121

```
    if (throwable instanceof RuntimeException) {
      throw (RuntimeException) throwable;
    } else {
      throw Status.fromThrowable(throwable)
          .augmentDescription(throwable.getMessage())
          .asRuntimeException();
    }
  }
```

Secondly I augmented the description I incorrectly assumed `fromThrowable` will put that in so I explicitly added it so I can see the error on the client side.
