### ISSUE TITLE
grpc compiler can't compatible with MAC M1

### ISSUE THREAD

**Issue by Walter-DEL** [grpc/grpc-java#8957]
qm-bpg0234@Walter grpc-java-master % ./gradlew build       
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

> Task :grpc-benchmarks:test

io.grpc.benchmarks.driver.LoadWorkerTest > runUnaryBlockingClosedLoop FAILED
    java.lang.AssertionError: Server failed to start
        at org.junit.Assert.fail(Assert.java:88)
        at io.grpc.benchmarks.driver.LoadWorkerTest.startServer(LoadWorkerTest.java:257)
        at io.grpc.benchmarks.driver.LoadWorkerTest.runUnaryBlockingClosedLoop(LoadWorkerTest.java:73)

5 tests completed, 1 failed

> Task :grpc-benchmarks:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grpc-benchmarks:test'.
> There were failing tests. See the report at: file:///Users/qm-bpg0234/IdeaProjects/grpc-java-master/benchmarks/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
160 actionable tasks: 15 executed, 145 up-to-date

**Comment by ejona86** [comment]
I thought we already had an M1 issue open, but couldn't find it, so I reopened #7690.

Currently the expectation is you use the amd64 binaries with Rosetta. You can try to build directly on an M1 mac, but I don't expect it'd work. I don't know why benchmarks failed, but you don't need it. You just need `./gradlew :grpc-compiler:build`

**Comment by Walter-DEL** [comment]
I still get an error

**Comment by ejona86** [comment]
What error?

**Comment by Walter-DEL** [comment]
qm-bpg0234@walter grpc-java-master % ./gradlew :grpc-compiler:build  
Starting a Gradle Daemon (subsequent builds will be faster)
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

FAILURE: Build failed with an exception.

* What went wrong:
Project 'grpc-compiler' not found in root project 'grpc'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

**Comment by Walter-DEL** [comment]
qm-bpg0234@walter grpc-java-master % ./gradlew :grpc-compiler:build
*** Android SDK is required. To avoid building Android projects, set -PskipAndroid=true

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/qm-bpg0234/IdeaProjects/grpc-java-master/android/build.gradle' line: 47

* What went wrong:
A problem occurred evaluating project ':grpc-android'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/qm-bpg0234/IdeaProjects/grpc-java-master/local.properties'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by ejona86** [comment]
You removed `skipAndroid=true` at the same time.

> *** Android SDK is required. To avoid building Android projects, set -PskipAndroid=true

Previously you had it:

> Skipping the build of Android projects because skipAndroid=true

Follow the instruction and use `-PskipAndroid=true`

**Comment by ejona86** [comment]
Haven't heard back, so nothing more to do here. If you have further problems, comment, and we can reopen.
