### ISSUE TITLE
Add authority to HandlerRegistry.lookupMethod

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#898]
It should be possible to do virtual hosting; that requires authority. It would just be an additional string to lookupMethod (presumably as the first parameter).

**Comment by ejona86** [comment]
(We may cheat and pass `null` today as the authority.)

**Comment by carl-mastrangelo** [comment]
@ejona Clarification:  are methods per authority, or are Services per authority?

**Comment by ejona86** [comment]
Services would be per-authority, but for this let's only update `HandlerRegistry.lookupMethod`; let's not add support for it in `MutableHandlerRegistry`.
