### ISSUE TITLE
ServerBuilder should expose keepalive methods from NettyServerBuilder

### ISSUE THREAD

**Issue by liamcassidy-eb** [grpc/grpc-java#8991]
Hello,

We've been encountering issues with connections getting closed. Eric Anderson recommended adjusting keep-alive settings on the server and client ([here](https://gitter.im/grpc/grpc?at=622f8603f43b6d783fff8ad2)). However, when I went to configure these settings, I couldn't find any documentation on it or examples on the grpc kotlin side. Could you help point me to how we can configure the server-side options mentioned in [the keep alive docs](https://github.com/grpc/grpc/blob/master/doc/keepalive.md)?

We've also asked this in grpc-kotlin here and thought that it would be helpful to ask on the java side as grpc-kotlin has the same API for server building as grpc-java. You can find further context in that issue as well.
issue: https://github.com/grpc/grpc-kotlin/issues/331

@ejona86 mentioned that this might be related to 
> Looks like the keepalive API is only on NettyServerBuilder, not ServerBuilder. 

Please let us know if you need any further information and we'll get that to you ASAP! 🙏

**Comment by faculbsz-sg** [comment]
Hi, do you mind sharing your grpc, protobuf, netty dependencies versions for your kotlin service?
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty

**Comment by liamcassidy-eb** [comment]
Hello, we're using:
```
+--- io.grpc:grpc-netty-shaded:1.40.1
```

As for protobufs is there something, in particular, you would need to look at? Happy to share generic examples but I want to be careful about what we expose as this is an internal API.

**Comment by ejona86** [comment]
NettyServerBuilder has the appropriate API. You'd need to use the APIs io.grpc.netty.NettyServerBuilder (and swap to grpc-netty) or the questionable io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder (to continue with grpc-netty). Neither option is great as grpc-netty-shaded is much preferred over grpc-netty but nominally it doesn't really expose a public API.

As a short-term "get it working." Using io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder is probably fair. But we need to add the keepalive methods to io.grpc.ServerBuilder.
