### ISSUE TITLE
grpc unary call performance and doubt on bi-directional streaming client-side implementation

### ISSUE THREAD

**Issue by k0p038x** [grpc/grpc-java#8994]
I'm trying to solve the following problem using grpc. we have one ml service which returns positivity score given a text. 
On the client side, we will receive multiple texts parallely and we need to get the score from ml service for each of those texts
I implemented that using unary calls with python on grpc server side and java on client side. 

Couple of questions on this,  
- I see in docs that we can share the same channel across multiple stubs/client objects. how to know the maximum requests a channel can handle? 
- how to get to know the time taken at each step for every grpc call? like time taken to create connection, time taken to send the request and so on. Any tool I can use to track things like these?
- Can I look into bi-directional streaming instead of using unary calls with multiple clients and channels?

And one more basic question, how to implement request-response kind of model in bi-directional streaming. I'm looking only for the basic idea of client side implementation using grpc-java. How do we get to know the response of a particular request in bi-directional streaming without passing some identifier for every request and mapping the response through that id?

**Comment by sanjaypujare** [comment]
> ...
> 
> Couple of questions on this,
> 
> * I see in docs that we can share the same channel across multiple stubs/client objects. how to know the maximum requests a channel can handle?

With NettyServerBuilder you can use [maxConcurrentCallsPerConnection(int maxCalls)](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L397) 

This is the same as setting MAX_CONCURRENT_STREAMS per connection.

> * how to get to know the time taken at each step for every grpc call? like time taken to create connection, time taken to send the request and so on. Any tool I can use to track things like these?

perfMark

https://www.perfmark.io/
https://github.com/perfmark/perfmark

> * Can I look into bi-directional streaming instead of using unary calls with multiple clients and channels?

Each bidi call will be associated with one particular client/connection but you can create multiple bidi calls on the connection.

> 
> And one more basic question, how to implement request-response kind of model in bi-directional streaming. I'm looking only for the basic idea of client side implementation using grpc-java. How do we get to know the response of a particular request in bi-directional streaming without passing some identifier for every request and mapping the response through that id?

You will have to incorporate that in your application request/response messages e.g. each request message contains a unique id which is referenced by the response for the request.

**Comment by k0p038x** [comment]
> > 
> > * I see in docs that we can share the same channel across multiple stubs/client objects. how to know the maximum requests a channel can handle?
> 
> With NettyServerBuilder you can use [maxConcurrentCallsPerConnection(int maxCalls)](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L397)
> 
> This is the same as setting MAX_CONCURRENT_STREAMS per connection.
> 
but my question is like how do we get to know this value? any standard tests to find the perfect value for this variable?

> > * Can I look into bi-directional streaming instead of using unary calls with multiple clients and channels?
> 
> Each bidi call will be associated with one particular client/connection but you can create multiple bidi calls on the connection.
> 
> > And one more basic question, how to implement request-response kind of model in bi-directional streaming. I'm looking only for the basic idea of client side implementation using grpc-java. How do we get to know the response of a particular request in bi-directional streaming without passing some identifier for every request and mapping the response through that id?
> 
> You will have to incorporate that in your application request/response messages e.g. each request message contains a unique id which is referenced by the response for the request.

Umm, I also thought of same solution but just wanted to know if there is any standard alternative which won't involve passing extra parameter like identifier

**Comment by sanjaypujare** [comment]
> ...
> but my question is like how do we get to know this value? any standard tests to find the perfect value for this variable?

Not aware of any standard tests as this is highly dependent on your environment and the application. There is an SO article that talks about max_concurrent_streams but not in the gRPC context https://stackoverflow.com/questions/68781943/appropriate-max-concurrent-streams-value-of-http2

> ...
> Umm, I also thought of same solution but just wanted to know if there is any standard alternative which won't involve passing extra parameter like identifier

Note that in case of bidi streaming the response and request messages are not related. As an example client can send 5 request messages but the server will send only one response message so there is no request to response message correlation in the protocol.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
