### ISSUE TITLE
ManagedChannelBuilder#directExecutor javadoc looks copy-pasted and needs refinement

### ISSUE THREAD

**Issue by Spikhalskiy** [grpc/grpc-java#9013]
Right now `ManagedChannelBuilder#directExecutor` javadoc looks like a direct copy-paste of `ServerBuilder#directExecutor`:

```
  /**
   * Execute application code directly in the transport thread.
   *
   * <p>Depending on the underlying transport, using a direct executor may lead to substantial
   * performance improvements. However, it also requires the application to not block under
   * any circumstances.
   *
   * <p>Calling this method is semantically equivalent to calling {@link #executor(Executor)} and
   * passing in a direct executor. However, this is the preferred way as it may allow the transport
   * to perform special optimizations.
   *
   * @return this
   * @since 1.0.0
   */
```

While this description makes total sense for the server configuration, it doesn't make much sense for a channel.

"Execute application code directly in the transport thread." probably may be replaced with "Execute gRPC transport code directly in the caller thread."

"However, it also requires the application to not block under any circumstances." probably may be replaced with something like "However, it may keep a caller thread for longer if FutureStubs are used".

**Comment by ejona86** [comment]
The javadoc looks correct. Both client and server behave the same way here. This executor is used for callbacks into the application, not for performing transport operations. The transport typically has its own special threads and cannot use direct executor, because it needs to block on epoll or similar.

**Comment by Spikhalskiy** [comment]
Thanks for the clarification!
