### ISSUE TITLE
How can I use ManagedChannel with a proxy?

### ISSUE THREAD

**Issue by IlSassone** [grpc/grpc-java#9057]
Is there a way to specify a proxy connection to use to connect to a grpc server?
This is the code that i'm currently using to instanciate the client used for the connection with the server
```java
ManagedChannel channel = ManagedChannelBuilder.forAddress(serverAddress, serverPort).build();
MyClientGrpc.ClientBlockingStub = MyClientGrpc.newBlockingStub(channel);
```
I would like to use this proxy for the connection with the server:
```java
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort));
```
Is there a way to do that?

**Comment by sanjaypujare** [comment]
Take a look at https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ProxyDetector.java#L24 and https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ManagedChannelBuilder.java#L522 to understand how proxies work in gRPC.

**Comment by ejona86** [comment]
Preference order of how to configure proxies (the first two are generic Java):
* `-Dhttps.proxyHost` and `-Dhttps.proxyPort` (and `-Dhttp.nonProxyHosts`, which is used for both http and https). [Java docs](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html). Note that gRPC will observe the https configuration, even when doing plaintext, as it will use the HTTP CONNECT proxing protocol
* [`ProxySelector.setDefault()`](https://docs.oracle.com/javase/8/docs/api/java/net/ProxySelector.html). Use this if you need more complex configuration logic
* gRPC's [ProxyDetector](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#proxyDetector-io.grpc.ProxyDetector-). This is best suited for libraries that are going to a fixed destination and they know they need a proxy. This happens, but is generally rare

**Comment by IlSassone** [comment]
Also, is it possible to connect using a SOCKS proxy instead of a HTTP/HTTPS proxy?

**Comment by ejona86** [comment]
Did you take a look at the ProxyDetector documentation? Return `null` if the address (which is generally hostname + port) shouldn't be proxied and otherwise return HttpConnectProxiedSocketAddress.

SOCKS is not currently supported.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

If you require SOCKS (not just nice to have) then that is probably best to open a feature request issue for.
