### ISSUE TITLE
io.grpc.StatusRuntimeException: UNKNOWN: Exception calling application: module 'grpc' has no attribute 'experimental'

### ISSUE THREAD

**Issue by hepengfei-ml** [grpc/grpc-java#9065]
<grpc.version>1.23.0</grpc.version>
		<protobuf.version>3.13.0</protobuf.version>

**Comment by sergiitk** [comment]
1. Could you provide a more detail on the setup?
2. Are you using `grpc-protobuf`? What version?
3. `1.23.0` is three years old now, would it make more sense to upgrade?

**Comment by ejona86** [comment]
No response to provide more information (especially item 1, for more error details), so closing. More information can be provided and then we can reopen.
