### ISSUE TITLE
How to clean/remove bi-directional streams when agent channel dies?

### ISSUE THREAD

**Issue by umapriyadarsi** [grpc/grpc-java#9066]
On GRPC server, channels are entirely abstracted to us. 

Now consider the case of bi-directional streams, or server-side streams. 

Suppose the server stores the Streams in a memory for each agent. The server can then (re)use the same stream to keep sending updates to (various) agent(s) using the respective stream.

If the agent abruptly dis-connects, there is no way for server to know this, until the server sends a message to agent and it fails.

Is this the only way to handle this case?

I assume that streams do consume quite some memory space on the server?
Keeping many dead streams perhaps is intensive? 

What is the beast way to clean up such StreamObservers to free up resources?

**Comment by ejona86** [comment]
Cast the StreamObserver provided to your service to `ServerCallStreamObserver`. Then use [`serverCallStreamObserver.setOnCallHandler()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#setOnCancelHandler-java.lang.Runnable-). That callback will not be called concurrently with the other notification StreamObserver methods (so you don't have to worry about synchronization). If you block processing when receiving requests and you want a notification on another thread, you can use [`context.current().addListener()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html#addListener-io.grpc.Context.CancellationListener-java.util.concurrent.Executor-) instead; that callback uses the provided executor instead.

Note that this should only be a problem once the client half-closes (the `onComplete()`); if the stream dies before that point gRPC will call onError().
