### ISSUE TITLE
client thread hangs forever and  can not exit

### ISSUE THREAD

**Issue by NeoZephyr** [grpc/grpc-java#9069]
### What version of gRPC-Java are you using?

implementation "io.grpc:grpc-protobuf:1.43.2"
implementation "io.grpc:grpc-stub:1.43.2"
runtimeOnly "io.grpc:grpc-netty-shaded:1.43.2"

### What is your environment?

Linux centos7
JDK8

### What did you expect to see?

The client should not block forever, even up to a few days

### What did you see instead?

All  client thread is hanging forever!

jstack log:
```
"collection_group-thread-3" #69 prio=5 os_prio=0 tid=0x00007f7b36024800 nid=0x53 waiting on condition [0x00007f7a764ea000]          
   java.lang.Thread.State: WAITING (parking)                                                                                               
        at sun.misc.Unsafe.park(Native Method)                  
        - parking to wait for  <0x00000000ca49cfd8> (a io.grpc.stub.ClientCalls$ThreadlessExecutor)      
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)                                                 
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:731)                                  
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)                                        
        at com.punk.identity.grpc.IdServiceGrpc$IdServiceBlockingStub.register(IdServiceGrpc.java:429)
```

grpc client code
```java
public class IdClient {

    IdServiceGrpc.IdServiceBlockingStub stub;
    ManagedChannel channel;
    boolean broken = false;

    IdClient(String target, int minutes) {
        channel = ManagedChannelBuilder.forTarget(target)
                .usePlaintext()
                .idleTimeout(minutes, TimeUnit.MINUTES)
                .build();
        HeaderEnhanceInterceptor interceptor = new HeaderEnhanceInterceptor();
        Channel enhanceChannel = ClientInterceptors.intercept(this.channel, interceptor);
        stub = IdServiceGrpc.newBlockingStub(enhanceChannel);
    }

    void close() throws InterruptedException {
        if (channel != null) {
            channel.shutdown().awaitTermination(5, TimeUnit.SECONDS);
        }
    }
}
```

### Steps to reproduce the bug

I dont know what happend, and it's very difficult to reproduce it.

I I solved the problem temporarily by restarting the client

**Comment by ejona86** [comment]
The problem is most likely in the HeaderEnhanceInterceptor. If it throws an exception or doesn't delegate the close notification, that could prevent the stub from learning the call is dead.

**Comment by NeoZephyr** [comment]
> 

The implementation of the client-side interceptor is so simple, And I don't think an exception will occur

```java
public class HeaderEnhanceInterceptor implements ClientInterceptor {

    @Override
    public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {
        return new ForwardingClientCall.SimpleForwardingClientCall<ReqT, RespT>(next.newCall(method, callOptions)) {
            @Override
            public void start(ClientCall.Listener<RespT> responseListener, Metadata headers) {
                String methodName = method.getBareMethodName();

                if (!"Ping".equals(methodName)) {
                    headers.put(RpcMetadataKey.TRACE_ID_KEY, RpcContextKey.TRACE_ID_KEY.get());
                }

                headers.put(RpcMetadataKey.REQUEST_ID_KEY, RpcContextKey.REQUEST_ID_KEY.get());
                super.start(responseListener, headers);
            }
        };
    }
}

public interface RpcContextKey {
    Context.Key<String> TRACE_ID_KEY = Context.key("traceId");
    Context.Key<String> REQUEST_ID_KEY = Context.key("requestId");
}

public interface RpcMetadataKey {
    Metadata.Key<String> TRACE_ID_KEY = Metadata.Key.of("traceId", Metadata.ASCII_STRING_MARSHALLER);
    Metadata.Key<String> REQUEST_ID_KEY = Metadata.Key.of("requestId", Metadata.ASCII_STRING_MARSHALLER);
}
```

If it is indeed caused by an exception, how should I resolve the problem? Is it possible to use `try-catch` and eat the exception like this
```java
public class HeaderEnhanceInterceptor implements ClientInterceptor {

    @Override
    public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {
        return new ForwardingClientCall.SimpleForwardingClientCall<ReqT, RespT>(next.newCall(method, callOptions)) {
            @Override
            public void start(ClientCall.Listener<RespT> responseListener, Metadata headers) {
                try {
                    String methodName = method.getBareMethodName();

                    if (!"Ping".equals(methodName)) {
                        headers.put(RpcMetadataKey.TRACE_ID_KEY, RpcContextKey.TRACE_ID_KEY.get());
                    }

                    headers.put(RpcMetadataKey.REQUEST_ID_KEY, RpcContextKey.REQUEST_ID_KEY.get());
                    super.start(responseListener, headers);
                } catch (Exception ignore) {}
            }
        };
    }
}
```

**Comment by ejona86** [comment]
Yeah, that interceptor looks fine.

Another possibility is the connection got hung. I see there's no keepalive on the connection. Most unary RPCs don't run that long, so it is rare for them to witness the connection getting silently killed. But it is possible.

I'd suggest using `managedChannelBuilder.keepAliveTime(5, TimeUnit.MINUTES)` and seeing if that resolves the problem by killing the connection when things get wedged. You may be interested in https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md . Note that gRPC servers default to a 5 minute limit, so configuring that lower than 5 minutes requires a server-side configuration change as well.

**Comment by NeoZephyr** [comment]
> Yeah, that interceptor looks fine.
> 
> Another possibility is the connection got hung. I see there's no keepalive on the connection. Most unary RPCs don't run that long, so it is rare for them to witness the connection getting silently killed. But it is possible.
> 
> I'd suggest using `managedChannelBuilder.keepAliveTime(5, TimeUnit.MINUTES)` and seeing if that resolves the problem by killing the connection when things get wedged. You may be interested in https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md . Note that gRPC servers default to a 5 minute limit, so configuring that lower than 5 minutes requires a server-side configuration change as well.


Thank you very much for your reply. But I have the following questions:

1. How do I know if a connection got hung, and how to kill a Grpc connection
2. What is the difference between keepAlive and idleTimeout, I have configured idleTimeout, do I still need to configure keepAlive?

**Comment by ejona86** [comment]
> How do I know if a connection got hung, and how to kill a Grpc connection

Enable keepalive like I suggested. It will do this for you.

> What is the difference between keepAlive and idleTimeout

You might find [this stackoverflow question](https://stackoverflow.com/q/57930529/4690866) helpful. Keepalive actively monitors the connection, although it is designed in a way that will frequently not cause extra load (because keepAliveWithoutCalls is disabled by default). idleTimeout just closes the connection if you haven't used the channel in a while. Connections dying is generally triggered after periods of inactivity. Keepalive helps by causing activity and idleTimeout helps by throwing away the connection when you don't need it. See also [gRFC A8](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md).

>  I have configured idleTimeout, do I still need to configure keepAlive?

Yes. idleTimeout only triggers if there are no RPCs in progress. keepAlive only triggers when there are RPCs in progress. If you only have one, you could have keepAlive. But the two work well on mobile in concert.

I will note that idleTimeout puts the channel into a low-resource idle mode. When you send an RPC after that idle period, it will need to do DNS resolution and create a connection.

**Comment by NeoZephyr** [comment]
> Yeah, that interceptor looks fine.
> 
> Another possibility is the connection got hung. I see there's no keepalive on the connection. Most unary RPCs don't run that long, so it is rare for them to witness the connection getting silently killed. But it is possible.
> 
> I'd suggest using `managedChannelBuilder.keepAliveTime(5, TimeUnit.MINUTES)` and seeing if that resolves the problem by killing the connection when things get wedged. You may be interested in https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md . Note that gRPC servers default to a 5 minute limit, so configuring that lower than 5 minutes requires a server-side configuration change as well.

The client thread hangs forever again, and I found the TCP connection is normal

**Comment by ejona86** [comment]
> I found the TCP connection is normal

How long was it stuck, and how did you configure keepalive?

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
