### ISSUE TITLE
All GRPC calls failed with DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by rubeenashirin** [grpc/grpc-java#9072]
We have an android app which calls a GRPC service. Sometimes for some clients the GRPC calls starts failing with DEADLINE_EXCEEDED. The request doesn't reach the server. It seems like a DNS resolution issue because the AWS calls also fails with the error unable to resolve host. After a while AWS issue is resolved but the GRPC continues to fail. The app has to be restarted for it to work. The internet connection is up throughout. I suspect the ManagedChannel is corrupted somehow. 

Any one faced this issue before?  Is there a way reset the ManagedChannel without having to restart the app or having to initialize it again?

I am using grpc version 1.39.0. It looks similar to this issue but that bug is supposed to be fixed in 1.7 version. https://groups.google.com/g/grpc-io/c/0t9n1-2GTms

**Comment by ejona86** [comment]
Can you provide the actual DEADLINE_EXCEEDED error? There's generally some more information encoded in the string details. What sort of time periods are involved here? How long after AWS started working did you wait for gRPC to recover and it hadn't? Does the channel have keepalive enabled?

Consistent DNS resolution failures generally mean that there is a connectivity problem. There's a couple options of what is going on, but it'd be best to have the deadline exceeded details.

**Comment by ejona86** [comment]
Cross-linking https://stackoverflow.com/questions/71802092/all-grpc-calls-failed-with-deadline-exceeded

**Comment by rubeenashirin** [comment]
This is the actual error we see.
`
Error occurred while sending request: DEADLINE_EXCEEDED : io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 4.999493334s. [remote_addr=****-****.*******.***/***.**.**.***:***]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at ChowIotServiceGrpc$ChowIotServiceBlockingStub.recordStatus(ChowIotServiceGrpc.java:906)
	at GrpcClient.sendRequest(GrpcClient.java:80)
	at GrpcRequestManager.processRequestsInBatch(GrpcRequestManager.java:104)
	at GrpcRequestManager.lambda$startGrpcHandlerThread$0$GrpcRequestManager(GrpcRequestManager.java:58)
	at -$$Lambda$GrpcRequestManager$8TI2Xry2PqOkmRErVdYghdakOSA.handleMessage(lambda)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)`
	
We do not have keepalive enabled since we do not want to tie up resources when its not used.  Usually if AWS recover within 30 mins of outage (which is the default idle timeout for grpc) the grpc also recovers otherwise most times it's unrecoverable. Not able to replicate this behavior by turning the internet off for more than 30 mins though. We usually notice within 4-5 hours if the grpc is not recovered and restart the app.

**Comment by ejona86** [comment]
Oh, that error is helpful. Since there is an address, it shows the RPC was sent. There was also no queuing involved locally (it would have been included in the message), so the connection was already established when this RPC was sent. That means keepalive is the thing you want in this situation.

Keepalive will only expend resources when there are RPCs on the connection, and only if those RPCs have not caused activity already. The "classic" approach is to combine keepalive with idleTimeout, and have idleTimeout kick in to close idle connections and release resources instead of letting them get wedged by bad networks.

**Comment by rubeenashirin** [comment]
@ejona86  Could you elaborate how keepalive will prevent this situation ? What exactly caused this DEADLINE_EXCEEDED error?

**Comment by ejona86** [comment]
I expect the TCP connection was broken. https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md has some more background, but in short, to detect broken TCP connections you have to do a write. Starting an RPC is a write _most_ of the time, but if hit a rarer case or if the connection breaks after the RPC is started, then the client will be waiting for a response that will never arrive. The keepalive then can kick in and detect the broken connection and kill the RPC. It provides an upper-bound for how long you may need to wait to learn of a broken connection.

**Comment by rubeenashirin** [comment]
Thanks for all the information @ejona86 .

I am wondering if TCP connection breaking after RPC call is the issue shouldn't the next RPC call succeed as that will detect the broken TCP connection? We sent a request every minute. Or is it that once the socket connection is established the connection is not checked again? 

We are waiting for only 5 seconds for a response, the proposal here states that we minimum keep alive time has to be at least 10seconds so I don't think this will work.
https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md

**Comment by rubeenashirin** [comment]
Thanks for all the information @ejona86 .

I am wondering if TCP connection breaking after RPC call is the issue, shouldn't the next RPC call succeed as that will detect the broken TCP connection? We are sending a request every minute. Or is it that once the socket connection is established the connection is not checked again?

We are waiting for only 5 seconds for a response, the proposal here states that minimum keep alive time has to be at least 10seconds so I don't think this will work. 
https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md

**Comment by ejona86** [comment]
> shouldn't the next RPC call succeed as that will detect the broken TCP connection? We are sending a request every minute.

Generally I'd expect and hope so. But it can't be guaranteed. There are things like waiting on TCP flow control that might prevent the host from sending additional packets.

> We are waiting for only 5 seconds for a response, the proposal here states that minimum keep alive time has to be at least 10seconds so I don't think this will work.

Well, one of the RPCs would fail. But gRPC would still detect the connection is bad 5 seconds after that RPC completes. And so the next RPC in a minute would then use a different connection.

**Comment by rubeenashirin** [comment]
Hmm. Okay. I don't want the server to be pinged when there is no RPC call on a connection. I wonder if I set keepAliveWithoutCalls as false will it still detect the connection has gone bad 5 seconds after the RPC fails.

**Comment by rubeenashirin** [comment]
Hmm. Okay. I don't want the server to be pinged when there is no RPC call on a connection. If I set keepAliveWithoutCalls as false will it still detect the connection has gone bad 5 seconds after the RPC fails ?

**Comment by ejona86** [comment]
>  If I set keepAliveWithoutCalls as false will it still detect the connection has gone bad 5 seconds after the RPC fails ?

Yes. Note that keepAliveWithoutCalls is false by default, and would be very difficult for us to change that default because of the server-side-default behavior. We agree that it is generally better not to do the ping activity if there are no calls.

**Comment by rubeenashirin** [comment]
Noted. Thanks for all information @ejona86!

**Comment by rubeenashirin** [comment]
Noted. Thanks for all the information @ejona86!
