### ISSUE TITLE
xDS example doesn't work as expected

### ISSUE THREAD

**Issue by olderwei** [grpc/grpc-java#9077]
I've tried grpc-java/examples/xds/ and it doesn't work.I'm using a customized control-plane based on [https://github.com/envoyproxy/java-control-plane/tree/main](url) then I run the server and the client.But the server cannot register itself sucessfully.  the error is :
```
Exception in thread "main" java.io.IOException: io.grpc.StatusException: UNAVAILABLE: Can only support xDS v3 with listener resource name template
	at io.grpc.xds.XdsServerWrapper.start(XdsServerWrapper.java:169)
	at io.grpc.examples.helloworldxds.XdsHelloWorldServer.main(XdsHelloWorldServer.java:72)
Caused by: io.grpc.StatusException: UNAVAILABLE: Can only support xDS v3 with listener resource name template
	at io.grpc.Status.asException(Status.java:543)
	at io.grpc.xds.XdsServerWrapper.internalStart(XdsServerWrapper.java:190)
	at io.grpc.xds.XdsServerWrapper.access$100(XdsServerWrapper.java:80)
	at io.grpc.xds.XdsServerWrapper$2.run(XdsServerWrapper.java:158)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.xds.XdsServerWrapper.start(XdsServerWrapper.java:155)
	... 1 more
```

and the bootstrap.json is as follows:
```
{
  "xds_servers": [
    {
      "server_uri": "127.0.0.1:12345",
      "channel_creds": [
        {
          "type": "insecure"
        }
      ],
      "server_features": ["xds_v3"]  
    }
  ],
  "node": {
    "id": "b7f9c818-fb46-43ca-8662-d3bdbcf7ec18~10.0.0.1"
  }
}
```
Another question that I want to ask is how to configurate the “yourServersName” when operating the command “./build/install/example-xds/bin/xds-hello-world-client "xds world" xds:///yourServersName". As the server doesn't register a name when it is started

**Comment by sanjaypujare** [comment]
Please check this out https://github.com/grpc/proposal/blob/master/A36-xds-for-servers.md#xds-protocol according to which:
```
  //A template for the name of the Listener resource to subscribe to for a gRPC
  //server. If the token `%s` is present in the string, all instances of the
  // token will be replaced with the server's listening "IP:port" (e.g.,
  // "0.0.0.0:8080", "[::]:8080").
```

This is not present in your bootstrap json file.

>  how to configurate the “yourServersName” ...

Check this out https://github.com/grpc/proposal/blob/master/A27-xds-global-load-balancing.md#xds-resolver . You need to have a Listener resource for "YourServersName" as described in this gRFC.

**Comment by olderwei** [comment]
Now the bootstrap.json is as follows:
`{
  "xds_servers": [
    {
      "server_uri": "127.0.0.1:12345",
      "channel_creds": [
        {
          "type": "insecure"
        }
      ],
      "server_features": ["xds_v3"]  
    }
  ],
  "node": {
    "id": "b7f9c818-fb46-43ca-8662-d3bdbcf7ec18~10.0.0.1"
  },
  "server_listener_resource_name_template": "grpc/server?xds.resource.listening_address=%s"
}`
But the server output "UNAVAILABLE: Listener grpc/server?xds.resource.listening_address=0.0.0.0:50051 unavailable".
The [java-control-plane](https://github.com/envoyproxy/java-control-plane) output "not responding in ADS mode for type.googleapis.com/envoy.config.listener.v3.Listener from node key at version v1 for request [grpc/server?xds.resource.listening_address=0.0.0.0:50051] since [grpc/server?xds.resource.listening_address=0.0.0.0:50051] not in snapshot"
Also, is it appropriate  for me to use java-control-plane as xDS server.

**Comment by olderwei** [comment]
thank you very much! I will spend some time looking into it, and I will close this issue.
