### ISSUE TITLE
serverCallStreamObserver.isCancelled() cannot detect client disconnection for gRPC version higher than 1.41.0

### ISSUE THREAD

**Issue by billwenboli** [grpc/grpc-java#9087]
I have recently discovered that serverCallStreamObserver.isCancelled() cannot detect client disconnection when gRPC version is higher than 1.41.0. We have several dependencies related to gRPC, namely grpc-netty-shaded, grpc-protobuf, grpc-stub and grpc-testing. I found that ONLY when grpc-netty-shaded is above 1.41.0, the disconnection cannot be detected. All other dependencies can be set to the latest release version, which is 1.45.1.

Here is a sample code snippet of what we have on the server side:

```java
Greeting greeting = request.getGreeting();
String firstName = greeting.getFirstName();
String lastName = greeting.getLastName();

int i = 0;

ServerCallStreamObserver<GreetResponse> serverCallStreamObserver =
    (ServerCallStreamObserver<GreetResponse>)responseObserver;

try {
  while (true) {
    if (serverCallStreamObserver.isCancelled()) {
      System.out.println("cancelled");
      serverCallStreamObserver.onCompleted();
      break;
    }

    String result = "Hello " + firstName + " " + lastName + ", response number: " + i;
    GreetResponse response = GreetResponse.newBuilder()
        .setResult(result)
        .build();
    responseObserver.onNext(response);

    Thread.sleep(1000L);
    i++;
  }
} catch (InterruptedException e) {
  e.printStackTrace();
}
```

Our client is written in Python. Here is the sample code snippet:

```python
def run():
    with grpc.insecure_channel('localhost:50051') as channel:
        stub = greet_pb2_grpc.GreetServiceStub(channel=channel)
        greeting = greet_pb2.Greeting()
        greeting.first_name = 'Bill'
        greeting.last_name = 'Li'
        for response in stub.GreetServerStreaming(greet_pb2.GreetRequest(greeting=greeting)):
            print(response.result)
        channel.close()
```

**Comment by ejona86** [comment]
#8408 was in v1.41.0, and the observed behavior here does seem to match the current implementation. So I think something isn't right in the code. A workaround is to swap to `Context.current().isCancelled()`.

I saw similar behavior, but seemingly not introduced in v1.41.0, and the sleep duration mattered, so we need to fitz with my "reproduction" in https://groups.google.com/g/grpc-io/c/Zowxz7JR3LI/m/163eWqTpCAAJ more to see what's going on.

CC @temawi

**Comment by temawi** [comment]
PR https://github.com/grpc/grpc-java/pull/9501 should assure that ServerCallStreamObserver.isCancelled() always returns true when the call has been cancelled.
