### ISSUE TITLE
do GrpcServerRule exist migrated to Extensions for using in Junit5?

### ISSUE THREAD

**Issue by juanjcal** [grpc/grpc-java#9088]
I have a task, where i have to migrate Junit4 test to Junit5 so, i can't use @Rule anotation. 
So my question is about exist any implementation about grpcServerRule in a Extension for can use GRPC in Junit5

Thank you so much

**Comment by sanjaypujare** [comment]
Based in this https://www.arhohuttunen.com/junit-5-migration/#rules it looks like you can try using the `junit-jupiter-migrationsupport` module to get support for `ExternalResource` which is what `GrpcServerRule` is based off of?

**Comment by ejona86** [comment]
I don't think gRPC will provide a more native form of test util for junit 5 than an External Resource.

This was discussed some in https://github.com/grpc/grpc-java/issues/5331 . GrpcServerRule is already an ExternalResource, so just use the ExternalResource support in junit 5. We will probably convert GrpcCleanupRule to extend ExternalResource for use in junit 5. The annotation approach in junit 5 seems counter to good design and I don't want to encourage environments where private fields are modified by impossible-to-discover code.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
