### ISSUE TITLE
Can someone help explain the cause of this stack trace

### ISSUE THREAD

**Issue by cyberpwnn** [grpc/grpc-java#9104]
About 4 days ago an issue started happening in firebase for flutter on android specifically that is preventing people from connecting to any firebase services at all (seems like streams cant connect specifically but whatever)

```
W/Firestore( 5850): (24.1.1) [WatchStream]: (150415a) Stream closed with status: Status{code=INTERNAL, description=error in frame handler, cause=java.lang.NoSuchMethodError: No interface method getBuffer()Lokio/Buffer; in class Lokio/BufferedSource; or its super classes (declaration of 'okio.BufferedSource' appears in /data/app/~~562CMs3V8mJAW5W-e8eBRQ==/care.mpm.app.myguide-vSZFTwtxrkRSO-SPz3Pd5g==/base.apk!classes5.dex)
W/Firestore( 5850): 	at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.data(OkHttpClientTransport.java:1144)
W/Firestore( 5850): 	at io.grpc.okhttp.internal.framed.Http2$Reader.readData(Http2.java:234)
W/Firestore( 5850): 	at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:147)
W/Firestore( 5850): 	at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:1103)
W/Firestore( 5850): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore( 5850): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore( 5850): 	at java.lang.Thread.run(Thread.java:923)
```

* Is this grpc not being updated on firebase's part?
* Is this a current issue in grpc?
* Is this an issue with okhttp?
* Is there any quick & dirty way to workaround this (dependency swapping) without waiting for firebase to update so flutter fire updates so that I can update?

Any help would be greatly appreciated, I cant seem to find very much information on this. The original firebase issue I've created pointed me here https://github.com/firebase/flutterfire/issues/8501

**Comment by sanjaypujare** [comment]
I don't see how this is a gRPC issue. Looks more like an okio version issue.

**Comment by swankjesse** [comment]
https://github.com/square/okio/discussions/1114#discussioncomment-2623804

**Comment by swankjesse** [comment]
Its an Okio version issue.

**Comment by ejona86** [comment]
It seems you are using a version of okio pre-1.16.0. https://github.com/firebase/flutterfire/issues/8501 looks like it has a good understanding of what is going on and is the place that needs addressing. Closing. Comment and we can reopen if that isn't the case.
