### ISSUE TITLE
Where is the documentation to configure io_grpc_netty_shaded_netty_transport_native_epoll_x86_64 in java.library.path?

### ISSUE THREAD

**Issue by edwbuck** [grpc/grpc-java#9105]
**Where is the documentation to configure io_grpc_netty_shaded_netty_transport_native_epoll_x86_64 in java.library.path?**

I know that the native library loader will eventually succeed, but I would like to configure my system to avoid the stacktrace in the debugging logs.

**Comment by YifeiZhuang** [comment]
To configure what in `io_grpc_netty_shaded_netty_transport_native_epoll_x86_64 `? I don't think there are places for such configurations.  @ejona86 

If it is about logging property, you need to provide the location of this file as a JVM flag, e.g., with the command-line flag -Djava.util.logging.config.file=logging.properties

**Comment by ejona86** [comment]
You're wanting to pre-extract the .so into java.library.path so that the Netty trial-and-error doesn't trigger? We don't have any documentation for that, but you extract the .so into java.library.path...

**Comment by ejona86** [comment]
Unclear if resolved, but we'd really need a response to provide more information if not. Haven't heard back, so closing. More information can be provided and then we can reopen.
