### ISSUE TITLE
Adding an iterator for Metadata entries

### ISSUE THREAD

**Issue by ohadgur** [grpc/grpc-java#9112]
In some cases, it's necessary to iterate over all the entries of the metadata instance, without prior knowledge of the existing keys.
For example, when writing the headers to the log\tracing framework, writing generic interceptors etc.

The way I'm doing it now is:
1. iterate over the keys using `Metadata.keys()` - which iterates over the underlying `Object[]`
2. for each key, get its value using `Metadata.get()` - which again, iterates over the array
3. create a map from key -> value
4. return an iterator

This makes iterating over the entries more inefficient than it needs to be, IMO.

Having a new `Metadata.iterator()` method with a reasonable runtime (O(n)) will be great.

Also, if there's a more reasonable way to do it that I missed, please let me know.
Thanks

**Comment by temawi** [comment]
What you are doing seems reasonable if you really need to produce an Iterator. The Metadata implementation, by design, favors insert performance over iteration. As the amount of data is relatively small, this tradeoff should be acceptable.

The keys() method was added to support cases like yours where all entries need to be iterated over and so far there have been no reports of performance issues with it. Do you have a specific scenario where performance becomes unacceptable?

**Comment by ohadgur** [comment]
Thanks for clarifying the design intention. it makes much more sense to me now.

Our use case is passing some arbitrary header from the client to the server on each request - mainly tracing context which is always propagated forwards and some are also returned by the server.
In addition, in our internal client wrapper, we give the users an option to read and modify the headers for their custom use cases, which also happens on each request.
Since the reads happen on each request, the performance hit grows with the number of requests, which can be great.
I mean, it will probably not be the largest bottleneck, but it would be great to eliminate that thing as well.

**Comment by temawi** [comment]
It seems like you are using the API correctly, the current implementation just is not optimized in the way you are hoping for. But this was a conscious design decision that comes down to the tradeoffs I mentioned in my earlier comment. We are currently happy with the implementation. If there was a concrete case where retrieval performance was causing a problem we might look at alternatives.

**Comment by ejona86** [comment]
Seems like this is resolved as much as expected right now. If not, comment, and it can be reopened. If you end up seeing performance issues, we'd be much more interested at that point.
