### ISSUE TITLE
gRPC java supports authorization. 

### ISSUE THREAD

**Issue by nickibi** [grpc/grpc-java#9114]
I looked at the SECURITY doc: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#security-policy, which is mainly focusing on authentication. I am wondering whether there is any native authorization support from gRPC Java? Thanks.

**Comment by sanjaypujare** [comment]
You may want to look at this https://github.com/grpc/proposal/blob/master/A43-grpc-authorization-api.md

**Comment by nickibi** [comment]
@sanjaypujare Thanks for sharing the link. That's very helpful. Do you know the Java support is completed or not? From the status in the link: https://github.com/grpc/proposal/blob/master/A43-grpc-authorization-api.md, currently it only supports C++, C-core and Go.

**Comment by sanjaypujare** [comment]
> Do you know the Java support is completed or not?

AFAIK Java is complete but I'll let @ejona86 and @ashithasantosh confirm

**Comment by ejona86** [comment]
This work is not complete in Java. I'll note that making an authz policy is pretty easy in grpc with an interceptor. The main value of the gRPC authz interceptor is being able to update the Authz rules without rebuilding your binary (as you might need to do for a custom policy).

**Comment by ejona86** [comment]
You probably want to subscribe to #8934 to notice when it starts making progress again. Seems like this is answered. If not, comment, and it can be reopened.
