### ISSUE TITLE
Exceptions created in onClose() path lack useful context

### ISSUE THREAD

**Issue by Spikhalskiy** [grpc/grpc-java#9164]
### What version of gRPC-Java are you using?

1.46.0

### What did you expect to see?

Ideally:
An exception that is returning from a call's Future should have a stack trace leading to this call and allowing to trace where the call was initiated.

Second option:
Likely having a stack trace of the original call is impossible or prohibitively expensive here. In that case, additional metadata may be included in the message to at least help identify the rpc method.

### What did you see instead?

When using future stubs:

```
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9.999773390s. [closed=[], open=[[remote_addr=/127.0.0.1:7233]]]
	at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.46.0.jar:1.46.0]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:542) ~[grpc-stub-1.46.0.jar:1.46.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.46.0.jar:1.46.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.46.0.jar:1.46.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.46.0.jar:1.46.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562) ~[grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743) ~[grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722) ~[grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.46.0.jar:1.46.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

This exception identifies neither the rpc method that was called nor the stack trace of the execution that led to this call. If this exception is getting logged, it's pretty much useless and untraceable to its source.

**Comment by ejona86** [comment]
I agree it is unfortunate, but yes, allocating a stack trace at the beginning of each RPC is prohibitive. It also seems a very strange request for someone using the future API; I don't think there's any precedence for that.

> If this exception is getting logged, it's pretty much useless and untraceable to its source.

This I think is a key piece. What code logged this exception? In general, code should be attaching additional context to exceptions (via wrapping) as it is processing the errors and that code would generally be specific to one callsite. Are you using generic code to log the exception?

**Comment by Spikhalskiy** [comment]
@ejona86 While I agree that gRPC can say that users are responsible for that, it's not the best experience. Because users will not know that they are responsible until they discover such an exception.

And thinking about a user who is not understanding how gRPC works and sees this exception... It looks like a completely internal gRPC stack trace, I think some users will have a hard time how to proceed from that. Some users may not even understand that this exception is a result of their call.

> Are you using generic code to log the exception?

Yeah, our specific scenario is that we have a tiny in-memory scheduler that accepts lambdas and log if any exceptions happened inside them. 
We wanted lambda code to don't be having exception handling and the scheduler retries them with backpressure if an exception happens.
We will fix it for sure for our usecase and will do something like

```
catch (StatusRuntimeException e) {
    // Can't create a new StatusRuntimeException with more data, it will not allow passing a cause.
    throw new StatusRuntimeExceptionWrapper("methodName", e)
}
```
but it's quite ugly.

I know it's probably tricky, because you want to just deserialize the error from the server and don't intervene with the content as much as possible. But... would be great to have something.

**Comment by ejona86** [comment]
> Because users will not know that they are responsible until they discover such an exception.

I dunno. Something as simple as IO failing with "read failed" and you already have to provide more context. I'll grant you that some libraries will add in the file name automatically in those cases, but it isn't universal. Future-based programming is really bad about losing context, so it seems "this is the sort of thing you'd learn quickly" and it has little to do with gRPC. I 100% agree it makes for a poor experience, but "that's futures for you."

I have considered adding more info in the past, but I quickly discovered we still needed more info because there were multiple pieces of code that called a particular gRPC method. I think the stronger argument for adding method name is for cases where the user _is_ adding context, but they are doing N RPCs to different methods and don't want to bother wrapping each individually.

> And thinking about a user who doesn't understand how gRPC works and sees this exception... It looks like a completely internal gRPC stack trace

We have considered just disabling the stack trace entirely. There were some API issues with doing it. I agree the stack doesn't serve a purpose.

> Yeah, our specific scenario is that we have a tiny in-memory scheduler that accepts lambdas and logs if any exceptions happened inside them.

Hmm... I see how this would be a problem. But it also seems a bigger problem than gRPC. Especially when avoiding the use of directExecutor().

> We will fix it for sure for our usecase and will do something like

StatusRuntimeException inherits the cause of the Status.
```java
// Normal way, when creating status afresh:
Status.UNAVAILABLE.withDescription("foo").withCause(ex).toRuntimeException();

try {
} catch (StatusRuntimeException e) {
  // But I guess this works:
  throw e.getStatus().withCause(e).toRuntimeException();
}
```

**Comment by ejona86** [comment]
I don't really see an appropriate way to handle this. This seems a general async-programming in Java issue and while gRPC could add some details to the exception, it would still be lacking and there is no way for gRPC to get a useful stacktrace. Honestly, gRPC not including some additional details may make this better, as then the only reasonable thing for a user to do is add their own error details, which is exactly what they should be doing even if gRPC adds more error details to the exception.
