### ISSUE TITLE
Is the stream thread safe?

### ISSUE THREAD

**Issue by jiankebe** [grpc/grpc-java#9182]
new StreamObserver<T> {
  public void onNext(T t) {
// do something
  }
public void onError(Throwable throwable) {
// do something
 }
public void onComplete() {
// do something
}
}

onNext，onError，onComplete is thread safe？

**Comment by ejona86** [comment]
From the [StreamObserver Javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html):

> Implementations are not required to be thread-safe (but should be thread-compatible). Separate StreamObservers do not need to be synchronized together; incoming and outgoing directions are independent. Since individual StreamObservers are not thread-safe, if multiple threads will be writing to a StreamObserver concurrently, the application must synchronize calls.

Relatedly:

> gRPC guarantees it does not block on I/O in its implementation, but applications are allowed to perform blocking operations in their implementations. However, doing so will delay other callbacks because the methods cannot be called concurrently.

So no, you don't need to have locking yourself. You only need locking (or other synchronization tool) if you want to _call_ a StreamObserver from multiple threads (e.g., onNext() for a streaming RPC).

**Comment by jiankebe** [comment]
tnks!

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
