### ISSUE TITLE
publishToMavenLocal failed in checkArtifacts

### ISSUE THREAD

**Issue by YifeiZhuang** [grpc/grpc-java#9183]
### What version of gRPC-Java are you using?
 '1.47.0-SNAPSHOT' 

### What is your environment?

MacOS Monterey 12.3.1
### What did you see instead?
```
> Task :grpc-compiler:checkArtifacts FAILED

Checking format of build/artifacts/java_plugin/protoc-gen-grpc-java.exe
Format=x86_64

Checking dependencies of build/artifacts/java_plugin/protoc-gen-grpc-java.exe
Checking for expected dependencies ...
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
Checking for unexpected dependencies ...
        /usr/local/opt/protobuf/lib/libprotoc.30.dylib (compatibility version 31.0.0, current version 31.4.0)
        /usr/local/opt/protobuf/lib/libprotobuf.30.dylib (compatibility version 31.0.0, current version 31.4.0)
ERROR: found unexpected dependencies (listed above).

```

### Steps to reproduce the bug
1. build protobuf: https://github.com/grpc/grpc-java/blob/master/COMPILING.md#build-protobuf
2. ` ./gradlew build`
3.  `./gradlew publishToMavenLocal`, see the failure above

Related: https://github.com/grpc/grpc-java/issues/5465

**Comment by ejona86** [comment]
From the other issue ` --disable-shared` was believed to be all that is needed. Did you double-check that you built protobuf with the shared library disabled?

**Comment by YifeiZhuang** [comment]
> From the other issue ` --disable-shared` was believed to be all that is needed. Did you double-check that you built protobuf with the shared library disabled?

tried multiple times still no luck, the config  `--disable-shared` is set

**Comment by YifeiZhuang** [comment]
FYI it is working now on my workspace.
What I did was to remove
```
/usr/local/opt/protobuf/lib/libprotoc.30.dylib 
/usr/local/opt/protobuf/lib/libprotobuf.30.dylib 
```
then build gradle plugin again(`--disable-shared`) and  then `./gradlew clean`.

So I believe root cause indeed is the shared library problem.

cc. @ejona86 @sergiitk
