### ISSUE TITLE
Using grpc-java SDK generator with only protoc

### ISSUE THREAD

**Issue by bartek1912** [grpc/grpc-java#9188]
Hello,
`Readme.md` describes how to use the generator with Maven or Gradle, but is there a way to use just the grpc-java plugin without all those dependencies? Where can I find a binary plugin release?

I would like to use the java generator with Golang SDK generation call, like 
```
protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    helloworld/helloworld.proto
```

**Comment by ejona86** [comment]
Yeah, you can use the grpc-java plugin just like you'd use any other plugin. Binaries are available [on Maven Central](https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.46.0/).

**Comment by bartek1912** [comment]
Thank you!
