### ISSUE TITLE
Issues when generating server/client stubs from .proto files. 

### ISSUE THREAD

**Issue by ybv** [grpc/grpc-java#922]
I've generated and ran client and server stubs painlessly for python using
```protoc -I . --python_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_python_plugin` <protofilename>```

I've been trying t generate client stubs for android using 
```protoc  --java_out=output_folder --plugin=protoc-gen-grpc-java=/home/vagrant/grpc-java-0.8.0/compiler/build/binaries/java_pluginExecutable/protoc-gen-grpc-java  --grpc-java_out=output <protofilename>```

Here's my .proto file https://gist.github.com/ybv/95debcb49169e8d8d3d1 After trying to codegen as specified in http://www.grpc.io/docs/tutorials/basic/java.html#generating-client-and-server-code and https://github.com/grpc/grpc-java/tree/master/compiler#compiling-and-testing-the-codegen using the command pasted above, I ended up with these files:
```CleanText.java                 LCEProto.java                  TranslatedText.java            TransRequest.java
CleanTextOrBuilder.java        LinkContentExtractorGrpc.java  TranslatedTextOrBuilder.java   TransRequestOrBuilder.java```

When I try to make a new object (of my request message type) I couldn't set the object properties like this https://github.com/grpc/grpc-java/blob/master/examples/android/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java#L64 
Also it seems weird that my codegen has created different files for different messages, where as here, https://github.com/grpc/grpc-java/blob/master/examples/android/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java#L17-L18 they seem to be classes inside the outer class? What am I missing here?

**Comment by carl-mastrangelo** [comment]
Dumb question: Are you trying to use nanoproto or not?  It looks like the nano arguments aren't present.

**Comment by ybv** [comment]
@carl-mastrangelo Nope, I'm not, should I be?

**Comment by carl-mastrangelo** [comment]
The reason I ask is that the code you have in HelloWorldActivity is the nanoproto style of accessing proto fields.  The other style (default?) is to use the builder pattern, and then call setters (i.e. message.setName(name))  


The inner classes is from java_multiple_files and java_outer_classname in your proto.  The files generated don't seem to be the ones you linked to [here](https://github.com/grpc/grpc-java/blob/master/examples/android/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java#L64)?

Could you list the specific commands you ran to generated your stubs, and include their output?

**Comment by ejona86** [comment]
@ybv there is debate in the proto world whether you should use nano proto or proto lite on Android. We have one small bug fix to do to allow using proto lite. Proto lite looks like "normal" proto with the builders but drops some parts of the API to be more lean. Nano proto is a completely different API.

**Comment by ybv** [comment]
@carl-mastrangelo and @ejona86 Thanks for responding guys!
[this] (https://github.com/grpc/grpc-java/blob/master/examples/android/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java#L64) is link to one of android examples on this repo, my proto file generated these classes: (like I mentioned above) 
```CleanText.java LCEProto.java TranslatedText.java TransRequest.java CleanTextOrBuilder.java LinkContentExtractorGrpc.java TranslatedTextOrBuilder.java TransRequestOrBuilder.java``` 
(That seems normal?)

I tried both default(?) protobuf and nano protobof like this --
```protoc -I /vagrant/lce --plugin=protoc-gen-grpc-java=/home/vagrant/grpc-java-0.8.0/compiler/build/binaries/java_pluginExecutable/protoc-gen-grpc-java --grpc-java_out=/vagrant/lce  /vagrant/lce/lce.proto ```
```protoc -I /vagrant/lce --plugin=protoc-gen-grpc-java=/home/vagrant/grpc-java-0.8.0/compiler/build/binaries/java_pluginExecutable/protoc-gen-grpc-java --grpc-java_out=nano=true:/vagrant/lce --java_out=/vagrant/lce /vagrant/lce/lce.proto ```
the Nano version seems to generated only one file with the name `<Servicename>Grpc.java`

I started building a channel like [this](https://github.com/grpc/grpc-
java/blob/master/examples/src/main/java/io/grpc/examples/routeguide/RouteGuideClient.java#L62) and all worked well until I realized android doesn't support `javax.*` classes?? when I came across [this](http://stackoverflow.com/questions/23211625/cannot-include-javaee-api-7-0-jar-in-android-application?answertab=votes#tab-top) .. 
I mean, shouldn't it be a little easier to just generate client stubs for android? I seem to be definitely missing something! Any help would be greatly appreciated.

**Comment by ybv** [comment]
I finally chose the default (non-protobufnano) route and got it to work with two steps:

```protoc --plugin=protoc-gen-grpc-java=/home/vagrant/grpc-java-0.8.0/compiler/build/binaries/java_pluginExecutable/protoc-gen-grpc-java  --proto_path="/vagrant/lce"  '--java_out=/vagrant/lce' /vagrant/lce/lce.proto ```  -> to generate classes for messages. 

```protoc --plugin=protoc-gen-grpc-java=/home/vagrant/grpc-java-0.8.0/compiler/build/binaries/java_pluginExecutable/protoc-gen-grpc-java  --proto_path="/vagrant/lce" '--grpc-java_out="/vagrant/lce" /vagrant/lce/lce.proto ``` -> for generating a service-rpc class. 

I've been trying to execute a server call via AysncTask and getting  Class not found errors on "io.netty.channel.socket.nio.NioSocketChannel" -- but I guess that's a different issue. 

I came to this step only via trial and error. Would definitely love to read up/ contribute to the documentation if you guys think it's okay.

**Comment by carl-mastrangelo** [comment]
Hmmm, users shouldn't have to generate their protos twice (and if so, that should be fixed).  

PRs welcome.

**Comment by ybv** [comment]
@carl-mastrangelo true! . Although I could make progress with the route I've taken and could establish a session between my android client and python server, I'm not sure if this is THE way to make it work. If anyone with grpc-proto experience from androidland can validate my findings/ let me know the correct set flags needed for `protoc` to generate both service classes and message classes in one shot, I would love to submit a PR. 
@ejona86 Given the amount of promise grpc offers for devices in developing countries, it would be really helpful to have a readme file that's targeted at Android-java (something better than [this] (https://github.com/grpc/grpc-java/tree/master/examples/android) unless there is a better one that I couldn't find )
