### ISSUE TITLE
It can't link when I click the grpc interface params in the generated html document

### ISSUE THREAD

**Issue by akak774** [grpc/grpc-java#9221]
### What version of gRPC-Java are you using?
1.46.0
### What is your environment?

Win10 64
### What did you expect to see?
![image](https://user-images.githubusercontent.com/28804050/170673878-dc64429f-b06b-4e1a-aa50-8ace7556b449.png)
This is the html document generated by protoc-gen-grpc-java.exe.
When I click, it should link to the related object,but there is no any effects.
### What did you see instead?
When I look up the source:
href="#CreateBusinessRequest">.CreateBusinessRequest
Maybe it should be  href="#.CreateBusinessRequest">CreateBusinessRequest
### Steps to reproduce the bug
It's easy , generate document.

**Comment by ejona86** [comment]
> This is the html document generated by protoc-gen-grpc-java.exe.

protoc-gen-grpc-java doesn't generate HTML. It looks like you are using https://github.com/pseudomuto/protoc-gen-doc which does generate HTML. You should file an issue against that repository.

**Comment by ejona86** [comment]
Seems like this is answered. If not, comment, and it can be reopened.
