### ISSUE TITLE
grpc-okhttp is not compliant with Network Profiler of Android Studio

### ISSUE THREAD

**Issue by ganadist** [grpc/grpc-java#9224]
### What version of gRPC-Java are you using?
Any

### What is your environment?

Any

### What did you expect to see?
[Network Profiler of Android Studio ](https://developer.android.com/studio/debug/network-profiler) should show http request of gRPC

### What did you see instead?
Android Studio shows nothing

### Extra information
Android Studio intercept methods of `com/squareup/okhttp/OkHttpClient` or `okhttp3/OkHttpClient$Builder` only.  
https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-main/profiler/transform/src/main/java/com/android/tools/profiler/OkHttpAdapter.java#23
But grpc-okhttp is implemented its own http client, so Network Profiler of Android Studio cannot intercept it.

X-posted on https://issuetracker.google.com/issues/234305101

**Comment by ejona86** [comment]
If Android Studio is intercepting methods, then there's not much we can do. This seems like a feature request for Android Studio. I've subscribed to the issuetracker for them. I think our involvement would probably be limited to telling them what APIs to intercept or the like.

**Comment by ejona86** [comment]
Seems like Android Studio has accepted this as a feature request, so nothing to be done here.. If not, comment, and it can be reopened.
