### ISSUE TITLE
a question about retry

### ISSUE THREAD

**Issue by XiaoWeiKIN** [grpc/grpc-java#9228]
Hello, I want to configure the same retry policy for all services on a channel. What should I do? I can't find the relevant doc.

**Comment by lmcdasi** [comment]
One way doing it - code snippet. 

public GrpcChannelConfigurer channelConfigurer() {
        return (channelBuilder, name) -> {

            ClientPolicy clientPolicy;
            if (Objects.nonNull(clientPolicyMap) && ((clientPolicy = clientPolicyMap.get(name)) != null) && clientPolicy.isEnabled()) {
                final RetryPolicy retryPolicy = clientPolicy.getRetryPolicy();
                if (Objects.nonNull(retryPolicy)) {
                    final Map<String, ?> retryPolicyMap = buildRetryPolicyMap(retryPolicy);
                    final List<Map<String, Object>> serviceInfo = buildServiceInfo(clientPolicy);
                    final Map<String, Object> methodConfig = buildMethodConfig(retryPolicyMap, serviceInfo);
                    final Map<String, Object> serviceConfig = buildServiceConfig(methodConfig);
                    channelBuilder.defaultServiceConfig(serviceConfig).enableRetry();
                } else {
                    .....
                }
            } else {
                ....
            }
        };
    }

    @SuppressWarnings("unchecked")
    private Map<String, ?> buildRetryPolicyMap(final RetryPolicy retryPolicy) {
        return new ObjectMapper().convertValue(retryPolicy, Map.class);
    }

    private List<Map<String, Object>> buildServiceInfo(final ClientPolicy clientPolicy) {
        final List<Map<String, Object>> serviceInfoArrayList = new ArrayList<>();
        final String methodNames = clientPolicy.getMethodName();
        if (Objects.nonNull(methodNames)) {
            String[] arrayMethodName = methodNames.split(COMMA_SEPARATOR);
            for (String methodName : arrayMethodName) {
                final Map<String, Object> serviceInfo = new HashMap<>();
                serviceInfo.put("service", clientPolicy.getServiceName());
                serviceInfo.put("method", methodName.strip());
                serviceInfoArrayList.add(serviceInfo);
            }
        } else {
            final Map<String, Object> serviceInfo = new HashMap<>();
            serviceInfo.put("service", clientPolicy.getServiceName());
            serviceInfoArrayList.add(serviceInfo);
        }

        return serviceInfoArrayList;
    }

    private Map<String, Object> buildMethodConfig(final Map<String, ?> retryPolicyMap, final List<Map<String, Object>> serviceInfo) {
        final Map<String, Object> methodConfig = new HashMap<>();
        methodConfig.put("name", serviceInfo);
        methodConfig.put("retryPolicy", retryPolicyMap);

        return methodConfig;
    }

    private Map<String, Object> buildServiceConfig(final Map<String, Object> methodConfig) {
        final Map<String, Object> serviceConfig = new HashMap<>();
        serviceConfig.put("methodConfig", Collections.<Object>singletonList(methodConfig));

        return serviceConfig;
    }
}

**Comment by XiaoWeiKIN** [comment]
thanks
