### ISSUE TITLE
NettyServerStream's  a  little question 

### ISSUE THREAD

**Issue by githubcheng2978** [grpc/grpc-java#9238]
NettyServerStream class hold the channel in previous versions commit-id 295d927 then it was deleted

i get channel in NettyServerStream by reflect at  grpc1.17。  but grpc1.45.1 

what kind of consideration to delete it ?

**Comment by temawi** [comment]
We don't really support this kind of use of reflection as internal gRPC classes can change at any time and users might inadvertently cause problems. Can you share why you need this access? There might be a better way to accomplish what you need to do.

**Comment by githubcheng2978** [comment]
because i want to send a message to all client,so I use reflection at the interceptor to hold the channel。

**Comment by ejona86** [comment]
@githubcheng2978, why does that require access to the Netty `channel`? What do you mean by "all client"? It isn't clear why that woludn't work with the public API.

**Comment by githubcheng2978** [comment]
thank for your replay. I want to  get the current channel  in the interceptor  when  the client channel was created at server side and store channel to the map.   After that,traverse map and send message to each channel. But I just found a way to get channel through reflection.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Eric Anderson ***@***.***>
发送时间: 星期一, 六月 13, 2022 23:53
收件人: grpc/grpc-java ***@***.***>
抄送: githubcheng2978 ***@***.***>; Mention ***@***.***>
主题: Re: [grpc/grpc-java] NettyServerStream's a little question (Issue #9238)


@githubcheng2978<https://github.com/githubcheng2978>, why does that require access to the Netty channel? What do you mean by "all client"? It isn't clear why that woludn't work with the public API.

―

**Comment by ejona86** [comment]
Why does that require accessing the Netty `Channel`? It seems you should just be able to use the normal gRPC Channel API to send a message.

**Comment by githubcheng2978** [comment]
Yes , how can I get the grpc channel in serverInterceptor???. 

 
I read the code source  that I can accessing the channel like this.
 
    private io.grpc.netty.shaded.io.netty.channel.Channel getInternalChannel(ServerCall serverCall) {
        ServerStream serverStream = (ServerStream) ReflectUtils.getFieldValue(serverCall, "stream");
        return (Channel) ReflectUtils.getFieldValue(serverStream, "channel");
}
 
it seems that the only way to get channel。

**Comment by ejona86** [comment]
The Netty Channel is not for your use, at all. It is not available. It isn't clear why or how you are using the channel, so it is hard to provide an alternative solution.

**Comment by githubcheng2978** [comment]
thank you very much for your patient reply.
I know that channel is not public api. But i want to broadcast message to client at server side. What did I do to achieve this goal?    In above case I use reflection to get the client channel in interceptor and store it in a global map(ip,channel) . Then  loop  map to send message every channel at a certain moment.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Eric Anderson ***@***.***>
发送时间: Thursday, June 16, 2022 12:23:18 AM
收件人: grpc/grpc-java ***@***.***>
抄送: githubcheng2978 ***@***.***>; Mention ***@***.***>
主题: Re: [grpc/grpc-java] NettyServerStream's a little question (Issue #9238)


The Netty Channel is not for your use, at all. It is not available. It isn't clear why or how you are using the channel, so it is hard to provide an alternative solution.

―

**Comment by ejona86** [comment]
I don't think this discussion is making any progress. Closing.

It is not supported to get the netty channel. Servers should generally save the StreamObserver for the client to send responses later. An interceptor could save the ServerCall, but in that case it must service the call and _not_ call `next`, because ServerCall is not thread-safe.
