### ISSUE TITLE
BouncyCastle ALPN broken when running with JDK 11 code compiled with JDK 8

### ISSUE THREAD

**Issue by yatirdagan** [grpc/grpc-java#9239]
### What version of gRPC-Java are you using?
1.44

### What is your environment?
linux, jdk 11.0.15, bc-fips.jar 1.0.2

### What did you expect to see?
on ProtocolNegotiators.class:
"TLS negotiation succeeded."

### What did you see instead?
on ProtocolNegotiators.class:
**"UNAVAILABLE: Failed ALPN negotiation: Unable to find compatible protocol"**

### Steps to reproduce the bug
on existing grpc client server env
set the BouncyCastleFipsProvider (required bc-fips-1.0.2.jar as multi-release jar) by `Security.addProvider(new BouncyCastleFipsProvider());` on the application startup.
set the grpc java client to use the jdk provider:
```
SslContextBuilder sslContextBuilder = SslContextBuilder.forClient()
                    .sslProvider(SslProvider.JDK)
                    .applicationProtocolConfig(new ApplicationProtocolConfig(
                            ApplicationProtocolConfig.Protocol.ALPN, 
                            ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
                        	ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
                            Collections.singletonList("h2")));
```

It looks like BouncyCastleFipsProvider, by its SSLParamertesUtil class, somehow remove the "h2" from the suggested application protocols list. increasing grpc version to 1.46 didn't help.

**Comment by ejona86** [comment]
Normally I'd say this probably needs explicit support for BouncyCastle in gRPC. It could be as easy as checking for its name (`BCFIPS`) in GrpcSslContexts. With such a change you wouldn't need to construct the SslContext manually; grpc would detect and use it. https://github.com/grpc/grpc-java/blob/c589441bded0cdf9e321f1d012fb52dd31c172b4/netty/src/main/java/io/grpc/netty/GrpcSslContexts.java#L203-L204

However, it appears bc-fips doesn't actually provide TLS; it is crypto-only. When creating SslContextBuilder, always pass it through `GrpcSslContexts`. You should test with GrpcSslContexts and that might help, but the snippet you show doesn't seem like it would fail this way.

How certain are you that it is bc-fips causing the trouble? Could you do `Security.getProviders()` and tell me the names of the providers you see?
