### ISSUE TITLE
Require content-type in Headers or Trailers-only

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#924]
By the [Spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md):

> Implementations should expect broken deployments to send non-200 HTTP status codes in responses as well as a variety of non-GRPC content-types and to omit Status & Status-Message. Implementations must synthesize a Status & Status-Message to propagate to the application layer when this occurs.

It appears that unsupported Content Types (such as "text/html; charset=UTF-8") can be returned with error information from some servers, which would be useful to propagate.

**Comment by nmittler** [comment]
For non 200's (i.e. errors), I believe the current implementation supports this.  Is that not the case?

**Comment by carl-mastrangelo** [comment]
This issue was more of a question than an actual issue.  You had looked at that code recently so I was wondering if it was handled properly.

 Looking at checkContentType(), it looks like it might only check for headers content type since contentTypeChecked will be true if trailers are received.

**Comment by nmittler** [comment]
Basically the way it works is that the first `HEADERS` block that's received wins. I believe that any unsupported content type would be returned as the first HEADERS block, so I think it should work fine.

**Comment by ejona86** [comment]
The invalid content type may or may not be in the trailers, but it would be in the status message as debugging information.

**Comment by nmittler** [comment]
So seems like we can close this as WAI?

**Comment by carl-mastrangelo** [comment]
What will happen if the following is received?  Should the trailing content type be considered an error?  It *looks* like the content type is only checked once per stream.

```
HEADERS (flags = END_HEADERS)
:status = 200
content-type = application/grpc+proto

DATA
<Delimited Message>

HEADERS (flags = END_STREAM, END_HEADERS)
grpc-status = 0 # OK
content-type = application/bad
```

**Comment by nmittler** [comment]
I'm not sure we should be handling 2 content-types on the same stream.  This seems like an error, but I would think that the safe thing to do would be to ignore the second (as we do today).  @ejona86 @louiscryan thoughts?

**Comment by ejona86** [comment]
Having content type in trailers is nonsensical, but it isn't really an error. Ignoring the second seems most appropriate.

**Comment by carl-mastrangelo** [comment]
After a quick discussion: 

I agree, it is not an error.  All trailers that don't have a "grpc-" prefix will be treated as Custom-Metadata (ignoring pseudo headers).


One thing that there is need for is for the content type to be in the headers preceding the data.  It is not clear what should happen if there are multiple Content types in that leading header.

**Comment by nmittler** [comment]
Given the discussion, renaming the issue to better fit the action required.

**Comment by ejona86** [comment]
I'm not sure what is necessary for this issue. It seems the code has already been doing the things discussed here. What am I missing?

https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/Http2ClientStream.java#L201

**Comment by nmittler** [comment]
@carl-mastrangelo do we still need this or can it just be closed?

**Comment by carl-mastrangelo** [comment]
Probably can be closed out.
