### ISSUE TITLE
how can I know the channel is inactive in the grpc server

### ISSUE THREAD

**Issue by XiaoWeiKIN** [grpc/grpc-java#9249]
I have the same problem as [#6209](https://github.com/grpc/grpc-java/issues/6209).

The scenario is: I use the GRPC client to report some microservice‘s metadata, and each client channel identifies a microservice. When the client destroy, I want to delete this  microservice‘s metadata on the server side, i.e. when the server channel breaks.

**Comment by YifeiZhuang** [comment]
I guess you might need [ServerCallStreamObserver.setOnCancelHandler](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#setOnCloseHandler-java.lang.Runnable-)?

**Comment by XiaoWeiKIN** [comment]
thanks, but I looked at the API doc and the [ServerCallStreamObserver.setOnCancelHandler](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#setOnCloseHandler-java.lang.Runnable-) seems to be stream level rather than channel level. I need to get a notification when the connection（channel） is closed.

**Comment by XiaoWeiKIN** [comment]
> I guess you might need [ServerCallStreamObserver.setOnCancelHandler](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#setOnCloseHandler-java.lang.Runnable-)?

thanks, but I looked at the API doc and the [ServerCallStreamObserver.setOnCancelHandler](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#setOnCloseHandler-java.lang.Runnable-) seems to be stream level rather than channel level. I need to get a notification when the connection（channel） is closed.
