### ISSUE TITLE
GRPC Uses Outdated Version Of protobuf-java

### ISSUE THREAD

**Issue by mr1716** [grpc/grpc-java#9264]
### What version of gRPC-Java are you using?
1.47.0

It looks like the version of protobuf-java used is outdated. It is version 3.19.2, and there are versions 3.19.4, 3.20.0, 3.20.1, 3.20.0, and 3.20.1 available that dont have vulnerabilities. Would it be possible to upgrade to one of these versions?

**Comment by mr1716** [comment]
@ejona86 I am just offering options to use. I am not the most familiar with the tool and which options would be best

**Comment by ejona86** [comment]
Is there a _problem_ you are experiencing? Upgrading protobuf [isn't a one-line change](https://github.com/grpc/grpc-java/pull/8805), but we do try to do it regularly.
