### ISSUE TITLE
failing to set Authority dynamically for custom name resolver 

### ISSUE THREAD

**Issue by sidhu-sb** [grpc/grpc-java#9266]
Hi Team , 
                   Currently we are implementing custom Name resovler for the channel which uses TLS for communication and and authority header + SNI for routing decision . we have custom scheme as below  

```
 composition:///<namespace> 
```
which resolves to either primary/secondary cluster where the namespace is currently active. 

```
dev-westeurope-01-primary-frontend.net:443 / dev-westeurope-01-secondary-frontend.net:443 
```

customResolver code looks as below 

```
public class CustomNameResolver extends NameResolver {

 @Override
    public String getServiceAuthority() {
        this.activeCluster = getActiveClusterUrl();
        return this.activeClusterUrl = this.activeCluster.getActiveCluster();
}
.
.
...
@Override
    @GuardedBy("this")
    public void refresh() {
        if (refreshing) return;
        try {
            refreshing = true;

            this.activeCluster = getActiveClusterUrl();

             activeHost = activeCluster.getActiveCluster().get().split(":");

            ScheduledExecutorService timerService = SharedResourceHolder.get(timerServiceResource);
            timerService.schedule(() -> {
                refresh();
            }, 30, TimeUnit.SECONDS);

            update(new InetSocketAddress(activeHost[0], port)));

        } finally {
            refreshing = false;
        }
    }


  private void update(SocketAddress... addresses) {
        List<EquivalentAddressGroup> servers = Arrays.stream(addresses)
                .map(EquivalentAddressGroup::new)
                .collect(Collectors.toList());
        Attributes attr = Attributes.newBuilder().set(EquivalentAddressGroup.ATTR_AUTHORITY_OVERRIDE, this.activeCluster.getActiveCluster()).build();
        listener.onAddresses(servers, attr);

    }

}
```

when use the above the initial connection works fine but on failover the we do get 404 as below because the authority header is not updated .

```
i.g.n.s.i.g.netty.NettyClientHandler - [id: 0xbc3319ae, L:/192.168.1.179:54922 - R:dev-westeurope-01-secondary-frontend.net/1.105.116.32:443] OUTBOUND HEADERS: streamId=33 headers=GrpcHttp2OutboundHeaders[:authority: dev-westeurope-01-primary-frontend.net:443, :path:/apuicall temporal.api.workflowservice.v1.WorkflowService/PollWorkflowTaskQueue, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.47.0, client-version: 1.12.0, supported-server-versions: >=0.31.0 <2.0.0, client-name: temporal-java] 

io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,date=Mon, 13 Jun 2022 08:44:31 GMT,content-type=text/plain; charset=utf-8,strict-transport-security=max-age=15724800; includeSubDomains,content-length=21)
DATA-----------------------------
default backend - 404
```
we were expecting the authority header to be updated dynamically but it doesn't get updated as i see in the above log. 

any leads or help on this would be appreciated .

we are using ManagedChannelBuilder as below 

```
ManagedChannelBuilder.forTarget("composition:///testNamespace")
.sslContext(SslContextBuilder
                                    .forClient()
                                    .trustManager(this.getClass().getClassLoader().getResourceAsStream("certs" + File.separator + config.getCertFileName()))
                                    .applicationProtocolConfig(
                                            new ApplicationProtocolConfig(
                                                    ApplicationProtocolConfig.Protocol.ALPN,
                                                    ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
                                                    ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
                                                    ApplicationProtocolNames.HTTP_2, ApplicationProtocolNames.HTTP_1_1))
                                    .build())
.build();
```

**Comment by ejona86** [comment]
See the documentation for [`getServiceAuthority()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/NameResolver.html#getServiceAuthority--):
> Returns the authority used to authenticate connections to servers. It **must** be from a trusted source, because if the authority is tampered with, RPCs may be sent to the attackers which may leak sensitive user data.
>
> An implementation must generate it without blocking, typically in line, and **must** keep it unchanged. NameResolvers created from the same factory with the same argument must return the same authority.

It is likely you are probably breaking both "must" requirements. Realize that means that TLS is useless and isn't providing much purpose; you might as well be using plaintext.

Using external I/O to determine the name of the authority simply isn't safe. You would probably need to list the allowed authorities somewhere. Let's say you put it in the target string (I'm just making up a format, you can do lots of other options like use query parameters if you want):
```
composition:///<namespace>/authorities=dev-westeurope-01-primary-frontend.net:443,dev-westeurope-01-secondary-frontend.net:443
```

Then, in your NameResolver you would verify the received name against the allowed list.

Is that something you are able to do? Given the formatting of those names, those authorities don't seem too stable over time. If they are stable, then I can point you to an API that lets you set the authority dynamically. But it is important to confirm you can implement it securely, because many people don't realize they are making TLS useless and once I point it out I get an "oh" response and they have to rethink their infrastructure.

**Comment by sidhu-sb** [comment]
@ejona86  In our case we control the server (cluster group) & the server authority is trusted as server API is responding with the endpoint and the authority it is expected the client to connect to. If the namespace on one cluster fails over to another cluster the server endpoint response changes so we need to change the authority as well on the client end for the SNI and authority header to reflect that change as otherwise the connection won't route to the secondary cluster successfully.

**Comment by ejona86** [comment]
Ah, excellent. Yeah, talking to a coordination server over TLS would satisfy the need. The only thing to realize is that coordination server can impersonate the actual service. But that's acceptable in many circumstances.

You can use [ATTR_AUTHORITY_OVERRIDE](https://grpc.github.io/grpc-java/javadoc/io/grpc/EquivalentAddressGroup.html#ATTR_AUTHORITY_OVERRIDE) in the EquivalentAddressGroup to tell gRPC to use a different authority.

The authority you return via `getServiceAuthority()` is best if it doesn't perform I/O. So I suggest just setting it based on the `<namespace>` or such. That authority mostly won't matter in your setup; it would just be what is returned in `Channel.authority()` which is rarely used.

**Comment by sidhu-sb** [comment]
@ejona86  thanks . I did use the [ATTR_AUTHORITY_OVERRIDE](https://grpc.github.io/grpc-java/javadoc/io/grpc/EquivalentAddressGroup.html#ATTR_AUTHORITY_OVERRIDE) of the EquivalentAddressGroup in the below code block . 

```
 private void update(SocketAddress... addresses) {
        List<EquivalentAddressGroup> servers = Arrays.stream(addresses)
                .map(EquivalentAddressGroup::new)
                .collect(Collectors.toList());

        Attributes attr = Attributes.newBuilder().set(EquivalentAddressGroup.ATTR_AUTHORITY_OVERRIDE, this.activeCluster.getActiveCluster()).build();

        listener.onAddresses(servers, attr);
    }
```

As i can see in the below logs the authority header is still pointing to primary while its updated secondary.  Am i doing something wrong while setting the ATTR_AUTHORITY_OVERRIDE ? 


```
i.g.n.s.i.g.netty.NettyClientHandler - [id: 0xf25bc88e, L:/192.168.1.149:63797 
- R:dev-westeurope-01-secondary-frontend.net/1.105.116.32:443] OUTBOUND HEADERS: streamId=27 
headers=GrpcHttp2OutboundHeaders[:authority: dev-westeurope-01-primary-frontend.net:443, 
:path: /temporal.api.workflowservice.v1.WorkflowService/PollActivityTaskQueue, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.47.0, client-version: 1.12.0, supported-server-versions: >=0.31.0 

i.t.internal.retryer.GrpcRetryer - Final exception, throwing
io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=404,date=Thu, 16 Jun 2022 04:53:56 GMT,content-type=text/plain; charset=utf-8,strict-transport-security=max-age=15724800; includeSubDomains,content-length=21)
DATA-----------------------------
default backend - 404
```

**Comment by ejona86** [comment]
The attribute needs to be set in the `EquivalentAddressGroup`, not passed to `onAddresses()`.

**Comment by sidhu-sb** [comment]
@ejona86  thanks 👍
