### ISSUE TITLE
ReferenceCounted is useless

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#927]
777e928 introduced reference counting for channel builders, but nothing ever does a retain(), making it useless.

I thought the original reason to propose having reference counting was so that transports would `retain()` their factory and then `ChannelImpl` would `release()` the factory immediately on `shutdown()`. As the transports shutdown they would each `release()` and any shared resources would naturally be released.

@nmittler, FYI

**Comment by nmittler** [comment]
@ejona86 the default reference count upon creation is 1, so there' s an implicit retain being done.

**Comment by ejona86** [comment]
@nmittler, but if the reference count is only zero or one, then all we need is a `close()` method. Actually reference counting is useless.
