### ISSUE TITLE
gRPC-okhttp ipv6 link local scope

### ISSUE THREAD

**Issue by jader-eero** [grpc/grpc-java#9325]
### What version of gRPC-Java are you using?
1.45.0

### What is your environment?
MacOS jdk 8

### What did you expect to see?
I expect gRPC-okhttp be able to work with ipv6 link local with scope

### What did you see instead?
AndroidNegotiator inside OkHttpProtocolNegotiator.java class is using `SNI_HOST_NAME.newInstance(hostname)` which throws exception because SNIHostName(String hostname) doesn't accept "%" and we need that for scoping ipv6 link local. 

**Suggestion** would be using SNIHostName(byte[] encoded). To do so we would need to replace line 252 to `SNI_HOST_NAME.newInstance(hostname.getBytes())`

### Steps to reproduce the bug
Any connection that uses `configureTlsExtensions` from AndroidNegotiator class which uses ipv6 link local with scoping like "%wlan0"

**Comment by jader-eero** [comment]
PR open https://github.com/grpc/grpc-java/pull/9326

**Comment by ejona86** [comment]
Reverted in #9375

**Comment by shivaspeaks** [comment]
The reverted PR mentioned above says, 
> It produced compilation issues inside Google. I strongly suspect it isn't
this commit or gRPC's fault, but it prevents further testing until it is
resolved.

I see that the blaze build is successful in google3 with the fix that was reverted.
`!InetAddresses.isInetAddress(HostAndPort.fromString(hostname).getHost())`

Perhaps, the compilation issue was not gRPC's fault? 🧐 @ejona86

**Comment by ejona86** [comment]
It wasn't gRPC's fault. But something using gRPC on Android had a build that couldn't depend on (IIRC) HostAndPort because of funny business they were doing with Guava or something.
