### ISSUE TITLE
Tracking Issue for Handler Registry being experimental.

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#933]
We're currently marking all of the `HandlerRegistries` as `ExperimentalAPI`. We should decide on the appropriate interface and move toward making them public.

**Comment by zhangkun83** [comment]
@ejona86 @louiscryan and I had a conversation today. Here are the highlights:
 1. Deprecate `MutableHandlerRegistry`, and later maybe place `MutableHandlerRegistryImpl`, which implements `HandlerRegistry`, in a util package.
 2. `ServerBuilder.addService()` register handlers to an internal primary registry, which is immutable after built. The primary registry is not public API, so we are free to do optimizations for hpack. It doesn't support `removeService()` so we can flatten the lookup table (#1713) without a problem.
 3. `HandlerRegistry` will stay as public API, but will only be used as a secondary dispatching mechanism which is only used when the primary handler registry doesn't find a match. This is the same idea as Stubby's default handler. `HandlerRegistry` can be a mutable lookup map (i.e., `MutableHandlerRegistryImpl`) or a totally dynamic one, which is up to the user. We will add a `setFallbackHandlerRegistry(HandlerRegistry)` to `ServerBuilder`.

This change will simplify our API surface while giving reasonable freedom of further optimization to us, and flexibility to the users.

**Comment by zhangkun83** [comment]
We are going to keep `HandlerRegistry` experimental, because many people will be using the internal static registry and there haven't been enough users to use the `HandlerRegistry` API.

**Comment by carl-mastrangelo** [comment]
This bug should stay open until all `@ExperimentalApi` annotations are removed for Handlers!
===

Specific usages:

* `HandlerRegistry`
* `MutableHandlerRegistry`
* `MutableHandlerRegistryImpl`
* `ServerCallHandler`

**Comment by zhangkun83** [comment]
Now `ServerCallHandler` is non-experimental. `HandlerRegistry`-related code will remain experimental in 1.0.

**Comment by ejona86** [comment]
API review:
* stabilize HandlerRegistry as-is (leaving getServices() experimental)
* stabilize ServerBuilder.fallbackHandlerRegistry
* No qualms with MutableHandlerRegistry. But want to delaying stabilizing things in util until we split grpc-api out of core.
