### ISSUE TITLE
How could I establish multiple tcp connections to the same IP address in single gRPC stub

### ISSUE THREAD

**Issue by aaron-ai** [grpc/grpc-java#9357]
Actually the IP address we used in the stub is a VIP(Virtual IP) which contains multiple RS(Real Server). 

We want to be able to establish multiple physical connections to a VIP for better load balancing.

**Comment by sanjaypujare** [comment]
Interesting use-case. One way I can think of is to use a custom [NameResolver](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/NameResolver.java) which returns the same IP address (VIP) as multiple [`EquivalentAddressGroup`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/NameResolver.java#L178)s and make each one distinct by setting distinct `Attributes` on each. And use this with round-robin load balancer.

**Comment by sanjaypujare** [comment]
Just noticed there is an issue https://github.com/grpc/grpc/issues/7957 that talks about this although it is in the core repo. Doing this properly would require cross lang design so it is best to track this request using the older core issue.

**Comment by ejona86** [comment]
See in particular https://github.com/grpc/grpc/issues/7957#issuecomment-289515839 which has a snippet for the approach in Java.
