### ISSUE TITLE
xds: support more HTTP filters

### ISSUE THREAD

**Issue by olderwei** [grpc/grpc-java#9364]
Are there any plans to support more HTTP filters, such as LocalRateLimit

**Comment by temawi** [comment]
In general we do want to support more filters, and we do that based on demand. There is no firm roadmap for new ones but there is some effort being put in supporting [rate limit quotas](https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/filters/http/rate_limit_quota/v3/rate_limit_quota.proto), although that would be global rate limiting, not local.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
