### ISSUE TITLE
Replace use of ExecutorService with Executor in builders

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#937]
@ejona86 
We don't depend on ExecutorService so we can downgrade the requirement here.

**Comment by ejona86** [comment]
+1. As discussed offline, it wouldn't be an API change, but it would be an ABI change, so we should probably do it now. I question if we've defined our ABI stability story post-beta.

**Comment by ejona86** [comment]
Using api-breaking label even though it is just abi-breaking.

**Comment by ejona86** [comment]
Because of our move from AbstractChannelBuilder to the no-impl ManagedChannelBuilder, this would actually be api-breaking.
