### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by moose007** [grpc/grpc-java#9386]
In the v1.44.0 release notes, 

Java 8 users pay note: per gRFC P5, gRPC may drop Java 8 support as soon as March this year.

My organization, a big enterprise, still uses jdk8 ubiquitously, I expect migration to jdk11+ early next year. Is dropping jdk8 still expected this year? If so, this will definitely disrupt our current project that uses grpc-java.

**Comment by ejona86** [comment]
I'm in talks with some others about Java 8 as well. Obviously it has been delayed some already. Right now the range of plans seems to be between dropped "soon" (within a month or two) or dropped simultaneously with Java 11 in September next year.

Can you help explain how it will disrupt you? (There's lots of ways it could, but it helps to understand how you are impacted.) There'd still remain a minor branch open that could receive bug fixes. So are the sorts of problem like "we want new features." Or other emergent problems like "it is hard to coordinate the version of grpc-java to use with a mix of Java 8 and 11 projects."

**Comment by ejona86** [comment]
Although I'd still be interested in how Java 8 impacts you, but haven't heard back, so closing.
