### ISSUE TITLE
How to obtain instance of ScheduledExecutorService in ServerInterceptor?

### ISSUE THREAD

**Issue by PeterFras** [grpc/grpc-java#9420]
Hi all,
I am writing a server interceptor which will set default deadline for calls missing the deadline. I am having problems calling `ctx.withDeadline` which requires instance of  ScheduledExecutorService. I searched through the code and it looks like `ServerTransport` has one which I could use but I am not sure how to reference transport in the interceptor. I would like to avoid creating new instance of executor to keep the interceptor stateless and as simple as possible. Any ideas? Cheers

```scala
object DeadlineInterceptor extends ServerInterceptor {

  private val defaultDeadline = 5 * 1000 // 5 seconds

  override def interceptCall[ReqT, RespT](call: ServerCall[ReqT, RespT], headers: Metadata, next: ServerCallHandler[ReqT, RespT]): ServerCall.Listener[ReqT] = {
    val ctx = Context.current
    val scheduler: ScheduledExecutorService = ???
    val contextWithDeadline = ctx.withDeadline(Deadline.after(deadline, TimeUnit.MILLISECONDS),  scheduler)
    Contexts.interceptCall(contextWithDeadline, call, headers, next)
  }
}
```

**Comment by sanjaypujare** [comment]
> ...I am not sure how to reference transport in the interceptor....

`ServerTransport` is an internal API so you should not use it. You should use your own executor - I don't see any problem with it.

**Comment by ejona86** [comment]
I'd normally expect you to pass the scheduled executor into the constructor of the interceptor.

**Comment by PeterFras** [comment]
Hi guys, thanks for your answers. Makes sense to me. Cheers
