### ISSUE TITLE
Equality of ConnectivityStateInfo depends on the not-well-defined equality of Status

### ISSUE THREAD

**Issue by bgruber** [grpc/grpc-java#9432]
Hello,

We were recently bitten by a bug caused by checking two instances of `io.grpc.Status`, and learned that we should really be comparing the Codes contained therein. In an attempt to ferret out other bugs caused by misusing Status, we tried turning on the `io.grpc.Status.failOnEqualsForTest` system property while running our tests. This caused several of our integration tests to fail when using a `HealthCheckingLoadBalancer`, because internally it [checks the equality of ConnectivityStateInfo objects](https://github.com/grpc/grpc-java/blob/050cdb14fe3ee9508ab3849ea38495edd47d904f/services/src/main/java/io/grpc/protobuf/services/HealthCheckingLoadBalancerFactory.java#L330), and that equality is [defined in terms of the equality of status](https://github.com/grpc/grpc-java/blob/050cdb14fe3ee9508ab3849ea38495edd47d904f/api/src/main/java/io/grpc/ConnectivityStateInfo.java#L77).

I'm not sure if there's any actual bug in`HealthCheckingLoadBalancer` because of this, since the worst thing that happens is the SubchannelStateListener gets called an extra time when the status didn't really change. But since `ConnectionStateInfo` is a public class in the library, I wanted to raise this as a potential issue.

**Comment by YifeiZhuang** [comment]
Thank you reporting the issue.
Sorry for it being causing troubles. Looking at the comments it looks best effort. Acknowledged, feel free to reopen if there are new findings.
