### ISSUE TITLE
why grpc-lite's Class Any doesn't contain is and unpack methods?

### ISSUE THREAD

**Issue by jiangjiongyu** [grpc/grpc-java#9446]
config:
//    implementation 'io.grpc:grpc-okhttp:1.42.0'
    implementation 'io.grpc:grpc-netty-shaded:1.42.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.42.0'
//       implementation 'io.grpc:grpc-protobuf:1.42.0'
    implementation 'io.grpc:grpc-stub:1.42.0'
    implementation 'org.apache.tomcat:tomcat-annotations-api:9.0.58'

**Comment by sanjaypujare** [comment]
This is a protobuf issue - see https://github.com/google/protobuf-gradle-plugin/issues/252#issuecomment-652492959 .

**Comment by jiangjiongyu** [comment]
fine...
