### ISSUE TITLE
Error while generating grpc files (--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.)

### ISSUE THREAD

**Issue by jubla102** [grpc/grpc-java#9450]
I’m trying to run the following command to generate grpc files:
`protoc --proto_path=$PROTO_PATH --plugin=protoc-gen-grpc=$PLUGIN_GRPC --grpc_out=$OUT/grpc $PROTO_FILES`

This results in the following error: 
**/Users/MYUSERNAME/Downloads/protoc-gen-grpc-java-1.48.1-osx-aarch_64.exe: program not found or is not executable Please specify a program using absolute path or make sure the program is available in your PATH system variable --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.**

I made sure the file from the error message is located at that path and has also the correct permissions.

`-rwxrwxrwx@ 1 MYUSERNAME staff 6334176 10 Aug 00:03 protoc-gen-grpc-java-1.48.1-osx-aarch_64.exe`

I also tried running the command as sudo.

Generating java or kotlin files with `--java_out=$OUT/java --kotlin_out=$OUT/kotlin`

works perfectly fine, so the problem is `--grpc_out=$OUT/grpc`

I also downloaded multiple versions of the protoc-gen-grpc-java-1.48.1-osx-aarch_64.exe file but it always results in the same error. I also tried replacing all path variables (e.g. $PROTO_PATH) with their corresponding values, without any effect. I’m using MacBook with M1Pro chip.

**Comment by temawi** [comment]
It does appear that there might be a problem with the executable - are you able to run it directly?

**Comment by ejona86** [comment]
Call `/Users/MYUSERNAME/Downloads/protoc-gen-grpc-java-1.48.1-osx-aarch_64.exe` directly in a console. If it hangs, that's okay, as it is waiting for input from stdin. But if it fails it means something is wrong in your environment, like you need to call `chmod +x` on it.

**Comment by Phlegethon90** [comment]
Fixed it by `softwareupdate --install-rosetta`, because the executable is still x86.

**Comment by jubla102** [comment]
> Fixed it by `softwareupdate --install-rosetta`, because the executable is still x86.

Fixed my issue!
