### ISSUE TITLE
grpc to tun (Android)

### ISSUE THREAD

**Issue by tormentous** [grpc/grpc-java#9454]
I'm new to grpc.
Is it possible for ParcelFileDescriptor instance to read and write packets to and from grpc? What is the proper way to do it? Thank you!

**Comment by temawi** [comment]
You could take a look at this related specification, maybe it will help you achieve what you need to.

https://github.com/grpc/proposal/blob/master/L73-java-binderchannel.md

**Comment by tormentous** [comment]
> You could take a look at this related specification, maybe it will help you achieve what you need to.
> 
> https://github.com/grpc/proposal/blob/master/L73-java-binderchannel.md

Thank you for your valuable response!
The proposal seems to be unapproved and is apparently available only to the author and some internal users. Any chance that I can test it?
