### ISSUE TITLE
Exceed deadline with different timeout as i set

### ISSUE THREAD

**Issue by smartnews-weitao** [grpc/grpc-java#9457]
Hello team, so i am using grpc-java to do some heavy network jobs, my service is setup on kubernetes and it's using grpc to request the servers. And i do noticed 2 weird things:

1. Netty is a real monster when it comes to consume direct memory, often i got outOfDirectMemory, I opened netty's detectLeak, however i didn't get any leak logs even i set the detect level to advanced. Not sure whether my grpc-netty-shaded version is too low or there's no memory leak at all. I am using io.grpc:grpc-netty-shaded:jar:1.36.0. So right now i have to give the pod more non-heap memory for direct memory allocation.

2. I am setting my grpc deadline as 200ms, however when i check my logs, i do find theres timeout logs:

DEADLINE_EXCEEDED: deadline exceeded after 0.121722083s. [buffered_nanos=124532238, waiting_for_connection]
Sometimes it's:
DEADLINE_EXCEEDED: deadline exceeded after 0.199874339s. [buffered_nanos=200032404, waiting_for_connection]

The second one makes more sense to me since my setting timeout is 0.2s.

So i am wondering is there any suggestions? Appreciate your help.

**Comment by sanjaypujare** [comment]
> ...i set the detect level to advanced...

What property name are you using to set the detect level? For shaded netty you have to update the property name accordingly.

**Comment by smartnews-weitao** [comment]
@sanjaypujare 
Appreciate the quick reply. I am using '-Dio.netty.leakDetection.level=advanced'

**Comment by sanjaypujare** [comment]
Since you are using shaded netty use `-Dio.grpc.netty.shaded.io.netty.leakDetection.level=advanced` or you may consider using paranoid like this `-Dio.grpc.netty.shaded.io.netty.leakDetection.level=paranoid`

**Comment by smartnews-weitao** [comment]
Thx i will try and come back later.

**Comment by smartnews-weitao** [comment]
Well, my service haven't log any LEAK message in past few days. But the kubernetes entire pod memory usage has been keep growing. I am wondering will the FULL GC clean the direct memory? Because currently my old generation is large and relatively empty, so i have never triggered a FULL GC yet, Just some minor GC in eden space. So if Full GC will clean the direct memory and i have never triggered the full gc, this might be the reason? And here is my JVM config:

"-Xmx6144m", "-Xms6144m", "-Dio.grpc.netty.shaded.io.netty.leakDetection.level=advanced", "-XX:MetaspaceSize=400m",  "-XX:+UseConcMarkSweepGC", "-XX:CMSInitiatingOccupancyFraction=70", "-XX:NewRatio=1", "-XX:SurvivorRatio=2", "-XX:TargetSurvivorRatio=90", "-XX:MaxTenuringThreshold=15", "-XX:+DisableExplicitGC"

**Comment by ejona86** [comment]
I wouldn't expect any leaks. Leaks would impact everyone quite a bit. You can configure things to prefer heap memory instead of direct via `-Dio.grpc.netty.shaded.io.netty.noPreferDirect=true`

**Comment by smartnews-weitao** [comment]
Thanks for the advice, but then will netty consume too much memory and thus increase our latency because we have GC very frequently?

**Comment by ejona86** [comment]
It does not change the amount of memory, only the type of memory. It would change the GC frequency, but you have to choose to either use direct or heap.

**Comment by ejona86** [comment]
Actually, it wouldn't change the GC frequency _much_ because the buffers are still reused. But peaks in memory and GC can still happen (but that would have been the case with direct as well).

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
