### ISSUE TITLE
com.google.protobuf issue while doing gradlew installDist

### ISSUE THREAD

**Issue by saimahaji** [grpc/grpc-java#9458]
When im running gradlew installDist from cmd, getting below error for grcp-java 1.48.0:

Plugin [id: 'com.google.protobuf', version: '0.8.18] was not found in any of the following sources.
-Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
-Plugin repositories (could not resolve plugin artifact 'com.google.protobuf:com.google.protobuf.gradle.plugin:0.818)

**Comment by temawi** [comment]
This is generally a problem with Gradle downloading the plugin. Maybe it's a flake - does it happen for you consistently?

**Comment by saimahaji** [comment]
I'm using jdk 8 and gradle 7.5. i. If I run this command from sts gradle task, it runs properly but does not generate build folder under examples. So I tried running it from command line. But it is getting failed each time.

**Comment by ejona86** [comment]
Can you paste the build code snippet you're using to use the protobuf plugin?

**Comment by saimahaji** [comment]
I have not made any change in examples/build.gradle 
I have taken a clone of this project and trying to run as it is.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
