### ISSUE TITLE
Support SSL mutual authentication

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#946]
Reported by @megapowers 

Hi all,

I am currently using gRPC 8.0 with ALPN and I am trying to implement a 2-way SSL authentication between a client and server.

However, upon inspection of the SSL debug logs, I noticed that the CertificateRequest message (as stated in https://en.wikipedia.org/wiki/Transport_Layer_Security#Client-authenticated_TLS_handshake), was never sent to the client to initiate the Client Authentication.

An excerpt of my server log is as follows:
```
...
*** ECDH ServerKeyExchange
Signature Algorithm SHA512withRSA
Server key: Sun EC public key, 256 bits
public x coord: 81392923578261760187813715443713168545877454618233337093852615933913992434989
public y coord: 26389586381130695169212775668808794166799180199461581135201001980310825571555
parameters: secp256r1 NIST P-256, X9.62 prime256v1
*** ServerHelloDone
[write] MD5 and SHA1 hashes: len = 1617
0000: 02 00 00 56 03 03 55 DF 34 10 9C 73 B5 00 C2 70 ...V..U.4..s...p
0010: FD B8 CC 36 5B 83 87 70 5B 74 A3 D2 AD B7 75 3B ...6[..p[t....u;
...
```

The code I am using at server is as follows:

```java
SslContext sslContext = GrpcSslContexts.forServer(new File(pathToOwnCertPemFile), new File(pathToOwnPrivateKeyPemFile)).trustManager(new File(pathToClientCertPemFile)).build();

ServerImpl server = NettyServerBuilder
.forPort(port)
.sslContext(sslContext)
.addService(MyGrpc.bindService(new MyGrpcService()))
.build().start();
```

The code I am using at my client is as follows:

```java
SslContext sslContext = GrpcSslContexts.forClient().trustManager(new File(pathToServerCertPemFile)).keyManager(new File(pathToOwnCertPemFile), new File(pathToOwnPrivateKeyPemFile)).build();

ChannelImpl channel = NettyChannelBuilder.forAddress(host, port)
.negotiationType(NegotiationType.TLS)
.sslContext(sslContext).build();

blockingStub = MyGrpc.newBlockingStub(channel);
asyncStub = MyGrpc.newStub(channel);
```

Am I missing out something? Or is it an inherent bug in gRPC?

**Comment by nmittler** [comment]
I've created this PR to address: https://github.com/netty/netty/pull/4237

**Comment by ejona86** [comment]
Although far too generic to really be helpful C has [security_context.h](https://github.com/grpc/grpc/blob/4f21d3549c8f652a152ae086a74dd8415ecca8fa/src/core/security/security_context.h), which is then exposed in C++ in [auth_context.h](https://github.com/grpc/grpc/blob/2311d4918f26e48500b790f538566032a1f0c713/include/grpc%2B%2B/security/auth_context.h)

**Comment by ejona86** [comment]
For IP-address (which is not authenticated, and seems likely to be separate from work on this issue), C has [call_get_peer](https://github.com/grpc/grpc/blob/4f21d3549c8f652a152ae086a74dd8415ecca8fa/include/grpc/grpc.h#L538). It returns a string like "ipv4:127.0.0.1:1234"

**Comment by ejona86** [comment]
The netty bug is fixed. It should be able to do mutual authentication now. It is not yet possible to retrieve the client certificate on the server though.

**Comment by robeden** [comment]
Any idea on the priority and/or ETA of allowing retrieval of the client certificate on the server?

**Comment by nmittler** [comment]
Sorry, I've been distracted by some other tasks and probably won't get to this in the near term.  Reassigning to @ejona86 to prioritize.

**Comment by ejona86** [comment]
I believe this is required for 1.0, which we are targeting for very late Q1. It isn't actually very hard; the biggest delay would probably be designing the ~1 method API.

**Comment by ejona86** [comment]
SSLSession was exposed in #1506, and API made more public in #1564
