### ISSUE TITLE
should grpc pass context when process triggered by drainPendingCalls

### ISSUE THREAD

**Issue by vio-lin** [grpc/grpc-java#9478]
I want to get Context  value when stream my request body.
There is something wrong when i get [null] value in context. 
I believe context should be unique and accessable when request and response.

Request process will use the Context.current  and response process use the context saved in  DelayedClientCall.

but when request process triggered by `drainPendingCalls`
it changed to execute delay and do not run in context we save .

io.grpc.internal.DelayedClientCall#drainPendingCalls
```java
  for (Runnable runnable : toRun) {
        // Must not call transport while lock is held to prevent deadlocks.
        // TODO(ejona): exception handling
        runnable.run();
      }
      toRun.clear();
```

i think it is more reasonable to use like this
```java
  for (Runnable runnable : toRun) {
        // Must not call transport while lock is held to prevent deadlocks.
        // TODO(ejona): exception handling
       context.run( ()->{runnable.run()});
   }
      toRun.clear();
```

**Comment by ejona86** [comment]
The code in DelayedClientCall isn't expecting to run under the context. Could you show a sketch of your code that calls into gRPC to make it clear how you notice the context isn't set?

**Comment by vio-lin** [comment]
> The code in DelayedClientCall isn't expecting to run under the context. Could you show a sketch of your code that calls into gRPC to make it clear how you notice the context isn't set?

https://github.com/vio-lin/GitMyLife/tree/grpc-demop
this is my code.  
run server : GitMyLife\main-app\src\main\java\com\violin\grpc\demo\main\GrpcServer.java
run client: GitMyLife\main-app\src\main\java\com\violin\grpc\demo\main\GrpcClient.java
input 1 for protobuf request
input 2 for  pojo request

We have a service wrotten with java bean。We want to migrate it to grpc witch based http2 protocol.
As we notice grpc use header "content-type/grpc+json" to support external serialization,
we change marshaller to support json. In this way the old system can easily upgrade.
We use header to transport serialization string from client to service and use Context to save this in progress request or response.

But the first request  can not read Context value。

**Comment by ejona86** [comment]
Using Context is Marshaller is definitely not a design goal, especially when combined with a transport tracer. So I'm very much not excited about the approach you've taken. But I do think your pointing out a legit issue, _especially_ for `listener.drainPendingCallbacks()`.

nit: `CodeContext` on client-side is unnecessary. You can use [`stub.withOption()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withOption-io.grpc.CallOptions.Key-T-) instead, which will show up in the `CallOptions` passed to the interceptor.

You don't need to use Context at all on client-side, as you can change the marshaller in MethodDescriptor in GrpcClientIntercept. There are some other options for server-side like rewriting the ServerServiceDefinition, but they are more complicated.

**Comment by ejona86** [comment]
Oh, actually, `drainPendingCallbacks()` is already okay. It is being run within a `ContextRunnable`.

We can fix the non-Listener calls just to reduce chances of other bugs, as the DelayedClientCall is used rarely and tracking down the source of problems would be very difficult.
