### ISSUE TITLE
invalid content-type: text/plain; charset=utf-8

### ISSUE THREAD

**Issue by tormentous** [grpc/grpc-java#9496]
Hi, I'm trying to make a grpc tunnel for android, I was able to connect to my server but when attempting to create terminal channel I got this error.

```
io.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 200
    invalid content-type: text/plain; charset=utf-8
    headers: Metadata(:status=200,content-type=text/plain; charset=utf-8,date=Sat, 27 Aug 2022 02:11:46 GMT,content-length=13)
    DATA-----------------------------
    Hello,世界!
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by tormentous** [comment]
file:/Users/mcbook/AndroidStudioProjects/gRPCClient/app/src/main/java/com/dzebb/grpc/SocketServerToGrpcTunnel.java

**Comment by tormentous** [comment]
package com.grpc.tunnel;

import android.util.Log;

import com.google.protobuf.ByteString;

import java.io.Closeable;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

import io.grpc.ManagedChannel;
import io.grpc.Metadata;
import io.grpc.netty.GrpcSslContexts;
import io.grpc.netty.NettyChannelBuilder;
import io.grpc.stub.MetadataUtils;
import io.grpc.stub.StreamObserver;
import io.netty.handler.ssl.SslContext;
import io.netty.handler.ssl.util.InsecureTrustManagerFactory;

public class SocketServerToGrpcTunnel implements Closeable {
    public SocketServerToGrpcTunnel(long target_id, String host, int port, int serving_port) throws Exception {
        target_id_ = target_id;
        serving_port_ = serving_port;

        channel_ = NettyChannelBuilder.forAddress(host, port)
                .enableFullStreamDecompression()
                .useTransportSecurity()
                .sslContext(GrpcSslContexts.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE)
                        .sslProvider(SslContext.defaultClientProvider())
                        .startTls(true)
                        .sessionTimeout(0)
                        .build())
                .idleTimeout(5, TimeUnit.MINUTES)
                .keepAliveWithoutCalls(true)
                .keepAliveTime(20, TimeUnit.MINUTES)
                .keepAliveTimeout(2, TimeUnit.HOURS)
                .build();
        Metadata metadata = new Metadata();
        metadata.put(Metadata.Key.of("target_id", Metadata.ASCII_STRING_MARSHALLER), Long.toString(target_id));
        async_stub_ = MetadataUtils.attachHeaders(GrpcServeGrpc.newStub(this.channel_), metadata);
    }

    public void start() {
        Log.i("tunnel", "Starting tunnel maintenance thread");
        System.out.println();
        execution_thread_.start();
    }
    public void close() {
        tunnel_closed(true);
        channel_.shutdown();
        try {
            execution_thread_.join();
        } catch (InterruptedException e) {
        }
    }

    private class TunnelMessageStreamObserver implements StreamObserver<PacketData> {
        @Override
        public void onNext(PacketData message) {
            Log.i("tunnel", "Received message " + message);
            if (message.getPayload() == null || message.getPayload().isEmpty())
                change_elector_availability();
            else
                send_through_socket(message);
        }

        @Override public void onError(Throwable t) {
            Log.w("tunnel", "error on tunnel", t);
            tunnel_closed(false);
        }

        @Override public void onCompleted() {
            tunnel_closed(false);
        }
    }

    private void execution_loop() {
        while (true) {
            // Always keep connection alive
            if (!start_call()) break;

            byte[] in_bytes = new byte[4096];
            while (wait_for_available_elector()) {
                try (ServerSocket server = new ServerSocket(serving_port_);
                     Socket socket = server.accept()) {
                    Log.i("tunnel", "accepted socket connection");
                    socket_.set(socket);
                    send_through_tunnel(ByteString.EMPTY);

                    int num_read;
                    while ((num_read = read_from_socket(in_bytes)) > 0)
                        send_through_tunnel(ByteString.copyFrom(in_bytes, 0, num_read));
                } catch (IOException e) {
                    Log.w("tunnel", "Error while handling socket", e);
                } finally {
                    Log.i("tunnel", "closing socket connection");
                    mark_socket_close();
                }
            }
        }
    }

    private synchronized boolean start_call() {
        if (stop_all_)
            return false;
        Log.i("tunnel", "Attempting to create terminal channel");
        tunnel_sender_ = async_stub_.tunnel(new TunnelMessageStreamObserver());
        return true;
    }

    private synchronized void change_elector_availability() {
        elector_available_ = !elector_available_;
        this.notify();
    }

    private synchronized boolean wait_for_available_elector() {
        while (!elector_available_ && !stop_all_ && tunnel_sender_ != null) {
            try {
                this.wait();
            } catch (InterruptedException e) {
                break;
            }
        }
        return elector_available_;
    }

    private synchronized void send_through_tunnel(ByteString bytes) {
        if (tunnel_sender_ == null)
                return;
        Log.i("tunnel", "sending message with " + bytes);
        tunnel_sender_.onNext(PacketData.newBuilder()
                .setTargetId(target_id_)
                .setPayload(bytes)
                .build());
    }

    private synchronized void tunnel_closed(boolean stop_requested) {
        if (stop_requested) {
            stop_all_ = true;
            if (tunnel_sender_ != null)
                tunnel_sender_.onCompleted();
        }
        tunnel_sender_ = null;
        socket_.set(null);
        elector_available_ = false;
        this.notify();
    }

    private int read_from_socket(byte[] in_bytes) throws IOException {
        Socket socket = socket_.get();
        if (socket != null)
            return socket.getInputStream().read(in_bytes);
        return 0;
    }

    private void send_through_socket(PacketData message) {
        Socket socket = socket_.get();
        if (socket == null)
            return;
        try {
            message.getPayload().writeTo(socket.getOutputStream());
        } catch (IOException e) {
            Log.w("tunnel", "Error sending to socket", e);
            mark_socket_close();
        }
    }

    private void mark_socket_close() {
        if (socket_.getAndSet(null) != null)
            send_through_tunnel(ByteString.EMPTY);
    }

    private final long target_id_;
    private final int serving_port_;
    private final ManagedChannel channel_;
    private final GrpcServeGrpc.GrpcServeStub async_stub_;
    private final Thread execution_thread_ = new Thread(this::execution_loop);

    private volatile StreamObserver<PacketData> tunnel_sender_;
    private final AtomicReference<Socket> socket_ = new AtomicReference<>();

    private boolean elector_available_ = false;
    private boolean stop_all_ = false;
}

**Comment by ejona86** [comment]
The server that created that response does not appear to be a gRPC server. The content type is text/plain and `Hello,世界!` is 13 bytes long which matches the content-length. gRPC would have had an additional 5 bytes for message framing. Check your server.
