### ISSUE TITLE
First received frame was not SETTINGS. Hex dump for first 5 bytes: 0000000401

### ISSUE THREAD

**Issue by guyinyou** [grpc/grpc-java#9499]
### What version of gRPC-Java are you using?
server(java):
<grpc.version>1.45.0</grpc.version>
<protobuf.version>3.20.1</protobuf.version>

client(go):
require google.golang.org/grpc v1.48.0

### What is your environment?

MacOS 12.3 (21E230)
jdk 1.8
go 1.17

**Comment by guyinyou** [comment]
refer https://github.com/grpc/grpc-go/issues/5615

**Comment by ejona86** [comment]
Can you provide code snippets or more information about your network. This sort of error is not normal. It isn't even clear where the error is happening, although I suspect it is on server-side because that looks like a grpc-java error.

That looks like a SETTINGS frame. It is a zero-length SETTINGS, but it is an ACK. That fifth byte should be `00`.

**Comment by guyinyou** [comment]
I want to ask a question.

Whether the SETTINGS frame can be sent anytime, anywhere.

Because when grpc-go sends the SETTINGS frame twice in a row, the server will return GOAWAY

**Comment by guyinyou** [comment]
![image](https://user-images.githubusercontent.com/36399867/186090154-9681dd34-9ddd-4d53-9f74-1bd43dad175e.png)

When the client sends SETTINGS several times in a row, the server sends GOAWAY to actively disconnect the link

**Comment by guyinyou** [comment]
![image](https://user-images.githubusercontent.com/36399867/186090591-3128dd51-5795-4da6-a0a3-e259409d7096.png)

After the client sends SETTINGS, the server initiates SETTINGS, and the connection is established normally

**Comment by guyinyou** [comment]
@dfawley @ejona86 
hi!
What other types of more information do you need. I will try to help you reproduce the problem. I've had this problem on two different computers, so it's unlikely to be related to the OS and environment variables.

**Comment by ejona86** [comment]
Two SETTINGS is normal. The first is telling the server the client's SETTINGS and the second one should have the ACK flag set, saying the client processed the server's settings (from that "SETTINGS, WINDOW_UPDATE" line). There should be another SETTINGS from the server to the client, with ACK flag. Since there is a GOAWAY instead, that means the server may be failing on the first SETTINGS; check it to make sure it doesn't have an ACK flag set. If it has the ACK flag set, then that explains the grpc-java error message and something is wrong with the Go client. This is assuming the client and server are talking directly to each other; it's assuming there's no proxy involved.

> I've had this problem on two different computers, so it's unlikely to be related to the OS and environment variables.

Let's put it this way: you're the only one having this problem, and we have cross-language automated testing. So there's either an issue in your setup, or you are using it in a less common way such that it is triggering a bug. I don't expect this is OS or env var related. But something about your application code might be triggering it.

**Comment by guyinyou** [comment]
> Two SETTINGS is normal. The first is telling the server the client's SETTINGS and the second one should have the ACK flag set, saying the client processed the server's settings (from that "SETTINGS, WINDOW_UPDATE" line). There should be another SETTINGS from the server to the client, with ACK flag. Since there is a GOAWAY instead, that means the server may be failing on the first SETTINGS; check it to make sure it doesn't have an ACK flag set. If it has the ACK flag set, then that explains the grpc-java error message and something is wrong with the Go client. This is assuming the client and server are talking directly to each other; it's assuming there's no proxy involved.
> 
> > I've had this problem on two different computers, so it's unlikely to be related to the OS and environment variables.
> 
> Let's put it this way: you're the only one having this problem, and we have cross-language automated testing. So there's either an issue in your setup, or you are using it in a less common way such that it is triggering a bug. I don't expect this is OS or env var related. But something about your application code might be triggering it.

I have tried many times to capture packets

The process of all normal connections is:
client->server
server->client
server->client
client->server

All GOAWAY processes are:
client->server
server->client
client->server

**Comment by guyinyou** [comment]
also the ack flag in the second SETTINGS is true
![image](https://user-images.githubusercontent.com/36399867/187819800-bdd35a10-ca18-4758-9c62-c543622cfc2c.png)

**Comment by guyinyou** [comment]
You can try to run my code, maybe you can reproduce the problem

https://github.com/guyinyou/untitle.git

**Comment by ejona86** [comment]
No luck reproducing.
```
$ ./untitle 
2022/09/01 09:07:09 status:{code:CLIENT_ID_REQUIRED message:"client id cannot be empty"}, err=<nil>
```

I tried to with Go 1.18 and 1.17.

Some additional info:
 * Is ACK: True on the first SETTINGS; the one from the client? It should be False
 * Is there debug data in the GOAWAY?

**Comment by guyinyou** [comment]
> No luck reproducing.
> 
> ```
> $ ./untitle 
> 2022/09/01 09:07:09 status:{code:CLIENT_ID_REQUIRED message:"client id cannot be empty"}, err=<nil>
> ```
> 
> I tried to with Go 1.18 and 1.17.
> 
> Some additional info:
> 
> * Is ACK: True on the first SETTINGS; the one from the client? It should be False
> * Is there debug data in the GOAWAY?

I am using go1.17
Try it a few times, there is a chance that there will be a problem

**Comment by guyinyou** [comment]
![image](https://user-images.githubusercontent.com/36399867/187968388-23cdbd40-dadc-4b6a-a851-b055071f1c3e.png)

I tried to use my personal computer Windows 10 system and also reproduced the problem

**Comment by ejona86** [comment]
I reproduced it by using the loop, but not much else.

The reproduction showed that the Go client's first SETTINGS did not have ACK. That leaves two possibilities: 1) there's something in the network reordering data 2) there's a race of some kind in the Netty server. (2) is much more likely, but I audited the code and I couldn't reproduce with a local server even after forcing certain timings in the packets received and doing PREFACE+SETTINGS+SETTINGS-ACK in same packet and SETTINGS+SETTINGS-ACK in the same packet. That means I'm out of ideas for (2). There's also not been any recent changes there, so this would be a very old bug.

Can you tell me more about the server setup? It is a grpc-java 1.45.0 server. Are you using grpc-netty or grpc-netty-shaded? Is the server directly accessible on the internet, or is there a proxy involved?

**Comment by guyinyou** [comment]
I haven't had this problem when I use grpc-java's client.
So is it possible that the problem is in grpc-go.

[git@github.com:guyinyou/untitled-java.git](https://github.com/guyinyou/untitled-java.git)

**Comment by dfawley** [comment]
Try removing the `conn.Connect()` line?  I don't _think_ it should have any effect, but it's unnecessary at least.

**Comment by ejona86** [comment]
> Can you tell me more about the server setup? It is a grpc-java 1.45.0 server. Are you using grpc-netty or grpc-netty-shaded? Is the server directly accessible on the internet, or is there a proxy involved?

I'm still waiting on this information. In the failing case the client received a TCP ACK for the first SETTINGS frame, yet the server didn't respond with a SETTINGS ACK. The network topology matters a lot.

> I haven't had this problem when I use grpc-java's client.

grpc-java client sends the initial Magic and SETTINGS in the same packet, where go sends them in separate packets. That could be related. It could also be that the Go client timing is "perfect" to trigger the race.

**Comment by guyinyou** [comment]
> Try removing the `conn.Connect()` line? I don't _think_ it should have any effect, but it's unnecessary at least.

The problem persists even after deleting
![image](https://user-images.githubusercontent.com/36399867/188298643-400770f1-5927-4b05-8bbb-ef90c0ced3a4.png)

**Comment by guyinyou** [comment]
> > Can you tell me more about the server setup? It is a grpc-java 1.45.0 server. Are you using grpc-netty or grpc-netty-shaded? Is the server directly accessible on the internet, or is there a proxy involved?
> 
> I'm still waiting on this information. In the failing case the client received a TCP ACK for the first SETTINGS frame, yet the server didn't respond with a SETTINGS ACK. The network topology matters a lot.
> 
> > I haven't had this problem when I use grpc-java's client.
> 
> grpc-java client sends the initial Magic and SETTINGS in the same packet, where go sends them in separate packets. That could be related. It could also be that the Go client timing is "perfect" to trigger the race.

Do you mean this problem is possible with grpc-netty or grpc-netty-shaded.
I need to ask my colleagues about this.

**Comment by drpmma** [comment]
> 

@ejona86 The server is using grpc-netty-shaded. The gRPC server is directly accessible and there is no other proxy.

**Comment by ejona86** [comment]
Are you able to get a tcpdump on the server-side? Ideally with both working and failing cases.

> The server is using grpc-netty-shaded

That means we are guaranteed the version of Netty being used.

> The gRPC server is directly accessible and there is no other proxy.

That means the ACKs I saw give me a good idea of when the packets are received.  I don't see anything on-the-wire different that predicts whether the handshake will succeed or fail. That means it needs to be a race on the server, but the processing is single-threaded and `read()`ing the packets together vs separately didn't seem to trigger it.

I really need to debug the server. I've not been able to reproduce it locally, and even against your server there's times when it reproduces more easily and others that are harder. The network latency is vastly different between my testing and your testing, which really begs the question "what is special about your server?" I still feel like the most likely answer is some hidden proxy/network component. Like a hardware/software firewall or some such.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
