### ISSUE TITLE
When tcnative is enabled, OkHttp tests timeout

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#950]
It fails like https://travis-ci.org/grpc/grpc-java/builds/78663746 . #949 reverted the change. It is unclear what the issue is.

**Comment by ejona86** [comment]
The problem is that tcnative would generally only support NPN (because not enough openssl is installed) whereas OkHttp is still using Jetty which only supports ALPN.

**Comment by nmittler** [comment]
@ejona86 can we close this, since the change was rolled back?

**Comment by ejona86** [comment]
I was leaving it open for us to develop a solution to test with tcnative. I'd consider #963 to be the fix for this.

**Comment by nmittler** [comment]
Ok sgtm ... thanks
