### ISSUE TITLE
process has been killed, grpc chnnel still alive!

### ISSUE THREAD

**Issue by jiangjiongyu** [grpc/grpc-java#9506]
### background:
* from pc client to phone service
* phone apk is launched by instrument

### phone config:
```
implementation 'io.grpc:grpc-okhttp:1.42.0'
implementation 'io.grpc:grpc-netty-shaded:1.42.0'
implementation 'io.grpc:grpc-protobuf:1.42.0'
implementation 'io.grpc:grpc-stub:1.42.0'
implementation 'org.apache.tomcat:tomcat-annotations-api:9.0.58'
implementation "com.google.protobuf:protobuf-java:3.19.3"
```

### scene:instrument process killed by shell "kill -9"
the timer from pc which invokes server Interface still avaliable.

### scene:instrument process killed by shell "am force-stop"
grpc channel is closed successfully.

what the difference between those?why process has been closed,grpc chnnel still alive?

**Comment by sanjaypujare** [comment]
Not clear if you are using `okhttp` based server on Android. Can you use the latest version [1.49.0](https://github.com/grpc/grpc-java/releases/tag/v1.49.0)?

**Comment by jiangjiongyu** [comment]
> Not clear if you are using `okhttp` based server on Android. Can you use the latest version [1.49.0](https://github.com/grpc/grpc-java/releases/tag/v1.49.0)?

I use netty-shaded based server on Android.I have tried to use okhttp based server,but it doesn't work.
ocasionally I find the reason why "kill -9" doesn't kill grpc chnnel.when I killed intrument process,app's process still exists,so the grpc channel isn't killed.
