### ISSUE TITLE
Cronet is not supported Retry

### ISSUE THREAD

**Issue by heqinglin8** [grpc/grpc-java#9507]
set retry config like this：
`CronetChannelBuilder.forAddress(host, port, engine).defaultServiceConfig(getRetryingServiceConfig()).enableRetry()`

but，it is not usefull！please call my tel：17773562773

**Comment by sanjaypujare** [comment]
Not clear what the issue is. What do you get when you try to do that? Can you add the stack trace?

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
