### ISSUE TITLE
Make findbugs as compileOnly dependency 

### ISSUE THREAD

**Issue by in-cloud-opensource** [grpc/grpc-java#9508]
### Describe the solution you'd like
Cleanup resulting runtime dependency tree for grpc, so that findbugs will not be published as compile dependency, resulting in a runtime dependency for consuming jars.

### Describe the solution you'd like
Make findbugs a `compileOnly` library:
protobuf
https://github.com/grpc/grpc-java/blob/c27f2d5a5713d9d4fb119e17fc0d4ed1349be0c2/protobuf/build.gradle#L14
protobuf-lite
https://github.com/grpc/grpc-java/blob/61f19d707a4c6fd4f5e327b8fceb09658b9cb452/protobuf-lite/build.gradle#L15
api
https://github.com/grpc/grpc-java/blob/61f19d707a4c6fd4f5e327b8fceb09658b9cb452/api/build.gradle#L15

### Describe alternatives you've considered
Modify the pom.xml in gradle before publishing compiled jars to maven repository works, but is tricky.

**Comment by sanjaypujare** [comment]
CC @ejona86

**Comment by ejona86** [comment]
The annotations have `@Retention(value=RUNTIME)`, so they should be available at runtime. Why does runtime seem inappropriate?

**Comment by in-cloud-opensource** [comment]
@ejona86 I am not an expert in findbugs., but what I understand it: the annotations are used for static code analysis by findbugs, but should not affect the execution of the code in an linking application. I would expect findbugs to run a different policy on the `@Retention(value=RUNTIME)` when scanning code.

**Comment by ejona86** [comment]
It isn't really a findbugs-specific discussion. The only findbug-specific part is "what retention are the annotations?" You can find the retention at https://javadoc.io/doc/com.google.code.findbugs/jsr305/latest/index.html

The main question is "should runtime annotations be runtime dependencies" and the answer to my knowledge is "yes." It is _possible_ to not have them at runtime, but if someone uses reflection on a class that has such annotations, then you can get annoying failures.

**Comment by in-cloud-opensource** [comment]
@ejona86 I see, thanks for pointing that out! Do you know how ProGuard will behave in such a case, does it remove findbugs from the resulting apk?

**Comment by ejona86** [comment]
I don't know how the various optimizers would function. If there were no users of the annotation (`clazz.getAnnotation(Nullable.class)`) it seems likely they may remove it. But overall I'd expect annotations to be pretty cheap, as they are small and lazily initialized, so I don't know how much they've invested in such optimizations.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
