### ISSUE TITLE
Support withCallCredentials / CallOptions with a Supplier

### ISSUE THREAD

**Issue by trietsch** [grpc/grpc-java#9509]
### Is your feature request related to a problem?
The current way an Authenticated Stub (i.e. a stub that has metadata with the Authorization header set) is built, is by specifying `withCallCredentials` (i.e. setting the credentials in the CallOptions). This does not work for short lived `Bearer` credentials, as they expire and the value in the metadata would be wrong. The current way I work around this, is by calling `withCallCredentials` with the value every single time before doing a call, as follows:

```stub.withCallCredentials(AuthorizationCallCredentials("<token>")).doGrpcCall(...)```

### Describe the solution you'd like
By letting `withCallCredentials` accept a `Supplier<CallCredentials>`, it would be possible to set the `CallCredentials` once when creating the Stub, without the need for setting the `CallCredentials` every time before each and every request.

### Describe alternatives you've considered
Alternative described in the problem description.

**Comment by sanjaypujare** [comment]
`CallCredentials` class has `applyRequestMetadata` which is called every time a credentials needs to be added to a request's metadata. You could refactor your `AuthorizationCallCredentials` so its `applyRequestMetadata` does the same thing as what you do in `AuthorizationCallCredentials("<token>")` ?  If `"<token>"` is going to be supplied for every call from the call site, how will the `Supplier` work?

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by trietsch** [comment]
Yes, that does work indeed! Thanks for thinking along @sanjaypujare
