### ISSUE TITLE
StreamObserver received  UNAVAILABLE: Connection closed after GOAWAY onError

### ISSUE THREAD

**Issue by wucheng1997** [grpc/grpc-java#9522]
### Steps to reproduce the bug

grpc work in xds with istio, istio have keepaliveMaxServerConnectionAge is 30m（default）
30m later send UNAVAILABLE: Connection closed after GOAWAY. HTTP/2 error code: NO_ERROR

StreamObserver will onError ，the observer can not use onNext later

```
io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed after GOAWAY. HTTP/2 error code: NO_ERROR
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)



```
    private class ResponseObserver implements StreamObserver<DiscoveryResponse> {
        private final long requestId;

        public ResponseObserver(long requestId) {
            this.requestId = requestId;
        }

        @Override
        public void onNext(DiscoveryResponse value) {
            logger.info("receive notification from xds server, type: " + getTypeUrl() + " requestId: " + requestId);
        }

        @Override
        public void onError(Throwable t) {
            logger.error("xDS Client received error message! detail:", t);
        }

        @Override
        public void onCompleted() {
            // ignore
        }
    }

```
      // channel reused
      StreamObserver<DiscoveryRequest> requestObserver = xdsChannel.createDeltaDiscoveryRequest(new ResponseObserver(request));
      requestObserverMap.put(request, requestObserver);

      ScheduledFuture<?> scheduledFuture = pollingExecutor.scheduleAtFixedRate(() -> {
          try {
              // observer reused
              StreamObserver<DiscoveryRequest> observer = requestObserverMap.get(request);

              // send request to control panel, 
              observer.onNext(buildDiscoveryRequest(names));  // Blocked here

          } catch (Throwable t) {
              logger.error("Error when requesting observe data. Type: " + getTypeUrl(), t);
          }
      }, pollingTimeout, pollingTimeout, TimeUnit.SECONDS);

**Comment by sanjaypujare** [comment]
The behavior seems to be correct - so your issue is about `NO_ERROR` as the error_code?

**Comment by wucheng1997** [comment]
> The behavior seems to be correct - so your issue is about `NO_ERROR` as the error_code?
so you think the error_code NO_ERROR make observer onError is correct. 
what can i do if the observer is blocked, create a new observer? i think maybe it is not a good idea.
Send UNAVAILABLE: Connection closed after GOAWAY. HTTP/2 error code: NO_ERROR is a mechanism in istio. 
my issue is how to deal this situation.

**Comment by ejona86** [comment]
Everything seems to be working like we'd expect. When you receive onError on the StreamObserver that RPC is dead. You can create a new RPC to replace it.

The NO_ERROR itself is not a concern. That is just saying the connection was closed routinely; no implementation did something wrong. From the [HTTP/2 spec](https://httpwg.org/specs/rfc9113.html#rfc.section.7):

> NO_ERROR (0x00):
The associated condition is not a result of an error. For example, a [GOAWAY](https://httpwg.org/specs/rfc9113.html#GOAWAY) might include this code to indicate graceful shutdown of a connection.

**Comment by wucheng1997** [comment]
> Everything seems to be working like we'd expect. When you receive onError on the StreamObserver that RPC is dead. You can create a new RPC to replace it.
> 
> The NO_ERROR itself is not a concern. That is just saying the connection was closed routinely; no implementation did something wrong. From the [HTTP/2 spec](https://httpwg.org/specs/rfc9113.html#rfc.section.7):
> 
> > NO_ERROR (0x00):
> > The associated condition is not a result of an error. For example, a [GOAWAY](https://httpwg.org/specs/rfc9113.html#GOAWAY) might include this code to indicate graceful shutdown of a connection.

thanks，I will create a new RPC to replace it.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
