### ISSUE TITLE
Calling a service in subdirectory

### ISSUE THREAD

**Issue by urprasad** [grpc/grpc-java#9619]
I am not able to call my service with subdirectory "https://example.com/subdirectory_path"
The call always resolves to example.com and ignores the subdirectory_path.
This is how I create the channel : OkHttpChannelBuilder.forTarget(uri.host+uri.path).build()

I found a resolution for this on dotnet [subdirectory_path](https://github.com/grpc/grpc-dotnet/issues/880)

But on android, since I don't have access to httpHandler of the channel, I am unable to use SubDirectoryHandler to inject the subdirectory into the URI.

Could someone please help me.

**Comment by ejona86** [comment]
Cross-linking to the StackOverflow answer: https://stackoverflow.com/a/74047805/4690866
