### ISSUE TITLE
SNI (Server Name Indication) is not present when using TLS to connect to back-end

### ISSUE THREAD

**Issue by mpeters-tha** [grpc/grpc-java#9627]
### What version of gRPC-Java are you using?
1.50.0

### What is your environment?
Client: Android 9.0 AOSP
Built with adopt open jdk 1.8.0.302
Back-end: Linux

### What did you expect to see?
SNI in TLS handshake (ClientHello)

### What did you see instead?
No SNI in TLS handshake (ClientHello)

### Steps to reproduce the bug
We are using OkHttpChannelBuilder method to connect to a server through a reverse proxy/WAF accepting only TLS (v1.2) connection that needs to check the SNI from client. The proxy server is refusing the connection because of SNI missing.
Adding overrideAuthority when building the OkHttpChannelBuilder does not help.

When performing a tcpdump, we can confirm (left side of screenshot) that SNI is not provided in the TLS handshake (ClientHello).

The same test with curl shows (right side of screenshot) that SNI is well present in ClientHello

Screenshot:
![noSNI_noIP](https://user-images.githubusercontent.com/6095599/196117871-868e35f3-daee-4894-8147-fc7e023c4bc0.png)

**Comment by mpeters-tha** [comment]
We found a way to workaround the issue.
The problem appears when using a host with format "myhost" but when using on on form "myhost.domain.com", it is working properly, and SNI is present in TLS handshake.
Feel free to close/fix/comment.

**Comment by ejona86** [comment]
SNI requires an absolute DNS domain name, so yes, you need to specify the full host name.
