### ISSUE TITLE
"SEVERE...Channel ManagedChannelImpl{...} was not shutdown properly..." warning even when shutdown properly

### ISSUE THREAD

**Issue by chrisditrani** [grpc/grpc-java#9628]
We have a java grpc client using grpc-java 1.48.1. We have the ability to add grpc server targets dynamically, which involves creating a trio of new ManagedChannels to be used against the new target server. We also have the ability to delete a grpc server target dynamically, which involves canceling any open streams, then calling channel.shutdownNow() then channel.awaitTermination(), which returns true, on the three channels.

A unit test designed to prove this dynamic server target (and therefore channels) creation/deletion works, has provoked repeated log messages like in the subject here, triggered when new channels are created. I have verified that shutdownNow() and awaitTermination() are being called and returning as expected for all channels.

The only thing we are doing that may be atypical is, we do have bi-directional streaming RPCs that are long-lived, and in order to allow these RPCs to be cancelled, we've implemented a cancellable wrapper for stream observers like so:

```
/*
     * Subclass to create a cancellable wrapper for a grpc stream observer
     */
    protected static class CancellableStreamObserver <T> {

        protected final CancellableContext context;
        protected final T qualifier;

        protected CancellableStreamObserver(T qualifier) {

            context = Context.current().withCancellation();
            this.qualifier = qualifier;
        }

        protected void Cancel() {
            context.cancel(null);
        }
    }
```

Creating the channels snippet:

```
                configChannel = ManagedChannelBuilder.forTarget(connection).usePlaintext()
                    .maxInboundMessageSize(1024*1024*100).build();
                dataChannel = ManagedChannelBuilder.forTarget(connection).usePlaintext().build();
                controlChannel = ManagedChannelBuilder.forTarget(connection).usePlaintext().build();
```

Shutting down the channels snippet (with debug logging added):

```
protected void ShutdownChannel(LecFep parent, String connection, ManagedChannel channel) {

            if (channel != null && !channel.isShutdown()) {

                channel.shutdownNow();

                parent.LogDebug(LogKind.LOG_FEP_CONN, 
                        "LecConnection.ChannelCloser Waiting for channel for %s to close", connection);

                long startTime = System.currentTimeMillis();
                try {
                    if (channel.awaitTermination(20, TimeUnit.SECONDS) != true) {
                        parent.LogDebug(LogKind.LOG_FEP, 
                                "LecConnection.ChannelCloser Timed out waiting for channel for %s to close", connection);
                    }
                } catch (InterruptedException e) {
                    parent.LogDebug(LogKind.LOG_FEP, 
                            "LecConnection.ChannelCloser InterruptedException awaiting channel shutdown for %s to close", 
                            connection);
                }

                boolean isTerm = channel.isTerminated();
                boolean isShut = channel.isShutdown();
                if (!isTerm || !isShut) {
                    parent.LogDebug(LogKind.LOG_FEP, 
                            "LecConnection.ChannelCloser for %s !!! Not shutdown (%s) or not terminated (%s)", 
                            isShut, isTerm);
                }

                parent.LogDebug(LogKind.LOG_FEP, 
                        "LecConnection.ChannelCloser Done waiting for channel for %s to close. Took %d ms", 
                        connection, System.currentTimeMillis() - startTime);
            }
        }
```

Looking at the grpc-java source in ManagedChannelOrphanWrapper.java, it's hard to see how this "SEVERE..." message is logged unless .shutdown() or .shutdownNow() was NOT called, and we clearly are, so there must be something we're not getting. Any insight appreciated.

**Comment by YifeiZhuang** [comment]
`ManagedChannelOrphanWrapper ` was best effort detecting previous channel not shutdown. Note that it does the check only on new channel creation on previous channels that lost reference but not shutdown. Is it possible that other test cases in your test suite you run did not shutdown or wait on termination? The log message should indicate which channel (logId and target) was not cleaned up.

**Comment by YifeiZhuang** [comment]
`ManagedChannelOrphanWrapper ` originally added in https://github.com/grpc/grpc-java/pull/3452

**Comment by YifeiZhuang** [comment]
Closing for now. If you still have questions, leave comment or reopen.
