### ISSUE TITLE
What happens if I ignore ContextCloser runnable?

### ISSUE THREAD

**Issue by smilu97** [grpc/grpc-java#9638]
Is there any bad effect if I ignore `io.grpc.internal.ServerImpl$ContextCloser`?

I'm using `java.util.concurrent.ThreadPoolExecutor` as a callExecutor which may reject some Runnables because our grpc requests are mostly not-critical, and nothing worries even if I drop some of them.

Recently, I realized ContextCloser is offered in the same queue with those unnecessary jobs, and being ignored. It looks very necessary to run ContextCloser but I'm not sure.

**Comment by temawi** [comment]
In general one should try to avoid rejections by the Executor you provide as that will result in memory leaking. There is a long term discussion on this topic here you can catch up on: https://github.com/grpc/grpc-java/issues/636

**Comment by smilu97** [comment]
Thanks for guide! :)
