### ISSUE TITLE
grpc-previous-rpc-attempts not added to initial response metadata

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#9641]
RetriableStream should add `grpc-previous-rpc-attempts` to the response headers (or trailers for trailers-only) when committing a stream and a retry was performed.

From [the gRFC](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#exposed-retry-metadata):
> the client will receive the number of retry attempts made when receiving the results of an RPC.

**Comment by sanjaypujare** [comment]
So this suggests gRPC adding `grpc-previous-rpc-attempts` locally on the client side before returning to the application. I thought it would be better for the server side to add to the response header (or trailer-only case trailer) so proxies or other intermediaries can also know that. Server side knows this from the request header, right?

**Comment by ejona86** [comment]
> I thought it would be better for the server side to add to the response header (or trailer-only case trailer) so proxies or other intermediaries can also know that.

They can know that from the request header. The same as the server.

This was a weird design, in that it adds trailers that didn't exist on the wire. But that is the way it is and the options are limited. I don't think the solution would be to have the server echo back the count; there's no benefit to that over the current design. A "cleaner" design would have needed to have a non-Metadata API to expose the count; and that's hard to do cross-language.

**Comment by sanjaypujare** [comment]
> This was a weird design, in that it adds trailers that didn't exist on the wire.

Was that the intent? From this statement:

"Likewise, the client will receive the number of retry attempts made when receiving the results of an RPC."

It is not clear. One could interpret this to mean client side receiving the info from the server side. Would it be wrong or bad to add this to the server side now? I suppose no other language has this so that cannot be an input.

**Comment by ejona86** [comment]
It was the intent. Everything in retries was client-side, except for the fact that C core eagerly sent headers for unary calls so needed to be reworked to more frequently send trailers_only.

We were talking about removing that part of the feature because we thought nobody had implemented it. But .Net has implemented it, and injects it on client-side: https://github.com/grpc/grpc-dotnet/blob/97b7f6d4d7d05b58f39471300732651c0281a083/src/Grpc.Net.Client/Internal/GrpcCall.cs#L313 .
