### ISSUE TITLE
Remove redundant availability judgment

### ISSUE THREAD

**Issue by RapperCL** [grpc/grpc-java#9644]
1 The availability filtering has been done when loading through ServiceProviders; no secondary filtering is required externally.
io.grpc.ServiceProviders.loadAll()
![image](https://user-images.githubusercontent.com/44110731/197125194-20c780ec-36e2-4e8a-821b-4c8e66f3fb2c.png)
io.grpc.ServerRegistry.getDefaultRegistry
![image](https://user-images.githubusercontent.com/44110731/197125822-b63199f5-300e-4b2d-ad76-388199239dff.png)

**Comment by ejona86** [comment]
Fixed by #9647
