### ISSUE TITLE
ManagedChannelImpl.SubchannelImpl args check bug

### ISSUE THREAD

**Issue by RapperCL** [grpc/grpc-java#9652]
path:io.grpc.internal.ManagedChannelImpl.SubchannelImpl

The verification of args should be advanced, otherwise when it is empty, args.getAddresses() will throw an null exception in advance;

![](https://user-images.githubusercontent.com/44110731/197348963-4b096e71-b3d2-4db3-9472-fb0222ef7f1b.png)

**Comment by ejona86** [comment]
Fixed by #9651
