### ISSUE TITLE
Who knows why these two items are not checked

### ISSUE THREAD

**Issue by RapperCL** [grpc/grpc-java#9653]
![image](https://user-images.githubusercontent.com/44110731/197454624-05f74c7d-9f9a-4564-ad74-ca4d3d12162a.png)

**Comment by temawi** [comment]
As it says, the haven't completed yet. Compared to the other checks, these take a lot longer.

**Comment by ejona86** [comment]
Actually, they hadn't started yet because you aren't a maintainer. A maintainer needed to review your PR and add the `kokoro:run` label to trigger them to run.
