### ISSUE TITLE
Are the static class method descriptor-returning methods part of the codegen contract?

### ISSUE THREAD

**Issue by hq6** [grpc/grpc-java#9656]
According to the generated code [reference](https://grpc.io/docs/languages/java/generated-code/), the gRPC plugin will generate a class named `io.grpc.examples.ServiceNameGrpc` for each `service` defined in a proto file.

I have empirically observed that these classes contain static methods named `getXMethod` which return method descriptors corresponding to the method `X` of the service.

Can I rely on these methods to be codegened with the correct name for future versions of `protoc` and the grpc plugin?

**Comment by ejona86** [comment]
Yes, you can depend on those functions and their names. Although we don't document how we generate the name, and there was another issue that was asking for such a function; I'll need to look it up later. https://grpc.io/docs/languages/java/generated-code/ should maybe be updated to mention the methods, although most users wouldn't need to use them. They are pretty useful if you want to make your own stub.

Note that we have annotations on those methods as well. The expectation is any annotation processors would use the annotations (and then not really care what the getXMethod is called) and any runtime code would call the method and use the returned MethodDescriptor.

**Comment by ejona86** [comment]
I think the other issue I was thinking of was #8826, but it is a different situation.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

I'll note that there is no need to access these methods via Java reflection. Java reflection users would use `FooGrpc.getServiceDescriptor()` instead which avoids the need to programatically calculate the method name.
