### ISSUE TITLE
Android lint InvalidPackage: javax.naming reappeared  

### ISSUE THREAD

**Issue by Filmaluco** [grpc/grpc-java#9661]
**What version of gRPC are you using?**
1.50.2 (seems to be happening since at least 1.47.0)

**Sample Project**
https://github.com/relaycorp/relaynet-gateway-android 
**that uses** 
https://github.com/relaycorp/awala-cogrpc-jvm 

currently, if you try to run 
`./gradlew lint `
**it will be suppressed...** 

but if you **remove the suppression from the android project lint.xml** you get:

```
./../../../../.gradle/caches/modules-2/files-2.1/io.grpc/grpc-core/1.47.0/3ac5502eaf5fde551b4cde8046cc933587df436/grpc-core-1.47.0.jar: Invalid package reference in io.grpc:grpc-core; not included in Android: javax.naming.directory. Referenced from io.grpc.internal.JndiResourceResolverFactory.JndiRecordFetcher.
../../../../../.gradle/caches/modules-2/files-2.1/io.grpc/grpc-core/1.47.0/3ac5502eaf5fde551b4cde8046cc933587df436/grpc-core-1.47.0.jar: Invalid package reference in io.grpc:grpc-core; not included in Android: javax.naming. Referenced from io.grpc.internal.JndiResourceResolverFactory.JndiRecordFetcher.
```

I know this issue was something already addressed with https://github.com/grpc/grpc-java/issues/5422 
somehow the **@SupressLint("all")** is no longer working with the latest versions...

I know that this case is a bit different from the one I linked, but is there a way I could get some help? and ask why the fix was using the annotation @SupressLint and not @Supress..?

**Comment by temawi** [comment]
@Filmaluco I investigated this today and I was able to reproduce what you reported with your project. But from what I can tell, the `JndiRecordFetcher` class is annotated correctly and should get ignored by the Android lint tool. I'm not sure how to help further. This could be an issue with how your project is set up or maybe the lint tool itself. If I think of other avenues to troubleshoot, I will give it a shot.

I believe the [@Supress](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-suppress/) annotation you mention is for Kotlin code, but [@SupressLint](https://developer.android.com/reference/android/annotation/SuppressLint) is what should be used with Java.
