### ISSUE TITLE
Support custom path prefix in gRPC service URL

### ISSUE THREAD

**Issue by yuliya-salesforce** [grpc/grpc-java#9671]
### Is your feature request related to a problem? Yes

The ask here is related to the following issue: https://github.com/grpc/grpc/issues/14900
We have following usecase:

We have multiple instances of the same gRPC server app running on multiple k8s deployments. Our routing  model from gRPC client to gRPC servers is not direct but rather using Ingress with rerouting based on **path** 

myserver/**path1**/myApi/**call1** goes to instance1
myserver/**path2**/myApi/**call1** goes to instance2
...
myserver/**pathN**/myApi/**call1** goes to instanceN

Now that nginx supports gRPC routing, this seems trivial to set up from the routing side. Alas, it does not seem to work. 
Since gRPC target and subsequently authority take only **_host:port_** into consideration

Number of destination servers is not finite as those come and go, so it's not possible to have static Ingress spec

Possibly this is a gRPC client limitation? 

### Describe the solution you'd like

What we'd like to have is a way to specify `path` part in the target or any other header that will allow to produce HTTP2 URI that can be rerouted **_finalDestinationServer/myApi/call1_**

### Describe alternatives you've considered
use REST instead of gRPC

**Comment by ejona86** [comment]
The gRPC service/method is the path. If that is changed, it is a different method. And protobuf methods don't support additional slashes in the path.

You can do authority-based routing and header-based routing. You can also have a custom grpc server parse the message and do routing. It sounds like header-based routing is probably easiest for your situation.

**Comment by yuliya-salesforce** [comment]
> You can do authority-based routing and header-based routing
I would love to see examples of those, as so far I was not able to set authority to what I want to set it, as grpc client code does not allow it with all the validations of authority to be actually `host:port` and not anything else
I have tried a lot of combinations so far

**Comment by ejona86** [comment]
`host:port` is authority. Authority-based routing is commonly known as "virtual hosting." For header-based routing your client would add a piece of Metadata to the request, and then you'd configure the proxy to change the destination based on that header.

Are you using Java on both client and server?

**Comment by yuliya-salesforce** [comment]
> Are you using Java on both client and server

We are using Java for client and most likely Python for server

> For header-based routing your client would add a piece of Metadata to the request, and then you'd configure the proxy to change the destination based on that header.

I see. So eventually it's k8s setup of a proxy that would need to be header based
If you have any Java example of the client and respective k8s setup - it would be great! (if you have it handy)

**Comment by ejona86** [comment]
```java
Metadata.Key destinationServer = Metadata.Key.of("destination-server", Metadata.ASCII_STRING_MARSHALLER)

Metadata metadata = new Metadata();
metadata.put(destinationServer, "path2");
stub.withInterceptors(MetadataUtils.newAttachHeadersInterceptor(metadata)).someMethod();
```

I don't have any snippet for k8s.

**Comment by ejona86** [comment]
Seems like this is resolved as best as we'd expect. If not, comment, and it can be reopened.
