### ISSUE TITLE
How to create grpc server code with cronet?

### ISSUE THREAD

**Issue by todd-liu** [grpc/grpc-java#9676]
I want to create a grpc server code with cronet,  and use android as client with cronet to call rpc interface, but i cannot find any server code in grpc-java branch, just only have som code for client  as below, could you help? thanks

`import io.grpc.cronet.CronetChannelBuilder;
import org.chromium.net.ExperimentalCronetEngine;

...

ExperimentalCronetEngine engine =
    new ExperimentalCronetEngine.Builder(context /* Android Context */).build();
ManagedChannel channel = CronetChannelBuilder.forAddress("localhost", 8080, engine).build();`

**Comment by ejona86** [comment]
Cronet is client-only. Historically we have not supported any HTTP/2 server on Android. But since 1.49 we added OkHttpServerBuilder, so I'd recommend that if you need a server on Android.

I'll also note for Android we have the Binder transport, but that's for device-local RPCs.

**Comment by todd-liu** [comment]
@ejona86 , thanks you comments, i know it isn't possible to build cronet server on android.  My purpose is that using grpc client with cronet connect one grpc cronet server, i builded a go quic grpc server, but  cann't connect with our android client with cronet, in cronet source code, only given some code to build cronet client code, not give server quic code, so i want to know:  with GRPC, is there method to build cronet server, using java, go and other language?

**Comment by ejona86** [comment]
grpc-cronet clients can connect to any gRPC server over TLS, which would use HTTP/2. Are you saying you want an HTTP/3 server?

**Comment by todd-liu** [comment]
no HTTP/3, because CronetChannelBuilder  support quic， i want to cronetChannelBuilder  client connect any gRPC over TLS throught quic protocol, but failed since TLS certificate connecting go quic server. i don't find solution...

**Comment by ejona86** [comment]
QUIC became HTTP/3, so I believe Cronet supports HTTP/3 these days. It may not even support the older QUIC versions now. QUIC doesn't use TLS.

> since TLS certificate connecting go quic server

I don't know what this is talking about.

It sounds like you want to find a HTTP/3 (or QUIC) supporting proxy. I don't have any particular recommendations for that, although it appears Envoy may support it.

**Comment by sanjaypujare** [comment]
> > 
> 
> Is there any sample code can build server on Android eg: OkHttpServerBuilder
> 
> I want to test android RPC betwwen two android device

This one https://github.com/grpc/grpc-java/blob/master/interop-testing/src/test/java/io/grpc/testing/integration/Http2Test.java#L102

**Comment by ejona86** [comment]
Use it like a normal server builder. So something like this:
https://github.com/grpc/grpc-java/blob/096898a46e8f15ce5eca07ee5231fcc458487202/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java#L37-L40

But replace `ServerBuilder` with `OkHttpServerBuilder`.

(At some point we'll hook up OkHttpServerBuilder into the ServerBuilder.forPort() API, so you could just use the ServerBuilder API. But we haven't done that as of yet.)

**Comment by todd-liu** [comment]
> QUIC became HTTP/3, so I believe Cronet supports HTTP/3 these days. It may not even support the older QUIC versions now. QUIC doesn't use TLS.
> 
> > since TLS certificate connecting go quic server
> 
> I don't know what this is talking about.
> 
> It sounds like you want to find a HTTP/3 (or QUIC) supporting proxy. I don't have any particular recommendations for that, although it appears Envoy may support it.

i create Go quic server, using certificate for TLS, example:
`		cert, err := tls.LoadX509KeyPair(certFile, keyFile)
		if err != nil {
			log.Printf("failed to tls.LoadX509KeyPair. %s", err.Error())
			return nil, err
		}
		return &tls.Config{
			Certificates: []tls.Certificate{cert},
			NextProtos:   []string{"http/2+quic/43"},
		}, nil
	}`
certFile: server crt, keyFile: server private key

client using android cronet as below:
`            ExperimentalCronetEngine engine =
                    new ExperimentalCronetEngine.Builder(getApplicationContext() /* Android Context */)
                            .setStoragePath(getApplicationContext().getFilesDir().getAbsolutePath())
                            .enableHttpCache(CronetEngine.Builder.HTTP_CACHE_DISK_NO_HTTP, 100 * 1024)
                            .addPublicKeyPins(hostname, pinsSha256, false, cal.getTime())
                            .enablePublicKeyPinningBypassForLocalTrustAnchors(true)
                            .enableQuic(true)
                            .enableHttp2(false)
                            .addQuicHint(hostname, 50051, 50051)
                            .setExperimentalOptions("{\"HostResolverRules\": {\"host_resolver_rules\": \"MAP * aaa.test.google.com.au\"}}")
                            //.setExperimentalOptions(experimentalOptions.toString())
                            .build();`
addPublicKeyPins get same root ca.

but client cannot connect go server, i don't know reason.

**Comment by ejona86** [comment]
> i create Go quic server, using certificate for TLS

What about that is quic? You need more than NextProtos. Are you using https://github.com/lucas-clemente/quic-go ?

**Comment by todd-liu** [comment]
> > i create Go quic server, using certificate for TLS
> 
> What about that is quic? You need more than NextProtos. Are you using https://github.com/lucas-clemente/quic-go ?

Thanks your comment,  our code is very simply, just some likely with guic-go CODE,  our go server and go client set NextProtos same value, ex, "quic-echo-example" or other self-design value, it can connect,  it's failed when use android client,  how to set NextProtos value? i don't know what's meaning ?

**Comment by ejona86** [comment]
>			NextProtos:   []string{"http/2+quic/43"},

What did this string come from? I'm not familiar enough with QUIC, but this doesn't seem all that likely to work. Especially because, does Chrome still support quic/43? I'd expect Chrome to have swapped to h3.
