### ISSUE TITLE
Why using LogLevel.DEBUG for Http2FrameLogger

### ISSUE THREAD

**Issue by morningman** [grpc/grpc-java#9680]
Hi there,

I read the code and see:

https://github.com/grpc/grpc-java/blob/a82ea0cb09caef7ad56cc5e0b07473ae420bbeab/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L176-L203

At L201, the log level is DEBUG for Http2FrameLogger?
Is there any reason to use DEBUG level? Or is there way that I can change this log level?

Thank you!

**Comment by ejona86** [comment]
You can change the log levels logged, but not the log levels of statements. For example:
```
# Provide this file as value to java.util.logging.config.file system property
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = ALL

io.grpc.netty.NettyClientHandler.level = FINE
io.grpc.netty.NettyServerHandler.level = FINE
io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.level = FINE
io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.level = FINE
```

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
