### ISSUE TITLE
How to turn off DEBUG log of Http2FrameLogger

### ISSUE THREAD

**Issue by ByteYue** [grpc/grpc-java#9685]
Hi guys! 
Recently we were trapped in one confusing occasion where Http2FrameLogger would continue to log debug information despite the INFO level configuration of `io.grpc.netty.shaded.io.netty`. 
At first we searched this problem using Google and saw this [comment](https://github.com/grpc/grpc-java/issues/3033#issuecomment-309567676) and this [one](https://github.com/grpc/grpc-java/issues/3033#issuecomment-309395136), so we then determined the binding logging backends right before the main function of the whole program just as the picture below.
![image](https://user-images.githubusercontent.com/43750022/201044795-0a1c3a0a-a09b-41ba-bf93-68a5d96ccbc2.png)

Unfortunately, the debug log exists still. The configure we take seem to take no effect on Http2FrameLogger.
![jbS574ce45](https://user-images.githubusercontent.com/43750022/201045103-096be8f4-4df0-4e8c-9ba8-c336de1f197e.jpg)

I wonder how could I turn off this debug log.

BTW, the version of grpc-java and netty we use are `grpc-java v1.30.0` and `netty-4.1.48.final`

**Comment by ByteYue** [comment]
Also, I saw this [comment](https://github.com/grpc/grpc-java/issues/9680#issuecomment-1307973994). I created one logging.properties file and added the configuration mentioned. Then passing this file as parameter to java when starting the program.
![2d4fa451-8a82-4124-b73f-12741d123fdc](https://user-images.githubusercontent.com/43750022/201050354-76911bea-66d9-4c02-a9a0-026b057fc57d.jpeg)

The debug log still occurs😂. It's so confusing.

**Comment by sanjaypujare** [comment]
In your `logging.properties` file you have the level set to `FINE` and also on NettyClient/ServerHandler instead of at io.netty level (or `io.grpc.nety.shaded.io.netty` level). Could that be the problem?

**Comment by ByteYue** [comment]
> In your `logging.properties` file you have the level set to `FINE` and also on NettyClient/ServerHandler instead of at io.netty level (or `io.grpc.nety.shaded.io.netty` level). Could that be the problem?

Thank you for your advice. I tried to use `io.grpc.nety.shaded.io.netty` level in `logging.properties` file.
![image](https://user-images.githubusercontent.com/43750022/201339926-cd827f26-e6a0-410c-a86c-95fa8023b9fb.png)

But it seems that it didn't work for Http2InboundFrameLogger.
![image](https://user-images.githubusercontent.com/43750022/201339841-b7d7d432-6091-47e4-89a5-0d812ed25077.png)

Also i attempted to add `Http2InboundFrameLogger.level` in `logging.properties` file, no matter INFO/FINE it didn't work neither.
![image](https://user-images.githubusercontent.com/43750022/201340484-f4b11aec-01e1-4870-a191-ab5df063909f.png)

**Comment by sanjaypujare** [comment]
Looking at netty's [`InternalLoggerFactory.newDefaultFactory(`](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java#L41) it attempts to first create one of Slf4j, or Log4j2 or Log4j factory before falling back to Jdk (java.util.logging) logger, if you are using one of those libraries. With one of those, you will need to use the corresponding configuration.

**Comment by ejona86** [comment]
Seems like there's nothing more for us to do here. If not, comment, and it can be reopened.
