### ISSUE TITLE
GRPC and zulu 11.10.17 - too many open files error; runs ok with zulu 11.10.15

### ISSUE THREAD

**Issue by lmcdasi** [grpc/grpc-java#9693]
I'm having an app running ubuntu jammy latest (22.04.1lts) and if I use ZULU 11.10.15 
I'm having no issues.

But when I update to ZULU 11.10.17 on same ubuntu jammy I'm getting:
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Exception calling application: [Errno 24] Too many open files
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)

Are you aware about any incompatibility between grpc & ZULU 11.10.17 ?!?

The grpc deps are:
$ ./mvnw dependency:tree | grep grpc
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.31.1:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.17.0:compile
[INFO] |  |  +- io.grpc:grpc-protobuf-lite:jar:1.31.1:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.31.1:compile
[INFO] |  +- net.devh:grpc-spring-boot-starter:jar:2.13.0.RELEASE:compile
[INFO] |  |  \- net.devh:grpc-server-spring-boot-starter:jar:2.13.0.RELEASE:compile
[INFO] |  |     \- net.devh:grpc-server-spring-boot-autoconfigure:jar:2.13.0.RELEASE:compile
[INFO] |  |        \- io.grpc:grpc-services:jar:1.42.1:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.46.0:compile
[INFO] |  |  +- io.grpc:grpc-api:jar:1.46.0:compile (version selected from constraint [1.46.0,1.46.0])
[INFO] |  |  |  \- io.grpc:grpc-context:jar:1.46.0:compile
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.46.0:compile
[INFO] |  +- net.devh:grpc-client-spring-boot-starter:jar:2.13.0.RELEASE:compile
[INFO] |  |  \- net.devh:grpc-client-spring-boot-autoconfigure:jar:2.13.0.RELEASE:compile
[INFO] |  |     \- net.devh:grpc-common-spring-boot:jar:2.13.0.RELEASE:compile
[INFO] +- io.opentracing.contrib:opentracing-grpc:jar:0.2.3:compile

**Comment by sanjaypujare** [comment]
No, we are not aware of any. CC @ejona86 for visibility.

May be you need to increase the open files limit? Use `ulimit` to check

**Comment by lmcdasi** [comment]
Thx. I run a tcpdump and I do see the 'Too many' msg in the grpc rsp from the client. I miss-understood the issue.

![image](https://user-images.githubusercontent.com/947517/202295405-7f3f1eb5-ae1b-4dca-b951-e7bcc2a0c7bf.png)

**Comment by ejona86** [comment]
That message was sent by the server. gRPC isn't really involved other than it delivered the bad news.
