### ISSUE TITLE
build: version conflict between gradle and maven

### ISSUE THREAD

**Issue by YifeiZhuang** [grpc/grpc-java#9714]
```
* Where:
Build file '/home/zivy/grpc-java/build.gradle' line: 524

* What went wrong:
Execution failed for task ':grpc-gcp-observability:checkUpperBoundDeps'.
> Maven version skew: io.opentelemetry:opentelemetry-api ( != 1.15.0) Bad version dependency path: [project ':grpc-gcp-observability'] Run './gradlew :grpc-gcp-observability:dependencies --configuration runtimeClasspath' to diagnose

```

Error:
> `> Maven version skew: io.opentelemetry:opentelemetry-api ( != 1.15.0) Bad version dependency path: [project ':grpc-gcp-observability'] Run './gradlew :grpc-gcp-observability:dependencies --configuration runtimeClasspath' to diagnose`

Reproduction:
add opentelemetry-api to gcp-observability package.

**Comment by ejona86** [comment]
Just for discussion:
https://github.com/grpc/grpc-java/commit/5642e0124391602affb2422d84d3e6958fa7c2b9

**Comment by YifeiZhuang** [comment]
#8238 was doing requireUpperBoundDeps check that maven plugin is doing. Purpose of the check is to prevent maven user from having version conflicts in their build. (We hope the dependency version of grpc artifact matches the maven build result).
To prevent the exception from throwing, solution is to reorder dependency, or add our dependency explicitly:
```
('io.opentelemetry:opentelemetry-api:1.20.1'), // Prefer our version
```
