### ISSUE TITLE
how to get io.grpc.netty.shaded.io.netty.channel.Channel from grpc

### ISSUE THREAD

**Issue by xingdong015** [grpc/grpc-java#9715]
in grpc 1.30.2 , I can get io.grpc.netty.shaded.io.netty.channel.Channel  as follow
```
ServerInterceptor serverInterceptor = new ServerInterceptor() {
            @Override
            public <T, S> ServerCall.Listener<T> interceptCall(ServerCall<T, S> call, Metadata headers,
                    ServerCallHandler<T, S> next) {
                  ServerStream serverStream = (ServerStream) ReflectUtils.getFieldValue(serverCall, "stream");
                  Channel internalChannel = (Channel)ReflectUtils.getFieldValue(serverStream, "channel");;
                  return Contexts.interceptCall(ctx, call, headers, next);
            }
        };
```
but when I upgrade 1.50.2 , 'channel' attribute is missed, where i get it. because i use 'channel.close() ','channel.isActive()'

**Comment by ejona86** [comment]
That seems pretty obviously not supported. Yes, private fields can move around from version to version.

Why are you digging in to get the Channel? Why do you need it?

**Comment by xingdong015** [comment]
> That seems pretty obviously not supported. Yes, private fields can move around from version to version.
> 
> Why are you digging in to get the Channel? Why do you need it?

The server has a connection pool. The connection pool maintains many grpc client connections. This connection pool periodically detects unavailable client connections. If an unavailable connection is detected, it is desirable to close the connection. And now the only way to do it is to close the bidirectional stream. As follows. I can't close the underlying netty channel.
```

public void close() {
    closeBiStream();
    channel.close();
}
private void closeBiStream() {
      if (streamObserver instanceof ServerCallStreamObserver) {
          ServerCallStreamObserver serverCallStreamObserver = ((ServerCallStreamObserver) streamObserver);
          if (!serverCallStreamObserver.isCancelled()) {
              serverCallStreamObserver.onCompleted();
          }
      }
}

```

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
