### ISSUE TITLE
io.grpc.CallOptions.Key doesn't have overridden 'equals()' method

### ISSUE THREAD

**Issue by LAmcpp** [grpc/grpc-java#9720]
### What version of gRPC-Java are you using?
I use 1.42.2 version, but I see the same problem in latest (1.51.0) version

### What is your environment?

Linux, Oracle OpenJDK 17.0.2

### What did you expect to see?
Expect to get options from stub.withOption()

Need to add overridden 'equals()' method in io.grpc.CallOptions.Key class
or need to refactor method io.grpc.CallOptions#getOption and equal keys as T values

### What did you see instead?
io.grpc.CallOptions#getOption return null when 'customOptions' contains key with the same value

cause: io.grpc.CallOptions.Key class doesn't have overridden 'equals()' method
but io.grpc.CallOptions#getOption has code:
`key.equals(customOptions[i][0])`

### Steps to reproduce the bug
1) Create stub.withOption():
`stub.withOption(CallOptions.Key.create("some_key"), "some_value");`
2) Intercept stub call (ClientInterceptor)
3) Try get your option from callOptions: 
`
callOptions.getOption(CallOptions.Key.create("some_key"));
`

**Comment by ejona86** [comment]
As shown in [the javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/CallOptions.Key.html) the string provided is a debug string. As also mentioned, "Uses reference equality."

Reference equality was on purpose so you can control the visibility of the key. You can make it public from the interceptor, and then something like:

```java
stub.withOption(CustomInterceptor.OPTION, "some_value");
```
