### ISSUE TITLE
Is there a connection pool for the grpc service connection? What is the maximum number of connections? Whether to modify

### ISSUE THREAD

**Issue by hakusai22** [grpc/grpc-java#9733]
Is there a connection pool for the grpc service connection? What is the maximum number of connections? Whether to modify

**Comment by sergiitk** [comment]
Could you please clarify the question? Not clear if this is about client connection pool to the server, or server-managed pool of client connections? An example of what you're trying to accomplish would be helpful.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
