### ISSUE TITLE
Provide grpc-xds artifact w/o the need of grpc-netty-shaded

### ISSUE THREAD

**Issue by alesj** [grpc/grpc-java#9736]
### Is your feature request related to a problem?

Yes.
The problem is when we try to generate a (GraalVM) native image with `grpc-xds` as a dependency
* https://gist.githubusercontent.com/alesj/a883aaf61689017ecdb27db10f035a1e/raw/0b1497f184cf5159aecddb88431343e00bda4ece/gistfile1.txt

This is what I get when I exclude `grpc-netty-shaded` dependency ...
* https://gist.githubusercontent.com/alesj/ea725449ca80c0406be372d9194a81aa/raw/a1f52580f6f8b289da9359c0ff11f50b9b2b87db/gistfile1.txt

### Describe the solution you'd like

To have a `grpc-xds` jar, which doesn't depend on `grpc-netty-shaded`.

### Describe alternatives you've considered

Currently none.
Dunno if I can 'trick' GraalVM to handle this ...

### Additional context

This is where we depend on `grpc-xds`
* https://github.com/alesj/quarkus/tree/xds1/extensions/grpc/runtime

And current PR
* https://github.com/quarkusio/quarkus/pull/29251

**Comment by alesj** [comment]
Yeah, the 1st error is weird -- as the Log4JLogger class is next to the 'factory' that wants to create it ... so no idea why that breaks.

There is more context here:
* https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/native.20image.20issues.20.2B.20grpc-netty-shaded

I did manage to get around this by extracting xDS stuff into a new module / jar, so our plain gRPC extension works as before; native and all ...

**Comment by ejona86** [comment]
We'd love contributions to make this easier, but we don't have the experience to figure out what is getting confused. So if someone figures out a way to make the GraalVM experience more seemless, please open an issue/PR.
