### ISSUE TITLE
Can i use ThreadLocal save var in ServerInterceptor and then use in service

### ISSUE THREAD

**Issue by jiankebe** [grpc/grpc-java#9737]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/7916816/206185000-f5380692-bba7-4fcd-a5f8-d0ac440fd662.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/7916816/206185074-bcf07a71-0504-41f1-af5b-845e40186157.png">

I found get var will be null when high concurrency

**Comment by jiankebe** [comment]
if can not！
How do interceptors interact with service parameters in a request？

**Comment by sanjaypujare** [comment]
Use [Context](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html) to exchange info between interceptor and service e.g. https://kuros.in/grpc/2019/08/handling-grpc-authorization-using-context/

**Comment by Jalr4ever** [comment]
> Use [Context](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html) to exchange info between interceptor and service e.g. https://kuros.in/grpc/2019/08/handling-grpc-authorization-using-context/

Hi sir, for ThreadLocal#set() in JDK, we remove value by ThreadLocal#revmove(), what for [Context](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html)? I can't find any removal method in [Context](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html) , or does it needn't remove val when using Context such as `Context.current()withValue(WHATEVER_CONTEXT, WHATEVER_CONTEXT_THINGS);` ?

**Comment by sanjaypujare** [comment]
what's your use case to remove values?

**Comment by Jalr4ever** [comment]
> 

In case memory leak, or like I said before, did it need'nt remove values actullay?  Would gRPC remove Context values automatically when it done per gRPC request by Stub?

**Comment by sanjaypujare** [comment]
> In case memory leak, or like I said before, did it need'nt remove values actullay? 

Sorry, didn't follow that. Could you restate/rephrase your question?

> Would gRPC remove Context values automatically when it done per gRPC request by Stub?

A content object will be GC'ed when not needed.

**Comment by Jalr4ever** [comment]
> > In case memory leak, or like I said before, did it need'nt remove values actullay?
> 
> Sorry, didn't follow that. Could you restate/rephrase your question?
> 
> > Would gRPC remove Context values automatically when it done per gRPC request by Stub?
> 
> A content object will be GC'ed when not needed.

Ok sir, maybe code would be better to explain. In the example (https://kuros.in/grpc/2019/08/handling-grpc-authorization-using-context/) you mentioned before, we can see the code below:

```java
public class AuthorizationInterceptor implements ServerInterceptor {

    public static final Context.Key<Object> USER_DETAILS = Context.key("user_details");

    private UserService userService;

    public AuthorizationInterceptor() {
        this.userService = new UserServiceImpl();
    }

    public <ReqT, RespT> Listener<ReqT> interceptCall(final ServerCall<ReqT, RespT> serverCall, final Metadata metadata, final ServerCallHandler<ReqT, RespT> serverCallHandler) {

        final String auth_token = metadata.get(Key.of("auth_token", Metadata.ASCII_STRING_MARSHALLER));

        final UserInfo userInfo = userService.validate(auth_token);

        Context context = Context.current()
                .withValue(USER_DETAILS, userInfo);

        return Contexts.interceptCall(context, serverCall, metadata, serverCallHandler);

    }
}
```
We can see that it set value by ` Context context = Context.current().withValue(USER_DETAILS, userInfo);`, for this `context` object, if we don't do any removal things to the `context` object, will it cause memory leak? Or it just simply will be GC when the request done?

**Comment by ejona86** [comment]
Context would be GC'ed when the request is done. The `Contexts.interceptCall()` keeps a reference to the `context`, but that is per-RPC, so it will all be GC'ed at end of RPC.

Context is also set in a thread-local, but it is only set within a normal Java scope; it is cleaned up as methods return up higher the stack. So when processing for the RPC is complete there's no more threads running that would have it set in a thread-local.

**Comment by Jalr4ever** [comment]
> Context would be GC'ed when the request is done. The `Contexts.interceptCall()` keeps a reference to the `context`, but that is per-RPC, so it will all be GC'ed at end of RPC.
> 
> Context is also set in a thread-local, but it is only set within a normal Java scope; it is cleaned up as methods return up higher the stack. So when processing for the RPC is complete there's no more threads running that would have it set in a thread-local.

😃 Thank you, sir, I got it now, really appreciate your examination!

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
