### ISSUE TITLE
Mock gRPC server for Integration Test

### ISSUE THREAD

**Issue by FedorSabeshkin** [grpc/grpc-java#9741]
Can I run a mock gRPC server as described in this [instruction](https://github.com/grpc/grpc-java/blob/v1.51.0/examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java) so that it runs on a specific port that the client I run in the integration test will access?

Something like this:

```java  
//1. Create a server, add service, start, and register for automatic graceful shutdown.
grpcCleanup.register(InProcessServerBuilder
        .forPort(8080).directExecutor().addService(serviceImpl).build().start());
//2. Run real gRPC client in another JVM, which call my mock server
//3. Verify my mock server
verify(serviceImpl)
       .sayHello(requestCaptor.capture(), ArgumentMatchers.<StreamObserver<HelloReply>>any());
```

**Comment by ejona86** [comment]
Yes. Just use `Grpc.newServerBuilderForPort()` or `ServerBuilder.forPort()` like you would with a [real server](https://github.com/grpc/grpc-java/blob/v1.51.0/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java).

InProcess is convenient for unit tests, but the mocking pattern works for other server types as well.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by FedorSabeshkin** [comment]
When i try verify(), like i described in first post, i get message:
>Wanted but not invoked: serviceImpl .sayHello(any(), any());
<...>
However, there was exactly 1 interaction with this mock:
serviceImpl.bindService();
-> at io.grpc.internal.ServerImplBuilder.addService(...).

But my gRPC client got response, and method from overrided mock service was called - i log in service method.
Couldn't you advise, what i should change for right verify?

**Comment by ejona86** [comment]
I can't help too much because this seems like a problem of your test and not gRPC. If you did a blockingStub.sayHello() call directly in the test, I suspect it would all work.

But if I make a guess, I'd say that it is probably a threading issue and sayHello hasn't executed _yet_. You can try using `verify(serviceImpl, timeout(1000))` and see if that helps.

**Comment by ejona86** [comment]
Seems like this is resolved as best we can help. If not, comment, and it can be reopened.
