### ISSUE TITLE
Where does the gRPC channel get terminated when the gRPC deadline in hit?

### ISSUE THREAD

**Issue by anvsaxen** [grpc/grpc-java#9759]
### Question:
If we set a deadline for a gRPC call and it takes more than X amount of time does the `ClientCallImpl.java` interrupt the gRPC thread here?: https://github.com/grpc/grpc-java/blob/46ed02ed7286fa998506b469732745768833c18c/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L409 or does another service/thread terminate the gRPC elsewhere?

### More context:
We are seeing our client get stuck at the `waitAndDrain` method due to a lock held by `LockSupport.park`:
```
java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x0000000470c44d28> (a io.grpc.stub.ClientCalls$ThreadlessExecutor)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:732)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
```

To mitigate this issue we are looking into creating a deadline for the gRPC but wanted to make sure that by adding a deadline we would be interrupting the current gRPC thread that is stuck for a long time. Seems that LockSupport.park will only return for below reasons ([reference](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/LockSupport.html#park()))
1. Some other thread invokes unpark with the current thread as the target; or
2. Some other thread interrupts the current thread; or
3. The call spuriously (that is, for no reason) returns.

We wanted to ensure that Case 1 is what happens --> when the deadline is hit the current thread is interrupted since in that is the only case LockSupport.park will exit as we intend.

**Comment by sanjaypujare** [comment]
When the deadline is hit, it cancels the RPC stream ([stream.cancel](https://github.com/grpc/grpc-java/blob/46ed02ed7286fa998506b469732745768833c18c/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L409)) which indirectly causes the call to `unpark` to unblock the `blockingUnaryCall` so yes, you can use that.

Note however that the gRPC client channel does *not* get terminated which is what you are asking in the issue title.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
