### ISSUE TITLE
failure with bazel@head

### ISSUE THREAD

**Issue by mai93** [grpc/grpc-java#9763]
buildfarm build with bazel@head is failing with the following error ([link](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2792#01852ade-7d37-46ba-8bbb-784e40f58482)):
```
Traceback (most recent call last):
File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d51bbf2cdb9a60dbda80f1f1ce6197ee/external/io_grpc_grpc_java/java_grpc_library.bzl", line 88, column 78, in _java_rpc_library_impl
args.add_joined("--descriptor_set_in", descriptor_set_in, join_with = ctx.host_configuration.host_path_separator)
Error: 'ctx' value has no field or method 'host_configuration'
```

This is fixed with https://github.com/grpc/grpc-java/commit/e325dc9112079ecd64e3099093ff0615e7e72de5 but I think the commit is not included in a release so that we can update buildfarm repo to use the new version of grpc-java.

**Comment by sanjaypujare** [comment]
Release 1.52.0 from the branch 1.52.x is coming soon and has the commit. Pls see https://github.com/grpc/grpc-java/commits/v1.52.x .

Can we close the issue then?

**Comment by mai93** [comment]
Sounds good, thanks @sanjaypujare
