### ISSUE TITLE
//services:services_maven should declare a compile-time dependency on //services:reflection

### ISSUE THREAD

**Issue by davidmandle** [grpc/grpc-java#9772]
### What version of gRPC-Java are you using?
1.51.1

I am using [`rules_jvm_external`](https://github.com/bazelbuild/rules_jvm_external) to build applications with dependencies on Maven artifacts. `grpc-java` [recommends](https://github.com/grpc/grpc-java/blob/530cf905b1b2ba2ae475e5634c254caaf99d2909/repositories.bzl#L87) configuring `rules_jvm_external`'s `maven_install` `override_targets` so  that the `io.grpc:grpc-services` Maven target is overridden to resolve to the `@io_grpc_grpc_java//services:services_maven` Bazel target. However currently `@io_grpc_grpc_java//services:services_maven` only declares a [**runtime** dependency on `//services:reflection`](https://github.com/grpc/grpc-java/blob/7c73baa450c87e6a6f767d7451c46ca256e5158a/services/BUILD.bazel#L19).

Consequently, any Maven artifact with a compile-time dependency on any classes defined in `//services:reflection` will fail to build. For example, [Helidon](https://github.com/helidon-io/helidon) has a compile time dependency on `io.grpc:grpc-services`: [here it defines a class that extends `io.grpc.reflection.v1alpha.ServerReflectionGrpc.ServerReflectionImplBase`](https://github.com/helidon-io/helidon/blob/29490ec85fdde4a47359bd4599aa33f34bbaa385/grpc/server/src/main/java/io/helidon/grpc/server/ProtoReflectionService.java#L92). Any application with a compile-time dependency on that class will fail to build with error message `error: cannot access ServerReflectionGrpc`.

Compile-time dependencies on `io.grpc:grpc-services` are recommended elsewhere as well, including in `grpc-java`'s [own documentation](https://github.com/grpc/grpc-java/blob/530cf905b1b2ba2ae475e5634c254caaf99d2909/documentation/server-reflection-tutorial.md?plain=1#L28).

Declaring `//services:reflection` as a **compile-time** dependency of the `services_maven` target will allow all Maven artifacts with a compile-time dependency on `io.grpc:grpc-services` to build successfully in Bazel using `maven_install`.

**Comment by sanjaypujare** [comment]
What you are saying is true when someone is actually using server-reflection from `grpc-services`. But what about the other cases when they want to use something else from `grpc-services` (say only `BinaryLogs`) wouldn't creating a compile-time dependency on `reflection` be problematic? e.g. needing the artifact just to compile/build the application when there is no real need? 

In the example you cited as - grpc-java's [own documentation](https://github.com/grpc/grpc-java/blob/530cf905b1b2ba2ae475e5634c254caaf99d2909/documentation/server-reflection-tutorial.md?plain=1#L28) - it is really an example of using server reflection so it needs the compile time dependency.

**Comment by davidmandle** [comment]
Thank you for the response!

So in my case where I have a compile-time dependency chain that looks like:

 `my_application`→`helidon`→`grpc-services`,

but `services_maven` isn't providing helidon with the classes it needs from `grpc-services` at compile time...

Is there something wrong with the way that helidon is depending on `grpc-services` that should be fixed?
Or should I work around this by declaring a compile-time dependncy on `grpc-services` in `my_application` even though `my_application` doesn't directly depend on `grpc-services`?

**Comment by sanjaypujare** [comment]
> Or should I work around this by declaring a compile-time dependency on //services:reflection in my_application even though my_application doesn't directly depend on it?

That seems to be the quickest solution/work-around. And I can't think of a proper long term solution.

**Comment by ejona86** [comment]
ProtoReflectionService extending ServerReflectionImplBase exposes reflection on the helidon API surface. With the runtime_deps, Bazel can't generate the necessary hjar. So yeah, we need to change the `runtime_deps` to `exports`. This could apply to all `*_maven` targets. Someone could depend on the `*_maven` if they were lazy, but it really doesn't hurt much to use `exports` instead of `runtime_deps`.

**Comment by ejona86** [comment]
(I think we should also backport this for the 1.52 release)
