### ISSUE TITLE
Override ContentType header not possible

### ISSUE THREAD

**Issue by sergeybrazhnik-cb** [grpc/grpc-java#9777]
Hello grpc-java team! 

I have found that it's not possible to override content type header using both implementations (client/server)
I need this to get work the Charles proxy which is saying in it's documentation that support of grpc [exists](https://www.charlesproxy.com/documentation/using-charles/protocol-buffers/) but only when messages has 
```Charles identifies that an HTTP request or response contains a Protocol Buffers message when the Content-Type header has a MIME type ofapplication/x-protobuf or application/x-google-protobuf. ``` 

ATM server always returns the 
`'content-type': 'application/grpc'`

On server Im trying to override this header using interseptor
```
@VisibleForTesting
  static final Metadata.Key<String> CUSTOM_HEADER_KEY =
      Metadata.Key.of("content-type", Metadata.ASCII_STRING_MARSHALLER);

  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
      ServerCall<ReqT, RespT> call,
      final Metadata requestHeaders,
      ServerCallHandler<ReqT, RespT> next) {
    logger.info("header received from client:" + requestHeaders);
    return next.startCall(new SimpleForwardingServerCall<ReqT, RespT>(call) {
      @Override
      public void sendHeaders(Metadata responseHeaders) {
        responseHeaders.put(CUSTOM_HEADER_KEY, "application/x-google-protobuf");
        super.sendHeaders(responseHeaders);
      }
    }, requestHeaders);
  }
```

But client keeps receiving `'content-type': 'application/grpc'` and not overriding it
```
HEADERS: '[':status': '200', 'content-type': 'application/grpc', 'my_custom': 'custom_value', 'grpc-encoding': 'identity', 'grpc-accept-encoding': 'gzip']']
```

Is it possible to override this header?

**Comment by sanjaypujare** [comment]
Couple of things:

- you probably need to call `Metadata.removeAll` (or `remove`) for the given key and then call `put` to add your value.

- However the gRPC [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests) says this: 
  _If Content-Type does not begin with "application/grpc", gRPC servers SHOULD respond with HTTP status of 415 (Unsupported Media Type)._ I believe a similar restriction probably exists for responses and that might be a factor?

**Comment by sergeybrazhnik-cb** [comment]
Thanks for explanation @sanjaypujare 
> you probably need to call Metadata.removeAll (or remove) for the given key and then call put to add your value.

I have modified interceptor source code to this 
```
public class HeaderServerInterceptor implements ServerInterceptor {

  private static final Logger logger = Logger.getLogger(HeaderServerInterceptor.class.getName());

  @VisibleForTesting
  static final Metadata.Key<String> CUSTOM_HEADER_KEY =
      Metadata.Key.of("content-type", Metadata.ASCII_STRING_MARSHALLER);
  
  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
      ServerCall<ReqT, RespT> call,
      final Metadata requestHeaders,
      ServerCallHandler<ReqT, RespT> next) {
    logger.info("header received from client:" + requestHeaders);
    return next.startCall(new SimpleForwardingServerCall<ReqT, RespT>(call) {
      @Override
      public void sendHeaders(Metadata responseHeaders) {
        responseHeaders.removeAll(CUSTOM_HEADER_KEY);
        responseHeaders.put(CUSTOM_HEADER_KEY, "application/x-google-protobuf");
        super.sendHeaders(responseHeaders);
      }
    }, requestHeaders);
  }
}
```

Still no success. I see that client keeps receive content-type: applicatin/grpc

```
HEADERS: '[':status': '200', 'content-type': 'application/grpc', 'grpc-encoding': 'identity', 'grpc-accept-encoding': 'gzip']']
```

**Comment by sanjaypujare** [comment]
>...
> It seems to me that this header added somewhere deeper in the execution stack. But I could not find where ...

Yes. check this https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/Utils.java#L239 and https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/GrpcHttp2OutboundHeaders.java#L49

**Comment by ejona86** [comment]
application/x-protobuf and application/x-google-protobuf are invalid content types for gRPC. That Charles support you linked to isn't for gRPC but instead for raw protobuf over HTTP (where those content types would be correct).

You should not change or hack the content-type used by gRPC.

**Comment by sergeybrazhnik-cb** [comment]
@sanjaypujare / @ejona86 thanks for the answers and detailed clarification
So if I understood you right there is no way to make charles work with gRPC protocol in current implementation because current content type is `application/grpc`

Could you guys advice any tool which I can use as a proxy server to view/breakpoint grpc requests?

**Comment by sanjaypujare** [comment]
> ...
> Could you guys advice any tool which I can use as a proxy server to view/breakpoint grpc requests?

[Envoy](https://www.envoyproxy.io/) supports gRPC but not sure about the breakpoint feature you mentioned.

**Comment by ejona86** [comment]
> So if I understood you right there is no way to make charles work with gRPC protocol in current implementation because current content type is application/grpc

The problem is not the content type per se. The problem is that Charles doesn't support the gRPC encoding, and the fact the gRPC encoding is used is communicated with the content type. So Charles correctly realizes it doesn't understand the contents.

gRPC has a 5 byte header in front of every (protobuf) message. That 5 byte header will prevent it from being parsed by Charles if Charles is trying to parse it as protobuf.

A search of [charles grpc] has results about Mediator.

**Comment by ejona86** [comment]
Seems like this is resolved as best it can. If not, comment, and it can be reopened.

**Comment by sergeybrazhnik-cb** [comment]
Yes, guys! 
Thanks a lot for quick responses. 
I will think further hot to proceed
