### ISSUE TITLE
Will gRPC support virtual threads (project Loom)?

### ISSUE THREAD

**Issue by novoj** [grpc/grpc-java#9785]
Project Loom (https://openjdk.org/jeps/425) is currently available in preview mode and it's probably going GA in next Java LTS release. Will there be a gRPC version that would support virtual threads? It probably relates to virtual thread support in Netty that is discussed in https://github.com/netty/netty/issues/12848.

If there is plan to adapt it. What impact will it have on current APIs? Will the non-blocking stub remain available and would it have any sense / benefit once the virtual threads kick in place?

**Comment by ejona86** [comment]
I've been anticipating some changes. We'll need to rethink [a byte[] allocation optimization](https://github.com/grpc/grpc-java/blob/040e2831e4e63e410b98309ad2fed31684cc4783/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java#L120) and might replace some intrinsic locks with full locks. Context's ThreadLocal is a concern if ThreadLocals are disabled.

The biggest piece of work we're looking at doing (talking about it this quarter) is real streaming support for the blocking stub. Client-side will probably be first. Server-side has an implementation complication with the threading model that would need to be worked through. But none of that is virtual thread-specific; it's just "I can has threads. Use moar threads."

I don't see much need for the gRPC architecture overall to change much. And we won't remove a stub type. I really, really hope virtual threads work out.

**Comment by novoj** [comment]
Thank you. My question originates from the task of designing a new API of CPU bound computational task for both embedded and client server setup. I'd like to have the same interface in order the clients can effortlessly switch from embedded variant to the client / server one. Knowing the API is CPU bound (in case of embedded execution) I don't want to introduce the async. complexity (Futures etc.) into it, but the client & server of course involves a lot of I/O for which the non-blocking approach would pay off.

So if there is an ongoing effort for introducing project Loom to gRPC/java implementation I will design the client in an optimistic fashion and stick to the blocking approach hoping that the project Loom performance will be close to the non-blocking one.

**Comment by novoj** [comment]
Thanks for the exhaustive answer!
