### ISSUE TITLE
How to set ProtobufVarint32FrameDecoder in NettyChannelBuilder

### ISSUE THREAD

**Issue by baigod** [grpc/grpc-java#9789]
### What version of gRPC-Java are you using?
1.42.1

### What is your environment?

docker: openjdk11:bullseye-slim

My code is as follows:
```java
NettyChannelBuilder builder = NettyChannelBuilder
                .forAddress(rpcHost, rpcPort)
                .maxInboundMetadataSize(Integer.MAX_VALUE)
                .maxInboundMetadataSize(Integer.MAX_VALUE)
                .keepAliveTime(keepAliveTimeSec, TimeUnit.SECONDS);
        if (sslEnabled) {
            try {
                SslContextBuilder sslContextBuilder = GrpcSslContexts.forClient();
                if (StringUtils.isNotEmpty(certResource)) {
                    sslContextBuilder.trustManager(ResourceUtils.getInputStream(this, certResource));
                }
                builder.sslContext(sslContextBuilder.build());
            } catch (SSLException e) {
                log.error("Failed to initialize channel!", e);
                throw new RuntimeException(e);
            }
        } else {
            builder.usePlaintext();
        }
        channel = builder.build();
        IntegrationTransportGrpc.IntegrationTransportStub stub = IntegrationTransportGrpc.newStub(channel);
        log.info("[{}] Sending a connect request to the IoE!", integrationKey);
        this.inputStream = stub.handleMsgs(initOutputStream(integrationKey, onIntegrationUpdate, onConverterUpdate, onDownlink, onError));
        this.inputStream.onNext(RequestMsg.newBuilder()
                .setMessageType(MessageType.CONNECT_RPC_MESSAGE)
                .setConnectRequestMsg(ConnectRequestMsg.newBuilder().setIntegrationRoutingKey(integrationKey).setIntegrationSecret(integrationSecret).build())
                .build());
```
### What did you expect to see?
I think the following errors are caused by TCP packet sticking/unpacking, so how to set ProtobufVarint32FrameDecoder in NettyChannelBuilder
### What did you see instead?
![image](https://user-images.githubusercontent.com/23446974/210797914-eff209bc-a187-4790-b7f8-51f32f38afcb.png)

### Steps to reproduce the bug
In the high-speed message flow, the client service occasionally encounters the following errors

`gRPC frame header malformed: reserved bits not zero`

`Caused by: io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence`

`Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).`

`Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.`

**Comment by ejona86** [comment]
What server is being used here? `ProtobufVarint32FrameDecoder` is never used. gRPC uses a fixed-length 5 byte header before each message that contains the length.

If the server is a Java server and that's a streaming method, you could get that sort of error if you call `onNext()` on a particular StreamObserver from multiple threads simultaneously. StreamObserver isn't thread-safe, so should only be called from one thread at a time.

**Comment by baigod** [comment]
> What server is being used here? `ProtobufVarint32FrameDecoder` is never used. gRPC uses a fixed-length 5 byte header before each message that contains the length.
> 
> If the server is a Java server and that's a streaming method, you could get that sort of error if you call `onNext()` on a particular StreamObserver from multiple threads simultaneously. StreamObserver isn't thread-safe, so should only be called from one thread at a time.

Oh, thanks for the answer. It seems that this is true. I did use `StreamObserver.onNext()` in multithreading

**Comment by baigod** [comment]
But I still have a question about whether to lock the RPC request sender?

`private void initInputStream() {
        this.inputStream = new StreamObserver<>() {
            @Override
            public void onNext(RequestMsg requestMsg) {
                log.trace("Grpc inputStream requestMsg: {}", requestMsg);
                if (!IntegrationGrpcSession.this.connected && requestMsg.getMessageType().equals(MessageType.CONNECT_RPC_MESSAGE)) {
                    ConnectResponseMsg responseMsg = IntegrationGrpcSession.this.processConnect(requestMsg.getConnectRequestMsg());
                    IntegrationGrpcSession.this.outputStream.onNext(ResponseMsg.newBuilder().setConnectResponseMsg(responseMsg).build());
                    if (ConnectResponseCode.ACCEPTED != responseMsg.getResponseCode()) {
                        IntegrationGrpcSession.this.outputStream.onError(new RuntimeException(responseMsg.getErrorMsg()));
                    } else {
                        IntegrationGrpcSession.this.connected = true;
                    }
                }

                if (IntegrationGrpcSession.this.connected && requestMsg.getMessageType().equals(MessageType.UPLINK_RPC_MESSAGE)
                        && requestMsg.hasUplinkMsg()) {
                    IntegrationGrpcSession.this.outputStream.onNext(ResponseMsg.newBuilder()
                            .setUplinkResponseMsg(IntegrationGrpcSession.this.processUplinkMsg(requestMsg.getUplinkMsg())).build());
                }

            }

            @Override
            public void onError(Throwable t) {
                IntegrationGrpcSession.log.error("[{}] Failed to deliver message from client!",
                        IntegrationGrpcSession.this.configuration.getId(), t);
                this.closeSession();
            }

            @Override
            public void onCompleted() {
                this.closeSession();
            }

            private void closeSession() {
                IntegrationGrpcSession.this.connected = false;
                if (IntegrationGrpcSession.this.configuration != null) {
                    try {
                        IntegrationGrpcSession.this.sessionCloseListener.accept(IntegrationGrpcSession.this);
                    } catch (Exception var3) {
                        log.error("accept error ", var3);
                    }
                }

                try {
                    IntegrationGrpcSession.this.outputStream.onCompleted();
                } catch (Exception var2) {
                    log.error("onCompleted error ", var2);
                }

            }
        };
    }`

**Comment by ejona86** [comment]
Those calls to `outputStream.onNext` and `onError`/`onCompleted` look fine. You only call those methods from the StreamObserver callbacks. Since StreamObservers aren't thread-safe, gRPC will make sure to not call the methods concurrently.

Since you are doing streaming, just FYI that if you use the other methods that call callbacks like `ServerCallStreamObserver.setOnCancelHandler(Runnable)` or (Client/Server) `setOnReadyHandler(Runnable)`, those Runnables are _also_ not run concurrently with the StreamObserver callbacks. So you can mix all of those together and your code can remain non-thread-safe.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
