### ISSUE TITLE
Netty client doesn't close connection after GOAWAY

### ISSUE THREAD

**Issue by mping-exo** [grpc/grpc-java#9813]
### What version of gRPC-Java are you using?
1.51.1

### What is your environment?
Ubuntu 22.10
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)

### What did you expect to see?
Consistent behaviour between Netty and OkHttp clients when the server is shutting down

### What did you see instead?
TCP connections are not closed with Netty after `GO_AWAY`.
They are closed with OkHttp though.

### Steps to reproduce the bug

1. Start a grpc server for a simple rpc request (we experimented with golang, using java for the server works as expected)
2. Start a grpc client (in this case, netty)
3. Client issue an rpc request 
4. Server calls [GracefulStop](https://pkg.go.dev/google.golang.org/grpc#Server.GracefulStop), then replies
4.1 ongoing RPC from point 3. should be finished
4.2 after that, server should close tcp connections (server emits two `GO_AWAY` frames)
5. Client receives rpc reply
6. Observe that grpc channel enters `IDLE` state
7. Observe that tcp connection never closes with Netty, but does close with OkHttp
8. If the tcp connection isn't closed, the golang server will block on `GracefulStop` (this might be a grpc golang issue)

[Here](https://gist.github.com/mping-exo/4e4b9ac393f683b91eac04ac7ba42e27) are the frames observed from the server side.

I see that a bug might be in golang grpc server (my understanding is that `GracefulStop` should close tcp connections after inflight RPCs are done, see https://github.com/grpc/grpc-go/issues/5930), but the different behaviour between Netty and OkHttp is puzzling.

I can provide a small sample repo if needed, for now I want to understand if this is expected behaviour or is something that can be configured for the Netty client.

**Comment by mping-exo** [comment]
@temawi Thanks for the reply, I did some tests afterwards with Netty on both the cliend and server, and the behaviour is as expected - connection closes after graceful shutdown. I didn't check who initiated the close though.

**Comment by SreeramdasLavanya** [comment]
Hi @mping-exo, @kannanjgithub 

I was going through this issue and as part of Analysis found like this issue is already fixed as per the comments mentioned in issue tracker and its working as expected.
 
Request you to confirm if any further action is required from our side on this issue or we are good to close this?

**Comment by mping-exo** [comment]
Good for me, thanks for the heads up.

**Comment by SreeramdasLavanya** [comment]
Hi @kannanjgithub,

Requesting you to close this issue as I don't have access to do so.

**Comment by kannanjgithub** [comment]
@temawi are you ok with closing this issue?

**Comment by temawi** [comment]
Sounds good, closing the issue.
