### ISSUE TITLE
Is it safe to have the server reflection enabled in production since it will expose all the grpc services, methods & schemas

### ISSUE THREAD

**Issue by checkers9** [grpc/grpc-java#9819]
Is it safe to have the server reflection enabled in production since it will expose all the grpc services, methods & schemas

Also are there any sample projects or documentation for client to call a method at server using serverReflection in Java (not through gcpc cli). There are no proper resources that could be found.

**Comment by temawi** [comment]
If your service is internal then leaving reflection enabled should be ok, but if you are exposing the service over the Internet you might end up revealing more about your service to the world than you care to - which can create some risk.

This is also discussed a bit [on StackOverflow](https://stackoverflow.com/questions/75052916/performance-security-impact-of-enabling-grpc-server-reflection).

Having a Java example on reflection is on the roadmap, but there's no fixed date on delivery. I'm hoping in the next few months.
