### ISSUE TITLE
Maven build hangs for any of grpc-netty, grpc-netty-shaded, or grpc-okhttp >= 1.51.1

### ISSUE THREAD

**Issue by cusher** [grpc/grpc-java#9848]
I'm running into an issue with a maven build where, when any of `grpc-netty`, `grpc-netty-shaded`, or `grpc-okhttp` are updated beyond version 1.51.0 (I have seen this at least for versions 1.51.1, 1.51.3, and 1.52.1), the build will just mysteriously hang indefinitely. This issue does not seem to be occurring when updating other grpc maven dependencies, e.g. `grpc-core`, `gprc-stub`, or `grpc-protobuf`.

I have run into the same issue on multiple machines, multiple OSes, with multiple maven versions (including latest 3.8.7 + maven-compiler-plugin 3.10.1). The project is using Java 8.

I'm would venture a guess that this isn't an issue with grpc-java itself, so I'm happy to raise this question/issue elsewhere, but I'm wondering what might have changed with these particular versions to cause this to start happening, since it might help narrow down a simpler repro case. Thanks!

**Comment by ejona86** [comment]
Netty and okhttp didn't change at all between 1.51.0 and 1.51.1. https://github.com/grpc/grpc-java/compare/v1.51.0...v1.51.1

That's really a very small window. I don't think we swapped Java compilers.

grpc-netty, grpc-netty-shaded, and grpc-okhttp all use the `[1.51.1]` syntax when specifying the grpc-core version. That causes Maven to lookup to list the available versions. Maybe there's an issue there.

**Comment by ejona86** [comment]
Seems like we've provided what help we can. I agree it is strange, but it isn't within our power to debug. The `[]` syntax is really the only interesting thing going on. If there's something more we can help with, comment, and it can be reopened.
