### ISSUE TITLE
optional nullable is not working

### ISSUE THREAD

**Issue by yingshaoxo** [grpc/grpc-java#9868]
## Generator version: 1.52.1
https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.52.1/protoc-gen-grpc-java-1.52.1-osx-x86_64.exe

## Generate command:
```bash
cd .gradle
wget https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.52.1/protoc-gen-grpc-java-1.52.1-osx-x86_64.exe
chmod 777 protoc-gen-grpc-java-1.52.1-osx-x86_64.exe
cd ..

mkdir -p app/src/main/java/generated_grpc

protoc --experimental_allow_proto3_optional --plugin=protoc-gen-grpc-java=.gradle/protoc-gen-grpc-java-1.52.1-osx-x86_64.exe \
--java_out=app/src/main/java --grpc-java_out=app/src/main/java \
--proto_path=../party_protocols/protocols free_map_service.proto
```

## Protocols
```proto
syntax = "proto3";
package free_map_service;

option go_package = "./free_map_service";

option java_package = "generated_grpc.free_map_service_grpc";
option java_outer_classname = "free_map_service_grpc_types";

service FreeMapService {
    rpc DeletePlace(DeleteRequest) returns (DeleteResponse);
}

message DeleteRequest {
    int32 location_id = 1;
}

message DeleteResponse {
    optional string error = 1;
    bool success = 2;
}
```

## Kotlin code
```kotlin
    override fun deletePlace(
        request: DeleteRequest?,
        responseObserver: StreamObserver<DeleteResponse?>?
    ) {
        responseObserver?.onNext(DeleteResponse.newBuilder()
            .setError(null).setSuccess(true)
            .build())
        responseObserver?.onCompleted()
    }
```

<img width="903" alt="image" src="https://user-images.githubusercontent.com/17190829/216223723-e3310f14-3c44-4978-8b51-fc647ef08a54.png">

## Error
As I tested out, if I use `setError("")`, there would have no error.

But if I use `setError(null)`, error happens.

> I also tested ` --experimental_allow_proto3_optional`, not working.

```
Feb 02, 2023 11:11:50 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@587ff7a5
java.lang.NullPointerException
	at generated_grpc.free_map_service_grpc.free_map_service_grpc_types$DeleteResponse$Builder.setError(free_map_service_grpc_types.java:5740)
	at kotlin_free_map_backend_system.FreeMapService.deletePlace(FreeMapService.kt:32)
	at generated_grpc.free_map_service_grpc.FreeMapServiceGrpc$MethodHandlers.invoke(FreeMapServiceGrpc.java:351)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:340)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/17190829/216223823-de1ac54d-0c97-4612-a3ab-142eeab7dddf.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/17190829/216223878-fda8b7a0-8d96-47bd-ae81-69bb3b43ffb5.png">

**Comment by sanjaypujare** [comment]
`optional` in proto3 does not imply `nullable` for the equivalent field in the generated Java (or Kotlin) code. Specifically you should not call `setError(null)` just because it is marked `optional`.

`optional` in proto3 means you can check on the receiving side to see if the value was explicitly set as stated in [Specifying Field Rules](https://protobuf.dev/programming-guides/proto3/#specifying-field-rules).

**Comment by yingshaoxo** [comment]
Well, if optional field can't be set to null, then why Java has the concept
of null? Idiot

Here is the progress of Dart:
https://github.com/google/protobuf.dart/pull/790#issuecomment-1412177984

According to my experiment, Python, JavaScript, Rust, they all support to
set optional field to null or None

What do you expect? Want me to test CPP and C as well?

**Comment by ejona86** [comment]
This seems really about the protobuf message codegen, so https://github.com/protocolbuffers/protobuf is the place you'd need to file an issue. (If it is an RPC issue then it is gRPC, if it is a message issue it is protobuf.)
