### ISSUE TITLE
Cannot get value out of io.grpc.Context due to reference comparison

### ISSUE THREAD

**Issue by koehlp** [grpc/grpc-java#9869]
Trying to get a object out of io.grpc.Context via:
`
Context.Key<Object> serverKey = Context.key("io.grpc.Server");
Object serverObject = serverKey.get();
`
It just returns null probably because you compare references here instead of values?
https://github.com/grpc/grpc-java/blob/b7164f0791d405e002d67c1e01603e0df9d1cc9f/context/src/main/java/io/grpc/PersistentHashArrayMappedTrie.java#L74

**Comment by ejona86** [comment]
https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.Key.html

> Keys use reference equality and Context does not provide a mechanism to loop over Keys. This means there is no way to access a Key's value from a Context without having access to the Key instance itself. This allows strong control over what code can get/set a key in the Context. For example, you might manage access to Key similar to a ThreadLocal using Java visibility (private/protected). Generally Keys are stored in static fields.
