### ISSUE TITLE
CertificateUtils can't parse private keys which contain the key type in the header/footer line

### ISSUE THREAD

**Issue by massdosage** [grpc/grpc-java#9883]
### What version of gRPC-Java are you using?
1.52.1

### What is your environment?
Linux, Java 11

### What did you expect to see?

When calling  `io.grpc.util.CertificateUtils.getPrivateKey(InputStream is)` on an RSA private key which has a header of the value `-----BEGIN RSA PRIVATE KEY-----` I would expect the key to be returned.

### What did you see instead?

Instead it throws a `java.security.InvalidKeyException: Missing key encoding`

### Steps to reproduce the bug

Call the above method with a private key where the header and footer have the text "RSA" in the BEGIN/END lines.

**Comment by sanjaypujare** [comment]
CC @ZhenLian

**Comment by ejona86** [comment]
The other header is a different format. We don't support that format, and I suspect we want to remain supporting just PKCS#8. A web search will talk about the differences between them, like https://stackoverflow.com/a/20065522/4690866

**Comment by massdosage** [comment]
OK, the root problem is that I'm trying to use `okhttp` with `grpc-java` and it calls out to `CertificateUtils` to load the private key:

https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java#L678

The key we're using is in this format so the above fails. If core `grpc-java` is never going to support this format should I change the above `okhttp` code to not use `CertificateUtils` and instead use something like `PemReader` which the `netty` gRPC implementation delegates to for this:

https://github.com/netty/netty/blob/4475b5c5719e7e7f36f2f01e25c139bcb2b048d4/handler/src/main/java/io/netty/handler/ssl/PemReader.java#L113

Because of the above we can use `netty` with our key but not `okhttp`.

**Comment by ejona86** [comment]
> The key we're using is in this format so the above fails. If core grpc-java is never going to support this format should I change the above okhttp code to not use CertificateUtils...

... or you could reencode the key. 
https://netty.io/wiki/sslcontextbuilder-and-private-key.html

> instead use something like PemReader

That is private, so isn't available for use. It doesn't claim to support PKCS#1, but it does allow the other header forms. Maybe there is more going on. I'll note that Netty will also [use Bouncy Castle](https://github.com/netty/netty/blob/6c81a3fa025f31bc0308d7913f8ecbf540f99247/handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java) if it is available.

**Comment by massdosage** [comment]
The keys are provided by an external provider so I would have to detect and change them programatically at runtime, which is possible I guess, it's just not something I've had to do when using the netty implementation as it handles both types.

As for the PemReader being private - I was thinking of creating a new class and copy/pasting the code out of it (or some form of it) into the `okhttp` module and using that new method/class instead of `CredentialUtils` if the latter is out of bounds for changing.

**Comment by massdosage** [comment]
I do indeed have BouncyCastle on the classpath and am programmatically adding it as a provider  in order to support older versions of the JDK. So you're saying I should only do that for netty? I tried using Conscrypt with okhttp but it wasn't able to parse the key.

For the unit test I just re-used the PEM that was in the repository but I see the problem you pointed out. I can add a key generated in the same format that we have the issue with if that would help but it sounds like this change isn't desired and I'm going to have to work around it in my code in some other way. Perhaps I can programmatically detect the key format and do that key re-encoding that you suggested above.

**Comment by ejona86** [comment]
The security provider is neither here nor there. Security provider doesn't change whether PKCS#1 is supported. I know it is confusing.

I suggest you use BouncyCastle to parse the certificate and produce a PrivateKey (like BouncyCastlePemReader in Netty does). That would work with PKCS#1 and PKCS#8. Use that to [create a KeyManager](https://github.com/grpc/grpc-java/blob/19eab29f8de17041e783d14a22f4cd9d759bfad1/okhttp/src/main/java/io/grpc/okhttp/OkHttpChannelBuilder.java#L666) (note that the code is uglier mostly because of exception handling; don't be too afraid). Then pass that KeyManager to `TlsChannelCredentials.Builder.keyManager()`

**Comment by massdosage** [comment]
OK, thanks for the suggestion. So for `okhttp` you said you wouldn't recommend using BouncyCastle, by that do you mean registering it as a provider? If so then for the above I could just use BC as a library, not register it and then do what you suggest to get the PrivateKey out?

**Comment by ejona86** [comment]
I was meaning we don't want `grpc-okhttp` depending on BouncyCastle because of its size. You are free to depend on BouncyCastle yourself, and that's fine. This isn't using it as a security provider, but just as a library and interacting with its classes directly.

I'd have to look more deeply, but I expect gRPC wouldn't use BC if it was registered as a security provider. I know grpc-netty wouldn't, but I'm unsure about grpc-okhttp.

**Comment by ejona86** [comment]
I just saw https://github.com/netty/netty/pull/12670 was recent. That is in a newer version of Netty that we have upgraded to, but not released the version that does the upgrade yet. That explains why I thought Netty didn't support PKCS#1. I guess that means you were using grpc-netty with the a newer version of netty than we depend on.

**Comment by massdosage** [comment]
I'm not using a direct netty dependency, I'm using 

> group: 'io.grpc', name: 'grpc-netty-shaded', version: 1.52.1

When I attach a debugger and step through what's being used to load the key in the netty case I end up at 

https://github.com/netty/netty/blob/4475b5c5719e7e7f36f2f01e25c139bcb2b048d4/handler/src/main/java/io/netty/handler/ssl/PemReader.java#L113

as indicated above (i.e. not the BouncyCastlePemReader from the above PR). This is where I got the idea to change `CredentialUtils` to be similary lenient in reading the key header like this class does.

**Comment by ejona86** [comment]
Oh, interesting. Then that would mean case 2 is more likely what is happening:
> The generator is broken and putting PKCS#8 content in a PKCS#1 header. While PKCS#1 is a bit of a mess in this space, [PEM PKCS#8 is well-defined](https://www.rfc-editor.org/rfc/rfc7468#section-10)

PKCS#1 isn't supported in part because the PEM encoding actually isn't standardized (and that's largely because it is "the old way" of doing things, so standards folks didn't bother). Only PKCS#8 has a standard describing the PEM encoding.

**Comment by ejona86** [comment]
Seems like this is resolved as best as we'd expect, so closing. If there's something more, comment, and we can reopen.

I'd encourage fixing/filing a bug for the certificate generator to use the standard MIME comment for PKCS#8. That would be the best solution. Failing that, you can parse the certificate outside of gRPC and pass in the KeyManager. I know the Java API to do some of that is obscure/opaque/weird, but with the references I provided earlier I hope that goes smoothly.
