### ISSUE TITLE
PARSER has private access

### ISSUE THREAD

**Issue by depend** [grpc/grpc-java#989]
I am using protoc-3.0.0-beta-1-win32 and protoc-gen-grpc-java-0.7.2-windows-x86_64.exe to generate code from a proto file. But the Grpc file has this line "io.grpc.protobuf.ProtoUtils.marshaller(grpc.grpcsvc.Grpcsvc.HelloRequest.PARSER)". Then java compiler complains because PARSER has private access in another generated file. Am I using the wrong protoc or plugin?

**Comment by carl-mastrangelo** [comment]
Can you use protoc-gen-grpc-java-0.8.0-windows-x86_64.exe  or another later version?  We bumped to using protoc beta after the 0.8.0 release I believe.

**Comment by depend** [comment]
@carl-mastrangelo Thanks. that's what I figure but 0.7.2 is the newest in Maven Central. Where can I download the binary for 0.8.0?

**Comment by carl-mastrangelo** [comment]
For some reason, it was not replicated fully.  I believe you can download it from one of the mirrors:

http://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/0.8.0/

**Comment by ejona86** [comment]
That is so strange. I wonder why it didn't propagate... It's been over a month now. I wonder if there is anything we can do to fix the glitch.

**Comment by depend** [comment]
Now it's working. Thanks for the quick help!
