### ISSUE TITLE
grpc vs rest performance benchmark

### ISSUE THREAD

**Issue by skumar1987** [grpc/grpc-java#9895]
I have written sample program to test perfromance of rest vs grpc, but in my test rest is faster than grpc.
load test 10k request with 100 req parallel, sample request and response is as below
Req: {
"emp_id": "34"
}

Resp:
{
    "emp_id": "34",
    "name": "abc",
    "role": "USER"
}

Throughput for REST: 1814 req/sec
                            GRPC: 209 req/sec

Is grpc slower than rest in case payload is small or am I missing something in my test.

**Comment by YifeiZhuang** [comment]
very hard to tell, share the setups and tools, etc?

**Comment by skumar1987** [comment]
Thanks for replying,
I am using the code from below article: 
https://www.techgeeknext.com/spring-boot/spring-boot-grpc-example#google_vignette

It's spring boot application.
Even for single request grpc is response time is 100 ms and REST is taking 12 ms only (tested in postman)

Load test done on jmeter.
java version : open jdk 1.8
Running in eclipse and calling api from same machine.

**Comment by ejona86** [comment]
Cross-linking: https://groups.google.com/g/grpc-io/c/0hmUPKdNyOU

**Comment by ejona86** [comment]
This discussion is continuing on the mailing list.
