### ISSUE TITLE
Why there is no each version of library in maven central?

### ISSUE THREAD

**Issue by slogic** [grpc/grpc-java#9904]
Why there is no each version of library in maven central? E.g. there is no 1.47.[2-4]

**Comment by YifeiZhuang** [comment]
Because the latest released version on branch 1.47.x is 1.47.1. 
1.47.2 is not released yet.
We release the next minor version if there are major bug fixes on older branches.

**Comment by slogic** [comment]
Hm, this is strage cause I was sure there were 1.47.2 up to 1.47.4. And I even remember that in some version there was a zip library security fix. Right now I scanned releases and see only 1.47.1.

**Comment by ejona86** [comment]
Patch releases vary per-language? Maybe you're remembering for a different language? C core had a 1.47.4, for example. https://github.com/grpc/grpc/releases/tag/v1.47.4

We try and stay aligned on the minor version ("47"), but make no effort for the patch version ("2" or "4" here).

**Comment by slogic** [comment]
Yep, that was core. Sorry.
