### ISSUE TITLE
[Question] Regarding sending multiple grpc requests concurrently.

### ISSUE THREAD

**Issue by iverson6588** [grpc/grpc-java#9913]
Hi team!

We're trying to build a new Java grpc service and I'm pretty a newbie for both grpc and Java so I really need help from you. Assuming my service name is NewbieService. 

One case I am encountering and I may need education is about sending multiple requests concurrently to another grpc service, let's say SomeDataService, and it has a grpc api named getSomeData. It may look like the following
```
service SomeDataService {
   rpc GetSomeData (GetSomeDataRequest) returns (GetSomeDataResponse);
}
```

I am encountering a case that I may need to call GetSomeData concurrently with multiple requests (let's say 100) and then wait for the responses from it then do something else with all the responses. Streaming is not a feasible choice since I have no control on the SomeDataService. I kinda figured out one seemingly naive solution and it may look like the following
```
SomeDataServiceGrpc.SomeDataServiceGrpcFuture stub = SomeDataServiceGrpc.newFutureStub(someChannel);
final List<ListenableFuture<GetSomeDataResponse>> listenables = new ArrayList<ListenableFuture<GetSomeDataResponse>>();
final ListenableFuture<List<GetSomeDataResponse>> responsesFuture;

for (int i = 0; i < 100; i++) {
   GetSomeDataRequest request = GetSomeDataRequest.newBuilder()........build();
   listenables.add(stub.getSomeData(request));
}
responsesFuture = Futures.allAsList(listenables);
responses = responsesFuture.get();
```

Here are my questions regarding the above codes:

1. Is there a better way of doing so? Like using multi threads with blockingstub or so? In terms of performance and memory consumption.
2. With the above approach, can I really consider it that all 100 requests are sent concurrently(if ignoring the time consumed for the creation of the request and ListenableFuture).
3. Let's say if I actually want to send 1000 but I may want to do a rate limit on 100. Which means after sending 100 concurrent grpc requests then send another 100. What is the best approach?

I couldn't find any example like my scenario with my google search so any advice is welcomed.
Thanks!

**Comment by ejona86** [comment]
> Is there a better way of doing so? Like using multi threads with blockingstub or so? In terms of performance and memory consumption.

Stubs are a very thin layer in grpc-java, so the gRPC internal don't really change much depending on which is used. So it is mostly "use what you prefer." Futures looked good here. If you did blocking you'd need 100 Threads, which would use a lot more memory.

> With the above approach, can I really consider it that all 100 requests are sent concurrently

Mostly. The server could limit the number of concurrent requests (e.g., `NettyServerBuilder.maxConcurrentCallsPerConnection()`), but otherwise yes. By default there isn't a limit.

> Let's say if I actually want to send 1000 but I may want to do a rate limit on 100. Which means after sending 100 concurrent grpc requests then send another 100. What is the best approach?

Very good question. Thank you for considering the poor server and burstiness.

In your case... I'm not immediately sure. I've seen this before, but generally in more complex scenarios so it made sense to have some infrastructure to support it.

Obviously, you could do batches of 100, with allAsList() after each batch. That would be very easy to adapt your current code. Though I assume you actually want "1000 total with 100 concurrent," so as one RPC finishes another one starts until none remain.

Without thinking about it too long, you could do something like:
```java
class Scheduler {
  private final Queue<Runnable> queue = new ArrayDeque<>();
  private final Executor executor;
  private int available;

  public Scheduler(int maxConcurrent, Executor sendRpcExecutor) {
    this.available = maxConcurrent;
    this.executor = executor;
  }

  public <T> ListenableFuture<T> schedule(Callable<? extends ListenableFuture<T>> callable) {
    SettableFuture<T> future = SettableFuture.create();
    future.addListener(this::futureCompleted, executor);
    synchronized (this) {
      if (available > 0) {
        available--;
      } else {
        queue.add(() -> future.setFuture(callable.call()));
        return future;
      }
    }
    // Could use 'executor' if you wanted
    future.setFuture(callable.call());
    return future;
  }

  private void futureCompleted() {
    Runnable runnable;
    synchronized (this) {
      available++;
      if (available != 1) {
        return;
      }
      runnable = queue.poll();
      if (runnable == null) {
        return;
      }
      available--;
    }
    runnable.run();
  }
}
```

**Comment by iverson6588** [comment]
Hi @ejona86 

Thanks quite a lot for the answer. For rate limiter, is there a way that we can pass something like an executor service with fixed thread pool into the future stub for concurrency control?

**Comment by ejona86** [comment]
You can use `stub.withExecutor(fixedThreadPool).getSomeData(request)`, but realize that doesn't restrict the number of concurrent RPCs, but the number of responses being processed concurrently.

**Comment by iverson6588** [comment]
Hi @ejona86 

Thanks for your answers so far. I do actually have another question that suddenly comes into my mind.
Given the high concurrency like 100 in my example given in the description, which is the below
```
for (int i = 0; i < 100; i++) {
   GetSomeDataRequest request = GetSomeDataRequest.newBuilder()........build();
   listenables.add(stub.getSomeData(request));
}
responsesFuture = Futures.allAsList(listenables);
responses = responsesFuture.get();
```

I may think there could be a little chance that one some of the requests might fail due to rate limiter or so. Is there a way for the ListenableFuture that comes from futureStub to have a retry mechanism? Like retry 5 times with a exponential backoff?

**Comment by ejona86** [comment]
That would be covered by the [gRFC A6 Retry Design](https://github.com/grpc/proposal/blob/master/A6-client-retries.md). See the examples folder [for the retrying example](https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/retrying).

**Comment by ejona86** [comment]
I'm going to close this assuming the testing has gone well. If you end up having trouble soon, you can comment here and we can reopen, or just create a new issue and reference back to this one (so we remember the context).
