### ISSUE TITLE
Is it safe to implement `io.grpc.Marshaller` without supporting rewind on the returned `InputStream`?

### ISSUE THREAD

**Issue by Lincong** [grpc/grpc-java#9932]
### Context:
Below method on the `io.grpc.Marshaller` interface serializes request value into a stream of bytes.
```java
public InputStream stream(T value);
```

Implementation of `InputStream` can choose whether to support rewind or not. By "support rewind", I mean `markSupported() == true` so that the `mark()` and `reset()` methods on the `InputStream` implementation is effective.

### Question:
When I provide my own implementation of the above serialization method on the `io.grpc.Marshaller` interfact, do I have to I return an `InputStream` that supports "rewind"? IOW, if "rewind" is not supported on the returned `InputStream`, what are the risks?

Let me know if I need to provide more context.

Thanks!

**Comment by larry-safran** [comment]
You don't need to return an InputStream that supports "rewind" (markSupported() returns true).  

On the server side we have ServerInterceptors.useInputStreamMessages() which will wrap an unsupported stream to take care of cases where it matters.

**Comment by Lincong** [comment]
> You don't need to return an InputStream that supports "rewind" (markSupported() returns true).
> 
> On the server side we have ServerInterceptors.useInputStreamMessages() which will wrap an unsupported stream to take care of cases where it matters.

Thanks @larry-safran for the input! I forgot to mention that I am interested in the client-side behavior instead of the server-side behavior. So, is there something on the client side to "wrap an unsupported stream to take care of cases where it matters" as well?

**Comment by larry-safran** [comment]
The same kind of wrapper doesn't exist on the client side because there hasn't been a situation where we need to rewind as we have on the server side.

**Comment by Lincong** [comment]
Got it. Thanks Larry!

I will close this issue/question.
