### ISSUE TITLE
gRPC Server unavailable just after restart/deployment

### ISSUE THREAD

**Issue by RupavJain** [grpc/grpc-java#9954]
Reference Question:
https://github.com/yidongnan/grpc-spring-boot-starter/issues/863

Hi Team,
How to ensure connection is established between client & server just after server is redeployed/restarted.

**Comment by ejona86** [comment]
Please include the error messages you saw.

If you have a single server, then when a server restarts, depending on how you do that precisely, it'd be common to see errors. But after the server starts up again, the client should start working again. Note that the client uses exponential backoff, so the amount of time it takes for the client to notice the server has started is related to how long the server wasn't running. The backoff maxes out at 2 minutes, so even if the server was off for an hour, two minutes after the server starts again the client should notice it is running.

**Comment by RupavJain** [comment]
status 'UNAVAILABLE' is shown during this.

We have a staggered deployment strategy (multiple AWS instances).
Based on your comment, using io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder, we have applied following retry config:

maxAttempts: 3
initialBackoff: 20s
maxBackoff: 60s
backoffMultiplier: 2
retryableStatusCodes: 
    - UNKNOWN
    - UNAVAILABLE

Reducing the backOff time might fix this issue because we have seen in 'x' amount of time after deployment, the server automatically gets connected. Our aim is to reduce this 'x', is there a better/alternate way to solve this?

**Comment by ejona86** [comment]
RPC retries is completely separate from connection reconnects. They both have backoff, but they are independent.

If you have multiple servers running, then you shouldn't need retries for most cases. When an instance is shutting down, it should do something like:
```java
// Prevent new RPCs from starting
server.shutdown();
 // Let RPCs complete; adjust based on how long your might RPCs last
if (!server.awaitTermination(10, TimeUnit.SECONDS)) {
  // Kill any remaining RPCs 
  server.shutdownNow();
}
```

With an approach like that, the client should not see any error. RPCs that started already will continue until completion, and new RPCs will go on a new connection to one of the still-running instances. That would work fine for both pick_first and round_robin LB policies.

**Comment by RupavJain** [comment]
We already have this grace period set as 30 seconds.

**Comment by ejona86** [comment]
@RupavJain, please include the error message you saw. The text of the UNAVAILABLE message tells more of what was happening.

**Comment by ejona86** [comment]
No response to provide the error message, so closing. Not much we can do without it. More information can be provided and then we can reopen.
