### ISSUE TITLE
IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS causes java_export to include grpc classes directly

### ISSUE THREAD

**Issue by sfc-gh-kleonhard** [grpc/grpc-java#9965]
### What version of gRPC-Java are you using?
1.50.2

### What is your environment?
OSX

### What did you expect to see?
The pom file generated from a java_export when using GRPC includes GRPC dependencies rather than inlining them into the generate jar file.

### What did you see instead?
The pom file does NOT include a grpc dependency. The generate jar includes directly grpc classes. For example: `io/grpc/Attributes.java`, `io/grpc/util/AdvancedTlsX509KeyManager.java`, `io/grpc/stub/AbstractAsyncStub.java`

### Steps to reproduce the bug

1. Create a java bazel project following the canonical example
2. Add a java_export rule, see below.
3. Run the publish rule: `bazel run --define "maven_repo=file://$HOME/.m2/repository" //export_test:export_test.publish`
4. Examine the resulting pom file and artifact
  * jar tf ~/.m2/repository/com/example/exporttest/0.0.1/exporttest-0.0.1-sources.jar|less
  * less ~/m2/repository/com/example/exporttest/0.0.1/exporttest-0.0.1.pom
5. Observe that protobuf and grpc dependencies are omitted from the pom file
6. Observe that protobuf and grpc classes are in the jar file

```
java_export(
    name = "export_test",
    maven_coordinates = "com.example:exporttest:0.0.1",
    runtime_deps = [
        "//export_test_lib",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_protobuf_protobuf_java_util",
        "@maven//:io_grpc_grpc_api",
        "@maven//:io_grpc_grpc_core",
        "@maven//:io_grpc_grpc_protobuf",
        "@maven//:io_grpc_grpc_stub",
    ],
)
```

### Workaround

Simply removing `IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS`, added [here](https://github.com/grpc/grpc-java/commit/9d6f5322c21db5e7067833e46c58718cd8324f23#diff-5b010cebc220a1927b558a589a75b3b34b573d435b19f89d5783de7ea0a3f61d), seems to work fine. 

Alternatively, perhaps someone could set the maven_coordinates tags so that java_export knows which artifacts to reference!

**Comment by ejona86** [comment]
We have no experience with `java_export`, and don't know how it works. `IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS` is very necessary when using dependencies from Maven Central that depend on gRPC. From the documentation, it would seem `java_export`'s pom management is for projects that are only using dependencies only from Maven Central. So yeah, I'd expect it to be broken if using the Bazel build included with gRPC, and I don't see any indications it is designed to work for `java_library`.

We'd accept contributions that help improve things; Bazel support itself was a community contribution.

**Comment by sfc-gh-kleonhard** [comment]
Thanks for the quick reply Eric! I'm far from in an expert in these areas. java_export works fine referencing java_library rules and it works as one would expect: transitive external dependencies are included in the pom.xml file and transitive internal dependencies are included in the jar. I agree, the documentation is pretty light!

With IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS removed, I added grpc dependencies directly to the artifacts property on my maven_install rule:
```
        "com.google.protobuf:protobuf-java:3.21.9",
        "com.google.protobuf:protobuf-java-util:3.21.9",
        "io.grpc:grpc-protobuf:1.50.2",
        "io.grpc:grpc-api:1.50.2",
        "io.grpc:grpc-stub:1.50.2",
        "io.grpc:grpc-core:1.50.2",
        "io.grpc:grpc-protobuf:1.50.2",
        "io.grpc:grpc-netty-shaded:1.50.2",
```

This appears to work fine.

Can you elaborate a little on why IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS is necessary? I ask to make sure I'm not shooting myself in the foot by removing it! The protobuf repository provides PROTOBUF_MAVEN_ARTIFACTS without any overrides, fwiw.

**Comment by larry-safran** [comment]
IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS was introduced because of errors caused by duplicate copies of grpc.

**Comment by ejona86** [comment]
> Can you elaborate a little on why IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS is necessary?

It is needed if gRPC code is coming from both the Bazel build (normal java_library targets) and through Maven transitive dependencies. It causes Bazel to use a single build (Bazel's) instead of adding both to the classpath which can cause surprises.

java_grpc_library has to depend on the gRPC Java code for part of the compilation. It [does so by depending on a java_library](https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/compiler/BUILD.bazel#L43). Thus you will have the Bazel build in your dependency tree. Using IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS avoids the second Maven build in your depedency tree.

It sounds like virtually every target in gRPC would need a `maven_coordinates` attribute. Since that includes a version number, there will need to be at least some indirection to avoid rewriting tons of lines when bumping our release version. This can be added by someone more familiar with `java_export`.
