### ISSUE TITLE
Get channel from the implementation of BindableService?

### ISSUE THREAD

**Issue by nc-jeni** [grpc/grpc-java#9971]
I receive a call on the server and get into the blocking stub.From that point I want to get channel, to make it possible to redirect the call to another server.

How do I obtain the channel, when I am in the implementation of the io.grpc.BindableService by extending the ImplBase class?

**Comment by nc-jeni** [comment]
For now, I have a server listening to a port, where it receives calls, then it creates channels for the target server and calls the stubs on that. However, I want the channel to be the same on the incoming request and the outgoing request. 
How is that possible, if  it is?
Can the ServerInterceptor help me on that?

**Comment by ejona86** [comment]
There is no channel server-side for the incoming request. What is your goal? If the channel was the same, how would you benefit?

**Comment by nc-jeni** [comment]
It should be acting in this way.

![image](https://user-images.githubusercontent.com/66730416/226705594-12ed017b-a777-4b52-a55e-ae80cc417618.png)

**Comment by ejona86** [comment]
"channel name" does not exist.

If you want to use the hostname Client used to connect to Proxy, that would typically be done by implementing a [HandlerRegistry](https://grpc.github.io/grpc-java/javadoc/io/grpc/HandlerRegistry.html) and passing that to `serverBuilder.fallbackHandlerRegistry()`. You can see [MutableHandlerRegistry as an example](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/util/MutableHandlerRegistry.java). In that approach you would create a different service instance for each destination server.

To use server IP address or authority with a single service, you'd need to use an interceptor and call `serverCall.getAuthority()` or `serverCall.getAttributes().get(Grpc.TRANSPORT_ATTR_LOCAL_ADDR)`. You'd then use Context to propagate the value to the service, like in the [JWT example](https://github.com/grpc/grpc-java/blob/39c9ebf180f4378a2cebe6e08c3f12e49e5af509/examples/example-jwt-auth/src/main/java/io/grpc/examples/jwtauth/JwtServerInterceptor.java#L64-L66), and the service would [get the value from the key](https://github.com/grpc/grpc-java/blob/39c9ebf180f4378a2cebe6e08c3f12e49e5af509/examples/example-jwt-auth/src/main/java/io/grpc/examples/jwtauth/AuthServer.java#L96-L97).

**Comment by ejona86** [comment]
Seems like this is resolved as best as we can with our understanding of what is needed. If there's something remaining, comment, and it can be reopened.
