### ISSUE TITLE
Fail to build examples in documentation in macOS arm64

### ISSUE THREAD

**Issue by shinnqy** [grpc/grpc-java#9981]
When I follow the documentation to clone the repo and try example. It failed. How can I use this in macOS arm64

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/15121888/226893115-c7d7666a-4207-4c14-ba1c-9345ca5f6766.png">

**Comment by ejona86** [comment]
You probably need to install Rosetta.

**Comment by ejona86** [comment]
Native arm64 support on Mac is tracked in #7690. (You can see specifically https://github.com/grpc/grpc-java/issues/7690#issuecomment-831617279 )

**Comment by shinnqy** [comment]
I think we can close this issue.
