### ISSUE TITLE
Possible race condition ServerImpl between start() and shutdown()

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#999]
I believe it may be possible if start and stop are called concurrently that the shared executor may not get released.  I'm not sure if this is an actual problem, but it does go against the @ ThreadSafe annotation.

**Comment by ejona86** [comment]
It looks like a race isn't even necessary. Simply `shutdown()`, and then call `start()`. Either way, that is a problem.

It looks like `start()` should do nothing if `shutdown == true`, similar to what it does when `started = true`.
