### ISSUE TITLE
New AsyncService

### ISSUE THREAD

**Issue by alesj** [grpc/grpc-java#9993]
I see new AsyncService was added into ImplBase, yet there is no mention of this change in 1.54.0 notes?
* https://github.com/grpc/grpc-java/releases/tag/v1.54.0

```
  public static abstract class BlockingTestServiceImplBase
      implements io.grpc.BindableService, AsyncService {

    @java.lang.Override public final io.grpc.ServerServiceDefinition bindService() {
      return BlockingTestServiceGrpc.bindService(this);
    }
  }
```

**Comment by larry-safran** [comment]
Release notes have been updated with this feature that was accidentally missed.

**Comment by alesj** [comment]
@larry-safran nit-pick ... `named AsyncService that the <service-name>ImplBase class extends` --> `named AsyncService that the <service-name>ImplBase class implements`

**Comment by larry-safran** [comment]
Good catch.  Thanks!
