### ISSUE TITLE
Control for underlying buffer sizes on detachable?

### ISSUE THREAD

**Issue by emkornfield** [grpc/grpc-java#9994]
[

https://github.com/grpc/grpc-java/commit/e5d0e9d9a8d672fbf16773bbd638cb8a0467e873 allows zero copy access to underlying byte buffers.  One question that came to mind when looking at usages is it appears a stream can have more then one backing ByteBuffer.  What determines how many ByteBuffer might be used for parsing a single message?  Is this something that can be influenced via configuration parameters?

I ask because for a use-case I'm considering it would be useful to make at least make it very unlikely for reasonably sized messages that a specific byte field spans multiple byte buffers.

**Comment by ejona86** [comment]
> What determines how many ByteBuffer might be used for parsing a single message?

Quite a few things. Without any evidence, biggest contributors in a simple situation are probably 1) RecvByteBufAllocator and 2) the max frame size. The max frame size is 16 KiB right now, so I'd expect anything larger than that to be fragmented. The sending implementation and whether other RPCs are being received will also impact things.

You will definitely need to support multiple buffers, but I can understand wanting the majority case to have a single buffer. What is the full message size you're dealing with? (Not just the byte field, but the entire message.)

**Comment by emkornfield** [comment]
Thanks for the quick resposne.

> The sending implementation and whether other RPCs are being received will also impact things.

In this use-case it is for a service that is using [long lived streaming RPCs](https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/storage/v1beta1/storage.proto#L337) and no more then 1-2 RPCs per core, so we could potentially use a new channel for each RPC.  

> What is the full message size you're dealing with? (Not just the byte field, but the entire message.)

Our median size response size ~100 to 200 KB, 90th percentile is a few megabytes.  The [actual bytes field payload we are concerned with](https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/storage/v1/arrow.proto#L40) is actually a concatenation of a bunch of buffers (i.e absl::cord) on the server side. It is likely that many of the individual buffers are under 16KB each, so if there was some way to make sure each buffer didn't span a frame in most cases it could still be useful.  

But based on this, I'm guess our best bet will be to plan on consolidating the messages ourselves and taking the copy hit (trying to do the index mapping across arbitrary buffers will likely have too much overhead in our use-case but we will need to benchmark).

**Comment by ejona86** [comment]
Yeah, for ~200 KB a lot more things come into play. For a low-RTT connection, it almost certainly will get cut up. For most links, they'd get cut up into 16 KB chunks at their largest. The only hope for 200 KB staying together would be an intercontinental link (high throughput, high latency).

If that 200 KB is "many small records, and we want a record to not be split" there could be options. For example, if records were 1 KB, then approximately 1 out of 16 could be cut in two. But if records are 10 KB, then lots will be cut. If you are reading random bytes at a time into a 1 MB segmented buffer of varying segment sizes, then you may be better off doing a copy. If you read bytes in bunches, a segmented buffer isn't necessarily that bad. 200 / 16 = 13 segments, which can be linearly scanned quickly enough.

**Comment by emkornfield** [comment]
> If that 200 KB is "many small records, and we want a record to not be split" there could be options. For example, if records were 1 KB, then approximately 1 out of 16 could be cut in two. But if records are 10 KB, then lots will be cut. If you are reading random bytes at a time into a 1 MB segmented buffer of varying segment sizes, then you may be better off doing a copy. If you read bytes in bunches, a segmented buffer isn't necessarily that bad. 200 / 16 = 13 segments, which can be linearly scanned quickly enough.

Thanks this is makes sense and we will need to do some benchmarking to see whether consolidating or scanning approach makes sense.  My guess is consolidation makes sense here.
